Fix a very slight grammatical issue
godotengine/godot pull request #100002
Opened 2024-12-04 01:34 UTC by wyvrtn

Changed the incorrect verb "have" into its correct form, "has." Fixes #99972

DANG IT SOMEONE TOOK MY 100,000th contrib

2024-12-04 01:36 UTC, clayjohn approved these changes

2024-12-04 09:16 UTC, AThousandShips approved these changes

2024-12-04 13:27 UTC, akien-mga requested changes
The same typo exists in many other files with the same description, which should be fixed too:
```
doc/classes/PackedInt64Array.xml
190:                            Returns a copy of the data converted to a [PackedByteArray], where each element have been encoded as 8 bytes.

doc/classes/PackedInt32Array.xml
189:                            Returns a copy of the data converted to a [PackedByteArray], where each element have been encoded as 4 bytes.

doc/classes/PackedFloat32Array.xml
195:                            Returns a copy of the data converted to a [PackedByteArray], where each element have been encoded as 4 bytes.

doc/classes/PackedFloat64Array.xml
196:                            Returns a copy of the data converted to a [PackedByteArray], where each element have been encoded as 8 bytes.
```

And also spotted this one with a quick regex search:
```
doc/classes/SurfaceTool.xml
150:                            Generates a tangent vector for each vertex. Requires that each vertex have UVs and normals set already (see [method generate_normals]).
```

2024-12-04 13:56 UTC, wyvrtn commented
On it sire

2024-12-04 14:25 UTC, akien-mga commented
Looks good! To match our workflow, the commits would need to be squashed (see [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions).

I'm happy to do it myself if you're not familiar with this process and it looks overwhelming (it can be, initially :D).

2024-12-04 14:32 UTC, wyvrtn commented
> Looks good! To match our workflow, the commits would need to be squashed (see [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions).
> 
> I'm happy to do it myself if you're not familiar with this process and it looks overwhelming (it can be, initially :D).

Sire, I've squashed the commits. First time I've ever used rebase in fact.

2024-12-04 14:33 UTC, akien-mga approved these changes
Looks great!

2024-12-04 15:49 UTC, AThousandShips approved these changes

2024-12-04 15:49 UTC, AThousandShips commented on doc/classes/SurfaceTool.xml
> +				Generates a tangent vector for each vertex. Requires that each vertex has UVs and normals set already (see [method generate_normals]).
```suggestion
				Generates a tangent vector for each vertex. Requires that each vertex already has UVs and normals set (see [method generate_normals]).
```
Just minor suggestion, I think this flows better

2024-12-05 14:36 UTC, akien-mga approved these changes

2024-12-05 20:16 UTC, merged