Add basic editor editing for `ConvexPolygonShape2D` and `ConcavePolygonShape2D`
godotengine/godot pull request #100183
Opened 2024-12-08 23:45 UTC by smix8

Adds basic editor tooling to move the existing `points` of a `ConvexPolygonShape2D` or move the `segments` of a `ConcavePolygonShape2D` while a `CollisionShape2D` node is selected.

Removes the `configuration warning` about those shape not being supported that added noise to all the nodes.

![collision_poly_edit](https://github.com/user-attachments/assets/e3c6efb8-5290-4a1f-8cce-d839662e4376)

Note this is only intended for very basic editing of moving points, e.g. what you already can do by fumbling with the exposed Resource Inspector arrays.

For more complex editing like adding, removing, splitting or converting shapes the  `CollisionPolygon2D` node is still the way to go as it has a dedicated editor for all those more complex things.

2024-12-09 18:39 UTC, rburing requested changes
This works and I like it a lot. Indeed I would say these shapes are fine to use directly. I have personally done so many times, mostly with shapes generated by scripts. The only issue (and probably the real reason for the configuration warning) is that editing them by hand is somewhat tricky: for the convex shape one might want some better feedback/assistance when the polygon is not convex, and for the concave shape one would like the ability to create chains (which is the most common use case).

I would not remove the configuration warning until more of the editor tooling is finished (on par with `CollisionPolygon2D`). As is, it would be quite confusing for a new user to figure out how to create a `ConvexPolygonShape2D` or a `ConcavePolygonShape2D` from scratch (e.g. by entering coordinates in the inspector). 

If you want, the configuration warning can be rephrased to address the above.

2024-12-11 01:32 UTC, smix8 commented
Added a reworded configuration warning back in.

2024-12-11 08:07 UTC, rburing approved these changes

2024-12-11 23:41 UTC, merged

2024-12-11 23:41 UTC, Repiteo commented
Thanks!