Add `memory_get_offset` to simplify data offset constants.
godotengine/godot pull request #100145
Opened 2024-12-07 15:59 UTC by Ivorforce

This should not change behavior. I just did not understand the 4 huge constant initializers, and finally found they were all sharing the exact same logic. I hope this new version is easier to understand.

2024-12-08 07:13 UTC, kiroxas approved these changes
Definitely easier to read. Maybe move it outside the global scope inside the class to call it like `Memory::get_offset` ?

2024-12-08 10:04 UTC, Ivorforce commented
I changed the interface to non-template, instead evaluating `address` and `alignment` outside the function. I think this is better because it makes fewer assumptions.

> Maybe move it outside the global scope inside the class to call it like `Memory::get_offset` ?

I had it in the `Memory` scope at first, it seems like static class functions cannot be truly `constexpr`. At least it refused to compile as such from my end, with a less than helpful error message:

```c++
./core/os/memory.h:63:26: error: constexpr variable 'ELEMENT_OFFSET' must be initialized by a constant expression
   63 |         static constexpr size_t ELEMENT_OFFSET = mem_aligned_address(SIZE_OFFSET + sizeof(uint64_t), alignof(uint64_t));
      |                                 ^                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./core/os/memory.h:63:43: note: undefined function 'mem_aligned_address' cannot be used in a constant expression
   63 |         static constexpr size_t ELEMENT_OFFSET = mem_aligned_address(SIZE_OFFSET + sizeof(uint64_t), alignof(uint64_t));
      |                                                  ^
./core/os/memory.h:57:26: note: declared here
   57 |         static constexpr size_t mem_aligned_address(size_t address, size_t alignment) {
      |                                 ^
./core/os/memory.h:64:26: error: constexpr variable 'DATA_OFFSET' must be initialized by a constant expression
   64 |         static constexpr size_t DATA_OFFSET = mem_aligned_address(ELEMENT_OFFSET + sizeof(uint64_t), alignof(max_align_t));
      |                                 ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./core/os/memory.h:64:60: note: initializer of 'ELEMENT_OFFSET' is not a constant expression
   64 |         static constexpr size_t DATA_OFFSET = mem_aligned_address(ELEMENT_OFFSET + sizeof(uint64_t), alignof(max_align_t));
      |                                                                   ^
./core/os/memory.h:63:26: note: declared here
   63 |         static constexpr size_t ELEMENT_OFFSET = mem_aligned_address(SIZE_OFFSET + sizeof(uint64_t), alignof(uint64_t));
      |                                 ^
```

2025-09-25 13:39 UTC, Repiteo approved these changes
Prerequisite to #105928, which was approved in yesterday's core meeting

2025-09-25 16:55 UTC, Repiteo requested changes
> I had it in the `Memory` as a static function first, it seems like static class functions cannot be truly `constexpr`. At least it refused to compile as such from my end, with a less than helpful error message

Ah! Glad I double-checked this. I ran into the same issue in #109744, and it came down to trying to assign `constexpr` variables with scoped logic before the class was fully declared. This can be worked around by initially declaring the variables as simply `const` within the class, then as `inline constexpr` outside the class:
```diff
 core/os/memory.h         | 22 ++++++++++++++--------
 core/templates/cowdata.h |  4 ++--
 2 files changed, 16 insertions(+), 10 deletions(-)

diff --git a/core/os/memory.h b/core/os/memory.h
index 192394fdcd..441503803a 100644
--- a/core/os/memory.h
+++ b/core/os/memory.h
@@ -36,11 +36,6 @@
 #include <new> // IWYU pragma: keep // `new` operators.
 #include <type_traits>
 
-static constexpr size_t mem_aligned_address(size_t p_address, size_t p_alignment) {
-	const size_t n_bytes_unaligned = p_address % p_alignment;
-	return (n_bytes_unaligned == 0) ? p_address : (p_address + p_alignment - n_bytes_unaligned);
-}
-
 class Memory {
 #ifdef DEBUG_ENABLED
 	static SafeNumeric<uint64_t> mem_usage;
@@ -55,9 +50,9 @@ public:
 	//             └─────────────────┴──┴────────────────┴──┴───────────...
 	// Offset:     ↑ SIZE_OFFSET        ↑ ELEMENT_OFFSET    ↑ DATA_OFFSET
 
-	static constexpr size_t SIZE_OFFSET = 0;
-	static constexpr size_t ELEMENT_OFFSET = mem_aligned_address(SIZE_OFFSET + sizeof(uint64_t), alignof(uint64_t));
-	static constexpr size_t DATA_OFFSET = mem_aligned_address(ELEMENT_OFFSET + sizeof(uint64_t), alignof(max_align_t));
+	static const size_t SIZE_OFFSET;
+	static const size_t ELEMENT_OFFSET;
+	static const size_t DATA_OFFSET;
 
 	static void *alloc_static(size_t p_bytes, bool p_pad_align = false);
 	static void *realloc_static(void *p_memory, size_t p_bytes, bool p_pad_align = false);
@@ -90,8 +85,19 @@ public:
 	static uint64_t get_mem_available();
 	static uint64_t get_mem_usage();
 	static uint64_t get_mem_max_usage();
+
+	static constexpr size_t mem_aligned_address(size_t p_address, size_t p_alignment);
 };
 
+constexpr size_t Memory::mem_aligned_address(size_t p_address, size_t p_alignment) {
+	const size_t n_bytes_unaligned = p_address % p_alignment;
+	return (n_bytes_unaligned == 0) ? p_address : (p_address + p_alignment - n_bytes_unaligned);
+}
+
+inline constexpr size_t Memory::SIZE_OFFSET = 0;
+inline constexpr size_t Memory::ELEMENT_OFFSET = mem_aligned_address(Memory::SIZE_OFFSET + sizeof(uint64_t), alignof(uint64_t));
+inline constexpr size_t Memory::DATA_OFFSET = mem_aligned_address(ELEMENT_OFFSET + sizeof(uint64_t), alignof(max_align_t));
+
 class DefaultAllocator {
 public:
 	_FORCE_INLINE_ static void *alloc(size_t p_memory) { return Memory::alloc_static(p_memory, false); }
diff --git a/core/templates/cowdata.h b/core/templates/cowdata.h
index c04727cfa0..a772ecf415 100644
--- a/core/templates/cowdata.h
+++ b/core/templates/cowdata.h
@@ -77,8 +77,8 @@ private:
 	// Offset:     ↑ REF_COUNT_OFFSET      ↑ SIZE_OFFSET    ↑ DATA_OFFSET
 
 	static constexpr size_t REF_COUNT_OFFSET = 0;
-	static constexpr size_t SIZE_OFFSET = mem_aligned_address(REF_COUNT_OFFSET + sizeof(SafeNumeric<USize>), alignof(USize));
-	static constexpr size_t DATA_OFFSET = mem_aligned_address(SIZE_OFFSET + sizeof(USize), alignof(max_align_t));
+	static constexpr size_t SIZE_OFFSET = Memory::mem_aligned_address(REF_COUNT_OFFSET + sizeof(SafeNumeric<USize>), alignof(USize));
+	static constexpr size_t DATA_OFFSET = Memory::mem_aligned_address(SIZE_OFFSET + sizeof(USize), alignof(max_align_t));
 
 	mutable T *_ptr = nullptr;
 
```
I'd also consider renaming it to `get_mem_offset` to match the naming scheme of the rest of the class, but I'm not gonna die on that hill

2025-09-25 17:49 UTC, Ivorforce commented
It's a bit awkward, but I agree it beats needing a free function for this. I've adjusted the code accordingly, thanks!

2025-09-25 18:50 UTC, Repiteo commented on core/os/memory.h
> +constexpr size_t Memory::DATA_OFFSET = get_aligned_address(ELEMENT_OFFSET + sizeof(uint64_t), alignof(max_align_t));
This'll fix the CI errors
```suggestion
inline constexpr size_t Memory::SIZE_OFFSET = 0;
inline constexpr size_t Memory::ELEMENT_OFFSET = get_aligned_address(SIZE_OFFSET + sizeof(uint64_t), alignof(uint64_t));
inline constexpr size_t Memory::DATA_OFFSET = get_aligned_address(ELEMENT_OFFSET + sizeof(uint64_t), alignof(max_align_t));
```

2025-09-25 18:55 UTC, Ivorforce commented on core/os/memory.h
> +constexpr size_t Memory::DATA_OFFSET = get_aligned_address(ELEMENT_OFFSET + sizeof(uint64_t), alignof(max_align_t));
That's weird, `constexpr` implies `inline` according to my IDE.

2025-09-25 19:01 UTC, Repiteo commented on core/os/memory.h
> +constexpr size_t Memory::DATA_OFFSET = get_aligned_address(ELEMENT_OFFSET + sizeof(uint64_t), alignof(max_align_t));
It implies it for functions, but not necessarily variables. It's strange that it's not implicit in a static class scope though

2025-09-25 19:02 UTC, Repiteo approved these changes

2025-09-25 19:57 UTC, merged

2025-09-25 19:58 UTC, Repiteo commented
Thanks!