Use UIDs in addition to paths for extracted meshes, materials and animations
godotengine/godot pull request #100786
Opened 2024-12-24 12:42 UTC by lyuma

This doesn't necessarily fix a bug, but this is trying to migrate more things to support UIDs. In this case, the extracted file paths for meshes and animations did not support UID, so if the paths were renamed it was possible for the import to fail.

Similarly, renaming materials could cause them to get lost between imports. This change will keep the uid updated so that the material can be referenced even after it is renamed.

Unifying the UID paths also should allow for more easily sharing assets between meshes.

The downside is the UID path is not obvious and isn't really readable by the user, so it might not be easy or possible for a user to change the path after it has been extracted, once the UID is assigned.

There's a missing change to allow using UIDs in animation slices, since this requires some duplicate code from _check_resource_save_paths and I want to first be sure to understand if this is the right approach.

It is also missing a change to pre-allocate the UIDs from the scene dialog.

2025-01-07 19:37 UTC, fire reviewed
Are you sure we are ok to merge this if the other parts are not implemented? There's also a call for all uid code contributors to meetup.

2025-01-07 19:42 UTC, lyuma commented
@fire if you think the change is good and just needs the missing pieces implemented, such as animation slices, I will implement the missing parts next week. I just wanted get approval for the overall concept before feature freeze.

2025-01-07 19:56 UTC, fire commented
It makes sense that uid works everywhere.

2025-01-10 08:17 UTC, makidoll commented
Thanks for the PR, I was having this exact issue. However, I noticed if I select an external material under mesh import in the UI, the res:// path is shown but the uid:// path is saved in the .import file. You mentioned that "the UID path isn't obvious and readable" and got confused when the engine deals with this issue

2025-01-14 00:38 UTC, Jordyfel commented
Fixes #95637

The path import option can currently be set not only in `_save_dir_confirm()`, which is called only when the batch extraction dialog is used, but also by the custom inspector thing which is the `SceneImportSettingsData` class in the same file.

What I'm thinking is that a user wouldn't really need to change the path after it was set, they would just move the extracted file in the filesystem instead.

This could justify something like, instead of introducing a new uid import option, store the uid in the currently existing path import option and use `ResourceUID.ensure_path()` for compatibility. If the user wants to reset the path and extract again, they would set the `enabled` option to false and use the other dialog (through `_save_dir_confirm()`) again. Following this logic it also makes sense to hide the import option so that it is only saved but not editable in the custom inspector thing.

2025-02-05 11:59 UTC, akien-mga commented
Would be good to rebase and test again as #101256 was fixed.

2025-02-05 13:06 UTC, KoBeWi commented
The path and uid are now stored correctly.
However if you reimported files in 4.4 and they have uid in path field, it can't be fixed by simply reimporting; you need to extract to another file.

2025-02-05 13:06 UTC, KoBeWi commented on editor/import/3d/scene_import_settings.cpp
> +				md.settings["use_external/uid"] = ResourceUID::get_singleton()->id_to_text(ResourceLoader::get_resource_uid(path));
```suggestion
				md.settings["use_external/uid"] = ResourceUID::path_to_uid(path);
```

2025-02-05 13:07 UTC, KoBeWi commented on editor/import/3d/resource_importer_scene.cpp
> +									uid = resource_uid->text_to_id(uid_str);
```suggestion
									uid = resource_uid->text_to_id(matdata["use_external/uid"]);
```

2025-02-05 13:24 UTC, KoBeWi approved these changes, later dismissed

2025-02-05 18:39 UTC, lyuma commented
So from looking into this, my understanding is @reduz PRs #97912 and #97363 address a lot of the issues that this PR was designed for. Here are some of the things I am still thinking about:

one of the things I am considering changing is to keep status quo with path = "uid://" (or res:// for compatibility) and put the file path into a property called "fallback_path" only to be used when the uid does not exist. That would make this PR smaller and less dangerous compared to beta, since it is only fixing the case where you have extracted files and the referenced file was deleted.

the other question I had is when is it appropriate to modify the .import settings, for example if a referenced file is moved. If we call it fallback_path... let's say the user extracts a material to "res://models/materials/red.material" and then moves it to "res://global/red.material". Should the fallback_path be updated to the new path next time it is imported. Then if the user deletes global/red.material and the gltf is reimported, what should happen?

Finally, we need to make sure all places that extract resources are updated to use uid:// at the time they perform the extraction (for example in the adv import dialog), and I should test if animation slices work)

2025-02-12 11:53 UTC, lyuma commented
Pushed a new version of this change. I updated the original comment to explain what the PR is now doing, but I wanted to have this ready for the core meeting. My goal is to have a minimal change. This does not change anything to users who use res:// paths in .import, and it does not change anything for users who use valid uid:// paths in .import.

During import, this PR should only impact cases when a uid:// path in .import is missing.

This PR also implements UID paths when the user selects a new directory to extract meshes, textures and materials, so in other words, it means that this code may also affect newly imported assets.

2025-02-12 21:11 UTC, KoBeWi commented on editor/import/3d/scene_import_settings.cpp
> +			path = ResourceUID::ensure_path(uid_path);
```suggestion
			path = ResourceUID::uid_to_path(uid_path);
```
`ensure_path()` should be used when the original path can be either.

2025-02-12 21:16 UTC, KoBeWi commented
I duplicated a GLB file and extracted mesh, but it saved as regular path for `path` and empty `fallback_path`. Seems like it's unreliable?

I think the general idea is fine.

2025-02-14 11:12 UTC, lyuma commented
@KoBeWi I got this change working for meshes, materials and animations. I have been doing some tests on the fox gltf (which has animations, a mesh and a material) and so far I'm pretty satisfied with it.

It feels nice and transparent to the user, since the file pickers only show the res:// path. I tested renames, even in cases where Godot doesn't update the res:// path, and it seems to be able to locate the file fine using the uid://

Some known issues:
1. I do not currently upgrade res:// paths to uid:// - This is kind of intentional to reduce the scope of this PR and reduce risk, but I'm open to changing it, for example due to the second issue.
2. Due to how `PROPERTY_HINT_SAVE_FILE` seems to work, if a new file is created using the file picker in the inspector, it puts a `res://` path into `save_to_file/path` which won't get upgraded. (The common flow of using extract / set save paths buttons works correctly)
3. The `ResourceSaver::set_uid` API is jank both in potentially causing glitches and performance, and from my research, there is no other way to save a resource to a file with a pre-determined uid:

`ResourceSaver::save` doesn't have a way to pass a UID, and I saw the code @reduz linked to first calls `ResourceSaver::save`, and then uses `ResourceSaver::set_uid`. However, set_uid is a really bad function for a few reasons:

a. it rewrites the file again, so it now means all meshes and animations are being written twice.

b. the temporary uid is saved to uid_cache.bin first, which causes other places that reference the extracted meshes to use the temporary uid, even though the .tres file itself has a different UID. It's very confusing and while I haven't run into a bug with this, it feels wrong and jank. I think the fix requires modifying ResourceSaver to allow passing a UID into save(), which will turn into a bigger change.

2025-02-14 18:56 UTC, reduz requested changes

2025-02-17 03:11 UTC, lyuma commented on editor/import/3d/resource_importer_scene.cpp
> +		ResourceSaver::set_uid(res_path, ResourceUID::get_singleton()->text_to_id(p_save_to_path));
I have made the change for Mesh and Animation to use hash for UID generation.
(Note: The hash generation in CSV Translation had a bug that was causing uid conflicts and uid://<invalid>, which I opted to fix in this PR. Let me know if the translation fixes should be a separate PR)

For Material, it is common for people to use other Material objects, switch to ShaderMaterial, or share materials between models. I think randomly generated UID makes more sense for this workflow because they are not overwritten on each import.

2025-02-17 10:28 UTC, KoBeWi commented on editor/import/3d/resource_importer_scene.cpp
> +			r_options->push_back(ImportOption(PropertyInfo(Variant::STRING, "save_to_file/fallback_path", PROPERTY_HINT_SAVE_FILE, "", PROPERTY_USAGE_NO_EDITOR), ""));
```suggestion
			r_options->push_back(ImportOption(PropertyInfo(Variant::STRING, "save_to_file/fallback_path", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_NO_EDITOR), ""));
```
Hints are useless if the property is not editable.

2025-02-17 10:34 UTC, KoBeWi commented on editor/import/3d/resource_importer_scene.cpp
> +			if (p_option == "save_to_file/path" || p_option == "save_to_file/fallback_path") {
Fallback path is always invisible, so this is unnecessary.

2025-02-17 10:50 UTC, KoBeWi commented on editor/import/3d/scene_import_settings.cpp
>  		if (!path.is_resource_file()) {
`uid://` will return false.

2025-02-17 11:23 UTC, lyuma commented on editor/import/3d/scene_import_settings.cpp
>  		if (!path.is_resource_file()) {
Ah I had the if statements in the wrong order. I didn't notice because the first time resources are extracted, they are always res://
Also found a related bug with material uid assignment. I realized for materials we can simply use the standard flow of ResourceSaver::save() -> ResourceUID::path_to_uid(). No need to complicate things by generating a UID first and then calling set_uid.

The material logic in scene_import_settings should be much simpler now

2025-02-17 11:24 UTC, KoBeWi commented on editor/import/3d/resource_importer_scene.cpp
> +								if (!external_mat.is_valid()) {
```suggestion
								if (external_mat.is_null()) {
```

2025-02-17 11:54 UTC, KoBeWi commented
I tested that it works (as much as I'm familiar with model import at least).
@reduz will probably have more to say about implementation.

2025-03-14 12:34 UTC, reduz approved these changes

2025-03-14 13:20 UTC, AThousandShips commented on editor/import/3d/resource_importer_scene.cpp
> +						WARN_PRINT(vformat("Failed to save mesh %s to %s", mesh->get_name(), save_res_path));
```suggestion
						WARN_PRINT(vformat("Failed to save mesh %s to '%s'.", mesh->get_name(), save_res_path));
```

2025-03-19 11:37 UTC, merged

2025-03-19 11:38 UTC, akien-mga commented
Thanks!

2025-03-20 22:25 UTC, OhiraKyou commented
Related? https://github.com/godotengine/godot/issues/74612