Use 1.5x growth factor for LocalVector
godotengine/godot pull request #100944
Opened 2024-12-30 17:56 UTC by Nazarwadim

This is explained here https://github.com/godotengine/godot-proposals/issues/7366.

Also, now if we use resize, as much memory as we need will be allocated if we increase the size by a value greater than `1.5 * capacity`.

I tested in tps-demo and the memory usage difference is 2-3 megabytes. Did not notice the difference in FPS.

2025-01-02 11:46 UTC, RandomShaper commented
Makes sense!

I'd still ask for a couple more things before considering this complete:
- Applying 1.5 factor also to `CowData::_get_alloc_size()`.
- Benchmarking.

2025-01-02 11:50 UTC, RandomShaper commented on core/templates/local_vector.h
> +				capacity = MAX((U)2, Math::ceil(capacity * 1.5f));
Will floating point multiplication be faster than `capacity + capacity / 2`? (Or `capacity + (capacity >> 1)`, to be sure we avoid the slow integer division if the compiler fails to optimize.)
Will floating point ceiling be faster than checking if current capacity is zero or doing some potential bitwise trick?

2025-01-02 13:30 UTC, Nazarwadim commented on core/templates/local_vector.h
> +				capacity = MAX((U)2, Math::ceil(capacity * 1.5f));
My version gives a distribution closer to Fibonacci for small numbers.
`capacity + capacity / 2`: 2, 3, 4, 6, 9
`Math::ceil(capacity * 1.5f)`: 2, 3, 5, 8 , 12

2025-01-03 08:05 UTC, Nazarwadim commented
> Applying 1.5 factor also to CowData::_get_alloc_size()

Well, there are two ways to do it. The first is to cache capacity. Another is to use a binary search among the Fibonacci numbers and choose a number slightly greater than or equal to the size.

> Benchmarking.

What specific benchmarks are needed?

2025-01-03 11:22 UTC, RandomShaper commented
> > Applying 1.5 factor also to CowData::_get_alloc_size()
> 
> Well, there are two ways to do it. The first is to cache capacity. Another is to use a binary search among the Fibonacci numbers and choose a number slightly greater than or equal to the size.

Caching capacity sounds fine to me.

> 
> > Benchmarking.
> 
> What specific benchmarks are needed?

Two possibilities (not necessarily exclusive):
- Via the Godot benchmarks project, or a relevant subset of it.
- Via a game project (Godot TPS demo or one of the platformers), paying attention to improvements in fps (or, well, frame time).

This change would ideally require benchmarking across a number of platforms, but, well, since we already understand why this new approach is theoretically beneficial, we would get enough peace of mind if we verify empircal benefits on a single platform. If only we had the mimalloc PR merged, we would be sure the change is a good for one platform as for the others.

2025-01-03 12:01 UTC, Nazarwadim commented
> Caching capacity sounds fine to me.

https://github.com/godotengine/godot/blob/bdf625bd54958c737fa6b7213b07581cc91059ad/core/templates/cowdata.h#L101-L103
When I tried to add capacity here, the size of the metadata became 32 bytes, not 24. It looks like `ptr` should be aligned by 16 bytes.

2025-01-04 09:55 UTC, Nazarwadim commented
> Via a game project (Godot TPS demo or one of the platformers), paying attention to improvements in fps (or, well, frame time).

Tested in tps-demo with minimum graphics settings. Before that, the average was 408 fps, now it is 422. I tested in dynamics, where I used all the mechanics of the game and moved along the path to the reactor.
I did two tests, but kept the last one, because in the first test I did not think that the fps would be higher.

[local_vector1.5-tps-demp-fps-test.ods](https://github.com/user-attachments/files/18306364/local_vector1.5-tps-demp-fps-test.ods)

2025-01-04 22:10 UTC, hpvb commented
Same comment as the other PR: https://godbolt.org/z/Phc53zGq1

The floating point calculation isn't necessary

2025-01-05 10:31 UTC, Nazarwadim commented
From this comment: https://github.com/godotengine/godot/pull/101138#issuecomment-2571535535

So I will correct myself. 

Using
```c++
capacity = capacity + ((1 + capacity) >> 1);
```
gives the same sequence https://godbolt.org/z/ssjT35ETW.

2025-01-06 17:12 UTC, RandomShaper commented
There are also some changes to inlining. Maybe this PR would better keep that out of its scope.

2025-01-08 22:35 UTC, Calinou approved these changes
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/6f3cc274237ea5142cd26f6357dfc6d876c45f75), it works as expected.

## Benchmark

<details open>

<summary>PC specifications</summary>

- **CPU:** Intel Core i9-13900K
- **GPU:** NVIDIA GeForce RTX 4090
- **RAM:** 64 GB (2×32 GB DDR5-5800 C30)
- **SSD:** Solidigm P44 Pro 2 TB
- **OS:** Linux (Fedora 41)
</details>

Using a release export template with LTO.

a: `master` https://github.com/godotengine/godot/commit/6f3cc274237ea5142cd26f6357dfc6d876c45f75
b: This PR

<details>

<summary>Results JSON File</summary>

```json
{
	"category": "C++ > Alloc",
	"name": "Deep Tree",
	"results": {
		"time": {
			"a": 146.8,
			"b": 145.6,
			"a_div_b": 1.0082417582417584
		}
	}
}
{
	"category": "C++ > Alloc",
	"name": "Duplicate",
	"results": {
		"time": {
			"a": 803.1,
			"b": 792.9,
			"a_div_b": 1.0128641695043512
		}
	}
}
{
	"category": "C++ > Alloc",
	"name": "Fragmentation",
	"results": {
		"time": {
			"a": 1973.0,
			"b": 1948.0,
			"a_div_b": 1.0128336755646816
		}
	}
}
{
	"category": "C++ > Alloc",
	"name": "Wide Tree",
	"results": {
		"time": {
			"a": 131.2,
			"b": 104.5,
			"a_div_b": 1.2555023923444975
		}
	}
}
{
	"category": "C++ > Array",
	"name": "Color Array",
	"results": {
		"time": {
			"a": 54.02,
			"b": 51.16,
			"a_div_b": 1.0559030492572323
		}
	}
}
{
	"category": "C++ > Array",
	"name": "Fill Loop",
	"results": {
		"time": {
			"a": 0.003,
			"b": 0.002,
			"a_div_b": 1.5
		}
	}
}
{
	"category": "C++ > Array",
	"name": "Float 32 Array",
	"results": {
		"time": {
			"a": 56.02,
			"b": 54.29,
			"a_div_b": 1.031865905323264
		}
	}
}
{
	"category": "C++ > Array",
	"name": "Float 64 Array",
	"results": {
		"time": {
			"a": 56.32,
			"b": 54.48,
			"a_div_b": 1.0337738619676946
		}
	}
}
{
	"category": "C++ > Array",
	"name": "Int 32 Array",
	"results": {
		"time": {
			"a": 54.85,
			"b": 52.76,
			"a_div_b": 1.0396133434420016
		}
	}
}
{
	"category": "C++ > Array",
	"name": "Int 64 Array",
	"results": {
		"time": {
			"a": 55.41,
			"b": 53.46,
			"a_div_b": 1.0364758698092031
		}
	}
}
{
	"category": "C++ > Array",
	"name": "String Array",
	"results": {
		"time": {
			"a": 592.9,
			"b": 590.4,
			"a_div_b": 1.0042344173441735
		}
	}
}
{
	"category": "C++ > Array",
	"name": "Vector 2 Array",
	"results": {
		"time": {
			"a": 54.74,
			"b": 51.49,
			"a_div_b": 1.063119052243154
		}
	}
}
{
	"category": "C++ > Array",
	"name": "Vector 3 Array",
	"results": {
		"time": {
			"a": 56.04,
			"b": 52.52,
			"a_div_b": 1.067022086824067
		}
	}
}
{
	"category": "C++ > Array",
	"name": "Vector 4 Array",
	"results": {
		"time": {
			"a": 52.97,
			"b": 51.11,
			"a_div_b": 1.0363920954803365
		}
	}
}
{
	"category": "C++ > Binary Trees",
	"name": "Binary Trees 13",
	"results": {
		"time": {
			"a": 23.07,
			"b": 23.16,
			"a_div_b": 0.9961139896373057
		}
	}
}
{
	"category": "C++ > Binary Trees",
	"name": "Binary Trees 15",
	"results": {
		"time": {
			"a": 110.5,
			"b": 110.8,
			"a_div_b": 0.9972924187725632
		}
	}
}
{
	"category": "C++ > Binary Trees",
	"name": "Binary Trees 18",
	"results": {
		"time": {
			"a": 1030.0,
			"b": 1028.0,
			"a_div_b": 1.0019455252918288
		}
	}
}
{
	"category": "C++ > Control",
	"name": "Control",
	"results": {
		"time": {
			"a": 0.004,
			"b": 0.004,
			"a_div_b": 1
		}
	}
}
{
	"category": "C++ > For Loop",
	"name": "Loop Add",
	"results": {
		"time": {
			"a": 0.002,
			"b": 0.003,
			"a_div_b": 0.6666666666666666
		}
	}
}
{
	"category": "C++ > For Loop",
	"name": "Loop Call",
	"results": {
		"time": {
			"a": 0.004,
			"b": 0.001,
			"a_div_b": 4
		}
	}
}
{
	"category": "C++ > Hello World",
	"name": "Hello World",
	"results": {
		"time": {
			"a": 0.01,
			"b": 0.008,
			"a_div_b": 1.25
		}
	}
}
{
	"category": "C++ > Lambda Performance",
	"name": "Lambda Call",
	"results": {
		"time": {
			"a": 0.001,
			"b": 0.001,
			"a_div_b": 1
		}
	}
}
{
	"category": "C++ > Mandelbrot Set",
	"name": "Mandelbrot Set",
	"results": {
		"time": {
			"a": 81.53,
			"b": 81.51,
			"a_div_b": 1.0002453686664212
		}
	}
}
{
	"category": "C++ > Merkle Trees",
	"name": "Merkle Trees 13",
	"results": {
		"time": {
			"a": 24.94,
			"b": 24.83,
			"a_div_b": 1.004430124848973
		}
	}
}
{
	"category": "C++ > Merkle Trees",
	"name": "Merkle Trees 15",
	"results": {
		"time": {
			"a": 117.5,
			"b": 120.2,
			"a_div_b": 0.9775374376039934
		}
	}
}
{
	"category": "C++ > Merkle Trees",
	"name": "Merkle Trees 18",
	"results": {
		"time": {
			"a": 1108.0,
			"b": 1116.0,
			"a_div_b": 0.992831541218638
		}
	}
}
{
	"category": "C++ > Nbody",
	"name": "Nbody 1 000 000",
	"results": {
		"time": {
			"a": 29.78,
			"b": 29.74,
			"a_div_b": 1.0013449899125757
		}
	}
}
{
	"category": "C++ > Nbody",
	"name": "Nbody 500 000",
	"results": {
		"time": {
			"a": 14.9,
			"b": 14.88,
			"a_div_b": 1.0013440860215053
		}
	}
}
{
	"category": "C++ > Spectral Norm",
	"name": "Spectral Norm 100",
	"results": {
		"time": {
			"a": 0.302,
			"b": 0.303,
			"a_div_b": 0.9966996699669967
		}
	}
}
{
	"category": "C++ > Spectral Norm",
	"name": "Spectral Norm 1000",
	"results": {
		"time": {
			"a": 29.21,
			"b": 29.15,
			"a_div_b": 1.0020583190394512
		}
	}
}
{
	"category": "C++ > Spectral Norm",
	"name": "Spectral Norm 500",
	"results": {
		"time": {
			"a": 7.375,
			"b": 7.298,
			"a_div_b": 1.0105508358454371
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Md 5 Buffer Empty",
	"results": {
		"time": {
			"a": 101.4,
			"b": 99.71,
			"a_div_b": 1.016949152542373
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Md 5 Buffer Non Empty",
	"results": {
		"time": {
			"a": 396.5,
			"b": 397.0,
			"a_div_b": 0.9987405541561712
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Md 5 Text Empty",
	"results": {
		"time": {
			"a": 102.1,
			"b": 102.6,
			"a_div_b": 0.9951267056530214
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Md 5 Text Non Empty",
	"results": {
		"time": {
			"a": 398.8,
			"b": 399.5,
			"a_div_b": 0.9982478097622027
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Sha 1 Buffer Empty",
	"results": {
		"time": {
			"a": 90.05,
			"b": 89.07,
			"a_div_b": 1.0110025822386888
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Sha 1 Buffer Non Empty",
	"results": {
		"time": {
			"a": 359.9,
			"b": 359.1,
			"a_div_b": 1.0022277917014757
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Sha 1 Text Empty",
	"results": {
		"time": {
			"a": 96.48,
			"b": 93.26,
			"a_div_b": 1.0345271284580742
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Sha 1 Text Non Empty",
	"results": {
		"time": {
			"a": 364.6,
			"b": 366.3,
			"a_div_b": 0.9953589953589954
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Sha 256 Buffer Empty",
	"results": {
		"time": {
			"a": 167.3,
			"b": 165.1,
			"a_div_b": 1.0133252574197458
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Sha 256 Buffer Non Empty",
	"results": {
		"time": {
			"a": 645.5,
			"b": 645.8,
			"a_div_b": 0.9995354598947043
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Sha 256 Text Empty",
	"results": {
		"time": {
			"a": 173.4,
			"b": 174.5,
			"a_div_b": 0.9936962750716333
		}
	}
}
{
	"category": "C++ > String Checksum",
	"name": "Sha 256 Text Non Empty",
	"results": {
		"time": {
			"a": 658.7,
			"b": 653.6,
			"a_div_b": 1.0078029375764994
		}
	}
}
{
	"category": "C++ > String Format",
	"name": "Complex Variable Concatenate",
	"results": {
		"time": {
			"a": 1305.0,
			"b": 1278.0,
			"a_div_b": 1.0211267605633803
		}
	}
}
{
	"category": "C++ > String Format",
	"name": "Complex Variable Method",
	"results": {
		"time": {
			"a": 2087.0,
			"b": 2054.0,
			"a_div_b": 1.0160662122687438
		}
	}
}
{
	"category": "C++ > String Format",
	"name": "Complex Variable Percent",
	"results": {
		"time": {
			"a": 1576.0,
			"b": 1563.0,
			"a_div_b": 1.0083173384516955
		}
	}
}
{
	"category": "C++ > String F [...]

2025-01-09 00:15 UTC, clayjohn commented
The physics benchmarks are a little distressing "Physics > Triangle Mesh" has an "a_dev_b" of 0.22

2025-01-09 01:11 UTC, Calinou commented
> The physics benchmarks are a little distressing "Physics > Triangle Mesh" has an "a_dev_b" of 0.22. Is that benchmark reproducible?

Unfortunately, no for two reasons:

- [There is no good way to get the time spent in the last frame processing physics](https://github.com/godotengine/godot-proposals/issues/6809), so I have to get an average value coming from the Performance singleton (measured over the last second). This is the largest reason why physics benchmarks vary so much across runs.
- The physics engine isn't deterministic, so there will always be small variance as the total number of collisions that occur during the runtime will vary across runs.

2025-01-10 10:56 UTC, Ivorforce requested changes

2025-01-10 10:56 UTC, Ivorforce commented on core/templates/local_vector.h
> +	_FORCE_INLINE_ void push_back(const T &p_elem) {
This would cause a regression of https://github.com/godotengine/godot/issues/31736

Not really your fault, it should have been commented in the code to protect against regressions :)

2025-01-10 10:56 UTC, Ivorforce commented on core/templates/local_vector.h
> +			if (tight) {
Please abstract this calculation into an inlined function instead of copying the code around.

2025-01-10 12:17 UTC, Nazarwadim commented on core/templates/local_vector.h
> +	_FORCE_INLINE_ void push_back(const T &p_elem) {
No, It won't do that. Since there is `memnew_placement(&data[count++], T(p_elem));`, the constructor will be called and a new element will be created.
This would only create regression for `Vector`, since there is no such thing and we first `resize` the array and then insert the element directly through `std::move`.

2025-01-10 12:22 UTC, Ivorforce commented on core/templates/local_vector.h
> +	_FORCE_INLINE_ void push_back(const T &p_elem) {
It will cause a regression if the vector is reallocated before the element allocation, moving the element and thus invalidating the pointer.

2025-01-10 12:37 UTC, Nazarwadim commented on core/templates/local_vector.h
> +	_FORCE_INLINE_ void push_back(const T &p_elem) {
This is, it is like?
```c++
LocalVector<LocalVector<int>> vector;
vector.push_back(element);
vector.push_back(vector[0]);
```

2025-01-10 12:40 UTC, Nazarwadim commented on core/templates/local_vector.h
> +	_FORCE_INLINE_ void push_back(const T &p_elem) {
Ahh, got it.

2025-01-10 12:49 UTC, Nazarwadim commented on core/templates/local_vector.h
> +	_FORCE_INLINE_ void push_back(const T &p_elem) {
Perhaps it would be better to insert first and then check whether the array is filled?
Like this:
```c++
	_FORCE_INLINE_ void push_back(const T &p_elem) {
		if constexpr (!std::is_trivially_constructible_v<T> && !force_trivial) {
			memnew_placement(&data[count++], T(p_elem));
		} else {
			data[count++] = std::move(p_elem);
		}
		if (unlikely(count == capacity)) {
			reserve(count + 1);
		}
	}
```

2025-01-10 12:55 UTC, Ivorforce commented on core/templates/local_vector.h
> +	_FORCE_INLINE_ void push_back(const T &p_elem) {
Yep, you got it! That's the problem the explicit copy is trying to precent.
Inserting first would almost certainly cause issues, because you'd be inserting into memory you don't know for sure is yours.
There are other ways to solve it, but I would encourage you to leave it be as-is for now (explicit copy) and, if you're motivated, try to resolve it another way with a separate PR :)

2025-01-10 14:03 UTC, Nazarwadim commented on core/templates/local_vector.h
> +	_FORCE_INLINE_ void push_back(const T &p_elem) {
Hmm, I will still ask if it is possible to do this.
```c++
	_FORCE_INLINE_ void push_back(const T &p_elem) {
		T *temp = alloca(sizeof(T));
		memcpy(temp, &p_elem, sizeof(T));

		if (unlikely(count == capacity)) {
			reserve(count + 1);
		}

		if constexpr (!std::is_trivially_constructible_v<T> && !force_trivial) {
			memnew_placement(&data[count++], T(temp[0]));
		} else {
			data[count++] = temp[0];
		}
	}
```
It looks poor, but  the constructor/destructor will not be called here, and we will write the memory on the stack before reallocation.

2025-01-10 14:09 UTC, Ivorforce reviewed
This is looking a lot better now! I'm lifting my NAK since the regression was fixed. I still have some style comments though.

2025-01-10 14:09 UTC, Ivorforce commented on core/templates/local_vector.h
> +				if (p_size > capacity) {
This is always true since you already tested this above. If it weren't true after the new capacity was found you'd get memory issues anyway, lol.

2025-01-10 14:09 UTC, Ivorforce commented on core/templates/local_vector.h
> +			if (tight) {
You can just use `capacity = tight ? p_size : MAX((U)2, capacity + ((1 + capacity) >> 1));`

2025-01-10 14:23 UTC, Nazarwadim commented on core/templates/local_vector.h
> +			if (tight) {
it needs for
```c++
if (p_size > capacity) {
```

2025-01-10 14:40 UTC, Ivorforce commented on core/templates/local_vector.h
> +	_FORCE_INLINE_ void push_back(const T &p_elem) {
This is one of the solutions I can see to work around this memory issue.
I did something similar in https://github.com/godotengine/godot/pull/100468, but ultimately it was far less important than move semantics. So I'm not sure if the additional complexity is warranted.
In either case, definitely better suited for a follow-up PR.

2025-01-10 15:36 UTC, Ivorforce commented
@Nazarwadim Please stop resolving discussions without me actively acknowledging it's been resolved.

2025-01-10 16:33 UTC, Nazarwadim commented
Sorry, ok. I thought it was resolved.

2025-01-10 16:38 UTC, Ivorforce commented on core/templates/local_vector.h
> +				if (p_size > capacity) {
@Nazarwadim This is the one I meant, it definitely warrants discussion before a merge.

2025-01-10 17:03 UTC, Nazarwadim commented on core/templates/local_vector.h
> +				if (p_size > capacity) {
So what's wrong with my implementation?

2025-01-10 17:09 UTC, Ivorforce commented on core/templates/local_vector.h
> +				if (p_size > capacity) {
It's a change of behavior, as explained above. 
Specifically, your implementation will be slower if `reserve` is called and more elements are added than reserved for, and slightly faster otherwise. 
This may be a trade-off worth making, but I'm not sure it's appropriate for this PR. If it's possible with a 1.5x growth factor, I would keep it agnostic and use the same behavior as before.

2025-01-10 17:39 UTC, Nazarwadim commented on core/templates/local_vector.h
> +				if (p_size > capacity) {
> Specifically, your implementation will be slower if reserve is called and more elements are added than reserved for.

In the engine this behavior is almost nowhere and this situation is unlikely. 
Due to the fact that less memory is used, the memory is more compact next to each other, which increases the probability that during the reserve we will allocate cached memory, and not cold from the OS.

2025-01-10 17:56 UTC, Ivorforce commented on core/templates/local_vector.h
> +				if (p_size > capacity) {
> In the engine this behavior is almost nowhere

I assume you went through the codebase and actually checked all `reserve` calls to see if this claim is actually true? :)

> and this situation is unlikely. Due to the fact that less memory is used, the memory is more compact next to each other, which increases the probability that during the reserve we will allocate cached memory, and not cold from the OS.

I have thought about the problem some more. Unfortunately, finding the 'next power of 1.5x' is a little bit harder than finding the next of 2x, so it would be a bit more complex to implement than what you have (probably with a little loop). The speed difference would likely be negligible for most scenarios.
I _think_ it would be ok to just cap it at the requested size, as you have proposed. But I'd like to hear one or two more voices before I feel comfortable giving this PR a final thumbs up.

2025-01-10 17:58 UTC, Ivorforce commented on core/templates/local_vector.h
> +			if (tight) {
Right, feel free to resolve this thread.

2025-03-28 16:30 UTC, Geometror commented on core/templates/local_vector.h
> +				if (p_size > capacity) {
I can confirm that in almost all cases we don't add more elements after a call to reserve, so it might make sense to make reserve always tight and only grow when the capacity is reached by a push_back call.
But in order to get this PR moving, I agree with @Ivorforce and would actually not do this for now. Instead, I'd go for:
```cpp
void reserve(U p_size) {
	if (p_size <= capacity) {
		return;
	}

	if (tight) {
		capacity = p_size;
	} else {
		while (p_size > capacity) {
			capacity = MAX((U)2, capacity + ((1 + capacity) >> 1));
		}
	}
	data = (T *)memrealloc(data, capacity * sizeof(T));
	CRASH_COND_MSG(!data, "Out of memory");
}
```

2025-04-14 15:59 UTC, Ivorforce approved these changes
Actually, I've come around. I think the behavior change for reserving in the above conversation makes sense (and it's precedented; `reserve` does the same in Rust).

I also want to note that 1.5x seems to be a common growth strategy now. It's often been told why, but I found [folly's](https://github.com/facebook/folly/blob/main/folly/docs/FBVector.md#memory-handling) explanations to be pretty detailed. We'll probably want to adopt a more sophisticated allocation algorithm too, but I think it's fine to move forward with this PR even without it.

2025-04-14 15:59 UTC, Ivorforce commented on core/templates/local_vector.h
> +				capacity = MAX((U)2, capacity + ((1 + capacity) >> 1));
This could use a comment that explains this is just calculates `capacity * 1.5`.

2025-04-14 16:01 UTC, Ivorforce commented on servers/rendering/rendering_device_driver.h
> +		static constexpr uint32_t UNUSED = 0xffffffff;
I'm not sure what this change is doing here but I guess it isn't doing any harm 😅

2025-04-15 17:26 UTC, Nazarwadim commented on servers/rendering/rendering_device_driver.h
> +		static constexpr uint32_t UNUSED = 0xffffffff;
As far as I remember, I did this because there were compilation errors

2025-04-21 13:31 UTC, merged

2025-04-21 13:31 UTC, Repiteo commented
Thanks!