Added support to rename projects from project manager
godotengine/godot pull request #10962
Opened 2017-09-04 14:22 UTC by nabor

Link #10740

2017-09-04 20:24 UTC, djrm requested changes

2017-09-04 20:24 UTC, djrm commented on editor/project_manager.cpp
> +		project_path = memnew(LineEdit);
if this is only for renaming, why do we need this input.

2017-09-04 20:24 UTC, djrm commented on editor/project_manager.cpp
> +	String _test_path() {
i dont think we need this here.

2017-09-04 20:43 UTC, djrm commented
@nabor after some review, there is so much repeated functionality in your PR, it might be better if you implemented something like MODE_RENAME, in the NewProjectDialog, if you want to reuse the functionality (meaning extend, the functionality of NewProjectDialog), in other case you can greatly reduce the logic following the points i suggested.

2017-09-06 22:09 UTC, nabor commented
I was bussy but will try to reimplement this, I tried to do it with a MODE_RENAME but the code wasn't clean. I agree that there is much repeated functionality. I'll try to implement it reusing NewProjectDialog in a clener way

2017-09-07 00:05 UTC, nabor commented
@djrm please delete this PR I'm creating a new one with your suggestions

2017-09-07 00:26 UTC, djrm commented
@nabor you can close your own PRs, there is a button next to comment.

2017-09-07 11:37 UTC, closed without merging