Remove instances of assignment in if statements
godotengine/godot pull request #11026
Opened 2017-09-06 21:57 UTC by hpvb

After discussing with @reduz and @akien-mga it was decided that we do
not allow assignments in if statements. This PR removes the instances of
this I could find by automated means.

2017-09-07 21:26 UTC, raymoo commented
Even for guaranteed initialization purposes?

2017-09-07 21:29 UTC, raymoo commented
I think that because declarations in if conditions are syntactically and semantically distinct from simply using an assignment expression in the condition, they should be considered separately.

2017-09-07 21:36 UTC, NathanWarden commented
100% agree with this pr. Thank you! :)

2017-09-07 21:44 UTC, raymoo requested changes
Declaration + Definition =/= assignment

The "declaration if" is a separate construct from just using assignment operators in the condition, and helps prevent null pointer dereferencing. It does not cause reading problems like using assignments in the condition does, because it is clearly visible and you cannot mix it with other conditions.

2017-09-07 21:44 UTC, raymoo commented on editor/import/resource_importer_scene.cpp
> -		if (MeshInstance *mi = Object::cast_to<MeshInstance>(p_node)) {
This is a declaration / definition, not an assignment.

2017-09-07 21:44 UTC, raymoo commented on editor/plugins/canvas_item_editor_plugin.cpp
> -			if (Node2D *node_2d = Object::cast_to<Node2D>(canvas_item)) {
Ditto

2017-09-07 21:44 UTC, raymoo commented on editor/plugins/canvas_item_editor_plugin.cpp
> -			} else if (Control *control = Object::cast_to<Control>(canvas_item)) {
Ditto

2017-09-07 21:44 UTC, raymoo commented on editor/scene_tree_dock.cpp
> -			if (List<Node *>::Element *e = selection.front()) {
Ditto

2017-09-07 21:44 UTC, raymoo commented on editor/scene_tree_dock.cpp
> -			if (List<Node *>::Element *e = selection.front()) {
Ditto

2017-09-07 21:44 UTC, raymoo commented on editor/scene_tree_dock.cpp
> -			if (List<Node *>::Element *e = selection.front()) {
Ditto

2017-09-07 21:44 UTC, raymoo commented on editor/scene_tree_dock.cpp
> -			if (List<Node *>::Element *e = selection.front()) {
Ditto

2017-09-07 21:44 UTC, raymoo commented on editor/scene_tree_dock.cpp
> -			if (List<Node *>::Element *e = selection.front()) {
Ditto

2017-09-07 21:44 UTC, raymoo commented on editor/scene_tree_dock.cpp
> -			if (List<Node *>::Element *e = selection.front()) {
Ditto

2017-09-07 21:44 UTC, raymoo commented on editor/scene_tree_dock.cpp
> -			if (List<Node *>::Element *e = selection.front()) {
Ditto

2017-09-07 21:44 UTC, raymoo commented on editor/scene_tree_dock.cpp
> -				if (Node *node = e->get()) {
Ditto

2017-09-07 21:44 UTC, raymoo commented on scene/3d/bone_attachment.cpp
> -	if (Skeleton *sk = Object::cast_to<Skeleton>(get_parent())) {
This is a declaration / definition, not an assignment.

2017-09-07 21:44 UTC, raymoo commented on scene/3d/bone_attachment.cpp
> -		if (Skeleton *sk = Object::cast_to<Skeleton>(get_parent())) {
This is a declaration / definition, not an assignment.

2017-09-07 21:44 UTC, raymoo commented on scene/3d/collision_shape.cpp
> -		if (MeshInstance *mi = Object::cast_to<MeshInstance>(n)) {
This is a declaration / definition, not an assignment.

2017-09-07 21:44 UTC, raymoo commented on scene/3d/gi_probe.cpp
> -	if (Spatial *s = Object::cast_to<Spatial>(p_at_node)) {
This is a declaration / definition, not an assignment.

2017-09-07 21:44 UTC, raymoo commented on scene/3d/interpolated_camera.cpp
> -				if (Camera *cam = Object::cast_to<Camera>(node)) {
This is a declaration / definition, not an assignment.

2017-09-07 21:44 UTC, raymoo commented on scene/gui/file_dialog.cpp
> -		if (TreeItem *item = tree->get_selected()) {
This is a declaration / definition, not an assignment.

2017-09-07 22:08 UTC, hpvb commented
@raymoo I made the exact same argument but @reduz and @akien-mga didn't want either case. I'll update the PR's title.

2017-09-07 22:49 UTC, raymoo commented
Ok, I guess it's their call in the end.

2017-09-08 00:30 UTC, raymoo commented
Another option that avoids a null dereference later on is to put an extra pair of braces around the whole thing. For example:

```
if (Banana* banana = GetABanana()) {
  // banana is not null in here
}

// becomes
{
  Banana* banana = GetABanana()
  if (banana) {
    // banana is not null
  }
}
```

2017-09-12 09:57 UTC, merged