Particles2D
godotengine/godot pull request #11516
Opened 2017-09-23 18:48 UTC by WorkShoft

I added descriptions for all Particles2D methods.

2017-09-23 20:52 UTC, cbscribe commented
Unfortunately, most of these method descriptions are going to go away. You are supposed to be documenting the member variables in the `<member></member` tags and ignoring the assorted get*/set* methods, as described in the contribution guide: http://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html

Also, please see the writing guidelines: http://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html
This will help you stick to the vocabulary/wording that the other documentation is using.

2017-09-23 22:24 UTC, WorkShoft commented
Fair enough. I don't know how I missed the writing and documenting guidelines. I will follow them on my future contributions.

2017-09-24 02:24 UTC, Noshyaar commented
Thank you for contributing! If you have done fixing the files according to the guideline, please squash commits together. ([PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request))

2017-09-24 13:15 UTC, WorkShoft commented
I moved the descriptions to the <member> tags and rewrote them following the guidelines.

2017-09-24 16:02 UTC, cbscribe requested changes

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  The amount of particles that will be spawned on each emission
Missing period. Also, I think "the number of particles" sounds better.

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  The particle list's drawing order
Also missing period.

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  If true the emitter is currently emitting, if false it is not
Should be "If [code]true[/code]" per style guide.  Remove everything after the comma, it is redundant.

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  If true the fractional delta (time between each frame) will be enabled, if false it will not
Should be "If [code]true[/code]" per style guide. Remove ", if false it will not"

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  The amount of horizontal frames
amount -> number

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  The amount of seconds that each particle will be visible
"amount of seconds" sounds very unnatural.  "The length of time each particle will be visible."

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  If true local coordinates are enabled, if false they are not
Should be "If [code]true[/code]" per style guide. Remove ", if false it will not"

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  If true, the system will stop after timeout, if false it will automatically restart.
Should be "If [code]true[/code]" per style guide. Second phrase after comma should be a new sentence.

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  The amount of seconds particles are processed before they are shown for the first time.
"length of time" or "time in seconds"

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  The emitted particles texture
missing apostrophe

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  The particles speed scale
missing apostrophe

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  The particle system's visibility rect
"rect" is not a word. Either say "rectangle" or reference the class using "[Rect2]"

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  The particle system's amount of vertical frames
Above you have "The amount of horizontal frames". Why not use the same wording here?

2017-09-24 16:02 UTC, cbscribe commented on doc/classes/Particles2D.xml
> +		  The particle system's visibility rect
Every sentence is missing a period at the end.

2017-09-25 14:31 UTC, WorkShoft commented
Feeling a bit lost here. Maybe I should get some help on IRC.

2017-09-25 20:03 UTC, cbscribe commented
Rebasing can be tricky. At this point since you're only changing one file, you might find it easier to just kill this PR, make a new branch from master, and copy your new Particles2D.xml in there.

2017-09-28 16:06 UTC, closed without merging