[DOCS] Adds JSON and JSONParseResult doc
godotengine/godot pull request #11734
Opened 2017-09-30 23:48 UTC by Jerome67000

I saw that GDScript.parse_json and GDScript.to_json is still here, JSON class is not here to replace that

2017-10-01 00:12 UTC, cbscribe requested changes

2017-10-01 00:12 UTC, cbscribe commented on doc/classes/JSON.xml
> +		Helper class for parsing JSON.
I suggest "for parsing JSON data."

2017-10-01 00:12 UTC, cbscribe commented on doc/classes/JSON.xml
> +				Parse a JSON encoded string and returns a [JSONParseResult] containing the result.
Parses

2017-10-01 00:12 UTC, cbscribe commented on doc/classes/JSON.xml
> +				Converts a Variant var to JSON text and return the result. Useful for serializing data to store or send over the network.
return -> returns

2017-10-01 00:12 UTC, cbscribe commented on doc/classes/JSONParseResult.xml
> +		Returned by [method JSON.parse], [JSONParseResult] contains decoded JSON or error information if JSON source not successfull parsed.	Check if JSON source successfull parsed with [code]if json_resul
"if JSON source was not successfully parsed."
Too many spaces after second sentence.
Last sentence:
"You can check if JSON source was successfully parsed"

2017-10-01 00:12 UTC, cbscribe commented on doc/classes/JSONParseResult.xml
> +			Returns error's type if JSON source not successfull parsed. See [@Global Scope].Error.
In general, member descriptions don't say "Returns". This is a value, not a function, and it usually can both set and get.
Try:
"The error type if if JSON source was not successfully parsed." 

That link at the end isn't right.  I don't think we have constant links, so you have to say something like "See [@Global Scope] ERR_* constants."

2017-10-01 00:12 UTC, cbscribe commented on doc/classes/JSONParseResult.xml
> +			Returns error's line if JSON source not successful parsed.
The line number where the error occurred if JSON source was not successfully parsed.

2017-10-01 00:12 UTC, cbscribe commented on doc/classes/JSONParseResult.xml
> +			Returns error message if JSON source not successful parsed. See [@Global Scope].Error.
The error message if JSON source was not successfully parsed.
See above re: link.

2017-10-01 00:12 UTC, cbscribe commented on doc/classes/JSONParseResult.xml
> +			Returns a [Variant] containing the parsed JSON. Use typeof() to check if it is what you expect. For exemple, if JSON source starts with braces [code]{}[/code] a [Dictionary] will be returned, if J
A [Variant] containing...

2017-10-01 14:08 UTC, Jerome67000 commented
@cbscribe updated 👍

2017-10-01 16:32 UTC, cbscribe commented on doc/classes/JSONParseResult.xml
> +			The line number where the error occurred if JSON source was not successfully parsed. See [@Global Scope]ERR_* constants.
Shouldn't this be the error string?

2017-10-01 20:20 UTC, Jerome67000 commented
@cbscribe fixed :)

2017-10-01 20:45 UTC, Noshyaar commented on doc/classes/JSONParseResult.xml
> +		Returned by [method JSON.parse], [JSONParseResult] contains decoded JSON or error information if JSON source not successfull parsed. You can check if JSON source was successfully parsed with [code]
successfull typo

2017-10-02 10:02 UTC, Jerome67000 commented
@Noshyaar Done ! Just intalled a spellcheck for Atom. Hop it will help with this type of errors.

2017-10-02 10:06 UTC, ghost approved these changes

2017-10-02 16:37 UTC, cbscribe approved these changes

2017-10-02 16:39 UTC, merged