Added Documentation for Sprite3D, AnimatedSprite3D and SpriteBase3D
godotengine/godot pull request #11886
Opened 2017-10-06 16:52 UTC by Grosskopf

Mostly copied from Sprite2D and AnimatedSprite2D, added some and failed to document the AlphaCut in SpriteBase3D as i don't understand it and get some Bugs trying it out

2017-10-06 18:18 UTC, NathanLovato requested changes
Thank you very much for your work. The PR does need a little polishing.
Please review the [writing guidelines](http://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html). In summary:
- Avoid the passive voice
- Avoid future tense
- Use [member member_name] to link to member vars (should work soon)
Ping me when you've amended your commit so I can approve and merge :)

2017-10-06 18:18 UTC, NathanLovato commented on doc/classes/AnimatedSprite3D.xml
> +		Sprite node in 3D that can use multiple 2D textures for animation. Animations are created using a [SpriteFrames] resource, which can be configured in the editor via the SpriteFrames panel.
Avoid repeating the brief description: develop it or at least don't duplicate it. Avoid the passive voice. Example:
`Animations rely on a [SpriteFrames] resource and work the same as [AnimatedSprite]: use the SpriteFrames bottom panel in the editor to set them up..`

2017-10-06 18:18 UTC, NathanLovato commented on doc/classes/AnimatedSprite3D.xml
> +			The current animation from the [code]frames[/code] resource. If this value is changed, the [code]frame[/code] counter is reset.
Link to member variables with [member frame], the docs should support this soon.
Passive voice: `If this value is changed` -> `If this value changes`

2017-10-06 18:18 UTC, NathanLovato commented on doc/classes/AnimatedSprite3D.xml
> +			The current frame index.
Could be clearer. Suggestion: `The index of the animation frame the node displays/displayed on screen.`
NB: passive voice is okay in some instances - when the node is acted upon, here processed by the renderer.

2017-10-06 18:18 UTC, NathanLovato commented on doc/classes/AnimatedSprite3D.xml
> +			If [code]true[/code] the [code]animation[/code] is currently playing.
Suggestion: `[code]true[/code] if the [member animation] is currently playing.`

2017-10-06 18:18 UTC, NathanLovato commented on doc/classes/Sprite3D.xml
> +			If [code]true[/code] texture will be cut from a larger atlas texture. See [code]region_rect[/code]. Default value: [code]false[/code].
Avoid future too. It adds extra words.
`If [code]true[/code], the node's texture is cut from a texture atlas. See [member region_rect]. Default value: [code]false[/code].

2017-10-06 18:18 UTC, NathanLovato commented on doc/classes/Sprite3D.xml
> +			The number of vertical frames in the sprite sheet.
What's a vertical frame? Is it a row count?

2017-10-06 18:27 UTC, cbscribe reviewed
On top of @NathanLovato 's comments - I know you took a bunch of these descriptions from Sprite & AnimatedSprite. If you fix things, can you copy them back over to those classes as well?

2017-10-07 14:31 UTC, cbscribe requested changes

2017-10-07 14:31 UTC, cbscribe commented on doc/classes/SpriteBase3D.xml
> +			If [code]true[/code], texture will be centered. Default value: [code]true[/code].
The comma here is not necessary. For the rest of the docs we've standardized on no comma after "If true", so please change to follow suit.

2017-10-07 14:31 UTC, cbscribe commented on doc/classes/SpriteBase3D.xml
> +			If set, the Texture's transparency and the opacity are used to make those parts of the Sprite invisible.
You're inconsistent about capitalizing "Texture". Unless you're linking to the Texture class, using `[Texture]`, this should be lowercase.

2017-10-07 14:31 UTC, cbscribe commented on doc/classes/SpriteBase3D.xml
> +			If [code]true[/code], the Light in the Environment has effects on the Sprite. Default value: [code]false[/code].
These should be links to the classes: `[Light]` and `[Environment]`

2017-10-07 14:31 UTC, cbscribe commented on doc/classes/SpriteBase3D.xml
> +			The Direction in wich the front of the texture faces.
Direction -> direction
wich -> which

2017-10-07 14:31 UTC, cbscribe commented on doc/classes/Sprite.xml
> +			The normalmap gives depth to the Sprite.
normal map

2017-10-07 14:31 UTC, cbscribe commented on doc/classes/AnimatedSprite.xml
> +			The index of the animation frame the node displays on screen.
This is overwritten ("on screen" is unncessary). I liked the first one, but if you want to be more specific, try something like:

    The displayed animation frame's index.

2017-10-07 14:31 UTC, cbscribe commented on doc/classes/AnimatedSprite3D.xml
> +		Sprite node in 3D that can use multiple 2D textures for animation.
"Sprite node in 3D" -> "3D sprite node"

2017-10-07 14:31 UTC, cbscribe commented on doc/classes/AnimatedSprite3D.xml
> +			The index of the animation frame the node displays on screen.
see above comment on AnimatedSprite

2017-10-07 20:42 UTC, cbscribe approved these changes

2017-10-07 23:25 UTC, merged