[DOCS] Document Tree & TreeItem
godotengine/godot pull request #11921
Opened 2017-10-07 18:56 UTC by mhilbrunner

2017-10-07 23:49 UTC, cbscribe requested changes
I didn't comment on every line, but in general:
    - use "the column's icon" instead of "the icon of the column
    - use [code]true[/code] and [code]false[/code] for boolean members/methods

2017-10-07 23:49 UTC, cbscribe commented on doc/classes/TreeItem.xml
> +				Sets whether the column [code]column[/code] is selectable.
Per writing guide, boolean methods prefer true/false wording over "whether". Try:

    If [code]true[/code] the given column is selectable.

2017-10-07 23:49 UTC, cbscribe commented on doc/classes/TreeItem.xml
> +				Sets the icon [Texture] for column [code]column[/code].
Avoid "of the" constructions where possible:

Sets the given column's icon [Texture].

2017-10-07 23:49 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Clear the tree. This removes all items.
Clear -> Clears

2017-10-07 23:49 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Make the currently selected item visible. This will scroll the tree to make sure the selected item is in sight.
Make -> Makes

"is in sight" -> "is visible"

2017-10-09 12:55 UTC, akien-mga commented
Please make sure to squash the commits together when making the requested changes: http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

2017-10-09 12:59 UTC, Noshyaar commented on doc/classes/TreeItem.xml
> +		Control for a single item inside a [Tree]. May have child [TreeItem]s and be styled as well as contain buttons.
`[TreeItem]\ s` with a backslash and a space, otherwise the link breaks.

2017-10-09 13:01 UTC, Noshyaar commented on doc/classes/TreeItem.xml
> +				Selects the colum [code]column[/code].
column

2017-10-09 20:01 UTC, mhilbrunner commented
Done & squashed. Implemented all suggestions above, hope I haven't missed anything :)

2017-10-09 20:34 UTC, cbscribe requested changes
Did a fairly quick pass. Very good - it's all minor wording changes.

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Get the title column's title.
You have an extra "title" and getters should use "Returns".

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Get the column's width in pixels.
Returns

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Get the current drop mode's flags.
Returns

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Get the currently edited item. This is only available for custom cell mode.
Returns

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Get the column for the currently edited item. This is only available for custom cell mode.
Returns

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Get the rectangle area for the specified item. If column is specified, only get the position and size of that column, otherwise get the rectangle containing all columns.
Returns

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Get the last pressed button's index.
Returns

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Get the tree's root item.
Returns

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Get the current selection's column.
Returns

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Set whether a cell that is currently already selected may be selected again.
Don't use "set whether", it's more explicit to use [code]true[/code]. 
"If [code]true[/code] the currently selected cell may be selected again."

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Set the selection mode. See the [code]SELECT_*[/code] constants.
Allows single or multiple selection. See...

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/Tree.xml
> +				Set whether the tree's root should be hidden.
Boolean

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/TreeItem.xml
> +				If [code]true[/code], column [code]column[/code] is editable.
Remove comma

2017-10-09 20:34 UTC, cbscribe commented on doc/classes/TreeItem.xml
> +				If [code]true[/code], column [code]column[/code] is expanded to the right.
Remove comma

2017-10-09 20:45 UTC, mhilbrunner commented
@cbscribe: Done.

2017-10-09 20:52 UTC, cbscribe approved these changes

2017-10-09 20:53 UTC, cbscribe commented
Thanks for your efforts - this was a big job.

2017-10-09 20:53 UTC, merged