[DOCS] - Complete Engine docs
godotengine/godot pull request #11942
Opened 2017-10-08 14:23 UTC by saltares

2017-10-08 19:05 UTC, cbscribe requested changes

2017-10-08 19:05 UTC, cbscribe commented on doc/classes/Engine.xml
> +		The [Engine] class allows you to query and modify basic parameters regarding the run-time characteristics of your game. For example: frames per second, number of frames rendered so far, time scale,
It's not necessary to link a class to itself. 

"parameters regarding" is too wordy, and "basic" is too relative. The last part is a sentence fragment. I would just say:

    allows you to query and modify the game's run-time parameters, such as frames per second, time scale, and others.

2017-10-08 19:05 UTC, cbscribe commented on doc/classes/Engine.xml
> +				Return the desired frames per second. If the hardware cannot keep up, this setting may not be respected. It defaults to 0, which indicates no limit.
Return -> Returns

2017-10-08 19:05 UTC, cbscribe commented on doc/classes/Engine.xml
> +				Controls how fast or slow the in-game clock ticks versus the real life one. It defaults to 1.0. A value of 2.0 means the game moves twice as fast as real life, whilst a value of 0.5 means the gam
The "get" method does not control the time scale, just returns the current value.

2017-10-08 19:05 UTC, cbscribe commented on doc/classes/Engine.xml
> +				Return whether or not the game is inside the fixed process and physics phase of the game loop.
Per writing guidelines, boolean methods/members prefer "[code]true[/code]" over "whether or not".

  Returns [code]true[/code] if the game is in the fixed process or physics phase of the game loop.

2017-10-08 19:05 UTC, cbscribe commented on doc/classes/Engine.xml
> +				Set whether or not the game is running in the editor.
Should use "[code]true[/code]"

2017-10-08 19:05 UTC, cbscribe commented on doc/classes/Engine.xml
> +				Set the target frames per second.
Set -> Sets

2017-10-08 19:05 UTC, cbscribe commented on doc/classes/Engine.xml
> +				Set the time scale.
Set -> Sets

2017-10-09 20:05 UTC, saltares commented
@cbscribe should be ready to go. Thanks.

2017-10-09 20:47 UTC, cbscribe requested changes
Missed a couple of requested changes.

2017-10-09 20:47 UTC, cbscribe commented on doc/classes/Engine.xml
> +				Returns whether or not the editor is running.
Per writing guidelines, boolean methods/members prefer "[code]true[/code]" over "whether or not".

Returns [code]true[/code] if the editor is running.

2017-10-09 20:47 UTC, cbscribe commented on doc/classes/Engine.xml
> +				Returns whether or not the game is inside the fixed process and physics phase of the game loop.
Per writing guidelines, boolean methods/members prefer "[code]true[/code]" over "whether or not".

Returns [code]true[/code] if the game is in the fixed process or physics phase of the game loop.

2017-10-09 20:47 UTC, cbscribe commented on doc/classes/Engine.xml
> +				Sets the amount of fixed iterations per second (for fixed process and physics).
amount -> number

2017-10-09 20:47 UTC, cbscribe commented on doc/classes/Engine.xml
> +				Returns the total amount of frames drawn.
amount -> number

2017-10-09 20:47 UTC, cbscribe commented on doc/classes/Engine.xml
> +				Returns the amount of fixed iterations per second (for fixed process and physics).
amount -> number

2017-10-09 21:21 UTC, saltares commented
Done

2017-10-09 21:35 UTC, cbscribe approved these changes

2017-10-09 21:35 UTC, cbscribe commented
Please squash the commits so we can merge.

2017-10-10 19:41 UTC, saltares commented
Squashed

2017-10-10 19:43 UTC, cbscribe commented
Thanks for your contribution!

2017-10-10 19:43 UTC, merged

2017-10-10 20:21 UTC, saltares commented
Thanks for your patience!