[DOCS] TouchScreenButton
godotengine/godot pull request #12004
Opened 2017-10-10 21:31 UTC by diowonderland

2017-10-11 02:02 UTC, Noshyaar commented on doc/classes/TouchScreenButton.xml
> +				If [code]true[/code], the button's shape is centered.
`If [code]...[/code]` shouldn't be followed by comma.

2017-10-11 02:10 UTC, Noshyaar commented on doc/classes/TouchScreenButton.xml
> +			If [code]true[/code] the button's shape is visibile.
visible

2017-10-11 04:24 UTC, cbscribe requested changes

2017-10-11 04:24 UTC, cbscribe commented on doc/classes/TouchScreenButton.xml
> +		Button that can be visible on all or only on touch screen devices.
This sentence needs attention.  Needs work, but something like:

Button for touch screen devices. You can set it to be visible on all screens, or only on touch devices.

2017-10-12 14:47 UTC, diowonderland commented
Updated!

2017-10-12 19:11 UTC, diowonderland commented on doc/classes/TouchScreenButton.xml
> +			The button's action.
Open for suggestions :)

2017-10-13 01:01 UTC, cbscribe commented on doc/classes/TouchScreenButton.xml
> +			The button's action.
How about:

The button's action. Actions can be handled with [InputEventAction].

2017-10-13 14:10 UTC, diowonderland commented
@cbscribe Done, changed the description for the action to your suggestion :)

2017-10-13 16:03 UTC, cbscribe approved these changes

2017-10-13 16:03 UTC, cbscribe commented
Thanks for your contribution!

2017-10-13 16:03 UTC, merged