[DOCS] BitmapFont
godotengine/godot pull request #12005
Opened 2017-10-10 21:51 UTC by diowonderland

2017-10-11 04:20 UTC, cbscribe requested changes

2017-10-12 14:44 UTC, diowonderland commented
Updated!

2017-10-12 17:09 UTC, Noshyaar commented on doc/classes/BitmapFont.xml
> +				Adds a character to the font, where [i]character[/i] is the unicode value, [i]texture[/i] is the texture index, [i]rect[/i] is the region in the texture (in pixels!), [i]align[/i] is the (optiona
maybe [code] instead of [i]?

2017-10-12 17:11 UTC, Noshyaar commented on doc/classes/BitmapFont.xml
> +			The chars in the BitmapFont.
'characters' would be clearer imo

2017-10-12 19:10 UTC, diowonderland commented
Updated!

2017-10-12 21:34 UTC, cbscribe approved these changes

2017-10-13 00:56 UTC, cbscribe commented
Thanks for your contribution!

2017-10-13 00:56 UTC, merged