Make slots called in the order of they are connected
godotengine/godot pull request #12248
Opened 2017-10-20 04:07 UTC by Geequlim

Store slots of signals in OrderedHashMap instead the VMap. So the connected method can be called with the order they connected.
Fix  #4898

2017-10-20 08:32 UTC, neikeq commented
> order in which objects are called is not warranted, enforcing an order
would decrease performance in connecting and disconnecting considerably.

@reduz Does this statement still apply?

2017-10-20 12:48 UTC, Zylann commented
It also looks like the container for connection will be heavier than VMap, which was basically a vector

2017-10-20 19:49 UTC, reduz requested changes

2017-10-20 19:49 UTC, reduz commented on core/object.cpp
> +	OrderedHashMap<Signal::Target, Signal::Slot, Signal::TargetHasher> slot_map = s->slot_map;
I wrote the comment above for a reason, and you are ignoring it. This will break.

2017-10-20 19:51 UTC, reduz commented
Apologies, but I don't want to merge this. It makes signals more complex and breaks the use case described in my comment. You are making a really big change for what I believe is probably a corner case that can probably be handled in a different way.

2017-10-30 22:38 UTC, akien-mga commented
Closing as per the above.

2017-10-30 22:38 UTC, closed without merging