[DOCS] Added descriptions to Camera2D
godotengine/godot pull request #12292
Opened 2017-10-21 20:27 UTC by StephenEdnave

Added descriptions to some member variables.

2017-10-21 20:53 UTC, cbscribe requested changes

2017-10-21 20:53 UTC, cbscribe commented on doc/classes/Camera2D.xml
> +			If [code]true[/code] this camera only moves when reaching the horizontal drag margins. If [code]false[/code] the camera moves horizontally regardless of margins.
Please add default value

2017-10-21 20:53 UTC, cbscribe commented on doc/classes/Camera2D.xml
> +			If [code]true[/code] smooth camera when reaching camera limits.
This feels incomplete. I think it needs an explanation of what "smooth camera" means.

2017-10-21 20:53 UTC, cbscribe commented on doc/classes/Camera2D.xml
> +			If [code]true[/code] this camera moves with smoothing.
As above, describe what smoothing does.

2017-10-21 20:53 UTC, cbscribe commented on doc/classes/Camera2D.xml
> +			Speed at which the camera moves to its current smoothing destination.
The camera's speed when moving to its...

2017-10-21 23:35 UTC, cbscribe commented on doc/classes/Camera2D.xml
> +			If [code]true[/code] the camera gradually changes its velocity vector. Default value: [code]false[/code].
Hmm, this makes it sound like the camera just moves by itself.  How about:

    If [code]true[/code] the camera's velocity changes gradually, preventing sudden starts and stops.

2017-10-21 23:36 UTC, cbscribe commented on doc/classes/Camera2D.xml
> +			The camera's acceleration if smoothing is enabled.
Not sure about this one. Is it an acceleration? The name says speed.

2017-10-21 23:37 UTC, cbscribe commented on doc/classes/Camera2D.xml
> +			If [code]true[/code] this camera only moves when reaching the horizontal drag margins. If [code]false[/code] the camera moves horizontally regardless of margins. Default value: [code]true[/code].
Everywhere else you say "the camera" instead of "this camera". You should make it consistent.

2017-10-22 05:21 UTC, cbscribe approved these changes

2017-10-22 05:21 UTC, cbscribe commented
Looks good, please squash the commits.

2017-10-22 09:58 UTC, akien-mga commented
Squashed and merged manually as 8f382879c.

2017-10-22 09:58 UTC, closed without merging