[DOCS] RemoteTransform & RemoteTransform2D
godotengine/godot pull request #12318
Opened 2017-10-22 18:25 UTC by mhilbrunner

2017-10-22 23:41 UTC, cbscribe requested changes

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform.xml
> +		RemoteTransform mirrors the [Transform] of another Node in the scene.
It can't be a Node, it must be a [Spatial] derived node.

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform.xml
> +		RemoteTransform mirrors the [Transform] of another Node (called the [code]remote node[/code]) in the scene.
As above, must be a [Spatial] node

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform.xml
> +		It can be set to track another Node's position, rotation, scale or all of those and update its own accordingly, using either global or local coordinates.
- "or all of those" implies it has to be only one or *only* all three.

track another node's position, rotation, and/or scale

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform.xml
> +		The [code]remote node[/code] has to inherit from [Spatial] (i.e. it actually has to have a [Transform] to mirror).
- why is "remote node" in [code]? It should either be text "remote node" or a link to the actual [member remote_path]
- may be redundant if you specify [Spatial] in the first sentence.

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform.xml
> +		Note that while the name may suggest otherwise, RemoteTransform has nothing to do with networking. It only works on local Nodes.
Not sure this is necessary.

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform.xml
> +		For a 2D version, see [RemoteTransform2D].
We should only do this if we're going to be consistent and link every 2D <-> 3D equivalent. Seems like too much.

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform.xml
> +			The [NodePath] of the mirrored [code]remote node[/code].
- The remote node's [NodePath].

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform.xml
> +			If [code]true[/code] the [code]remote node[/code]'s position is mirrored.
- remove [code] tags around "remote node"

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform.xml
> +			If [code]true[/code] the [code]remote node[/code]'s rotation is mirrored.
- remove [code] tags around "remote node"

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform.xml
> +			If [code]true[/code] the [code]remote node[/code]'s scale is mirrored.
- remove [code] tags around "remote node"

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform.xml
> +			If [code]true[/code] global coordinates are used. Otherwise local coordinates are used.
- Otherwise -> If [code]false[/code]
- Add default value (I'd like to know if it defaults to global or local)

2017-10-22 23:41 UTC, cbscribe commented on doc/classes/RemoteTransform2D.xml
> +		RemoteTransform2D mirrors the [Transform2D] of another Node in the scene.
Same comments as RemoteTransform above

2017-10-23 00:19 UTC, mhilbrunner commented
@cbscribe Fixed :)

2017-10-23 00:29 UTC, cbscribe approved these changes

2017-10-23 00:29 UTC, cbscribe commented
Thanks again!

2017-10-23 00:29 UTC, merged