[DOCS] Added description for camera2D missing members
godotengine/godot pull request #12400
Opened 2017-10-25 13:09 UTC by henriiquecampos

Also fixed typo in AudioEffectFilter and fixed some descriptions to better understanding.

2017-10-25 16:52 UTC, cbscribe requested changes

2017-10-25 16:52 UTC, cbscribe commented on doc/classes/Camera2D.xml
> +			If [code]true[/code] the camera rotates with the target.
Nice change, but don't remove the default value.

2017-10-25 16:52 UTC, cbscribe commented on doc/classes/Camera2D.xml
> +			If [code]true[/code] the camera smoothly moves towards the target at [member smoothing_speed].
Please keep the default value. It's useful to know at a glance that smoothing is off by default.

2017-10-25 16:52 UTC, cbscribe commented on doc/classes/Camera2D.xml
> +			Speed in pixels per second of the smoothing effect of the camera.
- Use possessive over "of the"

"of the camera's smoothing effect."

- add link to associated member:

See [member smoothing_enabled].

2017-10-25 17:39 UTC, henriiquecampos commented
Thanks guys, done the changes, but please don't make me squash'm I'm kinda traumatized with this :(

2017-10-25 17:44 UTC, akien-mga commented
If you follow the docs, there's nothing to be traumatized about: http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

And those docs even tell you that instead of making a new commit, you could have amended the original one directly.

2017-10-25 17:44 UTC, cbscribe approved these changes

2017-10-26 07:09 UTC, akien-mga commented
Merged manually as 1063ddfeb.

2017-10-26 07:09 UTC, closed without merging