[DOCS]Completed LineEdit.xml
godotengine/godot pull request #12445
Opened 2017-10-27 22:25 UTC by MattUV

I filled the LineEdit.xml file. However:

- I completed the ALIGN_FILL description but the code currently does nothing. It should be fixed, or the documentation should be modified
- I did not complete the MENU_MAX description, because it seems deprecated (or not implemented yet). This constant appears only in LineEdit.cpp and TextEdit.cpp and in both cases it does nothing. Should we delete it?
- I did not complete the Theme Items  section. Should I?

This is my second commit in the docs, I hope I did things right.

2017-10-28 12:21 UTC, Noshyaar commented on doc/classes/LineEdit.xml
> +			Centers the thext in the middle of the [LineEdit].
thext -> text

2017-10-28 12:22 UTC, Noshyaar commented on doc/classes/LineEdit.xml
> +			Opacity of the [member placeholder text]. From [code]0[/code] to [code]1[/code].
should be `[member placeholder_text]` with an underscore?

2017-10-28 14:10 UTC, MattUV commented
Thanks. It should be good now.

2017-10-28 14:15 UTC, ghost approved these changes

2017-10-28 16:47 UTC, cbscribe requested changes

2017-10-28 16:47 UTC, cbscribe commented on doc/classes/LineEdit.xml
> +			If [code]true[/code], every character is shown as "*".
Remove comma

2017-10-28 16:47 UTC, cbscribe commented on doc/classes/LineEdit.xml
> +			If [code]true[/code], the [LineEdit] width will increase to stay longer than the [member text]. It will [b]not[/b] compress if the [member text] is shortened.
Remove comma

2017-10-28 16:47 UTC, cbscribe commented on doc/classes/LineEdit.xml
> +			If [code]false[/code], existing text cannot be modified and new text cannot be added.
Remove comma

2017-10-28 16:47 UTC, cbscribe commented on doc/classes/LineEdit.xml
> +			If [code]true[/code], the caret (visual cursor) blinks.
Remove comma

2017-10-28 16:47 UTC, cbscribe commented on doc/classes/LineEdit.xml
> +				select(2, 5) # lco
If the LineEdit node is named "LineEdit", you need to use `$LineEdit.select()`, or change to `text = "Welcome"`

2017-10-28 21:56 UTC, MattUV commented
Why so much hate against commas? You just made them cry :,-(
Thanks for correcting me, I updated the commit

2017-10-29 02:47 UTC, cbscribe approved these changes

2017-10-29 03:22 UTC, merged