Allow to extends constant variable(master)
godotengine/godot pull request #12507
Opened 2017-10-30 12:00 UTC by sanikoyes

this pr same to : https://github.com/godotengine/godot/pull/12506

2017-10-30 16:42 UTC, akien-mga commented on modules/gdscript/gd_parser.cpp
> +				break;
It looks like clang-format doesn't like the indentation style you used: https://travis-ci.org/godotengine/godot/jobs/294820735

2017-10-30 20:29 UTC, akien-mga commented
Pre-approved in PR review meeting, will merge tomorrow once 3.0 alpha2 is released, to avoid potential regressions.

2017-10-30 21:00 UTC, Marqin requested changes

2017-10-30 21:00 UTC, Marqin commented on modules/gdscript/gd_compiler.cpp
> +						Ref<GDScript> base = base_class->constants[subclass];
You are overloading your outer scope variable `String base` here and I don't think it's a good practice. Try using some different name, for example `Ref<GDScript> new_base_class` would be better imho.

2017-11-16 23:39 UTC, akien-mga commented
Sorry for the delay - I've done a refactoring of the gdscript module in #12969 so there are now merge conflicts to resolve. As the file names changed and all `GD*` classes are now prefixed with `GDScript`, the faster solution might be to reimplement your changes on top of a clean branch and force push it to override this one.

2017-11-20 22:25 UTC, akien-mga commented
Merged manually as fb801d496 to fix the merge conflicts (and take @Marqin's review into account).

2017-11-20 22:25 UTC, closed without merging