Fix signals disconnecting on changing target node type
godotengine/godot pull request #12830
Opened 2017-11-11 02:44 UTC by ianb96

fixes #11673
I removed the ERR_CONTINUE that checked if the target has the signal method, it seemed unnecessary and was causing the problem.

2017-11-11 02:58 UTC, neikeq commented
That was a fix for #6602. I'm not sure if I understand #11673, is the target a script method? I would expect `has_method` to detect it and keep the connection:

https://github.com/godotengine/godot/blob/19b1ff0fc5f7acce23176ad6c8752604357472f0/core/object.cpp#L699-L716

Maybe it is not working for non-tool scripts because of placeholders? If that's the case, then I think checking it in the script itself should work. Something like this:
``` C++
ERR_CONTINUE(!p_new_target->has_method(c.method) && !(get_script().is_valid() && get_script()->has_method(c.method)));
```

2017-11-11 16:05 UTC, ianb96 commented
I updated the code to use `!p_new_target->has_method(c.method) && (!p_new_target->get_script().is_null() && !Ref<Script>(p_new_target->get_script())->has_method(c.method))` to check if the node has the method.

2017-11-11 16:07 UTC, neikeq approved these changes

2017-11-13 21:36 UTC, vnen requested changes

2017-11-13 21:36 UTC, vnen commented on scene/main/node.cpp
> +			bool invalid = !p_new_target->has_method(c.method) && (!p_new_target->get_script().is_null() && !Ref<Script>(p_new_target->get_script())->has_method(c.method));
You should reverse the logic to test if it's `valid` instead, then do `ERR_CONTINUE(!valid)`. It'll make the condition easier to understand.

Make sure to amend the commit after the change. You can consult our [PR workflow guide](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request) for instructions.

2017-11-13 23:00 UTC, ianb96 commented
I changed it to use `p_new_target->has_method(c.method) || p_new_target->get_script().is_null() || Ref<Script>(p_new_target->get_script())->has_method(c.method)` and !valid

2017-11-13 23:03 UTC, merged