Fixing tilemap rotation for non top-left tiles.
godotengine/godot pull request #12870
Opened 2017-11-12 21:55 UTC by Nibodhika

Fixes #11876. It still seems wrong, but now it behaves the same as in 2.x.

2017-11-13 07:34 UTC, akien-mga commented on scene/2d/tile_map.cpp
> +					//xform *= shapes[i].shape_transform;
Please remove commented out code. If there's a reason to keep it, there must be a comment explaining why.

2017-11-13 07:34 UTC, akien-mga commented on scene/resources/tile_set.cpp
> +	Transform2D transform = tile_get_shape_transform(p_id,0);
Style issue here (and on line 321): https://travis-ci.org/godotengine/godot/jobs/301115760

2017-11-13 07:35 UTC, akien-mga commented
Please squash the commits together when the style issue is fixed ([PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request)).

2017-11-13 10:03 UTC, Nibodhika commented
I think I did something wrong on the rebase because there's now another commit appearing in the pr that is not mine, altough mine were squashed.

2017-11-13 10:10 UTC, akien-mga commented
Try to rebase again on `upstream/master`.

2017-11-13 14:39 UTC, Nibodhika commented
Done, thanks for the patience

2017-11-13 14:43 UTC, akien-mga submitted a review, later dismissed

2017-11-13 16:24 UTC, bojidar-bg requested changes
Tested on a test project of mine, which had multiple shapes per tile, some of them were still off.

2017-11-13 16:24 UTC, bojidar-bg commented on scene/2d/tile_map.cpp
> +					Vector2 shape_ofs = tile_set->tile_get_shape_offset(c.id);
You should use `i` as well, since different tiles can have different shape offsets.

2017-11-13 16:24 UTC, bojidar-bg commented on scene/resources/tile_set.cpp
> +void TileSet::tile_set_shape_offset(int p_id, const Vector2 &p_offset) {
You should take `p_shape_id` as well, instead of hardcoding id = 0.

2017-11-15 11:11 UTC, Nibodhika commented
Sorry about the .h, must have lost it on the rebase.

2017-11-16 22:48 UTC, Nibodhika commented
I submitted the requested changes yesterday, I guess there was no notification because I amended the previous commit.

2017-11-16 23:05 UTC, merged