Few fixes for asset store browser
godotengine/godot pull request #13008
Opened 2017-11-18 11:56 UTC by Chaosus

1) Set an icon size to constant 80x80, assets will be stretched to this size. I think its better be constant for all assets, cuz different sizes of different assets looks ugly

2) Added missed icons for rating stars, I dont know how to recompile theme_data.h - I cant modify it cuz 
a banner says - // THIS FILE HAS BEEN AUTOGENERATED, DON'T EDIT!!, so I just placed two png files into default theme folder... and hope it work..(correct me if I wrong)
 
So the result looks like
![image](https://user-images.githubusercontent.com/3036176/32979766-890748be-cc6c-11e7-978c-4ede809e29ed.png)
yes I fill star with gray color, cuz transparent looks very hard for eyes(on dark themes)
and(if stars is active)
![image](https://user-images.githubusercontent.com/3036176/32979979-b7509e98-cc6f-11e7-95d0-21dd2c17b555.png)

2017-11-18 12:20 UTC, leoddd commented
Godot already comes with a star icon, couldn't that be used? The one displayed in the project browser for example.

2017-11-18 12:22 UTC, Chaosus commented
I didnt find it, by words "star" or "rating"

2017-11-18 12:24 UTC, Chaosus commented
Ah.. word favorite.. but is svg, needs to be converted to png

2017-11-18 12:39 UTC, Chaosus commented
![image](https://user-images.githubusercontent.com/3036176/32980388-a5e84596-cc76-11e7-8c23-eb54ab57031b.png)
- looks good ?

2017-11-18 12:42 UTC, reduz commented
It definitely looks better, hope @djrm eventually gives it a lift in general :)

2017-11-18 12:51 UTC, Chaosus commented
Ok, than I done for myself :) Its not good if in beta people looking on ERROR messages in place on rating stars, even if it is impossible(for now) to rate from asset store

2017-11-18 13:05 UTC, Chaosus commented
OOps, found a bug inside 1).. needs to be fixed before merged

2017-11-18 13:25 UTC, Chaosus commented
Ok, now its looking correct, I maked thumbnail to correct size

![image](https://user-images.githubusercontent.com/3036176/32980729-1f3cdc26-cc7d-11e7-95ed-e7dee14f4896.png)

Ready to merge !

2017-11-18 13:57 UTC, Chaosus commented
I also fixed invalid screenshot size so

![image](https://user-images.githubusercontent.com/3036176/32980979-90919890-cc81-11e7-9d80-5251b305c809.png)

2017-11-18 14:32 UTC, vnen commented
> Ah.. word "favorite".. but it is in svg format, needs to be converted into png

Not really, Godot has support for SVG and all icons are in this format, no need to convert them.

2017-11-18 14:44 UTC, Chaosus commented
Than why is make_icon method existed and called multiple times in default_theme.cpp ? It used to load png icon and I used it...

2017-11-18 14:56 UTC, Chaosus commented
I really tired from this PR, need a rest btw....  if its would be merged, I'be happy... :)

2017-11-18 19:01 UTC, Chaosus commented
I didnt find function for load icon from SVG, can someone help me or its fine to use png ?

2017-11-18 22:46 UTC, djrm commented
Using the header icons is discouraged, and actaully we only do that to keep the old editor theme, the thing you have to do to get icons is simply call 
`get_icon("Favorites", "EditorIcons");`
and 
`get_icon("NonFavorite", "EditorIcons");`

and you are getting the rendered SVGs, alternatively you can put an optimized version of your SVGs in editor/icons, all of them are placed under a header and then rendered in editor, so if you put an icon there called `icon_star.svg` you can retrieve it by calling `get_icon("Star", "EditorIcons");`

The optimization of the svg is quite important since it affects the binary size and the editor boot time.

2017-11-18 22:52 UTC, djrm requested changes
please check my other comment to see how to load svg icons, that would make this PR simpler

2017-11-18 22:52 UTC, djrm commented on scene/resources/default_theme/default_theme.cpp
> +	theme->set_icon("RatingStar", "EditorIcons", make_icon(star_active_png));
not good, deafult_theme should not be touched except for bug fixes, and this is not one, check my comment on how to load icons.

2017-11-18 22:52 UTC, djrm commented on editor/plugins/asset_library_editor_plugin.cpp
> +					image->resize(80, 80, Image::INTERPOLATE_CUBIC);
this might need to be multiplied by EDSCALE, so it works in hiDPI

2017-11-19 07:14 UTC, Chaosus commented
How its now ? A much cleaner I think... I applied hidpi fix as @djrm suggested

2017-11-19 07:32 UTC, djrm commented on editor/plugins/asset_library_editor_plugin.cpp
> +					image->resize(134 * EDSCALE, 69 * EDSCALE, Image::INTERPOLATE_CUBIC);
are you sure the backend always produce thumbnails with this aspect ratio, i dont see why we should asume such thing, as far as i can tell a thumbnail should also preserve its aspect ratio, with the icon it kinda makes sense but with this im not sure.

2017-11-19 08:04 UTC, Chaosus commented
And now its ok ?

2017-11-19 20:00 UTC, djrm commented
i think its ok, well there is some code repetition but its not that bad.

2017-11-20 08:09 UTC, akien-mga commented
Nice work and thanks for your patience :)

2017-11-20 08:10 UTC, merged