Added documentation (GeometryInstance and VisualInstance)
godotengine/godot pull request #13313
Opened 2017-11-26 16:31 UTC by TwistedTwigleg

I've filled in the documentation for both GeometryInstance and VisualInstance.

(I'm probably going to add docs for World, Theme, StreamTexture, Sky, and ShortCut as they're relatively easy to do. I'll add another commit on this PR when they're finished)

2017-11-26 18:21 UTC, akien-mga commented on doc/classes/GeometryInstance.xml
> +
Please don't add empty lines, one line == one paragraph already. Use `git commit --amend` to modify that commit (see [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html)).

2017-11-26 18:27 UTC, cbscribe requested changes
Great work! I added some corrections and a couple of requests for clarification.

2017-11-26 18:27 UTC, cbscribe commented on doc/classes/GeometryInstance.xml
> +			The currently selected shadow casting flag.
Whenever possible, remove extra words that don't add content, ex: "currently".

When a member uses named constants, the standard has been to refer to them in the description, so the reader knows where to look. "See SHADOW_CASTING_SETTING_* constants for values."

2017-11-26 18:27 UTC, cbscribe commented on doc/classes/GeometryInstance.xml
> +			The extra distance added to the GeometryInstance's bounding box ([AABB]) to increase it's cull box.
it's -> its

2017-11-26 18:27 UTC, cbscribe commented on doc/classes/GeometryInstance.xml
> +			The max distance for the LOD of this GeometryInstance.
Per doc guidelines, prefer possessive over "of the" constructions. 

The GeometryInstance's max LOD distance.

2017-11-26 18:27 UTC, cbscribe commented on doc/classes/GeometryInstance.xml
> +			The max margin for the LOD of this GeometryInstance.
See previous comment.

2017-11-26 18:27 UTC, cbscribe commented on doc/classes/GeometryInstance.xml
> +			The min distance for the LOD of this GeometryInstance.
See previous comment.

2017-11-26 18:27 UTC, cbscribe commented on doc/classes/GeometryInstance.xml
> +			The min margin for the LOD of this GeometryInstance.
See previous comment.

2017-11-26 18:27 UTC, cbscribe commented on doc/classes/GeometryInstance.xml
> +			If there is a material in material_override, it will be used instead of any material set in any material slot of the mesh.
Don't use blank lines. Newlines start new paragraphs.

2017-11-26 18:27 UTC, cbscribe commented on doc/classes/GeometryInstance.xml
> +			If [code]true[/code], then this GeometryInstance will be used when baking lights using a [GIProbe] and/or any other form of baked lighting.
Remove comma after "If [code]true[/code]"
Remove "then"

2017-11-26 18:27 UTC, cbscribe commented on doc/classes/VisualInstance.xml
> +				Returns the transformed [AABB] (also known as the bounding box) for this VisualInstance.
Might be useful to indicate what "transformed" means here.

2017-11-26 18:27 UTC, cbscribe commented on doc/classes/VisualInstance.xml
> +				Allows you to change the base of te VisualInstance, which changes how the engine handels the VisualInstance under the hood.
te -> the
handels -> handles

"Allows you to change" -> Sets

2017-11-26 18:27 UTC, cbscribe commented on doc/classes/VisualInstance.xml
> +			This object will only be visible for [Camera]'s whose cull mask includes the render object this VisualInstance is set to.
"[Camera]'s" - remove apostrophe, this isn't possessive.

2017-11-26 19:32 UTC, TwistedTwigleg commented
Thanks @cbscribe  and @akien-mga!

I fixed the problems in VisualInstance and GeometeryInstance. Now they hopefully have no more spelling and grammar issues, along with being more clear. I fixed them in the second commit, is that okay? I can try to fix the first commit if needed.

I added documentation for World, Theme, StreamTexture, Sky, and ShortCut. They probably could use a second pair of eyes, since I'm not sure everything is 100% accurate to what they actually do (mainly Sky and Shortcut). I tried to assure they don't have problems like VisualInstance and GeometeryInstance, so hopefully everything is good there.

2017-11-26 19:35 UTC, cbscribe commented
You will need to squash down to one commit before this can be merged - the Godot team likes to keep the commit log clean.

Also, as a general rule of thumb, try and do a separate PR for different, unrelated changes. It's easier to track and review if they're not all in one gigantic commit.

2017-11-26 19:38 UTC, TwistedTwigleg commented
Should I squash this commit into one? Or make another PR with the additional documentation? (World, Theme, StreamTexture, Sky, and ShortCut)

2017-11-28 03:15 UTC, cbscribe approved these changes

2017-11-28 03:15 UTC, cbscribe commented
Thanks for your effort!

2017-11-28 03:15 UTC, merged