Added documentation (World, Theme, StreamTexture, Sky, and ShortCut)
godotengine/godot pull request #13320
Opened 2017-11-26 20:04 UTC by TwistedTwigleg

I've filled in the documentation for World, Theme, StreamTexture, Sky, and ShortCut.

2017-11-26 23:42 UTC, cbscribe requested changes
Great work! Just some minor consistency changes needed.

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/ShortCut.xml
> +				Returns true if Shortcut's [InputEvent] equals [code]event[/code].
- wrap [code] tags around "true".
- *the* Shortcut

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/ShortCut.xml
> +				Returns whether or not this Shortcut is valid.
Per doc guidelines, we're trying to avoid "whether or not" construction. Use "If [code]true[/code] this Shortcut is valid."

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/ShortCut.xml
> +			Generally the [InputEvent] a keyboard key, though it can be any [InputEvent].
Missing "is"?

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Sky.xml
> +		The baseclass for [PanoramaSky] and [ProceduralSky].
base class

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Sky.xml
> +		The baseclass for [PanoramaSky] and [ProceduralSky].
base class

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Sky.xml
> +			Radiance texture size will be 32x32 pixels large.
In general, we're trying to avoid future tense, so try changing "will be" to "is".  Also, "large" doesn't fit, nor would "small" - it's just a size.

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Returns all of the [Color]s as a [PoolStringArray] filled with each [Color]'s name, for use in get_color, if Theme has [code]type[/code].
Reference methods with "[method get_color]"

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Returns all of the icons as a [PoolStringArray] filled with each [Texture]'s name, for use in get_icon, if Theme has [code]type[/code].
Reference methods with "[method get_icon]"

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Returns all of the [StyleBox]s as a [PoolStringArray] filled with each [StyleBox]'s name, for use in get_stylebox, if Theme has [code]type[/code].
Reference methods with "[method get_stylebox]"

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Returns all of the [StyleBox] types as a [PoolStringArray] filled with each [StyleBox]'s type, for use in get_stylebox and/or get_stylebox_list, if Theme has [code]type[/code].
Reference methods with "[method get_stylebox]"

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Returns whether [Color] with [code]name[/code] is in [code]type[/code].
Remove "whether" and use "Returns [code]true[/code] if..."

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Will return false if Theme does not have [code]type[/code].
"Returns" in previous sentence is correct, present tense. Don't use future tense here.

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Will return false if Theme does not have [code]type[/code].
As above

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Will return false if Theme does not have [code]type[/code].
As above

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Will return false if Theme does not have [code]type[/code].
As above

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Will return false if Theme does not have [code]type[/code].
As above

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Will not set if Theme does not have [code]type[/code].
"Will not set" -> "Does nothing if..."

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Will not set if Theme does not have [code]type[/code].
As above

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Will not set if Theme does not have [code]type[/code].
As above

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Will not set if Theme does not have [code]type[/code].
As above

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +			<argument index="2" name="stylebox" type="StyleBox">
You can't edit argument tags - these are automatically generated from source. Only `<description>` tags may be edited.

2017-11-26 23:42 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Will not set if Theme does not have [code]type[/code].
As above

2017-11-27 00:06 UTC, TwistedTwigleg commented
Thanks @cbscribe, I’ll fix these tomorrow 👍

2017-11-28 03:16 UTC, cbscribe approved these changes

2017-11-28 03:17 UTC, cbscribe commented on doc/classes/Theme.xml
> +				Returns false if Theme does not have [code]type[/code].
Please also add [code] tags around "false" (here and below)

2017-11-28 14:55 UTC, TwistedTwigleg commented
Fixed!

(Thanks for all the help cbscribe!)

2017-11-28 19:03 UTC, merged