Update TileMap doc descriptions for update_bitmask_area/region
godotengine/godot pull request #15006
Opened 2017-12-24 16:59 UTC by CyanBlob

2017-12-24 17:37 UTC, Noshyaar commented on doc/classes/TileMap.xml
> +				Calling with invalid (or missing) paramaters will apply autotiling rules for the entire TileMap
>paramaters

2017-12-24 17:55 UTC, CyanBlob commented
Woops, sorry about that. I corrected the spelling and added the missing periods. Thanks!

2017-12-27 19:59 UTC, cbscribe requested changes
Style changes - please see http://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html

2017-12-27 19:59 UTC, cbscribe commented on doc/classes/TileMap.xml
> +				Apply autotiling rules for the cell referenced by its grid-based X and Y coordinates, and its surrounding cells.
- Use present tense in all method descriptions: Apply -> Applies
- Remove unnecessary comma

2017-12-27 19:59 UTC, cbscribe commented on doc/classes/TileMap.xml
> +				Apply autotiling rules for the cells in given region (specified by grid-base X and Y coordinates).
- Apply -> Applies
- for -> to
- in given region -> in the given region
- grid-base -> grid-based

2017-12-27 19:59 UTC, cbscribe commented on doc/classes/TileMap.xml
> +				Calling with invalid (or missing) parameters will apply autotiling rules for the entire TileMap.
- will apply -> applies

2017-12-27 23:52 UTC, merged