Fix anoying crash when closing the Editor
godotengine/godot pull request #15702
Opened 2018-01-14 13:27 UTC by MarianoGnu

The reason of the crash was that flushing messages was trying to call get_icon from default them, but this was previously freed.
This PR needs review from core programmers because this change may cause unexpected and undesired execution order, in that case the solution should be prevent the call to be queued in the message queue which would take some more work.

2018-01-15 19:30 UTC, reduz requested changes

2018-01-15 19:30 UTC, reduz commented on main/main.cpp
> +	message_queue->flush();
fix is good, but i would move this a few lines up, below

```
ERR_FAIL_COND(!_start_success);
```

2018-01-16 21:28 UTC, akien-mga commented
Merged manually as ff59c562f with proposed change.

2018-01-16 21:28 UTC, closed without merging

2018-01-25 20:09 UTC, neikeq commented
This is causing crashes with the mono module, because the message queue is freed before finalizing languages which is when we run all pending finalizer and unload. If an object is disposed from the finalizer thread, we enqueue it for deletion in the main thread (call_deferred).

2018-01-25 23:45 UTC, reduz commented
But this does not free the message queue, not sure if I understand the problem

2018-01-25 23:49 UTC, akien-mga commented
Check the commit again, it memdeletes it. Maybe it should be flushed at start, then flushed and deleted at the end. (Or even flushed at each step?)

2018-01-26 00:18 UTC, neikeq commented
I ended up simply not deferring the call if the domain is being finalized, since it's gonna be called right after that anyway. I still don't think it's a good idea to free the `MessageQueue` singleton before finalizing script languages, but it's not urgent.