allow comments and whitespace before shader_type declaration
godotengine/godot pull request #16052
Opened 2018-01-25 01:21 UTC by brainsick

Needs review.

I re-define a GETCHAR macro in this file.  Should I use another name?  Both uses are local to their respective functions.

Fixes #16032.

2018-05-07 20:42 UTC, reduz requested changes

2018-05-07 20:42 UTC, reduz commented on servers/visual/shader_language.cpp
> +	}
seems fine, but please undefine GETCHAR at the end

2018-05-26 19:50 UTC, mhilbrunner commented
@brainsick Can you make the requested change?

2018-07-25 22:19 UTC, akien-mga commented
Merged manually as 9423f23ff with the required `#undef GETCHAR`. Also added one for the previous `GETCHAR` definition.

2018-07-25 22:19 UTC, closed without merging

2019-07-03 09:36 UTC, akien-mga commented
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.