Created a new function named get_element in GridContainer. This funct…
godotengine/godot pull request #16977
Opened 2018-02-24 12:41 UTC by SASUPERNOVA

…ion gets the Control at the specified row and column. This works in a similar manner as the operator[] (i.e. indexing starts from 0).

2018-04-08 15:00 UTC, reduz requested changes

2018-04-08 15:00 UTC, reduz commented on scene/gui/grid_container.cpp
> +Control* GridContainer::get_element(int row, int column)
would rename to get_child_control_at_cell(int row,int column)

2018-04-08 15:11 UTC, Noshyaar commented on scene/gui/grid_container.cpp
> +	ClassDB::bind_method(D_METHOD("get_element"), &GridContainer::get_element);
should be `D_METHOD("get_child_control_at_cell", "row", "column")`

2018-04-08 15:11 UTC, Noshyaar commented
There are some styling issues. The changes didn't comply with clang-format. Please use `clang-format -i <filename>` and `git commit --amend`.

2018-04-13 23:39 UTC, SASUPERNOVA commented
I had some issues with updating my branch, but I think it should be OK now. Please let me know if the files have not been properly updated.

2018-04-15 09:43 UTC, akien-mga commented
There are still merge conflicts + style issues (you changed indentation and line wrappings), see: https://github.com/godotengine/godot/pull/16977/files

Once fixed, the commits should be squashed together to have only one commit changing from the initial state to the new state.

2018-05-01 14:32 UTC, akien-mga commented
Thanks, looks good.

2018-05-01 14:32 UTC, merged

2018-10-04 10:47 UTC, akien-mga commented
This raises a warning with GCC 8:
```
scene/gui/grid_container.cpp: In member function 'Control* GridContainer::get_child_control_at_cell(int, int)':
scene/gui/grid_container.cpp:256:9: warning: 'c' may be used uninitialized in this function [-Wmaybe-uninitialized]
  return c;
         ^
```

Looking at it again, the whole method seems to be wrong - why use a for loop to iterate over all children when you only want the child with index `grid_index`? You could just use `get_child(grid_index)` directly.

And is it guaranteed that `GridContainer` will always have one child in each cell? If not this method really doesn't make sense. It also doesn't have proper checks that `row` and `column` are within bounds, and can thus return an uninitialized `Control *c` as raised above.

2018-10-07 10:59 UTC, akien-mga commented
Reverted in #22822, but it looks like I did misunderstand what the method does and that it's not that trivial, and might be worth readding with a fixed implementation and more comments. See https://github.com/godotengine/godot/pull/22788#discussion_r223178217