Make Button not emit press when container is scrolled
godotengine/godot pull request #17081
Opened 2018-02-27 16:04 UTC by endragor

This fixes the problem described in #13996 in a proper way.

This also adds "deadzone" property to ScrollContainer. It can be used
on mobile, where taps are not as precise as mouse clicks. Player could
slightly move their finger when tapping, in which case we still want
the button to be pressed rather than the container to be scrolled.

2018-02-27 16:06 UTC, volzhs commented
I DO like this PR. :)

2018-04-08 14:41 UTC, reduz requested changes

2018-04-08 14:41 UTC, reduz commented on scene/main/node.h
> +		NOTIFICATION_SCROLL_BEGIN = 27,
This should most likely go in Control notifications instead of Node, since only controls will use it.

Other than that, PR is perfect.

2018-04-09 13:36 UTC, endragor commented
Updated based on the comment from @reduz.

2018-04-10 05:56 UTC, merged

2018-04-10 05:56 UTC, akien-mga commented
Thanks!

2018-04-14 17:44 UTC, hpvb commented
cherry picked into 3.0.3