Fixes canvas light shaders.
godotengine/godot pull request #17391
Opened 2018-03-09 23:23 UTC by PJB3005

Fixes #16904 

So one thing I'm not sure about here is that it seems like previously, if the code were to compile, the `light` value wasn't actually used if a lighting shader is used, because the code for it is behind the `#else`. I fixed this.

2018-03-10 01:38 UTC, PJB3005 commented
![image](https://user-images.githubusercontent.com/8107459/37236822-02a5828e-240c-11e8-82bc-ce6c0570d21f.png)

Fun stuff.

2018-03-30 23:40 UTC, najarvis commented
Any idea how long until this fix will be implemented? Really was planning on using custom light shaders for our current project. Thanks!

2018-04-08 12:36 UTC, reduz requested changes

2018-04-08 12:36 UTC, reduz commented on drivers/gles3/shaders/canvas.glsl
> +#if defined(SHADOW_COLOR_USED)
I think if you pass a variable that was never used, the shader compiler will optimize it out, so this is probably unnecesary, just put the variable somewhere and dont use it

2018-04-09 11:56 UTC, PJB3005 commented
I'll squash the commits if this is good.

2018-04-13 11:26 UTC, reduz commented
i think it seems ok, feel free to squash

2018-04-18 11:31 UTC, merged

2018-04-28 14:04 UTC, hpvb commented
Cherry picked into 3.0.3