Add detail to doc for add_surface_from_arrays
godotengine/godot pull request #17911
Opened 2018-04-02 00:35 UTC by garyo

I'm no expert at this XML doc format, so please let me know if there are any formatting or content issues and I'll fix them.

2018-04-06 04:21 UTC, cbscribe requested changes
Thanks for your contribution. I've made some suggestions for clarity and to follow the docs guidelines.

2018-04-06 12:57 UTC, garyo commented
Updated per your comments, @cbscribe

2018-04-06 13:26 UTC, Noshyaar commented on doc/classes/ArrayMesh.xml
> +                Godot uses clockwise winding order for front faces of triangle primitive modes.
Indentation issue.

2018-04-06 13:27 UTC, Noshyaar commented on doc/classes/ArrayMesh.xml
> +
There should be no empty line. One line is one paragraph.

2018-04-06 13:49 UTC, garyo commented
Updated per your comments, @Noshyaar.

2018-04-22 13:23 UTC, merged

2018-04-29 12:37 UTC, hpvb commented
Cherry picked into 3.0.3