Add Navigation2D docs
godotengine/godot pull request #18071
Opened 2018-04-08 20:49 UTC by denisw

I have noticed that the API Reference had documentation for `Navigation`, but not `Navigation2D`. So I tried to use the former to add a class description and some method documentation to the latter. I hope everything is factually correct, especially the description of what the `optimize` parameter of `get_simple_path()` does.

2018-04-09 18:33 UTC, cbscribe requested changes
Thanks for your contribution!

I made a few changes and suggestions. Overall recommendation: avoid extra unnecessary addition of words (see what I did there?). It's a temptation because it makes the text feel more "technical" but this is a reference. Descriptions should be brief and to the point.

2018-04-09 18:33 UTC, cbscribe commented on doc/classes/Navigation2D.xml
> +		Node class that assists with 2D navigation and pathfinding.
Saying "Node class" is redundant, plus the most important information belongs at the front.  The brief description appears next to the name in context so you just need a few words to indicate the purpose. "2D navigation and pathfinding node."

2018-04-09 18:33 UTC, cbscribe commented on doc/classes/Navigation2D.xml
> +		The [code]Navigation2D[/code] class is used for navigation and pathfinding in the 2D space. By default it will automatically collect all child [code]NavigationPolygon[/code] resources, but they can
Don't put code tags around class names.

2018-04-09 18:33 UTC, cbscribe commented on doc/classes/Navigation2D.xml
> +				Determines the closest navigation point to the point passed and returns the owning [code]Object[/code] of the point's navigation polygon, usually a [code]NavigationPolygonInstance[/code]. If the
Other classes should be ref links: [Object] and [NavigationPolygonInstance]
Methods should be linked too: [method navpoly_add]

2018-04-09 18:33 UTC, cbscribe commented on doc/classes/Navigation2D.xml
> +				Calculates a path between two local-coordinate points and returns the result as a [code]PoolVector2Array[/code]. If the [code]optimize[/code] is [code]true[/code] (the default), string pulling wi
Remove "-" between local and coordinate.
If you mention [PoolVector2Array] it should be a link, although it's already listed above as the return value. 
Remove "the" before optimize
"smoothen" isnt' a word, change to "smooth"

Suggestion for first sentence:
Returns the path between two given points. Points are in local coordinate space.

2018-04-09 18:33 UTC, cbscribe commented on doc/classes/Navigation2D.xml
> +				Adds a [code]NavigationPolygon[/code] to the navigation node. Returns an ID that can be used to refer to the polygon when calling [code]navpoly_remove()[/code] or [code]navpoly_set_transform()[/c
" A [code]Transform2D[/code] that can be applied optionally applied to the polygon." - You used "applied" twice - remove the first one. Remove "that". 

Link objects and methods.

2018-04-09 18:33 UTC, cbscribe commented on doc/classes/Navigation2D.xml
> +				Removes the [code]NavigationPolygon[/code] with the passed ID from the navigation node.
"given" sounds better than "passed".

2018-04-09 18:33 UTC, cbscribe commented on doc/classes/Navigation2D.xml
> +				Returns the closest navigation point to the point passed. Both points are interpreted as relative to the navigation node's local coordinate system.
"to the point passed" -> "to the given point"

2018-04-09 18:33 UTC, cbscribe commented on doc/classes/Navigation2D.xml
> +				Sets the [code]Transform2D[/code] applied to the [code]NavigationPolygon[/code] with the passed ID.
Applies a transform to the [NavigationPolygon] with the given ID.

2018-04-09 18:44 UTC, denisw commented
@cbscribe Thank you for the thorough review! I agree with pretty much everything you said. I based my docs on the ones of `Navigation` which seems to validate several of the guidelines you gave here; I guess that needs some updating as well. 🙂 

I'll tweak the PR anddo a new push.

2018-04-09 18:47 UTC, cbscribe commented
Yeah, you have to be careful about using existing docs if they haven't been updated yet either.

If you're up for it, you can move your new descriptions over to `Navigation` as well. :)

2018-04-09 19:47 UTC, denisw commented
@cbscribe Done. Looking forward to your feedback. :)

2018-04-09 20:29 UTC, cbscribe approved these changes

2018-04-09 20:30 UTC, cbscribe commented
Looks great! Are you going to update navigation too? If so, you can add it to this PR. Otherwise this is ready to merge.

2018-04-09 20:32 UTC, denisw commented
Sure, I can do that!

2018-04-10 06:14 UTC, merged

2018-04-29 12:37 UTC, hpvb commented
Cherry picked into 3.0.3