Dummy texture importer
godotengine/godot pull request #18680
Opened 2018-05-07 13:40 UTC by Tugsav

Currently running a project in headless mode (binary built with p=server) causes a crash since the server platform does not have support for any kind of texture (which makes sense really).

This PR implements a dummy importer for textures in the server platform and allows for running a project in headless mode without crashing when loading scenes containing textured objects.

Also as a result decreases load time as no image files have to be loaded.

2018-05-08 07:47 UTC, Tugsav commented
@bojidar-bg Fixed both issues. good catch. I had forgotten all about that print statement

2018-05-08 23:32 UTC, hpvb requested changes

2018-05-08 23:32 UTC, hpvb commented on drivers/dummy/texture_loader_dummy.cpp
> +/*  texture_loader_pkm.cpp                                               */
This does not match the filename of the actual .cpp

2018-05-08 23:32 UTC, hpvb commented on drivers/dummy/texture_loader_dummy.h
> +/*  texture_loader_pkm.h                                                 */
This also doesn't match the filename

2018-05-09 06:15 UTC, Tugsav commented
@hpvb Fixed the copy paste errors, guess you guys now know what i used as a template to make this X)
Thanks for spotting it

2018-05-14 23:41 UTC, hpvb approved these changes

2018-05-15 08:27 UTC, merged

2018-05-15 08:27 UTC, akien-mga commented
Thanks a lot!

2019-07-03 08:24 UTC, akien-mga commented
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.