mono: Add Slerp method to vector classes, expose Cross for Vector2
godotengine/godot pull request #19063
Opened 2018-05-20 10:40 UTC by KellyThomas

and fix unnecessary casts in Basis

2018-05-21 20:24 UTC, aaronfranke requested changes

2018-05-22 00:32 UTC, KellyThomas commented on modules/mono/glue/cs_files/Vector2.cs
> +        public Vector2 Slerp(Vector2 b, float t)
Good call on the parameter type (changes made), but i'm inclined to stick to the `b`, `t` naming convention used for the other interpolation methods.

2018-05-22 20:31 UTC, aaronfranke approved these changes

2018-05-23 08:45 UTC, neikeq approved these changes

2018-05-25 07:44 UTC, merged

2018-06-01 16:05 UTC, hpvb commented
Cherry picked into 3.0.3