Fix onready vars / vars accessing class members if _ready / _init not present
godotengine/godot pull request #19637
Opened 2018-06-18 21:25 UTC by dragmz

Fixes #19548

**Please review**
I'm assuming that the condition was supposed to check for a static function only as per http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html:
"When a function is static it has no access to the instance member variables"

2018-06-18 21:29 UTC, akien-mga commented
Could you amend the commit log to be more explicit (`git commit --amend`)? A commit log should explain what the commit does in a human-readable way, independently of the issue tracker (in `git log` you don't have the data from GitHub), see https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind for details.

2018-06-18 21:33 UTC, karroffel commented on modules/gdscript/gdscript_compiler.cpp
> +	if (codegen.function_node && codegen.function_node->_static)
Not exactly sure what the context of this method is, but this doesn't return `false` when `codegen.function_node` is `NULL` anymore while previously it did.

Not sure how important that is, if at all.

2018-06-18 21:33 UTC, vnen commented
I don't think this is the right fix. I was investigating this right now and the problem is that the `_static` field is never set if it does not have an actual function in the code (i.e. it's generated by the compiler).

2018-06-18 21:37 UTC, vnen requested changes
The right fix would be to set the `_static` value even if the `_parse_function` is called with `NULL` (in this case it should be set to `false`).

Should be around here: https://github.com/godotengine/godot/blob/08c6cc668ac98773827d5007783f0b1ac29fd179/modules/gdscript/gdscript_compiler.cpp#L1490-L1493

2018-06-18 21:58 UTC, dragmz commented
I'm not sure how setting _static = false helps here as the function_node is still NULL if _ready func is missing.

2018-06-19 00:05 UTC, vnen commented
@dragmz true. Now I realize that **both** changes are needed. Because currently it's filling the `_static` field with garbage because it's never set (and the `rpc_mode` too).

But this PR is okay. The null check is not important because it's not accessed later.

2018-06-19 00:06 UTC, vnen approved these changes

2018-07-05 02:15 UTC, merged

2019-07-03 10:22 UTC, akien-mga commented
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.