Unified button mask behavior across platforms
godotengine/godot pull request #20063
Opened 2018-07-09 11:46 UTC by moiman100

Before on linux InputEvent would report button mask like this (pseudo)
InputEventMouseButton button_index=x **is_pressed=true** button_mask=**0**
InputEventMouseButton button_index=x **is_pressed=false** button_mask=**button_mask_x**

On all other platforms button mask is reported like this
InputEventMouseButton button_index=x **is_pressed=true** button_mask=**button_mask_x**
InputEventMouseButton button_index=x **is_pressed=false** button_mask=**0**

After this commit linux reports it like other platforms.

Before on linux InputEvent reported button mask for mouse wheel buttons, while other platforms didn't.
After this commit InputEvent reports mouse wheel button mask on all platforms.

Also someone should probably check horizontal mouse wheel buttons, because I don't have a mouse with tilting wheel. For example Logitech m705 has all supported functionality.

**NOTE: OSX is NOT tested because I don't have a mac.**
NOTE 2: os_windows.cpp diff looks really messy in GitHub because I removed an unnecessary indentation.
It looks fine, when comparing the files using something decent like KDiff3.

2018-07-09 12:37 UTC, leonkrause requested changes
Logic for HTML5 is good, but please keep the mentioned comment separate and remove the redundant call.

2018-07-09 12:37 UTC, eska014 commented on platform/javascript/os_javascript.cpp
> +	ev->set_button_mask(mask);
`set_button_mask` is already called once in line 229, remove that original invocation since we're calling it here.

2018-07-09 12:37 UTC, eska014 commented on platform/javascript/os_javascript.cpp
> +	ev->set_button_mask(mask);
I don't feel the `mask` variable helps readability, just this would be clearer:

    ev->set_button_mask(ev->get_button_mask() & ~button_flag);

2018-07-09 13:29 UTC, moiman100 commented
Made requested changes

2018-07-09 20:16 UTC, leonkrause approved these changes

2018-07-10 15:13 UTC, moiman100 commented
resolved conflicts

2018-12-14 22:31 UTC, akien-mga commented
Sorry for the delay. More testing from users and contributors would be nice to ensure that no regressions happen, but I guess this will be best done once in the master branch :)

2018-12-14 22:31 UTC, merged