mono: add constants to transform and vector structs
godotengine/godot pull request #20901
Opened 2018-08-11 01:09 UTC by KellyThomas

**What this does:**

This PR brings the constants offered by `Transform`, `Transform2D`, `Vector2` and `Vector3` into line with GDScript changes in #14704

For the vectors I have opted for `Inf` over `Infinity` to match the `Mathf` property, I am happy to change this if the full name is preferred.

This swaps the values of `Vector2.Up`/`Vector2.Down`, so that they match the new GDScript implementation.

**What this doesn't do:**

I was unable add `X`, `Y`, or `Z` to `Plane1 as it conflicts with existing instance properties.

I was unable to add `BackCircle`, `WhiteCircle`, `BlackDiamond`, or `WhiteDiamond` to `StringExtensions` due to lac of support to static extension properties.

I haven't looked at the named colors.

2018-08-11 04:24 UTC, aaronfranke approved these changes
One nitpicky thing but otherwise it all looks good to me. :+1:

2018-08-11 07:47 UTC, KellyThomas commented on modules/mono/glue/cs_files/VERSION.txt
> +9
Yeah, that was probably a bit optimistic of me.

I've changed this back to 8 for now.

2018-08-13 19:32 UTC, akien-mga commented
CC @neikeq

2018-08-14 16:22 UTC, neikeq requested changes

2018-08-14 18:11 UTC, KellyThomas commented
Thanks, I've removed all alignment beyond the line indents.  It should be clean now.

2018-08-14 18:20 UTC, neikeq approved these changes

2018-08-14 18:21 UTC, merged

2019-07-03 08:45 UTC, akien-mga commented
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.