Doc Tabcontainer rearrange tabs
godotengine/godot pull request #23009
Opened 2018-10-14 14:02 UTC by AlexHolly

2018-10-14 17:34 UTC, mhilbrunner requested changes

2018-10-14 17:34 UTC, mhilbrunner commented on doc/classes/TabContainer.xml
> +			if [code]true[/code], tabs can be rearranged with mouse drag.
Capitalize `if`.

2018-10-16 12:35 UTC, merged

2018-10-16 12:35 UTC, akien-mga commented
Thanks.

2018-10-31 10:40 UTC, akien-mga commented
Cherry-picked for 3.0.7.