[WIP] Ensure mouse is visible on destroying editor_spin_slider
godotengine/godot pull request #23563
Opened 2018-11-07 09:42 UTC by RySchmitt

This is a partial fix to a bug where the mouse becomes invisible when dragging to change the size of a DynamicFont. The behavior is still undesirable since changing the font size by one will move the mouse to the center of the window and the selection loses focus. There are likely other bugs caused by the same underlying issue. The issue is that when the size of DynamicFont is changed, the settings fields are destroyed and recreated. If the mouse is still hidden, it currently remains hidden regardless of user input.

For a demonstration, see #22581.

Using a destructor to solve this is likely the wrong approach, so I welcome input.

2018-11-09 04:51 UTC, RySchmitt commented
I took a further look at this. I am working on a fix to the underlying problem, but I think that either this should be pushed or we need to ensure that a focus lost event is fired before a UI object is destroyed.

2018-12-14 17:37 UTC, reduz requested changes

2018-12-14 17:37 UTC, reduz commented on editor/editor_spin_slider.cpp
> +	if (grabbing_spinner) {
this should probably better be in NOTIFICATION_EXIT_TREE, other than that it' s fine.

2018-12-16 22:36 UTC, akien-mga commented
I've pushed 74bf67c as a fix based on @reduz's feedback. Thanks for the contribution nevertheless!

2018-12-16 22:36 UTC, closed without merging