modified .import to .cache for project files
godotengine/godot pull request #23602
Opened 2018-11-08 21:10 UTC by ERUD1T3

Fixes ambiguity raised in issue #23368. However, it is not yet backward compatible. I will be working on making it able to recognize both .cache and .import folders in the user-created project directory.

2018-11-09 01:57 UTC, LikeLakers2 commented on CHANGELOG.md
> +  - Imported assets are now cached in a `.cache` directory, making distribution and versioning easier.
We shouldn't be editing the 3.0 changelog. 3.0's already been released.

2018-12-04 00:13 UTC, ERUD1T3 commented
added F8 shortcut to activate/deactivate plugin

2018-12-05 14:07 UTC, vnen commented
I don't like the name `.cache`, because it does not describe what the folder really is. I would call it `.imported` or something.

2018-12-05 14:12 UTC, Zireael07 commented
@vnen: .imported and the like means back to the ambiguity this means to solve.

2018-12-05 14:22 UTC, asheraryam commented
The names `.import_cache` or `.importcache ` might be great.

2018-12-05 14:44 UTC, akien-mga commented
Personally I don't think it's worth breaking compat for what is IMO not a big issue. Maybe for 4.0, but not for 3.1 nor 3.2.

2018-12-05 14:44 UTC, akien-mga commented
This PR also has completely unrelated commits that should be moved to their own PRs.

2018-12-05 23:12 UTC, ERUD1T3 commented
Sorry for the combined PRs, still figuring out pull request mechanics. I will separate them as asked. I will also try to change to .import_cache. Thanks again for the feedback

2018-12-05 23:14 UTC, vnen commented
> .imported and the like means back to the ambiguity this means to solve.

I disagree. The issue is that the names are exactly the same. If they are different, even by a small amount, it's clearer which one are you talking about when discussing. Also not confusing for `.gitignore`.

2018-12-08 23:58 UTC, aaronfranke commented
I don't see why `.cache` is an unsuitable name. These files are regeneratable without problems from other existing files, they are basically Godot's working cache of them.

2020-04-01 08:43 UTC, aaronfranke requested changes

2020-04-01 08:43 UTC, aaronfranke commented on CONTRIBUTING.md
> +  that several users will need in their real-life projects.
These are unrelated changes and shouldn't be in this PR.

2020-05-13 07:00 UTC, aaronfranke commented
Closing because:

* Git history is a mess.

* No response from the author for over a year.

* Superceded by #38607

2020-05-13 07:00 UTC, closed without merging