Introduce `OS.set_drag_mode()` rebase
godotengine/godot pull request #23972
Opened 2018-11-25 22:19 UTC by toger5

same as #16512 but rebased.

2018-11-26 10:20 UTC, akien-mga commented
Could you squash the commits together?

Note also that it fails building on OSX: https://travis-ci.org/godotengine/godot/jobs/459525810
And there are style issues: https://travis-ci.org/godotengine/godot/jobs/459525806

2018-11-26 10:22 UTC, toger5 commented
@akien-mga
Couldn't bild on mac myself yesterday so i let travis do it.
I will look into it and squash.

2018-11-26 11:14 UTC, toger5 commented
@akien-mga fixed the OS X issue and rebased

2019-01-06 11:59 UTC, Nobelix commented
What's the status of this?

2019-01-11 12:45 UTC, toger5 commented
confilcts :( ... no time right now. might check it this weekend

2019-02-18 18:34 UTC, bruvzg requested changes
On Windows resize is a bit laggy (but same is true for normal Godot window resize).
On Linux/X11 resize lags massively, leave dirty traces and sometimes blinks during resize (it's much more noticeable with transparent window, but happens win non transparent too).

2019-02-18 18:34 UTC, bruvzg commented on platform/osx/os_osx.mm
> +		OS_OSX::singleton->set_window_maximized(!OS_OSX::singleton->is_window_maximized());
On macOS double-clicking window title should minimize window not maximize, and there's nothing like this implemented on other platforms.

2019-02-18 18:34 UTC, bruvzg commented on platform/windows/os_windows.cpp
> +				case DRAG_MODE_NONE: return HTCLIENT;
`DRAG_MODE_NONE` / `default` should return `DefWindowProcW(hWnd, uMsg, wParam, lParam);` instead, returning `HTCLIENT` will break resizing of normal (non-borderless) windows.

2019-02-18 18:34 UTC, bruvzg commented on platform/osx/os_osx.mm
> +		OS_OSX::singleton->set_window_maximized(!OS_OSX::singleton->is_window_maximized());
On macOS double clicking should minimize window not maximize and this function is not implemented on any other platforms.

2019-02-18 18:46 UTC, bruvzg commented
And another problem, it's possible to resize borderless window to zero size and render it unusable.
Currently there's no way to prevent it (set minimum size limit or process and reject resize events). Ability to set size limits would be useful for normal windows as well.

2019-10-04 14:40 UTC, akien-mga commented
There are quite a few outstanding issues that still need to be addressed.

2019-10-06 22:51 UTC, toger5 commented
Not sure if i find time for it currently. Maybe someone else need to take care of it.

2020-05-13 07:26 UTC, aaronfranke commented
@toger5 Is this still desired? If so, this feature would probably need to be redone from scratch, considering the OS and DisplayServer split.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable). I see that above you say that you may not have time for this, if you can't fix this up yourself, feel free to close it.

2020-05-23 12:59 UTC, toger5 commented
I guess we close this one. It is not that propable that I will work on this commit. I think a lot it did was fixing issues with the old system. 
It should be redone and the PR can be used as a resource for the person who looks into this.

So I will close for now.

2020-05-23 12:59 UTC, closed without merging