Improve documentation of Control.
godotengine/godot pull request #24608
Opened 2018-12-26 15:24 UTC by PJB3005

2018-12-26 16:40 UTC, groud commented
The content of the changes are good in general. But I am not sure about the wording. 
Maybe someone from the documentation team could have a look ? @NathanLovato ?

2018-12-27 02:02 UTC, NathanLovato requested changes
Thanks for your work! This needed some update. There´s almost never a need for parentheses in docs writing. They create nested sentences and make the content harder to read. Use a short sentence or a proposition instead.

2018-12-27 02:02 UTC, NathanLovato commented on doc/classes/Control.xml
> +			The control will receive mouse button input events through [method _gui_input] if clicked on. If this control does not handle the event, the parent control (if any) will be considered for a mouse
Remove the parentheses.

2019-01-04 16:54 UTC, akien-mga commented
> This needed some update. There´s almost never a need for parentheses in docs writing. They create nested sentences and make the content harder to read. Use a short sentence or a proposition instead.

Bump :)

2019-01-06 12:15 UTC, merged

2019-01-06 12:15 UTC, akien-mga commented
Thanks!