Sender network id is now set to local network id for local rpc calls.
godotengine/godot pull request #24951
Opened 2019-01-12 18:37 UTC by Mr-Slurpy

I don't know if this is by design but I think this is a bug. When an rpc calls a function locally, it doesn't set the rpc sender id to the local id. This should be there so that the rpc function can know if the caller is from the network or sent locally.
```
func sender():
	rpc("reciever")

master func master():
	if multiplayer.get_rpc_sender_id() != 1:
		# do something if caller was not server...
```
In the example above, sender id is only set if the rpc did not come from the server.

2019-03-26 13:11 UTC, Dragoncraft89 commented
This would solve issue #27332 
You should add that to your description

2019-04-08 15:51 UTC, Faless requested changes
I've been a bit dubious about this (because it's then "harder" to differentiate the two), but given the high demand from users, I believe this is okay to merge. One thing though, it needs to be done for RSET too:
```diff
diff --git a/core/io/multiplayer_api.cpp b/core/io/multiplayer_api.cpp
index 86382939f..cfc544eb4 100644
--- a/core/io/multiplayer_api.cpp
+++ b/core/io/multiplayer_api.cpp
@@ -708,7 +714,11 @@ void MultiplayerAPI::rsetp(Node *p_node, int p_peer_id, bool p_unreliable, const
 
 		if (set_local) {
 			bool valid;
+			int temp_id = rpc_sender_id;
+
+			rpc_sender_id = get_network_unique_id();
 			p_node->set(p_property, p_value, &valid);
+			rpc_sender_id = temp_id;
 
 			if (!valid) {
 				String error = "rset() aborted in local set, property not found:  - " + String(p_property);
@@ -718,12 +728,14 @@ void MultiplayerAPI::rsetp(Node *p_node, int p_peer_id, bool p_unreliable, const
 		} else if (p_node->get_script_instance()) {
 			// Attempt with script.
 			RPCMode rpc_mode = p_node->get_script_instance()->get_rset_mode(p_property);
-
 			set_local = _should_call_local(rpc_mode, is_master, skip_rset);
 
 			if (set_local) {
+				int temp_id = rpc_sender_id;
 
+				rpc_sender_id = get_network_unique_id();
 				bool valid = p_node->get_script_instance()->set(p_property, p_value);
+				rpc_sender_id = temp_id;
 
 				if (!valid) {
 					String error = "rset() aborted in local script set, property not found:  - " + String(p_property);
```

2019-04-08 16:07 UTC, Faless commented
P.S.: @Mr-Slurpy I'm sorry this took so long to review :pray: , I was busy and had some doubts at the time. Then then kinda forgot :crying_cat_face: .

2019-04-17 02:01 UTC, Mr-Slurpy commented
Ok, I made the changes you requested.

2019-04-20 11:38 UTC, Faless approved these changes
Good job! Thanks!

2019-04-20 11:39 UTC, merged

2019-04-20 11:39 UTC, Faless commented
Thank you for your contribution!