[DOCS] rephrased impulse
godotengine/godot pull request #25412
Opened 2019-01-28 11:47 UTC by toger5

- improove coordinate system explanation
 - define usecase
@wmww can u review?

2019-01-28 15:36 UTC, cbscribe requested changes
Spelling and grammar corrections

2019-01-28 15:36 UTC, cbscribe commented on doc/classes/PhysicsDirectBodyState.xml
> +				Applies a positioned impulse to the body. An impulse is time independant! Applying an impulse every frame would result in a framerate dependant force. Thats why it should only be used, when simul
"independent" and "dependent" are spelled wrong.
 > Thats why it should only be used, when simulating one-time impacts

"Thats (sic) why" -> "For this reason,"
Remove the comma after "used"

2019-01-28 19:43 UTC, wmww commented
@toger5 Thanks for PRing this! I sure wasn't going to.

How about this:

> Applies a positioned impulse to the body. The force applied is not dependent on physics FPS, so instead of applying an impulse each frame, you should probably use [method add_force] instead. The position uses the rotation of the global coordinate system, but is centered at the object's origin.

2019-01-29 11:59 UTC, toger5 commented
@wmww I kind of want to mention that it is supposed to be used for one time impacts.
ill change that part to ur version for sure though:
> The position uses the rotation of the global coordinate system, but is centered at the object's origin.

2019-01-29 12:07 UTC, toger5 commented
updated.
any further changes requested?

2019-02-10 11:56 UTC, merged

2019-02-10 11:56 UTC, akien-mga commented
Thanks!