UndoRedo add version changed signal
godotengine/godot pull request #25863
Opened 2019-02-14 00:53 UTC by AlexHolly

added some functions to manage undo buttons

2019-05-29 14:11 UTC, akien-mga commented
Sorry for the delay.

Could you be more specific about the use case so that we can assess whether it's a good addition to the API?

2019-06-20 09:58 UTC, akien-mga commented
Alright, seems sensible. Could you rebase and add documentation for the new methods and signal?

2019-06-20 10:04 UTC, akien-mga approved these changes
OK to merge, pending rebase.

2019-06-26 10:11 UTC, akien-mga commented
> Could you rebase and add documentation for the new methods and signal?

Bump.

2019-06-26 14:03 UTC, akien-mga commented on doc/classes/UndoRedo.xml
> +      <signals>
Indentation is wrong, you can run `godot --doctool .` to make sure that your template is properly formatted (should also fix the extra newline added at the end of the file).

2019-06-26 14:03 UTC, akien-mga commented on doc/classes/UndoRedo.xml
> +			   <description>
This should be documented too.

2019-06-26 14:04 UTC, AlexHolly commented
Any idea why `./bin/godot.x11.tools.64 --doctool .` is removing many descriptions?

2019-06-26 14:09 UTC, akien-mga requested changes

2019-06-26 14:09 UTC, akien-mga commented on doc/classes/UndoRedo.xml
> -			Makes [code]do[/code]/[code]undo[/code] operations stay in separate actions.
Those shouldn't be removed, something wrong happened.

2019-06-26 14:09 UTC, akien-mga commented on doc/classes/UndoRedo.xml
> +				returns true if redo available.
Sentences start with a capital letter...
Please also style "true" as `[code]true[/code]` as done in the rest of the doc.

2019-06-26 14:09 UTC, akien-mga commented on doc/classes/UndoRedo.xml
> +				returns true if redo available.
Maybe be a bit more verbose too, e.g. "Returns [code]true[/code] if a 'redo' action is available, which means that one or more recent actions have been undone and could be reapplied."

2019-06-26 14:09 UTC, akien-mga commented on doc/classes/UndoRedo.xml
> +				returns true if undo available.
Same thing about capital letter and `[code]true[/code]`.

I'd suggest "Returns [code]true[/code] if an 'undo' action is available."

2019-06-26 14:10 UTC, akien-mga commented
> Any idea why ./bin/godot.x11.tools.64 --doctool . is removing many descriptions?

Did you compile Godot from this branch? It might be that you have a very old Godot build with no support for constant descriptions, which thus removes them.

2019-06-26 14:35 UTC, AlexHolly commented
You are right something was too old, solved it with `git clean -fdx`.

2019-06-26 20:54 UTC, akien-mga approved these changes

2019-06-26 20:56 UTC, merged

2019-06-26 20:56 UTC, akien-mga commented
Thanks!