Allow Selection of Collision Shapes with the Mouse
godotengine/godot pull request #26438
Opened 2019-03-01 11:58 UTC by AlmostBearded

Allows selecting collision shapes via mouse input in the new tileset editor.

During implementation, I added 2 new methods to keep the select_coord method a little smaller and refactored it a bit.

![](https://thumbs.gfycat.com/HonorableTepidAzurewingedmagpie-size_restricted.gif)

Should resolve #26369

2019-04-05 02:06 UTC, MarianoGnu approved these changes

2019-04-05 02:08 UTC, MarianoGnu requested changes
Please resolve conflicts and rebase the PR

2019-04-08 17:25 UTC, AlmostBearded commented
@MarianoGnu wasn't this PR obsoleted by https://github.com/godotengine/godot/pull/26385 ?

2019-04-30 11:26 UTC, akien-mga commented
Superseded by #26385.

2019-05-07 12:01 UTC, MarianoGnu commented
@AlmostBearded @akien-mga actually no, #26385 adds a way to select collision shapes using keyboard or a tool button, this PR adds the ability to also select them with the mouse, clicking on them. Unless this has been added on another PR that i dont know of, that's still not possible.

2019-05-30 09:46 UTC, AlmostBearded commented
Sorry I was pretty busy in the last couple of weeks. I had a quick look at it right now and i think I'll have to redo quite a bit of my stuff to get it working properly. My initial PR was also quite hacky because I just selected collision shapes that with the center closest to the mouse which lead to some pretty annoying selection scenarios. 

For when I redo my code: Does anybody know of a way to check if a position (mouse position) lies within a shape? I browsed the source back then and i couldn't find anything that's why i went with the shape center solution.

2019-06-20 09:38 UTC, akien-mga commented
I'll close this PR for now given that it needs a major rework as per the above comment. The reworked version will likely get better visibility as a new PR :)

2019-06-20 09:38 UTC, closed without merging