Initial WebRTC support
godotengine/godot pull request #26792
Opened 2019-03-08 14:00 UTC by Faless

This PR is the result of the joint effort of me and @brandonmakin during last GSoC.
Sadly, due to build issues and size, non-HTML5 support (on which @brandonmakin worked hard last summer) will be delegated to a GDNative plugin (and which will soon be available here https://github.com/godotengine/webrtc-native/ ).
This PR do not yet include the high level multiplayer peer (which might be added to this PR in a future commit as soon as we stabilize it a bit).

This will, of course, will all come in `3.2`.

2019-04-04 20:06 UTC, reduz commented
up to you, @akien-mga

2019-04-11 13:45 UTC, akien-mga commented
Looks good to me, but @karroffel might want to check the GDNative changes and @eska014 have a look at the JS integration.

2019-04-11 14:18 UTC, Faless commented
There's one little change I need to push (will do later today), to allow compiling with `module_gdnative_enabled=no`. Plus I have to remove the google demo stun server leftover from JS :-/

2019-04-11 14:21 UTC, Faless commented
@eska014 have a look at: https://github.com/godotengine/godot/pull/26792/files#diff-8cd4b6695db965b42410d87a3c6069d9 , maybe we can reuse it for XMLHTTPRequests too? I saw you had something similar using an array.

2019-04-11 16:01 UTC, karroffel requested changes

2019-04-11 16:01 UTC, karroffel commented on modules/gdnative/gdnative_api.json
> +          "name": "godot_net_bind_webrtc_peer",
This technically does not break binary compatibility, but the API struct for this extension will be "valid" even with Godot versions where this function does not exist.

So this should be in the "next" extension of the "NET" extension.

2019-04-15 17:57 UTC, merged

2019-04-15 17:57 UTC, akien-mga commented
Thanks!