Allow to undo TextEdit.set_text
godotengine/godot pull request #26809
Opened 2019-03-09 00:39 UTC by KoBeWi

Closes #20691

With this, `set_text()` is registered as "complex operation" for undo if undo is enabled, so after doing e.g. `$TextEdit.text = "some text"` you can return to previous text with CTRL + Z. It might be considered a minor compatibility breakage, since you need to call `clear_undo_history()` after setting text to keep old behavior. Also cursor moves to the end of the text now, instead of going to beginning after changing text (that change is rather debatable). 

I also cleaned `set_text()` a bit, as it was doing many unnecessary operations already done in `_clear()`.

2019-04-15 16:41 UTC, KoBeWi commented
I thought that with this change it will be trivial to fix #26325, so I wanted to make another PR. But seems like this change is actually remove-one-line-trivial, thus I made an update and added it here.

2019-05-12 18:31 UTC, Paulb23 requested changes
Spotted a couple of issues: 

If undo is not enabled the cursor will be set to the start of the line, as compared to the end.
If undo is enabled the selection is still active.

2019-05-13 21:15 UTC, KoBeWi commented
> If undo is not enabled the cursor will be set to the start of the line, as compared to the end.

But this is how it works originally. Should I change it?

> If undo is enabled the selection is still active.

Fixed.

2019-05-14 19:36 UTC, Paulb23 commented
> But this is how it works originally. Should I change it?

Yeah, it's better to be consistent, and as you mentioned, it's a harmless change.

2019-05-14 20:06 UTC, KoBeWi commented
Ok, done.

2019-05-16 20:48 UTC, Paulb23 approved these changes
LGTM.

Might be an idea to also apply the `reload_text` fix to `text_editor` as well. No need to worry about the shader editor, as it doesn't have this functionality.

2019-05-16 21:07 UTC, KoBeWi commented
>Might be an idea to also apply the reload_text fix to text_editor as well.

Done.

2019-05-20 20:00 UTC, merged

2019-05-20 20:00 UTC, akien-mga commented
Thanks!