Support UTF-8 in TextEdit and LineEdit navigation
godotengine/godot pull request #26848
Opened 2019-03-09 19:13 UTC by ptrojahn

This allows jumps over whole non ASCII words with Ctrl+Left/Right in
a LineEdit or TextEdit.
Fixes #25681

2019-05-26 14:19 UTC, Paulb23 requested changes
Underscores need to be treated as a edge case as they are a `text_char` whereas this will return false.

2019-06-03 14:21 UTC, ptrojahn commented
But this is `!is_symbol`. `is_symbol` has `c != '_'`.

2019-06-03 20:21 UTC, Paulb23 approved these changes
My bad! In that case it LGTM.

Also this should now close #28850

2019-06-03 20:28 UTC, merged

2019-06-03 20:28 UTC, akien-mga commented
Thanks!

2019-08-21 10:08 UTC, akien-mga commented
Cherry-picked for 3.1.2.