fixed an access after free in OS_X11::set_context.
godotengine/godot pull request #26961
Opened 2019-03-12 13:18 UTC by ibrahn

Added constructor and assignment operator for CharString
from const char* to simplify memory management when working with
utf8/ascii strings for APIs taking char*.
Reworked OS_X11::set_context to use CharString and avoid some manual
memory management.

2019-03-12 13:19 UTC, akien-mga commented
That's good but too involved for 3.1 (we're already building RC3 which should be the last RC, so I can't get this tested). For 3.1 I'd prefer the simple hotfix I suggested on that commit.

2019-03-12 13:21 UTC, ibrahn commented
Not sure if modifying and using CharString in this way is the right thing to do.
Any opinions/review on this very welcome

2019-03-12 13:46 UTC, ibrahn commented
Low impact quick-fix for release candidate at #26962

2019-04-22 11:18 UTC, hpvb requested changes
Overal this looks good apart from some small changes.

2019-04-22 11:18 UTC, hpvb commented on core/ustring.cpp
> +	char *dst = this->ptrw();
this-> is not required here

2019-04-22 11:18 UTC, hpvb commented on core/ustring.cpp
> +	const char *ptr = p_cstr;
Can we just use strlen() here?

2019-04-22 11:18 UTC, hpvb commented on core/ustring.cpp
> +	for (int i = 0; i < len + 1; i++) {
Maybe just use memcpy() or strcpy() here

2019-04-22 19:21 UTC, ibrahn commented
Updated with @hpvp recommendations and rebased

2019-04-23 03:14 UTC, merged

2019-04-23 03:14 UTC, hpvb commented
Thanks!

2019-11-12 10:05 UTC, akien-mga commented
Removing cherry-pick label, we already have a valid fix in #26962 so there's no strong need to cherry-pick this.