Fixes #27004 Updated editor_settings.cpp for current line colour
godotengine/godot pull request #27097
Opened 2019-03-15 15:37 UTC by siddharth952

Fixes #27004

Changed default current line colour to yellow, such that user is able to distinguish between the lines when using Find And Replace.

2019-03-15 15:40 UTC, volzhs commented
does this make current line noticeable with **Light theme** also?

2019-03-15 15:50 UTC, siddharth952 commented
@volzhs Yes.

2019-03-15 16:41 UTC, groud commented
Could you provide a screenshot please ?

2019-03-15 16:54 UTC, piyushdagar commented
It will not work if the search results are in the same line. You should have also changed the search_result_border_color.

2019-03-15 17:17 UTC, siddharth952 commented
@piyushdagar  Yeah, thats right cause this causes current line colour to be yellow while editing the text.

Making changes to search_result_border_color

2019-03-15 17:20 UTC, piyushdagar commented
Also reduce alpha of search_result_color (to maybe 0.3)

2019-03-15 17:45 UTC, siddharth952 commented
![Screenshot 2019-03-15 at 11 14 58 PM](https://user-images.githubusercontent.com/40488679/54451176-3b6a9880-4778-11e9-942b-e91e8eeccb17.png)

2019-03-17 09:12 UTC, bojidar-bg commented on doc/classes/TextEdit.xml
> +			Adjust [code]Vertical[/code] Scroll Sensitivity of Text Editor.
Move the old documentation to `wrap_enabled`.

2019-03-17 09:12 UTC, bojidar-bg commented on editor/editor_settings.cpp
> +	_initial_set("text_editor/highlighting/search_result_border_color", Color(255, 255, 0, 0.5));
Color() uses numbers in the range 0..1, not 0..255.

2019-04-01 08:50 UTC, akien-mga commented on doc/classes/TextEdit.xml
> +            If [code]true[/code], enables text wrapping when it goes beyond the edge of what is visible.
Wrong indentation, should use tabs.

2019-04-01 08:51 UTC, akien-mga commented on doc/classes/TextEdit.xml
>  			Adjust [code]Vertical[/code] Scroll Sensitivity of Text Editor.
There's no reason to use Title Capitalization here. Also no reason to make "Vertical" inline code as it's not a code identifier. "Vertical scroll sensitivity." would be fine.

2019-04-01 08:52 UTC, akien-mga commented
Please squash the three commits together and fix the pending comments.
For future PRs, please make one specific PR for each change, default color of the search border and TextEdit documentation fixes are not related.

2019-04-02 14:59 UTC, siddharth952 commented
@akien-mga Yes I did try, there seems to be a problem with the branch I'll sort it out within 1-2 days

2019-04-08 13:58 UTC, siddharth952 commented
@akien-mga Should I close this pull and request two new pull requests? I have some problem with my fork I was working with the Collaboration feature for GSoC and by mistake it was reflected on this branch.

Sorry for the inconvenience caused will be avoided on future PRs.

2019-04-08 14:51 UTC, akien-mga commented
> Should I close this pull and request two new pull requests? I have some problem with my fork I was working with the Collaboration feature for GSoC and by mistake it was reflected on this branch.

If you want yes. Otherwise you can force push an update to this PR's branch to make it have only one relevant commit, and open another PR for the other change.

2019-04-12 12:12 UTC, siddharth952 commented
@akien-mga I have updated the PR and made a separate PR for the other issue.

2019-04-30 17:47 UTC, Calinou requested changes
I suggest using `Color(0.41, 0.61, 0.91, 0.38)` for a more subtle appearance of non-selected matches:

![search_border_dark](https://user-images.githubusercontent.com/180032/56982118-d1b81980-6b80-11e9-9f6d-06f7dbe09894.png)

![search_border_light](https://user-images.githubusercontent.com/180032/56982119-d1b81980-6b80-11e9-8563-546548653a36.png)

Also, this only changes the default color for the **Default** text editor theme, not the **Adaptive** one. The same color should be applied in both themes, so please copy the color there too: https://github.com/godotengine/godot/blob/7de83375eaab725e064aceed9a803f3826cd870b/editor/editor_themes.cpp#L1155

2019-05-01 17:54 UTC, siddharth952 commented
@Calinou 
We are modifying the value of text_editor/highlighting/search_result_border_color to be (0.41, 0.61, 0.91, 0.38) so if we use,

set_initial_value("text_editor/highlighting/search_result_border_color", search_result_border_color, true)

in Adaptive will it not copy the color values we set in _initial_set?

2019-05-01 18:00 UTC, Calinou commented
@siddharth952 The `_initial_set` only affects the Default theme, not the Adaptive theme.

2019-05-01 18:15 UTC, siddharth952 commented
So to set the color value for the Adaptive theme we replace with the following ?

set_initial_value("text_editor/highlighting/search_result_border_color",Color(0.41, 0.61, 0.91, 0.38) , true);

2019-05-01 18:16 UTC, siddharth952 commented
> So to set the color value for the Adaptive theme we replace with the following ?
> 
> set_initial_value("text_editor/highlighting/search_result_border_color",Color(0.41, 0.61, 0.91, 0.38) , true);

@Calinou

2019-05-01 18:24 UTC, Calinou commented
@siddharth952 Yes, make sure to remove the variable above which will become unused (and add a space after the `,` to respect the established code style).

2019-05-02 13:11 UTC, Calinou approved these changes

2019-05-16 21:17 UTC, merged

2019-05-16 21:33 UTC, mhilbrunner commented
Merged. Thanks for your contribution, and thanks for the effort in incorporating our feedback!