Fix focus for TextEdit and LineEdit when certain input keys are triggered
godotengine/godot pull request #27118
Opened 2019-03-16 10:56 UTC by ElGatoNinja

now text_edit and line_edit modules release the focus under certain conditions when KEY_UP,DOWN,RIGHT or LEFT is triggered
_Bugsquad edit:_ Fix #27036

2019-05-14 20:00 UTC, Paulb23 requested changes
I don't think this is the correct way to solve this.

For exiting out of text controls, I've seen:
1) `Tab` / `Shift+tab` is not handled by the control however, switches focus.
2) Have two modes, selection and active. In this example it will enter selection mode by default, here the control border is highlighted. Focus navigation is as normal. When the action button is pressed, the control enters active mode. Here it captures text input. Then by pressing the back action it goes into selection mode again. 
3) A different shortcut to switch focus.

2019-06-19 13:29 UTC, akien-mga commented
Closing for now as it doesn't appear to be the right approach to solve this issue. I copied relevant info to #27036 for future attempts at solving it.

2019-06-19 13:29 UTC, closed without merging

2022-07-16 20:58 UTC, Shadowblitz16 commented
@akien-mga please reopen this, exiting with up, left down, and right is useful for keyboard/gamepad ui
Gamepad doesn't have tab or shift and it may not be viable on keyboard if your not going for pc style keyboard focus and instead gameconsole style focus.

2022-07-16 21:11 UTC, bruvzg commented
It should be enough to remove ` || k->get_keycode() == Key::TAB` from this line - [text_edit.cpp#L2131](https://github.com/godotengine/godot/blob/1137948015e28049699a4a040ceb78d01593372b/scene/gui/text_edit.cpp#L2131), it's not doing anything since Unicode value for the Tab is zero, just consuming an event when it should not.

2022-07-16 21:19 UTC, bruvzg commented
> Gamepad doesn't have tab or shift and it may not be viable on keyboard if your not going for pc style keyboard focus and instead gameconsole style focus.

I guess it is a valid use case, but probably it should be an option disabled by default, since it's not an expected behavior on desktop platforms.

2022-07-17 04:56 UTC, Shadowblitz16 commented
> > Gamepad doesn't have tab or shift and it may not be viable on keyboard if your not going for pc style keyboard focus and instead gameconsole style focus.
> 
> I guess it is a valid use case, but probably it should be an option disabled by default, since it's not an expected behavior on desktop platforms.

There could just be a focus style options, the options could be...
None,
Cardinal,
Desktop,
Both,