Allow adding disabled shapes
godotengine/godot pull request #27371
Opened 2019-03-24 09:50 UTC by ShyRed

This pull requests extends the `area_add_shape` and `body_add_shape` methods with a new optional parameter `p_disabled`. Using the parameter the caller can tell the physics engine to add the shape in a disabled state directly.

Before, a shape has always been assumed to be enabled and had to be disabled in an extra step. Since `CollisionObject2DSW::add_shape` always calls `_update_shapes()` this resulted in unnecessary calculations done for shapes that were going to be removed from physics anyways.

This change fixes #17812 and can be tested with the project provided in said issue.

2019-03-24 11:25 UTC, Xrayez commented
Strangely I've been doing something similar to avoid unnecessary calls to `_update_shapes()` as it seems:
```cpp
Physics2DServer *ps = Physics2DServer::get_singleton();
RID body = get_rid();

// Remove body from the space for faster processing
RID space = ps->body_get_space(body);
ps->body_set_space(body, RID());

// Modify shapes here ...

// Add body back to original space
ps->body_set_space(body, space);
```
Perhaps there should be a mechanism to lock/unlock the collision body when shapes need to be changed (similarly to Image's lock() before using set/get_pixel).

2019-04-04 16:54 UTC, reduz commented
Does not look bad, but add the same for the 3D physics too

2019-04-05 14:38 UTC, akien-mga commented
Looks fine, could you squash the commits together?

2019-04-05 17:38 UTC, ShyRed commented
Sure thing 😄

2019-04-21 13:43 UTC, reduz commented
Looks OK to me, I would merge, but would also like @AndreaCatania to approve it

2019-04-23 06:10 UTC, AndreaCatania commented
This is a good addition!

2019-04-23 06:10 UTC, AndreaCatania approved these changes

2019-04-23 06:18 UTC, AndreaCatania requested changes
The only thing to add is this:

```
if (shapes.write[p_index].active != p_disabled)
		return;
```
Here:
/godot/modules/bullet/collision_object_bullet.cpp:302

The result must be: 
```
void RigidCollisionObjectBullet::set_shape_disabled(int p_index, bool p_disabled) {
	if (shapes.write[p_index].active != p_disabled)
		return;
	shapes.write[p_index].active = !p_disabled;
	shape_changed(p_index);
}
```

2019-04-23 16:09 UTC, ShyRed commented
@AndreaCatania I put in the change:
```
	if (shapes[p_index].active != p_disabled)
		return;
```

Left out the `write` proxy, as this is a reading operation, though.

2019-04-23 16:16 UTC, AndreaCatania approved these changes

2019-04-30 09:43 UTC, merged

2019-04-30 09:43 UTC, akien-mga commented
Thanks!