Cursor Color Fix #26246
godotengine/godot pull request #27660
Opened 2019-04-03 22:10 UTC by mariambukenya

I was able to change the cursor color of the text edit from cursor_color (which displayed a caret with a dull color that was hard to see) to mono_color (which displayed a white caret in the dark theme of godot and black caret in the light theme of godot), making it easier to be seen.

2019-04-03 22:42 UTC, Calinou requested changes

2019-04-03 22:42 UTC, Calinou commented on editor/editor_themes.cpp
> +	theme->set_color("caret_color", "TextEdit", mono_color);
It'd make more sense to use `font_color` for consistency, as it's the color used by the cursor in LineEdit:

```suggestion
	theme->set_color("caret_color", "TextEdit", font_color);
```

2019-04-04 14:41 UTC, Calinou approved these changes

2019-04-05 10:07 UTC, akien-mga commented
Could you squash commits together?

2019-04-07 10:58 UTC, akien-mga commented
Pushed an edit to squash commits and improve commit log.

2019-04-07 10:58 UTC, akien-mga approved these changes

2019-04-08 08:05 UTC, merged

2019-04-08 08:05 UTC, akien-mga commented
Thanks!

2019-04-20 21:09 UTC, hpvb commented
Cherry-picked for 3.1.1.