tootle comment shortcut
godotengine/godot pull request #27946
Opened 2019-04-11 22:42 UTC by reisraff

2019-04-11 23:26 UTC, LikeLakers2 commented on editor/code_editor.cpp
> +			}
`toggle`, not `toogle`

2019-04-11 23:57 UTC, LeonardMeagher2 commented
Doesn't Ctrl+K already do this?

2019-04-12 00:33 UTC, LeonardMeagher2 commented
https://github.com/godotengine/godot/blob/07b76c0376eef34fcbf52ecc21074c5084f980f5/editor/plugins/script_text_editor.cpp#L1515

I guess ScriptTextEditor is different than the CodeEditor, but I imagine the default shortcuts should be the same. I know Ctrl+/ is pretty standard, I wonder why Ctrl+K is used in the script editor

Sorry for the off topic comment

2019-04-21 12:08 UTC, Paulb23 requested changes
I assume this is designed to fix #22177?

Rather then a new method in `CodeTextEditor` and shortcut.  it should be possible to change the existing method `toggle_inline_comment` (`CTRL+K`). 

In addition the comment / comment methods shouldn't be in `TextEdit`, but `CodeTextEditor`.

2019-04-21 12:08 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +		if (line_text[i] == '\t') {
Need to check for spaces as well, there's a helper method, `_is_whitespace()`.

2019-04-30 08:24 UTC, akien-mga commented
I'm not sure what this does which is not already supported with the Ctrl+K toggle comment hotkey?

@Paulb23's comment needs to be addressed in any case, and the commits should be squashed together with a clearer commit log for the final commit.

2019-05-28 09:59 UTC, akien-mga commented
Closing as per the above, the feature already exists via `toggle_inline_comment` so it should be expanded to support what is needed in #22177.

2019-05-28 09:59 UTC, closed without merging