add hotkeys to tileset editor
godotengine/godot pull request #27972
Opened 2019-04-13 05:58 UTC by ahouts

closes #27623

It seems the keyboard events only make it to this event handler if a specific region is active.
![Screenshot from 2019-04-12 22-53-14](https://user-images.githubusercontent.com/16907671/56075358-23396980-5d76-11e9-9ce1-cb22db04bd0e.png)

Also not sure about adding EditMode::EDITMODE_MIN, but it makes iteration much more clear.

2019-04-20 21:36 UTC, MarianoGnu requested changes
Take a look at how Shortcuts work at 
https://github.com/godotengine/godot/blob/41a6d41ed6df18316d22f6a3b2de449ff4a535aa/editor/plugins/tile_set_editor_plugin.cpp#L346
Adding the shortcut that way will make them work even if the workspace has not the mouse focus

2019-04-23 02:51 UTC, ahouts commented
@MarianoGnu Good to know, ty for the tip. 
I looked into it a bit, but it wasn't obvious to me what should be done if the shortcut for each button changes. In this case, depending on the type of sprite we are editing the buttons that are available change. This means the key we want to associate with each button changes as well.
Any tips on how to approach this?

2019-04-23 02:59 UTC, ahouts commented
I was thinking of registering the shortcuts when the tileset type was selected, but I didn't see a method that suggested it was for unregistering shortcuts to cleanup from the previous type.

2019-05-07 12:10 UTC, MarianoGnu commented
i personally dont like the idea of changing what mode is enabled by what key when they are visible or not, i would jsut asign a key to each button and if the button is not visible then the key doesn't work, like any other edition software

2019-05-11 01:12 UTC, ahouts commented
@MarianoGnu Fair enough, thanks for the clarification. The PR now reflects this change.

2019-05-28 09:57 UTC, merged

2019-05-28 09:57 UTC, akien-mga commented
Thanks!