Consistently wrap booleans in [code]
godotengine/godot pull request #28125
Opened 2019-04-17 11:54 UTC by KoBeWi

As briefly discussed in #27937 and as stated [here](http://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html#use-if-true-to-describe-booleans), booleans in docs should be wrapped in [code][/code] block and not all of them were, so this PR makes it consistent.

2019-04-17 13:37 UTC, Calinou requested changes
`False` and `false` aren't equivalent in GDScript, so it would be good to fix this for consistency with the rest of the documentation.

2019-04-17 13:37 UTC, Calinou commented on doc/classes/GraphNode.xml
> +				Return [code]true[/code] if right (output) slot 'idx' is enabled. [code]False[/code] otherwise.
```suggestion
				Return [code]true[/code] if right (output) slot 'idx' is enabled, [code]false[/code] otherwise.
```

2019-04-17 13:37 UTC, Calinou commented on doc/classes/GraphNode.xml
> +				Return [code]true[/code] if left (input) slot 'idx' is enabled. [code]False[/code] otherwise.
```suggestion
				Return [code]true[/code] if left (input) slot 'idx' is enabled, [code]false[/code] otherwise.
```

2019-04-17 15:15 UTC, KoBeWi commented
Pushed minor fixes, as requested by Calinou.

2019-04-17 17:54 UTC, Calinou approved these changes

2019-04-22 09:59 UTC, merged

2019-04-22 09:59 UTC, akien-mga commented
Thanks!

2019-07-29 12:54 UTC, akien-mga commented
Cherry-picked for 3.1.2.