fix improper uncommenting behavior in TextEditor
godotengine/godot pull request #28190
Opened 2019-04-19 07:51 UTC by griant

'Control+U' is not a registered shortcut, but handled internally in scene/gui/text_edit. Since TextEdit is a general edit control, it should not have this uncommenting action.

Fixes #28112

2019-04-21 11:33 UTC, Paulb23 requested changes
Yeah this is something that needs to be done, as the functionality should be moved into `CodeEditor`. However, I doubt we can remove it for 3.2, as removing functionality is a breaking change.

2019-04-29 15:43 UTC, akien-mga commented
> Yeah this is something that needs to be done, as the functionality should be moved into CodeEditor.

Seems like it should be moved to `ScriptTextEditor`?

BTW I find that it's not very intuitive what `CodeTextEditor` (from `editor/code_editor.h`), `ScriptTextEditor` (from `editor/plugins/script_text_editor.h`) and `ScriptEditor`/`ScriptEditorPlugin` (from `editor/plugins/script_editor_plugin.h`) are exactly and how they interface with each other. Might be worth some refactoring to have clearer names/locations. But I'm getting off topic :P

> However, I doubt we can remove it for 3.2, as removing functionality is a breaking change.

That's true, though we do accept *some* slight compat breakages in minor releases when they can be reasonably expected not to break anyone's project. In this case I doubt anyone is using the undocumented `Ctrl+U` as an uncomment toggle in their games, or if they are, they would see a mention of this change in the release notes.

So it's ok to change for 3.2 IMO.

2019-04-29 18:33 UTC, Paulb23 commented
> Seems like it should be moved to ScriptTextEditor? 
> But I'm getting off topic :P

Yeah, they are very similarly named, but in general:

`CodeTextEditor` is an abstraction on `TextEdit` for code editing. 

It's shared by more specific resources editor such as `ScriptTextEditor` for `Scripts`, `ShaderTextEditor` for `Shaders`  and `TextEditor` for `TextFiles`.

`ScriptEditor/ScriptEditorPlugin` is the actual plugin, managing the file / help list, function list etc.  

As un-commenting is not something specific to a resource type it can go in `CodeTextEditor`.

> So it's ok to change for 3.2 IMO.

Cool! In that case, the functionality just needs to be moved up to `CodeTextEditor`.

2019-05-28 09:47 UTC, akien-mga commented
> Cool! In that case, the functionality just needs to be moved up to CodeTextEditor.

@griant Could you amend the commit to do that?

2019-06-10 02:09 UTC, griant commented
> @griant Could you amend the commit to do that?

But `CodeTextEditor` already has `toggle_inline_comment` method. It's used by both `ScriptTextEditor` and `ShaderEditor`.
ref: commit 5165a90ef6915f20178a4abb1f008f442f1f17c5

2019-06-10 02:09 UTC, griant commented
> > @griant Could you amend the commit to do that?
> 
> But `CodeTextEditor` already has `toggle_inline_comment` method. It's used by both `ScriptTextEditor` and `ShaderEditor`.
> ref: commit [5165a90](https://github.com/godotengine/godot/commit/5165a90ef6915f20178a4abb1f008f442f1f17c5)

2019-06-10 02:12 UTC, griant commented
Sorry I messed up with some github buttons.

2019-07-09 06:56 UTC, merged

2019-07-09 06:56 UTC, akien-mga commented
Thanks!