Improve bookmarks
godotengine/godot pull request #29071
Opened 2019-05-21 15:13 UTC by YeldhamDev

The new bookmarks system is very hidden from the user, at the very end of an already bloated menu, and no way of having a overall view of the bookmarks, and to go directly to them. This commit fixes that:
![Screenshot_20190521_120616](https://user-images.githubusercontent.com/30739239/58108091-bae27100-7bda-11e9-99f5-d21d35b82ed1.png)

This gives the bookmarks its own accessible menu in script editor. Not only that, it shows all bookmarks of the current script, and clicking them takes you directly to the line.

2019-05-21 15:23 UTC, akien-mga commented
CC @KoBeWi 

What's that unknown character in the screenshot? A tab character?

2019-05-21 15:25 UTC, YeldhamDev commented
@akien-mga I actually use `strip_edges()`, but for some reasons those tabs aren't removed.

2019-05-21 15:34 UTC, KoBeWi commented
This is what I did originally with bookmarks, but @Paulb23 said that it should be an Edit sub-menu. Although with the bookmark list, it probably makes sense to have a completely separate menu for them.

2019-05-21 18:31 UTC, YeldhamDev commented
@KoBeWi Made the same improvements to the text and shader editors. The shader editor however doesn't save bookmarks, as it doesn't save the shader state at all.

2019-05-22 21:16 UTC, Paulb23 requested changes
Yeah it should stay as a Edit sub-menu. 

Otherwise, besides the one comment below, the rest of the changes look okay.

2019-05-22 21:16 UTC, Paulb23 commented on editor/plugins/script_text_editor.cpp
> +		bookmarks_menu->get_popup()->add_item(String::num((int)bookmark_list[i] + 1) + " - \"" + code_editor->get_text_edit()->get_line(bookmark_list[i]) + "\"");
Should this not be:
```suggestion
		bookmarks_menu->get_popup()->add_item(String::num((int)bookmark_list[i] + 1) + " - \"" + line + "\"");
```

2019-05-22 22:01 UTC, YeldhamDev commented
@Paulb23
> Yeah it should stay as a Edit sub-menu.
This doesn't address the issues I made. Bookmarks are supposed to be something easy to localize and reach, and where they are now, I'm quite people won't event notice that the feature exists. Every IDE I've used has its own menu for bookmarks, for a reason.

2019-05-24 13:25 UTC, KoBeWi commented
I took my time to test both options with multiple bookmarks. Here's comparison:

Old one
![image](https://user-images.githubusercontent.com/2223172/58330732-d5fdec80-7e37-11e9-818d-c5a2f1fc7006.png)

New one
![image](https://user-images.githubusercontent.com/2223172/58330741-dac2a080-7e37-11e9-8622-abbe0127f3ec.png)

IMO the new one is better for navigating the bookmark list. But it has a bug - shortcut buttons don't work until you open the menu for the first time.

2019-05-24 16:23 UTC, YeldhamDev commented
@KoBeWi Fixed.

2019-05-25 08:55 UTC, swarnimarun commented
@YeldhamDev Can't we have some shortcuts to jump to bookmarks like Ctrl/Cmd+Shift+1,..+2,..+3 and so on.
It would work for first 9 similar to tab switching in browsers.

2019-05-25 14:25 UTC, KoBeWi commented
> Can't we have some shortcuts to jump to bookmarks like Ctrl/Cmd+Shift+1,..+2,..+3 and so on.

This would work for tabs (and would be nice feature to have actually), but for bookmarks... not really. You can set bookmarks to arbitrary lines, they aren't labelled in any way, you rarely see all of them at once and they tend to shift a lot (I change bookmarked lines very often). Thus binding numbers to bookmarks is just impractical.

2019-05-26 14:14 UTC, Paulb23 commented
The visibility issue also applies to breakpoints, as there is currently no easy way to view all of them, so a similar approach will need to be applied to them eventually. 

I've seen three general approaches. 

Firstly, The approach here is used by Sublime text, with a list of bookmarks under `goto -> bookmarks`.

Secondly, I've also seen a separate panel under the script eg. in the bottom bar containing a tree of bookmarks. 

Alternatively, as a switchable panel in place of the function overview. 

Finally, last time something was added to the main bar it cased issues with smaller screens (#18078).

2019-05-26 15:36 UTC, YeldhamDev commented
@Paulb23 I could see breakpoints and bookmarks sharing a menu, "Goto", as you pointed out that Sublime does. That's still more accessible than putting it in the very end of the "Edit" menu.

And about the screen size, we have to find an equilibrium on things not taking too much space and easy localization. People which smaller screen may have to settle on lowering scale/font size on their end. And I speak as someone which a small screen myself (1366x768)

2019-05-27 15:28 UTC, akien-mga commented
> I could see breakpoints and bookmarks sharing a menu, "Goto", as you pointed out that Sublime does.

If we do that, I think we should spell it correctly as "Go to", otherwise it will be a headache for internationalization (and there's no real reason to spell it "Goto" as it's not really related to the programming `goto` statement).

2019-05-28 01:14 UTC, YeldhamDev commented
Sure, but while breakpoints aren't navigable (this should be done in a different commit), having the menu be "Bookmarks", and after they are, they can be united in a "Go To" menu.

2019-06-19 10:10 UTC, akien-mga commented
So what's the status in the end? Can we merge as is or should it be changed?

2019-07-01 14:34 UTC, akien-mga commented
I'll merge as is for now to reduce the backlog, it can be further improved in another PR.

2019-07-01 14:34 UTC, merged

2019-07-01 14:34 UTC, akien-mga commented
Thanks!