Applied some of FALLTHROUGH macro usage from #30122
godotengine/godot pull request #30177
Opened 2019-06-29 03:15 UTC by hbina

I am not sure how to deal with third party libraries as the macro is not defined there....and afaik thirdparty libraries usages should be 1 way only.

2019-06-29 06:42 UTC, bojidar-bg commented
I think you should remove the `// fallthrough` comments.

2019-06-29 14:49 UTC, Anutrix requested changes
I think you missed one in editor/plugins/sprite_frames_editor_plugin.cpp

2019-06-29 16:13 UTC, akien-mga commented on editor/plugins/tile_map_editor_plugin.cpp
>  		} // fallthrough
You can remove the comment.

2019-06-29 21:15 UTC, hbina commented on editor/plugins/tile_map_editor_plugin.cpp
>  		} // fallthrough
Fixed

2019-06-29 21:40 UTC, akien-mga approved these changes

2019-06-29 21:40 UTC, merged

2019-06-29 21:40 UTC, akien-mga commented
Thanks!

2019-08-21 10:17 UTC, akien-mga commented
Cherry-picked for 3.1.2.