Make Set methods obsolete
godotengine/godot pull request #30774
Opened 2019-07-23 11:28 UTC by aaronfranke

Mono: Declare all set methods obsolete https://github.com/godotengine/godot/issues/30744

Core: Make warnings and suggest using constructors instead. Previously the constructors called the methods, so I moved the logic into the constructors. We can delete them in 4.0+.

I also swapped the negative adding to subtracting by swapping the left and right sides in the constructor for eulerYXZ. No behavior change, but it looks cleaner.

Partial follow-up to https://github.com/godotengine/godot/pull/21348

2019-07-23 15:51 UTC, neikeq requested changes
I've commented how the Obsolete messages should be, to be consistent with the existing ones. I also think it's better to specify the exact constructor to use. The assignment part is not needed as people will understand it. Also, we must use named parameters for booleans.

I can't comment on the C++ API. I don't know if the changes are needed there.

2019-07-23 15:51 UTC, neikeq commented on modules/mono/glue/Managed/Files/Quat.cs
> +        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```C#
[Obsolete("Set is deprecated. Use the Quat(" + nameof(real_t) + ", " + nameof(real_t) + ", " + nameof(real_t) + ", " + nameof(real_t) + ") constructor instead.", error: true)]
```

2019-07-23 15:51 UTC, neikeq commented on modules/mono/glue/Managed/Files/Quat.cs
> +        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```C#
[Obsolete("Set is deprecated. Use the Quat(" + nameof(Quat) + ") constructor instead.", error: true)]
```

2019-07-23 15:51 UTC, neikeq commented on modules/mono/glue/Managed/Files/Quat.cs
> +        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```C#
[Obsolete("SetAxisAngle is deprecated. Use the Quat(" + nameof(Vector3) + ", " + nameof(real_t) + ") constructor instead.", error: true)]
```

2019-07-23 15:51 UTC, neikeq commented on modules/mono/glue/Managed/Files/Quat.cs
> +        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```C#
[Obsolete("SetEuler is deprecated. Use the Quat(" + nameof(Vector3) + ") constructor instead.", error: true)]
```

2019-07-23 15:51 UTC, neikeq commented on modules/mono/glue/Managed/Files/Vector2.cs
> +        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```C#
[Obsolete("Set is deprecated. Use the Vector2(" + nameof(real_t) + ", " + nameof(real_t) + ") constructor instead.", error: true)]
```

2019-07-23 15:51 UTC, neikeq commented on modules/mono/glue/Managed/Files/Vector2.cs
> +        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```C#
[Obsolete("Set is deprecated. Use the Vector2(" + nameof(Vector2) + ") constructor instead.", error: true)]
```

2019-07-23 15:51 UTC, neikeq commented on modules/mono/glue/Managed/Files/Vector3.cs
> +        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```C#
[Obsolete("Set is deprecated. Use the Vector3(" + nameof(real_t) + ", " + nameof(real_t) + ", " + nameof(real_t) + ") constructor instead.", error: true)]
```

2019-07-23 15:51 UTC, neikeq commented on modules/mono/glue/Managed/Files/Vector3.cs
> +        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```C#
[Obsolete("Set is deprecated. Use the Quat(" + nameof(Vector3) + ") constructor instead.", error: true)]
```

2019-07-24 06:45 UTC, akien-mga commented on core/math/quat.cpp
> +	ERR_EXPLAIN("set_axis_angle is deprecated. Use the Quat(Vector3 axis, float angle) constructor instead.");
You could remove the duplicated code below by a call to the constructor I guess.

2019-07-24 06:48 UTC, akien-mga commented
To be fair I'm not sure if it's really useful to deprecate this API in Quat. I can't comment about C#, but Quat has `set_euler()` and `set_axis_angle()`, which both make their mathematical implications clear. `Quat(Vector3)` and `Quat(Vector3, float)` on the other hand are a lot less obvious, and while the documentation can make the arguments expicit, once it's in your code, `quat = Quat(some_vec, some_float)` will be less explicit than `quat.set_axis_angle(some_vec, some_float)`.

2019-07-24 12:20 UTC, aaronfranke commented
@akien-mga Those methods in Basis aren't currently exposed (and also aren't in C#).

There are actual issues with these in C# that causes the code to silently fail, so if core is unchanged it would still be a good idea to remove them from the mono module.

2019-07-24 14:53 UTC, neikeq approved these changes
C# changes are good.

2019-07-29 05:02 UTC, aaronfranke commented
I removed the core Quat changes from this PR, so that it's just the C# changes and some nitpicking stuff. I have the core change saved elsewhere in case we want to revisit this later, if it's better to keep those methods in GDScript then that's fine even if it's inconsistent with C#.

2019-07-29 07:04 UTC, merged

2019-07-29 07:04 UTC, akien-mga commented
Thanks!

For the core changes, you can mention them in #16863.