Fixed crash when making subresource unique in inspector dock #30160
godotengine/godot pull request #30804
Opened 2019-07-25 03:12 UTC by hbina

The problem was that when a Node is deleted, the InspectorDock is left out from the update.
A possible improvement would be to refactor this into its own function.

2019-07-25 06:36 UTC, akien-mga commented
> Notice that all of them (except for one in my commit) are not updating inspector_dock.

As far as I know that's the purpose of `get_inspector()->edit(NULL)` calls that are in the snippets you linked.

2019-07-25 10:38 UTC, hbina commented
Unfortunately I don't think this is the case, InspectorDock have its own member variable called `current` that is supposedly the pointer to the current item selected. I think this `current` variable is not exposed to anyone outside i.e. used exclusively within InspectorDock.

2019-08-06 13:26 UTC, groud requested changes
I am ok with the principle of the PR. Could add this update wherever else it makes sense as you suggested in your comment ? Once this is done, it should be good to merge.

2019-08-06 22:06 UTC, hbina commented
I have made the changes that you recommended @groud

2019-08-07 09:43 UTC, merged

2019-08-07 09:43 UTC, akien-mga commented
Thanks!