Add Ability to Enable/Disable Shortcuts for LineEdit
godotengine/godot pull request #31188
Opened 2019-08-08 00:15 UTC by sparkart

This PR adds the ability to enable and disable shortcut keys for LineEdit.

Closes: #31183

2019-08-08 09:36 UTC, akien-mga commented on scene/gui/line_edit.cpp
> +					if (editable && is_shortcut_keys_enabled()) {
Instead of adding this check in all cases, maybe simply put it in the outer `if`?

2019-08-08 09:38 UTC, akien-mga commented on scene/gui/line_edit.cpp
> +	// Reorganize context menu.
Might be worth moving to a private method since it's called in two places.

2019-08-08 09:39 UTC, akien-mga commented
> Closes: #31183

This issue also requests the same feature in TextEdit.

2019-09-03 11:20 UTC, akien-mga commented
Needs a rebase to remove the merge commit and fix merge conflicts, otherwise I guess it should be ok to merge.

2019-09-03 18:47 UTC, Paulb23 requested changes
This doesn't seem to fix the linked issue? As it describes disabling selections not shortcuts.

In any case, you should only need to remove the shortcuts inside new method `_generate_context_menu` leaving the main switch alone.

2019-09-03 18:58 UTC, sparkart commented
> This doesn't seem to fix the linked issue? As it describes disabling selections not shortcuts.
> 
> In any case, you should only need to remove the shortcuts inside new method `_generate_context_menu` leaving the main switch alone.

I've tried that before, but it does not seem to have any effect. The context menu will show or not show the shortcut keys... but the switch statement causes the shortcut keys to have effect regardless of whether the context menu has them or not.

2019-09-03 20:21 UTC, Paulb23 commented
> I've tried that before, but it does not seem to have any effect

Ahh my bad, I remember now, currently they are visual only. Related #29490, which will require shortcuts to handle echoed events before they can be changed.

In that case, there are a couple missing:

* `select_all()` on line 3459 
* `cut()` on line 3201

2019-09-07 11:16 UTC, Paulb23 requested changes
Couple notes left inline, It's also still possible to select with the mouse or shift + arrow keys within `line_edit`.

2019-09-07 11:16 UTC, Paulb23 commented on scene/gui/line_edit.cpp
> +	_generate_context_menu();
If this is set to false, it should clear ant current selection.

2019-09-07 11:16 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +	_generate_context_menu();
Same here.

2019-09-14 19:13 UTC, Paulb23 approved these changes

2019-09-19 17:57 UTC, merged

2019-09-19 17:57 UTC, akien-mga commented
Thanks!