Add macro for Enums
godotengine/godot pull request #31358
Opened 2019-08-13 18:56 UTC by qarmin

Suppress #28297

PR adds special macro for checking enums.
It only can check enum values which starts in 0.

2020-02-15 18:57 UTC, qarmin commented
There are only 2 versions of error macro:  ERR_FAIL_ENUM_RANGE and ERR_FAIL_ENUM_RANGE_V, because I don't think that have sense to put a message(e.g. ERR_FAIL_ENUM_RANGE_MSG) to this macro, because output show everything what we need to know:
```
ERROR: Enum p_format = 25 out of size, allowed range [0, 2].
   at: get_format_name (core/image.cpp:3380)
```

2020-04-08 20:38 UTC, qarmin commented
I added support for enum values which doesn't start with 0(not much in Godot code)
Example of usage
```
	int p_value = -100;
	ERR_FAIL_ENUM_RANGE_V(p_value,-15,PATH_MAX,1);
```
and output
```
ERROR: Enum p_value = -100 out of size, allowed range [-15, 4095].
   at: main (platform/linuxbsd/godot_linuxbsd.cpp:49)
```

2020-06-21 06:23 UTC, aaronfranke commented
If you're defining the macro, maybe you should also use it in the same PR? For example, the other PR did this in several places where the check had `(int)` in it: https://github.com/godotengine/godot/pull/28297/files#diff-4f1f12df53bfa183b5cfc1fbb87d21daR452

2021-01-19 21:17 UTC, aaronfranke requested changes
@qarmin Is this still desired? If so, it needs to be rebased on the latest master branch. Also, the above feedback should be addressed.

Otherwise, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

2021-01-19 21:17 UTC, aaronfranke commented on core/input/input.h
> +		MOUSE_MODE_MAX
Enums should end with trailing commas. Also, this will conflict with #43450.

2021-08-09 18:59 UTC, qarmin commented
Closing, since I don't think that is needed anymore(ERR_FAIL works now fine for my use-cases and I don't think that anyone needs now this macro, but if is needed, feel free to fork branch)

2021-08-09 18:59 UTC, closed without merging