Fix various typos and style errors in text
godotengine/godot pull request #31486
Opened 2019-08-19 17:45 UTC by KoBeWi

This PR fixes some random things I spotted while translating.

2019-08-19 18:31 UTC, Calinou commented on doc/classes/Directory.xml
> +				If [code]skip_navigational[/code] is true, [code].[/code] and [code]..[/code] are filtered out.
```suggestion
				If [code]skip_navigational[/code] is [code]true[/code], [code].[/code] and [code]..[/code] are filtered out.
```

2019-08-19 18:32 UTC, Calinou requested changes

2019-08-19 18:32 UTC, Calinou commented on doc/classes/Directory.xml
> +				If [code]skip_hidden[/code] is true, hidden files are filtered out.
```suggestion
				If [code]skip_hidden[/code] is [code]true[/code], hidden files are filtered out.
```

2019-08-19 18:32 UTC, Calinou commented on doc/classes/Directory.xml
> +				If [code]skip_navigational[/code] is true, [code].[/code] and [code]..[/code] are filtered out.
```suggestion
				If [code]skip_navigational[/code] is [code]true[/code], [code].[/code] and [code]..[/code] are filtered out.
```

2019-08-20 10:50 UTC, merged

2019-08-20 10:50 UTC, akien-mga commented
Thanks!