Update TextEdit selection when inserting line
godotengine/godot pull request #31496
Opened 2019-08-20 07:45 UTC by pouleyKetchoupp

Selection columns could be invalid after inserting a line in TextEdit (e.g adding warning ignore hints). Now the line indices will be updated when needed, in order to grow or move the selection depending on the case.

Fixes #31458

2019-08-21 22:35 UTC, Paulb23 requested changes
Rather then adjusting the selection, it should deselect the text as this method moves the caret to the line. Which could be miles away.

2019-08-22 15:58 UTC, pouleyKetchoupp commented
It makes sense to make it consistent. But what about just not moving the caret either? I don't really see the purpose of changing anything in the current selection or cursor while disabling a warning.

2019-08-22 19:53 UTC, Paulb23 commented
Yeah that works too, looks like it's only used for disabling warnings and it's not exposed to scripting, so no compatibility breakage.

2019-08-22 21:14 UTC, pouleyKetchoupp commented
Cool, I'll do it this way then.

2019-08-25 13:50 UTC, pouleyKetchoupp commented
@Paulb23 Changes are done. Now the cursor is adjusted the same way as the selection.

2019-08-25 14:55 UTC, Paulb23 approved these changes
LGTM.

2019-08-25 20:33 UTC, merged

2019-08-25 20:33 UTC, akien-mga commented
Thanks!