Enable ProGuard for Android release builds to decrease APK size
godotengine/godot pull request #31509
Opened 2019-08-20 18:13 UTC by Calinou

This reduces the size of release APKs by about 300 KB on average.

I'm marking this as a draft since this will likely conflict with third-party modules in its current state. How could this be integrated so modules can supply their own ProGuard exclusions? (cc @megasoft78)

Also, this should be tested when Mono support is enabled to check for bugs that could appear when using ProGuard alongside. (cc @neikeq)

Other than that, I can confirm it works when exporting the Platformer 2D demo.

Related to #18253.

2019-08-20 20:00 UTC, neikeq commented
Does this only touch the Godot java code? I don't see how this would cause any problem only with mono enabled builds.

2019-08-21 05:47 UTC, m4gr3d commented
@Calinou one area to be careful, there are several java methods that are only used by the native layer, which ProGuard is usually not able to detect. As such, it may often be overly aggressive and remove these methods, causing hard to diagnose runtime crashes.

2020-07-01 02:22 UTC, aaronfranke commented
@Calinou Is this still desired? If so, it needs to be rebased on the latest master branch.

2020-07-01 07:19 UTC, Calinou commented
@aaronfranke Yes, but it needs more testing, especially with the new Android build system. We'll probably have to wait until people have started porting "real world" applications to Godot 4.

2020-11-13 05:44 UTC, m4gr3d requested changes
The PR should be updated based on comments in https://github.com/godotengine/godot/issues/43363#issuecomment-723705888

2022-06-19 03:42 UTC, Calinou commented
Rebased with @mbrlabs' `proguard-rules.pro` file included. Note that I haven't compiled APKs with and without ProGuard to compare binary size or check if the ProGuard'd APK still works.

2022-06-27 00:44 UTC, m4gr3d commented
> How could this be integrated so modules can supply their own ProGuard exclusions?

@Calinou [This page](https://developer.android.com/studio/projects/android-library#Considerations) has the instructions for how library modules can define their own proguard files and include it as part of the build (search for `A library module may include its own ProGuard configuration file`).

So to complete this PR, it looks like there are a couple remaining tasks:
- Update the Android plugin documentation to specify that plugin developers should define and include their module proguard files.
- Create an annotation (e.g: [@UsedByNative](https://android.googlesource.com/platform/prebuilts/fullsdk/sources/android-29/+/refs/heads/androidx-wear-release/com/android/mtp/annotations/UsedByNative.java)) to specify to proguard that certain methods/fields should be left untouched as they're being used by the native code.

2022-06-27 00:49 UTC, m4gr3d requested changes

2022-06-27 00:49 UTC, m4gr3d commented on platform/android/java/app/proguard-rules.pro
> +-keep class com.godot.** { *; }
This `proguard` file seems like it applies primarily to the `lib` module, so it should be moved there by following the instructions in https://github.com/godotengine/godot/pull/31509#issuecomment-1166700483 to ensure it's being picked by the `app` module's proguard, which should be much smaller/simpler.

I'll apply a similar update to https://github.com/godotengine/godot/pull/62235

2022-06-27 13:10 UTC, m4gr3d commented
> If this is merged, we should also update the documentation to mention that release export templates use ProGuard.

I don't think this should be applied to the generated templates. Given the way they're used for Android builds, it's likely to create issues.

We should make this an option for the custom Gradle based build (off by default) instead.

2024-11-05 19:02 UTC, fire commented
@Calinou and @m4gr3d is this still desired for 4.4?

2024-11-06 18:58 UTC, m4gr3d commented
I don't think it's needed at this point in time, but I'll defer to @Calinou as the author.

2024-11-07 14:40 UTC, Calinou commented
Closing per the above comments.

2024-11-07 14:40 UTC, closed without merging