Fixed UI navigation using joy axis inputs
godotengine/godot pull request #31880
Opened 2019-09-02 02:40 UTC by pouleyKetchoupp

This change fixes glitches when using joy axis inputs for ui navigation. Now inputs are only applied on the first frame they occur, even when joystick events are still being received.

Fixes #31879

2019-09-02 07:47 UTC, groud requested changes
For each action, the `is_action_pressed` check should be removed, it becomes redundant with the `is_action_just_pressed` check.

2019-09-02 08:35 UTC, pouleyKetchoupp commented
Are you sure it would be safe?
`p_event->is_action_pressed()` is checking the actual event the `Viewport` received, whereas `input->is_action_just_pressed()` just checks the global action to be triggered. I don't want a viewport to trigger events that it's not supposed to in some edge cases, that's why I kept both checks.

2019-09-02 08:46 UTC, groud commented
I see what you mean, but what you are doing here is likely not really consistent then. 
Either you use the global action system, either you use events, else that's where you might end up with inconsistencies when you have several Viewports. Could be merged like that until we find a better solution though.

Anyway, I kind of think this is not the perfect solution. I believe you should be able to keep the stick pressed to navigate on several entries, so you don't have to bring the stick to the center all the time on long lists. However that would require to setup a configurable timer between two focus change (and maybe another one offset the first change before it changes repeatedly).

2019-09-02 08:46 UTC, groud submitted a review, later dismissed

2019-09-02 08:52 UTC, pouleyKetchoupp commented
I agree, there's probably a more consistent solution to be implemented for this. This implementation just seemed safe and easy to do :)

Concerning moving through the menu by holding the stick, I love the idea but I think it could be added in a more general way for all input types, since there's also no support for key repeat on keyboard or joy buttons as far as I know.

2019-09-03 10:02 UTC, merged

2019-09-03 10:02 UTC, akien-mga commented
Thanks!