Changed some code found by Clang Tidy and Coverity
godotengine/godot pull request #32055
Opened 2019-09-09 11:12 UTC by qarmin

Changing type of variable in loops, prevent from overflow this variable - https://clang.llvm.org/extra/clang-tidy/checks/bugprone-too-small-loop-variable.html

also there is change from INT32 -> to INT64 in core/ustring.cpp because this function return 64 bit int.

2019-09-13 16:41 UTC, aaronfranke requested changes

2019-09-13 16:41 UTC, aaronfranke commented on core/io/file_access_zip.cpp
> +	for (unsigned long long i = 0; i < gi.number_entry; i++) {
You can replace `unsigned long long` with `uint64_t`

2019-09-13 16:41 UTC, aaronfranke commented on drivers/alsa/audio_driver_alsa.cpp
> +			for (unsigned long i = 0; i < ad->period_size * ad->channels; i++) {
I don't know if this is desirable. https://github.com/godotengine/godot/issues/25652

2019-09-22 17:19 UTC, aaronfranke approved these changes

2019-09-23 08:00 UTC, merged

2019-09-23 08:00 UTC, akien-mga commented
Thanks!