Fixed RigidBody stuttering when changing collision layer/mask
godotengine/godot pull request #32641
Opened 2019-10-08 09:37 UTC by pouleyKetchoupp

- Changing collision layer/mask now only updates the broadphase proxy to avoid the velocity to be reset each time (also avoids unnecessary computations)
- No rigid body update at all when the collision layer/mask stays the same
- Same changes for Area for optimization purpose

Fixes #32577

2019-10-08 10:09 UTC, AndreaCatania requested changes

2019-10-08 10:09 UTC, AndreaCatania commented on modules/bullet/bullet_physics_server.cpp
> +	if (area->get_collision_mask() != p_mask) {
Can you please perform this operation inside the `set_collision_mask` function?

In this way if any other function change collision mask by calling the `area->set_collision_mask(p_mask);` directly, the same logic is applied.

2019-10-08 10:09 UTC, AndreaCatania commented on modules/bullet/bullet_physics_server.cpp
> +		body->set_activation_state(true);
Following the above advice, can you please put the `set_activation_state` inside the `set_collision_layer` ?

2019-10-08 10:16 UTC, AndreaCatania commented
Can you please submit a sample project to check this PR?

2019-10-08 12:47 UTC, pouleyKetchoupp commented
@AndreaCatania Thanks for the review! I've pushed the changes you asked for.

Here's a sample project to test the changes, which is mostly based on the repro project from #32577.
[areatest.zip](https://github.com/godotengine/godot/files/3702384/areatest.zip)

You can set `test` property in the area script to 3 different modes:
- DynamicBody: press space to toggle the collision layer for the falling cube, on layer 2 it will fall through the static body under it.
- StaticBody: same but it changes the static body's collision layer.
- Area: toggles the collision layer of the area itself, and when detecting rigid bodies it forces them to have a velocity of 0.

2019-10-12 10:36 UTC, AndreaCatania commented
It works! thanks for the improvement!

@akien-mga you can merge this

2019-10-12 10:36 UTC, AndreaCatania approved these changes

2019-10-12 12:07 UTC, merged

2019-10-12 12:07 UTC, akien-mga commented
Thanks!