Add documentation for ReflectionProbe
godotengine/godot pull request #32662
Opened 2019-10-08 21:13 UTC by SamuelDeboni

2019-10-08 21:49 UTC, Calinou requested changes
I added some suggestions to make the documentation more detailed :slightly_smiling_face:

Also, the documentation XML must be indented with tabs, not spaces (with the exception of code samples).

2019-10-08 21:49 UTC, Calinou commented on doc/classes/ReflectionProbe.xml
> +            Capture it's surroundings to crate reflection.
```suggestion
			Captures its surroundings to create reflections.
```

2019-10-08 21:49 UTC, Calinou commented on doc/classes/ReflectionProbe.xml
> +            Capture it's surroundings as a sort of 360 degrees image, and stores versions of it with increasing levels of blur to simulate diferent roughness.
```suggestion
			Capture its surroundings as a dual parabolid image, and stores versions of it with increasing levels of blur to simulate different material roughnesses.
```

2019-10-08 21:49 UTC, Calinou commented on doc/classes/ReflectionProbe.xml
> +                    If true enable box projection.
```suggestion
			If [code]true[/code], enables box projection. This makes reflections look more correct in rectangle-shaped rooms by offsetting the reflection center depending on where the camera is located.
```

2019-10-08 21:49 UTC, Calinou commented on doc/classes/ReflectionProbe.xml
> +                    If true enable shadows.
```suggestion
			If [code]true[/code], computes shadows in the reflection probe. This makes the reflection probe slower to render; you may want to disable this if using the [constant UPDATE_ALWAYS] [member update_mode].
```

2019-10-08 21:49 UTC, Calinou commented on doc/classes/ReflectionProbe.xml
> +                    Defines the reflection intensity.
```suggestion
			Defines the reflection intensity.
```

2019-10-09 06:09 UTC, akien-mga commented on doc/classes/ReflectionProbe.xml
> +			Captures its surroundings to create reflections.
Too much indentation.

2019-10-09 06:09 UTC, akien-mga commented on doc/classes/ReflectionProbe.xml
> +        <description>
Should be indented with one tab, not spaces.

2019-10-09 06:10 UTC, akien-mga commented on doc/classes/ReflectionProbe.xml
> +			Capture its surroundings as a dual parabolid image, and stores versions of it with increasing levels of blur to simulate different material roughnesses.
Too much indentation.

2019-10-09 06:10 UTC, akien-mga commented
There are still indentation issues, and the commits should be squashed into one. Otherwise the added docs seem good :)

2019-10-09 12:00 UTC, akien-mga approved these changes

2019-10-09 12:00 UTC, merged

2019-10-09 12:00 UTC, akien-mga commented
Thanks!