TextEdit syntax highlighting fixes
godotengine/godot pull request #32940
Opened 2019-10-20 12:39 UTC by pouleyKetchoupp

Changes made in relation to #32931

- Fixed visual update when using `add_keyword_color()`, `add_color_region()`, `clear_colors()` in scripts
- More accurate description for `clear_colors()` in `TextEdit` documentation

2019-10-20 13:58 UTC, Paulb23 requested changes
You beat me to it :P

There's an internal one `add_member_keyword` that also needs to be cleared.

2019-10-20 15:47 UTC, pouleyKetchoupp commented
Thanks for the review :)
I've just pushed the changes to handle member keywords as well.

2019-10-20 17:58 UTC, Paulb23 approved these changes

2019-10-22 05:32 UTC, nathanwfranke commented
Now, `clear_colors()` clears all the keywords, but is there a way to clear all of the color regions?

2019-10-22 06:51 UTC, pouleyKetchoupp commented
@nathanwfranke Your examples are not color regions. They are set in the inspector:
Custom Colors > Member Variable Color / Function Color / Number Color

If you want to clear them by script, you can also use:
```
var font_color = get_color("font_color")
add_color_override("member_variable_color", font_color)
add_color_override("function_color", font_color)
add_color_override("number_color", font_color)
```

2019-10-22 18:40 UTC, merged

2019-10-22 18:40 UTC, akien-mga commented
Thanks!