Fix ruler origin is moving with zoom
godotengine/godot pull request #33043
Opened 2019-10-24 19:21 UTC by volzhs

Fix #32983

![ruler](https://user-images.githubusercontent.com/8281454/67517971-b9175f00-f6de-11e9-868b-0ec45a701827.gif)

2019-10-24 19:47 UTC, KoBeWi requested changes
Something is wrong. When you set zoom to e.g. 282.8% (zoom-in 3 times from 100%), the "secondary text" will sometimes appear on straight lines (i.e. with snapping enabled).
![image](https://user-images.githubusercontent.com/2223172/67519402-15f72300-f6a7-11e9-8717-ca11aa36a56f.png)

This does not happen in vanilla build.

2019-10-24 20:20 UTC, volzhs commented
@KoBeWi fixed. and also fixed displaying wrong unit.

![ruler-wrong-unit](https://user-images.githubusercontent.com/8281454/67522123-20391180-f6e7-11e9-9213-7f554fabe563.gif)

2019-10-24 20:20 UTC, KoBeWi approved these changes

2019-10-25 05:48 UTC, merged

2019-10-25 05:48 UTC, akien-mga commented
Thanks!