Fix HTTP HEAD requests
godotengine/godot pull request #33640
Opened 2019-11-15 14:48 UTC by mewin

The current implementation of the HTTP client unconditionally waits for the response body to be sent. Therefore when sending a HEAD request, the client always freezes/times out when waiting for the response.
I added a few lines to fix this and make HEAD requests possible.

2019-11-21 12:51 UTC, Faless requested changes
Thank you for your contribution!
This PR is promising, but needs some fixes.
See my comments.

2019-11-21 12:51 UTC, Faless commented on core/io/http_client.cpp
> +	head_request = p_method == METHOD_HEAD;
This should be done in `HTTPClient::request_raw` too.
Also needs initialization in constructor and `HTTPClient::close`.

2019-11-21 12:51 UTC, Faless commented on core/io/http_client.cpp
> +					// this is a HEAD request, we wont receive anything
Please capitalize "`This`"

2019-11-28 09:29 UTC, mewin commented
Thanks for the feedback. I updated the PR according to it.

2019-12-01 04:49 UTC, Faless approved these changes
Looks good, thank you for your contribution :1st_place_medal: !

2019-12-01 04:50 UTC, merged