Android singleton, support taking MulticastLock manually
godotengine/godot pull request #33911
Opened 2019-11-26 10:42 UTC by Faless

This PR is an alternative to #33910 .
Instead of using complex logic to try and automatically take the MulticastLock, this PR exposes a new `"Android"` engine singleton.
That singleton can `acquire` or `release` the lock.
Permission `CHANGE_WIFI_MULTICAST_STATE` is required to acquire the lock.
Like in #33910 UDP broadcast is now off by default.

```gdscript
func _ready():
	Engine.get_singleton("Android").multicast_lock_acquire()
	Engine.get_singleton("Android").multicast_lock_release()
```

Closes #33910

2019-11-26 12:04 UTC, Faless commented
Meh, now spits error when running IPv6. Will need some extra work

2019-11-26 12:56 UTC, Faless commented
Okay, should be ready now, sorry about the spam :(

2019-11-27 22:40 UTC, m4gr3d requested changes
Sorry but this looks like a bad idea. I'd be happy to clarify if you're curious why, but at this point, the other implementation (PR #33910) is much better way to go.

2019-12-10 11:17 UTC, Faless commented
@m4gr3d I trust your judgment, I'm closing this PR, and updating the other one.

2019-12-10 11:17 UTC, closed without merging