Parser: Check all the identifiers inside Arrays
godotengine/godot pull request #34342
Opened 2019-12-13 23:37 UTC by lupoDharkael

Fixes https://github.com/godotengine/godot/issues/34337

2019-12-28 10:10 UTC, bojidar-bg commented on modules/gdscript/gdscript_parser.cpp
> +					} else if (n->type == Node::TYPE_IDENTIFIER) {
Is the `if` really necessary? Wouldn't things work just fine if every node gets its type reduced?

Also, shouldn't similar code be added to dictionary parsing below?

2020-01-02 16:22 UTC, vnen requested changes

2020-01-02 16:22 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +						_reduce_node_type(n);
This shouldn't be called here. The type-check phase only happens after all parsing is finished. AFAIK this is already done: https://github.com/godotengine/godot/blob/bde52cc6881b3cb84602ffba1dede0a0180dbe4f/modules/gdscript/gdscript_parser.cpp#L6260-L6264

2020-03-05 09:24 UTC, akien-mga commented
Looks like #34337 was already fixed differently in 3.2.

2020-03-05 09:24 UTC, closed without merging