Allow attaching any external profiler, including JetBrains dotTrace
godotengine/godot pull request #34382
Opened 2019-12-16 17:29 UTC by van800

2019-12-16 18:59 UTC, neikeq requested changes
In addition to what I commented, Godot [enforces](https://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html#c-and-objective-c) the use clang-format for auto-formatting. This is why the CI build failed.

2019-12-16 18:59 UTC, neikeq commented on modules/mono/mono_gd/gd_mono.cpp
> +	_dupenv_s(&mono_env_ops, &len, "MONO_ENV_OPTIONS");
I think `_dupenv_s` is windows only. You can use `OS::get_singleton()->get_environment("MONO_ENV_OPTIONS")` instead.

2019-12-16 19:58 UTC, van800 commented
> In addition to what I commented, Godot [enforces](https://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html#c-and-objective-c) the use clang-format for auto-formatting. This is why the CI build failed.

Done. Thanks!

2019-12-16 20:42 UTC, neikeq approved these changes

2019-12-16 21:00 UTC, merged

2019-12-16 21:00 UTC, akien-mga commented
Thanks!

2020-01-15 18:17 UTC, akien-mga commented
> Official windows builds are cross-compiled with mingw and they statically link mono (passing mono_static=yes)

Can you give more details on why this is problematic for this feature?
Official Linux and macOS builds also link mono statically.

If there are things we can change in the official Windows distribution to make profiling work, that's something we can consider.

2020-01-16 09:34 UTC, van800 commented
Is linking mono somehow different on Windows? Even if it is not different mono documentations says that for windows each function should be marked for export.
https://www.mono-project.com/docs/advanced/embedding/#windows-considerations
Likely after static linking exports are not inherited.

Our dll loaded in your process is looking for mono api function and fails.
```
auto lib_handle = LoadLibrary("godot_exe_name");
auto func = GetProcAddress(lib_handle, "some_mono_function"); // this call fails
```
Example of the function: `MONO_API MonoProfilerHandle mono_profiler_create (MonoProfiler *prof);`

2025-08-24 07:33 UTC, MatthiasBae commented
Is profiling not working anymore?

As soon as I want to access my snapshots it says I need to activate the dotTrace plugin license. The docs and this snapshot indicate that it should work woithout license and I know it was working some time ago before the Non-Commercial license has been released.

But for now I am not able to use profiling tools in Jetbrains Rider+Godot+C# without dotTrace license.

Not mentioned in here: https://www.jetbrains.com/help/rider/Godot.html#test-and-profile

When I want to access my snapshot: 
<img width="463" height="143" alt="image" src="https://github.com/user-attachments/assets/05f45fe2-12fd-4b97-8546-60dd2e301253" />

<img width="732" height="646" alt="image" src="https://github.com/user-attachments/assets/d1ca3981-dfaa-41fe-a9c9-02096cbec4d5" />

Am I missing something?

2025-08-24 08:29 UTC, van800 commented
I think, it is expected. Please ask dottrace support or sales at JetBrains.com

2025-08-24 08:41 UTC, MatthiasBae commented
> I think, it is expected. Please ask dottrace support or sales at JetBrains.com

Thanks for your reply! Was about to write an issue in the godot-support repository but will contact the dottrace support now.

In case this is expected and not a bug it is unfortunate because there is **no** possibility to profile C# applications in Godot anymore. The built in Godot profiler does not support C# and now also Rider. Means we have to use a third tool / IDE just for profiling. I will update this comment when I have an answer from dottrace support.

I guess if it is the case, it should be atleast mentioned in the docs.