Docs: OptionButton
godotengine/godot pull request #34412
Opened 2019-12-17 22:29 UTC by flyingpimonster

Completed the documentation and made some existing descriptions a bit clearer.

2019-12-17 22:34 UTC, Calinou requested changes
Content looks good to me. I made some suggestions about formatting :slightly_smiling_face:

2019-12-17 22:34 UTC, Calinou commented on doc/classes/OptionButton.xml
> +				Returns the ID of the selected item, or 0 if no item is selected.
```suggestion
				Returns the ID of the selected item, or [code]0[/code] if no item is selected.
```

2019-12-17 22:34 UTC, Calinou commented on doc/classes/OptionButton.xml
> +			The index of the currently selected item, or -1 if no item is selected.
```suggestion
			The index of the currently selected item, or [code]-1[/code] if no item is selected.
```

2019-12-17 22:34 UTC, Calinou commented on doc/classes/OptionButton.xml
> +				Sets the metadata of an item. Metadata may be any type and can be used to store extra information about an item, such as an external string ID.
This looks more grammatically correct to me:

```suggestion
				Sets the metadata of an item. Metadata may be of any type and can be used to store extra information about an item, such as an external string ID.
```

2019-12-17 22:34 UTC, Calinou commented on doc/classes/OptionButton.xml
> +				This will work even if the item is disabled.
This could be put on the same paragraph as the line above (i.e. don't put a line break).

2019-12-18 06:59 UTC, merged

2019-12-18 06:59 UTC, akien-mga commented
Thanks!