Allow to focus previous item in editor
godotengine/godot pull request #34410
Opened 2019-12-17 22:05 UTC by NilsIrl

Fix #34405 

The ideal fix would that `is_action_pressed` checked for modifiers.

2019-12-18 07:33 UTC, akien-mga commented
I pushed a revert for now with 3d6f991a1742d89640b4b2c104d602de00dc0741.

Maybe you can rebase this PR to readd the reverted changes (to fix the issues #30721 meant to fix) + your proposed changes (to avoid #34405), and we can assess this further for 4.0?

2019-12-18 21:12 UTC, NilsIrl commented
@akien-mga actually this fixes the problem.

For some reason my local settings had some different bindings making me think and claim at #34405 that this didn't work.

Also neikeq was requested for review because of some git stuff, trying to merge...... So he isn't acutally code owner of the modified part.

2019-12-18 21:17 UTC, NilsIrl commented
These different bindings also lead me to think the same bindings was used for prev/next tab and focus prev/next and that one was used over the other depending on context. When actually they have distinct bindings.

2020-07-01 06:38 UTC, aaronfranke commented
@NilsIrl Is this still desired? If so, it needs to be rebased on the latest master branch.

2021-04-08 00:22 UTC, EricEzaM requested changes

2021-04-08 00:22 UTC, EricEzaM commented on scene/main/viewport.cpp
> +			if (!k->get_control() && !k->get_alt() && !k->get_metakey() && k->get_shift() && p_event->is_action_pressed("ui_focus_prev") && input->is_action_just_pressed("ui_focus_prev")) {
I believe this can now use the `exact_match` parameter which was added to `is_action_pressed` and other related methods. See #44355

2021-04-13 17:46 UTC, Calinou commented
Note that this pull request likely conflicts with https://github.com/godotengine/godot/pull/47671, since they try to fix the same thing but in different ways.

2021-08-07 04:00 UTC, EricEzaM commented
Superseded by #51346, which I am convinced is the "proper" fix, using the exact match checking.

2021-08-07 11:59 UTC, Calinou commented
Closing per @EricEzaM's comment. Thanks for the contribution nonetheless!

2021-08-07 11:59 UTC, closed without merging