Add time scale property to Timer node (and update docs accordingly)
godotengine/godot pull request #34544
Opened 2019-12-22 17:04 UTC by wingedadventurer

Adds time scale property to the Timer node, allowing it to tick faster/slower.

Useful if you are implementing slow motion mechanic, and want specific Timer nodes to behave accordingly (Engine.time_scale won't cut it as it is applied to every node). Think games like Superhot, where game timer can either tick in real-time or in slowmo-time.

2020-07-01 06:34 UTC, aaronfranke commented
@wingedadventurer Is this still desired? If so, it needs to be rebased on the latest master branch.

2021-03-20 15:04 UTC, Calinou requested changes

2021-03-20 15:04 UTC, Calinou commented on scene/main/timer.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "time_scale", PROPERTY_HINT_EXP_RANGE, "0.01, 4096, 0.01"), "set_time_scale", "get_time_scale");
If a value of `0.0` is valid, we should allow it in the inspector. Also, the hint should allow more precision and use a lower maximum value for easier editing but allow manually entering greater values:

```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "time_scale", PROPERTY_HINT_EXP_RANGE, "0.0,100,0.001,or_greater"), "set_time_scale", "get_time_scale");
```

2021-03-20 20:06 UTC, Calinou approved these changes

2021-08-28 17:37 UTC, mhilbrunner approved these changes

2021-08-30 20:15 UTC, reduz commented
I don't see a proposal attached to this pull request. Additionally, just using Timer::set_wait_time and multiplying that time for a scale value will result in exactly the same effect, for which adding an extra function looks of little use to me.

I suggest closing it.

2021-08-31 01:59 UTC, aaronfranke commented
This was discussed on Godot's RocketChat. The consensus is that this change is not necessary as it can be easily worked around, and therefore this PR is not desired. Closing.

2021-08-31 01:59 UTC, closed without merging

2024-04-25 08:40 UTC, rpahut commented
> Additionally, just using Timer::set_wait_time and multiplying that time for a scale value will result in exactly the same effect, for which adding an extra function looks of little use to me.

Not if you need to engage slow motion and then turn it off, and then on again with a different multiplier, while the timer is ticking.