Improved MenuButton Description
godotengine/godot pull request #35223
Opened 2020-01-16 22:07 UTC by Feniks-Gaming

I expanded description of MenueButton to explain how to create the items inside of the pop up as this is initially a mystery to many new people.

2020-01-17 21:10 UTC, Feniks-Gaming commented
@Calinou this is minor change of 2 sentences, any chance I could get a quick review for it please? I know you guys are busy but it would be nice to push those easy wins with before 3.2 stable is out.

2020-01-17 22:12 UTC, Calinou requested changes

2020-01-17 22:12 UTC, Calinou commented on doc/classes/MenuButton.xml
> +		New Items can be created inside this [PopupMenu] with code using [code]get_popup().add_item("My Item Name")[/code]. You can also create them directly from editor. First select MenueButton and then
```suggestion
		New items can be created inside this [PopupMenu] using [code]get_popup().add_item("My Item Name")[/code]. You can also create them directly from the editor. To do so, select the MenuButton node, then in the toolbar at the top of the 2D editor, click [b]Items[/b] then click [b]Add[/b] in the popup. You will be able to give each items new properties.
```

2020-01-18 07:24 UTC, Feniks-Gaming commented on doc/classes/MenuButton.xml
> +		New Items can be created inside this [PopupMenu] with code using [code]get_popup().add_item("My Item Name")[/code]. You can also create them directly from editor. First select MenueButton and then
done

2020-01-18 08:25 UTC, merged

2020-01-18 08:25 UTC, akien-mga commented
Thanks!