Update cached_width of the line_edit element (#35699)
godotengine/godot pull request #35714
Opened 2020-01-29 19:54 UTC by sumit0190

The `cached_width` of the `line_edit` elements is not recalculated after the `pass` property is set/unset, or if the `secret_character` property is changed. This results in alignment issues, as evident from issue #35699.

The solution is to recalculate the width after these properties are touched; my change creates a small helper function that can be called after these properties are set in their respective setter methods.

NOTE: I just saw that the indentation looks a little weird; it appeared fine on my end, so I'll change it after the first round of review is complete.

2020-01-31 08:26 UTC, Paulb23 reviewed
Thanks for the contribution. Couple of indent issues otherwise LGTM,

Could refactor `Ctrl+U` and `append_at_cursor` to use the method as well.

2020-02-02 23:12 UTC, sumit0190 commented
@Paulb23 Many thanks for the review. I've fixed the indentation and incorporated your suggestions (hopefully correctly).

2020-02-03 18:24 UTC, Paulb23 requested changes
Code looks good.

There are still some indent issues, I would recommend setting up the clang formatter locally, a guide can be found [here.](https://docs.godotengine.org/en/3.2/community/contributing/code_style_guidelines.html#using-clang-format-locally)

2020-02-08 15:51 UTC, sumit0190 commented
@Paulb23 Thanks for that link; I've formatted the changes using `clang-format`, I hope I got it right this time!

2020-02-08 17:26 UTC, Paulb23 approved these changes

2020-02-08 22:43 UTC, merged

2020-02-08 22:43 UTC, akien-mga commented
Thanks!

2020-02-14 14:56 UTC, akien-mga commented
Cherry-picked for 3.2.1.