Add visual feedback when hovering or dragging the code minimap grabber
godotengine/godot pull request #35859
Opened 2020-02-02 18:53 UTC by Calinou

This makes it more obvious that the minimap grabber can be dragged to scroll.

## Preview

2020-02-02 19:54 UTC, YeldhamDev commented
I think at this point the vertical scroll should be hidden when the minimap is enabled.

2020-02-02 20:14 UTC, Calinou commented
@YeldhamDev It's still displayed in Visual Studio Code for comparison:

![Minimap in Visual Studio Code](https://user-images.githubusercontent.com/180032/73614602-e68a7780-4600-11ea-828c-09f1104cc136.png)

Personally, I'd leave it in as it gives you a better idea of how long the current script is.

2020-02-03 18:35 UTC, Paulb23 reviewed
Code looks fine.

Though as an improvement, the minimap should not be highlighted during text selection.

2021-08-30 10:33 UTC, Paulb23 commented
@Calinou  Any chance of rebasing and addressing the above feedback?

One more note as of now, `get_local_mouse_position` should be replaced by `get_local_mouse_pos` for RTL.

2021-09-02 20:33 UTC, Calinou commented
Rebased and tested again, it works successfully.

2021-09-03 22:16 UTC, Paulb23 requested changes
Looks good, couple small notes inline.

2021-09-03 22:16 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +			print_line("no longer hovering");
Can remove this print.

2021-09-03 22:16 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +		print_line("now hovering");
Ditto

2021-09-03 22:16 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +	const bool new_hovering_minimap = row >= get_first_visible_line() && row < get_last_full_visible_line();
This seems to need `row <= get_last_full_visible_line()` to handle hovering past the end of the script.

2021-09-04 08:40 UTC, Paulb23 approved these changes
LGTM.

2021-09-06 14:22 UTC, merged

2021-09-06 14:22 UTC, groud commented
Thanks!