Fix false positive "Unreachable code" warning for loops
godotengine/godot pull request #35900
Opened 2020-02-04 08:53 UTC by yamgent

1. The first commit is to fix #35775. It will fix erroneous reports in these two cases:

```gdscript
func a():
	var arr = []
	for i in arr:
		return i
	# can be reached, but buggy analysis says cannot
	return -1

func b():
	var should_loop = false
	while should_loop:
		return 1
	# can be reached, but buggy analysis says cannot
	return 0
```

2. The second commit exist, because I notice that the intention of the `has_return` variable has clearly evolved as new fixes are pushed (see previous problems with erroneous "unreachable code" such as #25955 and #30458). I feel that the name `has_return` is now less appropriate as a result. I propose the new name to be `has_unconditional_return`, for blocks that has an "unavoidable" return statement. Name feels a bit long though, so I am open to any suggestions to improve the name.

2020-03-31 00:47 UTC, cgbeutler commented
Would this, by chance, fix using `continue`s as well? The below give the warning:

```gdscript
for i in 100:
	continue
	return 1
# warning here
return 0
```

2020-03-31 06:53 UTC, akien-mga commented
@cgbeutler The warning line might be off by one, the `return 1` in your example *is* unreachable.

2020-03-31 07:43 UTC, cgbeutler commented
I did kinda over simplify, but the issue is still there. In my real code I loop over a range of profile IDs in search of a usable one. It looked cleaner to continue from the various fail conditions and only return if all checks passed. Sadly, I get the false warning that makes it not-so-clean.

2020-04-24 14:12 UTC, vnen requested changes

2020-04-24 14:12 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +				p_block->has_return = false; // while body may never execute
`has_return` is already `false` by default, you can just remove the line. Resetting it to `false` may be wrong if there was a `return` before the `while` statement.

2020-04-24 14:12 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +				p_block->has_return = false; // for body may never execute
Same as above.

2020-05-16 13:03 UTC, yamgent commented
@vnen Fixed! Apologies for the delay, been pretty busy lately.

 @cgbeutler I tested a variant of your example and it seems to work, so I hope it solves your issue.

2020-05-20 23:14 UTC, vnen approved these changes

2020-05-21 09:00 UTC, merged

2020-05-21 09:00 UTC, akien-mga commented
Thanks!

2020-05-25 14:31 UTC, akien-mga commented
Cherry-picked for 3.2.2.