Perform a single recovery step and reverse the maximum penetration instead of the sum before testing motion.
godotengine/godot pull request #35945
Opened 2020-02-06 08:35 UTC by madmiraal

Fixes most of the jitter seen when using either `move_and_collide()`, `move_and_slide()` or `move_and_slide_with_snap()` and colliding with multiple surfaces. This is especially noticeable when two `BoxShape` `CollisionShape`s collide, for example a box shaped character on a `GridMap`.

Fixes #34596.
Fixes #35713.
Fixes #35780.

2020-02-07 18:25 UTC, reduz commented
No, I don't think this is a good idea, you may go into corners that apply opposing forces (like this _\), so you need the recovery to be iterative to always work.

The jitter is probably due to something else, I would suggest bisecting.

2020-02-07 19:01 UTC, AndreaCatania commented
The jittering is caused by that, but I agree that's not safe remove it.

The best solution would be change how it works entirely.

2020-02-07 19:04 UTC, AndreaCatania commented
In the past I worked on another approach to solve this issue, if you want I can make a proposal @reduz.

2020-02-08 13:29 UTC, madmiraal commented
Before I address @reduz's concern, I think I need to clarify a few things.

This PR resolves the issue of the jitter being noticeable when a `KinematicBody` using `move_and_collide()`, `move_and_slide()` or `move_and_slide_with_snape()` collides with multiple parallel surfaces as reported in #34596, #35713 and #35780. It does not solve the issue of all visible jitter, which still remains and is noticeable in #32182.

The jitter reported in #34596, #35713 and #35780 is noticeable, because the oscillations are greater than 0.01. After this PR the remaining jitter is not noticeable, because the oscillations are less than 0.0001. The jitter (> 0.01) first became noticeable in Godot Physics with 3.1-stable after f2e54057aec3a4e4fbb9f9da5729915deb2f4648, which "moved `EditorDefaultValue` to `ClassDB`" i.e. exposed the issue rather than caused it. The jitter first became noticeable in Bullet Physics with 3.2 alpha 1 with 6dd65c0 a.k.a. #27415, which fixed Bullet Physics to allow for multiple collisions. The cause of the remaining jitter in #32182 (and probably #18433, #20593, #31981, etc.) is subtly different in Godot Physics and Bullet Physics. I have not bisected it to discover its source, because I suspect that it's always been there.

The jitter and the other related issues occur, because the calculation of the safe movement is failing, and the body is then moved into an unsafe position. In Godot Physics, the calculation is failing, because it is not correctly incorporating the collision margin. In Bullet Physics, the calculation is failing, because it's not detecting collisions. Note: when Bullet Physics does detect a collision, it doesn't record the collision details, which causes #26550. A complete solution requires safe movement to be calculated correctly. Unfortunately, I've not yet been able to find a successful solution to this problem.

Moving the body into an unsafe position is not a major problem, because the body is quickly moved into a safe position through the recovery step. In Godot Physics, the recovery step is performed at the start of the next call to move_and_collide(). In Bullet Physics, the recovery step is called at the end of every call to move_and_collide(). However, the calculation of the recovery step is also flawed.

Currently, the recovery step sums the penetration vectors (distance x normal) from each collision shape the body is colliding with. This works when collision shapes are orthogonal e.g. a corner, but not with collision shapes that have normals with components in the same direction e.g. aligned boxes. The extreme case being a `BoxShape` `CollisionShape` character on four aligned `BoxShape` `CollisionShape`s such as a `GridMap`. The resultant recovery vector is 4x the length of the correct recovery vector. Even when scaled by 0.4, the recovery vector is still 1.6x the required length. The visible jitter is more extreme in Bullet Physics, because Bullet Physics only scales the vector at the beginning of the call to `move_and_collide()` and not at the end, which is what is being used to move the body into a safe position.

This PR does two things:
1. Uses the maximum penetration instead of reversing the sum.
2. Performs a single recovery step instead of 4 x 0.4.

The first change resolves #34596, #35713 and #35780, by using the maximum distance of each component, similar to creating an inverted `AABB`. This ensures that the recovery step is exactly what is required. This works in a corner (_rincón_, but not _esquina_, see #32182), because the orthogonal components are still added together. The second change is implemented, because Bullet Physics already uses a single step.

With regards @reduz's concern. There is a possibility that the recovery step can push the body into another body that it's not currently colliding with. This problem exists whether a single step or iterative partial steps are used. This is the reason, the current implementation needs to limit the number of partial iterations to four. Since the recovery step is exactly what is needed to move the body into a safe place, if it cannot be moved into a safe place, it is, by definition, stuck. In the situation where the other body's collision surface is not parallel e.g. an inverted wedge, a second step could nudge the body away from the tight corner. However, in most circumstances, the `test_body_motion()` function is called in via `move_and_collide()` from a `_process()` loop; so this iterative step will happen anyway. Furthermore, the number of steps required is incalculable and depends on the level of parallelism.

In summary, until a solution is found for correctly calculating the safe movement, this patch ensures that the recovery motion is not excessive, which resolves the serious issues of #34596, #35713 and #35780 that will stop users migrating to 3.2, and it works in corners (_rincones_) too.

2020-02-10 11:02 UTC, reduz commented
@madmiraal I will check the code again soon when I have a bit of time, but I have the feeling you are not interpreting what is going on correctly. Even if you have recovery in the same direction, recovery happens only as a fraction of the penetration depth, so it never goes beyond that. This is exactly how all discrete physics engine work. The jitter is most likely just having to adjust the minimum penetration dept in Godot physics, but I am not sure about what is going on in Bullet, I would need to check it again.

2020-02-11 10:25 UTC, madmiraal commented
@reduz Just to clarify my understanding of the purpose of the first step in `test_body_motion()`. It's there to attempt to free a body if it is stuck before attempting to move it. This should be done incrementally, using partial steps, to ensure it doesn't then intersect with another `CollisionShape` that it's not currently colliding with.

I believe this is based on two assumptions:
1. Under normal circumstances the body is not stuck; therefore, most of the time, it's not required.
2. When it is required, and it collides with multiple shapes, these shapes will be orthogonal (an implicit assumption based on the implementation).

The first assumption is not valid, because this function is currently needed every time a previous call to `test_body_motion()` collides. As explained above, (in Godot Physics) this is due to it miscalculating the `safe` fraction (possibly due to not including the margin). When a body is being moved against a static object (e.g. when simulating gravity on a floor) this happens on every call to `test_body_motion()`. Therefore, I believe, gently nudging the body into a safe location is currently an unneeded luxury, and a single step will suffice; especially since gently nudging the body doesn't guarantee that it will be moved into a safe location anyway and Bullet Physics is using a single step already.

The second assumption is not valid when the body is colliding with multiple aligned surfaces e.g. a `GridMap`. Therefore, this PR proposes using the maximum value in each basis direction to avoid the cumulative error that is causing the visible jitter seen in #34596, #35713 and #35780.

2020-02-12 21:04 UTC, wareya commented
Noting that #18433 (mentioned in a previous comment here) is technically not about jitter but its particular behavior will still probably change as a result of this patch. The problem in #18433 applies even when colliding against a single planar surface and manifests in different ways depending on exactly how `move_and_collide()` is being used (typically some kind of downhill drag).

2020-03-22 13:48 UTC, VictorLamoine commented
Any update on this? For now I have compiled Godot using @madmiraal branch
Is there an other pull request solving this issue that has been merged and that I missed?

2020-04-01 15:14 UTC, madmiraal commented
Rebased following the renaming of servers. Since #34596, #35713 and #35780 are regression issues from 3.1 I'll create a separate pull request against the 3.2 branch with the original changes.

2020-04-04 08:06 UTC, madmiraal commented
Rebased following NULL to nullptr change.

2020-04-05 20:31 UTC, piratesephiroth commented
I tested this and it has no effect at all on the weird collisions of kinematicbody2d with slopes (#20593)

2020-04-12 10:31 UTC, madmiraal commented
Updated to also fix #18433, #26550 and #32182 and improve #31981. This change has been added to this PR, because the problems are all interlinked.

2020-04-12 10:37 UTC, wareya commented
The underlying problem in #18433 is not linked to jitter and can't be truly fixed without entirely removing overlap rectification from the code paths used by move_and_collide (i.e. breaking backwards compatibility or adding more optional arguments).

2020-04-12 10:42 UTC, madmiraal commented
@wareya The remaining jitter and the sliding seen in #18433 had the same cause. This has now been fixed and included in this PR.

2020-04-24 14:54 UTC, madmiraal commented
Added a fix for the sticking identified by @MBZSoftProds.

2020-04-27 15:35 UTC, reduz commented
@madmiraal 

>The first assumption is not valid, because this function is currently needed every time a previous call to test_body_motion() collides. As explained above, (in Godot Physics) this is due to it miscalculating the safe fraction (possibly due to not including the margin).

Actually, all this is done on purpose, and the reason it works this way is due to numerical precision. Assuming stuck by checking margin then move safely without margin. If it did not work this way, your body would approach the collision point infinitely and start causing precision problems. Again, all physics engines work like this to avoid running into this problem.

I will give an overhaul to the physics engine when I am done with rendering and will eventually check issues there, so from my side I will not do any work or changes on physics until I can spend time on it in some months.

2020-04-28 13:36 UTC, madmiraal commented
Setting aside the enticing discussion on how a physics engine should work and why collision margins are necessary, I think it’s important to focus on what is causing the issues and how this PR addresses them. Also, even if the approach in this PR is flawed, it should at least be considered as a workaround until the the physics engine is overhauled, because the issues it addresses are cited as one of the main reasons people are not moving to 3.2. The 3.2 version of this PR is #37498.

To be specific, the issues addressed are caused by the current implementation of `test_body_motion()` and `test_body_ray_separation()` which is used by `move_and_collide()`, which is used by `move_and_slide()`, which is used by `move_and_slide_with_snap()`, which are all only used by `KinematicBody`s in 2D and 3D. Godot’s Bullet implementation copies the Godot Physics approach, with some slight differences.

In the current implementation `test_body_motion()` is divided into three steps. In Godot physics these are:
- Move to a safe position with margin using 4 incremental steps.
- Test the motion without margin. If there is a collision, find the maximum safe proportion and minimum unsafe proportion of the desired motion.
- Use the unsafe proportion to extract collision information, and use the safe proportion to move the body.

In Bullet physics these are:
- Move to a safe position using 4 incremental steps.
- Test the motion with a tolerance equivalent to the margin. If there is a collision, use the minimum unsafe proportion of the desired motion.
- Use the unsafe proportion to move and extract the collision information, and then move to a safe position using a single step.

In the current implementation of both Godot and Bullet physics, the move to a safe position with margin is calculated by summing the vectors of the shortest penetration distance between each collision shape. When using 4 incremental steps this distance is multiplied by 0.4 and repeated 4 times.

The jitter described in the issues is caused by the move to a safe position being greater than the attempted motion. To simplify things, I’m only going to cover `test_body_motion()` with box `CollisionShapes` continually hitting multiple aligned box `Collisionhapes` in 3D i.e. a box character with a downward velocity (simulated gravity) on a `GridMap` of boxes. However the same applies to other `CollisonShape`s including `RayShapes` and 2D and shapes that are not aligned.


The current Godot implementation works for a body (pink) colliding with a single surface (blue) as follows:

![Godot Current 1 Surface](https://user-images.githubusercontent.com/9253928/80492658-42dd0900-895c-11ea-82f7-4d68252cdd73.png)

- Step 1: The penetration distance with margin (the dashed lines) between the body and the surface is calculated (a). This value is multiplied by 0.4 (the vector arrow between (a) and (b)). The body is moved out by this amount. This process is repeated up to four times (b), (c), (d) and (e). Although I’ve shown them as four separate steps, the movements are actually added together and only a single recovery movement is performed, but the effect is the same. Note that even after four iterations there still remains a penetration with margin.
- Step 2: The movement without margin is attempted (f). If there is a collision, the safe and unsafe distances are calculated.
- Step 3: The unsafe distance is used to gather the collision information, and the safe distance is used to move the body (g).

Since the distance between the body and the surface in (a) and (g) is roughly the same, no jitter is seen. However, when the body collides with four parallel surfaces, for example on a `GridMap` the current implementation results in jitter, because it works in the following way:

![Godot Current 4 Surfaces](https://user-images.githubusercontent.com/9253928/80492699-4f616180-895c-11ea-8873-1b1870146a7f.png)

- Step 1: The penetration distance with margin between the body and each of the four surfaces is calculated (a). The values for each of the four surfaces are added together and multiplied by 0.4 (the four vector arrow between (a) and (b)) for a total of 1.6x the penetration distance The body is moved out by this amount. Since the recovery motion is greater than the penetration distance, there is no longer any penetration with margin; so only one iteration is performed.
- Step 2: The movement is attempted (c). With reasonable motion values, there is no collision.
- Step 3: The body is moved (d).
In the next frame, steps 1-3 are repeated as follows:
- Step 1: The penetration distance with margin between the body and each of the four surfaces is calculated (e). There may or may not be a recovery motion. However, if there is any penetration with margin only one iteration will be performed, because the recovery motion will be the penetration distance multiplied by 1.6.
- Step 2: The movement is attempted (f). There may or may not be a collision.
- Step 3: The body is moved (g).
Jitter is seen because the distances between the body and the surfaces at end of each frame (a), (d) and (g) are all different.

This PR proposes modifying the calculation of the recovery motion by using the maximum penetration distance of each surface instead of summing them together, and only performing a single iteration instead of four. This results in the following when the body collides with a single surface:

![Godot Proposed 1 Surface](https://user-images.githubusercontent.com/9253928/80492744-5daf7d80-895c-11ea-9e48-9096201d6855.png)

- Step 1: The penetration distance with margin between the body and the surface is calculated (a). The body is moved out by this amount (b). Note that there is now no penetration with margin.
- Step 2: The movement without margin is attempted (c). If there is a collision, the safe and unsafe distances are calculated.
- Step 3: The unsafe distance is used to gather the collision information, and the safe distance is used to move the body (d).

Since the distance between the body and the surface in (a) and (d) is roughly the same, no jitter is seen. When the body collides with four parallel surfaces, for example on a `GridMap` the proposed approach works in exactly the same way:

![Godot Proposed 4 Surfaces](https://user-images.githubusercontent.com/9253928/80492763-63a55e80-895c-11ea-8068-f849452e7360.png)

- Step 1: The penetration distance with margin between each of the four surfaces is calculated (a). The body is moved out by the difference between the maximum and minimum (negative) amount in each axial direction (b). If possible, i.e. the body is not stuck, the body will be moved to a position with no penetration distance with margin an no more! Note, if the body is stuck in an axial direction it will be moved the median position.
- Step 2: The movement without margin is attempted (c). If there is a collision, the safe and unsafe distances are calculated.
- Step 3: The unsafe distance is used to gather the collision information, and the safe distance is used to move the body (d).

The result is exactly the same as for a single surface, hence no jitter is seen.

For Bullet physics the situation is slightly different, when the body is colliding with a single surface it works as follows:

![Bullet Current 1 Surface](https://user-images.githubusercontent.com/9253928/80492793-6bfd9980-895c-11ea-8757-6571d48ca894.png)

- Step 1: The body is checked to ensure it is not currently colliding with the surface (a). Generally it’s not, but numerical errors in the depenetration algorithm may result in it being moved slightly. Note: if it is moved it is only moved 0.4 times the residual penetration and this is repeated four times, which, as explained in the current Godot physics with one surface, will not actually result in complete depenetration.
- Step 2: The movement is attempted with a tolerance equivalent to the collision margin (b). With reasonable motion values, there is no collision.
- Step 3: The depenetration [...]

2020-04-29 13:59 UTC, madmiraal commented
Rebased following merge of #37314.

2020-04-30 18:18 UTC, MBZSoftProds commented
Any word on when this might find it's way into a release like 3.2.2? Collision is unreliable to the point where it's hard to figure out if it's Godot or my code.

2020-05-14 11:34 UTC, unit73e commented
> Also, even if the approach in this PR is flawed, it should at least be considered as a workaround until the the physics engine is overhauled, because the issues it addresses are cited as one of the main reasons people are not moving to 3.2.

Not just that but I spent a few days figuring out why a simple KinematicBody (a cube) would bump or jitter in the intersections of a GridMap of cubes. The worst case being an intersection of 4 cubes. This patch is in my opinion essential for any newbie because frustration is a deal breaker. I'll be using Godot 3.1 until this is fixed or maybe this version if I need new features.

2020-05-14 14:47 UTC, madmiraal commented
Rebased following #38697.

2020-05-23 11:04 UTC, madmiraal commented
Rebased following #38738.

2020-06-30 14:00 UTC, akien-mga commented on servers/physics_2d/space_2d_sw.cpp
> +	if (p_object->get_type() == CollisionObject2DSW::TYPE_AREA && !p_collide_with_areas)
You lost braces when rebasing.

2020-06-30 15:25 UTC, madmiraal commented on servers/physics_2d/space_2d_sw.cpp
> +	if (p_object->get_type() == CollisionObject2DSW::TYPE_AREA && !p_collide_with_areas)
Updated with braces reinstated.

2020-07-08 08:09 UTC, madmiraal commented
Removed superfluous line as suggested [here](https://github.com/godotengine/godot/pull/37498#discussion_r451239897).

2020-07-14 13:36 UTC, reduz commented
This has been fixed in GodotPhysics by #40377, the bug was that the safe margin was not being passed correctly to the function in all cases. the bug was introduced by #12713 but it was masked for a long time until f2e5405 exposed it.

I suggest closing this PR and instead ensuring that Bullet test_body_motion works the same as in GodotPhysics.

2020-07-14 17:19 UTC, madmiraal commented
@reduz I think #40377 is complementary to not a replacement of the jitter fixed in Godot Physics 3D in this PR. As mentioned in [my review](https://github.com/godotengine/godot/pull/40377#pullrequestreview-448303562), #40377 doesn't fix all the jitter in Godot physics, but it does fix the remaining jitter that isn't fixed with this PR. Also the approach used in #40377 doesn't work with 2D, because the minimum contact depth in 2D is set to 0.005. It works in 3D, because the minimum contact depth is 0.00001.

2020-07-14 17:31 UTC, reduz commented
@madmiraal As I mentioned before I think the small jitter (when invisible) is fine. If it helps, I think at some point I changed the code so the margin was min(motion_distance,safe_distance) and this eliminated the jitter, but it caused other complications in some scenarios that I can't remember at the time. I really experimented with this stuff for many years and on many shipped games and came to the conclusion having the small (in practice, invisible) jitter is better than trying to work around it.

2020-07-19 14:27 UTC, madmiraal commented
I've rebased this PR following #40377; so people using this branch can have its benefit too.

@reduz Even with #40377, on a `GridMap`, Godot physics 3D still has sufficient jitter for `on_floor()` to alternate between `true` and `false`.
MRP v4.0: [40377.4.0.zip](https://github.com/godotengine/godot/files/4943791/40377.4.0.zip)
MRP v3.2: [40377.3.2.zip](https://github.com/godotengine/godot/files/4943792/40377.3.2.zip)

This is due to the fact (even with kinematic_safe_margin = 0.001) the distance recovered is still 0.00640, because the current approach adds all the collision distances together (before multiplying by 0.4) and with a `BoxShape` colliding with the four `GridMap` `BoxShapes` there are 16 collisions!

If gravity is simulated using ```velocity.y += -9.8 * delta```, the distance travelled when starting from 0 (after colliding with the floor) is only 0.00272, which is not enough to cover the recovery distance of 0.00640. Hence no collision and `is_on_floor()` returns `false`, until the next frame the velocity and distance will have increased sufficiently to cover the remaining distance.

By only recovering the maximum distance of all the collisions, as is done in the PR, the recovery distance is the kinematic_safe_margin i.e 0.001, which is covered by the distance moved under normal gravity of 0.00272, and `is_on_floor()` continually returns `true`.

2020-07-21 13:31 UTC, madmiraal commented
Rebased following #40489.

2020-07-27 07:18 UTC, hoontee commented
Would this fix #40710 or #40739?

2020-08-24 12:15 UTC, stoikerty commented
While I appreciate some would prefer this to be implemented in a different way, I feel that @madmiraal has explained his approach in utmost detail and I don't fully understand why releasing the change would be held back for so long.

I have been using Godot for roughly 3 months now and pretty much since the beginning I have been avoiding using GridMap (which I believe to be one of the best Godot features). As others have pointed out, I too thought that I was doing something wrong in my code and wasted time trying to resolve it. This jitter is a fairly frustrating issue to encounter when starting out.

2020-09-19 12:40 UTC, vesk4000 commented
Thanks a lot for the commit! I really hope that it is finally added to master.

2020-09-19 13:05 UTC, vesk4000 approved these changes
Great commit, very important changes that need to be implemented in Godot as soon as possible.

2020-10-04 16:22 UTC, shackra commented
any news with the revision of this PR?

2020-10-04 17:21 UTC, madmiraal commented
Rebased following merge of #42518.

2020-11-18 08:17 UTC, madmiraal commented
Rebased following merge of #38812.

2020-11-20 08:47 UTC, mindinsomnia commented
Hopefully this can be reviewed and merged soon.

2021-01-08 04:09 UTC, pouleyKetchoupp requested changes
I've checked all of these issues again, and almost all of them are specific to Bullet now, or already closed.

The only exception was #34098, and I've made a specific fix for Godot Physics (#45005).

So at this point, I would rather remove the changes in Godot Physics and make this PR Bullet specific.

2021-01-10 10:56 UTC, madmiraal commented
Rebased following merge of #42574.

2021-01-10 11:42 UTC, madmiraal commented
> I've checked all of these issues again, and almost all of them are specific to Bullet now, or already closed.
>
> The only exception was #34098, and I've made a specific fix for Godot Physics (#45005).
>
> So at this point, I would rather remove the changes in Godot Physics and make this PR Bullet specific.

This PR does more than just fix the issues listed. As explained in the commit message:
> The test_body_motion() and test_body_ray_separation() functions perform an
initial recovery step to attempt to move the body to a safe place before
testing whether the body can safely move. Currently this is done in four
partial steps, and during each step the detected penetrations are reversed
by summing them together.
> 
> This patch changes this approach to a single step and uses the maximum
penetration instead of the sum. The same approach is applied to Godot
Physics 2D, 3D and Bullet Physics, and to both CollisionShapes and
RayShapes.

#42574 improved the situation for Godot physics by changing the size of the partial recovery steps so that:
1. When colliding with a single shape, a full recovery step is performed. However, it still unnecessarily requires two steps.
2. When colliding with multiple shapes, the size of the summed penetrations is divided by the number of shapes. This reduced the likelihood of the recovery step being too large (the source of the jitter) and works well for standard `BoxShape` `GridMap`s. However, not only does it unnecessarily require four steps to achieve this, it will not fully recover if the number of shapes it is colliding with is greater than four.

This PR addresses the limitations of the solution included in #42574 by:
1. Only performing a single recovery step.
2. Ensuring that (if a full recovery is possible i.e. the `KinematicBody` is not stuck) the body is fully recovered.

2021-01-11 19:38 UTC, pouleyKetchoupp commented
@madmiraal There's no reason to change entirely the way recovery works in Godot Physics if it doesn't fix any known issue, so I'd like to aim at specific fixes instead.

Having multiple recovery steps makes the process bulletproof for cases with more than one shape around, where getting the body unstuck from one shape could cause penetration with another one. It's iterative, and that's what makes it robust in comparison to doing just one step with the exact recovery distance.

> it will not fully recover if the number of shapes it is colliding with is greater than four.

Looking at the code again, I would be up for fixing this case specifically and make the recovery more robust. Could you open a separate PR with just the changes on the recovery motion to use min/max on each axis instead of processing by addition? I'll also test it against existing cases. This seems like the proper calculation and it shouldn't hurt.

2021-01-16 19:03 UTC, pouleyKetchoupp commented
Closing this PR for now as it does too many unrelated things and got stale. We can't keep it open undefinitely with so many linked issues, and confuse contributors into not fixing them if needed.

Anyone feel free to open separate PRs for the different issues to address:
- Bullet fixes for `test_body_motion`: since it's working much better in Godot Physics now, the best approach is to mimic what Godot Physics does as closely as possible (given that it still requires some hacks).
- Fix recovery motion using min/max instead of addition to solve a potential issue (no repro so far) with more than 4 colliding shapes (see https://github.com/godotengine/godot/pull/35945#issuecomment-757461991 and https://github.com/godotengine/godot/pull/35945#issuecomment-758177410 for details).
- #18433 still needs a fix in Godot Physics for the case mentioned in https://github.com/godotengine/godot/issues/18433#issuecomment-758724209.
- #34098 has an open PR already: #45005 (needs review).

And for the last topic:
- Limiting recovery to only one step instead of 4 iterations is not desirable, either in Bullet or Godot Physics, and doesn't fix any known issue afaik (see https://github.com/godotengine/godot/pull/35945#issuecomment-758177410 for details).

2021-01-21 18:57 UTC, pouleyKetchoupp commented
Re-opening this PR while the physics team goes through the proper process of reviewing what direction to go and finds a consensus.

2021-01-27 17:01 UTC, reduz commented
@madmiraal I will try to explain this here since I did not have the opportunity during the last meeting.

To me the actual issue _is_ fixed in Godot physics. The issue that the pull request also addresses (several collisions on various fronts) is not something games will encounter simply because, in reality, things either fit or not but not "just fit" (I mean whathever you collide to has to actually reach this scenario, which is likely impossible) so in these cases, users just realize this and shrink the kinematic body a tiny bit to solve the problem. Just think about it, you will realize it's not a realistic use case.

What I mentioned before is that the depenetration needs to be iterative or else you will find other problems, but I am not against checking for max and min motion on either direction to avoid the jitter in the situation you mentioned. That part can be extracted fine, which is what we were discussing with @pouleyKetchoupp. Again, I don't think this is an use case users will find, but adding the max and min anisotropic test should solve the problem you mention.

2021-01-30 13:14 UTC, madmiraal commented
@reduz I agree that most of the jitter is fixed in Godot physics with #40377, #42574 and #45361 (unmerged). I also agree that the scenario of several collisions on more than three fronts (a corner) is unlikely, but it's not impossible: NPCs could trap the player in the corner resulting in collisions on six fronts; a large player could collide with any number of floor tiles; etc. I also agree that the PR doesn't fix any Godot physics related open issues, but, as [previously stated](https://github.com/godotengine/godot/pull/35945#issuecomment-757461991), it does improve Godot physics by:
1. Only performing a single recovery step.
2. Ensuring that (if a full recovery is possible i.e. the `KinematicBody` is not stuck) the body is fully recovered.

So I'm glad you agree that "checking for max and min motion on either direction to avoid the jitter" is a good solution i.e. point 2.

Therefore, it appears that the only disagreement is around point 1. You state:

> the depenetration needs to be iterative or else you will find other problems

I don't understand why you think the depenetration needs to be iterative. What other problems will we find? If, as you say, *"things either fit or not ... whathever you collide to has to actually reach this scenario from a previous one where it's not colliding, which is likely impossible,"* what scenario would require an iterative depenetration?

2021-01-30 13:23 UTC, madmiraal commented
Rebased following merge of #45519.

2021-01-30 18:01 UTC, pouleyKetchoupp commented
> I don't understand why you think the depenetration needs to be iterative. What other problems will we find? If, as you say, "things either fit or not ... whathever you collide to has to actually reach this scenario from a previous one where it's not colliding, which is likely impossible," what scenario would require an iterative depenetration?

As an example, think about a sphere in a corner with an angle < 45 degrees. You can overlap with one side while depenetrating from the other side. An iterative process can unstuck the body from this situation.

2021-01-30 19:10 UTC, Zireael07 commented
Regardless of the eventual decision, I think iterative depenetration should be left for another, follow-up PR (if decided on). This PR contains a lot of needed physics fixes.

2021-01-30 19:16 UTC, pouleyKetchoupp commented
@Zireael07 Iterative depenetration is how it currently works and this PR changes it to one iteration.

2021-01-30 22:12 UTC, reduz commented
@madmiraal here is a simple example of why you need depenetration to be iterative:
![image](https://user-images.githubusercontent.com/6265307/106369291-e4035080-632e-11eb-8094-8d1a64d4c94d.png)

This simply can't be solved in one go, while if you leave it be for a couple of frames it will eventually converge to the right position. This is why physics engines solve iteratively.

2021-01-30 22:29 UTC, reduz commented
@madmiraal Again, check any other kinematic controller implementation such as [Bullet](https://github.com/bulletphysics/bullet3/blob/master/src/BulletDynamics/Character/btKinematicCharacterController.cpp#L313) or [PhysX](https://github.com/NVIDIAGameWorks/PhysX-3.4/blob/master/PhysX_3.4/Source/PhysXCharacterKinematic/src/CctCharacterController.cpp#L801) you will see all do the same thing because it's the only possible way it can be done. I have no idea how else to explain it.

2021-01-30 23:41 UTC, reduz commented
@madmiraal So, the reason why the min-max is a good idea and we could probably still add it, even though it's unrelated to this is because of a different reason.

If you think about it, the right way to implement depentration is to actually _move_ the object for each collision it encounters and then re-test collisions against everything else. If you do this, even if you have multiple collisions pointing to the same side, it will never move more than intended and it will converge in less iterations and more precisely to the right place.

But, the problem is that this is more expensive. Besides moving it you need to re-check the broadphase to see if it now collides against something it did not before. Instead, for the sake of performance, we just take the deepest collisions and simply depenetrate against that, which is more incorrect and in some situations can lead to over-depenetration. This is what causes the jitter you see. So, this jitter is intended from the start, but it's meant to be so small that users don't really see it and will not care about it. 

The actual problem in this bug is that the margins were wrong, so jitter is visible, so you assumed that jitter was the problem when it actually it was just about wrong margins. The one step solving is wrong because of what I mentioned above, but the minmax hack actually has merit as it's not expensive and it will reduce (albeit not eliminate) jitter and it's inexpensive. This is why @pouleyKetchoupp was offering to salvage just this part from the PR.

2021-02-01 17:48 UTC, madmiraal commented
I have tested and analysed the circle/sphere shape in a wedge and I have not found a problem with the approach used in this PR. In fact, I have found that the approach used in this PR actually improves the situation.

First, for the benefit of others reading this, I want to clarify the situation presented. Since, we're assuming that "things either fit or not" the circle shape would not overlap the shapes creating the wedge. Therefore, for a 30° wedge, the worst case scenario would look like this:
![PR 35945 Wedge](https://user-images.githubusercontent.com/9253928/106492094-7599cc00-64af-11eb-9800-6987fc5f9ded.png)
The black dashed line represents the `KinematicBody2D` `Safe Margin`, which is used by Godot physics' method `test_body_motion()` method first step (free the body is stuck). The red arrows represent the vectors used to attempt to "free" the `KinematicBody2D`. The smaller red arrows represent their their x- and y-components. The green arrow represents the resultant movement.

Despite using different methods to calculate the green arrow, the direction of the resultant movement (the green arrow) is the same for both the current approach and the approach used in this PR. The difference is the length of the green arrow and the number of times the green arrow is calculated and the `KinematicBody2D` is moved (the iterations).

With the current default `Safe Margin` of 0.08 and a wedge angle of 30°, the length of the green arrow is calculated to be:

Iteration | 3.2.3 | 3.2.4.rc1 | 3.2.4.rc1+PR35945
-- | -- | -- | --
1 | 0.0299 | 0.0373 | 0.0746
2 | 0.0187 | 0.0199 |  
3 | 0.0117 | 0.0106 |  
4 | 0.0074 | 0.0057 |  
**Total** | **0.0677** | **0.0735** | **0.0746**

This shows that this PR does a better job i.e. moves it further – in one step – of "freeing" the `KinematicBody2D` than the method used in 3.2.3 or the #42574 modified approach included in 3.2.4.rc1.

2021-02-02 03:01 UTC, reduz commented
@maadmiral Yeah I guess in this case yours will give a similar result because it's vertical, and because the original approach is not actually moving the object, but the recovery vector, so in this very specific case it's not fundamentally that different. That said, I still think it's not a great idea. 

Again, as I mentioned in my previous post, the way I see things are:

1) Doing the iterative process correctly is expensive, prefer to not to do it.
2) The current iterative solver likely takes too many shortcuts. It may be possible to improve and make it closer to the correct way it should work, but honestly other physics engines don't care about correctness on this either. I have some ideas I would like to try, maybe in some days, but honestly I still think it's not worth it.
3) Your approach is wrong, I am sorry coming with examples of why it's difficult, but after you try these things for a while you realize that cutting corners this way sooner or later has side effects, so I am never going to approve it no matter how much you insist. Please don't be offended about it. I apologize that I should have been clearer on this earlier.

Again, the way I see it, I really believe all this is a waste of time because I consider the problem solved already. I am open to looking for ways to improving the approximation to the "correct" solver, but not to cut corners like this.

2021-02-02 03:21 UTC, mindinsomnia commented
I do not know if any such tests exist or not, but if not, perhaps it would be worth exploring creating some tests to verify results of depenetration methods?

The results could be used to confirm whether or not @madmiraal 's approach could work, and also be useful for identifying regressions for any later changes to physics, which could be important in the near future given the significant amount of work related to physics in Godot that is planned.

2021-02-02 03:40 UTC, reduz commented
@mindinsomnia The problem is that his approach cuts too many corners, as well as being anisotropic (diagonals wont work as well), when you do these kind of things, in my experience, you are not really certain what will fail (because all examples you can think of will work) until it fails (in a situation you did not think about). It's a sort of experience about not trusting certain types of solutions to problems that you get you grow up doing these things over and over again.

2021-02-02 03:57 UTC, reduz commented
![image](https://user-images.githubusercontent.com/6265307/106550111-3f7d3c00-64f1-11eb-8474-6aa351ee2772.png)

Also, I had to think a bit more, but here is a better example that will not work with this PR. Because the recovery is anisotropic, this will produce no recovery at all (which should be towards the upper right diagonal), and most likely cause the sphere to fall through the bottom.

2021-02-02 17:42 UTC, Riteo commented
Sooo... Will this be PR closed, or will it stay open until all the good bits are taken out?

2021-02-02 18:06 UTC, reduz commented
@wareya That is not really the problem that this PR is attempting to solve. (TBH the real problem here is that this should work for users in Godot Physics right now and nobody ported the same fix to Bullet).

@Riteo I want to experiment a bit more with this in the coming days, but I need to finish my upcoming PR.

2021-02-03 15:41 UTC, reduz commented
Here are some extra thoughts on this. You guys got me involved, so now bear with me :)

So, here are my two proposed solutions, one for a more robust one-step solver (non-iterative) and another for a more robust iterative one.

For a one-step solver, this is the best I can come up with. I tried this approach in the new particle collider and it seems to work very well. Its kind of similar to what this PR attempts to do, but does not have the anisotropy limitation.

```c++
Vector2 recover_motion;
for (int i = 0; i < cbk.amount; i++) {
    Vector2 a = sr[i * 2 + 0]; //own point
    Vector2 b = sr[i * 2 + 1]; //foreign point

    Vector2 n = b-n; 
    real_t l = n.length(); //collision length
    n.normalize(); //collision normal
    
    l -=MAX(0, n.dot(recover_motion)); //maximum amount you can move in this direction, without accumulating
    if (l > 0.0) {
        recover_motion += n * l;    
    }
}
```
What this does Is just push away the contact, but ensure it never pushes again more than the maximum depth in a given direction. In my view, this is what, in my mind, the _correct_ version of this PR would be. I am still not sure if I prefer this over an iterative solution, given the iterative solution is a lot more robust.

So I tried to come up with a more correct iterative solution and this is what I have so far. I think it would be worth testing as it requires minimal change to what there is now:

```c++
Vector2 recover_motion;
for (int i = 0; i < cbk.amount; i++) {
    Vector2 a = sr[i * 2 + 0]; //own point
    Vector2 b = sr[i * 2 + 1]; //foreign point

    //compute plane on b towards a
    Vector2 n = (a-b).normalized();  //normal
    float d = n.dot(b); //distance

    //compute depth on recovered motion
    real_t depth = n.dot(a + recover_motion) - d;
    if (depth > 0.0) { //only recover if there is penetration
        recover_motion -= n * depth * 0.4;
    }
}
```
The above is more close to how a correct iterative solver would work, as it considers motion (something the the current one does not) and I think it should also solve the jittering problem. Of course I may be wrong so all this need to be tested, so If you guys want to give a check to this or discuss these ideas, let me know.

2021-02-07 16:36 UTC, madmiraal commented
Rebased following merger of #45564.

2021-02-14 13:14 UTC, madmiraal commented
Rebased following merge of #43952.

2021-08-31 16:48 UTC, reduz commented
I am closing this pull request for the following reasons:

* The issue it attempts to fix is resolved in master using a more conservative technique.
* Lack of interest by the author in further discussion.

I think this is a very interesting and clever idea, and it is entirely possible that in practice it solves all possible cases that may arise, besides being far more efficient. 

The reason it was not adopted is that, given how unconventional it is, It is not possible for us to establish with 100% confidence that it will not have future side effects or fail in very specific situations. Given this is such a critical and often used piece of the engine, a more traditional approach using an iterative solver was preferred.

I am still thankful and appreciative of all the effort  that went into this, which contributed to making Godot a much better piece of free and open source technology for everyone.

2021-08-31 16:48 UTC, closed without merging