Fix: auto brace complete for quoted strings
godotengine/godot pull request #36089
Opened 2020-02-10 22:12 UTC by dreamsComeTrue

When inside of string (single or double-quoted) - disallows of completing other type of qutoes:

E.g: typing `'` inside of `""` String emits only one `' `character (and vice-versa).
Also works with escaped characters (`\'` and `\"`)

Fixes #36002

2020-02-10 22:15 UTC, dreamsComeTrue commented
Although those two code-blocks look like they could be merged into one big `if `statement, they can't. There are very specific use cases, for which order of those `if `checks matter.

2020-02-13 21:40 UTC, Paulb23 requested changes
This breaks auto-quote-completion if you use more then one escape char, i.e. adding quotes at the end of a line that looks like this: `var test = "\\"`

I would suggest taking a look at `TextEdit::Text::_update_line_cache` colour region loop to see how strings are currently calculated.

2020-02-21 22:09 UTC, dreamsComeTrue commented
Thanks for that hint - I've took one part from that place (omitting escapes) and cleaned overall solution a bit. 

I've spent last 20 minutes trying to break it in every possible way - with various single and double quotes combinations, using escapes, inserting text at the beginning, in the middle or at the end - and for all of my test cases it behaves properly. I am waiting now for your heavy payloads :)

2020-02-23 21:10 UTC, Paulb23 approved these changes
LGTM.

2020-02-23 21:13 UTC, merged

2020-02-23 21:13 UTC, akien-mga commented
Thanks!

2020-03-04 08:53 UTC, akien-mga commented
Cherry-picked for 3.2.1.