Fix suspicious | and + operators
godotengine/godot pull request #36478
Opened 2020-02-23 08:22 UTC by qarmin

2020-02-23 08:27 UTC, aaronfranke requested changes

2020-02-23 08:27 UTC, aaronfranke commented on modules/visual_script/visual_script_property_selector.cpp
> +		bool in_modifier = false || p_modifiers.empty();
You can just remove `false ||`, it does nothing.

2020-02-23 08:31 UTC, aaronfranke approved these changes

2020-02-23 09:30 UTC, merged

2020-02-23 09:30 UTC, akien-mga commented
Thanks!

2020-03-04 08:58 UTC, akien-mga commented
Cherry-picked for 3.2.1.