SCons: Add GCC/Clang minimum version check
godotengine/godot pull request #36484
Opened 2020-02-23 16:45 UTC by akien-mga

Prevent using GCC 8 as it does not properly support C++17's
guaranteed copy elision which we now need.
(Upstream bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86521)

Follow-up to #36457 and #36436.

2020-02-23 16:52 UTC, Calinou requested changes

2020-02-23 16:52 UTC, Calinou commented on SConstruct
> +            print("Detect GCC version older than 7, which does not fully "
```suggestion
            print("Detected GCC version older than 7, which does not fully "
```

2020-02-23 16:52 UTC, Calinou commented on SConstruct
> +            print("Detect Clang version older than 6, which does not fully "
```suggestion
            print("Detected Clang version older than 6, which does not fully "
```

2020-02-23 16:52 UTC, Calinou commented on SConstruct
> +                    "regression in its C++17 guaranteed copy elision support.")
```suggestion
                    "regression in its C++17 guaranteed copy elision support."
                    "Try updating GCC, or use Clang 6 or later by installing it "
                    "and passing \"use_llvm=yes\" to the SCons command line.")
```

2020-02-23 16:52 UTC, Calinou commented on SConstruct
> +                    "support C++17. Supported versions are GCC 7, 9 and later.")
```suggestion
                    "support C++17. Supported versions are GCC 7, 9 and later."
                    "Try updating GCC, or use Clang 6 or later by installing it "
                    "and passing \"use_llvm=yes\" to the SCons command line.")
```

2020-02-23 20:30 UTC, Calinou approved these changes

2020-02-23 20:34 UTC, merged

2020-03-20 21:59 UTC, tinmanjuggernaut commented
This broke my compiling.

```
$ gcc --version
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

$ g++ --version
g++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

$ dpkg -l |egrep '^ii  g(cc|\+\+)'|awk '{print $2 "    " $3; }'
g++     4:9.2.1-3.1ubuntu1
g++-9   9.2.1-9ubuntu2
g++-9-multilib  9.2.1-9ubuntu2
g++-mingw-w64   9.2.1-9ubuntu1+22~exp1ubuntu2
g++-mingw-w64-i686      9.2.1-9ubuntu1+22~exp1ubuntu2
g++-mingw-w64-x86-64    9.2.1-9ubuntu1+22~exp1ubuntu2
g++-multilib    4:9.2.1-3.1ubuntu1
gcc     4:9.2.1-3.1ubuntu1
gcc-8-base:amd64        8.3.0-26ubuntu1~19.10
gcc-9   9.2.1-9ubuntu2
gcc-9-base:amd64        9.2.1-9ubuntu2
gcc-9-base:i386 9.2.1-9ubuntu2
gcc-9-multilib  9.2.1-9ubuntu2
gcc-mingw-w64   9.2.1-9ubuntu1+22~exp1ubuntu2
gcc-mingw-w64-base      9.2.1-9ubuntu1+22~exp1ubuntu2
gcc-mingw-w64-i686      9.2.1-9ubuntu1+22~exp1ubuntu2
gcc-mingw-w64-x86-64    9.2.1-9ubuntu1+22~exp1ubuntu2
gcc-multilib    4:9.2.1-3.1ubuntu1
```

gcc-8-base is required for clang-9 on ubuntu, but there is no gcc or g++ v8 compiler on my system.

Even if I remove it, it still complains.
```
$ dpkg -l |egrep '^ii  g(cc|\+\+)'|awk '{print $2 "    " $3; }'
g++     4:9.2.1-3.1ubuntu1
g++-9   9.2.1-9ubuntu2
g++-9-multilib  9.2.1-9ubuntu2
g++-mingw-w64   9.2.1-9ubuntu1+22~exp1ubuntu2
g++-mingw-w64-i686      9.2.1-9ubuntu1+22~exp1ubuntu2
g++-mingw-w64-x86-64    9.2.1-9ubuntu1+22~exp1ubuntu2
g++-multilib    4:9.2.1-3.1ubuntu1
gcc     4:9.2.1-3.1ubuntu1
gcc-9   9.2.1-9ubuntu2
gcc-9-base:amd64        9.2.1-9ubuntu2
gcc-9-base:i386 9.2.1-9ubuntu2
gcc-9-multilib  9.2.1-9ubuntu2
gcc-mingw-w64   9.2.1-9ubuntu1+22~exp1ubuntu2
gcc-mingw-w64-base      9.2.1-9ubuntu1+22~exp1ubuntu2
gcc-mingw-w64-i686      9.2.1-9ubuntu1+22~exp1ubuntu2
gcc-mingw-w64-x86-64    9.2.1-9ubuntu1+22~exp1ubuntu2
gcc-multilib    4:9.2.1-3.1ubuntu1

$ scons 
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Detected GCC 8 version < 8.4, which is not supported due to a regression in its C++17 guaranteed copy elision support. Use a newer GCC version, or Clang 6 or later by passing "use_llvm=yes" to the SCons command line.
```

2020-03-21 08:33 UTC, akien-mga commented
What's your output for:
```
echo $CXX
gcc --version
```
or
```
$CXX --version
```
if your $CXX is not `gcc`.

2020-03-21 08:49 UTC, tinmanjuggernaut commented
CXX is blank. If I set it to `gcc`, scons still complains about the version.

2020-03-21 09:01 UTC, akien-mga commented
Try to debug it:
```diff
diff --git a/methods.py b/methods.py
index 56c495468d..1a4f3a4c17 100644
--- a/methods.py
+++ b/methods.py
@@ -545,13 +545,16 @@ def get_compiler_version(env):
         # Not using -dumpversion as some GCC distros only return major, and
         # Clang used to return hardcoded 4.2.1: # https://reviews.llvm.org/D56803
         try:
+            print(env['CXX'])
             version = decode_utf8(subprocess.check_output([env.subst(env['CXX']), '--version']).strip())
+            print(version)
         except (subprocess.CalledProcessError, OSError):
             print("Couldn't parse CXX environment variable to infer compiler version.")
             return None
     else:  # TODO: Implement for MSVC
         return None
     match = re.search('[0-9]+\.[0-9.]+', version)
+    print(match)
     if match is not None:
         return list(map(int, match.group().split('.')))
     else:
```

2020-03-21 10:21 UTC, tinmanjuggernaut commented
Ah, I got it. Silly me, I defaulted my build script to run through the ubuntu docker, which is where gcc8 is.  Thanks for your help finding that. So this change now breaks the ubuntu dockers. It looks like fedora is on 9.2.1.

2020-03-21 10:27 UTC, akien-mga commented
Yes the Ubuntu docker images will have to be updated for master/4.0, as GCC 8.0-8.3 has broken C++17 support.