Docs for some nodes in visual shader(part 3)
godotengine/godot pull request #36558
Opened 2020-02-26 11:29 UTC by Chaosus

Docs for:

- VisualShaderNodeFloatConstant
- VisualShaderNodeFloatFunc
- VisualShaderNodeFloatOp
- VisualShaderNodeIf
- VisualShaderNodeInput
- VisualShaderNodeIntConstant
- VisualShaderNodeIntFunc
- VisualShaderNodeIntOp

2020-02-26 17:59 UTC, clayjohn requested changes
Looks great!

All references to "Godot Shader Language" should be to "_the_ Godot Shader Language"

Also note changes to "... by [code]...[/code] formula."

The suggested changes should be applied to all similar instances.

2020-02-26 17:59 UTC, clayjohn commented on doc/classes/VisualShaderNodeFloatFunc.xml
> +			Returns the sine of the parameter. Translates to [code]sin(x)[/code] in Godot Shader Language.
in _the_ Godot Shader Language

2020-02-26 17:59 UTC, clayjohn commented on doc/classes/VisualShaderNodeFloatFunc.xml
> +			Returns the cosine of the parameter. Translates to [code]cos(x)[/code] in Godot Shader Language.
in the Godot Shader Language

2020-02-26 17:59 UTC, clayjohn commented on doc/classes/VisualShaderNodeFloatFunc.xml
> +			Returns the tangent of the parameter. Translates to [code]tan(x)[/code] in Godot Shader Language.
in _the_ Godot Shader Language

Same for below mentions of Godot Shader Language

2020-02-26 17:59 UTC, clayjohn commented on doc/classes/VisualShaderNodeFloatFunc.xml
> +			Finds reciprocal value of dividing 1 on [code]x[/code] by [code]1 / x[/code] formula.
Finds reciprocal value of dividing 1 _by_ [code]x[/code] (i.e. [code]1 / x[/code]).

2020-02-26 17:59 UTC, clayjohn commented on doc/classes/VisualShaderNodeFloatFunc.xml
> +			Subtracts scalar from 1 by [code]1 - x[/code] formula.
Subtracts scalar [code]x[/code] from 1 (i.e. [code]1 - x[/code]).

2020-02-26 17:59 UTC, clayjohn commented on doc/classes/VisualShaderNodeFloatOp.xml
> +			Sums two numbers by [code]a + b[/code] formula.
Sums two numbers using [code]a + b[/code].

2020-02-26 17:59 UTC, clayjohn commented on doc/classes/VisualShaderNodeFloatOp.xml
> +			Subtracts two numbers by [code]a - b[/code] formula.
Subtracts two numbers using [code]a - b[/code].

2020-02-26 17:59 UTC, clayjohn commented on doc/classes/VisualShaderNodeFloatOp.xml
> +			Multiplies two numbers by [code]a * b[/code] formula.
Multiplies two numbers using [code]a * b[/code].

2020-02-26 17:59 UTC, clayjohn commented on doc/classes/VisualShaderNodeFloatOp.xml
> +			Divides two numbers by [code]a / b[/code] formula.
Divides two numbers using [code]a / b[/code].

2020-02-26 17:59 UTC, clayjohn commented on doc/classes/VisualShaderNodeIntOp.xml
> +			Sums two numbers by [code]a + b[/code] formula.
See above regarding in *floatOp*

2020-02-26 18:58 UTC, Chaosus commented
@clayjohn Done.. check again pls

2020-02-26 19:33 UTC, clayjohn requested changes
Just a few more of the same we missed. :)

2020-02-26 19:33 UTC, clayjohn commented on doc/classes/VisualShaderNodeIntFunc.xml
> +			Extracts the sign of the parameter. Translates to [code]sign(x)[/code] in Godot Shader Language.
Missed one

2020-02-26 19:33 UTC, clayjohn commented on doc/classes/VisualShaderNodeInput.xml
> +				Returns a translated name of the current constant in Godot Shader Language eg. [code]"ALBEDO"[/code] if the [member input_name] equal to [code]"albedo"[/code].
_the_ Godot

2020-02-26 19:33 UTC, clayjohn commented on doc/classes/VisualShaderNodeIntFunc.xml
> +			Constrains a parameter between [code]min[/code] and [code]max[/code]. Translates to [code]clamp(x, min, max)[/code] in Godot Shader Language.
Missed one

2020-02-26 19:33 UTC, clayjohn commented on doc/classes/VisualShaderNodeIntFunc.xml
> +			Returns the absolute value of the parameter. Translates to [code]abs(x)[/code] in Godot Shader Language.
Missed one

2020-02-26 19:33 UTC, clayjohn commented on doc/classes/VisualShaderNodeIntFunc.xml
> +			Negates the [code]x[/code] by [code]-(x)[/code] formula.
Negates the [code]x[/code] using [code]-(x)[/code].

2020-02-26 19:33 UTC, clayjohn commented on doc/classes/VisualShaderNodeFloatFunc.xml
> +			Negates the [code]x[/code] by [code]-(x)[/code] formula.
Negates the [code]x[/code] using [code]-(x)[/code].

2020-02-26 19:33 UTC, clayjohn commented on doc/classes/VisualShaderNodeFloatFunc.xml
> +			Clamps the value between [code]0.0[/code] and [code]1.0[/code] by [code]min(max(x, 0.0), 1.0)[/code] formula.
Clamps the value between [code]0.0[/code] and [code]1.0[/code] using [code]min(max(x, 0.0), 1.0)[/code].

2020-02-27 06:10 UTC, Chaosus commented
Done.

2020-02-27 06:38 UTC, clayjohn approved these changes

2020-02-27 07:35 UTC, merged

2020-02-27 07:35 UTC, akien-mga commented
Thanks!