Fix wrong selection on cloning a line down in the editor
godotengine/godot pull request #36621
Opened 2020-02-27 21:53 UTC by WizardOhio24

Fixes #36282, the selection was wrong because the column being selected for the end of the selection was using some weird formula (it looks like the one used in finding the line the selection should be moved to).

2020-02-28 09:42 UTC, groud commented
Note, this was made in #24574 to close #21814. We have to make sure this does not bring back any problem.

2020-02-29 10:50 UTC, akien-mga commented
CC @rxlecky 

I think it was probably a copy paste mistake, we can see further up in https://github.com/godotengine/godot/pull/24574/files#diff-86e49621fcb98c850c78e73214c8b478R1081 that the same logic as in this PR is used.

2020-02-29 15:00 UTC, Paulb23 requested changes
Close fix, however the feature allows you to duplicate your selection on the same line. With this the selection is completely removed.

Taking a guess, it probably only needs to do the current calculation if the to and from lines match.

2020-02-29 16:39 UTC, WizardOhio24 commented
Ah Ok, I understand why the formula was there.  As you suggested, I've changed it so it only does the calculation if the to and from lines match, it works for a duplication on a single line now.

2020-03-01 12:22 UTC, Paulb23 approved these changes
Thanks for the contribution, LGTM!

2020-03-01 14:53 UTC, merged

2020-03-01 15:44 UTC, akien-mga commented
Thanks!

2020-03-04 09:05 UTC, akien-mga commented
Cherry-picked for 3.2.1.