Animation Editor: Add options for displaying function call keys
godotengine/godot pull request #36740
Opened 2020-03-02 21:32 UTC by DuncanSparks

Adds an extra OptionButton to the AnimationTrackEditor bottom panel that gives three options for displaying the text on function call keys. Keys can show the full function call and arguments, just the function name, or no text at all.
This improves readability in the animation editor when large amounts of function call keys are being used.
![image](https://user-images.githubusercontent.com/3895119/75719823-4caefc80-5c8a-11ea-9839-31bef6e9a98c.png)
![image](https://user-images.githubusercontent.com/3895119/75719724-238e6c00-5c8a-11ea-870c-7ff45898976a.png)
![image](https://user-images.githubusercontent.com/3895119/75719765-3143f180-5c8a-11ea-8f3a-3bd4ea478fbb.png)
![image](https://user-images.githubusercontent.com/3895119/75719788-3acd5980-5c8a-11ea-8c57-4ff9ffa294cf.png)

2020-03-02 21:45 UTC, Calinou requested changes
Use Title Case for labels and options to be consistent with the rest of the editor :slightly_smiling_face:

2020-03-02 21:45 UTC, Calinou commented on editor/animation_track_editor.cpp
> +	function_text_mode_label->set_text(TTR("Function calls:") + " ");
```suggestion
	function_text_mode_label->set_text(TTR("Function Calls:") + " ");
```

2020-03-02 21:45 UTC, Calinou commented on editor/animation_track_editor.cpp
> +	function_text_mode_button->add_item(TTR("Name only"));
```suggestion
	function_text_mode_button->add_item(TTR("Name"));
```

2020-03-02 21:45 UTC, Calinou commented on editor/animation_track_editor.cpp
> +	function_text_mode_button->add_item(TTR("Name and arguments"));
```suggestion
	function_text_mode_button->add_item(TTR("Name and Arguments"));
```

2020-03-02 21:57 UTC, DuncanSparks commented
Updated the case.

2020-09-27 04:32 UTC, aaronfranke commented
@DuncanSparks Is this still desired? If so, you will need to squash the commits and rebase this on the latest master branch. See [this article](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) for more information.

2020-09-27 04:40 UTC, DuncanSparks commented
Ah, almost forgot about this. I'll try to fix this up, but I'm busy, so it might take a few days.

2020-09-30 03:05 UTC, DuncanSparks commented
Unfortunately, it looks like I've somehow lost the fork that I used for this PR. I think I managed to clone the branch from this and rebase it correctly, but I can't figure out if it's possible to push to this again with the fork gone. Is there a way to do that, or should I just open a new pull request?

2020-09-30 03:07 UTC, aaronfranke commented
Once the repository (or branch) that a PR is based on is deleted, it can't be restored. You will need to open a new PR.

2020-09-30 03:07 UTC, closed without merging

2020-09-30 04:47 UTC, DuncanSparks commented
Opened #42424 to redo this.