Automatic remote debugger port assignment.
godotengine/godot pull request #37067
Opened 2020-03-15 11:33 UTC by zaksnet

This is the continuation of #34651.

2020-07-29 19:40 UTC, wojtossfm commented
While waiting for this to hit 3.2 anyone who has a similar issue can work around this as far as I can tell by adding a tailored plugin to each of their projects e.g. (with an altered range)
```
tool
extends EditorPlugin


const RANGE_MIN = 10100
const RANGE_MAX = 10200

func build():
	var interface = self.get_editor_interface()
	var settings = interface.get_editor_settings()
	var port = randi() % RANGE_MAX + RANGE_MIN
	settings.set('network/debug/remote_port', port)
	prints("Set port to in settings to", port)
	return true

```
Managing to consistently get my client/server to connect to their respective debuggers when launching from the editor. It might be overly complex but it works for me so figured I would share in case someone is running into a similar issue.

2020-10-02 09:45 UTC, akien-mga commented
CC @Faless

2021-02-27 11:50 UTC, Faless requested changes
Some necromancy here, should have reviewed this time ago.
I still fear this feature will be confusing, but it's good to go after removing the extra message (see above).
:+1:

2021-02-27 11:50 UTC, Faless commented on editor/script_editor_debugger.cpp
> +	EditorNode::get_log()->add_message("--- Debugging process started ---", EditorLog::MSG_TYPE_EDITOR);
This line should not be here, it's printed when the client connects (causing it to be printed twice).

2021-02-27 18:24 UTC, Faless approved these changes
Looks good to me :+1:

2021-02-28 12:52 UTC, akien-mga commented
The commit message should be amended, it doesn't say at all what the commit is about.

2021-02-28 12:52 UTC, akien-mga commented
And this targets 3.2, what about the master branch?

2021-03-02 10:32 UTC, zaksnet commented
> And this targets 3.2, what about the master branch?

I'm afraid that this can not be applied to 4.0 since there has been many structural changes there.

2021-03-04 14:46 UTC, zaksnet commented
> The commit message should be amended, it doesn't say at all what the commit is about.

Added more info about the commit in the description 👍

2021-04-28 15:06 UTC, akien-mga commented on editor/editor_run.cpp
>  #include "editor_settings.h"
These can be in the same block.

2021-04-28 15:07 UTC, akien-mga commented on editor/script_editor_debugger.h
> +	int remote_port;
This should likely be initialized to 0.

2021-04-28 15:07 UTC, akien-mga commented
> > And this targets 3.2, what about the master branch?
> 
> I'm afraid that this can not be applied to 4.0 since there has been many structural changes there.

@Faless Would you be able to do the forward-port to 4.0?

2021-05-01 10:57 UTC, merged

2021-05-01 10:57 UTC, akien-mga commented
Thanks!