Fixes transform gizmo position when node has default transform
godotengine/godot pull request #37161
Opened 2020-03-19 06:49 UTC by simpuid

`SpatialEditorSelectedItem`'s `last_xform` is default on initialization so `SpatialEditorViewport` skips the selected node because it has default value of transform.
This PR added an extra dirty flag `last_xform_dirty` that makes `SpatialEditorViewport` to not skip the selected node when `last_xform` is at initialized value.

2020-03-21 12:41 UTC, JFonS requested changes
The fix looks good to me, but I would invert the values of `last_xform_dirty`. To me, being "dirty" means it has not been processed yet, so I would set the dirty flag to `true` in the constructor and set it back to `false` once the selection has been updated. Of course, the condition has to be negated too.

2020-03-21 13:32 UTC, JFonS approved these changes
Looks good to me. Thanks!

2020-03-21 14:31 UTC, merged

2020-03-21 14:31 UTC, akien-mga commented
Thanks!

2020-03-25 08:59 UTC, akien-mga commented
Cherry-picked for 3.2.2.