Display collision shapes of tile map in the editor
godotengine/godot pull request #37212
Opened 2020-03-21 15:20 UTC by Janglee123

Fixes #19858

2021-02-25 16:20 UTC, pouleyKetchoupp commented
This change works, but it's going to cause collision to always show for tilemaps in the editor, whether "Visible Collision Shapes" is checked or not.

It's how it works for CollisionShape2D nodes, but in that case users can switch collision visibility on/off on the nodes. In the case of a TileMap, there would be no way for users to disable collision visibility in the editor.

I wonder if that could be addressed with a property in the tilemap to toggle collision visibility.

2021-02-25 18:37 UTC, Janglee123 commented
How about adding the same option for the TileMap node?

2021-02-25 21:59 UTC, pouleyKetchoupp commented
> How about adding the same option for the TileMap node?

I'm not sure I was perfectly clear, so here are more details to make sure we're on the same page :)

`CollisionShape2D` can use the `visible` property inherited from `Node3D` which allows to hide collision shapes without affecting the corresponding mesh (it's a different node in the tree).

`TileMap` has the same property, but it would hide all visuals together with collision shapes, so in this case it would instead require a new property (something like `show_collision`), which would allow collision shapes to be displayed if "Visible Collision Shapes" is on or we're in the editor.

It seems easy enough to add to this PR, as long as there's a consensus with other maintainers.

2021-02-27 09:46 UTC, Janglee123 commented
okay, I have made suggested changes and added a new variable `show_collision`. Let me know if you want to put this functionality under `TOOLS_ENABLED`.

2021-02-27 16:11 UTC, pouleyKetchoupp commented
> 
> 
> okay, I have made suggested changes and added a new variable `show_collision`. Let me know if you want to put this functionality under `TOOLS_ENABLED`.

Thanks! Maybe `show_collision` could affect the game as well instead of being editor specific? Since it's enabled by default, it wouldn't change the default behavior and would allow more control.

2021-02-28 16:58 UTC, pouleyKetchoupp approved these changes

2021-02-28 17:03 UTC, pouleyKetchoupp requested changes

2021-02-28 17:03 UTC, pouleyKetchoupp commented on scene/2d/tile_map.cpp
> +	bool debug_shapes = show_collision && (Engine::get_singleton()->is_editor_hint() || st && st->is_debugging_collisions_hint());
Actually it needs extra parenthesis to fix compilation errors on some platforms:
`bool debug_shapes = show_collision && (Engine::get_singleton()->is_editor_hint() || (st && st->is_debugging_collisions_hint()));`

2021-02-28 19:11 UTC, pouleyKetchoupp approved these changes

2021-02-28 21:28 UTC, akien-mga commented on scene/2d/tile_map.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "show_collision"), "set_show_collision", "is_show_collision_enabled");
Please also add documentation to the new property after generating the template with `godot --doctool .`.

2021-03-01 15:55 UTC, groud commented
I think that the feature is needed and the implementation ok. However, I don't think it is worth merging in master, as the rebase of my work on master will likely get rid of it (I almost rewrote the whole class).

Also, I wonder if this should not be an editor settings (accessible from the interface) instead, but I guess it kind of remove the possibility to show collision per-node.

Anyway, I believe this should be rebased on 3.2 where it makes more sense IMO.

2021-03-03 15:45 UTC, pouleyKetchoupp commented on doc/classes/TileMap.xml
> +			If [code]true[/code], it shows collision shape in-editor and in-game. It requires show collision shape option to be on in debug menu to work in-game.
Just a little feedback on wording and formatting:
```suggestion
			If [code]true[/code], collision shapes are shown in the editor and at run-time. Requires [b]Visible Collision Shapes[/b] to be enabled in the [b]Debug[/b] menu for collision shapes to show at run-time.
```

2021-03-03 15:49 UTC, pouleyKetchoupp commented
@Janglee123 You might have to open a new PR and close this one in order to make it 3.2 specific, because I think rebasing directly would include some unwanted commits to the PR (unless there's a clean way to do it that I don't know about).

2021-03-03 16:51 UTC, Calinou commented
Superseded by https://github.com/godotengine/godot/pull/46623.

2021-03-03 16:51 UTC, closed without merging