Fix OptionButton item_selected docs godotengine#36803
godotengine/godot pull request #37303
Opened 2020-03-25 18:24 UTC by zak-grumbles

Corrected incorrect parameter names for OptionButton's item_selected signal documentation.

2020-03-25 18:30 UTC, aaronfranke approved these changes
This is good, but also note that there could be further improvements in this area (for a future PR).

2020-04-10 11:19 UTC, akien-mga requested changes
The same should be done for `item_focused`.

2020-04-11 01:36 UTC, zak-grumbles commented
Made the changes for `item_focused` as well

2020-04-11 06:30 UTC, akien-mga approved these changes

2020-04-11 06:30 UTC, merged

2020-04-11 06:30 UTC, akien-mga commented
Thanks!

2020-04-16 09:45 UTC, akien-mga commented
Cherry-picked for 3.2.2.