Handle huge path2d offset values
godotengine/godot pull request #37311
Opened 2020-03-26 08:47 UTC by MickeMakaron

If `set_offset` is called with huge `p_offset` values, the game will freeze practically forever, since it's subtracting a small value from a huge value in a loop.

This issue was not present in 3.1.2.

After 3.1.2, it seems like the loop-handling was moved from `_update_transform` to `set_offset` and in the process the implementation changed from using `Math::fposmod` to a while-loop.

This commit fixes the underlying issue by using `Math::fposmod` again (i.e. the old way from 3.1.2).

2020-03-26 08:54 UTC, MickeMakaron commented
As an additional note: This happened in a real use case, for one of the games hosted on our site.

2020-03-26 09:02 UTC, akien-mga commented
See #29172 and #34012 for history about the changes. This PR might reintroduce some of the bugs that were fixed.

2020-03-26 13:14 UTC, KoBeWi requested changes
This reintroduces #7665, i.e. `unit_offset` of 1 will reset to 0 when `loop` is enabled.

Also you should do changes to 3D path too.

2020-03-26 14:14 UTC, MickeMakaron commented
@KoBeWi I've made additional changes that I think should prevent #7665. Please advise.

2020-03-26 14:38 UTC, KoBeWi approved these changes
Now it seems ok.

2020-04-10 11:15 UTC, akien-mga commented
Could you rebase to solve the merge conflicts and squash the commits into one?

2020-04-13 06:06 UTC, MickeMakaron commented
@akien-mga Rebased and squashed

2020-04-13 07:17 UTC, merged

2020-04-13 07:17 UTC, akien-mga commented
Thanks!

2020-04-16 09:45 UTC, akien-mga commented
Cherry-picked for 3.2.2.