Expose 'Embedded Windows Mode' as Editor Settings
godotengine/godot pull request #37391
Opened 2020-03-28 21:01 UTC by dreamsComeTrue

Exposing a bool property `interface/editor/embedded_windows_mode` which allows to toggle between OS-Native and Embedded windows - used to speed up process of settings that feature instead of appending `--single-window` in command line (many of users might not be aware of that command property yet).

2020-03-28 21:26 UTC, YeldhamDev commented
Would be nice to have an option for the project itself as well.

2020-03-28 21:27 UTC, dreamsComeTrue commented
> Would be nice to have an option for the project itself as well.

Yeah - I was actually thinking where would it suit the best - what do you think: Editor, Project, both?

2020-03-28 21:29 UTC, YeldhamDev commented
@dreamsComeTrue I think you misunderstood. By a project setting, I mean an option to make windows embedded for your actual game.

2020-03-28 21:33 UTC, dreamsComeTrue commented
> @dreamsComeTrue I think you misunderstood. By a project setting, I mean an option to make windows embedded for your actual game.

Yes - exactly as I understand that - currently, it steers behaviour only for Editor.
And you want to extend it, to allow Users to set that checkbox and that should affect their Projects/Games - as well as the editor.

That's why I am asking - would it be nice to have that checkbox basically duplicated for Editor Settings and Project Settings as well? Aaand - where exactly in Project Settings should it fit the in your opinion?

2020-03-28 21:35 UTC, YeldhamDev commented
Likely `display/window`.

2020-03-28 22:13 UTC, dreamsComeTrue commented
Done as requested - now it is possible to change default Window rendering/behaviour separately - for Engine and for a Project as well (thanks to how Windows & MainLoop are being designed - there is no need to restart whole Editor when that setting is updated for a Project - effect is instantaneous!)

2020-04-03 14:02 UTC, reduz requested changes

2020-04-04 05:58 UTC, merged

2020-04-04 05:58 UTC, akien-mga commented
Thanks!