Add option for editor freelook camera sensitivity
godotengine/godot pull request #37523
Opened 2020-04-02 14:54 UTC by 1abinitio1

adds an option in the editor settings, to change the camera sensitivity when flying around in free look.

2020-04-02 16:55 UTC, Calinou requested changes

2020-04-02 16:55 UTC, Calinou commented on editor/editor_settings.cpp
> +	_initial_set("editors/3d/navigation_feel/freelook_sensitivity", 0.4);
This should probably be `editors/3d/freelook/freelook_sensitivity` so you can find it with the other freelook settings.

2020-04-02 16:55 UTC, Calinou commented on editor/editor_settings.cpp
> +	hints["editors/3d/navigation_feel/freelook_sensitivity"] = PropertyInfo(Variant::FLOAT, "editors/3d/navigation_feel/freelook_sensitivity", PROPERTY_HINT_RANGE, "0.0, 2, 0.01");
Same as above.

2020-04-02 18:59 UTC, 1abinitio1 commented
changed to use editors/3d/freelook/freelook_sensitivity

2020-04-03 08:58 UTC, Calinou approved these changes

2020-04-07 07:23 UTC, akien-mga commented
Could you squash commits into one and amend the commit message to be more descriptive?

See [https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase] and [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind)

2020-04-17 05:06 UTC, 1abinitio1 commented
> Could you squash commits into one and amend the commit message to be more descriptive?
> 
> See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) and [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind).

Sorry for the late reply, but how would i go about doing that?
Made all the changes through githubs online text editor, and all tutorials i can find, seem to 
want you to have a local copy of the files. 
If i download my fork and link it using visual studio, could i squash the commits afterwards?
(first time using github)
thanks

2020-04-17 08:18 UTC, Calinou commented
> If i download my fork and link it using visual studio, could i squash the commits afterwards?
> (first time using github)

Yes :slightly_smiling_face:

2020-04-29 07:37 UTC, akien-mga commented
Rebased, amended and force pushed a fixed commit.

2020-04-29 07:37 UTC, akien-mga approved these changes

2020-04-29 09:20 UTC, merged

2020-04-29 09:20 UTC, akien-mga commented
Thanks!