Remove Node.get_position_in_parent()
godotengine/godot pull request #37556
Opened 2020-04-03 18:29 UTC by KoBeWi

See #21802

2020-04-03 18:33 UTC, pycbouh commented
Why remove this and not the other? It's shorter and perfectly aligns with the fact that the result will be used as an `index` argument in a function like `get_child`.

2020-04-03 20:22 UTC, KoBeWi commented
> I agree, get_position_in_parent() is waaay too wordy...

It's more descriptive though. Maybe we could come up with a completely new name?

2020-04-03 21:55 UTC, aaronfranke commented
`get_index_in_parent()` is what immediately occurred to me. `get_position_in_parent()` is a really poor choice of words because "position" means something else for Node2D and Node3D.

2020-04-03 22:01 UTC, KoBeWi commented
How about `get_sibling_index`?

2020-04-03 22:10 UTC, aaronfranke commented
I think `get_sibling_index` is not immediately clear that we're getting the index of this node among siblings, since it could also be read as "get the index of another sibling". `get_index_among_siblings`? I'm still leaning towards `get_index_in_parent`.

2020-04-04 18:14 UTC, pycbouh commented
Well, if we must include a reference to the parent, then `get_index_in_parent` is our only option. Definitely not `sibling`. That implies that this index has something to do with current node's siblings.

In fact, I can't think of any adjective to put before the word `index` here, that wouldn't sound ambiguous or even more confusing than without any.

2020-04-04 21:45 UTC, hubbyist commented
get_node_index() maybe?

2020-04-05 18:02 UTC, Xrayez commented
> > I agree, get_position_in_parent() is waaay too wordy...
> 
> It's more descriptive though. Maybe we could come up with a completely new name?

That's what documentation is for, thanks goodness Godot has good accessibility for docs.

2020-04-05 22:20 UTC, aaronfranke commented
Since `get_index()` seems good to many people, we should change this PR to be the opposite of what it currently is, keeping `get_index()` and removing `get_position_in_parent()`.

This way we can avoid having a duplicate methods for now, and we can maybe rename `get_index` later if it's desired.

2020-04-05 22:36 UTC, KoBeWi commented
Heh, looks like `get_index()` was more commonly used in the code. The number of changed lines significantly dropped.

2020-04-05 23:00 UTC, aaronfranke requested changes

2020-04-05 23:00 UTC, aaronfranke commented on doc/classes/Node.xml
> +		<method name="get_index" qualifiers="const">
`get_index` is no longer sorted properly in the documentation due to how this change was made.

2020-04-05 23:00 UTC, aaronfranke commented on scene/main/node.cpp
> +	ClassDB::bind_method(D_METHOD("get_index"), &Node::get_index);
This is a pointless diff, no need to remove line 2838 and re-add it here.

Same for the method declarations and definitions.

2020-04-05 23:11 UTC, aaronfranke requested changes

2020-04-05 23:11 UTC, aaronfranke commented on scene/main/node.h
> +	int get_index() const;
Pointless removal on line 323 and addition here.

2020-04-05 23:11 UTC, aaronfranke commented on scene/main/node.cpp
> +int Node::get_index() const {
Pointless removal on line 1917 and addition here.

2020-04-05 23:25 UTC, aaronfranke approved these changes

2020-04-06 07:44 UTC, merged

2020-04-06 07:44 UTC, akien-mga commented
Thanks!

2020-10-01 07:48 UTC, aaronfranke commented
Just adding this for the record: This fixes #37556