Add reference of Color8 function to Color class documentation
godotengine/godot pull request #37589
Opened 2020-04-04 19:33 UTC by Nannaquin

Responding to an issue made in the godot'docs repo
https://github.com/godotengine/godot-docs/issues/3314

Adding a reference acknowledging the existence of the Color8 function to the Color class documentation, in the same way ColorN is referenced.

2020-04-04 20:00 UTC, YuriSizov requested changes

2020-04-04 20:00 UTC, pycbouh commented on doc/classes/Color.xml
> +		You can also create a color from standardized color names by using [method @GDScript.ColorN] or directly using the color constants defined here. The standardized color set is based on the [url=http
> @GDScrpt.Color8

There is a typo. I would also move that into a separate paragraph, as this one deals with named colors.

2020-04-04 20:03 UTC, pycbouh commented
Please, edit your message to say *closes* or *fixes* before the link to the issue.

2020-04-04 23:02 UTC, Nannaquin reviewed
Adjusted typo and moved sentence to a new line.

2020-04-05 07:55 UTC, pycbouh commented
Thank you. Can you squash your commits as per guidelines: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html

2020-04-05 15:43 UTC, Nannaquin commented
Was having trouble rebasing, hopefully this is correct. Thanks for the help

2020-04-07 07:16 UTC, merged

2020-04-07 07:16 UTC, akien-mga commented
Thanks!

2020-04-16 10:07 UTC, akien-mga commented
Cherry-picked for 3.2.2.