control node global rect scale fix
godotengine/godot pull request #37765
Opened 2020-04-10 17:45 UTC by ThakeeNathees

fix: https://godotengine.org/qa/66963/how-get-the-scaled-rect-of-control-node-the-child-of-node2d-is
control node get_global_rect() returns global position and local size

steps to reproduce:
create scene tree like in the picture
set `Node2D2` scale to `.5, .5`
attach the script to both color rect
```gdscript
func _ready():
	print( name, ' local_size  : ', get_rect().size )
	print( name, ' global_size : ', get_global_rect().size )
```
![rect size](https://user-images.githubusercontent.com/41085900/79011004-bae7b880-7b80-11ea-8e7c-faa5cf7d3039.JPG)

2021-03-20 01:17 UTC, Calinou approved these changes
Looks good to me, but we may want to update the documentation for `get_global_rect()` in `doc/classes/Control.xml` as well.

This should be safe to cherry-pick to the `3.x` branch, but we should wait until 3.3 is released as this is potentially risky in existing projects that may rely on the buggy behavior.

2021-08-30 20:22 UTC, reduz requested changes

2021-08-30 20:22 UTC, reduz commented on scene/gui/control.cpp
> +	return Rect2(get_global_position(), get_size() * get_global_transform().get_scale());
I suggest a different approach:

```
Transform2D global_transform = get_global_transform();
return Rect2( global_transform.origin, global_transform.get_scale() * get_size() )
``` 

Likewise for get_screen_rect.

2021-09-15 08:00 UTC, akien-mga commented
@ThakeeNathees Are you able to update the PR according to @reduz's suggestion? (And rebase on latest `master`)

2021-12-17 05:20 UTC, filipworksdev commented
`get_screen_rect()` no longer exists in 3.x.

2023-01-26 12:26 UTC, akien-mga commented
Superseded by #66688.

2023-01-26 12:26 UTC, closed without merging