Relative scale snapping 2D
godotengine/godot pull request #37823
Opened 2020-04-12 09:23 UTC by MCrafterzz

Well relative snapping already works on movement and rotation so I though I'd implement it for scaling as well as I believe it otherwise will be inconsistent and confusing for people. So basically it works the same as it does for movement and rotation, if you have the scale snapping interval set to 1 then it will lead to the following:
1 (original) 2 3 4 5 6
1.1 (original) 2.2 3.3 4.4 5.5 6.6

So instead of snapping the result it snaps the difference (new value / old value)

2020-04-12 10:31 UTC, groud approved these changes

2020-04-12 22:52 UTC, akien-mga requested changes

2020-04-12 22:52 UTC, akien-mga commented on editor/plugins/canvas_item_editor_plugin.cpp
> +			Size2 originalScale = scale;
We use snake_case for identifiers.

2020-04-13 08:17 UTC, MCrafterzz commented
🤦 Shouldn't travis catch that stuff?

2020-04-13 10:09 UTC, akien-mga commented
> Shouldn't travis catch that stuff?

Doesn't seem trivial to analyze programmatically, how would you do this?

2020-04-13 10:10 UTC, akien-mga approved these changes

2020-04-13 10:10 UTC, merged

2020-04-13 10:10 UTC, akien-mga commented
Thanks!