Clean up profiler
godotengine/godot pull request #37966
Opened 2020-04-17 17:14 UTC by pkowal1982

- Fix issue where you can't select by mouse all frames (for example frame 0 can be selected only by edit field)
- Disable frame edit field when no data available
- Disable clear button when nothing to clean
- Align cursor to the middle of selected frame (it was misplaced)
- Remove some dead code

2021-03-30 22:37 UTC, Calinou commented
@pkowal1982 Could you look into rebasing this pull request on the latest `master` branch?

2021-03-31 10:24 UTC, pkowal1982 commented
@Calinou yeah, I'll try to look into it before this weekend.

2021-04-01 23:10 UTC, pkowal1982 commented
@Calinou Done.

2021-04-06 11:39 UTC, Faless requested changes
Haven't tried the changes yet, but see comments on style (we always require braces in control flows)

2021-04-06 11:39 UTC, Faless commented on editor/debugger/editor_profiler.cpp
> +		total_metrics = frame_metrics.size();
```cpp
	if (total_metrics > frame_metrics.size()) {
		total_metrics = frame_metrics.size();
	}
```

2021-04-06 11:39 UTC, Faless commented on editor/debugger/editor_profiler.cpp
> +		cursor_metric_edit->set_value(p_metric.frame_number);
```cpp
	if (!seeking) {
		cursor_metric_edit->set_value(p_metric.frame_number);
	}
```

2021-04-10 19:27 UTC, Faless approved these changes
I've tested it a bit, it's a great improvement.
There are still issues when you select a frame and then close the game without resuming it (the play/stop button stays disabled), but that's already happening in master so we can address that in a separate PR.
Great job :trophy: !

2021-04-10 19:27 UTC, merged