Improve the procedural geometry class documentations
godotengine/godot pull request #38025
Opened 2020-04-19 21:22 UTC by Calinou

This references Godot's winding order at the top of every procedural geometry class, as well as referencing other classes within a given geometry class.

A warning about ImmediateGeometry performance was also added.

See [this Reddit thread](https://www.reddit.com/r/godot/comments/g4a3a0/half_of_generated_tris_are_upsidedown_for_some/).

2020-04-19 22:44 UTC, clayjohn requested changes

2020-04-19 22:44 UTC, clayjohn commented on doc/classes/ImmediateGeometry3D.xml
> +	<tutorials>y
Whoops!

2020-04-20 07:30 UTC, clayjohn approved these changes

2020-04-20 09:48 UTC, StraToN commented
I am wondering if it's a good idea or not to refer to external https://learnopengl.com website. What if external links become unavailable ? This may require some kind of tool to regularly check external URL validity in the documentation.

2020-04-22 09:42 UTC, Calinou commented
@StraToN We've been referencing third-party websites in the class reference for a while now. I think we can keep doing it and use a tool to check for dead URLs/redirects from time to time. I've been meaning to find such a tool but haven't found any *generic* CLI tool that works well for this :slightly_frowning_face:

2020-04-24 15:28 UTC, merged

2020-04-24 15:28 UTC, akien-mga commented
Thanks!

2020-04-27 08:14 UTC, akien-mga commented
Cherry-picked for 3.2.2.