Add option to draw lines as rects instead of GL_LINES
godotengine/godot pull request #38417
Opened 2020-05-02 18:44 UTC by lawnjelly

GL_LINES may be slow on some hardware or even use a software fallback path. This PR adds a project setting to force the use of the rectangle path to draw lines instead of GL_LINES. This is primarily useful in the editor but may be useful in some exported projects.

#### Notes
* I wasn't sure to go with editor setting or project setting, but project setting proved to be easier to get working, and adds the option to export projects with the lines setting
* The project setting could possibly go in a better category, as it actually affects GLES2 and GLES3

2020-05-02 18:48 UTC, lawnjelly commented
There's also some anti-aliasing stuff in there even in the rect path with GLES_OVER_GL, I'll have a look over it tommorrow and see if that can be improved too.

2020-05-02 21:26 UTC, Calinou commented
I'll make sure to mention this setting in https://github.com/godotengine/godot-docs/pull/3482 :slightly_smiling_face:

2020-05-03 11:46 UTC, Calinou commented
If this is known to be always slow on macOS, we could enable it on macOS by default. This can be done by creating a project setting with the same name, but with a `.osx` suffix ([feature tags](http://docs.godotengine.org/en/latest/getting_started/workflow/export/feature_tags.html)).

2020-05-03 11:58 UTC, lawnjelly commented
> If this is known to be always slow on macOS, we could enable it on macOS by default. This can be done by creating a project setting with the same name, but with a `.osx` suffix ([feature tags](http://docs.godotengine.org/en/latest/getting_started/workflow/export/feature_tags.html)).

Wow, I never knew that existed! :grin:

I wouldn't say we know it to be always slow yet though, all we have is some anecdotal reports, and we have yet to confirm that this will fix it. I can't try it, not having a Mac myself. It also may not be all Macs affected. Is it possible to add as is and change the override setting later?

2020-05-03 12:02 UTC, Calinou commented
> Is it possible to add as is and change the override setting later?

Sure :slightly_smiling_face:

2020-05-05 08:13 UTC, lawnjelly commented
I've changed this to an editor setting, as it seems that was preferred. I wasn't quite sure an a good way of getting the editor setting from the rasterizer, as this technique is non-standard. Any suggestions for a better way of doing this are welcome, this is outside my knowledge area of Godot.

Recognising that a link between the editor settings and the rasterizer is potentially problematic on export builds, I've enclosed the reading / includes with #ifdef TOOLS_ENABLED.

2020-05-06 06:02 UTC, clayjohn approved these changes
@Akien at first I disagreed with passing in a generic editor settings struct, but lawnjelly explained that it can also be used to set the batching in editor property, and potentially others. So I am fine with it. 

Still need to get @reduz' approval on this one.

2020-05-06 06:09 UTC, lawnjelly commented
Yes I agree it would be nice to get @reduz input on what passing method would be best. To some extent we are second guessing.

2020-05-06 12:02 UTC, reduz requested changes

2020-05-06 12:02 UTC, reduz commented on drivers/gles2/rasterizer_canvas_gles2.cpp
> +void RasterizerCanvasGLES2::set_editor_settings(const VisualServer::EditorSettings &p_settings) {
Just create a function in VisualServer like set_draw_lines_as_rects() , no need to make it more generic

2020-05-06 13:57 UTC, hmans commented
I've compiled and tried 68352a8b1a on my MBP 13" with Intel Iris Plus Graphics 655 (I'm the guy who opened #17584 a while ago.)

I'm afraid there was no noticeable difference. I'm guessing the setting that this PR introduces needs to be set to _off_ for me, right? (I've tried both -- no difference.)

I've recorded a video of the slowness, but it's 2020 so it's impossible to find a site where I can upload it to that doesn't require logins or is Youtube. ;-) When I figure this out, I'll post a link.

2020-05-06 14:03 UTC, hmans commented
I've caved and uploaded it to YouTube:

https://youtu.be/yhC0xs_MjoI

Note that while enabling the rulers makes things choppy, also enabling the grid completely kills performance. Toggling the new option introduced by this PR doesn't change things in any noticeable fashion. (I also restarted the editor after changing the setting, just in case.)

If there's anything else I should try, please let me know.

2020-05-06 14:27 UTC, lawnjelly commented
> I'm afraid there was no noticeable difference. I'm guessing the setting that this PR introduces needs to be set to _off_ for me, right? (I've tried both -- no difference.)

Oh, well that's a bit of a let down, it would have been nice if this solved it. :disappointed: Thanks for testing though!

The only other obvious thing in the ruler rendering is possibly the number of drawcalls. I'll try and work out what this is. I guess we should put this PR on ice for now until we get more info.

As with the iOS issues, we are suffering a bit debugging this blind because we don't have macs.

2020-05-12 07:20 UTC, lawnjelly commented
Closing this for now, can always reopen later if we need to check for problems with GL_LINES.

2020-05-12 07:20 UTC, closed without merging