Graph node offset wouldn't update- Fixed
godotengine/godot pull request #38414
Opened 2020-05-02 13:26 UTC by theoway

Fixes #37780 

**Issue**:  `offset` of the graph node wouldn't update and change in the property inspector, when it was moved in editor, only the `position` of `Rect`(property of `Control`) of the graph node changed. As a result, when the scene was played with the graph node in it, the graph node would be positioned according to the unmodified `offset` value.

**Fix**: It turns out when editing in the editor, on moving the graph node, only the `position` was changing, when the `offset` should also have been changing as well. So, I overrode the `_edit_set_position()` method in `Control` class, which is called when `position` of `rect` is changed, and modified it such that it would update the `offset` and notify the change so that the new value of offset will appear in the property inspector as well.

**Results**:
![Godot Engine - New Game Project - Control tscn (_) 2020-05-02 18-22-21_Trim](https://user-images.githubusercontent.com/41969735/80865219-8493e980-8ca5-11ea-9624-e673c9df52c5.gif)

Now the value of the `offset` changes as the graph node is moved/dragged in the editor, along with the change in `position`. And the graph node is positioned according the updated value of offset when the scene is played.

2020-05-03 18:13 UTC, theoway commented
@KoBeWi This branch is building perfectly in my machine without Warning or Errors but Travic-CI is throwing some ambiguous errors. Could you help me with this?

2020-05-03 18:33 UTC, KoBeWi commented
You wrapped the declaration using `#ifdef TOOLS_ENABLED`, but you didn't do the same with the `.cpp` file. The failing builds are with TOOLS (editor) disabled.

2020-05-03 19:05 UTC, theoway commented
> You wrapped the declaration using `#ifdef TOOLS_ENABLED`, but you didn't do the same with the `.cpp` file. The failing builds are with TOOLS (editor) disabled.

Thank you so much for the prompt reply. So, I have to wrap the definition of the function in `#ifdef TOOLS_ENABLED` then, right?

2021-08-27 11:07 UTC, KoBeWi requested changes
The behavior is a bit buggy:
![xkwsr059OX](https://user-images.githubusercontent.com/2223172/131118201-de068398-b752-47eb-9efd-a8d78d291928.gif)
This should be fixed somehow. The edit rectangle should match the node position.

2021-08-29 10:29 UTC, theoway commented
@KoBeWi Sorry, I was unavailable for the past few days. I'll make the suggested changes.

2021-08-29 11:20 UTC, theoway commented
> Is it me, or do they both look offset from the actual position, just in different, opposite directions?

Yes, there's a constant difference of 40.0f. Weird!

2021-08-29 12:52 UTC, theoway commented
The bug was fixed when I had made the pull request. It was a long time back, since then, I can see there have been some changes made to some related modules. That's why, it's showing buggy behavior. Anyways, I'll do some testing and digging and hopefully fix it by tomorrow.

2021-08-31 07:13 UTC, theoway commented
@KoBeWi After some digging, `position_offset` and `rect_position` are different things. One should not affect the other.  `position_offset` is relative to `scroll_offset` of `GraphEdit` whereas `rect_position` is relative to `GraphEdit` position. Both are supposed to work differently. In nutshell, I don't think we should consider them one or make them act as one. Your thoughts?

2021-08-31 12:55 UTC, pycbouh commented
As stated in the issue this tries to close, `rect_position` doesn't have any effect on a `GraphNode` inside of the `GraphEdit`, and offset must be used. Properly disabling `rect_position` in the Inspector requires https://github.com/godotengine/godot/pull/30623. But what we can fix in this PR is that if the `GraphNode` is moved by hand in the 2D editor and that `GraphNode` is inside of `GraphEdit`, it should update its offset property, not `rect_position`.

2021-08-31 15:40 UTC, theoway commented
@pycbouh Yeah, it makes complete sense! Thanks! I'll make the code & documentation changes and update the description of this PR as you've suggested.

2021-09-04 19:26 UTC, theoway commented
> ![xkwsr059OX](https://user-images.githubusercontent.com/2223172/131118201-de068398-b752-47eb-9efd-a8d78d291928.gif)
@pycbouh Tried working on your suggestion, but it gives rise to this bug. The highlighted rect is drawn with `rect_position`. If it is not updated, it will be stuck at the origin. Although, this will implement what you had in mind, i.e., `position_offset` will be updated and `rect_position` won't be updated, when `GraphNode` is in `GraphEdit`, but it will mess up the drawing of the _editing_ rectangle. 
At this point, I dunno how we should proceed.

2021-09-05 18:25 UTC, theoway commented
To solve this issue, we have to update `position_offset` whenever `rect_position` changes. When `rect_position` is updated, `Control` sends this notification: **NOTIFICATION_LOCAL_TRANSFORM_CHANGED**. 
So, I added the piece of code given below to `GraphNode::_notifcation(int)`. 
```
case NOTIFICATION_LOCAL_TRANSFORM_CHANGED: {
			GraphEdit* graph = Object::cast_to<GraphEdit>(get_parent());
			if (graph) {
				position_offset = (get_position() + graph->get_scroll_ofs()) * graph->get_zoom();
			}
		} break;
```
The expected behaviour is when `rect_position` is changed, either via dragging or through typing value in the editor, this should trigger this piece of code, but that is not happening. 
@pycbouh Can you help me with this? If this notification can be received by `GraphNode`, then our problem is solved.

2021-09-05 18:28 UTC, KoBeWi commented
@theoway Use `set_notify_local_transform()`

2021-09-06 12:00 UTC, pycbouh commented
Okay, https://github.com/godotengine/godot/pull/30623 was actually finally merged, so we can rely on it to prevent rect_position from being edited on GraphNodes inside of GraphEdit for this PR.

2021-09-06 15:39 UTC, theoway commented
> Okay, #30623 was actually finally merged, so we can rely on it to prevent rect_position from being edited on GraphNodes inside of GraphEdit for this PR.

Alright, then I'll rebase and start again. Will post my results here.

2021-09-06 18:16 UTC, theoway commented
![Screenshot (313)_LI](https://user-images.githubusercontent.com/41969735/132251354-83b53200-a25d-44f2-b3ca-314c31e10905.jpg)

I don't think #30623 is working. I'm still able to edit these properties.

2021-09-06 22:14 UTC, KoBeWi commented
#30623 affects children of a container. If you add another node under your GraphNode, it will have disabled properties. The GraphNode itself can be editor normally, because GraphEdit is not a Container.

To prevent GraphNodes position from being edited, you need to check if they are under a GraphEdit and disable the property yourself. However it would still be possible to move them in 2D editor, so you'd have to block that too.

2021-09-19 17:25 UTC, theoway commented
**Update**: I've changed the old code and now `position_offset` updates with `rect_position`, correctly according to `scroll_offset` of `GraphEdit`, but the _editing rect_ is showing the same glitchy behaviour, like here:
> ![xkwsr059OX](https://user-images.githubusercontent.com/2223172/131118201-de068398-b752-47eb-9efd-a8d78d291928.gif)

**ToDo**: 

- Fix this _edit rectangle_ glitch
- Block direct changes to `rect_position` when `GraphNode` is child of `GraphEdit`.

**PS:** If someone can point out why the edit rectangle is like this, it'll make my job a lil' easy.

2021-09-22 17:01 UTC, theoway commented
To make the property read-only, I added this code(given below) to `add_child_notify()` in `GraphEdit.cpp`:
```
#ifdef TOOLS_ENABED
		List<PropertyInfo> *p_list;
		gn->get_property_list(p_list);
		for (List<PropertyInfo>::Element *E = p_list->front(); E; E = E->next()) {
			if (E->get().name == "rect_position") {
				E->get().usage |= PROPERTY_USAGE_READ_ONLY;
				break;
			}
		}
#endif
```

I'm getting a crash as the project is loaded. Kinda stuck here

2021-09-22 17:04 UTC, KoBeWi commented
You could use `validate_property()` method for that.

2021-09-22 17:11 UTC, theoway commented
> You could use `validate_property()` method for that.

How do I pass the property `rect_position` to `validate_property()`? Is there a _getter_ from which I can get the property reference?

2021-09-22 17:25 UTC, KoBeWi commented
`validate_property()` should be called automatically for each property. Then you use the property that it gets as an argument, so in your case you should check if it's `rect_position` and disable it.

2021-09-22 20:59 UTC, KoBeWi commented on scene/gui/graph_node.cpp
> +		set_position(p_position);
`set_position()` should be outside this condition, otherwise the node can't be moved if not inside GraphEdit.

2021-09-23 07:52 UTC, KoBeWi approved these changes

2021-09-24 11:01 UTC, merged

2021-09-24 11:01 UTC, akien-mga commented
Thanks!