Add documentation for the VisualShader nodes
godotengine/godot pull request #38505
Opened 2020-05-06 12:26 UTC by KoBeWi

This adds documentation to all remaining VisualShader classes. Many of the descriptions are copy-paste from Visual Shader edtior plugin.

Submitting as draft right now, because I didn't do any checking and there are some inconsistencies.

2020-05-07 04:33 UTC, clayjohn requested changes
Great work! This will really put a dent in the docs completion!

2020-05-07 04:33 UTC, clayjohn commented on doc/classes/VisualShaderNodeVectorFunc.xml
> +			Calculates the normalize product of the vector.
```suggestion
			Normalizes the vector so that it has a length of [code]1[/code] but points in the same direction.
```

2020-05-07 04:33 UTC, clayjohn commented on doc/classes/VisualShaderNodeVectorFunc.xml
> +		Returns [code]1/value[/code].
Missed an indent

2020-05-07 04:33 UTC, clayjohn commented on doc/classes/VisualShaderNodeVectorScalarStep.xml
> +		Calculates a vector SmoothStep function within the visual shader graph.
This is not a smoothstep

```suggestion
		Calculates a vector Step function within the visual shader graph.
```

2020-05-07 19:19 UTC, clayjohn approved these changes

2020-05-07 21:59 UTC, akien-mga commented
Some errors from `makerst.py`:
```
ERROR: Unresolved type 'Sprite', file: VisualShaderNodeTexture
ERROR: Unresolved type 'const Source.SOURCE_TEXTURE', file: VisualShaderNodeTexture
ERROR: Unresolved enum 'Function', file: VisualShaderNodeVectorOp
```

2020-05-07 22:21 UTC, KoBeWi commented
Yeah, I'm still fixing it. I should be done soon.

2020-05-10 11:07 UTC, merged

2020-05-10 11:07 UTC, akien-mga commented
Thanks!

2020-05-11 08:40 UTC, akien-mga commented
Cherry-picked for 3.2.2.