Fix to issue #38180
godotengine/godot pull request #39191
Opened 2020-05-31 12:43 UTC by kopcion

After this PR TextEdit::get_line_count() will return the number of entries in text vector, as well as a number of times those lines wrap around so that the result is the same as what users can see on screen, as opposed to a number of '\n' characters.

2020-05-31 13:27 UTC, YeldhamDev commented
Please use a more descriptive commit message.

2020-05-31 19:56 UTC, kopcion commented
I hope this commit message is more descriptive :)

2020-06-03 09:14 UTC, akien-mga commented
To clarify about the commit message, we usually favor having a commit title that accurately describe what the fixed bug is, instead of only pointing to a GitHub issue number (which can't be read through `git log`). See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

So here something like this would be great:
```
Fix TextEdit::get_line_count() when lines are wrapped

TextEdit::get_line_count() now considers visible lines instead of lines in source
text before wrapping by adding for each line TextEdit::times_line_wraps(int).

Fixes #38180.
```

2020-06-03 17:45 UTC, Paulb23 requested changes
This is more of a enhancement then bug, `get_line_count` is used for looping over the "raw" lines outside of `TextEdit` and a couple places internally. Got some notes down for #31739, where instead we create new method called `get_visual_line_count` that handles not only wrapping but hidden lines as well.

2021-08-30 09:39 UTC, Paulb23 commented
Closing as superseded by #50371 which exposed `get_total_visible_line_count` to do this.

2021-08-30 09:39 UTC, closed without merging