Added Custom Performance Monitor
godotengine/godot pull request #39302
Opened 2020-06-04 20:49 UTC by simpuid

Custom monitors can be added/removed/check using `Performance.add_custom_monitor`/`Performance.remove_custom_monitor`/`Performance.has_custom_monitor`

The value can be viewed in the `Custom` section of `Monitor` tab of Debugger.
Basically...
```
extends Node

func _enter_tree():
	var self_var = self
	Performance.add_custom_monitor("monitor_one", Callable(self_var, "monitor_call"), [1, 2])
	Performance.add_custom_monitor("monitor_two", Callable(self_var, "monitor_call"), [2, 3])
	Performance.add_custom_monitor("monitor_three", Callable(self_var, "monitor_call"), [3, 4])

func _exit_tree():
	Performance.remove_custom_monitor("monitor_one")
	Performance.remove_custom_monitor("monitor_two")
	Performance.remove_custom_monitor("monitor_three")

func monitor_call(from, to) -> float:
	return rand_range(from, to)
```
Above code causes

![monitors](https://user-images.githubusercontent.com/37181756/83808737-edbab280-a6d2-11ea-9d2c-1ab718eca302.png)

2020-06-04 23:45 UTC, samdze commented
Nice!
Would it be possible to add the capability to define monitors inside any category in the monitors tree? (Not only in the arbitrary "Custom" one)

Like this:
```
func _enter_tree():
	var self_var = self

        // This one goes under "Ammo"
	Performance.add_custom_monitor("Ammo/Gun", ..., ...)
        Performance.add_custom_monitor("Ammo/Rifle", ..., ...)

        // These one go under another category "Enemies"
	Performance.add_custom_monitor("Enemies/Bats", ..., ...)
        Performance.add_custom_monitor("Enemies/Spiders", ..., ...)

        // And you could also add a monitor to an already existing category
	Performance.add_custom_monitor("Physics 3d/Bouncing", ..., ...)

        // The method call could be changed this way if preferred:
        Performance.add_custom_monitor(category, name, callable, params)
```
I think the user would be able to organize his monitors much better.

Maybe I'd also drop the "_custom" from the method names, there's no need to specify those are "custom" monitors that you're adding/removing.

2020-06-05 00:29 UTC, simpuid commented
`add_monitor("category/name" , callable...., params....)` seems the best option.

`add_monitor("category", "name", callable..., params....)` will cause problems because internally the ids used for those monitors would be something like `category/name`(That slash could be any ASCII symbol). Method calls like `Performance.add_monitor("a/b", "c", callable..., params...)` would cause confusion among users.

I think something like this will work
* `/` is present => use the supplied category
* `/` is absent => use the `Custom` category.

Adding monitors to built-in categories seems difficult but I think I can do it. However keep in mind that there is no `Physics 3d` . The `Performance` class uses snake_case internally i.e. `physics_3d` is converted to `Physics 3d`, so something like `physics_3d/bouncing` will use the builtin category. This opens the issue of name collisions with monitors like `Physics 3d/bouncing` with `physics_3d/bouncing`
@Faless @mhilbrunner What are your opinions about categorizing custom monitors?

2020-06-05 00:31 UTC, simpuid commented
Accidently clicked the `Close and comment`

2020-06-05 06:26 UTC, simpuid commented
@samdze  Went ahead with Capitalized category names. (`Physics 3d/something` will work now).
The only limitation is that `Custom/something` and `something` both will be displayed in `Custom` category.

2020-06-05 09:13 UTC, samdze commented
@simpuid Seems good!

I also saw that renaming the methods to `add_monitor(...)`, `get_monitor(...)` and `has_monitor(...)` would collide with the already existing `get_monitor(Monitor p_monitor)`, used for built-in monitors.
So while I'd prefer not having that "_custom" in the method names, it's probably necessary if a more extensive refactor is unwanted.

2020-06-05 12:52 UTC, samdze commented
I also opened this proposal, you may be interested.
https://github.com/godotengine/godot-proposals/issues/1014

2020-06-16 15:31 UTC, Faless reviewed
This looks great! Excellent work :medal_sports: . I'm wondering if we should move the performance drawing functions (setup and parsing) to its own `EditorDebuggerPerformance` class. What do you think @simpuid ?

EDIT: That would also help keeping things clean if we implement godotengine/godot-proposals#1014 in the future (which I think it's a good idea).

2020-06-16 15:48 UTC, simpuid commented
> This looks great! Excellent work medal_sports . I'm wondering if we should move the performance drawing functions (setup and parsing) to its own `EditorDebuggerPerformance` class. What do you think @simpuid ?
> 
> EDIT: That would also help keeping things clean if we implement [godotengine/godot-proposals#1014](https://github.com/godotengine/godot-proposals/issues/1014) in the future (which I think it's a good idea).

Yes, we can do that (just like `EditorProfiler`, `EditorVisualProfiler` and `EditorNetworkProfiler`). I can also take help from their implementations.

Shouldn't we name it `EditorPerformance`? (there is no "debugger" word in `EditorProfiler`, `EditorVisualProfiler` and `EditorNetworkProfiler`)

2020-06-16 16:07 UTC, Faless commented
> Shouldn't we name it `EditorPerformance` / `EditorPerformanceProfiler`?

Yeah, I agree, both sounds good.
Maybe the latter is more in line with `RemoteDebugger::PerformanceProfiler` in `remote_debugger.cpp`

2020-06-22 13:45 UTC, simpuid commented
> Yeah, I agree, both sounds good.
> Maybe the latter is more in line with `RemoteDebugger::PerformanceProfiler` in `remote_debugger.cpp`

@Faless I rewrote the parsing and drawing logic to a separate class `EditorPerformanceProfiler`
The implementation deviates from the proposal but it's better.
Changes:
* Built-in performance monitors' data are stored the same way as custom monitor.
* There is only one drawing function `EditorPerformanceProfiler::_monitor_draw`, godotengine/godot-proposals#1014 could be implemented there for both type of monitors.
* There are only 2 types of messages instead of three
    1. 'performance:profile_frame' : contains the data of all (builtin + custom) monitors.
    2. 'performance:profile_names' : contains the name of custom monitors.

2020-06-27 17:43 UTC, simpuid commented
@samdze Added horizontal guide lines and a vertical marker line that can be placed by clicking LMB.
I think that should be enough for godotengine/godot-proposals#1014

Does text of horizontal guide lines looks too cumbersome?

![sample](https://user-images.githubusercontent.com/37181756/85928545-61637000-b8cb-11ea-9034-983aeb612fbf.png)

2020-06-27 18:47 UTC, Calinou commented
@simpuid There seem to be a lot of horizontal lines on your graph. My PR made it so the number of lines depends on the monitor's height (and never exceeds 5).

2020-06-27 18:54 UTC, simpuid commented
> @simpuid There seems to be a lot of horizontal lines on your graph. [My PR](https://github.com/godotengine/godot/pull/39719) made it so the number of lines depends on the monitor's height (and never exceeds 5).

I am calculating the number of horizontal lines depending on the graph height and text height (So they can be rendered easily)
```
int line_count = rect.size.height / (graph_font->get_height() * 2);
```
@Calinou should I limit it to max 5?

2020-06-27 20:00 UTC, Calinou commented
> @Calinou should I limit it to max 5?

Yes, there's not much benefit to having more than 5.

2020-06-29 12:47 UTC, simpuid commented
Added documentation

2020-06-29 16:12 UTC, Faless approved these changes
Looking good! Amazing job :trophy: !

2020-06-29 16:14 UTC, Faless requested changes
Actually, I think you accidentally committed ProjectSetting.xml, could you revert that? Thanks

2020-06-29 16:25 UTC, simpuid commented
> Actually, I think you accidentally committed ProjectSetting.xml, could you revert that? Thanks

Sorry! Reverted.

2020-06-29 18:20 UTC, akien-mga commented on doc/classes/Performance.xml
> +				[code]
This should be [codeblock]. [code] is online code like `this`.

2020-06-29 18:20 UTC, akien-mga commented on editor/debugger/editor_performance_profiler.cpp
> +EditorPerformanceProfiler::Monitor::Monitor() {
Initialize members directly when declaring them in the header.

2020-06-29 18:20 UTC, akien-mga commented on editor/debugger/editor_performance_profiler.h
> +#endif //EDITOR_PERFORMANCE_PROFILER_H
Add space after `//`.

2020-06-29 20:18 UTC, merged

2020-06-29 20:18 UTC, akien-mga commented
Thanks!

2020-06-29 20:28 UTC, neikeq commented
Your custom monitors will make a fine addition to our collection.

2020-06-29 20:36 UTC, williamd1k0 commented
Sorry, but is this portable for 3.2 branch? :P

2020-06-29 20:52 UTC, simpuid commented
> Sorry, but is this portable for 3.2 branch? :P

I don't think so! Callables are not available in 3.2 branch :(

2020-06-30 10:06 UTC, Faless commented
> Sorry, but is this portable for 3.2 branch?

Not really, the whole debugger was heavily refactored in the master branch, backporting is unlikely.