Add note about automatic window title to FileDialog documentation.
godotengine/godot pull request #39322
Opened 2020-06-05 13:53 UTC by dominiks

For #38896

2020-06-05 14:14 UTC, Calinou requested changes

2020-06-05 14:14 UTC, Calinou commented on doc/classes/FileDialog.xml
> +		FileDialog is a preset dialog used to choose files and directories in the filesystem. It supports filter masks. The FileDialog automatically sets its window title according to the [code]mode[/code]
Use property references so they can be clicked:

```suggestion
		FileDialog is a preset dialog used to choose files and directories in the filesystem. It supports filter masks. The FileDialog automatically sets its window title according to the [member file_mode. If you want to use a custom title, disable this by setting [member mode_overrides_title] to [code]false[/code].
```

2020-06-05 14:15 UTC, Calinou requested changes

2020-06-05 14:15 UTC, Calinou commented on doc/classes/FileDialog.xml
> +		FileDialog is a preset dialog used to choose files and directories in the filesystem. It supports filter masks. The FileDialog automatically sets its window title according to the [member file_mode
Sorry, I made a typo in the previous suggestion:

```suggestion
		FileDialog is a preset dialog used to choose files and directories in the filesystem. It supports filter masks. The FileDialog automatically sets its window title according to the [member file_mode]. If you want to use a custom title, disable this by setting [member mode_overrides_title] to [code]false[/code].
```

2020-06-05 18:39 UTC, YeldhamDev commented
Please squash your commits: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

2020-06-05 20:57 UTC, YeldhamDev approved these changes

2020-06-15 11:22 UTC, merged

2020-06-15 11:22 UTC, akien-mga commented
Thanks!

2020-06-15 11:22 UTC, akien-mga commented
Cherry-picked for 3.2.2.