Allow copying property path from inspector.
godotengine/godot pull request #39404
Opened 2020-06-09 01:38 UTC by rcorre

If you hover over a property lable in the inspector dock and press
the "property_ediotr/copy_property_path" shortcut (ctrl+c by default),
the complete property path will be copied to the system clipboard. This
is especially useful for the `AnimationTree`, where code might reference
properties like "parameters/state/aim/move/blend_position".

Resolves godotengine/godot-proposals#106.

One issue is that if you click a property, then click on the node you
currently have selected in the node tree, then press ctrl+c, it will
still copy the selected property path rather than the node path. If you
click on a different node in the nodetree, however, ctrl+c will return
to copying the nodepath.

2020-06-09 12:18 UTC, KoBeWi commented
There are 2 related PRs right now: #39398 and #34892

The reason I bring this up is that if the all 3 were going to be merged, the shortcut for your feature would need to changed to Ctrl + Shift + C for consistency (my scene tree PR changes Copy Node Path to this shortcut). But this is probably not important for now, as it's uncertain which of these PRs are going to make it 🤔

2020-06-09 12:29 UTC, rcorre commented
@KoBeWi it seems like your PR adds `ctrl+c` as an [accelerator](https://docs.godotengine.org/en/latest/classes/class_popupmenu.html#class-popupmenu-method-add-item), not as a global keyboard shortcut. I just tried it out and it seems to work for me, as in `ctrl+c` will focus the menu item for copy, but does not automatically copy if the menu isn't open.

I'm thinking we should add two separate editor shortcuts, "property_editor/copy_property_path" and "property_editor/copy_property", so the user can create individual bindings for either, both separate from "copy_node_path".

2020-06-09 12:29 UTC, rcorre commented
(BTW I'm trying to combine the two efforts now)

2020-06-09 12:37 UTC, rcorre commented
NVM, I misread. Your interpretation of accelerators is correct.

2020-06-09 13:07 UTC, rcorre commented
@KoBeWi I think I combined the two in a way that makes sense. Now the popup menu has options for "copy property (ctrl+c)", "paste property (ctrl+v)", and "copy property path (ctrl+shift+c)". The keybindings work -- I followed the same pattern that seemed to be used for other popup menus with shortcuts, e.g. https://github.com/rcorre/godot/blob/d110aa421b04312e428baf93e97f40049e452381/editor/scene_tree_dock.cpp#L2467.

2020-06-09 13:26 UTC, rcorre commented
I'm getting these warnings though, which I haven't figured out, as `InspectorDock` seems to be constructed before `InspectorProperty`:

```
ERROR: Used ED_GET_SHORTCUT with invalid shortcut: property_editor/copy_property.
   at: ED_GET_SHORTCUT (editor/editor_settings.cpp:1514)
ERROR: Cannot add item with invalid ShortCut.
   at: add_shortcut (scene/gui/popup_menu.cpp:711)
ERROR: Used ED_GET_SHORTCUT with invalid shortcut: property_editor/paste_property.
   at: ED_GET_SHORTCUT (editor/editor_settings.cpp:1514)
ERROR: Cannot add item with invalid ShortCut.
```

Its also weird that it throws for those two, but not `copy_property_path`. The shortcuts seem to work in spite of the warnings.

2020-08-10 23:17 UTC, HEAVYPOLY commented
Heads up this doesn't seem to be working on Mac with 3.2.3 rc3.  Also the editor hotkey for copy property was blank by default.  I tried setting to Command C and not getting any copy. 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/24432677/89840365-ebd2fc80-db24-11ea-8f7b-6cb2051bc2c5.png">

2020-08-11 05:48 UTC, akien-mga commented
@HEAVYPOLY This hasn't been merged yet so it's not included in 3.2.3 RC 3. Or do you mean that you cherry-picked this PR manually and made your own build?

2020-08-11 14:48 UTC, rcorre commented
I just backported to 3.2 [here](https://github.com/rcorre/godot/commits/proposal-106-copy-prop-path-backport-3.2) and it seems to work. I don't have a mac to test on though.

2020-08-11 17:17 UTC, HEAVYPOLY commented
@akien-mga Ah my mistake.  Look forward to trying this in the next release!

2021-08-20 15:26 UTC, KoBeWi approved these changes
Needs rebase, but otherwise looks good.

EDIT:
Well, seems like there is issue with Ctrl+V changing pivot if compatible node is selected (e.g. Sprite). The inspector doesn't correctly grab focus. This wasn't important before, but now that we have this inspector-specific shortcut, this should be solved somehow. Not sure how though, it could be done in another PR.

2021-08-22 12:18 UTC, rcorre commented
@KoBeWi I see what you're saying about the pivot shortcut, though it also conflicts with the existing copy/paste node shortcuts, so it seems like a more general problem that needs to be solved outside the context of this.

Is there a customizeable shortcut for changing the pivot? I couldn't find it (even typing `ctrl+v` into the editor shortcuts menu).

2021-08-22 13:45 UTC, KoBeWi commented
> Is there a customizeable shortcut for changing the pivot? I couldn't find it (even typing ctrl+v into the editor shortcuts menu).

The shortcut is just V and it's not customizable. It wouldn't be a problem if clicking a property would focus the inspector.

2021-08-22 13:53 UTC, KoBeWi requested changes
Wait, actually there is one thing that needs to be changed. Inspector creates many EditorProperties at once and creating a menu for each of them is inefficient. They should be created on demand. See #50530 Just add a method `_ensure_popup()` and call it each time the popup is supposed to open.

Another thing which will be relevant after #51722 is that you need to block the popup and shortcuts when the property is readonly (by using `is_read_only()`).

2021-08-22 17:23 UTC, rcorre commented
The popup is now created just-in-time. I'm assuming that if it is readonly, I should block the paste shortcut, but not the popup as a whole, since copy/copy_path should still be allowed, right?

2021-08-22 18:38 UTC, KoBeWi commented on editor/editor_inspector.cpp
> +		menu->set_position(get_global_transform().xform(get_local_mouse_position()));
This isn't correct way to set popup position anymore. Use `menu->set_position(get_screen_position() + get_local_mouse_position());` instead.

2021-08-22 18:45 UTC, KoBeWi commented
You are right, only paste should be blocked.

btw I now noticed that shortcut checking in `_unhandled_key_input()` and switch cases in `menu_option()` are ordered differently than the enum. You should reorder the code.

2021-08-22 20:39 UTC, rcorre commented
Fixed the enum ordering and respected is_read_only:

![menu](https://user-images.githubusercontent.com/2496231/130369400-15510a5a-f26d-496b-b6aa-4ce3f5dd39b2.png)

2021-08-22 22:13 UTC, KoBeWi approved these changes
Looks good now.

Will need update if #51983 gets merged first.

2021-08-22 22:19 UTC, pycbouh commented
I don't see it mentioned in the OP, but from the last screenshot... does this implement https://github.com/godotengine/godot-proposals/issues/3098?

2021-08-22 22:21 UTC, KoBeWi commented
Partially, Open in Help would be missing.

2021-08-22 22:22 UTC, pycbouh commented
Yeah, and reset I guess? But since the proposal is based around the problem of copying the path, I think we can say that it closes it, and maybe do a follow-up PR that adds extra options.

2021-08-22 22:25 UTC, KoBeWi commented
I wouldn't close the proposal, rather just leave a comment that it's halfway there.

2021-08-26 22:39 UTC, merged

2021-09-21 12:34 UTC, akien-mga commented
This would require a dedicated PR for `3.x` if a backport is wanted.

2021-09-21 16:29 UTC, rcorre commented
Pretty sure I still have the old `3.x` branch around. I can work on a backport if we want one.

2021-11-02 15:55 UTC, Calinou commented
> Pretty sure I still have the old `3.x` branch around. I can work on a backport if we want one.

A backport to `3.x` would be welcome (so that it can be merged for 3.5).

2022-05-18 17:57 UTC, Calinou commented
I can't find the `3.x` version of this pull request. Can anyone link it here?

2022-05-18 18:00 UTC, KoBeWi commented
#54913