add warning for move_and_slide()
godotengine/godot pull request #39508
Opened 2020-06-13 14:40 UTC by JiRuifanCR

This adds warning for move_and_slide when the up direction is not a normalized vector.

2020-06-13 15:03 UTC, JiRuifanCR commented
I realized that checking for normal has basically the same cost as normalizing. Not sure if this is a good idea anymore. Still leaving this as open though.

2020-06-13 17:29 UTC, madmiraal requested changes
@JiRuifanCR You're right, instead of a warning, it is actually worth creating a local variable `up_direction` at the start of the `move_and_slide()` function that normalizes `p_up_direction`; and use that everywhere that `p_up_direction` is currently used.

Furthermore, this should also be done to `move_and_slide_with_snap()`. You'll notice that `move_and_slide_with_snap()` already normalizes `p_up_direction` before taking the dot product.

**Edit:** As mentioned in the [issue comment](https://github.com/godotengine/godot/issues/39506#issuecomment-643652882), it's probably the right time to change this to `safe_acos` too.

2020-06-13 18:07 UTC, JiRuifanCR commented
> @JiRuifanCR You're right, instead of a warning, it is actually worth creating a local variable `up_direction` at the start of the `move_and_slide()` function that normalizes `p_up_direction`; and use that everywhere that `p_up_direction` is currently used.
> 
> Furthermore, this should also be done to `move_and_slide_with_snap()`. You'll notice that `move_and_slide_with_snap()` already normalizes `p_up_direction` before taking the dot product.
> 
> **Edit:** As mentioned in the [issue comment](https://github.com/godotengine/godot/issues/39506#issuecomment-643652882), it's probably the right time to change this to `safe_acos` too.

Thank you for the input. Will change this asap (about 24 hrs later). However, as Calinou mention

2020-06-13 18:13 UTC, Calinou commented
@JiRuifanCR We can perform the check in only debug builds using the `ERR_FAIL_*` macros (see [Common engine methods and macros](file:///home/hugo/Documents/Git/godotengine/godot-docs/_build/html/development/cpp/common_engine_methods_and_macros.html)).

2020-06-13 18:28 UTC, JiRuifanCR commented
> 
> 
> @JiRuifanCR We can perform the check in only debug builds using the `ERR_FAIL_*` macros (see [Error macros](https://docs.godotengine.org/en/latest/development/cpp/common_engine_methods_and_macros.html#error-macros)). Like this:
> 
> https://github.com/godotengine/godot/blob/58034f39829b8b95a3e5d4c6e8d1ab0427371548/core/math/vector3.h#L430

Thank you. However the above comment by @madmiraal seem to indicate that the cost induced by normalization isn't that significant? Anyways I'll just add the ERRs and safe_acos() first.

2020-06-14 09:47 UTC, madmiraal commented
> We can perform the check in only debug builds using the ERR_FAIL_* macros

Actually, the checks are still performed, only the error messages aren't printed.

2020-06-16 09:31 UTC, akien-mga commented
Superseded by #36079. Thanks for the contribution nevertheless as it helped further the discussion around what the best fix would be.

2020-06-16 09:31 UTC, closed without merging