Add description for "absorbent" and "rough"
godotengine/godot pull request #39546
Opened 2020-06-14 21:25 UTC by vorblen

2020-06-15 07:45 UTC, AndreaCatania commented
The description is correct, however I've the impression that it shows too much implementation details, causing some more confusion.
@Calinou you can judge this better than me, if you think it's fine then it's fine to me too.

2020-06-15 08:12 UTC, Calinou requested changes

2020-06-15 08:12 UTC, Calinou commented on doc/classes/PhysicsMaterial.xml
> +			Subtracts the bounciness off of the colliding object's bounciness instead of adding it.
```suggestion
			If [code]true[/code], subtracts the bounciness from the colliding object's bounciness instead of adding it.
```

2020-06-15 08:12 UTC, Calinou commented on doc/classes/PhysicsMaterial.xml
> +			By default, when two objects collide, the physics engine uses the lowest friction. Rough overwrites this and causes it to use the friction of the rough object.
```suggestion
			If [code]true[/code], the physics engine will use the friction of the object marked as "rough" when two objects collide. If [code]false[/code], the physics engine will use the lowest friction of all colliding objects instead.
```

2020-06-15 08:17 UTC, AndreaCatania commented on doc/classes/PhysicsMaterial.xml
> +			By default, when two objects collide, the physics engine uses the lowest friction. Rough overwrites this and causes it to use the friction of the rough object.
Much better

2020-06-15 08:55 UTC, vorblen commented
Should the docs also mention that if `rough` is true for both objects, then it will use the lowest friction?

2020-06-15 10:27 UTC, AndreaCatania commented
Yes, it's nice to have it. But please note that when both body have rough frictions the **higher** is take.

2020-06-15 11:19 UTC, akien-mga commented
It seems like you merged the `upstream/master` branch on your own branch (with `git merge`), instead of pulling (with `git pull --rebase`).

This PR should be rebased to keep only one commit which would be the result of squashing your 4 documentation changes. See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).

If you're not very experienced with salvaging Git branches when they're in this state, I'd suggest make a new branch based on the upstream `master`, and redo your changes as one commit, which you can then force push to this PR: `git push origin your-local-branch:master -f`.

2020-06-15 11:45 UTC, akien-mga approved these changes

2020-06-15 16:06 UTC, AndreaCatania approved these changes
Awesome, Thanks!

2020-06-15 18:45 UTC, merged

2020-06-15 18:45 UTC, akien-mga commented
Thanks!

2020-06-18 08:55 UTC, akien-mga commented
Cherry-picked for 3.2.2.