Project Settings 'restart' message put focus on editor rather than project itself
godotengine/godot pull request #39661
Opened 2020-06-18 22:44 UTC by dreamsComeTrue

Fixes: #39613

2020-06-19 07:24 UTC, Calinou requested changes

2020-06-19 07:24 UTC, Calinou commented on editor/project_settings_editor.cpp
> +	restart_label->set_text(TTR("Changed settings will be applied to the editor after restart."));
```suggestion
	restart_label->set_text(TTR("Changed settings will be applied to the editor after restarting."));
```

2020-06-19 19:17 UTC, dreamsComeTrue commented on editor/project_settings_editor.cpp
> +	restart_label->set_text(TTR("Changed settings will be applied to the editor after restart."));
Done!

2020-06-21 06:15 UTC, aaronfranke approved these changes

2020-06-21 10:21 UTC, merged

2020-06-21 10:21 UTC, akien-mga commented
Thanks!

2020-06-21 19:37 UTC, akien-mga commented
Not cherry-picking for 3.2.2 as it would break translations, and IMO the original string wasn't bad enough to justify it in the stable branch (but it's fine for 4.0, translations will have time to be updated).