Added Rigid Body Method "get_inertia_tensor"
godotengine/godot pull request #39817
Opened 2020-06-25 00:33 UTC by yrk06

## Exposed inertia tensor to GDScript

### How
This was done by creating a variable on the rigidbody class. The variable receives the inverse inertia tensor value each time the RigidBody state gets changed, then the `get_inertia_tensor()` returns the inverse of the inverse_inertia_tensor. The method is exposed to GDScript with `bind_method`

### Consequences
As a consequence of this, rotations with rigid bodies can be controlled more accurately through the use of Physics Formulas of Torque

### Requests
This was proposed in: https://github.com/godotengine/godot-proposals/issues/1114 also in https://github.com/godotengine/godot/issues/2125 and kind of related to https://github.com/godotengine/godot-proposals/issues/945

2020-06-25 07:33 UTC, Calinou commented on doc/classes/RigidBody.xml
> +				Returns the Inertia Tensor Basis. This is used to calculate the required torque for an angular acceleration on the RigidBody.
Is there a reason "Inertia Tensor Basis" is capitalized?

```suggestion
				Returns the inertia tensor basis. This is used to calculate the required torque for an angular acceleration on the RigidBody.
```

2020-06-25 07:34 UTC, Calinou commented
Also, pull requests should be opened against the `master` branch unless it *can't* be applied to the `master` branch for some reason. We can then cherry-pick the change into the `3.2` branch.

2020-06-25 10:54 UTC, yrk06 commented
> Also, pull requests should be opened against the `master` branch unless it _can't_ be applied to the `master` branch for some reason. We can then cherry-pick the change into the `3.2` branch if it doesn't break backwards compatibility.

I tried to make the change using the Master branch, but I couldn't get the engine to run on my local computer. That's why I decided to go with the 3.2 version

2020-06-25 19:39 UTC, yrk06 commented on scene/3d/physics_body.cpp
> +	return inverse_inertia_tensor.inverse();
I see, thanks for pointing out. I didn't know that. I knew only about the convenience for calculations, but in order to calculate torque, the not-inversed is needed, thus the function was to get the not-inversed. I'll change that and commit it

2020-07-02 07:02 UTC, madmiraal reviewed
Looks good, aside from my nitpick below, the commits just need to be squashed into a single commit.

2020-07-02 16:53 UTC, madmiraal approved these changes

2020-07-02 16:56 UTC, yrk06 commented
I force pushed the commit again in order to change the method name in the commit from `get_inertia_tensor` to `get_inverse_inertia_tensor`

2020-07-02 17:16 UTC, madmiraal requested changes
I'm was just looking at that. This should have been created as a property with a getter and a setter.

2020-07-02 18:13 UTC, yrk06 commented
> I'm was just looking at that. This should have been created as a property with a getter and a setter.

I didn't do it because the idea was just exposing using the already existent function on class `PhysicsDirectBodyState` in C++ to RigidBodies in GDscript

I Haven't looked yet on how the engine calculates the Inertia Tensor, but my guess is that it would require a new function inside the Bullet Physics Classes in order to Overwrite it with a Setter

2020-07-02 18:30 UTC, madmiraal commented
Okay, let's leave it as it is then.

One more change, please update the commit message, which still has all the individual commit messages to just the first commit message. Also, commit messages should be written in the present tense; so 'Add Rigid Body Method "get_inverse_inertia_tensor"'.

Finally, please create a second PR against the master branch referencing this one. If you've thoroughly tested it on the 3.2 branch, you should be confident that it will work on the master branch without being able to run a test project.

2020-07-20 07:52 UTC, madmiraal approved these changes

2020-07-21 14:50 UTC, merged

2020-07-21 14:51 UTC, akien-mga commented
Thanks!