Enhance visual script, selection area popped up when disconnected nodes
godotengine/godot pull request #40045
Opened 2020-07-02 06:57 UTC by ChristopheLY

2020-07-02 08:59 UTC, akien-mga commented on scene/gui/graph_edit.cpp
> +
Trailing whitespace.

2020-07-02 08:59 UTC, akien-mga commented on modules/visual_script/visual_script_editor.cpp
> +void VisualScriptEditor::_graph_disconnected(const String &p_from, int p_from_slot, const String &p_to, int p_to_slot, bool is_pressed) {
The parameter should be `p_is_pressed`.

2020-07-02 09:01 UTC, akien-mga commented
CC @swarnimarun @fire @kidrigger

2020-07-03 10:07 UTC, swarnimarun requested changes
If there's a need for them feel free to explain but I don't think there is a need for calling the function multiple times.

2020-07-03 10:07 UTC, swarnimarun commented
I still need to test the actual patch will do that later though.

2021-02-27 18:28 UTC, aaronfranke commented
@ChristopheLY Is this still desired? If so, it needs to be [rebased](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) and tested on the latest master branch. Additionally, the commits need to be squashed into one (or few).

2021-07-13 17:53 UTC, DavidCambre commented
I do not experience the source bug 11641

2022-08-24 14:03 UTC, akien-mga commented
Closing as [we just removed VisualScript for 4.0](https://github.com/godotengine/godot/pull/64822), so this can no longer be evaluated as is.

The VisualScript module has been moved to https://github.com/godotengine/godot-visual-script with the aim that it might be ported to a GDExtension if there are interested contributors to do so. Further work to improve the features could be done on that repository too (so currently there isn't anyone dedicated to maintain this repository, it will depend again on whether some contributors step up to do so).

2022-08-24 14:03 UTC, closed without merging