Allow Area2D mouse events without collision layer
godotengine/godot pull request #40193
Opened 2020-07-07 22:54 UTC by KoBeWi

Resolves #11159
And consequently reverts #28608

`_intersect_point_impl()` isn't used for anything else than mouse picking, so making it ignore layers is safe.

2020-07-08 04:51 UTC, akien-mga commented
How is the behavior in Area3D btw?

2020-07-08 08:01 UTC, KoBeWi commented
3D ignores layers too.

2020-07-08 09:42 UTC, madmiraal requested changes
It fixes #11159 in 2D, but, to echo @akien-mga's question, it is still broken in 3D; both Godot and Bullet physics. This PR should be extended to fix 3D Godot and Bullet physics too to make it all consistent. Otherwise, I think it's a good solution. :+1:

2020-07-08 09:42 UTC, madmiraal commented on servers/physics_2d/space_2d_sw.cpp
> -	if (!(p_object->get_collision_layer() & p_collision_mask)) {
If we're updating this, then we should add the missing blank line at the end of the includes.

2020-07-08 10:31 UTC, KoBeWi commented
> it is still broken in 3D; both Godot and Bullet physics

It's not, I tested it.

2020-07-08 11:11 UTC, madmiraal commented
I can't test it on 4.0, because master doesn't currently work on my computer, but I created a [3.2 backport](https://github.com/madmiraal/godot/tree/PR40193-3.2) (although it's not necessary since the PR doesn't change any 3D code), and tested using this simple project:
[11159.zip](https://github.com/godotengine/godot/files/4890238/11159.zip)

Moving the mouse over and off the cube should trigger signals that print "Mouse entered" and "Mouse exited" messages. Without a `Collision Layer` selected, nothing is printed; with a `Collision Layer` selected, the messages are printed. This happens with both Godot and Bullet physics.

2020-07-08 11:41 UTC, KoBeWi commented
Ok, my bad. For whatever reason the layer in my scene had a value of 2147483648 and it was showing in the inspector as empty :I

I looked into the 3D code and it looks more complicated, but I'll try to fix it too.

2020-07-08 12:25 UTC, akien-mga commented
> For whatever reason the layer in my scene had a value of 2147483648 and it was showing in the inspector as empty :I

Sounds like uninitialized memory.

2020-07-09 00:30 UTC, KoBeWi commented
Ok, I managed to fix it for GodotPhysics, but I have no idea how to do it for Bullet. It could be done in another PR, by someone who is more knowledgeable on that regard. (Also the issue mentioned specifically 2D, so technically it is resolved >_>)

2020-07-09 13:50 UTC, madmiraal commented
> I have no idea how to do it for Bullet. It could be done in another PR, by someone who is more knowledgeable on that regard.

@KoBeWi I've sent you a [PR](https://github.com/KoBeWi/godot/pull/1) for the same solution in Bullet physics.

2020-07-09 21:00 UTC, KoBeWi commented
@madmiraal Thanks for the code! Added it and rebased. I thought you'd be credited automatically, but seems like git removed you from the commit. I could manually add you as co-author if you want.

2020-07-10 10:50 UTC, madmiraal commented
> I could manually add you as co-author if you want.

Not essential, but while you're updating the commit message to "Allow Area2D **and 3D** mouse events without a collision layer" that would be nice. :-)

2020-07-10 13:49 UTC, madmiraal approved these changes

2020-07-10 22:26 UTC, merged

2020-07-10 22:27 UTC, akien-mga commented
Thanks!

2020-07-10 22:28 UTC, akien-mga commented
It changes behavior but I'd say it's a good change for 3.2.x too, do you agree?

2020-07-11 10:21 UTC, madmiraal commented
I agree. Although it is possible currently to disable an Area's pickability by removing it from all layers, the more logical approach is to disable pickable. It may be a long standing bug, but I don't think fixing it can be regarded as breaking compat.

@KoBeWi I have a ready-made [backport](https://github.com/madmiraal/godot/tree/PR40193-3.2) (with you as co-author) which I used for testing, ready for creating a PR; unless you want to do it.

2020-07-11 10:27 UTC, KoBeWi commented
> ready for creating a PR; unless you want to do it.

Go ahead.

2020-07-27 20:43 UTC, akien-mga commented
Reverting as per https://github.com/godotengine/godot/issues/40705#issuecomment-664554271, to fix regression #40705.