Fix cancel/OK button order on macOS
godotengine/godot pull request #40268
Opened 2020-07-10 19:39 UTC by DanielZTing

Closes #40216.

Also renamed the function so it no longer does the opposite of what it says and I personally can't think of any downsides. And I would feel guilty about wasting a CI build on a 0.5-line change.

2020-07-10 20:02 UTC, Calinou requested changes

2020-07-10 20:02 UTC, Calinou commented on doc/classes/ProjectSettings.xml
>  			If [code]true[/code], swaps OK and Cancel buttons in dialogs on Windows and UWP to follow interface conventions.
```suggestion
			If [code]true[/code], swaps Cancel and OK buttons in dialogs on Windows and UWP to follow interface conventions.
```

2020-07-10 20:16 UTC, DanielZTing commented
Fixed description in `doc/classes/ProjectSettings.xml`; rebased and fixed merge conflict following #40253.

2020-07-10 20:18 UTC, bruvzg approved these changes

2020-07-11 09:27 UTC, Xrayez commented
> And I would feel guilty about wasting a CI build on a 0.5-line change.

Please don't feel like that, the stability of the engine is more important compared to saving CI build times, in fact it was made for that. 🙂

2020-07-15 07:14 UTC, Calinou approved these changes

2020-07-15 07:21 UTC, merged

2020-07-15 07:21 UTC, akien-mga commented
Thanks!