fixed documentation for get_hit_length of spring arm 3D
godotengine/godot pull request #40605
Opened 2020-07-22 19:04 UTC by QbieShay

Solves #40585

2020-07-22 19:58 UTC, Calinou requested changes

2020-07-22 19:58 UTC, Calinou commented on doc/classes/SpringArm3D.xml
> +				Returns the current length of the spring arm.
We prefer to use this more compact form, as per the [Docs writing guidelines](https://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html):

```suggestion
				Returns the spring arm's current length.
```

2020-07-23 08:34 UTC, merged

2020-07-23 08:34 UTC, akien-mga commented
Thanks!

2020-07-24 08:03 UTC, akien-mga commented
Cherry-picked for 3.2.3.