Make unsaved scripts in the script editor more user-friendly
godotengine/godot pull request #40647
Opened 2020-07-23 22:58 UTC by Xrayez

Closes #33313.

![Annotation 2020-07-24 014226](https://user-images.githubusercontent.com/17108460/88345619-00ef1380-cd4f-11ea-8dae-fdb3c99038e9.png)

Unsaved scripts were previously displayed with blank tabs, which are mostly a result of deleted or improperly moved scripts, which is another issue in and of itself: #27635.

This patch makes sure that those kind of scripts are displayed as "[unsaved]" now, and ensures that scripts are removed from the list while deleting scripts from the filesystem dock preventing the unsaved tabs to appear in the first place (a user is already prompted with "no undo" warning while deleting any file).

A user is always prompted to save those "[unsaved]" scripts if they attempt to close them without saving in any case except as described above.

These changes don't seem to re-introduce #40175, as I've modified the "save" condition to allow saving in-memory scripts (have no resource path associated).

This also helps #35211.

2020-07-24 08:54 UTC, Xrayez commented
To make sure there's no blank scripts appear at all, it's possible to update the script tabs on filesystem change, or whenever `_update_script_names()` is called. But built-in scripts which are not yet saved do appear as "unsaved" too, and if a user makes changes to that script and modifies the filesystem in any way, it would be lost, and I haven't found a way to automatically save built-in scripts once they're created, which of course would solve the issue. That's why I went for more conservative approach (only remove scripts which were explicitly requested to be removed, from within Godot editor).

2020-07-24 11:11 UTC, Xrayez commented
Figured that the "[unsaved]" message can be encoded directly within `ScriptTextEditor::get_name()`, so that they appear in both script list and when you're prompted to save the file (also adds extra "(*)" as a byproduct):

![Annotation 2020-07-24 135239](https://user-images.githubusercontent.com/17108460/88385566-3deef080-cdb7-11ea-8511-c582a8f1128d.png)

![Annotation 2020-07-24 135218](https://user-images.githubusercontent.com/17108460/88385573-40514a80-cdb7-11ea-8e51-edced48e3b76.png)

2020-07-24 11:45 UTC, akien-mga commented on editor/plugins/script_editor_plugin.cpp
> +	ClassDB::bind_method("_file_removed", &ScriptEditor::_file_removed);
It doesn't need a binding since it uses `callable_mp`.

2020-07-25 11:10 UTC, Paulb23 requested changes
Code looks good. Need to add the `get_name` and `is_unsaved` changes to `TextEditor` and `VisualScriptEditor`.

2020-07-25 12:43 UTC, Xrayez commented
Then it also requires implementing the auto-remove feature in all editors for consistency as well. With the current approach I feel like it's quite hacky, and with #40640 being merged it becomes less of an issue (blank tabs resulting from deleting or moving scripts would no longer generate an error on project startup), so I'm considering removing those and leave that for another PR which could possibly solve that on more global level (but see my failed attempts in #40634)... WDYT?

2020-07-25 13:01 UTC, Xrayez commented
What I mean is that, ideally the script/text resource would also have to be removed from the list if you delete the file outside of Godot. Even with this PR, the script/text would only be removed automatically when you use "Remove" from the filesystem dock (which could perhaps be considered a feature anyways?)

I haven't found any signal which could be used to detect external filesystem changes to determine exactly what files are moved/deleted. Ideally I'd like godotengine/godot-proposals#468 to get implemented for this. But if you'd like this to get cherry-picked to 3.2, I can leave those `get_meta` hacks for now.

2020-07-25 13:26 UTC, Paulb23 commented
Not sure I follow. 

`ScriptTextEditor`, `TextEditor` and `VisualScriptEditor` extend `ScriptEditorBase`, so the changes here already affect all three. 
The PR updates `ScriptTextEditor` to return "[unsaved]" instead of blank, I was suggesting that the "[unsaved]" return needs to be copied to the other two else we'll still get blank `TextEditors` and `VisualScriptEditors`. Unless it's not possible with their resources paths, so it should be limited to `ScriptTextEditor`?

 I'm not worried about deletion outside Godot, that's an entirely different use case.

2020-07-25 14:25 UTC, Xrayez commented
I think I just got confused:
```
class VisualScriptEditor : public ScriptEditorBase
class ScriptTextEditor : public ScriptEditorBase
class ScriptEditor : public PanelContainer
class TextEditor : public ScriptEditorBase
```
I'll need to return to this later to make sure we're on the same page, but yeah I just wondered if those deletion hacks are acceptable.

2020-07-25 20:09 UTC, Xrayez commented
Yeah sorry for the confusion, the plugin shares the same functionality across editors. To note, all have pretty much the same implementation for `get_name()` currently, except that they reference the edited resource differently (`script` vs `text_file` etc).

It isn't possible to test `TextFile` deletion because those are not recognized by the editor in the first place, but in theory should work (perhaps will work for custom imported text resources).

2020-07-26 12:32 UTC, Paulb23 approved these changes
No worries, needs a rebase after #33760 otherwise LGTM.

2020-07-26 15:11 UTC, merged

2020-07-26 15:11 UTC, akien-mga commented
Thanks!

2020-09-29 07:17 UTC, akien-mga commented
I'll opt against cherry-picking for now as this is non trivial to do. If the enhancements are wanted in `3.2`, a dedicated PR would be OK.