Fix bug #39630
godotengine/godot pull request #40649
Opened 2020-07-24 00:04 UTC by themvl

This fixes a bug where leading ant trailing white spaces weren't taken into account when changing the label alignment to right or center. The leading spaces was fixed by removing a line that ignored the first word considering spaces and the trailing by making a fake word cache with only the spaces.

2020-08-29 15:08 UTC, Paulb23 requested changes
Overall looks good, one small case that needs handling commented inline.

2020-08-31 09:39 UTC, akien-mga commented
Please squash the two commits into one, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).

2020-08-31 17:30 UTC, themvl commented
I am sorry dont really know what im doing yet haha but should be fixed now right?

2020-09-05 10:36 UTC, Paulb23 approved these changes
LGTM.

2020-09-05 10:38 UTC, merged

2020-09-05 10:38 UTC, akien-mga commented
Thanks!

2020-09-24 10:10 UTC, akien-mga commented
Cherry-picked for 3.2.4.