Added missing information about File.open_encrypted function to docs
godotengine/godot pull request #40816
Opened 2020-07-29 05:47 UTC by codetorex

When I tried this function it was giving ERR_INVALID_PARAMETER
Checked source and found a check about key length and thought it would be good to add this information to docs. 

https://github.com/godotengine/godot/blob/227494be59eca4f50604a9c90c3c36ed15e7ecc5/core/io/file_access_encrypted.cpp#L44

2020-07-29 07:42 UTC, Calinou requested changes

2020-07-29 07:42 UTC, Calinou commented on doc/classes/File.xml
> +				The provided key must have length of 32 bytes.
```suggestion
				The provided key be 32 bytes long.
```

2020-07-31 11:07 UTC, merged

2020-07-31 11:07 UTC, akien-mga commented
Thanks!

2020-07-31 11:09 UTC, akien-mga commented
Cherry-picked for 3.2.3.