Added set_extra_headers() to WebSocketServer
godotengine/godot pull request #40975
Opened 2020-08-02 16:08 UTC by rohanrhu

Hi, I'm resending PR to `master` branch with changes.

2022-01-30 11:09 UTC, rohanrhu commented
Please merge this PR. I'm still using my revision on my server because I need sending CORS headers for my game to connect my server from itch.io.

2022-01-30 15:20 UTC, Faless requested changes
See comments (`const` usage and `p_` parameters prefix).
Looks overall good but needs a rebase :+1: .

2022-01-30 15:20 UTC, Faless commented on modules/websocket/doc_classes/WebSocketServer.xml
> +				Sets extra headers.
```suggestion
				Sets additional headers to be sent to clients during the HTTP handshake.
```

2022-01-30 15:20 UTC, Faless commented on modules/websocket/emws_server.cpp
> +void EMWSServer::set_extra_headers(Vector<String> headers) {
```suggestion
void EMWSServer::set_extra_headers(const Vector<String> &p_headers) {
```

2022-01-30 15:20 UTC, Faless commented on modules/websocket/emws_server.h
> +	void set_extra_headers(Vector<String> headers);
```suggestion
	void set_extra_headers(const Vector<String> &p_headers);
```

2022-01-30 15:20 UTC, Faless commented on modules/websocket/websocket_server.h
> +	virtual void set_extra_headers(Vector<String> headers) = 0;
```suggestion
	virtual void set_extra_headers(const Vector<String> &p_headers) = 0;
```

2022-01-30 15:20 UTC, Faless commented on modules/websocket/wsl_server.cpp
> +Error WSLServer::PendingPeer::do_handshake(const Vector<String> p_protocols, Vector<String> &extra_headers) {
```suggestion
Error WSLServer::PendingPeer::do_handshake(const Vector<String> p_protocols, const Vector<String> &p_extra_headers) {
```

2022-01-30 15:20 UTC, Faless commented on modules/websocket/wsl_server.cpp
> +void WSLServer::set_extra_headers(Vector<String> headers) {
```suggestion
void WSLServer::set_extra_headers(const Vector<String> &p_headers) {
```

2022-01-30 15:20 UTC, Faless commented on modules/websocket/wsl_server.h
> +		Error do_handshake(const Vector<String> p_protocols, Vector<String> &extra_headers);
```suggestion
		Error do_handshake(const Vector<String> p_protocols, const Vector<String> &p_extra_headers);
```

2022-01-30 15:20 UTC, Faless commented on modules/websocket/wsl_server.h
> +	void set_extra_headers(Vector<String> headers);
```suggestion
	void set_extra_headers(const Vector<String> &p_headers);
```

2022-01-30 15:25 UTC, Faless commented
> because I need sending CORS headers for my game to connect my server from itch.io.

While the PR scope is okay, I **strongly advise** (**STRONGLY!**) to put an HTTP proxy in front of it to manage both the extra headers and **requests sanitization**, [e.g. with nginx](https://nginx.org/en/docs/http/websocket.html)

2022-01-30 15:28 UTC, rohanrhu commented
> > because I need sending CORS headers for my game to connect my server from itch.io.
> 
> While the PR scope is okay, I **strongly advise** (**STRONGLY!**) to put an HTTP proxy in front of it to manage both the extra headers and **requests sanitization**, [e.g. with nginx](https://nginx.org/en/docs/http/websocket.html)

You mean using proxy for just sending additional headers? We can just send CORS headers when it is neccessary, why would we need to use a proxy?

2022-01-30 15:29 UTC, rohanrhu commented
Should I resolve conflicts or you do that?

2022-01-30 15:34 UTC, Faless commented
> Should I resolve conflicts or you do that?

I can't resolve the conflicts on your branch, please rebase and squash the commits, see here for instructions:
https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

2022-02-03 21:48 UTC, rohanrhu commented
> > Should I resolve conflicts or you do that?
> 
> I can't resolve the conflicts on your branch, please rebase and squash the commits, see here for instructions: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

Thank you @Faless I will resolve conflicts soon.

2022-02-17 08:08 UTC, Faless commented
> We can just send CORS headers when it is neccessary, why would we need to use a proxy?

As a bare minimum (it can offer more than that):
- Access/Error logging
- Requests filtering

I.e. a basic form of protection against the dozens of malicious requests (port scanners/exploit checkers/etc) you'll receive every day and that will otherwise end up being consumed by godot (most likely at a higher cost, and resulting in more errors in the godot log unrelated to the actual game).

2022-04-09 08:06 UTC, rohanrhu commented
Hiiiii @Faless I resolved conflicts with latest revision.

2022-04-09 14:27 UTC, Faless requested changes
Good job :+1: 
See review comment on adding the `override` keyword to `set_extra_headers` when overriding.
The commits also needs to be squashed together https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

2022-04-09 14:27 UTC, Faless commented on modules/websocket/emws_server.h
> +	void set_extra_headers(const Vector<String> &p_headers);
This needs to be marked as override
```suggestion
	void set_extra_headers(const Vector<String> &p_headers) override;
```

2022-04-09 14:28 UTC, Faless commented on modules/websocket/wsl_server.h
> +	void set_extra_headers(const Vector<String> &p_headers);
```suggestion
	void set_extra_headers(const Vector<String> &p_headers) override;
```

2022-04-10 17:43 UTC, rohanrhu commented
Hiiii @Faless I squashed it into one commit.

2022-04-12 10:38 UTC, Faless commented
CI is failing: https://github.com/godotengine/godot/runs/5964150172?check_suite_focus=true .
I think you just need to [re-update the class reference](https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html#updating-the-documentation-template) (`godot --doctool
`) and re-squash.

2022-04-12 11:07 UTC, rohanrhu commented
> CI is failing: https://github.com/godotengine/godot/runs/5964150172?check_suite_focus=true . I think you just need to [re-update the class reference](https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html#updating-the-documentation-template) (`godot --doctool `) and re-squash.

Meow.. I did it.

2022-04-12 14:16 UTC, Faless commented
I think CI will fail again, the doctool seem to not have worked properly :crying_cat_face: .
Can you please try applying this patch?

```diff
diff --git a/modules/websocket/doc_classes/WebSocketServer.xml b/modules/websocket/doc_classes/WebSocketServer.xml
index ef3279aac4..46b0274de3 100644
--- a/modules/websocket/doc_classes/WebSocketServer.xml
+++ b/modules/websocket/doc_classes/WebSocketServer.xml
@@ -60,6 +60,13 @@
 				If [code]false[/code] is passed instead (default), you must call [PacketPeer] functions ([code]put_packet[/code], [code]get_packet[/code], etc.), on the [WebSocketPeer] returned via [code]get_peer(id)[/code] to communicate with the peer with given [code]id[/code] (e.g. [code]get_peer(id).get_available_packet_count[/code]).
 			</description>
 		</method>
+		<method name="set_extra_headers">
+			<return type="void" />
+			<argument index="0" name="headers" type="PackedStringArray" default="PackedStringArray()" />
+			<description>
+				Sets additional headers to be sent to clients during the HTTP handshake.
+			</description>
+		</method>
 		<method name="stop">
 			<return type="void" />
 			<description>
```

2022-04-12 17:13 UTC, akien-mga approved these changes

2022-04-12 21:04 UTC, Faless approved these changes

2022-04-12 21:04 UTC, merged

2022-04-12 21:05 UTC, Faless commented
Thanks! :cat2: :trophy:

2022-04-13 09:27 UTC, akien-mga commented
Cherry-picked for 3.5.