Closing ColorPicker no longer modifies the scene
godotengine/godot pull request #41002
Opened 2020-08-03 16:51 UTC by AlphaOneProject

Editor now changes a color in the inspector only when it is different
from the current one.

Solves fake unsaved changes in editor after using the ColorPicker.

Resolves: #40879

2020-08-03 17:41 UTC, KoBeWi requested changes
The code looks fine.

Although the added comment should start with a capital letter and end with a period.
Also the commit message is a bit misleading, it should mention that the scene is not modified only if the color is the same.

2020-08-03 17:43 UTC, AlphaOneProject commented
Thank you, I'll correct this.

2020-08-03 17:51 UTC, AlphaOneProject commented
About the commit message, I'm not sure if this one is better:
"Only consulting color no longer modifies the scene"

What do you think?

2020-08-03 18:06 UTC, KoBeWi commented
Maybe something like "Modify the scene only when color changed"

2020-08-03 18:14 UTC, KoBeWi approved these changes

2020-08-11 17:09 UTC, merged

2020-08-11 17:09 UTC, akien-mga commented
Thanks!

2020-08-12 12:40 UTC, akien-mga commented
Cherry-picked for 3.2.3.