GLES3 fix normal map flipping with nvidia workaround
godotengine/godot pull request #41254
Opened 2020-08-14 13:01 UTC by lawnjelly

When not using TEXTURE_RECT path, flips have to sent via another method to the shader, to ensure that normal maps are correctly adjusted for direction. This PR adds an extra vertex attribute, LIGHT_ANGLE.

For nvidia workarounds, where the shader still has access to the final transform and extra matrix, the LIGHT_ANGLE can be 0 (no adjustment), 180 degrees for a horizontal flip, and negative indicates a vertical flip.

For batching path, the LIGHT_ANGLE can be used to directly specify the light angle for normal mapping, even when the final transform and extra matrix have been baked into vertex positions, so the same shader can be used for both.

Fixes #40905

## Notes
* This will also need to be fixed in GLES2 nvidia workaround and GLES2 batching, and can use the same method. (And also be applied in GLES3 batching)

2020-08-14 19:47 UTC, clayjohn reviewed
Overall, looks pretty good to me. 

Is it worth fixing GLES2 At the same time?

2020-08-14 19:47 UTC, clayjohn reviewed
Overall, looks pretty good to me. 

Is it worth fixing GLES2 At the same time?

2020-08-15 06:45 UTC, lawnjelly commented
> Overall, looks pretty good to me.
> 
> Is it worth fixing GLES2 At the same time?

Yes I'm just looking at GLES2 now. :+1:

I'm planning to have them separate PRs, for the nvidia workaround (with the shader change) and the batching (which will have the transforms baked in the rotate too).

The technique should be mostly similar though. The light angle approach was the best / most compact way I could come up with for storing all the information required.

2020-08-15 08:12 UTC, lawnjelly commented
Actually scratch that above idea about removing extra combinations.

On further investigation, the matrix is for combinations of color , uv, and light_angle, and for vertex arrays not shaders. Although a combination of no-uv and light_angle doesn't seem to make sense, I don't know enough to specifically say it can't happen due to either programmer or user error. So unless reviewers are confident enough for removing this, I'm inclined to leave as is. This will probably use negligible memory either way.

On the shader front, I'm now assuming they won't get created unless that particular combination of conditionals is bound, in which case I don't think there is a problem with unneeded shader combinations.

So yeah this PR should be good to go as is. :+1:

2020-08-22 05:36 UTC, clayjohn requested changes
Looks good! I would just move gl_check_error to rasterizer_gles3.cpp as it is not a canvas specific feature.

2020-08-23 17:52 UTC, clayjohn approved these changes

2020-09-28 08:40 UTC, merged

2020-09-28 08:40 UTC, akien-mga commented
Thanks!

2020-09-28 09:25 UTC, lawnjelly commented
Sorry I should have really closed this in advance, it is now part of unified batching and will be replaced when that PR is merged.

Still it should be okay to have this merged in the meantime as it will get some extra testing. :+1: :grin: