Viewport Usage enumeration documentation
godotengine/godot pull request #41394
Opened 2020-08-20 11:40 UTC by Yetizone

Mention that 3D effects are not available when using USAGE_2D

Opening this after the discussion in https://github.com/godotengine/godot-docs/pull/3911

I just noticed that the godot-docs README specifically points out not to edit class references in that repository.
I probably skipped that when reading, my bad :sweat_smile: 

Fixes https://github.com/godotengine/godot/issues/41151

2020-08-20 13:27 UTC, Calinou requested changes

2020-08-20 13:27 UTC, Calinou commented on doc/classes/Viewport.xml
> +			Allocates all buffers needed for drawing 2D scenes. This takes less VRAM than the 3D usage modes. Note that 3D rendering effects such as glow, HDR, SSAO, etc. are not available.
```suggestion
			Allocates all buffers needed for drawing 2D scenes. This takes less VRAM than the 3D usage modes. Note that 3D rendering effects such as glow and HDR are not available when using this mode.
```

I don't see how you could use SSAO in a purely 2D scene.

2020-08-20 13:27 UTC, Calinou commented on doc/classes/Viewport.xml
>  			Allocates buffers needed for 2D scenes without allocating a buffer for screen copy. Accordingly, you cannot read from the screen. Of the [enum Usage] types, this requires the least VRAM.
Also add the notice here for consistency:

```suggestion
			Allocates buffers needed for 2D scenes without allocating a buffer for screen copy. Accordingly, you cannot read from the screen. Of the [enum Usage] types, this requires the least VRAM. Note that 3D rendering effects such as glow and HDR are not available when using this mode.
```

2020-08-20 15:09 UTC, Yetizone commented
I noticed GitHub allowed me to automatically apply the suggested changes, but I think that would have created new commits, so I amended locally and force pushed the new commit. 

That resulted in me adding an extra space by mistake and having to force push two times.

Next time I'll try automatic apply -> pull locally -> squash -> force push, less error prone :) 

Dunno if anyone wanted to read this rambling, but anyway thanks for the help !

2020-08-20 18:30 UTC, clayjohn approved these changes

2020-08-21 00:05 UTC, merged

2020-08-21 00:05 UTC, akien-mga commented
Thanks!