Add FOG, RADIANCE, and IRRADIANCE shader overrides
godotengine/godot pull request #41415
Opened 2020-08-21 04:20 UTC by clayjohn

As discussed with reduz on IRC.

This allows users to implement their own custom fog, radiance, and irradiance by overriding the default behaviour. 

Closes https://github.com/godotengine/godot/issues/33616

In short, all 3 built ins just blend between the override and the internal value.

Documentation PR to follow.

2020-10-18 15:27 UTC, reduz requested changes

2020-10-18 15:27 UTC, reduz commented on servers/rendering/rasterizer_rd/shaders/scene_high_end.glsl
> +	if (custom_radiance.a > 0.0) {
I would use a define for this, making the shader fatter (more vgprs used) makes no sense imo.
like
#ifdef CUSTOM_RADIANCE_USED
code
#endif

check how other similar built-ins generate these ifdefs

2020-10-18 21:33 UTC, reduz approved these changes

2020-10-18 21:33 UTC, merged

2020-10-23 12:44 UTC, Calinou commented
Does this PR make it possible to implement https://github.com/godotengine/godot-proposals/issues/411 with a shader?

2020-10-23 15:13 UTC, clayjohn commented
@Calinou probably! I am a little unclear on exactly what that effect is. but now you can do anything you want!