State how 'MOUSE_MODE_CAPTURED' actually works in the 'Input' docs
godotengine/godot pull request #41441
Opened 2020-08-22 02:14 UTC by YeldhamDev

The docs previously erroneously stated that while on `MOUSE_MODE_CAPTURED`, the mouse was just kept inside the window, when in reality, it's locked at the center of the window. This PR gives the correct information, and also, gives a tip about getting the relative speed taken from the [online docs](https://docs.godotengine.org/en/latest/tutorials/inputs/mouse_and_input_coordinates.html).

2020-08-22 06:33 UTC, clayjohn approved these changes

2020-08-28 19:58 UTC, NathanLovato requested changes
I left a suggestion I feel makes the wording more accessible.

2020-08-28 19:58 UTC, NathanLovato commented on doc/classes/Input.xml
> +			[b]Note:[/b] Use [member InputEventMouseMotion.relative] instead of querying the mouse's position directly if processing of position changes is desired.
```suggestion
			[b]Note:[/b] If you want to process the mouse's movement in this mode, you need to use [member InputEventMouseMotion.relative].
```

2020-08-28 20:27 UTC, YeldhamDev commented on doc/classes/Input.xml
> +			[b]Note:[/b] Use [member InputEventMouseMotion.relative] instead of querying the mouse's position directly if processing of position changes is desired.
Changes made.

2020-08-28 21:02 UTC, NathanLovato approved these changes

2020-08-28 21:02 UTC, NathanLovato commented
Thanks much, looking good!

2020-08-28 21:30 UTC, merged

2020-08-28 21:30 UTC, akien-mga commented
Thanks!

2020-08-31 10:59 UTC, akien-mga commented
Cherry-picked for 3.2.3.