Fixes `is_action_released` firing with no modifiers
godotengine/godot pull request #41526
Opened 2020-08-26 01:39 UTC by Lunatoid

Should fix #34502
If you have an action like "CTRL + A", it will now fire on both press and release, however if you release "CTRL" while still holding "A" it will not fire the release event.

Also tested with just modifier keys like only "CTRL" or "CTRL+SHIFT" and that still works.

2021-01-20 07:24 UTC, aaronfranke commented
@Lunatoid Is this still desired? If so, this should be rebased on the latest master branch. While this PR has no conflicts, rebasing is helpful for ensuring the PR still works and it makes testing easier.

2021-01-20 07:48 UTC, Lunatoid commented
Just rebased locally and everything still works.

2021-01-20 09:00 UTC, akien-mga commented
Related to #44355, you might want to participate in the discussion there.

CC @EricEzaM @groud

2021-01-20 10:19 UTC, EricEzaM requested changes
Its buggy for me. MRP attached.

I have 2 actions set up. "z" and "ctrl z". Press Ctrl Z, and both "Only Z" and "Ctrl Z" are printed to the console (expected, although I disagree that this should always be the case, hence #44355). Now, let go of control; both of them are still printing (expected). Now, let go of Z. "Ctrl Z" is still printing... ???

The only way to stop it is by pressing Ctrl Z again. This does not happen in current master.

[41526-MRP.zip](https://github.com/godotengine/godot/files/5841642/41526-MRP.zip)

This is tangentially related to #44355... it is trying to solve a different issue though, and does not solve that one.

2023-02-11 19:51 UTC, akien-mga commented
Closing as this was found to cause issues and was not updated further.

I checked and the linked issue is still valid in 4.0 RC 1 though, so that might be something to look into for a future release.

2023-02-11 19:51 UTC, closed without merging