Edit vector/rect properties in a "linked" manner when holding down Ctrl
godotengine/godot pull request #41555
Opened 2020-08-27 01:38 UTC by Calinou

For Rect2, Rect2i and AABB, this only applies to the size,
not the position.

This closes https://github.com/godotengine/godot-proposals/issues/144.

2020-08-27 05:25 UTC, nathanfranke requested changes

2020-08-27 05:25 UTC, nathanfranke commented on editor/editor_properties.cpp
> +		if (p_name == "x") {
`_value_changed` has a `val` parameter. Use that instead of whatever this is.

2020-08-27 05:27 UTC, nathanfranke commented
I think that a link button would make more sense. I did a bit of work in my [fork](https://github.com/nathanfranke/godot/commit/d10fdeaa26a52a42f874fbafb45606c8c16075e3)

2020-08-27 05:38 UTC, nathanfranke requested changes
Added the lines to change and suggestions (Thanks @aaronfranke)

2020-08-27 05:38 UTC, nathanfranke commented on editor/editor_properties.cpp
> +		}
```suggestion
		v3 = Vector3(val, val, val);
```

2020-08-27 05:38 UTC, nathanfranke commented on editor/editor_properties.cpp
> +		}
Same with above

2021-02-27 17:15 UTC, aaronfranke commented
@Calinou What's the status of this PR? Do you plan to continue working on this? There are requested changes above that need to be addressed.

2022-06-14 14:19 UTC, akien-mga commented
Superseded by #59125.

2022-06-14 14:19 UTC, closed without merging