Expose OS::get_*_path functions
godotengine/godot pull request #41591
Opened 2020-08-29 02:01 UTC by Rubonnek

As I was working on issue #40584 I noticed these `OS::get_*_path` functions were not exposed to `GDScript`.

It took me a while to figure out that Godot was using a caching mechanism and I stumbled upon these functions after I did so. I think it would be great to have these functions exposed just to let users know where things are in case another issue like the one aforementioned pops up.

It will also be handy for users who want to use `add_tool_menu_item` to open their shells on these folders as they work on multiple projects.

2021-03-20 23:15 UTC, Calinou requested changes, later dismissed
Looks good to me. Make sure to apply suggestions for the documentation then squash the commits together.

2021-03-20 23:15 UTC, Calinou commented on doc/classes/OS.xml
> +				Returns the path to where the Godot templates and the application user data is stored per project.
```suggestion
				Returns the path to where the Godot templates and the application user data is stored per project. See [url=https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html]File paths in Godot projects[/url] for information on the default paths.
```

2021-03-20 23:15 UTC, Calinou commented on doc/classes/OS.xml
> +				Returns the path where the configuration for Godot is stored and possibly other applications.
```suggestion
				Returns the path where the configuration for Godot is stored and possibly other applications. See [url=https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html]File paths in Godot projects[/url] for information on the default paths.
```

2021-03-20 23:15 UTC, Calinou commented on doc/classes/OS.xml
> +				Returns the path to where the cache is stored per project.
```suggestion
				Returns the path to where the cache is stored per project. See [url=https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html]File paths in Godot projects[/url] for information on the default paths.
```

2021-03-21 05:08 UTC, Rubonnek commented
Done

2021-06-20 14:25 UTC, Rubonnek commented
Superseeded by  #48544. Closing.

2021-06-20 14:25 UTC, closed without merging