Documentation: specify how WindowDialog's default title bar is made
godotengine/godot pull request #41615
Opened 2020-08-30 05:56 UTC by hhsdev

Fixes #40828

2020-08-30 15:50 UTC, NathanLovato requested changes
Thanks for your contribution, I left you a suggestion.

2020-08-30 15:50 UTC, NathanLovato commented on doc/classes/WindowDialog.xml
> +      The style for both the content background of the [WindowDialog] and the title bar. The title bar is created with a top border and an expand margin of [code]panel[/code].
Here's a suggestion I feel makes the description read a little more clearly in plain English. Also, it restores the tabs for indentation, that were changed into spaces.

```suggestion
			The style for both the content background of the [WindowDialog] and the title bar. The title bar is created with a top border and an expand margin using the [code]panel[/code] stylebox.
```

2020-08-31 05:33 UTC, NathanLovato approved these changes

2020-08-31 09:14 UTC, akien-mga commented
Could you squash the two commits into one? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).

2020-08-31 10:57 UTC, merged

2020-08-31 10:57 UTC, akien-mga commented
Thanks!