Fix PopupMenu unresponsive on right side of menu
godotengine/godot pull request #41689
Opened 2020-09-01 21:27 UTC by nathanfranke

![2020-09-01 16-20-53 mp4](https://user-images.githubusercontent.com/14253836/91907772-102b8000-ec70-11ea-8c32-042ceef25f6e.gif)

2020-09-01 21:33 UTC, akien-mga commented
CC @EricEzaM

2020-09-01 22:25 UTC, EricEzaM commented
Hi @nathanfranke, @akien-mga.

Unfortunately I cannot reproduce the issue on my PR... not sure what is going on - maybe it is a platform specific issue? Anyway, this PR breaks what this piece of code tries to solve - not selecting items when trying to select the scrollbar. See below video of my test.
![scrollbar_selects](https://user-images.githubusercontent.com/41730826/91911888-5a0a7980-ecf5-11ea-93f6-f1ab5c59a718.gif)

So, the reason this code is required is because of the below situation. The scroll container just renders the scrollbar above the content.
![popup-menu-diagram](https://user-images.githubusercontent.com/41730826/91912153-e2891a00-ecf5-11ea-8065-d9ba04bb2f1f.png)

2020-09-01 22:34 UTC, EricEzaM requested changes
These changes do simplify the code quite a bit, thanks for that! I have suggested 2 options below - either work on my system. A good way to test the scrollbar is by going to the below button and changing the file dialog filter, since it has so many options.

![image](https://user-images.githubusercontent.com/41730826/91912707-19abfb00-ecf7-11ea-8960-7f269d904b77.png)

2020-09-01 22:34 UTC, EricEzaM commented on scene/gui/popup_menu.cpp
> +	Rect2 item_clickable_area = get_visible_rect();
Option a) change `get_visible_rect()` to `scroll_container->get_rect()`. The size of the scroll container will account for the offset of the margin container, while `get_visible_rect()` gets the rect of the entire popup.

2020-09-01 22:34 UTC, EricEzaM commented on scene/gui/popup_menu.cpp
> +		item_clickable_area.size.width -= scroll_container->get_v_scrollbar()->get_size().width;
Option b) also subtract get_theme_stylebox("panel").size.x to account for the width of the right hand side margin.

2020-09-02 06:25 UTC, nathanfranke commented
I chose option "A" since it seemed more elegant :smile:

2020-09-02 08:00 UTC, EricEzaM commented
All good on my end after a test, thanks!

2020-09-04 11:53 UTC, akien-mga commented
Also fixes #41762.

2020-09-04 11:53 UTC, merged

2020-09-04 11:53 UTC, akien-mga commented
Thanks!