Mention Viewport.render_target_clear_mode property is intended for 2D usage
godotengine/godot pull request #41713
Opened 2020-09-02 17:45 UTC by Yetizone

Targeting 3.2 since it seems this property has moved to the `SubViewport` class in master.
Making a separate PR for master now.

In response to https://github.com/godotengine/godot/issues/33831

2020-09-02 18:11 UTC, NathanLovato requested changes
Changing the formatting for consistency with the rest of the class ref.

2020-09-02 18:11 UTC, NathanLovato commented on doc/classes/Viewport.xml
> +			The clear mode when viewport used as a render target. Note this property is intended for 2D usage.
```suggestion
			The clear mode when viewport used as a render target.
			[b]Note:[/b] this property is intended for 2D usage.
```

2020-09-02 18:53 UTC, Yetizone commented on doc/classes/Viewport.xml
> +			The clear mode when viewport used as a render target. Note this property is intended for 2D usage.
Done. Thanks for the help !

2020-09-02 19:45 UTC, NathanLovato approved these changes

2020-09-02 19:50 UTC, akien-mga commented on doc/classes/Viewport.xml
> +			[b]Note:[/b] this property is intended for 2D usage.
Actually this should be:
```suggestion
			[b]Note:[/b] This property is intended for 2D usage.
```

2020-09-03 05:00 UTC, Yetizone commented on doc/classes/Viewport.xml
> +			[b]Note:[/b] this property is intended for 2D usage.
Done !

2020-09-03 05:35 UTC, merged

2020-09-03 05:35 UTC, akien-mga commented
Thanks!