Improve documentation related to Array error handling
godotengine/godot pull request #41812
Opened 2020-09-06 13:21 UTC by Calinou

This closes https://github.com/godotengine/godot-docs/issues/3834.

2020-09-08 23:18 UTC, NathanLovato requested changes
Some small changes to the docs to hopefully improve clarity a bit. I mostly made suggestions to remove the parentheses, following the docs writing guidelines, but I feel a change in wording can make some sentences a bit more explicit.

2020-09-08 23:18 UTC, NathanLovato commented on doc/classes/Array.xml
> +				Removes and returns the first element of the array. Returns [code]null[/code] if the array is empty (without printing an error message).
```suggestion
				Removes and returns the first element of the array. Returns [code]null[/code] if the array is empty, without printing an error message.
```

2020-09-08 23:18 UTC, NathanLovato commented on doc/classes/Array.xml
> +				Removes an element from the array by index. Does nothing if the index does not exist in the given array.
```suggestion
				Removes an element from the array by index. If the index does not exist in the array, nothing happens.
```

2020-09-08 23:18 UTC, NathanLovato commented on doc/classes/Array.xml
> +				Removes and returns the last element of the array. Returns [code]null[/code] if the array is empty (without printing an error message).
```suggestion
				Removes and returns the last element of the array. Returns [code]null[/code] if the array is empty, without printing an error message.
```

2020-09-08 23:18 UTC, NathanLovato commented on doc/classes/Array.xml
> +				[b]Note:[/b] This is not the same as [code]array[-1][/code], as accessing by index will pause project execution when running from the editor if the array is empty.
```suggestion
				[b]Note:[/b] Calling this function is not the same as writing [code]array[-1][/code]. If the array is empty, accessing by index will pause project execution when running from the editor.
```

2020-09-08 23:18 UTC, NathanLovato commented on doc/classes/Array.xml
> +				[b]Note:[/b] This is not the same as [code]array[0][/code], as accessing by index will pause project execution when running from the editor if the array is empty.
```suggestion
				[b]Note:[/b] Calling this function is not the same as writing [code]array[0][/code]. If the array is empty, accessing by index will pause project execution when running from the editor.
```

2020-09-09 13:00 UTC, NathanLovato approved these changes

2020-09-09 13:24 UTC, merged

2020-09-09 13:24 UTC, akien-mga commented
Thanks!

2020-09-10 10:04 UTC, akien-mga commented
Cherry-picked for 3.2.3.