Fix C# string.IsAbsPath()
godotengine/godot pull request #42259
Opened 2020-09-23 05:15 UTC by zaevi

fix #42250

2020-09-23 05:51 UTC, aaronfranke requested changes
This code should be changed to match the C++ implementation: https://github.com/godotengine/godot/blob/master/core/ustring.cpp#L3670

2020-09-23 05:51 UTC, aaronfranke commented on modules/mono/glue/GodotSharp/GodotSharp/Core/StringExtensions.cs
> +            if(string.IsNullOrEmpty(instance))
Formatting is wrong, `if(` should be `if (`.

2020-09-23 15:29 UTC, neikeq approved these changes

2020-09-23 16:12 UTC, merged

2020-09-23 16:12 UTC, akien-mga commented
Thanks!

2020-09-24 10:22 UTC, akien-mga commented
Cherry-picked for 3.2.4.