Fix documentation for Camera's Current member
godotengine/godot pull request #42325
Opened 2020-09-25 03:29 UTC by zak-grumbles

Behavior of the camera's `current` member wasn't fully documented for situations with more than one camera in a scene. Added some more info to clear that up.

Resolves #42221

2020-09-25 16:13 UTC, zak-grumbles commented
Resolved the formatting issue in my initial commit

2020-10-03 20:54 UTC, zak-grumbles commented
It looks like the issue this PR addresses has been closed. Is this PR still needed?

2020-10-03 20:56 UTC, akien-mga commented
It was not closed but moved: https://github.com/godotengine/godot-docs/issues/4080

The PR is still relevant :)

2021-02-25 16:38 UTC, akien-mga commented
Force pushed an amend to improve the formatting a bit.

2021-03-19 23:46 UTC, Calinou requested changes, later dismissed
Should be good to merge after applying the suggestion and [squashing the commits](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html).

2021-03-19 23:46 UTC, Calinou commented on doc/classes/Camera3D.xml
> +			If multiple cameras are in the scene, one will always be made current. E.g. if two are present and only one is current, setting it to [code]false[/code] will cause the other to be made current.
```suggestion
			If multiple cameras are in the scene, one will always be made current. For example, if two [Camera3D] nodes are present in the scene and only one is current, setting one camera's [member current] to [code]false[/code] will cause the other camera to be made current.
```

2022-07-17 09:30 UTC, akien-mga approved these changes

2022-07-17 11:42 UTC, merged

2022-07-17 11:42 UTC, akien-mga commented
Thanks!

2022-07-25 09:44 UTC, akien-mga commented
Cherry-picked for 3.5.