[WIP]Android click support 3.2
godotengine/godot pull request #42360
Opened 2020-09-27 03:13 UTC by thebestnom

Version of https://github.com/godotengine/godot/pull/37158 for 3.2.

2020-09-29 17:16 UTC, m4gr3d commented
@thebestnom Can you resolve this branch's conflicts with the `3.2` branch.

2020-09-29 17:18 UTC, thebestnom commented
Of course, when I'll be around a computer

2020-10-09 14:03 UTC, thebestnom commented
Ok, ready, Ill add the key modifier later

2020-10-26 21:06 UTC, thebestnom commented
Anything else?

2020-10-28 15:41 UTC, m4gr3d approved these changes

2020-10-28 15:44 UTC, m4gr3d commented
cc @pouleyKetchoupp for review.
@akien-mga Can this PR (and [the master version](https://github.com/godotengine/godot/pull/37158)) be included in the next beta for 3.2.4. It's critical for some of the upcoming editor porting work.

2020-10-28 15:48 UTC, pouleyKetchoupp commented
Ok, I'll try to test & review tomorrow.

2020-10-28 15:57 UTC, thebestnom commented
Ill just remind here that there is keyboard support fixes to cherrypick, and I would also like to add pointer capture 
before the beta (also remember when testing that a lot of devices roms doesn't support right and middle click and I couldn't find a rom that support 4 and 5 buttons as is)

2020-10-28 16:01 UTC, m4gr3d commented
@pouleyKetchoupp Thanks!

@thebestnom Do you have a PR for the keyboard support fixes to cherrypick?

2020-10-28 16:02 UTC, thebestnom commented
Ill add that once this PR is merged, as it adds keyboard modifier support and the mouse input needs that to be added

2020-10-29 07:19 UTC, pouleyKetchoupp requested changes

2020-10-29 07:19 UTC, pouleyKetchoupp commented on platform/android/os_android.h
> +	virtual Point2i mouse_get_position() const;
On 3.2 branch, the methods to override are `OS::get_mouse_position` (type `Point2` instead of `Point2i`) & `OS::get_mouse_button_state`

2020-10-29 07:43 UTC, pouleyKetchoupp commented
Looks good apart from the method override I commented. Didn't spot anything wrong while testing.

2020-10-30 13:24 UTC, thebestnom commented
Fixed 👍

2020-10-30 14:06 UTC, pouleyKetchoupp approved these changes

2020-10-30 14:38 UTC, akien-mga approved these changes

2020-10-30 14:38 UTC, merged

2020-10-30 14:39 UTC, akien-mga commented
Thanks a ton for your work on this feature, and thanks @m4gr3d and @pouleyKetchoupp for the in-depth reviews and testing! Great team work here :)