Fix editing items in tree making changes to the wrong item
godotengine/godot pull request #42423
Opened 2020-09-30 03:11 UTC by EricEzaM

This was caused by the fact that selecting a new item would immediately change that item to the "popup_edited_item" which meant that when the `item_edited` method was called, the wrong item was being changed. "popup_edited_item" would change immediately upon selection because bring_up_editor was based on it's current selection status, which could have changed to true just before, in the same method, where selection is handled (see line 1758). This change makes it based upon it's _previous_ selection status (which was already used) so that the editor does not popup immediately on first selection.

This was a pretty big pain to troubleshoot tbh. Tree could do with a refactor... It is quite messy and hard to decipher.

Closes #42419
![tree_fixed](https://user-images.githubusercontent.com/41730826/94638946-5e3eac80-031e-11eb-98f3-edf45a599afb.gif)

2020-09-30 07:10 UTC, akien-mga commented
Bug #42419 sounds like a regression (otherwise I doubt it would have gone unnoticed so long if it's in 3.x too), so it would be good to figure out what caused the regression before attempting a fix.

This line hasn't been modified since 2017 (cbcf40bd316), so if there's a regression it's triggered by another part of the code.

2020-09-30 07:33 UTC, EricEzaM commented
Yeah it is a regression and only occurs in 4.0, cant repro in 3.X.

I had a look at the commit history of tree.cpp and couldn't see anything that would affect it... Bit I guess bisecting would be the best option.

2020-09-30 12:43 UTC, EricEzaM commented
After a long night of bisecting... it appears b3080bc2f4d7bc5c15b3a0ff7b67690c4677577e is the first bad commit.

Confirmed after testing it and the previous commit, 09ba290364aaa5b54528e82144ec0a40e10b497b, which does not exhibit the issue. I'll have to look into this tomorrow.

2020-09-30 12:45 UTC, akien-mga commented
Ouch, sorry I sent you on a chase after such an old mid-refactoring commit. I thought the regression might have been newer than that.

2020-09-30 12:51 UTC, EricEzaM commented
All good, I'm generally on a goose chase of a few bugs and fixes while working on #42351 and https://github.com/godotengine/godot-proposals/issues/1532

All part of the fun haha :)

2020-10-01 00:16 UTC, EricEzaM commented
@akien-mga After a quick review, I think this still might be the correct solution?

See in the below gif, which is before this fix, when you click on another item it starts editing it immediately? I dont think this is the correct behaviour. It is also what causes the bug attached to this PR.

![tree_editing_broken](https://user-images.githubusercontent.com/41730826/94632197-575b6e00-030d-11eb-9655-be9bbffdd90b.gif)

When you click on an item it should stop editing the previous item but not start editing the one you clicked on:

![tree_fixed](https://user-images.githubusercontent.com/41730826/94638946-5e3eac80-031e-11eb-98f3-edf45a599afb.gif)

It's like on Windows if you are renaming a file, if you then click on another file it does not start immediately editing the one you clicked on.

Additionally the behaviour which occurs before this fix means that if, in response to the `item_edited` signal, you call `tree->get_edited()`, you will get the item you clicked on, as opposed to the one you actually edited.

2021-02-25 16:45 UTC, akien-mga commented
If you can confirm that this should still be the correct fix, we can likely merge as is @EricEzaM, unless someone else in @godotengine/gui-nodes has a strong opinion about this.

2021-06-01 17:08 UTC, Paulb23 requested changes
This seems to be already working as intended, tested this in Godot v3.3.2 and it works the same as 4.0. 

The editor should only appear on first click when `allow_reselect ` is false, setting it to true produces the behaviour seen here. 

Might be worth changing the default value from false to true?

2021-08-24 15:38 UTC, KoBeWi commented
> Might be worth changing the default value from false to true?

Wouldn't it basically mean that using non-default value would result in broken behavior? Changing default isn't enough to fix the issue.

2021-08-28 12:27 UTC, Paulb23 commented
> Wouldn't it basically mean that using non-default value would result in broken behavior?

As far as I know it is working as intended, with this PR `allow_reselect` no longer does anything. If the user expectations is what we see here, changing the default makes the current behaviour opt-in which should reduce confusion.

2021-08-28 12:32 UTC, KoBeWi commented
How is the behavior from the GIFs intended? Selecting an item will overwrite its value with the value of the previously selected one. This is definitely a bug.

Still, if the fix breaks something else, it's not correct.

2021-08-28 12:39 UTC, Paulb23 commented
Ahh, no idea how I missed that yeah that not indented.

2022-10-03 00:28 UTC, EricEzaM commented
Can't repro issue any more

2022-10-03 00:28 UTC, closed without merging