Re-add the track editor toggle button to Animation dock
godotengine/godot pull request #42605
Opened 2020-10-06 19:33 UTC by williamd1k0

This PR is a "cherry-pick" from the Godot v1 branch *(this is not a joke :sweat_smile:).*

Godot 1 used to have an "edit" button in the Animation Dock, because the default mode was "play mode". This feature was removed when Juan refactored the entire Animation Dock for Godot 2.0.
>Btw I found out about it a few years ago, when I tried Godot 1 just for fun/curiosity.

- Play mode
![image](https://user-images.githubusercontent.com/10428035/95243505-1d93d700-07e7-11eb-9eb3-621bfa6c52ac.png)
- Edit mode
![image](https://user-images.githubusercontent.com/10428035/95243557-30a6a700-07e7-11eb-8cca-3ed8b9abfb59.png)

I'm not good with C++, so I tried to implement it recently as a study, more specifically during this year's GGJ (Godot master branch was still v3.2). I didn't open a PR before because this year is being insanely busy for me.

So, I'm taking advantage of the hacktoberfest opportunity to re-implement (again) and open a PR before I forget it forever :P 

My implementation is a bit different from the original, it's just a simple toggle for the track editor, and the "edit" mode is still the default.

- Edit mode
![image](https://user-images.githubusercontent.com/10428035/95247008-b2003880-07eb-11eb-938f-2aaceb0f1264.png)
- Play mode
![image](https://user-images.githubusercontent.com/10428035/95247111-d4925180-07eb-11eb-9ebb-549b411d1d2f.png)

- Video:
![vokoscreenNG-2020-10-06_14-42-55](https://user-images.githubusercontent.com/10428035/95250371-67cd8600-07f0-11eb-8406-c846a7ea63a7.gif)

Sorry for not opening a GIP in advance, but as it is already implemented, I find it easier to discuss the implementation in this PR.
I implemented it because I found it useful, I always get upset when I just want to play animations, but the Animation Dock takes up almost half of my screen.

2020-10-06 22:11 UTC, aaronfranke requested changes, later dismissed

2020-10-06 22:11 UTC, aaronfranke commented on editor/plugins/animation_player_editor_plugin.cpp
> +	else
Braces are now required.

2020-10-06 23:59 UTC, williamd1k0 commented on editor/plugins/animation_player_editor_plugin.cpp
> +	else
Fixed!

2022-08-02 12:44 UTC, akien-mga commented
I think this still requires a proper proposal so we can assess if there's a real need for reintroducing this. As you mentioned, you cherry-picked this for Godot 1.0 and since 2.0 nobody ever complained about the lack of this feature. So while the implementation seems simple, if we don't have a significant number of users who would use it, it would just be bloating the UI.

2024-08-23 18:03 UTC, aaronfranke commented
It's been a few years with no activity, so I'm closing this. This PR requires a [proposal](https://github.com/godotengine/godot-proposals/) before it can be considered.

2024-08-23 18:03 UTC, closed without merging