Update ProjectSettings.xml
godotengine/godot pull request #42632
Opened 2020-10-08 07:23 UTC by merriam

typo.  Sorry, it bugged me.

2020-10-08 12:07 UTC, Calinou commented
Please amend the commit message to something more meaningful such as "Fix typo in the ProjectSettings class documentation".

2020-10-09 06:24 UTC, aaronfranke requested changes

2020-10-09 06:24 UTC, aaronfranke commented on doc/classes/ProjectSettings.xml
> +			Search path for project-specific script templates. Script templates will be searched both in the editor-specific path and in this project-specific path.
This reads weirdly, we may as well improve this sentence by using the active voice.

```suggestion
			Search path for project-specific script templates. Godot will search for script templates both in the editor-specific path and in this project-specific path.
```

2020-10-10 05:00 UTC, aaronfranke approved these changes
A [squash](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html) would be nice, but the changes look good.

2020-10-13 07:56 UTC, akien-mga commented
Force pushed an update with the commits squashed and a meaningful commit message as requested.

2020-10-13 08:30 UTC, merged

2020-10-13 08:30 UTC, akien-mga commented
Thanks!

2020-10-19 13:29 UTC, akien-mga commented
Cherry-picked for 3.2.4.