updating description
godotengine/godot pull request #42696
Opened 2020-10-10 16:38 UTC by arthurpaulino

From Discord, `#documentation` channel:

@arthurpaulino
Hey I just had some problems with is_on_floor() from KinematicBody2D. On the docs it says:
> Returns true if the body is on the floor. Only updates when calling move_and_slide().

I had a body that was on the floor but it hadn't collided on that exact frame, so is_on_floor() was returning false and causing some unexpected behavior on my code. Fortunately @zacryol helped me figure out the real meaning of what is_on_floor() returns. I think it would be better phrased as:
> Returns true if the body has collided with the floor on the last call of move_and_slide() and false otherwise.

Do you guys think it makes sense?

@NathanLovato 
It's been a common source of confusion. The change seems good to me, some minor tweak to better fit the writing guidelines and using the docs' bbcode:
> Returns [code]true[/code] if the body collided with the floor on the last call of [member move_and_slide]. Otherwise, returns [code]false[/code].

2020-10-10 16:55 UTC, NathanLovato approved these changes

2020-10-10 18:06 UTC, NathanLovato commented
Could you squash your commits? You need only 1 commit for maintainers to merge your PR.

2020-10-10 18:33 UTC, arthurpaulino commented
> Could you squash your commits? You need only 1 commit for maintainers to merge your PR.

Can it be done with the merge button using the option "squash and merge"? I don't think I can squash commits after the PR is open and before it's merged.

2020-10-10 19:11 UTC, aaronfranke commented
You can squash them and then force push. See [this](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) article for more information.

GitHub does have a "Squash and merge" button, but it destroys history, so it's better if the PR author does it.

2020-10-10 19:34 UTC, arthurpaulino commented
> You can squash them and then force push. See [this](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) article for more information.
> 
> GitHub does have a "Squash and merge" button, but it destroys history, so it's better if the PR author does it.

Oh yeah, I got it thanks!
The squash was pushed.

2020-10-12 15:58 UTC, madmiraal requested changes
The 3D version needs to be updated the same way too.

2020-10-12 15:58 UTC, madmiraal commented on doc/classes/KinematicBody2D.xml
>  			</description>
You've changed "**a** wall" to "**the** wall". Technically, there is a left wall and a right wall.

2020-10-12 23:25 UTC, arthurpaulino commented
@madmiraal Changes done :tada:

2020-10-13 00:37 UTC, NathanLovato approved these changes

2020-10-13 05:08 UTC, madmiraal approved these changes

2020-10-13 06:53 UTC, merged

2020-10-13 06:54 UTC, akien-mga commented
Thanks!

For future commits, please try to use a more descriptive commit message, e.g. the same as this PR's title would have been great.

In the `git log`, you can easily spot what change is not clear about what it's doing :)
```
[akien@cauldron godot.git (master)]$ git log --pretty=oneline --no-merges
cac4fedb2a15699979e062ffa64311249695e7f9 Respect Tree.set_icon_max_width size for drawing selection box
0c9a1a1cd4c5ebfbabe5b04e81a5ddb24b3dcb06 updating descriptions
aadc8d54a47cba2ec8c5fd40875fa77ef3d89974 Bind missing constant in VisualScriptPropertyGet
84a1817a75baf9f9c5e51a9aa42549203c50a615 Fixes leaks with shader and material
d22791c271aceeade16970bffd8e8a3a146de339 doc: Sync classref with current source
1d3aec4230c1de1a00de1b2e1b7500aa82e309d7 Free a SortShader and a ParticlesCopyShader
f98acd5cfb455d7402cd7e263251a8df41746782 Ensure grid index is valid before trying to change value.
f4eef287f927e6286516484fbb0be52a2c044131 Adds Metallic to spatial light input of visual shaders
8226cee8d875af8e89cfc79fd94cb430203867b4 Fixes HTTPClient::poll crash after connection is self-assigned
351a122029fea57f431672965d623f34262d6e11 Add ability to bind an unbind arguments to Callable.
26f5bd245c535fec5bfdd51a0f939d0a51179d85 Implement GPU Particle Collisions
```

2021-04-22 15:03 UTC, kleonc commented
@akien-mga Cherry-pick for `3.x`?

2021-04-23 19:51 UTC, akien-mga commented
Cherry-picked for 3.4.

2021-04-23 20:03 UTC, akien-mga commented
Cherry-picked for 3.3.1.