ScriptEditor: Fix line number gutter drag select
godotengine/godot pull request #42723
Opened 2020-10-11 17:49 UTC by Devination

Exposes TextEdit's selection as a protected variable so that CodeEdit can correctly set the selected lines when dragging on the line number gutter.

Fixes issue #42722
Also addresses https://github.com/godotengine/godot-proposals/issues/1247

2020-10-12 16:58 UTC, Paulb23 requested changes
As you mentioned in the issue, the selection shouldn't really be exposed.`TextEdit` should have a API for this. I'm sure there's was a separate issue about this somewhere, but I can't seem to find it.

2020-10-13 05:17 UTC, Devination commented
Just to be clear: you're thinking of dedicated public functions for set_selecting_line/column? That would match up nicely with the existing cursor_set_line/column functions.

2020-10-16 20:16 UTC, Devination commented
I pushed updates using the --amend method as suggested in the documentation. In this update, I exposed the `Selection` struct for use with the new `set_selection_mode` function but kept TextEdit's `selection` variable private.

2020-10-19 17:15 UTC, Paulb23 requested changes
Overall looks good, left a couple small notes inline, would also add bindings to GDScript.

2020-10-19 17:15 UTC, Paulb23 commented on scene/gui/text_edit.h
> +	void set_selection_line(int p_line) { selection.selecting_line = p_line; };
I can't see a use case for wanting to set `selection_line` or `selection_column` separately, without the mode, as `TextEdit` also changes these values, so would suggest removing these setters?

2020-10-19 17:15 UTC, Paulb23 commented on scene/gui/text_edit.h
> +		enum Mode {
Might be worth moving this out so we don't have to expose the entire struct, renaming it to `SelectionMode`

2020-10-19 17:15 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +	if (p_line >= 0) {
Should check it's not greater then the text size with `ERR_FAIL_INDEX(p_line, text.size());`

2020-10-19 17:15 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +	if (p_column >= 0) {
Same here should check it's not longer then `selection.selecting_line.length()`

2020-10-19 17:15 UTC, Paulb23 commented on scene/gui/text_edit.h
> +	Selection::Mode get_selection_mode() { return selection.selecting_mode; };
Need `const` on the getters. eg `Selection::Mode get_selection_mode() const;` Would also move them to the cpp file rather then keeping them here in the header.

2020-10-25 17:26 UTC, Devination commented
Thank you for your suggestions, I updated the code based on them. Sorry for the slow turnaround time, I wasn't able to work on this until the weekend.

2020-10-25 18:11 UTC, Paulb23 reviewed
No worries, one more small issue to fix then it should be good to approve.

2020-10-25 18:11 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +	ClassDB::bind_method(D_METHOD("set_selection_mode", "mode", "line", "column"), &TextEdit::set_selection_mode, DEFVAL(0), DEFVAL(-1), DEFVAL(-1));
```suggestion
	ClassDB::bind_method(D_METHOD("set_selection_mode", "mode", "line", "column"), &TextEdit::set_selection_mode, DEFVAL(-1), DEFVAL(-1));
```

`DEFVAL(0)` should be safe to remove.

2020-10-25 19:52 UTC, Paulb23 approved these changes
Thanks for the contribution, LGTM!

2020-10-26 07:13 UTC, merged

2020-10-26 07:13 UTC, akien-mga commented
Thanks!