Add FileSystem search results limit to Editor Settings
godotengine/godot pull request #42745
Opened 2020-10-12 16:21 UTC by Listwon

FileSystem search results limit is hardcoded to 128 (at least in split view), which is too low. I moved this to Editor Settings with saner default value. I know it's not accurate because of recursive nature of _search(), but it solved my problem with e.g. selecting multiple small images to reimport them as TextureAtlas.

![filesystem](https://user-images.githubusercontent.com/1554127/95768105-158bd980-0cb6-11eb-9ae1-f5ed8f6053f0.jpg)

[MultipleImages.zip](https://github.com/godotengine/godot/files/5366210/MultipleImages.zip)

2020-10-12 16:26 UTC, groud commented
Do we really need a limit there ? Also, if you make it 32k by default it is like having no limit at all in fact.

2020-10-12 17:04 UTC, Listwon commented
Ok, I completely removed the limit :) Works as I wanted.

2021-03-20 02:11 UTC, Calinou requested changes
I'd keep a very high hardcoded limit such as `10000` just in case. We never know how many files the user may have in the project (infinitely recursing symlinks?). Having the editor cause an infinite loop is poor user experience and may result in loss of data if the user didn't save what they were working on.

2021-03-22 14:42 UTC, Calinou requested changes

2021-03-22 14:42 UTC, Calinou commented on editor/filesystem_dock.cpp
>  			// Display the search results.
```suggestion
			// Display the search results.
			// Limit the number of results displayed to avoid an infinite loop.
```

2021-03-22 18:24 UTC, Calinou approved these changes

2021-07-06 11:37 UTC, akien-mga approved these changes

2021-07-06 11:37 UTC, merged

2021-07-06 11:37 UTC, akien-mga commented
Thanks!

2021-07-06 11:38 UTC, akien-mga commented
Cherry-picked for 3.4.