Enhance editor file dialog
godotengine/godot pull request #42779
Opened 2020-10-13 18:34 UTC by volzhs

1. show valid directory path when opening editor file dialog
2. keep file name when changing path by entering path
3. add first extension in filter automatically if not given
4. remove directory in recent list if it's not valid anymore

Fix #22509

![editor_file_dialog](https://user-images.githubusercontent.com/8281454/95901293-16179380-0dce-11eb-8660-8aaf5377e813.gif)

2021-01-01 17:09 UTC, volzhs commented
@Calinou @groud would you take a look? :smile:

2021-01-01 20:51 UTC, Calinou requested changes
Some comment style fixes, but the rest looks good to me :slightly_smiling_face:

2021-01-01 20:51 UTC, Calinou commented on editor/editor_file_dialog.cpp
> +	// check non-existance path
```suggestion
	// Check if the current path doesn't exist and correct it.
```

2021-01-01 20:51 UTC, Calinou commented on editor/editor_file_dialog.cpp
> +				// Remove invalid directory from Recent
```suggestion
				// Remove invalid directory from the list of Recent directories.
```

2021-01-01 20:51 UTC, Calinou commented on editor/editor_file_dialog.cpp
> +		// add first extension of filter if no valid extension found.
```suggestion
		// Add first extension of filter if no valid extension is found.
```

2021-01-02 08:58 UTC, volzhs commented
It's done. :smile:

2021-01-02 16:25 UTC, Calinou approved these changes

2021-01-02 18:58 UTC, groud approved these changes

2021-01-02 19:36 UTC, volzhs commented
@Calinou @groud Thanks for your review. :+1:

2021-01-03 12:37 UTC, merged

2021-01-03 12:37 UTC, akien-mga commented
Thanks!

2021-01-05 11:16 UTC, akien-mga commented
Cherry-picked for 3.2.4.