Keep 'Editor Description' metadata when changing a Node's type
godotengine/godot pull request #42878
Opened 2020-10-18 04:13 UTC by gvaneyck

Fixes #42871 
Can be cherry-picked

2020-10-18 11:27 UTC, KoBeWi requested changes
```
if (Object::cast_to<CanvasItem>(newnode)) {
```
^ the `_editor_description_` should be moved outside this condition, otherwise non-CanvasItem nodes will still lose the description.

But I also noticed that the condition doesn't include 3D nodes, which also had `_edit_group_` and `_edit_lock_` added. I could open a new issue, but while you are changing this part, it could be done in the same PR. The condition should look like this:
```
if (Object::cast_to<CanvasItem>(newnode) || Object::cast_to<Node3D>(newnode)) {
```

2020-10-18 18:24 UTC, gvaneyck commented
Updated per your comments.

Editor Description will always be copied since all Node types can have it.
Edit Group/Lock will now be copied for Node3Ds.

2020-10-18 18:29 UTC, KoBeWi approved these changes

2020-10-19 06:30 UTC, akien-mga approved these changes

2020-10-19 06:30 UTC, merged

2020-10-19 06:31 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2020-10-19 13:42 UTC, akien-mga commented
Cherry-picked for 3.2.4.