Document more NavigationMesh properties
godotengine/godot pull request #42974
Opened 2020-10-21 19:51 UTC by skyace65

Adds a description for Agent Height, Agent Radius and Cell Height.

2021-03-20 00:52 UTC, Calinou requested changes, later dismissed
Should be good to merge after applying the suggestion.

2021-03-20 00:52 UTC, Calinou commented on doc/classes/NavigationMesh.xml
> +			Determines where the edge of a navigation mesh is so an agent will not overlap with another mesh, or stand over nothing.
```suggestion
			Determines where the edge of a navigation mesh is. This way, an agent will not overlap with another mesh or stand over nothing.
```

2021-03-20 02:05 UTC, skyace65 commented
Fixed

2021-03-23 12:23 UTC, akien-mga approved these changes

2021-03-23 12:24 UTC, merged

2021-03-23 12:24 UTC, akien-mga commented
Thanks!