Make rect_clip_content clip input too by default
godotengine/godot pull request #43468
Opened 2020-11-12 00:14 UTC by KoBeWi

Closes #5172

This theoretically breaks compatibility, but I doubt anyone relied on this bug, so maybe it could be cherry-picked 🤔

2020-11-12 10:27 UTC, Zireael07 commented
Finally! I had to use a complex tree of nodes instead of just clipping due to this bug.

2020-11-27 15:52 UTC, reduz commented
This is not a bug, the problem is that clips_contents is for drawing, while the other is for clipping input. clips_contents should probably be called clip_to_size. It might be instead be possible to unify it, but you may want to clip input while not clipping drawing, so they are separate. To me its mostly a naming convention thing.

2020-11-27 16:04 UTC, KoBeWi commented
> you may want to clip input while not clipping drawing

This is still possible. Also the PR addresses opposite case. Clipping drawing without clipping input is rather rare thing to do.

2021-04-23 21:23 UTC, akien-mga requested changes
*Edit:* Welp clicked the wrong button by mistake, meant to approve...

2021-04-23 21:24 UTC, akien-mga approved these changes
Looks good to me. To clarify, it does not unify the two clipping options, it just makes input clipping follow content clipping **if not overridden**.

2021-04-23 22:03 UTC, akien-mga commented
One thing I wonder though is why this is implemented as a virtual method and not a property. I guess there are advanced use cases where one might want to conditionally clip input based on some internal logic?

Maybe there should be a property for clipping input, and if there's still a need for the virtual method, it could default to the value of that property, instead of clip contents?

Just food for thought, I'm fine with what is proposed in this PR for now until we know more about potential use cases for a different approach.

2021-04-26 13:56 UTC, groud commented
I think this makes sense, but I am not sure I understand why _clip_inputs needs to be exposed as a virtual function instead of a simple property. It could be made a property displayed next to the `rect_clip_content` one in the inspector no?

2021-04-26 14:04 UTC, akien-mga commented
Yeah see my analysis above - that's what #15358 was implementing but @reduz didn't think it worth a dedicated property:

> I don't think having this as a property is worth it, the use case is so
rare that having it exposed wont make much sense.

So the virtual method was implemented as alternative way to enable the use case. But that could be changed now if we agree that a property is indeed better suited.

2021-06-25 14:28 UTC, akien-mga commented
Superseded by #49908.

2021-06-25 14:28 UTC, closed without merging