Allow HTTPClient to talk to a proxy server
godotengine/godot pull request #43493
Opened 2020-11-13 08:28 UTC by timothyqiu

This PR makes it possible to talk to HTTP/HTTPS proxy server via `HTTPClient`, closes https://github.com/godotengine/godot-proposals/issues/1808

* Makes request uri accept absolute URL and authority
    * This is [allowed](https://tools.ietf.org/html/rfc2616#section-5.1.2) by http protocol, and [required](https://tools.ietf.org/html/rfc7231#section-4.3.6) by the `CONNECT` method
* Adds Host header only when missing
    * Before this PR, "Host" is determined by `connect_to_host` and there is no way to override it

These changes are actually bug fixes. But fixing these bugs makes it possible to talk to proxy servers.

With this PR, requests can be sent through HTTP/HTTPS proxies by setting up proxy manually:
[ProxyTest-3.2.zip](https://github.com/godotengine/godot/files/5535546/ProxyTest-3.2.zip) / [ProxyTest-4.0.zip](https://github.com/godotengine/godot/files/5535548/ProxyTest-4.0.zip)

Tested on the current master (f733746) and 3.2 branch (adf2dab).

2020-11-14 10:02 UTC, Faless requested changes
The work is good :+1: and addresses an issue that currently makes `CONNECT` unusable.
See my remarks on the `ERR_FAIL*` check.

2020-11-14 13:50 UTC, timothyqiu commented
OK. A `_check_request_url` method is added.

For `CONNECT`, I think it's kind of mentioned that it's authority is `host:port` in the RFC:

> i.e., the request-target consists of only the host name and port number of the tunnel destination, separated by a colon.

For the sake of simplicity, I only checks if a colon is in the middle of `p_url` :)

2020-11-16 14:59 UTC, Faless approved these changes
Looks good, great work :medal_sports:

2020-11-16 15:00 UTC, merged

2020-11-16 15:00 UTC, Faless commented
Thanks!

2020-11-17 10:55 UTC, akien-mga commented
Cherry-picked for 3.2.4.