Add option to exclude selected resources on export
godotengine/godot pull request #43550
Opened 2020-11-15 00:55 UTC by KoBeWi

Another part of https://github.com/godotengine/godot-proposals/issues/1454

2020-11-23 17:32 UTC, MCrafterzz commented
I don't know if its already a feature but how about an option to not export unused resources (3d models, textures etc)?

2020-11-23 18:57 UTC, KoBeWi commented
> I don't know if its already a feature but how about an option to not export unused resources (3d models, textures etc)?

Open a separate proposal for that. Also it's not easy to determine which resources are "used".

2021-03-20 01:53 UTC, Calinou requested changes

2021-03-20 01:53 UTC, Calinou commented on editor/project_export.cpp
> +	export_filter->add_item(TTR("Exclude selected resources"));
This description is quite long, but more explicit:

```suggestion
	export_filter->add_item(TTR("Export all resources in the project except resources checked below"));
```

2021-03-20 21:09 UTC, Calinou approved these changes

2021-03-23 11:42 UTC, akien-mga commented on editor/project_export.cpp
> +	export_filter->add_item(TTR("Export all resources in the project except resources checked below")));
Too many parentheses :)

2021-03-31 22:20 UTC, merged

2021-03-31 22:20 UTC, akien-mga commented
Thanks!