Proposal 1778 local transform rotation
godotengine/godot pull request #43601
Opened 2020-11-16 20:06 UTC by AlexanderPruss

Implements proposal 1778: https://github.com/godotengine/godot-proposals/issues/1788

Adds a new `rotated_local` function to `Transform`, usable in GDScript. This makes it more clear that the `Transform.rotated` function will change `Transform.origin`. 

I'm not 100% sure that `rotated_local` is the best name for the new function.

2020-11-16 20:28 UTC, Calinou requested changes

2020-11-16 20:28 UTC, Calinou commented on tests/test_math.h
> +	//Rotating should rotate both our basis and the origin.
We use a leading space for comments:

```suggestion
	// Start with the default orientation, but not centered on the origin.
	// Rotating should rotate both our basis and the origin.
```

2020-11-16 20:28 UTC, Calinou commented on tests/test_math.h
> +	//Rotating in-place should only rotate the basis, leaving the origin alone.
```suggestion
	// Start with the default orientation, but not centered on the origin.
	// Rotating in-place should only rotate the basis, leaving the origin alone.
```

2020-11-16 20:28 UTC, Calinou commented on tests/test_math.h
> +	//Make sure that the rotatedTransform isn't sharing references with the original transform.
```suggestion
	// Make sure that the rotatedTransform isn't sharing references with the original transform.
```

2020-11-16 20:28 UTC, Calinou commented on tests/test_math.h
> +const float FM_PI = 3.1415926535897932384626433832795028841971693993751f;
I think you can use `Math_PI` (defined in `core/math/math_defs.h`) instead of defining your own constant.

2020-11-16 20:28 UTC, Calinou commented on tests/test_math.h
> +	REQUIRE(rotatedTransform.is_equal_approx(expected));
Use snake_case for variables:

```suggestion
	Transform rotated_transform = transform.rotated(Vector3(0, 1, 0), FM_PI);
	REQUIRE(rotated_transform.is_equal_approx(expected));
```

2020-11-16 20:28 UTC, Calinou commented on tests/test_math.h
> +	REQUIRE(rotatedTransform.is_equal_approx(expected));
```suggestion
	Transform rotated_transform = transform.rotated_local(Vector3(0, 1, 0), FM_PI);
	REQUIRE(rotated_transform.is_equal_approx(expected));
```

2020-11-16 20:28 UTC, Calinou commented on tests/test_math.h
> +	REQUIRE(&rotatedTransform.origin != &transform.origin);
```suggestion
	REQUIRE(&rotated_transform.basis != &transform.basis);
	REQUIRE(&rotated_transform.origin != &transform.origin);
```

2020-11-17 08:54 UTC, lawnjelly commented
Unless I'm misunderstanding the OP, could this be based on a misunderstanding of how spatials are currently able to be rotated in Godot?

The following code works for your proposal case, rotating a spatial in local space to rotate a child camera:
```
func _process(delta):
	m_Time += delta
	
	# create a transform variable
	var tr : Transform = Transform()
	
	# set the basis of the transform to what you want
	tr.basis = Basis(Vector3(0, 1, 0), sin(m_Time))
	
	# set the origin (translate) to what you want
	tr.origin = Vector3(0, 0, 7)
	
	# apply the transform to be the transform of the node
	transform = tr
```
Or you can grab the existing transform with `var tr : Transform = transform` and use that in your calculation of the new transform.

Or is the PR is meant to be a shortcut for what can be achieved already?

2020-11-17 09:27 UTC, AlexanderPruss commented
@lawnjelly There are plenty of ways to accomplish a rotation in-place already. I made the proposal and PR because I was using the existing Transform GDScript and ended up with a result that surprised me. Being surprised can be because I'm less experienced with Godot, but in this case I think it's because something is counterintuitive.

Transform does already have a `rotated` function that returns a rotated Transform. But it's not at all clear that this rotation is around an origin that's not that Transform's origin, though. By adding a function that does rotate around the Transform's origin, the code becomes self-documenting. A user can see that there are two rotation functions, one explicitly for rotating around the Transform's origin.

You could also argue that `Transform.rotated` is currently bugged, or at least specified incorrectly. There are basically two rotations that make sense, imo - rotating in-place, and rotating around the origin of the parent transform. But `Transform.rotated` always rotates around the global (0,0,0) point, which is pretty weird.

2020-11-17 09:59 UTC, lawnjelly commented
Agreed if something is counter intuitive, that is not good. I just had a look at the rotated function from gdscript, and it does appear to be doing a global space rotate, and I'm not sure why either (I'm not really familiar with the gdscript source and functionality etc).

Irrespective of whether a local rotate function was added, this suggests renaming the existing gdscript function might be worth thinking about (although it would have to be for 4.0 as compatibility breaking).

2020-11-17 10:13 UTC, Calinou approved these changes

2020-11-17 10:15 UTC, BastiaanOlij commented
If you want a local rotation, just rotate the basis not the transform? Rotating the transform it's logical that the origin is rotated along with it as it is part of the transform, so calling rotated on the transform it is logical the whole thing rotates, not just half of it. 

There are so many different ways to do a local rotation I'm not sure we need another method. 

Like:
```
transform.basis = transform.basis.rotated(Vector3.UP, degrees)
```

Or:
```
transform = transform * Transform(Basis(Vector3.UP, degrees), Vector3())
```

(note that that last one, multiplying the transform with a rotation is akin to a local rotation, multiplying the rotation with the transform is akin to a rotation from the parents point of view)

2020-11-17 10:25 UTC, AlexanderPruss commented
The word "rotation" is a bit overloaded when talking about Transforms, it can mean multiple things. I'm guessing that whether you think the result of `Transform.rotated()` is surprising or not probably just depends on whether its version of "rotate" is the first one that comes to your mind.

2020-11-17 10:37 UTC, lawnjelly commented
I was also initially confused by the naming, so I do understand where you are coming from, but on reflection and talking with Bastiaan I can see it makes sense and goes with the naming convention used throughout the Godot structs.

Maybe you can make a PR (or modify this) to make a note in the docs to make it more clear what `Transform.rotated()` does? This seems to be the consensus for now unless we get more input.

> explain that if they want to rotate the orientation, they rotate the orientation, i.e. transform.basis.rotate(....)
<Mux213> Yeah I think a note on that function in the docs of the transform to explain "this rotates the transform, including its origin point. If you want to rotate just the basis, call rotate on the basis"

2020-11-17 18:20 UTC, aaronfranke commented
Isn't this identical to `basis.rotated()`?

```gdscript
transform = transform.rotated_local(Vector3.RIGHT, PI)
transform.basis = transform.basis.rotated(Vector3.RIGHT, PI)
```

2020-11-18 15:59 UTC, AlexanderPruss commented
> Maybe you can make a PR (or modify this) to make a note in the docs to make it more clear what Transform.rotated() does? This seems to be the consensus for now unless we get more input.

Looks like that's the decision, I'll take care of it in the next couple of days 👍

2021-06-06 13:54 UTC, Chaosus commented
@AlexanderPruss It needs to be rebased since Transform renamed to Transform3D recently.

2021-08-28 18:00 UTC, mhilbrunner commented
Yes, this needs a rebase and commits need to be squashed.

2021-08-29 12:30 UTC, AlexanderPruss commented
I'm not certain what the decision is. I'm happy to rebase this and squash the commits, but I thought the decision was to just update the documentation instead? That's what this PR is for - https://github.com/godotengine/godot/pull/43694

2021-08-29 14:43 UTC, aaronfranke commented
Yes, I think this should be closed as long as the documentation is updated, we don't need a function for this. #43694 needs a bit of work before it can be merged.

2021-08-30 22:27 UTC, reduz commented
I agree this should be closed. Additionally the same can be achieved with:

```
mat = Transform(axis,angle) * mat;
```

So there is not much of a point on this.

2021-08-30 22:34 UTC, aaronfranke commented
Closing as per the above discussion, the consensus is that this isn't needed.

@AlexanderPruss Updated documentation and tests are still appreciated, so if you can update #43694 that would be great.

2021-08-30 22:34 UTC, closed without merging