Fix ccd enabled by default on Bullet bodies
godotengine/godot pull request #43801
Opened 2020-11-23 17:35 UTC by pouleyKetchoupp

Fix based on https://github.com/godotengine/godot/pull/42643#issuecomment-732296444

It was due to main_shape_changed being called two times for each added body. The first time it disables ccd, which sets the internal ccd threshold to be 10000. The second time, it enables ccd again because the internal threshold is > 0.

Bodies are now consistently created with disabled ccd by default.

This was causing crashing asserts in Bullet when adding bodies in some scenarios, in `btVector3::normalize()`:
```btAssert(!fuzzyZero());```

2020-11-25 14:50 UTC, madmiraal requested changes
I think the problem is that when CCD is disabled, Bullet's ccdMotionThreshold should be set to 0. not 10000.0:
https://github.com/godotengine/godot/blob/c5451468cf09cc7d3f9d3018072b41125d921db1/modules/bullet/rigid_body_bullet.cpp#L747
First, it defaults to 0.:
https://github.com/godotengine/godot/blob/c5451468cf09cc7d3f9d3018072b41125d921db1/thirdparty/bullet/BulletCollision/CollisionDispatch/btCollisionObject.cpp#L49
Second, if it's 0, CCD is not used:
https://github.com/godotengine/godot/blob/c5451468cf09cc7d3f9d3018072b41125d921db1/thirdparty/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp#L863

2020-11-25 14:50 UTC, madmiraal commented on modules/bullet/rigid_body_bullet.cpp
>  }
`get_CcdMotionThreshold()` is zero by default, so this is the correct check.

2020-11-25 14:50 UTC, madmiraal commented on modules/bullet/rigid_body_bullet.cpp
>  	reload_shapes();
There is no need to set CCD to false, it will be disabled by default.

2020-11-25 14:52 UTC, madmiraal commented
> This was causing crashing asserts in Bullet when adding bodies in some scenarios, in btVector3::normalize():
btAssert(!fuzzyZero());

Crashing asserts will still happen with CCD enabled. A separate issue should be raised, because there is a problem with the way that Godot is configuring Bullet CCD.

2020-11-25 20:57 UTC, pouleyKetchoupp commented
> 
> 
> > This was causing crashing asserts in Bullet when adding bodies in some scenarios, in btVector3::normalize():
> > btAssert(!fuzzyZero());
> 
> Crashing asserts will still happen with CCD enabled. A separate issue should be raised, because there is a problem with the way that Godot is configuring Bullet CCD.

Good point, I'll open a ticket for the CCD issue.

2020-11-25 21:14 UTC, pouleyKetchoupp commented
Concerning the way CCD is currently set (threshold of 10000 when disabled) I've decided to keep it this way for now, because this PR is about fixing the crashes that happen without CCD, with minimal changes to current settings.

2020-11-25 21:29 UTC, pouleyKetchoupp commented
@AndreaCatania Do you remember why you set the CCD threshold to 10000 instead of 0 when CCD is disabled in PR #28595?

For now, I'm going to set it to 0 to make things more consistent, but let us know if it was solving a specific issue. Looking at Bullet code it shouldn't make a difference in behavior.

2020-11-26 08:55 UTC, madmiraal approved these changes

2020-12-03 12:28 UTC, merged

2020-12-03 12:28 UTC, akien-mga commented
Thanks!