fix to 'header_separator' requiring an extra space
godotengine/godot pull request #44121
Opened 2020-12-05 15:46 UTC by quendera

The HTTP spec does not require this extra space and, therefore, it causes problems even with properly typed code - when on web export.

2020-12-05 15:56 UTC, akien-mga approved these changes

2020-12-05 17:45 UTC, Faless approved these changes

2020-12-05 17:48 UTC, Faless requested changes
Mmmhhh.. I think we will need to trim the values, either in C++ or JS

2020-12-17 09:05 UTC, akien-mga commented
> Mmmhhh.. I think we will need to trim the values, either in C++ or JS

@quendera Is this something you can implement?
Or do you want to do it @Faless?

2021-03-08 13:56 UTC, Faless commented
Superseded by #46728

2021-03-08 13:56 UTC, closed without merging