Rename Node3D's property translation to positon
godotengine/godot pull request #44198
Opened 2020-12-08 18:06 UTC by madmiraal

Currently, `Node3D` has a helper property called `translation`, which would be better called `position` as exists in `Node2D`. This PR renames `Node3D`'s `translation` property, `position`.
Part of #16863.

2020-12-09 05:35 UTC, aaronfranke requested changes

2020-12-09 08:04 UTC, madmiraal commented on doc/classes/Node3D.xml
> +			Local position of this node.
I slightly modified your suggestion to: "Local position or translation of this node relative to the parent. This is equivalent to [code]transform.origin[/code]."

2020-12-09 09:57 UTC, aaronfranke reviewed
I support this change and the code looks good. Would also be nice to update the docs for Node2D.position to match though.

2020-12-09 09:57 UTC, aaronfranke approved these changes

2020-12-17 07:58 UTC, bluenote10 commented
See my concerns in the proposal https://github.com/godotengine/godot-proposals/issues/1557.

2021-02-13 08:24 UTC, madmiraal commented
Rebased following merge of #45879.

2021-04-05 18:26 UTC, madmiraal commented
Updated documentation with `--doctool .`.

2021-06-03 21:24 UTC, akien-mga commented
We discussed this in a PR preview meeting today, and it had been discussed on and off in chat in previous months too. With the contributors present, we finally reached a consensus that this rename might indeed be a good idea to make things consistent.

`translation` is more "accurate" for experienced 3D developers, but Godot aims at being user-friendly also to less savvy developers, and `position` is still a correct description of what this represents. So we prefer standardizing on `position` for both 2D and 3D than the other way around, assuming that `translation` in 2D would confuse beginners even more. Other issues with `translation` is the homonymy with text/language translation (localization), and the similarity with `transform` which also starts with `trans-`.

2021-06-03 21:24 UTC, akien-mga approved these changes
Good to merge after a rebase.

2021-06-04 09:34 UTC, merged

2021-06-04 09:34 UTC, akien-mga commented
Thanks!

2021-06-04 13:49 UTC, Calinou commented
Note that once this PR is merged, most existing 3D scenes will break until we add property rename handlers.

2021-06-04 13:53 UTC, aaronfranke commented
@Calinou Surprisingly I don't actually think this is a problem. Exactly zero of the scenes in the demo projects have `translation =` in them, because 3D nodes currently store a `Transform3D` for their transformations. The only cases where `translation` exists in the scene files is with animation tracks that animate the `translation` property.

2021-06-04 13:55 UTC, Calinou commented
> @Calinou Surprisingly I don't actually think this is a problem. Exactly zero of the scenes in the demo projects have `translation =` in them, because 3D nodes currently store a `Transform3D` for their transformations. The only cases where `translation` exists in the scene files is with animation tracks that animate the `translation` property.

Indeed, I was mistaken as only `transform` is saved in scene files.