Removed unused code from EditorSelection and added documentation.
godotengine/godot pull request #44249
Opened 2020-12-10 01:21 UTC by EricEzaM

A continuation of #44222

* `_get_transformable_selected_nodes` must have been a remnant of a previous implementation. It was not used anymore.
* `get_selected_nodes` moved lower to be with other `get_selected` methods
* Added documentation in the header to make it clear that in the `Map<Node *, Object *>`, the Object* is metadata provided by an editor plugin, which can then be accessed later by `get_node_editor_data()`.

2021-03-20 21:12 UTC, Calinou requested changes

2021-03-20 21:12 UTC, Calinou commented on editor/editor_data.h
> +*/
Fix Javadoc-style comment end alignment:

```suggestion
 */
```

2021-03-20 21:12 UTC, Calinou commented on editor/editor_data.h
> +	// Add an editor plugin which can provide metadata for selected nodes.
Use present indicative tense for method descriptions:

```suggestion
	// Adds an editor plugin which can provide metadata for selected nodes.
```

2021-03-20 21:12 UTC, Calinou commented on editor/editor_data.h
> +	// Gets all selected nodes
```suggestion
	// Returns all the selected nodes.
```

2021-03-20 21:12 UTC, Calinou commented on editor/editor_data.h
> +	// Gets selected nodes but does not include childen of selected nodes, if they are selected as well.
```suggestion
	// Returns the selected nodes but does not include children of selected nodes if they are selected as well.
```

2021-03-20 21:12 UTC, Calinou commented on editor/editor_data.h
> +	// Gets all selected nodes
```suggestion
	// Returns all the selected nodes.
```

2021-03-20 21:12 UTC, Calinou commented on editor/editor_data.h
> +	// Retuns the map of selected objects and their metdata.
```suggestion
	// Returns the map of selected objects and their metadata.
```

2021-03-20 21:12 UTC, Calinou commented on editor/editor_data.cpp
> +///////////////////////////////////////////////////////////////
In the day and age of IDE navigation, I'm not sure if those huge separator comments are still relevant. I'd leave it as it is currently, and we should discuss whether we should keep them (or haromonize them, or remove them) in a proposal.

2021-10-02 09:02 UTC, EricEzaM commented on doc/classes/EditorSelection.xml
> -		</method>
Though this was not used internally, this could have been used externally by plugins, etc, so this probably shouldnt be deleted.

2022-03-30 09:54 UTC, akien-mga commented
Superseded by #58395.

2022-03-30 09:54 UTC, closed without merging