Fixed issue #39299
godotengine/godot pull request #44344
Opened 2020-12-13 14:08 UTC by RexMaHaoXuan

2020-12-13 17:20 UTC, Calinou commented
Thanks for opening a pull request!

Please [amend the commit to use a human-readable commit message](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind). This way, people reading the Git log can easily figure out what's going on.

2020-12-13 19:11 UTC, akien-mga commented
Tests should go in the `tests` folder.

2021-03-25 19:26 UTC, Calinou requested changes

2021-03-25 19:26 UTC, Calinou commented on tests/test_array.h
> +	const Array a2 = [9.5]
```suggestion
	const Array a1 = [0.8];
	const Array a2 = [9.5];
```

2021-03-25 19:26 UTC, Calinou commented on tests/test_array.h
> +	const Array a2 = [1, 2]
```suggestion
	const Array a1 = [1, 1];
	const Array a2 = [1, 2];
```

2021-03-25 19:26 UTC, Calinou commented on tests/test_array.h
> +	const Array a2 = [2, 3, 4]
```suggestion
	const Array a1 = [1, 2, 3];
	const Array a2 = [2, 3, 4];
```

2021-03-25 19:26 UTC, Calinou commented on tests/test_array.h
> +	const Array a2 = ["a", 2, 3]
```suggestion
	const Array a1 = ["b", 2, 3];
	const Array a2 = ["a", 2, 3];
```

2021-03-25 19:26 UTC, Calinou commented on tests/test_array.h
> +	const Array a2 = [1, 0]
```suggestion
	const Array a1 = [1];
	const Array a2 = [1, 0];
```

2021-03-25 19:26 UTC, Calinou commented on tests/test_array.h
> +namespace TestArray {
There should be a blank line after the namespace declaration:

```suggestion
namespace TestArray {

```

2021-03-25 19:26 UTC, Calinou commented on tests/test_array.h
> +#endif // TEST_Array_H
```suggestion
#endif // TEST_ARRAY_H
```

2021-03-25 19:26 UTC, Calinou commented on tests/test_array.h
> +/*  test_array.h                                                          */
Align the end of the comment with the lines above and below:

```suggestion
/*  test_array.h                                                         */
```

2022-08-02 13:03 UTC, akien-mga commented
The tests never compiled and weren't fixed so closing.

The bug actually seems to be fixed in 4.0 already though the code is still the same. For 3.x I can still reproduce the issue so this might still be relevant to salvage, though I don't understand why this fix changes the behavior.

2022-08-02 13:03 UTC, closed without merging