allow input echo when changing ui focus
godotengine/godot pull request #44456
Opened 2020-12-17 13:28 UTC by univeous

It will allow us to change UI focus continuously by holding navigation key.

before:
![ftqMlL9Dlw](https://user-images.githubusercontent.com/40604180/102461373-3e986400-4083-11eb-8027-b90e259e725f.gif)

after:
![nAKWXeiieE](https://user-images.githubusercontent.com/40604180/102461387-422beb00-4083-11eb-8c1d-e30fdcecdfd5.gif)

It's a more common UI pattern. In Godot editor itself it works like the latter.

[Discussion](https://github.com/godotengine/godot-proposals/issues/1997)

2021-01-27 00:22 UTC, KoBeWi requested changes
The `input->is_action_pressed("ui_focus_next")` part is no longer necessary, as it's already checked in the event (or at least I don't see any difference after removing it).

Also this needs rebase.

2021-01-27 04:03 UTC, univeous commented
Is it looks ok now?

2021-01-27 12:11 UTC, KoBeWi approved these changes

2021-04-08 00:30 UTC, EricEzaM approved these changes

2021-04-08 08:22 UTC, akien-mga commented
@univeous FYI, the email used to sign your commit (see header of https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/44456.patch ) doesn't seem to be linked to your GitHub account. That's not a problem for Git nor for us, but if you want to get full attribution for this commit, you can add this email as secondary email in your GitHub settings.

2021-04-08 11:14 UTC, univeous commented
> @univeous FYI, the email used to sign your commit (see header of https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/44456.patch ) doesn't seem to be linked to your GitHub account. That's not a problem for Git nor for us, but if you want to get full attribution for this commit, you can add this email as secondary email in your GitHub settings.

not noticed before. Added. thank you!

2021-04-08 11:28 UTC, merged

2021-04-08 11:28 UTC, akien-mga commented
Thanks!

2021-04-29 09:28 UTC, akien-mga commented
Cherry-picked for 3.4.