Fix joint RID not being passed to _set in PhysicalBone
godotengine/godot pull request #44535
Opened 2020-12-20 00:02 UTC by Demindiro

The joint RID was never passed to the `_set()` function of the `joint_data`, which meant the joints on the PhysicalServer's side wouldn't be updated.

Attached is a reproduction project (just the platformer demo but with ragdoll physics). Press tab to toggle between stiff and pudding mode.

I think it would be best to remove the default `RID()` value for the `RID j` parameter. It's probably better to be explicit to prevent similar bugs in the future.

@Favkis could you check if this patch fixes your issue please?

[platformer.zip](https://github.com/godotengine/godot/files/5720313/platformer.zip)

2020-12-20 05:44 UTC, Chaosus commented
Changes should be made for the master branch first - that's a general rule of our contributing pipeline. Could you please create a 4.0 version of this PR?

2020-12-20 12:10 UTC, Demindiro commented
> Changes should be made for the master branch first - that's a general rule of our contributing pipeline. Could you please create a 4.0 version of this PR?

I will once @Favkis confirms whether this change fixes his issue or not.

2020-12-20 12:23 UTC, Favkis commented
@Demindiro thank you! I'll check i na few hours as soon as I get home!

2020-12-20 12:36 UTC, Favkis commented
@Demindiro 
It works now!
![image](https://user-images.githubusercontent.com/46406204/102713397-0d18d600-42d9-11eb-8e7e-fa836a029f40.png)

2020-12-20 12:48 UTC, Favkis approved these changes
It works. Now .set works for 6DOF and other types!
![image](https://user-images.githubusercontent.com/46406204/102713498-ca0b3280-42d9-11eb-91f6-5b112cd5c841.png)



https://user-images.githubusercontent.com/46406204/102713619-a0064000-42da-11eb-9719-301b71668817.mp4

As you can see on video, (upper torso is 6DOF), first run character watches up because torso is set to 89 min 90 max. Second time I comment the code and character falls relaxed.

2020-12-20 17:50 UTC, Chaosus commented
You've redirect it to `master`? Never do that again - it's not a common practice + this will confuse other contributors which maintain the bug tracker, you should open a new PR that targets it.

2020-12-20 17:51 UTC, Demindiro commented
> You've redirect it to master? Never do that again - it's not a common practice + this will confuse other contributors which maintain the bug tracker, you should open a new PR that targets it.

Okay, I'll keep it in mind for next time.

2020-12-21 07:06 UTC, madmiraal requested changes
Well done. As you suggest:
> I think it would be best to remove the default RID() value for the RID j parameter. It's probably better to be explicit to prevent similar bugs in the future.

If you make that change too, I think it will be good to go.

2020-12-21 07:09 UTC, madmiraal commented
I've added the cherrypick label, because, although the change is not cherrypickable, the change is easy enough to backport and it was originally created as a 3.2 PR.

2020-12-22 06:02 UTC, madmiraal commented
@Demindiro Thanks for the update. Please squash your commits into a single commit.

2020-12-23 05:40 UTC, madmiraal approved these changes

2020-12-23 11:41 UTC, AndreaCatania approved these changes

2020-12-23 15:08 UTC, merged

2020-12-23 15:08 UTC, akien-mga commented
Thanks!

2020-12-28 14:18 UTC, Favkis commented
@Demindiro 
Looks like that fixed only .set but not doing same throguh PhysicsServer:
![image](https://user-images.githubusercontent.com/46406204/103220139-901cda80-4930-11eb-876e-b2f0e37f906b.png)
![image](https://user-images.githubusercontent.com/46406204/103220146-990dac00-4930-11eb-957e-d5ba12cb880a.png)
![image](https://user-images.githubusercontent.com/46406204/103220154-a034ba00-4930-11eb-8e5a-92bf5f79813a.png)

2020-12-28 14:33 UTC, Demindiro commented
@Favkis Can you check if `print(rid.get_id())` returns 0? I'm fairly certain what the issue is but I'd like to confirm.

2020-12-28 14:48 UTC, Favkis commented
@Demindiro 
![image](https://user-images.githubusercontent.com/46406204/103221980-df650a00-4934-11eb-882a-6626b5fe3818.png)

2021-04-29 09:30 UTC, akien-mga commented
Cherry-picked for 3.4.

> Looks like that fixed only .set but not doing same through PhysicsServer:

Was there a follow-up for this? If not, it would be good to open a dedicated issue so that it's not forgotten.