Simplify `randi_range` implementation
godotengine/godot pull request #44562
Opened 2020-12-21 03:21 UTC by mcognetta

This PR simplifies `RandomPCG::random(int, int)` (called by `randi_range`) by removing some branching. 

The simplification also results in a modest (~11%) speedup for this function on some large benchmarks on two machines of mine (when compiled with -O3).

2020-12-21 12:35 UTC, Chaosus requested changes

2020-12-21 12:35 UTC, Chaosus commented on core/math/random_pcg.cpp
> +	if (p_from == p_to)
Use curly braces for that expression - that's a rule which accepted for the entire 
engine.

2020-12-21 12:37 UTC, Chaosus commented
Please, merge commits together as required by our pipeline:  https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request

2020-12-21 13:41 UTC, Xrayez commented
May be also worth to add some kind of bias test case for this to cover #27094 to ensure that this doesn't introduce regression.

Here's what I mean (test code from Goost): https://github.com/goostengine/goost/blob/gd3/tests/project/goost/core/math/test_random.gd#L110-L119 ([GUT](https://github.com/bitwes/Gut) code):

```gdscript
func test_randi_range_unbiased():
	var zero_count = 0
	var one_count = 0
	for x in 10000:
		var i = Random.randi_range(0, 1)
		if i == 0:
			zero_count += 1
		if i == 1:
			one_count += 1
	assert_almost_eq(zero_count / float(one_count), 1.0, 0.1) # 0.1 is maximum ratio difference.
```

But instead port this to use doctest, see [Unit testing](https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html) page.

See https://github.com/godotengine/godot/blob/master/tests/test_random_number_generator.h for existing test cases.

`Math::is_equal_approx()` can be used to compare ratios in C++ (or even `Math::is_zero_approx()` if works with Godot epsilon...).

Writing tests is not currently required, but recommended to write for core classes. 🙂

2020-12-21 19:04 UTC, mcognetta commented
Thanks for your comments. I have squashed the commits and added a test for (lack of) bias.

2020-12-21 19:09 UTC, Xrayez approved these changes

2020-12-21 19:14 UTC, mcognetta commented
Windows failure seems unrelated.

2020-12-21 20:19 UTC, Xrayez commented
```
tests/test_random_number_generator.h:266:31: runtime error: index 10 out of bounds for type 'int [10]'
tests/test_random_number_generator.h:266:31: runtime error: load of address 0x7ffee2f9b978 with insufficient space for an object of type 'int'
```
`randi_range` is inclusive if you generate numbers from 0 to 10.

The first assertion was enough to test this to be honest. 🙂

2020-12-21 20:24 UTC, Xrayez commented on tests/test_random_number_generator.h
> +		vals[rng->randi_range(0, 10)]++;
I think this should fix the crash.

```suggestion
		vals[rng->randi_range(0, 9)]++;
```

2020-12-21 20:35 UTC, Xrayez commented on tests/test_random_number_generator.h
> +TEST_CASE("[RandomNumberGenerator] Random int range bias check") {
Not sure about this, but may be worth allowing this to fail without affecting CI, similarly to #44560.

```suggestion
TEST_CASE_MAY_FAIL("[RandomNumberGenerator] Random int range bias check") {
```

2020-12-21 22:46 UTC, mcognetta commented
I may have inadvertently pulled in some changes from #44560 when rebasing. But it now has `TEST_CASE_MAY_FAIL` for the bias check.

2020-12-21 23:03 UTC, Xrayez commented
It doesn't seem like the rebase was smooth, it's very strange why changes from #44560 appear to be as addition after rebase in this PR, GitHub bug? 👀

But looking at your fork in https://github.com/mcognetta/godot/commits/randi_range_simplification, they don't contain recent commits to RNG tests, but your commit has those changes as in #44560.

Other than that, this PR looks good to me.

2020-12-22 01:27 UTC, mcognetta commented
I am not quite sure what happened, but I was able to resolve it by pushing a new minor change. Github now correctly detects that it is based on master after #44560. Sorry for the confusion. This should be ready to merge now.

2020-12-22 04:27 UTC, Chaosus approved these changes

2020-12-22 10:28 UTC, akien-mga approved these changes

2020-12-22 10:29 UTC, merged

2020-12-22 10:29 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2020-12-22 17:50 UTC, mcognetta commented
Thanks!