Initialize class variables with default values in scene/ [1/2]
godotengine/godot pull request #44630
Opened 2020-12-23 19:36 UTC by qarmin

Part of #43636

2021-02-02 16:21 UTC, pouleyKetchoupp approved these changes
Physics classes look fine (I haven't checked other classes).

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/animated_sprite_2d.h
> +		float speed = 5;
```suggestion
		float speed = 5.0;
```
Just to make the `float` explicit while we're at it.

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/animated_sprite_2d.h
> +	float timeout = 0;
```suggestion
	float timeout = 0.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/area_2d.h
> +	real_t angular_damp = 1;
```suggestion
	real_t gravity_distance_scale = 0.0;
	real_t linear_damp = 0.1;
	real_t angular_damp = 1.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/audio_stream_player_2d.h
> +	volatile float setplay = -1;
```suggestion
	volatile float setseek = -1.0;
	volatile bool active = false;
	volatile float setplay = -1.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/audio_stream_player_2d.h
> +	float pitch_scale = 1;
```suggestion
	float volume_db = 0.0;
	float pitch_scale = 1.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/camera_2d.h
> +	Point2 camera_pos = Vector2();
`Point2` is already default initialized IINM.

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/camera_2d.cpp
>  Camera2D::Camera2D() {
You forgot to remove some assignments in this constructor.

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/collision_object_2d.h
> +		float one_way_collision_margin = 0;
```suggestion
		float one_way_collision_margin = 0.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/collision_polygon_2d.h
> +	float one_way_collision_margin = 1;
```suggestion
	float one_way_collision_margin = 1.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/collision_shape_2d.h
> +	float one_way_collision_margin = 1;
```suggestion
	float one_way_collision_margin = 1.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/cpu_particles_2d.h
> +		float rotation = 0;
```suggestion
		float rotation = 0.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/cpu_particles_2d.h
> +		float lifetime = 0;
```suggestion
		float angle_rand = 0.0;
		float scale_rand = 0.0;
		float hue_rot_rand = 0.0;
		float anim_offset_rand = 0.0;
		float time = 0.0;
		float lifetime = 0.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/cpu_particles_2d.h
>  	float time;
You can update some of those too with the values from the constructor.

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/joints_2d.h
> +	real_t bias = 0;
```suggestion
	real_t bias = 0.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/joints_2d.h
> +	real_t softness = 0;
```suggestion
	real_t softness = 0.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/joints_2d.h
> +	real_t initial_offset = 25;
```suggestion
	real_t length = 50.0;
	real_t initial_offset = 25.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/joints_2d.h
> +	real_t length = 50;
```suggestion
	real_t stiffness = 20.0;
	real_t damping = 1.0;
	real_t rest_length = 0.0;
	real_t length = 50.0;
```

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/parallax_layer.h
> +	;
Stray semicolon.

2021-02-03 11:00 UTC, akien-mga commented on scene/2d/parallax_layer.h
> +	Size2 motion_scale = Size2(1, 1);
This can be removed from the constructor.

2021-02-03 11:00 UTC, akien-mga commented on scene/3d/camera_3d.h
> +	Vector2 frustum_offset = Vector2();
Not necessary, it's default initialized.

2021-02-03 11:00 UTC, akien-mga commented on scene/3d/camera_3d.cpp
>  	//active=false;
Could clean this one up while at it.

Also `doppler_tracking` was missed below.

2021-02-03 11:07 UTC, akien-mga commented on scene/3d/skeleton_3d.h
> +		bool enabled = false;
Wrong, it defaults to true in the constructor.

2021-02-03 11:16 UTC, akien-mga commented on scene/3d/vehicle_body_3d.h
> +	real_t m_brake = real_t(0.);
I know it was in the constructor but I don't see why the explicit `real_t()` cast is needed.

2021-02-03 11:16 UTC, akien-mga commented on scene/3d/vehicle_body_3d.h
> +	real_t m_rollInfluence = real_t(0.);
This was `0.1` in the constructor.

2021-02-03 11:16 UTC, akien-mga commented on scene/3d/vehicle_body_3d.cpp
>  	ccd = false;
Could be removed, assuming that they're the same default values as in PhysicsBody3D.

2021-02-03 11:37 UTC, akien-mga requested changes
Looks great overall, thanks for the huge amount of work (I did the same for `core` and I know how tedious it is :D).

I initially commented about floats that should have `.0` to make their type clear, but then stopped at some point as there's a ton of them. Would still be worth changing IMO, possibly by grepping the `git show` for `(float|real_t) .* = `.

2021-02-03 11:37 UTC, akien-mga commented on scene/animation/animation_blend_tree.h
> +	;
Stay semicolon.

2021-02-03 11:37 UTC, akien-mga commented on scene/animation/root_motion_view.h
> +	bool use_in_game = false;
Unused, can be removed.

2021-02-08 08:31 UTC, akien-mga approved these changes

2021-02-08 08:31 UTC, merged

2021-02-08 08:31 UTC, akien-mga commented
Thanks! Amazing work!