Fix crash on FileSystemDock's tree when trying to collapse or expand folder
godotengine/godot pull request #44887
Opened 2021-01-03 11:11 UTC by gongpha

This PR fixes a crash when opening a project and starting right-click on a root or any subdirectories (Without selecting any item else) in the file system dock. Then choose collapse or expand. (or when the tree gets updated.)

2021-01-03 17:07 UTC, Calinou requested changes, later dismissed

2021-01-03 17:07 UTC, Calinou commented on editor/filesystem_dock.cpp
> +		subdirectory_item->set_as_cursor(0);
Please add a comment to explain why this line is necessary:

```suggestion
		// Prevent crash when trying to collapse or expand a folder when nothing is selected.
		subdirectory_item->set_as_cursor(0);
```

2021-01-26 14:31 UTC, akien-mga approved these changes

2021-01-26 14:32 UTC, merged

2021-01-26 14:32 UTC, akien-mga commented
Thanks!

2021-01-26 14:48 UTC, akien-mga commented
Cherry-picked for 3.2.4.