Fixed 6DOF set/get check for the path starting with joint_constraints
godotengine/godot pull request #45267
Opened 2021-01-17 23:42 UTC by HipsterPenguin

New code simply checks whether or not property has joint_constraints as the first part of its path.
This fixes the bug mentioned in #44320.

2021-01-18 08:54 UTC, akien-mga commented on scene/3d/physics_body_3d.cpp
> +		return false;
You should use braces around the `if`'s block.

2021-01-18 11:58 UTC, akien-mga commented
Could you squash the two commits into one? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase)).

2021-01-18 17:18 UTC, pouleyKetchoupp requested changes
This works well! I would just use `if (!path.begins_with("joint_constraints/"))` instead for the condition. It's an exact equivalent, but it avoids constructing a new `String` (return value from `get_slicec`) and doing an extra String comparison.

2021-01-19 12:43 UTC, HipsterPenguin commented
Alright, I think I squashed the commits, sorry about any issues as I am new to this. (I'm sure you could tell). Let me know if there is anything else to fix and thank you for your reviews!

2021-01-19 15:30 UTC, pouleyKetchoupp approved these changes

2021-01-20 15:57 UTC, AndreaCatania approved these changes

2021-01-20 16:51 UTC, merged

2021-01-20 16:51 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2021-01-26 12:43 UTC, akien-mga commented
Cherry-picked for 3.2.4.