TileSet/TileMap rework
godotengine/godot pull request #45278
Opened 2021-01-18 08:42 UTC by groud

This is a first step in the TileSet/TileMap rework. It includes:
- A rework of the TileMap and TileSet nodes. Most properties have been moved to the TileSet resource, they better handle shapes (true support for hexagonal and isometric tiles),
- The TileSet editor supports only atlases for now (support for scenes will be added later on),
- For each tile in an atlas, you can create "alternative tiles", they will share the same part of the texture but you may assign them different properties (not yet implemented).

Disclaimer: the API is not ready yet and a lot of feature are missing.

Some screenshots for pleasure:
![2021-01-18-092628_1291x489_scrot](https://user-images.githubusercontent.com/6093119/104890015-4479b180-596f-11eb-98e8-e7ce68385231.png)
![2021-01-18-092602_1304x797_scrot](https://user-images.githubusercontent.com/6093119/104890017-45aade80-596f-11eb-9e24-37e15452dcce.png)

Download the builds:

TODO

**WARNING: opening an existing project with this build will break your TileMaps/TileSets resources for any other version of Godot. Make a backup of your project if you wish to try it on existing projects.**

This is the place to provide feedback on this build. Please report here any crash/errors.
I don't want to give any documentation for now on how to use the editors yet, to see if it is intuitive enough. ;)

2021-01-18 09:20 UTC, qarmin commented
I have crash when trying to open empty project with Address Sanitizer(this errors probably means that uninitialised variable was used)
```
scene/2d/tile_map.cpp:75:9: runtime error: member access within misaligned address 0xbebebebebebebebe for type 'const struct TileMap', which requires 8 byte alignment
0xbebebebebebebebe: note: pointer points here
<memory cannot be printed>
scene/2d/tile_map.cpp:75:9: runtime error: reference binding to misaligned address 0xbebebebebebec1de for type 'const struct Ref', which requires 8 byte alignment
0xbebebebebebec1de: note: pointer points here
<memory cannot be printed>
scene/2d/tile_map.cpp:75:9: runtime error: member access within misaligned address 0xbebebebebebebebe for type 'const struct TileMap', which requires 8 byte alignment
0xbebebebebebebebe: note: pointer points here
<memory cannot be printed>
core/object/reference.h:61:14: runtime error: member access within misaligned address 0xbebebebebebec1de for type 'const struct Ref', which requires 8 byte alignment
0xbebebebebebec1de: note: pointer points here
<memory cannot be printed>
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] bin/godot.linuxbsd.tools.64s() [0x1e180fa] (/mnt/Miecz/mojgodot/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f87592a6210] (??:0)
[3] Ref<TileSet>::ref(Ref<TileSet> const&) (/mnt/Miecz/mojgodot/./core/object/reference.h:61)
[4] Ref<TileSet>::Ref(Ref<TileSet> const&) (/mnt/Miecz/mojgodot/./core/object/reference.h:178)
[5] TileMap::get_tileset() const (/mnt/Miecz/mojgodot/scene/2d/tile_map.cpp:76)
[6] TileMapEditor::_update_bottom_panel() (/mnt/Miecz/mojgodot/editor/plugins/tiles/tile_map_editor.cpp:81)
[7] TileMapEditor::TileMapEditor() (/mnt/Miecz/mojgodot/editor/plugins/tiles/tile_map_editor.cpp:1012)
[8] TilesEditor::TilesEditor(EditorNode*) (/mnt/Miecz/mojgodot/editor/plugins/tiles/tiles_editor_plugin.cpp:201 (discriminator 2))
[9] TilesEditorPlugin::TilesEditorPlugin(EditorNode*) (/mnt/Miecz/mojgodot/editor/plugins/tiles/tiles_editor_plugin.cpp:253 (discriminator 2))
[10] EditorNode::EditorNode() (/mnt/Miecz/mojgodot/editor/editor_node.cpp:6607 (discriminator 1))
[11] Main::start() (/mnt/Miecz/mojgodot/main/main.cpp:2139 (discriminator 1))
[12] bin/godot.linuxbsd.tools.64s(main+0x32f) [0x1e15df5] (/mnt/Miecz/mojgodot/platform/linuxbsd/godot_linuxbsd.cpp:57)
[13] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f87592870b3] (??:0)
[14] bin/godot.linuxbsd.tools.64s(_start+0x2e) [0x1e15a0e] (??:?)
-- END OF BACKTRACE --
Przerwane (zrzut pamięci)
```

2021-01-18 13:26 UTC, Xrayez commented on core/math/geometry_2d.h
> +	static Vector<Point2i> bresenham_line(const Point2i &p_start, const Point2i &p_end) {
Should #43916 be closed then?

2021-01-18 14:03 UTC, groud commented
> I have crash when trying to open empty project with Address Sanitizer(this errors probably means that uninitialised variable was used)

I cannot reproduce. Could you give me the exact scons args you use and the steps to reproduce the bug? 
I am not sure which variable would be uninitialized. (tile_map is likely initialized automatically to nullptr, and the Ref<Tileset> is correctly checked with is_valid())

2021-01-18 14:16 UTC, qarmin commented
This contains leak, address and undefined sanitizers:
```
 scons p=linuxbsd -j7 use_asan=yes use_ubsan=yes;
````

2021-01-18 14:59 UTC, qarmin commented
I found that this is caused by non initializing tilemap - this patch fixes issue
```
diff --git a/editor/plugins/tiles/tile_map_editor.h b/editor/plugins/tiles/tile_map_editor.h
index 3c8af2a19e..b9466d7103 100644
--- a/editor/plugins/tiles/tile_map_editor.h
+++ b/editor/plugins/tiles/tile_map_editor.h
@@ -84,7 +84,7 @@ private:
        void _tile_alternatives_control_gui_input(const Ref<InputEvent> &p_event);
 
        // --- TileMap ---
-       TileMap *tile_map;
+       TileMap *tile_map = nullptr;
 
        HBoxContainer *tilemap_toolbar;
 
diff --git a/editor/plugins/tiles/tiles_editor_plugin.h b/editor/plugins/tiles/tiles_editor_plugin.h
index 4e5e59bddb..35ce608b6e 100644
--- a/editor/plugins/tiles/tiles_editor_plugin.h
+++ b/editor/plugins/tiles/tiles_editor_plugin.h
@@ -44,7 +44,7 @@ class TilesEditor : public VBoxContainer {
        static TilesEditor *singleton;
 
 private:
-       TileMap *tile_map;
+       TileMap *tile_map = nullptr;
        Ref<TileSet> tile_set;
 
        Button *tileset_tilemap_switch_button;
```

2021-01-18 15:02 UTC, groud commented
> I found that this is caused by non initializing tilemap - this patch fixes issue

Ah ok. I though pointers were supposed to be initialized automatically to nullptr. That's weird.
Ok I'll patch this then, thanks!

2021-01-18 15:29 UTC, qarmin commented
When opening and closing editor with this project - [Temp Projekty.zip](https://github.com/godotengine/godot/files/5831078/Temp.Projekty.zip) I have this read after free:
(`tileset_tab_sources` is already deleted, by tileset wants to use it again in destructor)

```
==244823==ERROR: AddressSanitizer: heap-use-after-free on address 0x61b000172990 at pc 0x000002a124e3 bp 0x7ffc892fd530 sp 0x7ffc892fd520
READ of size 8 at 0x61b000172990 thread T0
    #0 0x2a124e2 in Object::_change_notify(char const*) core/object/object.h:562
    #1 0xfcee69a in TileSet::remove_atlas_source(int) scene/resources/tile_set/tile_set.cpp:1097
    #2 0xfd07aad in TileSet::~TileSet() scene/resources/tile_set/tile_set.cpp:1400
    #3 0xb1d9642 in void memdelete<TileSet>(TileSet*) core/os/memory.h:115
    #4 0xb1d3584 in Ref<TileSet>::unref() core/object/reference.h:221
    #5 0xb1d1cfc in Ref<TileSet>::~Ref() core/object/reference.h:233
    #6 0xb1c836c in TilesEditor::~TilesEditor() editor/plugins/tiles/tiles_editor_plugin.cpp:222
    #7 0x2c007d9 in void memdelete<Node>(Node*) core/os/memory.h:115
    ...
    #125 0x1360312a in predelete_handler(Object*) core/object/object.cpp:1824
    #126 0xc7642fd in void memdelete<Window>(Window*) core/os/memory.h:111
    #127 0xc72316b in SceneTree::finalize() scene/main/scene_tree.cpp:527
    #128 0x1e23390 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:266
    #129 0x1e15ec1 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #130 0x7f112c03e0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #131 0x1e15a0d in _start (/mnt/Miecz/mojgodot/bin/godot.linuxbsd.tools.64s+0x1e15a0d)

0x61b000172990 is located 16 bytes inside of 1584-byte region [0x61b000172980,0x61b000172fb0)
freed by thread T0 here:
    #0 0x7f112d2711b7 in __interceptor_free (/lib/x86_64-linux-gnu/libasan.so.6+0xb01b7)
    #1 0x12506880 in Memory::free_static(void*, bool) core/os/memory.cpp:169
    #2 0x2c007ea in void memdelete<Node>(Node*) core/os/memory.h:118
    #3 0xc62d644 in Node::_notification(int) scene/main/node.cpp:169
    #4 0x2bbd20f in Node::_notificationv(int, bool) scene/main/node.h:45
    #5 0x2bbff7a in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:164
    #6 0x2bc2664 in Control::_notificationv(int, bool) scene/gui/control.h:47
    #7 0x2bc6fe2 in Container::_notificationv(int, bool) scene/gui/container.h:37
    #8 0xd3fd094 in TabContainer::_notificationv(int, bool) scene/gui/tab_container.h:39
    #9 0x135dad24 in Object::notification(int, bool) core/object/object.cpp:793
    #10 0x135cd75d in Object::_predelete() core/object/object.cpp:354
    #11 0x1360312a in predelete_handler(Object*) core/object/object.cpp:1824
    #12 0x2c0061b in void memdelete<Node>(Node*) core/os/memory.h:111
    #13 0xc62d644 in Node::_notification(int) scene/main/node.cpp:169
    #14 0x2bbd20f in Node::_notificationv(int, bool) scene/main/node.h:45
    #15 0x2bbff7a in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:164
    #16 0x2bc2664 in Control::_notificationv(int, bool) scene/gui/control.h:47
    #17 0x2bc6fe2 in Container::_notificationv(int, bool) scene/gui/container.h:37
    #18 0x2bc97d0 in BoxContainer::_notificationv(int, bool) scene/gui/box_container.h:37
    #19 0x2bcf974 in VBoxContainer::_notificationv(int, bool) scene/gui/box_container.h:78
    #20 0xc1fbb4e in TileSetEditor::_notificationv(int, bool) editor/plugins/tiles/tile_set_editor.h:40
    #21 0x135dad24 in Object::notification(int, bool) core/object/object.cpp:793
    #22 0x135cd75d in Object::_predelete() core/object/object.cpp:354
    #23 0x1360312a in predelete_handler(Object*) core/object/object.cpp:1824
    #24 0x2c0061b in void memdelete<Node>(Node*) core/os/memory.h:111
    #25 0xc62d644 in Node::_notification(int) scene/main/node.cpp:169
    #26 0x2bbd20f in Node::_notificationv(int, bool) scene/main/node.h:45
    #27 0x2bbff7a in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:164
    #28 0x2bc2664 in Control::_notificationv(int, bool) scene/gui/control.h:47
    #29 0x2bc6fe2 in Container::_notificationv(int, bool) scene/gui/container.h:37

previously allocated by thread T0 here:
    #0 0x7f112d271517 in malloc (/lib/x86_64-linux-gnu/libasan.so.6+0xb0517)
    #1 0x12505973 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:76
    #2 0x12505872 in operator new(unsigned long, char const*) core/os/memory.cpp:41
    #3 0xc1f7335 in TileSetEditor::TileSetEditor() editor/plugins/tiles/tile_set_editor.cpp:52
    #4 0xb1c6e61 in TilesEditor::TilesEditor(EditorNode*) editor/plugins/tiles/tiles_editor_plugin.cpp:211
    #5 0xb1c9d24 in TilesEditorPlugin::TilesEditorPlugin(EditorNode*) editor/plugins/tiles/tiles_editor_plugin.cpp:253
    #6 0x87d9d11 in EditorNode::EditorNode() editor/editor_node.cpp:6607
    #7 0x1f61f41 in Main::start() main/main.cpp:2139
    #8 0x1e15df4 in main platform/linuxbsd/godot_linuxbsd.cpp:57
    #9 0x7f112c03e0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-use-after-free core/object/object.h:562 in Object::_change_notify(char const*)
 value after free

```

2021-01-18 15:45 UTC, qarmin commented
This patch fixes invalid read(I don't know if it is proper, but works)
```
diff --git a/editor/plugins/tiles/tile_set_editor_sources_tab.cpp b/editor/plugins/tiles/tile_set_editor_sources_tab.cpp
index bdb0ac5ac5..858b7b7b3a 100644
--- a/editor/plugins/tiles/tile_set_editor_sources_tab.cpp
+++ b/editor/plugins/tiles/tile_set_editor_sources_tab.cpp
@@ -1814,6 +1814,7 @@ TileSetEditorSourcesTab::TileSetEditorSourcesTab() {
 }
 
 TileSetEditorSourcesTab::~TileSetEditorSourcesTab() {
+       edit(nullptr);
        memdelete(tile_proxy_object);
        memdelete(alternative_tile_proxy_object);
        memdelete(atlas_source_proxy_object);
```

2021-01-18 15:54 UTC, qarmin commented
Also `drag_type` variable isn't initialized in constructor `TileMapEditor::TileMapEditor()` but it is used.

2021-01-18 16:10 UTC, groud commented
Thanks again! I'll apply those patch.

2021-01-18 18:59 UTC, groud commented
@qarmin I updated the PR, could you try again and see if most of your problems are solved?

2021-01-18 20:54 UTC, KoBeWi commented
I gave the new editor a brief try and it's already much better than the old one. Fixed palette and multi-tile drawing is a life-changer for me.
My biggest gripe is that RMB doesn't erase tiles. I hope it's already planned, because switching to Eraser to remove something is a chore.

From other stuff (some of which is probably known/planned):
- TileMap doesn't seem to use tile size. It always draws with 16 pixels. Creating atlas with different size works fine.
- When you click TileMap with TileSet for the first time, it will show the atlas contents, but you can't select it, because atlas is not selected
![image](https://user-images.githubusercontent.com/2223172/104961563-dbc61f80-59d6-11eb-8bc4-ba43dcd8bd29.png)
- It's not really apparent that you can zoom the tileset view. I was going to report that zoom would be useful, but then tried Ctrl + Wheel and got surprised
- Holding Shift should switch to line tool (like in old TileMap)
- It would be useful if the faded grid was drawn over bigger area. E.g. if you want to draw a pitfall, the grid won't reach the other side, so it's difficult to judge distance
![image](https://user-images.githubusercontent.com/2223172/104961352-71ad7a80-59d6-11eb-9a7c-e467ba5c19b0.png)
maybe it should just extend to the preview?

Great work so far.

2021-01-18 22:28 UTC, groud commented
> My biggest gripe is that RMB doesn't erase tiles. I hope it's already planned, because switching to Eraser to remove something is a chore.

I am not against it, the main problem for me right now is that only right click works for me to move the view (I don't know why but middle mouse button to pan is not working well on my side).

> When you click TileMap with TileSet for the first time, it will show the atlas contents, but you can't select it, because atlas is not selected.

Yeah, this is a bug I have to fix. If nothing is selected on the left the atlas should not be displayed. I'll fix this.

> It's not really apparent that you can zoom the tileset view. I was going to report that zoom would be useful, but then tried Ctrl + Wheel and got surprised

Ah yeah, I should add the zoom buttons. :)

> Holding Shift should switch to line tool

Make sense, though I might deal with that kind of things later on. There might be a lot of different features people might like with modifier keys (maybe the rect tool is used more often than the line tool for example). I think it's better to wait for now to see what might be the best solution.

> It would be useful if the faded grid was drawn over bigger area. E.g. if you want to draw a pitfall, the grid won't reach the other side, so it's difficult to judge distance

Hmm... Maybe this should be made configurable, as this might depend on the game you are working on. But that's a good point.

2021-01-18 22:33 UTC, KoBeWi commented
> We might draw the grid around the preview, but it cannot be extended to there. There is a limit on how many lines we can draw.

But doesn't the grid extend anyways when you click and draw the tile at that position? My biggest worry would be that rapid mouse movements would cause lots of redrawing, but almost the same happens when you draw lots of tiles.

2021-01-18 22:49 UTC, groud commented
> But doesn't the grid extend anyways when you click and draw the tile at that position

No, there a limit on how many tiles shapes are drawn anyway, otherwise there would be significant slowdowns. The solution tries to always draw as much tiles as possible in the screen, and prioritizes the tiles in the center.


Btw I forgot this question:
> TileMap doesn't seem to use tile size. It always draws with 16 pixels. Creating atlas with different size works fine.

That's weird. The base tile size is to be modified in the inspector though (when editing the TileSet resource), did you modify this value? Because the tile size value in the atlas is only for rendering purposes (size of the texture region), this is needed for isometric tiles for examples, where usually tiles in the texture will have a different size from the one in the grid.

2021-01-18 23:03 UTC, KoBeWi commented
> No, there a limit on how many tiles shapes are drawn anyway, otherwise there would be significant slowdowns. The solution tries to always draw as much tiles as possible in the screen, and prioritizes the tiles in the center.

But I mean this:
![t7zqJX4AHh](https://user-images.githubusercontent.com/2223172/104969722-8e9f7900-59e9-11eb-9be6-da5596ade8d1.gif)
What if grid extended to cursor before clicking? In the end the effect is the same (or isn't?).

> The base tile size is to be modified in the inspector though (when editing the TileSet resource), did you modify this value?

I only see quadrant size and changing it doesn't have any visible effect.
![image](https://user-images.githubusercontent.com/2223172/104969632-55ff9f80-59e9-11eb-9571-7fc988952f0c.png)

2021-01-18 23:03 UTC, KoBeWi commented
> No, there a limit on how many tiles shapes are drawn anyway, otherwise there would be significant slowdowns. The solution tries to always draw as much tiles as possible in the screen, and prioritizes the tiles in the center.

But I mean this:
![t7zqJX4AHh](https://user-images.githubusercontent.com/2223172/104969722-8e9f7900-59e9-11eb-9be6-da5596ade8d1.gif)
What if grid extended to cursor before clicking? In the end the effect is the same (or isn't?).

> The base tile size is to be modified in the inspector though (when editing the TileSet resource), did you modify this value?

I only see quadrant size and changing it doesn't have any visible effect.
![image](https://user-images.githubusercontent.com/2223172/104969632-55ff9f80-59e9-11eb-9571-7fc988952f0c.png)

2021-01-19 09:06 UTC, groud commented
> What if grid extended to cursor before clicking? In the end the effect is the same (or isn't?)

If you unzoom a lot this is what happen, not to draw too many lines:
![Peek 19-01-2021 09-43](https://user-images.githubusercontent.com/6093119/105009495-d4d0f880-5a3a-11eb-840f-57d0dd774a3e.gif)

It keeps the lines drawn in the middle of the viewport. I think drawing around the previews is a better idea. It can be drawn into a dedicated canvas item to avoid redrawing the whole grid too.

> I only see quadrant size and changing it doesn't have any visible effect.

You have to edit the TileSet resource by clicking on it:
![Peek 19-01-2021 09-59](https://user-images.githubusercontent.com/6093119/105011321-1c588400-5a3d-11eb-88c4-129bced7819f.gif)

> I just checked and Space + LMB works fine for panning too.

Ah yes. I'm ok to allow using for right click to erase but I think we should then remove right-click to pane (and eventually make the middle mouse button work again). Because otherwise people might not like not to be able to pan with right click anymore when a TileMap is selected.

2021-01-19 11:11 UTC, KoBeWi commented
> You have to edit the TileSet resource by clicking on it:

Ah right, I didn't expect this. But maybe I had wrong assumptions about the new system 🙃

This led me to discover another bug: when you change tile size in the inspector, the currently drawn tiles aren't updated until you reload the scene.

> I think we should then remove right-click to pane (and eventually make the middle mouse button work again)

But middle mouse works for me, so it's either system-specific bug or just something on your side.

IMO it would be fine if tilemap editor prevented right-click panning. (although removing it entirely isn't a bad idea, because right now we have 3 ways of panning)

2021-01-19 11:23 UTC, groud commented
> This led me to discover another bug: when you change tile size in the inspector, the currently drawn tiles aren't updated until you reload the scene.

Ah. I fixed a similar bug long ago. It seems it appeared again. I'll fix it.

> But middle mouse works for me, so it's either system-specific bug or just something on your side.

Ah I had never checked in other programs, but it seems that I have bad behaviors in Firefox too. I'll investigate that on my side then.

> IMO it would be fine if tilemap editor prevented right-click panning. (although removing it entirely isn't a bad idea, because right now we have 3 ways of panning)

Yeah, I think that for consistency it would be better. An it would allow use to use right click for more context-aware things I guess. The current situation is kind of wasting a button.

2021-01-19 17:45 UTC, groud commented
Alright, I pushed some bugfixes and it now draws the grid around the preview.

2021-02-02 21:34 UTC, KoBeWi commented
The "Continuous" checkbox is a bit confusing. From what I see, fill will by default replace all tiles of the selected ID and continuous will instead fill a confined space. IMO the confined fill should be default behavior and the checkbox could be renamed to "Replace ID" or something.

btw this is minor thing but pressing E to toggle erasing should update the viewport.

2021-02-04 15:37 UTC, groud commented
> Another bug - when you change the texture to be smaller, but have some tiles outside the texture area, you won't be able to remove them anymore from the atlas, but they are selectable for painting.

It's not really a bug, I want to keep them anyway in case you switch textures. There is a "cleanup tiles outside texture" at the bottom of the left inspector, which I'll move it to a menu I think.

> Also new TileMap seems to ignore currently selected 2D tool

Ah yes. I would like to have a better way to solve the problem though, it would be better to be able to register the TileMap tools as mutually exclusive with the main tools.

2021-02-06 22:31 UTC, KoBeWi commented
Bug: When you are in tileset edit mode, simply clicking any tile will trigger "Move a tile" action.

2021-02-06 22:33 UTC, groud commented on editor/plugins/tiles/tile_map_editor.cpp
> +			sum += 1.0;
Ah yes, thanks!

2021-02-10 17:09 UTC, groud commented
@KoBeWi most of your comment are fixed now. The only thing which is a wontfix is the preview for the rect tool, as I updated it. Now the pattern is always aligned with the first tile, but as this first tile can changes depending on the orientation of the rect, the tile can change, which would make the preview wrong in some situations. See this gif:

![Peek 10-02-2021 18-09](https://user-images.githubusercontent.com/6093119/107545046-1fbdd600-6bcb-11eb-99ee-336d8c4503de.gif)

2021-02-11 22:00 UTC, KoBeWi commented
Bug: When you select "Remove tiles in fully transparent texture regions" while there are tiles outside the texture, you are spammed with infinite errors.

2021-02-16 09:17 UTC, groud commented
@KoBeWi I fixed those now. Thanks a lot for this testing, it helps a lot. :)

2021-02-24 10:09 UTC, qarmin commented
Executing
```
TileMap.new().set_cell(Vector2(10,10),10,Vector2(10,10),10)
```
Crashes with this backtrace
```
ERROR: Condition "!tile_set.is_valid()" is true. Returning: nullptr
   at: _create_quadrant (scene/2d/tile_map.cpp:417)
scene/2d/tile_map.cpp:542:32: runtime error: member call on null pointer of type 'struct Element'
core/templates/map.h:85:11: runtime error: member access within null pointer of type 'struct Element'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /home/rafal/Pobrane/godot-tiles/bin/godot.linuxbsd.tools.64s() [0x1dcbb56] (/home/rafal/Pobrane/godot-tiles/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f3505789210] (??:0)
[3] Set<Vector2i, Comparator<Vector2i>, DefaultAllocator>::insert(Vector2i const&) (/home/rafal/Pobrane/godot-tiles/./core/templates/set.h:511)
[4] TileMap::set_cell(Vector2i const&, int, Vector2i, int) (/home/rafal/Pobrane/godot-tiles/scene/2d/tile_map.cpp:543)
```

2021-02-24 10:15 UTC, qarmin commented
```
TileSetAtlasSource.new().has_alternative_tile(Vector2i(10,10),10)
```

```
ERROR: FATAL: Condition "!_data._root" is true.
   at: operator[] (./core/templates/map.h:575)
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /home/rafal/Pobrane/godot-tiles/bin/godot.linuxbsd.tools.64s() [0x1dcbb56] (/home/rafal/Pobrane/godot-tiles/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f9b78912210] (??:0)
[3] Map<Vector2i, TileSetAtlasSource::TileAlternativesData, Comparator<Vector2i>, DefaultAllocator>::operator[](Vector2i const&) const (/home/rafal/Pobrane/godot-tiles/./core/templates/map.h:575 (discriminator 1))
[4] TileSetAtlasSource::has_alternative_tile(Vector2i, int) const (/home/rafal/Pobrane/godot-tiles/scene/resources/tile_set/tile_set.cpp:1164)
```

2021-02-24 10:31 UTC, qarmin commented
Also I have crash when passing to `add_source` function a `SphereMesh`(yes it is possible to do it with `callv`)
```
add_source
{class_name:TileSetAtlasSource, hint:16, hint_string:TileSetAtlasSource, name:atlas_source_id_override, type:21, usage:7}
21
{class_name:, hint:0, hint_string:, name:arg1, type:2, usage:7}
2
Parameters [[SphereShape3D:-9223370231005513353], -35]
scene/resources/tile_set/tile_set.cpp:1058:33: runtime error: member access within null pointer of type 'struct TileSetSource'
scene/resources/tile_set/tile_set.cpp:1058:33: runtime error: member call on null pointer of type 'struct Object'
scene/resources/tile_set/tile_set.cpp:1058:33: runtime error: member access within null pointer of type 'struct Object'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /home/rafal/Pobrane/godot-tiles/bin/godot.linuxbsd.tools.64s() [0x1dcbb56] (/home/rafal/Pobrane/godot-tiles/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f8a05e75210] (??:0)
[3] TileSet::add_source(Ref<TileSetAtlasSource>, int) (/home/rafal/Pobrane/godot-tiles/scene/resources/tile_set/tile_set.cpp:1058 (discriminator 1))
```

2021-02-24 12:15 UTC, groud commented
Thanks a lot @qarmin, I've solved all of those on my local copy :)

2021-04-12 12:38 UTC, YeldhamDev commented
About the tab position, while it's better as to save unused space, they look disjointed as a result:
https://godotengine.org/storage/app/uploads/public/607/05f/ac6/60705fac69254963527894.png

Maybe it would be better to have it look like some other tab-like areas in the editor:
![Screenshot at 2021-04-12 09-34-39](https://user-images.githubusercontent.com/30739239/114395087-83dd2600-9b8b-11eb-83df-3cc9bb8c8685.png)

2021-04-12 12:39 UTC, YeldhamDev requested changes

2021-04-12 12:39 UTC, YeldhamDev commented on editor/plugins/tiles/tile_map_editor.cpp
> +	random_tile_checkbox->set_text(TTR("Place random tile"));
```suggestion
	random_tile_checkbox->set_text(TTR("Place Random Tile"));
```

2021-04-12 12:45 UTC, groud commented
> About the tab position, while it's better as to save unused space, they look disjointed as a result:
https://godotengine.org/storage/app/uploads/public/607/05f/ac6/60705fac69254963527894.png

Yeah, it probably needs a background. I think it's the better solution I have for now. Maybe it is possible to add a bottom separation line to make it more obvious it changes the bottom part, but I don't know I could I do it.

> Maybe it would be better to have it look like some other tab-like areas in the editor:

To be honest I don't like those much, they clearly don't look like tabs. In a toolbar it would be even worse I believe.

2021-04-23 15:19 UTC, qarmin commented
CI fails with this message 
```
TileSet.get_terrain_color
Parameters [100, 100]
ERROR: FATAL: Index p_index = 100 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:157)
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] bin/godot.linuxbsd.tools.64s() [0x1e857d8] (/home/runner/work/godot/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f270103d210] (??:0)
[3] CowData<TileSet::TerrainSet>::get(int) const (/home/runner/work/godot/godot/./core/templates/cowdata.h:157 (discriminator 7))
[4] Vector<TileSet::TerrainSet>::operator[](int) const (/home/runner/work/godot/godot/./core/templates/vector.h:89)
[5] TileSet::get_terrain_color(int, int) const (/home/runner/work/godot/godot/scene/resources/tile_set/tile_set.cpp:1757 (discriminator 2))
```
So that means that executing 
```
TileSet.new().get_terrain_color(100,100)
```
should crash Godot

2021-04-28 00:11 UTC, KoBeWi commented
When working with multiple layered TileMaps, it occurred to me that it would be useful if they retained the selected tile when switching between them when they have the same TileSet. (I'm fairly sure it used to be like that few commits ago...)

2021-05-06 15:33 UTC, akien-mga commented on editor/editor_node.cpp
> +// #include "editor/plugins/tile_set_editor_plugin.h"
These can be removed.

2021-05-06 15:33 UTC, akien-mga commented on editor/icons/EditAddRemove.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Editor icons should be optimized IIRC. https://docs.godotengine.org/en/latest/development/editor/creating_icons.html#icon-optimization

2021-05-06 15:33 UTC, akien-mga commented on editor/plugins/tiles/tile_atlas_view.h
> +	int source_id;
Make sure to initialize members in the header.

2021-05-06 15:33 UTC, akien-mga commented on editor/plugins/tiles/tile_data_editors.h
> +*/
Remove.

2021-05-06 15:33 UTC, akien-mga commented on editor/plugins/tiles/tile_data_editors.h
> +#include "scene/resources/tile_set/tile_set.h"
Duplicate.

2021-05-06 15:33 UTC, akien-mga commented on editor/plugins/tiles/tile_map_editor.h
> +#include "core/typedefs.h"
Usually we group all includes together (maybe apart from the relative one).

2021-05-06 15:33 UTC, akien-mga commented on editor/plugins/tiles/tile_set_atlas_source_editor.h
> +		int source_id;
Init.

2021-05-06 15:33 UTC, akien-mga commented on editor/plugins/tiles/tile_set_atlas_source_editor.h
> +	String selected_property = "";
`String` is default initialized to `""` already.

2021-05-06 15:33 UTC, akien-mga commented on editor/plugins/tiles/tile_set_atlas_source_editor.h
> +	int menu_option_alternative;
Init.

2021-05-07 02:02 UTC, YeldhamDev commented
Alright, guess it's my time to review this beast of a PR. Fair warning: I took a glance in the current conversation, but since there's so much, I may have missed something, so if I ended up repeating stuff that was already said, I'm sorry!

* First, there's no need for those two warnings to appear at the same time. If the first is shown, hide the second:
![Screenshot at 2021-05-06 22-24-32](https://user-images.githubusercontent.com/30739239/117385736-26f83580-aed5-11eb-95af-82294f9508c3.png)

* The TileSet editor toggle is kinda missable, maybe it would be better to add text to the button itself instead of a tooltip? That would allow to make it non-flat, which would further mark its presence:
![Screenshot at 2021-05-06 22-30-12](https://user-images.githubusercontent.com/30739239/117385809-498a4e80-aed5-11eb-8d5c-610c3dfe4866.png)

* The tile selector here could use a panel as a background:
![Screenshot at 2021-05-06 22-27-15](https://user-images.githubusercontent.com/30739239/117386874-31b3ca00-aed7-11eb-9d8b-d35aa1b81ef4.png)

* Couldn't those two Inspector sections be unified into one? As there is a way to create sections within a single instance:
![Screenshot at 2021-05-06 22-28-21](https://user-images.githubusercontent.com/30739239/117386792-05984900-aed7-11eb-85ed-b1b74df07298.png) ![Screenshot at 2021-05-06 22-28-44](https://user-images.githubusercontent.com/30739239/117386797-07faa300-aed7-11eb-897d-f374e086da2b.png)

@groud Now, I would love to analyze it further, but I'm stuck in the "TileSet has no source configured" message, even though I added an image in the TileSet editor. Maybe I'm missing something, maybe I'm just stupid, either way I could use some help.

Also, I stumbled into this bug, likely unrelated with the PR itself:
![Screenshot at 2021-05-06 23-00-50](https://user-images.githubusercontent.com/30739239/117387273-1ac1a780-aed8-11eb-81fc-675dcd03ba43.png)

2021-05-07 08:06 UTC, groud commented
> First, there's no need for those two warnings to appear at the same time. If the first is shown, hide the second:

Ah yeah, recent changes caused this. I'll do that.

> The TileSet editor toggle is kinda missable, maybe it would be better to add text to the button itself instead of a tooltip? That would allow to make it non-flat, which would further mark its presence:

Well, I am not strictly against it, but I don't want to take more horizontal space than needed. This button is in the toolbar, which tends to restrict the editor's horizontal available space considering the many item it already has. If we go with a wider button, I'd rather move it elsewhere, but not sure where.

> The tile selector here could use a panel as a background:

I'll try that and post a screenshot.

> Couldn't those two Inspector sections be unified into one? As there is a way to create sections within a single instance:

No I don't want to. Those are very different objects. One edits the whole atlas while the other edit selected tiles.
I think that, knowing that the main inspector use those categories for inheritance, it would be quite misleading.

> @groud Now, I would love to analyze it further, but I'm stuck in the "TileSet has no source configured" message, even though I added an image in the TileSet editor. Maybe I'm missing something, maybe I'm just stupid, either way I could use some help.

Not sure what happen, it seems to work fine for me.

> Also, I stumbled into this bug, likely unrelated with the PR itself:

I've never had this bug, weird. I guess we might have to investigate this later on and see how to reproduce.

2021-05-07 19:37 UTC, groud commented
Closing as superseeded by #48535

2021-05-07 19:37 UTC, closed without merging