Fix the tween null check
godotengine/godot pull request #45438
Opened 2021-01-25 05:15 UTC by Norrox

well this fixes the null check for tween for 4.0, the 3.2 code looks a little different so i dont know how to push both to the same master as this is my first time playing around with this :)

fixes this #45399 error for version 4

2021-01-25 05:16 UTC, Norrox commented
@Calinou is this ok? ;D

2021-01-25 13:42 UTC, Calinou commented
> @Calinou is this ok? ;D

I don't merge code pull requests on the main repository; you'll have to wait for Akien to take a look.

2021-01-25 13:43 UTC, Calinou requested changes, later dismissed
I think it'd be good to add a descriptive message to help the user troubleshoot the issue:

2021-01-25 13:43 UTC, Calinou commented on scene/animation/tween.cpp
> +	ERR_FAIL_COND(p_object == nullptr);
```suggestion
	ERR_FAIL_COND_MSG(p_object == nullptr, "The node to tween is null. Was it removed before tweening?");
```

2021-01-25 13:43 UTC, Calinou commented on scene/animation/tween.cpp
> +	ERR_FAIL_COND(p_object == nullptr);
```suggestion
	ERR_FAIL_COND_MSG(p_object == nullptr, "The node to tween is null. Was it removed before tweening?");
```

2021-02-24 12:38 UTC, akien-mga commented
I force pushed a rebase to squash the commits into one and clarify the commit message.

2021-02-24 12:38 UTC, akien-mga approved these changes

2021-02-24 14:09 UTC, merged

2021-02-24 14:09 UTC, akien-mga commented
Thanks!

2021-02-25 13:30 UTC, akien-mga commented
Cherry-picked for 3.2.4.