Use real_t in non-physics 2D nodes
godotengine/godot pull request #45571
Opened 2021-01-30 05:50 UTC by aaronfranke

This is similar to other recent `real_t` PRs I've made, but this PR specifically focuses on 2D nodes.

All code related to time was intentionally left unchanged. Code that works with time should be `double`, not `real_t`, but that would change behavior, so I think it's worth doing in a separate PR.

2021-03-08 17:15 UTC, KoBeWi commented on scene/2d/tile_map.h
> +	real_t fp_adjust = 0.00001;
This variable is no longer necessary after you replaced the only usage with `CMP_EPSILON`.

Although I wouldn't touch TileMap code at all, considering the coming rewrite.

2021-03-19 14:38 UTC, KoBeWi requested changes
As I mentioned in my last comment, it would be better if the TileMap changes were removed. This PR is only relevant for 4.0 and TileMap in 4.0 is getting a full rewrite, so doing changes in other PRs is rather useless. Unless you don't mind waiting and rebasing until the rework is merged.

2021-03-19 19:12 UTC, KoBeWi approved these changes

2021-03-22 23:10 UTC, merged

2021-03-22 23:10 UTC, akien-mga commented
Thanks!