Fix TextEdit autoscroll with wrapped lines
godotengine/godot pull request #45881
Opened 2021-02-11 02:09 UTC by pouleyKetchoupp

Index to find the last line wrap index was off by one, which prevented to trigger autoscroll the first time a line was wrapped.

Fixes #41962

2021-02-11 15:11 UTC, KoBeWi approved these changes

2021-02-11 19:44 UTC, Paulb23 requested changes
These seem to be returning the correct values for me? But I would guess the bug is somewhere in `adjust_viewport_to_cursor`.

2021-02-12 00:20 UTC, pouleyKetchoupp commented
@Paulb23 Here's the project I'm using for tests:
[textedit-tests-4.0.zip](https://github.com/godotengine/godot/files/5969022/textedit-tests-4.0.zip)

As an example, here's how to reproduce the issue:
Start the scene, set the cursor after the last 's' in the TextEdit control and press 'a'.

If you set a breakpoint in `adjust_viewport_to_cursor`, you can see `get_last_visible_line_wrap_index` returns 2 instead of 1, which prevents the scrolling from happening (you need to scroll when the last line is only partially visible).

From what I understand, this `get_visible_rows() + 1` in the last visible line methods allows to return any partially visible line as the last visible line. So an alternative could be to change `adjust_viewport_to_cursor` with `cur_line >= last_vis_line` and `cur_wrap >= last_vis_wrap`.

In this case, `_scroll_lines_up` would need the same change, as it has the same issue. You can test it in the same test project, by opening the script called `new_script.gd`, placing the cursor all the way down and scrolling up using ctrl + up. At some point the cursor is almost outside of the screen at the bottom, and this is fixed with the current PR.

If this makes sense for you, let me know which version you prefer  (remove `+ 1` or check `>=`), I don't have a strong opinion about it.

2021-02-12 17:56 UTC, Paulb23 commented
Hmm, that makes scene, guess it depends on what's classed as a visible line.

I made it slighting bigger and changed it to the below with only the first line wrapped, `get_last_visible_line` returns 1 where it looks like it should be 2:
![image](https://user-images.githubusercontent.com/6584330/107802133-def3c780-6d58-11eb-8ac0-bc5ea55bc572.png)

Making then both wrapped makes `get_visible_rows_offset` return 0 where it looks like should be 1:
![image](https://user-images.githubusercontent.com/6584330/107802415-34c86f80-6d59-11eb-8a8f-d5e654c40012.png)

Though I would guess that's because the entire line height is not visible, even though the chars are so it's not counting it (or another bug!). Kinda temped to rename it or create a new method `get_last_full_visible_line` so it clearer that partially visible lines are not included. Not sure what you think?

2021-02-12 20:47 UTC, pouleyKetchoupp commented
It looks like it's working fine when not counting partially visible lines. And from what I see it's always consistent with the scrollbar state so it should be ok. You have a point on the method name to make things clear, so I've just renamed both of them.

Things generally look more consistent to me now, but let me know if you spot any case where the behavior looks wrong and I'll investigate.

2021-02-13 15:14 UTC, Paulb23 approved these changes
LGTM

2021-02-13 16:41 UTC, merged

2021-02-13 16:41 UTC, akien-mga commented
Thanks!

2021-02-14 12:57 UTC, akien-mga commented
Cherry-picked for 3.2.4.