Allow to use a Reference during NOTIFICATION_PREDELETE
godotengine/godot pull request #45960
Opened 2021-02-13 15:15 UTC by trollodel

Fixes #31166

The issue happens because the refcount can't be incremented during the predelete, so objects that require to increment it (e.g. Variant) will fail.
This PR workaround the issue by setting the refcount to 1 before calling notification, so the reference seems valid during the predelete.

2021-02-13 15:50 UTC, YeldhamDev requested changes

2021-02-13 15:50 UTC, YeldhamDev commented on doc/classes/Object.xml
> +            [b]Warning:[/b] Don't keep a reference of self when handling this notification. If self is [Reference], keeping a reference of it causes a memory leak and, in some situations, a crash.
This needs to be indented further, and using tabs.

2021-02-13 17:27 UTC, YeldhamDev approved these changes

2021-02-13 17:36 UTC, reduz commented
This fix is not thread-safe, unfortunately, which is the whole point of the reference counter being done the way it is. Also, these types of languages don't let you access the destructor for a reason (it's easy to mess up). The idea was to simply hide this notification from GDScript, so I am not sure what's the status of that right now.

2021-02-13 17:58 UTC, trollodel commented
> This fix is not thread-safe

I was worried about that too.

> these types of languages don't let you access the destructor for a reason

Aren't there similar problems with GDNative? If I store away a Reference or try to use Variant during NOTIFICATION_PREDELETE, it will fail.

2021-02-13 18:20 UTC, reduz commented
> Aren't there similar problems with GDNative? If I store away a Reference or try to use Variant during NOTIFICATION_PREDELETE, it will fail.

I don't think so, GDNative is purely pointers, so it does not use a reference for self access. I suppose if you call a function with it, it will fail, but at least it will throw an error.

2021-02-13 18:41 UTC, trollodel commented
> I suppose if you call a function with it, it will fail, but at least it will throw an error.

If it is fine, a dummy object can a possible solution, so I can still use the script instance for cleanup. 
After all, after the handling of NOTIFICATION_PREDELETE, the object is supposed to be freed, so storing the dummy object becomes useless.

... Or there is always the "free it anyway" solution :)

2021-02-14 04:37 UTC, RandomShaper commented
I've made a draft of a possible way to achieve the same, potentially free of the issues this PR has: https://github.com/godotengine/godot/pull/45993

Please consider it's draft quality when assessing it.

2021-02-15 21:27 UTC, trollodel commented
I updated the fix, so it's a bit more thread-safe.

@RandomShaper I've seen and tested your PR, and It seems like a good fix (It behaves a bit better than mine, see below).
I test this and #45993 (with and without `use_asan`) by storing a reference outside the object during the predelete, then accessing it.
Both the PRs can crash when freeing the object where the reference is stored because they access to a freed object.

2021-02-16 00:04 UTC, RandomShaper commented
That's expected. I don't think we can do any better than allowing use of the object during the predelete notification. At that point it's already too late to save it from dying. Well, my draft could allow to cancel the deletion, but the object wouldn't be a `Refetence` anymore and allowing script variables to point to an object in such a weird state would be, well, too weird.

Thank you for testing it.

2021-08-30 22:46 UTC, reduz commented
I have to say I am not happy with this or #45993, I think it is better that GDScript simply never knows about this because there is always potential to mess up. This behavior is expected in all similar scripting languages.

2022-07-01 20:34 UTC, trollodel commented
This was one of my first PR and, while I learned a lot doing this, I don't think I have the knowledge now to have this merged, so closing.
However, I still believe GDScript and other non-gc languages can use that notification if enough safety is provided during the notification handling.

Also, #6784 #31166 (and another one I forgot) talks about the same issue.

2022-07-01 20:34 UTC, closed without merging