Fix out of bounds access into empty image data
godotengine/godot pull request #46249
Opened 2021-02-20 13:41 UTC by nmrkr

Fixes #46189.

This is the same as #46247 but for 3.2.

2021-02-20 16:22 UTC, hpvb approved these changes
LGTM, thanks!

2021-02-20 16:25 UTC, hpvb requested changes
XChangeProperty probably shouldn't be called if we hit this condition

2021-02-20 16:28 UTC, pouleyKetchoupp commented
@hpvb This is being discussed in the master version of this PR: #46247

2022-07-02 23:09 UTC, akien-mga commented
Closing the `3.x` version of the PR to reduce backlog, as I can cherry-pick the fix from #46247 if/when it's merged (the file structure changed but it's easy enough to solve the merge conflicts while cherry-picking).

2022-07-02 23:09 UTC, closed without merging