Prevent 'Change Type' on nodes from a foreign scene
godotengine/godot pull request #46327
Opened 2021-02-22 19:26 UTC by hilfazer

Fixes #45912.

2021-02-22 19:38 UTC, KoBeWi commented
The option should also be removed from the context menu when it's unavailable (`break` inside `menu_option` is mostly for shortcuts).

2021-02-22 20:15 UTC, hilfazer commented
There's a number of options in the context menu that can't be used on foreign nodes, e.g. Rename, Move Up. Should they also be removed (not neccesarily in this PR)?

2021-02-22 21:25 UTC, KoBeWi commented
> Should they also be removed (not neccesarily in this PR)?

Yep, the menu got few cleanups in the past, but still not everything is handled as it should.

2021-02-25 23:59 UTC, KoBeWi requested changes

2021-02-25 23:59 UTC, KoBeWi commented on editor/scene_tree_dock.cpp
> +			menu->add_icon_shortcut(get_theme_icon("Reload", "EditorIcons"), ED_GET_SHORTCUT("scene_tree/change_node_type"), TOOL_REPLACE);
Wrap the code under condition in brackets even if it's one line (as per Godot's code style guide).

2021-02-26 13:26 UTC, KoBeWi approved these changes

2021-02-26 13:37 UTC, akien-mga approved these changes

2021-02-26 13:37 UTC, merged

2021-02-26 13:37 UTC, akien-mga commented
Thanks!

2021-02-26 14:26 UTC, akien-mga commented
Cherry-picked for 3.2.4.