Documenation Contribution
godotengine/godot pull request #46398
Opened 2021-02-24 21:11 UTC by iatenine

Added description to GirdMap's get_bake_meshes() method

2021-02-24 21:18 UTC, iatenine reviewed
Failed checks likely resulted in attempt to link to Transform and MeshArray pages within description

2021-02-24 21:41 UTC, YeldhamDev requested changes

2021-02-24 21:41 UTC, YeldhamDev commented on modules/gridmap/doc_classes/GridMap.xml
> +				Returns an array of [MeshArray] and [Transform] references of all bake meshes that exist within the current GridMap.
It should be `[ArrayMesh]es` here.

2021-02-24 22:19 UTC, iatenine commented
Made requested change

2021-02-24 22:39 UTC, YeldhamDev approved these changes

2021-02-25 14:43 UTC, akien-mga commented
Force pushed a rebase to squash the two commits into one.

2021-02-25 14:43 UTC, akien-mga approved these changes

2021-02-25 14:57 UTC, merged

2021-02-25 14:57 UTC, akien-mga commented
Thanks!

2021-02-25 21:37 UTC, akien-mga commented
Cherry-picked for 3.2.4.