fix translation update in Window & AcceptDialog/ConfirmationDialog (Fix 39320 &  39258)
godotengine/godot pull request #46735
Opened 2021-03-06 20:08 UTC by fabriceci

- - Fix #39320 As @akien-mga explained well in the issue, Dialogs did not intercept the notification `NOTIFICATION TRANSLATION CHANGED`:

https://user-images.githubusercontent.com/6397893/110219413-597ab780-7ebf-11eb-810a-0b2c92bb5565.mp4

- Fix #39258 where title variable was used as translation instead of the translation key.

https://user-images.githubusercontent.com/6397893/110219409-4ec02280-7ebf-11eb-87e2-3cfe065a348a.mp4

2021-03-10 22:56 UTC, KoBeWi approved these changes
> However, I don't understand well the difference between _sub_windows_update and child_controls_changed as the last one end by calling _sub_windows_update. Both works, but I'm not sure which is the best.

I suppose it doesn't matter. The latter does more under the hood, so it might be more correct at the cost of performance, but you don't change translation very often anyways.

I tested the changes both in the editor and exported project and all seem to work fine.

2021-03-12 08:45 UTC, akien-mga commented
This likely breaks editor translations. Try to run `make update` and `make merge` in `editor/translations/` after this PR and it will likely remove all translations for those strings. `RTR()` is what is used to extract strings to translate in the template.

2021-03-12 10:53 UTC, KoBeWi commented
Maybe we could add a new macro that fetches translation, but doesn't translate?

2021-03-12 12:52 UTC, KoBeWi commented
Seems like this is what TTRC does, but judging from the comment, it's not the intended use.

2021-03-12 13:57 UTC, KoBeWi requested changes
Actually TTRC seems fine. So replace the removed RTRs with TTRCs.

2021-03-12 17:01 UTC, fabriceci commented
@akien-mga I was unaware of this behaviour.

@KoBeWi thanks for the review and providing me a solution! Changes are done.

By curiosity, how I can see what functions are used for generating translations? (For example, is the `tr()` function is used too?).

2021-03-12 22:49 UTC, KoBeWi commented
> By curiosity, how I can see what functions are used for generating translations? (For example, is the tr() function is used too?).

They are defined here:
https://github.com/godotengine/godot/blob/bf309b8a139732387229228f86939516c7dc64d4/editor/translations/extract.py#L186

2021-03-12 22:50 UTC, KoBeWi approved these changes

2021-03-22 23:01 UTC, akien-mga approved these changes

2021-03-22 23:03 UTC, merged

2021-03-22 23:03 UTC, akien-mga commented
Thanks!

2021-06-03 10:29 UTC, akien-mga commented
This could be useful to backport to the `3.x` branch, but it would need a dedicated PR and testing as `Window` is new in `master`, for `3.x` it would likely need changes in the `Dialog` implementation itself.