Add a Note in Project Settings for the Default Environment being Editor Only
godotengine/godot pull request #46789
Opened 2021-03-08 12:13 UTC by sps1112

Update Documentation as listed in #46478
Added a Note in Project Settings that the Default Environement is Editor-only. This will not be present in when running the project. A fix can be adding a `World Environment` Node with an `Environment` Resource.

2021-03-08 15:09 UTC, Calinou requested changes

2021-03-08 15:09 UTC, Calinou commented on doc/classes/ProjectSettings.xml
> +			[b]Note:[/b] The default environment is editor-only and will not be present when running the project. This is fixed by adding a [code]World Environment[/code] Node and adding an [code]Environment[
Use node reference links:

```suggestion
			[b]Note:[/b] The default environment is editor-only and will not be present when running the project. This is fixed by adding a [WorldEnvironment] node and loading the saved [Environment] resource in its [member WorldEnvironment.environment] property.
```

2021-03-08 15:56 UTC, sps1112 commented on doc/classes/ProjectSettings.xml
> +			[b]Note:[/b] The default environment is editor-only and will not be present when running the project. This is fixed by adding a [code]World Environment[/code] Node and adding an [code]Environment[
Done

2021-03-08 15:59 UTC, clayjohn commented
The default environment resource is actually no longer  used. Instead there is a "preview sun" and "preview sky" in the editor toolbar. See 
https://github.com/godotengine/godot-proposals/issues/1599 which was implemented recently.

We should work to remove all references to default environment.

2021-03-10 07:54 UTC, sps1112 commented
Could you please tell how i should i go along removing the said references?

2021-11-03 17:09 UTC, Calinou commented
Superseded by https://github.com/godotengine/godot/pull/52916. Thanks for the contribution nonetheless :slightly_smiling_face:

2021-11-03 17:09 UTC, closed without merging