Patch 2
godotengine/godot pull request #46870
Opened 2021-03-10 14:39 UTC by JonatasOrsini

Spatial Shader fix

godot/drivers/gles3/shaders/scene.glsl
Changed #elif for Spatial Shader to #else

godot/drivers/gles2/shaders/scene.glsl
Changed #elif for Spatial Shader to #else

2021-03-10 14:48 UTC, Calinou requested changes

2021-03-10 16:35 UTC, clayjohn commented
It looks like you lost the changes to GLES3 in the rebase!

2021-03-10 16:41 UTC, JonatasOrsini commented
I'm new to GitHub, trying to learn what I did wrong.
What should I do?
Maybe disregard my entries.

2021-03-11 01:32 UTC, BastiaanOlij commented
You need to squash the two commits together and indeed seems you've lost the changes to the GLES3 shaders.

As for the solution, yeah if not defining a shader mode should make `SPECULAR_SCHLICK_GGX` the default behavior an `#else` makes far more sense here.

2021-03-11 01:38 UTC, BastiaanOlij commented
> I'm new to GitHub, trying to learn what I did wrong.

Best advise here is to join either the Discord or Godot chat server. It is much easier to help someone in real time then in PRs. 
https://godotengine.org/community

A couple of quick tips:
- read through the PR workflow documentation: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html
- set up a text editor to edit your commit hashes: https://git-scm.com/book/en/v2/Appendix-C%3A-Git-Commands-Setup-and-Config
- squash your commits: https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

2021-03-11 22:47 UTC, closed without merging

2021-03-12 08:05 UTC, akien-mga commented
The contributor has deleted their Godot repository, but see #46838 for further discussion, I'm not convinced that this was a good fix.