Make Animation's SceneTreeDialog filter nodes properly
godotengine/godot pull request #46938
Opened 2021-03-12 15:47 UTC by dreamsComeTrue

Actually that's a "bug" which bothers me since many months already.
During work on my game I am creating a lot animations within AnimationPlayer.
What's not working as intended, is the first dialog, when selecting Node to animate - it has a "filter" input, but:
- it is NOT focused immediately after dialog pops up
- it doesn't accept Enter key events
- it doesn't allow to use cursor keys (up,down,pgup,pgdown) to move selection on the tree
- it does filter the list of nodes, but doesn't select them (according to partial name match)

Fun fact is that, after Node is picked, then second screen, with tree of properties/methods works properly - it immediately allows to filter, use arrow keys, and pick-up properties/methods, without using mouse at all.

This PR fixes the problem, and makes first dialog work similar to the second one, e.g - as it should from the very beginning :)

OLD behavior:

![old](https://user-images.githubusercontent.com/1110337/110963391-4e59d880-8352-11eb-894b-ab49061e642f.gif)

NEW behavior:

![new](https://user-images.githubusercontent.com/1110337/110963422-5580e680-8352-11eb-8c40-4f41952d2fd0.gif)

2021-03-19 15:14 UTC, KoBeWi requested changes

2021-03-19 15:14 UTC, KoBeWi commented on editor/animation_track_editor.cpp
> +				print_line(candidate->get_name());
Delet this.

(`print_line`)

2021-03-19 15:14 UTC, KoBeWi commented on editor/scene_tree_editor.h
> +	LineEdit *get_filter() { return filter; }
This could get a less ambiguous name (`get_filter()`  sounds like something that could return String), like `get_filter_line_edit()`.

2021-03-19 21:59 UTC, KoBeWi approved these changes

2021-03-20 23:16 UTC, merged

2021-03-20 23:16 UTC, akien-mga commented
Thanks!