Allow Navigation to be more flexible
godotengine/godot pull request #47024
Opened 2021-03-15 12:58 UTC by groud

In the previous implementation, you needed two edges to be almost exactly similar for two regions to be connected (same length, close to each other and almost parallel. Now, the conditions are similar but two edges of different length can be connected too. This makes navigation a lot more flexible.

![Peek 15-03-2021 13-56](https://user-images.githubusercontent.com/6093119/111156679-4f7b4780-8596-11eb-97ce-d3b432dd88b2.gif)

I also implemented some changes:
- Fixed a small bug where some places were not reachable in a polygon when calling map_get_path (the algorithm did not go over all of a polygon's faces).
- Navigation polygon debug display now shows different polygons with a slight variation of color. Edges are usually the places where the path finding algorithm can have issues, so it's important to be able to see where they are.
- Display doors connecting several regions, with the circles being the connection margin to connect two regions.

2021-03-15 13:13 UTC, Zireael07 commented
What happens if the two polys overlap slightly? In the past, that would break navigation, too.

Also, is this for 2D only or also for 3D?

2021-03-15 13:31 UTC, AndreaCatania requested changes
This PR doesn't have the 3D editor, right?

2021-03-15 13:31 UTC, AndreaCatania commented on modules/gdnavigation/gd_navigation_server.cpp
> +		int map_index = active_maps.find(map);
Minor, this could be `const`.

Please check if it exists before:
```
if(map_index != -1) {
or
ERR_FAIL_COND
```

2021-03-15 13:31 UTC, AndreaCatania commented on modules/gdnavigation/gd_navigation_server.cpp
> +		uint32_t new_map_update_id = active_maps[i]->get_map_update_id();
Minor, this could be `const`.

2021-03-15 13:31 UTC, AndreaCatania commented on modules/gdnavigation/gd_navigation_server.h
> +	Vector<uint32_t> active_maps_update_id;
Now that we have `LocalVector` I think it's much better use it, `Vector` is good when you need to pass it around.

(Vector and LocalVector API are the same, you can just change the class.)

2021-03-15 13:31 UTC, AndreaCatania commented on modules/gdnavigation/nav_map.cpp
> +			Face3 face(p1, p2, p3);
Minor, it's nice if we make this `const` too.

2021-03-15 13:31 UTC, AndreaCatania commented on modules/gdnavigation/nav_utils.h
> +	uint32_t back_navigation_edge = -1;
This is an `uint32_t` try to use `UINT32_MAX` instead of `-1`, or use an `int` or an `int64`. Otherwise it's an undefined behavior.

2021-03-15 14:24 UTC, drcucaracha commented
Hello, could you give my idea of an improvement if it is not implemented? the idea would be to have a slider in the inspector when creating a navmesh and that will be used to extrude the nacmesh in to prevent it from always navigating overboard and make it look like a more natural movement

2021-03-15 14:36 UTC, groud commented
> What happens if the two polys (edges) overlap slightly? In the past, that would break navigation, too. Also, is this for 2D only or also for 3D?

I don't know, it seems to work fine. Overlapping regions stil does not work, but if it's close enough to create a pathway it seems to work.

It's for both 3D and 2D, behind the scene the 2D servers calls the 3D version.

> This PR doesn't have the 3D editor, right?

Nope, I am not familiar with the 3D editor enough. And without a working test project it's hard to test.

> Hello, could you give my idea of an improvement if it is not implemented? the idea would be to have a slider in the inspector when creating a navmesh and that will be used to extrude the nacmesh in to prevent it from always navigating overboard and make it look like a more natural movement

Sorry that's out of the scope of this PR. You may open a proposal in the godot-proposal repository if you want.
Note that I don't plan to work on this  anymore for now, I have to go back to working on the TileMap/TileSet editors.

2021-03-15 15:14 UTC, groud commented
@AndreaCatania I made your requested changes, thanks!

2021-03-16 20:34 UTC, Cykyrios commented
Not sure how feasible it is, but would computing the boolean difference/intersection between overlapping regions help with said overlap breaking navigation? That way you could remove the difference from one region, or have the intersection as a separate region, and the edges would line up cleanly.

2021-03-17 07:25 UTC, AndreaCatania approved these changes
Good job!

2021-03-17 08:18 UTC, merged

2021-03-17 08:19 UTC, akien-mga commented
Thanks!