Better error messages when parsing CSV translation files.
godotengine/godot pull request #47169
Opened 2021-03-19 19:05 UTC by AndyBarcia

I think that this completely solves #46682 

If you forget to add a closing " in the CSV file now there is a warning. And if there is an incorrect number of lang values, it shows a helpful error instead of silently continuing. 

Note: should the closing " thing give an error instead of a warning? I think that it should, but then I suppose that ResourceImporterCSVTranslation::import should also return an error, and that would mean that there would be two errors messages. I don't know if that's more confusing.

2021-03-20 02:05 UTC, Calinou requested changes, later dismissed

2021-03-20 02:05 UTC, Calinou commented on editor/import/resource_importer_csv_translation.cpp
> +			ERR_FAIL_COND_V_MSG(line.size() != locales.size() + 1, ERR_PARSE_ERROR, vformat("Error importing CSV translation: expected %d lang(s), but '%s' key has %d lang(s).", locales.size(), key, line.size
```suggestion
			ERR_FAIL_COND_V_MSG(line.size() != locales.size() + 1, ERR_PARSE_ERROR, vformat("Error importing CSV translation: expected %d locale(s), but the '%s' key has %d locale(s).", locales.size(), key, line.size() - 1));
```

2021-03-20 02:06 UTC, Calinou commented on core/os/file_access.cpp
> +		WARN_PRINT("Warning: reached end of file before closing '\"' in CSV file '" + get_path() + "'.");
For consistency with the other addition, use `vformat()` here too:

```suggestion
		WARN_PRINT(vformat("Warning: reached end of file before closing '\"' in CSV file '"%s"'.", get_path()));
```

2023-02-11 21:09 UTC, akien-mga approved these changes

2023-02-11 21:10 UTC, akien-mga commented
Needs a rebase, but should be fine to merge then (after the 4.0 release, as we're already at RC stage so not taking any risks for non critical fixes).

2023-06-16 15:12 UTC, akien-mga commented
Rebased myself, should be good now.

2023-06-19 09:16 UTC, akien-mga commented
I fixed the unit test suite to separate generic FileAccess CSV testing from using CSV as translation.
And added more CSV translation tests while at it.

2023-06-19 11:35 UTC, merged

2023-06-19 11:36 UTC, akien-mga commented
Thanks!