Don't add degenerate triangles to trimesh shape
godotengine/godot pull request #47214
Opened 2021-03-21 06:49 UTC by e344fde6bf

Degenerate triangles can cause errors in collision detection as they
have no normal.

2021-03-21 10:17 UTC, Calinou commented
@e344fde6bf Do you have a minimal reproduction project for testing an issue that might occur with degenerate triangles?

2021-03-21 11:19 UTC, e344fde6bf commented
Here's a minimal case where the triangle is actually a line:

[degenerate-triangles.zip](https://github.com/godotengine/godot/files/6177266/degenerate-triangles.zip)

https://user-images.githubusercontent.com/79001820/111902680-5b7d7280-8a8a-11eb-87c6-f0e12b79097c.mp4

Here's a more realistic case were I first found it happening:


https://user-images.githubusercontent.com/79001820/111902737-9089c500-8a8a-11eb-8524-4dea6147d2e4.mp4

This issue seems to mainly effect GodotPhysics.  Bullet probably has code to handle them internally.

2021-08-20 16:53 UTC, pouleyKetchoupp requested changes
It seems like a good idea!

I would just add an extra check in Godot Physics as well, to possibly catch cases that didn't go through the `create_trimesh_shape` process.

It could be a similar check here:
https://github.com/godotengine/godot/blob/78bf06ea415873d336f7869edb632968b1be6bed/servers/physics_3d/shape_3d_sw.cpp#L1499

But instead of silently removing the face (which could cause discrepancies with face indices), I would go with a debug-only check that logs an error.

Maybe something like:
```
#ifdef DEBUG_ENABLED
if (unlikely(face.is_degenerate())) {
    ERR_PRINT_ONCE("Found degenerated face(s) in concave shape data, this will cause collision issues.");
}
#endif
```

2022-03-26 13:27 UTC, akien-mga commented
@e344fde6bf Are you interested in updating this PR further following @pouleyKetchoupp's feedback above?

2023-02-12 20:18 UTC, YuriSizov commented
Superseded by https://github.com/godotengine/godot/pull/72868. Thanks for your contribution nonetheless!

2023-02-12 20:18 UTC, closed without merging