Use Bullet's convex hull computer in place of QuickHull when available.
godotengine/godot pull request #47332
Opened 2021-03-24 17:58 UTC by mortarroad

Fixes #45946, maybe more.
Supersedes #47307.

Now against master.
Uses QuickHull if vhacd is unavailable.

2021-03-24 18:35 UTC, pouleyKetchoupp requested changes
Looks great apart from a few details with coding style.

2021-03-24 19:39 UTC, pouleyKetchoupp approved these changes

2021-04-06 15:55 UTC, pouleyKetchoupp commented
@mortarroad After discussing this PR again with @reduz, it seems the cleanest way to make this change would be to extract the Bullet convex hull code from vhacd so we can get rid of the dependency to vhacd and actually get rid of QuickHull.

This will take a few more steps:
- Extract the Bullet convex hull code from vhacd into core/math (vhacd will still keep the copy it has right now)
- This convex hull implementation needs to be converted to Godot coding style and math types
- QuickHull will be removed in favor of this implementation like you did before

I know it's a lot of refactoring, so let me know whether you're interested to do the extra work and finalize this change. Otherwise me or another contributor can do it later (and credit you for the work already done of course).

2021-04-06 15:56 UTC, pouleyKetchoupp requested changes
Removing approval for now since refactoring is needed.

2021-04-07 16:14 UTC, mortarroad commented
No, I don't think I will do that.
Converting the implementation to Godot's style doesn't seem particularly appealing, since it means we'll have to maintain it ourselves.

Also, some things in the implementation are a bit odd, for example it has its own memory pool, which seems a bit silly.
I suppose we'd also want to replace that with something a bit more sensible, if we refactor it.
Or at least it should be profiled whether it brings any performance benefit.

2021-04-07 17:14 UTC, pouleyKetchoupp commented
@mortarroad No problem, it's understandable that you don't want to do this extra work.

> Converting the implementation to Godot's style doesn't seem particularly appealing, since it means we'll have to maintain it ourselves.

It should be fine as it's not a lot of code and probably won't need much maintenance. We've done that before with other utilities from Bullet:
https://github.com/godotengine/godot/blob/master/servers/physics_3d/gjk_epa.cpp
https://github.com/godotengine/godot/blob/master/core/math/dynamic_bvh.h

> Also, some things in the implementation are a bit odd, for example it has its own memory pool, which seems a bit silly.
I suppose we'd also want to replace that with something a bit more sensible, if we refactor it.

Makes sense, it could possibly use something like `PagedAllocator` instead.
https://github.com/godotengine/godot/blob/master/core/templates/paged_allocator.h

2021-05-07 11:27 UTC, closed without merging

2021-05-07 11:42 UTC, akien-mga commented
Superseded by #48533.