Fix crash on RigidBody _direct_state_changed
godotengine/godot pull request #47485
Opened 2021-03-30 06:44 UTC by rafallus

Fixes: #46003 for master branch

2021-03-30 07:48 UTC, madmiraal requested changes
Three points:
1. As mentioned in https://github.com/godotengine/godot/issues/46003#issuecomment-809984407, unless there is a reason this method is exposed, the better solution would be to unexpose this method.
2. This method also exists in KinematicBody, VehicleBody and the equivalents in 2D; so whatever solution is agreed on, those should be updated too.
3. This will prevent the crash identified in #47485 in debug mode only i.e. when run from the editor.

2021-03-30 08:06 UTC, rafallus commented
@madmiraal  
1. I agree that's a decision to be made.
2. Thanks for pointing this out.
3. The comment for the non-debug section says to trust it. So I just leave it as is. I guess for release you are supposed to have already tested your code.

2021-04-08 15:58 UTC, pouleyKetchoupp commented
I agree we should just unexpose the method on master. The method binding seems to be used only because of an internal call (see https://github.com/godotengine/godot/issues/46003#issuecomment-810003807).

@rafallus If you're up for refactoring this fix, the proper changes are:
* Modify `body_set_force_integration_callback` in the physics server to use a callable:
https://github.com/godotengine/godot/blob/35066f39ff111ee0e9d4aba534bb08fc2d686156/servers/physics_server_3d.h#L489
```
virtual void body_set_force_integration_callback(RID p_body, const Callable &p_callable, const Variant &p_udata = Variant()) = 0; 
```
* Modify how it's stored in the body inside the physics server:
https://github.com/godotengine/godot/blob/35066f39ff111ee0e9d4aba534bb08fc2d686156/servers/physics_3d/body_3d_sw.h#L129-L133
```
struct ForceIntegrationCallback {
	Callable callable;
	Variant udata;
};
```
* Modify the call to use `Callable::get_object()` and `Callable::call()`:
https://github.com/godotengine/godot/blob/35066f39ff111ee0e9d4aba534bb08fc2d686156/servers/physics_3d/body_3d_sw.cpp#L696-L705
* Make the same changes in Bullet module and Godot Physics 2D
* Use `callable_mp` macro in calls to `body_set_force_integration_callback`
* Remove all the `_direct_state_changed` bindings

2021-04-09 19:10 UTC, pouleyKetchoupp commented
@rafallus Thanks for refactoring the PR! I haven't reviewed or tested yet, but for info some checks are failing because of compilation errors in test code:
```
tests/test_physics_2d.cpp: In member function 'RID TestPhysics2DMainLoop::_add_body(PhysicsServer2D::ShapeType, const Transform2D&)':
tests/test_physics_2d.cpp:246:76: error: no matching function for call to 'PhysicsServer2D::body_set_force_integration_callback(RID&, TestPhysics2DMainLoop*, const char [12], RID&)'
  246 |   ps->body_set_force_integration_callback(body, this, "_body_moved", sprite);
      |                                                                            ^
In file included from tests/test_physics_2d.cpp:39:
./servers/physics_server_2d.h:480:15: note: candidate: 'virtual void PhysicsServer2D::body_set_force_integration_callback(RID, const Callable&, const Variant&)'
  480 |  virtual void body_set_force_integration_callback(RID p_body, const Callable &p_callable, const Variant &p_udata = Variant()) = 0;
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./servers/physics_server_2d.h:480:15: note:   candidate expects 3 arguments, 4 provided
```
It seems there are some more cases in `test_physics_3d.cpp` as well.

2021-04-09 20:00 UTC, rafallus commented
Still there are some tests that haven't passed. I'll check that later

2021-04-10 00:19 UTC, rafallus commented
Ok, the PR is ready for review

2021-04-12 18:05 UTC, pouleyKetchoupp requested changes
Looks good except for 2 things:

* There are currently errors when starting the editor or game because of `body_set_force_integration_callback` in physics servers has different arguments now. The method binding needs to be updated here:
https://github.com/godotengine/godot/blob/5c8505c25adf9524bd9ea2bc2ad31eb44190ffcc/servers/physics_server_2d.cpp#L650
(and the same in the 3d physics server)

* The documentation for physics servers needs to be updated too:
https://github.com/godotengine/godot/blob/5c8505c25adf9524bd9ea2bc2ad31eb44190ffcc/doc/classes/PhysicsServer2D.xml#L657-L671
(again, for the 3d version as well)

2021-04-14 01:13 UTC, pouleyKetchoupp approved these changes

2021-04-14 02:00 UTC, pouleyKetchoupp approved these changes

2021-04-14 07:05 UTC, akien-mga commented on tests/test_physics_2d.cpp
> +		ps->body_set_force_integration_callback(body, callable_mp(this, &TestPhysics2DMainLoop::_body_moved), sprite);
This should let you remove the `ClassDB::bind_method(D_METHOD("_body_moved"), &TestPhysics2DMainLoop::_body_moved);` which was only used for this callback.

(And maybe clear the two commented lines below this which won't be reused as is.)

2021-04-14 07:05 UTC, akien-mga commented on tests/test_physics_3d.cpp
> +		ps->body_set_force_integration_callback(body, callable_mp(this, &TestPhysics3DMainLoop::body_changed_transform), mesh_instance);
You can also remove `ClassDB::bind_method("body_changed_transform", &TestPhysics3DMainLoop::body_changed_transform);` (and the whole `_bind_method` override).

2021-04-14 07:07 UTC, akien-mga approved these changes
Suggested a couple additional cleanups, but looks great overall. Thanks!

2021-04-15 09:00 UTC, madmiraal requested changes
It looks good. Just, as suggested below, the original check this PR suggested either needs to be applied consistently or not at all.

2021-04-23 12:44 UTC, madmiraal approved these changes

2021-04-23 14:02 UTC, merged

2021-04-23 14:02 UTC, akien-mga commented
Thanks!

2021-04-23 14:42 UTC, twocountriestrus commented
Gracias 


Enviado desde Yahoo Mail para iPhone


El viernes, abril 23, 2021, 10:03 a. m., Rémi Verschelde ***@***.***> escribió:




Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-23 14:48 UTC, pycbouh commented
@twocountriestrus Please don't spam PRs with "Thanks"