Update changelog for Godot 3.3
godotengine/godot pull request #47505
Opened 2021-03-30 19:28 UTC by Calinou

**Note:** Release date and announcement URL haven't been filled in yet.

2021-03-31 14:49 UTC, Calinou commented on CHANGELOG.md
> +[3.2.1]: https://github.com/godotengine/godot/compare/3.2-stable...3.2.1-stable
Fixed. Note that I used a 3.1 changelog comparison link which doesn't exist, since there is no such text file on the download repository.

2021-04-06 14:55 UTC, akien-mga approved these changes
Seems good to me. We could merge as is, I'd add the release announcement and release date when I tag the release.

2021-04-08 13:54 UTC, YeldhamDev requested changes

2021-04-08 13:54 UTC, YeldhamDev commented on CHANGELOG.md
> +- [Increased the page size for array/dictionary editors in the inspector from 10 to 2 0](https://github.com/godotengine/godot/pull/44864).
There's a typo here.
```suggestion
- [Increased the page size for array/dictionary editors in the inspector from 10 to 20](https://github.com/godotengine/godot/pull/44864).
```

2021-04-08 14:17 UTC, YeldhamDev approved these changes

2021-04-11 23:35 UTC, DarkKilauea commented
You might want to mention a breaking change from 3.2.3 to 3.3:

The signature of `Object _make_custom_tooltip(String)` changed to `Control _make_custom_tooltip(String)` on `Control`, which will require a code change for anyone overriding that method.

2021-04-11 23:57 UTC, Calinou commented
> You might want to mention a breaking change from 3.2.3 to 3.3:
> 
> The signature of `Object _make_custom_tooltip(String)` changed to `Control _make_custom_tooltip(String)` on `Control`, which will require a code change for anyone overriding that method.

Done.

2021-04-20 10:02 UTC, merged

2021-04-20 10:02 UTC, akien-mga commented
Thanks!