Document how to set up UPnP in a non-blocking manner
godotengine/godot pull request #47670
Opened 2021-04-06 16:37 UTC by Calinou

See https://github.com/godotengine/godot/issues/32160.

2021-04-06 17:16 UTC, Faless commented on modules/upnp/doc_classes/UPNP.xml
> +		[b]Note:[/b] UPnP discovery blocks the main thread. To perform non-blocking discovery, use [Thread]s like this:
> UPnP discovery blocks the main thread.

"UPnP discovery blocks the current thread. To perform discovery without blocking the main thread use [Thread]s like this:"

2021-04-06 17:23 UTC, Faless commented on modules/upnp/doc_classes/UPNP.xml
> +		        return push_error(err)
`push_error` returns void.
`push_error` also seems to fail (causing the script to crash) when passed a non-string argument.

```gdscript
	if err != OK:
		push_error(str(err))
		return
```

2021-04-06 17:29 UTC, Faless requested changes, later dismissed
See comments, we might also add a variable to check when the mapping is done.
It's hard to see the limit to what should be made as an example and what not.
E.g. I didn't feel this needed a specific example, as long as there is a generic example of using threads, because this just how you normally use them.

2021-05-01 16:58 UTC, Calinou commented
> See comments, we might also add a variable to check when the mapping is done.

Should this be a signal emitted instead of a `upnp_mapping_set` variable set to `true`?

2021-05-01 19:16 UTC, Faless commented
> Should this be a signal emitted instead of a `upnp_mapping_set` variable being set to `true`?

Yes, that's a good idea. Maybe a `upnp_completed` signal with an `Error` parameter (`OK` when done successfully or any error in case of failure, like done in HTTPRequest)?

2021-09-09 11:58 UTC, mhilbrunner commented
@Calinou Friendly reminder that this needs a small update :)

2021-09-30 16:28 UTC, Calinou commented
I added the `upnp_completed` signal emission as requested :slightly_smiling_face:

2021-09-30 18:09 UTC, mhilbrunner approved these changes

2021-09-30 18:12 UTC, merged

2021-09-30 18:12 UTC, mhilbrunner commented
Thanks for this!

2021-10-04 12:37 UTC, akien-mga commented
Cherry-picked for 3.4.