Fix docs description for CapsuleMesh::mid_height
godotengine/godot pull request #47797
Opened 2021-04-11 14:35 UTC by kleonc

Previous description is wrong. Not sure if the formatting is right in the note I've added.

Cherry-pickable for `3.x`.

2021-04-11 15:44 UTC, Calinou requested changes

2021-04-11 15:44 UTC, Calinou commented on doc/classes/CapsuleMesh.xml
> +			[b]Note:[/b] Total height of the capsule is equal [member mid_height] + 2 * [member radius].
```suggestion
			[b]Note:[/b] The capsule's total height capsule is equal to [member mid_height] + 2 * [member radius].
```

2021-04-11 16:26 UTC, kleonc commented on doc/classes/CapsuleMesh.xml
> +			[b]Note:[/b] Total height of the capsule is equal [member mid_height] + 2 * [member radius].
Done.

2021-04-13 21:11 UTC, Calinou approved these changes

2021-04-14 06:26 UTC, merged

2021-04-14 06:26 UTC, akien-mga commented
Thanks!

2021-04-14 11:53 UTC, akien-mga commented
Cherry-picked for 3.3.