Add Github CodeQL security checks
godotengine/godot pull request #47857
Opened 2021-04-13 13:26 UTC by jfcg

Add Github CodeQL security checks for C++, Python, C# and Java (the last two does not build).

In my fork under `/security/code-scanning` I see:

![godot](https://user-images.githubusercontent.com/1410597/114559660-a434df80-9c74-11eb-97a5-235029a7d208.jpg)

2021-04-13 13:28 UTC, pycbouh commented
Please squash your commits into one, and use a descriptive name for that one commit. For example, your PR title is fine.

2021-04-13 13:51 UTC, qarmin requested changes

2021-04-13 13:51 UTC, qarmin commented on .github/workflows/codeql-analysis.yml
> +       scons platform=x11 target=release_debug udev=no -j 4
Each command should have different steps:
- Dependencies
- Compilation
- Run

etc. just like in others CI files

2021-04-13 13:53 UTC, qarmin commented
This PR doesn't contains any caching mechanism(look at other CI jobs for more info), so each time it will need to compile ~50 minutes entire engine

2021-04-13 13:55 UTC, qarmin commented
> In my fork under `/security/code-scanning` I see:

This is hidden for me and probably for other people also.

2021-04-13 14:04 UTC, Calinou commented
> This PR doesn't contains any caching mechanism(look at other CI jobs for more info), so each time it will need to compile ~50 minutes entire engine

Due to the long build times, it may be better to not bother with building pull requests and only build pushes to the upstream repository.

2021-04-13 16:15 UTC, qarmin commented
Only 25 from 304 reports comes from Godot and the rest from thirdparty repositories.
This tool only found in code `Multiplication result converted to larger type`.

I was expecting a Cppcheck-like error detector, and with such results I don't think that `Github CodeQL` is good choice.

2021-04-14 04:35 UTC, jfcg commented
3rd party libraries are part of your codebase, and they may not be necessarily scanned for security checks, i dont know about the overall false positive rate, a deeper analysis of the alerts could be necessary.

2021-07-26 06:14 UTC, aaronfranke commented
Ideally, we can find and fix the bugs in third-party libraries, and contribute the fixes back upstream.

2022-08-02 13:06 UTC, akien-mga commented
This seems interesting, it would be good to revisit it.

I'm not sure it's a good idea to run it on each PR as in my experience this kind of tool finds lots of false positives and it will take a long time to fix or work around all of them before we can make its failures blocking for a given PR. Maybe it could run once per day instead.

OP's fork has been deleted so we can't check how useful the results were.

Would be good to salvage if a contributor is interested.

2022-08-02 13:06 UTC, closed without merging