Document AnimationNodeTimeSeek with clarified usage and code example
godotengine/godot pull request #47983
Opened 2021-04-17 18:08 UTC by smix8

Document AnimationNodeTimeSeek with clarified usage and code example.

Issue was that users often ask "how can I play my animation from a certain position inside the AnimationTree?" but have no idea from the current documentation what the SeekNode can do and how it is used. The majority didn't even know what a seek command in this context is to begin with.

2021-04-17 18:22 UTC, smix8 commented
What did I do to offend the clang-god? Is it the empty line between the different codeblocks? How can I properly add a clang-happy empty line then?

2021-04-17 19:05 UTC, Calinou requested changes, later dismissed

2021-04-17 19:05 UTC, Calinou commented on doc/classes/AnimationNodeTimeSeek.xml
> +		This node can be used to cause a seek command to happen to any sub-children of the animation graph. Use this node type to play an [Animation] from the start or a certain playback position inside th
```suggestion
		This node can be used to cause a seek command to happen to any sub-children of the animation graph. Use this node type to play an [Animation] from the start or a certain playback position inside the [AnimationNodeBlendTree]. After setting the time and changing the animation playback, the seek node automatically goes into sleep mode on the next process frame by setting its [code]seek_position[/code] value to [code]-1.0[/code].
```

2021-04-17 19:05 UTC, Calinou commented on doc/classes/AnimationNodeTimeSeek.xml
> +		animationTree.Set("parameters/Seek/seek_position", 12.0);
To fix CI checks, remove trailing whitespace:

```suggestion
		# Play child animation from the start.
		animation_tree.set("parameters/Seek/seek_position", 0.0)
		# Alternative syntax (same result as above).
		animation_tree["parameters/Seek/seek_position"] = 0.0

		# Play child animation from 12 second timestamp.
		animation_tree.set("parameters/Seek/seek_position", 12.0)
		# Alternative syntax (same result as above).
		animation_tree["parameters/Seek/seek_position"] = 12.0
		[/gdscript]
		[csharp]
		// Play child animation from the start.
		animationTree.Set("parameters/Seek/seek_position", 0.0);

		// Play child animation from 12 second timestamp.
		animationTree.Set("parameters/Seek/seek_position", 12.0);
```

2021-04-20 18:04 UTC, akien-mga approved these changes

2021-04-20 18:05 UTC, merged

2021-04-20 18:05 UTC, akien-mga commented
Thanks!

2021-04-20 18:15 UTC, akien-mga commented
Cherry-picked for 3.3.