Fix Closing Running Game, still shows remote and local tabs
godotengine/godot pull request #48079
Opened 2021-04-22 06:52 UTC by sboron

Fixing an issue with "Closing Running Game, still shows remote and local tabs".

To reproduce the error, just starting and game and use the "stop button" to close the game, the remote tree will not be disabled because the notifier will not be triggered.

![image](https://user-images.githubusercontent.com/76991284/115668987-11690480-a348-11eb-8968-1c8e3cfab785.png)

Related to this issue: https://github.com/godotengine/godot/issues/47643

2021-04-22 09:18 UTC, akien-mga commented
The change seems OK to me (though I'll let @Faless confirm who's more familiar with this code), but the commit message should be amended to give a human-readable description of what the commit does.

See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

2021-04-22 13:10 UTC, Faless requested changes
This is good, could be probably be done by moving the `!found` part of `_debugger_stopped` to its own function, and call it in `::stop` to avoid signal overhead, but I really like the brevity of this change :+1: .

As @akien-mga mentioned, please amend the commit message, then it's good to go for me.

2021-04-22 23:07 UTC, sboron commented
Changing the commit name.

2021-04-23 00:59 UTC, Faless approved these changes
Looks good :+1:

2021-04-23 00:59 UTC, merged

2021-04-23 00:59 UTC, Faless commented
Thanks!