Refactor import hints parser
godotengine/godot pull request #48167
Opened 2021-04-24 17:51 UTC by Shatur95

In this PR, I reworked the parsing of import hints. Here is what I did:

* Replaced `_fixstr` and `_teststr`, which contained duplicate code, with `_parse_hint` that changes passed name and returns obtained hint.
* Enhanced the hints detection algorithm. Now it finds a hint and make sure that there are no letters around it. Supersedes #43563.
* Now the hints are enums and they are parsed only once, which speeds up the import.
* Material import hints only worked in the following order: `-alpha` `-vcol`. I replaced the parsing with a loop and the order is no longer important.

2021-04-24 20:46 UTC, seadra commented
Does this fix #42041?

2021-04-24 21:17 UTC, Shatur95 commented
> Does this fix #42041?

Unfortunately no. But I'm interested in a fix. We will work on it as soon as this PR is merged!

2021-04-26 09:05 UTC, fire commented
I like his. Will wait for the completion of the pr.

2021-04-26 09:08 UTC, Shatur95 commented
> I like this. Will wait for the completion of the pr.

The PR is ready, waiting for a review. I will send the fix in a separate PR to simplify review process.

2021-04-27 16:27 UTC, fire requested changes
This is better.

I only reviewed the design of the code.

Did you systematically check the test cases? Please reply back about that and then I can approve.

Minor things:

* Our coding style puts braces { } in the switch.

2021-04-27 16:51 UTC, Shatur95 commented
> Did you systematically check the test cases? Please reply back about that and then I can approve.

I tested it before and after changes the on submitted file in https://github.com/godotengine/godot-tests/pull/22 for material hints and on https://github.com/godotengine/godot-tests/blob/master/tests/blend_export/blend/32678-respect-import-hints-with-empty.blend for all other hints

> Our coding style puts braces { } in the switch.

Thanks, fixed!

2021-04-28 01:56 UTC, fire approved these changes, later dismissed

2021-10-06 19:49 UTC, fire commented
I'm not sure about the status of this, this pr was limbo'ed.

2023-08-20 08:03 UTC, AThousandShips commented on core/string/ustring.h
> +bool is_alpha(char32_t c);
This exists as `is_ascii_char` under `char_utils.h` now

2024-03-13 12:29 UTC, closed without merging