Reload scene if it was modified on disk.
godotengine/godot pull request #4820
Opened 2016-05-26 11:47 UTC by jjay

This PR fixes #4769.
- Reload silently if the scene has no local modifications
- Ask user if the scene has local modifications

2016-05-29 16:33 UTC, akien-mga commented
This sounds quite interesting! There are now merge conflicts though, could you rebase it on top of the current master HEAD?

2016-05-30 09:13 UTC, jjay commented
Done.

2016-06-01 01:23 UTC, Geequlim commented
This would be really useful for import plugins for re-mporting.

2016-06-19 10:35 UTC, akien-mga commented
Assigning to @reduz as he did some work on reimporting/reloading for 2.1 already.

2016-06-21 11:45 UTC, jjay commented
Forget to handle deleting file from fs. Fixed.

2016-07-18 14:29 UTC, akien-mga commented on tools/ios_xcode_template/godot_ios.xcodeproj/xcuserdata/jjay.xcuserdatad/xcschemes/godot_ios.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
Those files should not have been added to the PR :)

2016-10-03 11:30 UTC, akien-mga requested changes
XCode files need to be removed before this can be considered for merging.

2016-10-14 08:02 UTC, jjay commented
Fixed. Also use md5 instead of mtime for changes detection from now.

2016-10-15 15:47 UTC, jjay commented
Rebased

2017-03-04 16:51 UTC, akien-mga commented
I'm told this was already implemented in master by @reduz, so closing. https://github.com/godotengine/godot/issues/4769#issuecomment-231348667

2017-03-04 16:51 UTC, closed without merging