Fix create physical bone when up vector is collinear to child origin
godotengine/godot pull request #48310
Opened 2021-04-29 21:01 UTC by Blackiris

Fix issue #39757 but for Godot 4.0

When generating physical bone, `set_look_at` is used to change the bone direction.

`body_transform.set_look_at(Vector3(0, 0, 0), child_rest.origin);`

However, if the vector child_rest.origin is collinear with the default up vector =Vector3(0, 1, 0), the cross product cannot generate a third vector (with length > 0) and `set_look_at` fails.
In order to avoid this issue, set_look_at is now called twice, using 2 different up vectors.

```
body_transform.set_look_at(Vector3(0, 0, 0), child_rest.origin, Vector3(0, 1, 0));
body_transform.set_look_at(Vector3(0, 0, 0), child_rest.origin, Vector3(0, 0, 1));
```

2021-04-29 21:39 UTC, fire commented
What happens if the first one succeeds and the second test fails?

2021-04-30 07:53 UTC, Blackiris commented
Good question, I was asking myself this question too yesterday night before sleeping...

In Transform::set_look_at...

```
	v_z = p_eye - p_target;
	v_z.normalize();
	v_y = p_up;

	v_x = v_y.cross(v_z);
#ifdef MATH_CHECKS
	ERR_FAIL_COND(v_x.length() == 0);
#endif
```
... the check is done only if MATH_CHECKS is defined. Then, in case of failure, the error is thrown and the basis and origin change, which happen in the next lines, won't happen.
So if the first `set_look_at` succeed and the second one failed, only the first will change the direction.

However, I am wondering if MATH_CHECKS is always defined in the editor. Currently it is defined in math_defs.h:
```
#ifdef DEBUG_ENABLED
#define MATH_CHECKS
#endif
```

But if DEBUG_ENABLED is not enabled in the editor, then the vectors check must be done before using set_look_at...
After looking  it seems it is enabled only if target is release_debug or debug.

Thus, I need to change the PR...

2021-04-30 10:31 UTC, Blackiris commented
I have changed the solution: up is now checked before being used in set_look_at. The first top comment is also changed to show exactly that.

2021-06-08 00:54 UTC, fire commented
Can you rebase? I'll try get some review on this pr.

2021-06-09 19:36 UTC, Blackiris commented
Thank you! Just done rebasing this morning

2021-10-16 08:22 UTC, fire commented
@pouleyKetchoupp Is this something in your area?

2021-10-18 18:53 UTC, lyuma requested changes
Oh sorry, I meant to say please use (up.cross(...).is_equal_approx(Vector3()) instead of .length == 0

conceptually it seems fine

2021-12-25 18:18 UTC, Blackiris commented
I have created the specific issue for the DAE bones #56242 as it is a different issue compared to this one.
This PR still looks good to me, as it respect the bones after import (good bones for GLTF, wrong for DAE)

2022-03-20 10:17 UTC, akien-mga approved these changes

2022-03-20 23:49 UTC, lyuma approved these changes
Yes, I remember reviewing this. I think it's fine for this purpose.

Long term, I'd think this type of fix ought to belong inside `Basis::looking_at` itself. For example, I could imagine a game developer using `looking_at` in an AI script, and having hard-to-reproduce bugs caused by these pole vectors)

2022-03-21 10:25 UTC, merged