[3.x] Document valid range of Node2D.z_index
godotengine/godot pull request #48868
Opened 2021-05-19 22:53 UTC by kleonc

`3.x` version of #48867.
Cherry-pickable for `3.3`.

2021-05-19 23:19 UTC, pycbouh requested changes

2021-05-19 23:19 UTC, pycbouh commented on doc/classes/Node2D.xml
> +			Z index. Controls the order in which the nodes render. A node with a higher Z index will display in front of others. Must be in [constant VisualServer.CANVAS_ITEM_Z_MIN], [constant VisualServer.CA
```suggestion
			Z index. Controls the order in which the nodes render. A node with a higher Z index will display in front of others. Must be between [constant VisualServer.CANVAS_ITEM_Z_MIN] and [constant VisualServer.CANVAS_ITEM_Z_MAX] (inclusive).
```

2021-05-19 23:40 UTC, pycbouh approved these changes

2021-05-20 07:01 UTC, merged

2021-05-20 07:01 UTC, akien-mga commented
Thanks!

2021-05-20 12:35 UTC, akien-mga commented
Cherry-picked for 3.3.2.