Document valid range of Node2D.z_index
godotengine/godot pull request #48867
Opened 2021-05-19 22:52 UTC by kleonc

Documents that `z_index` needs to be in the proper range:
https://github.com/godotengine/godot/blob/1450a72bfa25ae7920adb276271105966113545d/scene/2d/node_2d.cpp#L340-L345

2021-05-19 23:18 UTC, pycbouh requested changes

2021-05-19 23:18 UTC, pycbouh commented on doc/classes/Node2D.xml
> +			Z index. Controls the order in which the nodes render. A node with a higher Z index will display in front of others. Must be in [constant RenderingServer.CANVAS_ITEM_Z_MIN], [constant RenderingSer
```suggestion
			Z index. Controls the order in which the nodes render. A node with a higher Z index will display in front of others. Must be between [constant RenderingServer.CANVAS_ITEM_Z_MIN] and [constant RenderingServer.CANVAS_ITEM_Z_MAX] (exclusive).
```

2021-05-19 23:26 UTC, kleonc commented on doc/classes/Node2D.xml
> +			Z index. Controls the order in which the nodes render. A node with a higher Z index will display in front of others. Must be in [constant RenderingServer.CANVAS_ITEM_Z_MIN], [constant RenderingSer
Changed, thanks!

2021-05-19 23:40 UTC, pycbouh approved these changes

2021-05-20 07:00 UTC, merged

2021-05-20 07:00 UTC, akien-mga commented
Thanks!