Remove duplicate orientation settings in the iOS export preset
godotengine/godot pull request #48943
Opened 2021-05-21 21:58 UTC by Calinou

The screen orientation is now sourced from the Project Settings like it is done for Android already.

See https://github.com/godotengine/godot/issues/45422.

2021-05-24 11:20 UTC, akien-mga commented
```
./platform/android/export/gradle_export_util.h: In function 'String _get_activity_tag(const Ref<EditorExportPreset>&)':
./platform/android/export/gradle_export_util.h:253:54: error: '_get_screen_orientation' was not declared in this scope
  253 |  String orientation = _get_android_orientation_label(_get_screen_orientation());
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~
scons: *** [platform/android/export/export.x11.opt.tools.64.o] Error 1
platform/iphone/export/export.cpp: In member function 'void EditorExportPlatformIOS::_fix_config_file(const Ref<EditorExportPreset>&, Vector<unsigned char>&, const EditorExportPlatformIOS::IOSConfigData&, bool)':
platform/iphone/export/export.cpp:496:27: error: 'class OS' has no member named 'get_orientation_from_string'; did you mean 'get_screen_orientation_from_string'?
  496 |      OS::get_singleton()->get_orientation_from_string(GLOBAL_GET("display/window/handheld/orientation"));
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                           get_screen_orientation_from_string
```

2021-05-24 16:08 UTC, m4gr3d requested changes

2021-05-24 16:08 UTC, m4gr3d commented on platform/android/export/gradle_export_util.h
> -OS::ScreenOrientation _get_screen_orientation() {
As shown by @akien-mga's error stacktrace, there's another use of `_get_screen_orientation()` in this file that needs to be updated.

2021-05-25 22:13 UTC, akien-mga approved these changes

2021-05-25 22:18 UTC, m4gr3d approved these changes

2021-05-25 22:24 UTC, merged

2021-05-25 22:24 UTC, akien-mga commented
Thanks!

2021-05-31 09:27 UTC, akien-mga commented
Cherry-picked for 3.3.3.