Exporting -> Android: Keystore Warnings
godotengine/godot pull request #48963
Opened 2021-05-22 11:47 UTC by HaywardMorihara

Warns the user when they provide one or two of the three keystore values (path, user, password) in the Android export presets, but not all three. If the user does not provide all three, then they will get an APK signing error that doesn't give any details (all it says is `'apksigner' returned with error #1`). See https://godotengine.org/qa/101943/error-apksigner-returned-with-error-%231

Solution discussed in issue https://github.com/godotengine/godot/issues/48787

2021-05-22 14:08 UTC, HaywardMorihara commented
I didn't see any relevant unit tests to add to - is there a suite that I missed?

2021-05-22 17:38 UTC, Calinou commented
> I didn't see any relevant unit tests to add to - is there a suite that I missed?

There are some unit tests for core classes, but none of the editor itself. You don't have to do anything more for this PR :slightly_smiling_face:

2021-05-22 17:40 UTC, Calinou requested changes, later dismissed

2021-05-22 17:40 UTC, Calinou commented on platform/android/export/export.cpp
> +			err += TTR("Either Debug keystore, Debug User AND Debug Password presets must be configured OR none of them.") + "\n";
Use consistent capitalization and terminology:

```suggestion
			err += TTR("Either Debug Keystore, Debug User AND Debug Password settings must be configured OR none of them.") + "\n";
```

2021-05-22 17:40 UTC, Calinou commented on platform/android/export/export.cpp
> +			err += TTR("Either Release keystore, Release User AND Release Password presets must be configured OR none of them.") + "\n";
Use consistent capitalization and terminology:

```suggestion
			err += TTR("Either Release Keystore, Release User AND Release Password settings must be configured OR none of them.") + "\n";
```

2021-05-24 16:52 UTC, m4gr3d approved these changes

2021-05-24 16:58 UTC, Calinou commented
@HaywardMorihara Looks good to me, please squash the commits together so we can merge this. See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) for instructions :slightly_smiling_face:

2021-05-24 23:50 UTC, HaywardMorihara commented
Squashed!

2021-06-01 12:16 UTC, HaywardMorihara commented
Sorry to bother, just bumping this in case it got lost, thanks!

2021-06-01 12:25 UTC, akien-mga approved these changes

2021-06-01 13:22 UTC, merged

2021-06-01 13:22 UTC, akien-mga commented
Thanks!

2021-06-01 23:34 UTC, HaywardMorihara commented
> Thanks! And congrats for your first merged Godot contribution 🎉

@akien-mga Thank you! In fact, my first merge to any open-source project! Really appreciate all the guidance from you and @Calinou!

2021-06-03 08:55 UTC, akien-mga commented
Cherry-picked for 3.4.

2021-06-03 10:40 UTC, akien-mga commented
Cherry-picked for 3.3.3.