Use bold fonts in editor
godotengine/godot pull request #49148
Opened 2021-05-27 15:35 UTC by reduz

* Labels are now bold
* Categories in trees are bold
* Main editor buttons are bold
* Fixed section folding arrows in inspector

![image](https://user-images.githubusercontent.com/6265307/119855011-f1e56e80-bee7-11eb-96ea-89d40bd40d34.png)

2021-05-27 15:55 UTC, Logharaa commented
I guess a before/after might have been useful to compare the changes, but seems good!

2021-05-27 16:03 UTC, pycbouh commented
> Labels are now bold

Wait, all labels are bold by default? I'm not sure about that.

2021-05-27 17:31 UTC, reduz commented
@pycbouh for the most part it looks good in the editor. There are so me cases where it might be good to adjust at some point, but I think its pretty good for now.

2021-05-29 20:23 UTC, Calinou requested changes, later dismissed

2021-05-29 20:23 UTC, Calinou commented on editor/editor_inspector.cpp
> +		//Color color = get_theme_color("font_color", "Tree");
Remove commented out code:

```suggestion
```

2021-05-29 20:24 UTC, Calinou commented
Note that this could be remade for the `3.x` branch, since it doesn't break compatibility with existing projects. The per-TreeItem custom font feature can also be useful in other places in the editor (and possibly even in projects).

2021-06-02 15:10 UTC, reduz commented
@Calinou to be honest I would leave 3.x alone at this point, let it conserve its visual identity so 4.0 differentiates as much as possible.

2021-06-02 16:40 UTC, akien-mga approved these changes

2021-06-02 16:40 UTC, merged

2021-06-02 16:41 UTC, akien-mga commented
Thanks!

2021-06-09 08:25 UTC, Byteron commented
In the Node section there is still no bold sections.
![image](https://user-images.githubusercontent.com/24433899/121319903-f27cfc80-c90c-11eb-99d9-38892a14180f.png)