fixed a conflict in the AnimationTree cache between tracks with the s…
godotengine/godot pull request #49411
Opened 2021-06-07 23:39 UTC by TokageItLab

Fixed 48526.

The case where a single animation is played in the animation tree has been fixed, but when conflicts occur in the one animation, or when blending animations of different track types that rewrite the same value, only the track with the later iteration order will be played, regardless of the blend value. This may need to be fixed in the future.

2021-06-08 20:20 UTC, TokageItLab commented
Self considering. I thought it was fine to cache MethodTrack and AudioTrack separately.

However, currently, for Transform3D, Value, and Bezier, the changes are stored in the TrackCache, and they are not blended and are stored in each TrackType. To solve #49431. we need a way to convert and combine them into one.

2021-06-09 22:23 UTC, TokageItLab commented
`BezierTrack` and `ValueTrack` are now blended together. However, the subpath must match.

For example,

```
[BezierTrack]
Node2D:position:x
Node2D:position:y
```

and

```
[ValueTrack]
Node2D:position:x
Node2D:position:y
```

will be blended, but

````
[ValueTrack]
Node2D:position
````

will not be blended.

The above case can be seen in the demo project.

[track_blends_2.zip](https://github.com/godotengine/godot/files/6627173/track_blends_2.zip)

If we solve the matching problem, we will need to do a huge refactoring.

Currently, we can't tell from the subpath name "x" whether it is a `Vector2` or `Vector3`, so we need to do a search every frame, every `ValueTrack` with a subpath, by tracing the parent of the `NodePath` and actually getting the value of the path and checking the type.

2021-08-27 17:20 UTC, lyuma requested changes

2021-11-20 22:11 UTC, TokageItLab commented
This PR contains two fixes.

The first is that the caches of the Bezier and Value tracks have been merged to allow for blending. This is similar to the way @reduz split the Transform3D track. Fixed #49431. 

The second, as mentioned in the overview, is to resolve conflicts when there are tracks of different types with the same path in multiple animations. In order to avoid conflicts, we needed to store the cache as an array. Fixed #43848 and #48526.

2022-01-19 11:19 UTC, TokageItLab commented
Some method has been outdated; superseded by #56902.

2022-03-09 00:25 UTC, TokageItLab commented
Salvaged and rebased.

2022-09-16 21:13 UTC, TokageItLab commented
Closing this once since it is out of date. The inability to blend BezierTrack and ValueTrack can be made a documentation issue, but I think it needs to be taken care of in cases of path conflicts such as AudioTrack and MethodTrack.

2022-09-16 21:13 UTC, closed without merging