Remove unused `caret_background_color` property from TextEdit
godotengine/godot pull request #49513
Opened 2021-06-11 14:07 UTC by Calinou

This color wasn't used anywhere.

I found this out while working on https://github.com/godotengine/godot/pull/48548.

2021-06-11 14:16 UTC, Sslaxx commented
Any reason not to implement it?

2021-06-11 14:26 UTC, Calinou commented
> Any reason not to implement it?

I don't see any practical reason for it. You can already configure the caret color or change it into a block caret.

2021-06-11 14:45 UTC, YeldhamDev approved these changes

2021-06-11 14:51 UTC, Paulb23 requested changes
This is a bug, looks like it was missed as part of the RTL refactor. 

`caret_background_color` is the colour of the text behind the caret when block caret is enabled.

2021-06-11 16:11 UTC, Calinou commented
> This is a bug, looks like it was missed as part of the RTL refactor.
> 
> `caret_background_color` is the colour of the text behind the caret when block caret is enabled.

I see. Shouldn't we automatically determine this color instead (e.g. by inverting the text color)?

2021-06-11 17:24 UTC, Paulb23 commented
> Shouldn't we automatically determine this color instead (e.g. by inverting the text color if the caret's opacity is high enough)?

Yeah, I don't see a problem with doing that.

2022-07-30 19:39 UTC, Calinou commented
This should no longer be needed now in latest `master`, closing.

2022-07-30 19:39 UTC, closed without merging