[WIP] Focusable Tabs and TabContainer, tabs can be changed using keyboard and gamepad
godotengine/godot pull request #49928
Opened 2021-06-26 18:12 UTC by DrRevert

This PR adds support for UI focus Tabs and TabContainer so they can be navigated using keyboard and gamepad. Related issues: #25877 #46111
**Changes:**
- Tab and TabContainer focus mode is now set to all by default
- When Tab/TabContainer node has focus it will render a blue rectangle (the same as the button) 
![image](https://user-images.githubusercontent.com/69091976/123520941-d1116400-d6b3-11eb-802a-cd3b91b8fb65.png)
- When Tab/TabContainer node has focus pressing ui_left will switch to the tab on the left of the currently selected, if the first tab is currently selected it will loop over and choose the last tab
- Similary when pressing ui_right the tab on the right be selected, if the last tab is currently selected, it will loop over and select first tab
- Pressing ui_down when TabContainer will in practice have the same effect as pressing ui_focus_next, more details in the Known issues section.

**Known issues:**
- Because of the way TabContainer is implemented, changing focus from the TabContainer and Control inside the tab (child) is tricky. Engine for some reason doesn't TabContainer and child Control as valid neighbours. Switching from TabContainer to a child can be achieved using the find_next_valid_focus, but might cause issues in a more advanced UI design. Switching from child to TabContainer can be accomplished by explictly setting the Neighbor Top/Left/Right/Bottom parameter.
- Current implementation doesn't check if the tab is disabled, before switching to it.
- Behavior for looping over from last to first tab or vice versa might not be desired and should be enabled by a new property
- Focus graphic is the same as button focus graphic, it looks okay, but if the PR gets approved it should propably use its own graphic

2021-06-27 13:16 UTC, DrRevert commented
Updated PR:
- pressing ui_down when TabContainer is focus won't trigger "find next valid focus" - I came to the conclusion that if you need to prepare extra logic to handle getting from child element to the TabContainer you should also write logic for getting from TabContainer to child. Otherwise this breaks the flow, as the developer might not be expecting that the focus will get stolen because user pressed down. Fixing this issue globally probably requires changing how engine looks for neighbor Control nodes, which is way out of the scope of this PR and might cause more issue down the line.
- added handing disabled tabs
- added rollover boolean parameter, which controls if pressing right on the last tab or left on the first tab should select the tab on the other side

2021-06-27 14:07 UTC, Calinou commented
> Focus graphic is the same as button focus graphic, it looks okay, but if the PR gets approved it should propably use its own graphic

I think we could leave it as-is, especially since people using custom themes will have to provide a StyleBox for this new element once this PR is merged. What do you think the custom graphic should look like? How do other applications handle this?

2021-06-27 14:17 UTC, DrRevert commented
> I think we could leave it as-is, especially since people using custom themes will have to provide a StyleBox for this new element once this PR is merged. What do you think the custom graphic should look like? How do other applications handle this?

I didn't actually thought how the final graphic should look like. Windows in Win32 programs renders a dotted rectangle around the tab name if it has keyboard focus, which is slightly smaller that the tab
![image](https://user-images.githubusercontent.com/69091976/123547977-36705e00-d763-11eb-861b-1e38ee2ad3d9.png)

2023-06-01 16:14 UTC, Eoin-ONeill-Yokai requested changes
Hey, thanks for taking the time to write this PR. I'm sorry it's taken a while for the community to review.

I've provided some feedback but none of them are major blockers. Most are just my opinion, but things are working as expected for the most part. I think this PR is a good idea so I wanted to provide some feedback. I hope that by reviewing this PR we can speed up getting members of the project to consider it for the next 4.X release (4.2 since 4.1 is in feature freeze.) 


If you're around and are still willing to deal with rebasing the code, let me know. Otherwise, I could help you with the rebase process if necessary.

Finally, once all of the changes are made, make sure to condense your commits down to 1 commit message following our commit message standard if possible. 

Thanks!

2023-06-08 13:15 UTC, DrRevert commented
Hi, sure I can look intro rebasing/refactoring this weekend if I have time.
Thanks for the feedback.

2023-06-08 13:18 UTC, DrRevert commented on scene/gui/tabs.cpp
> +			while (valid) {
Not really, I just found while loop being easiest way to implement searching for a valid tab.

2023-06-25 16:06 UTC, DrRevert commented
Hey, so I started working on refactoring as there was actually a lot of changes in codebase between prerelease and current version.
https://github.com/godotengine/godot/compare/master...DrRevert:godot:focusable_tabs_refactor
I didn't have time to replace "while" loops with "for" so I'm not updating PR yet, however the main feature should be working with no problem. I will try to get back to this as soon as possible.

2023-07-06 15:11 UTC, DrRevert commented
There are too many changes between pre-alpha and stable versions so I think the best way is to start new PR instead of trying to rebase this one.
I created new PR for refactored approach here https://github.com/godotengine/godot/pull/79104

2023-07-06 15:11 UTC, closed without merging