Tweak StandardMaterial3D's default height properties
godotengine/godot pull request #49947
Opened 2021-06-27 14:09 UTC by Calinou

- Enable Deep Parallax by default as most people end up enabling it in the end. Non-Deep Parallax, while cheaper, is only suited to a few types of textures whereas Deep Parallax is much more general-purpose.
- Set the default height scale to 1 and multiply it by 0.05 in the shader.
  - This makes the height scale match normal map intensity and other scale factors.

2021-08-24 18:43 UTC, reduz commented
I dont think this is a great idea, if you are making a mobile game, deep parallax is very expensive and makes the technique unusable.

2021-08-25 06:00 UTC, Calinou commented
> I dont think this is a great idea, if you are making a mobile game, deep parallax is very expensive and makes the technique unusable.

I amended the pull request to leave Deep Parallax disabled by default. Hopefully, https://github.com/godotengine/godot/pull/50383 should make non-deep parallax more usable on most materials.

2021-11-16 14:40 UTC, reduz commented
Regarding this, what is generally the value range expected in similar applications/materials? I would think its the same spaces as the world.

2022-08-02 13:25 UTC, akien-mga requested changes
We discussed this in PR review meeting and agreed that it should be scaled by 0.01 (so if you interpret the unit as meter this property would be edited as cm, though this shouldn't be mentioned as is in the docs probably).

The scaling should be explained in the docs.

2022-08-02 21:07 UTC, Calinou commented
> We discussed this in PR review meeting and agreed that it should be scaled by 0.01 (so if you interpret the unit as meter this property would be edited as cm, though this shouldn't be mentioned as is in the docs probably).

Does this mean the default height should be 5 now?

2022-08-03 05:45 UTC, akien-mga commented
Yes.

2022-08-04 00:03 UTC, Calinou commented
Rebased and tested again, with the default height changed to 5.0. I also filled in the documentation for all heightmap properties in BaseMaterial3D.

2022-08-04 07:16 UTC, akien-mga commented
You need to convert the `>` in XML.

2022-08-04 09:31 UTC, akien-mga approved these changes

2022-08-04 09:31 UTC, merged

2022-08-04 09:31 UTC, akien-mga commented
Thanks!