Add a method to set the number of physics solver iterations in 3D
godotengine/godot pull request #50255
Opened 2021-07-07 17:10 UTC by Calinou

This is only for GodotPhysics, and adds a 3D counterpart to the [2D method that was recently added](https://github.com/godotengine/godot/pull/48827).

I can't see much difference (if any) when setting the number of iterations to 64 – can anyone confirm that it's working as intended? In the testing project, neither tunneling nor visible depenetration is prevented.

**Testing project:**

2021-07-10 00:40 UTC, pouleyKetchoupp approved these changes
Looks great!

It's working fine, but you won't necessarily see a difference when it comes to tunneling through a thin surface, because if your object goes through in one frame, it doesn't matter how many solver iterations you do, collision is just not detected. So for these cases, only proper CCD or physics frequency can improve things.

The effect is more obvious with joints, or piles of bodies like in this test:
https://github.com/godotengine/godot-demo-projects/blob/master/3d/physics_tests/tests/functional/test_pyramid.tscn

2021-07-10 00:43 UTC, pouleyKetchoupp requested changes

2021-07-10 00:43 UTC, pouleyKetchoupp commented on servers/physics_server_3d.h
> +	virtual void set_collision_iterations(int iterations) = 0;
This is missing `p_` prefix on the argument.

2021-07-13 23:43 UTC, pouleyKetchoupp approved these changes

2021-07-14 05:56 UTC, merged

2021-07-14 05:56 UTC, akien-mga commented
Thanks!