Try other resolved IPs if one fails to connect
godotengine/godot pull request #50365
Opened 2021-07-11 10:00 UTC by timothyqiu

When `HTTPClient` and `WebSocketClient` are connecting to server, save all resolved IPs, and try other candidates if one failed to connect. Not [Happy Eyeballs](https://tools.ietf.org/html/rfc8305), but at least it's happy I think :)

Fixes #46972, and hopefully fixes #36418, I don't have IPv6 connection to the AssetLib, so I only tested on my `localhost` which resolved to IPv6 first.

It's the same for 3.x, but `core/io/http_client_tcp.{h,cpp}` → `core/io/http_client.{h,cpp}` and `container.is_empty()` → `container.empty()`.

2021-08-29 15:06 UTC, Faless requested changes
See my comments about `ip_candidates` cleanup. Looks great otherwise :+1: :trophy:

2021-08-29 15:06 UTC, Faless commented on core/io/http_client_tcp.cpp
> +					ip_candidates = IP::get_singleton()->get_resolve_item_addresses(resolving);
`ip_candidates` should also be cleared when reaching `STATUS_CONNECTED` (i.e. fully connected, including SSL handshake).

2021-08-30 05:09 UTC, Faless approved these changes
Looks good, great job :trophy:

2021-08-30 05:25 UTC, merged

2021-08-30 05:25 UTC, Faless commented
Thanks!

2021-09-14 12:12 UTC, akien-mga commented
Cherry-picked for 3.4.

2021-09-29 06:15 UTC, akien-mga commented
Cherry-picked for 3.3.4.