Improve the appearance of Deep Parallax in StandardMaterial3D
godotengine/godot pull request #50377
Opened 2021-07-11 19:13 UTC by Calinou

This better preserves depth when viewed at oblique angles. Artifacts due to the amount of layers being low may be more noticeable as a result, but it's generally better to decrease the heightmap scale instead.

This is done by dividing the delta by the dot product of the view vector and normal vector.

## Preview

***Note:** From my testing, performance is about the same overall. The FPS counter on the last screenshot fluctuates a fair bit at higher values, so it's not meant to be used to compare performance here.*

| Before | After |
|-------:|:------|
|  |  |
|  |  |
|  |  |
|  |  |
|  |  |
|  |  |

2022-03-17 16:25 UTC, clayjohn requested changes
We discussed this at our PR review meeting and have agreed that in some cases it looks better and in others it looks worse. 

The problem is that at glancing angles, this PR makes the depth tend towards infinity. So in some places it creates way too much depth. 

We feel that there must be a more exact solution that will preserve the depth at glancing angles, but will not blow them up to infinity.

2022-03-17 20:55 UTC, Calinou commented
> The problem is that at glancing angles, this PR makes the depth tend towards infinity. So in some places it creates way too much depth.

Would using `max()` on the divisor help to avoid infinity?

2022-03-17 21:02 UTC, clayjohn commented
> > The problem is that at glancing angles, this PR makes the depth tend towards infinity. So in some places it creates way too much depth.
> 
> Would using `max()` on the divisor help to avoid infinite depth?

Yes it would, but it is still a hacky ad-hoc solution. There should be a correct mathematical solution that will allow for consistent levels of depth regardless of the viewing angle. We need to do the work of figuring that out instead of just scaling based on the view angle.

2022-06-28 18:37 UTC, clayjohn commented
Looking into this further as I review https://github.com/godotengine/godot/pull/62002. To my surprise, this is the "correct" solution in a sense. The "correct" calculation of ``delta`` would be ``P / num_layers / view_dir.z;`` This is functionally equivalent to the current ``P / num_layers / dot(VIEW, NORMAL);`` because ``view_dir`` is in tangent space. In tangent space, NORMAL is ``vec3(0,0,1)`` and accordingly the dot product between that and ``view_dir`` collapses to ``view_dir.z``. Indeed the delta increases to infinity at glancing angles, which has always been a problem either solved with a depth bias (like what you did in https://github.com/godotengine/godot/pull/50383 and what the current implementation of deep parallax uses) or by imposing a fixed limit.

2022-08-28 23:40 UTC, clayjohn commented
I am unconvinced that this change is worth making we recently added offset limiting in https://github.com/godotengine/godot/pull/50383 to "improve" the appearance of simple parallax and here we are removing it in deep parallax materials. At any rate, this PR is superseded by https://github.com/godotengine/godot/pull/62002 which maintains the old behaviour for compatibility.

2022-08-28 23:40 UTC, closed without merging