Explicit error message when setting active a Viewport that is already active
godotengine/godot pull request #50392
Opened 2021-07-12 09:06 UTC by TaskManagerCZ

#50382

2021-07-12 09:27 UTC, Calinou requested changes, later dismissed

2021-07-12 09:27 UTC, Calinou commented on servers/rendering/renderer_viewport.cpp
> +		ERR_FAIL_COND_MSG(active_viewports.find(viewport) != -1 , "Can't make active a Viewport that is already active" ); //already active
```suggestion
		ERR_FAIL_COND_MSG(active_viewports.find(viewport) != -1, "Can't make active a Viewport that is already active.");
```

2021-07-12 09:59 UTC, akien-mga commented
Looks good, please squash the two commits together (see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase)).

2021-07-12 10:47 UTC, TaskManagerCZ commented
> Looks good, please squash the two commits together (see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase)).

done :)

2021-07-12 11:15 UTC, akien-mga commented
Sorry I should have commented on this earlier, could you also amend the commit message to be more explicit about what it's changing? Mentioning line number is not useful btw, it's included in the diff itself and this will be outdated information as soon as a new line is added or removed in the file.

Something like this PR's title would be a clearer commit message: "Explicit error message when setting active a Viewport that is already active"

2021-07-12 12:25 UTC, TaskManagerCZ commented
> Sorry I should have commented on this earlier, could you also amend the commit message to be more explicit about what it's changing? Mentioning line number is not useful btw, it's included in the diff itself and this will be outdated information as soon as a new line is added or removed in the file.
> 
> Something like this PR's title would be a clearer commit message: "Explicit error message when setting active a Viewport that is already active"

Sorry for mistakes. It should be right now.

2021-07-12 12:30 UTC, akien-mga approved these changes

2021-07-12 12:52 UTC, merged

2021-07-12 12:52 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2021-07-13 07:59 UTC, akien-mga commented
Cherry-picked for 3.4.

2021-07-13 10:19 UTC, akien-mga commented
Cherry-picked for 3.3.3.