Start for project manager buttons rearrangement.
godotengine/godot pull request #50674
Opened 2021-07-20 23:45 UTC by starry-abyss

So each time I recommend Godot to someone, I'm ashamed of the Project Manager (the welcome screen, not the person).

This PR addresses the main problem with it - mixing buttons which affect the project list with buttons which affect the project selected. A separator is also added to make the new layout easier to read. All other "overhaul" ideas are not going to be included in this PR.

Notes:
1) Unfinished - I seemingly broke some of button functionality and my code is ugly for now, please don't worry about that yet
2) Technically "Remove Missing" also belongs in the top panel (and "About" does as well), but they don't feel as out of place as the other 3, so not sure

Before:
![project_manager_before](https://user-images.githubusercontent.com/11571820/126407513-53a0e9a9-a805-4594-9866-86200811833a.png)

After:
![project_manager_after](https://user-images.githubusercontent.com/11571820/126407530-68d89a90-dfe1-4e20-b2fe-66ddd41c3dd7.png)

Implements https://github.com/godotengine/godot/issues/25305
This is a first step towards something like https://github.com/godotengine/godot/issues/31342

2021-07-21 23:46 UTC, starry-abyss commented
Made the buttons a bit larger:

![image](https://user-images.githubusercontent.com/11571820/126573387-360092ac-21bb-4e8b-9ca5-b9c0b79687d0.png)

2021-07-22 07:05 UTC, Calinou commented
I like where this is going so far.

However, to preserve the vertical real estate we had previously, can you move the horizontal separator so that it's displayed *above* the **Edit** button instead of being displayed below the top bar? Like in this mockup I made:

![image](https://user-images.githubusercontent.com/180032/126601267-3b4a1021-5977-47ca-bc40-a72abf1d9f1c.png)

2021-07-22 09:00 UTC, starry-abyss commented
@Calinou Done! To be honest, I'm currently working on something else, so unless there is more feedback, it's pretty final. I think one can always do a separate PR later with their refinements.

2021-07-22 17:16 UTC, LightningAA requested changes
A little knit-picky, but the [style guide](https://docs.godotengine.org/en/stable/community/contributing/code_style_guidelines.html#comment-style-guide) suggests you end your comments with a period.  Other than that the code looks fine to me.

2021-07-22 17:16 UTC, LightningAA commented on editor/project_manager.cpp
> +		// A bar with buttons and options at top
```suggestion
		// A bar with buttons and options at top.
```

2021-07-22 17:16 UTC, LightningAA commented on editor/project_manager.cpp
> +		// A container for a project list and for a side bar with buttons
```suggestion
		// A container for a project list and for a side bar with buttons.
```

2021-07-22 17:16 UTC, LightningAA commented on editor/project_manager.cpp
> +		// A panel with the project list on it
```suggestion
		// A panel with the project list on it.
```

2021-07-22 17:16 UTC, LightningAA commented on editor/project_manager.cpp
> +		// The side bar with buttons
```suggestion
		// The side bar with the edit, run, rename, etc. buttons.
```

2021-07-22 21:17 UTC, starry-abyss commented
@LightningAA Done! I also changed "A bar with buttons and options at top" to "A bar at top with buttons and options".

2021-07-22 21:38 UTC, LightningAA approved these changes

2021-07-23 14:35 UTC, haskaris approved these changes

2023-07-21 12:52 UTC, AThousandShips commented
> I think I can rebase, but I'd need someone to lobby it for people who make decisions in Godot :'D

That's not quite how things work here, and without the PR in working conditions you can't really get reviewed

There's a very similar PR going currently, #79746 so the two of you should coordinate, but if you can rebase this and bring it up to date, and update the screenshots to match the current setup (with icons etc) this can be looked into

If not then this might be closed in favor of that other PR, as they are very similar and that one is currently active (just opened) but otherwise I'd argue this one has preference as it predates the other one

2023-07-24 20:18 UTC, starry-abyss commented
@AThousandShips Thank you for visiting, going to look into it :)

> That's not quite how things work here, and without the PR in working conditions you can't really get reviewed

That's a shame, because keeping it updated for 2 years and hoping that somebody considers it would be a waste of time...
As for the other PR, I think one design change per PR is better because with multiple changes there might be disagreement (somebody likes one change, but not the other), and it will take another 2 years then. :D

2023-07-24 20:24 UTC, YuriSizov commented
@starry-abyss I don't think there is a strong understanding that his would improve things. While there is some support, there is always some support for UI changes, so it should be taken with a grain of salt. You are correct that you shouldn't do too much work on something that is stuck in a limbo between some support and lack of approval/consensus.

I think we can agree to reject this for now, given that there hasn't been any resolution in 2 years and UI changes are inherently controversial. That would probably be more fair to you than stringing you along on a basis of hope.

2023-07-24 20:44 UTC, AThousandShips commented
Note that I wasn't necessarily saying that you have to keep it up to date constantly, but that a review can't be done properly without the PR being in a working state, the reaction was mostly to that when feedback/attention was given it helps to rebase and bring up to date

Mostly the comment was about that there's no one to lobby to for this, it's a review and decision making progress that is very much attached to the PR itself, not somewhere else to lobby to, that was my main point :)

2023-07-25 16:16 UTC, starry-abyss commented
> I think we can agree to reject this for now, given that there hasn't been any resolution in 2 years and UI changes are inherently controversial. That would probably be more fair to you than stringing you along on a basis of hope.

If there is a controversy, could you please bring it to this thread? From what I understand, initially it was decided to postpone it for after 4.0 release because of lack of time. And then it seems to be forgotten?

I think UI changes proposed in various threads here are controversial because they contain multiple changes. My PR contains exactly one small change, and so far nobody gave any objections.

> That said, there are some aspirations to improve the project manager overall.

That's what I'm talking about. Everyone wants big overhauls and gets endless debates. The result is project manager UI still looks like it's from previous century. :)

> Mostly the comment was about that there's no one to lobby to for this, it's a review and decision making progress that is very much attached to the PR itself, not somewhere else to lobby to, that was my main point :)

Sorry, I meant not the lobby to merge, but lobby to just consider. Somebody to sit in RocketChat and remind about it maybe, IDK how it works. :P

2023-07-25 16:17 UTC, AThousandShips commented
You can always go over there and link it for attention

2023-07-25 16:26 UTC, YuriSizov commented
> If there is a controversy, could you please bring it to this thread?

UI changes are inherently controversial because everyone has different preferences. Even a UI change with an overwhelming support can be canned because it doesn't fit some of the design goals (trust me, I know it first hand). This change with buttons have been discussed multiple times, including in PR review meetings, without much enthusiasm. Like I've said, it's not clear that this is an improvement. You have a different taste and think the current design is somehow outdated, but that's not an agreed upon premise.

> That's what I'm talking about. Everyone wants big overhauls and gets endless debates.

Well, my point was that there are project needs that are currently not fulfilled by the project manager. So we are going to address them, which may result in some layout changes and incorporating your suggestions. Or it may be done without any of that. I'm not talking about overhauling for the sake of overhauling/modernizing it. There are specific issues which we need to address, which may lead to some UI changes.

2023-07-25 16:52 UTC, starry-abyss commented
Ah, I see. So the key point in this change isn't about taste. It's about the match between what one sees on the screen and the underlying model.

The buttons New Project, Import and Scan are global (higher level), they are for the project manager as a whole. And so are Filter and Sort mechanisms (hence the buttons in question are moved nearby, also because higher level concepts usually go higher in UI, and not because of taste). While actions of most other buttons on the right are dependent on the currently selected project in the list. That's why mixing them is a mess for the user.

Most of the time the user doesn't create a project, instead they do something to the existing one, and it's likely the Edit. In the new layout it's easy to find the Edit button, in the old one it's not. One can of course double-click the project in the list to edit, but you only know about this possibility when you know. :P

> This change with buttons have been discussed multiple times, including in PR review meetings, without much enthusiasm. Like I've said, it's not clear that this is an improvement.

I never knew. Nobody told me. Hopefully this comment explains the improvement part!

2023-07-25 17:06 UTC, AThousandShips commented
Seems you accidentally closed the PR by resetting your branch

2023-07-25 17:23 UTC, starry-abyss commented
@AThousandShips Yes, this is because I couldn't push my new changes to Github for some reason. In the end had to sync it to stock Godot in the web interface and then re-commit and push.

So now I've updated the code and screenshots for latest Godot.

2023-07-28 01:47 UTC, Calinou approved these changes
Tested locally (rebased on top of `master` da81ca62a5f6d615516929896caa0b6b09ceccfc), it works as expected.

### Before

![Before](https://github.com/godotengine/godot/assets/180032/82d1d7fc-35cf-4489-bcd2-27a6886f0b70)

### After

![After](https://github.com/godotengine/godot/assets/180032/7f36fa14-8d07-48cc-b746-66eaaa3a3b86)

Keyboard shortcuts are still functional.

UI-wise, I think this is an improvement but if you've used the project manager previously, it'll obviously take you some time to get used to the new layout :slightly_smiling_face:

2023-07-31 18:51 UTC, YuriSizov approved these changes
Let's give it a go!

2023-07-31 19:09 UTC, merged

2023-07-31 21:14 UTC, KoBeWi commented
Is this separator intended?
![](https://chat.godotengine.org/file-upload/64c807e6cab4e8d8c5ab8bec/Clipboard%20-%2031%20lipca%202023%2021:13.png)