Updated softbody handling to allow for area/softbody collision detection and application of area gravity
godotengine/godot pull request #50785
Opened 2021-07-23 18:25 UTC by jeffrey-cochran

2021-07-26 17:19 UTC, pouleyKetchoupp requested changes
Great work! Gravity override works well.

Apart from my review (mostly code cleaning) I have a couple extra comments:

- Please add a description for the PR - even if short - so there's a record in the future. You can indicate that it's based on the body implementation, link to fixed issue or addressed proposal when relevant (I think there was an issue about area gravity in this case). If you have a test project you can easily share (unless you use a MRP from a bug report) it can be a plus to help with reviewing, but it's not mandatory.

- This PR doesn't add support for Area scene nodes to detect soft bodies and notify scripts for custom code by users (like it's done for detected bodies and areas) so `monitored_soft_bodies` in `Area3DSW` is currently not used.

This will be needed eventually, but it can be added in a separate PR as it requires a few more steps to be functional:

-New method in PhysicsServer3D for soft body monitor callback: https://github.com/godotengine/godot/blob/fef27e9b5b9b125ff535513c80b45953e8717f7d/servers/physics_server_3d.h#L347-L348
(and implementation in PhysicsServer3DSW)

-Handle soft bodies in Area3DSW::call_queries(): https://github.com/godotengine/godot/blob/fef27e9b5b9b125ff535513c80b45953e8717f7d/servers/physics_3d/area_3d_sw.cpp#L201
-Register monitoring callback in Area3D: https://github.com/godotengine/godot/blob/fef27e9b5b9b125ff535513c80b45953e8717f7d/scene/3d/area_3d.cpp#L280-L287

-Implement monitoring callback in Area3D, new method similar to bodies: https://github.com/godotengine/godot/blob/fef27e9b5b9b125ff535513c80b45953e8717f7d/scene/3d/area_3d.cpp#L139
 (it will need new specific signals for soft bodies)

 - New methods `get_overlapping_soft_bodies` and `overlaps_soft_body` exposed to script: https://github.com/godotengine/godot/blob/fef27e9b5b9b125ff535513c80b45953e8717f7d/scene/3d/area_3d.cpp#L560-L564
 
 -Updated documentation for new methods and signals in Area3D: https://github.com/godotengine/godot/blob/master/doc/classes/Area3D.xml

2021-08-03 15:41 UTC, jeffrey-cochran commented on servers/physics_3d/soft_body_3d_sw.h
> +	struct AreaCMP {
Yeah, agreed.

2021-08-03 15:42 UTC, jeffrey-cochran commented on servers/physics_3d/body_pair_3d_sw.h
> +
but that one was my favorite

2021-08-03 16:01 UTC, jeffrey-cochran commented on servers/physics_3d/space_3d_sw.cpp
> +			AreaSoftBodyPair3DSW *soft_area_pair = memnew(AreaSoftBodyPair3DSW((SoftBody3DSW *)B, p_subindex_B, area, p_subindex_A ));
> * This PR doesn't add support for Area scene nodes to detect soft bodies and notify scripts for custom code by users (like it's done for detected bodies and areas) so `monitored_soft_bodies` in `Area3DSW` is currently not used.

I'll do this later today. 💪

2021-08-04 15:11 UTC, pouleyKetchoupp commented on servers/physics_3d/soft_body_3d_sw.cpp
> +void SoftBody3DSW::_compute_area_gravity_and_dampenings(const Area3DSW *p_area) {
This method should be renamed to `_compute_area_gravity` or something more generic. Apart from that it all looks fine!

2021-08-13 09:30 UTC, akien-mga commented
For the reference, the email used to author your commits (see https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/50785.patch) doesn't seem to be linked to your GitHub account, which is why they appear with a default GitHub avatar instead of yours.

It's not a problem for Git but if you want to claim ownership so that they are attributed to your account, you can add this email as secondary email in your GH settings.

2021-08-16 02:19 UTC, jeffrey-cochran commented
> [diff.githubusercontent.com/raw/godotengine/godot/pull/50785.patch](https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/50785.patch)) doesn't seem to be

Thanks, I actually just noticed this the other day when I was searching for my commits lol. I'll do that

2021-08-16 14:30 UTC, pouleyKetchoupp approved these changes

2021-08-16 14:31 UTC, akien-mga commented
Thanks! And congrats for a great GSoC 2021 :tada:

2021-08-16 14:32 UTC, merged

2021-08-16 15:35 UTC, skaiware commented
Congrats @jeffrey-cochran 
I guess it could hardly be backported to the 3x branch ?  
Kind

2021-08-16 15:59 UTC, pouleyKetchoupp commented
@skaiware It should be possible to backport it in a future 3.x version, although it needs more work to make a Bullet version as well (this is Godot Physics only for now), and there are still some things to add to the nodes API to make it fully functional.

2021-08-16 17:00 UTC, jeffrey-cochran commented
> Congrats @jeffrey-cochran
> I guess it could hardly be backported to the 3x branch ?
> Kind

I will probably backport it to 3.x in the near future. Just don't have time in the next week or so to sort out finer details.