Generate docs on a thread
godotengine/godot pull request #50864
Opened 2021-07-25 17:47 UTC by reduz

* The main generation could not be moved to a thread, unfortunately, as it instantiates classes to get default values, interacts with ProjectSettings, etc.
* Only uncompressing documentation and merging it is thread.
* Seems to improve editor load times by 0.5 seconds.

2021-07-25 18:03 UTC, Calinou requested changes, later dismissed

2021-07-25 18:03 UTC, Calinou commented on editor/editor_help.cpp
>  void EditorHelpBit::_go_to_help(String p_what) {
Add a blank line between function declarations:

```suggestion
}

void EditorHelpBit::_go_to_help(String p_what) {
```

2021-07-25 18:03 UTC, Calinou commented on editor/editor_help.cpp
> +void EditorHelp::_gen_doc_thread(void *p_udata) {
Add a blank line between function declarations:

```suggestion
}

void EditorHelp::_gen_doc_thread(void *p_udata) {
```

2021-07-25 18:03 UTC, Calinou commented on editor/editor_help.cpp
> +static bool doc_gen_use_threads = true;
```suggestion
}

static bool doc_gen_use_threads = true;
```

2021-07-25 18:26 UTC, Calinou commented
[I backported this PR to `3.x`](https://github.com/Calinou/godot/tree/gen-doc-on-thread-3.x) and interestingly, it's slightly slower with the newer version:

```
❯ hyperfine -iw1 "bin/godot.x11.tools.64.llvm ~/Documents/Godot/escape-space/project.godot --quit" "bin/godot.x11.tools.64.llvm.vanilla ~/Documents/Godot/escape-space/project.godot --quit"
Benchmark #1: bin/godot.x11.tools.64.llvm ~/Documents/Godot/escape-space/project.godot --quit
  Time (mean ± σ):      6.990 s ±  0.330 s    [User: 4.041 s, System: 0.200 s]
  Range (min … max):    6.302 s …  7.232 s    10 runs
 
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
 
Benchmark #2: bin/godot.x11.tools.64.llvm.vanilla ~/Documents/Godot/escape-space/project.godot --quit
  Time (mean ± σ):      6.419 s ±  0.302 s    [User: 4.047 s, System: 0.194 s]
  Range (min … max):    5.832 s …  6.597 s    10 runs
```

I'll benchmark the `master` PR soon.

2021-07-26 07:10 UTC, akien-mga commented on editor/editor_help.h
> +#include "core/os/mutex.h"
I don't see a direct use of `Mutex` in the added code.

2021-07-26 07:11 UTC, akien-mga commented on editor/editor_help.cpp
> +	doc->generate(true); //not doable on threads, unfortunately since it instantiates all sorts of classes to get default values.
```suggestion
	doc->generate(true); // Not doable on threads unfortunately, since it instantiates all sorts of classes to get default values.
```

2021-07-26 07:11 UTC, akien-mga commented
Commits should be squashed.

2022-01-07 14:45 UTC, akien-mga commented
Tested after rebase against the current `master` branch, also seems to save 1.0s for me on a debug build:
```
$ hyperfine -iw1 "bin/godot.linuxbsd.tools.64.vanilla ~/tmp/godot/projects/FreeFall/project.godot --quit" "bin/godot.linuxbsd.tools.64.docthread ~/tmp/godot/projects/FreeFall/project.godot --quit"                                                                           
Benchmark #1: bin/godot.linuxbsd.tools.64.vanilla ~/tmp/godot/projects/FreeFall/project.godot --quit
  Time (mean ± σ):      9.148 s ±  0.334 s    [User: 7.238 s, System: 0.327 s]
  Range (min … max):    8.545 s …  9.398 s    10 runs
 
  Warning: Ignoring non-zero exit code.
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
 
Benchmark #2: bin/godot.linuxbsd.tools.64.docthread ~/tmp/godot/projects/FreeFall/project.godot --quit
  Time (mean ± σ):      8.362 s ±  0.402 s    [User: 7.261 s, System: 0.341 s]
  Range (min … max):    7.845 s …  8.917 s    10 runs
 
  Warning: Ignoring non-zero exit code.
 
Summary
  'bin/godot.linuxbsd.tools.64.docthread ~/tmp/godot/projects/FreeFall/project.godot --quit' ran
    1.09 ± 0.07 times faster than 'bin/godot.linuxbsd.tools.64.vanilla ~/tmp/godot/projects/FreeFall/project.godot --quit'
```

2022-01-07 15:28 UTC, akien-mga approved these changes

2022-01-07 15:28 UTC, merged

2022-01-07 15:28 UTC, akien-mga commented
Thanks!