Simplify C# print methods
godotengine/godot pull request #51020
Opened 2021-07-29 14:45 UTC by raulsntos

- Extracts the parameters logic to a single method
- Simplify the handling of null parameters

2021-08-03 20:41 UTC, aaronfranke requested changes
Overall this is nice. Having this logic be in a separate method is better than the repeated one-liners.

I tested this cherry-picked on 3.x and it gives me this error:

```
Core/GD.cs(85,49): error CS0246: The type or namespace name 'AllowNullAttribute' could not be found (are you missing a using directive or an assembly reference?) [/home/aaronfranke/workspace/godot-3/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]                                                                               
Core/GD.cs(85,49): error CS0246: The type or namespace name 'AllowNull' could not be found (are you missing a using directive or an assembly reference?) [/home/aaronfranke/workspace/godot-3/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
```

Removing `[AllowNull]` made this go away. This is likely just something to keep in mind when cherry-picking (and then the `using` isn't necessary).

Generally I'd like to keep C# methods in alphabetical order unless there is a significant reason to not do so. In this case this method is very related to the print methods so that may be enough of a reason. We can either move `GetPrintParams` above `Hash` or just leave it where it is, I don't have super strong feelings either way but I'm leaning towards moving it.

2021-08-03 20:41 UTC, aaronfranke commented on modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs
> +using System.Diagnostics.CodeAnalysis;
```suggestion
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
```

Let's keep these in alphabetical order at least.

2021-08-03 21:06 UTC, raulsntos commented
That's because in the `3.x` branch the `TargetFramework` is `netstandard2.0` while in `master` it's `netstandard2.1`.

**3.x**
https://github.com/godotengine/godot/blob/d9a07d1528a438ddf97b1a9cd37a96cbfa3a92ce/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj#L7

**master**
https://github.com/godotengine/godot/blob/769de0c35f10780edc1a670b09f63fc730fefc39/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj#L7

The `AllowNullAttribute` is only available from `netstandard2.1`:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.allownullattribute?view=net-5.0

I guess I could remove it to make it easier to cherry-pick but at one point I'd like to annotate the  API with [nullable](https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/) attributes to allow users who enable it in their projects get warnings and such.

2021-08-03 21:11 UTC, aaronfranke commented
IIRC @neikeq said that he doesn't want the 3.x and master codebases to diverge too much for the time being.

2021-08-03 21:13 UTC, aaronfranke approved these changes

2021-08-03 21:13 UTC, raulsntos commented
I ended up removing it, we can annotate the API later.

2021-08-03 22:22 UTC, merged

2021-08-03 22:22 UTC, neikeq commented
Thanks!

2021-08-05 14:36 UTC, akien-mga commented
Cherry-picked for 3.4.