WebsocketPeer outbound buffer fixes and buffer size query
godotengine/godot pull request #51036
Opened 2021-07-29 21:16 UTC by jordo

Fixes #50988 on master.

This PR addresses a few issue with outbound buffers in the WebsocketPeer class, and exposes an outbound buffer query for anyone working with a websocket server in godot.

Currently the wslay implementation of WebsocketPeer (anything non HTML5), will buffer an unlimited amount of outgoing messages in `wslay_event_queue_msg()`.  This is effectively an unbound outgoing queue.  

When implementing a websocket server, if an outbound websocket's tcp connection is saturated, `put_packet` will continue to buffer an unlimited amount of outgoing data within the wslay websocket library.  This PR will fail `put_packet` similar to what happens in `get_packet` if the amount of data being requested to send exceeds the current configured outbound buffer size.

Likewise this PR exposes querying the current amount of buffered outbound data in the websocketpeer buffer.  This is useful and needed when implementing a websocket server to implement throttling and congestion control per peer.  Normally congestion control would just happen via socket.send() and a stream will self-throttle, however WebsocketPeer is exposed as a `PacketPeer` interface with messages queuing up in a wslay in-memory queue.  With a working outbound buffer can, and the ability to introspect the amount of current buffered outgoing data, an application can make good decisions about how and when to throttle packets.  

The outbound buffer amount is implemented in HTML5 platform using the Websocket.bufferedAmount property https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/bufferedAmount and implemented using  `wslay_event_get_queued_msg_length` in the wslay implementation on other platforms.

2021-07-30 00:05 UTC, Faless requested changes
See comments, looks good otherwise :+1: . Great job!

2021-07-30 00:05 UTC, Faless commented on modules/websocket/wsl_peer.cpp
> +		return 0;
```suggestion
	ERR_FAIL_COND_V(!_data, 0);
```

2021-07-30 13:53 UTC, Faless approved these changes
Looks great, can you please squash the 2 commits together?
See here for instructions: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

2021-07-31 16:18 UTC, jordo commented
Squashed.  Also please see https://github.com/godotengine/godot/pull/51037 for 3.X version as well

2021-07-31 16:54 UTC, akien-mga commented
Would be nice if the commit message could be as clear as the PR title is ("WebsocketPeer outbound buffer fixes and buffer size query") for a nice Git log.

2021-08-01 01:50 UTC, jordo commented
modified commit msg.

2021-08-01 08:34 UTC, akien-mga approved these changes

2021-08-01 09:12 UTC, merged

2021-08-01 09:12 UTC, akien-mga commented
Thanks!