Added SSIL post processing effect
godotengine/godot pull request #51206
Opened 2021-08-03 07:53 UTC by clayjohn

Implements Screen Space Indirect Lighting (I still need to rename it in the code)

SSIL adds short-range indirect lighting into the scene by sampling much like SSAO. I went with the ASSAO-like approach after months of testing and experimenting with other methods (including full blown SSGI). This method strikes the best balance between performance and quality and does not require Temporal Super Sampling at all.

**SSIL is intended to complement VoxelGI or SDFGI and is not a form of GI on its own. It only adds light into the scene and it only takes lighting into account in a short to medium range**

**TODO:**

Before marking this PR as ready to merge I need to:

- [ ] 1. convert all references to SSGI to SSIL
- [ ] 2. clean up Screen Space reflections (likely I will just remove the changes to SSR and make them in another PR)
- [ ] 3. clean up code style (there are lots of places where the code is ugly)
- [ ] 4. move SSIL uniform sets into the renderbuffers
- [ ] 5. move SSIL after AO in the main scene shader
- [ ] 6. move framebuffer copy to raster (so we avoid jumping back and forth between raster and compute
- [ ] 7. write docs :)

After this PR is merged I need to investigate:
1. merging the SSIL buffer with the main GI buffer (might be nice, but limits flexibility)
2. generating Screen Space Bent Normals during SSIL pass (and using them for specular occlusion)

2021-08-15 23:57 UTC, clayjohn commented
> Lights' Indirect Energy property is not taken into account by SSIL. If this is a limitation that can't be resolved, it should be documented in the class reference.

That's right. I've added this limitation to the docs. It will also need to be reflected in a tutorial style doc

> SSIL colors are broken (everything is grayscale) when Half Size is disabled in the Project Settings. Not that it's very practical for performance reasons, but still 🙂

I think I have fixed this. At any rate I can't reproduce on the most recent version

> Enabling MSAA while SSIL is enabled may break rendering until you look away from any SSIL'd surface and look back.

I haven't been able to reproduce this. I will keep my eye on it though. 

> It seems the scene got excessively bright when approaching the material in question. This only happens if roughness is 0 or 0.01. With a roughness of 0.02 or higher, SSIL gets quite flickery but it doesn't turn the whole scene black. Maybe this can be fixed by clamping the material roughness to a minimum value (0.15 looks good from my quick testing). 

There is certainly a risk of infinite feedback loops forming between surfaces that face each other. I should put a cap on energy to avoid this.

2021-08-16 12:30 UTC, mrjustaguy commented on doc/classes/Environment.xml
> +			The amount that the screen-space ambient occlusion effect is allowed to blur over the edges of objects. Setting too high will result in aliasing around the edges of objects. Setting too low will m
ambient occlusion -> indirect lighting

2021-08-16 12:31 UTC, mrjustaguy commented on doc/classes/ProjectSettings.xml
> +			Distance at which the screen-space ambient occlusion effect starts to fade out. Use this hide screen-space indirect lighting at great distances.
ambient occlusion -> indirect lighting

2021-09-09 21:45 UTC, reduz requested changes

2021-09-09 21:45 UTC, reduz commented on servers/rendering/renderer_rd/effects_rd.h
> +		bool is_orthogonal;
Remember not use bool in push constants, some compilers will mess up alignment. Always use uint32_t.

2021-10-30 05:18 UTC, clayjohn commented
Okay updated with fixes for all the identified issues. I have solved the issue with propagating INFs and NaNs. It should be ready to go.

2021-11-01 06:08 UTC, clayjohn commented
After spending more time thinking about this, I think I can polish it a bit more before it is ready to merge.

2021-11-04 18:52 UTC, Calinou commented
It seems enabling SSIL creates an SSAO-like effect automatically. Should SSAO be disabled when SSIL is enabled?

2021-11-04 20:29 UTC, mrjustaguy commented
Eh, I know that technically SSIL on Ultra is broken (as it actually lights up a lightless scene on higher intensity, and also behaves differently to all the other settings), but I really love the Ultra setting effect, just have to set 0.1 intensity instead of 1 for the scene not to be lit by it without lights in a noticable way...

2021-11-06 19:44 UTC, clayjohn commented
Just pushed documentation updates to address recent comments. If CI is happy, I think this is ready for final review and merging!

2021-11-28 10:46 UTC, mrjustaguy commented
Hmm, Could SSIL maybe use Indirect Lighting by adding an extra step, instead of just using Direct Lighting to contribute to the end result?

I mean the way I see it, there are a few different possible implementations that would allow for Indirect Energy from lights to contribute to SSIL instead of just Energy. Here are some ideas

1) Compute a Frame where you Determine which pixel is affected by which lights, and then use the Indirect energy to multiply the output of the end result Light contribution by that amount
2) Compute an Extra Frame where instead of using Energy for the Light's energy, you use Indirect Energy, and mix the two results
3) Just render a Frame with Indirect Lighting Energy Instead of Direct Lighting Energy, and pass that to SSIL instead of the current Direct Lighting Energy that's passed to it.

I mean this could help with giving more fine-tune control over the intensity of the effect on a Per-Light basis, which would be great for artistic control

2021-12-11 22:41 UTC, unfa commented
In some cases (usually with exagerrated settings) the geometry wireframe becomes visible. I wonder what could be causing this:
![image](https://user-images.githubusercontent.com/491704/145693722-73d11abc-3171-4835-ad88-19f31341110e.png)

It's exagerrated when sharpness is turned up:
![image](https://user-images.githubusercontent.com/491704/145693750-72480742-66eb-4b40-b58c-af9b05fdb308.png)

Of course this example  uses an extremely rage radius.

It seems to occur only from Medium quality upwards.

On Low:
![image](https://user-images.githubusercontent.com/491704/145693801-140b6f43-95b6-4442-9668-8c13eb771483.png)

On Medium:
![image](https://user-images.githubusercontent.com/491704/145693806-3e93f697-9734-4bc1-8fb1-eed21139ba5e.png)

2021-12-11 22:47 UTC, Calinou commented
> It seems to occur only from Medium quality upwards.

The wireframe is present on Low too, but it's hard to discern:

![image](https://user-images.githubusercontent.com/180032/145693908-def037db-723a-4cf5-a735-fa299d6b3fb7.png)

2021-12-11 23:33 UTC, unfa commented
BTW, I'm testing what's the limit:
https://youtu.be/O39GyzSdZfc

It seems that if emissive sources are touching the screen border - sudden light energy increase is produced.
Maybe that could be tweaked?

2021-12-12 17:47 UTC, mrjustaguy commented
Is the Scene Geometry CSG Nodes? They Try disabling all gizmos and see if the geometry is still visible, or run the project..
I've noticed that it incorrectly uses in-Editor stuff in it's results, such as Skeletons, CSG node wireframes, etc...

2021-12-12 17:54 UTC, unfa commented
No, the scene geometry is imported from a GLTF exported from Blender. No CSG is used.

2021-12-12 19:50 UTC, clayjohn commented
@unfa The "wireframe" artifacts look like there may be an issue with your mesh normals along triangle edges. What does it look like when you use the "normal buffer" render mode from the perspective menu?

2021-12-13 13:29 UTC, unfa commented
The environment normal pass:
![image](https://user-images.githubusercontent.com/491704/145821237-70d16434-e01f-493b-b7aa-ed578ba595d4.png)

2022-01-04 08:08 UTC, reduz approved these changes

2022-01-04 09:00 UTC, akien-mga commented
Rebased locally to make sure that it still builds fine.

2022-01-04 09:00 UTC, merged

2022-01-04 09:00 UTC, akien-mga commented
Thanks!