Improve performance of editor grid redrawing
godotengine/godot pull request #51340
Opened 2021-08-06 22:57 UTC by RevoluPowered

This was noticed in the MacOS profiler and will apply to other platforms too:

[optimized before]
<img width="940" alt="Screenshot 2021-08-06 at 23 51 19" src="https://user-images.githubusercontent.com/748770/128578207-9349c281-6a1d-44e8-8321-d7f3f9957ee0.png">

[optimized after]
<img width="922" alt="Screenshot 2021-08-06 at 23 52 49" src="https://user-images.githubusercontent.com/748770/128578227-39e6cea4-9d83-432c-9f76-7c00aee20d57.png">

[unoptimized before]
<img width="928" alt="Screenshot 2021-08-06 at 23 04 49" src="https://user-images.githubusercontent.com/748770/128578272-4ef35c42-db7d-4faf-a875-f7568ca35494.png">

[unoptimized after]
<img width="889" alt="Screenshot 2021-08-06 at 23 08 55" src="https://user-images.githubusercontent.com/748770/128578291-6d7fa159-a706-4877-b974-666cbacbee68.png">

Most of us are deving on debug so will be nice to not have this taking up a lot of CPU.

2021-08-06 23:05 UTC, clayjohn reviewed
Woohoo a free millisecond every frame is always welcome

2021-08-07 02:49 UTC, RevoluPowered commented
latest improvement: significantly reduces cpu time spent on this task.

<img width="949" alt="Screenshot 2021-08-07 at 03 48 32" src="https://user-images.githubusercontent.com/748770/128585573-e64ecd53-4644-4ae3-95f0-dd9c542107d6.png">

2021-08-07 04:09 UTC, Chaosus commented
Can this be ported to master branch?

2021-08-07 15:06 UTC, RevoluPowered commented
> Can this be ported to master branch?

Yes, but I need to see if it has any discernible benefit :) one sec I'll check per figures with/without

2021-08-07 16:07 UTC, RevoluPowered commented
<img width="940" alt="Screenshot 2021-08-07 at 17 06 25" src="https://user-images.githubusercontent.com/748770/128606401-545d5762-7d6b-49ce-aa89-f13c1827611f.png">

This is the single process in 4.0 occupying a lot of CPU time so yes it will transfer over PR incoming :D

2021-08-08 15:19 UTC, RevoluPowered commented
4.0 PR is made and perf saving is awesome: #51399

2021-08-08 15:50 UTC, LightningAA requested changes

2021-08-08 15:50 UTC, LightningAA commented on editor/plugins/spatial_editor_plugin.cpp
> +		// cache these so we don't have to re-access memory.
```suggestion
		// Cache these so we don't have to re-access memory.
```
https://docs.godotengine.org/en/stable/community/contributing/code_style_guidelines.html#comment-style-guide

2021-08-08 15:50 UTC, LightningAA commented on editor/plugins/spatial_editor_plugin.cpp
> +Vector3 cumulativeMovement = Vector3();
```suggestion
Vector3 cumulative_movement = Vector3();
```

2021-08-08 16:48 UTC, RevoluPowered commented on editor/plugins/spatial_editor_plugin.cpp
> +Vector3 cumulativeMovement = Vector3();
Fixed

2021-08-08 16:48 UTC, RevoluPowered commented on editor/plugins/spatial_editor_plugin.cpp
> +		// cache these so we don't have to re-access memory.
Fixed

2021-08-08 16:57 UTC, RevoluPowered commented
TODO: Improve grid forward/backward redrawing

2021-08-08 19:12 UTC, LightningAA commented on editor/plugins/spatial_editor_plugin.cpp
> +		// cache these so we don't have to re-access memory.
... doesn't look fixed yet 🙂

2021-08-11 14:51 UTC, RevoluPowered commented
4.0 PR has an orthographic fix which should be ported

2021-08-16 23:07 UTC, RevoluPowered commented
closing this can just be cherrypicked from master

2021-08-16 23:07 UTC, closed without merging