Move cursor to edge of selection when moving caret left/right
godotengine/godot pull request #51502
Opened 2021-08-11 08:54 UTC by codecat

This is to mimic the behavior of many third party text editors. The reason it's not doing it when moving by word is due to that behavior being mostly the same on other editors.

The below example gifs show the change - pressing left arrow when there is a selection should move the caret to the start of the selection, and pressing right arrow should move it to the end of the selection. This also works when selecting multiple lines.

**Wrong behavior in Godot:**
![f517bfb3-ebae-4f86-8bf2-d64597743a68](https://user-images.githubusercontent.com/136534/128999401-3a370414-dc0f-4a0c-95aa-006fb07625a3.gif)

**Expected behavior in VSCode:**
![b6c9c313-f726-4deb-a321-026960fc3e9a](https://user-images.githubusercontent.com/136534/128999471-de830511-5c17-47d8-908f-67bc28139fcb.gif)

2021-08-11 10:49 UTC, KoBeWi approved these changes

2021-08-11 11:10 UTC, Paulb23 requested changes
Overall looks good, minor comment made inline.

2021-08-11 11:10 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +		cursor.column = selection.from_column;
Please don't set these directly, use `cursor_set_line` and `cursor_set_column`.

2021-08-12 08:04 UTC, Paulb23 approved these changes

2021-08-12 08:07 UTC, merged

2021-08-12 08:07 UTC, akien-mga commented
Thanks!

2021-08-12 14:45 UTC, akien-mga commented
This cannot be cherry-picked for `3.x` as the code changed too much since then. Feel free to make a dedicated PR for `3.x` if you want the feature there though :)