Rename LineShape2D to WorldMarginShape2D
godotengine/godot pull request #51636
Opened 2021-08-13 17:52 UTC by Calinou

The new name makes it more obvious that it acts as an infinite plane, and is consistent with its 3D counterpart (WorldMarginShape3D).

See https://github.com/godotengine/godot-proposals/issues/817.

2021-08-13 18:04 UTC, pouleyKetchoupp requested changes
Thanks for making this change!

2021-08-13 18:04 UTC, pouleyKetchoupp commented on servers/physics_2d/collision_solver_2d_sw.cpp
>  	if (p_shape_B->get_type() == PhysicsServer2D::SHAPE_LINE) {
In order to keep things consistent in the physics server, we should also rename these:
-`SHAPE_LINE` to `SHAPE_WORLD_MARGIN`
-`solve_static_line()` to `solve_static_world_margin()`
-`line` local variable to `world_margin`

2021-08-13 22:45 UTC, pouleyKetchoupp commented on servers/physics_3d/shape_3d_sw.h
> +SHAPE_WORLD_MARGIN, ///< plane:"plane"
Just one last nitpick: this file should only be changed as part of renaming the 3D version :)

2021-08-14 01:14 UTC, pouleyKetchoupp approved these changes

2021-08-14 07:36 UTC, merged

2021-08-14 07:36 UTC, akien-mga commented
Thanks!