auto-reload scripts with external editor
godotengine/godot pull request #51729
Opened 2021-08-16 10:06 UTC by yjh0502

2021-08-16 16:38 UTC, Paulb23 requested changes
`NOTIFICATION_WM_WINDOW_FOCUS_IN` not triggering is a bug see also #47176. Not sure it's worth adding workarounds for it.

2021-08-16 16:38 UTC, Paulb23 commented on editor/plugins/script_text_editor.cpp
> +		_live_auto_reload_running_scripts();
Should only call this if a script has been reloaded and `pending_auto_reload == false`

2021-08-17 05:11 UTC, yjh0502 commented
> `NOTIFICATION_WM_WINDOW_FOCUS_IN` not triggering is a bug see also #47176. Not sure it's worth adding workarounds for it.

Let's fix the bug first (ref: https://github.com/godotengine/godot/pull/51781). I'll update this PR after merging #51781

2021-08-17 08:34 UTC, yjh0502 commented
@Paulb23 I tried to address the issue you mentioned. Unfortunately I'm not good at naming, so please feel free to suggest another name :)

2021-08-17 12:30 UTC, Paulb23 commented
Looks good. No worries :) as far as naming goes perhaps `trigger_live_script_reload`?

2021-08-17 12:44 UTC, yjh0502 commented
> Looks good. No worries :) as far as naming goes perhaps `_trigger_live_script_reload`?

Thanks for your suggestion, I changed the name.

2021-08-17 12:45 UTC, Paulb23 approved these changes

2021-08-17 17:42 UTC, merged

2021-08-17 17:42 UTC, akien-mga commented
Thanks!

2021-08-18 01:33 UTC, rversteegen commented
Very pleased to see this fixed!

> Here's another patch for `3.x` branch. It also fixes error messages when script changed on external editor. (`Another resource is loaded from path` thing). I could create another PR if you prefer: https://gist.github.com/yjh0502/e2cb62f9216c953c8e54541199d7be09

Do I understand that this separate patch is needed to fix the error messages? Will this also get applied? Those errors are annoying and distracting.

2021-08-19 13:56 UTC, yjh0502 commented
@rversteegen The error message problem was already fixed on master branch, and I fixed the error message issue while back-porting this patch to 3.x branch, which is already merged. See also: https://github.com/godotengine/godot/pull/51828

2021-09-02 21:55 UTC, cptchuckles commented
This doesn't quite fix the issue I was having with the editor in #49298, particularly where export vars don't get updated after I save a script and return focus to the Godot editor, unless I close and re-open the scene.  My PR #49473 addresses that but it needs a review