Add simple explanation messages to some errors
godotengine/godot pull request #51853
Opened 2021-08-18 19:14 UTC by qarmin

This helps to find what exactly is wrong with bad code.

example from https://github.com/godotengine/godot/issues/50471#issuecomment-880581824

Before
```
ERROR: Condition "!method" is true. Returning: false
   at: is_builtin_method_vararg (core/variant/variant_call.cpp:1125)
```

After
```
ERROR: Cannot find "call_me" method in "Nil" class.
   at: is_builtin_method_vararg (core/variant/variant_call.cpp:1161)
```

2021-08-21 17:06 UTC, Ansraer requested changes
Just some small typos I spotted.

2021-08-21 17:06 UTC, Ansraer commented on core/variant/callable.cpp
Removed before what?

2021-08-21 17:06 UTC, Ansraer commented on core/variant/variant_utility.cpp
> +	ERR_FAIL_COND_MSG(utility_function_table.has(sname), "Function \"" + name + "\" already was registered as utility function.");
Imo this should be "[...] was already [...]"

2021-08-21 17:06 UTC, Ansraer commented on drivers/vulkan/vulkan_context.cpp
> +	ERR_FAIL_COND_MSG(err == VK_ERROR_OUT_OF_DEVICE_MEMORY, "Vulkan: Out of device memor!");
memory

2021-08-21 17:06 UTC, Ansraer commented on modules/navigation/godot_navigation_server.cpp
> +		ERR_FAIL_MSG("Trying to free invalid ID: " + itos(p_object.get_id()));
All the pther messages end with a dot.

2021-08-21 17:06 UTC, Ansraer commented on scene/3d/skeleton_3d.cpp
> +			ERR_FAIL_COND_MSG(bones[i].name == p_name, "Bone \"" + p_name + "\" already exists in Skeleton3D.");
Previously you used "sheleton", now "Skeleton3D". It would probably be better to use the same term.

2021-08-22 02:34 UTC, EricEzaM reviewed
I wrote these reviews a few days ago but forgot to submit.

2023-05-13 11:35 UTC, closed without merging