use bake method for NavigationMeshGenerator in Runtime
godotengine/godot pull request #51954
Opened 2021-08-21 15:49 UTC by thoced

Use bake with NavigationMeshGenerator in Runtime in Godot 3.x

Hello

The use of the Bake in NavigationMeshGenerator method did not work in runtime (because of EditorProgress which wants to display a message in runtime) but only in the editor (hint_editor). This fix allows you to generate navigationmesh directly in the runtime. This is very useful, in particular, when creating procedural or random level.

This patch had already been used by
DragonOfWar committed on Jan 19, 2020 but in version 3.3 it looks like this has been destroyed.

The system checks if the code is executed in the editor then the EditorProgress is used otherwise it is ignored

EditorProgress crashes the game in Runtime

Thanks

2021-08-21 21:45 UTC, LoipesMas commented on modules/recast/navigation_mesh_generator.h
> +#ifndef TOOLS_ENABLED
Shouldn't this be just `#else` instead?

2021-08-21 21:45 UTC, LoipesMas commented on modules/recast/register_types.cpp
> +#ifndef TOOLS_ENABLED
Same here

2021-08-21 21:59 UTC, thoced commented on modules/recast/navigation_mesh_generator.h
> +#ifndef TOOLS_ENABLED
Hello,
#else added
Thanks

2021-09-05 07:36 UTC, thoced commented
Hello, can you tell me what action I still need to take for this code to be verified ?

2021-09-20 13:42 UTC, lexferreira89 commented
It would be great to have this feature in Godot 3.x. Without the ability to bake navigation meshes during runtime, it's impossible to create certain kinds of games with Godot (RTS, City Builders, Simulation, etc). While we wait for Godot 4 and its new navigation system, allowing the bake function to be used during runtime would be a game changer. So could someone please take a look at this?

2021-09-20 14:21 UTC, Calinou commented on modules/recast/navigation_mesh_generator.cpp
> +	if (ep)
To follow the code style guidelines, please replace all instances of `if(ep)` with:

```
if (ep) {
```

2021-09-20 14:22 UTC, Calinou requested changes

2021-09-20 14:22 UTC, Calinou commented on modules/recast/navigation_mesh_generator.cpp
> +	if (ep)
To follow the code style guidelines, please replace all instances of `if(ep)` with:

```cpp
if (ep) {
```

Braces should now always be used for single-line `if` conditions.

2021-09-20 14:22 UTC, Calinou commented
While this change is useful, remember that it will increase the export templates' binary size due to the Recast module now being compiled in export templates. Binary sizes are especially important on mobile/web platforms, so users will have to compile custom export templates if they wish to keep the reduced binary sizes.

2021-09-20 18:18 UTC, thoced commented
Hello, Braces added in the code

2021-09-23 18:12 UTC, thoced commented
Hello, the test has not passed yet, could someone help me figure out what is missing in the code to pass the static checks?
 thank you

2021-09-23 18:50 UTC, Calinou commented
Copying from the CI log:

```diff
diff --git a/modules/recast/navigation_mesh_generator.cpp b/modules/recast/navigation_mesh_generator.cpp
index 10c9e2c..2d32ad1 100644
--- a/modules/recast/navigation_mesh_generator.cpp
+++ b/modules/recast/navigation_mesh_generator.cpp
@@ -297,7 +297,7 @@ void EditorNavigationMeshGenerator::_convert_detail_mesh_to_native_navigation_me
 }
 
 #ifdef TOOLS_ENABLED
-void EditorNavigationMeshGenerator::_build_recast_navigation_mesh(Ref<NavigationMesh> p_nav_mesh, 
+void EditorNavigationMeshGenerator::_build_recast_navigation_mesh(Ref<NavigationMesh> p_nav_mesh,
 		rcHeightfield *hf, rcCompactHeightfield *chf, rcContourSet *cset, rcPolyMesh *poly_mesh, rcPolyMeshDetail *detail_mesh,
 		Vector<float> &vertices, Vector<int> &indices , EditorProgress *ep = nullptr) {
 #else
@@ -462,7 +462,7 @@ void EditorNavigationMeshGenerator::_build_recast_navigation_mesh(Ref<Navigation
 	if (ep) {
 		ep->step(TTR("Converting to native navigation mesh..."), 10);
 	}
-#endif 
+#endif
 
 	_convert_detail_mesh_to_native_navigation_mesh(detail_mesh, p_nav_mesh);
 
@@ -492,11 +492,11 @@ void EditorNavigationMeshGenerator::bake(Ref<NavigationMesh> p_nav_mesh, Node *p
 		ep = memnew(EditorProgress("bake", TTR("Navigation Mesh Generator Setup:"), 11));
 		ep->step(TTR("Parsing Geometry..."), 0);
 	}
-#endif 
+#endif
 
 
 	ERR_FAIL_COND(!p_nav_mesh.is_valid());
-		
+
 	Vector<float> vertices;
 	Vector<int> indices;
 
diff --git a/modules/recast/navigation_mesh_generator.h b/modules/recast/navigation_mesh_generator.h
index afa919c..c3b9162 100644
--- a/modules/recast/navigation_mesh_generator.h
+++ b/modules/recast/navigation_mesh_generator.h
@@ -61,7 +61,7 @@ protected:
 	static void _build_recast_navigation_mesh(Ref<NavigationMesh> p_nav_mesh,
 			rcHeightfield *hf, rcCompactHeightfield *chf, rcContourSet *cset, rcPolyMesh *poly_mesh,
 			rcPolyMeshDetail *detail_mesh, Vector<float> &vertices, Vector<int> &indices);
-#endif 
+#endif
 
 public:
 	static EditorNavigationMeshGenerator *get_singleton();

*** Aborting, please fix your commit(s) with 'git commit --amend' or 'git rebase -i <hash>'
```

You need to remove trailing whitespace at the end of some lines. I recommend configuring your editor to do so automatically.

2021-09-27 14:28 UTC, lexferreira89 commented
Hi! I just wanted to thank thoced for all his work in this PR. Do you guys think it's still possible for this feature to be included in the next release? Sorry if I'm being annoying!

2021-10-03 12:46 UTC, thoced commented
Hello everyone
What is left for me to do now?
Thank you

2021-10-05 13:51 UTC, LoipesMas commented
As Calinou mentioned, all commits must be squashed to a single one before the PR can be merged. 
[Here are the instructions on how to do it. ](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase)

2021-10-20 09:00 UTC, akien-mga commented
> "Cannot rebase: You have unstaged changes.
Please commit or stash them. "

This means that you have local changes to files which have not been committed. You either need to commit them, or discard them, before you can do operations on the Git history. You can also "stash them" with `git stash`, which puts them away, and you can recall them with `git stash pop` later on.

You can see what changes you have pending with `git status` and `git diff`. See https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#making-changes for some Git tips.

2021-11-05 16:14 UTC, closed without merging

2021-11-05 17:08 UTC, Calinou commented
Superseded by https://github.com/godotengine/godot/pull/54634.