Make Node editable_instance methods available to GDScript
godotengine/godot pull request #52000
Opened 2021-08-23 02:29 UTC by lyuma

Provides access to the existing is_editable_instance and set_editable_instance Node methods to GDScript.

These methods are needed to permit editor tooling to make scene changes to children of instanced scenes on behalf of the user. They do not create any editor dependencies which are not already present.

Note that some discussion has come up on other similar PRs such as #20569 (closed) and #48014 that methods which are "only relevant for the editor" should not be exposed on the Node api. However, some existing Node api methods are editor specific, including `is_displayed_folded` and `set_editor_description`.

This function has tangible usecases, and it is at present impossible to replicate its functionality within reason in another way. The api I choose to expose has remained stable for years, and doing so adds no new code to the engine. Pinging @reduz because this changes a class in core.

2021-08-23 02:34 UTC, lyuma commented
Side note about #46006 sence Remi brought it up in the previous PR. The approach in that PR is overcomplicated and actually loses some of the nuance about how editable children works -- that is, editable children is a state of a given node relative to its owner scene.

I believe exposing these apis as they are in C++ is best, as it preserves the nuance of this being a _relationship_ of one node to its owner, rather than just a boolean flag on the node itself.

2021-08-24 00:59 UTC, reduz requested changes

2021-08-24 00:59 UTC, reduz commented on doc/classes/Node.xml
> +				Returns [code]true[/code] if [code]node[/code] has editable children enabled relative to this node.
I would add in both documentation items that this is meant to be useful only for editor tooling, so they understand the methods do nothing outside the editor.

2021-08-24 11:31 UTC, reduz approved these changes

2021-08-24 11:31 UTC, merged

2021-08-24 12:55 UTC, mhilbrunner commented
Thanks for this :)

2022-01-29 16:20 UTC, Zireael07 commented
Has this been ported to 3.x? I'm finding I have a need of this in porting a project from 3.x to 4, and I can't figure out if it's in the 3.x branch or not...

2022-10-27 12:18 UTC, kleonc commented
> Has this been ported to 3.x? I'm finding I have a need of this in porting a project from 3.x to 4, and I can't figure out if it's in the 3.x branch or not...

@Zireael07 It hasn't been backported. Yet. I don't see anything against it, seems like it can be just cherry-picked (no need for a dedicated 3.x PR).

2022-12-01 04:17 UTC, timothyqiu commented
Cherry-picked for 3.6.