Print error message when await is not followed by signal or coroutine
godotengine/godot pull request #52085
Opened 2021-08-24 22:36 UTC by williamd67

When await was not followed by a signal or coroutine the GDScript parser would
crash.

This fix will check if await is followed by a signal or coroutine in case that
isn't true (element == nullptr) then an error message is printed.

This PR should fix #51560.

2021-08-27 17:37 UTC, mhilbrunner approved these changes
Built and tested successfully, this indeed fixes the crash. I also ran the tests and tested this in a project. Seems fine.

2021-08-27 17:46 UTC, Calinou requested changes

2021-08-28 14:36 UTC, Calinou commented
Looks good to me, please squash the commits together so we can merge this. See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) for instructions :slightly_smiling_face:

2021-08-28 15:48 UTC, williamd67 commented
Thanks @Calinou, I tried that yet when I try to (force) push the result, I get the following error:
```
To https://github.com/williamd67/godot.git
 ! [remote rejected]       fix-await-without-argument -> fix-await-without-argument (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/android_builds.yml` without `workflow` scope)
error: failed to push some refs to 'https://williamd67@github.com/williamd67/godot.git'
```
As far as I can see, was `.github/workflows/android_builds.yml` not changed on my branch.

I also checked my git configuration and don't see anything unusual, so it would be really appreciated if someone could support me with this error.

2021-08-28 15:56 UTC, fabriceci commented
> Thanks @Calinou, I tried that yet when I try to (force) push the result, I get the following error:
> 
> ```
> 
> To https://github.com/williamd67/godot.git
> 
>  ! [remote rejected]       fix-await-without-argument -> fix-await-without-argument (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/android_builds.yml` without `workflow` scope)
> 
> error: failed to push some refs to 'https://williamd67@github.com/williamd67/godot.git'
> 
> ```
> 
> As far as I can see, was `.github/workflows/android_builds.yml` not changed on my branch.
> 
> 
> 
> I also checked my git configuration and don't see anything unusual, so it would be really appreciated if someone could support me with this error.

You need to add the Workflow right into your github access token configuration

2021-08-28 16:15 UTC, williamd67 commented
Thanks that solved it.

2021-08-28 17:22 UTC, mhilbrunner approved these changes

2021-08-28 21:01 UTC, Calinou approved these changes
Thanks! Congratulations for your first merged pull request :tada:

2021-08-28 21:01 UTC, merged