Replace close icon with button in the Bezier editor
godotengine/godot pull request #52142
Opened 2021-08-26 23:22 UTC by NathanLovato

This is the first (baby) step towards implementing https://github.com/godotengine/godot-proposals/issues/3141.

As this is my first contribution to Godot, I wanted to start really small and make incremental improvements to the Bezier editor.

This PR replaces the X icon in the Bezier editor with a button with a label. It also puts the handle options and the button in a VBoxContainer.

![Screenshot from 2021-08-26 17-22-05](https://user-images.githubusercontent.com/12694995/131048304-7bd99b35-f924-420b-a877-ef31a6007d56.png)

2021-08-26 23:38 UTC, Ansraer requested changes

2021-08-26 23:42 UTC, YuriSizov submitted a review, later dismissed

2021-08-27 07:11 UTC, groud approved these changes
LGTM

2021-08-27 08:57 UTC, fire approved these changes
Nitpick: the variable initiation is not consistently in the header.

2021-08-27 08:58 UTC, merged

2021-08-31 13:48 UTC, seppoday commented
@NathanLovato Could you make a video on GDQuest about how you implemented that feature? I wanted to learn C++ and help improving Godot, but as always don't know where to start. Example like that would be really helpful! Thanks for considering my proposition :)