Change to using doubles in XR classes
godotengine/godot pull request #52177
Opened 2021-08-28 04:34 UTC by BastiaanOlij

Change to using doubles in our XR classes. Ran into some issues with GD Extensions but it seems like a sensible change anyway.

2021-08-30 01:00 UTC, m4gr3d requested changes

2021-08-31 09:02 UTC, BastiaanOlij commented on modules/mobile_vr/mobile_vr_interface.h
>  	float eye_height = 1.85;
Thanks! missed that one :)

2021-08-31 10:24 UTC, m4gr3d approved these changes

2021-09-05 01:54 UTC, BastiaanOlij commented
@reduz we think we fixed the issue in `godot-cpp` that breaks floats, but I think we should still make this change. Are you okay with me merging this?

2021-09-16 13:28 UTC, akien-mga approved these changes
Needs a rebase, otherwise seems good.

Not sure if we could find a convenient way to document when things are `float` or `double` by design, and when they can be configured with `real_t`.

2021-09-21 12:51 UTC, BastiaanOlij commented
@akien-mga that's a difficult one. Doubles may be overkill in this situation but seeing we're mostly dealing with plugins and with GD extensions plugins convert everything to doubles anyway (well parameters and return values at least) there is little to be gained using floats.

I don't have any solid ideas here, but it seems to me we should be using real_t where there is a definite performance or memory benefit when using float so we can reserve the use of double for high end hardware.

2021-09-21 13:16 UTC, merged

2021-09-21 13:17 UTC, akien-mga commented
Thanks!

2021-09-21 14:12 UTC, aaronfranke commented
> Not sure if we could find a convenient way to document when things are `float` or `double` by design, and when they can be configured with `real_t`.

In terms of doing calculations for XR, `real_t` makes the most sense. However, if it's easier to bind to GDExtension using doubles then it makes sense to use doubles with those external APIs, especially if it ends up being converted to Variant anyway.