Update usabilaty of the CustomPropertyEditor
godotengine/godot pull request #52218
Opened 2021-08-29 13:33 UTC by Gallilus

Structure button layout so there is no more overlap.

They where all added to self instead of containers making the CustomProperty editor unusable in master branche

https://user-images.githubusercontent.com/20573784/125508184-79167207-6b78-4f66-acf0-269120f27f2f.png
[mrp_property_input.zip](https://github.com/godotengine/godot/files/7072581/mrp_property_input.zip)

A separate PR will be made to fix the object selector.

PS: My thanks to @NoFr1ends  for showing the way
Fix: #49441

2021-10-02 14:21 UTC, Gallilus commented
Did a rebase for clarity now that #52222 is merged.
Property editor when trying to edit multiline, before.
![image](https://user-images.githubusercontent.com/20573784/135720287-47a79dd3-2190-41d9-8aa4-2796abc83819.png)
Property editor when trying to edit multiline, after.
![image](https://user-images.githubusercontent.com/20573784/135720028-be1d7d40-237d-4b0d-be55-2767879f7a77.png)

CC @Anaxan @fire

2021-11-03 19:21 UTC, Gallilus commented
> Could you center the "Close" button?

Nope it's now ordered using vBox and hBox

2021-11-03 20:28 UTC, fire approved these changes
The pr puts the contents of the panel into a container and uses it to size.

Looks good to me. Was done in a review in Discord with @Gallilus 

Edited: I remember that typically the close and the cancel swap positions in different operating systems. Maybe use on of the godot popup. Not familar with the design.

2021-11-03 23:24 UTC, YeldhamDev commented
> Nope it's now ordered using vBox and hBox

Couldn't you just set the alignment of the HBox to "center"?

2021-11-04 06:32 UTC, Gallilus commented
> Couldn't you just set the alignment of the HBox to "center"?

Ifire also suggested to maybe use a popup as it has different configurations to keep in line with other OS, maybe resizable.
There also is an issue when you select a color the window stays unexpectedly large.
And the editors need to be converted to the same editors that are used in the inspector.
I will make a new issue about that and then experiment with a few possible solutions.

So I hope I get Your blessing on this merge, @YeldhamDev?

2021-11-04 13:48 UTC, YeldhamDev requested changes

2021-11-04 13:48 UTC, YeldhamDev commented on editor/property_editor.cpp
> +	action_hboxes = memnew(HBoxContainer);
>So I hope I get Your blessing on this merge, @YeldhamDev?

```suggestion
	action_hboxes = memnew(HBoxContainer);
	action_hboxes->set_alignment(BoxContainer::ALIGN_CENTER);
```

Just add this and I can give you an approval. :wink:

2021-11-04 15:45 UTC, YeldhamDev approved these changes

2021-11-04 15:46 UTC, Gallilus commented
Thats Quick Thanks @YeldhamDev

2021-11-04 16:44 UTC, merged

2021-11-04 16:44 UTC, akien-mga commented
Thanks!