fix animation blend tree update on inspector property input count change
godotengine/godot pull request #52296
Opened 2021-08-31 22:22 UTC by kodiwills

Fixes #45437 and  #49375

Connects blend tree plugin to the `"tree_changed"` signal which is emited when input count is updated in the inspector. The signal then calls `_update_graph()` to refresh the blend tree graph.

Duplicate of #49404 
I did not realize that deleting the fork would cause me to be unable to edit the pull request after re-forking (I was not planning on contributing for a while). 

I was told I would have to make a new pull request. I apologize for any duplicated work on the maintainers.

2021-09-02 19:16 UTC, TokageItLab approved these changes

2021-12-02 09:07 UTC, TokageItLab requested changes
Now that the overhaul of the Godot 4.0 animation has settled down, I've aproved it once, but I reviewed it again.

2021-12-02 09:07 UTC, TokageItLab commented on scene/animation/animation_blend_tree.cpp
> +	emit_signal(SNAME("tree_changed"));
The `tree_changed` is an exaggeration. It is a signal to use when the number of nodes in the tree increases or decreases, so you should fix it using available local functions such as `_validate_property()` instead.

2021-12-02 09:07 UTC, TokageItLab commented on scene/animation/animation_blend_tree.cpp
> +	emit_signal(SNAME("tree_changed"));
Same above, maybe `_update_inputs()` is useful.

2021-12-02 09:07 UTC, TokageItLab commented on scene/animation/animation_blend_tree.cpp
> +	emit_signal(SNAME("tree_changed"));
Same above.

2021-12-02 09:44 UTC, TokageItLab commented
Oh, I understand. The reason why the drawing is not updated is because `AnimationNode` is just a resource and its parent, `AnimationBlendTree`, needs to do the redrawing.In other words, updating only the parameters of `AnimationNode` will not update the drawing.

However, `tree_changed` is still an exaggeration. If we subscribe to it, for example, it would be strange to have `tree_changed` fire when the number of inputs to `NodeTransition` goes up or down, so you should avoid it.

So, I think the correct way is to implement a `public function to update individual containers' or a `public function to set a dirty flag for each container and redraw only dirty containers' in `AnimationBlendTree` and call it.

2022-08-25 17:42 UTC, mhilbrunner commented
cc @TokageItLab @SaracenOne Please assess whether this needs to be in 4.0 / in beta, thanks :)

2022-08-26 01:33 UTC, TokageItLab commented
It is not critical and does not need to be fixed before BETA, but it must be fixed before RC. We will need to discuss the right way for the fix with @reduz later.

2022-09-15 18:38 UTC, akien-mga commented
Superseded by #65196.

2022-09-15 18:38 UTC, closed without merging