Fix wrong folding behaviour of last block if containing comment
godotengine/godot pull request #52339
Opened 2021-09-02 12:16 UTC by jmb462

Fix #52326
Fix #52385

**Note : This first description is now obsolete. See comment here to new implementation : https://github.com/godotengine/godot/pull/52339#issuecomment-913032405**

### Issue description

When adding a comment in a method, any lines of code after the comment are not hidden when the method is folded.

### Fix proposal

As I can't find a case where it won't be OK, I suggest to ignore comment at same or higher indentation level as a cause of end folding condition.

### Before

![fold_bug](https://user-images.githubusercontent.com/3649998/131841255-7d42f569-aa48-4f66-9811-ca87ea8260a0.gif)

### After

![indented](https://user-images.githubusercontent.com/3649998/131841324-e253dbdd-37e4-4811-b503-7513ee6eb552.gif)

2021-09-02 17:29 UTC, Paulb23 requested changes
This check is to handle the second case in the issue where the comment or string does not follow the indent, but despite that should still be folded.

2021-09-02 19:02 UTC, jmb462 commented
@Paulb23 Do you mean this case ? 

![unindented](https://user-images.githubusercontent.com/3649998/131899636-dc501291-9e72-4305-b91b-6ddcbe15c9a1.gif)

Neither the current code in master nor my PR fold after the comment in that case.
I could modify to deal with it.

Or do you mean another case ?

2021-09-02 20:01 UTC, Paulb23 commented
> Do you mean this case ?

Yes.

2021-09-03 14:00 UTC, name-here commented
I think expected behavior would be to end folding on a comment *only* if the comment is at the end of the indented block (all *code* after it is less indented), and the comment is less indented than the block you're folding.  Someone doing their commenting in a funky way (say, `#[tab][tab] [comment]` instead of `[tab][tab] #[comment]` shouldn't reasonably mess up folding.  The exception for less-indented comments at the end of folding code blocks won't *always* match user intention, but I think it's the best we can do without reading the user's mind.

2021-09-03 17:23 UTC, jmb462 commented
@name-here Could you post a short script example that illustrate the case and what would be the expected behaviour.

I'm comparing with folding in visual studio / vscode or other code editor to try to find a "standard" behavior.

2021-09-04 20:00 UTC, jmb462 commented
The bug wasn't correctly identified in the issue.
It was not just a problem with comments but more with end of script : The end of script doesn't fold if there is a comment in this folded block.

So first fix proposed here is obsolete.

I force pushed the new way to fix the issue.

### Identified cause
The parse of the script never catches the case were the folded block contains a comment and is the last block of script. (end_line variable remain at last comment index instead of last line of script).

### Fix proposed
Add a test to update end_line to the last line of script in that case.

Also, I've compared with the folding behaviour of VS, VSCode and SublimeText.
All these editors don't folder the last empty line of block to keep a space between the folded block and the following block.
Seems to be standard behavior and more readable I think.

### Before

You can see that the first and second function are the same. But the one at the end of script doesn't fold correctly.
And no space is keep between folded function and the following one.
![buged](https://user-images.githubusercontent.com/3649998/132106501-39cedb32-034b-4df6-8627-553fa5e4b224.gif)

### After

The two blocks folds correctly. An empty line is kept unfolded after folded block.
![fixed](https://user-images.githubusercontent.com/3649998/132106556-6932672d-fd03-4b69-875c-57f6545a2087.gif)

2021-09-05 09:51 UTC, Paulb23 requested changes
Looks good, couple small changes to make it a little clearer.

As an aside, might be worth closing #52386 and just having this one as it should fix both issues.

2021-09-05 09:51 UTC, Paulb23 commented on scene/gui/code_edit.cpp
> +	int last_line = get_line_count() - 1;
Would suggest renaming this to `line_count` or  `text_size` to be little clearer. Could also make it `const`.

2021-09-05 09:51 UTC, Paulb23 commented on scene/gui/code_edit.cpp
> -
Would keep this blank line.

2021-09-05 09:51 UTC, Paulb23 commented on scene/gui/code_edit.cpp
> +				}
Nitpick: 
```suggestion
				end_line = i;
				if (get_line(i).strip_edges().size() == 0) {
					end_line--;
				}
```

2021-09-05 09:51 UTC, Paulb23 commented on scene/gui/code_edit.cpp
> +				}
Nitpick:
```suggestion
				/* Keep an empty line unfolded if any */
				end_line = i - 1;
				if (get_line(i - 1).strip_edges().size() == 0 && i - 2 > p_line) {
					end_line--;
				}
```

2021-09-05 10:16 UTC, jmb462 commented on scene/gui/code_edit.cpp
> -
This change was unintentionnal. Sorry.

2021-09-05 10:17 UTC, jmb462 commented
Thanks for the help.
Proposed changes has been applied.

I'm closing other PR as you suggested.

2021-09-05 10:31 UTC, Paulb23 approved these changes

2021-09-05 10:36 UTC, jmb462 commented
I've just added ``const`` to last_line variable declaration after your approval.

2021-09-07 18:39 UTC, mhilbrunner approved these changes

2021-09-07 18:40 UTC, merged

2021-09-07 18:40 UTC, mhilbrunner commented
Thanks!