Fix out of bounds error when folding last line of code
godotengine/godot pull request #52386
Opened 2021-09-03 21:56 UTC by jmb462

Fixes #52385

### Issue ;

Folding a block of code at the end of a script file causes an out of bonds error in the console.

### Identified cause : 

Error in folding loop. ``i`` should never be equal to endline. Valid line index goes from ``0`` to ``get_line_count() -1``

https://github.com/godotengine/godot/blob/18c0f0b3ba46caf3f6dda401362bc5993eaf7f8d/scene/gui/code_edit.cpp#L1433-L1435

### Fix proposal

Simply replace ``<=`` compare operator by ``<`` .

### Result

No more error. Folding OK.

2021-09-03 22:20 UTC, Paulb23 requested changes
We're taking `- 1` in the loops for this,  instead should `- 1` when we first set it on line `1403`.

2021-09-03 22:28 UTC, jmb462 commented
If I understand, you prefer keeping ``<=`` in the loop but changing line 1403 to
```int end_line = get_line_count();```

I can do that but I don't really understand why. Other loops ends with test ``< get_line_count()`` not ``<= get_line_count() -1`` (l. 1411, l 1420, ...)
That's why I choose this way.

2021-09-03 22:54 UTC, Paulb23 approved these changes

2021-09-04 06:58 UTC, mhilbrunner approved these changes

2021-09-04 07:00 UTC, mhilbrunner commented
Built & tested, confirmed to fix the issue. :) Thank you!

2021-09-05 10:21 UTC, jmb462 commented
Even if approved, I'm closing this PR cause changes are included my the other PR about code folding : #52339

2021-09-05 10:21 UTC, closed without merging