Fix global properties setters and add global skew for node2d
godotengine/godot pull request #52415
Opened 2021-09-05 09:34 UTC by deakcor

The introduction of the skew makes the setter of global properties false in some cases.

> For example, a parent has `local skew of 45° and scale of (1,1)`, and a child with `local skew of -45° and scale of (1,1)`.
> The child will have a global scale of (1,0.5). If we want to put `global scale of (1,1)`, the current global method will set the local scale with `new_global_scale/parent_global_scale` so `(1,1)/(1,1) = (1,1)`. So the global scale will stay `(1,0.5)`.

Same wrong behavior can be reproduced with the rotation. So fixed the setters of global rotation and scale.

Also added global skew property and added const when possible.

2021-12-23 18:09 UTC, KoBeWi commented
Do you have any reproduction project where the wrong behavior can be easily observed?

2022-04-13 18:42 UTC, deakcor commented
> Do you have any reproduction project where the wrong behavior can be easily observed?

Hey @KoBeWi, sure, please try this code

```
func _ready():
	var parent_sprite:=Sprite2D.new()
	parent_sprite.skew=PI/4
	parent_sprite.texture=preload("res://icon.png")
	add_child(parent_sprite)
	var child_sprite:=Sprite2D.new()
	child_sprite.texture=preload("res://icon.png")
	parent_sprite.add_child(child_sprite)
	child_sprite.skew=-PI/5
	child_sprite.position=Vector2.ONE*64
	print(child_sprite.global_scale)
	child_sprite.global_scale=Vector2.ONE
	print(child_sprite.global_scale)
```

In current godot 4 ver, the global scale will not be (1,1).

2022-04-14 06:50 UTC, Zireael07 commented
What is 'current Godot 4 ver'? Alpha 6? Some hash off master?

2022-04-14 07:36 UTC, fabriceci commented
I tried the snippet with the current master #[3b57c2c](https://github.com/godotengine/godot/commit/3b57c2ce6b81c39ae552b69633e4122117e07a19)
```
func _ready():
	var parent_sprite:=Sprite2D.new()
	parent_sprite.skew=PI/4
	add_child(parent_sprite)
	
	var child_sprite:=Sprite2D.new()
	child_sprite.skew=-PI/4
	parent_sprite.add_child(child_sprite)

	print(child_sprite.global_scale) #  output : (1, 0.541196)
	child_sprite.global_scale=Vector2.ONE
	print(child_sprite.global_scale) # output : (1, 0.541196)
```

After this PR

```
	print(child_sprite.global_scale) #  output : (1, 0.541196)
	child_sprite.global_scale=Vector2.ONE
	print(child_sprite.global_scale) # output : (1, 1)
```

2022-05-21 16:31 UTC, aaronfranke commented on scene/2d/node_2d.cpp
> +		new_transform = pi->get_global_transform().affine_inverse() * new_transform;
It seems that GitHub's syntax highlighting doesn't like `pi`, we should change it to `parent`:

```suggestion
	CanvasItem *parent = get_parent_item();
	if (parent) {
		Transform2D new_transform = get_global_transform();
		new_transform.set_skew(p_radians);
		new_transform = parent->get_global_transform().affine_inverse() * new_transform;
```

2022-05-22 11:08 UTC, deakcor commented
Applied the renaming of the variable and aligned in the other global setters. If everything is ok I will squash the commits.

2022-05-22 23:58 UTC, aaronfranke requested changes
I gave this a review, here are some notes:

* The behavior of this PR is 100% correct as far as I can tell. It works in any situation I can throw at it.
* This PR actually fixes a bug not just with skewing like mentioned in the OP. In the current master `set_global_rotation` does not work with non-uniform scaling either.
* The code in this PR is not as efficient as it could theoretically be, since it calculates an unnecessary origin vector.
  - ...but in order to optimize this while still having clean readable code we'd need to introduce a Basis2D type.
  - There is one small optimization we can do to make this more efficient, which is to calculate the parent's global transform once instead of twice.
  - It can always be optimized later if needed, with my small tweak I think we can call this good for now at least.
* Documentation and test cases would be appreciated.

2022-05-22 23:58 UTC, aaronfranke commented on doc/classes/Node2D.xml
> +		</member>
Documentation is missing.

2022-05-22 23:58 UTC, aaronfranke commented on scene/2d/node_2d.cpp
> +		new_transform = parent->get_global_transform().affine_inverse() * new_transform;
```suggestion
		Transform2D parent_global_transform = parent->get_global_transform();
		Transform2D new_transform = parent_global_transform * get_transform();
		new_transform.set_rotation(p_radians);
		new_transform = parent_global_transform.affine_inverse() * new_transform;
```

2022-05-22 23:58 UTC, aaronfranke commented on scene/2d/node_2d.cpp
> +		new_transform = parent->get_global_transform().affine_inverse() * new_transform;
```suggestion
		Transform2D parent_global_transform = parent->get_global_transform();
		Transform2D new_transform = parent_global_transform * get_transform();
		new_transform.set_skew(p_radians);
		new_transform = parent_global_transform.affine_inverse() * new_transform;
```

2022-05-23 00:01 UTC, aaronfranke commented on scene/2d/node_2d.cpp
> +		new_transform = parent->get_global_transform().affine_inverse() * new_transform;
```suggestion
		Transform2D parent_global_transform = parent->get_global_transform();
		Transform2D new_transform = parent_global_transform * get_transform();
		new_transform.set_scale(p_scale);
		new_transform = parent_global_transform.affine_inverse() * new_transform;
```

2022-05-23 14:52 UTC, aaronfranke reviewed
Should be good after the below and a squash.

2022-05-24 07:52 UTC, deakcor commented
Commits squashed, all should be good now. I tried to make a test but impossible to let it works.

2022-05-24 15:51 UTC, aaronfranke approved these changes

2022-06-10 07:45 UTC, reduz approved these changes

2022-06-10 07:49 UTC, merged

2022-06-10 07:49 UTC, akien-mga commented
Thanks!