Tiles renames/bugfixing and documentation
godotengine/godot pull request #52433
Opened 2021-09-06 10:44 UTC by groud

This PR is mainly fills in the documentation for tiles-related stuff. However, while working on it, I spotted a bug and a few things to rename, so I put it into the PR too. 

This is a draft for now as I need https://github.com/godotengine/godot/pull/52277 to be merged first.

2021-09-08 10:26 UTC, mhilbrunner requested changes
Looks good. A few nitpicks below. :)

2021-09-08 10:26 UTC, mhilbrunner commented on doc/classes/TileData.xml
> +				Returns if one-way collisions are enabled for the polygon at index [code]polygon_index[/code] for TileSet physics layer with index [code]layer_id[/code].
```suggestion
				Returns whether one-way collisions are enabled for the polygon at index [code]polygon_index[/code] for TileSet physics layer with index [code]layer_id[/code].
```

2021-09-08 10:26 UTC, mhilbrunner commented on doc/classes/TileData.xml
> +				Set the points of the polygon at index [code]polygon_index[/code] for TileSet physics layer with index [code]layer_id[/code].
```suggestion
				Sets the points of the polygon at index [code]polygon_index[/code] for TileSet physics layer with index [code]layer_id[/code].
```

2021-09-08 10:26 UTC, mhilbrunner commented on doc/classes/TileData.xml
> +				Set the polygons count for TileSet physics layer with index [code]layer_id[/code].
```suggestion
				Sets the polygons count for TileSet physics layer with index [code]layer_id[/code].
```

2021-09-08 10:26 UTC, mhilbrunner commented on doc/classes/TileData.xml
> +				Set the tile's custom data value for the TileSet custom data layer with name [code]layer_name[/code].
```suggestion
				Sets the tile's custom data value for the TileSet custom data layer with name [code]layer_name[/code].
```

2021-09-08 10:26 UTC, mhilbrunner commented on doc/classes/TileData.xml
> +				Set the tile's custom data value for the TileSet custom data layer with index [code]layer_id[/code].
```suggestion
				Sets the tile's custom data value for the TileSet custom data layer with index [code]layer_id[/code].
```

2021-09-08 10:26 UTC, mhilbrunner commented on doc/classes/TileData.xml
> +				Set the navigation polygon for the TileSet navigation layer with index [code]layer_id[/code].
```suggestion
				Sets the navigation polygon for the TileSet navigation layer with index [code]layer_id[/code].
```

2021-09-08 10:26 UTC, mhilbrunner commented on doc/classes/TileData.xml
> +				Set the occluder for the TileSet occlusion layer with index [code]layer_id[/code].
```suggestion
				Sets the occluder for the TileSet occlusion layer with index [code]layer_id[/code].
```

2021-09-08 10:26 UTC, mhilbrunner commented on doc/classes/TileSetScenesCollectionSource.xml
> +		Exposes a set of scenes as tiles for a TileSet resource.
```suggestion
		Exposes a set of scenes as tiles for a [TileSet] resource.
```

2021-09-08 11:14 UTC, groud commented
Alright, I addressed the feedback and added the missing documentation for TileSetScenesCollectionSource I forgot.
Let me know if anything is still missing :).

2021-09-08 11:23 UTC, mhilbrunner approved these changes
Looks good now. :)

2021-09-10 14:15 UTC, KoBeWi approved these changes

2021-09-10 14:32 UTC, merged

2021-09-10 14:32 UTC, mhilbrunner commented
Thanks!