#52499 Fix parsing 'preload': skip newlines after '(' and before ')'
godotengine/godot pull request #52521
Opened 2021-09-09 20:51 UTC by kdiduk

This PR fixes the issue #52499. The fix is very simple and safe - we just skip newline tokens if we encounter them after the '(' and before the ')'.
This fix is intended only for 3.4 version. The version 4.0 doesn't have this problem since all the parsing code is rewritten.

2021-09-20 11:49 UTC, vnen commented
I feel like this is not the proper way to go in this case. If you have something like this:

```gdscript
preload(
    "res://"
    +
    "my_resource.tres"
)
```

It won't work with this fix since it only skip newlines right after the opening parenthesis and before the closing one. I know it's a weird construct but functions allow newlines anywhere in the argument expression, so preload should do the same.

A way to solve this would be to just increment and decrement the `parenthesis` variable like it's done when finding parentheses in the expression:

https://github.com/godotengine/godot/blob/673612f1b726b605e44522213ffcfddd48266792/modules/gdscript/gdscript_parser.cpp#L270

2021-10-05 10:10 UTC, akien-mga requested changes
Needs changes as advised by @vnen.

2021-10-05 21:13 UTC, kdiduk commented
I've updated the PR.
@vnen thank you very much for your help!

2021-10-06 07:52 UTC, akien-mga commented
Tested with a weird case, it seems to work well :+1: 

```gdscript
const enemy_class = preload(
	
	"res://" +
	
	# Hello :)
	
	"enemies/enemy.gd"
	# Hi!
	)
```

2021-10-06 07:52 UTC, akien-mga approved these changes

2021-10-06 08:13 UTC, merged

2021-10-06 08:13 UTC, akien-mga commented
Thanks!