Clearer erase_section_key and erase_section explainations.
godotengine/godot pull request #52646
Opened 2021-09-13 22:39 UTC by georgespatton

To make clear documentation based on this: https://github.com/godotengine/godot/issues/52645

2021-09-13 22:42 UTC, Calinou requested changes, later dismissed

2021-09-13 22:42 UTC, Calinou commented on doc/classes/ConfigFile.xml
> +				Deletes the specified section along with all the key-value pairs inside. Raises an error if the section does not exist.  After calling this method, make sure to call the save() method to write th
```suggestion
				Deletes the specified section along with all the key-value pairs inside. Raises an error if the section does not exist. After calling [method erase_section], make sure to call [method save] method to write the change to the file.
```

2021-09-13 22:42 UTC, Calinou commented on doc/classes/ConfigFile.xml
> +				Deletes the specified key in a section. Raises an error if either the section or the key do not exist.  After calling this method, make sure to call the save() method to write the change to the f
```suggestion
				Deletes the specified key in a section. Raises an error if either the section or the key do not exist. After calling [method erase_section_key], make sure to call [method save] method to write the change to the file.
```

2021-09-14 09:11 UTC, mhilbrunner commented
It should be either `to call [method save]`, not `to call [method save] method` in both, or "to call _the_ [method save] method".

Also the commits need to be squashed into one.

Looks good otherwise, thanks :)

2021-09-14 10:28 UTC, akien-mga commented
Isn't this something which should be explained in the main description of the class? AFAIK, any operation that mutates the ConfigFile only changes what is loaded in memory - if you want to apply any change to a file (not just section removals), you have to `save()`.

2021-09-14 11:46 UTC, georgespatton commented
> Isn't this something which should be explained in the main description of the class? AFAIK, any operation that mutates the ConfigFile only changes what is loaded in memory - if you want to apply any change to a file (not just section removals), you have to `save()`.

Thanks for the feedback.  I have updated the PR with the explanation in the main description of the class.

2021-09-14 11:52 UTC, akien-mga commented
Looks great! Could you squash the commits together? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

2021-09-14 11:54 UTC, akien-mga commented
Also note that the Git identity you used to author that last commit (probably with local Git) is not configured properly, as your email is `root@localhost`, which is not valid (see header of https://github.com/godotengine/godot/commit/4f670e0d6d25444afe5931164595a17baa47f947.patch).

You might want to change it to a valid email linked to your GitHub account to get proper attribution for your commits (see https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address, which also has an option for a "no-reply" email if you prefer).

2021-09-14 12:08 UTC, georgespatton commented
> Also note that the Git identity you used to author that last commit (probably with local Git) is not configured properly, as your email is `root@localhost`, which is not valid (see header of https://github.com/godotengine/godot/commit/4f670e0d6d25444afe5931164595a17baa47f947.patch).
> 
> You might want to change it to a valid email linked to your GitHub account to get proper attribution for your commits (see https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address, which also has an option for a "no-reply" email if you prefer).

I think I did this right.  Let me know if there are any additional adjustments that you would like to see.

2021-09-14 12:49 UTC, akien-mga commented
It's not right yet, as you can see in the PR there are now 6 commits:

![Screenshot_20210914_144815](https://user-images.githubusercontent.com/4701338/133260304-d7893a49-bed3-469f-a8b9-51fea3518aa2.png)

Most likely, after squashing the commits you did not use `git push --force` to update the remote branch, but you pulled/merged the remote branch first to resolve the history conflicts.

I'll push an update to resolve the situation as it's a bit tricky now if you're not familiar with Git rebase.

2021-09-14 12:53 UTC, akien-mga approved these changes
Looks good to me.

I squashed the commits and edited the commit log (and wording) to make changes more explicit.

2021-09-14 14:22 UTC, merged

2021-09-14 14:22 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2021-09-14 14:26 UTC, georgespatton commented
> Thanks! And congrats for your first merged Godot contribution

Thanks for the assist.  I'll not be such a noob next commit.

2021-09-15 23:32 UTC, mhilbrunner commented
No worries, git is a complicated beast and we all needed to learn it :)

2021-09-21 13:29 UTC, akien-mga commented
Cherry-picked for 3.4.

2021-09-21 13:29 UTC, akien-mga commented
Cherry-picked for 3.3.4.