[3.x] Add a node configuration warning using NinePatchRect's Tile or Tile Fit modes in GLES2
godotengine/godot pull request #52728
Opened 2021-09-15 21:28 UTC by jmb462

Fixes #52708

### Issue fixed :

The options "Tile" and "Tile Fit" of NinePatchRect are without effect with GLES2 driver but there isn't any node configuration warning.

### Fix proposal

Add a node configuration warning when using one of these modes with GLES2 driver.

### Notes
As it's the first time I use NodeConfigurationWarning, I'm not sure about some points : 

- I only check ``ProjectSettings::get_singleton()->get("rendering/quality/driver/driver_name")`` but not the fallback_to_gles2 to avoid false positive warning.

- When modifying the Tile mode, warning icon update only if we click outside the inspector. Don't know if it's the attented behavior or if I need to call an update function.

- As it's the only warning for that node, not sure that this test is needed (seems to be used in other nodes warning) 
```
	if (!warning.empty()) {
				warning += "\n\n";
			}```

2021-09-16 06:24 UTC, Calinou commented
> When modifying the Tile mode, warning icon update only if we click outside the inspector. Don't know if it's the attented behavior or if I need to call an update function.

Call `update_configuration_warning()` within the `set_tile_mode()` functions (after the property itself has been set).

2021-09-16 11:04 UTC, jmb462 commented
> To resolve this, call `update_configuration_warning()` within the `set_tile_mode()` functions (after the property itself has been set).

Thanks. I've added the update calls.

2021-09-16 19:54 UTC, Calinou requested changes

2021-09-16 19:54 UTC, Calinou commented on scene/gui/nine_patch_rect.cpp
> +	if (ProjectSettings::get_singleton()->get("rendering/quality/driver/driver_name") == "GLES2") {
```suggestion
	if (String(GLOBAL_GET("rendering/quality/driver/driver_name")) == "GLES2") {
```

2021-09-16 19:54 UTC, Calinou commented on scene/gui/nine_patch_rect.cpp
> +			warning += TTR("The Tile and Tile Fit options for Axis Stretch properties are only effective when using the GLES3 rendering backend.");
```suggestion
			warning += TTR("The Tile and Tile Fit options for Axis Stretch properties are only effective when using the GLES3 rendering backend.\nThe GLES2 backend is currently in use, so these modes will act like Stretch instead.");
```

2021-09-17 04:30 UTC, jmb462 commented on scene/gui/nine_patch_rect.cpp
> +			warning += TTR("The Tile and Tile Fit options for Axis Stretch properties are only effective when using the GLES3 rendering backend.");
Thanks. Requested changes done.

2021-09-17 16:55 UTC, Calinou approved these changes

2021-09-17 18:22 UTC, merged

2021-09-17 18:22 UTC, akien-mga commented
Thanks!