change complete_exisitng_color to a visible one
godotengine/godot pull request #52873
Opened 2021-09-20 13:39 UTC by nonunknown

The current autocomplete color isnt visible as shown here: #52819

now its this way:
![image](https://user-images.githubusercontent.com/58845030/134012100-deaa8271-9587-4ab6-9ebd-624fee58cb9b.png)

2021-09-20 13:50 UTC, pycbouh requested changes

2021-09-20 13:50 UTC, pycbouh commented on editor/editor_settings.cpp
> -	_initial_set("text_editor/theme/highlighting/completion_existing_color", Color(0.13, 0.87, 0.87, 0.87));
This just looks like a typo. I would just fix it without completely changing the value.

2021-09-20 13:50 UTC, pycbouh commented on scene/resources/default_theme/default_theme.cpp
> -	theme->set_color("completion_existing_color", "CodeEdit", Color(0.87, 0.87, 0.87, 0.13));
I don't think there is any need to change the default theme either way, it's an okay default.

2021-09-21 10:56 UTC, nonunknown commented
@pycbouh there's something more needed to be done, in order to get this PR approved?

2021-09-21 11:08 UTC, akien-mga commented
The commits need to be squashed into one, and the commit message of the resulting commit should be made a bit more explicit, e.g. "Fix alpha typo in code completion color".

2021-09-21 12:11 UTC, closed without merging

2021-09-21 16:03 UTC, KoBeWi commented
Superseded by #52901