C# scripts reload in editor fixed
godotengine/godot pull request #52883
Opened 2021-09-21 00:43 UTC by Germanrc

Co-authored-by: Michael Bickel <mib@developium.net>

This fixes the problem when trying to run the same script more than once in the editor (see #48590). 
Originally started by in @dazKind in #48627. Changes were required to the merge the PR but unfortunatly he did not have the time to make them and the problem was never fixed. So I made the changes that were asked in his PR.

2021-09-21 01:04 UTC, Calinou requested changes, later dismissed

2021-09-21 01:04 UTC, Calinou commented on modules/mono/csharp_script.cpp
> +	if(!reload_invalidated) return OK;
To follow the new code style guidelines, don't use single-line `if` statements, add braces and remove the blank line at the beginning:

```suggestion
	if (!reload_invalidated) {
		return OK;
	}
```

2021-09-21 01:04 UTC, Calinou commented on modules/mono/csharp_script.cpp
> +	reload_invalidated = false; /* In the case of C#, reload doesn't really do any script reloading. That's done separately via domain reloading. */
We prefer `//` comments to `/* */` comments:

```suggestion
	// In the case of C#, reload doesn't really do any script reloading.
	// That's done separately via domain reloading.
	reload_invalidated = false;
```

2021-09-21 12:24 UTC, Germanrc commented
Done! Code style should be fixed now.

2021-09-21 20:39 UTC, neikeq approved these changes

2021-09-21 21:02 UTC, akien-mga commented
Looks good to me, but maybe you could amend the commit message to remove the mention to clang-format - passing style checks is the rule, not the exception, so is not worth mentioning in the commit message.

2021-09-24 06:18 UTC, Germanrc commented
Any additional changes needed to merge this PR? It has been a few days since I commited the required changes. I am guessing this is several commits behind the official repo branch by now.

2021-09-24 06:31 UTC, akien-mga approved these changes

2021-09-24 06:33 UTC, merged

2021-09-24 06:34 UTC, akien-mga commented
Thanks!

This should likely be changed in `master` too?

2021-09-24 06:38 UTC, Germanrc commented
Yes. I did not use master branch because C# is quite unstable right now, but it would be nice to have the fix in godot 4 too.

2021-09-24 22:28 UTC, neikeq commented
Whoops, I didn't realize this was made against the 3.x branch. It's needed in master too, but no hurries. I'll add it to my list just in case to not forget.

2021-09-29 06:28 UTC, akien-mga commented
Cherry-picked for 3.3.4.