check if 'shortcut' in InputEventShortcut is valid
godotengine/godot pull request #53058
Opened 2021-09-25 14:45 UTC by LATRio

fixes #52191

2021-09-25 23:17 UTC, EricEzaM approved these changes

2021-09-25 23:19 UTC, EricEzaM requested changes, later dismissed
This is going to throw an error if the shortcut *is* valid. Shortcut->is_null() should be used instead, to short circuit the method and return early if the shortcut reference is not valid.

2021-09-26 02:08 UTC, LATRio commented
fixed

2021-09-26 06:38 UTC, akien-mga approved these changes

2021-09-26 06:38 UTC, merged

2021-09-26 06:38 UTC, akien-mga commented
Thanks!