Document how to use degrees with `sin()` and `cos()`
godotengine/godot pull request #53178
Opened 2021-09-28 14:34 UTC by Calinou

This was already present in the `tan()` method description.

This also adds `var` keywords to code samples to make them valid GDScript.

This closes https://github.com/godotengine/godot/issues/53158.

2021-09-28 14:43 UTC, akien-mga approved these changes

2021-09-28 15:00 UTC, kleonc requested changes

2021-09-28 15:00 UTC, kleonc commented on doc/classes/@GlobalScope.xml
>  				Returns the arc tangent of [code]x[/code] in radians. Use it to get the angle from an angle's tangent in trigonometry: [code]atan(tan(angle)) == angle[/code].
Just catched my eye (you might wanna fix it in here too): note that

> [code]atan(tan(angle)) == angle[/code]

isn't true in general, it's true only for `angle` in [-PI / 2, PI / 2] range.

2021-09-28 22:14 UTC, aaronfranke commented on doc/classes/@GlobalScope.xml
> +				cos(rad2deg(90) # Returns 0.0
Yes, should be `deg2rad`. Also, why were the prints removed?

2021-09-28 22:45 UTC, Calinou commented on doc/classes/@GlobalScope.xml
> +				cos(rad2deg(90) # Returns 0.0
The prints were removed to be consistent with other `@GlobalScope` code samples. If we readd them here, we need to readd them everywhere.

2021-09-28 23:26 UTC, kleonc commented on doc/classes/@GlobalScope.xml
> +				If [code]x[/code] is between [code]-PI / 2[/code] and [code]PI / 2[/code] (inclusive), [code]atan(tan(angle))[/code] is equal to [code]angle[/code].
It should probably be either `x` or `angle` everywhere in that line.

2021-09-29 15:15 UTC, aaronfranke commented on doc/classes/@GlobalScope.xml
> +				cos(deg2rad(90)) # Returns 0.0
If the goal was to have alignment, the comments are not aligned. Although we could also just not have alignment and have each comment preceded by one space (I'm not sure which style is desired here).

2021-09-29 15:21 UTC, LightningAA commented on doc/classes/@GlobalScope.xml
>  				i = ceil(1.001) # i is 2
```suggestion
				i = ceil(1.001) # i is 2.0
```
Maybe for a different PR, but if `ceil` returns a float it should probably be `2.0`

2021-09-29 16:51 UTC, kleonc approved these changes

2021-09-29 20:56 UTC, merged

2021-09-29 20:56 UTC, akien-mga commented
Thanks!