[NET] Remove blocking network address resolution in connect_to_host in websockets
godotengine/godot pull request #53243
Opened 2021-09-30 03:27 UTC by jordo

This commit removes blocking address resolution in `connect_to_host` in websockets.  This is similar to what happens in HTTPClient.

Currently a few other peer's implementations of `connect_to_host` still include a blocking call to `resolve_hostname` which unfortunately can block in `getaddrinfo` for an unspecified amount of time.  This is not good, considering there is a good chance many projects are calling `connect_to_host` on the main engine thread.

This PR addresses one of the peers (websocket) with an resolving state, which is similar to what happens in HTTPClient.  

I'm hoping eventually we can clean up these connection status state enums into something shared among all the network classes, but until then this and the rest of the network classes `connect_to_host` implementations should follow what HttpClient does.  (Have an intermediate resolving state to avoid blocking in `connect_to_host`).  

As an aside, (as someone who's gone through Apple App review too many times), I'm pretty sure their test environment includes a laggy DNS response env.  I have seen app review bring this up a few time with different app submissions, and indeed our project was using the websocket `connect_to_host`, and ended up pausing the main thread for much too long waiting for a hostname to resolve.  This was easily confirmed with the iOS link conditioner, and setting a manual delay for dns resolution time.

2021-09-30 11:33 UTC, Faless requested changes
As mentioned multiple times, changes need to be PRed against the `master` branch first.

2021-09-30 15:25 UTC, jordo commented
https://github.com/godotengine/godot/pull/53262 for master

2021-09-30 17:25 UTC, jordo commented
fixes https://github.com/godotengine/godot/issues/53265 for websocket clients

2021-12-15 12:39 UTC, Faless submitted a review, later dismissed
I am deeply sorry for the very long review time, I have been sucked up by the work on the replication API.
This change looks okay, it is a bit of a mess that this has to be handled down in every peer separately, but it's definitely an improvement so I would merge this once the review comments are addressed.
Good work :+1:

2022-02-05 17:23 UTC, closed without merging