Removed blocking network address resolution in connect_to_host in web…
godotengine/godot pull request #53262
Opened 2021-09-30 15:24 UTC by jordo

Master pr for https://github.com/godotengine/godot/pull/53243 (untested)

2021-09-30 17:24 UTC, jordo commented
fixes https://github.com/godotengine/godot/issues/53265 for websocket clients

2021-12-15 12:45 UTC, Faless requested changes
I am deeply sorry for the very long review time, I have been sucked up by the work on the replication API.
This change looks okay, it is a bit of a mess that this has to be handled down in every peer separately, but it's definitely an improvement so I would merge this once the review comments are addressed.
Good work :+1:

2021-12-15 12:45 UTC, Faless commented on modules/websocket/wsl_client.h
> +	Vector<String> _original_protocols;
I don't understand why we need the `_original_protocols`.
It seems there is already the `_protocols` variable that could be used.

2021-12-15 12:45 UTC, Faless commented on modules/websocket/wsl_client.cpp
> +		// TODO custom extra headers (allow overriding this too?)
We can remove this TODO since we now support extra headers (was a leftover from the other PR I guess).

2022-02-05 17:23 UTC, closed without merging