Support arrays of StringName, NodePath and RID in mono
godotengine/godot pull request #53576
Opened 2021-10-08 16:54 UTC by raulsntos

Fixes #53362
Fixes #50661
Fixes #47621

Since these types don't inherit from `Godot.Object` they weren't supported in `mono_object_to_variant` which is used by tool exports.

2021-10-15 15:08 UTC, neikeq requested changes
~~Code looks good but this needs to be handled in `GDMonoField::set_value_from_variant` too:
https://github.com/godotengine/godot/blob/3f888966c0311a49541d6eb952b5a76d105f59d5/modules/mono/mono_gd/gd_mono_field.cpp#L48~~

2021-10-15 15:11 UTC, neikeq approved these changes
Never mind. Looks like the array implementation for fields was moved to `GDMonoMarshal::variant_to_mono_array` which this PR correctly implements.

2021-10-15 15:12 UTC, neikeq approved these changes

2021-10-15 15:34 UTC, merged

2021-12-11 06:30 UTC, pranshuthegamer commented
how do i use NodePath arrays in c# then?