GDScript 2.0: Access outer scope classes
godotengine/godot pull request #53726
Opened 2021-10-12 14:53 UTC by briansemrau

Resolves part of #52635
(The second part of that issue (outer scope static funcs) is much more involved.)

2021-10-12 22:56 UTC, vnen approved these changes

2021-10-12 22:57 UTC, vnen requested changes

2021-10-13 05:29 UTC, briansemrau commented
Seems I'm missing something. I'll look into it.

2021-10-13 21:36 UTC, vnen commented
> @vnen I believe it wasn't correct to strip the meta_type flag. It's causing `.new()` to not be recognized as a constructor here:

Ah, yeah, sorry. I confused it with something else.

2021-10-14 03:16 UTC, briansemrau commented
No problem, it was a good chance to learn how things work. PR should be all set now.

2021-10-14 13:12 UTC, vnen approved these changes

2021-10-14 13:12 UTC, merged