[3.x] Restrict the project data directory configuration
godotengine/godot pull request #53779
Opened 2021-10-13 20:19 UTC by m4gr3d

Limits the configuration range for the project data directory.

2021-10-13 20:37 UTC, Listwon requested changes

2021-10-13 20:48 UTC, Listwon commented
Please also review `EditorFileDialog::_item_list_item_rmb_selected` change you've made previously as
`if (item_meta["path"] == "res://.import") {` (which I assume worked fine before)
was changed to
`if (item_meta["path"] == ProjectSettings::get_singleton()->get_project_data_path()) {` (looks reasonably)
and then to
`if (String(item_meta["path"]).begins_with(ProjectSettings::get_singleton()->get_project_data_path())) {` (not sure why)

The MRP covering edge cases would be appreciated.

2021-10-13 20:52 UTC, m4gr3d commented
> Please also review `EditorFileDialog::_item_list_item_rmb_selected` change you've made previously as `if (item_meta["path"] == "res://.import") {` (which I assume worked fine before) was changed to `if (item_meta["path"] == ProjectSettings::get_singleton()->get_project_data_path()) {` (looks reasonably) and then to `if (String(item_meta["path"]).begins_with(ProjectSettings::get_singleton()->get_project_data_path())) {` (not sure why)
> 
> The MRP covering edge cases would be appreciated.

This change was made in `master` prior to my changes. I merely update the logic to follow suit.
See https://github.com/godotengine/godot/blob/d956904091b620bea5ee6eec9bd1413a97bba69a/editor/editor_file_dialog.cpp#L591 (the previous logic was `String(item_meta["path"]).begins_with("res://.godot")`.

2021-10-18 20:58 UTC, akien-mga approved these changes

2021-10-18 20:58 UTC, merged