Improve docs about plugin registration
godotengine/godot pull request #53836
Opened 2021-10-15 12:33 UTC by KoBeWi

Closes https://github.com/godotengine/godot-proposals/issues/195
The docs for EditorExportPlugin were filled, but they didn't mention the most important thing - that you need to register the plugin for any method to be called.

I also made the same changes to other similar plugins, unifying it a bit.

2021-10-15 13:16 UTC, YuriSizov requested changes
We can take this opportunity to unify the descriptions even further. But otherwise seems good.

2021-10-15 15:29 UTC, AaronRecord requested changes

2021-10-16 23:43 UTC, mhilbrunner approved these changes

2021-10-17 14:18 UTC, YuriSizov approved these changes
Pluralizing cross-references like that often looks ugly and doesn't help with localizations, but it's not critical right now. 🙃

2021-10-18 08:57 UTC, merged