The initialization window matches the editor base color or splash background color
godotengine/godot pull request #53922
Opened 2021-10-17 15:10 UTC by CodeLazier

Now, any window created by godot will be initialized to match the background color set by splash bg, and then the editor mode will be adapted to theme base color, which is to prevent the setting color and theme base color contrast over too large causing visual flicker. Yes,You can have it both ways. (only windows)

https://user-images.githubusercontent.com/14953625/137633490-586d1791-b2dc-4ce4-8987-3b680b623662.mp4

2022-07-31 08:58 UTC, reduz requested changes

2022-07-31 08:58 UTC, reduz commented on servers/display_server.h
> +	struct ExtraData {
I think for the time being, I would add a Color and not this struct. If we want to clean this up, we should do it later in a subsequent PR but not left the code in an intermediate state.

2022-07-31 09:00 UTC, reduz commented
Would be very nice to get this one rebased or  salvaged for 4.0.

2022-08-02 08:52 UTC, closed without merging

2022-08-02 09:39 UTC, Zireael07 commented
Why close?

2022-08-02 10:17 UTC, akien-mga commented
I believe @CodeLazier mistakenly pushed the upstream `master` branch on their fork instead of their own rebased `master` branch with this PR's changes. And GitHub automatically closes PRs when their base branch has no difference with upstream (and they can't be reopened).

@CodeLazier You'll have to open a new PR with the contents of https://github.com/godotengine/godot/commit/f82ab2898a109b92818c4287242d783a60ba51b2.