fix potential memory leak of AudioStreamPlaybackBusDetails
godotengine/godot pull request #53960
Opened 2021-10-18 13:59 UTC by Klowner

I found this one with `scan-build`. `AudioServer::start_playback_stream()` potentially leaks an instance of `AudioStreamPlaybackBusDetails` if an error is encountered within the for loop.

![image](https://user-images.githubusercontent.com/9374/137745672-02a40757-3bc5-4a7e-aeb6-2088a74b74d1.png)

Hopefully the way I did this makes sense, happy to revise if not :smile:

2021-10-18 14:21 UTC, ellenhp requested changes
This isn't a terribly huge issue because there's no script-facing API that could cause this code path to be executed. That said, totally not opposed to fixing it.

2021-10-19 03:47 UTC, ellenhp approved these changes
Looks good. Thank you for the contribution! I'm like 80% sure I'm allowed to merge this but I'd still like @akien-mga to take a look and verify it's good to merge.

2021-10-19 06:00 UTC, akien-mga approved these changes

2021-10-19 06:09 UTC, merged

2021-10-19 06:09 UTC, akien-mga commented
Thanks!