[3.x] Add error messages `String::hex_to_int` functions, and accept capital X in prefix
godotengine/godot pull request #54080
Opened 2021-10-21 16:42 UTC by Rubonnek

3.x equivalent of #54078

*Bugsquad edit:* Related to #54083.

2021-10-22 17:32 UTC, AaronRecord requested changes

2022-07-03 00:09 UTC, akien-mga commented on core/ustring.cpp
> +			ERR_FAIL_COND_V_MSG(true, 0, "Invalid hexadecimal notation character \"" + chr(*s) + "\" in string \"" + *this + "\".");
```suggestion
			ERR_FAIL_V_MSG(0, "Invalid hexadecimal notation character \"" + chr(*s) + "\" in string \"" + *this + "\".");
```

2022-07-03 00:10 UTC, akien-mga commented on core/ustring.cpp
> +			ERR_FAIL_COND_V_MSG(true, 0, "Invalid hexadecimal notation character \"" + chr(*s) + "\" in string \"" + *this + "\".");
```suggestion
			ERR_FAIL_V_MSG(0, "Invalid hexadecimal notation character \"" + chr(*s) + "\" in string \"" + *this + "\".");
```

2022-07-05 13:44 UTC, akien-mga commented on core/ustring.cpp
> +	ERR_FAIL_COND_V_MSG(p_with_prefix ? len < 3 : len == 0, 0, String("Invalid hexadecimal notation length in string ") + (p_with_prefix ? "with" : "without") + "prefix \"" + *this + "\".");
```suggestion
	ERR_FAIL_COND_V_MSG(p_with_prefix ? len < 3 : len == 0, 0, String("Invalid hexadecimal notation length in string ") + (p_with_prefix ? "with" : "without") + " prefix \"" + *this + "\".");
```

2022-07-05 13:45 UTC, akien-mga commented on core/ustring.cpp
> +	ERR_FAIL_COND_V_MSG(p_with_prefix ? len < 3 : len == 0, 0, String("Invalid hexadecimal notation length in string ") + (p_with_prefix ? "with" : "without") + "prefix \"" + *this + "\".");
```suggestion
	ERR_FAIL_COND_V_MSG(p_with_prefix ? len < 3 : len == 0, 0, String("Invalid hexadecimal notation length in string ") + (p_with_prefix ? "with" : "without") + " prefix \"" + *this + "\".");
```

2022-07-05 15:01 UTC, akien-mga approved these changes
Looks great!

2022-07-05 21:04 UTC, merged

2022-07-05 21:04 UTC, akien-mga commented
Thanks!