Fixed crash in `ScrollContainer` _notification
godotengine/godot pull request #54148
Opened 2021-10-23 10:56 UTC by miraz12

Fixes nullptr crash occurring when calling _notification on a new ScrollContainer when get_viewport is not available as reported in #54142 

_Fixes https://github.com/godotengine/godot/issues/54142_

2021-10-23 11:05 UTC, YuriSizov requested changes
It's better to add an error check here and fail, instead of just creating a condition. Entering ready without a viewport is an invalid state. See how it's done in https://github.com/godotengine/godot/pull/54120.

There are two reported cases in the linked issue, by the way. Please make sure to fix both of them.

PS. Also, please amend your commit message to refer to the node properly.

2021-10-23 14:02 UTC, YuriSizov approved these changes
Yes, seems alright. Not sure what `temp_variable2511.notification(96, true)` was supposed to do in the report, but it crashed regardless of that, and there is no notification 96.

2021-11-16 13:13 UTC, akien-mga approved these changes

2021-11-16 13:13 UTC, merged

2021-11-16 13:13 UTC, akien-mga commented
Thanks!

2021-11-18 11:22 UTC, akien-mga commented
Cherry-picked for 3.5.