Fix crash with TextEdit selection mode
godotengine/godot pull request #54204
Opened 2021-10-24 21:41 UTC by Ev1lbl0w

Fixes https://github.com/godotengine/godot/issues/54195

Moved the code for column to be inside the check for positive lines, otherwise `selection.selecting_line` can be an unitialized or invalid value.

2021-10-25 16:38 UTC, Paulb23 requested changes
This would still allow invalid value for `selection.selecting_column`.

We need to always validate both values.

2021-11-04 21:05 UTC, Ev1lbl0w commented
I've clamped the value for when the situation you described happens :+1:

2021-11-07 17:41 UTC, Paulb23 commented
My bad, should have specified earlier but we should still allow users to specify `selection.selecting_column` separately rather then nesting it, as it is here.

2021-11-10 12:46 UTC, Ev1lbl0w commented
I've tried another way of fixing this problem, hopefully much simpler than what I had before :slightly_smiling_face:

2021-11-10 18:02 UTC, Paulb23 approved these changes

2021-11-10 18:03 UTC, merged

2021-11-10 18:03 UTC, akien-mga commented
Thanks!