Allow using $/root node paths without having to quote them in GDScript
godotengine/godot pull request #54358
Opened 2021-10-28 18:18 UTC by Shawak

implement https://github.com/godotengine/godot-proposals/issues/3476

2021-11-08 15:32 UTC, vnen requested changes

2021-11-08 15:32 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +		advance();
It would be more semantic to use `match()` here:

```suggestion
	} else if (match(GDScriptTokenizer::Token::SLASH)) {
```

2021-11-08 15:32 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +		identifier_root->name = "/";
This should be empty, the slashes are added by the compiler.

2021-11-08 15:32 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +		int chain_position = 0;
I'm not even sure if this number is actually being used TBH.

2021-11-09 12:25 UTC, vnen requested changes
Other than the comment it looks good. The commits need to be squashed.

2021-11-09 12:25 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +		advance();
I think I wasn't clear about this, sorry, but the `advance()` also needs to be removed, since `match()` already does that.

2021-11-09 16:45 UTC, Shawak commented
Can't you just squash and merge?

2021-11-09 16:51 UTC, Calinou commented
> Can't you just squash and merge?

We don't use GitHub's squash and merge feature on the main Godot repository, since it loses the merge commit in the process. We prefer keeping the merge commit to make the Git history more self-documented (even if that makes it longer).

2021-11-10 13:38 UTC, vnen approved these changes

2021-11-10 14:19 UTC, merged

2021-11-10 14:19 UTC, akien-mga commented
Thanks!