Fix moving text in script editor with no selected character on last line
godotengine/godot pull request #54392
Opened 2021-10-29 16:08 UTC by jmb462

Fixes #54362

###  Issue

In script editor, when moving selection with alt+up/down, an extra line at the end or at the beginning can be moved.
It happens when selection ~~begins at the end of a line or~~ finishes at the beginning of a line (with no character of those lines selected).

### Fix proposal

Check if we are in such a case and prevent those line to move with the selection.
(I also rename a variable ``from_col`` to ``from_column`` for consistency reason.) 

### Before

You can see that in some case a line is moved whereas it shouldn't happen.
![move_bug](https://user-images.githubusercontent.com/3649998/139467402-34eb0d22-4c70-433f-9d84-e506e46d8502.gif)

### After

Behaviour is the expected one (as in Visual Studio / VS Code)
![move_fixed](https://user-images.githubusercontent.com/3649998/139467427-d31e2700-6f9e-4d65-986a-62a46b4142fe.gif)

2021-11-03 17:31 UTC, Paulb23 requested changes
Tested out other editors seems as though we should only be skipping the last line if `to_col == 0`. As it still moves the line if the `from_col` is at the end of the text.

2021-11-03 19:01 UTC, jmb462 commented
> Tested out other editors seems as though we should only be skipping the last line if `to_col == 0`. As it still moves the line if the `from_col` is at the end of the text.

After checking with VisualStudio, you're right. But there is a visual difference : 
![image](https://user-images.githubusercontent.com/3649998/140174586-0a5fd4ba-2112-4d52-ab85-076f4de3dbf5.png)
In VS Studio, VSCode and SublimeText, you see that the carriage return is selected so the selection on that line is not empty.
In godot editor, nothing seems to be selected at the end of the line.

2021-11-07 17:35 UTC, Paulb23 commented on editor/code_editor.cpp
> +			if (to_column == 0 && i == to_line) {
Should we be taking one from `to_line` rather then skipping, otherwise below this loop, it looks like `to_line_up` will be off by one?

2023-01-28 08:41 UTC, aXu-AP commented
@jmb462 are you going to continue the work on this? If not, I think I could finish it. This problem has been my biggest issue with script editor since forever, and now I'm at last capable of fixing it (I believe).

2023-01-28 09:41 UTC, jmb462 commented
> @jmb462 are you going to continue the work on this? If not, I think I could finish it. This problem has been my biggest issue with script editor since forever, and now I'm at last capable of fixing it (I believe).

Feel free to work on this :)

2023-01-28 09:49 UTC, aXu-AP commented
Thanks, I'll give it a shot :)

2023-02-03 20:19 UTC, YuriSizov commented
Superseded by https://github.com/godotengine/godot/pull/72672.

2023-02-03 20:19 UTC, closed without merging