Fix viewport with transparent bg changed to solid black if enable fxaa or debanding.
godotengine/godot pull request #54585
Opened 2021-11-04 07:17 UTC by Kinwailo

If enable fxaa or debanding in viewport with transparent bg, the transparent bg will change to solid black color. It is because the shader always output alpha as 1.0.

2021-11-04 10:11 UTC, Calinou commented
Does this fully address https://github.com/godotengine/godot/issues/45208, or are there still parts of the tonemapping shader that don't play well with Transparent Bg?

2021-11-05 16:58 UTC, Kinwailo commented
> Good catch slightly_smiling_face
> 
> Does this fully address #45208, or are there still parts of the tonemapping shader that don't play well with Transparent Bg?

Post processing is bypass if transparent is enabled in driver code, and the shader of glow / dof produce "black edge". I have changed the code and shader, should fix #45208.

2022-02-06 11:29 UTC, Calinou commented
I tested this PR rebased against the latest `3.x` branch as of writing. It indeed fixes the issue in the [original MRP](https://github.com/godotengine/godot/files/5820414/PostBug.zip) :slightly_smiling_face: 

### Before

![2022-02-06_11 57 40](https://user-images.githubusercontent.com/180032/152678703-b6260cbf-f16f-4dc4-8bbd-c27b6e1da0ed.png)

### After (with this PR)

![2022-02-06_12 27 29](https://user-images.githubusercontent.com/180032/152678704-e6e8222f-3fa7-4733-9211-c09ef37154cc.png)

When Transparent Bg is disabled, the appearance is identical:

### Before

![2022-02-06_12 27 38](https://user-images.githubusercontent.com/180032/152678706-04d4ee50-93bf-47f8-9623-e4f73b6115bd.png)

### After (with this PR)

![2022-02-06_12 27 52](https://user-images.githubusercontent.com/180032/152678707-738b8c2c-be41-4af9-9778-a287eb783417.png)

2022-02-06 11:30 UTC, Calinou requested changes

2022-02-06 11:30 UTC, Calinou commented on drivers/gles3/shaders/tonemap.glsl
> +		color.rgb /= color.a;
Use braces for single-line `if` statements, as per the code style guidelines:

```suggestion
	if (color.a == 0.0) {
		color.rgb = vec3(0.0);
	} else if (color.a < 1.0) {
		color.rgb /= color.a;
	}
```

2022-02-06 11:30 UTC, Calinou commented on drivers/gles2/shaders/tonemap.glsl
> +		color.rgb /= color.a;
```suggestion
	if (color.a == 0.0) {
		color.rgb = vec3(0.0);
	} else if (color.a < 1.0) {
		color.rgb /= color.a;
	}
```

2022-02-28 23:12 UTC, bfloch commented
I was able to verify this with a project that was suffering from the issue in 3.4.3. Works great, no complaints.

2022-03-01 07:19 UTC, bfloch commented
A negative side-effect I just noticed: In transparent viewports that are setup via a ViewportTexture in a TextureRect and not ViewportController the (supposedly transparent) background looks overly bright.
Somehow I noticed that transparency does not seem to work in either 3.4.3 or this PR this way, but that may be a separate issue or something wrong on my  end.

The screenshot shows the PR at the top:
![godot_transparency_effect](https://user-images.githubusercontent.com/2116566/156122556-d132a9fe-fee9-496d-ad1f-d8faa8bc0c36.png)

2022-05-03 17:58 UTC, Calinou commented
Looks good to me, please squash the commits together so we can merge this. See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) for instructions :slightly_smiling_face:

2022-05-04 20:21 UTC, clayjohn commented
This looks pretty good and is very promising. 

The only issue I noticed while testing is that FXAA doesn't weight the transparent samples by their alpha, so you end up with black edges when using FXAA.

This shouldn't be too hard to fix, it may just be a matter of premultiplying the sampled colour by its transparency so that transparent pixels don't contribute their color. 

_FXAA on_
![Screenshot from 2022-05-04 13-18-14](https://user-images.githubusercontent.com/16521339/166819232-5385c0d6-9ff1-421d-8393-ee04fb1f224c.png)

_FXAA off_
![Screenshot from 2022-05-04 13-18-18](https://user-images.githubusercontent.com/16521339/166819237-91335c33-dd17-4c88-ba29-56638ec6e1c7.png)

2022-05-09 17:45 UTC, clayjohn requested changes
Just the one change needed. Other than that, this is looking good to go!

2022-05-09 17:45 UTC, clayjohn commented on drivers/gles2/shaders/tonemap.glsl
> +	return output;
``output`` is a reserved word in glsl so this shader will fail to compile when drivers strictly enforce the glsl specification (typically Intel drivers). To compile, the name just needs to be changed. 

After making this change everything seems to work well!

```suggestion
	vec4 output = ((lumaB < lumaMin) || (lumaB > lumaMax)) ? rgbA : rgbB;
	if (output.a == 0.0) {
		output.rgb = vec3(0.0);
	} else if (output.a < 1.0) {
		output.rgb /= output.a;
	}
	return output;
```

2022-05-10 14:57 UTC, clayjohn commented
> > Just the one change needed. Other than that, this is looking good to go!
> 
> should change the shader for gles3 too?

Yes please

2022-05-12 08:36 UTC, Kinwailo commented
> > > Just the one change needed. Other than that, this is looking good to go!
> > 
> > 
> > should change the shader for gles3 too?
> 
> Yes please

changed

2022-05-16 03:01 UTC, clayjohn approved these changes
Looks great! Thank you!

2022-05-16 06:26 UTC, Calinou approved these changes
Thanks! Congratulations for your first merged pull request :tada:

2022-05-16 06:28 UTC, merged