Reduce cubic interpolated animation hitch
godotengine/godot pull request #54730
Opened 2021-11-07 17:35 UTC by robfram

Reduce cubic interpolated animation hitch

Cubic interpolation didn't wrap around first and last keys, clamping
pre and post keys to first and last before interpolating values.

Fixes #20087

2021-11-07 18:18 UTC, Calinou commented
Thanks for opening a pull request :slightly_smiling_face: 

Pull requests (especially ones that break backwards compatibility) should be opened against the `master` branch instead of `3.x`. This is because feature development occurs in the `master` branch. We can then cherry-pick specific PRs to the `3.x` branch if they don't break backwards compatibility.

2021-11-07 18:31 UTC, robfram commented
> Pull requests should be opened against the `master` branch instead of `3.x` (as long as the feature/fix is relevant for `master`). This is because feature development occurs in the `master` branch. We can then cherry-pick specific PRs to the `3.x` branch if they don't break backwards compatibility.

Sorry, I can't PR against `master` branch because I can't test changes as my machine is not vulkan capable (and not even sure it compiles at all). I was looking for bugs in the `3.x` branch for that reason, but I forgot this bug was still present in `master`.
My apologies.

2021-11-07 18:37 UTC, Calinou commented
> I can't PR against master branch because I can't test changes as my machine is not vulkan capable (and not even sure it compiles at all). 

The `master` branch now has OpenGL support for 2D rendering, which you can enable by using the `--rendering-driver opengl3 --single-window` command line arguments:

You can create a new project from the [command line](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html) as follows:

```
touch /tmp/test/project.godot
~/godot/bin/godot.linuxbsd.tools.64 --rendering-driver opengl3 --single-window /tmp/test/project.godot
```

2021-11-07 18:50 UTC, robfram commented
> The `master` branch now has OpenGL support for 2D rendering, which you can enable by using the `--rendering-driver opengl3 --single-window` command line arguments.
> 
> You can create a new project from the [command line](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html) as follows:
> 
> ```shell
> # Create an empty `project.godot` file within a folder.
> mkdir -p /tmp/test
> touch /tmp/test/project.godot
> 
> # Replace "~/godot/bin/godot.linuxbsd.tools.64" with the path to your compiled Godot executable.
> ~/godot/bin/godot.linuxbsd.tools.64 --rendering-driver opengl3 --single-window /tmp/test/project.godot
> ```
> 
> The 3D editor viewport won't display anything, but you should be able to switch to the 2D tab and see sprites added there.

Amazing! I'm trying to compile it right now, disabling all third party modules that throw errors. if I'm able to make it run, I could replace this PR with a new one against `master`, and try to use it for future ones.
Thanks!

2021-11-09 18:27 UTC, robfram commented
The PR for `master` is #54811

I was able to compile it patching 2 thirdparty libraries (`icu4c` and `basis_universal`). Should I open an issue/PR for them or they are outside Godot scope being thirdparty libs?

Although the editor works (in 2D as you said), I can't run the scenes. I got this message:
```
Your video card driver does not support any of the supported Vulkan or OpenGL versions.
Please update your drivers or if you have a very old or integrated GPU, upgrade it.
If you have updated your graphics drivers recently, try rebooting.
```

For this PR this was not a problem, as the hitch was noticeable directly in the editor.

2021-11-09 21:00 UTC, akien-mga commented
> I was able to compile it patching 2 thirdparty libraries (`icu4c` and `basis_universal`). Should I open an issue/PR for them or they are outside Godot scope being thirdparty libs?

We don't modify thirdparty libs unless we really can't fix issues differently. I'm not aware of any build issue for those libs on any platforms supported in our official builds though, I assume you're on a more exotic system? Please open issues for these.

2021-11-10 17:55 UTC, robfram commented
_**Note:** Perhaps this whole text should be it's own issue entry. I can move it to one if you want and delete it here. Thanks in advance, and I know this is not a common-enough scenario to be really attendend._

> I assume you're on a more exotic system? Please open issues for these.

Yes, I'm on FreeBSD. Before opening issues for this (for `basis_universal` is only add one more `defined` comparison to get the same `#include` as MacOS), I want to confirm the building module system is working as expected.

I mean, I understand that they are options and modules (mainly talking about `icu4c` here) that can be enabled or disabled because:
1. They are optional and not needed to compile a working version of Godot, and/or
2. They can be provided system wide (aldreay present in the OS) instead as a Godot module when compiling.

When I tried to compile with `builtin_icu=no`, compilation fails due to others thirdparty modules dependences on it:
```
[ 29%] build_gdnative_api_struct(["modules/gdnative/include/gdnative_api_struct.gen.h", "modules/gdnative/gdnative_api_struct.gen.cpp"], ["modules/gdnative/gdnative_api.json"])
[ 32%] modules/text_server_adv/text_server_adv.cpp:38:10: fatal error: 'thirdparty/icu4c/icudata.gen.h' file not found
#include "thirdparty/icu4c/icudata.gen.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 34%] 1 error generated.
[ 37%] tza_to_cpp(["thirdparty/oidn/weights/rtlightmap_hdr.gen.cpp"], ["thirdparty/oidn/weights/rtlightmap_hdr.tza"])
scons: *** [modules/text_server_adv/text_server_adv.linuxbsd.tools.64.llvm.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:28.468]
```
So, I proceed with `module_text_server_adv_enabled=no`, and then it's the turn for `basis_universal` to fail. Again, no problem, time to disable that module too with `module_basis_universal_enabled=no`, and continue compiling.

And then, finally, when we try to execute it following the previous indication for OpenGL, we have a core dumped:
```
$ godot.linuxbsd.tools.64.llvm --rendering-driver opengl3 --single-window -e .
Godot Engine v4.0.dev.custom_build.e8870ddef - https://godotengine.org
ERROR: Property not found: rendering/quality/2d/use_nvidia_rect_flicker_workaround
   at: _get (core/config/project_settings.cpp:246)
ERROR: Property not found: rendering/quality/shading/force_lambert_over_burley
   at: _get (core/config/project_settings.cpp:246)
ERROR: Property not found: rendering/quality/shading/force_blinn_over_ggx
   at: _get (core/config/project_settings.cpp:246)
OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
ERROR: Condition "!props.has(p_prop)" is true.
   at: set_custom_property_info (core/config/project_settings.cpp:977)
ERROR: Condition "!props.has(p_prop)" is true.
   at: set_custom_property_info (core/config/project_settings.cpp:977)
ERROR: Property not found: rendering/quality/2d/use_software_skinning
   at: _get (core/config/project_settings.cpp:246)
ERROR: Property not found: rendering/quality/2d/ninepatch_mode
   at: _get (core/config/project_settings.cpp:246)
  Undefined symbol "snd_dlpath"
  Undefined symbol "snd_config_is_array"
W: [(null)] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.

ERROR: TextServer: Unable to create TextServer interface.
   at: setup2 (main/main.cpp:1859)
ERROR: A Thread object has been destroyed without wait_to_finish() having been called on it. Please do so to ensure correct cleanup of the thread.
   at: ~Thread (core/os/thread.cpp:124)
Segmentation fault (core dumped)
```

First of all, compiled with the patched modules (with all the default modules enabled at compilation time) works good enough. Secondly, we can really ignore the core dump, as the important part is the `ERROR: TextServer: Unable to create TextServer interface.` message I think. Is `module_text_server_adv` mandatory?

Perhaps if the `text_server_adv` module could use system wide ICU, then no additional module modification would be needed at all. Otherwise, disabling the ICU module should disable `text_server_adv` automatically.

I don't mind trying to generate elaborated patches to thirdparty modules if it will fix the compilation problem to a runnable executable.

2021-11-15 22:30 UTC, akien-mga commented
If you disable `text_server_adv`, you need to enable `text_server_fb` (fallback), which has less features but should give you a functional editor.

But yes, please open issues about the compilation problems for basis_universal and icu4c, they should be fixed.

2021-11-15 22:30 UTC, akien-mga commented
Fixed by #54811.

2022-01-12 16:06 UTC, akien-mga commented
Closing as superseded by #54811 so we keep reviews in a single place (the `master` PR should be trivial to cherry-pick to `3.x` once approved and merged).

2022-01-12 16:07 UTC, akien-mga commented
I was too fast, the `master` PR says that things likely need a different implementation for 4.0 so it definitely makes sense to keep the `3.x` implementation around.

2022-02-20 03:54 UTC, TokageItLab approved these changes
I think it's fine for 3.x. In 4.0 https://github.com/godotengine/godot/pull/54811#issuecomment-1046153890, there is a problem as I mentioned there, so please let me postpone it.

2022-02-20 07:30 UTC, TokageItLab requested changes

2022-02-20 07:30 UTC, TokageItLab commented on scene/resources/animation.cpp
> +				if (p_loop_wrap) {
```suggestion
				if (loop && p_loop_wrap) {
```

2022-02-20 07:30 UTC, TokageItLab commented on scene/resources/animation.cpp
> +				if (p_loop_wrap) {
```suggestion
				if (loop && p_loop_wrap) {
```

2022-03-01 10:18 UTC, TokageItLab commented
Superseded by #58651.

2022-03-01 10:18 UTC, closed without merging