Copy/Paste property paths/values in inspector.
godotengine/godot pull request #54913
Opened 2021-11-12 12:57 UTC by rcorre

Resolves godotengine/godot-proposals#106.

Adds the following property menu options with default bindings:

- Copy Property (ctrl+c)
- Paste Property (ctrl+v)
- Copy Property Path (ctrl+shift+c)

If you hover over a property label in the inspector dock, you can copy
either the property value or the property path to the system clipboard
using the shortcuts above This is especially useful for the
`AnimationTree`, where code might reference properties like
"parameters/state/aim/move/blend_position".

One issue is that if you click a property, then click on the node you
currently have selected in the node tree, then press ctrl+shift+c, it
will still copy the selected property path rather than the node path. If
you click on a different node in the nodetree, however, ctrl+shift+c
will return to copying the nodepath.

The property value copy/paste was implemented by @KoBeWi at #39398 and
merged into this PR due to their similarity.

Backport of 0205fffbf3ebf03cf974802f07368a5d18326893 from master.

2021-12-25 16:54 UTC, KoBeWi requested changes
The menu is different than on master:
![image](https://user-images.githubusercontent.com/2223172/147389627-933fb0d1-3b25-4185-b932-206cbe5a4791.png)
vs
![image](https://user-images.githubusercontent.com/2223172/147389630-4b0d64e6-db52-4149-a109-d21b8ed44905.png)
It's missing separator and the Pin Value is at the top. This is because they were added in a different order. It should be made consistent.

Also the backport is missing #52376 bugfix.

2022-01-04 14:07 UTC, KoBeWi approved these changes
Looks ok now.

The Ctrl+V paste shortcut doesn't work for 2D nodes, probably because of the V being hijacked by 2D editor. It's not really related to this PR though.

2022-01-04 14:29 UTC, akien-mga approved these changes

2022-01-04 14:29 UTC, merged

2022-01-04 14:29 UTC, akien-mga commented
Thanks!