Enable detection of static bodies by non monitorable areas
godotengine/godot pull request #54997
Opened 2021-11-15 15:37 UTC by BimDav

Fixes https://github.com/godotengine/godot/issues/17238

Non monitorable areas were defined as static in the BVH, preventing their pairing with static bodies. With this fix, non monitorable areas and static bodies are separate cases.

2021-11-15 15:49 UTC, YeldhamDev requested changes

2021-11-15 15:49 UTC, YeldhamDev commented on core/math/bvh_public.inc
> +	}
```suggestion
	}
```

2021-11-15 15:54 UTC, YeldhamDev commented
Remember to squash your commits: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

2021-11-15 16:33 UTC, YeldhamDev requested changes

2021-11-15 16:33 UTC, YeldhamDev commented on core/math/bvh_misc.inc
> +		else if (_extra[p_handle.id()].pairable_type == 1) {
```suggestion
		} else if (_extra[p_handle.id()].pairable_type == 1) {
```

2023-02-12 13:28 UTC, YeldhamDev commented
Conflicts need fixing, and sorry that we let this PR marinate for so long.

2023-02-12 13:54 UTC, lawnjelly commented
The PR is no longer applicable as is, we changed the BVH to have templated trees and works a bit differently now. There is a PR for 3 trees (#58505 ), but we didn't decide what to do in this respect, as Pouley was unsure about performance implications.

2023-02-12 14:01 UTC, closed without merging