Register missing WebRTCDataChannelJS type.
godotengine/godot pull request #55044
Opened 2021-11-17 04:33 UTC by juanitogan

There's something totally different going on with **register_types.cpp** in master (that I can't say I understand) -- and master doesn't build right now to see if a similar fix is needed there -- thus, it seems, I'm forced to put this fix directly on 3.4.

The WebRTCDataChannelJS class was not registered in **register_types.cpp** and this generates an error in the HTML5 export (the Windows builds work fine with the WebRTC Native plugin).  This error goes back to at least 3.3.rc6.

Also, it appeared **webrtc_peer_connection_js.h** was missing a `GDCLASS()` line, so I added one.  I don't know what it's for, so maybe that was a mistake.  Builds and runs fine with it, however.

This doesn't fix any issue tickets that I could find.  I just pretended to be a C++ programmer and made the fix instead of filing an issue.  Seemed faster that way to get the fix I needed to ship the game (even though it took a while to find).

The browser error when receiving a data channel:

```
ERROR: Cannot get class 'WebRTCDataChannelJS'.
onPrintError @ Sendit Soccer.js:362
put_char @ Sendit Soccer.js:9
write @ Sendit Soccer.js:9
write @ Sendit Soccer.js:9
doWritev @ Sendit Soccer.js:9
_fd_write @ Sendit Soccer.js:9
$__stdio_write @ 042a7756:0x90e061
$__vfprintf_internal @ 042a7756:0x2260a0
$vfprintf @ 042a7756:0x200caa
$StdLogger::logv(char const*, void*, bool) @ 042a7756:0x9cdaf5
$Logger::logf_error(char const*, ...) @ 042a7756:0x1dda9e
$Logger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 042a7756:0xb8a4bc
$CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 042a7756:0xbdb387
$_err_print_error(char const*, char const*, int, char const*, char const*, ErrorHandlerType) @ 042a7756:0x28327
$_err_print_error(char const*, char const*, int, char const*, String const&, ErrorHandlerType) @ 042a7756:0x2952e
$ClassDB::_get_parent_class(StringName const&) @ 042a7756:0x6abe19
$ClassDB::_is_parent_class(StringName const&, StringName const&) @ 042a7756:0x6abcf9
$ClassDB::is_parent_class(StringName const&, StringName const&) @ 042a7756:0x6ecbf
$GDScriptDataType::is_type(Variant const&, bool) const @ 042a7756:0x2df90f
$GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) @ 042a7756:0xb2e5b
$GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) @ 042a7756:0xbb9991
$Object::call(StringName const&, Variant const**, int, Variant::CallError&) @ 042a7756:0x27c6b9
$Object::emit_signal(StringName const&, Variant const**, int) @ 042a7756:0x27c36e
$Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) @ 042a7756:0x297ee
$WebRTCPeerConnectionJS::_on_data_channel(void*, int) @ 042a7756:0x94b315
ondatachannel

  at: _get_parent_class (core/class_db.cpp:323) - Condition "!ti" is true. Returned: StringName()
[same trace as above]
```

2021-11-17 08:41 UTC, akien-mga commented
Even if this is not relevant as is for `master`, PRs for changes to Godot 3 should be made in the `3.x` branch - i.e. targeted for the next minor release, 3.5. It can be backported to 3.4.x, but we don't fix bugs in stable branches without fixing them too in development branches.

2021-11-17 11:21 UTC, Faless commented
`WebRTCDataChannelJS` is not supposed to be registered as it's not supposed to be directly instantiated and would create incompatibilities between the desktop and web API.

Do you have a minimal reproduction project? The missing `GDCLASS` could be the reason of the failure, though I'm not 100% sure.

2021-11-17 19:57 UTC, juanitogan commented
Oh...... I get it now, `3.x` is the dev branch!  Yeah, I totally missed that message if it's indicated anywhere.  What I read made it sound like `master` was the dev branch... which is entirely confusing.  Yeah, I'll retarget this PR if I can; or just close it.  Looks like I messed up some indents with an extra space anyhow.

@Faless : I made the `GDCLASS` addition early on and it had no effect on anything I could detect.  It took me much longer to figure out what **register_types.cpp** was for and the missing lines there.  That is obviously what fixed it, correct or not.  As to issues between desktop and web, that is clearly what the `#ifdef`s are for that I see in that file, and which I added to, as seen in the diff.

On the other hand, maybe I needed to only add the `#include "webrtc_data_channel_js.h"` line and the `ClassDB::register_class` lines are superfluous for web.  I can test that.

Sorry, no minimal test project.

2021-11-17 21:11 UTC, juanitogan commented
Okay, at a minimum, the `ClassDB::register_class<WebRTCDataChannelJS>();` line is required in addition to the `#include`.  I believe I tested this before but couldn't remember for sure.  I did find, however, that the similar `ClassDB::register_class<WebRTCPeerConnectionJS>();` line is not needed (and it wasn't there before either).  So, I guess I'll leave that one out of the next PR even though it looks suspicious without it.

2021-11-17 21:18 UTC, dsnopek commented
@juanitogan What does your GDScript code look like? You shouldn't ever need to directly interact with `WebRTCDataChannelJS` and I'm wondering if that is the problem.

2021-11-17 21:30 UTC, juanitogan commented
@dsnopek : I don't.  And the problem is fixed.  The only problem now is how to get the fix into the next patch release.

2021-11-17 22:04 UTC, dsnopek reviewed
I've got a game that uses WebRTC in HTML5, which is using one of the 3.4 rc's, which works fine. I'm trying to get a build of it with 3.4-stable -- unfortunately, it has a kinda complicated build process and my CI is being weird right now, so that might not be until much later tonight. I'll report back on that once I know for sure if it works or not.

However, these changes don't seem right to me.

2021-11-17 22:47 UTC, juanitogan commented on modules/webrtc/register_types.cpp
> + 	ClassDB::register_class<WebRTCDataChannelJS>();
Yeah, I can't claim any expertise here.  I can only tell you this line fixes the error.  If there's a better way to fix it, great.  Specifically, the error occurs in **library_godot_webrtc.js** here:

```javascript
		ondatachannel: function (p_id, callback, event) {
			const ref = IDHandler.get(p_id);
			if (!ref) {
				return;
			}

			const cid = IDHandler.add(event.channel);
			callback(cid);
		},
```

It doesn't appear to be able to find the class for whatever is in `event.channel`.

Here's C++ point of the error:

```cpp
void WebRTCPeerConnectionJS::_on_data_channel(void *p_obj, int p_id) {
	WebRTCPeerConnectionJS *peer = static_cast<WebRTCPeerConnectionJS *>(p_obj);
	peer->emit_signal("data_channel_received", Ref<WebRTCDataChannelJS>(new WebRTCDataChannelJS(p_id)));
}
```

I don't understand the wiring in all this.  I just went looking for how the wiring differs between WebRTCPeerConnection and WebRTCDataChannel, and this is the only diff I have found -- and it works.  I can believe there's another fix.  I just can't find it and this gets me out the door.

As for the GDScript side, the error only occurs on HTML5 guests and not the HTML5 host (nebulous definitions, I know).  No errors either way on Windows guest or host.  It occurs just before the `data_channel_received` signal comes in (a signal that still comes in, but things are now broke).  Which is setup here:

```gdscript
	# Create (receive) a data channel to the Host.
	var peer := WebRTCPeerConnection.new()
	peer.connect("session_description_created", self, "_on_session", [peer, guest_ref])
	peer.connect("ice_candidate_created", self, "_on_ice_candidate", [guest_ref])
	peer.connect("data_channel_received", self, "_on_data_channel")
```

2021-11-17 22:49 UTC, juanitogan commented on modules/webrtc/webrtc_peer_connection_js.h
> +	GDCLASS(WebRTCPeerConnectionJS, WebRTCPeerConnection);
Yeah, I'm aware this is a red herring.  It was just another point of difference I came across and decided to eliminate as a possible factor.

2021-11-17 22:58 UTC, juanitogan commented on modules/webrtc/register_types.cpp
> + 	ClassDB::register_class<WebRTCDataChannelJS>();
Well, the other differences are the class types and the calls to `make_default()` but, well, 🤷, I'm at my knowledge limit.

2021-11-18 00:56 UTC, juanitogan commented
BTW, here's the game I'm exploiting WebRTC with:  https://juanitogan.itch.io/sendit-soccer

I just now uploaded the first Godot version to replace the prior prototype in Phaser.  It's so fresh I haven't even written the devlog yet.

2021-11-18 02:52 UTC, Faless requested changes
> Sorry, no minimal test project.

Well, then sorry, but I don't understand what this PR is fixing, and it honestly just seems bogus.

2021-11-18 03:05 UTC, dsnopek commented
> BTW, here's the game I'm exploiting WebRTC with: https://juanitogan.itch.io/sendit-soccer

Your game looks super cool! :-)

So, I finally got my game to build with Godot 3.4-stable, and the HTML5 version with WebRTC works just fine. It does use custom compiled export templates, which got me wondering if maybe it was a problem with the build and not the code, so I reverted to an earlier version of the game that didn't need a custom compiled Godot, and tried it with the stock Godot 3.4-stable HTML5 export templates, but that worked fine too.

I suspect it's something in your game code, or maybe with the way it's exported, that's leading to this problem. I'd highly recommend making a minimal reproduction project to demonstrate the problem.

2021-11-18 23:48 UTC, juanitogan commented
So, yeah, if your game responds to the same `"data_channel_received"` signal without error, that is indeed terribly concerning to me.  I use a custom export template for release but I first came upon this with the default templates.  3.4, 3.3.4, 3.3.2, 3.3-rc6, all the same error.  I had tested all those before this fix because I thought I had the lobby code working at one time.  But, that was also many moons ago and I have no idea if I was testing with just Win builds or what back then.

A repro project is a hard ask right now.  The lobby code is long gone in my head but, as I recall, a repro would need a new test server to run the ice connections through and some way to simplify all that code that doesn't give all the lobby code away.  That's a ton of work for what I'm under right now -- for something I thought I already had a solid fix for.  Regardless, looking at my export, there's not much for HTML5 that could be affecting this but, okay, there is some funny stuff going on there elsewhere.  For example, turning off Focus Canvas On Start kills all keyboard input.  So, okay, I'll poke at the export more.  More likely to the point, I was reminded I use a JS polyfill so I can support Godot's switch to Fetch with older browsers.  I'll take that out and see what happens.  I don't know how it could make JS forget it has access to a class but, okay, I've seen stranger things in the JS world.  I also run the ice data over HTTPS client connections so, hmm, a lot going on here.

2021-11-19 00:26 UTC, juanitogan commented
Yeah, removing the polyfill made no difference.  Same error.  Will poke at a few other things to try to get more intel.

2021-11-19 03:12 UTC, juanitogan commented
Okay, I finally found another place to fix this.  One that will hopefully make everybody happy.

From the beginning, everything pointed to the `emit_signal` in this method, which was obvious by the trace info:

```cpp
void WebRTCPeerConnectionJS::_on_data_channel(void *p_obj, int p_id) {
	WebRTCPeerConnectionJS *peer = static_cast<WebRTCPeerConnectionJS *>(p_obj);
	peer->emit_signal("data_channel_received", Ref<WebRTCDataChannelJS>(new WebRTCDataChannelJS(p_id)));
}
```

It first appeared that the `WebRTCDataChannelJS` use there wasn't liked by something downstream.  I tried some changes to that line early on but they all failed to fix it.  And, yet, the more I poked around, the more I ended up back here.

Now, finally, after reading enough code from the other classes, I can monkey-see/monkey-do this line correctly, like so:

```cpp
	peer->emit_signal("data_channel_received", Ref<WebRTCDataChannel>(memnew(WebRTCDataChannelJS(p_id))));
```

Why `memnew()` works to propagate the class correctly and `new` does not, I don't know exactly.  It just does.  And, of course, `memnew()` is correct according to the Godot docs.

As to why @dsnopek isn't experiencing the same error, I can only surmise his game doesn't listen for a data channel, or, at least, not in the way I do.  To be clear, opening a data channel with `create_data_channel()` does not generate an error.  The error occurs on another peer, in another game session, that is only listening for the data channel.  I don't, for example, try to create channels both ways.  It's pretty clean and simple.  I don't know if that matches @dsnopek 's use case or not.  Just guessing.

2021-11-19 03:28 UTC, Faless commented
So, this is a minimal script that connects 2 (local) peers and do not use negotiated channels (i.e. the second peer listens to `data_channel_received`). I tried to reproduce the issue with both debug and release, but had no issue. Does it work for you?

```gdscript
extends Node

# Create the two peers
var p1 := WebRTCPeerConnection.new()
var p2 := WebRTCPeerConnection.new()

# And a channel for the first peer.
var ch1 := p1.create_data_channel("chat")
# And and var for the second peer channel (which will be received via signal)
var ch2 : WebRTCDataChannel = null


func _ready():
	# Connect P1 session created to itself to set local description
	p1.connect("session_description_created", p1, "set_local_description")
	# Connect P1 session and ICE created to p2 set remote description and candidates
	p1.connect("session_description_created", p2, "set_remote_description")
	p1.connect("ice_candidate_created", p2, "add_ice_candidate")

	# Same for P2
	p2.connect("session_description_created", p2, "set_local_description")
	p2.connect("session_description_created", p1, "set_remote_description")
	p2.connect("ice_candidate_created", p1, "add_ice_candidate")
	
	# Listen for received channels.
	p2.connect("data_channel_received", self, "_on_channel")

	# Let P1 create the offer
	p1.create_offer()


func _on_channel(ch):
	ch2 = ch
	# Send messages
	ch1.put_packet("Hi from P1".to_utf8())
	ch2.put_packet("Hi from P2".to_utf8())


func _process(_delta):
	# Poll connections
	p1.poll()
	p2.poll()

	# Check for messages
	if ch1.get_ready_state() == ch1.STATE_OPEN and ch1.get_available_packet_count() > 0:
		print("P1 received: ", ch1.get_packet().get_string_from_utf8())
	if ch2 and ch2.get_ready_state() == ch2.STATE_OPEN and ch2.get_available_packet_count() > 0:
		print("P2 received: ", ch2.get_packet().get_string_from_utf8())
```

2021-11-19 03:33 UTC, Faless commented
> Now, finally, after reading enough code from the other classes, I can monkey-see/monkey-do this line correctly, like so:
> 
> ```c++
> 	peer->emit_signal("data_channel_received", Ref<WebRTCDataChannel>(memnew(WebRTCDataChannelJS(p_id))));
> ```

Well, even if I'm unable to reproduce the issue, that's actually a good fix :+1: .
I think **we should really investigate better** under which condition this is happening to make sure not to just hide the real issue, but I think that fix is **definitely an improvement**, so I would approve of it.

2021-11-19 05:42 UTC, juanitogan commented
> So, this is a minimal script that connects 2 (local) peers and do not use negotiated channels (i.e. the second peer listens to `data_channel_received`). I tried to reproduce the issue with both debug and release, but had no issue. Does it work for you?

Yeah, this works, with and without the `memnew` fix.  I'll see if I can do anything to make it break like the rest of my stuff.

2021-11-20 21:38 UTC, juanitogan commented
> > So, this is a minimal script that connects 2 (local) peers and do not use negotiated channels (i.e. the second peer listens to `data_channel_received`). I tried to reproduce the issue with both debug and release, but had no issue. Does it work for you?
> 
> Yeah, this works, with and without the `memnew` fix. I'll see if I can do anything to make it break like the rest of my stuff.

There's not much I can do here.  This test, while useful, is too local.  The one, small difference I have from this basic setup (an option set on `create_data_channel()`) has no effect on this test.  If there was a relevant end-to-end test that works, I would dig into it.  But, neither of the Godot demo projects do this (webrtc_minimal and webrtc_signaling), so I'm guessing no such test was ever written or run.  There is a slight possibility that splitting this test into two classes locally may reveal more (guest and host for example), but I'm guessing an end-to-end test (app to app) is still needed.

I just came upon David's GitLab project with WebRTC and Nakama.  It looks like we were both spinning up WebRTC projects in Godot around the same time last spring.  Pretty cool.  It is apparent, however, his Nakama plugin handles all data through a `WebSocketClient` and not a WebRTC data channel and, thus, is not relevant for testing here.  In other words, there is no use of `create_data_channel()` and `"data_channel_received"` there.  Same story with the nakama-godot project.

2021-11-21 04:35 UTC, Faless commented
> There's not much I can do here. This test, while useful, is too local.

Not sure what you mean by too local, we are not debugging a network issue.

As I said, what you could do, is provide a minimal reproduction project, taking your game code, and trimming it down to the minimum. Since you are the only one getting this error for now, I cannot wild guess what your code look like.

But at this point it's not important, I think this is good to be merged since the fix now makes sense, but you would need to squash the commits together first.
See here for the details: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

2021-11-21 06:03 UTC, juanitogan commented
You are correct, this particular issue is not a networking issue.  But, if that is the only reason you can see to do an end-to-end test, then I can be of no more help here.  I am, after all, the would-be liar who filed a bogus report.  Those words hurt and it has become clear that any more work from me will not be treated any better.  The failure to do an end-to-end test up front was not mine to begin with.  No thank you on being punished twice for it.  Do the test and you will see that each side cannot stand on its own.  Don't do it and you will surely never see.

2021-11-21 06:26 UTC, Faless commented
@juanitogan I am deeply sorry I made you feel that way.

Your work is really appreciated, and this PR is now correct and ready to be merged once squashed.

What I was trying to convey, is that the easiest and fastest way for having a reproduction project for both of us, is to start from your code and trim it down to the minimum, instead of me trying to guess what a good reproduction project would be.

2021-11-21 07:06 UTC, Faless commented
I applied the following changes to the webrtc signaling demo (see attached zip) to test remotely, but still couldn't reproduce:

[webrtc_signaling.zip](https://github.com/godotengine/godot/files/7575865/webrtc_signaling.zip)

```diff
diff --git a/networking/webrtc_signaling/client/multiplayer_client.gd b/networking/webrtc_signaling/client/multiplayer_client.gd
index 4f088a2..a9463a0 100644
--- a/networking/webrtc_signaling/client/multiplayer_client.gd
+++ b/networking/webrtc_signaling/client/multiplayer_client.gd
@@ -2,6 +2,7 @@ extends "ws_webrtc_client.gd"
 
 var rtc_mp: WebRTCMultiplayer = WebRTCMultiplayer.new()
 var sealed = false
+var channels = []
 
 func _init():
        connect("connected", self, "connected")
@@ -38,9 +39,16 @@ func _create_peer(id):
        peer.connect("ice_candidate_created", self, "_new_ice_candidate", [id])
        rtc_mp.add_peer(peer, id)
        if id > rtc_mp.get_unique_id():
+               channels.append(peer.create_data_channel("my_chan"))
                peer.create_offer()
+       else:
+               peer.connect("data_channel_received", self, "_new_data_channel", [id])
        return peer
 
+func _new_data_channel(channel, id):
+       print("On Data Channel!", channel)
+       channels.append(channel)
+       pass
 
 func _new_ice_candidate(mid_name, index_name, sdp_name, id):
        send_candidate(id, mid_name, index_name, sdp_name)
```

2021-11-22 02:30 UTC, juanitogan commented
@Faless Thank you for the apology.  Accepted and moving on.

You were close with your mods to the signaling app.  The thing you missed was eliminating `WebRTCMultiplayer`.  That class, according to the app's own logging, creates three data channels to connect two peers.  Why?  Don't know.  Looks suspicious to me, but that is also beside the point.  The point is that, with that class in place, the test was not allowing each side of a single data channel to stand on its own.

Anyhow, I took what you did, commented out everything related to `WebRTCMultiplayer` and replaced it with a single `WebRTCPeerConnection`.  Now, it breaks as expected.  Nothing fancy or surprising going on here.  Just a straight-up test of a single channel.  Here's the marked-up code (including my html5 export that breaks, for what it's worth):

[webrtc_signaling_mod.zip](https://github.com/godotengine/godot/files/7577657/webrtc_signaling_mod.zip)

This signaling app was not easy to figure out (the readme doesn't describe how to run it) but I eventually got it by digging through the code.  Much more complex than where I'm at right now.  [[I'm sure you know how to run the app... I'm just going to be precise here for any other readers.]]  I run a Windows build of the app to act as the signaling server (click Listen to start the listener).  I then launch two instances of the html5 build, one in Chrome, one in Edge.  Click Start in one browser (it doesn't matter which browser), copy the lobby code from the log pane and paste it into the Room field in the other browser.  Click Start in the other browser and you will find the errors in that browser's console.  The app in the other browser (the one calling `create_data_channel`) does not break.

Connecting two peers within one browser tab will not break anything.  That works fine.  Hence, it appears to be some sort of memory thing and perhaps not odd that `memnew` fixes it -- even though, yes, it may be hiding something deeper.

I didn't test any other features of the app beyond that.  Most are likely broken due to the stuff I commented out.  I did hook up the Ping button for the heck of it (don't use unless connected).

Another important thing to note is that you only get the `Cannot get class 'WebRTCDataChannelJS'` error (as seen in the PR comment) if you define the type of the channel var (or argument).  Otherwise, you get other errors that do not point anywhere helpful.  These other errors look like this (depending on the function being called):

```
SCRIPT ERROR: Invalid call. Nonexistent function 'get_ready_state' in base 'WebRTCDataChannelJS'.

at: _process (res://demo/client_ui.gdc:24) - Invalid call. Nonexistent function 'get_ready_state' in base 'WebRTCDataChannelJS'.
```

2021-11-30 18:07 UTC, dsnopek commented
@juanitogan Thanks for sharing the reproduction project and the steps! I was able to reproduce the error locally, although, I used Firefox and Chrome (rather than Chrome and Edge) since I'm on Linux. I haven't had a chance to try the fix yet.

2021-11-30 18:29 UTC, dsnopek approved these changes
... and I just tested with Godot 3.4 + the patch from this PR, compiled to the release target. The change fixes it in my testing!

So, giving my personal approval (it's ultimately up to @Faless), conditional on CI passing.

EDIT: Heh, I didn't mean to approve "on behalf of godotengine/xr" since obviously this has nothing to do with XR. My approval is only on behalf of myself. :-)

2021-12-09 09:52 UTC, Faless commented
Yes, this is okay now, but needs squashing, and should target the `master` branch.
https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

2022-07-02 22:30 UTC, akien-mga commented
> Yes, this is okay now, but needs squashing, and should target the `master` branch. [docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase)

Done myself with #62651 since this PR was abandoned.

2022-07-02 22:30 UTC, closed without merging

2022-07-06 05:14 UTC, juanitogan commented
Thanks.  It wasn't squashable and... well... thanks.