Conditional wakeup
godotengine/godot pull request #55167
Opened 2021-11-20 16:47 UTC by brennengreen

In #55047 @pouleyKetchoupp recommended that the solution be implemented in `GodotBody2D::set_param` and `GodotBody3D::set_param`. My solution is to conditionally check if gravity_scale is zero prior to changing it, if it is, call `wakeup()` and then set the new gravity_scale.

In test, I can no longer reproduce the bug @nabfrew noted in the issue with his provided minimal project with these changes.

Fixes #55047

2021-11-20 16:49 UTC, brennengreen commented
Not super sure why two unique commits got hashed here first was done using the typical strategy to commit, the second commit was added using git commit --amend --no-edit. 

Not really sure how to fix the commit history here, but if you have a recommendation let me know.

2021-11-22 09:49 UTC, akien-mga commented
> Not really sure how to fix the commit history here, but if you have a recommendation let me know.

You'd have to do an interactive rebase to squash the two commits together, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).

2021-11-22 15:10 UTC, pouleyKetchoupp requested changes
Looks good! Just needs the little adjustments I've commented on and then squashing into one commit and it will be good to go.

2021-11-22 16:08 UTC, pouleyKetchoupp commented
@brennengreen Looks good to go but there are now 5 commits registered. When you use [interactive rebase](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase), just make sure to use `fixup` on every commit except for the first one in the list and it should do the trick.

2021-11-22 17:06 UTC, akien-mga approved these changes

2021-11-22 17:28 UTC, pouleyKetchoupp approved these changes

2021-11-22 18:43 UTC, merged