Add the function add_child_deferred.
godotengine/godot pull request #55581
Opened 2021-12-03 10:50 UTC by xsellier

This function acts as `call_deferred("add_child", node)`, however it is a handy thread safe method.
This handy shortcut outperform the use of `call_deferred("add_child", node)`.

```gdscript
func _ready():
    # Thread safe
    add_child(node)

func set_data(data):
    # Not thread safe
    add_child_deferred(load('res://my_scene.tscn'))
```

2021-12-03 11:04 UTC, Calinou commented
> This handy shortcut outperform the use of call_deferred("add_child", node).

Could you do a benchmark on a release build `tools=no target=release` and post the results here?

2021-12-03 11:46 UTC, xsellier commented
> Could you do a benchmark on a release build (`tools=no target=release`) and post the results here?
Made a github repository for this:
https://github.com/xsellier/gdscript-benchmark

From the editor itself (debug):
```
add_child_deferred(node)  *** 192% faster than ***  call_deferred('add_child', node)     (0.026 vs 0.076 msec)
```

Exported project (release):
```
Building (I'll update this ticket as soon as I have a result)
```

2021-12-03 12:34 UTC, pycbouh commented
It seems that your commits are authored with an identity that is not associated with your GitHub account (Xavier Sellier <xsellier@binogure-studio.com>). Might want to look into that, otherwise it won't count as a contribution made on your behalf.

2021-12-03 12:38 UTC, pycbouh requested changes
Small documentation suggestion.

2021-12-03 12:38 UTC, pycbouh commented on doc/classes/Node.xml
> +				Same as [code]call_deferred("add_child", node, legible_unique_name, internal)[/code]
```suggestion
				Adds a child node in a thread-safe manner. Analogous to using [method add_child] with [method Object.call_deferred], but can be more efficient.
```

2021-12-03 12:52 UTC, xsellier commented on doc/classes/Node.xml
> +				Same as [code]call_deferred("add_child", node, legible_unique_name, internal)[/code]
Better wording. Thank you

2021-12-03 13:21 UTC, pycbouh approved these changes
Docs are okay now, though I'd still put it in less confident terms about the efficiency. Can be dependent on a lot of factors, and it's better not to give false promises.

But that's more of a question to the core team.

2021-12-07 12:26 UTC, mhilbrunner commented
PR meeting: we discussed this, but its mostly a workaround to the fact scenes currently don't support multithreading. We want to change that and make it threadsafe, so this goes against that idea.
Also while maybe a handy shortcut, it kind of opens the door to adding tons of similar deferred shortcuts for other common functions.

Thanks for contributing!

2021-12-07 12:26 UTC, closed without merging

2021-12-07 14:52 UTC, xsellier commented
> PR meeting: we discussed this, but its mostly a workaround to the fact scenes currently don't support multithreading. We want to change that and make it threadsafe, so this goes against that idea. Also while maybe a handy shortcut, it kind of opens the door to adding tons of similar deferred shortcuts for other common functions.
> 
> Thanks for contributing!

Thank you for the update.
I though about the impact of adding such function, and it would require to list all the not-thread-safe functions to add a similar shortcut. Even if it is handy it will require some work, and a lot of back and forth just to target those not-thread-safe functions and add an extra-work each time a non-thread-safe function is added.

I use `call_deferred('add_child', node)` a lot, but since you plan to make this function thread-safe, I agree it's better not to add `add_child_deferred`.