Tweak VehicleBody3D and VehicleWheel3D property hints
godotengine/godot pull request #55627
Opened 2021-12-04 18:29 UTC by Calinou

These property hints are better aligned with the documentation and typical use cases, while still allowing values to go outside those ranges (except for steering, where steering above 180° doesn't make sense).

See https://github.com/godotengine/godot-proposals/issues/2217.

2021-12-09 14:53 UTC, pouleyKetchoupp requested changes

2021-12-09 14:53 UTC, pouleyKetchoupp commented on scene/3d/vehicle_body_3d.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "brake", PROPERTY_HINT_RANGE, "-128,128,0.01,or_greater,or_lesser"), "set_brake", "get_brake");
Does it make sense to allow negative values for brake? I'm not very familiar with VehicleBody3D, but it looks like the code expects an impulse value.

2021-12-09 14:53 UTC, pouleyKetchoupp commented on scene/3d/vehicle_body_3d.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "steering", PROPERTY_HINT_RANGE, "-3.141,3.141,0.01"), "set_steering", "get_steering");
You can use the hint `-180,180,0.1,radians` to display an angle in degree in the editor for a property in radians (see floor_max_angle in CharacterBody3D).

Also 0.1 increments are probably precise enough when it comes to angles.

2022-08-26 09:12 UTC, fabriceci commented
If it's still wanted can you do a rebase?

2023-06-15 07:29 UTC, akien-mga approved these changes

2023-06-15 08:51 UTC, merged

2023-06-15 08:52 UTC, akien-mga commented
Thanks!