Patch `MultiplayerPeerExtension` to allow derived classes
godotengine/godot pull request #55657
Opened 2021-12-06 02:00 UTC by MorganKF

This registers `MultiplayerPeerExtension` as a base class instead of a virtual one.
It seems to fall in line with how `PacketPeerExtension` and `StreamPeerExtension` are registered in `register_core_types.cpp`.

I'm not very familiar with the new GDExtension system yet, but it seems that deriving any virtual class will lead to being unable to instantiate. This is a workaround for the `MultiplayerPeerExtension` class.

Fixes #55635.

2021-12-06 14:36 UTC, mhilbrunner commented
cc @Faless :)

2021-12-06 15:05 UTC, Faless requested changes
Registering `MultiplayerPeerExtension` with `GDREGISTER_CLASS` is fine, but please do not change the registration order. I'm pretty sure it used to be that way for a reason, I'm not sure those assumptions still holds, but it's anyway unrelated to this PR.

2021-12-15 08:57 UTC, Faless approved these changes
Looks good :+1: !

2021-12-15 10:40 UTC, merged

2021-12-15 10:41 UTC, Faless commented
Thanks :tada:  !