Fixed a invalidation of sets and out of range for an alignment
godotengine/godot pull request #56347
Opened 2021-12-30 17:47 UTC by NNesh

Fixes #56276 and _set_operations return value with a possible invalidation

Result:
![image](https://user-images.githubusercontent.com/12952093/147775944-f3546f3c-94c9-4f35-b73a-3ca723bdf6af.png)

2022-01-01 13:19 UTC, fire commented
@theoway told me he commented here

2022-01-01 18:27 UTC, theoway requested changes

2022-01-01 19:26 UTC, NNesh commented on scene/gui/graph_edit.cpp
> +			int end = MIN(up.size() - 1, up.size() % 2 ? start + 1 : start);
Ok. I've applied these corrections!

2022-01-01 19:26 UTC, NNesh commented on scene/gui/graph_edit.cpp
> +			for (Set<StringName>::Element *E = r_u_c.front(); E; E = E->next()) {
I've understood. I've removed.

2022-01-02 06:38 UTC, theoway approved these changes
Test it locally. Fixes the bug! Thanks :)

2022-01-02 07:02 UTC, fire approved these changes
theoway tested the code.

2022-01-03 23:37 UTC, merged

2022-01-03 23:37 UTC, akien-mga commented
Thanks!

2023-04-18 15:20 UTC, bartimusprimed commented
I can reliably reproduce this still on M1 Mac. It was driving me crazy as I thought it was my code, but simply calling arrange_nodes or clicking it manually results in a crash. As soon as I remove that line (or don't click arrange) everything is fine.

2023-04-18 15:41 UTC, fire commented
Can you create a new issue? Fill in the form. I think the important part is nothing that this is a mac and provide a recreation project.

2023-04-18 15:42 UTC, YuriSizov commented
@bartimusprimed You may be experiencing a different problem that also results in a crash. Please open a bug report and provide a reproduction project. It would be also great if you could provide a crash log (you need to compile the engine with debug symbols for that).