Tree: Fix de-select when selection mode set to SELECT_ROW
godotengine/godot pull request #56414
Opened 2022-01-01 23:10 UTC by eazrael

It no longer de-selects an already selected row if the SELECT_MODE is
set to SELECT_ROW. Fixes #36047

2022-01-01 23:14 UTC, KoBeWi commented
The code seems to be the same as in #56408, so a dedicated 3.x PR wasn't really necessary. It could've been easily cherry-picked.

2022-01-01 23:19 UTC, YeldhamDev requested changes

2022-01-01 23:19 UTC, YeldhamDev commented on scene/gui/tree.cpp
>  				//p_current->deselected_signal.call(p_col);
```suggestion
					// Deselect other rows.
					c.selected = false;
				}
```

2022-01-01 23:32 UTC, YeldhamDev commented
Simple PRs should be squashed into a single commit. Here are the instructions on how do to so: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

2022-01-02 01:10 UTC, YeldhamDev approved these changes

2022-01-05 08:26 UTC, merged

2022-01-05 08:26 UTC, akien-mga commented
Thanks!