Show tile set editor bottom panel button when creating a tile set for a tile map
godotengine/godot pull request #56429
Opened 2022-01-02 12:34 UTC by PucklaMotzer09

Fixes #56413

In `TilesEditorPlugin::_update_editors`, which is connected to the `changed` signal of a `TileMap`, the bottom panel buttons `tileset_editor_button` and `tilemap_editor_button` are correctly hidden or shown. Also this fix switches to another bottom panel if the `TileSetEditor` panel is displayed while there is no active `TileSet`.

2022-01-02 12:58 UTC, YeldhamDev requested changes

2022-01-02 12:58 UTC, YeldhamDev commented on editor/plugins/tiles/tiles_editor_plugin.cpp
> +	// Update visibility of bottom panel buttons
```suggestion
	// Update visibility of bottom panel buttons.
```

2022-01-02 13:29 UTC, YeldhamDev commented
Simple PRs should be squashed into a single commit. Here are the instructions on how to do so: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

2022-01-03 23:15 UTC, YeldhamDev approved these changes

2022-01-04 09:16 UTC, groud approved these changes

2022-01-04 09:22 UTC, merged

2022-01-04 09:22 UTC, akien-mga commented
Thanks!