Make TextEdit new_line user override-able.
godotengine/godot pull request #56422
Opened 2022-01-02 07:02 UTC by glipR

Apologies, I know I should talk to somebody before working on such a change, but had already made this change before reading the contributing page. Additionally this change is small enough, and seems inline with existing features of the engine.

My current problem is that I'm using the new `backspace` and `handle_unicode_input` functions of `TextEdit` to add readonly sections within a `TextEdit`/`CodeEdit`. The issue here is that I still want users to be able to add newlines by pressing enter, provided the caret is in an editable position.

This pull request makes very similar to changes to `_new_line` that have already been done to `backspace`, allowing the action associated with `ui_text_newline` to be overwritten by the user.

2022-01-06 22:32 UTC, glipR commented
Believe I've fixed the error that was happening in workflows earlier.
I do have a quick question if someone is willing to help me out though - I'm not sure what is causing the doctest to think I should not include documentation for the `new_line` (no leading underlines) in the `TextEdit.xml` file. For this change I've essentially just searched project wide for all instances of `backspace` and made edits to include similar changes for newline where appropriate.

2022-01-07 09:54 UTC, bruvzg commented
> I'm not sure what is causing the doctest to think I should not include documentation for the new_line (no leading underlines) in the TextEdit.xml file.

It should be bound in the `TextEdit::_bind_methods()` as well, add:
```c++
	ClassDB::bind_method(D_METHOD("new_line"), &TextEdit::new_line);
```

2022-01-07 10:33 UTC, glipR commented
😱 I'm blind.
Thanks, added!

2022-01-09 15:59 UTC, Paulb23 requested changes
I was unsure about adding this originally as creating new lines unlike `backspace` and `handle_unicode_input` are not called internally, so you could override the 3 actions (`ui_text_newline_above, ui_text_newline_blank, ui_text_newline`) in `gdscript` as appropriate and it should "just" work. However, if there is something not covered here, I have no issues with exposing it.

As for this code review, we should expose `new_line` with the two args or add additional callbacks for them.

2022-01-09 21:05 UTC, glipR commented
Ah, that does make sense. In that case I have trouble seeing how this is particularly useful, if not confusing. 

Might be worth making some changes to the documentation for the current methods then, since then backspace is not only called when the `backspace` key is pressed, but in general is executed when an action similar to default functionality for the backspace key is desired by godot methods.

2022-01-09 21:05 UTC, closed without merging