Warn when setting very high attenuation on OmniLight3D or SpotLight3D
godotengine/godot pull request #56490
Opened 2022-01-04 19:10 UTC by Calinou

High attenuation values will negatively impact performance for 2 reasons:

- The light won't be culled as often.
- The light will cover more pixels, which have to be shaded individually.

Therefore, lower attenuation values (with a higher range to compensate) should be preferred whenever possible.

With the `master` branch's physical light attenuation, I've found that there is no tangible benefit to going above 10 with the light attenuation. (In fact, we may want to consider adding a hard cap here.)

See https://github.com/godotengine/godot/issues/54596.

2022-08-02 09:50 UTC, reduz requested changes, later dismissed
I think the doc is good to clarify for range that the more objects the light touches the more it may impact performance , but its still a valid use case in the end so a warning should not be shown.

2022-08-02 20:59 UTC, Calinou commented
I amended this PR to only change docuimentation.

2023-02-16 19:25 UTC, clayjohn approved these changes

2023-02-16 20:41 UTC, merged

2023-02-16 20:41 UTC, YuriSizov commented
Thanks!