Allow to override CLI args on a per-instance basis
godotengine/godot pull request #57975
Opened 2022-02-11 15:04 UTC by mhilbrunner

When running the Project from the Editor, this allows the user to override the CLI arguments each instance is started with per instance using the new project settings `editor/run/instance_1_run_args` through `editor/run/instance_4_run_args` (overriding `editor/run/main_run_args` for each instance if set).

This is useful for multiplayer testing or when testing with different settings/profiles to reduce manual configuration on each test/run.

2022-02-16 17:40 UTC, Faless requested changes
See my comments, I think these options should be project metadata in EditorSettings, and not stored in project settings.

Maybe it's time we add some form of "run configuration" page like many IDEs do? I'm not great at UX so I'm a bit unsure what a good simple design would be here.

2022-02-16 17:40 UTC, Faless commented on editor/editor_run.cpp
> +void EditorRun::parse_run_args(String *exec_path, List<String> *args, const String raw_custom_args) {
This fits more the godot codebase:

```suggestion
void EditorRun::parse_run_args(String &r_exec_path, List<String> &r_args, const String p_raw_custom_args) {
```

2022-02-16 17:40 UTC, Faless commented on editor/editor_run.cpp
> +		String raw_custom_args = ProjectSettings::get_singleton()->get(instance_arg_setting);
I feel like these should be in editor settings meta too (i.e. `EditorSettings::get_singleton()->get_project_metadata("debug_options", instance_arg_setting)`).

We don't really want to export them, they are debug/editor configurations, not something to store in the project settings.

I guess that raises the question of where to show those info, and maybe an hint to proceed towards an initial implementation of https://github.com/godotengine/godot-proposals/issues/522 ?

2022-02-22 12:38 UTC, bruvzg reviewed
Any reason to limit it to the 4 instances?

*Note: I have not tested suggested changes, but `PackedStringArray` project setting should work fine.*

2022-02-22 12:38 UTC, bruvzg commented on core/config/project_settings.cpp
> +	GLOBAL_DEF("editor/run/instance_4_run_args", "");
```suggestion
	GLOBAL_DEF("editor/run/instance_run_args", PackedStringArray());
```

2022-02-22 12:38 UTC, bruvzg commented on editor/editor_run.cpp
> +	int instances = EditorSettings::get_singleton()->get_project_metadata("debug_options", "run_debug_instances", 1);
```suggestion
	int instances = EditorSettings::get_singleton()->get_project_metadata("debug_options", "run_debug_instances", 1);
	PackedStringArray instance_arg_setting = ProjectSettings::get_singleton()->get("editor/run/instance_run_args");
```

2022-02-22 12:38 UTC, bruvzg commented on editor/editor_run.cpp
> +		String raw_custom_args = ProjectSettings::get_singleton()->get(instance_arg_setting);
```suggestion
		String raw_custom_args;
		if (instance_num >= instance_arg_setting.size()) {
			raw_custom_args = instance_arg_setting[instance_num - 1];
		}
```

2022-02-22 13:07 UTC, Faless commented
@bruvzg as mentioned above, I don't think these should be project settings at all.
They are not meaningful during export, only for the editor debug, so it should go in the EditorSettings project metadata.
Instances to run are limited to 4 because it's set from the `debug` menu -> `run multiple instance` in the editor and we decided to hardcode it at the time, so it has to be adjusted there too in case: https://github.com/godotengine/godot/blob/33c7f52f361961c64432cfd772909ed3ba76cd51/editor/plugins/debugger_editor_plugin.cpp#L101-L110

https://github.com/godotengine/godot/blob/33c7f52f361961c64432cfd772909ed3ba76cd51/editor/plugins/debugger_editor_plugin.cpp#L119-L125

2022-02-22 13:09 UTC, akien-mga commented
We discussed this on `#editor` and I propose making the configuration of these multiple instances a full featured dialog where the number of instances and their arguments can be configured. Quick and dirty mockup:
![image](https://user-images.githubusercontent.com/4701338/155138710-f4a4df9e-650d-444f-8570-1fc2bbce98ee.png)

I'll comment further in the proposal, it's probably best to keep things there.

2023-09-16 23:32 UTC, warent commented
Gentle ping here. Anything we can do to move things forward? Thanks everyone for the great work

2023-10-04 18:53 UTC, cyraid commented
@Faless If it were Editor Settings, then how would I specify -id 1 to one Project, and -someotherarg in a different one? It would have to be project settings.

@bruvzg I like it! I was hoping for such a change. Would someone be able to add this in?

2023-10-05 12:42 UTC, Faless commented
> @Faless If it were Editor Settings, then how would I specify -id 1 to one Project, and -someotherarg in a different one? It would have to be project settings.

EditorSettings project metadata are per project, so no, it doesn't have to be project settings.

2023-10-07 22:16 UTC, cyraid commented
Okeys. Would you be able to review #57975 or commit this one? ^_^ (since I have you here lol)

2024-06-29 23:34 UTC, mhilbrunner commented
Closing, as I currently lack the bandwidth for this one. Still should be done however IMO :)

2024-06-29 23:34 UTC, closed without merging