Address wrong behavior of TextEdit `ctrl` modifier while editing the text
godotengine/godot pull request #58452
Opened 2022-02-22 23:00 UTC by marcgpuig

_This PR is a work in progress._

My attempt to fix #58406.

In `TextEdit::_do_backspace()` the function `TextServer::shaped_text_get_word_breaks()` returns an empty array when the caret is in the column 0, and so, the function ended up not deleting anything when this is the case.

This PR makes it so this case is checked at the very beginning, alongside the other specific cases where the function can simply behave like a simple backspace.

I've also taken this chance to replace `int line` with `caret.line` since its value will not change and makes things less confusing by using the same style I've seen in similar parts of this file.

- [X] Fix `ctrl + backspace` with caret in column 0
- [ ] Fix `ctrl + backspace` with caret next to multiple spaces
- [ ] Fix `ctrl + right/left` with caret next to multiple spaces

I think the general root-cause is the output of `TextServer::shaped_text_get_word_breaks()`. I will try to dig a bit more in my free time.

2022-03-05 17:48 UTC, marcgpuig commented
Not entirely sure what should be the behavior of `TextServer::shaped_text_get_word_breaks()` while parsing text that contains adjacent spaces e.g: `Test█with██more███spaces\n`
_Notice I'm using the special character `█` as a space to help visually_

Given the previous String, and using `TextServer::GRAPHEME_IS_BREAK_SOFT` as a flag, it returns the following indices: `[0, 4, 5, 10, 11, 17, 18, 25]`. Which, and If I'm correct, corresponds to those positions:
```
Test with  more   spaces\n
^   ^^    ^^     ^^     ^
```

@bruvzg could you confirm that this is the expected output?
I want to understand where I need to keep digging to finish as I say in the PR description.

Thanks!

2022-03-05 18:18 UTC, bruvzg commented
`shaped_text_get_word_breaks()` returns start-end pairs, so the result looks expected: first word `0..4`, second word `5...10`, and so on. For some languages, like Thai, it's possible to get results like `0..4`, `4..10` (there's no space between words, and it's using dictionary to get word bounds).
Seems like it's not handling multiple adjacent spaces, that's probably should be improved. I guess `0..4`, `5..9`, `11..15`, `18..24` would be better result.

2022-03-05 20:27 UTC, bruvzg commented
> Given the previous String, and using TextServer::GRAPHEME_IS_BREAK_SOFT as a flag

Actually, in the case of `TextEdit`, it should be used with `GRAPHEME_IS_SPACE | GRAPHEME_IS_PUNCTUATION` flags, with your example, it will give you: `0..4`, `5..9`, `10..10`, `11..15`, `16..16`, `17..17`, `18..24`, you can skip words with the 0 length, and it should be fine.

`GRAPHEME_IS_BREAK_SOFT` should be used for line breaking only, so it's applied using slightly different rules and not suitable for work breaking.

2022-03-19 17:39 UTC, Paulb23 requested changes
Looks good, one small edge case when pressing `ctrl+backspace` with only spaces to the left removes one rather then all of them.

Also any chance you could squash commits?

2022-03-29 19:32 UTC, marcgpuig commented
Thanks for taking a look @Paulb23.
Let me address the issue and squash the commits. I'll find some time this weekend!

2022-04-03 23:11 UTC, marcgpuig commented
@Paulb23 should be fixed and squashed.

2022-04-04 20:34 UTC, Paulb23 approved these changes
Thanks for the Contribution! LGTM.

2022-04-04 21:58 UTC, merged

2022-04-04 21:58 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2022-04-04 22:41 UTC, marcgpuig commented
Thanks :)