fixing bug  #57553
godotengine/godot pull request #58575
Opened 2022-02-26 22:11 UTC by elmordo

2022-02-26 22:40 UTC, Calinou requested changes

2022-02-27 07:42 UTC, elmordo commented on core/object/object.cpp
> +        auto current_extension = _extension;
Ok, the change was done. Please review this carefully. This is my first contribution on the Godot and don't want to break anything :sweat_smile: 
But I thing the worst scenario caused by my change is duplication of some properties in inspector :-)

2022-03-02 10:41 UTC, akien-mga commented
Could you squash the commits together? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

2022-03-02 14:34 UTC, closed without merging

2022-03-02 18:07 UTC, Calinou commented
Superseded by https://github.com/godotengine/godot/pull/58690.