Prompt to confirm anim track delete on node delete
godotengine/godot pull request #58598
Opened 2022-02-27 17:30 UTC by KoBeWi

Closes #3562
Supersedes #42001
![godot windows tools 64_atLUjVm3wL](https://user-images.githubusercontent.com/2223172/155892734-33ae4f7d-086e-40a2-b76d-13540150bbaf.gif)
Whenever deleting a node, the editor will check whether there are animation tracks that refer to this node, and if yes, a prompt will appear asking if they should be deleted. The dialog will appear even when using "Delete (no confirm)". For now there is no editor setting that would disable it, but I could add one.

There is however one problem. As you can see in the GIF, the checkbox in the dialog overlaps buttons. Not sure how to solve it. (another thing is that removing the line about tracks from the dialog doesn't shrink it)

2022-07-03 23:05 UTC, akien-mga commented
Needs a rebase, and with some luck it might solve this issue?

> There is however one problem. As you can see in the GIF, the checkbox in the dialog overlaps buttons. Not sure how to solve it. (another thing is that removing the line about tracks from the dialog doesn't shrink it)

If not, maybe others in @godotengine/_editor can lend a hand figuring it out.

2022-07-04 01:14 UTC, KoBeWi commented
Rebased, didn't help.

2022-08-18 16:00 UTC, clayjohn commented
Looks good, but not a breaking change. Bumping to 4.x. Would be nice to have for 4.0 if it is ready.

2022-08-19 22:03 UTC, Piralein requested changes
Not sure how to highlight multiple lines in one change request.

The dialog expects only one child and scales the size according to biggest.
So to get it working:
- add new Label in the header file
- add a VBoxContainer as child to the dialog
- add a Label as child of the VBoxContainer
- add the Checkbox as child of the VBoxContainer
- Change the text of the new label inside the VBoxContainer and not the dialog label (_tool_selected function)

2022-08-19 22:53 UTC, Calinou commented
> Not sure how to highlight multiple lines in one change request.

Hover the mouse until you see a blue "+" symbol appearing, then click-and-drag downwards. Then request a suggestion by using the button in the top-right corner of the toolbar above the comment.

2022-08-24 14:01 UTC, KoBeWi commented
> add new Label in the header file
add a VBoxContainer as child to the dialog
add a Label as child of the VBoxContainer
add the Checkbox as child of the VBoxContainer
Change the text of the new label inside the VBoxContainer and not the dialog label (_tool_selected function)

This basically means reimplementing the dialog :/ (and won't even work, because the dialog uses the label directly instead of "first child", see `_update_child_rects()`) I think dialogs need ability to add custom controls to their content.

2022-08-26 11:24 UTC, KoBeWi commented
Actually the VBoxContainer trick wasn't difficult to do and it solved the issue. So this should be ready now.

2022-08-26 11:45 UTC, fire commented
editor setting that would disable it, but I could add one. Yes! Please

2022-08-28 00:29 UTC, KoBeWi commented
Ok I added editor setting: `docks/scene_tree/ask_before_deleting_related_animation_tracks`, enabled by default.

2022-09-18 23:50 UTC, fire commented
@TokageItLab

2023-03-21 20:35 UTC, yatesm4 commented
Can this be merged in already for the love of God?

2023-03-21 22:48 UTC, fire approved these changes
Not blocking but wondering it should respect the editor setting instead of creating a new one

2023-03-21 23:04 UTC, KoBeWi commented
Which existing editor setting it could use?

2023-03-22 00:18 UTC, fire commented
we have a generic don’t ask option?

2023-03-22 00:23 UTC, KoBeWi commented
There's a don't ask for creating animation tracks, but it's not the same.

2023-04-25 14:01 UTC, akien-mga approved these changes
Seems good to me. Needs rebase.

2023-04-25 17:30 UTC, merged

2023-04-25 17:31 UTC, akien-mga commented
Thanks!

2023-05-24 16:29 UTC, InfernalWAVE commented
so does this change only make it into 4.1? I just went through this but its nice to see its being addressed!

2024-11-20 00:55 UTC, pixel-boy commented
When nodes are deleted with CTRL+X the warning isn't triggered.