Document performance interactions with MSAA and depth prepass
godotengine/godot pull request #58768
Opened 2022-03-04 21:13 UTC by Calinou

2022-03-05 07:42 UTC, clayjohn commented
I'm not sure the advice that disabling depth prepass when using MSAA is a good idea. It's going to be a very context sensitive decision and a note in the docs like this makes it sound like it _should_ be disabled when MSAA is used. 

For complex scenes with a lot of overlapping geometry and many lights, the benefit of depth pre-pass will likely still far outweigh the cost of the MSAA depth resolve.

2022-05-12 20:05 UTC, Calinou commented
Rebased. I changed the wording a little since the depth prepass should always be beneficial in very complex scenes (even at high MSAA levels).

2022-05-16 02:04 UTC, clayjohn commented on doc/classes/ProjectSettings.xml
> +			[b]Note:[/b] If [member rendering/anti_aliasing/quality/msaa] is set to a value other than [b]Disabled[/b], the depth prepass ([member rendering/driver/depth_prepass/enable]) becomes considerably
I'm not sure this line is accurate, how MSAA/ the depth prepass impact performance is a complex relationship. I would keep this line a little more vague and avoid giving absolute performance advice. Instead say something like" the depth prepass helps improve performance in most cases by eliminating pixel overdraw, but especially when MSAA is used, can be quite expensive. You can try different MSAA/Depth prepass settings to find a configuration that is right for your project.

2022-05-24 00:42 UTC, clayjohn approved these changes

2022-05-24 00:43 UTC, clayjohn requested changes

2022-05-24 00:43 UTC, clayjohn commented on doc/classes/ProjectSettings.xml
> +			[b]Note:[/b] Only supported when using the Vulkan Clustered backend (not Vulkan Mobile or OpenGL). When using Vulkan Mobile or OpenGL, there is no depth prepass performed.
```suggestion
			[b]Note:[/b] Only supported when using the Vulkan Clustered backend or the OpenGL backend. When using Vulkan Mobile there is no depth prepass performed.
```
This line shouldn't change. The OpenGL backend use a prepass when it needs to

2022-08-03 17:34 UTC, reduz commented
I think its too soon to do these kind of judgements when work regarding optimization is pending.

2023-06-02 10:42 UTC, mhilbrunner commented
Closing due to lack of consensus as per the above discussion and due to how old this PR is. A new PR with up to date information is of course eventually welcome :)

2023-06-02 10:42 UTC, closed without merging