Make AnimatedSprite2D update animation property when SpriteFrames changes
godotengine/godot pull request #58966
Opened 2022-03-10 05:16 UTC by L4Vo5

AnimatedSprite2D will ensure it has a valid animation when the SpriteFrames is set, and on its "changed" signal.
To that end, makes SpriteFrames emit the "changed" signal when one or all of its animations are deleted.
Note that the animation property will remain as-is if the SpriteFrames has no animations at all.

Removes error message on set_animation when SpriteFrames is null, which caused "no animation with name X" errors even with the "default" value of freshly created instances.
So, this allows the animation property to be set even without a valid SpriteFrames. And once one is added, the animation will be changed if necessary to make it valid, making the error pointless.

Fixes #47578 and #28658.
Related to #49495 on the 3.x branch.

2022-07-04 09:45 UTC, kleonc commented on scene/2d/animated_sprite_2d.cpp
> +	}
`set_frame(frame)` validates the `frame` according to the `animation` so I think it makes more sense to firstly try to make the `animation` valid (if it's possible).
```suggestion
	Vector<String> animation_names = frames->get_animation_names();
	if (!animation_names.has(animation) && animation_names.size() != 0) {
		set_animation(animation_names[0]);
	}
	set_frame(frame);
```

2022-07-04 09:46 UTC, akien-mga commented on scene/resources/sprite_frames.cpp
> +	emit_changed();
This should probably go in `add_animation()` instead? Like in #49495.

2022-07-04 20:28 UTC, L4Vo5 commented
Changed the files according to the suggestions
on `_res_changed()`, I put the second `set_frame` on an else block. After all, `set_animation` shouldn't quit early, and it'll call `set_frame(0);` itself

2022-07-15 13:48 UTC, kleonc requested changes
@L4Vo5 Changes made in `AnimatedSprite2D` would need to be done in `AnimatedSprite3D` too.

Also as you can see [static checks fail](https://github.com/godotengine/godot/runs/7187012596?check_suite_focus=true) (formatting issues), you'd need to [apply clang-format](https://docs.godotengine.org/en/3.5/community/contributing/code_style_guidelines.html#using-clang-format-locally) to fix these. I recommend [adding relevant pre-commit hooks](https://docs.godotengine.org/en/3.5/community/contributing/code_style_guidelines.html#pre-commit-hook) to run it automatically when you commit (so you can fix formatting issues immediately).

2022-07-15 13:48 UTC, kleonc commented on scene/2d/animated_sprite_2d.cpp
> +		Vector<String> animation_names = frames->get_animation_names();
@akien-mga This returns sorted animation names, as desired (so its first element is indeed what we want):
https://github.com/godotengine/godot/blob/9904a9db5a90f2f1896b6b7e1603ca2dd2745bad/scene/resources/sprite_frames.cpp#L105-L112

But in other places in the source code `SpriteFrames::get_animation_list()` is being used instead and the obtained list is being sorted separately:
https://github.com/godotengine/godot/blob/9904a9db5a90f2f1896b6b7e1603ca2dd2745bad/scene/resources/sprite_frames.cpp#L99-L103
https://github.com/godotengine/godot/blob/9904a9db5a90f2f1896b6b7e1603ca2dd2745bad/editor/plugins/sprite_frames_editor_plugin.cpp#L985-L987

Both approaches seem to result in the same ordering (both end up comparing with `is_str_less`). But I think we should be consistent and use one over the other. I'd guess sorting a list is probably slower (it probably doesn't matter though) but in the list version there's no StringName -> String conversion (which is also cheap I guess). So is any of these approaches preferred?

2022-07-28 23:54 UTC, L4Vo5 commented
Thanks for the clang help!

> Changes made in AnimatedSprite2D would need to be done in AnimatedSprite3D too.

Should that be a separate PR?
There's a few other differences AnimatedSprite3D has compared with 2D. For example: it can't play backwards, it doesn't support speed scale, and it produces no errors on invalid animations.
That last one would make sense to change if I add AnimatedSprite3D to this PR, but since there's more important differences anyways, I think a separate PR to bring the missing features to AnimatedSprite3D would be better. I can get started on that, and if anything just bring the code to this one.

2022-09-17 21:53 UTC, L4Vo5 commented
Applied changes to AnimatedSprite3D following #64155, which brought the same errors to it (but also made it infinitely easier to make the same changes)

2023-02-08 22:05 UTC, L4Vo5 commented
Hmm, the current fix for 28658 is only in the inspector: it does nothing when deleting animations in code. Still, that makes the issue even more minor than it was before, so this PR is probably not worth keeping as it'd require a full revision to update it just for that.

2023-02-08 22:05 UTC, closed without merging