Fix mixed smoothed and non-smoothed face normals computation for CSG shapes
godotengine/godot pull request #59039
Opened 2022-03-11 18:10 UTC by MythTitans

When computing smoothed normals on CSG shapes, the normals from all the faces sharing a vertex are averaged together to compute the smoothed "shared" normal between the faces.

I don't think the behavior is correct, because it means that even faces that are not smoothed participate to the computation of their smooth neighbor's faces.

The problem is particularly visible when substracting a sphere or a torus from a box, at the edge between them :

**Before**
![smooth_normals_before](https://user-images.githubusercontent.com/1554884/157924889-e81c11e3-10fd-4300-8082-90a7e0e628ae.png)

**After**
![smooth_normals_after](https://user-images.githubusercontent.com/1554884/157924901-bd7d14e9-b2e5-4415-acf6-29979e8854c5.png)

and also on the cylinder which has a strange shading (and a small glitch is visible at the bottom left) :

**Before**
![cylinder_bottom_before](https://user-images.githubusercontent.com/1554884/157924935-c4bfe446-6f19-4e98-bc8c-2cfd07141d9f.png)

**After**
![cylinder_bottom_after](https://user-images.githubusercontent.com/1554884/157924955-9a9f3ed4-ab49-4a06-b865-ad38f1a691d0.png)

This is related to some comments in #49800.

Bugsquad edit:
- Fixes #49800

2022-03-11 18:24 UTC, akien-mga commented
CC @hoontee

2022-03-11 18:45 UTC, hoontee requested changes

2022-03-11 18:45 UTC, hoontee commented on modules/csg/csg_shape.cpp
> +				else {
Works as it should! Be sure to fix this extra newline though. :)

2022-03-11 18:46 UTC, hoontee commented
Fixes #49800.

2022-03-11 18:49 UTC, akien-mga commented
After fixing the style issue, be sure to rebase to squash the commits into one (see https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).

2022-03-11 18:56 UTC, Calinou commented
By the way, this likely supersedes https://github.com/godotengine/godot-proposals/issues/1862. Great work :slightly_smiling_face:

2022-03-11 18:56 UTC, MythTitans commented
@akien-mga Thanks, I'll read and try that

2022-03-11 19:44 UTC, hoontee commented
> By the way, this likely supersedes [godotengine/godot-proposals#1862](https://github.com/godotengine/godot-proposals/issues/1862). Great work 🙂

No, there are still instances where angle based smoothing would be appreciable. Note the odd lighting on the cylinder due to a lack of hard edges around the sphere negation:
![image](https://user-images.githubusercontent.com/5272529/157947449-5bf1e661-4241-41ab-b022-25e509d2994a.png)

2022-03-11 20:00 UTC, hoontee approved these changes

2022-03-11 22:48 UTC, akien-mga approved these changes

2022-03-11 22:48 UTC, merged

2022-03-11 22:48 UTC, akien-mga commented
Thanks!

2022-03-12 13:57 UTC, akien-mga commented
Cherry-picked for 3.5.

2022-03-13 14:35 UTC, akien-mga commented
Cherry-picked for 3.4.4.