Add Unit Tests for InputEventKey
godotengine/godot pull request #59193
Opened 2022-03-16 13:46 UTC by UltraTimon

This PR adds unit tests for the InputEventKey class.

I tried to test both happy paths and failure paths, such that each part of the if statement gets executed.
If you have any comments or remarks, please let me know!

This PR is part of #43440.

2022-05-02 16:39 UTC, Geometror requested changes
Looks good :)
Just a few style nitpicks: For some variable names you use camelCase, but snake_case should be used instead. (e.g. `noneKey`, `refKey`, `noneRef`,...)

2022-05-02 16:45 UTC, Geometror requested changes, later dismissed

2022-05-02 16:45 UTC, Geometror commented on tests/core/input/test_input_event_key.h
> +/*  test_input_event_key.h                                                        */
```suggestion
/*  test_input_event_key.h                                               */
```

2022-08-04 11:01 UTC, akien-mga approved these changes
Force pushed a rebase to solve style issues, should be good to go now.

I didn't do a thorough review of the actual tests, I think we might want to check a bit more in depth and see if we don't want to further improve the logic of InputEventKey.

For example the fact that physical/non-physical state is based solely on the value of `keycode` being `NONE` or not, and the text representation of this event.

2022-08-04 11:29 UTC, merged

2022-08-04 11:30 UTC, akien-mga commented
Thanks!