Fix getaddrinfo failed with undefined proxy config
godotengine/godot pull request #59351
Opened 2022-03-20 13:11 UTC by taisph

HTTPClientTCP expects proxy host to be empty or port to be -1 to ignore
the proxy. When getting the proxy config from the settings file, the
values will default to U"null" and 0, respectively, making HTTPClientTCP
to attempt to use the values as a proxy, which causes getaddrinfo to
fail looking up a "null" hostname.

Setting the default config values seems like a good approach to prevent
this issue.

Fixes #59037

2022-03-20 13:27 UTC, timothyqiu commented
My fault. I was not familiar with the editor settings system at the time of writing :( and this seems like my manual cherry-pick error from the `3.x` version.

Now I learned that these usages should be `EDITOR_GET(name)`, and the best practice is to define settings in either:

* In `EditorSettings::_load_defaults()` with `_initial_set(name, default_value)`, or
* In `EditorNode::EditorNode()` with `EDITOR_DEF(name, default_value)`.

2022-03-20 16:24 UTC, taisph commented
> My fault. I was not familiar with the editor settings system at the time of writing :( and this seems like my manual cherry-pick error from the `3.x` version.
> 
> Now I learned that these usages should be `EDITOR_GET(name)`, and the best practice is to define settings either
> 
> * In `EditorSettings::_load_defaults()` with `_initial_set(name, default_value)`, or
> * In `EditorNode::EditorNode()` with `EDITOR_DEF(name, default_value)`.

Thank you for the pointers. I've updated the PR to define the config parameters in EditorSettings. This actually made them configurable in the editor settings dialog which I found out they weren't before.

2022-03-21 00:56 UTC, mhilbrunner approved these changes
Had no time to test this, but the original issue, the reasoning outlined here and the changes make sense to me.

2022-03-21 01:40 UTC, timothyqiu requested changes
~~These two settings are also used in `editor/export_template_manager.cpp`. They have to be changed to `EDITOR_GET` too. Otherwise we have two different default value defined in the code.~~ Sorry, I looked at the wrong version :(

2022-03-21 01:42 UTC, timothyqiu approved these changes
Sorry, I looked at the wrong version. Looks good to me.

2022-03-21 07:11 UTC, merged

2022-03-21 07:11 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: