[3.x] Bind NOTIFICATION_LOCAL_TRANFORM_CHANGED
godotengine/godot pull request #59353
Opened 2022-03-20 14:02 UTC by jasonwinterpixel

The NOTIFICATION_LOCAL_TRANFORM_CHANGED constant is not exposed to GDScript, which means that using `canvas_item.set_notify_local_transform` requires hard coding '35' into your GDScript.

This PR binds this constant to GDScript.

2022-03-20 16:21 UTC, Calinou commented on doc/classes/CanvasItem.xml
> +				If [code]enable[/code] is [code]true[/code], this node will receive [constant NOTIFICATION_LOCAL_TRANSFORM_CHANGED] when it's local transform changes.
```suggestion
				If [code]enable[/code] is [code]true[/code], this node will receive [constant NOTIFICATION_LOCAL_TRANSFORM_CHANGED] when its local transform changes.
```

2022-03-20 16:22 UTC, Calinou requested changes, later dismissed

2022-03-20 16:22 UTC, Calinou commented on doc/classes/CanvasItem.xml
> +				If [code]enable[/code] is [code]true[/code], this node will receive [constant NOTIFICATION_LOCAL_TRANSFORM_CHANGED] when it's local transform changes.
Possessive "its" doesn't have an apostrophe:

```suggestion
				If [code]enable[/code] is [code]true[/code], this node will receive [constant NOTIFICATION_LOCAL_TRANSFORM_CHANGED] when its local transform changes.
```

2022-03-20 16:22 UTC, Calinou commented on doc/classes/CanvasItem.xml
> +				If [code]enable[/code] is [code]true[/code], this node will receive [constant NOTIFICATION_TRANSFORM_CHANGED] when it's global transform changes.
```suggestion
				If [code]enable[/code] is [code]true[/code], this node will receive [constant NOTIFICATION_TRANSFORM_CHANGED] when its global transform changes.
```

2022-03-20 17:34 UTC, jasonwinterpixel commented
Good catch. Fixed.

2022-03-21 11:27 UTC, akien-mga approved these changes

2022-03-21 11:27 UTC, merged