Add better alert dialogs if directory already exists
godotengine/godot pull request #59495
Opened 2022-03-24 23:23 UTC by DanielKriz

Checks if directory already exists and depending on that prints better Alert/Warning messages.

Implements: godotengine/godot-proposals#3809

I found out that in are few commented code lines in [editor/editor_dir_dialog.cpp ](https://github.com/godotengine/godot/blob/391633760b0ea292af079287faf79c1aee6d9254/editor/editor_dir_dialog.cpp) (on lines [60](https://github.com/godotengine/godot/blob/391633760b0ea292af079287faf79c1aee6d9254/editor/editor_dir_dialog.cpp#L60), [167](https://github.com/godotengine/godot/blob/391633760b0ea292af079287faf79c1aee6d9254/editor/editor_dir_dialog.cpp#L167) and [195](https://github.com/godotengine/godot/blob/391633760b0ea292af079287faf79c1aee6d9254/editor/editor_dir_dialog.cpp#L195)) Most of them are several *years* old and I think that they might be deleted, but that should be matter of another PR.

Also, the process of adding a new directory is functionally almost the same across all files that this PR changes, but the naming and error popup handling is inconsistent, perhaps that happens on other places in the code base and it should be changed to one more consistent approach?

2022-03-24 23:59 UTC, YeldhamDev requested changes

2022-03-24 23:59 UTC, YeldhamDev commented on editor/editor_file_dialog.cpp
> +		error_dialog->set_text(TTR("Could not create folder. File iwth that name already exists"));
```suggestion
		error_dialog->set_text(TTR("Could not create folder. File with that name already exists."));
```

2022-03-24 23:59 UTC, YeldhamDev commented on editor/editor_file_dialog.cpp
> +		makedirname->set_text(""); // reset label
```suggestion
		makedirname->set_text(""); // Reset label.
```

2022-03-25 13:57 UTC, YeldhamDev approved these changes

2022-03-25 14:13 UTC, DanielKriz commented
@YeldhamDev What about that failed check?

2022-03-25 14:20 UTC, YeldhamDev commented
@DanielKriz The CI failed to create the artifacts for Windows originally. Doesn't seem that the error was caused by the PR itself, so don't worry.

2022-03-25 15:22 UTC, merged

2022-03-25 15:22 UTC, akien-mga commented
Thanks!