Fix incorrect 'drag_from' assignment of GraphNodes
godotengine/godot pull request #59954
Opened 2022-04-06 18:02 UTC by sriramun

Fixes #59843

2022-04-06 18:04 UTC, YeldhamDev requested changes

2022-04-06 18:04 UTC, YeldhamDev commented on scene/gui/graph_node.cpp
> +
```suggestion
```

This empty line is unnecessary.

2022-04-06 18:12 UTC, YeldhamDev requested changes

2022-04-06 18:12 UTC, YeldhamDev commented on scene/gui/graph_node.cpp
> +	if (drag_from == Vector2(0,0)) {
```suggestion
	if (drag_from == Vector2(0, 0)) {
```

2022-04-06 18:32 UTC, YeldhamDev approved these changes
It fixes the bug, but I don't have much experience with `GraphNode`, so I want the opinion of another maintainer as well.
And if everything is fine, it should  also be ported to `master`, as the bug happens there as well.

2022-09-12 16:48 UTC, Geometror reviewed
I can confirm that this fixes the issue. However, there are a couple of ways to fix this, I'm not sure if this is the best one (although I'm not completely opposed to merging). It really depends on how we want the API to work. For now, I think it should probably be done in GraphEdit since that class is actually responsible for the whole dragging logic. (GraphNode's set_drag and get_drag_from are not exposed and only used by GraphEdit). So here is what we could do: (No guarantees that the following will work) GraphEdit can update `drag_from` via `set_drag` when several nodes are selected and the user begins the drag.
As an alternative, just inserting
```cpp
drag_from = get_position_offset();
```
in `set_selected` also fixes the issue.

2022-09-12 17:01 UTC, YuriSizov commented
> although I'm not completely opposed to merging

For the record, I am opposed. I haven't looked deep into it, but I don't like that this PR compares things to `Vector2(0, 0)` and that the getter is changing the value internally. Getters should be `const` or at least avoid modifying the internal field. So this doesn't feel like a good solution.

2023-02-21 11:03 UTC, YuriSizov commented
I'll close this based on my comment above. A different solution is needed. And we should fix it in `master` too.

2023-02-21 11:03 UTC, closed without merging