Disallow setting editor-only metadata in the editor
godotengine/godot pull request #59969
Opened 2022-04-07 02:00 UTC by RechieKho

Issue: https://github.com/godotengine/godot/issues/59852

![NotAllow](https://user-images.githubusercontent.com/50512341/162104909-0165cf48-2c7a-4027-9a08-dd4b0021c46c.png)

Metadata starts with `_` considered as editor-only metadata and disallowed as mentioned in the issue. 

A bit sorry for [Ayush-singla27](https://github.com/Ayush-singla27), it has been 3 days and it really just need a few lines of code (or maybe Ayush already make a PR and I don't know how to use github). This is, too, my first contribution to me beloved game engine.

2022-04-19 18:42 UTC, Calinou requested changes

2022-04-19 18:42 UTC, Calinou commented on editor/editor_inspector.cpp
> +		error = TTR("Editor-only metadata only allowed setting in code.");
Use a more informative error message:

```suggestion
		error = TTR("Names starting with _ are reserved for editor-only metadata.");
```

2022-05-02 01:42 UTC, RechieKho commented
Commited

2022-05-04 23:21 UTC, Calinou approved these changes
Looks good to me, please squash the commits together so we can merge this. See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) for instructions :slightly_smiling_face:

2022-05-05 16:41 UTC, merged

2022-05-05 16:42 UTC, akien-mga commented
Thanks!

2022-05-05 16:44 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: