Improve shaped_text_get_word_breaks()
godotengine/godot pull request #60102
Opened 2022-04-10 15:40 UTC by KoBeWi

Inspired by #55228
- adds missing default arguments to the method
- improves documentation

Closes #55228 (but the actual error the issue mentions was already fixed)

2022-04-10 15:42 UTC, bruvzg requested changes

2022-04-10 15:42 UTC, bruvzg commented on doc/classes/TextServer.xml
> +				Breaks text into words and returns array of character ranges. Use [code]grapheme_flags[/code] to set what characters are used for breaking (see [enum LineBreakFlag]).
```suggestion
				Breaks text into words and returns array of character ranges. Use [code]grapheme_flags[/code] to set what characters are used for breaking (see [enum GraphemeFlag]).
```

2022-04-10 15:44 UTC, bruvzg approved these changes

2022-04-11 15:49 UTC, merged

2022-04-11 15:49 UTC, akien-mga commented
Thanks!