Fix opaqueness of Sprite2D
godotengine/godot pull request #60149
Opened 2022-04-11 18:17 UTC by sriramun

Completed repeat mode compatibility in Sprite2D nodes with appropriate assignments.

2022-04-11 18:18 UTC, sriramun commented
Related issue: #60141

2022-04-24 22:16 UTC, KoBeWi requested changes
This does not work if repeat comes from the parent node. That's because `get_texture_repeat()` returns the repeat you have set in node, not the "final" value.

You need to implement a function that returns repeat based on hierarchy (as mentioned in the comment you removed :v )

Something like: (not tested)
```C++
CanvasItem *ci = this;
while (ci) {
    if (ci->get_texture_repeat() != TEXTURE_REPEAT_PARENT_NODE) {
        return ci->get_texture_repeat();
    } else {
        ci = ci->get_parent_item();
    }
}

if (get_viewport()) {
    return get_viewport()->get_default_canvas_item_texture_repeat();
}

return get_texture_repeat();
```
Should be in CanvasItem.

2022-10-19 22:02 UTC, KoBeWi commented
@sriramun You should update your PR with the new method from #66546

2023-01-12 14:53 UTC, YuriSizov commented
Bump :) Let us know if you are available to finish this!

2023-02-17 11:46 UTC, akien-mga commented
Closing as this is not the right solution and is not being worked on further.

2023-02-17 11:46 UTC, closed without merging