Fix error messages for hours, minutes, and seconds when datetime string is negative
godotengine/godot pull request #60201
Opened 2022-04-13 09:21 UTC by laws65

Resolves #60192. Works by changing type of hour, second, and minute in the PARSE_IS08601_STRING macro from uint8_t to int16_t, allowing it to be read as negative, allowing it to be properly validated in the VALIDATE_YMDHMS macro.

2022-04-14 15:22 UTC, aaronfranke requested changes
We should also do the same for the month and day.

2022-04-14 15:22 UTC, aaronfranke commented on core/os/time.cpp
> +	int16_t second = 0;                                           \
Since `split_ints` gives us `int`, we should likely just use `int` here, in case someone tries to parse `32770`.

2022-04-15 18:23 UTC, aaronfranke commented on core/os/time.h
> +	enum Month : int16_t {
```suggestion
	enum Month {
```

2022-04-15 18:23 UTC, aaronfranke commented on core/os/time.cpp
> +	int16_t day = p_datetime.has(DAY_KEY) ? int16_t(p_datetime[DAY_KEY]) : 1;                     \
```suggestion
	Month month = Month((p_datetime.has(MONTH_KEY)) ? int(p_datetime[MONTH_KEY]) : 1);        \
	int day = p_datetime.has(DAY_KEY) ? int(p_datetime[DAY_KEY]) : 1;                     \
```

2022-04-15 18:25 UTC, aaronfranke commented on core/os/time.cpp
> +	int16_t second = p_datetime.has(SECOND_KEY) ? int16_t(p_datetime[SECOND_KEY]) : 0;
```suggestion
	int hour = p_datetime.has(HOUR_KEY) ? int (p_datetime[HOUR_KEY]) : 0;                  \
	int minute = p_datetime.has(MINUTE_KEY) ? int (p_datetime[MINUTE_KEY]) : 0;            \
	int second = p_datetime.has(SECOND_KEY) ? int (p_datetime[SECOND_KEY]) : 0;
```

2022-04-15 22:25 UTC, aaronfranke commented
This PR needs to be rebased now that #60215 was merged.

2022-04-16 17:04 UTC, aaronfranke reviewed
This PR needs a [rebase and squash](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html), but otherwise the code looks good.

2022-04-16 17:04 UTC, aaronfranke commented on core/os/time.cpp
> +	ERR_FAIL_COND_V_MSG(day == 0, ret, "Invalid day value of: " + itos(day) + ", days are 1-indexed and cannot be 0.");                                                   \
Nice catch!

2022-04-17 23:46 UTC, laws65 commented
All good, right? GitHub says there's a change requested but I can't see what it is

2022-04-21 02:01 UTC, aaronfranke approved these changes

2022-04-23 00:21 UTC, merged

2022-04-23 00:21 UTC, aaronfranke commented
Thanks for your contribution!

2022-04-27 10:22 UTC, akien-mga commented
Cherry-picked for 3.5.