END key state on navigating lines for TextEdit
godotengine/godot pull request #60239
Opened 2022-04-14 13:50 UTC by rohanrhu

Meooowww... I made END key state for TextEdit.

Looks like this:
![godot-end-key-state](https://user-images.githubusercontent.com/1125150/163404738-8b6e8731-e54a-461d-a742-18d20c69d6a8.gif)

2022-04-14 14:05 UTC, rohanrhu commented
Can we re-run workflows? I removed trailing whitespace.

2022-04-27 16:42 UTC, Paulb23 requested changes
Can we not set `caret.last_fit_x` to a very large value rather then adding more state here?

Secondly, recently `TextEdit` unit test have been added, any chance you could create one for this?

2022-04-28 18:04 UTC, rohanrhu commented
@Paulb23 Okiii I will look.

2022-04-28 18:43 UTC, rohanrhu commented
> Can we not set `caret.last_fit_x` to a very large value rather then adding more state here?

I tried to set it to high value on in `TextEdit::_move_caret_to_line_end()` but it doesn't work.

2022-04-29 12:10 UTC, Paulb23 requested changes
> I tried to set it to high value on in TextEdit::_move_caret_to_line_end() but it doesn't work.

Seems to work okay for me? `set_caret_column` will reset the value, so it needs to be adjusted it at the end of the method.

Should also probably test behaviour around wrapped lines.

2022-04-30 05:22 UTC, rohanrhu commented
> Seems to work okay for me? `set_caret_column` will reset the value, so it needs to be adjusted it at the end of the method.

Hiiii @Paulb23 yesss I figured out that this time 😊

Buuuuuut I think `is_eol` state is better because because it works for all cases like folding the line that we go to end of:

With `is_eol` state:
![is_eol](https://user-images.githubusercontent.com/1125150/166092413-d2b1a582-f5f9-4c51-b689-72af02216af7.gif)

With setting `caret.last_fit_x` to `INT_MAX`:
![last_fit_x](https://user-images.githubusercontent.com/1125150/166092422-12774600-5c07-4d67-bc76-59af9f4ce933.gif)

2022-05-01 12:08 UTC, Paulb23 commented
> it works for all cases like folding

We should be able to add a small check in `CodeEdit` for that, so we don't set the `caret` column if it's already eol.

2022-05-01 12:31 UTC, rohanrhu commented
> > it works for all cases like folding
> 
> We should be able to add a small check in `CodeEdit` for that, so we don't set the `caret` column if it's already eol.

We could check if it is `INT_MAX`.

2022-05-01 13:17 UTC, Paulb23 commented
> We could check if it is INT_MAX.

We'd have to expose `last_fit_x` for that to work, which I'm not a big fan of, for this single usecase.

2022-05-01 14:00 UTC, rohanrhu commented
> > We could check if it is INT_MAX.
> 
> We'd have to expose `last_fit_x` for that to work, which I'm not a big fan of, for this single usecase.

If you mean "checking if it is end of current line" with that, it would be bad imo because the common end key behaviour for text editors is like that if you go to end of line with arrows, it is not end state but if you use end key it is end state.

What do you want me to meow exactly? `is_eol` is good and enough imo. 😊

2022-05-02 16:20 UTC, Paulb23 commented
> What do you want me to meow exactly? `is_eol` is good and enough imo.

Not a fan of the extra state, when we can handle it with an existing system.

I'm proposing, on end key press we set `caret.last_fit_x `to `INT_MAX`. Then in `CodeEdit::fold_line`, if the caret is already eol, skip calling `set_caret_column` after `set_caret_line`, to avoid updating `caret.last_fit_x `.

2022-05-04 17:22 UTC, Paulb23 requested changes
> If it is a bug, I can look for it too and send another PR.

I'm pretty sure that's expected behaviour, easier to understand visually, rather then in terms of column count.

2026-07-21 17:14 UTC, kitbdev commented
Thanks for the contribution!
- Closing as superseded by https://github.com/godotengine/godot/pull/97932
- Also see the proposal https://github.com/godotengine/godot-proposals/issues/10930

2026-07-21 17:14 UTC, closed without merging