Prevent blank command prompts from spawning when building a mono project
godotengine/godot pull request #60956
Opened 2022-05-11 23:58 UTC by macjuul

When building a mono solution or opening a script in an external editor a short-lived blank command prompt is displayed. I've made these hidden since they don't appear to provide any actual use.

Since im unsure if this affects other platforms besides windows here is an example of what it used to look like
![Godot_4_TnyvJZNHSI](https://user-images.githubusercontent.com/7606171/167965633-ace43255-304e-4385-8a70-11551fd03482.gif)

2022-05-12 04:27 UTC, neikeq requested changes

2022-05-12 04:27 UTC, neikeq commented on modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs
> +			};
Bad indentation here

2022-05-12 11:53 UTC, macjuul commented on modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs
> +			};
Thanks! Fixed and force pushed

2022-05-12 18:46 UTC, neikeq approved these changes

2022-05-12 19:23 UTC, merged

2022-05-12 19:23 UTC, akien-mga commented
Thanks!

2022-05-16 14:55 UTC, akien-mga commented
Cherry-picked for 3.5.