Tweak minsize of editor ColorPickerButtons
godotengine/godot pull request #61133
Opened 2022-05-17 20:47 UTC by KoBeWi

Follow-up to #60867
I set the size to twice the default font size and it looks the same as before:
![image](https://user-images.githubusercontent.com/2223172/168906826-f013469d-38ab-4239-9438-989f00ae12f5.png)
On bigger editor font sizes the buttons automatically adjust, on smaller sizes they are bigger than text.

2022-05-18 00:10 UTC, fire-forge requested changes
It needs to take editor scale (`EDSCALE`) into account. To do that, it might be better to store ColorPickerButton min size in the editor theme. It can be stored as a theme constant, and usages of `EditorNode::COLOR_PICKER_BUTTON_SIZE` can be replaced with `Size2(0, get_theme_constant(SNAME("color_picker_button_height"), SNAME("Editor"))`

2022-05-19 13:22 UTC, KoBeWi commented
Changed to theme constant.

2022-05-19 15:14 UTC, fire-forge approved these changes

2022-05-19 15:25 UTC, akien-mga approved these changes

2022-05-19 15:26 UTC, merged

2022-05-19 15:26 UTC, akien-mga commented
Thanks!