Add missing properties to default theme
godotengine/godot pull request #61328
Opened 2022-05-23 17:06 UTC by KoBeWi

- added functional theme properties that existed in editor theme, but not default theme: GraphEdit `title_h_offset`, OptionButton `modulate_arrow`
- removed unused properties: LineEdit `read_only`, TooltipLabel `font_color_shadow`
- fixed `modulate_arrow` displaying wrong color for DRAW_HOVER_PRESSED
- implemented missing disabled icons in PopupMenu (and added them to default theme)

Resolves #33370

2022-08-03 17:56 UTC, YuriSizov requested changes
After a couple of fixes, should be good to merge.

2022-08-03 17:56 UTC, YuriSizov commented on scene/gui/option_button.cpp
> +						clr = get_theme_color(SNAME("font_hover_pressed_color"));
Should add explicitly to the default theme then, as it is only defined for the base class, but `OptionButton` type redefines all the other colors.

2022-08-03 17:56 UTC, YuriSizov commented on editor/editor_themes.cpp
> -	theme->set_color("font_color_shadow", "TooltipLabel", Color(0, 0, 0, 0));
It's not unused, but it was missed in some rename. Should be `font_shadow_color`. Default theme has this defined correctly.

2022-08-03 17:56 UTC, YuriSizov commented on editor/plugins/texture_editor_plugin.cpp
> -		metadata_label->add_theme_color_override("font_color_shadow", Color::named("black"));
Same, should be `font_shadow_color`.

2022-08-03 17:56 UTC, YuriSizov commented on editor/editor_themes.cpp
> -	theme->set_color("read_only", "LineEdit", font_disabled_color);
Seems to be `font_uneditable_color` instead, which is defined below anyway, but to a different color. I wonder...

2022-08-06 19:31 UTC, reduz approved these changes

2022-08-06 19:31 UTC, reduz commented
It look good to me in general, please arrange with @YuriSizov what may be needed to be fixed.

2022-08-11 13:26 UTC, YuriSizov approved these changes

2022-08-11 13:26 UTC, merged

2022-08-11 13:26 UTC, YuriSizov commented
Thanks!