Fixed dragging curve points
godotengine/godot pull request #61628
Opened 2022-06-02 11:13 UTC by Vitika9

Fixes #61617

2022-06-02 17:40 UTC, raulsntos reviewed
The problem seems to be that calling `notify_property_list_changed` causes the inspector to interrupt the dragging.

This PR tries to fix that by moving the call from `Curve::mark_dirty` to `CurveEditor::gui_input` (when the dragging is finished). This has the side-effect of no longer calling it in many other cases (such as when adding/deleting a point from the curve) which means the list of points in the inspector no longer gets updated.

**EDIT:** After asking in the dev chat I was told the method `notify_property_list_changed` should only be called when the list of points is modified (list elements are added/removed) not when their value is modified. This means this PR is correct in removing the call from `Curve::mark_dirty` but the call should be added to the `Curve` methods that add/remove points. This would also need to be done to `Curve2D` and `Curve3D` since I made the same mistake there, but you don't need to do it in this PR.

2022-06-03 08:25 UTC, Vitika9 commented
> The problem seems to be that calling `notify_property_list_changed` causes the inspector to interrupt the dragging.
> 
> This PR tries to fix that by moving the call from `Curve::mark_dirty` to `CurveEditor::gui_input` (when the dragging is finished). This has the side-effect of no longer calling it in many other cases (such as when adding/deleting a point from the curve) which means the list of points in the inspector no longer gets updated.
> 
> **EDIT:** After asking in the dev chat I was told the method `notify_property_list_changed` should only be called when the list of points is modified (list elements are added/removed) not when their value is modified. This means this PR is correct in removing the call from `Curve::mark_dirty` but the call should be added to the `Curve` methods that add/remove points. This would also need to be done to `Curve2D` and `Curve3D` since I made the same mistake there, but you don't need to do it in this PR.

Following your instructions, I moved the call to `Curve::add_point`, `Curve::remove_point` and `Cruve::clear_points`, but the dragging problem still exists.

2022-06-03 08:52 UTC, Vitika9 commented
@raulsntos the problem is with `set_point_offset` which is calling `remove_point` and `add_point` as it's getting called while dragging.

2022-06-03 16:14 UTC, raulsntos commented
You are right, `set_point_offset` re-adds the point to keep them in order but that doesn't seem to require a call to `notify_property_list_changed`.

The method `mark_dirty` should still be called even when not calling `notify_property_list_changed`, since the point values changed so the baked points are now outdated and need to be recalculated. I believe calling `mark_dirty` should not interrupt dragging.

I'm not sure if I like having two methods for adding/removing points with the only difference being whether `notify_property_list_changed` is called, maybe @akien-mga can review this part.

You have also accidentally added an empty file `add_point(point_pos)`.

2022-06-03 17:26 UTC, Vitika9 commented
> You are right, `set_point_offset` re-adds the point to keep them in order but that doesn't seem to require a call to `notify_property_list_changed`.
> 
> The method `mark_dirty` should still be called even when not calling `notify_property_list_changed`, since the point values changed so the baked points are now outdated and need to be recalculated. I believe calling `mark_dirty` should not interrupt dragging.
> 
> I'm not sure if I like having two methods for adding/removing points with the only difference being whether `notify_property_list_changed` is called, maybe @akien-mga can review this part.
> 
> You have also accidentally added an empty file `add_point(point_pos)`.

2022-06-03 17:38 UTC, Vitika9 commented
> The method `mark_dirty` should still be called even when not calling `notify_property_list_changed`, since the point values changed so the baked points are now outdated and need to be recalculated. I believe calling `mark_dirty` should not interrupt dragging.

> You have also accidentally added an empty file `add_point(point_pos)`.
Done, thanks for the review!

2022-06-22 09:48 UTC, akien-mga commented
> I'm not sure if I like having two methods for adding/removing points with the only difference being whether `notify_property_list_changed` is called, maybe @akien-mga can review this part.

That's OK but the names are a bit unconventional. Usually this would be done by rename `add_point` to `_add_point` and making it private, and then adding a new `add_point` that calls `_add_point` + `notify_property_list_changed`. Just renaming `add_point` to `_add_point` should reduce the diff compared to moving it around in the `.cpp` to a new location.

2022-06-22 12:36 UTC, akien-mga approved these changes

2022-06-22 14:46 UTC, raulsntos requested changes
Looks great! Just gave it one last checked and realized I forgot about `set_point_count`, since `mark_dirty` now doesn't call `notify_property_list_changed` it needs to be added there:

```diff
diff --git a/scene/resources/curve.cpp b/scene/resources/curve.cpp
index 361ec2a585..b9235f1a21 100644
--- a/scene/resources/curve.cpp
+++ b/scene/resources/curve.cpp
@@ -54,6 +54,7 @@ void Curve::set_point_count(int p_count) {
        if (_points.size() >= p_count) {
                _points.resize(p_count);
                mark_dirty();
+               notify_property_list_changed();
        } else {
                for (int i = p_count - _points.size(); i > 0; i--) {
                        add_point(Vector2());
```

2022-06-22 16:38 UTC, kleonc commented
The cause of what @KoBeWi mentioned: setting preset triggers `Curve::set_data()` (bounded as `_set_data`) which calls `Curve::mark_dirty()` which was modified in this PR to not call `notify_property_list_changed()`.
https://github.com/godotengine/godot/blob/d8ef904ffcad2ab07947918fcfdad59c2ea034d8/editor/plugins/curve_editor_plugin.cpp#L303-L309
https://github.com/godotengine/godot/blob/e312fd8ead553adc813d87da8d6b6d30f91b53d5/scene/resources/curve.cpp#L443

2022-06-22 17:27 UTC, raulsntos approved these changes

2022-06-23 13:36 UTC, merged

2022-06-23 13:36 UTC, akien-mga commented
Thanks!