Improve EditorPlugin state documentation
godotengine/godot pull request #61659
Opened 2022-06-03 12:16 UTC by KoBeWi

This PR provides more details for `_get_state`, `_get_window_layout`, `_set_state` and `_set_window_layout` methods.

2022-06-03 13:37 UTC, Calinou requested changes, later dismissed

2022-06-03 13:37 UTC, Calinou commented on doc/classes/EditorPlugin.xml
> +				Override this method to provide the GUI layout of the plugin or just any data you want to be stored. This is used to save the project's editor layout when [method queue_save_layout] is called or
```suggestion
				Override this method to provide the GUI layout of the plugin or any other data you want to be stored. This is used to save the project's editor layout when [method queue_save_layout] is called or the editor layout was changed (for example changing the position of a dock). The data is stored in the [code]editor_layout.cfg[/code] file in the editor metadata directory.
```

2022-06-03 13:37 UTC, Calinou commented on doc/classes/EditorPlugin.xml
> +				Override this method to provide a state data you want want to be saved, like view position, grid settings, folding etc. This is used when saving the scene (so state is kept when opening it again)
```suggestion
				Override this method to provide a state data you want to be saved, like view position, grid settings, folding, etc. This is used when saving the scene (so state is kept when opening it again) and for switching tabs (so state can be restored when the tab returns). This data is automatically saved for each scene in an [code]editstate[/code] file in the editor metadata folder. If you want to store global (scene-independent) editor data for your plugin, you can use [method _get_window_layout] instead.
```

2022-06-09 07:57 UTC, akien-mga approved these changes

2022-06-09 07:57 UTC, merged

2022-06-09 07:57 UTC, akien-mga commented
Thanks!

2022-06-09 08:42 UTC, akien-mga commented
Cherry-picked for 3.5.