Add an option to jitter shadow map dithering pattern across frames
godotengine/godot pull request #61834
Opened 2022-06-09 00:13 UTC by Calinou

If set to Auto (the default), jittering is enabled whenever TAA is also enabled. With TAA, jittering will look the best regardless of the monitor refresh rate, framerate or monitor response time.

If set to Always, when TAA is disabled, this makes the dithering pattern less noticeable as the monitor will smear across frames (due to its reponse time not being instant). When TAA is disabled, the effect works best on high refresh rate monitors (> 80 Hz) and at high framerates (> 80 FPS). That said, even at lower framerates, jittering the shadow pattern may still be desired to prevent the dithering pattern from "following" the camera as it moves and rotates.

If set to Never, the existing behavior before this commit is used. The shadow filtering quality won't improve when TAA is enabled. This is mostly useful for troubleshooting, but may also be desired when image stability needs to be maximized.

## Preview

2022-06-09 00:16 UTC, Calinou commented on servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp
> +	if (shadows_use_jitter_get() == RS::SHADOW_JITTER_ALWAYS || (shadows_use_jitter_get() == RS::SHADOW_JITTER_AUTO && !p_render_data->taa_jitter.is_equal_approx(Vector2()))) {
Is there a more efficient way to check whether TAA is enabled?

Also, when TAA is enabled, `taa_jitter` is sometimes `Vector2(0, 0)` (always 4 times in a row, it seems). Maybe this is part of secondary passes though.

2022-06-09 00:19 UTC, Calinou commented on servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> +		float r = quick_hash(gl_FragCoord.xy + frame * 3) * 2.0 * M_PI;
No rendering books were harmed in the making of this dither jittering :slightly_smiling_face: 

On a more serious note, this is the same algorithm I used in my initial proof of concept (before TAA was merged). This algorithm works pretty well when TAA is enabled, but is not always ideal when TAA is disabled (at least at lower framerates). Any ideas for cheap jittering patterns that could provide better results.

2022-06-09 06:03 UTC, clayjohn commented on servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> +		float r = quick_hash(gl_FragCoord.xy + frame * 3) * 2.0 * M_PI;
The way the current per-pixel rotation works is actually already optimized to work with TAA. What you want to do is instead increase r (the rotation amount) by the proportion of the TAA cycle you are in e.g. TAA_FRAME/NUMBER_OF_JITTERS. So if you use 16 different jittered samples, you would use ``(frame %16)/16``. Then, add it to the result of quick_hash before multiplying by TAU. 

Remember ``r`` represents a rotation of the Vogel disk. It is not a dither. We rotate the Vogel disk randomly per pixel to break up patterns, but we also want to rotate it over time. 

The beauty of the Vogel disk is that, when rotated, the path created by each sample will not overlap the path from another. So by using a rotation, you are able to spread the samples out and maximize the benefit of the TAA

2022-06-09 17:38 UTC, Calinou commented on servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> +		float r = quick_hash(gl_FragCoord.xy + frame * 3) * 2.0 * M_PI;
Done. I pushed a second commit so it can be reviewed separately.

Visual comparisons: https://imgsli.com/MTExNzA1, https://imgsli.com/MTExNzA2

2022-06-28 21:33 UTC, clayjohn requested changes
Testing this out locally I noticed that the temporal supersampling seemed to introduce some artifacts in the penumbra that weren't their before. So I returned to http://www.iryoku.com/next-generation-post-processing-in-call-of-duty-advanced-warfare to see what we are missing and noticed something interesting. The author suggests an approach for use with 2X SMAA, he says you should use ``IGN() * 0.5 + frame`` where frame flips between ``0.0`` and ``0.5``. I realized that as implemented the rotation ranges from ``0`` to ``4 * PI`` because both IGN and frame range between 0 and 1. This creates an issue where it is possible to sample the same (or essentially the same) rotation twice. Removing the ``2.0`` multiplier restores the range to ``0`` to `` 2 * PI`` and improves the result. 

One final optimization, since we are only using ``frame`` to calculate this rotation. And since we are using 32 bits anyway, we might as well pass ``frame`` as a float with ``JITTER_FRACTION`` baked in.

2022-06-28 21:33 UTC, clayjohn commented on servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> +		float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * 2.0 * M_PI;
```suggestion
		float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * M_PI;
```

2022-06-28 21:33 UTC, clayjohn commented on servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> +		float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * 2.0 * M_PI;
```suggestion
		float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * M_PI;
```

2022-06-28 21:33 UTC, clayjohn commented on servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> +		float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * 2.0 * M_PI;
```suggestion
		float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * M_PI;
```

2022-06-28 21:33 UTC, clayjohn commented on servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> +		float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * 2.0 * M_PI;
```suggestion
		float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * M_PI;
```

2022-06-28 21:33 UTC, clayjohn commented on servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> +				float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * 2.0 * M_PI;
```suggestion
				float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * M_PI;
```

2022-06-28 21:33 UTC, clayjohn commented on servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> +				float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * 2.0 * M_PI;
```suggestion
				float r = (quick_hash(gl_FragCoord.xy) + frame * JITTER_FRACTION) * M_PI;
```

2022-06-28 21:34 UTC, clayjohn commented on servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> +		float r = quick_hash(gl_FragCoord.xy + frame * 3) * 2.0 * M_PI;
> Even with TAA enabled, when jittering is enabled, I can sometimes see diagonal (but mostly vertical) lines appearing on the dithering pattern sometimes. I don't know why.

I figured it out in my review below.

2022-06-28 23:07 UTC, Calinou commented
I've tried the above change and optimization but it makes shadows flicker wildly while TAA is enabled and the camera is moving. It looks good when still, but it's worse than before when the camera is moving.

2022-06-28 23:55 UTC, clayjohn commented
> @clayjohn I've tried the above change and optimization, but it makes shadows flicker wildly while TAA is enabled and the camera is moving. It looks good when still, but it's worse than before when the camera is moving, both for PCSS and non-PCSS shadows.
> 
> I committed it separately so you can take a look.

I tried out your newest commit, but I can't reproduce the shadows flickering wildly while in motion. Keep in mind, there will also be some extra movement during motion from the jitter frames as TAA won't be able to fully reproject and resolve the image. But what I am seeing now is no worse than in the previous commit.

2022-06-29 00:32 UTC, Calinou commented
> I tried out your newest commit, but I can't reproduce the shadows flickering wildly while in motion. Keep in mind, there will also be some extra movement during motion from the jitter frames as TAA won't be able to fully reproject and resolve the image. But what I am seeing now is no worse than in the previous commit.

At realistic viewing distances, it's probably not too bad, so I guess we can move forward with this PR.

2022-06-29 01:00 UTC, clayjohn commented
It would be good to compare the results with your earlier commit to verify whether they indeed got worse with the changes. 

Keep in mind, a blur scale of 4 is an absurdly high value. Blur scale was designed to tweak the blur radius by a small amount and anything in that kind of range is bound to cause issues. In this case the issue is that the radius is being increased to 4 times its size and the distance between samples is directly related to the radius size. In other words, pixels on the far end of the radius travel quite far when the sampling disk is rotated. This is compounded by the fact that shadow quality very low only takes a few samples, so you end up not really benefiting from TAA.

2022-08-06 22:04 UTC, reduz commented
I think when TAA is enabled, we should disable updating after N frames to allow convergence.

2023-05-26 21:15 UTC, Calinou commented
Rebased and tested again, it works as expected in all configurations (directional/omni/spot, with and without PCSS shadows, Forward+/Mobile).

2023-07-10 06:16 UTC, Saul2022 commented
The check don´t seem to work and can´t download artifact.

2023-07-10 12:38 UTC, AThousandShips commented
It failed CI so no artifacts are available, try checking out the branch and building yourself if you want to test it

2023-07-10 16:28 UTC, Saul2022 commented
Tested it and it removes the weird noise for me when i see the shadow without moving on 1024 resolution,,though it still gives some circle patterm  at resolution like 524 when using the suft ultra, but that another issue(will post screenshot later when i have time ), good step forward and lets see how it can improve later.

2023-07-10 20:22 UTC, Calinou commented
> Tested it and it removes the weird noise for me when i see the shadow without moving on 1024 resolution,,though it still gives some circle patterm at resolution like 524 when using the suft ultra, 

This PR only aims to make the dithering pattern less visible. It can't fix aliasing in the shadow map if it has resolution/blurring. https://github.com/godotengine/godot-proposals/issues/4632 can help with this, but only to an extent and it'll have a performance cost as it prevents caching opportunities.

2023-10-11 23:36 UTC, clayjohn reviewed
As we have discussed on Rocketchat, I think we should remove the project setting entirely and just always jitter when using TAA and never jitter when not using TAA. The project setting is confusing and enabling temporal jitter without TAA is pointless. 

While testing the changes locally I updated the PR to include support for FSR2 and remove the project setting. commit here: https://github.com/godotengine/godot/commit/db4d2a3048da2aeb60de0e23f5f951937651356c

2023-10-12 03:37 UTC, jcostello commented
Works fine but the camera has to be still in order to this to happen. Does it make sense? Is not that common to have a fixed camera

2023-10-12 17:05 UTC, clayjohn commented
> Works fine but the camera has to be still in order to this to happen. Does it make sense? Is not that common to have a fixed camera

This doesn't require a fixed camera? Are you saying that when you tested it, this didn't work while the camera was moving?

2023-10-12 17:06 UTC, jcostello commented
> > Works fine but the camera has to be still in order to this to happen. Does it make sense? Is not that common to have a fixed camera
> 
> This doesn't require a fixed camera? Are you saying that when you tested it, this didn't work while the camera was moving?

Exactly, only when I stop moving the camera I can see the shadow filtered. Let me record a video

2023-10-12 17:10 UTC, jcostello commented
Here are two examples. One with moving camera and moving object

https://github.com/godotengine/godot/assets/1168582/a975836a-41ca-46a5-9fdc-4b2d7cf54cfd

One only with moving camera:
https://github.com/godotengine/godot/assets/1168582/e6453e08-6439-454b-8467-21c993d4944a

In the last one you can see close the ramp that the filter is lost when the camera is moving

2023-10-12 17:28 UTC, clayjohn commented
> Here are two examples. One with moving camera and moving object
> 
>  Peek.2023-10-12.14-09.mp4 
> One only with moving camera: https://github.com/godotengine/godot/assets/1168582/ff2a07be-b06e-4520-beed-c558714816f3
> 
> In the last one you can see close the ramp that the filter is lost when the camera is moving

When moving the object, the shadow will alias as we can't provide good motion vectors for shadows. So the TAA will lose track of it. 

For the moving camera only, it should resolve better than that. 

Perhaps there is an issue with how we calculate motion vectors from the camera rotation? cc @DarioSamo

2023-11-30 21:02 UTC, mrjustaguy commented
This Might soon be only relevant to FSR2.. Here's the current state of https://github.com/godotengine/godot/pull/85462 results with TAA on vs off

TAA On:

![image](https://github.com/godotengine/godot/assets/50302479/052cd333-60d7-4fdd-8d26-800c8d87f9e2)

TAA Off:

![image](https://github.com/godotengine/godot/assets/50302479/f0887325-6e13-48cd-b7db-5df5816c48cd)

2024-01-04 19:18 UTC, clayjohn commented
Testing this again after recent updates and I can reproduce the issue pointed out by jcostello. All accumulation is lost when the camera moves and it takes a noticeable amount of time to converge. FSR has similar artifacts, but also has unavoidable pixel swimming

I think we need to investigate what is wrong with TAA before we can go ahead with this PR

2024-01-05 00:23 UTC, clayjohn commented
Okay, https://github.com/godotengine/godot/pull/86809 fixes the issue with motion throwing out the accumulation buffer when using TAA. This looks really good with TAA now. 

We just need to figure out why it looks so bad with FSR. For now I suggest we only enable this when using non-FSR TAA.

2024-05-07 17:56 UTC, Calinou commented
Rebased and tested again with all rendering methods, it works as expected. Note that this PR only has an effect on Forward+ as this is the only rendering method where TAA is implemented.

2024-05-08 19:29 UTC, clayjohn commented
> Rebased and tested again with all rendering methods, it works as expected. Note that this PR only has an effect on Forward+ as this is the only rendering method where TAA/FSR2 is implemented.

Does it still look bad with FSR2? If so, let's just disable it for now when using FSR2

2024-05-09 00:38 UTC, Calinou commented
> Does it still look bad with FSR2? If so, let's just disable it for now when using FSR2

It still doesn't look great with FSR2, but unfortunately I don't know how to disable this specifically when FSR2 is used. The jitter fraction is defined based on the TAA phase count, which depends on the antialiasing method in use. We can't just set this to `0` when FSR2 is used as this will break the rest of the FSR2 jittering for its own TAA.

2024-09-24 19:36 UTC, clayjohn commented
I was able to figure out why FSR2.2 looks so bad with this PR and resolve it. 

First, some background: 
1. The reason to use IGN here is that it minimizes the difference between neighbouring pixels while being overall random. This works really well for TAA which looks at the pixels around it to determine whether to accept/reject a sample
2. To get good temporal blending without artifacts, we need to offset the samples a bit each frame in a temporally stable way, and in a way that minimizes the difference between frames (while still being random)
3. FSR2.2 is extremely sensitive to high frequency color changes when used at 100% screen scale (it's much less sensitive at lower scales)
4. I was testing with a blur of 4.0 and a brightness of 10.0 which created high frequency, high contrast penumbras which is really bad for TAA

If we use the temporal sampling from https://blog.demofox.org/2022/01/01/interleaved-gradient-noise-a-different-kind-of-low-discrepancy-sequence/ we get more coherent per-frame randomness (fewer large jumps means TAA can smooth things out better). Using this sampling strategy (which, coincidentally, is very close to the original sampling strategy in this PR) reduces the temporal noise significantly. This approach offsets the coordinates that are input into the IGN. The old approach added an additional rotation to the IGN.

_Worst case scenario: Brightness 10; blur 4; samples 1. Per frame offset left, per frame rotation right_
<img width="154" alt="Screenshot 2024-09-24 at 12 07 23 PM" src="https://github.com/user-attachments/assets/681eb9d8-dda2-4fef-ba3a-c989e1e507a8">
As you can see, using the per frame rotation creates temporal aliasing that get locked in place over time 

_More reasonable scenario: Brightness 3; Blur 4; samples 8. Per frame offset left, per frame rotation right_
<img width="160" alt="Screenshot 2024-09-24 at 12 07 52 PM" src="https://github.com/user-attachments/assets/ef092b88-e2ed-4937-ae05-94b17a56bdd6">

There is still a big improvement with the new sampling strategy

### Conclusion

We need to document that FSR2.2 at 1.0 scale is more sensitive to high contrast areas than TAA or FSR2.2 at lower scales as this will impact many users. 

Other than that, moving to the new sampling strategy is enough to make things look really good. So I suggest we go ahead with that and then merge this. At default settings it looks perfect with both TAA and FSR2.2. At more extreme settings it is a big improvement for FSR2.2 and keeps FSR2.2 usable for a wider range of situations.

2024-09-24 23:03 UTC, Calinou commented
- Superseded by https://github.com/godotengine/godot/pull/97428. Thanks @clayjohn for picking this up and improving it 🙂

2024-09-24 23:03 UTC, closed without merging