Fix methods may not be called at the end of the animation.
godotengine/godot pull request #61836
Opened 2022-06-09 02:20 UTC by Rindbee

Previously, the delta could be too small, preventing the methods at the end of the animation from being called.

Fix #61766.

2022-06-09 06:35 UTC, TokageItLab requested changes
If delta is small enough, the animation should be stopped. The problem that needs to be fixed is not the comparison, but the way keys are gotten at the end of the animation.

2022-06-09 13:14 UTC, Rindbee commented
This should make the **non-zero** `delta` available to the integral function again.

2022-06-09 15:01 UTC, Rindbee commented
Although I'm not very familiar with **CPP**, isn't `0 * delta` equal to `0`? 

>When TimeScale is 0, there is case where small deltas are generated continuously.

Isn't this a bug of TimeScale? Or implement restrictions?


![Peek 2022-06-07 18-57](https://user-images.githubusercontent.com/30386067/172878601-eda523b4-bc12-4b50-8dff-8ee68409100e.gif)

2022-06-09 15:03 UTC, Rindbee commented
Although I'm not very familiar with **CPP**, isn't `0 * delta` equal to `0`? 

>When TimeScale is 0, there is case where small deltas are generated continuously.

Isn't this a bug of TimeScale? Or implement restrictions?


![Peek 2022-06-07 18-57](https://user-images.githubusercontent.com/30386067/172878601-eda523b4-bc12-4b50-8dff-8ee68409100e.gif)

2022-06-09 22:37 UTC, Rindbee commented
Fix #61853. Reset the internal `time` while reseek in `AnimationNodeAnimation::process`.

2022-06-11 07:02 UTC, Rindbee commented
Superseded by #61885.

2022-06-11 07:02 UTC, closed without merging