Fix inner class parsing when statement after colos in on the same line
godotengine/godot pull request #61993
Opened 2022-06-13 12:50 UTC by kdiduk

This commit fixes the bug #56703 

The fix is to increase indent level when the statement after the colon token is on the same line. 

It looks like this issue is a regression introduced after some of the changes. Because in one of the earlier versions of that piece of code the intend level was increased ([see this](https://github.com/kdiduk/godot/blob/99736e63e45b323d06411926bd92210a08c717c2/modules/gdscript/gd_parser.cpp#L80), for example).

2022-06-13 13:10 UTC, kdiduk commented
If this PR is approved and merged, we need to update documentation for GDScript grammar (both in [3.x](https://docs.godotengine.org/en/stable/development/file_formats/gdscript_grammar.html) and [4.0](https://docs.godotengine.org/en/latest/development/file_formats/gdscript_grammar.html)), because it says that after the colon in the inner class declaration there is a newline:
```ebnf
innerClass = "class" IDENTIFIER [ inheritance ] ":" NEWLINE
    INDENT [ inheritance NEWLINE ] topLevelDecl { topLevelDecl } DEDENT ;
```

As I understand, the idea is to have it more Python'ic way, where this is allowed:
```python
class Foo: pass
```

At lease, in 4.0 it already works like that.

2022-06-13 13:23 UTC, akien-mga commented
> It looks like this issue is a regression introduced after some of the changes. Because in one of the earlier versions of that piece of code the intend level was increased ([see this](https://github.com/kdiduk/godot/blob/99736e63e45b323d06411926bd92210a08c717c2/modules/gdscript/gd_parser.cpp#L80), for example).

For the record, the `+1` was removed in this PR: #8123.
And that code was further refactored in #32808.

Please make sure that this doesn't reintroduce the issues that those PRs fixed.

2022-06-16 06:02 UTC, kdiduk commented
> Please make sure that this doesn't reintroduce the issues that those PRs fixed. 

@akien-mga Thank you for mentioning the original PR! Indeed my initial fix re-introduced some issues from them.

I've just pushed another implementation. I've implemented a special case for inner classes and it doesn't touch the cases mentioned in those PRs. 

Please, review it. I can also do some refactoring to clean up and eliminate duplicated code.

2022-06-17 13:40 UTC, vnen requested changes

2022-06-17 13:40 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +		// report location at the previous token (on the previous line)
Comments should start with a capital letter and end with a period (`.`).

```suggestion
		// Report location at the previous token (on the previous line).
```

2022-06-17 13:40 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +		// (note: only "pass" is allowed on the same line after the colon)
Same here, should end with a period.

2022-06-17 13:40 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +			return false; //wtf
I guess you copied from another place but I think you can remove this comment.

2022-06-17 13:40 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +		tokenizer->advance(); // go to next newline
Same here, either remove the comment of format it.

2022-06-17 13:40 UTC, vnen commented
Looks good to me, my remarks are only about the comment formatting.

2022-06-17 22:01 UTC, kdiduk commented
@vnen Thank you for your remarks. I've just pushed new changes with some refactoring. I have eliminated duplicated code blocks, extracting it into separate methods. Could you review it again?

2022-06-21 01:27 UTC, vnen requested changes
Looks good to me, just have one style remark.

2022-06-21 01:27 UTC, vnen commented on modules/gdscript/gdscript_parser.cpp
> +		//return false;
Being nitpicky again, but you shouldn't add commented out code (again, I know you are copying from the other function but these things can be fixed in the copy).

2022-06-27 19:45 UTC, vnen approved these changes
Looks good to me

2022-08-05 20:36 UTC, merged

2022-08-05 20:36 UTC, akien-mga commented
Thanks!