Remove linked properties for SDFGI cell sizes
godotengine/godot pull request #62230
Opened 2022-06-19 20:51 UTC by Calinou

These properties affected each other when set, which could be confusing from an user perspective. The class reference now mentions the formulas used to calculate the max distances (with a correction to the max distance formula, as it reported a distance that was twice as large as it actually was).

This closes https://github.com/godotengine/godot/issues/57366.

2022-06-19 21:21 UTC, fire approved these changes
Fixes confusion with @lyuma, thanks!

2022-06-19 23:30 UTC, jcostello commented
Thanks <3

2022-06-19 23:43 UTC, jcostello commented
Isn't posible to modify those variables independently? For example I would like to cover more ground without changing the cell size

2022-06-20 00:17 UTC, Calinou commented
> Isn't posible to modify those variables independently? For example I would like to cover more ground without changing the cell size

No, changing one of those properties will always change the other two properties. SDFGI cascades are always 64×64×64 cells.

2022-06-20 06:48 UTC, BastiaanOlij approved these changes
I'm fine with removing these if we think it will remove confusion, however the issue can also be fixed by ensuring we trigger a consistent property update on change and mark 2 of the 3 properties as editor only so only one actually gets saved (I believe we have a property hint for that, I could be wrong).

2022-06-20 15:53 UTC, lyuma commented
It would be nice to see the values of these other fields, so I wouldn't support removing them.
The only thing I found confusing was that there was a way to edit one that didn't update the others...
and also the fact that the 64 cell limit is hardcoded, because that's too small for some levels. Perhaps the inspector could show that 64x64x64 texture dimension somewhere...
I would wait and see how sdfgi as a feature gets fixed over time, and file specific issues if you have levels where it looks broken.

2022-06-20 16:50 UTC, jcostello commented
Also, dumb question, but cells has to be squares? Maybe longer cells can be useful in some cases

2022-06-21 12:15 UTC, akien-mga requested changes
Discussed with @reduz in a PR review meeting, he prefers to keep those as they are useful when configuring the SDFGI.

But they should indeed be changed so that only the `min_cell_size` gets saved, the other ones should just be editor-only aliases. (Or just no storage, they should likely still be in the docs / scripting API.)

2022-06-21 13:29 UTC, jcostello commented
> > Also, dumb question, but cells has to be squares? Maybe longer cells can be useful in some cases
> 
> This is already what **SDFGI Y Scale** lets you change. A lower Y scale will create smaller cells on the Y axis.

Yeah, but what about other axis? For example I notice in some cases of longer corridors that the cascades breaks the effect of a dark corridor because the far away cascade have light leak. So having longer cells in a particular axis could solve this without affecting the other axis

2022-08-04 07:21 UTC, akien-mga approved these changes

2022-08-04 07:22 UTC, merged

2022-08-04 07:22 UTC, akien-mga commented
Thanks!