Allow to disable TextEdit scroll
godotengine/godot pull request #62259
Opened 2022-06-20 23:21 UTC by KoBeWi

Closes https://github.com/godotengine/godot-proposals/issues/4546
![godot windows tools 64_RjBLImp3JP](https://user-images.githubusercontent.com/2223172/174688109-45107c71-86d7-4725-aaba-e58559ad4c72.gif)

2022-06-25 11:24 UTC, Paulb23 requested changes
Rather then dotting around calls to `update_minimum_size();` can we make a single call inside `_update_scrollbars`?

Also not sure on the naming, as `set_vertical_scroll_enabled` sounds like it's impossible to scroll, not that it will change the size of the Control. Something like `RichTextLabel` `set_fit_content_height` would fit better?

2022-06-25 11:24 UTC, Paulb23 commented on scene/gui/text_edit.h
> +	bool is_vertical_scroll_enabled() const;
This should go under the `viewport` section

2022-06-25 12:00 UTC, KoBeWi commented
> Also not sure on the naming, as set_vertical_scroll_enabled sounds like it's impossible to scroll, not that it will change the size of the Control.

The name was actually inspired by ScrollContainer.

2022-06-26 12:29 UTC, Paulb23 requested changes
> The name was actually inspired by ScrollContainer.

Thinking about this, I suppose we could add scroll modes to `TextEdit` instead, but that might be overkill.

2022-06-26 12:29 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +
`.h` and `.c` content should follow the same order, so this should be under `get_v_scroll_speed`, same with the other changes. Including moving `fit_content_height` next to `content_height_cache` in the header.

2022-06-26 12:29 UTC, Paulb23 commented on scene/gui/text_edit.h
> +	bool is_fit_content_height() const;
Should be `is_fit_content_height_enabled` for consistency.

2022-06-26 14:19 UTC, KoBeWi commented
> Thinking about this, I suppose we could add scroll modes to TextEdit instead

This will be possible now, at least vertically. The new property disables scroll, so you can put TextEdit into ScrollContainer and let it manage the scrolls instead.

2022-06-27 21:42 UTC, KoBeWi commented on scene/gui/text_edit.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "fit_content_height_enabled"), "set_fit_content_height_enabled", "is_fit_content_height_enabled");
It doesn't work, because the property doesn't have a right prefix.

2022-07-03 16:20 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "fit_content_height_enabled"), "set_fit_content_height_enabled", "is_fit_content_height_enabled");
Can we not call the property `scroll_fit_content_height_enabled`, keeping the methods the same?

Bit awkward from a code perspective, but nothing too strange, but would be better for the editor.

2022-07-03 19:42 UTC, KoBeWi commented on scene/gui/text_edit.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "fit_content_height_enabled"), "set_fit_content_height_enabled", "is_fit_content_height_enabled");
I wanted to keep the old name, but renamed it for consistency with other methods.

2022-07-04 12:12 UTC, Paulb23 approved these changes
Small nitpick on property name, but not going to block review.

2022-07-05 07:52 UTC, merged

2022-07-05 07:52 UTC, akien-mga commented
Thanks!