added usage_defines for SPECULAR_SHININESS
godotengine/godot pull request #62265
Opened 2022-06-21 04:45 UTC by d-robbins

This change resolves issue #62261 by adding usage_define for SPECULAR_SHININESS.

2022-06-21 18:21 UTC, clayjohn requested changes
Looks good so far! The same change needs to be made in the Opengl3 renderer as well:
https://github.com/godotengine/godot/blob/c18d0f20357a11bd9cfa2f57b8b9b500763413bc/drivers/gles3/storage/material_storage.cpp#L1374-L1381

2022-06-24 16:22 UTC, clayjohn commented
Looks great! Before merging, you will need to combine your commits into one, how to do so is explained here: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

2022-07-17 16:26 UTC, d-robbins commented
I believe it should be good to go!

2022-07-17 16:30 UTC, akien-mga commented
FYI you authored the commit with an email linked to @robbi183 but then PR'ed from a fork owned by @d-robbins. If you meant to use only the latter, you can reset the author details with `git commit --amend --reset-author`.

Otherwise if you don't mind the double signing it's also fine as is (but the commit will count towards @robbi183's contribution count).

2022-07-17 17:27 UTC, d-robbins commented
Thank you, I hadn't noticed.

2022-07-18 19:28 UTC, clayjohn approved these changes
Looks great! Thanks for sticking with it

2022-07-18 19:35 UTC, merged

2022-07-18 19:35 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: