Make the alternative tile control correctly handle right-click dragging.
godotengine/godot pull request #62629
Opened 2022-07-02 11:29 UTC by linkpy

Fixes #62626 

I am not sure if it is all correct (like, regarding `drag_start_mouse_pos`) but this fixes the bug.

2022-07-08 09:47 UTC, groud commented
I am not sure how mouse events are handled while dragging, but IIRC, if you start dragging on a given control, this control will keep receiving MouseMotion events even if you drag outside of it. If that's the case as I think it is, I think your fix only needs a few changes to be good.

To do so you should replicate and adapt those lines from `_tile_atlas_control_gui_input` into `_tile_alternatives_control_gui_input`: 
```
else if (drag_type == DRAG_TYPE_MAY_POPUP_MENU) {
				if (Vector2(drag_start_mouse_pos).distance_to(tile_atlas_control->get_local_mouse_position()) > 5.0 * EDSCALE) {
					drag_type = DRAG_TYPE_NONE;
				}
			} 
```

2022-07-08 09:50 UTC, groud requested changes

2022-07-08 09:50 UTC, groud commented on editor/plugins/tiles/tile_set_atlas_source_editor.cpp
>  				Vector3 tile = tile_atlas_view->get_alternative_tile_at_pos(mouse_local_pos);
The popup of the menu should be conditioned by `if (drag_type == DRAG_TYPE_MAY_POPUP_MENU)`. The point is to only to popup the menu if you did not drag too far.

2022-07-18 01:40 UTC, linkpy commented
I've implemented the requested changes and rebased on master.

2022-07-29 01:12 UTC, linkpy commented
> > To do so you should replicate and adapt those lines from _tile_atlas_control_gui_input into _tile_alternatives_control_gui_input:
> 
> You still need to address that. The popup should not be displayed if you moved your mouse, which requires the lines mentionned in my previous comment to be added in the handling of mouse motion events on the alternative tiles' control node.

Sorry, I forgot about this part.
It should be okay now.

2022-07-29 07:35 UTC, groud approved these changes

2022-07-29 08:14 UTC, merged

2022-07-29 08:14 UTC, akien-mga commented
Thanks!