Made ScriptTextEditor::clear_edit_menu to set the menu pointer to nullptr to avoid use-after-free crashes.
godotengine/godot pull request #62657
Opened 2022-07-03 07:37 UTC by linkpy

Fixes #61689.

The generating the crash in the above issue was already checking for null pointers, so this indeed fixes the crash but the behaviour is still broken : 
1. There is an error `Condition "!is_inside_tre()" is true` being generated from `ScriptEditor::_tab_changed` : 
```
#0  Control::grab_focus (this=0x5555788e9270) at scene/gui/control.cpp:2534
#1  0x00005555597244c5 in ScriptTextEditor::ensure_focus (this=0x5555788dd6e0) at editor/plugins/script_text_editor.cpp:392
#2  0x00005555596e7231 in ScriptEditor::ensure_select_current (this=0x55556ca6d570) at editor/plugins/script_editor_plugin.cpp:1794
#3  0x00005555596e35c9 in ScriptEditor::_tab_changed (this=0x55556ca6d570, p_which=0) at editor/plugins/script_editor_plugin.cpp:1596
```
2. The script list is has a broken display afterward : 

https://user-images.githubusercontent.com/2700596/177029986-a4cfc180-8722-4fd6-8923-4e8b83bac737.mp4

 I'll try investigating both issues but I am open to any advice or pointer regarding it as I don't really know how that part of the engine works.

2022-07-03 07:50 UTC, linkpy commented
`ScriptEditor::ensure_select_current` tries to focus the current editor but the latter is out of the tree, making `ScriptTextEditor::ensure_focus` to try focusing one of its child control (which is also out of the tree).

I added a `is_inside_tree` check to fix the error and by chance it also fixed the display bug for me.

2022-07-03 15:54 UTC, Paulb23 requested changes
`clear_edit_menu` changes look good, I think this also fixes #58720, if I can remember correctly after a brief look a while back.

Not so sure on the `is_inside_tree` tree check, feels like something deeper is going on here, as the `se` should be inside the tree. Or we at least shouldn't be calling `ensure_select_current` with one that isn't.

2022-07-04 00:14 UTC, linkpy commented
After more investigation I found out that `ScroptEditor::ensure_select_current()` tries to focus the now-removed tab. The `TabContainer` control returns the expected 2 when calling `get_tab_count`.

But `get_tab_control` doesn't use the tab count and directly look at its children, and thus : 
```
Thread 1 "godot.linuxbsd." hit Breakpoint 1, ScriptEditor::ensure_select_current (this=0x55556ca63700) at editor/plugins/script_editor_plugin.cpp:1794
1794                                    se->ensure_focus();
(gdb) p se
$1 = (ScriptEditorBase *) 0x5555766dd080
(gdb) p tab_container->get_tab_count()
$2 = 2
(gdb) p tab_container->get_tab_control(0)
$3 = (Control *) 0x5555766dd080
(gdb) p tab_container->get_tab_control(1)
$4 = (Control *) 0x55557859e5d0
(gdb) p tab_container->get_tab_control(2)
$5 = (Control *) 0x5555786d33b0
(gdb) p tab_container->get_tab_control(3)
$6 = (Control *) 0x0
```

The pointer `$1 = (ScriptEditorBase *) 0x5555766dd080` is the same pointer as the `ScriptTextEditor` that received its `NOTIFICATION_EXIT_TREE`. So my guess is that the tab control is removed after `tab_changed` signal is emited (so after `ensure_select_current`).

2022-07-04 00:21 UTC, linkpy commented
```cpp
// node.cpp:1218 in Node::remove_child
        // this is a TabContainer
	remove_child_notify(p_child); // leads to `ScriptEditor::ensure_select_current`
	p_child->notification(NOTIFICATION_UNPARENTED);

	data.children.remove_at(idx);
```

So this seem to confirm it, but what I don't understand is why this bug doesn't happen everytime a script tab is closed ahah.

2022-07-04 00:36 UTC, linkpy commented
I tried deferring the call to `ensure_select_current` but the display bug is still present. But I removed the `is_inside_tree` check and there is no longer any `Condition !is_inside_tree` error happening.

2022-07-04 00:54 UTC, linkpy commented
I've looked a bit into `TabBar`'s code. The tab is removed correctly and the underlying `tabs` vector updated correctly as well, but something happens with the display code somewhere (notice the script list, the 2nd one is duplicated) : 

![image](https://user-images.githubusercontent.com/2700596/177063927-20a0808e-c11f-487f-b117-e04e07757bce.png)

From what I can see, it seems like it is working as intended. I have no idea why that display bug is happenning so if anybody got an idea feel free to share it.

2022-07-04 12:19 UTC, Paulb23 commented
Huh that's interesting.

I wonder if it's because we call `memdelete` without calling `tab_container->remove_child` first, so we don't send the signal? Though I would have also thought that deleting it would stop it from being found.

2022-07-05 01:02 UTC, linkpy commented
That is another way of fixing it (instead of deferring the `ensure_select_current`), but I am not sure it will help regarding the display bug. I'll see if doing it this way fixes the display bug.

2022-07-19 17:24 UTC, Paulb23 commented
Superseded by #63145 and #63195

2022-07-19 17:24 UTC, closed without merging