Implement registering protocols on Windows, Mac, and Linux
godotengine/godot pull request #62788
Opened 2022-07-06 19:22 UTC by aaronfranke

This PR implements this proposal https://github.com/godotengine/godot-proposals/issues/4665 on Windows, macOS, and Linux.

On Windows and Linux, we register protocols at runtime using the new OS method `register_protocol`, and there's also `unregister_protocol` so you can undo it. I did not implement `is_protocol_registered`.

On macOS, protocols are registered in the app bundle manifest, so it must be done at export time, not at runtime (there is a new field in the export dialog). Also, I have no idea how we are supposed to receive the information in the URL on macOS, since it's not a command line argument - but hey, at least the app opens.

This was built on top of code from Facade / Marc Weber, who wrote the Windows code, and then I tweaked it and made the Linux and macOS code. If you want to take a look at the original Git history before I squashed it, here's a link: https://github.com/godotengine/godot/compare/master...marc-weber1:godot:protocol-registration Co-authored-by: Marc <marc.weber54@gmail.com>

2022-07-06 19:27 UTC, bruvzg commented
I'm pretty sure that macOS App delegates `openFile:` method should be replaced with [`openURLs:`](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/2887193-application?language=objc) method (it should handle both file associations and URL schemas, since macOS do not use command line arguments):

https://github.com/godotengine/godot/blob/09e12ba9b46934c32ffc9e178b5c6f0348de809f/platform/osx/godot_application_delegate.mm#L102-L119

2022-07-07 00:47 UTC, aaronfranke commented on platform/windows/os_windows.cpp
> +	}
Note that this only allows unregistering protocols specific to this user account.

I'm not sure what would happen if we tried to disallow this, such as what would happen if you tried to register over an existing protocol, and what would happen if the app ID changes?

2022-07-07 08:02 UTC, bruvzg commented
Opened a separate PR that should make associated file opening to behave the same as on other platforms. It's also handing URL schemas in the same way, a new instance is launched with `-url="proto://whatever"` as a command line argument - https://github.com/godotengine/godot/pull/62808/

2022-07-07 13:20 UTC, hpvb commented
I also don't think this is the right approach. I think this needs to be a *project setting* that does the right thing on all platforms.

* On MacOSX the project setting should set the correct changes in the exported plist
* On Linux and Windows during boot of the game it should check the url registration and fix it for the current running program

Having two wildly different ways for end-users to achieve the same thing seems very user hostile. Particularly since on OSX the engine has no option to register or not register the url handler.

2022-07-07 13:26 UTC, hpvb requested changes
The OS approach seems flawed, especially since it actually can't work on all OSses. @RevoluPowered is already working on an approach using a project setting instead which I think will solve the problems raised here.

2022-07-07 14:49 UTC, aaronfranke commented
> Moving the game executable will break the protocol handler on both windows and linux (as another proof that this is "install" material).

The game executable can just run the register protocol method on startup, which means you can move the game, run it once, and then the protocol will work again.

> @RevoluPowered is already working on an approach using a project setting instead

I look forward to seeing this, and hopefully some of the work I did here will be useful.

2022-07-07 15:11 UTC, hpvb commented
> I look forward to seeing this, and hopefully some of the work I did here will be useful.

Oh yeah, the actual registration code from your PR will be very useful!

2022-08-07 02:27 UTC, aaronfranke commented
Closing as superseded by #63631. I did one last rebase in case anyone wants to reference this in the future.

2022-08-07 02:27 UTC, closed without merging

2024-03-17 06:09 UTC, aaronfranke commented
For anyone who wants this feature, it is available as a part of The Mirror's fork of Godot, now open source: https://github.com/the-mirror-gdp/godot

Specifically, it is in a module with folder name `app_protocol`: https://github.com/the-mirror-gdp/godot/tree/themirror/modules/app_protocol