Document initializing PackedVectorArray/PackedColorArray correctly
godotengine/godot pull request #62958
Opened 2022-07-12 17:26 UTC by Calinou

This closes https://github.com/godotengine/godot/issues/62927.

This can be remade for `3.x` once we agree on the text to add.

2022-07-12 18:15 UTC, fire-forge requested changes

2022-07-12 18:15 UTC, fire-forge commented on doc/classes/PackedVector2Array.xml
> +		[b]Note:[/b] When initializing a [PackedVector2Array] with elements, it must be initialized with an [Array] of [Color] values, not separate [float]s:
```suggestion
		[b]Note:[/b] When initializing a [PackedVector2Array] with elements, it must be initialized with an [Array] of [Vector2] values, not separate [float]s:
```

I assume this is a copy and paste mistake?

2022-07-12 18:15 UTC, fire-forge commented on doc/classes/PackedVector3Array.xml
> +		[b]Note:[/b] When initializing a [PackedVector3Array] with elements, it must be initialized with an [Array] of [Color] values, not separate [float]s:
```suggestion
		[b]Note:[/b] When initializing a [PackedVector3Array] with elements, it must be initialized with an [Array] of [Vector3] values, not separate [float]s:
```

2022-07-12 18:29 UTC, fire-forge approved these changes

2022-07-12 23:21 UTC, kleonc commented
I think it would make more sense to add these notes to the descriptions of `Packed<Type>Array(Array from)` constructors instead. These notes are about just these specific constructors.

2022-08-08 10:53 UTC, reduz approved these changes, later dismissed

2022-08-08 10:58 UTC, akien-mga reviewed
I think these should go in the description of the relevant constructor instead.
Not sure about mentioning "not separate floats", I know that's what the user tried to do in the relevant issue but that's not something that I would naturally expect to work, so I don't think we need to specifically point out this arbitrary possibility.

2023-06-15 05:51 UTC, Calinou commented
I've amended the PR to put the descriptions in the specific constructors.

2023-06-15 07:31 UTC, akien-mga approved these changes

2023-06-15 08:51 UTC, merged

2023-06-15 08:52 UTC, akien-mga commented
Thanks!