magic _str method
godotengine/godot pull request #6306
Opened 2016-08-27 20:20 UTC by profelis

Python has many magic methods, one of them [__str__](https://docs.python.org/2/reference/datamodel.html#object.__str__) 

I propose to add same magic to GDScript. This PR is just proof of concept. I tested some expressions and all works ok, but probably I forgot something

Example:
```
func _str(): return "Test.gd script"
```
Was:
```
print(self) # [Node:588]
print("Init %s" % self) # Init [Node:552"]
```
Now:
```
print(self) # Test.gd script
print("Init %s" % self) # Test.gd script
```

2016-09-10 14:52 UTC, reduz commented
We don't have operator overloading in GDScript, If we add it, this would go with it. If we don't this would not. I'm not against adding it but no one else asked for it so I'm not sure if it's worth it.

2016-09-12 21:35 UTC, profelis commented
You are boss. But i just want worked reflection ( exists Object.has_method and has_meta but no has_property method, #6308 ), magic methods (_str, _iter, _has, _get, _equals, etc), switch operator   :)

2016-09-12 22:19 UTC, vnen commented
@profelis I can see how `Object.has_property()` can be useful and also the `switch` statement. But the magic functions aren't quite as useful IMO. Do you have a real use case for a game where you need to use such thing? As in: it's the best solution and the workarounds are more like hacks?

2016-09-15 12:52 UTC, Tybobobo commented
I would also like to see this implemented.

2016-09-15 18:33 UTC, Zylann commented
You could easily do the following:
```gdscript
	static func to_string(v):
		if typeof(v) == TYPE_OBJECT:
			if v.has_method("_to_string"):
				return v._to_string()
		return str(v)

Util.to_string(stuff)
```
But that would indeed doom the use of `str`.
So far I never needed such a thing, but it could have its use when building a GUI framework or logging objects more easily. Otherwise, it looks more like a convenience.

2016-09-15 18:44 UTC, neikeq requested changes
If this is going to be merged, be sure to add `BIND_VMETHOD( MethodInfo("_str:String") );` to `Object::_bind_methods()`. This way the method will appear in the docs like `_process` and other virtual methods.

2017-01-14 21:12 UTC, akien-mga commented
As @reduz mentioned above and confirmed to me today, we need to implement full operator overloading before this makes sense, so it won't be merged as is. If/when operator overloading is implement, a _str method will be part of it.

2017-01-14 21:12 UTC, closed without merging