Add read-only mode to AnimationTreeEditor plugins
godotengine/godot pull request #63249
Opened 2022-07-20 14:22 UTC by SaracenOne

Adds a read-only mode to the AnimationTreeEditor plugin when operating on resources embedded in foreign scenes. Currently only covers state machines, blend 1D, and blend 2D editors. Blend trees do not currently support a read-only mode due to their reliance on the built-in GraphEdit control which does not yet have the required read-only state needed to prevent edits.

Complementary PR to #63245

2022-08-19 06:41 UTC, reduz requested changes, later dismissed

2022-08-19 06:41 UTC, reduz commented on editor/plugins/animation_blend_space_1d_editor.cpp
> +	tool_erase->set_disabled(!point_valid || blend_space_is_foreign);
I would just call it read_only, as I mentioned in other PRs, we also want this for locked resources for VCS eventually.

2022-08-19 06:41 UTC, reduz commented
Looks good to me save for minor nitpick, I think @TokageItLab should review too.

2022-08-19 09:40 UTC, TokageItLab commented
I have confirmed that the change to BlendSpace is prevented. But I concerned about the behavior of the BlendSpace point being canceled after it is grabbed. It would be better if it could be prevented from grabbing the point.

I am more concerned that #63245 is not working very well. I think that instead of preventing overwrites, #63245 should also cancel the user's operation, just like this PR.

2022-08-25 03:18 UTC, SaracenOne commented
Okay, @reduz, this has now been updated to address the issues @TokageItLab pointed out; the dragging of points in the blend spaces is no longer allowed, amongst other tweaks such as disabling a few buttons which I missed. I apologize that the read-only modes for blend spaces was so sloppy, I think that part of the code was a bit rushed on my behalf. I also went and replaced some of the duplicate code required for detecting if a resource is read_only with the new 'is_resource_read_only' function introduced in #63282

Aside from that, I've actually gone and ostensibly *finished* this PR by going ahead and adding read-only mode to the blend trees too, which did requires some minor tweaks the GraphEdit and GraphNode APIs, such as including a new 'draggable' and 'selectable' property for GraphNodes, and an option to hide the Arrange Nodes button in GraphEdit. I also introduced a new behaviour to GraphNode slots which does have accompanying documentation explaining it. The rule introduced is that slot types with negative numbers will not allow the user to create connections via the GraphEdit, which taking advantage of now allows the GraphEdit node in the BlendTreeEditor to be exist in a fully read-only state.

It also fixes a bug in the EditorSpinSplider which allowed the slider to still be moved in read-only mode.

2022-08-25 04:44 UTC, TokageItLab commented
Looks good except that the name of the StateMachine's Nodes is editable.

2022-08-27 00:46 UTC, TokageItLab approved these changes
Seems good.

2022-08-27 06:14 UTC, merged

2022-08-27 06:14 UTC, akien-mga commented
Thanks!