Clean-up array editing
godotengine/godot pull request #63266
Opened 2022-07-20 23:39 UTC by reduz

Some clean ups and improvements to Array editing:

* Remade how linked properties are exposed to avoid bloating PropertyInfo, which is used everywhere.
* Added a simpler way to add linked properties for undo via duck typing a call to `_get_linked_undo_properties`.
* Added a simpler way to implement complex moving objects in array editing by defining a swap method.
* Added more options to array editing:
  * Foldable
  * Movable
  * Numbered
  * Page Length
  * Pass text for add item button
  * Pass a swap method (simpler way to do complex moving of objects when the property list swapping is not enough). This is much simpler than adding a plugin for these cases.

2022-07-21 01:58 UTC, fire-forge commented
This has made inspector arrays either not show up or crash the editor. After a bit of investigation, I've found that arrays added with `ADD_ARRAY_COUNT` don't show up at all. These include OptionButton, ItemList, MenuButton, PopupMenu, TabBar, Curve, Curve2D and Curve3D. Any array properties that they have are shown as groups.
![image](https://user-images.githubusercontent.com/67974470/180111945-ccbab12b-e3d5-4ee0-bd37-742377ee1cb9.png)
![image](https://user-images.githubusercontent.com/67974470/180112309-051cf80e-73f9-4acc-8844-c45f75f27790.png) 
![image](https://user-images.githubusercontent.com/67974470/180111908-01c479b6-3dc0-401b-afb0-b30a91faf792.png)

Arrays added with `ADD_ARRAY` crash the editor. These include TileSet, TileMap, BoneMap, and AudioStreamRandomizer.

2022-07-21 08:44 UTC, groud requested changes
I think the new approach is too close to something we already have with `EditorData::add_move_array_element_function` and `EditorInspectorArray::setup_with_move_element_function`, covering the exact same use case but from the object directly instead of an editor plugin.

I think this PR is incomplete and needs few changes:
- Remove EditorData::add_move_array_element_function, and replace it with the new approach where it is used.
- The moving/adding/removing function (here add and swap) should be arguments of `EditorInspectorArray::setup_with_move_element_function`, as that is what this function was built for.

On a side note, I don't like much having to provide a swap function. Having only a swapping function will mean that it will have to be called a lot when you would need to move an element from one place to another. Depending on the underlying structure used to store the array, this can have a significant performance impact, especially when you are using Vector and/or need to update some side data structure (like a cache for example, or something like that). This is particularly the case for TileSet data layers for example.
Instead, the function should required to be called only once for each operation you need to do, so that those sort of underlying updates can be only triggered once per operation.

So what I suggest instead is to replace the `swap` function by a `move` function, so instead of swapping two elements, it takes one element and move it to another position. We can keep the same logic for `p_element_index < 0` and `p_to_pos < 0` to respectively to add and remove elements. This should avoid any performance issue.

2022-07-21 08:44 UTC, groud commented on editor/editor_inspector.h
> +	void setup_with_count_property(Object *p_object, String p_label, const StringName &p_count_property, const StringName &p_array_element_prefix, int p_page, const Color &p_bg_color, bool p_foldable, b
The `p_movable`, `p_numbered`, `p_page_length` and `p_add_item_text` should be added to `setup_with_move_element_function` too.

The `p_swap_method` should not be added there IMO, but likely to the other function.

2022-07-21 09:38 UTC, reduz commented
@groud I understand the concerns with the swap function, but to me the problem is that the move function is _far_ more complex to implement that the swap function. IMO I think its ok to provide both somehow.

2022-07-21 10:22 UTC, groud commented
> @groud I understand the concerns with the swap function, but to me the problem is that the move function is far more complex to implement that the swap function.

I would not say it's "far more complex", this is with a move function:
```
	if (p_from_index < 0) {
		local_vector.insert(p_to_pos, TileMapLayer());
	} else if (p_to_pos < 0) {
		local_vector.remove_at(p_layer);
	} else {
		local_vector.insert(p_to_pos, local_vector[p_from_index]);
		local_vector.remove_at(p_to_pos < p_layer ? p_layer + 1 : p_layer);
	}
 ```
And this is with a swap:
```
	if (p_from_index < 0) {
		local_vector.insert(p_to_pos, TileMapLayer());
	} else if (p_to_pos < 0) {
		local_vector.remove_at(p_layer);
	} else {
		Type object = local_vector[p_to_pos];
		local_vector[p_to_pos] = local_vector[p_from_index];
		local_vector[p_from_index] = object;
	}
 ```
So I am not convinced at all that it is far more complex, but well, I understand the logic might be a little bit trickier.
 
If we want to keep both possibilities (using either a swap or a move function depending on whether or not you need performance) I don't mind. But in such case, we should still change the solution using the move function to work the same way as the one using swap, as it would be more consistent. That would still require to remove `EditorData::add_move_array_element_function` and likely add another `setup_with_swap_element_function`.

Btw it's clear that the function argument should not be added to `setup_with_count_property`. This setup relies on the count property to add and remove elements, and on the property names to move them.

2022-07-22 08:24 UTC, reduz commented
@groud In reality, its more like this:

```C++
    if (p_from_index < 0) {
        for(all elements) {
            if (active_index > p_to_pos) {
                active_index++;
            }
        }
		local_vector.insert(p_to_pos, TileMapLayer());
	} else if (p_to_pos < 0) {
        for(all elements) {
            if (active_index == p_to_pos) {
                // Do something, I have no idea, and whathever I do I need to figure out how to undo.                
            } else if active_index > p_to_pos) {
                active_index--;
            }
        }
		local_vector.remove_at(p_layer);
	} else {
            if (active_index == p_from_pos) {
                active_index=p_to_pos;
            } else if (p_from_pos < p_to_pos && active_index >p_from_pos && active_index<p_to_pos) {
                    active_index--;

            } else if (p_from_pos > p_to_pos && active_index >p_to_pos && active_index<p_from_pos) {
                    active_index++;
            }
            
		Type object = local_vector[p_to_pos];
		local_vector[p_to_pos] = local_vector[p_from_index];
		local_vector[p_from_index] = object;
	}
	
	
	// VS
	
	if (active_index==p_from_pos) {
	    active_index=p_to_pos;
	} else if (active_index==p_to_pos) {
	    active_index=p_from_pos;
	}
	
	SWAP(local_vector[p_from_pos],local_vector[p_to_pos]);
	
	// I dont have to care about adding or removing!
	
```

2022-07-22 08:43 UTC, groud commented
Well, IMO that's an exaggeration of the complexity. My example is what I use in TileMaps and TileSet (modulo some internal updates) and I didn't need that much code.

To make it clear, I don't mind adding the possibility to use a swap function for those who find it easier to implement and don't need complex updates. But we need to keep the possibility to use the move function where needed, otherwise it will significantly harm performances in TileMaps and TileSets.

2022-07-22 08:56 UTC, reduz commented
@groud I don't think its an exaggeration, if you have indices to the elements, that is the logic you must apply to get them updated. The move function is of course a lot more optimal because its called once, but its not easy to write to me. This is why I think the option to just do a swap function is useful, because its just much simpler to write.

2022-07-22 14:31 UTC, reduz commented
@groud yeah I think they are just two different use cases. I did further clean up, so let me know if you think the code is OK.

2022-08-02 07:33 UTC, groud approved these changes
Needs a rebase but looks good.

2022-08-03 09:37 UTC, merged

2022-08-03 09:37 UTC, akien-mga commented
Thanks!