added Curve in state machine interpolation
godotengine/godot pull request #63369
Opened 2022-07-23 22:25 UTC by jeronimo-schreyer

added Curve in state machine interpolation for better control over blending
theres a proposal for this https://github.com/godotengine/godot-proposals/issues/1402

here you can see the interpolation with and without curve setting
https://user-images.githubusercontent.com/29764541/180624853-6a53dd8a-a6ee-4a04-8547-a3f9656fbcf8.mp4

2022-07-23 22:42 UTC, Calinou commented
@jeronimo-schreyer Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL. I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

2022-07-23 23:11 UTC, jeronimo-schreyer commented
I didn't know why I could see it OK in the preview and not in the final posted version. Thanks.

This build error says I need to add documentation for the new Curve property, right?

2022-07-24 00:10 UTC, Calinou commented
> This build error says I need to add documentation for the new Curve property, right?

Yes, and make sure you're using tab indentation within the XML instead of spaces (except within `[codeblock]`).

2022-07-24 00:33 UTC, jeronimo-schreyer commented
I'm almost certain I use tabs instead of spaces. Is there a way to be sure?

2022-07-27 09:58 UTC, TokageItLab commented
IMO it is good, it could be implemented also for NodeTransition, but maybe after this is Approved, we can send additional PRs.

2022-07-27 12:09 UTC, jeronimo-schreyer commented
I added this for NodeTransition also on my latest commit

2022-07-28 07:34 UTC, TokageItLab requested changes
You must follow the rebasing work-flow recommended by Godot. See [Pull request workflow](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase).

In brief, check out `74d84d170aab4e692a81165872f040296a2ca7f0` and apply the fixes, then do a `--fixup`. In the end, there should be only one commit.

2022-07-28 07:34 UTC, TokageItLab commented on scene/animation/animation_blend_tree.cpp
> +		float curved_blend = (xfade_curve.is_valid()) ? xfade_curve->interpolate(1.0 - blend) : 1.0 - blend;
```suggestion
		float curved_blend = (xfade_curve.is_valid()) ? 1.0 - xfade_curve->interpolate(blend) : 1.0 - blend;
```

2022-07-28 07:34 UTC, TokageItLab commented on scene/animation/animation_blend_tree.cpp
> +		float curved_blend = (xfade_curve.is_valid()) ? xfade_curve->interpolate(1.0 - blend) : 1.0 - blend;
The interpolation calculation is wrong.

2022-07-28 07:34 UTC, TokageItLab commented on scene/animation/animation_node_state_machine.cpp
> +		curved_blend = (current_curve.is_valid()) ? current_curve->interpolate(1.0 - fade_blend) : 1.0 - fade_blend;
```suggestion
		curved_blend = (current_curve.is_valid()) ? 1.0 - current_curve->interpolate(fade_blend) : 1.0 - fade_blend;
```
Same above.

2022-07-28 08:03 UTC, TokageItLab requested changes

2022-07-28 08:03 UTC, TokageItLab commented on scene/animation/animation_blend_tree.cpp
> +			blend_input(prev, p_time, false, p_seek_root, curved_blend, FILTER_IGNORE, true);
Suggestion:
```cpp
	} else { // cross-fading from prev to current

		float blend = xfade_time == 0 ? 0 : (prev_xfading / xfade_time);
		if (xfade_curve.is_valid()) {
			blend = xfade_curve->interpolate(blend);
		}

		if (from_start && !p_seek && switched) { //just switched, seek to start of current

			rem = blend_input(current, 0, true, p_seek_root, 1.0 - blend, FILTER_IGNORE, true);
		} else {
			rem = blend_input(current, p_time, p_seek, p_seek_root, 1.0 - blend, FILTER_IGNORE, true);
		}

		if (p_seek) {
			blend_input(prev, p_time, true, p_seek_root, blend, FILTER_IGNORE, true);
			time = p_time;
		} else {
			blend_input(prev, p_time, false, p_seek_root, blend, FILTER_IGNORE, true);
			time += p_time;
			prev_xfading -= p_time;
			if (prev_xfading < 0) {
				set_parameter(this->prev, -1);
			}
		}
	}
```
Your interpolation calculation is wrong; you only need to overwrite blend with curve.

2022-07-28 08:03 UTC, TokageItLab commented on scene/animation/animation_node_state_machine.cpp
> +		p_state_machine->blend_node(fading_from, p_state_machine->states[fading_from].node, p_time, p_seek, p_seek_root, curved_blend, AnimationNode::FILTER_IGNORE, true);
Suggestion:
```cpp
	if (current_curve.is_valid()) {
		fade_blend = current_curve->interpolate(fade_blend);
	}
	float rem = p_state_machine->blend_node(current, p_state_machine->states[current].node, p_time, p_seek, p_seek_root, fade_blend, AnimationNode::FILTER_IGNORE, true);

	if (fading_from != StringName()) {
		p_state_machine->blend_node(fading_from, p_state_machine->states[fading_from].node, p_time, p_seek, p_seek_root, 1.0 - fade_blend, AnimationNode::FILTER_IGNORE, true);
	}
```
Same above.

2022-07-31 15:01 UTC, TokageItLab commented
@jeronimo-schreyer This feature is good. Can I salvage it?
We have to do a feature freeze to release the Godot 4 beta, so implementation of the new feature is a bit rushed. If I don't hear back by 8/2, I will send a proxy PR with your name as co-authored.

2022-08-02 01:54 UTC, closed without merging

2022-08-02 05:21 UTC, akien-mga commented
Superseded by #63802.