Crash when renaming the active node in AnimationTree
godotengine/godot pull request #63450
Opened 2022-07-25 16:47 UTC by kidmosey

Fix #61808: crash when renaming the active node in AnimationTree.

The cause of the crash was attempting to read an empty node within
`AnimationNodeStateMachine::can_edit_node()`. The node was empty due to
`HashSet<>` adding a default state if the old key does not exist.

- Fixed a copy/paste typo in `AnimationNodeStateMachine::_rename_transition()`.
- When renaming transitions, also update the local_* fields.
- To prevent future crashes by this code, verify a state exists before accessing it
in `AnimationNodeStateMachinePlayback::process()`
- To prevent future crashes by this code, verify the node is valid before accessing
it in `AnimationNodeStateMachine::can_edit_node()`

2022-11-29 11:50 UTC, mhilbrunner commented
cc @fire @SaracenOne

2023-02-16 22:28 UTC, akien-mga commented
Sorry for the delay reviewing.

This would need a rebase, and it seems like the original issue is fixed, at least several of us couldn't reproduce it anymore.

Some of the changes in this PR might still be relevant though, at least the "from" -> "to" typo fix seems quite important.

CC @TokageItLab

2023-02-17 00:12 UTC, TokageItLab requested changes
Crash can no longer be confirmed. This PR does not seem to do anything, so I believe it is closeable.

2023-02-17 00:12 UTC, TokageItLab commented on scene/animation/animation_node_state_machine.cpp
> +			Vector<String> path = String(transitions[i].to).split("/");
I don't think this change makes sense since this is to get the path of the parent of the nested state machine.

2023-02-17 00:12 UTC, closed without merging