Fix `FOG` built-in in spatial/fragment shader
godotengine/godot pull request #63477
Opened 2022-07-26 05:12 UTC by Chaosus

Currently, it leads to shader compilation failure since `custom_fog` is not defined.

2022-07-26 20:56 UTC, clayjohn requested changes
Broken by: https://github.com/godotengine/godot/pull/45023

Instead of changing all references from ``fog`` to ``custom_fog`` we should change the shader compiler to replace ``FOG`` with ``fog`` instead of ``custom_fog``. The trouble with the current PR is that when custom fog is not used we are still referring to built in fog as ``custom_fog`` which will be confusing for people reading the code. 

https://github.com/godotengine/godot/blob/0a420c478761d49b5f973ff292e1f3e4a63613b3/drivers/gles3/storage/material_storage.cpp#L1521
https://github.com/godotengine/godot/blob/0a420c478761d49b5f973ff292e1f3e4a63613b3/servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp#L685
https://github.com/godotengine/godot/blob/0a420c478761d49b5f973ff292e1f3e4a63613b3/servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp#L587

2022-07-27 05:31 UTC, Chaosus commented
@clayjohn Done

2022-07-27 07:28 UTC, clayjohn approved these changes

2022-07-27 07:35 UTC, merged

2022-07-27 07:35 UTC, akien-mga commented
Thanks!