Store line change in script navigation history
godotengine/godot pull request #63515
Opened 2022-07-26 22:35 UTC by KoBeWi

Closes #16554
Closes https://github.com/godotengine/godot-proposals/issues/4989 (what a coincidence...)

Any movement with more than 10 lines apart is saved into history.
![godot windows tools 64_qixu8sT8AL](https://user-images.githubusercontent.com/2223172/181123686-b9c2c307-02dd-4e21-a7eb-624401e8f85a.gif)
The implementation is rather hacky and might be not 100% reliable, but script editors are a mess :/ At least it works.

2022-08-11 09:55 UTC, reduz commented
I have the feeling I implemented this at some distant time in the past..

2022-08-11 10:36 UTC, Calinou commented
> I have the feeling I implemented this at some distant time in the past..

You might be thinking about script tab temperature, which is a different feature that serves different needs;

2022-08-11 10:37 UTC, reduz commented
@Calinou No I am pretty sure I made the history go back to the proper script/line.

2022-08-11 10:40 UTC, KoBeWi commented
Yes, the history works this way, but the line change wasn't recorded in the history. Only script changes and in 3.x Ctrl+clicks on members (which was probably a convenient bug lol).

2022-08-11 10:44 UTC, reduz commented
Oh alright, in any case, up to @Paulb23 to review

2022-08-21 18:02 UTC, Paulb23 requested changes, later dismissed
Yep definitely a slightly hacky approach, using `[set|get]_edit_state` will also change breakpoints and bookmarks etc, so currently we could end up resting these as well, which is not ideal.

Should also probably add support for scrolling around the docs as well.

2022-08-30 14:24 UTC, KoBeWi commented
> Should also probably add support for scrolling around the docs as well.

Docs don't have caret though.

2022-08-30 14:25 UTC, KoBeWi commented on editor/plugins/script_text_editor.cpp
> +		emit_signal(SNAME("request_save_previous_state"), previous_line);
I don't think there is a way to use a signal without exposing it, is there?

2022-09-19 10:36 UTC, Paulb23 commented on editor/plugins/script_text_editor.cpp
> +		emit_signal(SNAME("request_save_previous_state"), previous_line);
I mean't not exposing the `[get|set]_previous_state` methods by emitting the state directly here (only navigation state).

2022-09-19 10:38 UTC, Paulb23 commented
For docs I was thinking along the lines of, clicking some in doc navigation such as a method in the same class. It would be nice to store that as a navigation action.

2022-10-22 21:56 UTC, KoBeWi commented
Updated. I changed to use the new navigation history and simplified storing a bit. Also I added some scroll saving to editor help, but it's unreliable.

There is a bug sometimes where a position can be saved twice in a history, but I don't know what triggers it.

2023-03-22 20:17 UTC, KoBeWi commented
I did some more tweaks and I think this works reliably now.

2024-04-26 13:01 UTC, akien-mga approved these changes
Tested, seems to work fine.

2024-04-26 13:22 UTC, merged

2024-04-26 13:24 UTC, akien-mga commented
Thanks!

2025-07-15 13:26 UTC, vimhead commented
Was there a reason to choose 10 lines? It's not intuitive and doesn't correspond to how e.g. Intellij IDEA works (it goes back to every selection made)

2025-07-15 13:29 UTC, KoBeWi commented
VS Code has 10 line threshold.
Either way there needs to be some threshold, because when you e.g. hold Down arrow, it would flood the history if it stored every line.

2025-07-15 13:38 UTC, vimhead commented
You're right. Though IDEA solves it differently: only clicks are recorded to the history. I guess, it's just a taste. Thank you for such a rapid response.

2026-01-14 11:19 UTC, TheDying0fLight commented on editor/plugins/script_text_editor.h
> +	void store_previous_state();
I found these on master and looked for their usage, but from what I can tell these the `get` functions aren't called and `previous_state` is not used directly. So the functions and the code for them in `CodeTextEditor` seem to do nothing. Am I missing something or can these be removed?

2026-01-14 11:36 UTC, KoBeWi commented on editor/plugins/script_text_editor.h
> +	void store_previous_state();
See #108057

2026-01-14 11:37 UTC, TheDying0fLight commented on editor/plugins/script_text_editor.h
> +	void store_previous_state();
I see thanks (sorry forgot to look at linked PRs)