Generate errors for getters of untyped variables returning nothing
godotengine/godot pull request #63541
Opened 2022-07-27 14:40 UTC by garychia

Fixes #63393
Errors are generated for getter functions where not all code paths return a value.
![image](https://user-images.githubusercontent.com/88014292/181275114-ba2ddb42-4654-4fda-a8ec-d58ec1bfb2b3.png)

2023-06-17 14:09 UTC, adamscott commented
As the PR needs a rebase and the release is close, I moved the milestone to 4.2.
I put it, though, in the list of PRs that needs a review from the team, not to forget it.

2023-07-10 12:11 UTC, dalexeev requested changes

2023-07-10 12:11 UTC, dalexeev commented on modules/gdscript/gdscript_analyzer.cpp
> +	parser->current_function = p_getter;
I don't think a separate method is needed here. The current function context is not used below (lines 1264-1266). Also, in this case, you would also need to switch the static context (see #77151).

You should move lines 1264-1266 inside `resolve_class_body()` after calling `resolve_function_body()` on line 920 and remove the `resolve_getter_body()` method.

2023-07-11 16:50 UTC, garychia commented
I'll close this pull request and open a new one to work on the lastest codebase.

2023-07-11 16:50 UTC, closed without merging