Fix GraphEdit::arange_nodes causing a freeze when cycle in Graph
godotengine/godot pull request #63838
Opened 2022-08-02 19:37 UTC by tefusion

When a Graph contains cycle(s), e.g. GraphNode->GraphNode _layering would end up in an infinite loop since IS_SUBSET would never be true. By keeping check of the size of z, which contains the already layered nodes, one can detect a freeze (since it should change after current_layer increases). If it doesn't "u" didn't change and q and u will  never be equal resulting  in a freeze/infinite while loop).
If a freeze happens warn the user and put all the nodes part of the cycle (leftover in p) to the  first layer which will then just list them top to bottom at the end.

This is the more complete version of #63765. While not optimal (see video, everything part of cycle just gets listed randomly) it still sorts the non cyclic graphs part of the selected nodes, breaks the freeze and doesn't really impact performance of the more common non cyclic graphs (ShaderEditor, etc.). 

https://user-images.githubusercontent.com/69000267/182458611-138a1197-993b-483b-80b4-b177c81a35fd.mp4

2022-08-02 19:53 UTC, fire commented
@theoway Can you review?

2022-08-04 14:41 UTC, theoway commented on scene/gui/graph_edit.cpp
> +				WARN_PRINT("Graph contains cycle(s) so arranged one may be faulty.");
We can change the warning to: `"Graph contains cycle(s). The cycle(s) will not be rearranged accurately."`

2022-08-04 14:44 UTC, theoway requested changes
Great catch! The code is designed only for DAGs. As it is very rare for someone to code recursions in visualscripts, cycles rarely occur. This approach handles them well. 
It is not possible to layer a cyclic graph so we cannot expect any decent rearrangement. 
For time being, a warning to user is sufficient.

2022-08-04 14:48 UTC, fire approved these changes
Approvable after revisions are made.

2022-08-04 17:36 UTC, merged

2022-08-04 17:36 UTC, akien-mga commented
Thanks!