Fix input handling issue of autocompletion candidates list
godotengine/godot pull request #63876
Opened 2022-08-03 14:07 UTC by heppocogne

This commit fixes #63726 
Add CodeEdit::CodeCompletionInputHandler (inherits `Control`) for input handling.

2022-08-04 20:22 UTC, Paulb23 requested changes
This seems a bit overkill, can we not handle the `InputEventMouseMotion` in `CodeEdit` preventing being passed to `TextEdit` if it's over the completion menu?

2022-08-05 04:33 UTC, heppocogne commented
@Paulb23 
As you say, we didn't have to add another control node. 
Add `accept_event()` to CodeEdit::gui_input() to prevent `InputEventMouseMotion` from being handled by TextEdit::gui_input().

2022-09-29 15:15 UTC, KoBeWi commented
Needs rebase
I tested and this fixes the issue. CC @Paulb23

2023-02-13 19:54 UTC, akien-mga commented
I pushed a rebase myself. Didn't test.

2023-02-13 21:42 UTC, KoBeWi commented
Does not seem to work now 🙃

2023-02-17 21:46 UTC, KoBeWi commented
The condition works and event is accepted. But looking at these changes, I don't know how it fixed the issue before 🙃

2023-03-09 13:05 UTC, YuriSizov commented
This seems to prevent some of the issues for me. Previously you could get random text selection on clicks and drags within the completion box. Now it only seems to happen if you start the drag on the inside, but finish it on the outside. This should be handled as well, of course.

This issue can lead to a crash too, under some conditions (see https://github.com/godotengine/godot/issues/72114).

2023-03-09 15:01 UTC, YuriSizov commented
Okay, I've figured a way to prevent the rest of the issues. Thanks for working on this, but I will have to supersede it with https://github.com/godotengine/godot/pull/74665, which covers more cases.

2023-03-09 15:01 UTC, closed without merging