Implement coloring for disabled branches in the shader editor
godotengine/godot pull request #63872
Opened 2022-08-03 12:30 UTC by Chaosus

This PR implement dimming of the disabled branches of the shader preprocessor. To do it, besides adding a handling of the branch to the shader preprocessor, I've implemented some new methods to the `CodeHighlighter`:

![image](https://user-images.githubusercontent.com/3036176/182606793-9be5aab1-30ba-489d-82e0-21fe3671cd07.png)

This is a part of https://github.com/godotengine/godot-proposals/issues/5062

2022-08-03 12:37 UTC, akien-mga commented
Looks nice!

How come `#else` has a different color than `#ifdef` and `#endif`?

2022-08-03 12:40 UTC, Chaosus commented
> How come #else has a different color than #ifdef and #endif?

That's strange, I will look what caused this a bit later this day.

2022-08-03 14:07 UTC, Chaosus commented
@akien-mga It's not related or introduced by this PR, it's due preprocessor directive and keywords have similar names (#if, #else and `if`, `else`) and the control flow keywords have a separate `control_flow_keyword_color`. Not sure how it should be fixed, and I think it's a subject for other PR.

2022-08-03 15:05 UTC, bitsawer commented
That was fast :) I guess you were already working on that before I made that improvement proposal! Looks good!

Interestingly, I think the structure ShaderPreprocessor::SkippedCondition and all logic related to that is actually dead code and mostly unused. I think TheOrangeDay was working on that to implement this very syntax highlighting feature but never finished it and now it doesn't really do anything useful. Removing it up might be a good idea, unless I am wrong. It has been a while since I touched that code, so no guarantees. Not really related to this PR either.

2022-08-04 20:41 UTC, Paulb23 requested changes
`SyntaxHighlighters` are designed to be self contained rather then having "overrides" passed in or should make calls out e.g `GDScriptSyntaxHighlighter`.

Not entirely sure what that looks like, some initial thoughts, are something along the lines of the way regions work, or create a sub class e.g `GDShaderSyntaxHighlighter` for it.

2022-08-06 12:54 UTC, Chaosus commented
@Paulb23 Done, I think - pushed new methods to a new class `GDShaderSyntaxHighlighter`.

2022-08-09 20:49 UTC, Paulb23 reviewed
Couple notes inline, would also suggest making this editor only similar to the `GDScriptSyntaxHighlighter`.

2022-08-09 20:49 UTC, Paulb23 commented on scene/resources/syntax_highlighter.cpp
> +			}
There shouldn't be a need to loop here as the highlighter will only stop using the current colour when it reaches a new line, or a new entry in the `color_map`. Given we're setting the entire line the same colour, `color_map[0] = highlighter_info;` should work.

2022-08-09 20:49 UTC, Paulb23 commented on scene/resources/syntax_highlighter.h
> +	};
Can use a `Point2i` rather then adding struct, unless this is for some future changes?

2022-08-10 04:21 UTC, Chaosus commented
@Paulb23 Fixed as you said.

2022-08-14 10:21 UTC, Paulb23 requested changes

2022-08-14 10:21 UTC, Paulb23 commented on scene/resources/syntax_highlighter.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::COLOR, "disabled_branch_color"), "set_disabled_branch_color", "get_disabled_branch_color");
This is no longer needs to be bound.

2022-08-14 10:21 UTC, Paulb23 commented on scene/register_scene_types.cpp
> +	GDREGISTER_CLASS(GDShaderSyntaxHighlighter);
As before no need to expose it, should be fine to have this as editor only.

2022-08-14 10:21 UTC, Paulb23 commented on scene/resources/syntax_highlighter.h
> +	void add_disabled_branch_region(int p_from_line, int p_to_line);
Can have this take a `Point2i` now to save us from parsing it.

2022-08-14 10:21 UTC, Paulb23 commented on scene/resources/syntax_highlighter.h
> +	void set_disabled_branch_regions(const Vector<String> &p_regions);
Ditto here, or as it editor only can remove these methods if we have no plans to use them.

2022-08-14 10:21 UTC, Paulb23 commented on scene/resources/syntax_highlighter.h
> +	Vector<String> get_disabled_branch_regions() const;
`Point2i` here also.

2022-08-14 10:42 UTC, Chaosus commented
@Paulb23 OK, I've cut all unused methods and made this class unexposed to the editor.

2022-08-14 10:52 UTC, Paulb23 commented
@Chaosus would move the highlighter code to the top of `shader_editor_plugin.[cpp|h]` as it's not relevant for scene now. Same way `EditorSyntaxHighlighter` is at the top of `script_editor_plugin`.

2022-08-14 11:06 UTC, Chaosus commented
@Paulb23 Done

2022-08-14 11:26 UTC, Paulb23 approved these changes
Highlighter changes looks good.

On `How come #else has a different color than #ifdef and #endif?`

Keywords cannot contain symbols apart from `_` so other then adding an exception for the shader editor, we could try using regions something like `add_color_region('#', ' ', colour, false)`

2022-08-15 10:16 UTC, akien-mga approved these changes

2022-08-15 10:16 UTC, merged

2022-08-15 10:16 UTC, akien-mga commented
Thanks!