Add `Dictionary.find()`
godotengine/godot pull request #63968
Opened 2022-08-05 17:33 UTC by KoBeWi

I use `enum.keys().find(key)` to reverse-lookup an enum value saved as string. The problem is that `keys()` dumps all keys into an array, so `keys().find()` first extracts the array and then finds value in the array, which is just bad :/ The new method skips the extraction part and is ~10x faster.

I also added some unit tests.

2022-08-05 17:34 UTC, KoBeWi commented on doc/classes/Dictionary.xml
> -		Dictionary type. Associative container which contains values referenced by unique keys. Dictionaries are composed of pairs of keys (which must be unique) and values. Dictionaries will preserve the
The printed order is always correct after #57052

2022-08-06 09:23 UTC, timothyqiu commented
I understand this is for dealing with enums. But for a normal dictionary, `null` is a valid key, so `Dictionary.find()` won't be able to distinguish between found and not found in that case. I think it's worth documenting if acceptable.

2022-08-06 10:16 UTC, kleonc commented
> for a normal dictionary, `null` is a valid key, so `Dictionary.find()` won't be able to distinguish between found and not found in that case. I think it's worth documenting if acceptable.

Current description in the docs is correct and implies this though. But I guess that case can be mentioned explicitly.
```gdscript
var key = dict.find(value)

# Correct check:
var found: bool = key != null or null in dict

# Same as: (wondering if it could end up being cheaper because of the GDScript overhead)
var found: bool = key in dict
```

2022-08-06 20:37 UTC, KoBeWi commented
I added some note about, I don't think anything more is necessary. I bet `null` as a Dictionary key is not used very often and even less with `find()`.

2022-08-11 15:21 UTC, reduz requested changes, later dismissed

2022-08-11 15:21 UTC, reduz commented on core/variant/dictionary.cpp
> +Variant Dictionary::find(const Variant &p_value) const {
I think this should be called `find_key` or `find_by_value` as clarification since all methods in Dictionary operate by key.

2022-09-01 15:38 UTC, akien-mga approved these changes
Approved in PR review meeting.

Some doubts on what the best name should be for this but nobody seems to care enough to make suggestions :P

2022-09-01 15:38 UTC, merged

2022-09-01 15:38 UTC, akien-mga commented
Thanks!

2022-09-05 13:13 UTC, akien-mga commented
Should be backported manually if wanted in 3.x.