Add `textureQueryLod/Levels` functions to the shader language
godotengine/godot pull request #64310
Opened 2022-08-12 09:54 UTC by Chaosus

Adds https://registry.khronos.org/OpenGL-Refpages/gl4/html/textureQueryLod.xhtml and https://registry.khronos.org/OpenGL-Refpages/gl4/html/textureQueryLevels.xhtml GLSL functions to the Godot Shading Language.

2022-08-12 16:26 UTC, clayjohn requested changes
These should all be marked as high-end only as they will not be supported in the OpenGL 3 renderer

2022-08-12 17:45 UTC, Chaosus commented
@clayjohn Fixed

2022-08-12 17:47 UTC, clayjohn approved these changes

2022-08-12 18:28 UTC, merged

2022-08-13 17:14 UTC, Calinou commented
Out of curiosity, what are some use cases for those functions?

2022-08-13 17:23 UTC, Chaosus commented
https://stackoverflow.com/questions/24388346/how-to-access-automatic-mipmap-level-in-glsl-fragment-shader-texture for `textureQueryLod`, I guess something similar for levels - e.g. draw something different on geometry with different LOD/mipmap levels.