Rename `str2var` to `str_to_var` and similar
godotengine/godot pull request #64367
Opened 2022-08-13 16:14 UTC by Mickeon

As brought up in https://github.com/godotengine/godot/issues/54161#issuecomment-1198981759.

To make it short, the naming scheme with "2" in the middle is not always used across Godot (`String.int_to_bin()`), and it isn't proper English.

Affects the internal **Math** class, some translations and a good chunk of the audio filter code.

| Before | After|
| --------| ---------|
| `var2str` | `var_to_str`
| `str2var` | `str_to_var`
| `bytes2var` | `bytes_to_var`
| `bytes2var_with_objects` | `bytes_to_var_with_objects`
| `var2bytes` | `var_to_bytes`
| `var2bytes_with_objects` | `var_to_bytes_with_objects`
| `linear2db` | `linear_to_db`
| `db2linear` | `db_to_linear`

I think it's worth noting, before merging this, that while testing I did find writing these methods to be much slower (_underscore, two characters, another underscore, and the Italian keyboard requires holding Shift to access the underscores_), although it may be a matter of getting used to it.

2022-08-13 16:23 UTC, raulsntos commented
The `.po` and `.pot` files in the `doc/translations/` folder are auto-generated when syncing translations from Weblate, you should not manually change them.

2022-08-13 16:38 UTC, fire commented
@Calinou Thoughts on this? I support this rename of 2 to "to".

2022-08-13 16:42 UTC, Mickeon commented
The mentioned reply is among the most liked in the tracker. Among the thumbs up, Calinou is also present.

2022-08-13 18:44 UTC, TokageItLab commented
also deg2rad/rad2deg?

2022-08-13 18:53 UTC, Mickeon commented
Oopsie.

2022-08-13 23:37 UTC, Mickeon commented
Updated to include `deg_to_rad` and `rad_to_deg`.

2022-08-14 09:35 UTC, YuriSizov commented
The last time this was discussed, we didn't decide how far the naming change should go. For example, with these changes it no longer makes sense to use shortened terms, e.g. str instead of string, deg instead of degree.

The 90s naming scheme is more forgiving in that regard. The new naming starts to look weird without proper renames.

2022-08-14 09:48 UTC, Mickeon commented
I personally think that going "too" far would do the opposite of what the PR is meant to do, that is, potentially making the code too verbose and actually harder to read.

In fact, and I don't know what to make of this...
I actually prefer to read `deg2rad()` in the actual source code, but exposed as `deg_to_rad()` in GDScript (`DegToRad()` in **C#**). I don't know what the opinion of most is, but it does look nicer to me in **C++**.

```C++
		// Before.
		p_rotation_offset = Math::deg2rad(rotation_offset->get_value());
		p_rotation_step = Math::deg2rad(rotation_step->get_value());
		
		// After.
		p_rotation_offset = Math::deg_to_rad(rotation_offset->get_value());
		p_rotation_step = Math::deg_to_rad(rotation_step->get_value());
```

2022-08-14 12:37 UTC, MewPurPur commented
@YuriSizov Abbreviations and acronyms are OK, but "2" instead of "to" or "two", and "4" instead of "for" - these are not abbreviations, just interwebz slang.

2022-08-14 13:21 UTC, m-oezokyay commented
@YuriSizov I think this isn't a big problem. In proramming, pretty much everyone is used to "int" for "integer". "var" is a keyword in GDScript, mostly used to declare a Variant. "deg" and "rad" are common in calculators and are also alternative symbols for the corresponding SI units. "str" for "string" seems harder to justify, but I wouldn't mind. So I think the use of shortened terms can often be justified much easier than something like "2" for "to".

2022-08-14 13:56 UTC, Mickeon commented
`str()` coverts any given **Variable** to **String** and is already present in the GlobalScope. For **Object**, it calls its `to_string()` method.

2022-08-15 10:33 UTC, YuriSizov commented
@m-oezokyay I don't think that "in programming" is a good defense in this case, because this style of naming, `foo2bar`, is also very common in programming, or at least it used to be when the authors of these methods were building their experience.

If we do these changes to improve the clarity of our API surface, then we shouldn't lean onto "in programming" conventions at all, because otherwise I see no problem with the clarity of `foo2bar`.

PS. By the way, `var`, I think, is the worst offender in Godot, because it's not clear to the reader if it's for "variable" or for "Variant". In case of the keyword, it's a variable, in case of `var2str` and `str2var` it's a Variant. But that's not obvious, especially for people learning the API (and these are the people most affected by these changes).

2022-08-15 10:47 UTC, Mickeon commented
Again, I find there's gotta be a good balance to strike between readability and... verbosity. But at the same time, in the specific cases of `str2var()` and `var2str()`, I really struggle to think when it was the last time I used it...

2022-08-15 10:51 UTC, Mickeon commented
In the cases of `linear2db()`, `db2linear()`, `deg2rad()`, `rad2deg()`, their meaning is very likely to be inferred by the context around the code (working with sounds or angles, names of passed variables that are called "volume, angle, rotation, yaw, tilt, pitch..."), so their shortened names may even be welcome.

2022-08-15 10:56 UTC, Mickeon commented
But regardless of the overall final consensus, it seems like most users seeing this PR do like switching the "**_2_**" with "**\_to\_**".

2022-08-15 15:41 UTC, Mickeon commented
If there's need to split this into multiple, smaller PRs to discuss which ones should be merged, by all means, I can do it.

2022-08-15 15:49 UTC, YuriSizov commented
@Mickeon To be honest, we are not sure how to handle your renaming PRs in general, at the moment. They are based on quick mentions and limited discussions in a tracker issue and often don't have an associated issue or a proposal (the tracker was never supposed to replace proposals).

So even in cases where there are plenty of upvotes we cannot be sure everyone who would be opposed had a chance to join the discussion (again, tracker is not a substitute for that). We would also prefer to avoid bikeshedding too much this close to beta.

So, keep it as is for now. Until we figure out how to decide on this.

2022-08-15 15:58 UTC, Mickeon commented
Do I open proposals for the most substantial and/or contested changes?

2022-08-15 16:03 UTC, YuriSizov commented
> Do I open proposals for the most substantial and/or contested changes?

I guess, if you want to advocate for these changes. But like I've said, we aren't sure how to deal with them yet.

2022-08-17 19:53 UTC, Mickeon commented
Setting myself a reminder:
This PR doesn't currently change the variable names in gd_glue.cpp and GD.cs (GodotSharp) (oops). I could see how the final reception from the core developers before doing it, I suppose.

2022-08-19 19:23 UTC, MewPurPur commented
Missed `inst2dict` and `dict2inst`

2022-08-25 16:22 UTC, YuriSizov commented
Approved for the list present in this PR/linked proposal

2022-08-25 16:48 UTC, Mickeon commented
There's some of these that have been missed in this PR. What about them? Would it still be possible to make a separate PR for them?

2022-08-25 17:00 UTC, YuriSizov commented
You can add inst2dict and dict2inst here, I think. I'm not sure there is anything else that needs changing. Feel free to bring it up, I guess, in the next few days or so.

2022-08-25 20:57 UTC, Mickeon commented
Merging mess, trying to solve...

2022-08-26 06:38 UTC, akien-mga approved these changes
We approved this in a bikeshedding meeting.
I'll check locally to make sure everything is properly converted.

2022-08-26 06:41 UTC, akien-mga commented
C# solution fails building with:
```
Error: /home/runner/work/godot/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs(550,65): error CS1061: 'object' does not contain a definition for 'NativeVar' and no accessible extension method 'NativeVar' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?) [/home/runner/work/godot/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
```

2022-08-26 08:38 UTC, Mickeon commented
Epic merge fail.

2022-08-26 10:30 UTC, akien-mga commented
There seems to be some code in Mono that might still need porting:
```
modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs
186:                                    NativeFuncs.godotsharp_var2bytes(var, false.ToGodotBool(), out var varBytes);

modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs
27:            NativeFuncs.godotsharp_bytes2var(varBytes, allowObjects.ToGodotBool(), out godot_variant ret);
535:            NativeFuncs.godotsharp_str2var(godotStr, out godot_variant ret);
550:            NativeFuncs.godotsharp_var2bytes((godot_variant)var.NativeVar, fullObjects.ToGodotBool(), out var varBytes);
574:            NativeFuncs.godotsharp_var2str((godot_variant)var.NativeVar, out godot_string ret);

modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/NativeFuncs.cs
464:        internal static partial void godotsharp_bytes2var(in godot_packed_byte_array p_bytes,
507:        internal static partial void godotsharp_str2var(in godot_string p_str, out godot_variant r_ret);
509:        internal static partial void godotsharp_var2bytes(in godot_variant p_what, godot_bool p_full_objects,
512:        internal static partial void godotsharp_var2str(in godot_variant p_var, out godot_string r_ret);

modules/mono/glue/runtime_interop.cpp
1236:void godotsharp_var2str(const godot_variant *p_var, godot_string *r_ret) {
1242:void godotsharp_str2var(const godot_string *p_str, godot_variant *r_ret) {
1259:void godotsharp_var2bytes(const godot_variant *p_var, bool p_full_objects, godot_packed_array *r_bytes) {
1271:void godotsharp_bytes2var(const godot_packed_array *p_bytes, bool p_allow_objects, godot_variant *r_ret) {
1482:   (void *)godotsharp_bytes2var,
1502:   (void *)godotsharp_str2var,
1503:   (void *)godotsharp_var2bytes,
1504:   (void *)godotsharp_var2str,
```

CC @godotengine/dotnet

Everything else seems good.

2022-08-26 10:37 UTC, Mickeon commented
Oooh I did see it, I actually wasn't sure what was the naming scheme used for them (`godotsharp_strtovar` or `godotsharp_str_to_var`)?

2022-08-26 10:40 UTC, raulsntos commented
The naming scheme would be `godotsharp_str_to_var`.

2022-08-26 10:40 UTC, akien-mga commented
Should be `godotsharp_str_to_var` I believe.

2022-08-26 12:30 UTC, raulsntos requested changes
The mono module looks good except for a few rebasing mistakes.

2022-08-26 12:30 UTC, raulsntos commented on modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs
> +        /// Converts a formatted string that was returned by <see cref="VarToStr(object)"/> to the original value.
```suggestion
        /// Converts a formatted string that was returned by <see cref="VarToStr(Variant)"/> to the original value.
```

2022-08-26 12:30 UTC, raulsntos commented on modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs
> +        /// Deserialization can be done with <see cref="BytesToVar(byte[], bool)"/>.
```suggestion
        /// Deserialization can be done with <see cref="BytesToVar(Span{byte}, bool)"/>.
```

2022-08-26 12:59 UTC, Mickeon commented on modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs
> +        /// Converts a formatted string that was returned by <see cref="VarToStr(object)"/> to the original value.
Solved with a merge

2022-08-26 13:57 UTC, raulsntos approved these changes

2022-08-26 21:04 UTC, merged

2022-09-02 07:47 UTC, aXu-AP commented
This is a great, welcome change. As I english isn't my first language, I usually end up reading numbers in my own language (finnish), resulting in strange sounding functions (varkaksistr etc.). I'm sure I'm not the only one who had this problem. Glad it's getting changed :)