Rename every instance of `caret_blink_speed` to `caret_blink_rate`
godotengine/godot pull request #64361
Opened 2022-08-13 13:32 UTC by Mickeon

As brought up in https://github.com/godotengine/godot/issues/54161#issuecomment-1175135591 and https://github.com/godotengine/godot/issues/54161#issuecomment-1175247779.

While none of the comments mentioned "rate", I chose it because the Windows settings and registry call it **CursorBlinkRate**. I was about to rename it to `caret_blink_time`, but just as I was creating this Pull Request, I realised how much better `caret_blink_rate` rolls off the tongue, especially because it can't be confused for the internal `caret_blink_timer` variable.

It's been changed in the **editor settings**, and in the **LineEdit** and **TextEdit** classes.
Affects setters and getters, and passed parameters, too.

2022-08-13 13:33 UTC, Mickeon commented
Speaking of which, the **LineEdit** and **TextEdit** description, while short, has also been a bit misleading?
> Duration (in seconds) of a caret's blinking cycle.

"cycle" implies the time it takes for both states (visible and hidden) to complete, but the current behaviour simply toggles between the two every `caret_blink_speed` seconds, so it's just half the "total" caret blinking cycle.

2022-09-06 12:30 UTC, akien-mga approved these changes
Approved in PR meeting. Needs rebase.

2022-09-06 12:36 UTC, aaronfranke approved these changes
The old name of "speed" was definitely wrong, since an increased value is slower.

2022-09-06 13:14 UTC, akien-mga commented
So I got confused in the meeting a bit but "rate" is often used as a synonym to "frequency", which is the inverse of the time period.

Maybe "caret_blink_interval" would be better?

2022-09-06 13:17 UTC, Mickeon commented
I wanted to keep it shorter but both _rate_ and _interval_ make more sense than _speed_. Sounds good to me.

2022-09-06 13:48 UTC, aaronfranke approved these changes

2022-09-06 13:50 UTC, Mickeon commented
Wait! Forgot C# renames

2022-09-06 13:59 UTC, aaronfranke requested changes

2022-09-06 13:59 UTC, aaronfranke commented on scene/gui/line_edit.cpp
> +	caret_blink_interval = p_rate;
```suggestion
void LineEdit::set_caret_blink_interval(const float p_interval) {
	ERR_FAIL_COND(p_interval <= 0);
	caret_blink_interval = p_interval;
```

2022-09-06 14:10 UTC, Mickeon commented on scene/gui/line_edit.cpp
> +	caret_blink_interval = p_rate;
Fixed every occurrence.

2022-09-06 14:12 UTC, aaronfranke approved these changes

2022-09-06 14:51 UTC, akien-mga commented on editor/project_converter_3_to_4.cpp
> +	{ "get_caret_blink_speed", "get_caret_blink_interval" }, // TextEdit, LineEdit
This method name didn't exist in `3.x` so it doesn't need to be handled. Same for `set_caret_blink_speed`.

2022-09-06 14:52 UTC, akien-mga commented on editor/project_converter_3_to_4.cpp
> +	{ "GetCaretBlinkSpeed", "GetCaretBlinkInterval" }, // TextEdit, LineEdit
This wasn't the `3.x` name of these methods. It's `Cursor{Set,Get}BlinkSpeed` that should be changed.

2022-09-06 17:00 UTC, akien-mga approved these changes

2022-09-07 07:21 UTC, merged

2022-09-07 07:21 UTC, akien-mga commented
Thanks!