Fix `EditorPropertyArray` to accept arrays with specific resource type
godotengine/godot pull request #64383
Opened 2022-08-14 08:47 UTC by Chaosus

Currently, it's not possible to pass the textures to a shader array uniform (at least with a simple drag & drop):

![image](https://user-images.githubusercontent.com/3036176/184529411-7fd37b8f-bf01-4426-9be8-24bb391b0cee.png)

After the fix, it's simple:

![image](https://user-images.githubusercontent.com/3036176/184529460-abba72d1-eb7f-4bca-ac5f-5a10abcb92df.png)

2022-10-27 07:51 UTC, reduz requested changes

2022-10-28 15:17 UTC, Chaosus commented on editor/editor_properties_array_dict.cpp
> +		} else { // subType
But how? It's just handle for hints declared like: (```ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "attachments", PROPERTY_HINT_ARRAY_TYPE, "RDPipelineColorBlendStateAttachment"), "set_attachments", "get_attachments");```) - all other cases (like int arrays) handles by the different functions.

2022-11-22 14:08 UTC, akien-mga commented on editor/editor_properties_array_dict.cpp
> +		} else { // subType
Yes this should be able to use the hint string logic just above this `else`.
Where is the code that registers those properties?

2022-11-22 14:40 UTC, akien-mga commented
Superseded by #69005.

2022-11-22 14:40 UTC, closed without merging