Fix alternative tile popup menu not being openable
godotengine/godot pull request #64601
Opened 2022-08-19 03:00 UTC by MinusKube

Fixes #64600

This fixes the alternative tile popup menu which was not openable anymore, due to a regression from #62629.

2022-08-25 08:53 UTC, groud requested changes

2022-08-25 08:53 UTC, groud commented on editor/plugins/tiles/tile_set_atlas_source_editor.cpp
> +				drag_type = DRAG_TYPE_NONE;
I think we should set `drag_type = DRAG_TYPE_NONE` even if `drag_type != DRAG_TYPE_MAY_POPUP_MENU`. As a safety measure.
Thus the logic should likely be changed to:
```
if (mb->is_pressed()) {
   ...
} else {
   if (drag_type == DRAG_TYPE_MAY_POPUP_MENU) {
      ...
   }
   drag_type = DRAG_TYPE_NONE;
}
```

That will make it 100% sure that dragging is "released" when mouse is released.

2022-08-25 12:49 UTC, groud approved these changes
Needs for CI to pass, but LGTM otherwise. Thanks!

2022-08-26 08:35 UTC, merged

2022-08-26 08:35 UTC, akien-mga commented
Thanks!