Add GraphNode 'selected' and 'deselected' signals, simplify GraphEdit
godotengine/godot pull request #64840
Opened 2022-08-24 16:22 UTC by maximkulkin

Make GraphEdit node selection signals more consistent whether node is selected through UI or through code.

Implementation details:
* Add "selected" and "deselected" signals on GraphNode.
* Update GraphNode.set_selcted() to
  * do redundancy check (if node is already in proper selection state);
  * fire corresponding signal.
* Update GraphEdit to subscribe to "selected" and "deselected" signals of each child GraphNode
  * on signal callback fire "node_selected" or "node_deselected" signals
* Remove logic to fire "node_selected" / "node_deselected" from GraphEdit code as it is now handled by GraphNode

That way proper signals are fired regardless of whether GraphNode is selected from UI, by setting it's "selected" property in the code, or by calling GraphEdit.set_selected(graph_node).

The patch is not compatible with 3.x branch because of renamed signals and type annotations introduced in 4.x version. Once merged I will do proper backport to 3.x branch.

Fixes #41799

2022-08-27 20:04 UTC, maximkulkin commented
@YuriSizov can we get it started?

2022-08-30 14:45 UTC, maximkulkin commented
Resolved recent conflicts caused by adding "selectable" logic. @SaracenOne you're welcome to review changes

2022-09-02 01:33 UTC, maximkulkin commented
This PR is ready for review

2022-09-02 21:21 UTC, Geometror requested changes
The overall implementation looks good to me. However, there's currently one issue: The `node_selected` signal is emitted twice when clicking on a GraphNode (since it is emitted in `_graph_node_raised` and `_graph_node_selected`).

2022-09-04 01:56 UTC, maximkulkin commented
@Geometror Updated code to not send node_selected signal.

2022-09-04 21:10 UTC, Geometror approved these changes
Works fine now:)

2022-09-05 06:26 UTC, akien-mga commented on scene/gui/graph_edit.cpp
> +			// Find node which was clicked on
Please end comment sentences with a period (same below).

2022-09-05 06:26 UTC, akien-mga commented
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

2022-09-05 06:29 UTC, maximkulkin commented
@akien-mga Done

2022-09-05 06:32 UTC, maximkulkin commented on scene/gui/graph_edit.cpp
> +			// Find node which was clicked on
Done

2022-09-05 06:35 UTC, akien-mga approved these changes

2022-09-05 06:54 UTC, merged

2022-09-05 06:56 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: