Rename uniform to parameter in visual shader classes and ShaderMaterial
godotengine/godot pull request #64952
Opened 2022-08-27 09:31 UTC by Chaosus

Changes:

- `ShaderMaterial::`set_shader_uniform` renamed to `set_shader_param`
- `ShaderMaterial::`get_shader_uniform` renamed `get_shader_param`
- All visual shader classes `<Type>Uniform` renamed `<Type>Parameter`
- Separates `VisualShaderNodeTextureUniform` to `VisualShaderNodeTextureParameter` and `VisualShaderNodeTexture2DParameter`
- Added compatibility classes and changed docs accordingly

Target to close https://github.com/godotengine/godot-proposals/issues/5123 hope I did everything correct (as far as I remember the last bikeshedding meeting)

2022-08-27 20:29 UTC, QbieShay commented
Hey @Chaosus, thanks a lot for taking the time to do this!
I have two questions:
1. Is the entry for "global shader unifrom" in project setting also changed?
2. I am not sure if they preferred `set_shader_param` or `set_shader_parameter`? (@akien-mga ?)
The rest looks good to me! (Note I didn't test, i can't this weekend)

2022-08-28 08:48 UTC, Chaosus commented
```
Is the entry for "global shader unifrom" in project setting also changed?
```
In the project setting, it's called `Shader Globals` - how do you want to change it?

![image](https://user-images.githubusercontent.com/3036176/187065660-4f1c1162-0194-49d4-a11b-0672acf59c5c.png)

Also, I didn't change the name of the methods in the `RenderingServer` and `MaterialStorage` - I'm not sure that it is a good thing to do, and @reduz would certainly against it.

2022-08-28 19:43 UTC, clayjohn commented
> Also, I didn't change the name of the methods in the RenderingServer and MaterialStorage - I'm not sure that it is a good thing to do, and @reduz would certainly against it.

I think anything exposed to users should use "parameter". I don't think it is a big deal to change the naming in RenderingServer and MaterialStorage. After all, reduz originally named them with parameter and it was just changed to "uniform" recently (in https://github.com/godotengine/godot/pull/59840 and https://github.com/godotengine/godot/pull/59844)

2022-08-28 19:59 UTC, Chaosus commented
Okay, if this is desired I will make a patch to do it ^^

2022-08-29 07:27 UTC, Zireael07 commented
> I think anything exposed to users should use "parameter". 

Yep, should be consistent whichever way the cookie crumbles

2022-08-29 07:44 UTC, Chaosus commented
@clayjohn Alright, I've renamed uniform term to parameter across all functions and enumeration members:

![image](https://user-images.githubusercontent.com/3036176/187150232-4350fbc0-7a86-48fc-a4ac-c393226df4db.png)

2022-08-29 10:50 UTC, nathanfranke commented
If anyone disagrees with the naming in https://github.com/godotengine/godot/pull/64092, let me know. I decided `shader_param/` for compatibility/simplicity, and since the internal properties are not user facing (users should really be using `set_shader_param("foo", bar)`)

2022-08-29 11:03 UTC, akien-mga commented
> If anyone disagrees with the naming in #64092, let me know. I decided `shader_param/` for compatibility/simplicity, and since the internal properties are not user facing (users should really be using `set_shader_param("foo", bar)`)

We should fully spell out `parameter` everywhere (it's already `set_shader_parameter` in this PR).

It would be useful to have compatibility code for `shader_param` (before #59844) and `shader_uniform` (before this PR) to ease transition from 3.x and earlier alphas.

2022-08-29 14:42 UTC, Chaosus commented
I've added `set_shader_param` -> `set_shader_parameter` to the project converter. Also renamed bunch of parameter names and other internal functions. I leave only some internal classes untouched such as `RD::Uniform`, `UniformSet` etc - do I need to rename them too?

2022-08-29 18:19 UTC, clayjohn commented
> I've added `set_shader_param` -> `set_shader_parameter` to the project converter. Also renamed bunch of parameter names and other internal functions. I leave only some internal classes untouched such as `RD::Uniform`, `UniformSet` etc - do I need to rename them too?

No, RD::Uniform and Uniform set etc. should all remain as is. Just the user-facing functions to set a single uniform should be changed. I'll review now!

2022-08-29 18:59 UTC, clayjohn reviewed
Looks mostly good. Great work! I think everything in RenderingDevice should continue to use "uniform". So you'll have to undo those changes unfortunately. I think it is best it maintains the original name as people using it will be more familiar with uniforms as uniform has a specific meaning in the context of graphics APIs that is incompatible with the more general term "parameter". Parameter is fine for the Godot-shader API though, so it is suitable for user-facing code in the editer, scene nodes and RenderingServer

2022-08-29 18:59 UTC, clayjohn commented on drivers/vulkan/rendering_device_vulkan.h
> +		ParameterType type = ParameterType::PARAMETER_TYPE_MAX;
I don't think we should change the RenderingDevice API. Its better to keep this closer to the actual names. It won't be used by beginners either, i.e. you have to know what a uniform is in order to use the RD API

2022-08-29 18:59 UTC, clayjohn commented on scene/resources/shader.cpp
>  	List<PropertyInfo> local;
This function should be renamed to ``get_shader_parameter_list``

2022-08-29 18:59 UTC, clayjohn commented on scene/resources/shader.cpp
> +	return params_cache.has("shader_uniform/" + p_name);
Probably should be ``shader_parameter``, but I wonder where the variables are set in the cache

2022-08-29 18:59 UTC, clayjohn commented on scene/resources/material.cpp
>  			shader->get_shader_uniform_list(&pl);
In this function "shader_uniform" should be "shader_parameter"

2022-08-29 18:59 UTC, clayjohn commented on scene/resources/material.cpp
>  			shader->get_shader_uniform_list(&pl);
Also backwards compatibility should be added to ``_set()`` and ``_get()``

2022-08-29 18:59 UTC, clayjohn commented on servers/register_server_types.cpp
> +	GDREGISTER_CLASS(RDParameter);
Should be reverted

2022-08-29 18:59 UTC, clayjohn commented on servers/rendering/rendering_device.h
> -class RDUniforms;
All of this should be reverted. RenderingDevice should continue using "uniform"

2022-08-30 06:07 UTC, Chaosus commented
@clayjohn Done I think - check again

2022-09-01 07:04 UTC, reduz commented
The actual problem is that uniform term is unfriendly to VisualShader for artists, everywhere else it should be uniform, which is the right term. "parameter" is not more friendly for programmers, its more confusing because anything can be a parameter.

2022-09-01 07:14 UTC, reduz requested changes
It also marks vulkan_core.h as changed, it should not be?

2022-09-01 07:14 UTC, reduz commented on drivers/vulkan/rendering_device_vulkan.h
> +	virtual RID uniform_set_create(const Vector<Uniform> &p_parameters, RID p_shader, uint32_t p_shader_set);
RenderingDevice needs to be left alone, these are fine.

2022-09-01 07:14 UTC, reduz commented on servers/rendering/renderer_geometry_instance.h
> +	virtual void set_instance_shader_parameters_offset(int32_t p_offset) = 0;
This is OK as uniforms

2022-09-01 07:14 UTC, reduz commented on servers/rendering/renderer_geometry_instance.h
> +	virtual void set_instance_shader_parameters_offset(int32_t p_offset) override;
Also OK as uniforms

2022-09-01 07:14 UTC, reduz commented on servers/rendering/renderer_geometry_instance.cpp
> +void RenderGeometryInstanceBase::set_instance_shader_parameters_offset(int32_t p_offset) {
This should be ok as uniforms

2022-09-01 07:14 UTC, reduz commented on servers/rendering_server.h
>  	virtual void global_shader_uniforms_load_settings(bool p_load_textures) = 0;
Missed these

2022-09-01 07:17 UTC, Chaosus commented
```It also marks vulkan_core.h as changed, it should not be?```

Sorry, due to formatting suddenly, reverted it back

2022-09-01 07:42 UTC, reduz requested changes

2022-09-01 07:42 UTC, reduz commented on drivers/gles3/rasterizer_scene_gles3.cpp
> +	GLuint global_buffer = GLES3::MaterialStorage::get_singleton()->global_shader_parameters_get_parameter_buffer();
it should be:
`global_shader_parameters_get_uniform_buffer`

2022-09-02 10:11 UTC, reduz approved these changes

2022-09-02 12:06 UTC, merged

2022-09-02 12:07 UTC, akien-mga commented
Thanks!