ci: wait for static check results before starting builds
godotengine/godot pull request #65232
Opened 2022-09-02 07:05 UTC by yedpodtrzitko

// Another attempt for what did not work in #65123

The CI workflow "📊 Static Checks" checks code formatting etc. and even if all the build workflows in pipeline are successful, the pipeline needs to be eventually re-run in case this one fails. From what I understand the bottleneck for the CI pipeline is the number of available workers which can run builds, so it would make sense to not run the "expensive" jobs unless we know the basic one is successful. 

Unfortunately it's impossible to make various workflow files depend directly among themselves, so the approach here utilizes [Reusable Workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows):
- change the trigger event for all builders to [workflow_call](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_call), which means they need to be invoked manually
- create [new workflow file runner.yml](.github/workflows/runner.yml) as an entrypoint for the pipeline
- in there, invoke "📊 Static Checks" first
- run other builds if Static Checks succeed

This means builders wont be shown separately in the [Actions Tab](https://github.com/godotengine/godot/actions), since they are now treated as a part of the Runner workflow. That makes is easier to cancel the whole build with a single click (a minuscule case, but still a nice thing to have) and it declutters the content there to a single row only per build.

2023-03-27 16:56 UTC, umarcor approved these changes
FTR, I independently proposed almost the same modification (#75338). The only difference is a few names.

2023-04-04 14:22 UTC, umarcor commented on .github/workflows/runner.yml
> +name: 🔗 Tiered Pipeline Runner
```suggestion
name: 🔗 GHA
```

See https://github.com/godotengine/godot/pull/75338#issuecomment-1484017251 and https://github.com/godotengine/godot/pull/75338#issuecomment-1485166201.

2023-04-04 14:24 UTC, umarcor commented on .github/workflows/runner.yml
> +  static-checks:
```suggestion
  static-checks:
    name: 📊 Static
```

See https://github.com/godotengine/godot/pull/75338#issuecomment-1485488463.

2023-04-04 14:25 UTC, umarcor commented on .github/workflows/runner.yml
> +  ios-build:
```suggestion
  ios-build:
    name: 🍏 iOS
```

See https://github.com/godotengine/godot/pull/75338#issuecomment-1485488463.

2023-04-04 14:25 UTC, umarcor commented on .github/workflows/runner.yml
> +  linux-build:
```suggestion
  linux-build:
    name: 🐧 Linux
```

See https://github.com/godotengine/godot/pull/75338#issuecomment-1485488463.

2023-04-04 14:26 UTC, umarcor commented on .github/workflows/runner.yml
> +  macos-build:
```suggestion
  macos-build:
    name: 🍎 macOS
```

See https://github.com/godotengine/godot/pull/75338#issuecomment-1485488463.

2023-04-04 14:27 UTC, umarcor commented on .github/workflows/runner.yml
> +  windows-build:
```suggestion
  windows-build:
    name: 🏁 Windows
```

See https://github.com/godotengine/godot/pull/75338#issuecomment-1485488463.

2023-04-04 14:31 UTC, umarcor requested changes
As discussed in #75338, please make workflow/job names shorter to reduce overflow in web views.

2023-04-04 14:32 UTC, yedpodtrzitko commented
@umarcor regarding shorter names - this is discussed in #75333 and I couldnt find there any compeling reason to do the renames other than for the sake of doing the renames. Did I miss your answer there?

2023-04-04 14:34 UTC, umarcor commented
@yedpodtrzitko click "Show all checks" at the bottom of this PR. Or see the sidebar of https://github.com/godotengine/godot/actions/runs/4608607317.

Currently, this PR drops the icons and a third of the space is used by 'Tiered Pipeline Runner'.

2023-04-04 14:36 UTC, yedpodtrzitko commented
I rest my case. I'm just gonna do the rebase as requested and leave the rest to maintainers.

2023-04-04 14:38 UTC, umarcor commented
@yedpodtrzitko fair enough. Please do edit the first message to explain the reason for dropping the icons.

2023-04-04 14:46 UTC, umarcor commented
For clarification, #75333 is about the priority of the hardcoded/static content in parens vs the dynamically generated content also in parens or in italics. This PR is introducing a prefix that hides both the static and the dynamic content.

2023-04-04 14:58 UTC, YuriSizov commented
> I'm just gonna do the rebase as requested and leave the decision to maintainers.

For the record, Akien and I agree that we shouldn't lose the icons and that we should use short names so that the checklist is readable.

2023-04-04 15:13 UTC, yedpodtrzitko commented
ok it should be done

2023-04-05 09:14 UTC, akien-mga approved these changes

2023-04-05 09:23 UTC, YuriSizov approved these changes

2023-04-05 10:08 UTC, merged

2023-04-05 10:08 UTC, akien-mga commented
Thanks!

2023-04-07 15:25 UTC, YuriSizov commented
Cherry-picked for 4.0.3.

2023-08-29 10:07 UTC, akien-mga commented
Cherry-picked for 3.6.

2023-09-06 11:15 UTC, akien-mga commented
Cherry-picked for 3.5.3.