[WIP] Improve dark mode on Windows 10.
godotengine/godot pull request #65262
Opened 2022-09-02 18:46 UTC by bruvzg

- Adds Windows 10 build version checks.
- Redraw window frame after setting dark mode.

2022-09-02 21:04 UTC, Calinou commented
The class reference should mention which Windows 10 versions support dark mode detection. As I understand it, 1809 is required for basic support, and 20H2 is required for full support (or any Windows 11 version).

2022-09-02 22:44 UTC, fire-forge commented
This doesn't work, unfortunately. The title bars have the same problem with this PR as they did in https://github.com/godotengine/godot/pull/65026.

I am working on finding a fix for this in a separate branch though. So far, I've tried two approaches that don't work, and I have a few more ideas for a solution. Hopefully I can find one that works.

2022-09-03 05:16 UTC, fire-forge commented
I've made several unsuccessful attempts to fix this issue using various Windows window APIs. So I'll have to defer this to someone else who knows what they're doing :P

I will write a new issue for this bug soon where I'll document the different methods I tried so I can hopefully save whoever tries to fix this some time.

2022-09-03 05:22 UTC, fire-forge requested changes

2022-09-03 05:22 UTC, fire-forge commented on platform/windows/display_server_windows.cpp
> +					SetWindowPos(windows[window_id].hWnd, 0, 0, 0, 0, 0, SWP_DRAWFRAME | SWP_NOACTIVATE | SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER);
This line can be removed. The window title bar updates correctly when the theme changes even when this line is removed.

2022-09-03 05:22 UTC, fire-forge commented on platform/windows/display_server_windows.cpp
> +				SetWindowPos(windows[window_id].hWnd, 0, 0, 0, 0, 0, SWP_DRAWFRAME | SWP_NOACTIVATE | SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER);
This line can also be removed, same as above.

2022-09-03 05:22 UTC, fire-forge commented on platform/windows/display_server_windows.cpp
> +			SetWindowPos(wd.hWnd, 0, 0, 0, 0, 0, SWP_DRAWFRAME | SWP_NOACTIVATE | SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER);
This line can also be removed because it has no effect. The window title bar doesn't draw correctly with or without this line included.

2022-09-03 08:15 UTC, bruvzg commented
> This doesn't work, unfortunately.

I have no idea how to fix it, so I guess it's better to disable dark title bar for Windows 10 (but keep dark mode/accent APIs) until it's fixed, and use it only on Windows 11.

2022-09-10 17:19 UTC, fire-forge commented
Blender 3.3 was released recently, and it supports the dark title bar on Windows 10 without any issues. At some point I will look at Blender's source code to see how they did it, and open a PR to implement it in Godot if I'm able to. Until then, this PR will be fine to merge since it's better to keep using the light title bar than a broken one.

2022-09-13 08:48 UTC, akien-mga approved these changes

2022-09-13 09:04 UTC, merged

2022-09-13 09:04 UTC, akien-mga commented
Thanks!

2022-09-13 09:07 UTC, bruvzg commented
> This is the commit on the Blender repository

It seems to be doing exactly the same. Probably something else is interfering with the title.

2022-12-12 22:08 UTC, naphipps commented
Doing the following fixed the dark mode title bar on Windows 10 for me:
```cpp
//include <dwmapi.h> and link to dwmapi.lib

LPCSTR subkey = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize";
LPCSTR value = "SystemUsesLightTheme";
DWORD word = 0;
DWORD size = sizeof(DWORD);
LSTATUS status = RegGetValueA(HKEY_CURRENT_USER, subkey, value, RRF_RT_DWORD, nullptr, &word, &size);
bl is_dark_mode = status == ERROR_SUCCESS && word == 0;

if (is_dark_mode)
{
	HWND native_window = (HWND)GetNativeWindow();
	BOOL value = true;
	DwmSetWindowAttribute(native_window, 20, &value, sizeof(value));

	WPARAM wparam{};
	LPARAM lparam{};
	wparam = FALSE;
	CallWindowProcA(_prev_window_procedure, native_window, WM_NCACTIVATE, wparam, lparam);
	wparam = TRUE;
	CallWindowProcA(_prev_window_procedure, native_window, WM_NCACTIVATE, wparam, lparam);
}
```
For some reason, deactivating the title bar, then activating it again works... Feel free to use the DefWindowProcA instead of CallWindowProcA. I happen to subclass my window procedure in my project.

I started on this topic over on [pull 65026](https://github.com/godotengine/godot/pull/65026) and found my way here as well.