Add strip_bbcode() method to String
godotengine/godot pull request #65384
Opened 2022-09-05 21:18 UTC by ztc0611

Adds a function to strip bbcode tags out of strings.

Example Code:
```
var s = "[color=#ffffff]Hello![/color]
print(s.strip_bbcode())
```

Result: `Hello`

Implements [godot-preposals/#5056](https://github.com/godotengine/godot-proposals/issues/5056)

2022-09-06 19:05 UTC, ztc0611 commented
Sorry for that, I made the mistake of putting new changes on the same branch as this PR.

2022-09-11 02:27 UTC, ztc0611 commented
Any update on this? Since I was silly and didn't correctly branch from master, it means I can't submit my other PR about re-adding the center window function.

2022-09-11 05:24 UTC, Chaosus requested changes

2022-09-11 05:24 UTC, Chaosus commented on core/string/ustring.cpp
> +		if (operator[](i) == 91) {
No need to use numbers instead of characters:

```suggestion
		if (operator[](i) == '[') {
```

2022-09-11 05:24 UTC, Chaosus commented on core/string/ustring.cpp
> +				if (operator[](j) == 93) {
```suggestion
				if (operator[](j) == ']') {
```

2022-09-11 05:24 UTC, Chaosus commented on core/string/ustring.cpp
> +				} else if (operator[](j) == 91) {
```suggestion
				} else if (operator[](j) == '[') {
```

2022-09-11 12:40 UTC, Chaosus commented
> Any update on this? Since I was silly and didn't correctly branch from master, it means I can't submit my other PR about re-adding the center window function until this one is gone.

Accepting the pull request is a random process - sometimes it takes years to be accepted, in general if you have such problem - there is no shame to close the PR and then re-open a fixed version.

2022-09-15 18:15 UTC, closed without merging