Breakpoint indicator QoL
godotengine/godot pull request #65805
Opened 2022-09-14 23:09 UTC by MewPurPur

Addresses the first two problems in https://github.com/godotengine/godot/issues/65517

Also makes the breakpoint icon a little brighter when a it is toggled and hovered.

2022-09-15 14:46 UTC, MewPurPur commented
(don't merge yet, found a small regression)

2022-09-15 14:59 UTC, KoBeWi commented
(t's not even approved)
(also you can mark it as draft)

2022-09-15 17:18 UTC, YuriSizov commented
We can mark it too, I just thought MewPurPur was about to ninja-fix that regression 😛

2022-09-15 21:42 UTC, MewPurPur commented
I was gunna, got caught up in work though~

2022-09-19 13:02 UTC, Paulb23 requested changes

2022-09-20 20:08 UTC, MewPurPur commented
Reverted some of the changes, now it only addresses the horizontal discrepancy. I'm not sure how to properly fix the vertical discrepancy.

2022-09-27 15:44 UTC, MewPurPur commented
Added the lightening for bookmarks too :)

2022-10-09 17:03 UTC, Paulb23 approved these changes

2022-10-09 17:23 UTC, akien-mga commented
Needs rebase to fix godot-cpp build.

2022-10-10 08:04 UTC, merged

2022-10-10 08:05 UTC, akien-mga commented
Thanks!