Add DisplayServer Window Center functions
godotengine/godot pull request #65843
Opened 2022-09-15 19:37 UTC by ztc0611

Re-Adds an equivalent to 3.x's `OS.center_window()`, which was lost in the DisplayServer refactoring.

Testing is required for Windows and Linux, I only have a Mac.

Issue: Dragging the window to a different monitor then centering it places the window always on my second (bigger) monitor, but uses the size of whichever one the window was on for centering. I am unsure if this is caused by my function having an error, or a quirk of how `DisplayServer.window_set_position()` works. I attempted to set the window's current screen to be the screen it is on prior to setting the position, but this had no effect so I removed it.

Test project, press space to center the window.
[DisplayServer Center.zip](https://github.com/godotengine/godot/files/9578435/DisplayServer.Center.zip)

Closes https://github.com/godotengine/godot-proposals/issues/5232.

2022-09-16 05:53 UTC, bruvzg requested changes, later dismissed
I would also add `p_screen` as an argument to these functions (with default value of `0`), instead of always using `0`, it might be useful to center windows on any screen.

2022-09-16 05:53 UTC, bruvzg commented on platform/linuxbsd/display_server_x11.cpp
> +	Point2i position = screen_size / 2 - window_size / 2;
```suggestion
	Point2i position = screen_get_position(0) + screen_size / 2 - window_size / 2;
```

Window position is in "virtual desktop" coordinates, which always starts at `(0, 0)`, but screen `0`, is not necessary at the `(0, 0)` coordinates, therefore screen position should be taken into account (same for all functions / platforms).

e.g., if you have screens configured like this, `(0, 0)` (marked with ❌) is outside any screen:

<img width="397" alt="Screenshot 2022-09-16 at 08 44 56" src="https://user-images.githubusercontent.com/7645683/190565715-5559437c-5226-4a1b-bdcf-2b20e8398044.png">

2022-09-16 14:26 UTC, ztc0611 commented
Shouldn't there be a way to just tell it to center the window on the current screen as well? Having to do DisplayServer.window_set_centered(DisplayServer.window_get_screen(),0) to do that seems janky.

2022-09-19 17:49 UTC, ztc0611 commented
@bruvzg Just to make sure I understand, Windows and MacOS also need the exact same virtual desktop coordinate addition, correct? And I should just go ahead and make it include a screen argument that defaults to 0? If so, should the window ID or the screen ID come first in the function? Just want to make sure I do this correctly.

2022-10-30 14:02 UTC, ztc0611 commented
I believe that I implemented the feature correctly now, anybody willing to check these on Linux and Windows?

2022-10-30 18:32 UTC, paddy-exe commented
> I believe that I implemented the feature correctly now, anybody willing to check these on Linux and Windows?

Tested on Windows. It works. However I have a two-monitor setup and I had the editor screen on the left side when running and when centering the window it automatically always centered it on the right screen

2022-10-30 18:56 UTC, paddy-exe commented
Okay this seems to work fine for both monitors. I am just confused that p_screen on 0 is my right screen and 1 is my left screen when my system settings are like this:
![image](https://user-images.githubusercontent.com/38077837/198896473-8b6cc69e-b0fe-4017-987d-fd97de093b27.png)

2022-11-02 01:55 UTC, ztc0611 commented
Corrected merge conflict.

2022-11-02 07:05 UTC, bruvzg reviewed
I not sure is there's any use for `window_is_centered`. `window_set_centered` seems fine.

2022-11-02 07:05 UTC, bruvzg commented on platform/macos/display_server_macos.mm
> +	return (window_get_position(p_window) == position);
This won't reliably work, the result might be (and almost always is) off by one pixel due to rounding errors.

2022-11-02 07:08 UTC, bruvzg commented on platform/macos/display_server_macos.mm
> +	return (window_get_position(p_window) == position);
This might be a result of macOS hiDPI scaling.

2022-11-02 13:24 UTC, ztc0611 commented
When writing the 3.x -> 4.0 migration guide, it must be noted that this new function does not operate as it did in 3.x, in which it centered the window on its current screen. 

I still am concerned about how unintuitive this can be, especially for people with only one monitor. I'm not sure why someone would want the default behavior to be for the function to cause the window to jump monitors. Usually this seemed to be used for resizing the window in game settings in 3.x and keeping it centered, which shouldn't care where the user drags the window.

2022-11-03 03:04 UTC, ztc0611 commented
Just had a very strange error.

Github began claiming that `platform/linuxbsd/display_server_x11.cpp` and `platform/linuxbsd/display_server_x11.h` had merge conflicts with `master`, but Git did not. Trying to rebase to `origin/master` using Git on my computer was causing an issue where it wouldn't properly sync with `master` and forcing it to would amend some unrelated commits to say they were done by me. After me retrying about 4 times it randomly corrected itself but I started getting "unicorn errors" while trying to view this page or anything related to this commit. 

Hopefully nothing is permanently messed up here and it's just Github's servers being rocky.

2023-04-27 21:01 UTC, Calinou commented
The name `set_centered()` feels odd to me, as you're not setting a boolean value. I think `window_center()` would make more sense.

2023-04-28 02:49 UTC, ztc0611 commented
> The name `DisplayServer.window_set_centered(...)` feels odd to me, as you're not setting a boolean value. I think `DisplayServer.window_center(...)` would make more sense.

Yeah, in retrospect it is pretty weird. I guess it made more sense when it had a checker (window_is_centered) as an alternative. I’ll alter that soon.

I am still concerned about the behavior as directed in which executing this function centers the window on the primary monitor of the computer, vs centering it on whichever monitor the window is currently open on. 

I would imagine the most common use case of this would be for centering the window while resizing it in a settings menu, and it would be annoying if the user had dragged the window elsewhere and it kept snapping back to Display 1.

2023-04-28 20:50 UTC, Calinou commented
> I am still concerned about the “default” behavior as directed in which executing this function centers the window on the primary monitor of the computer, vs centering it on whichever monitor the window is currently open on.

I think the default should be to center on the current monitor.

2023-04-30 20:36 UTC, ztc0611 commented
Updated test project.

[DisplayServer Center.zip](https://github.com/godotengine/godot/files/11362258/DisplayServer.Center.zip)

2023-05-06 01:09 UTC, Calinou commented on doc/classes/DisplayServer.xml
> +				Centers the window on the screen.
```suggestion
				Centers the window on the screen the window is currently on.
```

2023-05-06 01:10 UTC, Calinou approved these changes
Should be good to merge after applying suggestions and squashing.

2023-05-06 15:15 UTC, ztc0611 commented
Will this be in a 4.0.x or will it be held until 4.1?

2023-05-06 17:36 UTC, aaronfranke commented
@ztc0611 Most new features will only go in the next minor release. The cherry-picks to stable branches are for bug fixes and other minor things. However, the plan is for 4.1 to be out within a few months, so it will be in a stable version soon if it's accepted in time.

2023-06-16 01:20 UTC, ztc0611 commented
Changes pushed.

2023-06-16 07:25 UTC, akien-mga commented
> Edit: Why is the spell check failing for code unrelated to what I added? I'm caught up to master.

It's now fixed in `master`, rebasing should solve it.

2023-06-26 17:18 UTC, ztc0611 commented
> It's now fixed in `master`, rebasing should solve it.

Worked.

2023-07-05 14:10 UTC, ztc0611 commented
Are there still changes that I need to make?

2023-08-07 19:15 UTC, fire commented
@bruvzg can you take a look?

2023-08-08 07:13 UTC, bruvzg reviewed
Code seems fine. But I'm not sure if there is any point to have a function that can be replicated with a few lines of GDScript.

2023-08-08 09:17 UTC, produno commented
> Code seems fine. But I'm not sure if there is any point to have a function that can be replicated with a few lines of GDScript.

If that is the case then that probably should have been mentioned before time and effort was spent on the pr from @ztc0611. I cant imagine it brings confidence in wanting to do more pr's in the future.

This function was present in 3.x so I think most people would expect it to be in 4.x. Especially if they are coming from 3.x.

Almost every game that allows the resolution to be changed whilst not in full screen will use this function.

2023-08-08 14:53 UTC, ztc0611 commented
The more friction put between basic function and what people will want to do, the less likely it is that it will be implemented. If everyone has to do this manually, I predict many games that allow resolution changing will not center the window. "Bugs" like this, no matter how unfair it is, will not reflect positively on the engine, in my opinion.

All that being said, I do agree with @produno that if you never wanted the function to reappear in 4.x I wish you would have said so before asking for numerous revisions. They weren't exceptionally time consuming, but it's the principle of the matter.

2023-08-09 12:42 UTC, bruvzg commented
> All that being said, I do agree with @produno that if you never wanted the function to reappear in 4.x I wish you would have said so before asking for numerous revisions. They weren't exceptionally time consuming, but it's the principle of the matter.

To be clear, I'm not against merging it, just pointing out that this function is not strictly necessary.

2023-08-09 13:31 UTC, reduz commented
This discussion is very strange to me. Why do you need this on DisplayServer? 
- It means adding code to every single platform for something that is not strictly platform specific.
- Users would not be able to use it anyway since in Godot 4 you use Window instead.

Does it not make more sense to just add the function to Window?

2023-08-09 13:51 UTC, closed without merging

2023-08-09 13:53 UTC, reduz commented
@ztc0611 Sorry also that you lost so much time with this, It looks like we should have documented this better and you had the misfortune of bumping into some area of the engine where there was not much clarity for those involved, so many of us did not quite understood the purpose of this PR nor were able to give good feedback as a result.

2023-08-09 15:21 UTC, produno commented
> Okay I think there is a very big misunderstanding here, so I apologize.
> 
> To clarify, in Godot 4, DisplayServer is not meant to be used directly. You have to do window management in the Window class. This is a failure of documentation I guess as many Godot 3 users try to migrate to use DisplayServer directly and this is not ideal. The fact that many contributors in this thread were not aware of this either shows that from the project we did a bad job at communicating this change.


Yep, i never knew this and all searches seem to point to using DisplayServer, so it seems to be a very common issue.

Does this also mean mentions of it in the documentation like ```Note: This property is only read when the project starts. To change the V-Sync mode at runtime, call DisplayServer.window_set_vsync_mode() instead.``` are also incorrect?

2023-08-10 07:56 UTC, reduz commented
@produno Probably that is OK to use on DisplayServer, I meant more anything regarding to window management.

2023-08-28 10:18 UTC, akien-mga commented
Superseded by #81012.