AnimatedSprite: Preserve frame elapsed time when toggling `playing`
godotengine/godot pull request #65986
Opened 2022-09-17 13:50 UTC by Mickeon

Sometimes, **AnimatedSprite**s require pausing, whether it be for special effects, stylistical purposes, or just for the sake of it. However, there is no way to preserve the elapsed time between one frame and the next in a "nice way".  Certainly, you can actively stop internal processing, or set `speed_scale` to **0.0** which, until a while ago, wasn't even documented. 

Trying `stop()` resets it, and setting `playing` to false does the same thing. For the latter, it can be said that the animation really should only just pause and resume back where it left off. This oddity is especially noticeable for really slow animations.

This PR attempts to get rid of this oddity by preserving the current frame's elapsed time when `playing` is toggled off.

Calling `stop()`, changing animation or frames still resets the frame's elapsed_time.

2022-09-17 14:58 UTC, TokageItLab commented
I remember a similar discussion about this in AnimationPlayer about whether to implement pause(). pause() is included in #65609, but I think we need to carefully consider that as well.

2023-01-04 14:54 UTC, KoBeWi approved these changes
Aside from the signal concern it looks ok.

2023-01-04 15:10 UTC, TokageItLab commented
I wonder whether set_playing() should be exposed to the public in the first place. Perhaps this was implemented in Inspector instead of putting a play button on the SpriteEditor like AnimationPlayerEditor.

I suggest we should consider making set_playing() private and adding a method like pause() or resume() as described above with add play/pause/stop button to SpriteEditor.

2023-01-04 15:18 UTC, TokageItLab requested changes
Perhaps @Mickeon wants this PR as a hack to fulfill https://github.com/godotengine/godot/pull/66219#issuecomment-1254108290, but as I said in https://github.com/godotengine/godot/pull/66219#issuecomment-1254133544, the proper way is to make sure the seek is done correctly with setter/getter of the playback position.

2023-01-04 15:18 UTC, KoBeWi commented
But `set_playing()` is a setter for the property.

2023-01-04 15:23 UTC, TokageItLab commented
It would be okay to get `is_playing()`, but the `playing` property should be written only with some playback methods such as `play()`, `stop()`. Exposing the `playing` property is not consistent with `AnimationPlayer`.

2023-01-05 02:00 UTC, TokageItLab commented
I sent https://github.com/godotengine/godot-proposals/issues/6043. It will supersede this PR.

2023-01-27 10:08 UTC, closed without merging

2023-01-27 10:14 UTC, akien-mga commented
Superseded by #71907.