Expose in builtins' members internal type & size (on top of offset) in extension_api.json
godotengine/godot pull request #65990
Opened 2022-09-17 15:43 UTC by touilleMan

fix #64189

(replaces #64365 that was incorrectly based on a branch own by `godotengine/godot` instead of `touilleMan/godot`)

2022-09-26 15:11 UTC, touilleMan commented
@akien-mga rebased

2022-10-11 08:04 UTC, reduz commented
I don't entirely understand the need for this, can't this information be inferred from the existing json?

2022-10-30 09:12 UTC, touilleMan commented
@reduz see #64189

*tl;dr:*

currently `float` in `gdextension_api.json` means different things (e.g. in `float_32` config, `Vector2` type contains `float` fields that are 4bytes, where the `float` builtin type is 8bytes long).

This makes sens from GDScript point of view (given `foo = 0.1` and `foo = Vector2(0.1, 0).x` both return the same real variant. 

However it is misleading in GDExtension where providing a parameter with the wrong size means memory corruption 😄 

Currently to know that Vector2 is composed of 4bytes long floats, one has to do arithmetic with builtin total size per-field offset information...

On top of that it's easy to jump to the conclusion that "`float` builtin is 4bytes long, builtin fields are 4bytes long on config float_32/64 and 8 bytes on double_32/64"... then missing the fact Color's `float` fields are always 4bytes long !

So this PR provide a `meta` field for the builtins attribute that works exactly like the `meta` field already existing for classes methods' parameters.

2022-11-12 19:17 UTC, touilleMan commented
rebased ;-)

2022-12-15 11:36 UTC, groud requested changes
We reviewed this PR during the GDextension PR review meeting. The feature seems fine and useful, though we are not sure the "size" field is, as the size itself could be inferred from the type's size provided in the meta field.

The PR should be split into two, one with the "meta" field which was approved, and maybe another with the size if we find use case where that would be useful.

2022-12-15 11:44 UTC, touilleMan commented
@groud Updated to remove the `size` field ;-)

2022-12-15 13:22 UTC, groud approved these changes

2022-12-19 15:29 UTC, merged

2022-12-19 15:29 UTC, akien-mga commented
Thanks!