AnimatedSprite: Do not always reset `frame` on animation switch
godotengine/godot pull request #66219
Opened 2022-09-21 15:48 UTC by Mickeon

Somewhat related to https://github.com/godotengine/godot/pull/65986 tackling a similar issue.

### Something that has bothering me for a bit:

Say, we have two almost identical animations in our **SpriteFrames** resource, `run`, and `run_hurt`. I want to dynamically switch between two as they're in motion. This means I want to change **only** the `animation`, but even by doing this, without calling `play()`, resets _everything_ back from the start. This is typically no issue, but it is in this decently common case. While `frame` can be set back to what it was, there's no way to set the elapsed frame time manually _(nor an actual need to in most cases)_. This causes the animation to play unexpectedly, which is especially noticeable the slower it is.

The odd thing here is that changing `animation` manually behaves almost exactly like `play("different_animation")`, which really feels like shouldn't be the case. **Only** the animation should change. I can only speculate it is done this way is to improve usability in the Editor.

#### Furthermore, as a consequence of the pieces of code responsible for this, another oddity is present:
If you set your animation to play in reverse, then call `play()` at frame **0**, the elapsed frame time is reset, as if the animation began from scratch. Typically, `play()` doesn't do anything if the animation is already playing, so what if you didn't intend to do that?

--------------------------
In this PR, changing `animation` resets `frame` & the _elapsed frame time_ only if the new animation doesn't have enough frames to sustain it, and is also dependent on the animation direction.

`play()` always resets `frame` if the `animation` successfully switches. In the Editor, for usability reason, the previous behaviour is retained.

Applies to both **AnimatedSprite2D** and **AnimatedSprite3D**.

###### _Also tweaks an ERR_FAIL_COND_MSG._

2022-09-21 17:57 UTC, TokageItLab commented
Also, this method is not safe for animations with different frame lengths.

In my opinion, probably the right way to deal with your case without using AnimationTree would be to open a proposal to implement something like Skin feature in AnimatedSprite.

2022-09-21 18:08 UTC, Mickeon commented
I do not believe this to be as situational or "advanced" as thought, but that would require a proposal for this to say.

> Also, this method is not safe for animations with different frame lengths.

It is. `frame` is clamped appropriately.

2022-09-21 18:16 UTC, TokageItLab commented
No errors are not equal to being safe. It means adding checks that are not normally needed for specific cases. Although @reduz says that changes should be minimal to ensure the required behavior, this change looks more like a makeshift than a properly work-around.

2022-09-21 18:55 UTC, TokageItLab commented
Again, I recommend a suggestion to the Skin feature to resolve this comprehensively.
But alternatively, as a compromise I can agree for now is to publish a getter that returns the internal time of the AnimatedSprite.

2022-09-21 19:01 UTC, Mickeon commented
I feel like this is misunderstanding the issue. What would at least "mitigate" it is a **setter** for the elapsed frame time, not a getter:

> [...] resets _everything_ back from the start. This is typically no issue, but it is in this decently common case. While `frame` can be set back to what it was, there's no way to set the elapsed frame time manually _(nor an actual need to in most cases)_. This causes the animation to play unexpectedly [...]

2022-09-21 19:05 UTC, TokageItLab commented
Okay I see. Setters are also acceptable if implemented correctly. In short, the following are correct what is needed, correct?

- Implement a setter and getter that changes the internal playback position with a float value, since the `frame` property is not sufficient for seamless Skin switching

2022-09-21 19:21 UTC, Mickeon commented
It's not really the internal playback position, it's more like the "countdown time it takes for the current frame to switch to the next one to the next one", but yes, in away, that would mitigate this case. I am concerned that a method for this is actually more situational than this PR and potentially clutters the class.

2022-09-21 19:25 UTC, TokageItLab commented
I guess you just need to calculate the timeout at the setter and getter depends on frame length. But, do not forget the possibility that #65609 needs to be considered with respect to the length of the frame.

2023-01-04 15:51 UTC, TokageItLab approved these changes
~~Approved in the previous animation meeting. Breaks compat, should probably be mergeable, reduz' feedback doesn't seem like a blocker.~~

2023-01-04 15:51 UTC, TokageItLab requested changes
Sorry, above approve is mistake...

2023-01-04 17:28 UTC, reduz commented
@Mickeon If nobody complained except you, then this means the default behavior should not change. If this is wanted and it makes sense as a feature, it should be an optional mode.

2023-01-27 10:08 UTC, closed without merging

2023-01-27 10:14 UTC, akien-mga commented
Superseded by #71907.