Replace single quotes by double quotes in HTML files
godotengine/godot pull request #66291
Opened 2022-09-23 09:42 UTC by Mickeon

Revival of https://github.com/godotengine/godot/pull/48488.

Also tidies up comments and header markups.

If the original PR could be cherrypicked for 3.x, I don't see why not this one, as well.

2022-09-23 13:33 UTC, jcostello commented
Any reason to use double quote vs single?

2022-09-23 13:56 UTC, Faless commented
> Any reason to use double quote vs single?

We should in fact use single quotes and not double quotes, which is consistent with the current JS style in `platform/web/js/`.

That said, I would only do that if we can enforce it with `eslint` like we do for the rest of JavaScript code.
There seem to be [a plugin for that](https://www.npmjs.com/package/eslint-plugin-html), if that works we should be able to add html files formatting to `platform/web/package.json` so it gets checked in CI (and can be auto-formatted).

2022-09-23 14:03 UTC, Mickeon commented
Do I rebase this PR to be entirely single-quoted first or are there some exceptions to it (such as attributes)?

2022-09-23 14:16 UTC, Faless commented
@Mickeon I would start by just doing the JS part, but again, do so using `eslint` auto-formatting. Then, if `eslint` can auto-format the html/css too, we can decide which rule we prefer (I think double quotes for HTML attributes is more common.)

2022-09-23 15:11 UTC, Mickeon commented
For now I've inverted the PR. I do not have ESLint on this machine and I don't know an easy way to validate the files, nor the environment(s) to choose for this,

2022-09-23 15:35 UTC, aaronfranke commented
If you want to get technical, there is an objectively superior quote in JavaScript (ECMAScript 6 or later), though it's neither of the characters we are used to from other languages:

```js
var world = `World`;
var hello = `Hello ${world}!`;
```

2022-09-23 15:38 UTC, Mickeon commented
Oh yeah, I'm aware. I'd only use it whenever String concatenation is necessary, however, not across the entire codebase.

2022-09-24 09:32 UTC, Faless requested changes
As said, this really needs to be automated with `eslint` and checked in CI to make sense, otherwise is just noise.

2022-09-24 09:33 UTC, Mickeon commented
EsLint gives me a choice of environments, which one should I check the files with?

2022-10-11 10:31 UTC, Mickeon commented
@Faless Refactored this entire PR to use EsLint.

2022-10-11 11:47 UTC, Faless commented
> @Faless Refactored this entire PR to use EsLint.

I'm sorry but this is still wrong.
First, there is no esconfig attached, nor the proper plugin and commands have been added to `package.json`,
secondly, I thought this was started to format the JavaScript code inside the HTML, while now it's only formatting the HTML and not the JS.

2022-10-12 07:01 UTC, closed without merging

2022-10-12 07:01 UTC, akien-mga commented
Superseded by #67258.