Split script navigation state and edit state
godotengine/godot pull request #66300
Opened 2022-09-23 12:52 UTC by KoBeWi

Right now when you move in script editor history, the editor will store everything, including bookmarks, breakpoints and current highlighter. This actually leads to some bugs, e.g. old bookmarks can be restored if you go back to previous script.

This PR adds a navigation state, which is a subset of script edit state. Script editor history will use it instead.

Helps #63515

2022-09-25 09:52 UTC, Paulb23 requested changes
Not a fan of duplicating this code.

Could we get rid of `set_navigation_state` and use `set_edit_state`. Then make `get_edit_state` use `get_navigation_state`.

2022-09-25 21:10 UTC, KoBeWi commented on editor/plugins/script_editor_plugin.cpp
> +		Ref<Script> script = seb->get_edited_resource();
This is not necessary after removal of `set_navigation_state()`, but it's probably a nice refactor.

2022-10-04 18:26 UTC, Paulb23 approved these changes

2022-10-05 07:00 UTC, merged

2022-10-05 07:00 UTC, akien-mga commented
Thanks!