Add GDScript template to RichTextEffect
godotengine/godot pull request #66600
Opened 2022-09-29 13:40 UTC by RedMser

Since RichTextEffect requires a very specific setup, it makes sense to include this as the default script template.

Sadly `_CLASS_` uses the file name's capitalization, so the `class_name` doesn't follow PascalCase. It might make sense to introduce more placeholders for different casing.

2023-02-10 16:20 UTC, YeldhamDev requested changes

2023-02-10 16:20 UTC, YeldhamDev commented on modules/gdscript/editor/script_templates/RichTextEffect/default.gd
> +
Extra blank lines are need at the start and end of this section.

2023-02-10 17:24 UTC, YeldhamDev requested changes

2023-02-10 17:24 UTC, YeldhamDev commented on modules/gdscript/editor/script_templates/RichTextEffect/default.gd
> +var bbcode = "_CLASS_"
```suggestion
var bbcode := "_CLASS_"
```

2023-02-10 17:24 UTC, YeldhamDev commented on modules/gdscript/editor/script_templates/RichTextEffect/default.gd
> +	var param = char_fx.env.get("param", 1.0)
```suggestion
	var param: float = char_fx.env.get("param", 1.0)
```

2023-02-10 18:15 UTC, YeldhamDev approved these changes

2023-04-18 12:03 UTC, YuriSizov commented
Class name should go before extends according to our style guide. So I changed that and rebased on your behalf.

2023-04-18 12:42 UTC, merged

2023-04-18 12:42 UTC, YuriSizov commented
Thanks!