Fix C# delegate signal not disconnected when Object is destroyed
godotengine/godot pull request #66674
Opened 2022-09-30 17:23 UTC by pkdawson

Fixes #66319

This just implements a TODO comment by neikeq, which helpfully described the solution to a bug I encountered:
https://github.com/godotengine/godot/blob/56563ef09e779b9f4b105fea0e5a1a8e59c7cfe8/modules/mono/managed_callable.cpp#L82

If the delegate target is an Object, the connected signal will be registered in that object instead of the middleman. So when that object is destroyed, the signal will be properly disconnected.

This is quite a simple change, but it needs to touch a lot of files to pass along the additional parameter.

2022-09-30 19:16 UTC, neikeq commented
I'll be reviewing this later, but from a quick look, the delegate target is not necessarily a Godot Object. It can be any type.

2022-09-30 19:20 UTC, pkdawson commented
> I'll be reviewing this later, but from a quick look, the delegate target is not necessarily a Godot Object. It can be any type.

Right, that's why I used the "as" operator, so if it's not a Godot.Object the target just becomes null. Then the middleman will still be used.

I did test this with static methods, and methods on non-Object classes, and that still works fine.

2022-09-30 19:31 UTC, neikeq commented
My bad, I did not read this well. Can you include this part in the commit message?:

> If the delegate target is an Object, the connected signal will be registered in that object instead of the middleman. So when that object is destroyed, the signal will be properly disconnected.

2022-09-30 19:40 UTC, neikeq requested changes

2022-09-30 19:40 UTC, neikeq commented on modules/mono/managed_callable.h
> +	ManagedCallable(GCHandleIntPtr p_delegate_handle, ObjectID p_object);
For clarity:

```suggestion
	ManagedCallable(GCHandleIntPtr p_delegate_handle, ObjectID p_object_id);
```

Same for all other occurrences in this PR.

2022-09-30 19:40 UTC, neikeq commented on modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/Marshaling.cs
> +                ulong objectId = p_managed_callable.Target?.GetInstanceId() ?? 0;
For performance, it's better to pass the object pointer to the native function and get the instance id from there:

```suggestion
                IntPtr objectPtr = p_managed_callable.Target != null ? Object.GetPtr(p_managed_callable.Target) : IntPtr.Zero;
```

2022-09-30 22:46 UTC, kleonc commented on modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.cs
> +            _target = @delegate.Target as Object;
The passed in `@delegate` can be `null`.
```suggestion
            _target = @delegate?.Target as Object;
```

2022-10-02 17:22 UTC, neikeq approved these changes

2022-10-02 17:23 UTC, merged

2022-10-02 17:23 UTC, neikeq commented
Thanks!