Fix unary op warnings never showing
godotengine/godot pull request #66733
Opened 2022-10-02 00:18 UTC by MewPurPur

Fixes #66730

I have no idea what this does, I just copied stuff from the equivalent binary op function until it worked.

2022-11-30 22:58 UTC, anvilfolk requested changes
It looks good. Some nice simple refactoring, and made sure error reporting can happen by taking out an `else if` into just an `if`. Confirmed that it solves the issue and makes sense also!

Since you did some refactoring, I'd suggest making it more complete. There's an instance of it that you missed in `if (!is_type_compatible(test_type, p_binary_op->left_operand->get_datatype(), false))`, line 2150 :)

2022-12-01 00:10 UTC, MewPurPur commented
Ah, true. Doned.

2022-12-01 00:11 UTC, anvilfolk approved these changes

2022-12-11 21:33 UTC, akien-mga approved these changes

2022-12-11 21:33 UTC, merged

2022-12-11 21:34 UTC, akien-mga commented
Thanks!