Fix for issue #38009 "2D polygon indices barely visible on bright background"
godotengine/godot pull request #66796
Opened 2022-10-03 03:07 UTC by levyjonathan31

Added a black box behind the numbers to make them visible. Also increased font size.
![GodotFix1](https://user-images.githubusercontent.com/80333857/193494609-0d54d16c-2c62-47ff-96e5-f77ff88b8c68.PNG)

2022-10-03 03:53 UTC, clayjohn requested changes
The changes you included for sonar projects should not be included in the PR. You;ll have to remove them and update the PR, we have helpful instructions for doing so in the docs here: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request

When you are finished, there should only be 1 commit remaining

2022-10-03 03:53 UTC, clayjohn commented on .github/workflows/build.yml
> +name: Build
This file should not be included in the PR

2022-10-03 03:53 UTC, clayjohn commented on sonar-project.properties
> +#sonar.sourceEncoding=UTF-8
This should not be included in the PR

2022-10-03 03:59 UTC, clayjohn commented
Also note, [a PR](https://github.com/godotengine/godot/pull/60094) has already been made to fix https://github.com/godotengine/godot/issues/38009. https://github.com/godotengine/godot/pull/60094 has the benefit of using font outlines which is more consistent with what was proposed in #38009 and what is done in other areas of the editor. 

CC @Calinou to weigh in

2023-01-04 03:18 UTC, Cretezy commented
It seems like this PR doesn't take https://github.com/godotengine/godot/pull/36530#issuecomment-744750818 into account. I'll give this a shot by porting changes in https://github.com/godotengine/godot/pull/36530/files

2023-01-07 12:24 UTC, akien-mga commented
Superseded by #70902.

2023-01-07 12:24 UTC, closed without merging