Show custom data names in the tile set editor
godotengine/godot pull request #66853
Opened 2022-10-04 00:21 UTC by aligator

I noticed that the custom properties in the new tile editor have no name, just the index, even if a name is set.
I couldn't find another Issue or PR targeting this.
![image](https://user-images.githubusercontent.com/663900/193708136-b3fc6f18-c9c3-469b-88a4-2fec5c541011.png)
![image](https://user-images.githubusercontent.com/663900/193708248-f162e762-8024-4968-96e5-d045230ed9ee.png)

Which is very annoying if you have several custom properties.

This PR just changes that to show the names instead.
Currently it fall-backs to the index.

![image](https://user-images.githubusercontent.com/663900/193708173-ff11a724-d24e-474b-8f80-58db3756be31.png)

2022-10-04 08:10 UTC, groud requested changes
No, this PR is simply not working. What you did there renamed the property only in the property list, but does not modify the `_get` and the `_set` functions setting those properties.

But this is a bad idea anyway, those properties are ordered in a table with the same amount of element as the number of custom data layers, and it is important that the TileSet's custom data layer count and the TileData custom data properties stay the same, and this is a lot easier to do with numbered properties than with named properties.

As a consequence, the internal names of the properties should not change, only their displayed name in the inspector.

2022-10-04 16:32 UTC, aligator commented
Thanks for your review.

> What you did there renamed the property only in the property list, but does not modify the _get and the _set functions setting those properties.
My intention was not to change the id, but to change the display name. 
It actually felt wrong...  
However I could not find another way to set the displayed name.

I think I have to dig deeper in the codebase to understand this properly.

2022-10-04 23:14 UTC, aligator commented
@groud 
After some experimentation, I realized, that (if I don't miss something) the current PropertyInfo cannot hold information about an alternative display name. 
The only way I can think off would be to use a new PROPERTY_HINT_ with the hint_string, but that would prevent the usage of any other PROPERTY_HINT_ (which would be no problem in the current case as it's not used there, yet.). Also I am not sure if the hint was meant for something like this...

Do you have any other idea? Or do I miss something completely?

2022-10-05 08:17 UTC, groud commented
> After some experimentation, I realized, that (if I don't miss something) the current PropertyInfo cannot hold information about an alternative display name.

Yeah, that's the main problem. I see two solutions:
1) Modify PropertyInfo by adding an "alias" property that would be used to display properties with a different label. This is not complicated, but would mean modifying the core for something quite specific. But it may be useful in other areas, so it could be worth.
2) Implement an EditorInspectorPlugin to override the way those properties are displayed. It may be a lot of code though.

2022-10-05 18:25 UTC, aligator commented
Actually I was a bit surprised that the PropertyInfo does not allow for something like this. That's why I initially thought it cannot be that hard to display custom titles^^

I pushed 1. as POC.
I think it is a good solution, as I don't think the alias is very specific to the current case but may be useful for other things too. However that's nothing I can decide as it must be discussed with the core team. Maybe there is a specific reason that an alias is missing, or maybe it just wasn't needed yet as there is no other that generic feature which allows setting the name... 

Not sure if for something so basic like setting a display name, a new EditorInspectorPlugin, which introduces some new complexity, is the better way.

However I will try to look into 2., too. However I have not looked into how to build an EditorInspectorPlugin, yet. I am quite new to the codebase, so I am not sure if I will be successful :-)

2024-04-25 13:27 UTC, berarma commented
This would actually make the tile set editor much more readable when using many custom data fields.

Using the name of the property as an internal index instead of using an actual internal index sounds like the issue. Creating an alias is a solution but it's confusing. As a core feature, I think it should use more clear field naming. Something like `id` or `index` for the internal index and `name` for the display.

2024-04-28 15:47 UTC, IkutiDev commented
@groud Has there been decision whether this way of adding alias to PropertyInfo is the way to go? Or it needs to be done with EditorInspectorPlugin?
I will be giving a go with the project using this PR and I will try to report here any possible issues the PropertyInfo change might have.

2024-04-29 09:51 UTC, groud commented
> @groud Has there been decision whether this way of adding alias to PropertyInfo is the way to go? Or it needs to be done with EditorInspectorPlugin?

Not really. I'd say the PropertyInfo change is probably the easiest solution to implement but it's quite a core change. It might not be accepted, IDK. I'll ask maintainers.

2024-04-29 12:21 UTC, IkutiDev commented
@groud Sounds promising! Are you planning on creating a plugin for this or is it currently open for anyone to give it a shot? (I could try, but completly newish to the whole source editing and only basic c++ knowledge).
Also does it need to be a whole new plugin or can it be just an edit/addition to tile_set_atlas_source_editor.cpp?

2024-04-29 12:25 UTC, groud commented
> @groud Sounds promising! Are you planning on creating a plugin for this or is it currently open for anyone to give it a shot? (I could try, but completly newish to the whole source editing and only basic c++ knowledge).
Also does it need to be a whole new plugin or can it be just an edit/addition to tile_set_atlas_source_editor.cpp?

You can give it a try, I haven't planned to work on it now. 

I guess the code could lie in tile_set_atlas_source_editor.cpp, but you need to check how other editors implement it. You can look for classes that extend `EditorInspectorPlugin` in the codebase.

2024-05-24 17:07 UTC, closed without merging