Added custom node export
godotengine/godot pull request #67055
Opened 2022-10-07 22:31 UTC by GuilhermeGSousa

Small draft PR that aims to implement #4785. I've been testing it for a while and it has been quite a handy feature, here is a small demo:
![node_export](https://user-images.githubusercontent.com/13313321/194670736-d9fd5a67-d819-4ef0-b28c-6fa6633ba169.gif)

Test Export node script
```gdscript
extends Node

@export var x : TestClass
```

Test Class node script
```gdscript
extends Node

class_name TestClass
```

Many other PRs have paved the way so that this feature shouldn't be too hard to implement. Currently only the selection using the scene tree popup is done here, the drag/drop of a node of a specific custom class isn't done yet. I'll update this draft once I have it implemented correctly.

2022-10-08 09:07 UTC, GuilhermeGSousa commented
Ok drag/drop is in there as well now. The https://github.com/godotengine/godot-proposals/issues/4785 proposal wasn't really approved yet so I'll leave this PR as a draft for now. Let me know if you see anything missing here or if you want me to un-draft it.

2022-10-08 16:26 UTC, GuilhermeGSousa commented
Just realized that according to #62916 exported typed arrays are currently broken (and confirmed on beta 2 while testing these changes), so I don't think there is much more to add to this PR. 

[#4785](https://github.com/godotengine/godot-proposals/issues/4785) wasn't approved yet so I'll leave this PR as is, but let me know when you want me to "undraft-it" or if I should add anything else to it.

2022-10-08 16:31 UTC, akien-mga commented
> [#4785](https://github.com/godotengine/godot-proposals/issues/4785) wasn't approved yet so I'll leave this PR as is, but let me know when you want me to "undraft-it" or if I should add anything else to it.

If it's ready it doesn't need to have draft status. Proposals are not always formally approved before approving a matching PR, sometimes we cut corners :)

2022-10-14 12:54 UTC, GuilhermeGSousa commented on editor/editor_properties.cpp
> +	StringName type = EditorNode::get_singleton()->get_object_custom_type_name(dropped_node);
Indeed I'll remove it

2022-10-18 12:41 UTC, mhilbrunner commented
PR review meeting: looks good at first glance, would be good if @reduz and @willnationsdev can have a look

2022-10-25 14:38 UTC, GuilhermeGSousa commented
@vnen could I get your review for this one?

2022-10-27 07:52 UTC, reduz commented
Its probably ideal that @willnationsdev reviews this at this point in the current absence of @vnen.

2022-10-28 03:47 UTC, willnationsdev commented
I just checked this out now. The basic testing I've done of the feature all seems to work just fine. However, there is an edge case that isn't accounted for. Not sure if it's within the scope of this PR or not though.

Say you have a `Base`, `DerivedA`, and `DerivedB`, along with an initially exported property of static type `DerivedA`. You assign a `DerivedA` node to it, but then modify the script with the property so that it exports `DerivedB` instead. Currently, the scene retains the reference to the node despite the fact that it now violates the exported property type. How do we resolve the now conflicting inheritance hierarchy? Conceptually it's simple; it should be updated with a `null` value. However, implementation-wise, I'm unsure of the best way to implement it. The scene file isn't necessarily going to be open in the Godot Editor when the script's exported property's static type hint is updated, but the Editor will need to update it (and every other scene with a now-conflicting exported node) regardless.

Exported resources should've had to deal with this for a long time already I would think. How is the scene's serialized data updated in that scenario? Can that apply here?

2022-10-28 03:49 UTC, willnationsdev requested changes
See previous comment.

2022-10-28 07:02 UTC, GuilhermeGSousa commented
@willnationsdev Good point, thought that is an issue already present with built-in type exports, I get that same behaviour if I export with type `Camera2D`, assign it then change the export type to something else like `Sprite2D`. I'd argue it could be done in another PR. 

It does seem to be managed correctly with exported custom resources though, so we should probably be able to do the same for nodes. After taking a quick look into the `editor_resource_picker` code the type seems to be checked when the `EditorResourcePicker` is updated, the same could be done for nodes.

Let me know if you want me to do that here or on a separate PR.

2022-10-29 04:30 UTC, willnationsdev approved these changes
@GuilhermeGSousa 

> Good point, thought that is an issue already present with built-in type exports, I get that same behaviour if I export with type Camera2D, assign it then change the export type to something else like Sprite2D. I'd argue it could be done in another PR.

If that edge case is already the current behavior regardless of whether the node is a scripted type or not, then it sounds like it should be dealt with by an entirely separate PR. I'm inclined to approve this one.

> It does seem to be managed correctly with exported custom resources though, so we should probably be able to do the same for nodes.

My thoughts too.

> After taking a quick look into the editor_resource_picker code the type seems to be checked when the EditorResourcePicker is updated, the same could be done for nodes.

While that might work, it wouldn't fundamentally fix the problem. That would only update inline whatever objects are opened in the Inspector. You'd have to manually click on every erroneous node in the scene, re-save the scene, and then linearly move on to opening the next erroneous scene manually. It wouldn't globally and automatically update all of the project's scene files that have corrupted data integrity.

Whatever solution we use would likely involve a pre-existing mechanism for resources to recursively update in response to changes in their dependency hierarchy relative to other resources in the project. Something like... 1) save a Script, triggers notifications on all resources depending on that Script, 2) for each of those resources, they determine whether or not *they* need to update themselves. If so, then they trigger notifications on things depending on *them*, 3) etc.

2022-10-29 12:07 UTC, GuilhermeGSousa commented
@willnationsdev sounds good, I'll open an issue for that specific case then

2022-10-31 10:10 UTC, akien-mga approved these changes

2022-10-31 10:25 UTC, merged

2022-10-31 10:26 UTC, akien-mga commented
Thanks!

2022-11-05 09:42 UTC, gelvinp commented
It looks like this isn't quite working with @tool scripts. I'm testing this to export the initial state for a node based state machine, and it's working (launching the game has the player in the correct initial state), but I'm also using `_get_configuration_warnings()` to check if the initial state is set or not, and throwing a print statement in there displays the `initial_state` variable to be `<null>`, even though it's set in the editor.