Expose unregister language & improve usability with GDExtension
godotengine/godot pull request #67155
Opened 2022-10-09 20:26 UTC by touilleMan

This PR is separated into 3 commits:
- first add `Engine::unregister_script` (currently only `Engine::register_script` is present), this is needed by GDExtension when the asked is torndown
- second modify `Engine::register_script`&`Engine::unregister_script` to return a boolean indicating the operation succeeded, this is required to know if the `ScriptLanguageExtension` instance passed in parameter can be safely freed (currently we have the choice between memory leak or segfault 😄 )
- last one add sanity checks to `Engine::register_script` to ensure we don't end up with multiple script languages using the same extension/name/type.

Of course I can remove some of the commits if you think it is not needed ;-)

2022-11-12 19:41 UTC, touilleMan commented
rebased ;-)

2022-12-08 13:13 UTC, groud requested changes
We reviewed this PR in the GDExtension meeting. Could you squash the commits together, the change is small enough ?
Also, we were wondering whether or not the two function could return an `Error` instead of a bool (I guess mostly for consistency), but if a bool if enough and `Error` would not provide more information that's not necessary.

2023-01-18 11:13 UTC, touilleMan commented
@groud I've updated the PR with your suggestions (better documentation + using Error as return value)

btw I've noticed singleton registration is pretty similar to language registration. Do you think it would be worth it for consistency to open another PR that provide `register_singleton`/`unregister_singleton `with a similar `Error` return type (instead of the current `void`) ?

2023-01-18 11:15 UTC, groud approved these changes

2023-01-18 16:33 UTC, akien-mga commented
There's some doc update needed:
```diff
diff --git a/doc/classes/Engine.xml b/doc/classes/Engine.xml
index 1a3b4f3..461ffcb 100644
--- a/doc/classes/Engine.xml
+++ b/doc/classes/Engine.xml
@@ -244,7 +244,7 @@
 			</description>
 		</method>
 		<method name="register_script_language">
-			<return type="Error" />
+			<return type="int" enum="Error" />
 			<param index="0" name="language" type="ScriptLanguage" />
 			<description>
 				Registers a [ScriptLanguage] instance to be available with [code]ScriptServer[/code].
@@ -263,7 +263,7 @@
 			</description>
 		</method>
 		<method name="unregister_script_language">
-			<return type="bool" />
+			<return type="int" enum="Error" />
 			<param index="0" name="language" type="ScriptLanguage" />
 			<description>
 				Unregisters the [ScriptLanguage] instance from [code]ScriptServer[/code].
```

2023-02-06 15:37 UTC, YuriSizov commented
Bump :)

2023-02-10 18:50 UTC, akien-mga commented
Pushed a rebase with fixed docs.

2023-02-11 13:42 UTC, merged

2023-02-11 13:42 UTC, akien-mga commented
Thanks!