Add `_get_unsaved_status()` method to EditorPlugin and implement it for script and shader editors
godotengine/godot pull request #67503
Opened 2022-10-16 17:44 UTC by KoBeWi

This PR adds `_get_unsaved_status()`. When editor is being closed, it calls this method on every plugin. The method returns a string. If the string is not empty, its content will be displayed in save confirmation dialog and the user can normally choose to save or discard. If the returned string is empty, the editor will close normally.

I implemented this method for script editor and shader editor, so unsaved scripts will now prompt on editor exit. Unfortunately you can't discard them due to #18010

Fixes #55026
Supersedes #55586

Depends on #67466

2023-04-05 14:13 UTC, KoBeWi commented
Rebased and ready for review. I did a small modification: `get_unsaved_status()` is now called when closing a scene and passes the scene path as an argument. This allows to handle built-in resources and effectively fixes #44053

2023-07-18 12:09 UTC, YuriSizov requested changes
Haven't tested, but the code looks mostly correct (left a couple of notes).

The feature itself is fine, though I think we should at some point make it more convenient to handle unsaved resources specifically. I proposed before an API that would allow plugins to mark arbitrary strings as dirty, which could be used to identify resources and any other stuff as unsaved.

But maybe we just need this new method and some kind of `_get_unsaved_files` which returns a list. This can be done in a follow-up though.

2023-07-18 12:30 UTC, YuriSizov approved these changes

2023-07-18 13:15 UTC, merged

2023-07-18 13:15 UTC, YuriSizov commented
Thanks!