Add Selection and Caret for Next Occurrence of Selection
godotengine/godot pull request #67644
Opened 2022-10-19 19:54 UTC by alfredbaudisch

Adds the bind `add_selection_for_next_occurrence` to TextEdit, with `CTRL+G` as the default shortcut, that adds a selection and a caret to the next occurrence of the current selection.

The bind and the behaviour is similar to the VS Code's "Add Selection to Next Find Match" and JetBrains' "Add Selection for Next Occurrence". It takes advantage of the multi-caret API.

Implements and closes https://github.com/godotengine/godot-proposals/issues/5621

## Usage
Define an Editor Shortcut for `ui_text_add_selection_for_next_occurrence` (default: `CTRL+G`):

![image](https://user-images.githubusercontent.com/248383/196790498-5436fb3b-c13f-47bc-9606-87276517a76c.png)

Select text and keep pressing the shortcut to select the next occurrences:

https://user-images.githubusercontent.com/248383/196789526-e01fec12-a520-462f-a94d-c2964dd40d12.mp4

2022-10-20 05:06 UTC, bruvzg reviewed
<kbd>Ctrl/Command + G</kbd> will conflict with macOS action `script_text_editor/find_next` <kbd>Meta  + G</kbd> (`Meta` and `Command` are the same key).

2022-10-20 05:49 UTC, alfredbaudisch commented
> Ctrl/Command + G will conflict with macOS action `script_text_editor/find_next` Meta + G (`Meta` and `Command` are the same key).

Any suggestion? I was thinking `ALT+G` then (at least it's the default in Rider).

2022-10-20 05:56 UTC, bruvzg commented
> Any suggestion @bruvzg ? I was thinking ALT+G then (at least it's the default in Rider).

I'm not sure. <kbd>Alt + G</kbd> is used to input `©` symbol (we already use shortcuts like <kbd>Alt + 1/2/3</kbd> which is also used for input, so it might be OK, if someone will need it is always possible to rebind it on the user side).

2022-10-20 06:14 UTC, alfredbaudisch commented on scene/gui/text_edit.cpp
> +	ClassDB::bind_method(D_METHOD("add_selection_for_next_occurrence"), &TextEdit::add_selection_for_next_occurrence);
Done!

2022-10-20 17:42 UTC, coppolaemilio commented
If this is a keyboard shortcut that exists in JetBrains or VS Code we could use their combination for mac? Not sure where I can find that info myself at the moment 😅

2022-10-20 18:09 UTC, Paulb23 requested changes
I would be tempted to swap the `ui_text_select_word_under_caret` and `ui_text_add_selection_for_next_occurrence` shortcuts to better align with other editors.

In VSCode, rather then only using the last caret, seems to check whether all carets have the same word selected before selecting the next occurrence. Though interestingly sublime and Jetbrains do only use the last caret. Not necessary need to change, but probably worth putting in the docs.

Secondly, in both VSCode and sublime, if one or more carets do not have a selection it behaves like `ui_text_select_word_under_caret` (without deselecting). Jetbrains has the same behaviour but only for the last caret.

2022-10-20 19:00 UTC, alfredbaudisch commented on scene/gui/text_edit.cpp
> +	if (has_selection(p_caret)) {
What actually should be inverted?

2022-10-20 19:00 UTC, alfredbaudisch commented on scene/gui/text_edit.cpp
> +		if (next_occurrence.x != -1 && next_occurrence.y != -1) {
Like previously, what actually should be inverted?

2022-10-20 19:02 UTC, alfredbaudisch commented
> Secondly, in both VSCode and sublime, if one or more carets do not have a selection it behaves like `ui_text_select_word_under_caret` (without deselecting). Jetbrains has the same behaviour but only for the last caret.

@Paulb23 that's a good one. I'll add the `ui_text_select_word_under_caret` behaviour to the feature, it makes sense, but it will be like Jetbrains.

2022-10-20 19:04 UTC, alfredbaudisch commented on scene/gui/text_edit.cpp
> +				select(next_occurrence.y, next_occurrence.x, next_occurrence.y, end, new_caret);
Yes, currently an overlap is caused if a caret is already there:

![image](https://user-images.githubusercontent.com/248383/197035649-7b91f10c-c77e-481e-8444-bf83e03c4a16.png)

2022-10-20 19:05 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +	if (has_selection(p_caret)) {
The `if` i.e

```suggestion
	if (!has_selection(p_caret)) {
	    return;
	}
```

makes it easier to read by reducing nesting.

2022-10-20 19:07 UTC, alfredbaudisch commented on doc/classes/ProjectSettings.xml
> +			[b]Note:[/b] Currently, this is only implemented in [TextEdit], not [LineEdit].
`[b]Note:[/b] Currently, this is only implemented in [TextEdit], not [LineEdit].` is currently into `ui_text_select_word_under_caret`: 

```
		<member name="input/ui_text_select_word_under_caret" type="Dictionary" setter="" getter="">
			If no selection is currently active, selects the word currently under the caret in text fields. If a selection is currently active, deselects the current selection.
			[b]Note:[/b] Currently, this is only implemented in [TextEdit], not [LineEdit].
		</member>
```

Shouldn't the mention to `[LineEdit]` be removed from both of them then?

2022-10-20 19:10 UTC, alfredbaudisch commented on scene/gui/text_edit.cpp
> +	if (has_selection(p_caret)) {
Thanks.

In this case this is going to be supersede by adding `select_word_under_caret` like in VSCode, ex:

```
if (!has_selection(p_caret)) {
  select_word_under_caret();
  # ...
}
```

2022-10-20 19:15 UTC, Paulb23 commented on scene/gui/text_edit.cpp
> +				select(next_occurrence.y, next_occurrence.x, next_occurrence.y, end, new_caret);
A call to `merge_overlapping_carets` should fix that :)

2022-10-20 19:20 UTC, Paulb23 commented
> I'll add the ui_text_select_word_under_caret behaviour to the feature, it makes sense, but it will be like Jetbrains. What do you think?

No strong preference, both are good. Can go with the Jetbrains approach as it's simpler for now. Can always change it later.

2022-10-21 06:32 UTC, alfredbaudisch commented
> > I'll add the ui_text_select_word_under_caret behaviour to the feature, it makes sense, but it will be like Jetbrains. What do you think?
> 
> No strong preference, both are good. Can go with the Jetbrains approach for now as it's simpler. Can always change it later.

Ok, I just implemented the JetBrains behaviour (and all other changes we talked about). The PR has also been updated with an additional example (regarding the JetBrains select word under caret behavior) and new instructions.

2022-10-21 16:40 UTC, Paulb23 approved these changes
Looks great!

2022-10-28 00:21 UTC, clayjohn approved these changes
Looks good to me and Paulb23 is the maintainer here, so let's go ahead and merge

2022-10-28 00:21 UTC, merged

2022-10-28 00:21 UTC, clayjohn commented
Thanks!

2023-11-04 20:40 UTC, PLyczkowski commented
Current implementation is missing the option to select next occurrence if it's a whole word only. To activate this is VSCode you can use this option:

![image](https://github.com/godotengine/godot/assets/7307968/20ff9ce5-1ff1-4767-ad32-36ea4d7bf3c6)

In Godot, this is ignored:

![image](https://github.com/godotengine/godot/assets/7307968/a96970ee-8dfb-40b3-8304-2220e98d51d6)