Check for a Vulkan extension before checking its features
godotengine/godot pull request #67729
Opened 2022-10-21 20:43 UTC by Riteo

For some reason AFAICT mesa reports a feature as enabled even when its extension isn't supported. The Vulkan specification says nothing aboutd this so this is technically more of a workaround, but it works.

I think that this oddity has always been present in mesa but we just got lucky by targeting features supported by all GPUs, up until variable rate shading.

Fixes #65409.

Note that this approach technically still uses `vkGetPhysicalDeviceFeatures2` in an invalid way (passing disabled extension feature structs in `pNext`), but a proper solution would require a more convoluted approach and this works fine.

2022-10-22 10:19 UTC, RandomShaper commented on drivers/vulkan/vulkan_context.cpp
> +		// feature as enabled. While this isn't in the spec, this has caused some
Now we know it's in the spec, this comment warrants a change.

2022-10-22 10:20 UTC, RandomShaper commented on drivers/vulkan/vulkan_context.cpp
> +			if (!strcmp(VK_KHR_FRAGMENT_SHADING_RATE_EXTENSION_NAME, extension_names[i])) {
It's up to you, but let me suggest using `== 0` syntax, which is more readable as equality

2022-10-22 10:21 UTC, RandomShaper requested changes
I've left a couple of little comments. Looks good otherwise.

2022-10-22 15:35 UTC, RandomShaper approved these changes
Makes sense!

2022-10-31 09:49 UTC, akien-mga approved these changes
Great work, thanks a lot for fixing this!

2022-10-31 10:25 UTC, merged