Fixed #66820
godotengine/godot pull request #67739
Opened 2022-10-22 02:01 UTC by TchnlgPsnt

Fixes error thrown when clicking on a json file in the file dock

2022-10-22 18:13 UTC, YeldhamDev commented on editor/editor_node.cpp
> +	else if (ResourceLoader::exists(p_resource, "")) {
The `else if` should go right after the bracket.

2022-10-22 19:48 UTC, Paulb23 requested changes
This change will no longer open scenes using the filedock if `.tscn` exists in the list of `textfile_extensions`. We have to give priority to the `ResourceLoader`.

2022-10-23 05:59 UTC, TchnlgPsnt commented
Is that not the desired effect of adding .tscn to the list of textfile_extensions? As I understood it, the list of textfile extensions existed for the purpose of causing those files to be editable in the script editor instead of being imported. That's why none of the default items in textfile_extensions are resource types.
![image](https://user-images.githubusercontent.com/65353062/197376511-ce8e0ee6-3163-4702-8fc3-216665ce7df6.png)

2022-10-23 07:50 UTC, Chaosus commented
Please squash the commits as required by our pipeline and amend the commit name to be correct (we don't accept names like "fixes [link]").

2022-10-23 16:30 UTC, Paulb23 commented
`textfile_extensions` do not prevent the `Resource` from being imported. They where designed as a catch all for editing (text) files that are not imported (non-resources), but are still needed as part of development.

There is nothing stopping users from adding `.tscn` to the list and nor should we prevent it, as the user may have an engine plugin to edit other filetypes. We cannot not know this, hence we need to give priority to the `ResourceLoader`. As the user shouldn't have to edit their settings every time they open different projects.

Opening items in the filesystem dock should always take you to the dedicated editor for that `Resource`, regardless of what's in `textfile_extensions`. As the dedicated editor will be specialised to edit the `Resource`, as such should be the preferred workflow.

However, there is no prevention stopping the user from opening up a `.tscn` file if they wish, directly via `ScriptEditor` menus which bypasses `textfile_extensions` checks. Though not recommended.

2023-02-13 23:04 UTC, akien-mga commented
Superseded by #72259.

2023-02-13 23:04 UTC, closed without merging