Implement 64-bit float arrays on Android.
godotengine/godot pull request #67759
Opened 2022-10-22 18:03 UTC by TechnoPorg

Fixes #67193.
This uses the same code as 32-bit float arrays, but it's with doubles instead.

2022-10-23 15:28 UTC, m4gr3d requested changes

2022-10-23 15:28 UTC, m4gr3d commented on platform/android/jni_utils.cpp
> +		} break;
I think you also need to update the mappings in `get_jni_type(...)` and `get_jni_sig(...)`

2022-10-23 15:28 UTC, m4gr3d commented on platform/android/api/jni_singleton.h
> +			case Variant::PACKED_FLOAT64_ARRAY: {
For completion, we can also add the implementation for the `PACKED_INT64_ARRAY` variant type, using `long` instead of `int`.

2022-10-23 20:07 UTC, TechnoPorg commented
I have now added support for 64-bit integer arrays and updated `get_jni_type` and `get_jni_sig`.
I've also added some lines that should allow for more flexible conversions involving long integers.
I really appreciate your reviewing this, because I unfortunately don't have access to an Android device, so I'm basically going blind 🙂.

2022-11-08 14:29 UTC, TechnoPorg commented
Rebased this PR following #67581, which contained some of the changes included here.

2022-12-17 03:00 UTC, TechnoPorg commented
@m4gr3d Sorry to bump, but would you mind taking a look at this when you have time?

2022-12-23 20:34 UTC, m4gr3d approved these changes
Looks good!

2022-12-23 22:45 UTC, merged

2022-12-23 22:45 UTC, akien-mga commented
Thanks!