Documentation of RPC-related methods and classes
godotengine/godot pull request #6779
Opened 2016-10-10 13:49 UTC by WalasPrime

Obviously RPC needs to be documented. It's surprisingly hard to do without images...
Anyway, I'm having a hard time understanding `rpc_config` and `rset_config` methods. Since we can define multiple functions with different rpc rules (master slave sync remote)... what does `rpc_config` actually do? The sourcecode seems to overwrite a method's `RPC_MODE_*`, but then again, what's the difference between this and doing `set_network_mode` to the same value?

- [x] Basic SceneTree and NetworkedMultiplayerENet connection
- [x] Describe basic rpc and rset functions
- [ ] Describe `*_config` functions

Anyway, suggestions and feedback greatly appreciated. Is the content understandable?

2016-10-13 15:59 UTC, WalasPrime commented
Done, examined the whole RPC system a little more, discovered you actually can't define the same method name multiple times (duh) with different RPC modes, so `_config` methods now make sense.

2016-10-13 19:22 UTC, bojidar-bg requested changes

2016-10-13 19:22 UTC, bojidar-bg commented on doc/base/classes.xml
> +				Change the networking mode of the [Node], where [i]mode[/i] is one of the constants NETWORK_MODE_*. Master nodes will only call gdscript methods defined as [i]master func[/i] if a RPC call is rec
Ouch, -doctool reordered the descriptions? :smile:

2016-10-13 21:39 UTC, WalasPrime commented on doc/base/classes.xml
> +				Change the networking mode of the [Node], where [i]mode[/i] is one of the constants NETWORK_MODE_*. Master nodes will only call gdscript methods defined as [i]master func[/i] if a RPC call is rec
Wow, no idea how did this get there 😮

2016-10-14 07:54 UTC, bojidar-bg commented on doc/base/classes.xml
> +				Change the networking mode of the [Node], where [i]mode[/i] is one of the constants NETWORK_MODE_*. Master nodes will only call gdscript methods defined as [i]master func[/i] if a RPC call is rec
Wait, my bad, the line numbers are incorrect indeed :/
`/me blames GitHub`

2016-10-14 07:54 UTC, bojidar-bg approved these changes

2016-10-17 07:58 UTC, merged