#67925 - update default cursor shape for javascript export
godotengine/godot pull request #67964
Opened 2022-10-28 01:36 UTC by tehsquidge

this looks to already be fixed in master: https://github.com/godotengine/godot/blob/master/platform/web/js/libs/library_godot_display.js#L177

It seems I needed to update the default shape in `$GodotDisplayCursor`  to match the changes made in 3f8830ec50ba349bed473fd55f7cbe77d266e0fa

This MR should fix #67925.

2022-10-28 05:00 UTC, clayjohn approved these changes
We just fixed the same bug in master, so this looks good to me! https://github.com/godotengine/godot/pull/67045

2022-10-28 06:57 UTC, Faless requested changes
Also requires changes in `clear` and `set_shape`. See: https://github.com/godotengine/godot/pull/67045/files

2022-10-28 09:01 UTC, tehsquidge commented
> Also requires changes in `clear` and `set_shape`. See: https://github.com/godotengine/godot/pull/67045/files

I've applied the changes

2022-10-28 11:25 UTC, kleonc commented
> I've applied the changes

@tehsquidge A single commit is preffered, please squash your commits (see: [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase)).

2022-10-28 11:34 UTC, tehsquidge commented
Thanks @kleonc

The docs are really good, I should have read them better. :stuck_out_tongue: 

I believe I've squashed my commits correctly.

2022-10-28 16:33 UTC, Calinou commented
Thanks for opening a pull request :slightly_smiling_face: 

Pull requests targeting the stable branch should be opened against the `3.x` branch instead of `3.5`.We can then cherry-pick specific bug fix PRs to the `3.5` branch.

2022-10-28 17:46 UTC, clayjohn commented
> Shouldn't we cherry-pick #67044 to `3.5` instead? Cherry-picking makes it easier to track commits across branches, instead of merging separate pull requests.

Ah, yep. I didn't realize this was already fixed in 3.x

2022-10-29 07:29 UTC, RPicster commented
One thought. My original PR that caused this regression was not merged without a good reason, too.

So if this is reverted, the other problem comes back.

Wouldn't it make sense to check if a custom cursor is used before using this behaviour? Otherwise use the behaviour I added in my PR.

That would solve both problems.

2022-10-29 13:05 UTC, tehsquidge commented
It'd make more sense to cherrypick #67044. I hadn't realised this was already fixed in 3.x/4 when I put this PR in.

My intention wasn't to revert the changes made by @RPicster - is it definitely the case that has happened? Because my PR is identical to the PR already in 3.x

2022-11-03 15:32 UTC, tehsquidge commented
I've opened a new MR to cherry-pick as suggested here #68214

I'll close this one

2022-11-03 15:32 UTC, closed without merging