Fix propagation order for 2D physics picking events
godotengine/godot pull request #68492
Opened 2022-11-10 22:07 UTC by Sauermann

This patch adds a viewport-configuration-option for sorting physics-picking events by the Z-Index of the collision objects.

resolve #23051

2023-01-31 23:13 UTC, Sauermann commented
I have updated the PR according to the discussion in the PR-review-meeting and
added sorting by the scene-tree position as a secondary comparison option.

2023-02-01 08:38 UTC, RandomShaper requested changes
The only missing piece is taking into account relative vs absolute z-indices. That may not be trivial, but otherwise the code is assuming they're absolute, which is not even the default.

2023-02-04 21:10 UTC, Sauermann commented
I have updated the PR to address relative-z-sorting

2023-02-04 21:39 UTC, RandomShaper requested changes
Looks very good. I also realized you opened this PR on my birthday! I'd just ask you to document that the setting is disabled by default because it's potentially expensive in performance. (In the future we may look into caching the effective z-index, but that's another story.)

2023-02-04 21:49 UTC, RandomShaper approved these changes

2023-02-06 14:45 UTC, merged

2023-02-06 14:45 UTC, akien-mga commented
Thanks!