Add track validator to AnimationPlayerEditor to detect tracks which have error
godotengine/godot pull request #68770
Opened 2022-11-17 06:33 UTC by TokageItLab

Fixes #64340

Unnormalized quaternion keys will cause problems in playing back animations, but it is hard to know which track has the problem just from the error `The start/end quaternion must be normalized`.

However, checking for error tracks at runtime will reduce the performance, so to notify the problematic track, the validation is run only at the moment the animation playback button is pressed in the editor.

![image](https://user-images.githubusercontent.com/61938263/202373335-5f3dd9d8-d44e-43be-bd55-8361aedb5bea.png)

2022-11-17 14:21 UTC, fire commented
Do you handle basis value tracks?

2022-11-17 14:44 UTC, TokageItLab commented
Basis does not need to be checked since basis allows skew and basis animation is not using slerp.

2022-11-17 16:56 UTC, fire commented
I think the isfinite function is useful for checking for nan and infinities.

2022-11-17 17:35 UTC, TokageItLab commented
Those invalid values will be prevented from being keyed due to errors at a previous step of the keying process. Can they be keyed when keying in a script?

For now, I think it is enough to check as long as the error occurs on keying possible in the normal operation. And, I made it stop playback to avoid spamming if there is a validation error.

2022-11-28 13:58 UTC, reduz requested changes

2022-11-28 14:36 UTC, TokageItLab commented on editor/plugins/animation_player_editor_plugin.cpp
> +		ERR_FAIL_COND_MSG(!_validate_tracks(player->get_animation(current)), "Animation tracks may have any invalid key, abort playing.");
Changed. Also I changed `ERR_BREAK_MSG` to `ERR_BREAK_EDMSG`.

2022-12-04 18:26 UTC, reduz approved these changes

2022-12-04 23:07 UTC, merged

2022-12-04 23:07 UTC, akien-mga commented
Thanks!