Fix Area node description mistake
godotengine/godot pull request #68905
Opened 2022-11-20 00:03 UTC by jaymehta-g

Change brief descriptions for Area2D and Area nodes to be less confusing.

For Area2D:
Changed
"2D area for detection and physics and audio influence."
to
"2D area for detection, physics, and audio influence."

For Area (Area3D):
"3D area for detection and physics and audio influence."
to
"3D area for detection, physics, and audio influence."

2022-11-20 02:40 UTC, timothyqiu commented
As expanded in the description, the original brief description means an area can:

* detect (other body and area)
* influence physics and audio

I think this modification changes the meaning, making "detection", "physics", and "audio influence" the same level.

2022-11-20 02:50 UTC, souplamp requested changes
"3D area for collision detection, as well as physics and audio influence."
Perhaps this wording would help emphasize the difference a bit stronger.

2022-11-20 02:54 UTC, skyace65 requested changes
souplamp's suggested change would be perfect.

2022-11-21 01:47 UTC, jaymehta-g commented
Just changed it to better reflect the separation between collision and physics/audio

I still don't know if it's accurate to call it "collision detection" since no physics collision actually happens with an Area as far as I know, should it be instead called a "collider detection"?

2022-11-21 17:08 UTC, souplamp approved these changes
> I still don't know if it's accurate to call it "collision detection" since no physics collision actually happens with an Area as far as I know, should it be instead called a "collider detection"?

Areas inherit from CollisionObject2D/3D, and they need CollisionShapes/Polygons, but I can see why that phrasing could still be confusing (implying it interacts with physics when that's not necessarily true). I think you could leave it as simply "detection" just to keep it concise, and users can read the description below for more information.

2022-11-22 00:55 UTC, skyace65 commented
I agree with souplamp again. Leaving it as "detection" is probably for the best

2023-02-07 21:27 UTC, YuriSizov commented
Bump :)

2023-02-07 22:10 UTC, jaymehta-g commented
> Bump :)

forgot about this lmao. ill change it to just "detection" and commit again

2023-02-11 03:05 UTC, skyace65 approved these changes

2023-02-11 03:06 UTC, merged

2023-02-11 03:06 UTC, skyace65 commented
Thanks! And congrats on your first merged PR!