Update docs to clarify `@icon` only works with global script classes
godotengine/godot pull request #69166
Opened 2022-11-25 13:23 UTC by souplamp

Fixes: #65203

Update the docs to clarify that the `@icon` annotation does not work when only attaching a script to a node; the script itself must be a globally accessible script type.

2022-12-01 14:36 UTC, YuriSizov requested changes

2022-12-01 18:43 UTC, souplamp commented on modules/gdscript/doc_classes/@GDScript.xml
> +				[b]Note:[/b] Inner classes are not supported to have their own icons.
Reverted.

2022-12-01 18:44 UTC, YuriSizov commented on modules/gdscript/doc_classes/@GDScript.xml
> +				Add a custom icon to a global script class. The icon specified at [param icon_path] is displayed in the Scene dock for every node of that script class type, or inheriting the script class in anot
I think the following sentence already explains what visible effect it is, don't you think so?

And no, there is no need to include reviewer as a co-author, at least not in Godot organization repositories. Also don't forget to squash your changes so it stays as a single commit 🙂

2022-12-01 18:50 UTC, souplamp commented on modules/gdscript/doc_classes/@GDScript.xml
> +				Add a custom icon to a global script class. The icon specified at [param icon_path] is displayed in the Scene dock for every node of that script class type, or inheriting the script class in anot
Maybe so then, I added these changes as is.

And okay! Thank you for the clarification :)

2022-12-01 19:12 UTC, YuriSizov approved these changes

2022-12-02 00:04 UTC, merged

2022-12-02 00:04 UTC, YuriSizov commented
Thanks!