Handle corner cases for curve baking
godotengine/godot pull request #69726
Opened 2022-12-07 15:39 UTC by xiongyaohua

When control point and point have equal position, the derivative is 0 vector, which cause error message in Basis::look_at(). This commit handles this case.

2022-12-09 19:10 UTC, TokageItLab requested changes
Corner cases should be handled (checked) in the Curve class, not in the Math class.

2022-12-13 12:04 UTC, xiongyaohua commented
To be more precise, they are the corner cases of how to correctly calculate tangent for one 2D/3D bezier segment. And like `Vector2D/3D::bezier_derivative()`, they can be used more generally than in `Curve2D/3D`. So I feel it could also be put on `Vector2D/3D` instead of `Curve2D/3D`.

2022-12-13 12:31 UTC, TokageItLab commented
I don't think so. There are several ways to think about the treatment of end/sharp points, and the error caused by the Curve class calculation using `look_at()` should be handled by the Curve class.

2022-12-14 00:56 UTC, xiongyaohua commented
Thanks for the explanation. I think you are right. I moved these methods to `Curve2D/3D` as internal methods, to keep them as implementation detail.

2022-12-14 08:47 UTC, TokageItLab approved these changes

2022-12-14 10:26 UTC, merged