Add blend mode setting to BlendSpace1D animation node, for parity with BlendSpaceD
godotengine/godot pull request #69999
Opened 2022-12-13 04:57 UTC by Skrapion

A simple patch to bring the blend mode setting from BlendSpace2D to BlendSpace1D.

This feature is useful for animating asymmetrical characters that have different left/right sprites. It also allows sprite-based games to use a similar Idle->Walk->Run blend like you would use in a 3D game.

It's also just an obvious stumbling block, especially since [the documentation](https://docs.godotengine.org/en/stable/tutorials/animation/animation_tree.html) implies that BlendSpace1D can be used like BlendSpace2D, however, BlendSpace2D works for sprites and BlendSpace1D doesn't.

2022-12-13 05:26 UTC, TokageItLab commented
I understand to some extent what you are intending, but please write the proposal first to explain it to others.. https://github.com/godotengine/godot-proposals

2022-12-13 07:28 UTC, Skrapion commented
@TokageItLab Proposal filled out, with video: https://github.com/godotengine/godot-proposals/issues/5930

2022-12-13 07:41 UTC, TokageItLab commented
Thank you! Yeah, I think it makes sense to implement such a feature since the current BlendSpace1D only provides the most of same functionality as NodeBlend3.

2023-01-19 10:08 UTC, TokageItLab requested changes
It seems to be copied and pasted what is needed from BlendSpace2D correctly and working fine.

After fixing the points I pointed out, please squash the commits into one. See [PR workflow](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html).

BTW, I have a concern that it is committing directly to master.

It is no problem if this is the only time you are sending a PR. However, if you are planning to send PRs in the future, it is recommended that you create a new branch before working on the modification. Take a look at the instructions on [how to sync upstream](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) :)

2023-01-19 10:08 UTC, TokageItLab commented on scene/animation/animation_blend_space_1d.cpp
> +	}
```suggestion
	if (p_parameter == closest) {
		return -1;
	} else {
		return 0;
	}
```
It can be written like above.

2023-01-30 17:57 UTC, akien-mga commented
Superseded by #72396.

2023-01-30 17:57 UTC, closed without merging