Improve clarity of Tree's activated/double-clicked signals
godotengine/godot pull request #70290
Opened 2022-12-19 07:38 UTC by aaronfranke

When double-clicking a Tree's TreeItem, you might expect `item_double_clicked` to be emitted. However, this signal is badly named. It's only emitted when the icon is double-clicked, not any other part of the item. The actual signal that works when double-clicking on any part of the item is `item_activated`.

This PR improves the documentation to make this clear and also renames `item_double_clicked` to `item_icon_double_clicked` to reflect that it only emits when double-clicking on an item's icon.

2022-12-19 12:04 UTC, YeldhamDev commented
Maybe `item_activated` should also be renamed to `item_label_double_clicked`?

2022-12-19 16:42 UTC, aaronfranke commented
@YeldhamDev `item_activated` is also emitted when clicking on the icon, or on the empty space to the left or right side.

2022-12-21 13:52 UTC, YuriSizov commented
> This PR improves the documentation to make this clear and also renames `item_double_clicked` to `item_icon_double_clicked` to reflect that it only emits when double-clicking on an item's icon.

I think if you add it to the project convertor, it would be okay to break compat here.

2022-12-21 13:59 UTC, YuriSizov requested changes, later dismissed

2022-12-21 13:59 UTC, YuriSizov commented on doc/classes/Tree.xml
> +				Emitted when an item is double-clicked, or selected with [code]ui_accept[/code] (the enter key or spacebar).
```suggestion
				Emitted when an item is double-clicked, or selected with a [code]ui_accept[/code] input event (e.g. using [kbd]Enter[/kbd] or [kbd]Space[/kbd] on the keyboard).
```

2023-01-24 15:38 UTC, akien-mga approved these changes
Approved by production team.

Did a thorough byte-wise review of why the heck GitHub shows a space being added after `item` here:
![image](https://user-images.githubusercontent.com/4701338/214338272-c8359801-c6b0-4534-af47-960f20f5e4ba.png)

2023-01-24 19:20 UTC, YuriSizov commented
Needs a rebase, though :)

2023-01-24 23:05 UTC, merged

2023-01-24 23:05 UTC, YuriSizov commented
Thanks!