Updated error message to be more human readable
godotengine/godot pull request #70386
Opened 2022-12-21 04:18 UTC by sfrembling

Fixes: #70141 

Updates a call from a non-descriptive error macro to one that is easier to understand for the typical user.

2023-05-06 08:29 UTC, brno32 commented
Can this be merged?

2023-05-06 10:53 UTC, kleonc commented on core/object/object.cpp
> +		ERR_FAIL_COND_MSG(!p_name.operator String().is_valid_identifier(), "Invalid identifier");
Probably makes sense to also tell what was that invalid identifier:
```suggestion
		ERR_FAIL_COND_MSG(!p_name.operator String().is_valid_identifier(), "Invalid identifier: '" + p_name + "'.");
```

2023-05-06 11:11 UTC, kleonc commented
@sfrembling Also both PR/commit titles: *"updated error message to be more human readable"* are too vague. I suggest something like *"Add human readable error message for Object::set_meta"* instead.

2023-05-06 19:12 UTC, sfrembling commented
@kleonc I went ahead and made those changes you mentioned. I definitely agree with the code change; bringing that information to the user will make things easier to debug. Thanks for the suggestions.

2023-05-06 19:27 UTC, kleonc commented
@sfrembling Note you've changed the PR title, but not the commit title. Also now there are 2 commits but a single commit is preferred for keeping the git history clean. So please squash the commits and change the title. You can do so by rebasing, for how-to [see the docs](https://docs.godotengine.org/en/4.0/contributing/workflow/pr_workflow.html#the-interactive-rebase). In the interactive rebase you'd want to do something like:
```
reword e620a43 updated error message to be more human readable
fixup 405fde2 Update core/object/object.cpp 
```
Besides that looks good to me.

2023-05-07 17:59 UTC, sfrembling commented
@kleonc, went ahead and went through with your advice. Are we all good to merge now?

2023-05-07 18:21 UTC, kleonc approved these changes
LGTM

2023-05-07 18:39 UTC, brno32 approved these changes

2023-05-07 20:10 UTC, mhilbrunner requested changes
This should include the information "metadata" in the error message, so something like "Invalid metadata identifier:" IMO

2023-05-15 20:15 UTC, sfrembling commented
> This should include the information "metadata" in the error message, so something like "Invalid metadata identifier:" IMO

Anything else anyone can think of for this change?

2023-05-29 14:26 UTC, mhilbrunner approved these changes

2023-05-29 14:53 UTC, YuriSizov commented on core/object/object.cpp
> +		ERR_FAIL_COND_MSG(!p_name.operator String().is_valid_identifier(), "Invalid metadata identifier: '" + p_name + "'.");
```suggestion
		ERR_FAIL_COND_MSG(!p_name.operator String().is_valid_identifier(), vformat("Invalid metadata identifier: '%s'.", p_name));
```

We use `vformat` to format strings.

2023-05-29 15:24 UTC, YuriSizov commented on core/object/object.cpp
> +		ERR_FAIL_COND_MSG(!p_name.operator String().is_valid_identifier(), "Invalid metadata identifier: '" + p_name + "'.");
I have been overruled on this.

2023-05-29 15:24 UTC, merged