Add missing OptionButton method descriptions
godotengine/godot pull request #70571
Opened 2022-12-25 22:41 UTC by Piralein

Add description for:

- get_selectable_item
- has_selectable_items
- is_item_separator

2022-12-26 22:48 UTC, KoBeWi commented on doc/classes/OptionButton.xml
> +				Returns the index of the first item which is not disabled, or marked as separator. If [param from_last] is set as [code]true[/code], the items will be searched in reverse order.
```suggestion
				Returns the index of the first item which is not disabled, or marked as separator. If [param from_last] is [code]true[/code], the items will be searched in reverse order.
```

2022-12-27 21:30 UTC, KoBeWi approved these changes

2022-12-28 13:03 UTC, YuriSizov requested changes

2022-12-28 13:03 UTC, YuriSizov commented on doc/classes/OptionButton.xml
> +				Returns [code]true[/code] if the [OptionButton] contains at least 1 item which is not disabled, or marked as separator.
```suggestion
				Returns [code]true[/code] if this button contains at least one item which is not disabled, or marked as a separator.
```

2022-12-28 13:03 UTC, YuriSizov commented on doc/classes/OptionButton.xml
> +				Returns [code]true[/code] if the item at index [param idx] is marked as separator.
```suggestion
				Returns [code]true[/code] if the item at index [param idx] is marked as a separator.
```

2022-12-28 18:35 UTC, YuriSizov approved these changes

2022-12-28 18:35 UTC, merged

2022-12-28 18:35 UTC, YuriSizov commented
Thanks!