GDScript: Fix editor ignoring parsing errors during code suggestions
godotengine/godot pull request #70710
Opened 2022-12-29 19:45 UTC by vonagam

Analyzer expects valid state from parser, like absence of name conflicts between members of a class. Editor was ignoring errors from parser in `GDScriptLanguage::complete_code` and `GDScriptLanguage::lookup_code`, which in case of issue bellow was crashing editor.

Analyzer itself can return an error too. Is it ok to ignored it for code suggestions?

Fixes #70665.

2023-01-05 00:39 UTC, anvilfolk approved these changes
Looks great! Essentially just makes sure that parsing errors are accounted for!

2023-01-12 13:22 UTC, adamscott approved these changes
LGTM

2023-01-12 14:02 UTC, akien-mga approved these changes

2023-01-12 14:17 UTC, vnen requested changes
Actually, this bad for usability. It is on purpose the parser errors are ignored. Most of the time you are completing code that is partially written and won't be correctly parsed, so if completion stops when there's a parser error, then it will pretty much never work.

2023-01-13 13:24 UTC, vnen commented
I got curious ended up working a fix for the specific issue: #71329

In general, the analyzer does not (and should not) expect a valid result from the parser. There's a lot of checks for places where the parser could fail to avoid crashes. This is exactly because of completion so we can have the most information available even when the script code is invalid.

2023-01-13 13:24 UTC, closed without merging