Remove side effect of the `handles` method
godotengine/godot pull request #70907
Opened 2023-01-04 07:06 UTC by xiongyaohua

Fix https://github.com/godotengine/godot/issues/70688

The cause of the problem is that, when the inspector panel is on, selecting a `Path3D` object will generate two calls to `Node3DEditorPlugin::handles(Object *p_object)`. In the first call, the `p_object` parameter is the `Path3D` object itself, so the gizmo is turned on. However in the second call, generated by the inspector to test if inner resources can be handled by editor plugins, the parameter is a `Curve3D`, the inner resource of "Path3D". Because the side effect of the `handles` method, the gizmos is turned off again, hence the problem. When the inspector panel is off, there is no second call, hence no problem.

Removing the side effect from "handles" method solve current problem, but based on the comments, it may cause problem in places where side effect is required. But I think those place should clear gizmo explicit, or call a version with side effect.

2023-01-04 09:00 UTC, TokageItLab commented
As I commented in https://github.com/godotengine/godot/issues/70688#issuecomment-1370637385, there are too many objects affected by this method and I feel that other methods should be investigated. At worst, it may be better to revert #70696.

2023-01-04 11:02 UTC, TokageItLab requested changes
Well, it seems that this sideeffect was already causing the bad behavior, regardless of #68498. It looks like there has been a bug for some time that breaks the EditorPlugin if you add a script in any `Node3D` child class and open SubInspector.

However, commit #68498 makes it much worse. Even with this fix, opening the script's SubInspector will not open the EditorPlugin for the other SubResource that Node has, and will kill the Path3D and Collision3D editor plugins.

So, this fix can be accepted, but #68498 should be reverted.

Honestly, I don't know how many situations actually require this explicit clearing, but I have confirmed that `Skeleton3D`, `Path3D`, and `CollisionPolygon3D` have no problem.

2023-01-04 12:10 UTC, xiongyaohua commented on editor/plugins/node_3d_editor_plugin.cpp
>  	}
done

2023-01-04 12:13 UTC, TokageItLab approved these changes

2023-01-04 13:13 UTC, YuriSizov commented
While on the surface this hacky code seems unnecessary, it was added recently for a reason: https://github.com/godotengine/godot/pull/61292

Ultimately, it boils down to the overall issue with how edited objects are tracked. But either way it seems to be necessary for now. cc @KoBeWi

2023-01-04 13:45 UTC, KoBeWi commented
This will reopen #13849

2023-01-05 12:07 UTC, akien-mga commented
Is this still needed after #70909?

2023-01-05 12:10 UTC, TokageItLab commented
Yeah, as I said in #70914, regardless of #70909 there is a problem that is causing a little bit of a drawing problem in Editor. This eliminates the bug in Editor due to the inspector status, but https://github.com/godotengine/godot/issues/13849 will reopen.

2023-01-05 12:35 UTC, TokageItLab commented
@akien-mga With this fix, the SkeletonEditor display is now proper, regardless of whether the subinspector is opened or closed:

Before (hidden bone gizmo):
![image](https://user-images.githubusercontent.com/61938263/210780932-96fcb599-db38-4263-9252-a9a07bb82048.png)

After this fix:
![image](https://user-images.githubusercontent.com/61938263/210780036-8d0f4813-edd0-4582-90f6-1f54aa90855e.png)

---

This also fixes a bug in Path3D caused by opening and closing the Curve inspector.

https://user-images.githubusercontent.com/61938263/210781168-a155e34c-c403-459c-8669-a76ca2696925.mp4

However, there is remaining problem is that the CollisionPolygon and Path3D editors can still be broken by opening and closing the Sctipt SubInspector. I think it depends on the update order of the inspector.

Well, since this PR was implemented as a hack in #61292 for #13849 in the first place, it will need to be reverted at some point anyway. To fix it completely, we need to do a radical fix after these reverts, as discussed in RocketChat with @YuriSizov and @KoBeWi.

2023-01-05 12:44 UTC, Rindbee commented
In fact, if there is no good way to solve #13849, changing the condition to `else if (p_object->is_class("Node"))` may be a compromise.

2023-01-05 13:55 UTC, YuriSizov approved these changes
We can merge this to address another part of https://github.com/godotengine/godot/issues/70914. With this hack gone you can select the Curve resource of Path3D without losing gizmos. This doesn't fix the issue with selecting script resources, for some reason. So there is yet another problem with path3d and collision shape plugins, so far unidentified.

https://github.com/godotengine/godot/issues/13849 needs to be reopened, if we merge this.

2023-01-05 14:01 UTC, merged