Improve description of `GetNodeOrDefault` in C# API
godotengine/godot pull request #71168
Opened 2023-01-10 18:00 UTC by guilleatm

Closes https://github.com/godotengine/godot-docs/issues/6577.

2023-01-10 18:06 UTC, guilleatm commented
PR from issue in docs: https://github.com/godotengine/godot-docs/issues/6577

Provided same text as GDScript version: https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-get-node-or-null

First PR :)

2023-01-10 18:31 UTC, YuriSizov commented
Note that you will need to squash your commits into one, with a clear but short message, before this can be merged. You can do it later, in case there are some review comments that you need to address, but you will have to do this eventually. For a reference when crafting a good commit message you can read [this](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind).

2023-01-10 20:32 UTC, guilleatm commented
Squash done

2023-01-11 00:44 UTC, raulsntos requested changes

2023-01-11 00:44 UTC, raulsntos commented on modules/mono/glue/GodotSharp/GodotSharp/Core/Extensions/NodeExtensions.cs
> +		///	Similar to <see cref="GetNode"/>, but does not log an error if <paramref name="path"/> does not point to a valid <see cref="Node"/>.
Use spaces for indentation. Also, I think the line is a bit long and would be better to break it up.

```suggestion
        /// Similar to <see cref="GetNode"/>, but does not log an error if <paramref name="path"/>
        /// does not point to a valid <see cref="Node"/>.
```

2023-01-11 15:14 UTC, raulsntos approved these changes

2023-01-11 16:27 UTC, merged

2023-01-11 16:27 UTC, YuriSizov commented
Thanks! And congratulations on getting your first PR merged :)

2023-01-11 17:28 UTC, guilleatm commented
Thanks! :)