Add EXPOSURE built in to spatial shaders
godotengine/godot pull request #71364
Opened 2023-01-13 22:47 UTC by clayjohn

This allows users to restore light values to pre-prebaked-exposure amounts

Fixes: https://github.com/godotengine/godot/issues/69847
Supersedes: https://github.com/godotengine/godot/pull/71304

When using Physical Light Units or ``exposure_multiplier`` in a ``CameraAttributes***`` resource all light sources are pre-baked by the exposure amounts in the ``CameraAttributes``. This ensures that the screen texture values stay within a manageable range.

A side-effect of this pre-baking is that SCREEN_TEXTURE returns the post-pre-baked exposure amount. I.e. the final brightness after applying exposure from CameraAttributes, but before applying exposure from the tonemapper. If this value is fed back in as an ALBEDO, everything works fine because ALBEDO expects a non exposed color. However, if you feed the SCREEN_TEXTURE result in EMISSION, it appears black because EMISSION is in physical light units, so it expects un-pre-baked exposed values (it will apply the pre-baked exposure internally after the user shader has ended). The end result is that we can either have SCREEN_TEXTURE properly exposed for ALBEDO (including baked exposure) or for EMISSION (including baked exposure). 

https://github.com/godotengine/godot/pull/71304 falls short as all it does is revert the default so that SCREEN_TEXTURE works for EMISSION, but not for ALBEDO (i.e. it returns the un-pre-baked exposure value). 

This PR exposes an ``EXPOSURE`` (open to alternative naming suggestions) builtin to spatial shaders that allows us to account for the pre-baked exposure. Simply multiplying ``EXPOSURE`` by values that already have the exposure baked in will undo the pre-baked exposure and return the original value. For example, multiplying this by a light's energy will give the original energy before pre-baking the CameraAttributes exposure. Or alternatively, multiplying by the result of SCREEN_TEXTURE will give you what the screen texture pixel would have been if the pre-baking had not been applied.

Tagging as 4.x as there is no rush on this. It is a pain for people using Physical Light units, but this is an addition to the shader API so I would also like more time for this to be tested and discussed, accordingly, I would prefer to merge after 4.0 stable release.

2023-04-12 15:01 UTC, akien-mga commented
Needs rebase, otherwise should be good to go if nobody has any comment :)

2023-04-12 15:38 UTC, Chaosus commented on editor/plugins/visual_shader_editor_plugin.cpp
> +	add_options.push_back(AddOption("Time", "Input/All", "VisualShaderNodeInput", vformat(input_param_shader_modes, "exposure", "EXPOSURE"), { "time" }, VisualShaderNode::PORT_TYPE_SCALAR, -1, Shader::M
```suggestion
	add_options.push_back(AddOption("Exposure", "Input/All", "VisualShaderNodeInput", vformat(input_param_shader_modes, "exposure", "EXPOSURE"), { "time" }, VisualShaderNode::PORT_TYPE_SCALAR, -1, Shader::MODE_SPATIAL));
```

2023-04-12 15:39 UTC, Chaosus commented on editor/plugins/visual_shader_editor_plugin.cpp
> +	add_options.push_back(AddOption("Time", "Input/All", "VisualShaderNodeInput", vformat(input_param_shader_modes, "exposure", "EXPOSURE"), { "time" }, VisualShaderNode::PORT_TYPE_SCALAR, -1, Shader::M
Also, please put it to follow the alphabet order.

2023-04-12 15:40 UTC, Chaosus commented on scene/resources/material.cpp
> +		code += "	EMISSION += textureLod(screen_texture,ref_ofs,ROUGHNESS * 8.0).rgb * ref_amount * EXPOSURE;\n";
```suggestion
		code += "	EMISSION += textureLod(screen_texture, ref_ofs, ROUGHNESS * 8.0).rgb * ref_amount * EXPOSURE;\n";
```

2023-04-12 15:41 UTC, Chaosus requested changes
Seems good except few typos in visual shader.

2023-04-12 17:35 UTC, clayjohn commented
Thanks @Chaosus! I pushed a new version with your suggested changes

2023-04-12 20:36 UTC, Calinou commented
Could this help with https://github.com/godotengine/godot/issues/74140?

2023-04-12 23:33 UTC, clayjohn commented
> Could this PR help with #74140 and #75128?

I don't think so

2023-04-13 04:39 UTC, Chaosus approved these changes

2023-04-13 07:58 UTC, merged