Fix close all script tabs issue
godotengine/godot pull request #71428
Opened 2023-01-14 19:18 UTC by honix

Fixes #71331.
Observed and created a issue #71426. This is related but different problem.

2025-04-28 19:58 UTC, kitbdev requested changes

2025-04-28 19:58 UTC, kitbdev commented on editor/plugins/script_editor_plugin.cpp
> +	erase_tab_confirm->connect("cancelled", callable_mp(this, &ScriptEditor::_clear_close_queue));
There is no `cancelled` signal, so `_clear_close_queue` never gets called.
This leads to issues with the queue holding too many entries.

2025-04-28 22:07 UTC, kitbdev commented
This also needs to be rebased to fix conflicts, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#updating-your-branch) for more info.

2025-04-28 22:19 UTC, honix commented
Not sure that I have a setup to merge and test it right now. Maybe I'll try in coming weeks.

2025-05-10 18:40 UTC, honix commented
The initial issues are fixed in main branch. #71331 have some new error message, I'll look at in another PR. This PR is not actual for now.

2025-05-10 18:40 UTC, closed without merging