Fix missing/incorrect autocomplete on nested types
godotengine/godot pull request #71842
Opened 2023-01-22 08:12 UTC by poohcom1

Fix #71734

1. Fix nested classes not being suggested for global classes
![image](https://user-images.githubusercontent.com/74857873/213905707-c77e6fb2-df5e-41c3-9566-0240ca192723.png)

2. Remove various invalid suggestions (functions, constants, parent classes/enums) for when suggesting types from nested classes.
![image](https://user-images.githubusercontent.com/74857873/213905751-d5f8f4fc-5095-4e11-a673-215a526d7f15.png)

*User signals are still being suggested, but this should be fixed by #70002

## Technical Details
Changes:
- When auto-completing `COMPLETION_TYPE_ATTRIBUTE`, use `_guess_identifier_type` for the first type in the type chain to account for global classes.
- Added `p_only_types` parameter in `_find_identifiers_in_base` and `_find_identifiers_in_class` to filter for only type identifiers.
- Added `is_meta_type` for found classes in `_guess_identifier_type` and `_guess_identifier_type_from_base`. Correct me if I'm wrong, but `is_meta_type` should be for identifiers that represents it's own type (like a class identifier) rather than being an instance of said type. If that's true, then all found class identifiers should be a meta type.

2023-01-22 08:20 UTC, poohcom1 commented
I also added a small clarification comment for `CompletionContext.current_argument`. At first I was very confused why "current_argument" was being [used for a type_chain's size](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_editor.cpp#L2881-L2888), but turns out it's used for both parameter index and type_chain size, so I thought having a small comment could help clear confusion for future devs.

2023-01-22 11:25 UTC, poohcom1 commented
I realized constants could also be used as types, but decided against including them because of the difficulty of figuring out if a constant is a script or a resource. The three options I had were:
1. Show no constants.
2. Show all constants. While this would make it easier for users to choose what they want, it introduces potentially incorrect suggestions
3. Show only constants that is initialized with preload and is preloading a `.gd` file. This works, but is inconsistent. It seems to work with a global classes but not with a preloaded scripts. 

For now, I'm inclined to not show constants at all. Even with option 3, it is still pretty inconsistent, plus the fact that this won't work for constants assigned to other constants and that users are unlikely to be mixing global class and preloaded scripts make me think it's not really worth it. Let me know if you have any other opinions/suggestions.

2023-02-06 16:43 UTC, vnen requested changes

2023-02-06 16:43 UTC, vnen commented on modules/gdscript/gdscript_editor.cpp
> +						if (p_only_functions || p_only_types || p_only_types) {
Added `p_only_types` twice here.

2023-02-06 18:29 UTC, poohcom1 commented
> Not sure what is the difficulty here. If it's a constant it should have a value already, then you can check if the value is a script or not.

Just realized I could just check the datatype of the initializer to see if a constant is a script. I was trying to check if the expression node was a preload. I've added and a line to allow constant that are scripts or classes. It works well for global classes, but for preloaded classes still doesn't show constants as it seems like the constant's initializer hasn't been reduced at the time of auto-completion.

2023-02-06 18:29 UTC, poohcom1 commented on modules/gdscript/gdscript_editor.cpp
> +						if (p_only_functions || p_only_types || p_only_types) {
Fixed

2023-06-16 21:52 UTC, adamscott commented
Moved the milestone from 4.1 to 4.2, as the PR needs a rebase and the 4.1 release is too close for such a PR.

Will add this PR to the list of PR to review by the GDScript team.

2023-10-27 09:12 UTC, dalexeev commented
Postponed to 4.3 as this is not a critical bug and some work is needed on this PR.

2024-07-08 10:27 UTC, HolonProduction commented
> I also added a small clarification comment for `CompletionContext.current_argument`. At first I was very confused why "current_argument" was being [used for a type_chain's size](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_editor.cpp#L2881-L2888), but turns out it's used for both parameter index and type_chain size, so I thought having a small comment could help clear confusion for future devs.

Couldn't we use a union for that?

2024-07-08 18:06 UTC, HolonProduction commented
@poohcom1 are you still interested in working on this, or can it be salvaged?

2024-07-08 18:11 UTC, poohcom1 commented
@HolonProduction Yeah I'd prefer it if someone else could salvage it. I mostly work with C# now and I've kinda forgotten what I was doing here.

2025-07-11 03:19 UTC, poohcom1 commented
Superseded by https://github.com/godotengine/godot/pull/94996

2025-07-11 03:19 UTC, closed without merging