Tilemap update erase_cell() to also delete instantiated scenes
godotengine/godot pull request #72456
Opened 2023-01-31 15:14 UTC by Sch1nken

As mentioned here: #69596 

The current implementation has two potential flaws. I've thought about possible fixes but would like to get some feedback first before implementing them:

1. If a Node (instantiated scene) gets moved to another place in the tree (i.e. not a direct child of the TileMap anymore) OR the node gets renamed OR the node gets freed by the user, the current implementation can NOT remove the scene anymore (it should however be able to free-up the internal cell reference).
2. It would be possible to connect to the exited_tree() signal of the nodes to mitigate some of these issues. This could be an optional parameter for set_cell() ("listen to lifetime events" = yes/no, or something similiar). Once the node gets removed/renamed/etc the tilemap could update its reference (or remove it depending on what happened to the node).

So right now the user should only add/remove cells through set_cell()/erase_cell() and never manually remove/move/rename any nodes that the tilemap created.

So the question is: Is it the TileMaps job to update references to scenes when they are modified through other means than using the TileMaps interface?

2023-01-31 15:28 UTC, groud commented
> So the question is: Is it the TileMaps job to update references to scenes when they are modified through other means than using the TileMaps interface?

No. There are hundreds of scenarios where a TileMap's internal scenes could be modified one way or another. We don't disallow completely editing scenes instantiated by a TileMap, as I guess it might be useful to workaround some limitations, but it's the user's responsibility not to mess up here. 

We cannot cover all situations where users would do weird things, like renaming an instantiated scene, moving it around, etc... It's simply easier to assume that, if a user do something like that, the TileMap node might not be able to recover from that state.

This should however be properly documented though.

2023-01-31 15:50 UTC, Sch1nken commented
Good. In that case the pull request could suffice (if up to standards).

2023-01-31 16:25 UTC, groud commented
Sorry but I don't think the PR is right. The calls to `_erase_quadrant` or `_make_quadrant_dirty` should automatically free those scenes. The bug is likely there.

2023-01-31 16:49 UTC, Sch1nken commented
I think I see what you mean, yes. From what I gathered the only way scenes are deleted is when `instantiated_scenes.is_empty() == true` on line 1873. 

But there is only one call to clear the `instantiated_scenes` set (inside `_tile_set_changed`). This would also remove _all_ scenes and not just single ones removed by erase_cell()/set_cell().

So there currently is no good way to identify scenes that are to be deleted. I'll see what I can come up with.

2023-05-27 03:02 UTC, KevinWh0 commented
until this is merged I have been reading the tilemap godot source code and found a hack to make it roughly work. Probably way worse, and it is just a hack, but if you really need it to work now here you go:

```py
func _clear_tilemap_cache(tilemap):
    for n in tilemap.get_children():
        tilemap.remove_child(n)
        n.queue_free()
    tilemap.tile_set.add_source(tilemap.tile_set.get_source(0), -1)
```
I will add if you are doing raycasting or something and its not hitting like expected then you would want to store the tilemaps children and delete them a frame later when its re-instanced (remember to make sure it hasn't already been removed from the scene)
Here is a implementation of that, but this possibly has some other issues:
```py
var tiles_to_delete = {}
var saved_tilemap
var delete_at_frame = -1
#YOU HAVE TO CALL THIS AFTER EVERY SET CELL
# SHOULD BE OK AFTER https://github.com/godotengine/godot/pull/72456 is merged
func clear_tilemap_cache(tilemap):
    tiles_to_delete = tilemap.get_children()
    saved_tilemap = tilemap
    delete_at_frame = Engine.get_frames_drawn() + 1
    tilemap.tile_set.add_source(tilemap.tile_set.get_source(0), -1)

#Deleting it later once the next batch of tiles is already instanced makes it so that
#The raycasts dont fail
func _process(delta):
    if delete_at_frame < Engine.get_frames_drawn() and delete_at_frame != -1:
        for n in tiles_to_delete:
#            Make sure it has not already been deleted, if so skip it
            if !weakref(n).get_ref():
                continue;
            saved_tilemap.remove_child(n)
            n.queue_free()
        delete_at_frame = -1
        tiles_to_delete = {}
```

For both of these you will need to call _clear_tilemap_cache every time you modify the tilemap. Hopefully this helps someone, and keep in mind I think all this code should be able to be removed after this is merged but you should make sure of that before totally ripping it out, and also this is kinda experimental and hacky, but it works for me. Probably shouldn't use it if you want 100% sure it wont crash, but do your own testing, its pretty stable for me.

2023-07-26 20:15 UTC, KoBeWi commented
Needs rebase. I tested the PR and it doesn't seem to work, i.e. the scene is not removed. The recent changes to TileMap layers might've broken it.

2023-07-27 08:26 UTC, AThousandShips commented on scene/2d/tile_map.cpp
> +		auto entry = q.scenes.find(pk);
Usage of `auto` is [not allowed](https://docs.godotengine.org/en/stable/contributing/development/cpp_usage_guidelines.html#auto-keyword)

2023-07-27 08:26 UTC, AThousandShips requested changes, later dismissed
See above

2023-07-27 17:25 UTC, KoBeWi commented on scene/2d/tile_map.cpp
> +			String name = entry->value;
`name` will shadow a property in TileMapLayer (after recent changes) so it needs to be renamed.

2023-08-09 01:02 UTC, joshmitcho commented
Is this fix coming soon? It seems a lot of people are having the same issue

2023-08-09 11:34 UTC, KoBeWi commented
@Sch1nken Can you rebase the PR and apply changes?

2023-08-11 16:33 UTC, KoBeWi approved these changes
Works correctly now, but you still need to rebase and squash the PR.
Here's the rebased code:
```C++
		// Find node in scenes and remove it.
		HashMap<Vector2i, String>::Iterator entry = q.scenes.find(pk);
		if (entry != q.scenes.end()) {
			String scene_name = entry->value;
			Node *scene = tile_map_node->get_node_or_null(scene_name);
			if (scene) {
				scene->queue_free();
				instantiated_scenes.erase(Vector2i(pk.x, pk.y));
			}
		}
```

2023-08-11 17:34 UTC, Sch1nken commented
Currently working on it. Not much experience with rebasing and apparently rebased before pulling master. 

Currently trying to resolve the conflict... Sorry for the delay.

2023-08-11 17:48 UTC, KoBeWi commented
The code has moved around a lot. It's better if you accept the current code (i.e. on the master branch) when resolving conflict and then apply your changes again. You can use my snippet as a reference how to fixes compile errors that will emerge, because the original code will not work after the recent TileMap changes.

2023-08-11 19:46 UTC, Sch1nken commented
I don't think I've made the correct steps (rebasing, squashing etc). But my local git says everything is up to date while GitHub mentions 8 commits ahead and 10 commits behind from master...

2023-08-15 13:06 UTC, Sch1nken commented
Okay, I feel like I borked my PR/Git history beyond my comprehension. To not delay this any further: Should I just open a fresh new PR with the necessary changes? Or: If someone is willing to do it themselves, go for it.

I'm really struggling fixing my local git history. Rebasing and squashing are pretty new to me and it would take longer for me to understand it right now (and fix my mess) than to just start over.

2023-08-15 14:43 UTC, closed without merging