Non-realtime simulation
godotengine/godot pull request #7269
Opened 2016-12-09 12:56 UTC by Tugsav

Added support for running Godot as a game simulator.

Two cmd-line flags can be set to use the functionality
- fixed_fps [int fps]: can be set to disable the frame delay turning the application into a non-realtime one.
- disable_render_loop: can be set to disable rendering completely in the main loop, speeding up the
 simulation.

The fps set, is the frames pr. game second, allowing the game to speed up or slow down 
according to processing speed.
It is useful for using Godot to simulate many game outcomes quickly, which can f.ex. be used for AI 
training.

We can also render frames to files using these flags, by controlling the rendering from script (i used a 
simple .gd script in my project that queued a screenshot, called draw, and then got the screenshot in the 
_process() function)

2017-01-10 14:13 UTC, akien-mga commented
@Tugsav BTW, it looks like the email address you use to sign your commits is not linked to your GitHub account, so it does not show you (i.e. your @Tugsav account) as author of the commit. That's no big deal, but if you do want this link to be made, you can add your other email as secondary emails in the GH settings.

2017-01-12 09:57 UTC, Tugsav commented
@akien-mga Thanks for the heads up. I have added the email as a secondary.

2017-08-17 11:29 UTC, reduz requested changes

2017-08-17 11:29 UTC, reduz commented on main/main.cpp
> +	if(fixed_fps == -1){
I think it's more readable to do
if (fixed_fps != -1)
   return exit;

2017-08-17 11:29 UTC, reduz commented on main/main.cpp
> +	if(!disable_render_loop){
This is probably pretty unsafe, if rendering was moved to another thread, the command ringbuffer will never be flushed. At least sync() needs to be called always.

2017-08-17 11:29 UTC, reduz commented
Sorry, missed this somehow

2017-08-30 11:45 UTC, Tugsav commented
PR has been updated to work on current master
I have created a small test project to show an example use of the feature:
[https://github.com/Tugsav/godot-test-nonrealtime.git](url)

2017-08-30 12:10 UTC, Noshyaar commented
There are issues with code style. Please run `clang-format` prior to committing.

2017-08-30 12:25 UTC, Tugsav commented
@Noshyaar Attempted to fix code style. Thanks for the quick feedback

2017-08-31 09:52 UTC, merged

2022-04-15 20:32 UTC, Calinou commented
@Tugsav Out of curiosity, is there a reason `-1` was used as the "non-fixed" value instead of `0`? I'm not sure if a fixed FPS of 0 is valid, since this results in a division by zero.

2022-04-15 20:41 UTC, Tugsav commented
@Calinou nope. No specific reason other than it being an obviously invalid fps value. Would be fine to change it for consistency.