PopupMenu upgrade: Hide on item selection
godotengine/godot pull request #7306
Opened 2016-12-15 21:54 UTC by Tybobobo

Added the option to set hide on item selection. Usable in GDScript and from within the source code when you want to specify popup menus you don't want to close immediately when selecting an item.

_(Sorry about Git, still learning and messing up..!)_

2016-12-15 23:40 UTC, leonkrause requested changes
Please fix at least the submenu behavior and rename `get_hide_on_item_selection`.

Kudos for adding documentation from the get-go

2016-12-15 23:40 UTC, eska014 commented on scene/gui/popup_menu.cpp
> +	}
`PopupMenu` allows creating submenus by adding `PopupMenu` children to the `PopupMenu`  and calling `add_submenu_item`.

When clicking a submenu item with `hide_on_item_selection` turned off, the parents will be hidden, while the submenu remains shown (see logic below the `//hide all parent PopupMenue's` comment). The parents should remain visible as well.

2016-12-15 23:40 UTC, eska014 commented on scene/gui/popup_menu.cpp
> +void PopupMenu::set_hide_on_item_selection(bool p_bool) {
Prefer using `p_enabled` to `p_bool`, that name is used throughout the code and slightly more expressive

2016-12-15 23:40 UTC, eska014 commented on scene/gui/popup_menu.cpp
> +bool PopupMenu::get_hide_on_item_selection() {
This is a boolean, so the name should start with `is_`

2016-12-15 23:40 UTC, eska014 commented on scene/gui/popup_menu.cpp
> +	ADD_PROPERTY( PropertyInfo(Variant::BOOL, "hide_on_item_selection" ), _SCS("set_hide_on_item_selection"), _SCS("get_hide_on_item_selection") );
The property defaults to `true`, so save some memory here by using `ADD_PROPERTYNO`, which will only save the value if it's not `true` (i.e. if it's not 1, `NO` = non-one)

2016-12-16 00:21 UTC, Tybobobo commented
Gotcha! I'll fix them all up!

2016-12-16 13:59 UTC, Tybobobo commented
Fixed requested changes by @eska014

2016-12-18 19:49 UTC, leonkrause approved these changes

2016-12-23 14:43 UTC, merged