monochrome icon for android 13
godotengine/godot pull request #73102
Opened 2023-02-11 14:13 UTC by Donnnno

A monochrome icon for android 13

2023-02-11 14:15 UTC, YuriSizov commented on platform/android/java/lib/res/mipmap-anydpi-v26/icon.xml
> +	<monochrome android:drawable="@drawable/icon_monochrome"/>
Should be spaces instead of tabs.

2023-02-13 03:24 UTC, m4gr3d approved these changes
Can you provide a screenshot for what the monochromatic icon looks like on Android 13.

2023-04-25 13:59 UTC, akien-mga commented
I rebased and squashed the commits myself.

We still need to see how the icon looks like before merging though. Seems to be some pseudo-SVG but Inkscape can't read it, if someone has Android Studio installed and can take screenshots, that would be welcome.

I don't have any Android 13 device to test it either.

2023-05-03 01:04 UTC, m4gr3d commented
The icon is too big and doesn't look right in the app library

![godot_screenshot_icon_monochrome](https://user-images.githubusercontent.com/914968/235815705-f3505f0c-60bd-49ff-bd9d-deae33f92b6c.png)
![godot_icon_monochrome](https://user-images.githubusercontent.com/914968/235815707-aa715e62-a5ef-46ef-bfea-e99baeb2908f.PNG)

2023-05-03 01:05 UTC, m4gr3d requested changes
The icon needs to be resized to match the guidelines at https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#design-adaptive-icons

2023-06-16 07:34 UTC, akien-mga commented
Closing as this seems to be abandoned by the original author.

CC @MewPurPur @Calinou if you're interested.

For the record the "icon too big" issue seems to be true for the default, colored icon too, and would be good to address one way or another (either adding a new default icon for Android that matches the adaptive icon guidelines, or adding export code that takes care of properly padding it, as I see also a lot of Godot games on Android having way too zoomed in icons).

2023-06-16 07:34 UTC, closed without merging