Prevent crash in ImmediateMesh.create_outline
godotengine/godot pull request #73262
Opened 2023-02-14 00:42 UTC by chutchinson

Prevents a crash in ```ImmediateMesh.create_outline``` by ensuring that when no indices are specified, the number of vertices is divisible by 3 without residue. We must check if the vertices vector is divisible by 3 because the outline method constructs normal vectors from a triangle (in other words, there are 3 accesses per iteration)

2023-02-14 01:18 UTC, clayjohn approved these changes

2023-02-14 06:36 UTC, Chaosus requested changes

2023-02-14 06:36 UTC, Chaosus commented on scene/resources/mesh.cpp
> +			// ensure there are enough vertices to construct at least one triangle
```suggestion
			// Ensure there are enough vertices to construct at least one triangle.
```

2023-02-15 05:11 UTC, Chaosus approved these changes

2023-02-15 08:54 UTC, merged

2023-02-15 08:55 UTC, akien-mga commented
Thanks!