Bugfixes for Tree node
godotengine/godot pull request #7341
Opened 2016-12-20 23:19 UTC by bruno-ortiz

This PR fixes 2 bugs: 

-  Deselecting a TreeItem when select_mode is SELECT_SINGLE now works;
- Fixes #3549, now when select_mode is SELECT_SINGLE, the signal item_selected is emitted.

2016-12-23 14:55 UTC, akien-mga requested changes

2016-12-23 14:55 UTC, akien-mga commented on scene/gui/tree.cpp
> +    if (select_mode==SELECT_MULTI || select_mode == SELECT_SINGLE) {
Indentation issue, you should be using tabs like in the rest of the code, but your editor is likely enforcing 4 spaces. (same thing in the other commit). Could you rebase to fix them?

2016-12-23 16:59 UTC, bruno-ortiz commented on scene/gui/tree.cpp
> +    if (select_mode==SELECT_MULTI || select_mode == SELECT_SINGLE) {
fixed! :+1:

2017-01-02 13:08 UTC, bruno-ortiz commented
I noticed now that i merged my edit_resource branch in the master branch. I shouldn't have done that. How can i fix this?

2017-01-02 13:10 UTC, akien-mga commented
`git rebase -i HEAD~6` and remove the unwanted commits. You could also take the opportunity to squash the remaining commits together so that the commit is merge ready.

2017-01-02 13:29 UTC, bruno-ortiz commented
Thanks, I think that now everything is correct.

2017-01-02 14:52 UTC, akien-mga approved these changes

2017-01-02 14:53 UTC, merged