Allows to start the scene with custom arguments within the editor
godotengine/godot pull request #7347
Opened 2016-12-21 14:46 UTC by bebae

fixes #7346

Path from the current scene isn't added too the argumens anymore by default and needs to be added throug the custom arguments, with $scene. Matches the behaviour of the executable without any arguments.
Custom Arguments are read from editor/main_run_args

2016-12-21 20:23 UTC, bojidar-bg requested changes
Looks good overall

2016-12-21 20:23 UTC, bojidar-bg commented on tools/editor/editor_node.cpp
> +    args = Globals::get_singleton()->get("editor/main_run_args");
Nothing personal (not to you nor to them), but you put some spaces instead of a tab here.

2016-12-21 20:23 UTC, bojidar-bg commented on tools/editor/editor_run.cpp
> +            args.push_back(cargs[i].replace("$scene",p_scene).replace(" ","%20"));
Same spaces vs. tabs issue here.

2016-12-21 21:20 UTC, bebae commented
killed that evil spaces

2016-12-22 10:18 UTC, bojidar-bg approved these changes

2016-12-23 14:59 UTC, merged