GDScript: Rework type check
godotengine/godot pull request #73489
Opened 2023-02-17 08:38 UTC by vonagam

Handle type check - `a is A` - as its own thing, not as after-thought in logic of binary operator. A type is now parsed as a proper type specifier, not an expression. 

Add support for typed arrays.
```gdscript
a is Array[int] # now possible
```

Add support for checking with `Script` type, not only `GDScript`.

Fix handling of constants. Look at a type of actual reduced value instead of a declared type. Also fix constant null handling.
```gdscript
class A: pass

const three: Variant = 3
print(three is A) # before: true, now: false

print(null is A) # before: true, now: false
```

Since right side now needs to be compile time known type to support previously available functionality, where type value was a dynamic variable, add `is_type_of` utility function to GDScript.
```gdscript
is_type_of(a, TYPE_INT)
is_type_of(a, RefCounted)
is_type_of(a, A)
```

In `GDScriptAnalyzer::resolve_datatype` do not set `builtin_type` to `Variant::OBJECT` for `Variant` type.

In `GDScriptCompiler::_gdtype_from_datatype` and `GDScriptCompiler::_parse_expression` trust analyzer with `builtin_type` of enum. (Irrelevant to this PR, just noticed, can remove.)

2023-02-17 17:14 UTC, vnen requested changes

2023-02-17 17:16 UTC, vonagam commented on modules/gdscript/gdscript_byte_codegen.cpp
> +			append(get_constant_pos(native_class) | (GDScriptFunction::ADDR_TYPE_CONSTANT << GDScriptFunction::ADDR_BITS));
Hah, I actually wanted to ask you why in some places `GDScriptNativeClass` is passed and in some `StringName` is enough. Ok, will change it to `StringName`.

2023-02-17 17:17 UTC, vnen commented
`is_type_of` sounds backwards to me (that is, I would expect the order of arguments to be inverted). Maybe we could use `is_instance_of`? While builtin types aren't technically "instances", I think the name is more fitting.

2023-02-17 17:20 UTC, vonagam commented
I thought that in the future there might be a unified representation for a type (like `Variant::TYPE` or something) and with that in mind `is_type_of` would be more direct than `is_instance_of` (with second argument being of that type). But `is_instance_of` is obvious alternative, have no problem with that.

2023-02-17 18:14 UTC, vonagam commented
Renamed to `is_instance_of`.

2023-02-19 16:43 UTC, vnen approved these changes

2023-02-20 14:43 UTC, merged

2023-02-20 14:44 UTC, akien-mga commented
Thanks!

2023-02-21 20:24 UTC, Iniquitatis requested changes

2023-02-21 20:24 UTC, Iniquitatis commented on modules/gdscript/tests/scripts/analyzer/features/type_test_usage.gd
> +	var const_b_array: Variant = [] as Array[B]
```suggestion
	const const_b_array: Variant = [] as Array[B]
```