Ensure that C# script names (and therefore class names) are valid identifiers
godotengine/godot pull request #74330
Opened 2023-03-03 23:47 UTC by aleksrutins

This fixes #74307.
Previously, C# script names (and therefore class names) were not limited to valid C# identifiers, which could cause problems. This PR limits C# script names to valid identifiers.

2023-03-04 00:01 UTC, raulsntos commented
Thanks for contributing!

I think we should be able to use `String::is_valid_identifier` for the check.

Also, make sure to squash the commits. See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

2023-03-04 10:10 UTC, RedworkDE commented
Actually `TS->is_valid_identifier` should probably be used instead, since C# allows Unicode in identifiers.
(The C# and Unicode definition of an identifier are slightly different, in that C# allows `Category Other, subcategory format` characters and Unicode allows some chars backwards compatibility with previous versions of the standard, which C# doesn't do, but the definitions are probably close enough that the differences don't really matter).

2023-03-04 12:16 UTC, aleksrutins commented
Does C# also support `$` as a valid identifier character, or am I confusing it with JavaScript?

2023-03-04 12:50 UTC, RedworkDE commented
No, `$` is not allowed in an identifier.

2023-03-04 12:56 UTC, RedworkDE commented on modules/mono/csharp_script.cpp
> +
There is some whitespace on this line that should be removed.

2023-03-04 14:12 UTC, raulsntos commented
> Actually `TS->is_valid_identifier` should probably be used instead, since C# allows Unicode in identifiers.

That makes sense to me. I'm not sure that the text server is always available, but I think it's fine. TextEdit seems to use it without wrapping it in if checks so I guess we can assume it's always available.

2023-03-04 14:13 UTC, raulsntos requested changes

2023-03-04 14:13 UTC, raulsntos commented on modules/mono/csharp_script.cpp
> +	if(!ts->is_valid_identifier(class_name)) {
We can use the macro instead.

```suggestion
	if (!TS->is_valid_identifier(class_name)) {
```

2023-03-04 14:38 UTC, raulsntos commented
You may want to configure your IDE to use clang-format to follow our code style. See https://docs.godotengine.org/en/stable/contributing/development/code_style_guidelines.html#using-clang-format-locally.

2023-03-04 15:47 UTC, raulsntos approved these changes
LGTM

2023-03-04 22:26 UTC, neikeq approved these changes

2023-03-05 12:39 UTC, merged

2023-03-05 12:42 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2023-03-05 12:43 UTC, aleksrutins commented
Thanks! I hope to contribute more in the future.

2023-03-13 20:52 UTC, YuriSizov commented
Cherry-picked for 4.0.1.