Code style improvements to text_edit and related
godotengine/godot pull request #74623
Opened 2023-03-08 22:08 UTC by MewPurPur

Simplifies a bit of code and adjusts comments to abide by the comment style we use nowadays in `text_edit.cpp`, `code_edit.cpp`, `code_editor.cpp`. Replaces things like `carets[caret_idx].selection.from_line` with `get_selection_from_line(caret_idx)` where appropriate. Fixes a typo in TextEdit docs.

I have a few PRs on TextEdit and I keep adjusting these things along the way and cluttering my diff, making them harder to review, so it would be nice to get this in separately.

2023-03-09 11:59 UTC, MewPurPur commented
Whaaat? C'mon, how are my cosmetic changes making tests fail

2023-03-09 21:07 UTC, Paulb23 requested changes
I would be careful with replacing `carets[caret_idx].selection.` it's sometimes used to access the selection when it has not yet been created or has already been removed.

There are a couple of prints in the unit tests that indicate some of these fall under that banner.

2023-03-10 09:21 UTC, MewPurPur commented on editor/code_editor.cpp
> +			} else {
Hmm, okay, I did this for consistency with the other move_lines function.

2023-03-10 09:24 UTC, MewPurPur commented
Which prints? I noticed this and I think I fixed it, AFAIK this is only done in methods that handle particularly selections (`get_selection_[something]`, `set_selection_[something]`, and `update_selection_[something]`)

2023-03-10 10:32 UTC, MewPurPur commented
What I said is correct, however, I did forget to leave it alone in `update_selection_mode_line()`.

2023-04-17 16:59 UTC, Paulb23 approved these changes
Looks okay to me.

2023-04-17 17:07 UTC, YuriSizov approved these changes

2023-04-17 17:08 UTC, merged