[TextEdit] Expose all auto-wrap modes, use TextServer auto-wrap enum instead of custom one.
godotengine/godot pull request #74813
Opened 2023-03-12 11:21 UTC by bruvzg

Fixes https://github.com/godotengine/godot/issues/74256
Fixes https://github.com/godotengine/godot/issues/74812

2023-03-21 10:40 UTC, YuriSizov approved these changes
This looks like a good feature, but it does break compatibility. So we need to make sure existing projects won't be broken when opened in 4.1.

2023-03-21 17:54 UTC, Paulb23 requested changes, later dismissed
I think there are two types of wrapping here, the text server for how to wrap, and `TextEdit` when to wrap. For example if adding a new wrap mode at the guidelines rather then the control boundary. Shouldn't we separate these into two properties?

2023-03-22 08:31 UTC, YuriSizov commented
I think that would just affect the width parameter somewhere. So it's not necessary to introduce some special wrapping mode for it, just a flag?

2023-03-25 14:44 UTC, Paulb23 commented
No it needs to be wrapped, as there could be an option to allow mixed i.e fix column or viewport whichever is smallest, that cannot be conveyed with a width parameter (See VSCode). That was the intended purpose of this property.

2023-03-25 15:03 UTC, YuriSizov commented
> fix column or viewport whichever is smallest, that cannot be conveyed with a width parameter

That still sounds like something that is conveyed with a width.

So we have two things to handle here:
- What's the bounding box for the text (i.e. where to wrap),
- And how to handle text wrapping (i.e. how to wrap).

The control can decide on the bounding box whichever way it wants. It can use its own rect, it can add extra constraints like the guide line, etc. From what I'm seeing, the enum that has been removed in this PR, `LineWrappingMode`, does not implement any of that yet. Instead if provides options similar to the `TextServer::AutowrapMode` enum, but more limited.

If the intend for the existing enum is to be extended to support options that you describe, then we can keep it. But then the new enum should still be added and exposed to the `TextEdit` API to allow defining the wrapping behavior itself.

But then the existing enum remains with a conflicting option, `LINE_WRAPPING_NONE`, which duplicates the text server behavior option. If we remove `LINE_WRAPPING_NONE`, then the `LineWrappingMode` enum is left with a single option for defining boundaries, and that means it doesn't do anything at this point. So IMO we should just replace the enum like this PR does, and then reintroduce it in some way later, as you implement those extended wrapping boundary options.

2023-04-02 15:59 UTC, Paulb23 commented
Yes the intent was to prevent breaking compatibility during 4.0, leaving room for the functionality to be extended. 

I think I like the idea of moving this to a separate API an leaving the current enum with one option, as I don't think `TextEdit` has a way to override the `TextServer` enum. That way we can add `set_autowrap_mode` methods which would align this functionary with the other control nodes i.e  `Label`, `Label3D` and `RichTextLabel`.

2023-06-13 07:33 UTC, bruvzg commented on tests/scene/test_text_edit.h
> +	CHECK(text_edit->get_last_full_visible_line_wrap_index() == 0);
I do see any logic in these calculations, so I have only adjusted values to match real ones. Default `TextEdit` wrapping behavior should not be change, and the only reason this test was passing - `set_line_wrapping_mode` was not calling `queue_redraw();` and updating wrapping until something else triggered redraw.

2023-06-13 07:34 UTC, bruvzg commented
Updated to use separate property.

2023-06-15 13:51 UTC, akien-mga approved these changes

2023-06-15 14:29 UTC, merged