Change to_utf8 to to_utf8_buffer in remaining docs
godotengine/godot pull request #74885
Opened 2023-03-13 22:15 UTC by vmedea

The method `to_utf8` doesn't exist in Godot 4, but is still mentioned in the documentation in some places. Replace it with the new name `to_utf8_buffer`.

2023-03-13 22:32 UTC, Calinou submitted a review, later dismissed
Please don't edit files in `translations/`, as these are automatically generated following Weblate.

2023-03-13 22:35 UTC, vmedea commented
Thanks. I've removed the `.po` changes.

2023-04-09 13:38 UTC, MewPurPur commented
Please squash your commits as explained here.

https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

Other than this the changes are all good now.

2023-04-09 14:23 UTC, vmedea commented
done.. it's one commit now

2023-04-10 11:18 UTC, YuriSizov approved these changes

2023-04-10 11:20 UTC, YuriSizov requested changes
This looks good, but we should also update the C# samples. Changes there should be similar, e.g. `ToUtf8Buffer`.

2023-04-10 12:58 UTC, vmedea commented
Thanks… added C# changes too.

2023-04-10 14:23 UTC, YuriSizov commented on doc/classes/HMACContext.xml
> +		    var msg2 = "super duper secret".to_utf8_buffer()
You missed C# examples here.

2023-04-10 14:24 UTC, YuriSizov approved these changes
Missed one, but good otherwise :)

2023-04-10 19:17 UTC, vmedea commented on doc/classes/HMACContext.xml
> +		    var msg2 = "super duper secret".to_utf8_buffer()
Whoops. Should be fixed now.

2023-04-10 19:57 UTC, merged

2023-04-10 19:57 UTC, YuriSizov commented
Thanks!

2023-04-24 12:18 UTC, YuriSizov commented
Cherry-picked for 4.0.3.

2023-04-26 11:28 UTC, vmedea commented
Thank you!

-------- Original Message --------
On 24 Apr 2023, 13:18, Yuri Sizov wrote:

> Cherry-picked for 4.0.3.
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/godotengine/godot/pull/74885#issuecomment-1520051873), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AKINZTUWKCU2GRKZNDTLYDTXCZVTFANCNFSM6AAAAAAVZVHSVM).
> You are receiving this because you authored the thread.Message ID: ***@***.***>