Implemented UWP version of OS.get_unique_id function.
godotengine/godot pull request #75136
Opened 2023-03-20 06:28 UTC by DylanCheetah

I have successfully implemented the `OS.get_unique_id` function for 
Universal Windows builds of Godot.

Here is a basic overview of how it works:
1. fetch package specific token
2. get an IBuffer interface for the hardware specific ID of the package 
3. create a data reader to read the hardware ID data
4. allocate a buffer to hold the hardware ID data
5. read the hardware ID data into the buffer
6. convert the hardware ID date into a hexadecimal string
7. free the buffer
8. return the hexadecimal ID string

2023-03-20 18:13 UTC, DylanCheetah commented
I have used clang-format 13 to fix the style issues and corrected the commit.

2024-01-05 09:58 UTC, akien-mga requested changes
Sorry for the late review, we don't have an active maintainer for the UWP platform in 3.x currently.

I haven't reviewed the code in depth but if it works, it should be fine. Maybe @panreyes can help testing?

You also need to update the docs which say that this method isn't supported on UWP.
```diff
diff --git a/doc/classes/OS.xml b/doc/classes/OS.xml
index e20f6c0c1a..a393cdff8e 100644
--- a/doc/classes/OS.xml
+++ b/doc/classes/OS.xml
@@ -550,7 +550,7 @@
 			<description>
 				Returns a string that is unique to the device.
 				[b]Note:[/b] This string may change without notice if the user reinstalls/upgrades their operating system or changes their hardware. This means it should generally not be used to encrypt persistent data as the data saved before an unexpected ID change would become inaccessible. The returned string may also be falsified using external programs, so do not rely on the string returned by [method get_unique_id] for security purposes.
-				[b]Note:[/b] Returns an empty string on HTML5 and UWP, as this method isn't implemented on those platforms yet.
+				[b]Note:[/b] Returns an empty string on HTML5, as this method isn't implemented on this platform yet.
 			</description>
 		</method>
 		<method name="get_unix_time" qualifiers="const">
```

2024-01-05 09:58 UTC, akien-mga commented on platform/uwp/os_uwp.cpp
> +	return id;
```suggestion
	// Get the hardware token and read it into an array of bytes.
	HardwareToken ^ token = HardwareIdentification::GetPackageSpecificToken(nullptr);
	IBuffer hwId = token->Id;
	DataReader ^ dr = DataReader::FromBuffer(hwId);
	uint8_t *data = new uint8_t[hwId->Length];
	dr->ReadBytes(Platform::ArrayReference<uint8_t>(data, hwId->Length));

	// Convert the byte array to hexadecimal.
	String id;
	char hexStr[3] = "00";

	for (int i = 0; i < hwId->Length; i++) {
		// Convert next byte to hexadecimal.
		sprintf(hexStr, "%x", (int)data[i]);

		if (data[i] < 16) {
			hexStr[1] = hexStr[0];
			hexStr[0] = '0';
		}

		// Add the next 2 hexits to the ID string.
		id += hexStr;
	}

	// Free the temporary data array and return the device ID.
	delete[] data;
	return id;
```

We don't use `auto`, and want the types to be explicit to code reviewers. I had to look up the MSDN documentation to know what type this is.

Also style fixes to the comments.

2024-01-05 16:00 UTC, panreyes commented
This is what OS.get_unique_id() returns in my Windows 11 PC running Godot in UWP:
![image](https://github.com/godotengine/godot/assets/13276823/8234750d-ac2d-4a05-bdce-f4206bc3c1ca)

And this is what returns in a Windows 11 VM:
![image](https://github.com/godotengine/godot/assets/13276823/0fbaac86-6edd-4fdc-860b-b7b599d70d72)

I reinstalled the Windows 11 VM and the ID was still the same :)
Seems that it's working well enough!

2024-01-05 18:25 UTC, DylanCheetah commented
> Sorry for the late review, we don't have an active maintainer for the UWP platform in 3.x currently.
> 
> I haven't reviewed the code in depth but if it works, it should be fine. Maybe @panreyes can help testing?
> 
> You also need to update the docs which say that this method isn't supported on UWP.
> 
> ```diff
> diff --git a/doc/classes/OS.xml b/doc/classes/OS.xml
> index e20f6c0c1a..a393cdff8e 100644
> --- a/doc/classes/OS.xml
> +++ b/doc/classes/OS.xml
> @@ -550,7 +550,7 @@
>  			<description>
>  				Returns a string that is unique to the device.
>  				[b]Note:[/b] This string may change without notice if the user reinstalls/upgrades their operating system or changes their hardware. This means it should generally not be used to encrypt persistent data as the data saved before an unexpected ID change would become inaccessible. The returned string may also be falsified using external programs, so do not rely on the string returned by [method get_unique_id] for security purposes.
> -				[b]Note:[/b] Returns an empty string on HTML5 and UWP, as this method isn't implemented on those platforms yet.
> +				[b]Note:[/b] Returns an empty string on HTML5, as this method isn't implemented on this platform yet.
>  			</description>
>  		</method>
>  		<method name="get_unix_time" qualifiers="const">
> ```

I agree with your suggestions. It looks cleaner now. The changes have been committed.

2024-01-10 12:24 UTC, akien-mga commented
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

2024-01-10 12:26 UTC, akien-mga commented
I squashed the commits and amended the doc change myself, should be ready to merge now.

2024-01-10 12:26 UTC, akien-mga approved these changes

2024-01-10 13:13 UTC, merged

2024-01-10 13:13 UTC, akien-mga commented
Thanks!

2024-01-17 10:26 UTC, akien-mga commented on platform/uwp/os_uwp.cpp
> +	return id;
One pro of `auto` seems to be that it didn't get the type wrong, I suppose :P 
I ran into an issue with VS 2017, this seems to solve it: https://github.com/godotengine/godot/pull/87288