Fixed auto-scroll in Animation window
godotengine/godot pull request #75322
Opened 2023-03-25 14:37 UTC by DarellLdark

Fixed auto-scroll in Animation window
Linked issue: https://github.com/godotengine/godot/issues/74185

Just added one line in _select_animation, it's possible the best place to add scroll to selected item

2023-05-26 12:51 UTC, TokageItLab requested changes

2023-06-17 08:24 UTC, DarellLdark commented on editor/plugins/sprite_frames_editor_plugin.cpp
> +	animations->scroll_to_item(selected);
Did I get you correctly: you want to move `scroll_to_item() `call to _update_library() function?

2023-06-17 09:10 UTC, TokageItLab commented on editor/plugins/sprite_frames_editor_plugin.cpp
> +	animations->scroll_to_item(selected);
Yes, please see the above example.

2023-07-24 17:16 UTC, YuriSizov commented
Superseded by https://github.com/godotengine/godot/pull/79743. Your contribution has been credited by the other PR, so thanks for your work and congrats with your first Godot PR!

2023-07-24 17:16 UTC, closed without merging