Expose NavigationAgent path postprocessing and pathfinding algorithm options
godotengine/godot pull request #75326
Opened 2023-03-25 16:45 UTC by smix8

Exposes the path postprocessing and pathfinding algorithm options of the NavigationAgent internal NavigationPathQueryParameters object.

Basically a requirement that the NavigationAgent can be properly used with other navigation layouts and movement types like e.g. movement restricted to grids.

Should be cherry-picked for Godot 4.0.x

2023-03-25 18:56 UTC, DarkKilauea requested changes

2023-03-25 18:56 UTC, DarkKilauea commented on scene/2d/navigation_agent_2d.cpp
> +	navigation_query->set_pathfinding_algorithm(p_pathfinding_algorithm);
Need to update the local field on the node as well.

Applies to the other setters in this PR as well.

2023-03-31 06:22 UTC, DarkKilauea approved these changes

2023-04-03 12:10 UTC, akien-mga approved these changes

2023-04-03 14:19 UTC, merged

2023-04-03 14:36 UTC, akien-mga commented
Thanks!

2023-04-07 14:52 UTC, YuriSizov commented
Cherry-picked for 4.0.3.