Properly set sky_cover property of sky_material to Nil in setter
godotengine/godot pull request #75469
Opened 2023-03-29 18:28 UTC by ibotha

issue [74259](https://github.com/godotengine/godot/issues/74259) seems to be caused by being the value being set to "RID()" in the setter for the sky_cover property. I was able to fix this by setting the sky cover property back to Variant::Nil when it is reset in the editor.

I have tested this locally by running the engine before the fix, seeing the bug is present, then running it after the fix and seeing it works as expected.

2023-03-29 18:33 UTC, ibotha commented
My understanding of the engine is limited. If it is meant to be the case that RID() behaves as a nil value then I can make that change too

2023-03-29 18:59 UTC, ibotha commented
Noticed the formatting caused one of the tests to fail so I fixed it

2023-05-03 19:19 UTC, clayjohn approved these changes
Looks good! This pattern is used in a few other places in the codebase, so we will need to keep our eyes open to other areas where this might cause an issue

2023-05-05 12:38 UTC, mhilbrunner requested changes, later dismissed
See clayjohn's comment.

2023-05-16 17:02 UTC, ibotha commented
Alright, I have updated the other sky materials, sorry it took a while for me to get back to this.

2023-05-21 18:35 UTC, ibotha commented
> Looks great! The final step before merging is to squash all the commits together so that the whole PR only contains 1 big commit with all your changes. We like to merge one commit at a time to keep the git history clean and navigable.
> 
> If you don't know how to do that, we have a helpful tutorial in the official documentation https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

Alright, The commit has been squashed

2023-05-21 20:58 UTC, clayjohn approved these changes

2023-05-22 12:13 UTC, merged

2023-06-16 16:14 UTC, YuriSizov commented
Cherry-picked for 4.0.4.