Fix linux fullscreen mode doesn't preserve maximized state
godotengine/godot pull request #75838
Opened 2023-04-08 21:06 UTC by jmb462

Fix #75804

Unlike what happens under Windows, the maximized state was not saved when switching to full screen.
Added  a ``was_maximized`` variable to restore previous windowed state while leaving fullscreen.

2023-06-19 22:29 UTC, Calinou approved these changes
Tested locally (rebased on top of `master` 764193629ff0bac11c4a6ddfa946f1dd3d841799), it works. The logic looks good to me.

2023-06-20 07:03 UTC, akien-mga requested changes
Won't this fail if you have multiple windows?

In the Windows platform there is also a `was_maximized` boolean but it's part of the `WindowData`, so it's window-specific. Here it's a single boolean for the whole DisplayServer so maximizing or windowing any window will impact the value, causing unexpected behavior.

Also I assume the macOS DisplayServer needs the same treatment?

2023-11-13 17:07 UTC, YuriSizov commented
I guess this is related to (and the opposite of) https://github.com/godotengine/godot/pull/84504?

2025-11-20 21:31 UTC, Repiteo commented
Superseded by #85427

2025-11-20 21:31 UTC, closed without merging