Export: Modify template without rcedit, fix #73497
godotengine/godot pull request #75950
Opened 2023-04-11 18:39 UTC by pkowal1982

Using rcedit is little problematic so I've created a POC which shows how it can be dropped.
PR contains only crucial code, if it's decided to go this way I'll fix loose ends.
For now code drops old resources section and replaces it with brand new created from scratch.
Questions which I can think of:
1. How to test this solution properly?
2. Do we need to copy anything from original resources?
3. Is there a minimum set of information which user should provide?
4. All the editor code regarding rcedit should be probably removed in another dedicated PR?

2023-04-11 22:50 UTC, Calinou commented
> All the editor code regarding rcedit should be probably removed in another dedicated PR?

I think the rcedit code should be removed in the same PR, as we don't want to support both approaches at the same time.

2023-04-12 06:35 UTC, akien-mga commented
> > All the editor code regarding rcedit should be probably removed in another dedicated PR?
> 
> I think the rcedit code should be removed in the same PR, as we don't want to support both approaches at the same time. While we try to preserve compatibility across 4.x, this mainly applies to the API, not the export system.
> 
> (Also, it should be possible to create compatibility handlers to automatically update old entries' names in the Windows export presets to the new names.)

I think it's fine to first assess whether this approach is good, before doing the extra work to remove the old. If it's not clear whether this PR wouldn't be merged (it hasn't been reviewed yet), there's no point doing removing the code it's meant to replace.

2023-05-01 06:44 UTC, sammypanda commented
rcedit go away for integrated solution soon? :pleading_face::pray:

2023-07-17 03:09 UTC, fire commented
I am interested in getting this to work since I export from Linux for Windows.

2023-12-21 22:04 UTC, Maran23 commented
I also think this is a good idea since it has multiple advantages:
- No `rcedit` needed on Windows
- Project can be exported on Linux or MacOS without using Wine (for this particular feature)

Note: This PR needs a rebase. I would be happy to test this as I always used `rcedit` in the past.

2023-12-22 13:29 UTC, pkowal1982 commented
Ok, rebased it so you can test it.

Also fixed a bug introduced [here](https://github.com/godotengine/godot/commit/9a33c97c2a1e46f79426fa091c271d273a458bb8) which prevented exporting console template.
Looks like it never worked, probably not too popular feature.

2023-12-22 13:37 UTC, YuriSizov commented
> Also fixed a bug introduced [here](https://github.com/godotengine/godot/commit/9a33c97c2a1e46f79426fa091c271d273a458bb8) which prevented exporting console template.
> Looks like it never worked, probably not too popular feature.

This is incorrect. The official export templates (and the editor executable) are named with the underscore:

![image](https://github.com/godotengine/godot/assets/11782833/7ab80d06-62bb-432e-bd25-13a4bc1de2dd)

The name with a period is what is produced by our buildsystem by default, but the actual distribution is renamed. So this code was correct and should not be modified.

2023-12-22 13:57 UTC, pkowal1982 commented
Ok, the ones built on github contained in artifact windows-template.zip are named:
**godot.windows.template_release.x86_64.console.exe**

Would be nice to change the github workflow probably to be consistent.

2023-12-22 14:07 UTC, YuriSizov commented
@pkowal1982 That's not related to the CI. As I mentioned, that's how the name is generated by the buildsystem. It uses a number of suffixes to differentiate between build options, but those get removed for the official distribution. It may be worth discussing the naming scheme of the official distribution, but in the meantime we should not break the system in favor of CI artifacts which are not supposed to be used in development anyway.

2023-12-22 18:46 UTC, pkowal1982 commented
Ok, reverted **_console** -> **.console** change. Though I think it would be nice
to change the CI workflow in another PR to produce _console named templates.
Now editor built from master does not work smoothly with templates built from the same branch.

2024-01-07 15:51 UTC, Maran23 reviewed
Right now, I can not really test this as I always get `Wrong number of icon images.`.
With the old implementation, I just got a bunch of warnings but the export worked.

2024-01-07 16:06 UTC, Maran23 commented
Tested now with an icon containing all 6 required image formats.
Looks good. I can confirm that the icon and all the metadata is set correctly. Nice!
Results below (Note: My Windows is set to German)

| Godot 4.2.1| Godot 4.3.dev (this PR) |
| - | - |
| ![image](https://github.com/godotengine/godot/assets/66004280/a19c9639-3642-4a5a-beaa-8448f370c34e) | ![image](https://github.com/godotengine/godot/assets/66004280/8c8a453c-359c-428f-b072-77f4e5af2a41) |

I would still recommend that if the icon does not contain all 6 image formats, we just print a warning as before, and continue with the modification.

2024-09-04 20:10 UTC, Maran23 commented on platform/windows/export/template_modifier.cpp
> +		print_error("Wrong number of icon images.");
Is it possible like with rcedit to also do that operation with just one icon image? Would be nice for backward compatibility.

2024-09-04 21:44 UTC, fire commented
@KoBeWi What are you thoughts about modifying the template without rcedit?

2024-09-04 21:47 UTC, KoBeWi commented
This reimplements what rcedit does and makes it built-in, no? If it works the same as before then why not I guess.

2024-09-04 21:56 UTC, Maran23 commented
And it works on other platforms as well. Currently you need to use Wine on Linux to run rcedit to modify the .exe. Which is annoying for cross platform creation of the games.

2024-09-04 21:59 UTC, fire reviewed
* design proposal review: I think it's a great idea
* technical review: unreviewed
* style review: @AThousandShips Can you take a look?
* test plan: untested

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.h
> +		Vector<uint8_t> &add_length(Vector<uint8_t> &bytes) const;
```suggestion
		Vector<uint8_t> &add_length(Vector<uint8_t> &r_bytes) const;
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.h
> +		StringStructure(String p_key, String p_value);
```suggestion
		StringStructure(const String &p_key, const String &p_value);
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	for (Vector<uint8_t> image : p_group_icon.images) {
```suggestion
	for (const Vector<uint8_t> &image : p_group_icon.images) {
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +TemplateModifier::VersionInfo TemplateModifier::_create_version_info(const HashMap<String, String> &strings) const {
```suggestion
TemplateModifier::VersionInfo TemplateModifier::_create_version_info(const HashMap<String, String> &p_strings) const {
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	for (KeyValue<String, String> E : strings) {
```suggestion
	for (const KeyValue<String, String> &E : p_strings) {
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +Error TemplateModifier::_truncate(const String &path, uint32_t size) const {
```suggestion
Error TemplateModifier::_truncate(const String &p_path, uint32_t p_size) const {
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +Error TemplateModifier::_modify_template(const Ref<EditorExportPreset> &p_preset, const String &template_path, bool p_console_icon) const {
```suggestion
Error TemplateModifier::_modify_template(const Ref<EditorExportPreset> &p_preset, const String &p_template_path, bool p_console_icon) const {
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +Vector<TemplateModifier::SectionEntry> TemplateModifier::_get_section_entries(const String &executable_path) const {
```suggestion
Vector<TemplateModifier::SectionEntry> TemplateModifier::_get_section_entries(const String &p_executable_path) const {
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +Error TemplateModifier::modify(const Ref<EditorExportPreset> &p_preset, const String &template_path, bool p_console_icon) {
```suggestion
Error TemplateModifier::modify(const Ref<EditorExportPreset> &p_preset, const String &p_template_path, bool p_console_icon) {
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	for (IconEntry icon_entry : icon_entries) {
```suggestion
	for (const IconEntry &icon_entry : icon_entries) {
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +		return;
```suggestion
		ERR_FAIL_MSG("Wrong icon file type.");
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +		return;
```suggestion
		ERR_FAIL_MSG("Wrong number of icon images.");
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ERR_FAIL_COND_V(error, ERR_CANT_OPEN);
```suggestion
	ERR_FAIL_COND_V(error != OK, ERR_CANT_OPEN);
```
Be consistent about error check here (you use `!= OK` below)

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ERR_FAIL_COND_V(error, ERR_CANT_CREATE);
```suggestion
	ERR_FAIL_COND_V(error != OK, ERR_CANT_CREATE);
```

2024-09-05 08:37 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	for (StringStructure string : strings) {
```suggestion
	for (const StringStructure &string : strings) {
```

2024-09-05 14:11 UTC, KoBeWi commented
Tested on Windows. Using svg icon prints "Wrong icon file type.", using ico generated with GIMP iconify extension, which I'm always using, results in "Wrong number of icon images.". The executables end up without any icon. Both cases worked perfectly before the change.

2025-03-22 02:42 UTC, ztc0611 commented
@pkowal1982 are you still working on this? I'm also interested in this functionality. Not sure if there's anything I can do to help but I'd like to try. 🙂

2025-03-24 11:15 UTC, pkowal1982 commented
@ztc0611 Yeah, now as 4.4 is released I'll give it some love.

2025-03-30 17:52 UTC, fire commented
What tasks are remaining on this?

2025-03-30 19:10 UTC, pkowal1982 commented
I would say it's complete. If it passes code review it needs only thorough testing.

2025-03-30 19:22 UTC, KoBeWi commented on platform/windows/export/template_modifier.h
> +#include "editor/export/editor_export_platform_pc.h"
These can be moved to cpp file, with necessary classes forward-declared.
Not sure about simple types though (Vector, String), you could maybe include `variant.h` for that.

2025-03-30 19:35 UTC, KoBeWi commented on platform/windows/export/template_modifier.h
> +		uint32_t image_offset;
You need to initialize all elements (ints).
Same in other structs.

2025-03-30 19:46 UTC, KoBeWi approved these changes
The icons now get modified correctly. I also tested metadata and they get properly written too.

2025-03-30 20:58 UTC, bruvzg requested changes
This is not working with x86-32 and arm64 release templates with embedded PCK enabled, rcedit do.

2025-03-30 20:58 UTC, bruvzg commented on platform/windows/export/template_modifier.cpp
> +	template_file->store_buffer(relocations);
What's this supposed to do? I assume it's intended to read the existing `.reloc` section to write it back later, but it's using `pointer_to_raw_data` after it was modified, and writing garbage (since non-zeroed resize is used) to the file instead of reading.

2025-04-12 18:16 UTC, pkowal1982 commented
Ok, fixed this .reloc copying. I can't test the arm64 build but on my Windows 7 the arm64 embedded export does not show icon. Doesn't matter if it's modified or not.
Tried to export arm64 project with 4.4.1 and it behaves the same, embedded versions do not show proper icon on my pc.

2025-05-26 06:40 UTC, bruvzg commented
With the latest changes it seems to be completely broken and not working with any architecture exports, all fail with `Magic number has wrong value` errors.

2025-06-04 09:26 UTC, pkowal1982 commented
@bruzvg Somehow calling FileAccess::open(p_template_path, FileAccess::READ_WRITE) twice on Windows was returning an error. For Linux it was working.
Resolved the issue and I think it's ready for another try.

2025-06-04 10:13 UTC, bruvzg approved these changes
Now it seems to be working with all architectures, icons and metadata are set correctly.

2025-06-04 10:17 UTC, AThousandShips approved these changes

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.h
> +	Vector<SectionEntry> _get_section_entries(Ref<FileAccess> executable) const;
```suggestion
	uint32_t _get_pe_header_offset(Ref<FileAccess> p_executable) const;
	Vector<SectionEntry> _get_section_entries(Ref<FileAccess> p_executable) const;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryTable root_directory_table = ResourceDirectoryTable();
```suggestion
	ResourceDirectoryTable root_directory_table;
```
Unnecessary default

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryEntry rt_icon_entry = ResourceDirectoryEntry();
```suggestion
	ResourceDirectoryEntry rt_icon_entry;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryEntry rt_group_icon_entry = ResourceDirectoryEntry();
```suggestion
	ResourceDirectoryEntry rt_group_icon_entry;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryEntry rt_version_entry = ResourceDirectoryEntry();
```suggestion
	ResourceDirectoryEntry rt_version_entry;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryTable icon_table = ResourceDirectoryTable();
```suggestion
	ResourceDirectoryTable icon_table;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +		ResourceDirectoryEntry icon_entry = ResourceDirectoryEntry();
```suggestion
		ResourceDirectoryEntry icon_entry;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +		ResourceDirectoryTable language_icon_table = ResourceDirectoryTable();
```suggestion
		ResourceDirectoryTable language_icon_table;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +		ResourceDirectoryEntry language_icon_entry = ResourceDirectoryEntry();
```suggestion
		ResourceDirectoryEntry language_icon_entry;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryTable group_icon_name_table = ResourceDirectoryTable();
```suggestion
	ResourceDirectoryTable group_icon_name_table;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryEntry group_icon_name_entry = ResourceDirectoryEntry();
```suggestion
	ResourceDirectoryEntry group_icon_name_entry;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryTable group_icon_language_table = ResourceDirectoryTable();
```suggestion
	ResourceDirectoryTable group_icon_language_table;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryEntry group_icon_language_entry = ResourceDirectoryEntry();
```suggestion
	ResourceDirectoryEntry group_icon_language_entry;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryTable version_table = ResourceDirectoryTable();
```suggestion
	ResourceDirectoryTable version_table;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryEntry version_entry = ResourceDirectoryEntry();
```suggestion
	ResourceDirectoryEntry version_entry;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryTable version_language_table = ResourceDirectoryTable();
```suggestion
	ResourceDirectoryTable version_language_table;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	ResourceDirectoryEntry version_language_entry = ResourceDirectoryEntry();
```suggestion
	ResourceDirectoryEntry version_language_entry;
```

2025-06-04 10:17 UTC, AThousandShips commented on platform/windows/export/template_modifier.cpp
> +	GroupIcon group_icon = GroupIcon();
```suggestion
	GroupIcon group_icon;
```

2025-06-04 14:08 UTC, akien-mga commented
Tested on Linux and it seems to work great, both for setting the icon and other metadata. Checked the resulting binary with `exiftool` for metadata (version, product name, etc.) and confirmed that the icon is correct in Dolphin.

I think we can remove the rcedit code too. Is there any way it would still be used currently?

2025-06-04 14:15 UTC, bruvzg commented
> I think we can remove the rcedit code too. Is there any way it would still be used currently?

Is there any left, it seems to be removed.

2025-06-04 14:18 UTC, bruvzg commented
> I think we can remove the rcedit code too. Is there any way it would still be used currently?

Found few lines related to the editor setting which can be removed, the rest is already gone.

https://github.com/godotengine/godot/blob/1b37dacc1842779fb0d03a5b09026f59c13744fc/platform/windows/export/export_plugin.cpp#L826-L829

https://github.com/godotengine/godot/blob/1b37dacc1842779fb0d03a5b09026f59c13744fc/platform/windows/export/export.cpp#L44-L45

2025-06-04 14:30 UTC, akien-mga commented
Yeah it's just a few, I found those:
```
platform/windows/export/export_plugin.cpp
524:    String tmp_icon_path = EditorPaths::get_singleton()->get_temp_dir().path_join("_rcedit.ico");
735:    String rcedit_path = EDITOR_GET("export/windows/rcedit");
736:    if (p_preset->get("application/modify_resources") && rcedit_path.is_empty()) {
737:            err += TTR("The rcedit tool must be configured in the Editor Settings (Export > Windows > rcedit) to change the icon or app information data.") + "\n";

platform/windows/export/export.cpp
44:     EDITOR_DEF_BASIC("export/windows/rcedit", "");
45:     EditorSettings::get_singleton()->add_property_hint(PropertyInfo(Variant::STRING, "export/windows/rcedit", PROPERTY_HINT_GLOBAL_FILE, "*.exe"));
52:     // On non-Windows we need WINE to run rcedit

editor/editor_property_name_processor.cpp
261:    capitalize_string_remaps["rcedit"] = "rcedit";
```
(The `_rcedit.ico` one is actually used by the new system, but maybe we can rename it to not refer to rcedit.)

And I guess we can remove the `wine` editor setting too, unless we use it for anything else:
```
$ rg '"export/windows/wine"'
platform/windows/export/export.cpp
53:     EDITOR_DEF_BASIC("export/windows/wine", "");
54:     EditorSettings::get_singleton()->add_property_hint(PropertyInfo(Variant::STRING, "export/windows/wine", PROPERTY_HINT_GLOBAL_FILE));
```

2025-06-04 14:38 UTC, bruvzg commented
Yes, `wine` is not used by anything else, so can be removed, it's only a setting and a `capitalize_string_remaps`.

https://github.com/godotengine/godot/blob/1b37dacc1842779fb0d03a5b09026f59c13744fc/platform/windows/export/export.cpp#L53-L54

2025-06-04 22:19 UTC, pkowal1982 commented
I've removed the aforementioned rcedit related code in additional commit so it's easier for track.
When ready and approved it'll be squashed.

2025-06-05 10:54 UTC, akien-mga approved these changes
Looks good to me. You can squash the commits and it's ready to merge.

2025-06-05 10:54 UTC, akien-mga commented on editor/editor_property_name_processor.cpp
> -	capitalize_string_remaps["rcedit"] = "rcedit";
There's also `wine` here which can be removed.

2025-06-05 15:28 UTC, merged

2025-06-05 15:30 UTC, akien-mga commented
Thanks! Amazing work :tada:

2026-07-23 16:23 UTC, glkdrlgkrlzflnjkgh commented
Now i need to get my rcedit install to a therapist- it doesnt have a purpose and is now depressed.
Which is mildy unfortunate.
(note: this is a joke.)