Update size or size cache when toggling `expand_icon` in `Button`
godotengine/godot pull request #75958
Opened 2023-04-12 01:40 UTC by Rindbee

When the `expand_icon` is switched, the size cache can be updated to solve the issue that the cache cannot be updated when the `OptionButton` is enabled with `fit_to_longest_item`.

Fix #68930.

2023-04-12 04:57 UTC, YeldhamDev commented
Feels a little hackish to just bring `_queue_refresh_cache()` back a class.

2023-04-12 22:45 UTC, Rindbee commented
When the properties of the parent class change, the way to notify the subclass, here all I can think of is a callback function or a signal. Maybe there's a better way than either of these. But it feels unnecessary to use a signal for this property change alone.

2023-05-02 14:07 UTC, KoBeWi approved these changes
It's hacky, but I can't really think of a better solution (we could make `set_expand_icon()` virtual, but it's meh). Maybe we could rename the method to something more generic, like `_expand_icon_toggled()`, but the current name is fine.

2023-05-16 17:09 UTC, YuriSizov commented
Yeah, it's hacky, but pretty minor. Can you please rename the method though, so its purpose clear? `_queue_update_size_cache` should do the trick.

2023-05-16 17:10 UTC, YuriSizov requested changes
Yeah, it's hacky, but pretty minor. Can you please rename the method though, so its purpose clear? _queue_update_size_cache should do the trick.

2023-05-16 22:10 UTC, Rindbee commented
OK, renaming is done.

2023-05-16 23:51 UTC, YuriSizov approved these changes

2023-05-17 09:27 UTC, merged

2023-05-17 09:27 UTC, akien-mga commented
Thanks!