Fix several drawing and logic issues in TabContainer
godotengine/godot pull request #7600
Opened 2017-01-21 18:12 UTC by RayKoopa

Tabs in `TabContainer` were drawn incorrectly and clicking the navigation buttons had no effect. This issue was probably introduced in an effort to allow tab alignment for https://github.com/godotengine/godot/issues/2207

- Fixes https://github.com/godotengine/godot/issues/7546: Navigation buttons left / right did not work.
- Navigation buttons were drawn outside of the control.
- Tabs were drawn outside of the available area and incorrectly aligned.
- Navigation buttons were drawn above tabs, making it impossible to use them.

Beyond rewriting the drawing and GUI logic, I also changed the method of retrieving all the nodes which are handled as tabs (this does not include non-`Control` children and toplevel ones). Most methods reimplemented iterating through the children and checking the controls, now the method `_get_tabs()` is used in each.

- Fixes a bug that caused `get_tab_count()` to return a wrong number of tabs as it did not check for toplevel controls.

2017-01-21 19:13 UTC, karroffel requested changes

2017-01-21 19:13 UTC, karroffel commented on scene/gui/tab_container.cpp
> +	Control *control = _get_tabs()[p_index]->cast_to<Control>();
bounds check?

2017-01-21 19:34 UTC, karroffel commented on scene/gui/tab_container.cpp
> +	Control *control = _get_tabs()[p_index]->cast_to<Control>();
oops, not needed here. Only called when iterating the tab list

2017-01-21 19:44 UTC, RayKoopa commented on scene/gui/tab_container.cpp
> +	int height = MAX(tab_bg->get_minimum_size().height,tab_fg->get_minimum_size().height);
I originally renamed the whole function to `_get_tab_height`; but the other `tabs.cpp` has a `_get_top_margin` asweel, so I kept it. I can rename the variable tho.

2017-01-21 21:13 UTC, karroffel approved these changes
Looks good. Tested it on my machine and worked good so far.

2017-02-27 07:56 UTC, akien-mga approved these changes
Looks good, though needs a rebase before I can merge.

Note for future PRs: please avoid to fix the formatting in code lines with no logic change, as it makes the diff much harder to read (and to generate for git/GitHub, so it does not show meaningful removal/addition blocks). That's partly why it took me so long to review the changes, as the diff is quite big.

2017-02-27 14:27 UTC, RayKoopa commented
I think I just rebased it and merged it with the more recent changes, then I got a mail you did the same. I don't know if it's fine now or not. Everything's green though so I guess that's a good sign.

2017-02-27 14:30 UTC, akien-mga commented
> I think I just rebased it and merged it with the more recent changes, then I got a mail you did the same. I don't know if it's fine now or not. Everything's green though so I guess that's a good sign.

Hehe that's why GitHub was showing me nonsense when I tried to review my own changes :D

You rebased it wrong though, as you kept your own version instead of the master one for the actually conflicting changes:
- `MD()` is now `D_METHOD()`
- `_SCS()` is no longer needed, just keep its string argument

That's what you get for making cosmetic changes to code you did not even change ;)

2017-02-27 14:31 UTC, RayKoopa commented
I actually changed those MD() calls to D_METHOD() and removed _SCS(). No idea why you cannot see that in my repo as of now.
And yes, let's please accelerate efforts in reformatting code. It's a hell to read at the moment.

2017-02-27 14:35 UTC, akien-mga commented
> I actually changed those MD() calls to D_METHOD() and removed _SCS(). No idea why you cannot see that in my repo as of now.

Then GitHub seems mistaken:
![image](https://cloud.githubusercontent.com/assets/4701338/23365161/4628b97c-fd02-11e6-96bb-b2b6b612887c.png)

> And yes, let's please accelerate efforts in reformatting code. It's a hell to read at the moment.

Yes, but not on code that you are not changing, that's just asking for trouble and makes diffs hard to read. The whole code base will be reformatted at once.

2017-02-27 14:37 UTC, akien-mga commented
See also https://github.com/RayKoopa/godot/blob/3218db7af33bf0b02bfae4d2b28aa4c9579c08d2/scene/gui/tab_container.cpp#L597-L621

2017-02-27 14:39 UTC, RayKoopa commented
Problem is that VS reformats parts automatically if I copy paste them or barely touched them. I can press Ctrl+Z to undo that but after changing most of the file anyway you just forget about it somewhen. I'll just leave my hands off Godot code until there are some coding standards.

And yes, it looks like some modification is hanging around in my local repository it doesn't wanna push. God git is great.

2017-02-27 14:40 UTC, akien-mga commented
You need to force push.

2017-02-27 14:40 UTC, akien-mga commented
> Problem is that VS reformats parts automatically if I copy paste them or barely touched them. I can press Ctrl+Z to undo that but after changing most of the file anyway you just forget about it somewhen.

I'm pretty sure you can configure your IDE not to do that.

2017-02-27 14:41 UTC, RayKoopa commented
Then copy pasting becomes stupid and I have to tab everything manually to the right indent.

2017-02-27 14:43 UTC, RayKoopa commented
I can try and have fun with git rebase i~2 or what it was to make my two commits one but I obviously forgot the exact command. :)

2017-02-27 14:44 UTC, akien-mga commented
`git rebase -i HEAD~2` (i.e. two commits (inclusive) on top of HEAD, the last commit).

2017-02-27 14:45 UTC, RayKoopa commented
And the commit number is the ID of the earliest commit I wanna merge into?

2017-02-27 14:46 UTC, akien-mga commented
I think so, or maybe it should be the commit before, which you can get with `that_earliest_commit^` IIRC (that's why I always use the `HEAD~X` trick as I can never remember it - maybe https://github.com/gleitz/howdoi could help :D)

2017-02-27 14:47 UTC, RayKoopa commented
`howdoi use git without going crazy`

E.g., trying a rebase at the moment. Stand by...

2017-02-27 14:48 UTC, RayKoopa commented
DID IT JUST WORK?!

2017-02-27 14:49 UTC, akien-mga commented
Yes, you nailed it :)

2017-02-27 14:54 UTC, RayKoopa commented
I will somewhen rewrite https://github.com/godotengine/godot/pull/7517 ontop of this as trying to rebase it to the most recent changes will be *snip*.

2017-02-27 14:59 UTC, akien-mga commented
> I will somewhen rewrite #7517 ontop of this as trying to rebase it to the most recent changes will be snip.

Once rewritten in a local branch, you can force push this local branch to your remote `gui_disabled_tabs` (used to make #7517) to update the PR. Or you can just make a new PR and we'll close #7517, as you prefer ;)

2017-02-27 15:01 UTC, RayKoopa commented
If that gets rid of the intermediate changes, then I can give that a try.

2017-02-27 15:06 UTC, akien-mga commented
Yes, it would just replace the current remote `gui_disabled_tabs` with whatever local branch you're force pushing. Assuming that you have a `gui_disabled_tabs_v2` local branch with the correct stuff, you'd update the PR with `git push --force myfork gui_disabled_tabs_v2:gui_disabled_tabs` (where `myfork` is the name of the remote that points to your fork, which might be `origin` if you cloned your own fork initially, and where the `git push` syntax is `git push <remote> <local branch>:<remote branch>`).

2017-02-27 16:03 UTC, merged