Fixed issues with @export var tooltip descriptions
godotengine/godot pull request #76147
Opened 2023-04-16 22:30 UTC by emr4378

https://github.com/godotengine/godot/issues/64432
Don't assume the category name can be used as the doc_name. Just leave it blank so it can be properly determined later on just before looking up cached doc info.

https://github.com/godotengine/godot/issues/63997
update_tree() populates description-related caches, but nothing was ever clearing them out so they'd forever hold onto the first description seen.

2023-04-17 12:40 UTC, YuriSizov commented
cc @anvilfolk

2023-04-17 13:43 UTC, anvilfolk commented
Oh, very interesting! I can't take a deeper look right now, but the idea behind the first fix sounds really cool!!!

I'm not super sure on the second one. When is `EditorInspector::_clear()` called? If it's very often, I believe it might basically invalidate the use of the cache, right? There's another PR that might address this, I believe: #71843, and I think that #70217 is related to #63997 as well!

2023-04-19 06:13 UTC, emr4378 commented
AFAICT `EditorInspector::_clear()` is only called in `EditorInspector::edit()` (so whenever the node selection changes) and at the start of `EditorInspector::update_tree()`. I put the doc cache clearing there since that's where other caches were being reset.

But I think you're right and it's invalidating the benefit of these particular caches. I'll dig around to find better spot(s) to clear them out.

2023-04-21 12:37 UTC, anvilfolk commented
Gave this a tiny little bit more thought - sorry it's taking a while, life has been hectic lately :)

So I suspect that #71843 is the better solution to #63997. Instead of clearing the cache completely, it simply stops caching doc information that comes from GDScripts. This means that the cache works fully with the static documentation like `@Globals` and native classes.

GDScript stuff is obtained from `EditorHelp/DocTools` when it's needed and not cached.

I haven't gotten around to testing the other fix in this PR, since that part of the code can be pretty subtle! But I love the simplicity of it 🥳 How much testing have to manage to do on it? Would you be able to check that e.g. resource docstrings still work? And can we be 100% certain that `doc_name` is always being set before being used? :)

I'll try to get some more testing done myself, time is just hard to come by atm! :)

2023-06-19 13:04 UTC, akien-mga commented
> #71843 fixes this but hasn't been accepted yet - I will come back to this once that's merged :)

It was merged ;)

2023-06-19 23:54 UTC, Calinou commented
The caching issue should be resolved in `master`, see https://github.com/godotengine/godot/issues/63997#issuecomment-1597884700.

2023-06-20 01:06 UTC, anvilfolk commented
Correct! At this point the only outstanding issue should be the category issue, which I will attempt to test :) It's a single-line fix :)

2023-06-20 09:49 UTC, KoBeWi commented
The cache changes should be removed

I looked into what `doc_name` line tries to do. Seems like it's supposed to use category name as type to fetch the property description. It obviously breaks with custom categories.
It was added by #64246, but removing this line does not reintroduce the original issue, so this change is ok.

2023-06-20 11:35 UTC, anvilfolk requested changes
As long as the cache lines are removed, as @KoBeWi said, this fixes the issue.

The PR description is correct: there's no reason that a category should attempt to set `doc_name`, which is used to index where documentation can be found. That should be set when the script's category is evaluated.

I couldn't find any regressions when using zero, one or multiple categories, or with the remaining categories, e.g. `Node`.

@emr4378, can you make these changes? :)

2023-06-20 11:35 UTC, anvilfolk commented on editor/editor_inspector.cpp
> +	class_descr_cache.clear();
```suggestion
```

2023-08-08 12:56 UTC, YuriSizov commented
Looks like there is unaddressed feedback in the discussion above. @emr4378 Are you still interested in contributing? This needs a rebase too.

2023-08-09 02:37 UTC, anvilfolk commented
I'd say if someone with privileges for it wanted to amend this commit leaving only the removal of the `doc_name = p.name;` line, this would be good to merge. Sounds like the OP might be inactive at the moment, but could still be credited for fixing that bug :)

2023-09-30 20:01 UTC, akien-mga commented
I updated this PR myself as advised by @anvilfolk, as OP seems to be inactive.

Should be ready to merge now.

2023-09-30 20:01 UTC, akien-mga approved these changes

2023-09-30 20:08 UTC, YuriSizov commented
> Should be ready to merge now.

I wanted to wait for https://github.com/godotengine/godot/pull/82051 to be merged to make sure this still behaves as expected afterwards. It's probably fine, but the code is not straightforward so I wanted to be sure.

2023-10-02 09:05 UTC, akien-mga commented
So I wanted to confirm the bug again to test the fix, and the bug seems already fixed since 4.2-dev5. Weird.

2023-10-02 09:13 UTC, akien-mga commented
@dalexeev Is this one line change still worth doing for good measure, or would risk introducing other issues?

2023-10-02 09:16 UTC, dalexeev commented
I haven't tested this yet, but I suspect the change may break tooltips for native classes. I'll reply later.

2023-10-02 09:36 UTC, dalexeev commented
I tested it. For some reason this doesn't break tooltips (probably because for native classes the `doc_name` is left empty and the `class_descr_cache` is never filled). But the code doesn't look correct to me, `doc_name` changes only for scripts, not for native classes.

2023-10-02 09:50 UTC, dalexeev commented
* The linked issue has already been fixed by #81221.

Thanks for the contribution nonetheless!

2023-10-02 09:50 UTC, closed without merging

2023-10-02 10:28 UTC, anvilfolk commented
Oh, damn, great catch @dalexeev, I had focused on testing GDScript classes! Glad you came along ❤️