Fix tile resizing towards atlas boundary
godotengine/godot pull request #76152
Opened 2023-04-17 02:08 UTC by timothyqiu

Fixes #75213

The resizing logic was fine. It was built around the assumption that it can get out-of-bound tile coordinates. But the function to get tile coordinate was probably changed later, clamping the returned coordinate inside the atlas boundary.

This PR changes the `clamp` argument of `TileAtlasView::get_atlas_tile_coords_at_pos()` from `bool` to `ClampMode`, adding a way to clamp to the `(-1, -1, width, height)` region.

https://github.com/godotengine/godot/blob/4e4ba295226030ebf3e9c26a920f0f7511fc21f7/editor/plugins/tiles/tile_atlas_view.h#L125-L129

The previous `clamp = false` can't be reused because it should error by returning the `INVALID_ATLAS_COORDS` constant when the input position is out-of-bound.

2023-05-11 10:54 UTC, groud requested changes

2023-05-11 10:54 UTC, groud commented on editor/plugins/tiles/tile_set_atlas_source_editor.cpp
> +				new_base_tiles_coords = tile_atlas_view->get_atlas_tile_coords_at_pos(tile_atlas_control->get_local_mouse_position(), TileAtlasView::CLAMP_MARGIN);
If this is the only place where this is needed, I believe modifying so much code is not really needed.
Instead,  I think you should use the unclamped version and clamp it manually like how it was done before. Basically you would just replace this line by:
```
new_base_tiles_coords = tile_atlas_view->get_atlas_tile_coords_at_pos(tile_atlas_control->get_local_mouse_position()).max(Vector2i(-1, -1)).min(grid_size);
```

2023-06-21 08:58 UTC, groud approved these changes

2023-06-21 09:19 UTC, merged

2023-06-21 09:19 UTC, YuriSizov commented
Thanks!