adding method to fetch layers from tilemap, get_layer_for_body_rid()
godotengine/godot pull request #76246
Opened 2023-04-19 04:29 UTC by Proggle

Currently it isn't possible to find the tilemap layer of what object you're colliding with.  This adds a tilemap method, get_layer_for_body_rid(), which works just like the already-existing get_coords_for_body_rid(), except it returns the tilemap layer instead of the tilemap coordinates.

2023-04-20 12:45 UTC, groud requested changes
Needs the commits to be squashed. Looks good otherwise.

2023-04-24 20:55 UTC, Proggle commented
> Needs the commits to be squashed. Looks good otherwise.

Sorry to ask, but can someone better with Git squash that for me?  Something is screwy with git on my computer, I spent an hour talking with the helpful people in godot development chat trying to run commands and it keeps refusing to work.

I could make a new branch from scratch with the changes, but from what I understand that would also produce a new pull request rather than merging into this one.

2023-04-25 10:51 UTC, akien-mga commented
> > Needs the commits to be squashed. Looks good otherwise.
> 
> Sorry to ask, but can someone better with Git squash that for me? Something is screwy with git on my computer, I spent an hour talking with the helpful people in godot development chat trying to run commands and it keeps refusing to work.

No problem, I squashed the commits for you :)

2023-04-25 11:01 UTC, groud approved these changes

2023-04-25 12:51 UTC, merged

2023-04-25 12:52 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: