Update OptionButton.xml
godotengine/godot pull request #76552
Opened 2023-04-28 17:19 UTC by Koyper

Adds a note clarifying the effect of the `Button` theme's `icon_max_width` constant on the size of the `OptionButton` icon, which is otherwise not obvious.

2023-04-28 20:47 UTC, YuriSizov commented
You can link to theme items in the documentation. I'm also not sure what kind of problem this resolves.

2023-04-29 03:06 UTC, Koyper commented
> You can link to theme items in the documentation. I'm also not sure what kind of problem this resolves.

I'm documenting how to work around what I think is unexpected behavior. It seems like the desired behavior would be for the icon size of the `OptionButton` to automatically follow that set using `icon_max_width` in its `PopupMenu`. `expand_icon` doesn't work properly because you can only indirectly size the icon and winds up being out of pixel alignment.

If you know the trick, it's probably okay as-is, though it would be more convenient if the `OptionButton` had it's own `icon_max_width` setting. I could set that up at some point if it makes sense.

2023-04-29 13:15 UTC, Koyper commented
I think this would fix the behavior without adding any new settings: `OptionButton` adopts its `PopupMenu.icon_max_size` if that is set to a non-default value AND both `expand_icon` if false, and `Button.icon_max_size` has NOT been set.

2023-05-16 16:52 UTC, YuriSizov commented
> though it would be more convenient if the `OptionButton` had it's own `icon_max_width` setting.

It has. You can add it. `OptionButton` inherits `Button`, so it has all the same theme properties. `icon_max_width` is just not defined for `OptionButton` explicitly, so it inherits the value from the `Button` definition. But you can override that with a theme.

In any case, I don't think that the tip added here is useful for the documentation. It doesn't address a well-defined problem, and it also doesn't provide a solution. It just states several facts without giving any guidance, IMO. Perhaps it can be rephrased and reshaped, but from the provided use case it looks more like a general misunderstanding of how themes work.

2023-05-16 16:53 UTC, YuriSizov requested changes
See above.

2023-05-16 17:28 UTC, Koyper commented
I definitely concede the point that `OptionButton` already has it's own `icon_max_width` via `Button`. My better thought on the matter is this fix:

>I think this would fix the behavior without adding any new settings: `OptionButton` adopts its `PopupMenu.icon_max_size` if that is set to a non-default value AND both `expand_icon` if false, and `Button.icon_max_size` has NOT been set.

If that looks like a good idea, I can modify `OptionButton` accordingly when I get a chance.

In the meantime, do you disagree that a tip in the documentation might save some new users some time trying to figure out why setting the icon width in `PopupMenu` isn't effecting `OptionButton`?

2023-05-16 17:39 UTC, YuriSizov commented
> why setting the icon width in `PopupMenu` isn't effecting `OptionButton`?

Why would `PopupMenu` affect `OptionButton` at all? They are not related. Sometime users are confused through no fault of the engine. Just some error in the thought process that derails it. Can you demonstrate that it's the engine that somehow implies that `OptionButton` should take its styling from `PopupMenu`?

2023-05-16 18:39 UTC, Koyper commented
> Why would `PopupMenu` affect `OptionButton` at all? They are not related. Sometime users are confused through no fault of the engine. Just some error in the thought process that derails it. Can you demonstrate that it's the engine that somehow implies that `OptionButton` should take its styling from `PopupMenu`?

To be clear, I'm only referring to the `PopupMenu` obtained via `OptionButton.get_popup()`.

When I click on `OptionButton`, a `PopupMenu` appears with a list of items; I select an item from it, and the text and icon of the selected item is now transferred back to the `OptionButton`. I therefore typically expect to see the same formatting of the thing I clicked in the `PopupMenu` appear in the `OptionButton`. If I theme the `OptionButton`'s `PopupMenu` with an `icon_max_width`, this doesn't automatically happen, and the `OptionButton` icon is now a different size, which I don't consider to be intuitive or expected.

2023-05-16 18:56 UTC, Koyper commented
I think you could also argue that the `icon_max_width` from the `OptionButton` theme should propagate to its `PopupMenu` unless overridden by the `PopupMenu` theme instead of the other-way-round like I've been proposing.

2023-05-16 19:06 UTC, YuriSizov commented
> I think you could also argue that the `icon_max_width` from the `OptionButton` theme should propagate to its `PopupMenu` unless overridden by the `PopupMenu` theme instead of the other-way-round like I've been proposing.

Yes, that you could argue, that would be a sensible expectation and a pattern that is sometimes used in Godot.

2023-05-16 21:34 UTC, Koyper commented
> Yes, that you could argue, that would be a sensible expectation and a pattern that is sometimes used in Godot.

The below works except for checking in the `if` conditional that the popup has not had the `icon_max_width` overridden after a `get_popup()` - how do you check that to differentiate from a project `PopupMenu` theme override?

```
void OptionButton::show_popup() {
	if (!get_viewport()) {
		return;
	}
	if (Button::has_theme_constant(SNAME("icon_max_width"))) {
		popup->add_theme_constant_override("icon_max_width", Button::get_theme_constant("icon_max_width"));
	}
```

2023-05-16 23:54 UTC, YuriSizov commented
There is no way to check for that in this case, we would have to assume that enforcing a value from the parent OptionButton is a more preferred behavior. You should should apply overrides on theme changes though, not when popping the popup.

2023-05-17 00:32 UTC, Koyper commented
The thought about putting it in `show_popup` is for the case where we want the two constants to differ, the initial popup can be saved if `get_popup()` is called, then compared with the current override before popping? Otherwise, you would be unable to have two differing `icon_max_width' values if the button one is set?

That's interesting about not needing the `Button::` - so you can query up the entire theme hierarchy?

2023-05-17 11:26 UTC, YuriSizov commented
> Otherwise, you would be unable to have two differing `icon_max_width' values if the button one is set?

Indeed, to override the button's popup with a different value you'd need to code a script that reacts on theme changes and enforces some value. There is no way around it, but it's a fine compromise to have if this behavior of having the button and the popup in sync by default is the expected one. We do it in some other compound GUI nodes, so it's an established pattern.

If, however, having them in sync by default is not expected, then there is nothing to change, neither the code, nor the docs.

> That's interesting about not needing the `Button::` - so you can query up the entire theme hierarchy?

Not sure what you mean, but each control can call `get_theme_constant` from itself. Calling it through another class breaks the expected theming logic.

2023-05-17 14:44 UTC, closed without merging

2023-05-17 15:19 UTC, Koyper commented
No worries - sorry about all the words for just a puff of code, but sometimes it happens.

The other PR is a bit more complicated, but looks like it will work - it might have been nice to not have involved the `expand_icon` setting.