Fixes an issue where renaming a Node to the same name as one of its siblings causes the exported `NodePath` to point to the wrong node.
godotengine/godot pull request #76575
Opened 2023-04-29 10:29 UTC by nongvantinh

Once text editing is complete, the method `void SceneTreeEditor::_renamed()` is triggered, followed by `void SceneTreeDock::_node_prerenamed(Node *p_node, const String &p_new_name)`. Afterward, the method `void SceneTreeDock::perform_node_renames(Node *p_base, HashMap<Node *, NodePath> *p_renames, HashMap<Ref<Animation>, HashSet<int>> *r_rem_anims)` is called, which ultimately leads to line 1707 where the method `p_base->set(propertyname, updated_variant);` modifies the previously set value with the new Node's name. Next, the method `void SceneTreeEditor::_rename_node(ObjectID p_node, const String &p_name)` is triggered to update the TreeItem in SceneTreeEditor and the Node's name. However, the problem arises in line 962: `n->set_name(p_name);` when the Node's name is validated using `data.parent->_validate_child_name(this, true);`. It is then discovered that the new name conflicts with a sibling's name, prompting `_generate_serial_child_name(p_child, name);` to append a number to the renaming Node's name. Unfortunately, the value of the exported variable is not updated, causing the bug.

Fixes: #76192

2023-05-01 16:55 UTC, ajreckof requested changes
This a good fix. Unfortunately this only fixes it for basic renames and do not fix it for batch rename. You should do the same [here](https://github.com/godotengine/godot/blob/9f12e7b52d944281a39b7d3a33de6700c76cc23a/editor/rename_dialog.cpp#L603) to fix it for batch rename too

2023-05-01 16:55 UTC, ajreckof commented on scene/main/node.cpp
> +}
I would rename this function to `prevalidate_child_name` to make it clear what is the difference with the other function.

2023-05-03 02:44 UTC, ajreckof commented
While reviewing this and working on #76376 at the same time, I realized Batch Rename was too fucked up for an easy fix and would need to wait for my proper fix in the linked PR. I think you should re-focus this PR solely on fixing the original bug with only simple renames. I'm so sorry as this was my fault for bringing up Batch rename in the first place. 
The current state of the PR is non functional as it has a lot of problems with undo redo.  I would advise you to remake it to its original state which was functional and in a mergeable state to fix the original bug for basic renames. the other possibility is to wait for my other PR to be merged then you will be able to make a proper fix for the original bug for both basic renames and batch renames.

2023-05-03 03:27 UTC, nongvantinh commented
I agree with you. However, the current implementation of UndoRedo does not align with the `node_prerename` signal and the `_rename_node` method. Therefore, I have made updates to the PR to resolve the current issue. In case the `team` wishes to merge the original PR in the future, I have made sure to revert the changes.

2023-06-15 20:25 UTC, ajreckof commented
now that #76376 is merged would you mind rebasing this to be included in 4.1 ? This should be similar to what you had done first just placed in the function `_rename_node` this would handle both normal renames and batch rename as both call this function now.

2023-06-17 05:01 UTC, ajreckof requested changes
I like the idea of this PR. Would you mind just renaming the function to prevalidate_child_name?

2024-01-19 10:29 UTC, AThousandShips commented
Superseded by:
* https://github.com/godotengine/godot/pull/87252

2024-01-19 10:29 UTC, closed without merging