Fix calculation bug in `TextEdit::get_visible_line_count`
godotengine/godot pull request #76605
Opened 2023-04-30 03:02 UTC by Rindbee

When `get_line_height()` is not greater than `0`, there is no visible text.

Fix #69209.

2023-04-30 11:06 UTC, adamscott approved these changes
Fixes a possible nasty division by 0.

2023-04-30 13:49 UTC, adamscott approved these changes
Thanks for updating the documentation. The code is much better now too.

2023-05-07 14:03 UTC, Paulb23 requested changes
Should make the minimum return `1`, then we wouldn't need to worry about a divide by `0`, or is there a use case for `0` line height?

We should also print a warning if it is below the minimum.

2023-05-07 23:43 UTC, Rindbee commented
> Should make the minimum return `1`, then we wouldn't need to worry about a divide by `0`, or is there a use case for `0` line height?

Set `line_spacing` small enough to hide all text. Might not be necessary for the use cases of `TextEdit`. So not less than `1` is fine.

2023-05-14 16:00 UTC, Paulb23 commented
Missing the warning print, either with `ERR_FAIL_COND_MSG` or a check in `_update_cache / _update_theme_item_cache` so it doesn't go unnoticed.

2023-05-14 23:18 UTC, Rindbee commented on scene/gui/text_edit.cpp
> +	}
Now prints a warning in `_update_theme_item_cache()`.

2023-05-15 18:27 UTC, Paulb23 approved these changes

2023-05-16 09:06 UTC, merged

2023-05-16 09:07 UTC, akien-mga commented
Thanks!

2023-06-16 16:16 UTC, YuriSizov commented
Cherry-picked for 4.0.4.