[TLS] Add support for platform-specific CA bundles.
godotengine/godot pull request #76836
Opened 2023-05-08 11:36 UTC by Faless

Adds a new OS::get_system_ca_certs method which can be implemented by platforms to retrieve the list of trusted CA certificates using OS specific APIs.

The function should return the certificates in PEM format, and is currently implemented for Windows/macOS/LinuxBSD(*)/Android.

mbedTLS will fall back to bundled certificates when the OS returns no certificates.

(*) LinuxBSD does not have a standardized certificates store location. The current implementation will test for common locations and may return an empty string on some distributions (falling back to the bundled certificates).

Implements https://github.com/godotengine/godot-proposals/issues/2970

2023-05-08 15:30 UTC, m4gr3d requested changes

2023-05-08 15:30 UTC, m4gr3d commented on platform/android/java/lib/src/org/godotengine/godot/Godot.java
> +	}
This is only intended for use by the native code, so you can make the method `private` and add the `@Keep` annotation to denote it should not be stripped by proguard.

2023-05-08 15:30 UTC, m4gr3d commented on platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java
> +	static public String getCACertificates() {
Can you add a javadoc comment and link to the documentation/reference guide for retrieving certificates on Android.

2023-05-08 15:30 UTC, m4gr3d commented on platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java
> +	static public String getCACertificates() {
nit: Should be `public static`.

2023-05-08 15:30 UTC, m4gr3d commented on platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java
> +			StringWriter writer = new StringWriter();
You want to use `StringBuilder` instead of `StringWriter` (e.g: https://stackoverflow.com/a/2980852)

2023-05-09 15:52 UTC, cunyx commented
Thank you for working on this!

May I ask to check for "_SYSTEM_CERTS_PATH" in function
"OS_LinuxBSD::get_system_ca_certificates"
of file
"platform/linuxbsd/os_linuxbsd.cpp"
before testing distro specific paths?

This would allow to set a path at compile time with higher priority,
regardless of the distribution.
Additionally this gives environments not explicitly listed here a chance to
be covered as well.

Is it possible, to get the path
"/var/lib/ca-certificates/ca-bundle.pem"
included for openSUSE?

Thanks!

2023-05-10 14:05 UTC, Faless commented
@m4gr3d thanks for the speedy review :partying_face: ! I updated the PR with your suggestions.

> Is it possible, to get the path "/var/lib/ca-certificates/ca-bundle.pem" included for openSUSE?

@cunyx done, thanks :partying_face: !

> May I ask to check for "_SYSTEM_CERTS_PATH" in function [...] to set a path at compile time with higher priority [and] give environments not explicitly listed here a chance to be covered as well.

@cunyx I am unsure about this, I see the value for package maintainers but I'm not really sure it's a good solution at large, as it would create an export template only working with a specific distro ( CC @akien-mga , opinions?).

2023-05-10 15:46 UTC, Calinou commented
In the long term, would this change PR for no longer bundling a certificate bundle on most platforms? This would allow decreasing binary size by a non-negligible amount, while also making binaries more "future-proof".

2023-05-10 16:22 UTC, m4gr3d approved these changes
The Android section looks good!

2023-05-11 05:58 UTC, Faless commented
@akien-mga @cunyx I added the `_SYSTEM_CERTS_PATH` check, let me know if I understood correctly the desired behavior.

---

> In the long term, would this PR allow for no longer bundling a certificate bundle on most platforms?

@Calinou Yes, I think Windows/macOS/Android could already unbundle them.

On linuxbsd it's a bit trickier due to each distro having its own paths so we should probably evaluate if we can cover 99% of the users I guess.

The only missing platforms are Web (where we don't need bundling), and iOS/iPadOS/tvOS which as far as I understand does not give developers access to the anchor certificates.

2023-05-11 16:25 UTC, cunyx commented
@Faless 
Really nice that you are open and so fast to adapt the code!

> I added the _SYSTEM_CERTS_PATH check, let me know if I understood correctly the desired behavior.

As your coding knowledge is much more superior, i can not offer
useful technical comments for your implementation.

If i understand the code logic correctly,
if "_SYSTEM_CERTS_PATH" is non-empty but opening the file fails,
the empty string "" is returned immediately.

I'm not sure if in this case it might be better to probe the remaining explicitly listed files nevertheless.

This will make it perhaps more robust and portable.
"_SYSTEM_CERTS_PATH" would only take priority if it is set at compile time
**and** pointing to an existing readable file.

But this might be more complex and of course I'm fine with your current solution as well.

Thanks!

2023-05-12 08:00 UTC, Faless commented
> I'm not sure if in this case it might be better to probe the remaining explicitly listed files nevertheless.

Ah, I see, no problem, done :).

2023-05-12 08:50 UTC, akien-mga approved these changes
Looks great!

2023-05-12 09:19 UTC, merged

2023-05-12 09:19 UTC, akien-mga commented
Thanks!