Add emission_finished signal to particles.
godotengine/godot pull request #76853
Opened 2023-05-08 17:30 UTC by HolonProduction

Closes godotengine/godot-proposals#649.

Can be tested with [this](https://github.com/godotengine/godot/files/11423625/particle_emission.zip) project.

2023-05-08 18:14 UTC, Calinou commented on scene/3d/gpu_particles_3d.cpp
> +				if (RS::get_singleton()->particles_is_inactive(particles)) {
This should be implemented by waiting for `lifetime * 1.2` seconds, rather than querying whether particles are still active.

2023-05-08 18:20 UTC, HolonProduction commented on scene/3d/gpu_particles_3d.cpp
> +				if (RS::get_singleton()->particles_is_inactive(particles)) {
> after `emitting` was set to `true`

I assume you mean `false`?

In which case would particles linger longer then `lifetime`?

2023-05-08 18:28 UTC, Calinou commented on scene/3d/gpu_particles_3d.cpp
> +				if (RS::get_singleton()->particles_is_inactive(particles)) {
> In which case would particles linger longer than lifetime?

I don't know, but the original code does it for some reason:

https://github.com/Calinou/godot/blob/febc674f4818dd1185b2e43e899115f70f55b4f5/scene/3d/cpu_particles_3d.cpp#L582-L592

https://github.com/Calinou/godot/blob/febc674f4818dd1185b2e43e899115f70f55b4f5/servers/rendering/renderer_rd/storage_rd/particles_storage.cpp#L1353-L1357

2023-05-08 18:39 UTC, HolonProduction commented on scene/3d/gpu_particles_3d.cpp
> +				if (RS::get_singleton()->particles_is_inactive(particles)) {
Sadly there is no explanation of it on the original commit. But from what I can tell it is ment to ensure that `_set_redraw` is called after the last `_particles_update`. This is the case with my solution as well. I did some basic test and it seemed to work as well. I decided for checking the particles activity as this also respects lifetime randomness.

2023-05-08 18:48 UTC, clayjohn commented on scene/3d/gpu_particles_3d.cpp
> +				if (RS::get_singleton()->particles_is_inactive(particles)) {
> I noticed this as well but I assumed it was ok for now, as the old code uses `is_emitting` which relies on `particles_get_emitting` which causes a synchronisation as well.
> 
> If this is a concern I would remove the GPU nodes from this PR for now and create a draft for them.

That is totally fair, but unfortunately, that code should not have been added and removing it has been on our long-term TODO list (see https://github.com/godotengine/godot/issues/64094). I'm sorry this information isn't more visible, we don't expect all contributors to keep up to date on little things like this. But we should avoid adding any more synchronization issues that need to be fixed. 

I think duplicating the logic on the scene-side is the best approach here (as Calinou pointed out), both for this PR and for fixing the "is_emitting" issue

2023-05-08 18:50 UTC, HolonProduction commented on scene/3d/gpu_particles_3d.cpp
> +				if (RS::get_singleton()->particles_is_inactive(particles)) {
I will try to implement it in a different way. As mentioned above I will create a new PR for that.

2023-05-08 21:11 UTC, HolonProduction commented
Just noticed that this breaks the resetting of `emitting` with high `explosiveness` values. (Might be related to the `lifetime * 1.2` that Calinou pointed out before.)

2023-05-09 08:24 UTC, HolonProduction commented
`emitting` is set to `false` when a cycle ends. This means even withe `explosiveness = 1` emitting will only be false after `lifetime`. Combined with `lifetime_randomness` all particles can vanish before `emitting` is set to `false`. Therefore the internal process should only end if not emitting and not active.

2023-07-06 16:20 UTC, clayjohn requested changes
This works quite well for the most part. However, if emitting is set to ``true`` in the same frame that the particle is created (or the same frame that the particle is restarted), the signal will fire immediately. You probably need to also check if cycle is 0 or if time == 0.

I tested with a very simple script in a scene with a default CPUParticles2D node set to `one_shot`
```
extends Node2D

func _ready():

	$CPUParticles2D.emission_finished.connect(finished_emitt)
	$CPUParticles2D.restart() # this emits the signal in the first frame, but not when emission actually finishes
#	$CPUParticles2D.call_deferred("restart") # this works
	
func finished_emitt():
	print("done emitting")
	$Sprite2D.visible = false
```

2023-07-07 09:56 UTC, HolonProduction commented
> This works quite well for the most part. However, if emitting is set to `true` in the same frame that the particle is created (or the same frame that the particle is restarted), the signal will fire immediately. You probably need to also check if cycle is 0 or if time == 0.
> 
> I tested with a very simple script in a scene with a default CPUParticles2D node set to `one_shot`

This seems to happen if restarting in `_ready`. The reason for this seems to be [here](https://github.com/godotengine/godot/blob/1b03ec918edd50f1e926e8cf71259e14e1ee70d9/scene/2d/cpu_particles_2d.cpp#L1111-L1114). The internal process is called here but not from the process notification. Therefore the delta time is zero and the restart computation will fail. Therefore all particles are inactive during the first internal process. During this process the checks for emitting the signal run as well and since all particles are inactive it is emitted. The particles only become active during the second iteration of internal process when delta time is not zero.

Calling internal process early seems to have a reason so the best solution seems to be adding a check whether delta time is zero and not emitting the signal if so. Are there any implications with this (means: are there other valid cases with a delta time of zero)?

2023-07-07 10:55 UTC, clayjohn commented
> Are there any implications with this (means: are there other valid cases with a delta time of zero)?

It looks like the particles will process when delta time is 0 if the ``pre_process_time`` is greater than 0 https://github.com/godotengine/godot/blob/1b03ec918edd50f1e926e8cf71259e14e1ee70d9/scene/2d/cpu_particles_2d.cpp#L577

2023-07-07 11:37 UTC, HolonProduction commented
All preprocessing happens while time == 0 so the signal cannot be emmitted during pre processing. But after this it seems to work fine for me. Even if preprocess is higher than lifetime the internal processing will only be turned of after the signal gets emitted so internal process will run and the signal is emitted emediately.

If you find another case that makes problems with pre process I will look into it.

2023-07-07 12:50 UTC, clayjohn commented
> All preprocessing happens while time == 0 so the signal cannot be emmitted during pre processing. But after this it seems to work fine for me. Even if preprocess is higher than lifetime the internal processing will only be turned of after the signal gets emitted so internal process will run and the signal is emitted emediately.
> 
> If you find another case that makes problems with pre process I will look into it.

Ah, of course. You are right. It will never signal during the pre_process which is a good thing!

2023-07-07 12:53 UTC, clayjohn approved these changes
I am happy with this implementation. I have tested locally and it appears to work well. 

This should be a great early inclusion to 4.2. 

Note for merger, this should be merged at the same time as its counterpart https://github.com/godotengine/godot/pull/76859 (for GPUParticles) which I still need to test/review

2023-07-13 08:07 UTC, clayjohn approved these changes

2023-07-14 17:00 UTC, merged

2023-07-14 17:11 UTC, YuriSizov commented
Thanks!