C#: Check if .NET runtime has been finalized in the instance binding reference callback
godotengine/godot pull request #77362
Opened 2023-05-22 18:02 UTC by RedworkDE

Fixes #77305

Turns out you can't detach an instance binding from an object, so duplicate a check from `_instance_binding_free_callback`.

2023-06-22 08:38 UTC, akien-mga commented
CC @raulsntos

2023-06-22 23:16 UTC, raulsntos approved these changes
I'm not very familiar with the reference count system so take this review with a grain of salt. In general it makes sense to me that if the .NET runtime is finalized, the `reference_callback` implementation would return true and let the object be freed.

2023-06-23 00:08 UTC, neikeq requested changes
I'm preemptively blocking this from being merged before I review it tomorrow. But in advance I can say there's probably something wrong elsewhere as instance bindings should have been cleaned up before/after finalizing.

2023-06-23 06:40 UTC, RedworkDE commented on modules/mono/csharp_script.cpp
> +		return true;
At a time where the if is taken, `p_binding` is a dangling pointer, so we cannot get at the actual object and thus refcount without going though freed memory, so we cannot do that.

2023-06-23 06:48 UTC, RedworkDE commented
> But in advance I can say there's probably something wrong elsewhere as instance bindings should have been cleaned up before/after finalizing.

Yes, arguably the instance binding should have been detached from objects before https://github.com/godotengine/godot/blob/f9fc77bbe474e33967dfde69a2efa442f465fae2/modules/mono/csharp_script.cpp#L165 but there is no way of doing that currently and thus I went for the simple crash fix that doesn't require core changes.

2023-06-28 17:15 UTC, neikeq commented
The problem is indeed somewhere else. We cannot remove the script bindings, but that's what the `script_binding.inited`. This method checks that, so for some reason it's not cleaned up. Probably a script binding is being created again after all the bindings were finalized, which would explain why #78157 fixes the issue.

2023-06-28 17:22 UTC, neikeq commented
Wait, I just realized we check `script_binding.inited` after `CRASH_COND(!rc_owner);`. Does moving it to check that first work?

2023-06-28 19:38 UTC, RedworkDE commented
> Does moving it to check that first work?

When these issues occur `p_binding` is a dangling pointer to freed memory and we can no longer safely check `script_binding.inited`, so no that doesn't help.

I would use #78157 to fix the issue (It gracefully deletes the managed objects before dropping the instance bindings map) and then either keep this PR as-is as backup or just close this as superseded.

2023-10-31 19:44 UTC, raulsntos commented
If https://github.com/godotengine/godot/pull/78157 fixes the issue, then I think I'm leaning towards closing this PR as superseded.

If, as you say, some bound objects survive after `OnGodotShuttingDown`, then it may be preferable to let Godot crash instead of potentially hiding an issue somewhere else.

As I understand it from the previous conversation, the bound objects should have been cleared before reaching `_instance_binding_free_callback` so if any bound objects survive it's likely a bug in the .NET module that should be fixed.

2023-10-31 19:53 UTC, akien-mga commented
So should we close this as superseded by #78157, or does it still have value to be merged?

2023-11-01 07:49 UTC, RedworkDE commented
Superseded by #78157

2023-11-01 07:49 UTC, closed without merging