GLTF: Set `gltf_skeleton->godot_bone_node` when importing skeletons
godotengine/godot pull request #77718
Opened 2023-06-01 03:24 UTC by aaronfranke

In the current master, `gltf_skeleton->godot_bone_node` is only used when exporting a GLTF file from Godot, but when importing it is always empty. This PR populates it during import so you can use it during the import process. I also renamed `skeleton` to `godot_skeleton` to improve the clarity of the code.

Note: This maps a bone index to a GLTF node index, but for my uses I actually need it the other way around, starting with a GLTF node index and getting the bone index. If desired I could add another data structure that maps the other way.

2023-06-01 14:21 UTC, fire commented
Note that this is deprecrated from the gltf spec. I think you need to scan all the nodes and find the skeleton[s] that way. Skeletons are a godot engine construct that also exists in Blender but is generated and doesn’t exist.

2023-06-01 14:57 UTC, fire commented
The implementation in godot engine and the implementation note of the gltf spec says to ignore the skeleton property.

https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#skins-overview

2023-06-01 15:17 UTC, fire commented on modules/gltf/doc_classes/GLTFSkeleton.xml
> +				Returns a [Dictionary] that maps skeleton bone indices to the indices of the GLTF nodes that the bones came from. In a GLTF file, a bone is a node, and Godot converts it to a skeleton bone.
I think I get it.

This does a three level mapping:

1. gltf_skeleton is ignored
2. when we generate a godot_skeleleton a gltf_skeleton is generated
3. the gltf_skeleton maps a godot engine skeleton3d node to a bone to a gltf_node

2023-06-01 15:29 UTC, fire approved these changes
The only addition is this line (plus the documentation) .
gltf_skeleton->godot_bone_node.insert(godot_skeleton->get_bone_count(), node_i);

It makes sense.

2023-06-01 15:32 UTC, fire requested changes
Do we need the setter and the property?

We didn't need it previously?

2023-06-03 11:05 UTC, fire approved these changes
We discussed at length and concluded that only a documentation change is needed.

2023-06-03 11:53 UTC, fire commented
I believe this is a documentation bug because of @aaronfranke confusion and the update is documentation updates, so it should be mergable for 4.1 and backportable.

2023-06-05 11:43 UTC, merged

2023-06-05 11:45 UTC, akien-mga commented
Thanks!