Clarify when things with _IDLE and _PHYSICS enums will run
godotengine/godot pull request #77717
Opened 2023-06-01 01:07 UTC by L4Vo5

Clarified when objects using `*_IDLE` and `*_PHYSICS` enums will run their code. "idle frame", "idle step" and "idle process" are confusing terms that have caused confusion in the past.
Also clarified when SceneTreeTimers run, since they're similar to Tweens and those are clarified already.

2023-06-02 09:01 UTC, mhilbrunner approved these changes

2023-06-02 10:58 UTC, YuriSizov requested changes
I would not replace plain language with constant links. It doesn't help to understand and talk about these matters. I think constants can be linked in parenthesis though.

2023-06-02 20:33 UTC, L4Vo5 commented
> I would not replace plain language with constant links. It doesn't help to understand and talk about these matters. I think constants can be linked in parenthesis though).

I was afraid that using both plain language and the links could make the descriptions too long, but I'll see how it ends up.

2023-06-02 20:46 UTC, L4Vo5 commented
hmm, any thoughts on whether it'd be better to keep referencing the internal process notifications (to be more accurate) or instead the `Node._process` and `Node._physics_process` methods (to be more immediately understandable)?

2023-06-20 12:41 UTC, YuriSizov commented on doc/classes/SceneTree.xml
> +				[b]Note:[/b] SceneTreeTimers are processed after all of the nodes in the current frame, i.e. after [method Node._process] or [method Node._physics_process] (depending on [param process_in_physics
```suggestion
				[b]Note:[/b] The timer processed after all of the nodes in the current frame, i.e. node's [method Node._process] method would be called before the timer (or [method Node._physics_process] if [param process_in_physics] is set to [code]true[/code]).
```

2023-06-20 12:43 UTC, YuriSizov commented on doc/classes/SceneTreeTimer.xml
> +		[b]Note:[/b] SceneTreeTimers are processed after all of the nodes in the current frame, i.e. after [method Node._process] or [method Node._physics_process] (depending on the value of [code]process_
```suggestion
		[b]Note:[/b] The timer is processed after all of the nodes in the current frame, i.e. node's [method Node._process] method would be called before the timer (or [method Node._physics_process] if [code]process_in_physics[/code] in [method SceneTree.create_timer] has been set to [code]true[/code]).
```

2023-06-20 12:45 UTC, YuriSizov commented on doc/classes/Tween.xml
> +		[b]Note:[/b] Tweens are processed after all of the nodes in the current frame, i.e. after [method Node._process] or [method Node._physics_process] (depending on [enum TweenProcessMode]).
```suggestion
		[b]Note:[/b] The tween is processed after all of the nodes in the current frame, i.e. node's [method Node._process] method would be called before the timer (or [method Node._physics_process] depending on the value passed to [method set_process_mode]).
```

2023-06-20 12:45 UTC, YuriSizov approved these changes
Should be fine after making suggested adjustments.

2023-06-20 15:52 UTC, YuriSizov commented
Sorry for the CI issue, it's not from your changes. But you need to do a rebase against the current master and the force-push again to fix it.

2023-06-20 18:48 UTC, merged

2023-06-20 18:48 UTC, YuriSizov commented
Thanks, and congrats on your first merged Godot PR!