Fix issue #77944 (Clicking a selected item in the error log doesn't scroll back to it)
godotengine/godot pull request #78093
Opened 2023-06-10 19:34 UTC by samar-01

A line was added where the error tree is initialized allowing for items to be reselected.

2023-06-10 19:53 UTC, AThousandShips commented
Please change it to "Fixes #77944" to link it to the issue

2023-06-11 02:20 UTC, YeldhamDev requested changes
Both the commit message and the PR's title needs to be changed to something that reflects what it's doing. A good message could be "Allow reselecting error messages in the debugger".

You can change the message by doing:
```
git commit --amend -m "[MESSAGE HERE]"
git push --force origin fix-77944
```

2023-06-11 04:40 UTC, YeldhamDev approved these changes

2023-06-12 09:58 UTC, merged

2023-06-12 10:00 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: