Fix crash when opening a TileSet with invalid tiles
godotengine/godot pull request #78165
Opened 2023-06-13 03:37 UTC by timothyqiu

Fixes #77673

`get_tile_data()` returns null for invalid identifiers so a check is needed. Checks `has_tile()` and `has_alternative_tile()` first so that `get_tile_data()` won't print errors.

2023-06-13 10:42 UTC, groud requested changes

2023-06-13 10:42 UTC, groud commented on editor/plugins/tiles/tiles_editor_plugin.cpp
> +
The check should be expanded to the following two lines, otherwise they will spit errors in `get_tile_texture_region`

2023-06-13 10:55 UTC, groud approved these changes

2023-06-13 11:54 UTC, merged

2023-06-13 11:54 UTC, akien-mga commented
Thanks!

2023-07-20 11:52 UTC, YuriSizov commented
Cherry-picked for 4.0.4.