Make GraphEdit's cpp virtuals equal to gdscript.
godotengine/godot pull request #78426
Opened 2023-06-19 04:00 UTC by Daylily-Zeleen

Some GraphEdit's methods can be overrided in GDScript but can't be override in C++, I don't know it is Intentional or not, but it blocking the development of godot module.

2023-06-19 05:57 UTC, fire approved these changes
I agree that exposing virtuals is important to allow extending via C++ modules. Did not look deeply technically.

Note we are in feature freeze.

2023-08-07 11:48 UTC, akien-mga commented
Needs rebase after #79308. CC @Geometror

2023-08-08 14:09 UTC, akien-mga approved these changes

2023-08-08 14:42 UTC, YuriSizov requested changes

2023-08-08 14:42 UTC, YuriSizov commented on scene/gui/graph_edit.h
> +	bool is_in_port_hotzone(const Vector2 &pos, const Vector2 &p_mouse_pos, const Vector2i &p_port_size, bool p_left);
You lost parameter renames here.

2023-08-08 14:42 UTC, YuriSizov commented on scene/gui/graph_edit.h
> +	virtual bool is_in_output_hotzone(GraphNode *p_node, int p_port, const Vector2 &p_mouse_pos, const Vector2i &p_port_size);
And here.

2023-08-08 18:05 UTC, YuriSizov approved these changes

2023-08-09 13:21 UTC, merged

2023-08-09 13:23 UTC, akien-mga commented
Thanks!