Add a button in the export dialog to fix missing texture formats
godotengine/godot pull request #78457
Opened 2023-06-20 03:07 UTC by aaronfranke

This PR improves the error message about texture formats to include a button to fix it. I was inspired by a similar fix button in VRChat and realized the same idea would work perfectly here. This will greatly help with #78395.

<img width="783" alt="Screenshot 2023-06-19 at 9 09 50 PM" src="https://github.com/godotengine/godot/assets/1646875/0fd923fe-84e6-473e-88d1-fc94b48d0753">

When the button is pressed, the project setting is enabled, the settings are saved, the editor file system is re-scanned (which reimports all textures as needed), and the export dialog is refreshed.

Draft because this PR depends on #78455 and #78456 to be merged first, but I put it on the 4.1 milestone because I think this usability enhancement is both simple and important.

2023-06-20 19:26 UTC, YuriSizov commented
From the discussion we had in the production meeting today I can say that this is a good improvement, but there may be some suggestions on how to adjust this new UI. So to give it a bit time to polish I'm putting it onto 4.2. https://github.com/godotengine/godot/pull/78456 should already help a lot in 4.1.

2023-08-08 15:07 UTC, YuriSizov requested changes, later dismissed
Haven't tested, just the code and style review. Overall the editor bits look fine.

Design-wise, I think we use `LinkButton` (or meta tags if in RTL) for such actions, though. A normal button stands out more and is easier to understand, but it also kind of looks out of place. Not a blocker though.

2023-08-09 02:03 UTC, aaronfranke commented on editor/export/editor_export.h
> +#include "editor/import/resource_importer_texture_settings.h"
It's needed for these files:

<img width="335" alt="Screenshot 2023-08-08 at 9 01 28 PM" src="https://github.com/godotengine/godot/assets/1646875/4784638b-c903-4da6-af13-61579450b44d">

I could move the include to each of those files, if that's preferred.

2023-08-09 02:31 UTC, aaronfranke commented
> Design-wise, I think we use LinkButton (or meta tags if in RTL) for such actions, though. A normal button stands out more and is easier to understand, but it also kind of looks out of place. Not a blocker though.

Usually you would expect a LinkButton to, well, be a link to something, like opening a menu or web page. This button doesn't link to anything, it performs an action. A regular button makes more sense to me here.

2023-08-09 09:28 UTC, akien-mga commented on editor/export/editor_export.h
> +#include "editor/import/resource_importer_texture_settings.h"
Platform code should be safe contained, and platforms can be plugged in which don't exist in this repo (console ports, Haiku, etc.) so this isn't an option.

Not sure if what's done currently is correct either, haven't reviewed that yet. Just keep the modularity of platforms in mind, ideally `editor/` code shouldn't need to include platform code directly.

2023-08-09 10:29 UTC, YuriSizov commented on editor/export/editor_export.h
> +#include "editor/import/resource_importer_texture_settings.h"
@akien-mga I think it's the other way around, no? Aaron needs an include from editor in platform classes, which should be totally fine.

2023-08-09 10:58 UTC, akien-mga commented on editor/export/editor_export.h
> +#include "editor/import/resource_importer_texture_settings.h"
Oh right, that's good then.

2023-08-09 16:27 UTC, aaronfranke commented on editor/export/editor_export.h
> +#include "editor/import/resource_importer_texture_settings.h"
PR updated.

2023-08-17 07:22 UTC, akien-mga approved these changes
The overall feature looks good to me.

Also not convinced by the looks of this "Fix Import" button which looks a bit out of place in an error message IMO, but we can iterate on this further later.

2023-08-17 07:57 UTC, aaronfranke commented
Updated the PR to use a LinkButton (and re-tested).

<img width="710" alt="Screenshot 2023-08-17 at 2 56 21 AM" src="https://github.com/godotengine/godot/assets/1646875/f0a58330-fbbd-4ba0-80bd-bf577c760dc9">

2023-08-17 08:16 UTC, akien-mga commented
I like the look if it. I somewhat agree with your previous statement:

> Usually you would expect a LinkButton to, well, be a link to something, like opening a menu or web page. This button doesn't link to anything, it performs an action.

But somehow it still looks nicer like this :P

2023-08-17 08:24 UTC, clayjohn approved these changes
Changes look good from my perspective!

2023-08-17 09:28 UTC, merged

2023-08-24 12:23 UTC, YuriSizov commented on editor/export/project_export.cpp
> +		case NOTIFICATION_ENTER_TREE:
This was excessive btw, `NOTIFICATION_THEME_CHANGED` already fires when the node enters the tree.