C# Fix deserialization of delegates that are 0-parameter overloads
godotengine/godot pull request #78877
Opened 2023-06-30 15:05 UTC by mattdiener

`TryDeserializeSingleDelegate` causes `GetMethod` to throw when deserializing a method with a 0-parameter overload.

`GetMethod` without a `types` argument matches all methods with the given `name`, whereas a 0-length `types` argument explicitly matches methods with 0 parameters.

E.g.
```
private void OnValueChanged(float _) {
    OnValueChanged();
}

private void OnValueChanged() {
   //...
}

//...
{
    _mySlider.ValueChanged += OnValueChanged;
}
```

2023-06-30 15:08 UTC, mattdiener commented
Thanks ahead of time for your patience with my first PR. Happy to go back and add more details or spend some more time on a cohesive repro. I ran into this working on an editor plugin and this fix worked for me.

2023-06-30 15:09 UTC, AThousandShips commented
Please open an issue to track this more effectively, in case some other solution is required, or something else is wrong

2023-06-30 15:13 UTC, mattdiener commented
On it, thanks!

2023-06-30 19:11 UTC, raulsntos requested changes
Thanks for contributing to the .NET module!

Indeed, the [`Type.GetMethod`](https://learn.microsoft.com/en-us/dotnet/api/system.type.getmethod#system-type-getmethod(system-string-system-reflection-bindingflags)) documentation says that it throws an exception if:

> More than one method is found with the specified name and matching the specified binding constraints.

So if we are specifically looking for a method with no parameters, we should be using the overload that takes a parameter type array.

This PR already looks good to me :+1:, but I'd like you to make a small change to avoid allocating empty arrays.

2023-06-30 19:31 UTC, mattdiener commented
Created https://github.com/godotengine/godot/issues/78886.

2023-06-30 19:39 UTC, mattdiener commented
Re-tested with your change @raulsntos. Works just as well! thanks for the feedback!

2023-06-30 20:12 UTC, raulsntos approved these changes
The code looks good so I'm approving, but before we can merge you'll have to squash the commits into one.

Since it's your first time contributing, make sure to take a look at [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md) and the [contributing documentation](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) if you haven't already. It contains information about squashing, in case you need it.

Feel free to reach out in the [development chat](https://chat.godotengine.org) if you need help.

2023-07-12 13:22 UTC, merged

2023-07-12 13:24 UTC, YuriSizov commented
Thanks! And congrats on your first merged Godot PR!

Please consider in the future creating a feature branch for your PR instead of using your `master`. It would be more convenient for everyone, including yourself, if you plan to contribute more to the engine. Cheers!

2023-08-31 18:24 UTC, YuriSizov commented
Cherry-picked for 4.1.2.