Re-architect how Android plugins are packaged and handled at export time
godotengine/godot pull request #78958
Opened 2023-07-02 18:41 UTC by m4gr3d

The previous packaging format for Godot Android plugins consisted of the plugin's `gdap` config file accompanied by binaries defined in the `gdap` file. 
This format is now deprecated (starting with Godot 4.2), and instead Godot Android plugins are now packaged as `EditorExportPlugin` plugins.

The `EditorExportPlugin` class has been updated with the following methods to provide the necessary set of functionality:
- `_supports_platform`: returns true if the plugin supports the given platform
- `_get_android_dependencies`: retrieve the set of android dependencies (e.g: `org.godot.example:my-plugin:0.0.0`) provided by the plugin
- `_get_android_dependencies_maven_repos`: retrieve the urls of the maven repos for the provided android dependencies
- `_get_android_libraries`: retrieve the local paths of the android libraries (AAR files) provided by the plugin
- `_get_android_manifest_activity_element_contents`: update the contents of the `<activity>` element in the generated Android manifest
- `_get_android_manifest_application_element_contents`: update the contents of the `<application>` element in the generated Android manifest
- `_get_android_manifest_element_contents`: update the contents of the `<manifest>` element in the generated Android manifest

The last three methods allow the plugin to automatically provide changes to the app's manifest which are preserved when the editor is updated, resolving a long standing issue.

Fixes https://github.com/godotengine/godot/issues/76963
Fixes https://github.com/godotengine/godot/issues/78782

2023-07-02 18:44 UTC, m4gr3d commented
cc @naithar The same concept can be applied on iOS removing the need for the `.gdip` config file, and aligning all the plugins to the same architecture.

2023-07-03 12:48 UTC, BastiaanOlij commented
Amazing work @m4gr3d, this indeed solves all the issues we were discussing in the XR meeting. For any logic we add to the core we can add the needed features and permissions to the loader for each platform (though I still hope that in that scenario we'll end up with standardised strings in due time), for any OpenXR extension we implement as a GDExtension we'll be able to handle those in that extension by adding an export plugin class to that as well.

@kisg , @dsnopek you guys should review this as well.

2023-07-03 12:55 UTC, akien-mga commented
> cc @naithar The same concept can be applied on iOS removing the need for the `.gdip` config file, and aligning all the plugins to the same architecture.

For the record, naithar hasn't been actively contributing to Godot lately. @bruvzg is the sole maintainer for iOS, he might be able to have a look at doing the matching changes for iOS, though any help from interested contributors would be welcome.

2023-07-03 18:40 UTC, m4gr3d commented
Ran into a bug with restoring the saved values of the editor export plugin options from the preset:
- The preset is created in [EditorExport::load_config()](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export.cpp#L231)
- During its creation, it [retrieves the options from the platform and from the available export plugins](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export_platform.cpp#L331-L335) and use them to initialize a few maps and list. However this happens before editor plugins in the project have been loaded.
- This causes the saved export plugin options to be [discarded at loading time](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export.cpp#L309) because [they're not included in the preset's map](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export_preset.cpp#L34)

Given an export plugin can be added at any time, we may need to separate the platform options from the export plugins' options and store them in the preset regardless of whether the export plugin is available or not.

2023-07-04 21:33 UTC, m4gr3d commented
> Ran into a bug with restoring the saved values of the editor export plugin options from the preset:
> 
> * The preset is created in [EditorExport::load_config()](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export.cpp#L231)
> * During its creation, it [retrieves the options from the platform and from the available export plugins](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export_platform.cpp#L331-L335) and use them to initialize a few maps and list. However this happens before editor plugins in the project have been loaded.
> * This causes the saved export plugin options to be [discarded at loading time](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export.cpp#L309) because [they're not included in the preset's map](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export_preset.cpp#L34)
> 
> Given an export plugin can be added at any time, we may need to separate the platform options from the export plugins' options and store them in the preset regardless of whether the export plugin is available or not.

Fixed by https://github.com/godotengine/godot/pull/79025

2023-07-18 04:08 UTC, BastiaanOlij approved these changes
As mentioned before, I really like this new approach. Code wise it looks really good

2023-07-18 11:11 UTC, YuriSizov requested changes
A couple of nitpicks, but also a couple of bigger notes worth addressing.

2023-07-18 11:11 UTC, YuriSizov commented on editor/export/editor_export_plugin.cpp
> +	}
I think this should result in a warning, not in an early return. Unsupported platform does mean that configuration passed to this method is invalid. The caller can safely check for this cases itself (and you already do that, actually).

2023-07-18 11:11 UTC, YuriSizov commented on editor/export/editor_export_plugin.h
> +
These shouldn't be public themselves. If we need to call them from outside of the class, we need public counterparts. Yeah, it's a bit of boilerplate but it's for the sake of code clarity and maintainability. If this is only needed for some small hackish logic within editor/export plugin classes, you can also use class `friend`ness, while keeping the methods private.

2023-07-18 11:11 UTC, YuriSizov commented on editor/export/editor_export_preset.cpp
> +	// Get property warning for the editor export plugins
```suggestion
	// Get property warning from editor export plugins.
```

2023-07-18 12:59 UTC, YuriSizov commented on editor/export/editor_export_plugin.h
> +
Or rather, I think C++ virtual methods themselves can be public if that's how they are supposed to be used. Whichever you prefer.

2023-07-18 18:47 UTC, YuriSizov approved these changes

2023-07-18 18:47 UTC, merged

2023-07-18 18:47 UTC, YuriSizov commented
Thanks!

2023-07-26 16:51 UTC, m4gr3d commented
> If I understand correctly, only the way Godot interacts with the plugins has changed. The way the plugin is written remains the same. Am I correct?
> 
> I've checked the example repo, the package is placed inside the **addons** folder instead of **plugins/android**. Does this matter or location is irrelevant?

The plugin logic (java code) remains the same, but the configuration for the plugin, including the folder layout, are changed to the new format which better aligns with other types of Godot plugins.

> I've checked the example repo, the package is placed inside the addons folder instead of plugins/android. Does this matter or location is irrelevant?

Yes the location matters. See the [tutorial about making Godot plugins](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html) for reference.

The documentation for the Android plugins will be updated to reflect all of these changes prior to Godot 4.2 being stable. The current version of the documentation is now obsolete.

2023-07-29 17:43 UTC, tokengamedev commented
This is big change with respect to how plugins are handled. Can the documentation be updated earlier than beta release so that I can test it properly and if any issues than it can be fixed within 4.2 release

2023-07-29 18:49 UTC, m4gr3d commented
> This is big change with respect to how plugins are handled. Can the documentation be updated earlier than beta release so that I can test it properly and if any issues than it can be fixed within 4.2 release

It'll be done prior to the beta release, but there are a few more incoming changes / refactor so the documentation will be updated once those are landed and the full end to end plugin flow has been validated.

I'll be posting examples as the refactor progress so you can use those as reference until the documentation is updated.
The Godot OpenXR loader plugin for example has already been updated.

2023-08-12 04:58 UTC, WNJH commented
This is machine translation.
I want to delete “intent-filter“ from AndroidManifest.xml. However, after exporting as shown in the diagram, only elements are added.
How can I delete the red circle in the picture?
<img width="698" alt="屏幕截图 2023-08-12 103339" src="https://github.com/godotengine/godot/assets/96534717/e0a0b9af-5206-4fed-8a80-8ee53e651d2b">
<img width="1265" alt="屏幕截图 2023-08-12 103455" src="https://github.com/godotengine/godot/assets/96534717/4cba9585-6b02-4a4b-b39f-696c4b3963fc">

2023-08-12 13:16 UTC, m4gr3d commented
> This is machine translation. I want to delete “intent-filter“ from AndroidManifest.xml. However, after exporting as shown in the diagram, only elements are added. How can I delete the red circle in the picture? <img alt="屏幕截图 2023-08-12 103339" width="698" src="https://user-images.githubusercontent.com/96534717/260200431-e0a0b9af-5206-4fed-8a80-8ee53e651d2b.png"> <img alt="屏幕截图 2023-08-12 103455" width="1265" src="https://user-images.githubusercontent.com/96534717/260200446-4cba9585-6b02-4a4b-b39f-696c4b3963fc.png">

@WNJH it's not possible to do so on purpose to prevent export plugins from interfering with each other.
What are you trying to achieve by removing the default `intent-filter`?

2023-08-12 14:58 UTC, WNJH commented
> > 这是机器翻译。我想从 AndroidManifest 中删除“意图过滤器”.xml。但是，如图所示导出后，仅添加元素。如何删除图片中的红色圆圈？<img alt="屏幕截图 2023-08-12 103339" width="698" src="https://user-images.githubusercontent.com/96534717/260200431-e0a0b9af-5206-4fed-8a80-8ee53e651d2b.png"> <img alt="屏幕截图 2023-08-12 103455" width="1265" src="https://user-images.githubusercontent.com/96534717/260200446-4cba9585-6b02-4a4b-b39f-696c4b3963fc.png">
> 
> 不可能故意这样做以防止导出插件相互干扰。你想通过删除默认值来实现什么？`intent-filter`

Similar to this https://github.com/godotengine/godot/issues/78782#issue-1778268099
I want to start my custom activity before going to GodotApp and then jump to GodotApp with the button.
So I create a new activity and cut GodotApp's intent-filter from build\AndroidManifest.xml into the custom activity.
When I use "one-click deploy", two apps will be installed on my phone, One is a GodotApp and the other is a custom activity.
So I need to remove "intent-filter" from build\src\debug\AndroidManifest.xml.

build\AndroidManifest.xml:
<img width="488" alt="屏幕截图 2023-08-12 225133" src="https://github.com/godotengine/godot/assets/96534717/3cbf092a-0b09-49ad-b528-dd216ed71b83">

build\src\debug\AndroidManifest.xml:
<img width="532" alt="屏幕截图 2023-08-12 225234" src="https://github.com/godotengine/godot/assets/96534717/9a1dc05d-97de-43e0-a592-e3b8fa37c9dd">

My temporary solution is to make debug\AndroidManifest.xml read-only.

2023-08-12 22:33 UTC, m4gr3d commented
@WNJH Only the `android.intent.category.LAUNCHER` category needs to be removed. I'll add an export settings for doing so.

2023-08-12 22:47 UTC, m4gr3d commented
@WNJH I've added https://github.com/godotengine/godot/pull/80569 which adds an export setting to control whether the app shows in the app library.

2023-08-13 01:40 UTC, WNJH commented
@m4gr3d Thank you!

I have one more small question." one-click deploy" Does it have to go directly to GodotApp? After I annotated "intent-filter", "one-click deploy" did not display the custom activity. But when I quit, and tap into the APP on my phone, the custom activity is displayed.

2023-08-13 13:57 UTC, m4gr3d commented
> @m4gr3d Thank you!
> 
> I have one more small question." one-click deploy" Does it have to go directly to GodotApp? After I annotated "intent-filter", "one-click deploy" did not display the custom activity. But when I quit, and tap into the APP on my phone, the custom activity is displayed.

@WNJH Yes it launches the `GodotApp` directly. 
@BastiaanOlij is working on a proposal to improve the launch flow. As part of that proposal, we can add the option to specify which activity to launch, but for the moment it's hardcoded to the `GodotApp` since that's the most prevalent launch flow.

2023-08-18 18:50 UTC, duarteroso commented
Is there an early version of the updated documentation that I could read? Having a crash in gd_mono.cpp:431 and I believe it to be related to the GodotPlugins with a failed initialization (a blank project works fine). 
Instead of opening an issue, I'd rather try seriously 🙂

2023-09-06 10:41 UTC, m4gr3d commented
> Is there an early version of the updated documentation that I could read? Having a crash in gd_mono.cpp:431 and I believe it to be related to the GodotPlugins with a failed initialization (a blank project works fine). Instead of opening an issue, I'd rather try seriously 🙂

@duarteroso Early draft of the documentation update available in https://github.com/godotengine/godot-docs/pull/7884