Fixes "Create shader Node" window position when visual shader editor is floating
godotengine/godot pull request #78996
Opened 2023-07-03 18:36 UTC by Tetane

Fixes the issue where the "Create shader node" window was appearing inside the boundaries of the main Godot editor window instead of the visual shader editor window when it's floating. (mentioned in issue #78854.)

2023-07-03 19:24 UTC, trollodel requested changes
I would set the dialog `current_screen` to the `get_window()` one, because I'm not sure if the screens space is unified in all platforms.

2023-07-03 19:44 UTC, Tetane commented
@trollodel Something like that: `members_dialog->set_current_screen(get_window()->get_current_screen());`?
(I only tested on Windows 10, I can't currently test on other platforms.)

2023-07-23 14:10 UTC, trollodel commented
> trollodel Something like that: `members_dialog->set_current_screen(get_window()->get_current_screen());`? (I only tested on Windows 10, I can't currently test on other platforms.)

Sorry for the late response, but yes, like that.

2023-08-20 11:00 UTC, Sauermann approved these changes
Using `DisplayServer` was the cause of the problem, that this PR fixes.
Have also tested single-window-mode and didn't notice any problems.

During testing I noticed, that it is possible to move the window-title outside of the screen-area, when placing the shader-dock on the top of the screen, but this can also be solved in a separate PR:
![image](https://github.com/godotengine/godot/assets/6299227/5fb33aae-a024-41cf-93ac-20ce0328396e)

2023-08-21 06:29 UTC, merged

2023-08-21 06:30 UTC, akien-mga commented
Thanks!