Expose `String.resize()`
godotengine/godot pull request #79177
Opened 2023-07-07 22:05 UTC by dsnopek

This supersedes PR https://github.com/godotengine/godot/pull/79156 (which didn't expose `String.resize()` the normal way, but instead added a function to `gdextension_interface.h` so it wouldn't be exposed to GDScript)

The one thing I'm concerned about (now that this would be exposed to GDScript) is that `resize()` takes the array size of the string (so, including the null terminator character), but `length()` returns the string length (so, without the null terminator aka 1 less than the array length).

Will this be too confusing to users? Would it make sense to also expose `size()` so that `str.resize(str.size() + 2)` clearly makes the string 2 characters longer? Or, will having both `size()` and `length()` just be even more confusing? Or, should the version of `String.resize()` that's exposed be made to work with string length, rather than array length?

Fixes godot-cpp issue https://github.com/godotengine/godot-cpp/issues/1141 which originally came up when trying to compile the text_server_adv module in Godot as a GDExtension. See: https://github.com/godotengine/godot/pull/77532

2023-07-07 22:15 UTC, bruvzg approved these changes

2023-07-07 22:17 UTC, bruvzg commented
> Will this be too confusing to users? Would it make sense to also expose size()

I guess it makes sense to expose size as well.

2023-07-07 23:02 UTC, JoNax97 commented
How does length/size work with multi-byte characters? I assume size() counts raw bytes, right?

2023-07-07 23:35 UTC, aaronfranke commented on doc/classes/String.xml
> +				Resizes this string to the new size. The size should be one more than desired string length (in order to accommodate the null terminator).
Doesn't this make the String data mutable?

In most programming languages, Strings are immutable. I think this is true for all String methods in GDScript except for this one. Wouldn't it be better to return a copy that's resized?

2023-07-08 01:29 UTC, dsnopek commented
> How does length/size work with multi-byte characters? I assume size() counts raw bytes, right?

String stores it's data as an array of `char32_t` encoded as UTF-32, so each item in the array represents a single unicode character. `size()` counts the number of `char32_t`'s in the array (including the null terminator) and `length()` does the same but excludes the null terminator.

2023-07-08 05:18 UTC, AThousandShips commented
Strings have to be immutable in GDScript AFIK, as they are COW you can't modify them via methods but only by assignment, this is why there aren't any mutable methods to them (and why several mutable methods were removed previously, like `erase`)

2023-07-08 06:44 UTC, bruvzg commented
Strings aren't immutable, there's an `[]` operator already.

2023-07-08 06:51 UTC, AThousandShips commented
My bad, not sure what has changed in core to make that possible

2023-07-08 06:58 UTC, bruvzg commented
> not sure what has changed in core to make that possible

I think it was always the case, at least it is in 3.5.

2023-07-08 06:59 UTC, AThousandShips commented
Does this actually work for properties though? That's the issue with mutability, not that variant of it can be mutated

Test for example:
```gdscript
class TestClass:
    var s0 := "abc"

func foo():
    var t0 := TestClass.new()
    print(t0.s0) # Prints "abc"
    t0.s0.resize(3)
    print(t0.s0) # Still prints "abc", not "ab"
```

2023-07-08 07:02 UTC, AThousandShips commented
This is why some methods were removed from `Transform2D`, like `set_shear/scale/rotation` because they were confusing

This also affects arrays, like:
```gdscript
var arr := ["abc"]
print(arr[0])
arr[0].resize(3)
print(arr[0])
```

2023-07-08 07:02 UTC, bruvzg commented
> Does this actually work for properties though? That's the issue with mutability, not that variant of it can be mutated

Yes and no, it will change the value of a variable in the object, but won't trigger any extra code in the setter function (same is true for any type which doesn't have `changed` signal, like `Array` or `Dictionary` - like https://github.com/godotengine/godot/pull/79166).

2023-07-08 07:03 UTC, AThousandShips commented
It won't change the value though, see the above code, I've verified that

2023-07-08 07:15 UTC, bruvzg commented
Well, if it's not desired and there are issues with GDScript (seems like a GDScript bug to me), I guess it's better to use https://github.com/godotengine/godot/pull/79156 instead. `resize()` + raw `ptrw()` definitely should be accessible for GDExtension, other methods of constructing strings are much slower.

2023-07-08 07:15 UTC, bruvzg commented
> The only reason the [] operator works is because it uses a proxy

Maybe it should not be exposed to scripting in this case?

2023-07-08 07:17 UTC, AThousandShips commented
Agreed, but exposing a method that is confusing in GDScript shouldn't be done, imo even with a warning it'll be annoying

Unsure how to expose resize just for GDExtension

2023-07-08 09:16 UTC, dalexeev commented
I agree that exposing `size()` can be confusing. I think this is a low-level detail that has no practical use for users.

Also I don't think we should expose `resize()` as is. I would expect `resize()` to change the length of the string, i.e. the number of characters without the null terminator. Maybe we can add a method with some other name (so as not to increase the inconsistency between GDScript and C++)? Like `set_length()` or `resize_length()`?

2023-07-08 09:18 UTC, AThousandShips commented
That still won't work correctly unless it's returning a string by copy instead of mutating

2023-07-08 09:46 UTC, AThousandShips requested changes
The `resize` method, other than the mutability issues, needs to be implemented so it handles null termination correctly, the current version creates defective strings, test:
```gdscript
var s0 := "abcd"
var s1 := "ab"
s0.resize(3)
print(hash(s0))
print(hash(s1))
```

These will print different results

Haven't tested but this implies that there are some concerns with how accessing the raw string will work

In fact you will notice that the hash *changes* each time you run, implying it keeps going after the end of the string, this likely risks crashing if it doesn't catch a zero correctly

Edit: It also breaks if you change the size to be larger, as it doesn't ensure zeros

2023-07-08 12:35 UTC, dsnopek commented
Thanks, Everyone, for all the great discussion and insight! 

I'm a little confused about the conclusion, though. Is the consensus that we should return to https://github.com/godotengine/godot/pull/79156? I wouldn't mind, I personally liked that approach better anyway. :-) Or, that we should make a better `resize()` that can be exposed to GDScript too?

2023-07-08 13:47 UTC, AThousandShips commented
It wouldn't be possible to do a "modify in place" `resize` for GDScript without massively changing the underlying implementation, without causing the confusion above

For GDExtension it depends on the usecase if it should do dedicated null handling IMO, the limitation here is that from GDScript it's cumbersome and weird to handle nulls internally without having them automatically (see above for the actually impossible situations), but GDExtension might be closer to bare metal to have the performance critical version

It would probably not be good to have the default method do any zeroing, as it would likely be expected to insert null elsewhere

2023-07-08 13:50 UTC, dsnopek commented
Alright, I'll re-open PR https://github.com/godotengine/godot/pull/79156 and close this one!

2023-07-08 13:50 UTC, closed without merging