Add a test suite for TranslationServer
godotengine/godot pull request #79317
Opened 2023-07-11 07:48 UTC by azuloo

A test suit that covers `TranslationServer`, see #43440 for more details.

2023-07-11 10:48 UTC, azuloo commented
I've fixed formatting issues and removed unneeded includes. Also squished 2 commits into one.

2023-07-11 10:52 UTC, AThousandShips requested changes

2023-07-11 10:52 UTC, AThousandShips commented on tests/core/string/test_translation_server.h
> +	// Newly created Translation object should be added to the list, so the counter should increase, too
```suggestion
	// Newly created Translation object should be added to the list, so the counter should increase, too.
```

Comments should start with a capital and end with a period, same elsewhere

2023-07-11 10:52 UTC, AThousandShips commented on tests/core/string/test_translation_server.h
> +	// No such variant in variant_map; should return everyting except the variant
```suggestion
	// No such variant in variant_map; should return everything except the variant
```

2023-07-11 10:53 UTC, AThousandShips commented
Go ahead and update the commit message spelling when fixing the issues

2023-07-11 10:57 UTC, closed without merging

2023-07-11 10:58 UTC, AThousandShips commented
You accidentally reset your branch to `master`, automatically closing the PR, you need to open a new one

2023-07-13 21:51 UTC, Calinou commented
Superseded by https://github.com/godotengine/godot/pull/79331.