Include Display Server Type in Copy System Info
godotengine/godot pull request #79396
Opened 2023-07-12 21:15 UTC by Sauermann

Add info about X11 or Wayland to System Information on LinuxBSD.

2023-07-12 22:35 UTC, Calinou requested changes

2023-07-12 22:45 UTC, Calinou commented
Tested locally (rebased on top of `master` 60f3b7967cbd00b4e1f52d33d372646f7bec02f6
), it works as expected.

```
Godot v4.2.dev (38c6a02a8) - Fedora Linux 38 (KDE Plasma) - X 11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 535.54.03) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)
```

However, `capitalize()` makes it write "X 11" instead of "X11". This could be fixed using `.capitalize().replace(" ", "")`.

2023-07-12 22:46 UTC, Sauermann commented on editor/editor_node.cpp
> +	const String display_server = OS::get_singleton()->get_environment("XDG_SESSION_TYPE");
Thanks, I have included your change. `capitalize()` makes it write `X 11` (with a whitespace between).

2023-07-12 22:49 UTC, Sauermann commented
Yes, that addition fixed it.

2023-07-12 22:56 UTC, Calinou approved these changes

2023-07-15 06:02 UTC, deralmas requested changes
I've found one tiny flaw in the logic but other than that and a nitpick this looks great!

2023-07-15 07:27 UTC, Sauermann commented on editor/editor_node.cpp
> +	const String display_server = OS::get_singleton()->get_environment("XDG_SESSION_TYPE").capitalize().replace(" ", "");
Just to be on the same page ... a few lines down, I check for `display_server.is_empty()`.
In the case, that it is empty, display-server-info is simply left out.
I'm not sure, if adding `Unknown Display Server` would help?!

The comment is a good idea. Will add an explanation.

2023-07-17 20:35 UTC, deralmas approved these changes
Fantastic! This will avoid us so many headaches :)

2023-07-21 16:02 UTC, merged

2023-07-21 16:07 UTC, YuriSizov commented
Thanks!

2023-08-31 18:21 UTC, YuriSizov commented
Cherry-picked for 4.1.2.