Fix physics passive hovering with `MOUSE_FILTER_IGNORE`
godotengine/godot pull request #79443
Opened 2023-07-13 21:26 UTC by Sauermann

When the parent `SubViewportContainer` ignores mouse, then the `SubViewport` shouldn't create mouse-move-events for passive hovering.

resolve #79441
follow-up to #78017

2023-07-17 10:15 UTC, RandomShaper requested changes
When `parent_ignore_mouse` is true, the `for` loop can be skipped.

2023-07-17 11:35 UTC, Sauermann commented
I'm not entirely sure, if that is correct, because the loop covers also non-mouse events, like `InputEventScreenDrag`.
Skipping the loop in the case `parent_ignore_mouse == true` would mean, that `InputEventScreenDrag`-events don't get evaluated.
Also ... skipping would have the effect, that these events stay in `Viewort::physics_picking_events` to be executed during the next physics-frame(s).

2023-07-19 09:39 UTC, RandomShaper commented
My point was about putting the loop inside an `if` because it was only used to determine if `has_mouse_event` should be `true`. If other conditions didn't meet, the value of `has_mouse_event` was unused. But you have already changed the code, eliminating the loop altogether, and I can't say for sure now.

2023-07-19 09:45 UTC, Sauermann commented
Now I understand you. I was talking about a different loop, than you were.
With that in mind, I agree and will update the PR.

2023-07-26 11:02 UTC, RandomShaper approved these changes
Isn't the wording of the various filter modes inaccurate as they say things like "the control will not receive mouse button input [...]"? I mean, it's not only about buttons but also movement, isn't it?

2023-07-26 16:48 UTC, merged

2023-07-26 16:50 UTC, YuriSizov commented
Thanks!