Add a nearest-neighbor scaling option to Viewport's Scaling 3D Mode property
godotengine/godot pull request #79731
Opened 2023-07-20 23:58 UTC by Calinou

This is useful for 3D games with a pixel art appearance, or when using a resolution scale of `0.5` to improve performance without compromising crispness too much when not using FSR 1.0.

The property hints now allow decreasing the scale further to accomodate for pixel art use cases, as well as increased precision in the value (useful for a scale of `0.3333`).

This is supported in both Forward+ and Mobile rendering methods. See https://github.com/godotengine/godot/issues/70142 for the Compatibility rendering method.

I've made sure that effects relying on bilinear filtering to look correct (such as glow and depth of field) still work correctly.

**Testing project:** [test_scaling_3d_nearest.zip](https://github.com/godotengine/godot/files/12114807/test_scaling_3d_nearest.zip)

- This closes https://github.com/godotengine/godot-proposals/issues/4697.

## Preview

### Bilinear

![Screenshot_20230721_014809](https://github.com/godotengine/godot/assets/180032/9e368a43-ee6c-4a96-939d-7fbbadfccdd0)

### AMD FSR 1.0

![Screenshot_20230721_014756](https://github.com/godotengine/godot/assets/180032/e17c1ad7-e70f-4508-b514-c80283b6a602)

### Nearest *(this PR)*

![Screenshot_20230721_014711](https://github.com/godotengine/godot/assets/180032/f2757542-05bf-4697-a574-a5bb0f5dc03f)

2023-07-21 07:06 UTC, Sauermann commented
I 'm not familiar with RenderingServer, but would this help with #72548?

2023-07-21 16:38 UTC, Calinou commented
> I 'm not familiar with RenderingServer, but would this help with #72548?

Not entirely, as the use case from that issue is to scale both the 2D and 3D rendering. We only have `scaling_3d_scale`, not `scaling_2d_scale` :slightly_smiling_face:

2023-09-25 22:30 UTC, Calinou commented
Rebased and tested again, it works as expected.

2023-10-02 10:54 UTC, akien-mga commented
CC @DarioSamo

2023-10-02 11:34 UTC, DarioSamo commented
Looks fine to me, although I'm not the biggest fan of nearest due to the shimmering on uneven pixel scales it makes sense to provide the option regardless.

For games that actually want to preserve the pixel art aspect, I'm a bigger fan of filters like [these](https://www.shadertoy.com/view/csX3RH), although they're free performance wise compared to nearest.

But like I said this is one case where the more options the better.

2023-11-28 16:09 UTC, mrjustaguy commented
What happens if you set resolution scale above 1 with nearest scaling? such as 2?
In such scenarios I can see it breaking and might be better to check for that case and revert to bilinear

2023-11-28 17:43 UTC, Calinou commented
> What happens if you set resolution scale above 1 with nearest scaling? such as 2? In such scenarios I can see it breaking and might be better to check for that case and revert to bilinear

It reverts to bilinear automatically if resolution scale is above 1.0.

2024-05-02 20:52 UTC, Calinou commented
Rebased and tested again, it works as expected.

Note that 3D scaling support was implemented in the Compatibility rendering method in https://github.com/godotengine/godot/pull/83976, but I haven't implemented nearest-neighbor filtering there yet.

2024-05-09 15:12 UTC, Calinou commented
It's implemented in Compatibility now:

### Bilinear

![godot windows editor x86_64_5RbHuxXRVt](https://github.com/godotengine/godot/assets/180032/b208b3d3-8587-4071-9a75-01cdbd9d7c93)

### Nearest

![godot windows editor x86_64_YfK94QxbKT](https://github.com/godotengine/godot/assets/180032/1b7eae6b-ae9e-4720-b021-962ff69a88ff)

2024-05-20 14:07 UTC, GlitchedPolygons commented
pls pls merge this soon <3

2024-05-20 14:11 UTC, AThousandShips commented
@GlitchedPolygons Please don't bump without contributing significant new information. Use the :+1: reaction button on the first post instead.

2024-05-20 14:13 UTC, GlitchedPolygons commented
> @GlitchedPolygons Please don't bump without contributing significant new information. Use the 👍 reaction button on the first post instead.

sry, I'm new here and I got excited with this PR :)

is there anywhere else where I can add my vote for this?

2024-12-04 22:36 UTC, RadiantUwU approved these changes
Tested, working as expected.

2024-12-05 03:27 UTC, clayjohn commented on servers/rendering/renderer_rd/effects/tone_mapper.cpp
> +	u_source_color.append_id(viewport_scale_sampler);
I'm a bit confused about this, you are passing in a sampler, but its in an input attachment, not a `UNIFORM_TYPE_SAMPLER_WITH_TEXTURE`. Additionally, clearly this was working previously without a linear sampler, and yet there are no shader changes to accommodate  the sampler. 

How does this work?

2024-12-11 15:53 UTC, Framebuffers commented
Hi, I did a game with this PR baked in for a game jam. The game needed this kind of look, so I self-compiled the engine with this PR baked into the engine. Its code is in [my GitHub as Premonition.](https://github.com/Framebuffers/Premonition) 

On that repo's description there's a link to the binary on itch.io. The game itself is written in C#, and the code isn't good at all. However, it's a good tech demo of how the PR would look like on a released game.

Hope it helps, and thanks @Calinou for your hard work on the engine! Really hope I can contribute little by little and give back to this wonderful community.

2025-01-07 00:02 UTC, Calinou commented
Rebased and tested again following the merge of https://github.com/godotengine/godot/pull/99603, it works as expected.

Note that if you were already using this PR locally, you'll have to reassign the **Scaling 3D Mode** project setting and/or Viewport property as the enum values were shifted around (**Nearest** is now at `5` instead of `3` to accomodate for the MetalFX options being placed before it). The enum's ordering in the project setting was changed so that Nearest is displayed first, but Bilinear remains the default. (This does not affect the actual enum values, it's an editor-only change using property hints.)

2025-01-25 11:05 UTC, Calinou commented on servers/rendering/renderer_rd/effects/tone_mapper.cpp
> +	u_source_color.append_id(viewport_scale_sampler);
I've changed it to `RD::UNIFORM_TYPE_SAMPLER_WITH_TEXTURE` and can confirm it still works.

2025-03-31 18:25 UTC, Calinou commented
Rebased and tested again, it mostly works as expected.

Nearest-neighbor scaling in Compatibility broke because the value that is read in `drivers/gles3/effects/post_effects.cpp` is always `0` (bilinear). I've put numerous prints to try to troubleshoot this and it's set correctly in RendererViewport. I don't know at which point exactly the value is no longer being passed around correctly.

2025-04-01 14:09 UTC, clayjohn approved these changes
Looks good now! Thanks for taking another look

Should be good once you figure out the compatibility issue. It might early out if any the scale_3d is anything but zero in the viewport renderer code

2025-04-19 23:01 UTC, SimplyBLGDev commented
Hope this is merged soon 👍

2025-04-21 16:11 UTC, Dowsley commented
Hello, is there any plan to merge this? Or does it already exists in any form (other PR maybe)?

2025-04-21 19:35 UTC, stuartcarnie commented
@Calinou did you solve this?

2025-04-21 21:09 UTC, Calinou commented
> @Calinou did you solve this?

No, I haven't found a way to resolve this. Feel free to look into it and open a PR if you manage to find a solution 🙂

2025-04-30 12:32 UTC, SimplyBLGDev commented
Is there a problem with godotengine/core team (reviewer)? It seems to lead to a 404 page

2025-07-24 04:29 UTC, danbolt commented
@Calinou I think I found the issue with the Compatibility regression. We're reverting to bilinear if we don't support FSR, but I think we're missing a check for nearest-neighbor now. Note:
https://github.com/godotengine/godot/blob/e0603aeda3ce0e15c5843f5202172a56f3ff5534/servers/rendering/renderer_viewport.cpp#L181

I have a PR for your branch here:
https://github.com/Calinou/godot/pull/12

Please let me know if I can elaborate or if you need anything else, and thanks for your hard work! I'm really glad to have this feature for my current personal project.

2025-07-24 18:08 UTC, Calinou commented
Rebased and tested again on macOS, it works as expected in all rendering methods (I also tested Metal).

@danbolt Works great, thanks! I've added you as a co-author 🙂

2025-09-16 10:15 UTC, F3der1co commented
this was approved but not moved to a release milestone, maybe an oversight or anything else holding this back? I would love to have this in 4.6

2025-09-16 15:18 UTC, Repiteo commented
Needs rebase

2025-09-16 22:57 UTC, Calinou commented
Rebased and tested again, it works as expected.

However, it broke in Compatibility (acting like Bilinear) despite @danbolt's change still being present. I don't know why.

2025-09-18 06:34 UTC, Kaleb-Reid commented
@Calinou I submitted a PR to your repo which I believe fixes the issue in Compatibility.

2025-09-18 08:13 UTC, danbolt commented
I tested @Kaleb-Reid s changes locally, and they address the issue we're seeing with the Compatibility renderer:

<img width="1890" height="980" alt="Screenshot_2025-09-18_15-57-04" src="https://github.com/user-attachments/assets/652fc1ce-ce21-44dc-b438-9f9a62089edb" />

Looking great!

2025-09-18 15:26 UTC, Calinou commented
I've tested the PR in question on macOS and it works great 🙂 

This should be good to merge now.

2025-10-13 01:12 UTC, Kaleb-Reid commented on servers/rendering/renderer_rd/effects/tone_mapper.cpp
> +	u_source_color.uniform_type = RD::UNIFORM_TYPE_SAMPLER_WITH_TEXTURE;
This breaks rendering in Mobile for me, where most Mobile projects spam this error and fail to render:
```
ERROR: Mismatch uniform type for binding (0), set (0). Expected 'InputAttachment', supplied: 'CombinedSampler'.
   at: uniform_set_create (servers/rendering/rendering_device.cpp:3601)
ERROR: Condition "rid.is_null()" is true. Returning: rid
   at: _allocate_from_uniforms (./servers/rendering/renderer_rd/uniform_set_cache_rd.h:120)
ERROR: Parameter "uniform_set" is null.
   at: draw_list_bind_uniform_set (servers/rendering/rendering_device.cpp:4636)
ERROR: Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline.
   at: draw_list_draw (servers/rendering/rendering_device.cpp:4782
```
I'm thinking it's related to this: https://github.com/godotengine/godot/blob/cb7cd815eeeb11aaa1f68453a515c76bec5ba73d/servers/rendering/renderer_rd/shaders/effects/tonemap.glsl#L41-L42

2025-10-13 02:00 UTC, Kaleb-Reid commented on servers/rendering/renderer_rd/effects/tone_mapper.cpp
> +	u_source_color.uniform_type = RD::UNIFORM_TYPE_SAMPLER_WITH_TEXTURE;
I've made https://github.com/Calinou/godot/pull/14 to fix this. I think that the changes here are not necessary in terms of correctness?

2025-10-14 11:20 UTC, AThousandShips commented on servers/rendering/renderer_viewport.cpp
> +				// FSR, MetalFX and nearest-neighbor scaling are not designed for downsampling.
```suggestion
				// FSR, MetalFX, and nearest-neighbor scaling are not designed for downsampling.
```

2025-10-14 11:20 UTC, AThousandShips commented on servers/rendering/renderer_viewport.cpp
> +				WARN_PRINT_ONCE("FSR, MetalFX or nearest-neighbor 3D resolution scaling is not designed for downsampling. Falling back to bilinear 3D resolution scaling.");
```suggestion
				WARN_PRINT_ONCE("FSR, MetalFX, and nearest-neighbor 3D resolution scaling are not designed for downsampling. Falling back to bilinear 3D resolution scaling.");
```

2025-10-14 11:20 UTC, AThousandShips commented on doc/classes/ProjectSettings.xml
> +			[b]Note:[/b] When using the [b]Nearest[/b] scaling mode, to avoid uneven pixel scaling, it's highly recommended to use a value equal to an integer divisor of 1, such as [code]1.0 / 2 = 0.5[/code].
```suggestion
			[b]Note:[/b] When using the [b]Nearest[/b] scaling mode, to avoid uneven pixel scaling, it's highly recommended to use a value equal to an integer divisor of [code]1[/code], such as [code]1.0 / 2 = 0.5[/code]. For example, it's best to use a scale of [code]0.5[/code] (2×2), [code]0.3333[/code] (3×3), [code]0.25[/code] (4×4), [code]0.2[/code] (5×5), and so on.
```

2025-10-14 11:20 UTC, AThousandShips commented on doc/classes/RenderingServer.xml
> +			[b]Note:[/b] To avoid uneven pixel scaling, it's highly recommended to use a value equal to an integer divisor of 1, such as [code]1.0 / 2 = 0.5[/code]. For example, it's best to use a scale of [c
```suggestion
			[b]Note:[/b] To avoid uneven pixel scaling, it's highly recommended to use a value equal to an integer divisor of [code]1[/code], such as [code]1.0 / 2 = 0.5[/code]. For example, it's best to use a scale of [code]0.5[/code] (2×2), [code]0.3333[/code] (3×3), [code]0.25[/code] (4×4), [code]0.2[/code] (5×5), and so on.
```

2025-10-14 11:20 UTC, AThousandShips commented on doc/classes/Viewport.xml
> +			[b]Note:[/b] To avoid uneven pixel scaling, it's highly recommended to use a value equal to an integer divisor of 1, such as [code]1.0 / 2 = 0.5[/code]. For example, it's best to use a scale of [c
```suggestion
			[b]Note:[/b] To avoid uneven pixel scaling, it's highly recommended to use a value equal to an integer divisor of [code]1[/code], such as [code]1.0 / 2 = 0.5[/code]. For example, it's best to use a scale of [code]0.5[/code] (2×2), [code]0.3333[/code] (3×3), [code]0.25[/code] (4×4), [code]0.2[/code] (5×5), and so on.
```

2025-10-14 20:42 UTC, AThousandShips commented on servers/rendering/renderer_viewport.cpp
> +				WARN_PRINT_ONCE("FSR, MetalFX, or nearest-neighbor 3D resolution scaling is not designed for downsampling. Falling back to bilinear 3D resolution scaling.");
```suggestion
				WARN_PRINT_ONCE("FSR, MetalFX, and nearest-neighbor 3D resolution scaling are not designed for downsampling. Falling back to bilinear 3D resolution scaling.");
```
"Or" doesn't fit in this case

2025-11-13 18:20 UTC, Calinou commented
Rebased and tested on all renderers, it works as expected.

2025-11-16 10:04 UTC, danbolt commented
@Calinou I think I found the issue with the GitHub Actions checks failing. Perhaps the rebase kept a now-unused variable? This caused the build to fail with `dev_mode` enabled, turning warnings into errors.

I've created a Pull Request for your branch here:
https://github.com/Calinou/godot/pull/15

EDIT: Also, I've tested with the changes applied to a recent `HEAD` of `ef34c3d534a` and everything still works great. :+1:

2025-11-18 00:03 UTC, Calinou commented
> @Calinou I think I found the issue with the GitHub Actions checks failing. Perhaps the rebase kept a now-unused variable? This caused the build to fail with dev_mode enabled, turning warnings into errors.

The variable is supposed to be used (it was introduced in a recent PR). The fact it's not used is a bug from my rebase, but we shouldn't remove the variable declaration.

I'll take a look.

2025-11-18 00:06 UTC, danbolt commented
> > @Calinou I think I found the issue with the GitHub Actions checks failing. Perhaps the rebase kept a now-unused variable? This caused the build to fail with dev_mode enabled, turning warnings into errors.
> 
> The variable is supposed to be used (it was introduced in a recent PR). The fact it's not used is a bug from my rebase, but we shouldn't remove the variable declaration.

Ah, my mistake!

I’ll close the PR. Thank you for letting me know.

2025-11-18 17:46 UTC, Calinou commented
> Ah, my mistake!
> 
> I’ll close the PR. Thank you for letting me know.

Actually, you were correct. The variable doesn't exist anymore in `master`, so I went ahead and applied your PR manually. Thanks :slightly_smiling_face:

2025-11-24 23:15 UTC, Berkru commented
As a 3D retro style artist, this is what is preventing me to upgrade from 3.6 to 4.x... would be awesome to have it in 4.6... is there any chance?

2025-11-25 23:44 UTC, allenwp commented on doc/classes/ProjectSettings.xml
> +			[b]Note:[/b] When using the [b]Nearest[/b] scaling mode, to avoid uneven pixel scaling, it's highly recommended to use a value equal to an integer divisor of [code]1[/code], such as [code]1.0 / 2
I'm confused by this. I would expect it to be written as follows?

```suggestion
			[b]Note:[/b] When using the [b]Nearest[/b] scaling mode, to avoid uneven pixel scaling, it's highly recommended to use a value equal to an integer divisor with a dividend of [code]1[/code]. For example, it's best to use a scale of [code]0.5[/code] (1/2), [code]0.3333[/code] (1/3), [code]0.25[/code] (1/4), [code]0.2[/code] (1/5), and so on.
```

If this is correct and adopted, it should be copied to the other places in this PR that use this text.

2025-11-26 14:27 UTC, allenwp commented on servers/rendering/renderer_viewport.cpp
> +			bool scaling_3d_is_not_nearest_or_bilinear = scaling_3d_mode != RS::VIEWPORT_SCALING_3D_MODE_OFF && ((scaling_3d_mode != RS::VIEWPORT_SCALING_3D_MODE_NEAREST) && (scaling_3d_mode != RS::VIEWPORT_S
```suggestion
			bool scaling_3d_is_not_nearest_or_bilinear = scaling_3d_mode != RS::VIEWPORT_SCALING_3D_MODE_OFF && (scaling_3d_mode != RS::VIEWPORT_SCALING_3D_MODE_NEAREST && scaling_3d_mode != RS::VIEWPORT_SCALING_3D_MODE_BILINEAR);
```

2025-11-26 15:53 UTC, allenwp commented
It seems like the scaling is behaving well, including centring:

Scale | Icon | Image 1 | Image 2
-- | -- | -- | --
Bilinear 1.00 | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/3fc03393-4989-45d1-9c0d-b1d563cc98bd" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/2921e1c4-c55c-4e98-9b05-62c93566b632" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/ecd38ecf-5c08-434f-ae0b-2d57e0720202" />
Nearest-neighbor 1.00 | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/3b471797-14f4-4bde-80ec-930e7c3206b3" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/0bce6a6c-56b1-44c4-a05b-e3656647093c" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/e2d6d270-ce69-40ec-893f-4af4199e9083" />
Bilinear 0.5 | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/dbcece84-96a6-442e-9982-c78ff48a2507" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/f4818838-2fe6-4033-848f-0ed0190613b0" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/86e3793a-0a79-475a-bcac-76b1dbd48458" />
Nearest-neighbor 0.5 | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/0dc864b4-5620-4ff5-97cc-881cb2ccf18b" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/118a3504-0795-4e49-8e43-73900509d546" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/6b89e903-be3f-4aa6-a7a8-7aa3d771a7bb" />
Bilinear 0.3333 | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/4bb7c974-7e86-4603-b4c5-2bc689c68d86" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/a7a01663-477e-462e-a3fd-1a5e3522f4e4" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/2c85f1a2-14da-43e2-afa4-745a6098f8ad" />
Nearest-neighbor 0.3333 | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/698bb1f0-ea1b-444f-b753-60c33ae8c447" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/073981bf-6021-46ae-8c8f-189c6d4bde1d" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/1f9f09cf-3f1a-424a-a6cf-64ae35cf8df3" />
Bilinear 0.2 | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/e8886b9f-3ff5-4880-b6a0-61885de2f135" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/cac95c52-a1e1-4a9e-abaa-1ff6819fae20" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/b69100fe-4ff4-4722-b14f-c6c6edb693a8" />
Nearest-neighbor 0.2 | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/e86bf392-a422-4df5-be1c-7c81f490f516" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/8bda05b4-a7e4-4ecb-aab7-dba4b2c364a7" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/2a3ed8fc-13ed-47b6-9db5-9be567168c20" />
Bilinear 0.1 | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/e3745361-1de2-4318-adf9-b2317e8ee6a4" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/8690093e-47b8-48c5-8741-14a0954e1476" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/8460e9ff-0537-4e89-92d5-2eb68afe79c9" />
Nearest-neighbor 0.1 | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/b5ab5cac-cf13-4554-9894-c6d0fefcc6eb" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/8a8da45b-ba3d-4ca8-89a3-fac0cf5c229e" /> | <img width="256" height="256" alt="image" src="https://github.com/user-attachments/assets/992118ab-fefe-469c-a1a4-d484af0289bc" />

(Check out that 0.1 scaling of the Godot icon 😂)

2025-11-26 16:11 UTC, allenwp commented
This is unrelated to this PR, but the default values for `SubViewport` are confusing to me. This is a screenshot of Godot 4.5.1:
<img width="410" height="379" alt="image" src="https://github.com/user-attachments/assets/e1a582a1-d5a7-4d0e-b50b-917a150a6ae4" />

It seems they try and match your project settings? But it doesn't seem to work consistently... Anyway, it doesn't seem to be a behaviour of this PR.

2025-11-26 16:44 UTC, allenwp commented on servers/rendering/renderer_rd/renderer_scene_render_rd.cpp
> +			}
This doesn't seem to be working(?)

I'm getting the **exact** same image with both nearest and bilinear when I have SMAA enabled (Mobile, HDR 2D):

SMAA + Bilinear | SMAA + Nearest-neighbour
--|--
<img width="1152" height="1152" alt="Image" src="https://github.com/user-attachments/assets/d48e3de2-5fdd-4d05-ad5a-d3b9e66224a5" />|<img width="1152" height="1152" alt="Image" src="https://github.com/user-attachments/assets/0dec2201-a441-45d8-8b04-1bb4b703e5c0" />

Is there any other way to test if this line is actually working as intended?

If it doesn't work, I'd be fine removing this and just saying that SMAA doesn't work with nearest-neighbour.

2025-11-26 16:45 UTC, allenwp requested changes
I think [this comment](https://github.com/godotengine/godot/pull/79731/files#r2565719927) needs some looking into and a decision before this is merged.

2025-11-26 23:20 UTC, Calinou commented on servers/rendering/renderer_rd/renderer_scene_render_rd.cpp
> +			}
This is likely due to the same cause as this bug:

- https://github.com/godotengine/godot/issues/111650

We could try to skip SMAA (or fallback to FXAA) when using nearest-neighbor scaling as a workaround, but if we fix the above bug, we should make sure to re-enable it.

2025-11-26 23:20 UTC, Kaleb-Reid commented on servers/rendering/renderer_rd/renderer_scene_render_rd.cpp
> +			}
@allenwp I've attempted to fix this with https://github.com/Calinou/godot/pull/16. Not sure if it's correct / which other textures used by SMAA need their filtering modes changed, but it's there if you would like to test it.

2025-11-27 21:25 UTC, allenwp commented on servers/rendering/renderer_rd/renderer_scene_render_rd.cpp
> +			}
I'm not yet sure about these changes (I added a comment about my uncertainty to the PR), but if we're looking to sneak this in before feature freeze we might not have time to fix this. To get it in, it might make sense to just add a documentation note saying that nearest and SMAA can't be used together and leaving it at that...

But I don't know what the best solution is here. Filter modes and 3d scaling on intermediate buffers isn't in my wheel house.

2025-11-28 18:13 UTC, Calinou commented on servers/rendering/renderer_rd/renderer_scene_render_rd.cpp
> +			}
The linked PR is now merged. Thanks @Kaleb-Reid :slightly_smiling_face:

2025-11-28 18:14 UTC, Calinou commented
@BastiaanOlij https://github.com/Calinou/godot/pull/16 has changed some code related to multiview. I incorporated the PR's changes as-is, could you take a look if there's anything that could be an issue?

2025-11-28 19:47 UTC, allenwp requested changes

2025-11-28 19:47 UTC, allenwp commented on servers/rendering/renderer_rd/renderer_scene_render_rd.cpp
> +			RD::get_singleton()->draw_command_begin_label(spatial_upscaler->get_label());
```suggestion
		RD::get_singleton()->draw_command_begin_label(spatial_upscaler->get_label());
```

2025-11-28 20:17 UTC, allenwp commented on servers/rendering/renderer_rd/renderer_scene_render_rd.cpp
I think this comment is still correct? But a lot changed here, so I just want to confirm it's not out-of-date now.

(I'm having a hard time selecting the lines for this comment; I'm talking about line 764 in the new version of this file.)

2025-11-28 22:03 UTC, Kaleb-Reid commented on servers/rendering/renderer_rd/renderer_scene_render_rd.cpp
From my understanding this should still be correct.

2025-11-28 22:14 UTC, Kaleb-Reid commented
After putting more thought into it I made what are hopefully my final adjustments in https://github.com/Calinou/godot/pull/17

2025-12-16 18:25 UTC, bits-by-brandon commented
Tested this PR, Worked great for my project.

2025-12-21 14:50 UTC, allenwp commented
> After putting more thought into it I made what are hopefully my final adjustments in https://github.com/Calinou/godot/pull/17

I see this PR is still open. @Calinou let me know when you're satisfied with any of these sort of changes and I can re-review your PR. (I've been holding off on a re-review until the dust settles with how to handle SMAA, etc.)

2026-01-04 23:46 UTC, Calinou commented
> I see this PR is still open. @Calinou let me know when you're satisfied with any of these sort of changes and I can re-review your PR. (I've been holding off on a re-review until the dust settles with how to handle SMAA, etc.)

All PRs on my fork have been merged, so this is ready for review.

2026-01-07 20:08 UTC, allenwp requested changes
Thanks for the updates. This almost looks good to me.

In addition to my [previous code formatting comment](https://github.com/godotengine/godot/pull/79731/changes#r2565222837), I noticed that the debanding logic has not been updated, so I've added another change request comment with the fix for that (including a comment that describes how this code should work).

I'm a bit curious why `0.1` is the minimum scale... I tried setting it lower, but it still seems to be forced to a minimum of `0.1`. Not a big deal at all, just something I don't understand. My guess is that if you want to have a pixelated screen transition where the nearest neighbour scaling is animated, you might want to go quite a bit lower than 0.1. Do you happen to know why this can't be done with the current PR? Not a blocker, mind you!

2026-01-07 20:08 UTC, allenwp commented on servers/rendering/renderer_rd/renderer_scene_render_rd.cpp
Edit: I have removed my suggestion. None of these lines need to be modified after https://github.com/godotengine/godot/pull/114890 is merged.

2026-01-08 16:04 UTC, allenwp requested changes
If I'm reading this code correctly, an additional pass is always required when using Nearest, which means that it is always slower than Bilinear. Because of this, it should be documented as such.

...But does this really need to be the case?? Is there any way that, when SMAA and spatial upscaler are not used, that Nearest could be implemented without this additional pass?

If so, better to improve this PR so that Nearest is actually as fast as bilinear and ignore these suggested changes to the documentation.

2026-01-08 16:04 UTC, allenwp commented on scene/main/viewport.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::INT, "scaling_3d_mode", PROPERTY_HINT_ENUM, "Nearest (Fastest):5,Bilinear (Fastest):0,FSR 1.0 (Fast):1,FSR 2.2 (Slow):2,MetalFX (Spatial - Fast):3,MetalFX (Tempora
Since an additional pass is needed for nearest, it should probably be the second on the list and labelled as "very fast", not "fastest".

```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::INT, "scaling_3d_mode", PROPERTY_HINT_ENUM, "Bilinear (Fastest):0,Nearest (Very fast):5,FSR 1.0 (Fast):1,FSR 2.2 (Slow):2,MetalFX (Spatial - Fast):3,MetalFX (Temporal - Slow):4"), "set_scaling_3d_mode", "get_scaling_3d_mode");
```

2026-01-08 16:04 UTC, allenwp commented on servers/rendering/storage/render_scene_buffers.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::INT, "scaling_3d_mode", PROPERTY_HINT_ENUM, "Nearest (Fastest):5,Bilinear (Fastest):0,FSR 1.0 (Fast):1,FSR 2.2 (Slow):2,MetalFX (Spatial - Fast):3,MetalFX (Tempora
Since an additional pass is needed for nearest, it should probably be the second on the list and labelled as "very fast", not "fastest".

```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::INT, "scaling_3d_mode", PROPERTY_HINT_ENUM, "Bilinear (Fastest):0,Nearest (Very fast):5,FSR 1.0 (Fast):1,FSR 2.2 (Slow):2,MetalFX (Spatial - Fast):3,MetalFX (Temporal - Slow):4"), "set_scaling_3d_mode", "get_scaling_3d_mode"); // TODO VIEWPORT_SCALING_3D_MODE_OFF is possible here too, but we can't specify an enum string for it.
```

2026-01-08 16:04 UTC, allenwp commented on servers/rendering/rendering_server.cpp
> +			Vector<String> mode_hints_arr = { "Nearest (Fastest):5", "Bilinear (Fastest):0", "FSR 1.0 (Fast):1", "FSR 2.2 (Slow):2" };
Since an additional pass is needed for nearest, it should probably be the second on the list and labelled as "very fast", not "fastest".

```suggestion
			Vector<String> mode_hints_arr = { "Bilinear (Fastest):0", "Nearest (Very fast):5", "FSR 1.0 (Fast):1", "FSR 2.2 (Slow):2" };
```

2026-01-08 18:01 UTC, Calinou commented
> I'm a bit curious why 0.1 is the minimum scale... I tried setting it lower, but it still seems to be forced to a minimum of 0.1. Not a big deal at all, just something I don't understand. My guess is that if you want to have a pixelated screen transition where the nearest neighbour scaling is animated, you might want to go quite a bit lower than 0.1. (Edit: actually, animating this scale is probably a horrible idea because it would be quite slow?) Do you happen to know why this can't be done with the current PR? Not a blocker, mind you!

There is a clamp to `0.1` somewhere in the rendering code (I don't recall where exactly). We have (or had?) some issues that occur in viewports that are internally less than 32x32 in some situations due to mip generation, so very low render scales may not be a good idea anyway.

> (Edit: actually, animating this scale is probably a horrible idea because it would be quite slow?)

Indeed, it's a bad idea as it will constantly recreate buffers on every change (which is a slow operation). See https://github.com/godotengine/godot-proposals/issues/917 for what would be needed to be able to change resolutions without a slow operation on every change.

Regardless, using a shader effect is preferable for a screen transition.

2026-01-08 21:22 UTC, Kaleb-Reid commented
@allenwp Yes it should be possible to disable this copy without side effects if both SMAA and FXAA are disabled. I thought I already did this but I guess not. I will submit a fix to calinou's branch for this.

I made https://github.com/godotengine/godot/pull/113413 to apply this to bilinear scaling to fix scaling + FXAA or SMAA, so in the end they should still be the same speed.

I was also thinking that this extra pass could be removed from this pr and its introduction could be #113413 instead, which would make more sense imo. @Calinou what do you think about this?

2026-01-09 22:55 UTC, Calinou commented
> I was also thinking that this extra pass could be removed from this pr and its introduction could be https://github.com/godotengine/godot/pull/113413 instead, which would make more sense imo. @Calinou what do you think about this?

I agree it makes more sense to move that code to that other PR.

2026-01-10 00:30 UTC, Kaleb-Reid commented
I created https://github.com/Calinou/godot/pull/18 which reverts the behaviour so that there is no framebuffer copy and FXAA / SMAA are broken when using nearest. It is good to note that screen-space AA methods are already broken when scaling with bilinear filtering, which https://github.com/godotengine/godot/pull/113413 will aim to fix. Whichever pr doesn't get merged first can be adapted so that both nearest and bilinear scaling work properly with screen-space AA.

2026-01-15 22:34 UTC, Calinou commented
> I created [Calinou#18](https://github.com/Calinou/godot/pull/18) which reverts the behaviour so that there is no framebuffer copy and FXAA / SMAA are broken when using nearest. It is good to note that screen-space AA methods are already broken when scaling with bilinear filtering, which #113413 will aim to fix. Whichever pr doesn't get merged first can be adapted so that both nearest and bilinear scaling work properly with screen-space AA.

Merged, squashed and tested again, thanks :slightly_smiling_face:

2026-01-22 11:54 UTC, danbolt commented on scene/main/viewport.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::INT, "scaling_3d_mode", PROPERTY_HINT_ENUM, "Nearest (Fastest):5,Bilinear (Fastest):0,FSR 1.0 (Fast):1,FSR 2.2 (Slow):2,MetalFX (Spatial - Fast):3,MetalFX (Tempora
This suggestion, as well as the other suggestions below, might no longer be necessary now that the SMAA fix has been pulled out into https://github.com/godotengine/godot/pull/113413.

2026-01-22 22:35 UTC, Calinou commented on servers/rendering/storage/render_scene_buffers.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::INT, "scaling_3d_mode", PROPERTY_HINT_ENUM, "Nearest (Fastest):5,Bilinear (Fastest):0,FSR 1.0 (Fast):1,FSR 2.2 (Slow):2,MetalFX (Spatial - Fast):3,MetalFX (Tempora
See https://github.com/godotengine/godot/pull/79731#discussion_r2716591874.

2026-01-22 22:35 UTC, Calinou commented on servers/rendering/rendering_server.cpp
> +			Vector<String> mode_hints_arr = { "Nearest (Fastest):5", "Bilinear (Fastest):0", "FSR 1.0 (Fast):1", "FSR 2.2 (Slow):2" };
See https://github.com/godotengine/godot/pull/79731#discussion_r2716591874.

2026-02-20 05:55 UTC, danbolt commented
Just tested this change on 4.7.dev with HEAD at 230e6bfc3. 

Forward+, Mobile, and Compatibility all working as expected on Linux. :+1: 
<img width="1746" height="1209" alt="A screenshot showing a Godot rendering scene at a low, pixelated, resolution, with corresponding GDScript visible." src="https://github.com/user-attachments/assets/6ec6b9ab-d85a-499a-9341-ec7172b5a1af" />

2026-03-20 15:10 UTC, allenwp requested changes
Now that so many of the underlying bugs have been fixed, the code of this PR looks really clean and simple. Looking great!

I've added a couple of comments for things that need to be addressed. In the spirit of moving quickly, I'm posting the comments now and will continue to test after posting this message to see if I find any issues.

2026-03-20 15:10 UTC, allenwp commented on servers/rendering/renderer_viewport.cpp
>  			}
Based on the documentation, comments, and warnings: I expect nearest-neighbour scaling to act as bilinear when 3d scale is `>= 1.0`.

But this code logic appears to act as nearest-neighbour scaling in this case.

Edit: I've verified visually that this is the case and indeed, it's probably desirable to fix this code to correctly force bilinear when scale > 1.0.

2026-03-20 15:10 UTC, allenwp commented on servers/rendering/renderer_rd/effects/tone_mapper.cpp
Is there a reason the subpass doesn't also use this new filter like `tonemapper` and `tonemapper_mobile`? I suspect this might just be the result of an incomplete rebase, since these functions were introduced fairly recently.

2026-03-24 20:12 UTC, Kaleb-Reid commented on servers/rendering/renderer_rd/effects/tone_mapper.cpp
@allenwp This is intentional, there used to be modifications here with the intention of "disabling" bilinear filtering during subpass post processing but I removed it at some point because it completely broke rendering when using subpass post processing since this is an input attachment and not a sampler. Also, subpass post processing is disabled if any scaling is used: https://github.com/godotengine/godot/blob/64596092ae60e8fc10da7b61ac024d099a80a3b7/servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp#L955-L957 If scaling is enabled (including nearest neighbour), `tonemapper_subpass` will never be called.

2026-03-24 20:55 UTC, Kaleb-Reid commented on servers/rendering/renderer_viewport.cpp
>  			}
@allenwp I made https://github.com/Calinou/godot/pull/19 to fix this

2026-03-25 14:36 UTC, allenwp commented on servers/rendering/renderer_rd/effects/tone_mapper.cpp
Yes, thank you for the explanation! This makes perfect sense and matches the behaviour I see when debugging :)

2026-03-25 14:37 UTC, allenwp approved these changes
All of the issues that I've been able to find with behaviour and code have been addressed. This looks clean, simple, and bug-free -- Ready to merge!

2026-03-26 15:10 UTC, allenwp commented
It would be best to have this PR merged before #113413 so that Kaleb-Reid can update the bugfix PR to address both bilinear and nearest neighbour.

2026-04-01 09:20 UTC, blueskythlikesclouds approved these changes
Looks and works great!

2026-04-02 17:33 UTC, merged

2026-04-02 17:34 UTC, Repiteo commented
Thanks!

2026-04-10 12:39 UTC, EzraT commented
Thanks a lot!