resolved #79509
godotengine/godot pull request #79795
Opened 2023-07-22 18:31 UTC by anuragdaksh7

2023-07-22 19:58 UTC, AThousandShips commented
Please provide a more descriptive name for this PR and for the commit message

2023-07-22 19:59 UTC, AThousandShips commented on servers/rendering/renderer_rd/environment/sky.cpp
> +		// Save our screen size, our buffers will already have been cleared
```suggestion
		// Save our screen size, our buffers will already have been cleared.
```
Code style requires that comments begin with a capital and end with a period, same for other comments here

2023-07-22 20:00 UTC, AThousandShips commented on servers/rendering/renderer_rd/environment/sky.cpp
> +
Remove these two empty lines

2023-07-23 03:00 UTC, anuragdaksh7 commented on servers/rendering/renderer_rd/environment/sky.cpp
> +
ok

2023-07-23 07:53 UTC, AThousandShips commented on servers/rendering/renderer_rd/environment/sky.cpp
> +	if (sky ||render_fog){
```suggestion
	if (sky || render_fog) {
```

2023-07-23 07:54 UTC, AThousandShips commented on servers/rendering/renderer_rd/environment/sky.cpp
> +		// Trigger updating radiance buffers
```suggestion
		// Trigger updating radiance buffers.
```

2023-07-23 08:19 UTC, AThousandShips commented
Once you've added all the changes please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

2023-07-23 09:06 UTC, AThousandShips requested changes
This unfortunately won't work, it moves the initialisation of `shader_data` after it is used

2023-07-23 10:59 UTC, closed without merging