Fix ix an error message that floods the editor logs:
godotengine/godot pull request #79853
Opened 2023-07-24 13:14 UTC by xsellier

Fix ix an error message that floods the editor logs:
ERROR: Index p_gutter = -1 is out of bounds (gutters.size() = 4).
   at: set_line_gutter_item_color (scene/gui/text_edit.cpp:5900)

![image](https://github.com/godotengine/godot/assets/6616005/c5782682-1cf9-41e3-9ca3-50a81baa4f21)

2023-07-31 17:31 UTC, Paulb23 requested changes
This doesn't look like the correct fix to me, `_update_gutter_indexes` should be called when the editor is activated, and only at that point should the themes / validation start being ran.

2023-08-01 10:18 UTC, xsellier commented
> This doesn't look like the correct fix to me, `_update_gutter_indexes` should be called when the editor is activated, and only at that point should the themes / validation start being ran.

If you got a better fix, I won't be mad if you want to close this PR, and fix it by yourself.
Cheers

2023-08-01 10:37 UTC, AThousandShips commented
I'd suggest you take the feedback to heart and try it out, that's core to contributing, flexibility and being able to incorporate feedback

2023-08-01 10:45 UTC, xsellier commented
> I'd suggest you take the feedback to heart and try it out, that's core to contributing, flexibility and being able to incorporate feedback
I'm glad to have received feedback on the fix I proposed. However, I don't have time to delve further into the code.

I'm using this fix locally, it works, and I don't need to look any further. Nevertheless, I understand that Godot needs a better fix than the one I proposed.

So, from my side, I have a commit that changes 2 integers from -1 to 0, with no side effects, where I don't want to start modifying conditions for the editor theme updates, taking the risk of breaking more things than I understand.

If you feel like it, @AThousandShips, you can also make the fix, as you mentioned, it's an open-source software, and it doesn't have to come from me. And as I believe, my fix works well enough given the time invested.

2023-08-01 10:59 UTC, AThousandShips commented
How do you know that it doesn't have side effects? I don't think they were manually set to -1 on construction previously just for no reason, but to indicate the invalid start state, and that there's missing handling elsewhere, as pointed out

I haven't mentioned anything about this being open-source, and it working well enough compared to the time invested isn't a metric for how appropriate a fix is

I just find this attitude of "if you have a better fix you can do it yourself, I won't change anything" unhelpful and not appropriate for a community driven project, especially when getting feedback from a team member who has this area

2023-08-01 11:08 UTC, xsellier commented
Honestly, I thought that @Paulb23 had looked at the code to find a fix but didn't want to take credit for it. That's why I responded by saying that he was free to make a higher-quality fix if he wanted to.

2023-08-01 11:10 UTC, closed without merging

2023-08-01 11:17 UTC, AThousandShips commented
I understand but that was not communicated in your messages, I'm sorry that I didn't pick up on that implied message of yours

2023-08-01 11:35 UTC, xsellier commented
> I understand but that was not communicated in your messages, I'm sorry that I didn't pick up on that implied message of yours
> 
> Have a nice day
I'm relieved; I really thought you were lecturing me with full knowledge of the situation. Anyway, I don't have time to deal with this, and since this fix doesn't suit you, it's best to leave it closed. Have a good day to you too.