Softbody3d documentation update
godotengine/godot pull request #79933
Opened 2023-07-26 17:35 UTC by SamDevelopsCode

2023-07-26 17:41 UTC, AThousandShips requested changes
Formatting needs fixing

2023-07-26 17:41 UTC, AThousandShips commented on doc/classes/SoftBody3D.xml
> +		<member name="drag_coefficient" type="float" setter="set_drag_coefficient" getter="get_drag_coefficient" default="0.0">
```suggestion
		<member name="drag_coefficient" type="float" setter="set_drag_coefficient" getter="get_drag_coefficient" default="0.0">
```

2023-07-26 17:41 UTC, AThousandShips commented on doc/classes/SoftBody3D.xml
> +            Lower values will increase the SoftBody's ability to bend while higher values will make the Softbody more rigid.
```suggestion
			Lower values will increase the SoftBody's ability to bend while higher values will make the Softbody more rigid.
```

2023-07-26 18:19 UTC, AThousandShips approved these changes

2023-07-26 18:21 UTC, aaronfranke approved these changes

2023-08-07 06:01 UTC, aaronfranke commented on doc/classes/SoftBody3D.xml
> +			Higher values will result in a more rigid SoftBody, while lower values will increase the SoftBody's ability to bend. On a range of 0 to 1.
"a more rigid body" might be confusing to read considering there is RigidBody, perhaps it should say "a more rigid soft body"?

2023-08-07 10:18 UTC, akien-mga commented on doc/classes/SoftBody3D.xml
> +			Higher values will result in a more rigid SoftBody, while lower values will increase the SoftBody's ability to bend. On a range of 0 to 1.
"will increase the rigidity of the body"?

2023-08-07 10:18 UTC, akien-mga approved these changes

2023-08-07 13:02 UTC, merged

2023-08-07 13:04 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2023-08-07 21:42 UTC, SamDevelopsCode commented
Thanks everyone for helping me with the issues and to grow as a developer. Love Godot!

2023-10-19 19:56 UTC, YuriSizov commented
Cherry-picked for 4.1.3.