fixed ClassDB inconsistencies
godotengine/godot pull request #8020
Opened 2017-03-13 15:58 UTC by karroffel

partially fixes #7960 (The property problem isn't solved)

2017-03-13 19:47 UTC, bojidar-bg requested changes

2017-03-13 19:47 UTC, bojidar-bg commented on scene/gui/control.cpp
> +	BIND_VMETHOD(MethodInfo(Variant::VECTOR2, "_get_minimum_size"));
That's incorrect, you forgot to call the new method..... (you should probably edit SceneStringNames too, IDK)

2017-03-13 19:53 UTC, karroffel commented on scene/gui/control.cpp
> +	BIND_VMETHOD(MethodInfo(Variant::VECTOR2, "_get_minimum_size"));
Call the new method, what do you mean? And why? All other virtual methods don't use SceneStringName as well

2017-03-13 19:54 UTC, karroffel commented on scene/gui/control.cpp
> +	BIND_VMETHOD(MethodInfo(Variant::VECTOR2, "_get_minimum_size"));
Ohhhh I see what you mean. Yeah, will do.

2017-03-13 20:18 UTC, karroffel commented on scene/gui/control.cpp
> +	BIND_VMETHOD(MethodInfo(Variant::VECTOR2, "_get_minimum_size"));
@bojidar-bg updated

2017-03-14 08:53 UTC, bojidar-bg approved these changes
Ok, no more comments from my side, but some other reviewer might want to have a look at it :smiley:

2017-03-15 18:09 UTC, merged