Expose PlaceHolderScriptInstance to GDExtension
godotengine/godot pull request #80394
Opened 2023-08-08 01:40 UTC by maiself

Exposes `PlaceHolderScriptInstance` used by the `gdscript` and `csharp_script` modules in Godot to GDExtension. 

While use of this class is technically optional as placeholder implementation can be done with the existing interface, exposing it allows extensions to avoid reimplementing the entire behavior.

This would likely be useful for existing language bindings:
- [godot_dart](https://github.com/fuzzybinary/godot_dart) has used their normal `ScriptInstance` implementation and disabled `call` when used as a placeholder.
- [godot-luau-script](https://github.com/Fumohouse/godot-luau-script) has completely reimplemented `PlaceHolderScriptInstance`

I've started using this in my Python bindings and it seems to work quite well. Without this I would be doing what has been done for the luau bindings.

2023-08-08 13:24 UTC, dsnopek reviewed
Thanks!

I haven't had a chance to test this yet, which I'd really like to do, but at a high-level, this looks great :-)

2023-08-08 13:24 UTC, dsnopek commented on core/extension/gdextension_interface.cpp
> +	}
```suggestion
	ERR_FAIL_COND_MSG(!placeholder, "Unable to update placeholder, expected a PlaceHolderScriptInstance but received an invalid type.");
```

2023-08-08 21:28 UTC, maiself commented on core/extension/gdextension_interface.h
> +typedef GDExtensionScriptInstancePtr (*GDExtensionPlaceHolderScriptInstanceCreate)(GDExtensionConstObjectPtr p_language, GDExtensionConstObjectPtr p_script, GDExtensionConstObjectPtr p_owner);
Yes, good catch!

2023-08-28 21:15 UTC, dsnopek requested changes
I've started messing around with this with godot-cpp, and I think it'd be sufficient for my cppscript experiment.

I also spent some time reading through the Luau binding's code, and I think this would be sufficient for its purposes as well.

However, I noticed a small naming issue which is pointed out in the code comments. But after that is fixed, I think I'm personally happy with this PR!

2023-08-28 21:15 UTC, dsnopek commented on core/extension/gdextension_interface.h
> +typedef GDExtensionScriptInstancePtr (*GDExtensionPlaceHolderScriptInstanceCreate)(GDExtensionObjectPtr p_language, GDExtensionObjectPtr p_script, GDExtensionObjectPtr p_owner);
All the other interface function pointers (ie the ones that you request via `get_proc_address()`) start with `GDExtensionInterface` - this should be updated to match:
```suggestion
typedef GDExtensionScriptInstancePtr (*GDExtensionInterfacePlaceHolderScriptInstanceCreate)(GDExtensionObjectPtr p_language, GDExtensionObjectPtr p_script, GDExtensionObjectPtr p_owner);
```

2023-08-28 21:15 UTC, dsnopek commented on core/extension/gdextension_interface.h
> +typedef void (*GDExtensionPlaceHolderScriptInstanceUpdate)(GDExtensionScriptInstancePtr p_placeholder, GDExtensionConstTypePtr p_properties, GDExtensionConstTypePtr p_values);
Same here:
```suggestion
typedef void (*GDExtensionInterfacePlaceHolderScriptInstanceUpdate)(GDExtensionScriptInstancePtr p_placeholder, GDExtensionConstTypePtr p_properties, GDExtensionConstTypePtr p_values);
```

2023-08-28 21:46 UTC, maiself commented
Fixed the naming issue and rebased on `master`.

2023-08-28 22:03 UTC, dsnopek approved these changes
Thanks! This looks great to me :-)

2023-08-29 10:54 UTC, merged

2023-08-29 10:59 UTC, akien-mga commented
Thanks!