[4.0] Fix tween_cheatsheet 404 in Tween.xml
godotengine/godot pull request #80496
Opened 2023-08-10 20:36 UTC by sk757a

2023-08-10 20:52 UTC, aaronfranke commented
Instead of having this PR, we could cherry-pick the original PR: https://github.com/godotengine/godot/pull/77941

2023-08-10 21:09 UTC, AThousandShips commented
This isn't right, the link should be to the PNG in the 4.0 version, the 4.1 version isn't applicable, as the transition types aren't available in 4.0

2023-08-10 21:13 UTC, AThousandShips requested changes
As per above comment

2023-08-10 21:13 UTC, AThousandShips commented on doc/classes/Tween.xml
> +		[url=https://raw.githubusercontent.com/godotengine/godot-docs/master/img/tween_cheatsheet.webp]Tween easing and transition types cheatsheet[/url]
```suggestion
		[url=https://raw.githubusercontent.com/godotengine/godot-docs/4.0/img/tween_cheatsheet.png]Tween easing and transition types cheatsheet[/url]
```

2023-08-11 07:55 UTC, AThousandShips approved these changes

2023-08-11 07:56 UTC, AThousandShips commented
Please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

2023-08-18 07:27 UTC, merged

2023-08-18 07:27 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: