Check if any global script class is shadowed by a variable
godotengine/godot pull request #80587
Opened 2023-08-13 09:38 UTC by garychia

Related to #80003

2023-09-19 14:20 UTC, anvilfolk approved these changes
Looks great to me! Make sure to use keywords that github understands, like directly say `Fixes #<pr-number>`, which will autolink it :)

2023-09-19 14:43 UTC, dalexeev commented
I haven't tested, just guessing. Can you get a false positive warning when reloading the script in the editor if the class name is already in the global script cache?

2023-09-19 14:45 UTC, anvilfolk commented
Oh, good point. Let me try.

2023-09-19 14:57 UTC, anvilfolk requested changes
I couldn't get the warning to fire when it shouldn't. This is an easy one to revert should problems crop up, so I'd say I still want to merge!

However, I'd actually like to see improved error handling, like so:
1) The current warning should explicitly say it's a `native` class, because I think what `ClassDB` contains?
2) We should add another case for the GDScript/scriptserver warning, which should also actually expose what file the class is defined in using `ScriptServer::get_global_class_path(class_name)`. That way we easily know where the conflict is coming from!

2023-09-20 10:41 UTC, anvilfolk commented
Also, I notice you have quite a few PRs but often say related to instead of fixes/closes in them - feel free to edit those so that GH actually links the issues!

And you'd be very welcome in the [Godot contributors chat](https://chat.godotengine.org/) if you wanted to discuss stuff with other godot devs!

2023-09-21 12:44 UTC, anvilfolk requested changes
Just a small change more so the code is consistent, then I think it's good to merge :)

2023-09-21 14:55 UTC, anvilfolk approved these changes
Looks great!!! :)

2023-09-26 06:25 UTC, dalexeev approved these changes

2023-09-26 06:25 UTC, dalexeev commented on modules/gdscript/gdscript_analyzer.cpp
> +			class_path = class_path.substr(class_path.rfind("/") + 1);
```suggestion
			String class_path = ScriptServer::get_global_class_path(name).get_file();
```

There is [`get_file()`](https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-get-file) method. I'm not sure if it's worth truncating the path, but unfortunately the tests now use absolute paths, so the choice is between the file name and not using the path at all.

2023-09-26 11:49 UTC, merged

2023-09-26 11:50 UTC, akien-mga commented
Thanks!