GLTF: Add a comment for skinned mesh tree placement and cleanup code
godotengine/godot pull request #80807
Opened 2023-08-20 07:13 UTC by aaronfranke

This PR does these things:

* Add a comment explaining why we generate an empty node here. The reason is not obvious from just reading the code, so we need to have a comment explaining why we do this.
* Clean up the code so that all the mesh generation code is inside one `if (gltf_node->mesh >= 0) {` check.
* Clean up the code so that `_generate_mesh_instance(p_state, p_node_index)` is not duplicated. This makes it clear that the only difference in the skinned mesh check is the placement of the node, not how it's generated.

I tested this PR on a GLTF file with a skinned mesh, both with and without children, and confirmed that the behavior is correct and the same as before.

2023-08-20 07:20 UTC, fire commented
Since this is sensitive code, I think adding the comment is enough.

I am not sure the code compression is worth it.

2023-08-20 15:14 UTC, fire commented
We discussed there's a tradeoff between small bug fixes and large overhauls. Since this code is load bearing, smaller changes aren't worth doing the validating for correctness.

@aaronfranke wanted to make a new proposal.

> The current discussion is about enhancing the Godot game engine's handling of GLTF nodes. Presently, Godot can only generate one node from a single GLTF node JSON, which limits the creation of complex structures without code duplication.
>
> The proposed solution is to modify the code to allow multiple Godot nodes from a single GLTF node JSON. This would enable creating intricate structures like a physics body with various components without repeating code.
> 
> However, there are debates on the implementation. One idea is to run all extensions first, and the first extension that provides a node directly maps to the GLTF node. The rest become children. If no extension provides a node, another element (camera, light, etc.) may be generated. A mesh is created last as it might want to be a leaf (like with skinned meshes).
> 
> There's also concern about backward compatibility. Some believe the old method should not be preserved, while others suggest an import option for backward compatibility. The consensus is to treat this as a significant version change that upgrades with a checkbox. While the need for change is agreed upon, the specifics are still under discussion.
> 
> **Summarized by ai**

2023-09-04 10:40 UTC, RevoluPowered approved these changes

2023-09-04 10:42 UTC, AThousandShips commented on modules/gltf/gltf_document.cpp
> +			// not be the base node, so generate an empty spatial base.
```suggestion
			// GLTF specifies that skinned meshes should ignore their node
			// transforms, only being controlled by the skeleton, so Godot
			// will reparent a skinned mesh to its skeleton. However, we
			// still need to ensure any child nodes keep their place in the
			// tree, so if there are any child nodes, the skinned mesh must
			// not be the base node, so generate an empty spatial base.
```
This should be regrouped IMO, it's very hard to read when each sentence is broken up between lines, especially as the condition above is wider so the width isn't really significant

2023-09-04 16:54 UTC, fire requested changes
We discussed there's a tradeoff between small bug fixes and large overhauls. Since this code is load bearing, smaller changes aren't worth doing the validating for correctness.

@aaronfranke has a proposal for a change to modify the code to allow multiple Godot nodes from a single GLTF node JSON.

2023-09-04 19:08 UTC, fire approved these changes
@lyuma I think this is good now. Can you check?

2023-09-05 14:29 UTC, AThousandShips commented on modules/gltf/gltf_document.cpp
> +			// not be the base node, so generate an empty spatial base.
```suggestion
			// GLTF specifies that skinned meshes should ignore their node transforms,
			// only being controlled by the skeleton, so Godot will reparent a skinned mesh to its skeleton.
			// However, we still need to ensure any child nodes keep their place in the tree,
			// so if there are any child nodes, the skinned mesh must not be the base node,
			// so generate an empty spatial base.
```
Or similar, the current layout is very hard to read

2023-09-05 17:20 UTC, AThousandShips approved these changes

2023-09-06 06:35 UTC, lyuma approved these changes
Looks great. This was indeed one of the trickier edge cases and you'd otherwise have to git blame to find the PR and the linked issue with the particular testcase that led this to be added.

2023-09-06 13:10 UTC, merged

2023-09-06 13:12 UTC, YuriSizov commented
Thanks!