[Client side decorations] Implement window drag handles.
godotengine/godot pull request #80891
Opened 2023-08-22 13:02 UTC by bruvzg

Based on https://github.com/godotengine/godot/pull/16512

Implements more features for https://github.com/godotengine/godot-proposals/issues/4846

Adds support for adding custom native window move / resize handles.
- [x] X11
- [x] Windows
- [x] macOS

https://github.com/godotengine/godot/assets/7645683/4b8ecdba-0102-48fb-b959-a9d24f7aea59

2023-08-22 19:57 UTC, ryanabx commented
Interesting! As this is marked as a draft, what is still left to work on?

2023-08-22 21:11 UTC, Calinou commented
@bruvzg Can you upload the project you used for testing somewhere? Thanks in advance 🙂

2023-08-23 07:16 UTC, bruvzg commented on scene/gui/window_decoration.cpp
> +	ClassDB::bind_method(D_METHOD("set_decoation_type", "pressed"), &WindowDecoration::set_decoation_type);
Fixed.

2023-08-23 07:21 UTC, bruvzg commented
> Can you upload the project you used for testing?

Added test project to the first post.

> I know that this is WIP, but I notice that you're including a WindowDecoration class and an associated editor plugin. Does this imply that you're actually finalizing CSDs or is this just an iterative step towards them?

For now, it's just a mover / resizer. I'm not sure if there is anything else necessary for the CSDs. I guess window min/max/close buttons, but the only platform specific about them is snap/display switch popup menu for the maximize button on macOS/Windows, and checking if how minimized/minimized states works with the borderless window.

2023-08-24 17:13 UTC, ryanabx commented
> The only thing I'm not really sure about is how you plan to actually frame some pretty decoration. Will the decoration object be a parent of `Window`?

Is the framing of the decorations necessary for this PR? Or could it be a separate PR

2023-08-24 17:31 UTC, bruvzg commented
>The only thing I'm not really sure about is how you plan to actually frame some pretty decoration. Will the decoration object be a parent of Window?

Currently, it's children of the Window. `WindowDecoration` is a normal `Control` node, can be placed anywhere (and optionally hold a polygonal region for more customization), so any drawing methods can be used. I do not see any reason to restrict it to the actual frame around the window. But I guess something similar to GTK `HeaderBar` control might be useful as well.

2024-08-13 02:45 UTC, Mervius commented
So I tested this and that project a bit and there seems to be an issue with the resize bottom handles where they either stop working completely or stop working until you resize using a different handle.

2024-11-28 14:55 UTC, Calinou requested changes
Tested locally on Windows 11 23H2 (rebased on top of `master` https://github.com/godotengine/godot/commit/0eadbdb5d0709e4e557e52377fa075d3e2f0ad1f), there's an issue:

I can see the mouse cursor changing when hovering one of the corners (the area outside the red triangle here):

![image](https://github.com/user-attachments/assets/2acc6857-5714-4ba5-9936-11ae9d66d062)

However, left-clicking and dragging does nothing.

I also don't see a horizontal/vertical resize cursor appearing when hovering the window edges, only the diagonal resize cursors at the corners.

PS: The resize cursors appear even if **Resizable** is disabled in the Project Settings, which is strange.

2024-11-28 14:58 UTC, bruvzg commented
> However, left-clicking and dragging does nothing.

Yes, I have noticed that after last rebase, something seems to change and resize handles only work if window have `think` border enabled (not sure if it's Windows change or something with our window style flags).

2024-12-17 22:06 UTC, bruvzg commented
Superseded https://github.com/godotengine/godot/pull/100464 and https://github.com/godotengine/godot/pull/100532 (works on all platforms and allow implementing custom decorations in more Wayland friendly way).

2024-12-17 22:06 UTC, closed without merging