Deselect multi caret when alt clicking on it
godotengine/godot pull request #80956
Opened 2023-08-24 09:19 UTC by MarcusElg

Fixes #80895

If a caret can't be added it checks if it already exists and then removes it. So now it works similarly to vscode when alt clicking once adds a caret, and alt clicking again removes it.

It does loop through the carets twice but preventing that would require changing the return value of add_caret and therefore break compatibility. The amount of carets are always quite low so the performance impact should be neglectable.

2023-08-24 10:10 UTC, MewPurPur approved these changes
I like this implementation, in all honesty I wonder why this wasn't part of the initial implementation.

2023-08-24 10:10 UTC, MewPurPur commented on scene/gui/text_edit.cpp
> +							// Remove caret at clicked location
Add punctuation here.

2023-08-24 13:15 UTC, KoBeWi approved these changes

2023-08-24 16:56 UTC, AThousandShips approved these changes
LGTM, the comment punctuation needs to be fixed though

2023-08-24 22:10 UTC, Calinou reviewed
Tested locally, it mostly works as expected.

However, with this PR, unlike in VS Code, it's not possible to deselect a character/word selection by holding Alt and clicking the selection or the caret:


https://github.com/godotengine/godot/assets/180032/678b8c06-2a9a-467e-8706-ab75ea20b256

2023-08-25 07:25 UTC, MarcusElg commented on scene/gui/text_edit.cpp
> +							// Remove caret at clicked location
Fixed

2023-08-28 14:10 UTC, Paulb23 reviewed
LGTM, would be nice to add a unit test :)

2023-09-02 16:56 UTC, MarcusElg commented
@Calinou fixed, you can now deselect by clicking its selection

2023-09-03 12:10 UTC, Paulb23 requested changes

2023-09-03 17:21 UTC, AThousandShips commented on scene/gui/text_edit.cpp
> +								// Deselect if clicked on caret or its selection.
```suggestion
								// Deselect if clicked on caret or its selection.
```

2023-09-10 17:38 UTC, Paulb23 approved these changes

2023-09-11 14:02 UTC, merged

2023-09-11 14:03 UTC, akien-mga commented
Thanks!