Add shorthand for using singleton string names
godotengine/godot pull request #81303
Opened 2023-09-04 15:10 UTC by KoBeWi

Follow-up to #80573

This PR adds `CoreStringName()` and `SceneStringName()` macros as a shorthand for `CoreStringNames::get_singleton()->` and `SceneStringNames::get_singleton()->`. It makes the singleton string names easier to use and code is cleaner.

I also applied some minor cleanup:
- removed some stringname singleton includes from header files
- removed unused stringnames: `___pdcdata`, `__getvar`
- renamed some stringnames to be less confusing (they used underscore for member, but not for string, e.g. `_script` for `"script"`

For the last point I had to make some exceptions, because the actual name conflicted with a C++ keyword. I changed the name from `_name` to `sn_name` (up to discussion), to make it more clear that underscore is not part of the name.

My plan after that is to replace all usage of "strings" and SNAME("strings") with their singleton equivalent *if it exists already*. Right now they are used inconsistently.

Another thing is that some names are used only once. I think they can be replaced with `SNAME()`; it didn't exist when they were created.

2024-02-14 22:36 UTC, Calinou requested changes
Tested locally, it mostly works as expected.

This reduces binary size by about 8 KB too (optimized Linux x86_64 editor).

```
106,980,384  godot.linuxbsd.editor.x86_64  <-- This PR
106,988,576  godot.linuxbsd.editor.x86_64.master
```

However, I get a series of errors when exiting the editor. This occurs on any project, even an empty project:

```
ERROR: Attempt to disconnect a nonexistent connection from '@CreateDialog@5292:<CreateDialog#505883418985>'. Signal: 'confirmed', callable: 'CreateDialog::_confirmed'.
   at: _disconnect (./core/object/object.cpp:1416)
ERROR: Attempt to disconnect a nonexistent connection from '@CreateDialog@10229:<CreateDialog#775476516600>'. Signal: 'confirmed', callable: 'CreateDialog::_confirmed'.
   at: _disconnect (./core/object/object.cpp:1416)
ERROR: Attempt to disconnect a nonexistent connection from '@CreateDialog@6763:<CreateDialog#575894745070>'. Signal: 'confirmed', callable: 'CreateDialog::_confirmed'.
   at: _disconnect (./core/object/object.cpp:1416)
ERROR: Attempt to disconnect a nonexistent connection from '@CreateDialog@6344:<CreateDialog#556684831719>'. Signal: 'confirmed', callable: 'CreateDialog::_confirmed'.
   at: _disconnect (./core/object/object.cpp:1416)
ERROR: Attempt to disconnect a nonexistent connection from '@CreateDialog@6197:<CreateDialog#550175271553>'. Signal: 'confirmed', callable: 'CreateDialog::_confirmed'.
   at: _disconnect (./core/object/object.cpp:1416)
ERROR: Attempt to disconnect a nonexistent connection from '@EditorFileSystem@3:<EditorFileSystem#28269610226>'. Signal: 'filesystem_changed', callable: 'EditorDirDialog::reload'.
   at: _disconnect (./core/object/object.cpp:1416)
ERROR: Attempt to disconnect a nonexistent connection from '@CreateDialog@4543:<CreateDialog#471121025568>'. Signal: 'confirmed', callable: 'CreateDialog::_confirmed'.
   at: _disconnect (./core/object/object.cpp:1416)
ERROR: Attempt to disconnect a nonexistent connection from '@CreateDialog@4361:<CreateDialog#462698862674>'. Signal: 'confirmed', callable: 'CreateDialog::_confirmed'.
   at: _disconnect (./core/object/object.cpp:1416)
```

2024-02-14 22:46 UTC, KoBeWi commented
I can't reproduce the errors. Are you sure they are caused by this PR? Any chance for their stack trace?

2024-05-11 19:43 UTC, akien-mga approved these changes
I like the change, and it seems to work fine on my end from a quick test.

Would be good if @Calinou could test again and see if he reproduces the error about missing signal connections.

2024-05-12 21:49 UTC, Calinou approved these changes
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/bdc0316217940a8ccc80ce536547d42e6477adf4), it works as expected now. I can't reproduce the errors on exit anymore.

2024-05-13 10:08 UTC, merged

2024-05-13 10:08 UTC, akien-mga commented
Thanks!

2024-05-13 10:20 UTC, AThousandShips commented on core/core_string_names.h
> +	StringName script;
Introduced a conflict with:
* https://github.com/godotengine/godot/pull/91329