Add a bus_renamed AudioServer signal
godotengine/godot pull request #81641
Opened 2023-09-14 10:42 UTC by MewPurPur

A more powerful, slightly compat-breaking alternative to #81611. See the first few comments.

2023-09-14 11:07 UTC, MJacred requested changes
: )

2023-09-14 11:07 UTC, MJacred commented on editor/editor_audio_buses.cpp
> +	print_line("test");
```suggestion
```

2023-09-14 11:08 UTC, MewPurPur commented
Funnily, the old docs description is even more overbearing, it suggests any change in the AudioBusLayout is supposed to signal. Including... things like muting, bypassing, solo, volume changes, maybe even effects! I don't know what the signal is truly intended for at this point, so might as well invent a proper meaning now?

2023-09-14 15:31 UTC, YuriSizov approved these changes
This change makes more sense to me than the alternative (basically because I wrote the original comment in the modified code :P)

PS. We can preserve compatibility by adding another signal (or signals) that would be emitted for all the other activities. So we would avoid using `bus_layout_changed` entirely.

2023-09-14 16:10 UTC, MewPurPur commented
Yup I saw in the blame. Since the signal never did what the documentation describes anyway, I think we can break compatibility here.

Unfortunately, I think that the initial idea was that the "bus layout changed" signal was meant to be for when the active AudioBusLayout changed - but the idea was forgotten over the eons as people interpreted "layout" as its standard meaning - the positioning of things.

I thought the intention of the signal was to alert things that the user-facing part of AudioBusLayout has changed, which does include renaming since buses can be accessed via their names.

So, idk what to do with this, man. I hope I provided the facts and the different possible perspectives here.

2023-09-15 09:53 UTC, reduz approved these changes
looks good

2023-09-15 10:48 UTC, YuriSizov commented
Note on merging: This is one of two alternatives to address the problem, https://github.com/godotengine/godot/pull/81611 is the other one. We likely need to pick just one, because they don't really make sense together.

2023-09-15 11:49 UTC, MJacred commented
This one could be merged into master for 4.2 and the other one into 4.0 and 4.1, no?

2023-09-15 11:52 UTC, YuriSizov commented
@MJacred This is not how we maintain Godot's codebase. Discrepancies like that makes it harder to support several branches at the same time, so the solution must come through all branches, or not come through at all. Unless it's something really really critical, but in this case it's just some lag.

If we want to preserve the compatibility and cherry-pick this fix, there are other options, as I've mentioned.

2023-09-17 12:48 UTC, merged