Improve VisibleOnScreen classes' docs
godotengine/godot pull request #81774
Opened 2023-09-16 22:29 UTC by MewPurPur

These docs were super old and had some misleading information, unless I've misunderstood something. Some bad English too. And a few descriptions were missing.

I tested to reaffirm that I'm not getting things wrong, but I'm not a big user of these classes so I might have missed some peculiarity or something.

2023-09-16 22:42 UTC, Calinou commented
cc @mrjustaguy, as they worked with this class previously.

2023-09-17 09:04 UTC, mrjustaguy requested changes

2023-09-17 09:04 UTC, mrjustaguy commented on doc/classes/VisibleOnScreenEnabler2D.xml
> +			The path to the target node, relative to the [VisibleOnScreenEnabler2D]. The target node is cached; it's only assigned when setting this property (if the [VisibleOnScreenEnabler2D] is inside the s
It'll Print an error in the editor, but in game it won't do anything.

2023-09-17 09:04 UTC, mrjustaguy commented on doc/classes/VisibleOnScreenEnabler3D.xml
> +		[b]Note:[/b] [VisibleOnScreenEnabler3D] uses an approximate heuristic that doesn't take walls and other occlusion into account. This is an implementation detail and may change in future versions.
This Note is somewhat wrong, it takes Occlusion into account if you are using Occlusion Culling and have set it up properly, it's using the same logic as the Notifier.

2023-09-17 09:04 UTC, mrjustaguy commented on doc/classes/VisibleOnScreenEnabler3D.xml
> +			The path to the target node, relative to the [VisibleOnScreenEnabler3D]. The target node is cached; it's only assigned when setting this property (if the [VisibleOnScreenEnabler3D] is inside the s
Like above, it'll print an error in the editor, but the game should keep on going fine

2023-09-17 09:04 UTC, mrjustaguy commented on doc/classes/VisibleOnScreenNotifier3D.xml
> +		[b]Note:[/b] [VisibleOnScreenNotifier3D] uses the render culling code to determine whether it's visible on screen, so it won't function unless [member Node3D.visible] is set to [code]true[/code].
emphasize that it works with Occlusion Culling

2023-09-20 09:35 UTC, mrjustaguy approved these changes
Looks good to me

2023-10-17 16:14 UTC, YuriSizov commented on doc/classes/VisibleOnScreenNotifier2D.xml
> +		If you want a node to be disabled automatically when this region isn't visible on screen, use [VisibleOnScreenEnabler2D].
Same here, I guess.

2023-10-17 16:16 UTC, YuriSizov approved these changes
Aside from the note that I have left, looks solid to me.

2023-10-17 22:04 UTC, merged

2023-10-17 22:05 UTC, akien-mga commented
Thanks!