Fix Curve3D baking up vectors for nontrivial curves.
godotengine/godot pull request #81885
Opened 2023-09-18 22:36 UTC by rmmh

The code was modified in 42aa539 to have a different basis vector, but this line was missed and caused up vectors to invert sometimes.

Fixes #81879

One-character bugfix by @kleonc, bisection and test case by me.

2023-09-18 22:37 UTC, rmmh commented
Is there a better macro to test for vectors being nearly equal? CHECK_EQ is nice because it shows the precise values that are incorrect, but it's inappropriate for precise floating checks.

2023-09-18 22:52 UTC, rmmh commented on scene/resources/curve.cpp
> +			rotate.rotate_to_align(-frame_prev.get_column(2), forward);
Flipping that z-vector does not appear to fix the bug.

2023-09-18 22:59 UTC, kleonc commented on scene/resources/curve.cpp
> +			rotate.rotate_to_align(-frame_prev.get_column(2), forward);
AFAICT the forward vectors are calculated/stored correctly and #72842 haven't touched that. What it changed (or tried to change) was how such forward vectors are used for creating Basis "frames" (used for obtating up vectors). It was changed for calculating the initial frame but not for the following ones, specifically in here. So I do think that's the exact code which needed fixing

2023-09-18 23:01 UTC, kleonc commented
The bug is also present in 4.1, should be safe for cherry-picking? :thinking:

2023-09-18 23:19 UTC, TokageItLab commented on scene/resources/curve.cpp
> +			rotate.rotate_to_align(-frame_prev.get_column(2), forward);
Or passing true to the third argument of all Basis::looking_at(forward, up) in that would be one correct solution, although there is the weirdness of +Z being forward inside Curve3D.

2023-09-18 23:56 UTC, TokageItLab commented on scene/resources/curve.cpp
> +			rotate.rotate_to_align(-frame_prev.get_column(2), forward);
Oh sorry, column(2) is z-axis, I mistakenly thought it is y-axis. This would not be a problem if so,

2023-09-19 00:09 UTC, TokageItLab requested changes

2023-09-19 00:09 UTC, TokageItLab commented on scene/resources/curve.cpp
> +			rotate.rotate_to_align(-frame_prev.get_column(2), forward);
Having tested it, I can assure that this is the wrong fix.

This prevents incorrect rotation, but it is equivalent to changing all `Basis::looking_at(forward, up)` to `Basis::looking_at(forward, up, true)`, which **again flips the forward direction**. You can see that the direction of PathFollow is reversed before and after this modification.

2023-09-19 00:18 UTC, TokageItLab approved these changes
Sorry, the code got confused when I was testing. This fix is probably fine, but we should fix the comment in Line 1656:

```cpp
		Basis frame; // X-right, Y-up, Z-forward.
```
to
```cpp
		Basis frame; // X-right, Y-up, -Z-forward.
```

2023-09-19 06:01 UTC, akien-mga approved these changes
Looks good to me.

As this bug got popular on Twitter, I'll clarify that even though this will be merged in a bit, it won't make the cut for 4.2-dev5 which was built yesterday (even though we'll release it today).

It should be in 4.2-dev6 and likely 4.1.2 RC 1.

2023-09-19 07:10 UTC, merged

2023-09-19 07:11 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2023-09-20 16:51 UTC, YuriSizov commented
Cherry-picked for 4.1.2.