Make GDScript allow some keywords as identifiers
godotengine/godot pull request #8217
Opened 2017-03-31 17:34 UTC by bojidar-bg

Fixes #8085

Here is a test script:
```gdscript
extends SceneTree

func log(a): # Call with self.log()
	print(a)

func _initialize():
	var dict = {
		"true": 1,
		"false": 1,
		"null": 1,
		"sync": 1,
		"remote": 1,
		"slave": 1,
		"if": 1,
		"match": 1,
	}

	print(dict.true)
	print(dict.false)
	print(dict.null)
	print(dict.sync)
	print(dict.remote)
	print(dict.slave)
	print(dict.if)
	print(dict.match)
	print(log(1))
	print(self.log(1))
	quit()
```

Here are some things that won't work with this changes:
```gdscript
var var = 1
var const = 1
var func = 1

func and(a, b): # Technical issues for this one, since it is equivalent to func &&(a, b):..
```
And here are some strange ones that would work
```gdscript
func var(): pass # Call with self.var()
func func(): pass # self.func() or just func() if lambda isn't merged
class class:
  static func static(): return true
func _ready():
  self.var()
  self.func()
  print(class.static()) # true
```

2017-03-31 17:54 UTC, karroffel requested changes
Looks good so far, I'd keep the old error messages though.

2017-03-31 17:54 UTC, karroffel commented on modules/gdscript/gd_parser.cpp
> +							_set_error("Expected literal for argument.");
literal? It's still an identifier. It's just that the identifier might have the same name as a keyword, it's an identifier nonetheless.

Usually "constant values" (like a string or a number) are called literals. I'd keep the old error message.

2017-03-31 17:54 UTC, karroffel commented on modules/gdscript/gd_parser.cpp
> +							_set_error("Expected literal for setter function after 'setget'.");
Old relict? 😄 This is more descriptive, cool. But I'd still change it to back to identifier.

2017-03-31 17:55 UTC, bojidar-bg commented on modules/gdscript/gd_parser.cpp
> +							_set_error("Expected literal for argument.");
Ookay, would revert that part.

2017-03-31 17:58 UTC, bojidar-bg commented
@karroffel Fixed

2017-03-31 17:58 UTC, karroffel approved these changes
👍 Looks good!

2017-05-03 09:55 UTC, akien-mga commented
Since we now prevent naming variables like properties of the base class (e.g. if you name a member variable `position` or `rotation` in a Node2D, the debugger will raise an error), I think it's unnecessary to allow some half-shadowing of keywords and global scope methods. Because to be consistent we'd have to allow the same for member variables, and it would just become very confusing.

I think Godot users will learn to live with this limitation, it might be frustrating a couple times, but then you make do and benefit from the consistency.

2017-05-03 10:26 UTC, bojidar-bg commented
@akien-mga Still, I think we should allow calling methods like `sync` or `log`, even if we disallow creating variables or methods with such names.

2017-05-03 10:52 UTC, akien-mga commented
Well if we disallow creating them, it makes no sense to allow calling them, since the situation would never arise.

2017-05-03 10:59 UTC, bojidar-bg commented
@akien-mga That's wrong, since we can just have a GDNative or C# script which would be free to register them...

2017-07-11 09:31 UTC, akien-mga commented
So what should we do here (apart from a needed rebase)?

2017-07-11 13:37 UTC, vnen commented
I'm OK with this change as it fixes some current problems, like String.match() that can't be called. Creating functions with keywords as names should be documented to explain the need of the `self.` prefixing.

2017-07-17 22:19 UTC, akien-mga commented
@bojidar-bg You've got the go from @reduz, albeit you need to add some more documentation (and rebase):
```
<reduz> it's ok, but i would add a bit more doc on the source code to make sure what everything is doing and why, since it's clearly an usability hack
<reduz> as in, anyone who looks at the source eould expect to find TK_IDENTIFIER in the switch, for example
<reduz> so explaining those hacks would be a good idea
```

2017-07-23 13:14 UTC, bojidar-bg commented
Ok, rebased, now I would have to think how to include the doc. 😃

2017-07-23 20:35 UTC, bojidar-bg commented
(Bump, done, updating for email notifications)

2017-07-23 20:40 UTC, reduz commented
we really should update all docs..

On Sun, Jul 23, 2017 at 5:36 PM, Bojidar Marinov <notifications@github.com>
wrote:

> (Bump, done, updating for email notifications)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/godotengine/godot/pull/8217#issuecomment-317280261>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF-Z26NxyYnWoqKhWrR5YRMG8wlUkBsyks5sQ66ygaJpZM4Mv8uM>
> .
>

2017-07-25 06:18 UTC, merged

2017-07-25 15:10 UTC, Geequlim commented
After this commit the GDScript is totally broken!

![image](https://user-images.githubusercontent.com/6964556/28578843-766964a6-718d-11e7-96ae-100faeb33f42.png)

![image](https://user-images.githubusercontent.com/6964556/28578864-8d9c2c62-718d-11e7-8aaa-1128144a9b4a.png)

2017-07-25 15:22 UTC, akien-mga commented
Let's give @bojidar-bg some time to try a fix :)

2017-07-25 18:29 UTC, akien-mga commented
@Geequlim Fixed by #9846.