theme mods. reomoved border, changed stylebox for top part, tabs left aligned
godotengine/godot pull request #8232
Opened 2017-04-02 13:32 UTC by toger5

I changed some style box numbers so that there is no border at the left and right anymore. I think it looks really cool especially combined with a new theme. to get an idea how this looks checkout this issue:
https://github.com/godotengine/godot/issues/7294

I also would love to implement bold font since that would make a nice addition to the overall editor look.

But I'm not sure how I can achieve that with minimal changes.
since the make_default_theme function only takes one param for the font. so I would need to change that. also I'm not quite sure how the font pipeline works.
I think I just add the otg file and SCons than adds that file to the font header. than it is a available as a global var stating with _

would be cool if someone can give me some help and explanation how to add bold font to the default editor theme.

I'm not sure if this is the same with other textures for the theme, but there are currently still a couple of minor issues with positioning of ui elements, they are sometimes to close to the ground. So we might need to do some position changes to the editor node.
Would be happy for any possible help.

2017-04-02 14:22 UTC, karroffel requested changes
clang-format isn't happy. There are tabs on empty lines. Just keep the lines completely empty (aka *remove the tabs*). I commented the lines that need changing.

2017-04-02 14:22 UTC, karroffel commented on editor/editor_node.cpp
> +
here

2017-04-02 14:22 UTC, karroffel commented on scene/gui/tabs.cpp
> +
here

2017-04-02 14:22 UTC, karroffel commented on scene/gui/tabs.cpp
> +
here

2017-04-02 14:22 UTC, karroffel commented on scene/gui/tabs.cpp
> +
here

2017-04-03 09:32 UTC, bojidar-bg commented
Or just run clang-format on the affected files, rather than doing it manually.

2017-04-03 15:35 UTC, toger5 commented
did the clang formatting

2017-04-26 07:05 UTC, akien-mga commented on scene/gui/tabs.cpp
> +				Ref<Font> fo;
Using `sb` for `StyleBox` on the above line is a bad convention, so you should not try to emulate it. `font` would have been just fine as identifier.

2017-04-26 07:05 UTC, akien-mga commented
@djrm Can you check that this goes in the same direction as your own theme changes, so that we don't merge conflicting stuff?

2017-04-26 21:35 UTC, toger5 commented
@djrm we need to discuss anyways if you even want to use that pr or if you prefer making one big pr where you add all the changes.
I would be willing to update that pr and change the requested changes but first we need to decide if it is even with using it.

2017-04-26 23:16 UTC, djrm commented
@toger5 yeah i got kind of tired about the theme thing so i guess i will make a PR with the last tweaks and then people can improve the theme, i stated before my opinions about the theme and tried to improve acording to people comments but i think that people should try new variations and see what is better usabillity wise, im going to keep improving the proposed theme, but i need some help with the details (a task that is proving the be a bit tedious) also amost everytime that i rebase my local branch there is something that breaks my theme (or at least some part of it, currently the window margins), so thats it i will create a PR then you can try new thing or fix existing issues, also i see that the vector theme thread is going theorical so i dont thing it will be possible for godot 3.0 to improve usabillity at the proposed levels.

2017-04-26 23:21 UTC, toger5 commented
@djrm that sounds really well. Thank you for the work you did till now!
I don't know how much time I will have in the upcoming days but having your theme as a pr is great!
I understand that keeping the pr mergable is a tidies task. Lets see how things go.

2017-06-05 07:18 UTC, akien-mga commented
@toger5 What should we do with this PR? I guess it was partly obsoleted by recent theme changes; are there still changes there you'd like to rebase on top of master?

2017-06-05 07:45 UTC, closed without merging

2017-06-05 07:46 UTC, toger5 commented
@akien-mga Sorry I forgot about it...
All the changes are obsolete with the new theme! So I close. Thank you for asking and reminding me though!