Make SkeletonIk3D node usable
godotengine/godot pull request #82391
Opened 2023-09-26 18:27 UTC by warriormaster12

Fixed an issue where "Play IK" would stop playing IK in editor when changing from one node to another. This issue made basically SkeletonIK3D node useless since you couldn't preview how it looked like or you could but it would have involved going back and forth between ik and target node. 

Now you can:

- preview ik without going back and forth between ik and target node.
- turn on multiple SkeletonIK3D nodes.

 

https://github.com/godotengine/godot/assets/33091666/a59c4c8c-587c-4f03-b4e3-d6268c3a0b39

Fixes: not sure if there's an issue reported, but I was so annoyed by this when making my own game

2023-09-26 19:02 UTC, bitsawer commented
Looks like this would possibly fix https://github.com/godotengine/godot/issues/72945?

2023-09-28 04:05 UTC, SaracenOne approved these changes
Tested. LGTM 👍

2023-09-28 04:14 UTC, SaracenOne requested changes
Actually, on further inspection, there still appears to be a bug with this. It looks like if the SkeletonIK node is deleted, the IK will continue to be performed unless the scene is completely closed. Would you mind investigating this so we can conclusively say that issues regarding previewing the IK node in the editor are fixed?

2023-09-28 04:22 UTC, warriormaster12 commented
Sure, didn't even realize to test that use case 👍

2023-09-28 04:42 UTC, warriormaster12 commented
@SaracenOne now when the node exits tree, it will stop ik playback. Undoing the action won't turn it back on though, not sure if it is necessary to even track.

2023-09-28 05:34 UTC, SaracenOne approved these changes
Seems all good now! 👍

2023-09-28 17:23 UTC, YuriSizov commented
For future reference, please use more descriptive commit messages and PR titles.

2023-09-28 18:09 UTC, merged

2023-09-28 18:10 UTC, YuriSizov commented
Thanks!

2023-09-28 18:17 UTC, warriormaster12 commented
Yeah sorry, the title and description was written a bit out of frustration

2023-10-25 10:25 UTC, YuriSizov commented
Cherry-picked for 4.1.3.