[iOS] Fix build with Xcode 15.
godotengine/godot pull request #82458
Opened 2023-09-27 18:30 UTC by bruvzg

- Add a workaround for linker bug (same as https://github.com/godotengine/godot/pull/81968)
- Bump iOS min. version to 12.0, since SDK for 11.0 is no longer included or supported.
- Remove some deprecated code.

2023-09-29 14:30 UTC, Scoppio requested changes
Since you are changing the xcode build target, there is need to add the target change to the documentation as well, those two cannot be different, otherwise we endup with a doc that says you can build for iPhone 11 and an engine that only targets 12 and up.

2023-09-29 14:35 UTC, akien-mga commented
We should fix the build issue on `4.1`/`4.0` and `3.x`/`3.5`, but ideally there I would like to preserve iOS 11 support (at least for release branches, for `3.x` we could bump to 12).

2023-09-29 22:11 UTC, LeandroHPerez commented
@akien-mga 
@bruvzg 

I noticed that it is not possible to downgrade xcode to version 14.x.
The newest version (Xcode 14.3.1) is not compatible with Macos Sonoma 14.0.
Therefore, if the bug is not fixed, users with Macos Sonoma will not be able to export the Godot project to iOS.
Only Xcode version 15 runs on macos sonoma.

2023-09-29 22:38 UTC, bruvzg commented
> but ideally there I would like to preserve iOS 11 support

I'll take a look if it's possible, but I do not think there's any reason to support it. Unlike iOS 12, iOS 11 is completely obsolete and does not receive security updates for 5 years, no one should use it.

2023-09-30 08:14 UTC, akien-mga commented
Ok, let's drop iOS 11 then, if Apple forces our hand there's no reason to fight them.

2023-09-30 09:04 UTC, merged

2023-09-30 09:05 UTC, akien-mga commented
Thanks!

2023-10-03 18:16 UTC, akien-mga commented
Cherry-picked for 4.1.2.

2023-10-04 00:48 UTC, LeandroHPerez commented
I came here to inform that i tested on brand new [4.2-dev6](https://github.com/godotengine/godot-builds/releases/tag/4.2-dev6) and cannot perfectly build it in xcode 15 with macbook with Apple Silicon yet....

But now, minimum iOS version is 12.0.  

Errors:
![image](https://github.com/godotengine/godot/assets/5435476/7d731506-9edd-4cac-8ff7-46435125d085)

Complete project and configuration can be found here:
https://github.com/godotengine/godot/issues/82551
but now de Godot version is 4.2-dev6

@akien-mga

2023-10-28 13:23 UTC, stevencodeuk commented
With this issue still existing, what is currently the best combo versions of Godot 4/Xcode to export iOS with plugins with?

2024-06-01 22:02 UTC, AsielPosada commented
Facing same issue currently with v4.2.2.stable.official [15073afe3]
<img width="1000" alt="image" src="https://github.com/godotengine/godot/assets/36686010/4696c882-c2ea-4fd4-86cf-3acde177d629">

2024-06-02 06:32 UTC, akien-mga commented
Which Xcode version do you have? The upstream bug was fixed in 15.2.

2024-06-02 07:21 UTC, bruvzg commented
> Facing same issue currently with v4.2.2.stable.official

Are you trying to run it in the simulator on Apple Silicon Mac? Official templates include only `x86_64` simulator and `arm64` device libs, but not `arm64` simulator lib (it's build with OSXCross, and it still not capable of building it). You can run it on the real iOS device, or select "This mac" instead of simulator, or run Xcode under Rosetta to use `x86_64`, or build a custom template.