Add preprocessor pass on visual shader when showing generated code
godotengine/godot pull request #82570
Opened 2023-09-30 02:34 UTC by 100gold

Fixes #82555 
Add preprocessor pass and check for errors in visual shader editor.

2023-10-02 14:23 UTC, bitsawer commented
Looks pretty good. I would also add the preprocessor error file name, which makes it easier to find the actual issue if you have complex or nested includes.

Also, looks like the error line number highlight is off by one, needs `- 1`. Updated section of the code would be this:


```cpp
if (err != OK) {
    ERR_FAIL_COND(err_positions.size() == 0);

    String file = err_positions.front()->get().file;
    int err_line = err_positions.front()->get().line;
    Color error_line_color = EDITOR_GET("text_editor/theme/highlighting/mark_color");
    preview_text->set_line_background_color(err_line - 1, error_line_color);
    error_panel->show();

    error_label->set_text("error(" + file + ":" + itos(err_line) + "): " + error_pp);
    shader_error = true;
    return;
}
```

2023-10-02 15:44 UTC, 100gold commented
> Looks pretty good. I would also add the preprocessor error file name, which makes it easier to find the actual issue if you have complex or nested includes.
> 
> Also, looks like the error line number highlight is off by one, needs `- 1`. Updated section of the code would be this:
> 
> ...

Thanks! There was another issue with the error line number when there was an error in the included file. Fixed both issues.

2023-10-29 15:11 UTC, bitsawer requested changes
Tested locally and works as expected. One comment should be updated to the new format (capitalized and ends with a dot), but other than that looks good.

As a note to myself and future maintainers, this code is now pretty similar to ShaderTextEditor version with some small differences, so it might be possible to merge them in the future. No need to do that in this PR, however.

2023-10-29 15:11 UTC, bitsawer commented on editor/plugins/visual_shader_editor_plugin.cpp
> +			//error is in an include
```suggestion
			// Error is in an include.
```

2023-10-29 16:16 UTC, AThousandShips commented
Your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

2023-10-29 21:23 UTC, clayjohn approved these changes
Seems fine to me. I am not familiar with this code, but I trust the other reviewers

2023-10-30 13:43 UTC, bitsawer approved these changes

2023-10-30 13:44 UTC, AThousandShips approved these changes

2023-10-30 15:27 UTC, merged

2023-10-30 15:30 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: