fixing bitmap error when parsing '-'
godotengine/godot pull request #82911
Opened 2023-10-06 13:12 UTC by k0T0z

Fixes #82880.

2023-10-06 13:51 UTC, bruvzg requested changes
This won't work and will break parsing of every range in ` U+xxxx` or hex form.

2023-10-06 13:59 UTC, k0T0z commented on editor/import/resource_importer_imagefont.cpp
>  		Vector<String> tokens = ranges[i].split("-");
Very good, this looks much better, but can you give an example of a range of hex ``U+xxxx``?

2023-10-06 14:04 UTC, k0T0z commented on editor/import/resource_importer_imagefont.cpp
>  		Vector<String> tokens = ranges[i].split("-");
@bruvzg What about this: ``'''-'''`` or ``'"'-'"'``?

2023-10-06 18:07 UTC, k0T0z commented
@bruvzg I think this will do it. I added a step before splitting the range to replace every ``"'-'"`` with ``"0x2D"`` if existed and valid of course. I tested it and it working great.

2023-10-07 08:51 UTC, AThousandShips commented on editor/import/resource_importer_imagefont.h
> +	String CorrectOutlierSplitters(const String &range);
```suggestion
	String correct_outlier_splitters(const String &p_range);
```
Prefix arguments with `p_` and use `snake_case`

2023-10-07 08:51 UTC, AThousandShips commented on editor/import/resource_importer_imagefont.cpp
> +				accumulator += range[ptr];
```suggestion
String ResourceImporterImageFont::correct_outlier_splitters(const String &p_range) {
	String new_range, accumulator;
	if (p_range.length() == 0) {
		return new_range;
	}
	enum Tokens {
		OPEN_SINGLE_QUOTE,
		CHARACTER,
		CLOSE_SINGLE_QUOTE,
		SPLITTER,
		INVALID
	};
	Tokens next_token[2] = { OPEN_SINGLE_QUOTE, CHARACTER };
	int ptr = 0 ;
	bool opened_quote = false, outlier_splitter = false;
	while (true) {
		if (ptr >= p_range.length()) {
			break;
		}
		switch (p_range[ptr]) {
			case '\'':
				if (next_token[0] == OPEN_SINGLE_QUOTE || next_token[1] == OPEN_SINGLE_QUOTE) {
					next_token[0] = CHARACTER;
					next_token[1] = INVALID;
				} else if (next_token[0] == CHARACTER || next_token[1] == CHARACTER) {
					next_token[0] = CLOSE_SINGLE_QUOTE;
					next_token[1] = INVALID;
				} else if (next_token[0] == CLOSE_SINGLE_QUOTE || next_token[1] == CLOSE_SINGLE_QUOTE) {
					next_token[0] = SPLITTER;
					next_token[1] = INVALID;
					accumulator.clear();
					if (outlier_splitter) {
						outlier_splitter = false;
						new_range += "0x2D"; // Outlier? replace it.
					} else {
						new_range += p_range.substr(ptr - 2, 3);
					}
				} else {
					new_range += accumulator;
					new_range += p_range.substr(ptr);
					return new_range;
				}
				accumulator += p_range[ptr];
				break;
			case '-':
				if (next_token[0] == CHARACTER || next_token[1] == CHARACTER) {
					next_token[0] = CLOSE_SINGLE_QUOTE;
					next_token[1] = INVALID;
					outlier_splitter = true;
				} else if (next_token[0] == SPLITTER || next_token[1] == SPLITTER) {
					next_token[0] = OPEN_SINGLE_QUOTE;
					next_token[1] = CHARACTER;
					accumulator.clear();
					new_range += '-'; // Not outlier? add it.
				} else {
					new_range += accumulator;
					new_range += p_range.substr(ptr);
					return new_range;
				}
				accumulator += p_range[ptr];
				break;
			default:
				if (next_token[0] == CHARACTER || next_token[1] == CHARACTER) {
					accumulator.clear();
					new_range += p_range[ptr]; // Not outlier? add it.
				} else {
					new_range += accumulator;
					new_range += p_range.substr(ptr);
					return new_range;
				}
				accumulator += p_range[ptr];
```

2023-10-07 08:51 UTC, AThousandShips commented on editor/import/resource_importer_imagefont.cpp
> +		String range{ ResourceImporterImageFont::CorrectOutlierSplitters( ranges[i]) };
```suggestion
		String range = correct_outlier_splitters(ranges[i]);
```

2023-10-07 08:51 UTC, AThousandShips commented on editor/import/resource_importer_imagefont.cpp
> +				String token{ tokens[0] };
```suggestion
				String token = tokens[0];
```

2023-10-07 09:23 UTC, k0T0z commented
I would like this PR to be part of Hacktoberfest. Thank you!

2023-10-07 09:25 UTC, AThousandShips commented on editor/import/resource_importer_imagefont.cpp
> +	if (p_range.length() == 0) {
```suggestion
	if (p_range.is_empty()) {
```

2023-10-07 09:25 UTC, AThousandShips commented on editor/import/resource_importer_imagefont.cpp
> +		}
```suggestion
		if (tokens.size() == 2 && tokens[0] == tokens[1]) {
			String token = tokens[0];
			tokens.clear();
			tokens.push_back(token);
		}
```

2023-11-09 15:05 UTC, k0T0z commented
@AThousandShips I want to finalize this by adding unit tests but actually there is no place for ``editor/imports/`` inside ``tests/`` so I just add a new directory there or there is a specific place for them?

2023-11-09 15:08 UTC, AThousandShips commented
Don't think we do unit tests for the editor builds right now, think that needs to be discussed and see if it's possible, and if this can be tested without certain features available

2023-11-09 15:09 UTC, k0T0z commented
Alright then, I will discuss this on the related channel ASAP 👍.

2023-11-09 15:10 UTC, AThousandShips commented
No rush, probably a complex topic that might not be worth waiting for with this PR but add later, though this PR will be for 4.3 anyway

2023-11-09 15:14 UTC, k0T0z commented
Cool, I hope I can be here for a more complex topic but I am busy with other things now. I get it and I intend to achieve more challenging things here 🤝

2023-11-09 15:39 UTC, AThousandShips commented
You removed the method in the header file, accident?

2023-11-09 15:41 UTC, k0T0z commented
I am just squashing commit, I will fix this now

2024-02-14 10:49 UTC, akien-mga commented
Superseded by #88088. Thanks for the contribution!

2024-02-14 10:49 UTC, closed without merging