Show warning on AnimationTree for invalid advance expression
godotengine/godot pull request #82975
Opened 2023-10-07 16:30 UTC by jackwilsdon

This PR makes the engine display a warning in the scene tree editor against AnimationTrees which have a `AnimationNodeStateMachineTransition` with an invalid expression (i.e. one that can't be parsed):

![Configuration warning for invalid advance expression](https://github.com/godotengine/godot/assets/1843197/b30bd624-a746-46a9-96ff-f4b6bf6f198e)

It also adds some error reporting to `set_advance_expression`, which shows up in the editor's output (and debugger for running projects):

![Error in output](https://github.com/godotengine/godot/assets/1843197/d1ccc65a-9e9c-40ea-b06a-8ac46d96d085)

![Error in debugger](https://github.com/godotengine/godot/assets/1843197/b1e7a88f-c497-421a-bb6e-6546ec9f59a0)

One downside to adding this error reporting to the setter is that there is no debouncing when editing the expression via the inspector, causing every keystroke to report an error in the output (unless the expression is valid):

![Errors reported whilst typing "value == 3 + 4"](https://github.com/godotengine/godot/assets/1843197/8720fba6-576a-4c39-b7de-5609424b6b57)

I'm happy to remove this error reporting if need be, as it is only really useful if setting `advance_expression` at runtime, which I can't imagine is done very often.

2023-10-07 17:05 UTC, jackwilsdon commented
I've just pushed c396f5e2453b0e0aab83fcf0be749d3ffe720f73 which makes it so that we no longer report an error in the setter whilst running in the editor - this avoids the error being reported repeatedly whilst the user is typing in an expression. We still report an error if the project is running in the editor.

2023-10-07 17:09 UTC, Calinou commented
It may be worth detecting the `=` case in particular and suggesting the use of `==` in the node configuration warning.

2023-10-07 17:36 UTC, jackwilsdon commented
Yeah that sounds good. I've implemented it by checking the error returned by `get_error_text` - doing it this way seems a bit fragile, but Expression doesn't appear to expose anything else that we could check.

I've also changed the warning to now include the actual error returned by `get_error_text`, which should hopefully make it easier to understand:

![Configuration warning for invalid advance expression](https://github.com/godotengine/godot/assets/1843197/60b492db-4011-4371-8f96-0416c510f1b2)

The warning is getting a bit long now though - I'm wondering if it's worth dropping the actual expression from the error seeing as the warning already indicates which transition has the invalid expression.

Also, "maybe '=' should be '=='?" probably needs rewording, although I can't think of anything better off the top of my head.

2023-10-15 23:39 UTC, SaracenOne requested changes
I think this is fine since it provides much-needed feedback if something goes wrong, but I would recommend having the configuration_warnings bury into the subnodes too, since it currently only detects expression warnings in the highest level node, and its quite common to have a mix of blendtrees and state machines.

2026-06-29 19:06 UTC, closed without merging