Add optional warnings when accessing properties and methods whose name starts with an underscore from other scripts.
godotengine/godot pull request #83250
Opened 2023-10-13 09:04 UTC by HexagonNico

Whether GDScript should have access modifiers or not is a matter that has been discussed for a long time. Up to now, the convention has been to use identifier names starting with an underscore for private variables and functions, so I suggest to implement an optional warning (ignored by default) that triggers when an attribute or method whose name starts with an underscore is accessed from another script.

For example, this will trigger the warning:
```
class_name MyScript
extends Node

var _private: int = 1

func _private_func():
    pass
```
```
extends Node

@onready var _my_script: MyScript = $MyScript

func _ready():
    _my_script._private += 1
    _my_script._private_func()
```

I believe this should help to enforce the convention.

I should also mention that accessing the same variables and function from a child script will not trigger the warning, so technically they wouldn't be private, but protected. For example, this will not trigger the warning.

```
class_name OtherScript
extends MyScript

func _ready():
    _private += 1
    _private_func()
```

2023-10-13 09:07 UTC, AThousandShips commented
Please open a [proposal](https://github.com/godotengine/godot-proposals) to gauge the support for this idea

2023-10-13 09:18 UTC, AThousandShips commented on modules/gdscript/gdscript_analyzer.cpp
> +		if (((String) p_call->function_name).begins_with("_")) {
```suggestion
		if (String(p_call->function_name).begins_with("_")) {
```

2023-10-13 09:18 UTC, AThousandShips commented on modules/gdscript/gdscript_analyzer.cpp
> +				if (((String) p_subscript->attribute->name).begins_with("_")) {
```suggestion
				if (String(p_subscript->attribute->name).begins_with("_")) {
```

2023-10-13 09:18 UTC, AThousandShips commented on modules/gdscript/tests/scripts/analyzer/warnings/private_property_access.gd
> +    var _private := 1
```suggestion
    var _private := 1

```
Missing line termination

2023-10-13 09:18 UTC, AThousandShips commented on modules/gdscript/tests/scripts/analyzer/warnings/private_method_access.gd
These should use tabs for indentation

2023-10-13 09:18 UTC, AThousandShips commented on modules/gdscript/tests/scripts/analyzer/warnings/private_property_access.gd
Same here, tabs

2023-10-13 09:48 UTC, AThousandShips commented
The documentation has to be in alphabetical order, update it by running `godot --doctool`, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/updating_the_class_reference.html#updating-class-reference-when-working-on-the-engine)

2023-10-13 10:37 UTC, AThousandShips commented
Also the test doesn't work correctly, it warns on access to ones in the same class or script, even without `self`

2023-10-13 11:19 UTC, AThousandShips requested changes
Needs to be rewritten to handle the access properly, currently it always throws the warning/error when a property/method with leading `_` is accessed, also needs more comprehensive tests to catch both false negatives and false positives, see above

2023-10-13 11:20 UTC, dalexeev commented
> All of the effort to implement this really sounds like it could better be spent on actually bringing some form of a `private` keyword someday, huh?

I agree, if we don't want false positive warnings (see also https://github.com/godotengine/godot/issues/74879#issuecomment-1471634312), then untyped code should never produce the warning:

```gdscript
var a: OtherClass
var b: Variant
a._property # Warning.
b._property # No warning, can be the same class.
```

But then this warning can be ignored using `(expression as Variant)._property`, and will not cause an error at runtime, unlike real private variables.

This also needs to take inheritance into account, meaning that GDScript's "private" members are more like "protected" members (some languages, like Haxe, don't have a `protected` modifier either).

2023-10-14 12:04 UTC, HexagonNico commented
Closing in favor of #641.

2023-10-14 12:04 UTC, closed without merging

2023-10-14 12:10 UTC, AThousandShips commented
Thank you for your contribution nonetheless!