Fix phantom tab right button
godotengine/godot pull request #83296
Opened 2023-10-13 23:13 UTC by Wierdox

Fixes #83232

Was caused by only updating the right button `rb_rect` of a tab if the texture was valid. Therefore, it would never be updated when texture is `null` and so keep its size forever.

Solved by adding a branch to its update logic in `TabBar::_draw_tab()` to set `rb_rect` to an empty `Rect2`.

2023-10-13 23:26 UTC, YeldhamDev requested changes

2023-10-13 23:26 UTC, YeldhamDev commented on scene/gui/tab_bar.cpp
> +		tabs.write[p_index].rb_rect = rb_rect;
```suggestion
	} else {
		tabs.write[p_index].rb_rect = Rect2();
```

2023-10-14 03:02 UTC, YeldhamDev approved these changes

2023-10-16 08:45 UTC, merged

2023-10-16 08:46 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: