added remove all children from a node
godotengine/godot pull request #8337
Opened 2017-04-09 16:20 UTC by AlexHolly

#8125

2017-04-09 17:48 UTC, karroffel requested changes
clang-format isn't happy. Fix your formatting. Take a look at the travis page for that.

2017-04-09 17:48 UTC, karroffel commented on scene/main/node.cpp
> +	ClassDB::bind_method(D_METHOD("remove_all_children:Node"), &Node::remove_all_children);
`remove_all_children` doesn't return `Node`, please remove the `:Node` part, it's wrong.

2017-04-09 18:41 UTC, neikeq commented
`remove_child` does not `queue_free` the child, this will lead to confusion. This new method should be named `queue_free_children`, not `remove_all_children`.
I don't think there is any point in adding such method though, IMO. Doing this is already pretty simple.

2017-04-09 18:56 UTC, volzhs commented
@neikeq I second that it should be `queue_free_children`

2017-04-09 18:59 UTC, akien-mga commented
>  I don't think there is any point in adding such method though, IMO. Doing this is already pretty simple.

Agreed. IMO `for child in get_children_count(): child.queue_free()` is simple enough and more explicit.

2017-04-09 19:12 UTC, volzhs commented
And I'm worrying this can cause unexpected behavior like #7142

2017-04-12 12:59 UTC, closed without merging

2020-04-29 00:18 UTC, Shadowblitz16 commented
@akien-mga  please reopen this.
your logic is flawed due to gdscript being so slow

2020-04-29 06:08 UTC, akien-mga commented
Make a benchmark before calling my logic flawed.

2024-12-03 20:42 UTC, Calandiel commented
Well, for languages other than gdscript (C# or Rust, for example), this will very clearly be slower than the proposed API.

You need `n` calls into engine routines for `n` children (instead of just one) and you perform an allocation to get the list of children.

What kind of benchmark would you like to see?