[WIP] Implemented part of core API
godotengine/godot pull request #8351
Opened 2017-04-10 21:30 UTC by cynicaldevil

cc @karroffel 
I haven't tried to build it yet, just pushed in the state it is right now.

2017-04-10 21:37 UTC, karroffel commented on modules/gdnative/godot/godot_image.cpp
> +	memnew_placement_custom(img, Image, img->compressed(p_mode));
`memnew_placement_custom` is only used to *construct* the objects. If you just want to use them you can do

```cpp
Image *img = (Image *)p_img;
img->compressed(p_mode);
```

2017-04-10 21:38 UTC, karroffel commented on modules/gdnative/godot/godot_image.cpp
> +	memnew_placement_custom(img, Image, img->compressed(p_mode));
For example take a look at the `has_mipmap` function.

2017-04-10 21:41 UTC, karroffel commented on modules/gdnative/godot/godot_image.h
> +void GDAPI godot_image_decompressed(const godot_image *p_img);
This and `godot_image_compressed` should return a new image.

2017-04-15 14:13 UTC, cynicaldevil commented
@karroffel I've updated the PR, and it builds ok now. Let me know if functions need to be added/updated.

2017-04-15 14:49 UTC, bojidar-bg commented on modules/gdnative/godot/godot_image.cpp
> +	godot_rect2 *rect = (godot_rect2 *) &cpp_rect2;
Should be :
```cpp
godot_rect2 *rect = (godot_rect2 *)&cpp_rect2;
//---------------------------------^ No space here
```
According to styleguide

2017-05-11 10:44 UTC, cynicaldevil commented
@bojidar-bg Sorry for the long delay, I had my end terms and some other stuff to attend to.I've updated the PR now.

2017-05-11 13:59 UTC, karroffel requested changes

2017-05-11 13:59 UTC, karroffel commented on modules/gdnative/godot/godot_image.cpp
> +	godot_image *compressed_img = (godot_image *)&cpp_img;
careful with this, it doesn't work. The destructor will be called at the end of the scope, taking a pointer doesn't change that.

So you need to create an object with non local lifetime using `memnew_placement` and then assign this new image to it.

This simple "pointer casting" technique doesn't work with objects that have a destructor.

2017-05-13 11:27 UTC, cynicaldevil commented on modules/gdnative/godot/godot_image.cpp
> +	godot_image *compressed_img = (godot_image *)&cpp_img;
Soemthing like this?
```
godot_image GDAPI godot_image_compressed(godot_image *p_img, int p_mode) {
	Image *img = (Image *)p_img;
	godot_image compressed_img;
	Image *cpp_img = (Image *)&compressed_img;
	memnew_placement(cpp_img, Image);
	cpp_img = img->compressed(p_mode);
	return compressed_img;
}
```

2017-05-13 11:48 UTC, karroffel commented on modules/gdnative/godot/godot_image.cpp
> +	godot_image *compressed_img = (godot_image *)&cpp_img;
`*cpp_img = img->compressed(p_mode);`

But yes, this looks better.

2017-05-13 13:13 UTC, cynicaldevil commented
@karroffel Updated PR with changes.

2017-06-05 23:50 UTC, karroffel commented
@cynicaldevil uhm, so thanks very much for the initiative! But Image has been removed from the list of core types, so a wrapper isn't needed anymore. Actually most of the core API is complete now, the only thing that's really missing are string functions.

So it depends on you. I can close this and implement the string stuff myself or you can try to fill in the string stuff.

2017-06-07 13:46 UTC, cynicaldevil commented
@karroffel I don't have time to contribute anymore, so I don't think I'll be able to write the string functions.

2017-06-07 13:59 UTC, karroffel commented
@cynicaldevil that's okay, thanks for your initiative! 💙

2017-06-14 20:22 UTC, closed without merging