[WIP] Add duplicate / cut / copy / paste to animation tree editors
godotengine/godot pull request #83518
Opened 2023-10-17 18:44 UTC by astillich

This PR will add the missing duplicate / cut / copy / paste functions for the animation tree editors.

Fixes #80009

2023-10-22 12:34 UTC, AThousandShips requested changes, later dismissed

2023-10-22 12:44 UTC, astillich commented on editor/plugins/animation_blend_space_1d_editor.cpp
> +	auto node = _dup_copy_point();
Updated PR with auto removed.

2023-11-08 13:09 UTC, KoBeWi commented
When I cut with Ctrl+X shortcut in the blend tree editor, I can't paste.

2023-11-08 13:49 UTC, KoBeWi commented
I think it's fine currently, what I reported looks like existing selection bug. Clicking a stack of points will select the one added earlier, but the later one is on top, which looks like the point can't be selected. Maybe you could improve that somehow.

2023-12-17 13:41 UTC, KoBeWi commented
The last problem I mentioned (preview not refreshing after adding node) needs to be resolved.

2023-12-18 17:21 UTC, astillich commented
I'll find some time over the (German) Christmas holidays. I wasn't in a hurry because this wasn't assigned to a milestone and I was busy with other things.

2024-08-04 21:26 UTC, colinmbo commented
Really hoping this gets resolved soon. AnimationTree state machines are unnecessarily difficult to work with currently because you have to manually rebuild every single node that you want to move inside a nest. I've already had to rebuild the same state machine over and over again in order to get the nested structure set up how I want. If not this, there needs to be some other way to move nodes inside sibling state machines instead of manually deleting them and recreating them every time they need to be moved around.

2024-08-04 21:52 UTC, Calinou commented
4.3 is currently in release freeze, so new features can only be merged in 4.4 at the earliest. Also, this PR needs to be [rebased](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) to resolve merge conflicts.

2025-01-17 17:20 UTC, Calinou commented
@astillich Could you look into rebasing this PR on `master` to fix merge conflicts? Thanks in advance :slightly_smiling_face: 

If you aren't available to do this, let us know and we can mark this PR as salvageable.

2025-03-29 10:02 UTC, dfendt commented
Heyyo! With 4.4 released, is there any possibility this will get some love and care? :) Hate having to ask for someone else to do it, but I'm no engine programmer unfortunately.

2026-01-29 09:37 UTC, AThousandShips commented on editor/animation/animation_state_machine_editor.h
> +	void _add_node_and_transition(const String &p_base_name, Ref<AnimationNode> node);
```suggestion
	void _add_node_and_transition(const String &p_base_name, Ref<AnimationNode> p_node);
```

2026-01-29 09:38 UTC, AThousandShips commented on editor/animation/animation_state_machine_editor.cpp
> +void AnimationNodeStateMachineEditor::_add_node_and_transition(const String &p_base_name, Ref<AnimationNode> node) {
```suggestion
void AnimationNodeStateMachineEditor::_add_node_and_transition(const String &p_base_name, Ref<AnimationNode> p_node) {
```

2026-01-29 09:43 UTC, AThousandShips commented on editor/animation/animation_blend_space_1d_editor.h
> +	void _dup_paste_point(Ref<AnimationNode> node, float p_position);
```suggestion
	void _dup_paste_point(Ref<AnimationNode> p_node, float p_position);
```

2026-01-29 09:44 UTC, AThousandShips commented on editor/animation/animation_blend_space_1d_editor.cpp
> +void AnimationNodeBlendSpace1DEditor::_dup_paste_point(Ref<AnimationNode> node, float p_position) {
```suggestion
void AnimationNodeBlendSpace1DEditor::_dup_paste_point(Ref<AnimationNode> p_node, float p_position) {
```

2026-02-09 17:55 UTC, astillich commented
@Calinou I updated the PR to master and it still seems to work. However, there are two remaining problems: 1) refreshing the view does not always work, but this is nothing new as it also happens when undoing creating nodes via the context menu (event on the master branch).  What more can I do other than calling _update_graph()? 2) sometimes the shortcuts for copy / paste does not work, I'm willing to figure this out if I find a solution for 1).

2026-02-09 19:26 UTC, Calinou commented
> 2) sometimes the shortcuts for copy / paste does not work, I'm willing to figure this out if I find a solution for 1).

Double-check where you are currently focused in the editor when pressing the copy/paste shortcuts. Something else may be intercepting the shortcut (e.g. if the mouse is already on an animation node, or you've clicked outside the animation node editor dock).

2026-04-15 17:28 UTC, vaner-org commented
@astillich Thanks for your work on this, it is a very important feature to have and if time is difficult to find I'd like to offer help in getting it to the finish line.

Unfortunately a [merge commit](https://github.com/godotengine/godot/pull/83518/commits/4ef4f6558fb7a53855e8d59b039d3997f005a1db) has made it into your commit chain, when you intended to rebase instead. [There is a guide here](https://stackoverflow.com/questions/24383813/remove-an-unwanted-merge-commit-and-rebase-instead-with-git) that lists steps in rectifying this, merging into master won't be possible otherwise.

2026-05-31 15:43 UTC, rchavik commented
@astillich i tried copying your changes and apply it on top 4.6-stable.  It combined your branches into a single commit. I use your first commit sha for the amend message.

Here is the diff: https://github.com/godotengine/godot/compare/4.6...rchavik:godot:4.6-animation-tree-editor-copy-paste

Tried applying this on top of master but failed.  Hopefully someone can pick it up for master.

2026-06-01 03:58 UTC, rchavik commented
> Tried applying this on top of master but failed. Hopefully someone can pick it up for master.

Here's on top of master: https://github.com/godotengine/godot/compare/master...rchavik:godot:4.7-animation-tree-editor-copy-paste

2026-07-13 07:49 UTC, Cthutq295 commented
@vaner-org Hey, any chance you could pick this PR up? to get this finally merged into engine?

2026-07-14 08:23 UTC, vaner-org commented
> Duplicate in BlendSpace1D is confusing. The new point is created at the same position and when you try to drag it, the point behind is selected instead and lacks selection highlight. EDIT: Seems like the point is inserted at the cursor position, which can be the same as the old point. It's still confusing to interact. BlendSpace2D has the same problem, but it's less prominent, because the points have more space to appear.

This can be solved by #118628.

> 1) refreshing the view does not always work, but this is nothing new as it also happens when undoing creating nodes via the context menu (event on the master branch).

This is no longer the case as of #116946.

> 2) sometimes the shortcuts for copy / paste does not work

If I can iron out this remaining bug, is this PR ok for me to salvage?

2026-07-14 16:12 UTC, Calinou commented
> If I can iron out this remaining bug, is this PR ok for me to salvage?

Sure, feel free to open a PR to salvage this one (make sure to keep the original Git commit author information, and add yourself as a co-author).

2026-07-17 00:34 UTC, vaner-org commented
Salvage is ready for review at https://github.com/godotengine/godot/pull/121410.

2026-07-18 22:03 UTC, KoBeWi commented
Superseded by #121410

2026-07-18 22:03 UTC, closed without merging