add support for EGL 1.4
godotengine/godot pull request #83930
Opened 2023-10-25 08:32 UTC by underdoeg

Debian 10 and (I think) 11 only have libEGL Version 1.4. Those OS are still widely used in integrated hardware like Rock PI and similar ARM devices. 
This patch checks for the EGL version and calls older methods if necessary.

2023-10-25 08:45 UTC, bruvzg reviewed
1.5 was assumed as default when EGL was only used with ANGLE on macOS/Windows, for X11 in should be fine to 1.4 (not sure about Wayland).

2023-10-25 08:45 UTC, bruvzg commented on drivers/egl/egl_manager.cpp
> +	}
```suggestion
	if (egl_version >= GLAD_MAKE_VERSION(1, 5)) {
		Vector<EGLAttrib> attribs = _get_platform_display_attributes();
		new_gldisplay.egl_display = eglGetPlatformDisplay(_get_platform_extension_enum(), new_gldisplay.display, (attribs.size() > 0) ? attribs.ptr() : nullptr);
	} else {
		new_gldisplay.egl_display = eglGetDisplay(new_gldisplay.display);
	}
```

2023-10-25 08:45 UTC, bruvzg commented on drivers/egl/egl_manager.cpp
> +	}
```suggestion
	if (egl_version >= GLAD_MAKE_VERSION(1, 5)) {
		glwindow.egl_surface = eglCreatePlatformWindowSurface(gldisplay.egl_display, gldisplay.egl_config, p_native_window, nullptr);
	} else {
		EGLNativeWindowType* native_window_type = p_native_window;
		glwindow.egl_surface = eglCreateWindowSurface(gldisplay.egl_display, gldisplay.egl_config, *native_window_type, nullptr);
	}
```

2023-10-25 08:50 UTC, AThousandShips commented on drivers/egl/egl_manager.cpp
> +		EGLNativeWindowType* native_window_type = (EGLNativeWindowType*)p_native_window;
```suggestion
		EGLNativeWindowType *native_window_type = (EGLNativeWindowType*)p_native_window;
```

2023-10-25 08:51 UTC, underdoeg commented
Trying to fix the formatting.

@bruvzg This change should theoretically not affect newer systems with EGL 1.5 in place

2023-10-25 08:52 UTC, AThousandShips commented
I'd recommend using `clang-format`, see [here](https://docs.godotengine.org/en/stable/contributing/development/code_style_guidelines.html#using-clang-format-locally)

2023-10-25 08:54 UTC, AThousandShips commented
Please amend your commits instead of making new ones, with `git commit --amend`

2023-10-25 09:07 UTC, underdoeg commented
too late to ammend but I haves squashed them now

2023-10-25 09:10 UTC, deralmas requested changes
I'm a bit surprised that EGL 1.5 is still not widely supported (from what I can tell, it's a 9+ years old spec), that said, improving compatibility is very good! :)

Still, the way the version is checked is a bit redundant in some places and outright wrong in the others, so some changes are due.

2023-10-25 09:20 UTC, underdoeg commented on drivers/egl/egl_manager.cpp
> +	ERR_FAIL_COND_V_MSG(egl_version < GLAD_EGL_VERSION_1_4, ERR_UNAVAILABLE, "EGL version is too old!");
You are right, here it should be ```ERR_FAIL_COND_V_MSG(!GLAD_EGL_VERSION_1_4, ...```

2023-10-25 09:21 UTC, underdoeg commented on drivers/egl/egl_manager.cpp
> +	if (egl_version >= GLAD_MAKE_VERSION(1, 5)) {
You mean we should check for GLAD_EGL_VERSION_1_5 if we can use the newer functions.

2023-10-25 09:22 UTC, underdoeg commented
> I'm a bit surprised that EGL 1.5 is still not widely supported (from what I can tell, it's a 9+ years old spec), that said, improving compatibility is very good! :)

That is sadly very often the case with embedded arm devices. lots of manufacturers have their own OS or push Android and Debian is just an afterthought.

2023-10-25 09:28 UTC, underdoeg commented on drivers/egl/egl_manager.h
> +	int egl_version = 0;
True, I did not realize that GLAD_EGL_VERSION_1_5 was a bool but thought its a version number int. (which confused me ;) ) New commits implement a cleaner solution

2023-10-25 09:48 UTC, underdoeg commented on drivers/egl/egl_manager.cpp
> +	int egl_version = gladLoaderLoadEGL(tmp_display);
done

2023-10-25 10:47 UTC, deralmas approved these changes
Perfect, great job! Thanks for your patience!

2023-10-25 12:42 UTC, akien-mga approved these changes

2023-10-26 07:04 UTC, merged

2023-10-26 07:07 UTC, akien-mga commented
Thanks!