Fix `TabContainer` drag to rearrange issue
godotengine/godot pull request #83966
Opened 2023-10-25 20:23 UTC by kitbdev

related: #83637

`TabContainer`  was using `TabBar`'s dragging logic when drag to rearrange enabled was false.
Since it was using `TabBar`'s drag to rearrange enabled it prevented proper forwarding to `TabContainer`.

2023-10-25 22:54 UTC, YeldhamDev requested changes
A blank line separating the `if` statements from the `return`s below would nice.

Also, I wonder if there's some C++ magic that would make the `_handle_*_data()` methods from `TabBar` only accessible to `TabContainer`, as having them be completely public leaves a bit of a sour taste in my mouth. :stuck_out_tongue:

2023-10-25 23:00 UTC, KoBeWi commented
> A blank line separating the if statements from the returns below would nice.

I'd argue it's redundant here. `}` acts like a separator already.

> Also, I wonder if there's some C++ magic that would make the _handle_*_data() methods from TabBar only accessible to TabContainer

Friend class. Although not sure if it can be used without including TabContainer in TabBar.

2023-10-25 23:54 UTC, kitbdev commented
> I'd argue it's redundant here. } acts like a separator already.

I'm fine with just the `}` and no blank line. 
But if the blank lines are wanted, I could also put them `_drag_move_tab_from` and `TabBar::get_drag_data`.

> Friend class. Although not sure if it can be used without including TabContainer in TabBar.

Yeah, I wanted to avoid putting `TabContainer` in `TabBar`. 
A non-public, non-friend solution would have them be protected, and inherit a custom `TabBar` to use in `TabContainer` just to override the drag methods, but that's a lot just for drag overrides.

2023-10-26 00:20 UTC, YeldhamDev approved these changes
Oh well, it's fine then.

2023-10-26 07:04 UTC, merged

2023-10-26 07:08 UTC, akien-mga commented
Thanks!