Fix InputEventScreenDrag on Android
godotengine/godot pull request #84331
Opened 2023-11-01 22:51 UTC by Alex2782

Fixes: #84138

I haven't checked the effects on other events yet.
Event `onScroll` is not fired directly and is not so good for 'ScreenDrag': 
<details><summary>androidx.core sources</summary>

![image](https://github.com/godotengine/godot/assets/41921395/a4d26f13-f018-4932-aa8c-47fdbb5531a0)
![image](https://github.com/godotengine/godot/assets/41921395/068ddd49-1697-4835-97e7-4a238e040dc9)
</details>

**Tests**

[test-project.zip](https://github.com/godotengine/godot/files/13232340/test-project.zip)

v4.2.beta2.official [f8818f85e]

The "Drag At" and "Motion At" values are higher (the fingers have to be moved more)

https://github.com/godotengine/godot/assets/41921395/87b3e269-cd65-4cb7-babb-5be21a616f3e

**this PR:**

https://github.com/godotengine/godot/assets/41921395/5ece2845-7bad-4eaf-83fc-9d3aea736cb2

2024-02-13 23:24 UTC, m4gr3d approved these changes
The logic looks good.

Can you add comments to the added code to clarify what it does.

2024-02-13 23:49 UTC, m4gr3d requested changes
I'm seeing some scrolling artifacts when testing these changes using the Android editor; can you address them.


https://github.com/godotengine/godot/assets/914968/03bf53a9-bd3a-4e09-8720-4320e54209f5

2024-02-14 02:27 UTC, Alex2782 commented
I'll try to find time for it again in 2 or 3 days.

2024-02-20 03:26 UTC, Alex2782 commented
@m4gr3d The new solution should be better, easier to understand and probably also perform better.  I tried out various gestures with Godot Editor and checked them in Logcat. Checking 'pointerCount' is not necessary as it was in my old version.

2024-03-27 22:14 UTC, akien-mga commented
@Alex2782 Did you intend to close this? Or did you delete the branch by mistake while cleaning up?

2024-03-27 23:58 UTC, Alex2782 commented
sorry, my mistake, I didn't think it would be deleted here too.

2024-05-20 15:33 UTC, m4gr3d commented
@Alex2782 Your commit still had a few issues that I addressed in db6f1c9e2f36721d7a7f7fac17f4baebdb31615d. Can you take a look and merge the commit together if the updates look good.

2024-05-20 15:34 UTC, m4gr3d approved these changes
Approved with the updates included in db6f1c9e2f36721d7a7f7fac17f4baebdb31615d.

The commits will need to be squashed together prior to merging.

2024-05-20 15:48 UTC, akien-mga commented on platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt
> +			if(lastDragX != event.getX(0) || lastDragY != event.getY(0)) {
```suggestion
			if (lastDragX != event.getX(0) || lastDragY != event.getY(0)) {
```

2024-05-20 22:31 UTC, m4gr3d commented
@Alex2782 Looks like the rebase wasn't done properly.

2024-05-20 23:13 UTC, Alex2782 commented
Maybe now.

It still works like in the video:

https://github.com/godotengine/godot/assets/41921395/5ece2845-7bad-4eaf-83fc-9d3aea736cb2

2024-05-20 23:15 UTC, m4gr3d approved these changes
Looks good!

2024-05-20 23:30 UTC, m4gr3d approved these changes

2024-05-21 09:24 UTC, merged

2024-05-21 09:25 UTC, akien-mga commented
Thanks!