Offset Node3D position when drag and dropping
godotengine/godot pull request #84438
Opened 2023-11-04 05:23 UTC by warent

Fix https://github.com/godotengine/godot/issues/84424

2023-11-04 07:50 UTC, Calinou approved these changes
Tested locally, it works as expected.

2023-11-06 01:16 UTC, fire reviewed
Should the rotation be applied too? I think its currently identity. I’d assume axis aligned drops?

2023-11-08 08:42 UTC, akien-mga commented
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

2023-11-08 08:55 UTC, akien-mga commented
Tested locally, this seems to work when dropping 3D scenes on a scene whose root transform is the identity.

But once you start transforming the root scene, there are more (new?) issues.

For example:

Node3D scene with `(2, 0, 0)` position:
![image](https://github.com/godotengine/godot/assets/4701338/7112236a-3c46-45e7-a647-05d5952994b5)

I drag and drop a mesh scene with `(-10, 0, 0)` position:

- If I drop that scene on the position of the parent Node3D `(2, 0, 0)`, then the child instance ends up at `(-10, 0, 0)` (so -12 offset to the parent node position)
- If I drop that scene on the `(0, 0, 0)` origin of the scene, the child instance ends up at `(-12, 0, 0)`.

2023-11-08 08:58 UTC, akien-mga requested changes
See above review, this seems to introduce other issues.

2023-11-11 04:00 UTC, warent commented
Hmm good catch, apologies I should have tested this more thoroughly. I may have time to follow up on this in a week or so

2023-12-19 17:36 UTC, YuriSizov commented
@warent Will you be able to work further on this? 🙃

2024-01-10 21:22 UTC, ryevdokimov commented
> Tested locally, this seems to work when dropping 3D scenes on a scene whose root transform is the identity.
> 
> But once you start transforming the root scene, there are more (new?) issues.
> 
> For example:
> 
> Node3D scene with `(2, 0, 0)` position: ![image](https://private-user-images.githubusercontent.com/4701338/281328869-7112236a-3c46-45e7-a647-05d5952994b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTk1MjgsIm5iZiI6MTcwNDkxOTIyOCwicGF0aCI6Ii80NzAxMzM4LzI4MTMyODg2OS03MTEyMjM2YS0zYzQ2LTQ1ZTctYTY0Ny0wNWQ1OTUyOTk0YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMjA0MDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ5NTE0NTI2NzIxNzY2M2NkMDc5MzYzZTIyZDAzZjU5Y2UzMzg4MjI5NDI4MDgzZmU3NGZjN2QwNGRiZmQxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z6RxxoQiVCiatQx_oO1TBXmLhpo1vzeyENznXwHKqDg)
> 
> I drag and drop a mesh scene with `(-10, 0, 0)` position:
> 
> * If I drop that scene on the position of the parent Node3D `(2, 0, 0)`, then the child instance ends up at `(-10, 0, 0)` (so -12 offset to the parent node position)
> * If I drop that scene on the `(0, 0, 0)` origin of the scene, the child instance ends up at `(-12, 0, 0)`.
> 
> If I then add rotation and scaling of the parent node to the mix, things get even weirder.

Maybe I'm misunderstanding something, but not including the issue with rotation and scaling. Isn't this the expected behavior?

Those vectors represent the position of the instantiated scene relative to its parent node. If it's at (-10,0,0) world space, it should show as (-12,0,0) local, right?

2024-02-13 22:08 UTC, akien-mga commented
> Maybe I'm misunderstanding something, but not including the issue with rotation and scaling. Isn't this the expected behavior?
> 
> Those vectors represent the position of the instantiated scene relative to its parent node. If it's at (-10,0,0) world space, it should show as (-12,0,0) local, right? It's -12 units away from its parent (2,0,0).

My expectation is that the position of the node I'm adding as a child is a local position relative to its new parent, not a global position.

Imagine my child scene is a sidecar positioned 1m to the right of its origin. I parent it to the origin (center of gravity) of my motorbike scene. I expect it to be 1m to the right of the bike, like a sidecar would be, regardless of the world position of the bike scene.

2024-02-14 10:12 UTC, akien-mga commented
Superseded by #87126. Thanks for the contribution!

2024-02-14 10:12 UTC, closed without merging