Correct image parameter type for set_custom_mouse_cursor()
godotengine/godot pull request #84477
Opened 2023-11-05 13:23 UTC by Daniel-The-Fox

Hi there, 

the current image parameter type of `Input.set_custom_mouse_cursor()` suggest that objects of type `Image` (part of inherited  object list of `Resource`) can be passed, but this leads to an error. Instead, an `ImageTexture` object seems to be expected

The following worked for me in Godot 4.1.2, while following a tutorial on how to set a custom mouse cursor in Godot 4:
`
var _cursor_texture = ImageTexture.create_from_image(_cursor_img)
Input.set_custom_mouse_cursor(_cursor_texture, Input.CURSOR_ARROW)
`

Simply passing `_cursor_img` of type `Image` failed with the following error message:

>  e 0:00:00:0900 cursor_manager.gd:75 @ update_cursor(): condition "!texture.is_valid()" is true. <c++ source> platform/macos/display_server_macos.mm:3327 @ cursor_set_custom_image() <stack trace> cursor_manager.gd:75 @ update_cursor() cursor_manager.gd:42 @ _ready()

See also https://ask.godotengine.org/65265/problem-getting-a-portion-of-an-image, which pointed me into the right direction to solve the error. 

PS: I'm totally new to Godot, but thought I'd help to improve the docs, based on my experiences while learning Godot... :)

2023-11-05 16:15 UTC, AThousandShips requested changes
Thank you for contributing 

While this is technically correct the actual documentation can't be changed like this without changing the parameter of the actual method, which can't be done without breaking compatibility 

This is not correct

2023-11-05 18:24 UTC, Daniel-The-Fox commented
> Thank you for contributing
> 
> While this is technically correct the actual documentation can't be changed like this without changing the parameter of the actual method, which can't be done without breaking compatibility
> 
> This is the bound method:
> 
> ```c++
> void set_custom_mouse_cursor(const Ref<Resource> &p_cursor, CursorShape p_shape = Input::CURSOR_ARROW, const Vector2 &p_hotspot = Vector2());
> ```
> 
> This is not correct

Thanks for the fast feedback/response.
As I'm totally new to Godot and don't want to dig into the C++ source code of the Godot Engine any time soon, I'm not sure how to continue. How should I continue / do now? 😆

2023-11-05 18:30 UTC, AThousandShips commented
Understandable!

The current change is invalid, the type in the documentation is automatic and based on what is provided

And changing the type in c++ breaks compatibility

The approach should be to fix the code that breaks in the rendering system, instead of the input type, the specific type also isn't necessary limited to just a texture which might be why it has this type, i.e. the current type might not be a bug

So I'd say to look into the code that actually bugs, you can see the file it is in based on the error

But unfortunately the current change isn't the way to do this

2023-11-06 15:58 UTC, Daniel-The-Fox commented
> Understandable!
> 
> The current change is invalid, the type in the documentation is automatic and based on what is provided
> 
> And changing the type in c++ breaks compatibility
> 
> The approach should be to fix the code that breaks in the rendering system, instead of the input type, the specific type also isn't necessary limited to just a texture which might be why it has this type, i.e. the current type might not be a bug
> 
> So I'd say to look into the code that actually bugs, you can see the file it is in based on the error
> 
> But unfortunately the current change isn't the way to do this, and it's likely best to just close it and open a new one if you find a solution

Ok, closing this then.

2023-11-06 15:59 UTC, Daniel-The-Fox commented
Ok, closing this then as suggested...

2023-11-06 15:59 UTC, closed without merging