Fix material drop
godotengine/godot pull request #84486
Opened 2023-11-05 16:57 UTC by jcostello

My first PR :smile: 

Fixes: https://github.com/godotengine/godot/issues/74077

Explanation: When dragging over meshes with the same material (as the one dragged) and going over other mesh, material preview were reset but never assign again, causing to have a wrong state

2023-11-05 20:28 UTC, fire commented
@SaracenOne you might be interested in looking at this one.

2023-11-06 13:03 UTC, SaracenOne requested changes
Good catch! Though it doesn't quite fix it completely because the issue persists when using per-surface overrides (with the CTRL modifier).

My suggestion for fixing this fully is adding line:
`spatial_editor->set_preview_material_surface(-1);` to line 4255

And removing it from line 4274

2023-11-06 15:59 UTC, jcostello commented
@SaracenOne I applied that change. Seems to work fine

I also tried to remove the material override when `ctrl` is pressed. If there is a material override and you applied a surface override, you wont see anything because the material override is over everything. I couldn't make that change because when reseting the material, the surface information were lost because we only store the material of the last surface

2023-11-06 21:45 UTC, SaracenOne approved these changes
LGTM 👍

2024-01-04 13:29 UTC, merged

2024-01-04 13:31 UTC, akien-mga commented
Thanks!

2024-01-04 14:01 UTC, jcostello commented
@akien-mga thanks <3