disable brace mismatch hightlight in comment
godotengine/godot pull request #84606
Opened 2023-11-08 07:05 UTC by jsjtxietian

Fixes #84556

But the fix is very brute force and hard coded, let's see if there is more elegant ways.

2023-11-09 13:06 UTC, Chubercik commented
This doesn't seem to fix the issue, only one edge case:

![image](https://github.com/godotengine/godot/assets/37378746/92fa1e91-9803-42a6-becf-0c39cef640f1)

If the line doesn't start with `#` (so basically all inline comments), the issue at hand is still present:

![image](https://github.com/godotengine/godot/assets/37378746/3c78092a-02e9-4ec1-9366-071fadbe8510)

2023-11-09 13:17 UTC, Chubercik requested changes
To test if the fix works, one should consider the following checks:

1. Comment at the beginning of the line (here - passes):
```gdscript
# test)
```

2. Above example, but with an indent:
```gdscript
    # test)
```

3. An inline comment:
```gdscript
var test: int = 0  # test)
```

2023-11-09 13:19 UTC, AThousandShips commented on scene/gui/text_edit.cpp
> +									if (lineData.begins_with("//") || lineData.begins_with("#")) {
This isn't just for GDScript

2023-11-09 13:22 UTC, Chubercik commented on scene/gui/text_edit.cpp
> +									if (lineData.begins_with("//") || lineData.begins_with("#")) {
I see, fair point

2023-11-10 06:24 UTC, jsjtxietian commented
Thanks for all the suggestion!

2023-11-10 07:50 UTC, Paulb23 commented
Please take a look at my comment in #53364 the fix is quite a lot more involved then it first seems.

2023-11-10 08:47 UTC, jsjtxietian commented
Yes, the brace highlight should not exist in `TextEdit` and it needs to be moved to `CodeEdit`.

2023-12-17 16:21 UTC, closed without merging