fix: wrong get_import_options glue signature in some cases
godotengine/godot pull request #84701
Opened 2023-11-10 10:16 UTC by Lunatix89

- fixed for EditorSceneFormatImporter
 - fixed for EditorScenePostImportPlugin

fixes #84516

2023-11-10 13:10 UTC, raulsntos reviewed
Changing the signature of a virtual method breaks compatibility, but since the previous signature was unusable it's probably fine. I'll add the `breaks compat` label so we don't forget to document this.

2024-02-19 06:36 UTC, lyuma commented
Is there a relation to #81421 ? That PR is also changing `get_import_options`

> Changing the signature of a virtual method breaks compatibility, but since the previous signature was unusable it's probably fine. I'll add the `breaks compat` label so we don't forget to document this.

Can we get a more specific answer on whether or not this compatibility break is fine? I understand the old method was unusable, but my worry is if something referenced that function for whatever reason, will it crash due to changing the method declaration? (For example Rust likes to hard-depend on all functions in Godot's API)

2024-02-19 06:56 UTC, raulsntos commented
I can only speak from the C# perspective, I don't know how this affects godot-cpp or Rust.

Changing the method signature of a virtual method means that every user-defined class that implemented the method now no longer compiles. And, just like normal methods, invocations in a previously built assembly will fail to find the method and throw an exception.

If the method was previously unusable I assume nobody was overriding it, so breaking compat won't matter to implementers since there aren't any. I also think it's unlikely that users are calling these methods from user-code, Godot virtual methods are usually callbacks called by the engine so I think users calling them is rare.

That's why I think it's safe to break compat here.

2024-05-19 02:01 UTC, lyuma commented
Sorry this didn't make it into 4.3 - it is quite the gaping API hole.
Part of the issue with import options is they seem to be somewhat global and the logic in some importers can be affected by options added by other importers:

For example, try and decipher the following:
```cpp
Variant EditorSceneFormatImporterUFBX::get_option_visibility(const String &p_path, bool p_for_animation,
		const String &p_option, const HashMap<StringName, Variant> &p_options) {
	String file_extension = p_path.get_extension().to_lower();
	if (file_extension != "fbx" && p_option.begins_with("fbx/")) {
		return false;
	}
	if ((file_extension != "gltf" && file_extension != "glb") && p_option.begins_with("gltf/")) {
		return false;
	}
	return true;
}

void EditorSceneFormatImporterUFBX::get_import_options(const String &p_path,
		List<ResourceImporter::ImportOption> *r_options) {
	r_options->push_back(ResourceImporterScene::ImportOption(PropertyInfo(Variant::INT, "fbx/importer", PROPERTY_HINT_ENUM, "ufbx,FBX2glTF"), FBX_IMPORTER_UFBX));
	r_options->push_back(ResourceImporterScene::ImportOption(PropertyInfo(Variant::BOOL, "fbx/allow_geometry_helper_nodes"), false));
	r_options->push_back(ResourceImporterScene::ImportOption(PropertyInfo(Variant::INT, "fbx/embedded_image_handling", PROPERTY_HINT_ENUM, "Discard All Textures,Extract Textures,Embed as Basis Universal,Embed as Uncompressed", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), FBXState::HANDLE_BINARY_EXTRACT_TEXTURES));
}

void EditorSceneFormatImporterUFBX::handle_compatibility_options(HashMap<StringName, Variant> &p_import_params) const {
	if (!p_import_params.has("fbx/importer")) {
		p_import_params["fbx/importer"] = EditorSceneFormatImporterUFBX::FBX_IMPORTER_UFBX;
	}
}
```
Something here clearly needs to be reworked: it's probably for the best that the API is a bit broken.
Luckily, there is a workaround in the form of an even lesser-known but more powerful API:
[EditorScenePostImportPlugin.get_import_options](https://docs.godotengine.org/en/stable/classes/class_editorscenepostimportplugin.html#class-editorscenepostimportplugin-private-method-get-import-options)

2024-08-23 17:41 UTC, dsnopek commented
> Changing the signature of a virtual method breaks compatibility, but since the previous signature was unusable it's probably fine.

I agree with this. If the original signature was unusable, then breaking compat is OK, because no one could reasonably be using it.

2024-10-10 04:00 UTC, aaronfranke commented on editor/import/resource_importer_scene.cpp
> +			}
Why reimplement this code when we have `PropertyInfo::from_dict`?

2025-03-15 10:53 UTC, aaronfranke commented
@Lunatix89 Can you rebase this PR and change it to use `PropertyInfo::from_dict`?

2025-06-23 10:45 UTC, Lunatix89 commented on editor/import/resource_importer_scene.cpp
> +			}
I think I took the code fragment from `EditorImportPlugin::get_import_options` back then.
Howerver, I've changed to code to use `PropertyInfo::from_dict` now.

2025-06-23 14:05 UTC, aaronfranke reviewed
Looks good to me assuming it works and is OK from GDExtension folks. But this needs to have the API changes added to the API validation expected values. You can wait for the CI checks to finish and it will tell us what is missing.

2025-06-24 09:44 UTC, Lunatix89 commented
> Looks good to me assuming it works and is OK from GDExtension folks. But this needs to have the API changes added to the API validation expected values. You can wait for the CI checks to finish and it will tell us what is missing.

So.. I poked around here and there but don't have a clue what to do here now.
I mean, I understand the results from the validation but not how I can fix them.

2025-06-24 13:06 UTC, aaronfranke commented
@Lunatix89 The errors output by CI need to be added to the `misc/extension_api_validation/4.4-stable.expected` file.

2025-06-24 22:05 UTC, dsnopek commented
We discussed this at the GDExtension meeting, and we think this is a case where it's OK not to have a compatibility method. Since there was no way to get the data back out of the previous version, it's unclear what the compatibility code would do. And since this is a virtual method, not having a compatibility method won't lead to a crash, it just means that Godot will never call the old version of the virtual method.

2025-06-25 13:24 UTC, dsnopek commented
> And since this is a virtual method, not having a compatibility method won't lead to a crash, it just means that Godot will never call the old version of the virtual method.

Actually, I just realized this part isn't true if the GDExtension is targeting Godot 4.3 or earlier, because that was before we had compatibility hashes for virtual methods.

I think this needs to declare a compatibility method, but it doesn't need to ever actually call it. Otherwise, this bit of code will evaluate to `true` and it'll fallback on the hash-less version of the virtual method:

https://github.com/godotengine/godot/blob/30456ba095c425d5ecde320a96a763afb93bbcb0/core/object/make_virtuals.py#L238

So, I think this just needs both these pieces added:

- `GDVIRTUAL1_COMPAT(_get_import_options_compat_84701, _get_import_options, String)`
- `GDVIRTUAL_BIND_COMPAT(_get_import_options_compat_84701, "path");`

But no need to actually do `GDVIRTUAL_CALL()` on this compat method

2025-06-26 08:01 UTC, lyuma requested changes
I'd like some clarification on what this PR is fixing. The original bug this PR was made to fix was addressed by my PR #100782. Therefore, my understanding is that this change is no longer necessary in order to be able to use the EditorSceneFormatImporter APIs.

The updated documentation here explains how to use `EditorSceneFormatImporter._get_import_options`:
https://docs.godotengine.org/en/latest/classes/class_editorsceneformatimporter.html#class-editorsceneformatimporter-private-method-get-import-options
and here is the same for `EditorScenePostImportPlugin`:
https://docs.godotengine.org/en/latest/classes/class_editorscenepostimportplugin.html#class-editorscenepostimportplugin-private-method-get-import-options

The design is that the user implements `_get_import_options` and calls `add_import_option` or `add_import_option_advanced` from inside. The fact that there is no return value is by design.

I noticed the code is removing `current_option_list = r_options`, which will break existing code using `add_import_option` and `add_import_option_advanced`.  As such, if is decided to break compatibility and remove the admittedly confusing current API and replace it with a new one, we would need to obsolete + remove all of the methods which will become broken/unusable as a result of removing the `current_options_list` assignment.

2025-06-26 10:49 UTC, Lunatix89 commented
I think I'm out here, maybe someone with more insights into the API can take over.
After 1.5 years since I initially opened this PR there is just no motivation left to progress any further as I don't feel like it will ever be merged.

2025-06-26 10:49 UTC, closed without merging