Fetch theme editor items from ThemeDB
godotengine/godot pull request #84763
Opened 2023-11-11 18:15 UTC by KoBeWi

Together with #84760 fixes #82402

2024-01-12 16:23 UTC, YuriSizov commented on editor/plugins/theme_editor_plugin.cpp
> +		}
It's probably worth it to add a new method to filter by the data type and avoid excessive loops.

2024-01-12 16:26 UTC, YuriSizov approved these changes
Needs a rebase, but otherwise looks good.

Do you think we leave any performance on the table by switching from a method pointer to `get_theme_item_list`? I know this is needed for `ThemeDB` anyway, so it's fine. But I'm not well versed in C++ so curious what your take is here.

2024-01-12 16:40 UTC, YuriSizov commented on editor/plugins/theme_editor_plugin.cpp
> +		}
Looks like it's needed in https://github.com/godotengine/godot/pull/85015 as well.

2024-01-12 17:22 UTC, YuriSizov requested changes
Actually, as I was testing https://github.com/godotengine/godot/pull/84760, I realized there is something wrong will all 3 PRs. While we can use `get_class_own_items` in the docs (and in fact we should), for the theme editor, the override list, and the argument autocompletion we need to include inherited items as well.

This requires a new `get_class_items` method, which returns not just own items. Plus we need a method to get such items filtered based on the data type, as outlined above. I think one of these PRs need to do all this groundwork, and then others can be built on top of it.

Let me know if you need any help with any of that.

2024-01-31 12:30 UTC, KoBeWi commented
Updated. I added yet another argument to `get_class_items()`, which can be used to filter by type. If I were to add a new method, it would be pretty much the same, so I wanted to avoid code duplication.

2024-02-13 14:38 UTC, akien-mga approved these changes
Code changes look fine to me.

2024-02-13 16:26 UTC, merged

2024-02-13 16:34 UTC, akien-mga commented
Thanks!