Fix memory leaks in Animation mixer
godotengine/godot pull request #85001
Opened 2023-11-17 07:02 UTC by alesliehughes

2023-11-17 09:21 UTC, TokageItLab requested changes

2023-11-17 09:21 UTC, TokageItLab commented on scene/animation/animation_mixer.cpp
> +						track_value = memnew(TrackCacheValue);
```suggestion
						// If a value track without a key is cached first, the initial value cannot be determined.
						// It is a corner case, but which may cause problems with blending.
						ERR_CONTINUE_MSG(anim->track_get_key_count(i) == 0, "AnimationMixer: '" + String(E) + "', Value Track:  '" + String(path) + "' must have at least one key to cache for blending.");

						TrackCacheValue *track_value = memnew(TrackCacheValue);
```

2023-11-17 09:45 UTC, TokageItLab requested changes

2023-11-17 09:45 UTC, TokageItLab commented on scene/animation/animation_mixer.cpp
> +
```suggestion
```

2023-11-17 10:03 UTC, alesliehughes commented
I'll fix the commit up shortly. Didn't mean to create a second commit.

2023-11-17 10:33 UTC, TokageItLab approved these changes

2023-11-17 10:34 UTC, TokageItLab commented
Okay, please squash later.

2023-12-11 10:52 UTC, akien-mga commented
@alesliehughes It's not obvious to me what this does, could you add more details on what the bug is in the PR description?

2023-12-11 20:31 UTC, alesliehughes commented
> @alesliehughes It's not obvious to me what this does, could you add more details on what the bug is in the PR description?

When a animation track doesn't have an keys, it's possible that we leak memory due the ERR_CONTINUE_MSG macro usage. 

By checking the error condition first, we avoid a allocated and thus the leak.

I'll update the patch with the above.

2023-12-11 20:58 UTC, akien-mga approved these changes

2023-12-11 23:35 UTC, merged

2023-12-11 23:37 UTC, akien-mga commented
Thanks!

2024-01-25 17:39 UTC, YuriSizov commented
Cherry-picked for 4.2.2.