Fix issue with 3D scene drag and drop preview node
godotengine/godot pull request #85087
Opened 2023-11-19 13:58 UTC by EelisOtsamo

Fixes #84422

Fixes a bug with drag and dropping multiple scenes in the 3D editor. The preview node was previously being parented inside the loop that iterated over the selected files to drag, when it only had to be parented once.

2023-11-20 12:02 UTC, akien-mga approved these changes
Looks good to me.

2023-11-21 14:24 UTC, YuriSizov requested changes
This ignores the checks, which I don't think is correct. The same code existed in the canvas item editor (in fact, it was copied here from there), and the same issue was identified there. It was fixed in https://github.com/godotengine/godot/pull/15516, and I think you should do the same here.

Introduce a new bool, set it to `true` in place of the line that you've removed, and then only call `add_child` if it is set to true. You can see how it's done in the linked PR.

2023-11-24 13:48 UTC, YuriSizov approved these changes
LGTM now, thanks!

2023-12-04 22:11 UTC, merged

2023-12-05 13:33 UTC, YuriSizov commented
Cherry-picked for 4.2.1.