Adjust pick_main_scene punctuation
godotengine/godot pull request #85108
Opened 2023-11-19 22:30 UTC by theDrake

I changed all instances of the sentences shown below by splitting each of them into two sentences: a statement and a question. I think many would agree that this is clearer and "looks better" (in fact, many translators already performed this change for their respective languages, but of course I am only touching the English text).

"No main scene has ever been defined, select one?" -> "No main scene has ever been defined. Select one?"

"Selected scene '%s' does not exist, select a valid one?" -> "Selected scene '%s' does not exist. Select a valid one?"

"Selected scene '%s' is not a scene file, select a valid one?" -> "Selected scene '%s' is not a scene file. Select a valid one?"

2023-11-19 22:49 UTC, AThousandShips requested changes, later dismissed

2023-11-19 22:49 UTC, AThousandShips commented on editor/translations/editor/ar.po
The translation files should not be changes, please revert this

2023-11-19 23:00 UTC, AThousandShips commented
Thank you for your contribution

> I think many would agree that this is clearer and "looks better"

I don't think I do, and this will invalidate any translations already done because of how translation syncing and linking works, so I don't think this is a change that is worth it, we prefer to avoid minor, nitpick changes to text that is translated because it is mostly a matter of personal preference and has an impact on the translations

2023-11-20 01:16 UTC, theDrake commented
Please pardon me for being a bit more blunt, but I think "No main scene has ever been defined, select one?" as a single sentence is downright bad (or at least unprofessional) English and I found it quite jarring the first time I saw it. That's why I consider this change (somewhat) important: things like that affect an engine's professional image and this text is likely to be seen early on by newcomers. Having said all that, I concede that such a change isn't "essential" and will understand if the final decision is to simply close this PR.

As for translations, this certainly doesn't _need_ to affect them in any way, especially since, as I indicated, you can see within the translation files that many translators already chose to change the comma to a period (or equivalent punctuation) anyway. If the "syncing and linking" you refer to involves the English text within those translation files, that's one of the reasons I included changes to all those lines of English text. But of course I'm not yet familiar with how all of this repo's pieces and processes interrelate, nor how it interrelates with other systems such as Weblate, so if this would trigger processes that would be deemed too troublesome then, once again, I can understand if the final decision is to close this PR.

2023-11-20 08:27 UTC, AThousandShips commented
> As for translations, this certainly doesn't need to affect them in any way, especially since, as I indicated, you can see within the translation files that many translators already chose to change the comma to a period (or equivalent punctuation) anyway

That's not the point here, the translations are synced with the English text, I'm not sure but I don't think it allows matching against *any* change to the English text, so this change means these texts have to be re-translated

> If the "syncing and linking" you refer to involves the English text within those translation files, that's one of the reasons I included changes to all those lines of English text.

I understand but the translation files cannot and should not be changed like this, they are strictly only updated by syncing with the webplate

Again I consider this a matter of preference and style and isn't a matter of absolute grammar rules AFAIK. And while this change could be considered an improvement, it has to be weighed against the impact of it, which is my entire point, my personal opinion on whether it is better or not is not the main point here, and we can discuss the finer points of grammar and professionality (though I think you are exaggerating the unprofessional aspect of the current wording), and tbh it's *more* unprofessional to potentially erase the translation of an important segment of text if that is in fact how it works

Again, I don't know for certain that the translation is wiped out, but that's what I recall from how it works

So the first step would be to remove the incorrectly changed translation files, and then get an opinion from someone who knows more of the details about the way the translation linking works

2023-11-20 11:20 UTC, akien-mga commented
> That's not the point here, the translations are synced with the English text, I'm not sure but I don't think it allows matching against _any_ change to the English text, so this change means these texts have to be re-translated

The translations won't be wiped out. Gettext does fuzzy matching, and identifies that the new string is close to the old one and thus will preserve the translations. It will mark them as `fuzzy`, which means that they need to be re-checked by translators (e.g. if they notice the change, they can also change the comma to a period).

We do not use `fuzzy` translations in production as the fuzzy matching is broad and often leads to nonsensical translations, so translators would need to review those strings anyway.

So doing such a change is ok if it's done early on in a release cycle, to give translators enough time to catch up.

2023-11-20 12:19 UTC, AThousandShips commented
To clarify: Do we either keep all the different translation strings from the different supported versions like 4.0 and 4.1, or have them as separate translation sources, so that this change doesn't affect the original wording in those versions? Even if the translators can update the changes for 4.2

2023-11-20 21:55 UTC, theDrake commented
I amended the commit to remove changes to translation files.

2023-11-22 22:04 UTC, theDrake commented
FWIW, the issue at hand is referred to as a **comma splice** (joining two independent clauses with a comma) and here are relevant quotes from, respectively, the [Wikipedia](https://en.wikipedia.org/wiki/Comma_splice) and [Grammarly](https://www.grammarly.com/blog/comma-splice/) articles on the topic:

> The comma splice is sometimes used in literary writing to convey a particular mood of informality. It is usually considered an error in English writing style. Some authorities on English usage consider comma splices appropriate in limited situations, such as informal writing or with short similar phrases.

> You should avoid comma splices in formal writing, but now that you know the rule, you can sometimes break it in more artistic types of writing.

2024-08-20 04:16 UTC, theDrake commented
Godot 4.3 is absolutely beautiful! And yet, the comma splices addressed by my PR persist:
![image](https://github.com/user-attachments/assets/054e2d7d-ea4b-419c-a2c7-f8b678a84d1e)

2024-08-20 05:30 UTC, akien-mga approved these changes

2024-08-20 08:06 UTC, merged

2024-08-20 08:09 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: