OpenGL: Implement rendering of lightmaps
godotengine/godot pull request #85120
Opened 2023-11-20 03:44 UTC by dsnopek

This PR aims to add rendering of lightmaps (via `LightmapGI`) when using the GL Compatibility renderer.

**Note: This doesn't add lightmap baking when using the GL Compatibility renderer. Lightmaps still need to be baked using Vulkan.**

This marked as a draft because while it's "working", the result looks much worse than I'd expect. :-) I want to see if I can get to the bottom of that first.

2023-11-20 13:40 UTC, dsnopek commented
FYI, here's some images of the visual differences...

**Compatibility:**
![Selection_093](https://github.com/godotengine/godot/assets/191561/b1d56d72-306d-4379-91a8-0060904ec47e)

**Mobile:**
![Selection_094](https://github.com/godotengine/godot/assets/191561/a60af654-ec7f-4124-9de0-bc83f01cd1fe)

In both, you can see some "lines" by the edges of the triangles, but it's much more noticeable on the Compatibility renderer, and the light seems dimmer overall. 

I'm surprised that the difference is so big (at least relatively speaking) given that it's the exact same lightmap (it was baked with the editor using the Mobile renderer) and the exact same shader math (I copy-pasted it from the Mobile renderer).

Any advice would be appreciated!

2023-11-20 15:11 UTC, Calinou commented
> In both, you can see some "lines" by the edges of the triangles, but it's much more noticeable on the Compatibility renderer, and the light seems dimmer overall.

This is due to sRGB vs linear rendering. The lines are due to Godot 4.x not supporting bicubic sampling in lightmaps yet (unlike Godot 3.x where it's present and enabled by default).

2023-11-20 15:26 UTC, dsnopek commented
@Calinou Ah, thanks!

2023-11-20 16:56 UTC, Calinou requested changes
Tested locally, it mostly works as expected.

One issue is that light sampling for all light types isn't skipped on meshes that use the Static global illumination mode and have had lightmaps baked on them. This is done by design when using Forward+ and Mobile to avoid double lighting and improve performance.

Forward+ | Mobile | Compatibility
-|-|-
![Screenshot_20231120_175447](https://github.com/godotengine/godot/assets/180032/fc4c2c79-fa9e-4d42-ba2a-d1b6ebf71ada) | ![Screenshot_20231120_175505](https://github.com/godotengine/godot/assets/180032/44d23afc-423f-4cac-8d80-13561acde805) | ![Screenshot_20231120_175456](https://github.com/godotengine/godot/assets/180032/6a9b9338-172e-4d7d-9d4a-d1ed56f6daae)

Dynamic object lighting also appears to not influence the object enough compared to other rendering methods. (The torus on the front uses the Disabled GI mode, while the torus on the back uses the Dynamic GI mode.)

2023-11-20 23:03 UTC, dsnopek commented
@Calinou Thanks for the feedback!

> One issue is that light sampling for all light types isn't skipped on meshes that use the Static global illumination mode and have had lightmaps baked on them.

I think this is fixed in my latest push.

It got kind of messy, because there's just so many ways a light can be rendered, so there needed to be checks in a whole bunch of places.

Also, I had to add 16 bytes to the `LightData` struct , because there wasn't any spare padding to use. This isn't ideal, but if we were going to add anything else to that struct in the future, then we would have hit this eventually, and now there's a whole bunch of padding for those future things to use. :-)

2023-11-21 11:46 UTC, Calinou approved these changes
Tested locally, it works as expected. Light shadow sampling for static lights is now skipped on lightmapped surfaces, which brings performance up from 1600 FPS to 2000 FPS in 4K on a RTX 4090 in the testing project linked above.

2023-11-22 19:05 UTC, AThousandShips approved these changes

2023-11-22 19:05 UTC, AThousandShips commented on drivers/gles3/storage/light_storage.cpp
> +		return; //nothing could be done
```suggestion
		return; // Nothing could be done.
```

2023-11-22 19:05 UTC, AThousandShips commented on drivers/gles3/rasterizer_scene_gles3.cpp
> +						if (!(inst->lightmap_instance.is_valid() && GLES3::LightStorage::get_singleton()->light_get_bake_mode(light) == RenderingServer::LIGHT_BAKE_STATIC)) {
```suggestion
						if (!inst->lightmap_instance.is_valid() || GLES3::LightStorage::get_singleton()->light_get_bake_mode(light) != RenderingServer::LIGHT_BAKE_STATIC) {
```
I find `!(...)` harder to read, would suggest making the negation not as easy to overlook

2023-11-22 19:05 UTC, AThousandShips commented on drivers/gles3/rasterizer_scene_gles3.cpp
> +						if (!(inst->lightmap_instance.is_valid() && GLES3::LightStorage::get_singleton()->light_get_bake_mode(light) == RenderingServer::LIGHT_BAKE_STATIC)) {
```suggestion
						if (!inst->lightmap_instance.is_valid() || GLES3::LightStorage::get_singleton()->light_get_bake_mode(light) != RenderingServer::LIGHT_BAKE_STATIC) {
```

2023-11-22 19:19 UTC, Calinou commented on drivers/gles3/shaders/scene.glsl
> +		uvw.z *= 4.0; //SH textures use 4 times more data
By the way, these comment styling issues are also present in `scene_forward_clustered.glsl` and `scene_forward_mobile.glsl`.

2023-11-22 20:16 UTC, dsnopek commented on drivers/gles3/shaders/scene.glsl
> +		uvw.z *= 4.0; //SH textures use 4 times more data
Yep, I copy-pasted this code form `scene_forward_mobile.glsl` :-)

2023-11-22 20:21 UTC, dsnopek commented on drivers/gles3/shaders/scene.glsl
> +		uvw.z *= 4.0; //SH textures use 4 times more data
Thanks for the review!

I applied this suggestion and all the others in my latest push.

2023-12-04 23:53 UTC, clayjohn reviewed
Just some little shader nitpicks. 

When running the scene from Calinou, I am getting a totally black mesh. Looking into it with a debugger now

_edit: there is nothing obviously wrong. But the shader has disabled all the lights for some reason despite lights touching the mesh._

_This is what I am seeing_
![image](https://github.com/godotengine/godot/assets/16521339/618f0e74-b7dd-4a00-b2c0-444d17d374c8)

2023-12-04 23:53 UTC, clayjohn commented on drivers/gles3/shaders/scene.glsl
> +	uint bake_mode;
```suggestion
	lowp uint unused;
	lowp uint bake_mode;
```

2023-12-04 23:53 UTC, clayjohn commented on drivers/gles3/shaders/scene.glsl
> +	uint bake_mode;
```suggestion
	lowp vec3 pad;
	lowp uint bake_mode;
```

2023-12-05 00:10 UTC, dsnopek commented on drivers/gles3/shaders/scene.glsl
> +	uint bake_mode;
Thanks, updated! The next one too

2023-12-05 00:12 UTC, dsnopek commented
> When running the scene from Calinou, I am getting a totally black mesh. Looking into it with a debugger now
>
> edit: there is nothing obviously wrong. But the shader has disabled all the lights for some reason despite lights touching the mesh.

That really weird :-/

I just recompiled (after making the suggested `lowp` changes) and re-tested with Calinou's scene, and it's still working for me.

I'm not sure what could be the difference. I'm on Linux with an nvidia card. What's your environment like?

2023-12-05 00:17 UTC, clayjohn commented
> I'm not sure what could be the difference. I'm on Linux with an nvidia card. What's your environment like?

On linux with an intel integrated GPU

2023-12-05 00:18 UTC, clayjohn commented
Okay, some progress. It looks like UV2s are disabled for some reason 
![image](https://github.com/godotengine/godot/assets/16521339/1170aa00-50e8-4e6b-8b98-bcfc4e6a89b6)

2023-12-05 00:24 UTC, dsnopek commented
> I've been rebasing on master, so maybe something upstream unintentionally broke this

Ah, I just tried rebasing on master, and now I'm seeing what you're seeing too.

2023-12-05 00:30 UTC, clayjohn commented
Diff with the fix:
```
diff --git a/drivers/gles3/rasterizer_scene_gles3.cpp b/drivers/gles3/rasterizer_scene_gles3.cpp
index 90440d6b73..18d4ae3562 100644
--- a/drivers/gles3/rasterizer_scene_gles3.cpp
+++ b/drivers/gles3/rasterizer_scene_gles3.cpp
@@ -2773,12 +2773,16 @@ void RasterizerSceneGLES3::_render_list_template(RenderListParameters *p_params,
 
                        GLuint vertex_array_gl = 0;
                        GLuint index_array_gl = 0;
+                       uint64_t vertex_input_mask = shader->vertex_input_mask;
+                       if (inst->lightmap_instance.is_valid()) {
+                               vertex_input_mask |= 1 << RS::ARRAY_TEX_UV2;
+                       }
 
-                       //skeleton and blend shape
+                       // Skeleton and blend shapes.
                        if (surf->owner->mesh_instance.is_valid()) {
-                               mesh_storage->mesh_instance_surface_get_vertex_arrays_and_format(surf->owner->mesh_instance, surf->surface_index, shader->vertex_input_mask, vertex_array_gl);
+                               mesh_storage->mesh_instance_surface_get_vertex_arrays_and_format(surf->owner->mesh_instance, surf->surface_index, vertex_input_mask, vertex_array_gl);
                        } else {
-                               mesh_storage->mesh_surface_get_vertex_arrays_and_format(mesh_surface, shader->vertex_input_mask, vertex_array_gl);
+                               mesh_storage->mesh_surface_get_vertex_arrays_and_format(mesh_surface, vertex_input_mask, vertex_array_gl);
                        }
 
                        index_array_gl = mesh_storage->mesh_surface_get_index_buffer(mesh_surface, surf->lod_index);
```

2023-12-05 00:35 UTC, dsnopek commented
Thanks so much! Your patches fixes it in my testing too, so I've rebased, added your patch and pushed.

2023-12-05 00:41 UTC, clayjohn approved these changes
Looks good to me! Tested locally with Calinou's test project and I can confirm it now works.

2023-12-08 14:29 UTC, merged