Prefer identifiers annotated type if assigned type is incompatible to it
godotengine/godot pull request #85224
Opened 2023-11-22 15:46 UTC by HolonProduction

Fixes #74888 (partially)

A small self contained example demonstrating the problem:
```
func _ready():
    var a: String = 1
    a. # no string methods are suggested
```

Obviously the example isn't valid GDScript, but in more complex situations like #74888 the incompatible assignment might result from an issue with interfering the type of the assignment which might still be valid at runtime. In such cases we should respect the type that the user specified.

Implementation detail:
- If there are any ideas to prevent changing the analyzer without copying the over hundred line long function I'm all in for it.

2024-01-17 12:19 UTC, vnen approved these changes
LGTM

2024-01-17 12:42 UTC, vnen requested changes

2024-01-17 12:42 UTC, vnen commented on modules/gdscript/gdscript_analyzer.cpp
> +	}
Actually, since this is only relevant if there is a source node, I think the `p_source_node` check should be the outermost one.

2024-01-24 12:43 UTC, vnen approved these changes
LGTM. Sorry for the delay in reviewing it

2024-01-24 12:46 UTC, YuriSizov commented
Should we consider https://github.com/godotengine/godot/pull/78929 superseded?

2024-01-24 13:14 UTC, merged

2024-01-24 13:17 UTC, YuriSizov commented
Thanks!