Implement LightmapGI shadowmasks
godotengine/godot pull request #85653
Opened 2023-12-02 11:30 UTC by BlueCube3310

Salvages #77284
Implements https://github.com/godotengine/godot-proposals/issues/2354

Adds support for baked shadowmasks to LightmapGI. The shadowmasks are then saved as compressed images and applied on top of the dynamic shadowmaps. 

Progress:
- [x] Support baking shadowmasks,
- [x] Support Forward+ renderer,
- [ ] Support Mobile renderer,
- [ ] Allow lightmaps without shadowmasks,
- [ ] Blend seams and denoise,
- [ ] Fix shadow acne,
- [ ] Add a `shadowmask_reesolution_ratio` property,
- [ ] Document everything properly.

Features outside the scope of this PR, but still would be nice to have:
- Import grayscale textures as L8 uncompressed and RGTC_R compressed,
- Filter the shadowmasks in the Lightmapper,

2023-12-06 21:31 UTC, Calinou reviewed
Tested locally, it mostly works as expected.

**Testing project:** [test_lightmapgi_mobile.zip](https://github.com/godotengine/godot/files/13591806/test_lightmapgi_mobile.zip)

The way shadowmask interacts with real-time shadows looks strange. I don't recall this happening with previous PRs, but maybe I started noticing this issue just now. This is most noticeable with **Directional Soft Shadow Filter Quality** set to **Ultra**, but it occurs with any setting:

![image](https://github.com/godotengine/godot/assets/180032/3040b276-83fd-44ec-89b1-234209046049)

I'd expect the final shadow color to be `min(shadowmask, real_time_shadowmap)`. Right now, it seems to be `real_time_shadowmap > 0.0 ? real_time_shadowmap : shadowmask`. This issue affects both Forward+ and Mobile.

If you set **Directional Soft Shadow Filter Quality** to **Hard**, notice how shadowed area transitions look much sharper than intended:

![image](https://github.com/godotengine/godot/assets/180032/74cc3f76-a468-4881-b2ae-a15fc00d5011)


Regarding fixing seams, I'd say it's worth the effort as right now, seams can be quite noticeable in the distance:

Real-time shadow | Shadowmask
-|-
![Screenshot_20231206_222718](https://github.com/godotengine/godot/assets/180032/4d9d159e-ebd3-4b24-b5d7-3b5f73a70689) | ![Screenshot_20231206_222726](https://github.com/godotengine/godot/assets/180032/97357d22-eb94-4542-b9d1-037035cb9797)

2023-12-07 23:41 UTC, bitsawer commented on modules/lightmapper_rd/lm_compute.glsl
> +void trace_direct_light(vec3 p_position, vec3 p_normal, uint p_light_index, bool p_soft_shadowing, out vec3 r_light, out vec3 r_light_dir, out float r_shadow, inout uint r_noise) {
`r_shadow` is an `out` parameter, but the function can return early without writing to it, in which case its value will be undefined when used later in the calling function. It should have a valid value in all code paths, for example `r_light` initializes its default value at the start of the function to make sure it always has a valid value.

2024-01-17 18:24 UTC, YuriSizov commented
Could you please rebase on the current master? We had an issue with macOS builds which failed your CI.

2024-01-23 20:27 UTC, BlueCube3310 commented
> The way shadowmask interacts with real-time shadows looks strange. I don't recall this happening with previous PRs, but maybe I started noticing this issue just now. This is most noticeable with **Directional Soft Shadow Filter Quality** set to **Ultra**, but it occurs with any setting:
> 
> Regarding fixing seams, I'd say it's worth the effort as right now, seams can be quite noticeable in the distance:

Both of these issues should be fixed now.

2024-01-24 23:23 UTC, Calinou commented
> Both of these issues should be fixed now.

It works great now, thanks :slightly_smiling_face:

2024-02-03 08:25 UTC, atirut-w commented
Having combined realtime and static shadows probably isn't a very good idea especially with automatically wrapped UV2s:

<details><summary>Image</summary>
<p>

![image](https://github.com/godotengine/godot/assets/25323231/130b03c9-550f-45fe-9fd3-a26b61103fc8)

</p>
</details> 

The quality becomes even worse if your light have it's size or angular dist set to more than 0:

<details><summary>Image</summary>
<p>

![image](https://github.com/godotengine/godot/assets/25323231/1b0c3e13-6bea-4827-8387-2f8f4d121736)

</p>
</details> 

On another note, I have a version of GDQuest's TPS demo with lightmaps and this PR breaks shadow on everything for some reason. I yet to encounter this on other projects.

2024-02-03 08:29 UTC, atirut-w commented
Also, could this method be adapted to static lights to give them specular reflections?

2024-02-03 17:12 UTC, Calinou commented
> Having combined realtime and static shadows probably isn't a very good idea especially with automatically wrapped UV2s. It should definitely be opt-in.

Once [bicubic sampling is reimplemented](https://github.com/godotengine/godot/pull/77912), this will be much less of an issue as the shadowmask will be much smoother.

2024-02-04 03:33 UTC, atirut-w commented
> Storing light direction requires much more memory than shadow information, which fits in a R8 texture.

A sort of semi-realtime mode, maybe? Baked shadows with realtime specular reflections? It sounds nice to have, but I'm not sure how practical that would be.

2024-02-10 10:09 UTC, atirut-w commented
Feedback/issue: light size/angular distance is not being taken into account

Also, if done right, this PR could help make #63610 less impacting.

2024-02-10 18:13 UTC, Calinou commented
> Feedback/issue: light size/angular distance is not being taken into account

The GPU lightmapper takes these parameters into account since https://github.com/godotengine/godot/pull/62054. When I tested this PR, it worked correctly on shadowmasks too.

2024-02-11 01:12 UTC, atirut-w commented
This PR apparently doesn't use the same code as #62054. This is what a directional light with angular dist of 5 looks like:

![image](https://github.com/godotengine/godot/assets/25323231/80b9d51e-b34b-4b92-8667-aac51767b07e)

2024-02-11 19:12 UTC, BlueCube3310 commented
> Old version
> 
> Oops, yeah. My testing scenarios didn't try to exaggerate the soft shadows enough. By the way, are shadowmaps not denoised?
> 
> 
> Addendum: will this PR get support for light types other than directional?

Rebased, now shadows are denoised + other light types can be baked, although that feature is very experimantal.

2024-02-13 16:49 UTC, Calinou commented
The denoising seems to work well from my testing.

Baking omnilights into a shadowmask seems broken currently:

![image](https://github.com/godotengine/godot/assets/180032/460c2355-b06b-4d33-9e4c-109f7e8f45d4)

Compare this to when you get closer and real-time shadows appear:

![image](https://github.com/godotengine/godot/assets/180032/e26e18e6-d0bc-46e4-86d8-befcac49cdb3)

Remember that baking more than one light in a shadowmask requires switching the texture to RGBA8 (supports 4 intersecting lights at once), which will require more memory and storage. That's why I generally consider positional light shadowmasks to be not worth the trouble, especially since positional light shadows have infinite distance by default (unless you opt into distance fade).

2024-04-19 10:09 UTC, WickedInsignia commented
This feature works especially well when shadowmasks are never drawn over shadowmaps but instead replace them at a certain distance. This allows for more efficient shadowmap settings with a much lower max distance than would usually be necessary, while also providing rudimentary shadowing to faraway scenery. This is present as Distance Shadowmask in Unity and also exists in Unreal.
Insurgency Sandstorm uses this technique very effectively.
I'm fairly certain Counter Strike 2 overlaps its shadowmasks with shadowmaps, but use a fairly high-resolution bake to avoid too much of a discrepancy in quality.

Optimally users would have the option to either:
- Replace shadowmaps with shadowmask at a specific distance
- Overlap shadowmaps and shadowmasks together
- Use only shadowmasks if desired

2024-06-02 19:14 UTC, BlueCube3310 commented
The different shadowmask blending modes are now available: None, Replace, Overlay and Only. Currently these properties can be tweaked by individual lightmap nodes (and therefore the instances they affect) in the scene, but this may change in the future.

2024-06-03 21:56 UTC, SpockBauru commented
Tested the windows artifact. Results are quite good!

Tested on an roughly 1km² map with lightmaps at 4096 resolution (about 4 samples per meter).
To amplify the effect, the shadow distance was reduced to only 20 meters.

 Here the test scene:
[Shadowmap_Test.zip](https://github.com/user-attachments/files/15539914/Shadowmap_Test.zip)
 
Shadowmap modes are working as expected:
![Shadowmask_None](https://github.com/godotengine/godot/assets/67930504/317b831e-7333-4d3a-b473-3b84d1760394)
![Shadowmask_Replace](https://github.com/godotengine/godot/assets/67930504/f809194a-b4bd-45f0-bb9d-acaa9d4372a2)
![Shadowmask_Overlay](https://github.com/godotengine/godot/assets/67930504/79c63504-79aa-4068-acee-f27b27b100a1)
![Shadowmask_Only](https://github.com/godotengine/godot/assets/67930504/1d0f1aef-8323-4ce0-bce2-61c2a5e30d25)

Here a video comparison, since GitHub only allows up to 10MB the quality is reduced:


https://github.com/godotengine/godot/assets/67930504/2e811203-a220-4a47-a9de-b6330f6659e0

Finally, my classic tunnel comparison:

https://github.com/godotengine/godot/assets/67930504/ab2c0473-44b9-4aeb-8921-eadaf79505c0

Overall, everything seems to be working as expected. Excellent job everyone! \o/

2024-06-04 02:08 UTC, atirut-w commented
That's an awful amount of duped texts in the enum docs you suggested, imo.

2024-06-04 10:48 UTC, BlueCube3310 commented
Added the docs, Compatibility should also work now.

2024-06-04 12:00 UTC, WickedInsignia commented
Works well on directional lights in my brief checks. A couple considerations:
- Spotlights and Omni lights are unaffected. It can be useful to replace these with Shadowmask entirely for performance reasons when shadows are needed for many static sources. Maybe a new bake mode for these called "Shadowmask and Indirect" could be added? Then whatever is set in the Lightmap node only affects Directional. Not sure about UX consistency with that so might require more thought/discussion.
- Shadowmask data is saved to a separate PNG correct? We might want to allow for separate texel density between Lightmap/Shadowmask (and Directional if possible). Bakery allows the user to define a fraction for each of these (so Directional maps can use 1/2 the texel density or less of the main Lightmap to save space). Adjusting Shadowmask resolution independent of the main Lightmap is important depending on how it's used (Only will require more resolution than Replace, for example).

2024-06-04 14:38 UTC, SpockBauru commented
Found some interesting things on compatibility render. This PR seems to be working correctly but there are additional issues that I believe are unrelated.

## This PR
Tested the windows artifact. Docs are a bit verbose but they are working:
![image](https://github.com/godotengine/godot/assets/67930504/158af158-2180-4659-a345-0ec8fea881b6)

Tested the 4 Shadowmask Modes (None, Replace, Overlay, Only). Every one seems to be working as expected. Good job!

## Additional Issues on Compatibility Renderer (Probably unrelated)
Found some additional issues regarding LightmapGI and Shadowmask on the Compatibility Renderer. I think they are not related to this PR but will let here for reference. Maybe they need their own issue but I'm not sure.

### (Docs) LightmapGI
On the Compatibility Renderer, LightmapGI Node shows a warning saying that Lightmaps cannot be baked on devices that not support **RD Backends**, which is confusing because most people (including me) have no idea what this means and since is a warning it leads to understand that the compatibility render will not bake at all. A bit of clarification is needed, or even better: Detect if these whatever backends are supported and not show a warning at all. (warnings are scary)
![image](https://github.com/godotengine/godot/assets/67930504/09d7a7b3-54ec-488a-b41a-170d564ea1f8)

### (Bug) Shadowmaps
Distant hills that project shadows near the camera on other renderers does not show on compatibility renderer. Take a look on the mountain shadow at right:

![Shadowmap_Bug](https://github.com/godotengine/godot/assets/67930504/3f74d604-3944-4cc4-8fb6-77876cb419ab)


This seems to be just a detail on the picture, but while moving is pretty distracting.

https://github.com/godotengine/godot/assets/67930504/3b276ae8-1fd5-44ed-92ee-43e61c0f3c99

The same scene on Forward+ shows the entire shadow, and clips at the desired distance (20m):

![image](https://github.com/godotengine/godot/assets/67930504/87c0cbe6-f324-4c40-8fbb-b5ec167654c7)

2024-06-04 20:54 UTC, Calinou commented
> A bit of clarification is needed, or even better: Detect if these whatever backends are supported and not show a warning at all.

Unfortunately, performing this check is slow so we can't do it every time `_get_configuration_warnings()` is shown.

Personally, I'd get rid of the warning entirely, except on the web platform as it only supports Compatibility.

2024-08-21 10:04 UTC, BlueCube3310 commented
Bicubic sampling and aliasing fixes are now supported after #89919 and #95828.

2024-08-21 15:41 UTC, SpockBauru commented
Made a quick test on the Windows fragment and overall got almost the same results from [my previews test](https://github.com/godotengine/godot/pull/85653#issuecomment-2146194388). The only visual difference is that edges are better filtered :D
![shadowmask_replace](https://github.com/user-attachments/assets/a29fb4d3-8889-4072-8f8f-4a8e6d98b90b)

Also tested on Forward+, Mobile and Compatibility renderers. There are some issues, but they are not related to this PR and should have their own issue (some [already do](https://github.com/godotengine/godot/issues/84846)).

I believe that this PR is in a good shape and **can be merged as it is now**. Future improvements can be added later.

Excellent job everyone!

2024-08-21 16:39 UTC, BlueCube3310 commented
I think this is mostly done, it just needs some optimizations + testing on different hardware (especially VR - multiview is probably broken on Compatibility, though I can't test it locally).

2024-08-22 02:16 UTC, Calinou commented
> especially VR - multiview is probably broken on Compatibility, though I can't test it locally

There's a Viewport property you can use to force XR-style rendering regardless of whether you have an HMD connected. Its variable rate shading property can also be set to XR for a similar effect (the VRS project setting affects the root viewport).

2024-08-29 14:01 UTC, BlueCube3310 commented
The documentation is now slightly shorter, a configuration warning is shown when attempting to use a shadowmask without one existing, and some rendering fixes for Compatibility.

2024-08-29 14:04 UTC, BlueCube3310 commented
The only big issue left is how shadowmasks should interact with directional lights. Currently when several lights are present, the shadowmask's opacity or visibility will depend on the last light's properties.

2024-09-06 20:39 UTC, Calinou commented
> The only big issue left is how shadowmasks should interact with directional lights. Currently when several lights are present, the shadowmask's opacity or visibility will depend on the last rendered light's properties.

I'd print a warning on bake if multiple directional lights are detected when shadowmasking is enabled, and print the node name of the light that was taken into account for the shadowmask.

2024-09-07 18:52 UTC, BlueCube3310 commented
> > The only big issue left is how shadowmasks should interact with directional lights. Currently when several lights are present, the shadowmask's opacity or visibility will depend on the last rendered light's properties.
> 
> I'd print a warning on bake if multiple baked directional lights are detected when shadowmasking is enabled, and print the node name of the light that was taken into account for the shadowmask.
> 
> You could also try to pick the one that has the brightest effective energy (`(color * energy).get_v()`), since its shadows will be the most visible.

The first suitable light found is now used for the shadowmask.

2024-09-08 09:22 UTC, BlueCube3310 commented
OIDN works correctly now, I think this PR is finally ready for review

2024-09-24 15:20 UTC, Calinou reviewed
Tested locally, it works as expected.

One remaining issue I found is that when you set the shadowmask mdoe to **None** and bake lightmaps again, the shadowmask source texture isn't removed from the filesystem (unlike what the description implies).

Another issue is that in Compatibility, DirectionalLight3D's **Blend Splits** doesn't work correctly with the last split when the LightmapGI shadowmask mode is **Overlay**:

![image](https://github.com/user-attachments/assets/8f889d3a-e453-4f4e-bda7-f7b703d6536a)

With all rendering methods, dynamic object shadows are not rendered (even up close) when using the **Only** shadowmask mode, even though I'd expect them to appear:

Replace | Only
-|-
![image](https://github.com/user-attachments/assets/c8be97ed-3752-445b-bd04-073a5d7a18fe) | ![image](https://github.com/user-attachments/assets/4ef85c32-e0e0-45bf-a5d8-7a49e678c6c4)


In comparison, this works with the **Replace** and **Overlay** shadowmask modes.

Also, it was suggested during a recent rendering meeting that the shadowmask texel scale should be adjustable separately from the lightmap texel scale, so that your shadowmask can be more detailed than the lightmap. This can be important if you only bake indirect light, as indirect light data is low-frequency but the shadowmask can be higher-frequency.

2024-09-24 22:04 UTC, BlueCube3310 commented
> * When you set the shadowmask mdoe to **None** and bake lightmaps again, the shadowmask source texture isn't removed from the filesystem (unlike what the description implies).

I'm not sure whether this should be the correct behavior, I intended the docs to imply that the reference to the texture would be removed so it doesn't get loaded. Though it may be better from the user's perspective to delete it, since it will get overwritten anyway on subsequent bakes.

>* With all rendering methods, dynamic object shadows are not rendered (even up close) when using the **Only** shadowmask mode, even though I'd expect them to appear:
> 

I'm not certain how to approach this, currently all real-time shadows are ignored in the shader when an object has an 'Only' shadowmask. One way would be to only disable shadow casting for static objects with a shadowmask, but that would mean they wouldn't also cast shadows onto dynamic ones. The shadows of static and dynamic objects are combined, so it's not possible to tell which ones are cast by the dynamic ones.

2024-09-26 09:02 UTC, SpockBauru commented
> * With all rendering methods, dynamic object shadows are not rendered (even up close) when using the **Only** shadowmask mode, even though I'd expect them to appear:

This is not what I would expect for a mode called "Only". I think it can be added as a new mode after the merge, maybe something like "static + dynamic".

This is a big PR and is in a good shape, there’s no need to keep overthinking it. New features can always be added later. Please, consider merge before we miss the window of opportunity ^_^

2024-09-26 09:32 UTC, pineapplemachine commented
Seconding @SpockBauru. Not having shadow masks in any form currently makes Godot's baked shadows impractical for a lot of projects, forcing those projects to accept the performance cost of real-time shadows for static geometry only in order to have acceptable shadows for dynamic geometry. This feature is currently a major blocker for optimizing performance in 3D games and supporting lower-end platforms with Godot without sacrificing shadows entirely. In my opinion, getting this merged in at least a basically usable form ought to be a very high priority.

2024-09-26 10:28 UTC, mrjustaguy commented
Eh, correct me if I'm wrong, but wouldn't you still need to render static objects in the shadow map for dynamic objects to be able to get statically cast shadows?

2024-09-26 13:24 UTC, atirut-w commented
> Eh, correct me if I'm wrong, but wouldn't you still need to render static objects in the shadow map for dynamic objects to be able to get statically cast shadows?

I've also initially thought about this, but we can't separate the two because they render into the same shadow map AFAIK. This means that if static objects both receive shadows and use static shadowmap, they could potentially look *wrong* due to getting both dynamic and static shadows.

This is why most engines have the **Only** mode not cast dyanmic shadows onto static objects, and **Replace** mode for when you need that to work where static shadows are only rendered outside of dynamic shadow's range.

2024-10-30 15:21 UTC, SpockBauru commented
Updated my MRP to the latest windows fragment:
[shadowmask_test.zip](https://github.com/user-attachments/files/17575152/shadowmask_test.zip)

I'm getting flickering issues while in movement in Forward+ rendering. This does not happens on Mobile or Compatibility:


https://github.com/user-attachments/assets/839283b3-63bb-4b28-832d-a2e110380da5

2024-10-30 16:59 UTC, marcinn commented
I see no flickering on my setup.
I'm noticing that opacity is always 1.0 for shadowmask=overlay (for replace it works fine). I don't know if it's ok.

![image](https://github.com/user-attachments/assets/d030a3d2-8c41-465c-8977-0cdb3404e591)


----

This PR is a huge improvement in terms of quality and performance. I can switch to short distance (i.e. 50m) and cheap  orthogonal shadows, and still the entire scene is properly lit.  Thank you!

2024-10-30 18:02 UTC, BlueCube3310 commented
Both issues should now be resolved

2024-10-30 20:17 UTC, marcinn commented
Thanks. Opacity works fine now!

----

One more question. How shadowmasking should work with fog/volumetric fog?
With volumetric fog enabled darkest parts are drawn in color of the fog:

![shadowmask_volumetricfog](https://github.com/user-attachments/assets/2b405fa6-7c13-4447-82e5-60085c884575)

Without volumetric fog you can see pure darkness:
![image](https://github.com/user-attachments/assets/c6a778be-49b3-4348-b2f3-ac60e3f9f62f)

The goal is to achieve lightshafts from volumetric fog. I can achieve this by setting global density=0 and local fog volumes for each light. 

![image](https://github.com/user-attachments/assets/39da337b-4568-4c39-8fc1-b909b82eb760)

Is this a proper way to achieve this?

2024-10-30 21:06 UTC, marcinn commented
Can I exclude some meshes from baking their shadows or receiving static shadows?

I have moving platforms like this one.  In overlay mode two shadows are visible:
![image](https://github.com/user-attachments/assets/b3d4e84c-d225-4076-9548-020264d4dae5)

This can be partially workarounded by "replace" mode, but after shadow max distance the baked shadows are getting visible:
![image](https://github.com/user-attachments/assets/e57f03ae-54e6-4146-b8bc-c7de8099584a)

Shadows of other objects were also baked on these platforms:
![image](https://github.com/user-attachments/assets/5f8485ff-3bac-49f1-8d16-9afe9d6f9f7c)

As a workaround I'm thinking about hiding all moving platforms during baking lights, but I think that would be nice to have shadowmask layers (similar to light_cull_mask) to exclude object layers from baking their shadows.

As far I can see there is a Caster Mask, so I've excluded layer 2:
![image](https://github.com/user-attachments/assets/ee7eb2c5-7b10-4105-a561-c22b63989d82)

I've also set platform's mesh to layer 2:
![image](https://github.com/user-attachments/assets/966c2015-3e66-4f19-946c-69f06b61a290)

But this changed nothing. Platform's shadows are baked. I'm not sure is this a bug or not.

2024-10-31 00:37 UTC, SpockBauru commented
@BlueCube3310 
> Both issues should now be resolved

Thank you, now Forward+ works and Mobile seems to be working. But I'm facing a weird issue on the Compatibility renderer, it took a while to find the issue but here it is: 

On Compatibility renderer when I set a Spotlight to "Dynamic" the shadowmask vanishes and is replaced by the shadowmap, even when Shadowmask is set to "Only". When I look away from the light the shadowmask reapears. Rebaking doesn't help the issue.

https://github.com/user-attachments/assets/617b6861-aace-43b4-aa82-2bbad83ce645



@marcinn 
> Can I exclude some meshes from baking their shadows or receiving static shadows?

Not sure If I understand the issue, maybe you are referring to setting the `Geometry Instance` -> `Global Illumination` > `Mode` to `Dynamic`:

![image](https://github.com/user-attachments/assets/b5e918ae-7ead-46c3-85f8-c0994c4e440d)

In LightmapGI, when the mesh GI Mode is set to Dynamic it will be lit by the [Lightmap Probes (that little ballls)](https://docs.godotengine.org/en/stable/tutorials/3d/global_illumination/using_lightmap_gi.html#dynamic-objects). Those are like "little lights" that illuminates dynamic objects. The `gen probes` setting controls how many of them are in the screen and you can put more with nodes `LightmapProbe` if needed. 

Shadowmasks are not baked on Dynamic objects.

2024-10-31 01:07 UTC, marcinn commented
>  maybe you are referring to setting the Geometry Instance -> Global Illumination > Mode to Dynamic
> Shadowmasks are not baked on Dynamic objects.

Thanks! That was the cause. I completely forgot about GI mode. My apologies!

2024-10-31 01:53 UTC, Calinou commented
> As far I can see there is a Caster Mask, so I've excluded layer 2:

Note that this option doesn't affect lightmap baking due to https://github.com/godotengine/godot/issues/98684.

2024-10-31 11:22 UTC, marcinn commented
> Note that this option doesn't affect shadowmask baking due to #98684.

Oh, thanks for pointing this out!

2024-10-31 18:34 UTC, BlueCube3310 commented
> Thanks. Opacity works fine now!
> 
> One more question. How shadowmasking should work with fog/volumetric fog? With volumetric fog enabled darkest parts are drawn in color of the fog:
> 
> ![shadowmask_volumetricfog](https://private-user-images.githubusercontent.com/139032/381716100-2b405fa6-7c13-4447-82e5-60085c884575.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTkxNjQsIm5iZiI6MTczMDM5ODg2NCwicGF0aCI6Ii8xMzkwMzIvMzgxNzE2MTAwLTJiNDA1ZmE2LTdjMTMtNDQ0Ny04MmU1LTYwMDg1Yzg4NDU3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxODIxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjE4ZTBlOTY2NDcxNDhjNzk1Mzg1ODk3MDkzNzQxNDVmYTUzNWNlMDgzMWM1MzFhYTI1ZjdhM2YwYmYxZjRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T2YzPZO67rxX5Ju48Vqc_f4QY6ir3Gq0I91ov20M6KY)
> 
> Without volumetric fog you can see pure darkness: ![image](https://private-user-images.githubusercontent.com/139032/381716138-c6a778be-49b3-4348-b2f3-ac60e3f9f62f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTkxNjQsIm5iZiI6MTczMDM5ODg2NCwicGF0aCI6Ii8xMzkwMzIvMzgxNzE2MTM4LWM2YTc3OGJlLTQ5YjMtNDM0OC1iMmYzLWFjNjBlM2Y5ZjYyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxODIxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzM3ZjZjNTlmNDRmNTQ5Y2Y4NDgwNzA0OWM3YzMzODMxMTczODg4YjQ5MmMyZTllYjBhZmI5MTIyMDMzMmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AJRdkrXbgEjGJ2sL5iVIKxCHtUV-Z0RYgPJQxsYb_HU)
> 
> The goal is to achieve lightshafts from volumetric fog. I can achieve this by setting global density=0 and local fog volumes for each light.
> 
> ![image](https://private-user-images.githubusercontent.com/139032/381717560-39da337b-4568-4c39-8fc1-b909b82eb760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTkxNjQsIm5iZiI6MTczMDM5ODg2NCwicGF0aCI6Ii8xMzkwMzIvMzgxNzE3NTYwLTM5ZGEzMzdiLTQ1NjgtNGMzOS04ZmMxLWI5MDliODJlYjc2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxODIxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjU2ODFkMDZhYWQwZGEwNGJjNzY4ODVkMGNjNmI1OTQ4MjY5M2E0ODZmNDA4M2VhMmJjYWQ4M2Y4MWQ1ZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._zV61GoWFCy4yk0I7p2pet2XH9IxQNLvuzbAvLy1CmQ)
> 
> Is this a proper way to achieve this?

Volumetric fog and lightshafts depend on the real-time shadow projection since they contain more information (like depth), which is required for certain effects to work correctly. The shadowmasks are simply textures applied to a model's UV2 channel, they only store the shadow intensity.

2024-11-16 12:24 UTC, BlueCube3310 commented
Shadowmasks with vertex shading now work correctly.

There are two remaining issues which I don't know how to fix:
- with the Mobile renderer, lightmaps don't render at all on certain scenes. This is unrelated to this PR, however,
- the aforementioned issue with spot lights on Compatibility. For some reason, it looks like the shaders don't process the shadowmask logic when an object has additive lighting

2024-11-17 10:08 UTC, BlueCube3310 commented
Point/omni lights and shadowmasks should now work correctly on Compatibility. Therefore, I think this PR is now complete

2024-11-17 14:53 UTC, SpockBauru commented
Tested my MRP on Forward+, Mobile and Compatibility renderers. Shadowmasks is working as intended without any visual issues. Also baked the LightmapGI on each renderer and everything just works \o/

I didn't find any issue related to this PR and believe that is ready do merge :D

https://github.com/user-attachments/assets/44431be1-2253-4aa9-954c-1df46a0b2a27


### After merge

After merging, here are some thoughts about what I believe should be prioritized for LightmapGI overall:

**After merge LightmapGI Blocking bug**
Lightmap Probes are completely broken on both Mobile and Compatibility renderers, making LightmapGI unusable on the devices that would benefit most from it.

I believe this bug should be prioritized.

**After merge todo feature**
As discussed before, including an option for Shadowmask resolution would be a nice to have, but only after the merge!

**After merge to be discussed**
Currently the "Shadowmask Only" option seems to have different opinions on what it should do. I believe that it should disable all shadowmaps for good letting only shadowmasks and nothing else for both static and dynamic objects. We may have other option that project shadowmaps from dynamic objects on purely static objects (not possible right now). But these needs to be carefully discussed after the merge.

2024-12-10 19:43 UTC, clayjohn requested changes
We discussed this in the Rendering meeting today and the consensus is that we should move forward and merge this as soon as possible. However, we are a bit concerned about the current `ShadowmaskMode` options. They are a bit confusing and they seem to cater to very niche use-cases that may not be widely used. 

- Replace seems to be what most people expect from this feature. It allows for having baked shadows at a distance and high quality shadows when up close when baking indirect lighting
- Overlay seems interesting, but problematic. It will break if you have any animated objects. I suspect that there will be few cases where users want to have the low resolution lightmap fully overlaid on dynamic shadows. I suspect that it would be better to have an option to blend between the shadowmask and shadow map at the edges of the shadow range instead
- Only appears to be an inferior version of using the "Static" lightmapping mode on Light3Ds. It forces using the shadowmask (which is good for performance), but still uses real time direct lighting, so it is worse for performance than static lights. Ultimately, it presents a clunky workflow to do something that is already supported by the engine. I suspect that this option was more useful before we implemented bicubic sampling because users were unhappy with the quality of baked shadows before. 

Accordingly, we agreed that two things are needed before merging:
1. Un-expose the `SHADOWMASK_MODE_ONLY` enum. Its fine to leave the code in internally for now, but we don't want to expose it to users unless we need to.
2. Mark the `shadowmask_mode` as experimental. (We also need to call it out in the release notes as something that will likely change)

Personally, I suspect that we can get away with making the shadowmask a binary selection "SHADOW_MASK_ENABLED", "SHADOW_MASK_DISABLED" with a boolean that pops up when enabled to turn on/off blending. But I would like to get some more user feedback about what they need before we go down the rabbit hole of trying to decide on users problems for them.

2024-12-10 20:19 UTC, SpockBauru commented
I believe that the Shadowmask Only will be beneficial when the option to increase shadowmask resolution is implemented, so we can have high frequency shadowmask and low frequency lightmap. But this feature can wait.

For now I fully agree with @clayjohn: we should un-expose the shadowmask modes, keep only the binary selection and merge as soon as possible. Just keep the code for future improvements.

2024-12-11 14:47 UTC, SpockBauru commented
Tested [my MRP](https://github.com/godotengine/godot/pull/85653#issuecomment-2447529657) on Forward+, Mobile and Compatibility renderers. Shadowmasks is working as intended without any visual issues. Baked the LightmapGI on each renderer and everything is working.

Also made a quick test on my (halted) personal project. Out of the box, it works as expected without any issues. Far shadows are now present:

| Shadowmaps None| Shadowmaps Replace|
| ----- | ---- |
| ![shadowmap_none](https://github.com/user-attachments/assets/dd7a8a9c-7e3d-4bd9-ba3b-30fb664170d2) | ![shadowmap_replace](https://github.com/user-attachments/assets/54b93340-c6a1-453d-8f76-0411bf74f06a) |

With this developers can make an option to reduce shadowmaps resolution and distance, improving the performance on weak systems.

I didn't find any issue related to this PR and believe that is ready to merge.

2024-12-12 02:44 UTC, clayjohn approved these changes
Let's go ahead and merge this!

It looks great and while I think there is room for iteration, I think it's time to get this in the hands of users so we can get some feedback

2024-12-12 13:18 UTC, merged

2024-12-12 13:19 UTC, akien-mga commented
Thanks!

2024-12-12 17:25 UTC, Calinou commented
@BlueCube3310 I noticed shadowmasks are saved as PNGs, but saving them as WebPs can make them much smaller on disk:

```
321k test_shadow.png
151k test_shadow.webp
```

This does not affect memory usage, but it'll reduce file sizes in version control, which is helpful as lightmap data is often iterated upon.

The downside is that we can only do that for images that are 16383×16383 or smaller, so shadowmasks that are larger would have to be resized down. In practice, only 16384×16384 can be an issue here, so we could downsize it to 16383×16383 upon saving (Godot's VRAM compression will pad the last pixel automatically).

2024-12-13 21:32 UTC, michaelharmonart commented
Not sure if this is the place to mention it, but after some testing it seems that this doesn't take into account whether shadow casting is on per mesh. Would be nice to have that supported as well to be able to disable shadow casters for baking as well.

2024-12-13 23:43 UTC, clayjohn commented
> Not sure if this is the place to mention it, but after some testing it seems that this doesn't take into account whether shadow casting is on per mesh. Would be nice to have that supported as well to be able to disable shadow casters for baking as well.

That's an existing issue in LightmapGI. https://github.com/godotengine/godot/issues/98684

2024-12-14 00:33 UTC, michaelharmonart commented
ahh ok. l never noticed since there was never a way to blend between real-time and baked lighting like this before now

I noticed now only since there was a clear transition line between realtime and baked shadows only since there was a mismatch in which objects had shadows.

2024-12-20 01:39 UTC, IsaacMarovitz commented
In 4.4.dev7 despite, having shadowmask mode set to Replace, baking does not seem to build the shadowmasks. 

![image](https://github.com/user-attachments/assets/7306efbf-c1ee-4227-a4ea-4845515f8fb0)

I can't tell if I'm using it wrong, or if this is a bug.

2024-12-20 02:59 UTC, SpockBauru commented
> baking does not seem to build the shadowmasks.

@IsaacMarovitz It's working here, did you remembered to set shadowmasks to replace **before** baking?

2024-12-20 12:05 UTC, IsaacMarovitz commented
> It's working here, did you remembered to set shadowmasks to replace before baking?

I did. I'll test on another device to see if maybe this is a Mac thing.

2024-12-20 12:17 UTC, IsaacMarovitz commented
Nvm, I was using it wrong, my direction light was set to static and I missed the warn in the console. The DirectionLight Bake Mode documentation needs to be updated to reflect this change.

2024-12-28 15:43 UTC, unfa commented
Hey, where can I find a good explanation of this feature? I was looking around and couldn't really find anything.

2024-12-28 16:04 UTC, SpockBauru commented
Officially there's an explanation on the "latest" version of the docs, not the "stable" one since 4.4 stable was not released yet. Be aware that it's an experimental feature so there's no much explanation yet: 

- https://docs.godotengine.org/en/latest/classes/class_lightmapgi.html#class-lightmapgi-property-shadowmask-mode 
- https://docs.godotengine.org/en/latest/classes/class_lightmapgidata.html#enum-lightmapgidata-shadowmaskmode



I'm also answering people on this Reddit thread: https://www.reddit.com/r/godot/comments/1hcr73g

2025-01-07 16:03 UTC, Calinou commented
> Hey, where can I find a good explanation of this feature? I was looking around and couldn't really find anything.

I've opened a PR to document shadowmasks: https://github.com/godotengine/godot-docs/pull/10482

2025-01-10 01:29 UTC, GustJc commented
Not sure if something changed. 
But using the latest master (v4.4.dev.gh [24d74510e]) and trying to bake the lightmapGI using the testproject from (https://github.com/godotengine/godot/pull/85653#issuecomment-2447529657) crashes Godot.
With a lot of "Couldn't map PC to fn name" errors.

But testing it using a simple scene on a new projected or using the test_lightmapgi_mobile project (https://github.com/godotengine/godot/pull/85653#pullrequestreview-1768657637) worked fine. 



https://github.com/user-attachments/assets/852e65f9-1f42-476e-928f-f004ba76c92c

Here is the start of the crash:
(On Windows 10, Foward+, Nvidea 1070)


![shadowmask](https://github.com/user-attachments/assets/62311593-d235-4e54-86a3-1cfcd4b08b4e)

2025-01-10 03:17 UTC, SpockBauru commented
Compiled locally and can confirm that the demo is not working anymore. First time I baked, it got my PC unresponsive for a while and I had to make a hard reset. Second time it crashed Godot.

My system: `Godot v4.4.dev (24d74510e) - Windows 11 (build 22631) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.6614) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 threads)`

@GustJc Would you kindly open a new issue?

2025-01-10 03:18 UTC, SpockBauru commented
> Compiled the master branch locally and can confirm that the demo is not working anymore. First time I baked, it got my PC unresponsive for a while and I had to make a hard reset. Second time it crashed Godot.
> 
> My system: `Godot v4.4.dev (24d74510e) - Windows 11 (build 22631) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.6614) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 threads)`
> 
> @GustJc Would you kindly open a new issue?

2025-01-14 17:54 UTC, FeralBytes commented
@clayjohn 
> Personally, I suspect that we can get away with making the shadowmask a binary selection "SHADOW_MASK_ENABLED", "SHADOW_MASK_DISABLED" with a boolean that pops up when enabled to turn on/off blending. But I would like to get some more user feedback about what they need before we go down the rabbit hole of trying to decide on users problems for them.

I would like to provide some user feedback. In my limited testing overlay seemed to work better for me on the web than replace, because the default dynamic shadow distance was so low in compatibility mode on the web, the shadow would begin to hide itself before it could be replaced for objects that were tall, such as a hill nearby. So for the web, which really needs such a performant feature, I think overlay may be a better option than replace.

That also makes me wonder if shadow mask ONLY would do even better. But it does really come do to the needs of the game and the artist designing the game. I personally am in favor of keeping all of the modes exposed, because Godot is a general solution game engine. People have many potential use cases and we cannot know them all right now, so early in the release of the feature. 

Thank you for your time.