Fix 3D Select Mode not moving clicked node
godotengine/godot pull request #85740
Opened 2023-12-04 06:32 UTC by Cammymoop

Fixes #85736 

Fixed:
Clicking and dragging a node when no nodes are selected selects and starts to translate it, rather than starting a box select.
With a node selected, clicking and dragging another node in select mode both selects and starts to translate the clicked node rather than the currently selected node.
Clicking and dragging on a locked node now starts a box select rather than translating the currently selected node (just as clicking and dragging on the background.

Clicking and dragging on (one of) the selected node(s) works as before.

3D Select Mode now works more or less like 2D Select Mode, and 3D Select Mode prior to 3.2
With the added bonus of not selecting locked nodes like was possible in 3.1

2024-01-30 22:39 UTC, ryevdokimov requested changes
All tools can select now since: https://github.com/godotengine/godot/pull/86804

So, when you select->drag, in other models the behavior does not match.

2024-01-30 22:55 UTC, ryevdokimov commented
Also, I'm not sure if this is desired behavior. I could see situations where you want to box select, with unlocked nodes in the background where the select would be initiated. I think this makes too strong of an assumption of what the user wants, where a two-step process will prevent accidents. I would argue 2D is the one that needs to be changed.

2024-01-31 00:24 UTC, Cammymoop commented
Thanks for pointing that out, I'll fix that up.

> Also, I'm not sure if this is desired behavior. I could see situations where you want to box select, with unlocked nodes in the background where the select would be initiated. I think this makes too strong of an assumption of what the user wants, where a two-step process will prevent accidents. I would argue 2D is the one that needs to be changed.

This seems to be a regression from 3.1 and a worse regression from 3.2 onward, see the mentioned issue. I restored the old, presumably intended behavior, I think a case could be made to change the behavior (including the 2d editor) but that is separate from fixing this bug I think.

For what it's worth I support an (optional) setting to have select mode start a box select when dragging over another node instead of selecting then dragging as I would find that useful, not to the exclusion of the current behavior though, especially in 2d where I use the select mode for moving things around a lot. I just see that as a feature addition and primarily wanted to fix the bug.


As it currently stands it is simply intuitive and unhelpful and doesn't allow for starting a box select in that situation or several other more unambiguous situations. A pretty common example is where a large environment mesh exists in the scene but is locked for obvious reasons, and you want to use the select tool make box selections and move things around (along with axis constraining shortcuts this is pretty usable). 

The regression since 3.2 makes it even worse because in addition to having to hide the environment or use shift to make the box selections you also can't move an individual node without two clicks, and clicking to select it might put a gizmo under your cursor so you have to search for a neutral spot after the first click.

2024-01-31 02:19 UTC, Cammymoop commented
Translation now only starts on first click select + drag with Select or Move tool active, as in 2D editor.

2024-01-31 02:38 UTC, ryevdokimov commented
I can confirm that this PR does what it says it does and matches 2D behavior, without any issues I can find. I'll be interested to hear what the engine team thinks. @Calinou?

2024-01-31 02:43 UTC, Cammymoop commented
There is one difference from the 2D editor in that you can click on 2D nodes that are behind a locked node, but you cannot in 3D. (see also #84764 and my comment on the attached PR)

2025-03-03 15:02 UTC, Repiteo commented
Superseded by #87948

2025-03-03 15:02 UTC, closed without merging