Add list initialization to Array, Variant, and TypedArray
godotengine/godot pull request #86015
Opened 2023-12-10 23:00 UTC by kitbdev

- closes https://github.com/godotengine/godot-proposals/issues/1357 (unless any other types need it)
- salvages #50504
- related #50493

Arrays use Vector list initialization to set its internal Vector.
Variant becomes an array type.
TypedArrays<> must have a type to use the list initialization.

Added initializer list tests for Array, TypedArray<int>, Variant, and PackedInt32Array.
Packed Arrays are typedefs for Vector, so they had this functionality before.

I didn't change any code to use initializer lists in this PR.
In another PR, I think `build_array()` can be replaced with initializer lists in a few test files.

2024-04-28 18:58 UTC, nlupugla commented
Thanks for working on this @kitbev. I think this would make working with Arrays in the engine code much nicer. My only comment so far is whether we would rather have the argument be an initializer list or a `Vector<Variant>`. Note that having both would be an issue I think because then an expression like `Array({1, 2})` becomes ambiguous about whether it invokes the initializer list constructor or the vector constructor. I would argue in favor of the `Vector<Variant>` route (unless there are any performance reasons I'm not considering) because there are other places in the codebase where it would be useful to directly convert a vector to an array.

2024-05-02 09:31 UTC, RandomShaper commented
> [...] an expression like `Array({1, 2})` becomes ambiguous about whether it invokes the initializer list constructor or the vector constructor [...]
Would making the `Vector` constructor `explicit` avoid it being a candidate in such an expression?

Aside, I like this kind of changes to take Godot's C++ to the 21st century. I'm not sure about adding this kind of constructor to `Variant`. What are your thoughts in keeping initializing `Array`s in `Variant` more explicit (`Variant v = Variant(Array({...});`)?

2024-05-02 20:41 UTC, kitbdev commented
Rebased to fix merge conflict.

> vector constructor

Variant already has constructors for Packed*Array and a few other Vectors including `Vector<Variant>`, so array doesn't need its own constructor for it.

>  What are your thoughts in keeping initializing Arrays in Variant more explicit

Personally, I don't think it is needed and I like the ability to nest initializer lists for array and variant without it. The variant initializer list was made just for this purpose.
If we decide it would be better, I could remove it and make it explicit.

```gdscript 
Array nested = { { 0, 1 }, 'a' };
Array nested2 = { Array({ 0, 1 }), 'a' };
```

2024-05-06 09:28 UTC, RandomShaper commented
I'm not sure about the status of this conern:
> [...] an expression like `Array({1, 2})` becomes ambiguous about whether it invokes the initializer list constructor or the vector constructor [...]

2024-05-06 13:08 UTC, nlupugla commented
Personally, I'd prefer the explicitness, but it might be an odd outlier if that's already how it works for some of the other types.

2024-09-03 16:44 UTC, kitbdev commented
>I'm not sure about the status of this conern:
    [...] an expression like Array({1, 2}) becomes ambiguous about whether it invokes the initializer list constructor or the vector constructor [...]

Array doesn't have a vector constructor, so there is no issue. And I'm pretty sure it would use the initializer list in that case if it did.

As for Variant, where there is an initializer list constructor and vector constructors (including Packed*Arrays since they're vector typedefs):
```cpp
Variant({ 0.0, 1.0 }); // Variant uses initializer_list constructor.
Variant(Vector({ 0.0, 1.0 })); // Variant uses PackedFloat64Array constructor.

Variant({ 0.0, "b" }); // Variant uses initializer_list constructor.
Variant(Vector<Variant>({ 0.0, "b" })); // Variant uses Vector<Variant> constructor.
Variant(Array({ 0.0, 1.0 })); // Variant uses Array constructor.
Variant(PackedFloat32Array({ 0.0, 1.0 })); // Variant uses PackedFloat32Array constructor.
```

The first two are actually not the same since they have different Variant types, and they won't be equal. The first is type Array and the second is type PackedFloat64Array.
So maybe it should be explicit? Or some more logic should be done in the Variant initializer list constructor to convert to a packed type? Or maybe it is fine as is?

2025-02-22 15:45 UTC, tomfull123 approved these changes
Looks good to me!

2025-03-19 13:27 UTC, akien-mga approved these changes

2025-03-19 13:34 UTC, KoBeWi commented
> I didn't change any code to use initializer lists in this PR.

Probably time to rebase #89782 after this is merged.

2025-03-19 13:38 UTC, Ivorforce requested changes

2025-03-19 13:38 UTC, Ivorforce commented on core/variant/typed_array.h
> +				Array(Array(p_init), m_variant_type, StringName(), Variant()) {                                  \
Are you sure this is typesafe? I think this will allow instantiation like:
```c++
TypedArray<int> array = { "string" };
```
Because the array `initializer_list` constructor doesn't do type checks.

2025-03-19 13:46 UTC, Ivorforce approved these changes

2025-03-19 22:46 UTC, merged

2025-03-19 22:46 UTC, Repiteo commented
Thanks!