Prevent crash when call set_text() on a removed treeItem
godotengine/godot pull request #86028
Opened 2023-12-11 11:34 UTC by jsjtxietian

Fixes #85650

Also, should I use add more description or just use `ERR_FAIL_NULL` is sufficent ?

2023-12-11 11:37 UTC, AThousandShips commented
This should be before updating the text IMO, in the relevant methods calling these methods

Unless we can confirm it's valid and doesn't have strange sideeffects to update the text off the tree

2023-12-11 12:16 UTC, YuriSizov requested changes
This would just raise a pointless error. It should be a normal if-check, not an error macro.

2023-12-12 04:58 UTC, jsjtxietian commented
> This should be before updating the text IMO, in the relevant methods calling these methods

Yes but there are too many places that might call `_changed_notify`, since ` the previous assumption tree items were always in a tree`

2023-12-12 10:19 UTC, AThousandShips commented
> Yes but there are too many places that might call

I don't think that's a valid argument against adding it there, but if you confirm that it's safe and doesn't cause any side effects to manipulate the text etc. not on the tree we can add it just to the places where `tree` is accessed, otherwise I'd say we shouldn't allow the manipulation if it's not safe

2023-12-12 10:46 UTC, jsjtxietian commented
> we'd need to verify this before we make this change

Indeed, you are right. Does anyone familiar with this part of code and can give me some suggestions?

2023-12-12 10:47 UTC, AThousandShips commented
A basic test would be to try your own code and see if there's any noticeable difference, if there isn't studying the code in more detail should help

2023-12-12 18:18 UTC, YuriSizov approved these changes
I think this is good as is right now. I don't particularly see a reason to check places that call these methods. Changing items should be fine out of `Tree`.

2023-12-12 18:24 UTC, AThousandShips commented
I'll trust that the manipulation of these is safe off the tree, despite the aspects mentioned above 🙂, but won't approve myself as I can't confirm it

2023-12-13 09:34 UTC, merged

2023-12-13 09:35 UTC, akien-mga commented
Thanks!