Add Wayland support (squashed review edition)
godotengine/godot pull request #86180
Opened 2023-12-15 01:43 UTC by Riteo

Squashed version of #57025 laid out for ease of reviewing.

Resolves godotengine/godot-proposals#990.

**See #57025 for further information.**

Not everything is yet implemented, either for Godot or personal limitations (I don't have all hardware in the world). A brief list of the most important issues follows:

- Single-window only: the `DisplayServer` API doesn't expose enough information for properly creating XDG shell windows.

- Very dumb rendering loop: this is very complicated, just know that the low consumption mode is forced to 2000 Hz and some clever hacks are in place to overcome a specific Wayland limitation. This will be improved to the extent possible both downstream and upstream.
**EDIT: big (maybe) improvement pending in a new PR as soon as this one gets merged**

- Features to implement yet: IME, touch input, native file dialog, drawing tablet (commented out due to a refactor), screen recording.

- Mouse passthrough can't be implement through a poly API, we need a rect-based one.

- The cursor doesn't yet support fractional scaling.

- Auto scale is rounded up when using fractional scaling as we don't have a per-window scale query API (basically we need `DisplayServer::window_get_scale`).

- Building with `x11=no wayland=yes opengl=yes openxr=yes` fails.

This also adds a new project property and editor setting for selecting the default DisplayServer to start, to allow this backend to start first in exported projects (X11 is still the default for now). The editor setting always overrides the project setting.

Special thanks to Drew Devault, toger5, Sebastian Krzyszkowiak, Leandro Benedet Garcia, Subhransu, Yury Zhuravlev and Mara Huldra.

## How to review this PR

Don't let the diff size scare you, it's smaller than you think!

"Wayland" is mostly an IPC; the actual interfaces are defined in XML "protocol" files. It has a very lean core protocol designed to be extended. Each of those XML files is used to generate the C wrappers that the backend uses through an utility named `wayland-scanner` which must be available on the building system (`libwayland-bin` package on Debian). We generate them this way because the result changes between Wayland versions and so it's good practice for all Wayland programs.

The core protocol is present in `thirdparty/wayland` (+3087) and the various extensions are present in `thirdparty/wayland-protocols` (+4303), copied verbatim as in `thirdparty/README.md` (+43).

Talking about `thirdparty`, various dependencies got dynwrapped into `platform/linuxbsd/wayland/dynwrappers` (+1698) and their library headers got put into `thirdparty/linuxbsd_headers/` (+7929), according to `thirdparty/linuxbsd_headers/README.md` (+14).

Note that the dynwrappers are still the handpatched kind, although the latest version of dynload-wrapper, 0.4, should create working equivalents.

Regarding the dependencies, we pull in `wayland-client` (self-explanatory), `wayland-cursor` (cursor handling), `wayland-egl-core` (EGL support) and `libdecor-0` (client-side decorations)

If you're wondering about `libdecor-0`: Wayland allows compositors to not provide SSDs (and thus require CSDs). We don't have yet support for them so I implemented (optional) support for this library that draws CSDs for us. I think that we should eventually implement our own solution (as it's being slowly being done AFAIK) to reap all the benefits of them and, well, to get rid of a dependency and all its handling code :P

As you can see, a good part of the diff (+17048) is actually data or autogenerated stuff. There's not much review that has to be done, outside of a quick glance to verify those claims. I swear I didn't put any malware in there :P

Now we talk about the actually juicy stuff.

Wayland moves a lot of responsibility to the client. Because of that, the logic is actually split between a `DisplayServerWayland` (`platform/linuxbsd/wayland/display_server_wayland.*`, +1615) and a `WaylandThread` (`platform/linuxbsd/wayland/wayland_thread.*`, +4929).

As you can see, most of the Wayland logic is in the thread, which is also probably the hardest to review. It offers various methods (which _don't_ set the internal mutex manually, this has to be done by the caller) and an `InputEvent`-style queue, which gives various notifications to the main thread, like input and rect changes.

The advantage of this design is that we can keep the thing as responsive as possible and that it takes care to translate the information to something that the engine can understand in the same place that it's handled (e.g. HiDPI scaling, `InputEvent` generation). That also moves, well... The main Wayland logic, into one place.

You should be able to understand `DisplayServerWayland` pretty well without any knowledge about the Wayland library, perhaps with the exception of `window_can_draw`. In short, the compositor wants to tell us when to draw, so we do this dirty hack where we set it to `true` only when we get a frame event. This is good enough for now but it will be improved.

Of note there's `platform/linuxbsd/wayland/detect_prime_egl.*` (+296) which is mostly similar to the X11 counterpart, with the exception that it probes up to 4 devices, allowing a bit more of leeway for people with an IGPU, DGPU and a SW rasterizer, as sometimes the DGPU would not be probed at all. That code could be shared somehow but that's a topic for another time I think.

Other than that, there's some plumbing, project/editor setting handling, doc changes, driver implementations (Vulkan, EGL) and licensing information but it should be already familiar to most of us I hope.

That's it really. I hope that this helps with reviewing :)

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/display_server_wayland.h
> +	static String _get_app_id_from_context(Context context);
```suggestion
	static String _get_app_id_from_context(Context p_context);
```

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/display_server_wayland.h
> +	void _resize_window(Size2i size);
```suggestion
	void _resize_window(const Size2i &p_size);
```

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/display_server_wayland.h
> +	virtual Point2i screen_get_position(int p_screen = SCREEN_OF_MAIN_WINDOW) const override;
```suggestion
	virtual Point2i screen_get_position(int p_screen) const override;
```
Default arguments on overrides are unnecessary (and not recommended AFAIK) and clutters here IMO

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/display_server_wayland.cpp
> +String DisplayServerWayland::_get_app_id_from_context(Context context) {
```suggestion
String DisplayServerWayland::_get_app_id_from_context(Context p_context) {
```

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/display_server_wayland.cpp
> +void DisplayServerWayland::_resize_window(Size2i size) {
```suggestion
void DisplayServerWayland::_resize_window(const Size2i &p_size) {
```

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/key_mapping_xkb.h
> +		static _FORCE_INLINE_ uint32_t hash(const unsigned p_key) { return hash_fmix32(p_key); }
```suggestion
		static _FORCE_INLINE_ uint32_t hash(Key p_key) { return hash_fmix32(static_cast<uint32_t>(p_key)); }
		static _FORCE_INLINE_ uint32_t hash(unsigned p_key) { return hash_fmix32(p_key); }
```
No `const` for simple types

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/wayland_thread.h
> +	static Vector2i scale_vector2i(Vector2i p_vector, double p_amount);
```suggestion
	static Vector2i scale_vector2i(const Vector2i &p_vector, double p_amount);
```

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/wayland_thread.h
> +	void window_set_min_size(DisplayServer::WindowID p_window_id, Size2i p_size);
```suggestion
	void window_set_max_size(DisplayServer::WindowID p_window_id, const Size2i &p_size);
	void window_set_min_size(DisplayServer::WindowID p_window_id, const Size2i &p_size);
```

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/wayland_thread.h
> +	void window_set_app_id(DisplayServer::WindowID p_window_id, String p_app_id);
```suggestion
	void window_set_title(DisplayServer::WindowID p_window_id, const String &p_title);
	void window_set_app_id(DisplayServer::WindowID p_window_id, const String &p_app_id);
```

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/wayland_thread.h
> +	void pointer_set_hint(Point2i p_hint);
```suggestion
	void pointer_set_hint(const Point2i &p_hint);
```

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/wayland_thread.h
> +	void cursor_shape_set_custom_image(DisplayServer::CursorShape p_cursor_shape, Ref<Image> p_image, Point2i p_hotspot);
```suggestion
	void cursor_shape_set_custom_image(DisplayServer::CursorShape p_cursor_shape, Ref<Image> p_image, const Point2i &p_hotspot);
```

2023-12-15 10:56 UTC, AThousandShips commented on platform/linuxbsd/wayland/wayland_thread.h
> +	void primary_set_text(String p_text);
```suggestion
	bool selection_has_mime(const String &p_mime) const;
	Vector<uint8_t> selection_get_mime(const String &p_mime) const;

	void selection_set_text(const String &p_text);

	// Optional primary support - requires wp_primary_selection_unstable_v1
	bool primary_has_mime(const String &p_mime) const;
	Vector<uint8_t> primary_get_mime(const String &p_mime) const;

	void primary_set_text(const String &p_text);
```

2023-12-15 11:28 UTC, AThousandShips commented on platform/linuxbsd/wayland/display_server_wayland.h
> +	virtual Point2i screen_get_position(int p_screen = SCREEN_OF_MAIN_WINDOW) const override;
That's very strange, gotcha

2023-12-15 11:58 UTC, AThousandShips commented on platform/linuxbsd/wayland/display_server_wayland.h
> +	virtual Point2i screen_get_position(int p_screen = SCREEN_OF_MAIN_WINDOW) const override;
Looked further into it and not a weirdness just got confused about overrides and calling them

2023-12-20 00:06 UTC, v01dXYZ commented on platform/linuxbsd/wayland/display_server_wayland.cpp
> +			Error err = egl_manager->window_create(MAIN_WINDOW_ID, wayland_thread.get_wl_display(), wd.wl_egl_window, wd.rect.size.width, wd.rect.size.height);
It seems `EGLManager::window_create` expects a `display*` and a `window*` as the names of the variables suggest:

https://github.com/godotengine/godot/blob/3ce73e5d419011d1642ed30a3417362b82c41898/drivers/egl/egl_manager.cpp#L200

2023-12-20 17:42 UTC, v01dXYZ commented on platform/linuxbsd/wayland/display_server_wayland.cpp
> +			Error err = egl_manager->window_create(MAIN_WINDOW_ID, wayland_thread.get_wl_display(), wd.wl_egl_window, wd.rect.size.width, wd.rect.size.height);
The manager doesn't send the values directly (for EGL != 1.5). It dereferences them before: 

https://github.com/godotengine/godot/blob/3ce73e5d419011d1642ed30a3417362b82c41898/drivers/egl/egl_manager.cpp#L61

https://github.com/godotengine/godot/blob/3ce73e5d419011d1642ed30a3417362b82c41898/drivers/egl/egl_manager.cpp#L219

Maybe that's not a bug related to your MR.

2023-12-26 22:05 UTC, ansipunk commented
Hello Riteo! Thank you for your incredible contributions.
I can't help but be curious, have you tested if Wayland support fixes black window flickering on high refresh screens on KDE with VRR enabled?

2023-12-27 10:33 UTC, vmedea commented
> Should I keep the protocol definitions vendored or should I depend on wayland-protocols?

I guess using the installed wayland-protocols gives a better idea of what wayland protocols are actually used on the computer it's built on.

One drawback would be that you'd have to take into account different versions of the protocol files that may be installed on the devr's computer (which can cover a very wide range). We've seen this with the `wl_pointer.axis_v120` event. Some experimental ones like the tablet support may be missing completely.

There may be reasons to deviate from it here specifically but in general I like the self-containedness of godot's build system, it's very convenient. Also, the computer it's built on is not the one it's going to be run on if you're distributing a game, it's not the same as usual FOSS assumptions.

2023-12-27 17:15 UTC, geowarin commented
@ansipunk Coul this be [this bug](https://gitlab.freedesktop.org/drm/amd/-/issues/2967), reported in upstream KDE.

Nobara recommends the [following workaround](https://feed.nobaraproject.org/en/flicker-issues-with-kde-wayland-at-frame-rates-100-fps).

2023-12-28 04:26 UTC, ansipunk commented
@geowarin

This problem, from my experience, is exclusive to Godot — all the other programs and games work just fine.  However, it also appears on Windows as well. From what I understand, it will happen on any platform with any configuration as long as refresh rate is higher than 60.

I asked my question because Wayland, unlike X, supports VRR and KDE is the first and only DE I know of that supports VRR, so I imagined adding Wayland support might fix this problem in serendipity.

There are many issues in Godot project that address the flickering problem like #77337 and the only workaround for it, as of now, is to turn VRR off.

2024-01-01 18:19 UTC, Calinou commented
> I asked my question because Wayland, unlike X, supports VRR and KDE is the first and only DE I know of that supports VRR, so I imagined adding Wayland support might fix this problem in serendipity.

X11 has VRR support in single-monitor configurations – I'm using one right now on KDE + NVIDIA.

2024-01-04 10:46 UTC, iMonZ commented
Finally Godot becomes usable…
Can’t wait to try Godot the first time with 4.3
I have actually waited for 4 years already…

2024-01-04 11:16 UTC, akien-mga commented
@iMonZ You can communicate your support by giving the PR a thumbsup, but please refrain from commenting if you're not participating in reviewing the PR.

2024-01-04 13:33 UTC, akien-mga commented
Needs rebase to build after the RenderingDeviceDriver rework.
```
platform/linuxbsd/wayland/display_server_wayland.h:41:10: fatal error: drivers/vulkan/rendering_device_vulkan.h: No such file or directory
   41 | #include "drivers/vulkan/rendering_device_vulkan.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

2024-01-05 16:03 UTC, adamscott requested changes
## Must have before merge
- [ ] Default to `xwayland` first.
- [ ] Add an editor setting option to select which backend to use on Wayland (`native` or `xwayland`).
- [ ] Add a command line parameter to force select a Wayland backend (`native` or `xwayland`).

2024-01-06 02:00 UTC, Decodetalkers commented
> > Add a command line parameter to force select a Wayland backend (native or xwayland).
> 
> BTW, regarding this one, it's already there. It's just the default `--display-server` CLI argument.

Can there be an environment variable? Like Firefox use moz_wayland to enable Wayland support

2024-01-06 16:48 UTC, TuxTheAstronaut commented
@Riteo thats good to hear, one by concerns was that after this was merged users would update and wonder why their shaders broke but since xwayland will default most probably wont notice. 

However for people who are testing this PR if you haven't also added the fix in yourself to fix the shader bug then a quick fix is to instead cap the frame rate at your monitors refresh rate instead of using vsync to fix shaders. tho note setting the fps cap much higerer than the refresh rate will cause shaders to act up again at least from my testing.

2024-01-09 19:28 UTC, vmedea commented on platform/linuxbsd/wayland/display_server_wayland.cpp
> +	drivers.push_back("opengl3");
not a big deal i think but FWIW, `display_server_x11.cpp` calls this same driver `opengl3_es`, `opengl3` is the desktop GL

2024-01-09 20:09 UTC, vmedea commented
When launching godot editor using `--display-driver wayland`, any projects will still launch in X11 by default. Not sure this is intentiona but it was slightly confusing to me. Changing the project setting worked.

2024-01-09 21:34 UTC, vmedea commented on platform/linuxbsd/wayland/display_server_wayland.cpp
> +	drivers.push_back("opengl3");
Oh, thought wayland used EGL+GLES, that's fine then!

2024-01-10 21:28 UTC, TuxTheAstronaut commented
testing the new editor setting it seems to break the `--display-driver` command line argument. if the setting is set to prefer wayland then `--display-driver x11` will still use wayland instead.

2024-01-10 23:26 UTC, TuxTheAstronaut commented
@Riteo its working now 👍

2024-01-26 02:08 UTC, technobaboo requested changes

2024-01-26 02:08 UTC, technobaboo commented on modules/openxr/extensions/platform/openxr_opengl_extension.cpp
Consider replacing the X11 OpenGL graphics bindings with XrGraphicsBindingEGLMNDX for Linux (maybe in another PR), as both Monado and SteamVR, X11 and Wayland support them + it does not require a desktop window being open.

I'd be willing to help with this, as in my experience the X11/Wayland-specific graphics bindings are more trouble than they're worth and I fought to get the EGL extension supported everywhere.

2024-01-26 02:11 UTC, technobaboo commented on modules/openxr/extensions/platform/openxr_opengl_extension.cpp
though if better, I could also just add wayland graphics bindings support (but why not unify them?)

2024-01-26 06:47 UTC, technobaboo commented on modules/openxr/extensions/platform/openxr_opengl_extension.cpp
the reason I suggested delaying the PR was just to fix wayland, whether that's via the wayland or egl graphics bindings.

2024-01-26 06:55 UTC, technobaboo commented on modules/openxr/extensions/platform/openxr_opengl_extension.cpp
i asked in the XR chat what they'd allow in terms of graphics bindings (because i can fix it up once i know that) and hopefully this won't be delayed for long!

btw i suggested delaying this PR because you mentioned it wouldn't even compile with openxr enabled, is that still true or will it just error?

2024-01-26 08:27 UTC, technobaboo commented on modules/openxr/extensions/platform/openxr_opengl_extension.cpp
https://github.com/Riteo/godot/pull/4

fixed it, worth double-checking it's up to par with the other code but functionally it works great

2024-01-27 23:22 UTC, technobaboo commented on modules/openxr/extensions/platform/openxr_opengl_extension.cpp
we agreed this is better done in a separate PR with different code

2024-01-29 12:25 UTC, Domeee commented
Running the editor with `run/platforms/linuxbsd/prefer_wayland` set to `true` works. Running the project from this same editor instance launches the game in X11. See the outputs of `swaymsg -t get_tree`:

```
#25: output "DP-2"
    #17: workspace "8"
      #19: con "prototype_03.tscn - awakening - Godot Engine" (xdg_shell, pid: 4072, app_id: "org.godotengine.Editor")
      #36: con "awakening (DEBUG)" (xwayland, pid: 16610, instance: "Godot_Engine", class: "awakening", X11 window: 0x800003)
```

I expect the game to run with Wayland too.

Running the game directly via command line, e.g. `/home/dome/code/godot/bin/godot.linuxbsd.editor.x86_64 --path /home/dome/code/awakening --display-driver wayland` runs the game in Wayland. Running the editor (`--editor`) via command line and then run the game from within this editor instance launches the game in X11 again.

2024-01-29 15:04 UTC, Domeee commented
In my opinion the settings from `run/platforms/linuxbsd/prefer_wayland` should be carried over to a project that is run from within the editor (not exported). When developing inside the editor I regard the running game as an extension of the editor and therefor don't expect other settings regarding the display server. This is my personal expected behavior.

Regarding exported projects I would expect an option in the projects settings, e.g. `application/run/linuxbsd/prefer_wayland`.

2024-01-29 15:54 UTC, Domeee commented
Sorry, I was not aware of the new project property section "Display Server". Still, I think for a game launched in the editor the editor settings should be carried over. From a users (game dev) point of view, working in the editor, which includes running games via the editor, should be configured via editor settings. This allows me to set the display server for the export in the project settings (an probably leaving it be for the lifetime of the project) while changing the editor settings according to my needs as developer (which may even differ across dev envs [in my case wayland on my desktop, while i run x11 on my notebook]). The current implementation may lead to a lot of builds with the wrong display server configured (just because the dev used it on his machine and forget to reset the setting).

If you don't agree, I wish the description in the editor settings will be extended with an info (e.g. set display server for the player in project settings). Thanks for your consideration! Really looking forward for wayland support to land in the next release 😍

2024-01-29 16:33 UTC, Domeee commented
The editor settings should **always** be carried over to the game when launched via editor. The editor settings should not affect the exported game. The project setting should only affect the exported game. This is how I as a Godot user would expect things to work. But I am not the reference ;-)

In the current state I consider this a minor inconvenience, which can be resolved by extending the description in the editor settings to make things clear. This way there are no more larger changes and the PR gets merged faster. This way it's also possible to consult with the community regarding the project vs. editor settings to see if my expectation matches with the community :-D

2024-01-29 22:03 UTC, akien-mga approved these changes
Did a code review on GitHub, this is excellent work! :tada: :1st_place_medal: 

I admit I didn't review WaylandThread in depth yet, but the overall architecture seems very solid and I didn't spot anything out of place in the areas I'm familiar with.

I tested briefly on Linux X11 and it works as expected ;)

I'll aim to test on Wayland in coming days, just need to setup a proper Wayland environment and get familiar with whether quirks are from this PR or from Wayland itself :)

Note this recently merged PR which impacts the keymapping code, should likely be reflected here: #80231.

2024-01-30 03:18 UTC, AlexRamallo commented
For what it's worth, I just quickly tested this on my system (Fedora Kinoite 39 + RTX 4090 + Wayland) and it seems to be working very well. Godot's editor has always been borderline unusable for me without X11 because of tons of display and input bugs, but none of those are present in this branch. Good job! :D

2024-01-30 10:01 UTC, akien-mga commented
I've been testing on KDE on Wayland (Plasma 5.27.5), and it seems to work well for the most part.
Editing a project with Wayland from the command line with `godot-git --display-driver wayland -e --path /home/akien/Projects/godot/projects/godot-4-3d-third-person-controller/ ` works fine.

As mentioned above, the parameter isn't passed further to instances created by the editor when running the project, but that's currently the way Godot works for most things. So while a subpar experience, it's not related to this PR and not something to change here.

---

A few times I was confused as to whether I was actually running on Wayland or X11. I had to use `xprop` to figure it out.
I would suggest looking into whether we could print the display server in the output, maybe on the same line as the rendering info, which currently is like:
```
OpenGL API 4.6 (Core Profile) Mesa 23.3.2 - Compatibility - Using Device: Intel - Mesa Intel(R) HD Graphics 630 (KBL GT2)
```

It could maybe become:
```
Linux (Wayland) - OpenGL API 4.6 (Core Profile) Mesa 23.3.2 - Compatibility - Using Device: Intel - Mesa Intel(R) HD Graphics 630 (KBL GT2)
```
(And likewise for other OSes, leaving out the display driver if it's the same as the OS name maybe so we don't get "Windows (Windows)", but still get "Windows (Headless)".)

Either way, that's also something for a follow-up PR IMO, doesn't need to be here.

---

One significant issue I ran into is that the project manager seems to crash my Mesa drivers when running with Wayland. Strangely enough, running a GL Compatibility project from the command line with `--display-driver wayland` does *not* crash the same way. So there's something specific to the PM. Maybe related to low processor usage mode?

It crashes on my AMD discrete GPU (Radeon RX Vega M) when auto-detected by `prime_detect` or selected with `DRI_PRIME=1`, and doesn't crash with the integrated Intel HD Graphics 630 (when forced with `DRI_PRIME=0`).

Here's the stacktrace from `DRI_PRIME=1 godot-git --display-driver wayland`:
```
OpenGL API 4.6 (Core Profile) Mesa 23.3.2 - Compatibility - Using Device: AMD - AMD Radeon RX Vega M GL Graphics (radeonsi, vegam, LLVM 15.0.6, DRM 3.54, 6.5.13-desktop-6.mga9)
(gdb) bt
#0  0x00007ffff7518580 in wl_proxy_get_version () from /lib64/libwayland-client.so.0
#1  0x00007ffff00aba8d in create_wl_buffer () from /lib64/libEGL_mesa.so.0
#2  0x00007ffff00ac1e8 in dri2_wl_swap_buffers_with_damage () from /lib64/libEGL_mesa.so.0
#3  0x00007ffff00a13c3 in dri2_swap_buffers () from /lib64/libEGL_mesa.so.0
#4  0x00007ffff0095665 in eglSwapBuffers () from /lib64/libEGL_mesa.so.0
#5  0x0000000006ed0714 in EGLManager::swap_buffers (this=0xb2c1120) at drivers/egl/egl_manager.cpp:290
#6  0x0000000005868d13 in DisplayServerWayland::swap_buffers (this=0xb2a9840) at platform/linuxbsd/wayland/display_server_wayland.cpp:1115
#7  0x0000000006e25812 in RasterizerGLES3::end_viewport (this=0xb39ef80, p_swap_buffers=true) at drivers/gles3/rasterizer_gles3.cpp:112
#8  0x0000000006e273e0 in RasterizerGLES3::set_boot_image (this=0xb39ef80, p_image=..., p_color=..., p_scale=false, p_use_filter=true) at drivers/gles3/rasterizer_gles3.cpp:475
#9  0x00000000093c63b7 in RenderingServerDefault::set_boot_image (this=0xb4ff7e0, p_image=..., p_color=..., p_scale=false, p_use_filter=true) at ./servers/rendering/rendering_server_default.cpp:279
#10 0x00000000058add13 in Main::setup2 () at main/main.cpp:2732
#11 0x00000000058aac0c in Main::setup (execpath=0x7fffffffd9e4 "/home/akien/.local/bin/godot-git", argc=2, argv=0x7fffffffd510, p_second_phase=true) at main/main.cpp:2251
#12 0x00000000057fb7e5 in main (argc=3, argv=0x7fffffffd508) at platform/linuxbsd/godot_linuxbsd.cpp:62
```

---

Related to the above, I get a bunch of warnings when running without `DRI_PRIME`, i.e. letting our `prime_detect` figure it out:
```
$ godot-git --display-driver wayland
Godot Engine v4.3.dev.custom_build.7790b2be9 - https://godotengine.org
libdecor-0.so.0: cannot open shared object file: No such file or directory
Invalid value (0) for DRI_PRIME. Should be > 0
Inconsistent value (2) for DRI_PRIME. Should be < 2 (GPU devices count). Using: 1
Inconsistent value (3) for DRI_PRIME. Should be < 2 (GPU devices count). Using: 1
Found discrete GPU, setting DRI_PRIME=1 to use it.
Note: Set DRI_PRIME=0 in the environment to disable Godot from using the discrete GPU.
OpenGL API 4.6 (Core Profile) Mesa 23.3.2 - Compatibility - Using Device: AMD - AMD Radeon RX Vega M GL Graphics (radeonsi, vegam, LLVM 15.0.6, DRM 3.54, 6.5.13-desktop-6.mga9)
```
(and then the crash as described above)

---

My Linux distro (Mageia) doesn't seem to provide libdecor-0 at all :exploding_head: 
I'll have to package it. But we should assess whether it's widely available on more mainstream distros (I expect it is and Mageia is just lagging behind in its Wayland integration).

2024-01-30 10:13 UTC, YuriSizov commented on main/main.cpp
> +
As a codestyle nitpick, benchmarking calls must be wrapping the scope, so this addition needs to be moved below `OS::get_singleton()->benchmark_begin_measure("Servers", "Display");`

2024-01-30 15:59 UTC, akien-mga commented
> _Edit:_ Actually even `DRI_PRIME=0` raises a warning it seems, despite us suggesting it as an option to select the integrated GPU. It seems like it should be `DRI_PRIME=` without `0`.
> The warning `Inconsistent value (2) for DRI_PRIME. Should be < 2 (GPU devices count). Using: 1` does sound like it could support passing numbers above 2 if you have more than 2 GPUs so maybe your interpretation is correct? But at least on my system, a software renderer isn't registered as a GPU.

So I guess let's keep it as is for now and see how to improve the logic later.

2024-01-30 16:21 UTC, adamscott approved these changes
Congrats, @Riteo for your hard and long commited work!

2024-01-30 16:25 UTC, YuriSizov commented on main/main.cpp
> +					while (!screen_found || !prefer_wayland_found) {
Shouldn't this be `&&`? I assume we want to find both properties.

2024-01-30 16:26 UTC, YuriSizov commented on main/main.cpp
> +					while (!screen_found || !prefer_wayland_found) {
Ah wait, that's correct.

2024-01-30 16:30 UTC, YuriSizov commented on main/main.cpp
> +					while (!screen_found || !prefer_wayland_found) {
Yes, the negatives tricked me.

2024-01-30 16:32 UTC, YuriSizov approved these changes
Changes outside of the Linux platform code seem low risk, so this should be good to merge to facilitate further testing.

2024-01-30 16:49 UTC, merged

2024-01-30 16:52 UTC, akien-mga commented
A huge thankyou and congratulations for the amazing work done here @Riteo, and every one involved testing, proposing changes, and reviewing the code. :tada: :1st_place_medal: 

This is a major update for Linux users and an impressive achievement!

And just the start of the journey... now let's polish, add missing features, and see how to make good use of Wayland to improve things ever further!

2024-01-30 22:12 UTC, oschl-git commented
This might slip by unnoticed by most people in the community, but it's a really huge deal, especially for the future. Congratulations and thanks so much for working on this, @Riteo.

2024-01-30 22:19 UTC, agentx3 commented
This is fantastic! I recently got into Godot, and was experiencing frustrations with its xwayland buggy-ness. What a fortunate and blessed contribution to the FOSS community.

2024-01-31 01:13 UTC, Rindbee commented on platform/linuxbsd/detect.py
> +        BoolVariable("wayland", "Enable Wayland display", True),
These two are conflicting options, so leave one as `True`.

2024-01-31 12:23 UTC, sim1cent commented
Great work for the wayland backend, though i think the availability of a SDL backend is necessary for true linux long term compatibility, here's a old comment i posted on a related merge request.

_Many commercial engines use SDL, though statically linked (it has a neat mechanism to override itself even when statically linked), only on Linux, even if it might be used as a cross-platform abstraction.
This proves is that the de-facto windowing API for Linux is SDL, they are the only ones that seem committed to backward compatibility, and it's proven judging from their effort of maintaining a stable ABI and things like sdl12-compat (and soon sdl2-compat).
I can run 2003 builds of Linux games using modern display and audio protocols thanks to it.
It's not that Godot developers aren't good enough to make a decent Linux port, it's that SDL is the necessary overlay for long term compatibility.
This is especially critical right now when this engine is being adopted more and more, and game developers don't certainly have to maintain the Linux builds for the years to come._

2024-05-04 19:55 UTC, Enderteck commented
Is Wayland support now pretty much ready, or are there important issues/missing features ?