Fix `blend_node` crash with invalid p_node
godotengine/godot pull request #86321
Opened 2023-12-19 04:59 UTC by jsjtxietian

Fixes https://github.com/godotengine/godot/issues/86070

It's a regression because https://github.com/godotengine/godot/commit/5acf6b4ca6360bb53a4f67bde207a730170d00b2  changed  `node_state.connections.clear()` to `p_node->node_state.connections.clear()` , previously the crash can be prevented by null check in `_blend_node` .

2024-02-11 12:49 UTC, TokageItLab requested changes
It looks like the null check in the first line of `_blend_node()` could be removed, as it would be a duplicate check. If so, does it cause a problem that there is no check on the call within `blend_input()`?

2024-02-11 12:49 UTC, TokageItLab commented on scene/animation/animation_tree.cpp
> +	ERR_FAIL_COND_V(!p_node.is_valid(), 0);
```suggestion
	ERR_FAIL_COND_V(p_node.is_null(), 0);
```

2024-02-15 13:25 UTC, jsjtxietian commented
> If so, does it cause a problem that there is no check on the call within `blend_input()`

Reading the code, it looks like the provided `p_node` must be a valid one.

2024-02-20 11:10 UTC, akien-mga commented
> It looks like the null check in the first line of `_blend_node()` could be removed, as it would be a duplicate check. If so, does it cause a problem that there is no check on the call within `blend_input()`?

`_blend_node()` is also called in other places. Those would also need a check if we're removing it from `_blend_node` itself:
```
scene/animation/animation_blend_tree.cpp
1410:   return _blend_node(output, "output", this, pi, FILTER_IGNORE, true, p_test_only, nullptr);

scene/animation/animation_tree.h
87:     double _blend_node(Ref<AnimationNode> p_node, const StringName &p_subpath, AnimationNode *p_new_parent, AnimationMixer::PlaybackInfo p_playback_info, FilterAction p_filter = FILTER_IGNORE, bool p_sync = true, bool p_test_only = false, real_t *r_activity = nullptr);

scene/animation/animation_tree.cpp
146:    double ret = _blend_node(node, node_name, nullptr, p_playback_info, p_filter, p_sync, p_test_only, &activity);
157:    return _blend_node(p_node, p_subpath, this, p_playback_info, p_filter, p_sync, p_test_only, nullptr);
```

2024-02-20 13:03 UTC, jsjtxietian commented
> Those would also need a check if we're removing it from `_blend_node` itself:

I'm not 100% sure about the logic here. But like I said earlier, from the code, the other places calling `_blend_node` seems all get the AnimationNode reference from the `nodes` in defined in `AnimationNodeBlendTree`, which seems to be assumes the it's always have a valid node.

But there's no harm in adding more checkes I guess, or just keep the check inside  `_blend_node`

2024-02-21 13:28 UTC, TokageItLab commented
I prefer to add more two checks to

animation_tree.cpp line 167:
```cpp
	Ref<AnimationNode> node = blend_tree->get_node(node_name);
	ERR_FAIL_COND_V (node .is_null ( ), NodeTimeInfo());

	real_t activity = 0.0;
	Vector<AnimationTree::Activity> *activity_ptr = process_state->tree->input_activity_map.getptr(node_state.base_path);
	NodeTimeInfo nti = _blend_node(node, node_name, nullptr, p_playback_info, p_filter, p_sync, p_test_only, &activity);

	if (activity_ptr && p_input < activity_ptr->size()) {
		activity_ptr->write[p_input].last_pass = process_state->last_pass;
		activity_ptr->write[p_input].activity = activity;
	}
	return nti;
```

animation_blend_tree.cpp line 1635:
```cpp
AnimationNode::NodeTimeInfo AnimationNodeBlendTree::_process(const AnimationMixer::PlaybackInfo p_playback_info, bool p_test_only) {
	Ref<AnimationNodeOutput> output = nodes[SceneStringNames::get_singleton()->output].node;
	node_state.connections = nodes[SceneStringNames::get_singleton()->output].connections;
	ERR_FAIL_COND_V (output .is_null ( ), NodeTimeInfo());

	AnimationMixer::PlaybackInfo pi = p_playback_info;
	pi.weight = 1.0;

	return _blend_node(output, "output", this, pi, FILTER_IGNORE, true, p_test_only, nullptr);
}
```

2024-02-22 05:08 UTC, TokageItLab approved these changes

2024-02-22 10:25 UTC, merged

2024-02-22 10:27 UTC, akien-mga commented
Thanks!