OS_Unix: Makes SIGCHLD handler wait only for stored pids
godotengine/godot pull request #8648
Opened 2017-05-05 00:03 UTC by neikeq

This way, #8310 won't need any modifications to `OS_Unix::execute` and almost no modifications to the forkfd thirdparty. Also now it's possible to use #8310 as a module, which will allow me to use it in GodotSharp without waiting for it to be merged.

2017-06-19 21:41 UTC, reduz requested changes

2017-06-19 21:41 UTC, reduz commented on core/safe_refcount.h
> +
please add these in the .cpp like the other functions above, so we avoid namespace pollution with the windows.h include

2017-07-11 09:13 UTC, akien-mga commented
Bump.

2017-07-13 20:54 UTC, neikeq commented
This only made sense if #8310 were to get merged.

2017-07-13 20:54 UTC, closed without merging