Fix `ScriptLanguageExtension::_find_function` documentation
godotengine/godot pull request #86520
Opened 2023-12-26 11:29 UTC by touilleMan

`ScriptLanguageExtension::_find_function` documentation is currently wrong when compared to it GDScript implementation: 
https://github.com/godotengine/godot/blob/13a0d6e9b253654f5cc2a44f3d0b3cae10440443/modules/gdscript/gdscript_editor.cpp#L212

2023-12-26 11:59 UTC, AThousandShips requested changes
This can't be changed like this, the binding is here:
https://github.com/godotengine/godot/blob/13a0d6e9b253654f5cc2a44f3d0b3cae10440443/core/object/script_language_extension.cpp#L110

Not in `GDScript`, which *isn't* a `ScriptLanguageExtension` but a `ScriptLanguage` in the first place

The discrepancy is an issue, but this will not be a valid fix as the documentation generation won't match

2023-12-26 12:04 UTC, AThousandShips commented
The problem here is that I don't know that this can be changed without breaking compatibility with extensions, I'm not sure if these bound arguments are compatibility relevant for other languages and binds

2023-12-26 13:05 UTC, touilleMan commented
> This can't be changed like this, the binding is here:

You're right I should have modified this part too ! (I've updated my PR)

> Not in GDScript, which isn't a ScriptLanguageExtension but a ScriptLanguage in the first place

True, I was pointing out `GDScript` given it is the standard `ScriptLanguage`, and `ScriptLanguageExtension` is just a wrapper over `ScriptLanguage`.

The keypoint is that `ScriptLanguageExtension` exposes a `_find_function` method that is used to implement `ScriptLanguage::find_function`:
https://github.com/godotengine/godot/blob/13a0d6e9b253654f5cc2a44f3d0b3cae10440443/core/object/script_language_extension.h#L374

So in the end, `ScriptLanguageExtension::_find_function` should have the same signature as `ScriptLanguage::find_function`.

> The problem here is that I don't know that this can be changed without breaking compatibility with extensions

The fix is only on the name of the parameters, are you sure this breaks compatibility ?

2023-12-26 15:04 UTC, AThousandShips commented
> The fix is only on the name of the parameters, are you sure this breaks compatibility ?

I'm not sure, that's why I said "I don't know if this can be done without breaking compatibility" 🙂

CC @dsnopek

2023-12-26 15:16 UTC, dsnopek approved these changes
> I don't know that this can be changed without breaking compatibility

Yeah, I think this is fine! It doesn't change how the arguments are used, only their names. From the perspective of GDExtension, arguments are only positional, the names aren't significant.

2023-12-26 15:18 UTC, AThousandShips approved these changes

2024-01-02 17:06 UTC, merged

2024-01-02 17:09 UTC, akien-mga commented
Thanks!