Add warning for using concave shape on CharacterBody3D
godotengine/godot pull request #86576
Opened 2023-12-28 12:41 UTC by bikemurt

As per #86574 

Tested a simple scene to confirm that ConcaveShapes do not work for collisions on CharacterBody3D (same as RigidBody3D).

Added the following node config warning:
![image](https://github.com/godotengine/godot/assets/23486102/7688733d-c514-4ef8-a718-39b3dd4014cc)

I didn't update the language documentation as I assume that's handled separately

2023-12-28 12:44 UTC, AThousandShips requested changes, later dismissed
This wording isn't correct, it should be more clear, `CharacterBody3D` does support this shape, it just isn't recommended:
> When used for collision, ConcavePolygonShape3D is intended to work with static [CollisionShape3D](https://docs.godotengine.org/en/stable/classes/class_collisionshape3d.html#class-collisionshape3d) nodes like [StaticBody3D](https://docs.godotengine.org/en/stable/classes/class_staticbody3d.html#class-staticbody3d) and will likely not behave well for [CharacterBody3D](https://docs.godotengine.org/en/stable/classes/class_characterbody3d.html#class-characterbody3d)s or [RigidBody3D](https://docs.godotengine.org/en/stable/classes/class_rigidbody3d.html#class-rigidbody3d)s in a mode other than Static.

The warning should match the one for `RigidBody3D` instead

2023-12-28 12:49 UTC, milkiq commented
> ConcavePolygonShape3D doesn't support RigidBody3D in another mode than static.

RigidBody3D uses this wording, so would we change both of them?

2023-12-28 12:52 UTC, bikemurt commented
> > ConcavePolygonShape3D doesn't support RigidBody3D in another mode than static.
> 
> RigidBody3D uses this wording, so would we change both of them?

Initially I found this description to be wordy, but I see what @AThousandShips is saying - you _can_ use concave shapes, it just won't work with moving bodies.

2023-12-28 12:55 UTC, AThousandShips commented
The warning should be descriptive, so it shouldn't be changed for `RigidBody3D` IMO, but both could be updated, on second thought I'm not 100% sure what is meant by the static mode here, *or* if it applies to both types, the documentation for the shape should probably be improved to clarify this 🙂

I would suggest to update both descriptions to be clearer that it's not recommended to use these

2023-12-28 13:04 UTC, AThousandShips commented
The physics team would have to confirm but I think the documentation for the shape needs to be made more clear, something like:
> When used for collision, ConcavePolygonShape3D is intended to work with static CollisionShape3D nodes like StaticBody3D and will likely not behave well for or RigidBody3Ds (except when frozen and freeze_mode set to FREEZE_MODE_STATIC) or CharacterBody3Ds.

Or something like that

And then change all the wordings here to align with that, saying something like "not recommended"

2023-12-28 13:15 UTC, bikemurt commented
I just did a little bit of testing by using a RigidBody3D (with convex collision shape) and pushing it into a RigidBody3D and CharacterBody3D.

When the RigidBody3D is set to freeze/static, the concave shape does actually work for collisions. It behaves exactly like a StaticBody3D in that case.

I think CharacterBody3D does not work at all with a concave collision shape (as far as I can tell). It doesn't interact with a StaticBody3D (my floor) or the RigidBody3D with a convex shape.


> > When used for collision, ConcavePolygonShape3D is intended to work with static CollisionShape3D nodes like StaticBody3D and will likely not behave well for or RigidBody3Ds (except when frozen and freeze_mode set to FREEZE_MODE_STATIC) or CharacterBody3Ds.

I like this.  Could split out the description for RigidBody3D and CharacterBody3D:

RigidBody3D:

`When used for collision, ConcavePolygonShape3D is intended to work with static CollisionShape3D nodes like StaticBody3D and will likely not behave well for or RigidBody3Ds (except when frozen and freeze_mode set to FREEZE_MODE_STATIC).`

CharacterBody3D:

`When used for collision, ConcavePolygonShape3D is intended to work with static CollisionShape3D nodes like StaticBody3D and will likely not behave well for CharacterBody3Ds.`

2023-12-28 13:25 UTC, bikemurt commented
Here's what I have for now. Also added a new line so it looks a little cleaner:

![image](https://github.com/godotengine/godot/assets/23486102/53b7aefa-55ba-44d3-ab49-a564101f9ba4)

2023-12-28 13:42 UTC, milkiq commented
> Here's what I have for now. Also added a new line so it looks a little cleaner:这是我现在所拥有的。还添加了一个新行，因此看起来更干净一些：
> 
> ![image](https://private-user-images.githubusercontent.com/23486102/293213287-53b7aefa-55ba-44d3-ab49-a564101f9ba4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzAzOTQsIm5iZiI6MTcwMzc3MDA5NCwicGF0aCI6Ii8yMzQ4NjEwMi8yOTMyMTMyODctNTNiN2FlZmEtNTViYS00NGQzLWFiNDktYTU2NDEwMWY5YmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEzMjgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZTAyYzM3MGFhYTE4YThkZDhiYmM3YmM1N2FiNGQyYmViODAxZDRmNjEyMmQzNzExNzA3Y2Y5MWRjYjE5MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TpbhUKXusAiv4bpVViOKIIDrFJOV5kf5t8bzK0b6GZA)

It's looks nice! Easier to understand than before

2023-12-28 14:25 UTC, AThousandShips commented on scene/3d/collision_shape_3d.cpp
> +			warnings.push_back(RTR("When used for collision, ConcavePolygonShape3D is intended to work with static CollisionShape3D nodes like StaticBody3D. \nIt will likely not behave well for or RigidBody3D
```suggestion
			warnings.push_back(RTR("When used for collision, ConcavePolygonShape3D is intended to work with static CollisionObject3D nodes like StaticBody3D.\nIt will likely not behave well for RigidBody3Ds (except when frozen and freeze_mode set to FREEZE_MODE_STATIC)."));
```
The documentation uses the wrong type here, should be fixed along with updating that wording

2023-12-28 14:25 UTC, AThousandShips commented on scene/3d/collision_shape_3d.cpp
> +			warnings.push_back(RTR("When used for collision, ConcavePolygonShape3D is intended to work with static CollisionShape3D nodes like StaticBody3D. \nIt will likely not behave well for CharacterBody3
```suggestion
			warnings.push_back(RTR("When used for collision, ConcavePolygonShape3D is intended to work with static CollisionObject3D nodes like StaticBody3D.\nIt will likely not behave well for CharacterBody3Ds."));
```

2024-01-01 17:53 UTC, Calinou reviewed
I suggest adding the same warning for VehicleBody3D and VehicleWheel3D, as these have the same constraints due to their dynamic nature.

2024-01-01 19:04 UTC, AThousandShips commented on scene/3d/collision_shape_3d.cpp
> +		if (Object::cast_to<VehicleBody3D>(col_object)) body_type = "VehicleBody3D";
```suggestion
		if (Object::cast_to<VehicleBody3D>(col_object)) {
			body_type = "VehicleBody3D";
		}
```

2024-01-01 19:05 UTC, bikemurt commented
> I suggest adding the same warning for VehicleBody3D and VehicleWheel3D, as these have the same constraints due to their dynamic nature.

Makes sense. I took another look, and it appears that VehicleBody3D is (currently) the only node that inherits RigidBody3D. So I updated the code to use a string substitution in the RTR - not sure if we prefer writing out the strings verbosely.

Also, to me it seems that VehicleWheel3D shouldn't have a CollisionShape3D added to it since it doesn't inherit CollisionObject3D, so I didn't add a warning for that.

2024-01-03 17:18 UTC, Calinou approved these changes
Tested locally, it works as expected.

2024-01-04 10:05 UTC, AThousandShips approved these changes

2024-01-04 10:11 UTC, akien-mga commented
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

2024-01-04 14:35 UTC, bikemurt commented
Sorry - missed that in the documentation for amending commits. Will do it that way next time

2024-01-04 15:40 UTC, merged

2024-01-04 15:41 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: