Clarify the FOV setting in the 3D editor camera is vertical FOV
godotengine/godot pull request #86690
Opened 2024-01-01 16:43 UTC by Calinou

*Happy new year* :slightly_smiling_face:

## Preview

![image](https://github.com/godotengine/godot/assets/180032/7cd3e745-88f1-417b-b8f3-6fc564b712a8)

2024-01-27 02:40 UTC, ryevdokimov commented
It should be clarified here as well: 
![image](https://github.com/godotengine/godot/assets/105675984/c59ca189-5436-4615-b293-59ac3d065bab)

2024-01-27 18:18 UTC, Calinou commented
> It should be clarified here as well:

Done :slightly_smiling_face:

2024-01-27 18:27 UTC, Mickeon approved these changes
It's good to know!

2024-01-27 18:27 UTC, Mickeon commented on doc/classes/EditorSettings.xml
> +			[b]Note:[/b] The editor camera always uses the Keep Height aspect mode.
It's not exactly clear what this is referring to at a glance. May be worth surrounding this in quotes? 
```suggestion
			[b]Note:[/b] The editor camera always uses the "Keep Height" aspect mode.
```

2024-01-27 18:27 UTC, Mickeon commented on doc/classes/EditorSettings.xml
> +			The default camera vertical field of view to use in the 3D editor (in degrees). The camera field of view can be adjusted on a per-scene basis using the [b]View[/b] menu at the top of the 3D editor
While you're here:
```suggestion
			The default camera vertical field of view to use in the 3D editor (in degrees). The camera field of view can be adjusted on a per-scene basis using the [b]View[/b] menu at the top of the 3D editor. If a scene had its camera field of view adjusted using the [b]View[/b] menu, this setting is ignored in the scene in question. This setting is also ignored while a [Camera3D] node is being previewed in the editor.
```

2024-01-27 18:29 UTC, Mickeon commented on editor/plugins/node_3d_editor_plugin.cpp
> +	settings_fov->set_tooltip_text(TTR("The editor camera always uses the Keep Height aspect mode, so FOV is defined as a vertical value."));
Forgot to insert in the review. The latter sentence is much more "of interest" to the user than the former.
```suggestion
	settings_fov->set_tooltip_text(TTR("FOV is defined as a vertical value. The editor camera always uses the Keep Height aspect mode."));
```
Or similar

2024-01-27 18:40 UTC, ryevdokimov commented
I'm not my reviews show up for anyone, so I'll leave a comment. Sorry if it's redundant. 

I think the lower case "v" in vertical is a bit odd, and inconsistent with the rest of the editor. Making it capital or saying VFOV (which is an appropriate term) would look better IMO.

2024-01-27 18:45 UTC, Mickeon commented
> I'm not sure my reviews show up for anyone, since I'm not a member and they're not visible when I'm not logged in,

Any user can review, add comments and request changes! It should work completely fine. You may have forgotten to submit your review (there's a big green button on the top right of the files tab), as they are not showing up to anyone.

2024-01-27 18:47 UTC, ryevdokimov requested changes

2024-01-27 18:48 UTC, ryevdokimov commented
Hah, doy. Thank you.

2024-01-27 19:00 UTC, Mickeon commented on editor/plugins/node_3d_editor_plugin.cpp
> +	settings_vbc->add_margin_child(TTR("Perspective vertical FOV (deg.):"), settings_fov);
I agree but for a different reason. I'm more concerned on how much horizontal space the text takes (the other Viewport settings are much shorter in comparison).

2024-01-31 00:24 UTC, ryevdokimov approved these changes
Looks good.

2024-01-31 08:41 UTC, Mickeon approved these changes

2024-01-31 10:09 UTC, merged

2024-01-31 10:13 UTC, akien-mga commented
Thanks!