Hide Keystore Release password on Android's Export window
godotengine/godot pull request #86882
Opened 2024-01-06 14:46 UTC by Mickeon

Resolves https://github.com/godotengine/godot-proposals/issues/8813

<img src=https://i.gyazo.com/344608dcdfa531d5cb3df4026f255b2f.gif>

2024-01-06 17:31 UTC, m4gr3d requested changes

2024-01-06 17:31 UTC, m4gr3d commented on platform/android/export/export_plugin.cpp
> +	r_options->push_back(ExportOption(PropertyInfo(Variant::STRING, "keystore/release_password", PROPERTY_HINT_PASSWORD, "", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_SECRET), ""));
The change makes sense! 

For consistency, can you update the export debug password and the debug password in the editor settings to match.

2024-01-06 17:40 UTC, Mickeon commented
Updated the PR with the above requests

2024-01-06 17:40 UTC, Mickeon commented
Updated the PR with the above requests

2024-01-06 17:49 UTC, m4gr3d approved these changes
Looks good!

2024-01-08 11:10 UTC, merged

2024-01-08 11:15 UTC, akien-mga commented
Thanks!