Tweak Timer documentation
godotengine/godot pull request #87436
Opened 2024-01-21 09:53 UTC by Mickeon

Meant to close https://github.com/godotengine/godot-docs/issues/8543

Related to [several other past efforts](https://github.com/godotengine/godot/pulls?q=is%3Apr+author%3AMickeon+overhaul+).

This PR
The Timer is such a simple Node that adding anything more of substance is extremely difficult. Still, the documentation could use a touch of consistency because:
- it feels like it was written by 3 different people, with different words used to refer to the same concept.
- `process_callback`'s description says nothing,
- The `wait_time` note is overly verbose.

This PR originally also reworked the leading description of the class. However, I was not happy with it, and I'm not sure WHAT should be said, so that's postponed for later to not have this as a draft for 3 more weeks. If I am satisfied, this PR will be updated accordingly.

2024-01-29 00:56 UTC, skyace65 requested changes
One minor issue, but other than that this looks great!

2024-01-29 00:56 UTC, skyace65 commented on doc/classes/Timer.xml
> +			If [code]true[/code], the timer will start immediately when it enters the scene tree.
```suggestion
			If [code]true[/code], the timer will start immediately when it enters the scene tree.
```

2024-01-29 09:09 UTC, Mickeon commented
Should be good now.

2024-01-31 00:07 UTC, skyace65 approved these changes

2024-01-31 00:17 UTC, Calinou commented on doc/classes/Timer.xml
> +				[b]Note:[/b] This method does not resume a paused timer. See [member paused].
I suggest reducing the number of paragraphs to make the description more compact:

```suggestion
				Starts the timer, if it was not started already. Fails if the timer is not inside the tree. If [param time_sec] is greater than [code]0[/code], this value is used for the [member wait_time].
				[b]Note:[/b] This method does not resume a paused timer. See [member paused].
```

2024-01-31 00:17 UTC, Calinou approved these changes
Looks good to me.

2024-01-31 10:09 UTC, merged

2024-01-31 10:10 UTC, akien-mga commented
Thanks!