Separate iterators, small internal changes
godotengine/godot pull request #87794
Opened 2024-01-31 19:01 UTC by dimkKy

Both `LocalVector` and `Vector` now use the same `VectorIterator` defined in STL-algorithms-compatible `vector_iterator.h` ([#86573](https://github.com/godotengine/godot/pull/86573) included)

`LocalVector` `if(tight)` checks are now [compile-time](https://godbolt.org/z/W1YcrK1aY), and `remove_at()` and `insert()` now use `std::memmove()` for _trivially copyable_ types to shift data.

2024-01-31 19:03 UTC, AThousandShips requested changes, later dismissed
Using aspects of the STL library isn't allowed, this includes the `<iterator>` library, we don't need these iterators to be compliant

2024-01-31 19:04 UTC, AThousandShips commented on core/templates/local_vector.h
> +			constexpr auto new_cap = [](U p_cap) noexcept {
Don't use lambda unless absolutely necessary, see [here](https://docs.godotengine.org/en/latest/contributing/development/cpp_usage_guidelines.html#lambdas)

2024-01-31 19:13 UTC, AThousandShips commented on core/templates/local_vector.h
> +		constexpr auto new_size = [](U _p_size) noexcept {
Same here

2024-01-31 19:13 UTC, AThousandShips commented on core/templates/local_vector.h
> +			std::memmove(&data[p_index], &data[p_index + 1],
I'm not sure this is a good change, and again using the standard library

2024-01-31 19:13 UTC, AThousandShips commented on core/templates/local_vector.h
> +	_FORCE_INLINE_ Iterator begin() { return { data }; }
```suggestion
	_FORCE_INLINE_ Iterator begin() { return data; }
```
Unnecessary and hurts readability, same for all

2024-01-31 19:13 UTC, AThousandShips commented on core/templates/local_vector.h
> +				std::memmove(&data[p_index + 1], &data[p_index],
Same here about STL

2024-01-31 19:13 UTC, AThousandShips commented on core/templates/local_vector.h
> +		for (U i = p_from; i < count; ++i) {
Revert these, unnecessary changes 🙂

2024-01-31 19:13 UTC, AThousandShips commented on core/templates/vector_iterator.h
> +	reference operator*() const noexcept { return *elem_ptr; }
No need for all the `noexcept` as we don't even use exceptions
```suggestion
	reference operator*() const { return *elem_ptr; }
```

2024-01-31 19:17 UTC, AThousandShips commented
Thank you for your contribution! This looks interesting, but needs quite a bit of change to follow our style and use rules, if you need more help please ask 🙂

For style see [here](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html)

2024-01-31 19:27 UTC, AThousandShips commented on core/templates/local_vector.h
> +			std::memmove(&data[p_index], &data[p_index + 1],
Then I'd say to use the non-prefix version for clarity 🙂, then it's fine

2024-02-01 01:25 UTC, dimkKy commented
I have applied suggested changes, thank you for the quick response. However I do think `iterator_tag` should stay

2024-02-01 01:36 UTC, dimkKy commented
Looks like formatter broke some tabs, will fix it later

2024-02-01 08:50 UTC, AThousandShips commented
That's fine, I'll keep my "changes requested" for now, if someone on the core team approves this as it is I'll remove that, but I still think that the addition of the `<iterator>` part is unnecessary and does nothing for the engine, as it is only useful for components that we don't use

2024-02-01 09:22 UTC, AThousandShips commented
Will do a deeper dive later but my first pointers are:
* I'm unsure about the consequences of adding new templates, I worry that adding two new template declarations to pollute the name system for each pair of `Vector/LocalVector`, I'm not sure but I think it might be worse than just the names inside those types, like `Vector<T>::Iterator`
* I'm not sure about the inheritance of the two iterator types, I'd prefer them as two independent classes

One idea I just realized that might resolve all this but leave everything unchanged but improving code unification is this:
Create a macro instead, make a macro for the whole iterator and then use them in the two classes

That effectively keeps things as they were for the most part, but reduces duplication

And finally I'd suggest splitting this into two PRs, the other changes are unrelated to the iterators, and is best reviewed as a separate improvement, so please separate the iterator improvements from the allocation and memory rearrangements, this is a general preference for improvements to the engine 🙂

And thank you for your work on this in any case, it's very interesting and I think at least some of the memory related changes might well be included, even if the iterators aren't (another reason to split it up)

2024-02-01 14:59 UTC, AThousandShips commented
Not sure about the force trivial part

What I mean with the namespace is that you now add `VectorIterator<T>` as a name in the global namespace, which is not always desired, they make debug data larger

2024-02-17 00:06 UTC, dimkKy commented
Splitted into [#88420](https://github.com/godotengine/godot/pull/88420) and [#87794](https://github.com/godotengine/godot/pull/88422).

2024-02-17 00:06 UTC, closed without merging