Update Range.xml: fix incorrect default value for `step`
godotengine/godot pull request #87865
Opened 2024-02-02 13:20 UTC by MJacred

Unless there's a hidden change from `1.0` to `0.01`, the correct default value is `1.0`.

See https://github.com/godotengine/godot/blob/10e111477db68fe65776a1d68fb1ffccaf6520fc/scene/gui/range.h#L43

2024-02-02 13:28 UTC, MJacred commented
I don't see how the change could fail the Linux w/Mono check and cause an 
```
ERROR: unimplemented base type encountered in renderer scene cull
   at: instance_set_base (servers/rendering/renderer_scene_cull.cpp:636)
```

2024-02-02 13:48 UTC, Mickeon commented
No, the default values are generated by the class reference generator and you shouldn't touch them this way. You need to override the value manually in `_bind_methods` to make it an exception to the norm.
**RandomNumberGeneration** does this:
https://github.com/godotengine/godot/blob/10e111477db68fe65776a1d68fb1ffccaf6520fc/core/math/random_number_generator.cpp#L49-L51

2024-02-02 14:05 UTC, MJacred commented
@Mickeon: the class reference guides for contribution say nothing about this. And I see only a handful uses of `ADD_PROPERTY_DEFAULT`. I also don't see where it could get the `0.01` from.  
Perhaps the class reference generator (wherever it is) cannot read that value because it's not in the class, but rather in a struct within the class...

Should I close the PR?

2024-02-02 14:06 UTC, AThousandShips commented
It seems that it might be due to some delay in the generation, as the actual value even when constructing it is `1`, but this is likely a larger, more complex issue to solve

2024-02-02 14:40 UTC, Mickeon commented
> the class reference guides for contribution say nothing about this

Yyyyyeah, it doesn't say _many_ things. It could use a refresher someday... 📝

> Should I close the PR?

If you change it to use **ADD_PROPERTY_DEFAULT** I don't see a reason to. Right now the PR does not work as you may think, because the doc generation will always want to override it.
If you do make the change, you should probably comment the reason on the side.

> There might also be other cases that change with this, so needs a deeper investigation, if necessary

True, but the same could be said for other classes that use the macro. I mentioned **RandomClassGenerator** because it is the most obvious exception.
Other ones worth noting:
https://github.com/godotengine/godot/blob/9adb7c7d130c6d4eb0e80b92d6eebd71fac3384d/scene/2d/collision_shape_2d.cpp#L286-L287
https://github.com/godotengine/godot/blob/10e111477db68fe65776a1d68fb1ffccaf6520fc/servers/audio_server.cpp#L1767-L1769

Very few are not as obvious:

https://github.com/godotengine/godot/blob/10e111477db68fe65776a1d68fb1ffccaf6520fc/modules/multiplayer/scene_multiplayer.cpp#L679
https://github.com/godotengine/godot/blob/10e111477db68fe65776a1d68fb1ffccaf6520fc/scene/2d/tile_map.cpp#L1255

2024-02-02 14:42 UTC, AThousandShips commented
I meant that this might be a bug in the doctool, which has other cases like this

2024-02-18 16:23 UTC, Mickeon requested changes
See discussion above. I think an **ADD_PROPERTY_DEFAULT** for this would be fine (above it should be documented why it is inserted). At worst it can be re-evaluated later.

2024-02-18 16:27 UTC, MJacred commented
@Mickeon: I reserved some time tomorrow evening to change and test it

2024-02-19 19:48 UTC, Mickeon commented on scene/gui/range.cpp
> +	// Default values are non-deterministic, override for doc generation purposes.
This is not true, that's for RNG.
```suggestion
	// Default value would be 0.01 otherwise, override for doc generation purposes.
```

2024-02-19 19:48 UTC, MJacred commented
Ok, I've updated the code to use `ADD_PROPERTY_DEFAULT`. But it does not work. I have no idea why. It works for others, but not here. `object.h` is indirectly included. Maybe it does not work for floats, or it does not reach `default_values` in class_db.h. No idea

And I only could get the doctool to run after commenting some code because this error was popping up 6 times:

```
ERROR: Condition "actions.default_repeat == ShaderLanguage::REPEAT_DEFAULT" is true. Returning: String()
   at: _get_sampler_name (servers/rendering/shader_compiler.cpp:283)
```

2024-02-19 19:50 UTC, MJacred commented on scene/gui/range.cpp
> +	// Default values are non-deterministic, override for doc generation purposes.
Done

2024-02-19 20:04 UTC, MJacred commented
@akien-mga: you have used `ADD_PROPERTY_DEFAULT` before. Do you have any idea why it doesn't work here?

2024-02-19 20:55 UTC, Mickeon commented
Interesting that the checks have NOT failed, despite the default value being changed. There may either indeed be an underlying problem here.

> Why do I have the feeling it's because `step` is within `struct Shared`

Oh.

2024-02-19 21:29 UTC, KoBeWi commented
It's not a problem with the struct, but rather with Range itself being an abstract class. I'm trying to find where the default value is initialized. Since the class itself is not instantiated, the default is fetched from another class that inherits it (except none of them use `0.01`...).

2024-02-19 21:49 UTC, Mickeon commented
I wonder why that's the case and how many properties unintentionally use the wrong default value as a result?

2024-02-19 21:57 UTC, KoBeWi commented
Well, since the class can't be instantiated, ClassDB is not expected to fetch a default value, so doctools instead try to fetch the default from the inheriting classes (which might override the default). tbh abstract classes not being instantiable is an artificial limitation, as they are not abstract in C++ sense and creating instance of Range should be normally possible.

I'm not sure how to solve this *properly*. It's possible to make `ADD_PROPERTY_DEFAULT` work properly by tweaking the code I linked, but that still means manually checking for unexpected defaults and hard-coding them. Until abstract classes can be instantiated on their own, they will always be prone to accidentally using default from an inheriting class.

2024-02-27 10:12 UTC, MJacred commented
This is a bigger issue than just fixing one property in `Range`. Therefore, I opened a proposal [here](https://github.com/godotengine/godot-proposals/issues/9184), and I'm closing this PR.

2024-02-27 10:12 UTC, closed without merging