Use indeterminate progressbars for editor downloads (export templates & assets)
godotengine/godot pull request #88084
Opened 2024-02-08 00:30 UTC by ckaiser

Now that we have [indeterminate progress bars](https://github.com/godotengine/godot/pull/87318), I've implemented their use for the most obvious case: downloads.
There might be other places that could use them but it'd involve changes to `ProgressDialog` and tasks, haven't looked through that as of yet.

Before & After:

https://github.com/godotengine/godot/assets/138269/7643d5d1-dd94-441d-8a95-30d5211db6fb

https://github.com/godotengine/godot/assets/138269/1184a474-176f-4311-b7ab-0de7bd8de632

---

https://github.com/godotengine/godot/assets/138269/5eab6a2d-7eef-43d3-8613-63170d2ea826

https://github.com/godotengine/godot/assets/138269/ddec0abd-18a9-4813-a286-e7f791e2d575

(I was connected to a slow VPN for testing I swear I'm not on dial-up or something 😅)

2024-02-08 10:13 UTC, Calinou requested changes
Tested locally, there's an issue with the editor redrawing constantly when a progress bar from the asset library is visible, even if it's not currently indeterminate:

https://github.com/godotengine/godot/assets/180032/0679b415-2d17-4926-861d-db968018ec0f

You can check this locally by enabling **Show Update Spinner** in the editor settings or starting the editor with the `--debug-canvas-item-redraw` command line argument.

2024-02-08 14:12 UTC, ckaiser commented
Fixed the redraw issue

2024-02-08 15:43 UTC, Calinou approved these changes
Tested the export template downloader and asset library download, they both work as expected now.

2024-02-09 11:37 UTC, merged

2024-02-09 11:37 UTC, akien-mga commented
Thanks!