Fix `TabBar` size when theme changes
godotengine/godot pull request #88293
Opened 2024-02-13 17:50 UTC by WhalesState

Fixes: https://github.com/godotengine/godot/issues/87511

2024-02-13 17:58 UTC, YeldhamDev requested changes
Should be

2024-02-13 17:58 UTC, YeldhamDev commented on scene/gui/tab_bar.cpp
>  			queue_redraw();
```suggestion
			queue_redraw();
			update_minimum_size();
```

2024-02-13 19:38 UTC, YeldhamDev approved these changes

2024-02-13 22:53 UTC, merged

2024-02-13 22:54 UTC, akien-mga commented
Thanks!

2024-02-15 17:40 UTC, wez470 commented
Thank you!

2024-03-11 22:28 UTC, akien-mga commented
Cherry-picked for 4.2.2.