C#: Implement proper generic type name printing for Godot Editor
godotengine/godot pull request #88363
Opened 2024-02-15 14:16 UTC by Delsin-Yu

The current Godot Editor Implementation fetches a class_name directly from the `System.Type.Name`, which does not return the full definition of a generic type (only the generic parameter count).

This PR uses an algorithm created by @ZerxZ, @TML233, and @jinsediaoying for printing the actual underlying generic type definition.
Our [tests](https://github.com/Delsin-Yu/System.Type.PrettyPrint/blob/main/GenericCSharpProgram.Test/Tests.cs) have convinced us this algorithm is capable of handling all generic use cases, see the following comparison.
This only runs under `DEBUG` (fallback to `System.Type.Name` otherwise), so it should not affect runtime performance.

|Before|After|
|:---|:---|
|![image](https://github.com/godotengine/godot/assets/71481700/07d5ad77-b407-4f22-a88d-b3dd7c3feae3)|![image](https://github.com/godotengine/godot/assets/71481700/a93d562d-da56-4ac1-b90e-9ded69536374)|

These are the actual type header definitions in the scripts
```csharp
public partial class ListItemComponent<TData> : Control { /*other*/ }

public partial class ComplexCrazyListItemComponent<T1, T2, T3, T4> : ListItemComponent<(int, float, (List<Func<List<Dictionary<List<int?>, List<int?[,,]>>>, List<(List<int>, List<int[]>)?>>>, List<int[,,][,][,,,,]>))?> { /*other*/ }

public partial class Test<T> : ComplexCrazyListItemComponent<int, float, GodotObject, List<int>> { /*other*/ }

public partial class Test2 : Test<GodotObject> { /*other*/ }
```

2024-05-16 06:29 UTC, Delsin-Yu commented on modules/mono/glue/GodotSharp/GodotSharp/Core/ReflectionUtils.cs
> +        _isEditorHintCached = Engine.IsEditorHint();
Sure, I just want to minimize the allocation possible.

2024-05-16 06:32 UTC, Delsin-Yu commented on modules/mono/glue/GodotSharp/GodotSharp/Core/ReflectionUtils.cs
> +    [ThreadStatic] private static StringBuilder? _typeNameBuilder;
Sure, I just want to minimize the per-call allocations for this new approach, but since it's editor-only, I guess that's not that much of a deal.

2024-05-16 06:38 UTC, Delsin-Yu commented on modules/mono/glue/GodotSharp/GodotSharp/Core/ReflectionUtils.cs
> +    private static readonly Dictionary<Type, string>? _builtinTypeNameDictionary;
But this will cause these two collections to initialize even in runtime (which they are unused at all).

2024-05-19 12:01 UTC, Delsin-Yu commented
I removed the cached `StringBuilder` and optimized the `while(true)` section; however, I think we need a consensus on whether we should cache the `IsEditorHint` or initialize `_builtinTypeNameDictionary` `_tupleTypeSet` by default.

I wish to minimize the performance impact on runtime by this PR, where `IsEditorHint` calls back to the native code base (which is expensive compared to a check on cached boolean), and two collections are never called in runtime so that I don't think we should initialize them at all.

2024-09-22 15:27 UTC, raulsntos requested changes
The .NET team discussed this and we think it's a good addition. The technical aspects look good, this is a code-style review.

2024-09-22 15:29 UTC, raulsntos commented on modules/mono/glue/GodotSharp/GodotSharp/Core/ReflectionUtils.cs
> +        _isEditorHintCached = Engine.IsEditorHint();
I don't know if it makes a big difference, and AFAIK this would only run in the editor anyway. But it's fine.

2024-09-22 19:19 UTC, raulsntos commented on modules/mono/glue/GodotSharp/GodotSharp/Core/ReflectionUtils.cs
> +
```suggestion
```

2024-09-23 11:47 UTC, raulsntos approved these changes
Looks good to me and works as expected. Thanks!

2024-09-24 11:09 UTC, merged

2024-09-24 11:10 UTC, akien-mga commented
Thanks!