Fix Skeleton 3D insert key tooltip
godotengine/godot pull request #88386
Opened 2024-02-16 02:47 UTC by skyace65

Original text looks like it was written by someone in the middle of a stroke. This PR fixes that. Closes [#](https://github.com/godotengine/godot-docs/issues/8957).

2024-02-16 05:35 UTC, hunterbk commented
Does the button only key rotations, or also translations? If it's only rotations, that button was even more severely mislabeled than I originally thought

2024-02-16 07:29 UTC, fire approved these changes

2024-02-16 07:32 UTC, fire requested changes, later dismissed
I suspect something is wrong.

I think this refers to keyframes of loc,rot, and scale. Where does it say rotation only?

2024-02-16 07:32 UTC, fire commented on editor/plugins/skeleton_3d_editor_plugin.cpp
> +	key_insert_button->set_tooltip_text(TTR("Insert key for bone rotations with an existing track."));
```suggestion
	key_insert_button->set_tooltip_text(TTR("Insert keyframes for the bone with an existing track."));
```

2024-02-16 07:33 UTC, fire commented on editor/plugins/skeleton_3d_editor_plugin.cpp
> +	key_insert_all_button->set_tooltip_text(TTR("Insert key for all bone rotations."));
```suggestion
	key_insert_all_button->set_tooltip_text(TTR("Insert keyframes for all bone poses."));
```

2024-02-16 12:09 UTC, skyace65 commented
@fire both buttons only work for rotation, I tested that before making this PR. If they're intended to keyframe position and scale as well that's currently broken in 4.2.1. Here's a video of me using the buttons.
[Button Test.zip](https://github.com/godotengine/godot/files/14310776/Button.Test.zip)

2024-02-16 18:21 UTC, fire commented
In your video the button for rotation was selected, did you try selecting the other buttons (next to it).

2024-02-17 04:14 UTC, skyace65 commented
You were right Fire, I completely forgot about those buttons. I've updated this PR but I'd like to re-word it further tomorrow. I want to try and keep the description consistent with what we use for the key button in the toolbar for 2D scenes.

2024-02-18 15:50 UTC, skyace65 commented
Updated description again, ready for review again.

2024-07-28 19:38 UTC, KoBeWi approved these changes

2024-07-29 12:51 UTC, akien-mga commented
Needs rebase.

2024-07-30 10:36 UTC, merged

2024-07-30 10:37 UTC, akien-mga commented
Thanks!