Clarify that LightmapGI is not supported in compatibility renderer (at all)
godotengine/godot pull request #88406
Opened 2024-02-16 15:40 UTC by vaartis

The documentation currently does not mention that LightmapGI _rendering_ is not supported in the compatibility renderer. It only states the fact that baking it is not supported (thus it is possible to make an assumption that _rendering_ it is supported, while baking isn't).

I'd originally wanted to reply in https://github.com/godotengine/godot/issues/75726#issuecomment-1499752607 but appening this to documentation seemed fairly easy to do myself.

2024-02-16 16:01 UTC, Mickeon approved these changes
Good to know, to not waste the developer's time testing

2024-02-16 16:06 UTC, dsnopek commented
`LightmapGI` rendering _does_ work with the compatibility renderer - this was added in PR https://github.com/godotengine/godot/pull/85120

2024-02-16 16:13 UTC, DarioSamo commented
> `LightmapGI` rendering _does_ work with the compatibility renderer - this was added in PR #85120
> 
> EDIT: Although, I guess that is only 4.3+, which, of course, isn't released yet. If we're only targeting the docs for 4.2 and below, then it's true that it isn't supported in those versions.

And baking also works since 4.3+ too, the host system just needs to be able to run Vulkan at the moment. I feel the documentation should reflect the current state of the feature.

2024-02-16 16:27 UTC, Mickeon commented
Pretend I retracted my approval until the documentation is changed accordingly.

Unless this PR is allowed to _specifically target 4.2 but that would be a major, major exception.

2024-02-16 16:30 UTC, DarioSamo commented
Yeah upon looking at the history, this would seem to overwrite what efb1cbaad40b910dbb39d35c896bbe27cb782e49 does, which is Clay adding specifically that the feature currently works if you can run a Vulkan renderer even while in compatibility mode.

2024-02-16 16:35 UTC, Mickeon requested changes
See above (yippie).

2024-02-17 09:08 UTC, vaartis commented
It would still be nice if this was at least in 4.2.2, if possible. Which I think is still yet to have a release and will not have LightmapGI.

2024-02-17 09:10 UTC, Calinou commented
> It would still be nice if this was at least in 4.2.2, if possible. Which I think is still yet to have a release and will not have LightmapGI.

In this case, you need to open a PR against the `4.2` branch as the statement will only be true for 4.2.x, not 4.3.

2024-02-17 10:03 UTC, closed without merging