Fix snapping multiple keys in Animation
godotengine/godot pull request #88498
Opened 2024-02-18 15:11 UTC by CookieBadger

Fixes an old bug, that snapped all moved keyframes in the Animation Player and Bezier editor to the same position, hence reducing a selection of keyframes to a single keyframe. 

Before:
![AnimationKeyframeSnapError](https://github.com/godotengine/godot/assets/53947784/2f445e43-0f9f-40f1-9700-01aff96db732)

![AnimationKeyframeSnapErrorBezier](https://github.com/godotengine/godot/assets/53947784/b3f1ee09-6f7a-4141-af8d-16c8c2e03b31)

After:
![AnimationKeyframeSnapErrorAfter](https://github.com/godotengine/godot/assets/53947784/f69296b9-a417-4db2-a21b-092f2badad3a)

2024-02-18 19:26 UTC, CookieBadger commented
If you are testing this, in order to test with multiple selected keyframes, need to merge #88459 first (or wait for that one to be merged, then I'll rebase this one).

2024-02-26 12:06 UTC, CookieBadger commented
This is ready for review btw, so somebody could give it a look, that'd be great :)

2024-03-07 07:13 UTC, lyuma commented
There's a weird glitch in the last gif where the top keyframe moves left before moving right. Is there a reason it appears to act differently depending on where the mouse is dragged?

I would think that snap would move the selected keyframes in units of one snap length. Though I've found snap tends to corrupt keyframes even when selecting them so I shy away from the feature in general.

2024-03-09 15:49 UTC, CookieBadger commented
@lyuma This is entirely normal and intended. When you select a keyframe and begin dragging the mouse, it snaps the key to the closest snapping point. Say you select it at t=0.6 and snapping is 0.5. Even though you move the mouse in the positive time direction, it would first snap at 0.5, hence the opposite direction of the mouse movement. Only when you move the mouse past t=0.75 it will snap the key to 1.0. This is what you observe in the gif.

2024-03-16 13:34 UTC, TokageItLab requested changes
There is a problem with keys teleporting to the mouse cursor position when dragging a key with a length. That must be fixed.

https://github.com/godotengine/godot/assets/61938263/e5504e47-470e-4e52-9eba-f7ca05f70ee6

In the preview video in description there is also a rapid movement at the start of the drag, which seems to be a problem as pointed out by lyuma. Even if that is the behavior you are assuming, it would appear to be a bug to the general user, so until that is resolved this change should not be allowed.

2024-03-16 21:45 UTC, CookieBadger commented
As for the key with a length, thanks, that is indeed very problematic. I guess the best approach would be to snap the end that is closer to the mouse to its nearest snapping point, instead of snapping the beginning of the mouse.
I also agree that the rapid movement might be unpleasant, so one fix that I thought of, is leaving the current snapping position unchanged if snapping it would move it the opposite direction of the mouse. That would result in this behavior:
![SnappingFix1](https://github.com/godotengine/godot/assets/53947784/026f2eb5-5c8b-4f42-8c2a-4813c5866d2e)
As you see, when passing back, the keys at some point snap to where they were originally. I do not think that this is a bad thing, though.
However, I do have to disagree that using only the first key for snapping would be preferred, since this leaves the user with less control, and is - in my humble opinion - unintuitive.

2024-03-16 22:59 UTC, TokageItLab commented
> But this also raises the question of whether to snap only the beginning, or snap the end that is closer to the mouse to its nearest snapping point, hence enabling snapping the end of a track. This is common in DAWs, so I thought it might be useful here. What do you think?

In the case of clicking on a blank space in a multiple selection, it is better to snap based on the first key, since it is a rough use case to click on an empty space after multiple selections. It would be uncomfortable not knowing which key will be snapped in priority when dragging just between two keys. So using the first key rather than any of them as the basis for snapping is desirable here because it is clearly consistent.

As a compromise, it is recommended to separate the operations according to whether or not you are actually clicking on the key. If you are actually pointing down/dragging a specific key in multiple selections, it is fine to snap based on that key.

2024-03-17 00:00 UTC, CookieBadger commented
There is effectively no use case for "clicking on a blank space in a multiple selection" here. You can only drag keys if you explicitly click on one, which makes perfect sense. Clicking on blank space just deselects everything. 
Regarding tracks with length, which you originally mentioned, I hope I gather correctly that you would not find snapping the end of an audio track helpful.
I may however note, that you are not responding to my second question, or at least not in a clear way. I am sure we have the same interest in getting this bug fixed that exists probably as long as snapping in the animation player, so it would be more helpful to get a solution-oriented answer here.

2024-03-17 00:18 UTC, TokageItLab commented
> I may however note, that you are not responding to my second question, or at least not in a clear way.

>> As you see, when passing back, the keys at some point snap to where they were originally. I do not think that this is a bad thing, though, but I could add a flag to prevent this behavior once the key has been moved, what do you think?

I think it doesn't make sense to snap it back to its original position.

If you are trying to implement it as a hack to prevent unintended fast key shaking at the start of a drag, you need to address the root cause of that shaking instead of doing so. Perhaps the cause may be that keys are copied and deleted individually in sequence, so changing the process so that multiple keys are deleted at the same time and added at the same time may fix the problem.

2024-03-17 02:46 UTC, CookieBadger commented
I don't think we have a clear mutual understanding of what is meant by the "shaking". I understood that you meant that the keys are snapped at positions that the user would not intend to e.g. when he moves the key in the positive time direction, but the nearest snapping point is in the negative direction. It does look weird in the GIFs I posted, but simply because I am always grabbing a keyframe that is sort of "on the edge" of two snap points, being zoomed out quite a lot. If you try the feature yourself slowly, you might notice what this issue stems from. However, there are no issues in the way keyframes are deleted or inserted, the issue that this PR fixes is simply that the insertion positions are calculated in a wrong way. However, at this point I am unsure what behavior you actually want me to implement. Maybe you want to take a look at the PR again, and reorder your thoughts.

2024-03-17 03:34 UTC, TokageItLab commented
>> There is effectively no use case for "clicking on a blank space in a multiple selection" here. You can only drag keys if you explicitly click on one, which makes perfect sense. Clicking on blank space just deselects everything.

So never mind that I was misunderstood about this.

> I don't think we have a clear mutual understanding of what is meant by the "shaking".

Shaking means that the key is shaken in an unintended direction for a moment at the start of the drag in the first video as lyuma and I said. I don't know the details of what causes that, but you must fix that behavior anyway.

> I am always grabbing a keyframe that is sort of "on the edge" of two snap points

If you are thinking of using two snap points for the entire range, I think it is not a good behavior in Godot which basically has discrete keys; You need to refer to the use case of editing keyframes in AfterEffects or Blender, not DAW. The snap points should only be held by the one key that is actually pointed down, and the other keys should only follow relative to it.

2024-03-17 03:56 UTC, TokageItLab commented
>>>  This is entirely normal and intended. When you select a keyframe and begin dragging the mouse, it snaps the key to the closest snapping point. Say you select it at t=0.6 and snapping is 0.5. Even though you move the mouse in the positive time direction, it would first snap at 0.5, hence the opposite direction of the mouse movement. Only when you move the mouse past t=0.75 it will snap the key to 1.0. This is what you observe in the gif.

I confirmed this with the old behavior, but I think the old behavior was less noticeable because it snapped individually when multiple selections were made. This PR makes it appear that all keys move in the wrong direction at the same time, so which should be fixed.

To prevent unintended movement, it seems to me that it would be better to set a special case at the first movement of the drag (the moment the abs of mouse movement value exceeds CMP_EPSILON), snap to right if it is positive, snap to left if it is negative.

2024-03-17 17:28 UTC, CookieBadger commented
I implemented a fix for both the audio track issue, and the issue of keyframes snapping against the direction of mouse movement. Feel free to test it, and let me know if this behavior was what you had in mind.

2024-03-18 00:38 UTC, TokageItLab approved these changes
Okay LGTM! Thanks for adjusting the behavior.

2024-03-18 07:25 UTC, CookieBadger commented
my pleasure! :)

2024-03-18 09:08 UTC, CookieBadger commented
I discovered there is still a small issue with reselection of the keys. Going to fix now.

2024-03-24 00:28 UTC, merged

2024-03-24 00:36 UTC, akien-mga commented
Thanks!