Force device CPU architecture for Android Remote Debug.
godotengine/godot pull request #88611
Opened 2024-02-20 23:16 UTC by Alex2782

Fixes #86284

Editor crash / freeze _(with arm32 devices)_ are prevented by selecting the correct device CPU architecture. It should also be more user-friendly. https://github.com/godotengine/godot/issues/86284#issuecomment-1941920808

2024-02-20 23:25 UTC, m4gr3d requested changes

2024-02-20 23:25 UTC, m4gr3d commented on platform/android/export/export_plugin.cpp
> +	}
We should provide a warning to the user, maybe throw an error dialog with the option to continue regardless. I don't like the idea of forcing a behavior without user consent and / or knowledge.

2024-02-23 18:56 UTC, m4gr3d approved these changes
This updated approach looks good to me!

I wonder if it's worth adding an additional `Fix and run` button to the confirm dialog to automatically add the missing architecture as your previous approach was doing, though that may make the UX looks busy.

cc @Calinou Any thoughts on the UX used in this PR?

2024-02-23 19:48 UTC, Calinou commented
> I wonder if it's worth adding an additional Fix and run button to the confirm dialog to automatically add the missing architecture as your previous approach was doing, though that may make the UX looks busy.

This should be done if we want to provide a "Run Remote Debug anyway" button, as the button is unlikely to work otherwise. This is even more the case with Android 14 and later which is no longer able to run 32-bit ARM apps on 64-bit ARM devices.

2024-02-26 09:51 UTC, merged

2024-02-26 09:51 UTC, akien-mga commented
Thanks!

2024-02-26 23:13 UTC, Alex2782 commented
`Fix and run` button maybe later (new PR).