Retargeting option to use a template for silhouette.
godotengine/godot pull request #88824
Opened 2024-02-25 16:59 UTC by lyuma

Adds `retarget/rest_fixer/silhouette_template` option to replace bone rest with an exported SkeletonProfile before retargeting.

Screenshots of workflow.
First, how to export a known good reference pose. This can be T-Pose or anything reliably fixable by Silhouette Fixer (such as A-pose)
BoneMap must not be used for the reference model. This is likely going to be the most confusing part of the process.
![import_silhouette_template](https://github.com/godotengine/godot/assets/39946030/9a8b3f74-98e4-4856-879e-9783c5779a7d)
The "Export Skeleton Profile" feature in the Skeleton3D menu already existed, but was previously only used for constructing new types of rigs. If you adjust the rest pose, make sure to use "Apply all Poses to Rest" also in the Skeleton3D menu before exporting the profile.
![export_skeleton_profile](https://github.com/godotengine/godot/assets/39946030/ba2cb7f1-c69a-4a24-b34c-04fe3bd83ab5)
This goes into a new slot for "Silhouette Template"
![using_silhouette_template](https://github.com/godotengine/godot/assets/39946030/f8123c75-2ef5-4632-b5c7-594f15d82d7f)
The importer performs validation of the silhouette to ensure it comes from a compatible rig:
![using_silhouette_template_warning](https://github.com/godotengine/godot/assets/39946030/c7a59b40-de40-411a-b201-7ea32ccd2724)

This allows manually fine-tuning the silhouette pose which can be used to mitigate cases where Silhouette fixer cannot fix the initial pose.
Fixes #65656

(Note that the preview is invisible because #78188 was not yet merged)

2024-02-25 17:18 UTC, fire commented
Thoughts on a boolean that hides the bonemap. Like a switch between bone map or `retarget/rest_fixer/silhouette_template` where we control visibility.

2024-02-25 17:29 UTC, fire commented
We discussed a read-only multiline string property for displaying correction instructions.

2024-02-25 17:47 UTC, TokageItLab commented
Wasn't the real problem with this that all the other animations have T or A poses other than the top of the animation list?
I don't think this workflow requiring a separate model is a good idea. So the right way is to add a GUI to select the reference animation such as adding processing steps in the importer IMO.

2024-02-25 17:58 UTC, lyuma commented
There is no list of animations on Maya exports. It is very common for an animation export from Maya to be a single animation named "Take 001", which is why animation authors in Unity typically include a separate fbx file in the reference pose.

I do not know if there are different workflows common in other engines such as Unreal, but the suggestion to add additional animations in each file for t-pose or a-pose is impractical at least for FBX and Maya exports.

Can you explain why it is not a good idea?

2024-02-25 18:11 UTC, TokageItLab commented
There are several problems

Importing another model as an actual object increases the size of the project folder by the amount of the imported model.

It is difficult to detect the possibility that a profile has incorrect rests. This may have to be left to the user's file management practices, but at least it is a hassle to output a profile from the model each time and save it as a separate resource.

If managed as another model, it would be better to use a name suffix or special extension so that the collider uses `_col` and the external fbx can be specified directly from the importer as a file to be used only at import time.

2024-02-25 18:40 UTC, lyuma commented
> Importing another model as an actual object increases the size of the project folder by the amount of the imported model.
Usually these models don't need the mesh, so they are just a skeleton posed in t-pose. So it may take on the order of one extra megabyte. For character models with separate animations, usually the character itself *is* the reference pose, so there is often no need to add additional files.

This is a critique of the workflow, but not a reason why it is wrong to do this, just that it is not as efficient. Also, there is no requirement to retain the original t-posed model in the project after extracting a skeleton profile. This is one of the reasons I decided to take this approach, since it creates an asset that can be reused for subsequent imports of a particular character.

> It is difficult to detect the possibility that a profile has incorrect rests. This may have to be left to the user's file management practices, but at least it is a hassle to output a profile from the model each time and save it as a separate resource.

I warn if a SkeletonProfile is used which does not match up with the chosen BoneMap. If two models have the same sets of bones, my assumption is that they likely have the same rests, but of course it is no guarantee. This feature is designed to work when two files refer to precisely the same skeleton, but the burden is on the user to make sure not to mix up files. This is indeed a workflow challenge but not a reason why this cannot be used as a workflow.

> If managed as another model, it would be better to use a name suffix or special extension so that the collider uses _col

I strongly dislike the collider suffix convention, and I would be unhappy creating a new workflow which depends on name suffixes, as other parts of the system may need to become aware of such rules..

> and the external fbx can be specified directly from the importer as a file to be used only at import time.

This certainly could be done as an alternative to specifying a SkeletonProfile. It adds complexity because the external model would have to be loaded which creates an import dependency. If you insist that we implement the feature this way, I can try to work on it.

I have some concerns about referencing another scene file from the import. Godot might not have a guarantee that models are imported in a particular order, or it could create a cyclic import if the user by mistake sets two gltf files as each other's silhouette.

2024-02-25 19:03 UTC, lyuma commented
> after fbx changes the rest, this steps is required again

It should not be required, because the model uses the same skeleton either way (For example, if I have Alicia in t-pose and Alicia doing a walk animation, the skeleton is the same, so it does not matter which version of Alicia's bone rest I use.

Overwriting the bone rest is merely adjusting the model into a known pose, Also, this known pose can be combined with silhouette fixer to account for any offset between the reference t-pose and the desired t-pose.

> allow external fbxes to be specified IMO.

I'll have to figure out how to do this, but I assume it would be a scene file. We just need to make sure that the imports happen in the correct order if I lose my `.godot` directory. Perhaps it would be sufficient to call `reimport_append` if the dependency scene cannot be loaded.

We'd still have the problem that the target scene is not allowed to use BoneMap (since we lose the original bone rolls if the user has set a BoneMap, but it would be easy to detect this because the node names will not match (GeneralSkeleton vs Skeleton3D) as well as the bone names.

Anyway, I will work on this version of the change. From the user's perspective it should not be much different.

Technically I fear we are opening a can of worms that has not been tested. Do I use a PackedScene resource picker? a little scared to serialize a .glb or .fbx reference from a .import file
... or a `PROPERTY_HINT_FILE` file picker with `*.fbx,*.glb,*.gltf,*.scn,*.tscn,*.dae` ... but it can't target a .vrm if I do that: the user would have to inherit scene and reference the inherited .scn

2024-02-25 20:42 UTC, Illauriel commented
> Importing another model as an actual object increases the size of the project folder by the amount of the imported model.

But if you export the Skeleton Profile, and remove the model afterwards, it shouldn't be that big of an impact, right? And this approach would fit with a kind of workflow where source model files themselves are not version-controlled and are split into their respective resources. So the FBX (or GLTF or whatever) from which the correct pose was borrowed only bloats the project folder of the team member responsible for setting the models up.

Overall, I see merit in both approaches, and if it would be possible to reference either a scene file _or_ a Skeleton Profile in the Silhouette Template field, that might be the best way to do it. Exporting a Skeleton Profile would be an extra step you have to do for each model, but it looks like a 'cleaner' workflow. Correct me if I'm wrong.^^'

> If managed as another model, it would be better to use a name suffix or special extension so that the collider uses `_col` and the external fbx can be specified directly from the importer as a file to be used only at import time.

It might be an option, but I don't use suffixes in my workflow so I don't think it would necessarily be 'better' to do it this way.

2024-02-25 23:25 UTC, TokageItLab commented
It is true that SkeletonProfile is not referenced with the source model. It is focused to work in cases where changes to the source model are not important.

For example, SkeletonProfile is designed to be independently sharable for sharing among workers to allow retargeting of monster models with specific Rest, etc.

However, this is not the case in this PR case. If only one silhouette of one specific model is to be targeted, the Profile must have an reference with the source model. This is the same as the AnimationLibrary continuing to have an reference with the source file. In other words, if the referenced Profile is a tres, it must be generated with the .import through ImportedAs in Godot.

2024-02-26 03:35 UTC, Illauriel commented
> This is the same as the AnimationLibrary continuing to have an reference with the source file.

I think I get your point, but we have also independent Animation Libraries that are not "models imported as AnimationLibrary", but "A grouping of externally stored animations" so this analogy is not entirely correct.

> In other words, if the referenced Profile is a tres, it must be generated with the .import through ImportedAs in Godot. 

But wat if I don't want to import the file as this kind of resource, because it also holds a ton of other useful data, like meshes, materials, etc. Say we have one big blend file with character, animations and all the stuff. It's like 150Mb. I never ever plan to edit it under any circumstances. (because I'm not an artist) I want to export all of this useful data as separate resources and discard the source .blend file for good. Should I instead create multiple copies of this .blend file to import one as an AnimationLibrary, another as SkeletonProfileForBetterSilhouetteFix and save meshes and materials from the third one?

> I think it would be suitable to have something like SilhouetteData

If it's a standalone file and it can safely lose reference to the imported model file that it got created from, it might be okay, but also as you've said, making a separate class just for this specific purpose seems wasteful. 

Here's how I see my specific workflow with this in my imagination:
- I bought a pack of animations from some store and want to retarget them to my character that has vastly different proportions to Unreal Mannequin or whatever the animation creators used as their base model.
- I drop the folder with animation FBX files in the project hierarchy, open the file that says T-pose, set BoneMapHumanoid, reimport open it as a scene and export a SkeletonProfile or whatever it will be called from it. 
- I open each of the other animation files' advanced import dialogues, set BoneMapHumanoid, set the exported SkeletonProfile, set a destination to export the animations, reimport.
- Then I delete the FBX source files and forget about their existence. I don't include them in the version control, I don't bloat my project folder, and feel happy about it.

TL;DR: all of the "ImportAs" and resource inheritance discussed previously is very good when you have a project where assets are in constant state of iteration and need updating, but it's not the only use case.

2024-02-26 04:05 UTC, TokageItLab commented
> I think I get your point, but we have also independent Animation Libraries that are not "models imported as AnimationLibrary", but "A grouping of externally stored animations" so this analogy is not entirely correct.

Conversely, if the SkeletonProfile can also have a reference to the original model, it should do so.

Finally, it would be best if the split fbx could be imported as an AnimationLibrary and specified as per my comment above.

If that is possible, then we can share a method with the ability to specify animations other than the top of the animation list to address the two problem cases:

1. if the reference pose is in a separate file, we can load it as an external animation library and specify the reference  animation
2. if the reference pose is in the same file, but not at the beginning of the animation list, we can specify that reference animation

2024-02-26 14:08 UTC, lyuma commented
Revision 442bbced8512cb3e13c1f704d6cb7dff3fd1c10f adds a better warning to the SkeletonProfile template.
![image](https://github.com/godotengine/godot/assets/39946030/053e6da8-01d5-4f1e-b934-2ca9fefc9b27)

I have spent several hours prototyping a workflow for animations or AnimationLibrary or PackedScene references, but they all seemed so clunky, and animations in particular are highly error prone either due to mixing up post-retargeting animations from pre-retargeting animations, as well as the default setting of "Remove Immutable Tracks" being on (BoneMap forces immutable tracks to be written, but we can't use a BoneMap'ed animation)

> If only one silhouette of one specific model is to be targeted, the Profile must have an reference with the source model. This is the same as the AnimationLibrary continuing to have an reference with the source file. In other words, if the referenced Profile is a tres, it must be generated with the .import through ImportedAs in Godot. Also, many fields are unnecessary for SkeletonProfile for this purpose.

Anyway, I was chatting with @Illauriel and thinking about your comment, and it occurred to me: I can make the SkeletonProfile generated by the .import.
![image](https://github.com/godotengine/godot/assets/39946030/79211d38-8999-469e-9b2c-0f7fe4b8657d)
This also adds a new workflow to easily create new workflow-specific profiles without having to open the scene and manually select "Export Skeleton Profile"

Further, since it is generated before the BoneMap is applied, it no longer requires an additional file for "retargeted" and "not retargeted" versions: you can enable the new Export Skeleton Profile to file and still perform the retarget, and the exported profile will be pre-retarget and hence suitable for use as a "Silhouette Template":
![image](https://github.com/godotengine/godot/assets/39946030/6cf325ff-81ce-492e-b945-7e8e8204b099)

2024-02-26 14:34 UTC, fire commented on scene/resources/skeleton_profile.cpp
> +void SkeletonProfile::init_from_skeleton(Skeleton3D *skeleton) {
```suggestion
void SkeletonProfile::initialize_from_skeleton(Skeleton3D *skeleton) {
```

We typically spell out abbreviations.

2024-02-26 14:37 UTC, AThousandShips commented on scene/resources/skeleton_profile.h
> +	void init_from_skeleton(Skeleton3D *skeleton);
```suggestion
#ifndef _3D_DISABLED
	void init_from_skeleton(Skeleton3D *p_skeleton);
#endif
```

2024-02-26 14:37 UTC, AThousandShips commented on scene/resources/skeleton_profile.h
> +#include "scene/3d/skeleton_3d.h"
```suggestion
#ifndef _3D_DISABLED
#include "scene/3d/skeleton_3d.h"
#endif
```

2024-02-26 14:47 UTC, AThousandShips commented on scene/resources/skeleton_profile.h
> +	void initialize_from_skeleton(Skeleton3D *skeleton);
```suggestion
	void initialize_from_skeleton(Skeleton3D *p_skeleton);
```
Prefix arguments with `p_`

2024-02-26 14:47 UTC, AThousandShips commented on scene/resources/skeleton_profile.cpp
> +void SkeletonProfile::initialize_from_skeleton(Skeleton3D *skeleton) {
```suggestion
void SkeletonProfile::initialize_from_skeleton(Skeleton3D *p_skeleton) {
```

2024-02-26 19:26 UTC, lyuma commented
> There at least two different type of animation in FBX Maya, one is one single clip and the other is a series of animations.

Thank you, fire. I appreciate that you have identified that there are multiple cases here. That's exactly right.

I am solving the FBX split case.

However, I would also be happy to solve the multiple animation case. I believe this is best solved using a different approach:

> The current approach using SkeletonProfile does not look good as it is too specialized for the split fbx special case. The feature to select reference animation from AnimationLibrary would be a comprehensive solution to the problems with the order of blender's animation list in glTF as well as split fbx.

Rather than build one complexx comprehensive solution, we should take specific problems and solve both with specific solutions. That is the godot way.
The solution I built works extremely well for split FBX. It is difficult to improve on the workflow in terms of number of clicks or steps.

That leaves solving the gltf case.
I believe that can be done with a checkbox on the individual animation in the import settings for a given model. We can also make a dropdown if people prefer that.

Basically, it would be choosing an animation from the same model (not using an external AnimationLibrary) to use as the reference pose. I think this would be easy to do and I would be happy to implement this.

I am not going to compromise this design on the basis of forcing AnimationLibrary to be a suitable workflow. It simply is not a clean workflow
1. exported animations by default are missing immutable tracks
2. exported animations are subject to retargeting by default, so we need to remind the user to disable BoneMap from the reference model.
3. it is extremely difficult to include both an animation library reference as well as a dropdown for which animation wihtin the library. I don't even know where to start on building such a feature with godot's default inspector
4. Import As -> Animation library requires dedicating a whole model file just for the rest pose (since you then can't use as scene). exporting an individual animation would be simpler but we still have the first few issues.

Anyway I know I am not using SkeletonProfile the way you designed, but there was inspiration to do things this way, and I think it makes some sense to use the same datatype even if not 100% of the functionality of that data type is being used.

2024-02-26 22:06 UTC, TokageItLab commented
> exported animations by default are missing immutable tracks
> exported animations are subject to retargeting by default, so we need to remind the user to disable BoneMap from the reference model.
> it is extremely difficult to include both an animation library reference as well as a dropdown for which animation wihtin the library. I don't even know where to start on building such a feature with godot's default inspector
> Import As -> Animation library requires dedicating a whole model file just for the rest pose (since you then can't use as scene). exporting an individual animation would be simpler but we still have the first few issues.

So I mean that it is the role of the AnimationLibrary importer to solve these, not the post importer.

2024-02-26 23:45 UTC, lyuma commented
We talked in the meeting about it, there was a lot of pushback to using SkeletonProfile. I think we agreed that an Animation represents a skeleton pose.

There was some discussion that Animation is difficult to import currently, so we talked about adding Import As Animation (or animation pose?)
However, AnimationLibrary is difficult to reference because i would need a picker in the adv import dialog.
Furthermore, with sub-resource references, animation will become much easier to reference in 4.4+. Hence, I think we should reference Animation in anticipation of this change.

2024-03-07 13:22 UTC, fire commented on editor/import/3d/scene_import_settings.cpp
> +							hint_string += "," + anim_name; // Include preceeding , for as catch-all
```suggestion
							hint_string += "," + anim_name; // Include preceding, for as catch-all
```

2024-03-08 10:53 UTC, lyuma commented
Updated the PR to accept animation libraries, either externally or animations from the same file's AnimationPlayer.

There are now a few different cases here, and I have some warnings to detect the common pitfalls, (these pitfalls are why I originally shied away from using animations). For example, using a BoneMap converted animation; or using an animation with (almost) no tracks -- both of these are easy to create by mistake due the remove immutable tracks.
![image](https://github.com/godotengine/godot/assets/39946030/957780fd-1f34-4f02-a450-b91cb1f5600a)

2024-03-08 23:30 UTC, fire commented on editor/import/3d/resource_importer_scene.cpp
> +							Variant::STRING, U"rest_pose/\u26A0_warnings/mismatched_or_empty_profile",
```suggestion
							Variant::STRING, U"rest_pose/\u26A0_validation/mismatched_or_empty_profile",
```

I wonder if validation or something like is better than warnings.

2024-03-10 00:48 UTC, Invertex commented
Oh, glad to see this PR haha. I actually implemented this a couple months ago: 
https://github.com/Invertex/godot/tree/fix-silhouette-using-other-source

![](https://i.gyazo.com/35e17527918cf6221abc0df47b5d32c4.png)

But I never submitted a PR because I assumed it probably wouldn't get approved... Was waiting to see if I could think of some other solutions. This has been a pretty big issue for more as it has severly restricted what third party animations we can use as a smaller studio. Many of the animation packs people may buy will come in this "bad workflow" format.


I took a similar approach as here, but instead of storing the Resource as an externally referenced file, I embed it in the **.import** of the model it belongs to. My thought here is that it ensures there's no mistake of ownership or possibility of another asset instance overwriting the Resource.

Other models can choose the target source model and read the BindPose resource from its .import if it exists.

I also update the pose at the very start before any of the regular importing fixes happen, so that the file is basically utilized by the import system as though it actually contained the proper rest pose. Don't need to mess with any of the actual import code.
BoneMap can do its thing, working with a proper matching bindpose then.

--------------------------------------
A possibility for triggering dependency could be having a list in the source file of other assets that rely on this profile. When this source model reimports, it could trigger those list of files for reimport after the source file is done (and any paths that don't exist anymore can be culled and warned about).

2024-03-10 18:24 UTC, fire commented
@lyuma https://github.com/Invertex/godot/commit/62a98c4f4cbb8095b615c30f3f889ddbaa2cf16c#diff-d524f1765c15505d971875ccbf5ea13733989c77101db63a2f84fb09eb1b5ca3R57-R66

2024-03-16 06:17 UTC, TokageItLab requested changes
The UI seems much improved. However, I feel that the `Export Skeleton Rest Pose` features need more discussion.

I understand where you are coming from with the desire to extract individual Animations, but from a consistency standpoint, an option to "include rests as "REST" animation in the AnimationPlayer of imported tres, and separate the animation from the imported scene and save it as new animation" would seem more appropriate, IMO.

Even if it is extracted separately, at least it should be a folded option like `Use External`, similar to Mesh and Material since this option should be not necessary in many cases.

![image](https://github.com/godotengine/godot/assets/61938263/7db82bea-f579-43b8-a410-d62d42f1f810)

@lyuma So, I believe that the `Export Skeleton Rest Pose` functionality can be separated from this PR for now, can you separate that functionality once it is in place? Other than that, it seems to make sense and we can be Approved.

2024-03-16 08:44 UTC, lyuma commented
Before I update this PR, I would like to first understand the intended direction so that I can prepare both PRs: there is no point merging one feature without the other feature: a user cannot select a rest pose animation when there is no way to create a rest pose animation.

Sure, I would be fine without "Export Skeleton Rest Pose" since I am using Unidot to import fbx files, and Unidot now creates the rest pose animation automatically on 4.3. But losing this feature would interfere with ordinary users who are not using a third party tool script to create this animation automatically. While it does not need to be implemented in exactly this way, a way to create a "rest pose animation" does need to exist in some form in 4.3 for FBX animation import to be functional.

Therefore, I would like to understand the intended user-facing **workflow** / steps for FBX. 

To be clear, here is the problem that is being solved with "Export Skeleton Rest Pose":
The user has two FBX files. One is in t-pose, call it "TPose.fbx". The other is an animation FBX, maybe "Walking.fbx" posed on the first frame (incorrect rest pose) and no mesh, so no bind pose.

Here is my understanding of the workflow you are proposing:

1. Open the advanced importer of TPose.fbx
2. Select "Include rests as "RESET" animation" checkbox on the Skeleton3D
3. The advanced importer will refresh and the RESET animation is now listed as an animation
4. The user selects to extract animations to a file or import as library
5. Open "Walking.fbx" in the advanced importer
6. Now select the extracted RESET animation in "Load pose"

Clearly, this "RESET" animation would always include all keys (ignore the immutable track policy), since all tracks are immutable when only one keyframe exists.

(also, is "REST" this the same thing as "RESET"? I think the similar names in all caps may be confusing me.)

2024-03-16 09:30 UTC, TokageItLab commented
I understand that REST animation and RESET animation are different things.

RESET was supposed to define a pause at load time, but as we discussed on RocketChat, if that is not currently working and AutoPlay is working as an alternative, then I think it is acceptable to include it in RESET.

Also, it would be ideal to include that setting in the normal importer settings rather than the advanced importer.

![image](https://github.com/godotengine/godot/assets/61938263/b18566cc-342d-4a47-a5ec-6eba81588b90)

Because the rest extraction itself is done outside of the Retartget process and has no direct impact on Retartget.

2024-03-16 10:59 UTC, lyuma commented
I think I understand: if it's in the normal import settings, then it can be generated before `_pre_import` completes, so it will enforce the creation of an AnimationPlayer and a rest animation, which can then be extracted using Godot's standard animation flow (AnimationLibrary or extract animations)

Ok, so adjusting my above workflow, it would be:

1. Select TPose.fbx in the Import Dock
2. (Optional) Enable "Import as skeleton bones"
3. Enable "Generate Rest Pose Animation"
4. Do not enable humanoid import. Instead:
    1. either: Switch "Import As" to AnimationLibrary and Reimport
    2. or: Open advanced importer and selects Extract Animations and Reimport.
5. Select animation (e.g. Walking.FBX)
6. Enable "Import as skeleton bones"
7. Open advanced importer:
8. Enable BoneMap
9. Set "Rest Pose" to "External Animation"
10. Select the animation exported in step 4.
11. Click Reimport

Does this flow look correct?

2024-03-16 11:15 UTC, TokageItLab commented
> Enable "Import as skeleton bones"

Does this mean that you implement something new? Does this mean that it uses the Skeleton as its root, unlike the import as Scene which uses the Node3D as its root?

I think it is sufficient to add the option "Import Rest as RESET" under "Remove Immutable Tracks".

2024-03-16 11:36 UTC, lyuma commented
> Does this mean that you implement something new

No, since "Import as skeleton bones" is the feature implemented in #88819 and was already merged,

I am merely recommending to use this feature in conjunction: It should be documented as part of the recommended flow for animation import, since it will guarantee that the animation FBX contains a skeleton (otherwise, a FBX with no meshes might only contain nodes and no bones)

> Does this mean that it uses the Skeleton as its root

No, that feature does not change the root of the scene to skeleton: this created too many compatibility problems, so the root is Node3D but the children are always Skeleton3D and AnimationPlayer if animations are present.

> "Import Rest as RESET"

Sounds like a good name. I would be happy to implement this and name the resulting animation "RESET" by default.

> Is the problem when there are more than one Skeletons?

It could be confusing when there are multiple skeletons.

However, the "Import as skeleton bones" feature above will guarantee that exactly one skeleton is present, since all nodes in the scene are now bones in that single skeleton.

Generally speaking, our workflow is not well suited to scenes with multiple skeletons, so this should be discussed separately with a specific example file (I have a few but they are not designed to be retargeted). The limitation of one logical skeleton per animation file seems fairly common across several engines / file formats, so I don't think we should try to solve this right now.

2024-03-16 11:45 UTC, TokageItLab commented
> No, since "Import as skeleton bones" is the feature implemented in https://github.com/godotengine/godot/pull/88819 and was already merged,

Okay, so it is no problem. However, please keep in mind that ""Import Rest as RESET" option may be enabled even for Import as Scene. I think we now agree.

2024-03-18 03:41 UTC, lyuma commented
Updated this PR to remove the "Export Skeleton Rest Pose" option.

Opened #89629 to add a "Import Rest as Reset" option in the top-level import dock, which can be used to generate a compatible rest pose (t-pose) animation from fbx or similar files which did not come with one.

2024-03-18 06:10 UTC, TokageItLab approved these changes
LGTM

2024-03-18 09:13 UTC, AThousandShips approved these changes

2024-03-18 09:13 UTC, AThousandShips commented on editor/import/3d/resource_importer_scene.cpp
> +				if (!rest_animation.is_valid()) {
```suggestion
				if (rest_animation.is_null()) {
```

2024-03-18 09:13 UTC, AThousandShips commented on editor/import/3d/resource_importer_scene.cpp
> +					if (!skeleton_bone) {
```suggestion
					if (skeleton_bone == StringName()) {
```

2024-03-18 09:13 UTC, AThousandShips commented on editor/import/3d/resource_importer_scene.cpp
> +			r_options->push_back(ImportOption(PropertyInfo(Variant::FLOAT, "rest_pose/selected_timestamp", PROPERTY_HINT_RANGE, "0,1,0.001,allow_greater,suffix:s", PROPERTY_USAGE_DEFAULT), 0.0f));
```suggestion
			r_options->push_back(ImportOption(PropertyInfo(Variant::FLOAT, "rest_pose/selected_timestamp", PROPERTY_HINT_RANGE, "0,1,0.001,or_greater,suffix:s", PROPERTY_USAGE_DEFAULT), 0.0f));
```

2024-03-23 23:37 UTC, akien-mga commented
There seems to be a build issue for the editor:
```
Error: editor/import/3d/scene_import_settings.cpp:116:7: error: 'option' was not declared in this scope; did you mean 'options'?
  116 |   if (option.name == "rest_pose/load_pose") {
      |       ^~~~~~
      |       options
Error: editor/import/3d/scene_import_settings.cpp:121:7: error: 'option' was not declared in this scope; did you mean 'options'?
  121 |   if (option.name == "rest_pose/selected_animation") {
      |       ^~~~~~
      |       options
```

2024-03-24 04:13 UTC, merged

2024-03-24 04:13 UTC, akien-mga commented
Thanks!