Do not attempt to set cursor shape in headless mode.
godotengine/godot pull request #89099
Opened 2024-03-02 21:14 UTC by chrisl8

Every time I run anything in `--headless` mode I receive this warning:

**WARNING: Custom cursor shape not supported by this display server.**

This does not seem helpful or useful to me. Instead it distracts from the process and encourages us to get used to ignoring errors and warnings without reading them each time.

My, possibly naive, interpretation of the code is that it can skip this step always when running `--headless` with no negative effect, but if I'm wrong, feel free to reject.

It seems to work for me.

2024-03-02 21:58 UTC, deralmas requested changes
I do agree that we shouldn't do things that emit warnings in core code.

That said, the current approach is a bit too `DisplayServerHeadless`-specific, see the review comment.

2024-03-02 23:16 UTC, akien-mga commented
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

2024-03-03 05:13 UTC, deralmas approved these changes
Looks fine and dandy! :D

You started something really nice BTW, I think we should do this to other "special" calls, one of which comes to mind: the pesky icon setting code that prints a warning on startup on Wayland, as there's no support for "runtime" icons in the first place.

2024-03-04 13:11 UTC, merged

2024-03-04 13:13 UTC, akien-mga commented
Thanks!