Allow exporting variables of type Variant
godotengine/godot pull request #89324
Opened 2024-03-09 19:05 UTC by KoBeWi

Inspired by https://github.com/godotengine/godot-proposals/issues/9269

This PR allows for exporting variables of type Variant. Internally they are treated like `Variant::NIL` and show a customized EditorPropertyNil:
![image](https://github.com/godotengine/godot/assets/2223172/4149bc03-8159-4d70-979f-ff56a24b67a1)

This allows for nice flexibility, where you can change not only the variable, but also its value. Granted, you need a custom editor, as mentioned in the hint.

Here's example plugin for "tri-state bool":
```GDScript
@tool
extends EditorPlugin

var state3 := TriStateBoolInspectorPlugin.new()

func _enter_tree() -> void:
	add_inspector_plugin(state3)

func _exit_tree() -> void:
	remove_inspector_plugin(state3)

class TriStateBoolInspectorPlugin extends EditorInspectorPlugin:
	func _can_handle(object: Object) -> bool:
		return true
	
	func _parse_property(object: Object, type: Variant.Type, name: String, hint_type: PropertyHint, hint_string: String, usage_flags: int, wide: bool) -> bool:
		if type == TYPE_NIL and hint_string == "3bool":
			add_property_editor(name, TriStateBoolEditor.new())
			return true
		return false

class TriStateBoolEditor extends EditorProperty:
	var button: TriStateCheckbox
	
	func _init() -> void:
		button = TriStateCheckbox.new()
		add_child(button)
		button.pressed.connect(func(): get_edited_object().set(get_edited_property(), button.state))
	
	func _update_property() -> void:
		button.state = get_edited_object().get(get_edited_property())

class TriStateCheckbox extends Button:
	const STATES = [null, false, true]
	
	var textures: Array[Texture2D]
	var state: Variant:
		set(s):
			state = s
			icon = textures[STATES.find(state)]
	
	func _init() -> void:
		size_flags_horizontal = SIZE_SHRINK_BEGIN
		
		for color in [Color.RED, Color.GREEN, Color.BLUE]:
			var gradient := Gradient.new()
			gradient.remove_point(1)
			gradient.colors = [color]
			
			var texture := GradientTexture2D.new()
			texture.gradient = gradient
			texture.width = 16
			texture.height = 16
			textures.append(texture)
	
	func _pressed() -> void:
		for i in STATES.size():
			if STATES[i] == state:
				state = STATES[(i + 1) % STATES.size()]
				break
```
Example usage:
```GDScript
@export_custom(0, "3bool") var boolean_hat_trick
```

https://github.com/godotengine/godot/assets/2223172/1aab2534-ff73-4f29-aa85-0b7792b6319f

2024-03-09 19:10 UTC, AThousandShips commented on editor/editor_properties.h
> +	virtual void update_property() override{};
```suggestion
	virtual void update_property() override {}
```

2024-03-09 20:03 UTC, dalexeev commented
* See also #33080.

I wanted to salvage/re-implement it. I think this should work like `Dictionary` key/value editor, the user could select the type first, then the value.

2024-03-09 20:37 UTC, KoBeWi commented
I thought about that too, but opted for a simpler solution (as the goal was customizability itself).
I can rework this into the type dropdown widget if that's better.

2024-03-24 20:36 UTC, KoBeWi commented
Ok reworked

https://github.com/godotengine/godot/assets/2223172/b5aa8fdc-f107-44fd-b79a-bc46658857de

2024-06-23 19:13 UTC, Jan-PieterInghels commented
Just checking in to see if this can be approved and merged?

2024-06-24 07:33 UTC, AThousandShips commented
We're currently in feature freeze so this won't be considered until 4.4, and it's not been decided on yet

2024-09-24 15:07 UTC, Calinou reviewed
Code looks good to me at a glance. Could you look into rebasing this on top of `master`?

2024-09-24 19:28 UTC, KoBeWi commented
> PS: Is there much use in exposing Object in the list of types in the dropdown? As far as I know, you can't give it any useful value directly in the inspector.

You can assign it a Resource.

2024-09-24 19:32 UTC, KoBeWi commented on modules/gdscript/gdscript_parser.cpp
> +			return false;
Sus change after rebase.

2024-09-24 19:33 UTC, KoBeWi commented on editor/plugins/tiles/tile_set_editor.cpp
> +	return p_object && (p_object->is_class("TileSetAtlasSourceProxyObject") || p_object->is_class("TileSetScenesCollectionProxyObject"));
For some reason this crashes without null check. I did not bother investigating why, it just makes no sense. No other plugin has this problem.

2025-01-17 13:02 UTC, Gnumaru commented
Since 4.4 beta 1 came out, we are feature freezed and this probably won't get to be merged in 4.4.

But is there anything preventing this to be merged? That is, besides the collosal work of maintainers in evaluating the enormous ammount of pull request the godot project receives every day and deciding, for non bugfix PRs, wheter it is worth or not incorporating into the engine, and if so, deciding when doing it?

2025-01-22 15:09 UTC, Calinou requested changes
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/a7146ef807a7676f51a8a63cf4441ad647f4be66), there's a build error:

```
Generating core/version_generated.gen.h ...
Generating core/version_hash.gen.cpp ...
Compiling core/version_hash.gen.cpp ...
Compiling editor/scu/scu_editor_4.gen.cpp ...
Linking Static Library core/libcore.linuxbsd.editor.x86_64.a ...
Ranlib Library core/libcore.linuxbsd.editor.x86_64.a ...
In file included from editor/scu/scu_editor_4.gen.cpp:4:
./editor/editor_properties.cpp: In member function 'void EditorPropertyVariant::_notification(int)':
./editor/editor_properties.cpp:91:30: error: 'class MenuButton' has no member named 'set_icon'
   91 |                 change_type->set_icon(get_editor_theme_icon("Edit"));
      |                              ^~~~~~~~
scons: *** [editor/scu/scu_editor_4.gen.linuxbsd.editor.x86_64.o] Error 1
scons: building terminated because of errors.
```

2025-01-23 00:00 UTC, Calinou approved these changes
It works now :slightly_smiling_face: 

![image](https://github.com/user-attachments/assets/4377bae2-691f-452c-91ce-b812aa84bb07)

Note that the Variant type hint must be specified explicitly, and you must not set a default value of `null` for it to work as a proper Variant export where you can change the type. I think this makes sense, as this is an uncommon use case and it's better to be explicit about it.

2025-02-15 07:39 UTC, ryevdokimov reviewed
I get errors when using the .NET version of Godot after just typing:

`@export var test : Variant` 

```
ERROR: C:/Users/RobertYevdokimov/Desktop/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
ERROR:    at GodotTools.Inspector.InspectorPlugin.EnumerateScripts(GodotObject godotObject)+MoveNext() in C:\Users\RobertYevdokimov\Desktop\godot\modules\mono\editor\GodotTools\GodotTools\Inspector\InspectorPlugin.cs:line 58
ERROR:    at GodotTools.Inspector.InspectorPlugin._CanHandle(GodotObject godotObject) in C:\Users\RobertYevdokimov\Desktop\godot\modules\mono\editor\GodotTools\GodotTools\Inspector\InspectorPlugin.cs:line 13
ERROR:    at Godot.EditorInspectorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in C:\Users\RobertYevdokimov\Desktop\godot\modules\mono\glue\GodotSharp\GodotSharpEditor\Generated\GodotObjects\EditorInspectorPlugin.cs:line 184
ERROR:    at GodotTools.Inspector.InspectorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in C:\Users\RobertYevdokimov\Desktop\godot\modules\mono\editor\GodotTools\GodotTools\obj\Release\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\GodotTools.Inspector.InspectorPlugin_ScriptMethods.generated.cs:line 50
ERROR:    at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in C:\Users\RobertYevdokimov\Desktop\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\Bridge\CSharpInstanceBridge.cs:line 24

```

2025-02-16 10:14 UTC, ryevdokimov approved these changes
This is a useful feature, it works, and code looks fine.

2025-04-08 18:57 UTC, Gnumaru commented
Is there a chance of seeing this in the 4.5 dev snapshots?

2025-04-28 14:24 UTC, Repiteo approved these changes
Looks good to me

2025-04-28 15:09 UTC, merged

2025-05-11 15:33 UTC, lord-muad-dib commented
hello, is having Variant not coming up on auto completion a wanted behaviour? thanks