Don't duplicate internal nodes
godotengine/godot pull request #89442
Opened 2024-03-13 12:36 UTC by KoBeWi

As commented in https://github.com/godotengine/godot-proposals/issues/9282#issuecomment-1992802567, this PR makes nodes added with `INTERNAL_MODE_FRONT` or `INTERNAL_MODE_BACK` not duplicated, similar to `parent_owned`. Also removed `parent_owned` and related methods, because they are no longer needed. AFAIK all internal nodes already use the proper internal mode. I also added helper method `is_internal()` to make it easier to use.

Supersedes #88114
Supersedes #89388

Resolves https://github.com/godotengine/godot-proposals/issues/9282 (with alternate solution)

2024-03-13 13:11 UTC, AThousandShips commented
Doesn't fully supersede #88114 without cherry picking

Interesting otherwise, I'd say it breaks compatibility even though the parent owned feature isn't accessible to scripting, though I'm not sure how people would handle this behavior currently in scripting

2024-03-13 13:36 UTC, KoBeWi commented
Well currently handling this is not possible via scripting. The internal nodes before this PR didn't prevent duplication. https://github.com/godotengine/godot-proposals/issues/9282 proposed exposing the "parent owned" property, but it's a hack and now that we have a proper API for adding internal children, it can be used to replace this legacy code.

2024-03-13 13:37 UTC, AThousandShips commented
The internal nodes not handling this before *is* the compatibility breakage I'm talking about though 🙃, unsure if people do use it but if they do use internal nodes then their code will break now, especially if they *don't* intend them to not be duplicated

2024-03-13 15:30 UTC, Mickeon commented
I agree. It would break compatibility. But "break compatibility (good)". It also gives more reasons to make use of this feature. It could use some testing to ensure it doesn't break built-in Control nodes.

2024-09-08 18:29 UTC, kitbdev commented
- Also fixes https://github.com/godotengine/godot/issues/92880
- Supersedes https://github.com/godotengine/godot/pull/96018

2025-02-10 12:27 UTC, akien-mga approved these changes
As discussed on RC, let's merge this early on in the 4.5 dev cycle, so it gets ample testing to catch potential regressions.

In the meantime we'll merge #88114 for 4.4, which you'll likely want to revert in this PR since it's removing `force_parent_owned`.

2025-02-12 21:26 UTC, KoBeWi commented on scene/main/node.cpp
>  	for (int i = 0; i < get_child_count(); i++) {
This is the only one.

2025-03-06 15:13 UTC, Repiteo commented
Now that we're on 4.5, this should revert #88114 so builds can succeed

2025-03-06 15:59 UTC, 0xcafeb33f requested changes
In addition to reverting #88114, I had to remove a few other calls of `force_parent_owned` to get this PR to compile:
```
--- a/scene/gui/color_picker.cpp
+++ b/scene/gui/color_picker.cpp
@@ -887,7 +887,6 @@ void ColorPicker::_quick_open_palette_file_selected(const String &p_path) {
        if (!file_dialog) {
                file_dialog = memnew(FileDialog);
                add_child(file_dialog, false, INTERNAL_MODE_FRONT);
-               file_dialog->force_parent_owned();
                file_dialog->connect("file_selected", callable_mp(this, &ColorPicker::_palette_file_selected));
                file_dialog->set_access(FileDialog::ACCESS_FILESYSTEM);
                file_dialog->set_current_dir(Engine::get_singleton()->is_editor_hint() ? "res://" : "user://");
@@ -1826,7 +1825,6 @@ void ColorPicker::_options_menu_cbk(int p_which) {
        if (!file_dialog) {
                file_dialog = memnew(FileDialog);
                add_child(file_dialog, false, INTERNAL_MODE_FRONT);
-               file_dialog->force_parent_owned();
                file_dialog->connect("file_selected", callable_mp(this, &ColorPicker::_palette_file_selected));
                file_dialog->set_access(FileDialog::ACCESS_FILESYSTEM);
                file_dialog->set_current_dir(Engine::get_singleton()->is_editor_hint() ? "res://" : "user://");
```

2025-03-06 16:30 UTC, 0xcafeb33f approved these changes
Tested on 64-bit Windows: now compiles without errors and fixes `duplicate` errors mentioned.

2025-03-06 22:15 UTC, 0xcafeb33f requested changes
One problem that has come up is when nodes are dynamically added via script ([see here for MRP](https://github.com/godotengine/godot/issues/102573#issuecomment-2704708194)) -- `_duplicate_properties` assumes that all non-internal nodes exist in the copied tree, causing errors for nodes added without an owner. It seems like this conditional is not necessary now that we are guarding against internal nodes inside of `get_child_count` and `get_child`. This patch fixes the errors in the MRP. Can you confirm whether this change is appropriate, and if so, implement it?
```
--- a/scene/main/node.cpp
+++ b/scene/main/node.cpp
@@ -2792,10 +2792,6 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
                        for (int i = 0; i < N->get()->get_child_count(false); ++i) {
                                Node *descendant = N->get()->get_child(i, false);

-                               if (!descendant->get_owner()) {
-                                       continue; // Internal nodes or nodes added by scripts.
-                               }
-
                                // Skip nodes not really belonging to the instantiated hierarchy; they'll be processed normally later
                                // but remember non-instantiated nodes that are hidden below instantiated ones
                                if (!instance_roots.has(descendant->get_owner())) {
```

2025-03-07 12:50 UTC, KoBeWi commented
I'm not sure, removing this check is another change in behavior. It was added in #84824, instead of skipping internal nodes. So now we'd switch to the opposite. It's probably fine, but worse for compatibility, as ownerless nodes are more common than internal nodes.

Alternative fix is tweaking `_duplicate_properties()` to skip nodes without owner.

2025-03-07 14:21 UTC, 0xcafeb33f commented
> Alternative fix is tweaking `_duplicate_properties()` to skip nodes without owner.

At least anecdotally, I would prefer not to do this. My project has a module that relies heavily on `duplicate()` of nodes with dynamically added children, and the previous behavior in 4.1 and 4.2 seems to duplicate all dynamically added nodes (even without owner).

This change (#84824) seems to only affect dynamically added nodes that are children of children of instantiated scenes. So, for instance, a node created by a script and added to a scene's root would be duplicated when that scene was duplicated, but a dynamically added node to a scene's child would not. I think reverting it would produce the most consistent behavior, as in that case all non-internal nodes would be duplicated regardless of whether they are dynamically added to children of a scene.

CC @Rindbee since, as you mention, they added this section of code.

2025-03-07 15:04 UTC, Rindbee commented
Nodes added by scripts are difficult to predict:
1. It is uncertain whether the nodes attached by the script are copied, that is, how many times the code for adding nodes by the script is run;
2. It is uncertain **where** the nodes added by the script are added;

We cannot predict the behavior of user scripts, so we assume that users use scenes to manage nodes, and we can only give general suggestions:

1. The logic for managing the addition and removal of nodes in the scene is best in the script attached to the scene root node.
2. And the parent scene is best not to manage the addition and deletion of nodes in the child scene.

2025-03-07 15:10 UTC, KoBeWi commented
I made the ownerless node duplicated. I realized it was never a documented behavior. Also owner is more intended for scenes, not for nodes alone, so making ownerless nodes not duplicated didn't make sense in hindsight.

2025-03-07 15:58 UTC, 0xcafeb33f approved these changes

2025-03-07 18:11 UTC, merged

2025-03-07 18:11 UTC, Repiteo commented
Thanks!

2025-03-11 23:49 UTC, JekSun97 commented
Is this for 4.4.1? or 4.5?

2025-03-11 23:53 UTC, KoBeWi commented
4.5