Implement FXAA 3.11 to replace the current broken implementation
godotengine/godot pull request #89582
Opened 2024-03-16 17:26 UTC by mrjustaguy

Resolves https://github.com/godotengine/godot-proposals/issues/9300
Fixes https://github.com/godotengine/godot/issues/83089
Fixes https://github.com/godotengine/godot/issues/64985
Improves Temporal stability over the old implementation (No Issue on github opened regarding the extremely low temporal stability of FXAA in motion)

Implements FXAA 3.11 to replace the current Godot FXAA implementation which is heavily messed up.

Multiview Hasn't been tested (nor can I test it) and Need to find the exact license text for FXAA 3.11, and where to place it in Godot, so help with these aspects is very welcome.

No AA:
![image](https://github.com/godotengine/godot-proposals/assets/50302479/36e2bed7-a325-40b6-b055-015b920a99c4)

New Implementation:
![image](https://github.com/godotengine/godot-proposals/assets/50302479/917077ea-95e8-4103-940e-66146f079c93)

Old Implementation:
![image](https://github.com/godotengine/godot-proposals/assets/50302479/83088d1e-e56c-4ede-9e45-a298660d41a0)

Note: don't mind the performance metrics, for some reason they fluctuate heavily between 4 and 5ms all the time in the scene regardless of version and AA used/not, and these are just the numbers that happened to be at screenshot time, Actual benchmarks are required to determine actual performance differences.

2024-03-16 17:27 UTC, AThousandShips commented
Can someone confirm the license and origins of this code, see the discussion in:
* https://github.com/godotengine/godot-proposals/issues/9300

2024-03-16 17:31 UTC, mrjustaguy commented
I just found the License text in the gist https://gist.github.com/kosua20/0c506b81b3812ac900048059d2383126 which links to the implementation at https://github.com/kosua20/Rendu/blob/master/resources/common/shaders/screens/fxaa.frag that I've used.. Don't know How I've missed it..

2024-03-16 17:34 UTC, AThousandShips commented
It says "cleaner version" but does that mean it's just a copy? The original code is proprietary yes? 
> COPYRIGHT (C) 2010, 2011 NVIDIA CORPORATION. ALL RIGHTS RESERVED.

Nothing about any ability to share it, are they the author? Otherwise this looks very fishy and not valid

2024-03-16 17:41 UTC, mrjustaguy commented
> FXAA 3 is released under a [public domain](https://en.wikipedia.org/wiki/Public_domain) license. A later version, FXAA 3.11, is released under a 3-clause BSD license.(https://en.wikipedia.org/wiki/Fast_approximate_anti-aliasing)

which links to
https://stackoverflow.com/questions/12170575/using-nvidia-fxaa-in-my-code-whats-the-licensing-model/12170857#12170857

2024-03-16 17:43 UTC, AThousandShips commented
The link to the license in that page is dead, as is the link to FXAA 3.11, so that doesn't seem like a confirmation

2024-03-16 17:47 UTC, mrjustaguy commented
Well all the official Nvidia links regarding FXAA seem to be dead so...

2024-03-16 17:50 UTC, AThousandShips commented
So then there's no original reference to it *being* open source, so that's a big issue

2024-03-16 17:57 UTC, AThousandShips commented
Even that claim about it being open source licensed is far not up to the standards of Wikipedia, a random blog or forum post isn't a valid reference, and the fact that they *don't* quote a proper source is a huge red flag to me, if it *was* possible to find a NVIDIA source for it being licensed like that it *would* be on the Wiki page, trust to Wikipedians to fix that quick if they can

2024-03-16 18:12 UTC, mrjustaguy commented
Well I guess the only way to resolve this is to contact Nvidia, and see if the Wiki information is right or not, and pray they answer.

2024-03-16 18:14 UTC, AThousandShips commented
In either case *this* source is not compatible with that unless it's under a public domain license, so in that case you'd have to find NVIDIA source code, this code is copied from a page which claims copyright for the code without any attribution to NVIDIA or any original author

2024-03-16 19:27 UTC, mrjustaguy commented
Well, Bevy is using the Gist FXAA implementation - https://github.com/bevyengine/bevy/blob/main/crates/bevy_core_pipeline/src/fxaa/fxaa.wgsl

2024-03-16 19:30 UTC, AThousandShips commented
Well their header claims that it's a cleaned version of the NVIDIA code, which is very clearly not open source unless there's some part in that code I missed, as see above it says "ALL RIGHTS RESERVED", also this one also doesn't give proper attribution and license details 🙃 so it still all hinges on the original NVIDIA code being open source, and if it is that would just mean we need to find how to add proper attribution

2024-03-16 19:35 UTC, mrjustaguy commented
This is Blender's FXAA - https://github.com/blender/blender/blob/main/source/blender/draw/intern/shaders/common_fxaa_lib.glsl

2024-03-16 19:37 UTC, AThousandShips commented
That does look more legitimate, and Blender is big enough to get in trouble, but is that actually FXAA 3.11?

2024-03-16 19:39 UTC, mrjustaguy commented
The original Gist seems like the same thing as the Blender FXAA, and the code I used is a cleaner implementation of the Gist...

2024-03-16 20:28 UTC, mrjustaguy commented
The cleaned code that I used when porting code to Godot and the source code (both gist and blender versions) seem to be doing the same thing, it's just that the source didn't use things such as iterators which blew the number of lines of code like crazy..

Given Wikipedia states BSD3, and Blender actually confirms BSD3, and the gist is also used by bevy (the same implementation as I've ported) I'm fairly confident if there were Issues, Nvidia would have taken action long ago, especially given the Size of Blender and the fact they clearly know about Blender for quite a long time, and I think for a while they were even Sponsors, though could be wrong on that one, as I don't see them on the Sponsor list for blender..

2024-03-16 20:36 UTC, AThousandShips commented
> Given Wikipedia states BSD3

It doesn't cite a remotely reliable source though, so let's not use it as an argument, this sounds like a game of telephone and there's no actual original source of this claim

The Wikipedia source is a screenshot, of a person claiming to be the author of the code, claiming it's open source, that's all we have, if we look at it critically

2024-03-16 21:01 UTC, fire commented
https://github.com/AmplifyCreations/FXAA This website has a copyright notice for FXAA.

2024-03-16 21:04 UTC, fire commented
There is also https://stackoverflow.com/a/40107522/381724

2024-03-16 21:07 UTC, AThousandShips commented
Yes the second of those links were discussed above and the issues with that all the references there are dead links

2024-03-16 21:12 UTC, fire commented
A clear response would be for us to remove FXAA?

I could try asking Nvidia what license it is and they can make a redeclaration?

2024-03-16 21:14 UTC, AThousandShips commented
I don't know about the existing implementation, where it's from

2024-03-16 21:16 UTC, fire commented
I can say that https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Shaders/Private/Fxaa3_11.ush might be the source of the gist, but it's not public.

2024-03-16 21:19 UTC, fire commented
I might be satisfied with https://github.com/hghdev/NVIDIAGameWorks-GraphicsSamples/blob/master/samples/es3-kepler/FXAA/FXAA3_11.h 

1. it is from a nvidia employee
2. doesn't seem tampered

2024-03-16 21:22 UTC, AThousandShips commented
That does have this license:
https://github.com/hghdev/NVIDIAGameWorks-GraphicsSamples/blob/master/license.txt

Assuming it applies to this file

However I'm not sure if the clauses are compatible, it has a "government users" clause which I don't think is MIT compatible, the MIT license doesn't allow any further constraints afaik, as per the MOT license:
> to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so

2024-03-16 21:25 UTC, fire commented
I didn't see that in these files:

FXAA.cpp
FXAA.h
FXAA3_11.h

2024-03-16 21:26 UTC, AThousandShips commented
That's the license for the repo, for the files themselves there's no license just a "all rights reserved"

2024-03-16 21:26 UTC, AThousandShips commented
That's the license for the repo, for the files themselves there's no license just a "all rights reserved"

2024-03-16 21:27 UTC, fire commented
It says for Redistribution and use in source and binary forms are permitted.

// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:

2024-03-16 21:28 UTC, AThousandShips commented
That's true, now the issue is that that's not the code used in this PR, *that* code violates this requirement, so it can't be licensed IMO

2024-03-16 21:30 UTC, AThousandShips commented
However by my reading the linked version you provided seems sufficiently legitimate, so we should instead base this PR on that code, but let's get someone with some knowledge on the legalities in before we do any further work :)

2024-03-18 16:30 UTC, Calinou commented
Out of curiosity, which FXAA quality level is this PR implementing? The difference between Low and Ultra quality is very low nowadays (given the reference FXAA implementation was last updated in 2011), but Ultra does a better job at smoothing things out. I noticed that Ultra looks a tad blurrier though, so many people may actually prefer Normal (the highest quality which doesn't add blur over Low in my experience).

2024-03-18 17:41 UTC, mrjustaguy commented
Currently It's custom, Subpixel is at default, Edge threshold min is highest (2 above default), Edge threshold max is high (one above default)

2024-03-20 15:49 UTC, AThousandShips commented
As mentioned above writing our own implementation based on the white paper is fully legal, but that's a lot of work, and having an existing, well tested, implementation is worth a lot, the one linked above with good licensing (it seems, would be good to get it verified) would be a good start, but the current code isn't valid based on the licensing issues (and the current code here doesn't follow the license either)

2024-03-20 17:55 UTC, bikemurt commented
> As mentioned above writing our own implementation based on the white paper is fully legal, but that's a lot of work, and having an existing, well tested, implementation is worth a lot, the one linked above with good licensing (it seems, would be good to get it verified) would be a good start, but the current code isn't valid based on the licensing issues (and the current code here doesn't follow the license either)

Practically every game these days (besides pixelated style graphics) ships with FXAA. It will be a big feature for Godot to have nailed in implementation.

So the community, whether by committee or not, probably needs to figure out what the direction forward is. Which sounds like either, engage a legal team, or write a Godot FXAA implementation.

I know I'm asking a lot and so I apologize. I know the engine has 2300 people working so many different things. It's just a feature I would look forward to.

2024-03-20 20:03 UTC, mrjustaguy commented
FXAA or SMAA is basically a must for anyone that wants AA and doesn't want TAA for whatever reason (a good reason being that Godot's TAA is Broken, and FSR2 has Super ghosting issues due to Pixel Locking, which is unclear if it's FSR2 issue or Godot issue or a mix, and the reason Why I went into this tbh)

What shocked me actually when looking at the current implementation and thinking about it, and comparing it to reference, I'm not surprised that ours is such garbage, as it's only taking into account a 3x3 pixel grid, whereas 3.11 reference walks on for multiple pixels in a given direction which makes sense, and I see my attempts at making my own AA method were on the right track, though the biggest error I made was blending all those pixels I walk over instead of using the walking over to determine where I sample the end result pixel, though It would have taken ages to figure out how to calculate that position even if I did have that information.

2024-03-21 10:40 UTC, AThousandShips commented
> I'm not surprised that ours is such garbage

Please don't talk about the work of others in that way, it's not friendly or constructive :)

2024-04-01 19:07 UTC, clayjohn commented
I will get in touch with NVidia. It seems that the linked source (https://github.com/hghdev/NVIDIAGameWorks-GraphicsSamples/blob/master/samples/es3-kepler/FXAA/FXAA3_11.h) is a mirror of something that NVidia originally posted

NVidia posted the entire graphics samples to github, but then removed them at some point https://developer.nvidia.com/gameworks-vulkan-and-opengl-samples-30-released (link at end of article). I trust that the mirrors we have seen accurately reproduce the licence (so in theory it should be fine if we do as well), but its best for us to double check with NVidia before doing anything. 

More tidbits:
- Unity uses the mirror hosted by hghdev (https://docs.unity.cn/Packages/com.unity.render-pipelines.universal@16.0/license/Third%20Party%20Notices.html)
- Wayback machine copy of github page (https://web.archive.org/web/20170723104021/https://github.com/NVIDIAGameWorks/GraphicsSamples)
- The samples are still hosted on Archive.org (https://archive.org/details/nvidiagame-works-graphics-samples-master) (they were a zip file before being open sourced on github) (version 3.00 of FXAA only)
- Falcor used to contain a slang version of FXAA (https://github.com/NVIDIAGameWorks/Falcor/blob/f2b53b1bb9f8433f3c9e2570d2dc90dcd2440415/Framework/Source/Data/Effects/FXAA.slang)
- Miniengine has a compute-optimized version of FXAA (https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/MiniEngine/Core/Shaders/FXAAPass1CS.hlsli) (it cites the original source, but also makes nice improvements) Maybe we should consider using this for desktop and something simpler for mobile
- Filament uses a modified version (via G3D) (https://github.com/google/filament/blob/main/filament/src/materials/antiAliasing/fxaa.fs)

I cannot find a copy of the Gameworks samples SDK that contains FXAA 3.11 anywhere. I have a feeling it might have only been released on the official Github which was then deleted. Seeing as there are a number of sources using the same code, I think it is safe to use

2024-04-03 18:05 UTC, Calinou approved these changes
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89), it works as expected. This noticeably improves smoothness, especially on near-parallel lines. Image sharpness isn't noticeably affected by this PR.

**Testing project:** [test_pr_89582.zip](https://github.com/godotengine/godot/files/14856438/test_pr_89582.zip)
*This uses the approach described in https://github.com/godotengine/godot/pull/89582#issuecomment-2004391226 for testing.*

No AA | FXAA Before | FXAA After *(this PR)*
-|-|-
![No AA](https://github.com/godotengine/godot/assets/180032/bd965666-c6fe-4139-abd9-0b7714fba985) | ![FXAA Before](https://github.com/godotengine/godot/assets/180032/a7c8bdbb-54f1-4012-8f4b-6f41a40fc6c9) | ![FXAA After](https://github.com/godotengine/godot/assets/180032/1c49107e-d3b8-449b-8760-e74f292d316d)

4× zoom:

No AA | FXAA Before | FXAA After *(this PR)*
-|-|-
![No AA](https://github.com/godotengine/godot/assets/180032/961134fc-2b07-4061-a459-1a939c97bda8) | ![FXAA Before](https://github.com/godotengine/godot/assets/180032/e0200c39-1486-4ee6-b9a8-f517053d0a30) | ![FXAA After](https://github.com/godotengine/godot/assets/180032/0823eeb7-f6f9-4a8f-8268-75fd75a59228)

Comparisons between the new FXAA and Tesseract's FXAA on Medium and Ultra quality:

FXAA PR | Tesseract FXAA Medium | Tesseract FXAA Ultra
-|-|-
![FXAA After](https://github.com/godotengine/godot/assets/180032/1c49107e-d3b8-449b-8760-e74f292d316d) | ![Tesseract FXAA Medium](https://github.com/godotengine/godot/assets/180032/100d233a-7a7f-417b-9c4f-a5b8fc5538c6) | ![Tesseract FXAA Ultra](https://github.com/godotengine/godot/assets/180032/c68694f7-2aa2-4c34-a1fa-561780cacae9)

4× zoom:

FXAA PR | Tesseract FXAA Medium | Tesseract FXAA Ultra
-|-|-
![FXAA PR](https://github.com/godotengine/godot/assets/180032/4356e402-1e47-4fda-a2ca-82ae1dd99222) | ![Tesseract FXAA Medium](https://github.com/godotengine/godot/assets/180032/629fbe17-7130-4307-9df9-3985e0795ce5) | ![Tesseract FXAA Ultra](https://github.com/godotengine/godot/assets/180032/3d06e633-c3e0-4a4f-be43-a6e1ae2fbf40)

2024-04-03 18:06 UTC, AThousandShips requested changes
Still needs proper attribution, this is not in line with the linked repo's license (i.e. regardless of the source being valid this copy of *it* isn't)

I'll defer to the legal people on he legality of this, and wash my hands of it, I'm not convinced but I defer to them

Though I'd say to check with Nvidia properly before merging

2024-04-03 18:32 UTC, AThousandShips commented
To be clear, I won't stand in the way of this being merged with correct attibution, but I'd very much prefer it if we base it on a version that actually follows Nvidia's licensing in the mirrors, i.e. mentions them as originators at all

2024-04-04 06:36 UTC, mrjustaguy commented
Well for the attribution, I just need to know where to place what

2024-04-06 14:33 UTC, AThousandShips commented
You should copy this license text and add it next to the link you have, assuming we're going with this and not the properly sourced one linked above
https://github.com/kosua20/Rendu/blob/master/LICENSE

2024-04-06 17:41 UTC, mrjustaguy commented
isn't there like a place where we put all of the licenses and their texts?

2024-04-06 17:43 UTC, AThousandShips commented
Not for included code, those cases are for licenses in 3rd party code, the license has to be with the code

2024-04-06 17:49 UTC, AThousandShips approved these changes, later dismissed

2024-05-24 15:50 UTC, bikemurt commented
Any issue with listing the license at the top of this file?
https://github.com/hghdev/NVIDIAGameWorks-GraphicsSamples/blob/master/samples/es3-kepler/FXAA/FXAA3_11.h

Regardless of the fact that this is from a fork of a dead repo, the license attached to the file should still stand:

```
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
```

It stands well enough for Unity to use it (I know, not a great argument, but still, it's something).

2024-06-13 00:48 UTC, clayjohn commented
Revisiting this. I see that I mistakenly thought that the 3.00 version of the Gameworks SDK did not include FXAA 3.11. But it did. Accordingly, I can confirm that the mirror hosted by hghdev contains the most up to date version of FXAA from NVIDIA. Accordingly, we should use that version and we should copy the licence text from that version (https://github.com/hghdev/NVIDIAGameWorks-GraphicsSamples/blob/master/samples/es3-kepler/FXAA/FXAA3_11.h) 

This PR uses the wrong licence (it uses the licence for Rendu, not FXAA).

To move forward with this PR, we need to update it to use the correct licence, and then also reproduce the licence in the `COPYRIGHT.txt` file here (between Bullet and ASSAO):
https://github.com/godotengine/godot/blob/292e50e17e3f6e2509d3178a00204f964a907460/COPYRIGHT.txt#L131-L133

```
Files: ./servers/rendering/renderer_rd/shaders/effects/tonemap.glsl
Comment: FXAA 3.11
Copyright: 2014-2015, NVIDIA CORPORATION
License: BSD-3-clause
```

2024-06-22 17:13 UTC, mrjustaguy commented
Is there anything else that needs to be done for this to be merged then?

2024-06-22 17:26 UTC, AThousandShips commented on servers/rendering/renderer_rd/shaders/effects/tonemap.glsl
> +/*============================================================================
Unterminated comment

2024-06-22 18:35 UTC, clayjohn commented
> Is there anything else that needs to be done for this to be merged then?

Probably not. I still need to do a careful review of the code, but if everything is working well then we can merge this for 4.4!

2024-07-27 21:46 UTC, jams3223 commented
> > Is there anything else that needs to be done for this to be merged then?
> 
> Probably not. I still need to do a careful review of the code, but if everything is working well then we can merge this for 4.4!

This issue has been finally fixed.

2024-11-17 15:12 UTC, mrjustaguy commented
That's outside the scope of this PR IMO, as it's just replacing the algorithm, there are things beyond when it runs that may make sense to change later on.

2025-01-14 21:06 UTC, mrjustaguy commented
Should this be moved to 4.5 now that 4.4 is in beta?

2025-04-23 05:27 UTC, clayjohn approved these changes
I finally did a careful review. I noted 2 things:
1. Simon's adaptation is very significant. The code is clearly the same underlying algorithm, but the style is totally different and it re-rolls the unrolled loops etc. 
2. The copyright notice was only mentioning NVidia. 

I force pushed an update that includes Simon on the copyright notice (following the style of other licenses for code that has been significantly modified) and rebases the PR on master.

I tested the PR and can confirm that it is a strict improvement in terms of quality. This approach is way more expensive than the old one, so I think it is best left for the RD renderers. 

The original author is adamant that this needs to be used in SDR-gamma space, so we may want to consider porting this to its own pass in the future to further improve quality. 

Overall, I think this is ready to merge and get more widespread testing.

2025-04-23 17:11 UTC, merged

2025-04-23 17:11 UTC, Repiteo commented
Thanks!

2025-07-10 11:12 UTC, thottee commented
I think, this FXAA implementations is much worse than the old version. I got smooth picture with the original fxaa, but this fxaa has a lot sharper, lesser anti-aliased picture.

original version:
<img width="211" height="186" alt="image" src="https://github.com/user-attachments/assets/5a77de1f-1792-4c17-ab15-4bc04ba0737f" />

this version:
<img width="211" height="186" alt="image" src="https://github.com/user-attachments/assets/b4c62f10-cddd-4764-819c-03a1abb6c455" />

2025-07-10 14:09 UTC, Calinou commented
> Maybe keep the original version too, and the user can choose, that he/she like more.

We can't really afford to have two competing FXAA implementations in core for maintenance reasons, but remember that 4.5 provides higher-quality SMAA support anyway: https://github.com/godotengine/godot/pull/102330

The performance difference between FXAA and SMAA is pretty small on modern GPUs, yet the increase in quality is significant.

2025-07-10 16:10 UTC, mrjustaguy commented
We could tweak the FXAA parameters to be more aggressive, as the current settings IIRC are just defaults for 3.11

2025-07-11 15:16 UTC, Jamsers commented
There might be some merit to exposing the parameters for users to change to their liking. SMAA could also use some parameters to tweak - SMAA as it's implemented in Godot right now is equivalent to the Ultra preset, but sometimes developers or users might prefer to use High preset equivalent settings so that you get a sharper, more CMAA2 like resolve, like if you're making a multiplayer shooter or something.

Of course, exposed parameters is more code, more maintenance, more work...

2025-07-12 06:14 UTC, thottee commented
I checked the SMAA before I wrote the original post, and the quality is SMAA is clearly better, but I got 170 fps in a single scene with SMAA, instead of 280 fps with FXAA (on a amd ryzen integrated gpu). The reason I like to use FXAA the great performance, even on an integrated gpu, and I think Godot had one of the best quality of FXAA earlier.

@Calinou 
Please check this test again, if you have a little free time. I think, the picture on the right is the old method:
<img width="789" height="343" alt="image" src="https://github.com/user-attachments/assets/6bb27634-35fe-422d-a3b8-cb0e28890dcd" />
It sounds stupid, but I've been using it for a very long time and I know its visual world. Of course, I could be wrong, but if you have some time, please take a look at it again.

Thank you again for your respond.

2025-07-12 06:25 UTC, thottee commented
> We could tweak the FXAA parameters to be more aggressive (and heavier), as the current settings IIRC are just defaults for 3.11
> 
> I don't think we should make FXAA heavier when we have SMAA for a higher quality AA, but maybe the settings could be exposed like with SMAA

@mrjustaguy If you can add some tweeaking possibilities, that would be nice. Than maybe we could tweek that quality we like.

2025-07-31 16:14 UTC, allenwp commented
> The original author is adamant that this needs to be used in SDR-gamma space, so we may want to consider porting this to its own pass in the future to further improve quality.

Yes, the current placement of fxaa in `tonemap.glsl` is surprising and [against the implementation guidelines](https://github.com/hghdev/NVIDIAGameWorks-GraphicsSamples/blob/61350521f6b183d9f694f5c72c11efcf1a0cc665/samples/es3-kepler/FXAA/FXAA3_11.h#L169-L172). I would expect it to be applied just before the final step of debanding or equivalent.

Additionally, I see the [calculation of luma is apparently very important](https://github.com/hghdev/NVIDIAGameWorks-GraphicsSamples/blob/61350521f6b183d9f694f5c72c11efcf1a0cc665/samples/es3-kepler/FXAA/FXAA3_11.h#L163).

I believe the current [luma](https://en.wikipedia.org/wiki/Luma_(video)) calculation is for Rec. 709 with 2.2 gamma, which is close enough to be suitable for sRGB. In regards to HDR output with Rec. 2020, which does not use the nonlinear sRGB colour space, it looks like [(0.2627, 0.6780, 0.0593) coefficients could be used(???)](https://en.wikipedia.org/wiki/YCbCr). It seems that these don't take the ST2084 transfer function into account, though, so I question whether this would be a good calculation of luma for these purposes.

I suspect it would be a lot easier to simply calculate CIE relative luminance from linear values just before conversion to the final non-linear space instead of using luma... But I also suspect the current approach of using luma instead of CIE relative luminance was chosen to produce a value that is perceptually uniform. (In which case, it's extra important that luma is calculated from the final nonlinear RGB values.)

Definitely still a lot to look into and improve here, especially with the introduction of HDR output and new transmission colour spaces...

2025-09-05 17:32 UTC, allenwp commented
> > The original author is adamant that this needs to be used in SDR-gamma space, so we may want to consider porting this to its own pass in the future to further improve quality.
> 
> Yes, the current placement of fxaa in `tonemap.glsl` is surprising and [against the implementation guidelines](https://github.com/hghdev/NVIDIAGameWorks-GraphicsSamples/blob/61350521f6b183d9f694f5c72c11efcf1a0cc665/samples/es3-kepler/FXAA/FXAA3_11.h#L169-L172). I would expect it to be applied just before the final step of debanding or equivalent.
> 
> Additionally, I see the [calculation of luma is apparently very important](https://github.com/hghdev/NVIDIAGameWorks-GraphicsSamples/blob/61350521f6b183d9f694f5c72c11efcf1a0cc665/samples/es3-kepler/FXAA/FXAA3_11.h#L163).
> 
> I believe the current [luma](https://en.wikipedia.org/wiki/Luma_(video)) calculation is for Rec. 709 with 2.2 gamma, which is close enough to be suitable for sRGB. In regards to HDR output with Rec. 2020, which does not use the nonlinear sRGB colour space, it looks like [(0.2627, 0.6780, 0.0593) coefficients could be used(???)](https://en.wikipedia.org/wiki/YCbCr). It seems that these don't take the ST2084 transfer function into account, though, so I question whether this would be a good calculation of luma for these purposes.
> 
> I suspect it would be a lot easier to simply calculate CIE relative luminance from linear values just before conversion to the final non-linear space instead of using luma... But I also suspect the current approach of using luma instead of CIE relative luminance was chosen to produce a value that is perceptually uniform. (In which case, it's extra important that luma is calculated from the final nonlinear RGB values.)
> 
> Definitely still a lot to look into and improve here, especially with the introduction of HDR output and new transmission colour spaces...
> 
> (edit: maybe something like the [ICTCP colorspace, as utilized by BT.2124](https://sid.onlinelibrary.wiley.com/doi/full/10.1002/msid.1146) is a better way to get perceptually uniform "luma" for use in FXAA? Probably too expensive, but it would work with any transfer function...(?))

I looked a bit more into this and I believe the current implementation is the best that can be done without introducing more passes. This is because the entirety of the tonemap shader before FXAA is applied needs to be applied to any adjacent samples of the source texture. With the current positioning of FXAA, this means just `exposure` and `luminance_multiplier`. If it was moved to be near the end of the shader, that would mean all tonemapping, glow, etc. So at this point, it would need a whole other pass... So it's best that it's just kept as is for performance reasons.

2025-09-05 17:35 UTC, clayjohn commented
@allenwp On desktop hardware the cost of doing another pass is trivial. We should consider doing FXAA "properly" for the Forward+ renderer and then doing our cheap fallback only for the mobile renderer