GDScript: Fix object iterator opcodes
godotengine/godot pull request #89639
Opened 2024-03-18 11:54 UTC by dalexeev

* Fixes #89290.

2024-04-24 12:49 UTC, vnen requested changes
Looks good, just need to remove the `TODO` comments.

2024-04-24 12:49 UTC, vnen commented on modules/gdscript/gdscript_vm.cpp
> +				*counter = Variant(); // TODO: Fix in compiler/codegen?
Please remove the `TODO` comment. I think it's fine doing it here, as doing with the codegen would have to execute yet another instruction.

2024-04-24 12:49 UTC, vnen commented on modules/gdscript/gdscript_vm.cpp
> +				*counter = Variant(); // TODO: Fix in compiler/codegen?
Here too.

2024-04-25 23:00 UTC, vnen approved these changes
LGTM. Thanks!

2024-04-25 23:01 UTC, vnen commented
There are some weird errors on the CI tests though, not sure what's going on.

2024-04-26 05:45 UTC, dalexeev commented
> There are some weird errors on the CI tests though, not sure what's going on.

* See #91120.

2024-04-26 06:25 UTC, dalexeev commented
To fix #74686 and #91155 I added the following:

```diff
@@ -2998,11 +2998,10 @@ Variant GDScriptFunction::call(GDScriptInstance *p_instance, const Variant **p_a
 				VariantInternal::initialize(&vref, Variant::ARRAY);
 				*VariantInternal::get_array(&vref) = ref;
 
-				Variant **args = instruction_args; // Overriding an instruction argument, but we don't need access to that anymore.
-				args[0] = &vref;
+				const Variant *args[] = { &vref };
 
 				Callable::CallError ce;
-				Variant has_next = obj->callp(CoreStringNames::get_singleton()->_iter_init, (const Variant **)args, 1, ce);
+				Variant has_next = obj->callp(CoreStringNames::get_singleton()->_iter_init, args, 1, ce);
 
 #ifdef DEBUG_ENABLED
 				if (ref.size() != 1 || ce.error != Callable::CallError::CALL_OK) {
@@ -3332,11 +3331,10 @@ Variant GDScriptFunction::call(GDScriptInstance *p_instance, const Variant **p_a
 				VariantInternal::initialize(&vref, Variant::ARRAY);
 				*VariantInternal::get_array(&vref) = ref;
 
-				Variant **args = instruction_args; // Overriding an instruction argument, but we don't need access to that anymore.
-				args[0] = &vref;
+				const Variant *args[] = { &vref };
 
 				Callable::CallError ce;
-				Variant has_next = obj->callp(CoreStringNames::get_singleton()->_iter_next, (const Variant **)args, 1, ce);
+				Variant has_next = obj->callp(CoreStringNames::get_singleton()->_iter_next, args, 1, ce);
 
 #ifdef DEBUG_ENABLED
 				if (ref.size() != 1 || ce.error != Callable::CallError::CALL_OK) {
```

2024-04-26 09:09 UTC, merged

2024-04-26 09:11 UTC, akien-mga commented
Thanks!