Fix XRBodyModifier3D hip driving for avatars no Root bone
godotengine/godot pull request #89727
Opened 2024-03-21 04:11 UTC by Malcolmnixon

The XRBodyModifier3D node fails to correctly drive avatars which have no Root bone. This occurs on common avatars such as ReadyPlayerMe, Mixamo, and AvaturnMe where the root bone of the skeleton is the hips. The importers Skeleton Retarget doesn't add a Root but instead leaves the Hips as the root bone but with the corrected name.

The XRBodyModifier3D code assumes their must always be a bone associated with the Root tracking joint, and picks bone 0 (the first bone) if it didn't find it by the correct bone name. Unfortunately if it does this with an avatar where bone 0 is the hips then it associates the hips with the root and locks the hips in place.

This PR removes the offending code:
https://github.com/godotengine/godot/blob/89f70e98d209563abb4dbc1f8cd5d76c81eb7940/scene/3d/xr_body_modifier_3d.cpp#L255-L258

With this removed the behavior is as follows:
- The XRBodyModifier3D is still positioned at the trackers "root" location
- The Hips bone is correctly positioned relative to the trackers "root" location

The following video demonstrates four different avatars moving correctly:
1. An AvaturnMe avatar with no Root bone (bone 0 = Hips)
2. A Mixamo avatar with no Root bone (bone 0 = Hips)
3. A ReadyPlayerMe avatar with no Root bone (bone 0 = Hips)
4. A VRM avatar with bone 0 = Root

https://github.com/godotengine/godot/assets/1863707/9f1d90b8-fccc-4769-8bc1-ee7cad062ae9

2024-03-21 05:38 UTC, BastiaanOlij approved these changes
lgtm

2024-03-21 05:47 UTC, fire commented
At a first glance a hips bone is not a root bone. I’ll try to give a proper answer or someone from the animation can be more detailed.

2024-03-21 10:38 UTC, TokageItLab commented
I assume that adding RootBone would seem to be better than making Hip RootBone. (If necessary, such a feature may need to be added to Retargeter as well)

2024-03-21 10:48 UTC, TokageItLab requested changes
I have seen a PR somewhere that tried to extract the root motion from the hips transformation at realtime in AnimationTree, but I remember that it was rejected because it would not be good for performance.

Also, just yesterday, reduz and I were discussing moving the root motion from AnimationMixer to Skeleton3D, and in this case, using Hips as Root is also not a good idea for the same reason as above.

2024-03-21 10:54 UTC, TokageItLab approved these changes
Oh, sorry, I misunderstood the PR.

If this is a PR to "do nothing" instead of "include RootMotion in Hips", then it makes sense.

2024-03-21 17:46 UTC, Malcolmnixon commented
The purpose of this PR is indeed to prevents the hips from erroneously being driven with "root motion" rules.

My Godot Mocap plugins (VMC, Movella, AxisStudio) do synthesize root motion from the hips - because the mocap data-stream they're consuming doesn't include root motion information. It's just a Vector3.slide to project the hips onto the floor, followed by a double-cross-product to orient the joint facing upwards.

```gdscript
	# Get the hips transform
	var hips : Transform3D = _body_tracker.get_joint_transform(XRBodyTracker.JOINT_HIPS)

	# Construct the root under the hips pointing forwards
	var root_y = Vector3.UP
	var root_z = -hips.basis.x.cross(root_y)
	var root_x = root_y.cross(root_z)
	var root_o := hips.origin.slide(Vector3.UP)
	var root := Transform3D(root_x, root_y, root_z, root_o).orthonormalized()
```

2024-03-24 00:28 UTC, merged

2024-03-24 00:34 UTC, akien-mga commented
Thanks!