Fix issue with moving maximized window in macOS
godotengine/godot pull request #90101
Opened 2024-04-01 13:46 UTC by Jiali-Qiu

When opening the Godot editor and maximizing the window by double-clicking the title bar, users are unable to drag the window with the mouse.

With this commit, `mouseDownCanMoveWindow` is enabled, allowing the window to be moved by dragging it.

Fixes #78758.

2024-04-01 13:59 UTC, bruvzg requested changes
This will make the window movable by any unprocessed mouse event, which is not a desired behavior.

What's preventing window move in maximized mode is this condition:

https://github.com/godotengine/godot/blob/master/platform/macos/display_server_macos.mm#L1998-L2000

It was added specifically to prevent moving maximized windows (probably to match behavior on the other platforms, I do not remember why it was done exactly).

2024-04-01 14:13 UTC, bruvzg commented
The mentioned condition probably can be safely replaced with `if (wd.fullscreen) {` to fix moving maximized window.

2024-04-02 06:04 UTC, bruvzg approved these changes

2024-04-04 12:45 UTC, merged

2024-04-04 12:46 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: