Fix `add_root_node()` being no-op
godotengine/godot pull request #90136
Opened 2024-04-02 14:43 UTC by KoBeWi

The method was non-functional since e9bbb97acccc08ae03fde41e4cc6d2dc6722021a, for no reason.

2024-04-02 15:37 UTC, ryevdokimov commented
I'm not sure it's a great idea to start revitalizing the EditorPlugin class since it's borderline entirely deprecated by other classes. This functionality seems like it would fit better as part of EditorInterface.

2024-04-02 15:38 UTC, ryevdokimov requested changes
After adding the root node, the tab for the scene will still show as [empty].

2024-04-02 16:05 UTC, KoBeWi commented
> After adding the root node, the tab for the scene will still show as [empty].

Fixed.

> I'm not sure it's a great idea to start revitalizing the EditorScript class since it's borderline entirely deprecated by other classes.

The base functionality of this class is running scripts directly in the editor, which is still relevant. Methods other than `_run()` are mostly extras that we can't remove for compatibility reasons.

2024-04-02 16:16 UTC, ryevdokimov commented
> The base functionality of this class is running utility scripts in the editor, which is still relevant. Methods other than `_run()` are mostly extras that we can't remove for compatibility reasons.

Would this method still be under the purview of compatibility after not having worked for nearly a decade haha. It has been marked unimplemented since 3.0. I can see a rational for the answer being yes, so I won't press the matter. 

I still think it makes sense at least for a similar function to be implemented in EditorInterface, and this one to be marked as deprecated (along with `get_scene()`, since get_tree().current_scene does the same thing).

2024-04-03 00:21 UTC, ryevdokimov commented
When using this method with scenes, would it make sense for this method to add an inherited instance of a scene instead of just opening a scene? 

![image](https://github.com/godotengine/godot/assets/105675984/7aff55ab-69eb-4417-a2c7-c05e19e9ecf2)

vs

![image](https://github.com/godotengine/godot/assets/105675984/6314236e-b0d4-4c0e-8bde-f0adbaf8b6d5)

2024-04-03 07:43 UTC, KoBeWi commented
This PR is supposed to make the method functional again the way it was designed, any additional changes can be done later.

> When using this method with scenes, would it make sense for this method to add an inherited instance of a scene instead of just opening a scene?

It does not open a scene, you need to be already in empty scene to use it.

2024-04-03 12:50 UTC, KoBeWi commented
I made it create inherited scene when adding an instance.

2024-04-03 13:54 UTC, ryevdokimov requested changes
The tab should probably be marked as unsaved similar to as if you were creating a new scene through the GUI.

2024-04-03 18:14 UTC, ryevdokimov approved these changes
Works great now. 

Along with https://github.com/godotengine/godot/pull/90057 this will fully implement: 

https://github.com/godotengine/godot-proposals/issues/3907, giving users the option to create a new inherited scene either over an empty scene or straight into a new tab.

2024-06-21 14:43 UTC, akien-mga approved these changes

2024-06-21 14:53 UTC, merged

2024-06-21 14:53 UTC, akien-mga commented
Thanks!