Fix double click in cjk characters and create unit test
godotengine/godot pull request #90178
Opened 2024-04-03 17:28 UTC by Crashim03

Fixes #75808 -> selecting chinese, japanese and korean characters with double click. The problem was with the external library UBreakIterator.
Solution: Check manually if the character is cjk.

2024-04-15 09:13 UTC, Crashim03 commented
@KoBeWi Hi! If there aren't any problems with my fix, I would kindly ask a review. Thank you!

2024-04-15 10:23 UTC, akien-mga commented on tests/test_utils.h
> +
This file is for utilities for the test suite, not for testing `char_utils.h`.

String tests should go to `tests/core/string/test_string.h` (or if needed a new `tests/core/string/test_char_utils.h`).

2024-04-15 10:55 UTC, bruvzg reviewed
We probably should try checking break iterator config (or add a second iterator for `UBRK_WORD`) instead of adding custom checks.

2024-04-15 10:55 UTC, bruvzg commented on modules/text_server_adv/text_server_adv.cpp
> +							sd->breaks[pos] = true;
```suggestion
							sd->breaks[pos] = false;
```

`true` is for hard breaks (new line characters), word breaks are soft and should be `false`.

2024-04-15 11:36 UTC, bruvzg requested changes
Actually, this change does not make any sense and will break proper line breaking. And the issue can't be here, since line breaking do work, something should be wrong in the `TextEdit`.

2024-04-15 12:01 UTC, bruvzg commented
The actual issues seems to be in `TextServer::shaped_text_get_word_breaks` and `TextEdit`, not in the ICU iterator.

2024-04-15 19:12 UTC, bruvzg commented
To summarize my findings:
- There's an issue in `shaped_text_get_word_breaks` that can result in missing words.
- There's an issue in `TextEdit` which prevents selecting single character words by double-clicking.
- ICU iterator without setting locale to specific language with `@lb=strict` will add break after every CJK character, it's OK for line breaking, but probably not desired for word selection.
- Adding changes from this PR will prevent a lot of line breaks, so it's not a suitable fix. Also, different types of breaks are already marked and known after ICU iterator, so there's no need to hard-code character check (there are a lot more CJK character ranges beside used in this PR). It should be possible to modify `shaped_text_get_word_breaks` to skip non-space/punctuation breaks, which should be better for word selection (and won't change line breaking).

I'll do PR tomorrow (includes some public API changes to keep old behavior accessible, so require compact wrapper).

2024-04-15 19:56 UTC, kitbdev commented
>There's an issue in TextEdit which prevents selecting single character words by double-clicking.

- There is a separate issue for this https://github.com/godotengine/godot/issues/89551
- and it's fixed in https://github.com/godotengine/godot/pull/89556

2024-04-20 20:38 UTC, akien-mga approved these changes
@teacher: I met your student today and confirm this was a top-notch first contribution to an open source project of the scale of Godot ;)

Won't be merged as is as assessed by the senior maintainer in this area (not a junior task in the end), but this was a good attempt, with test suite included.

(Also do reach out, I'm interested in your program to get students contributing to open source ;))

2024-04-22 20:29 UTC, closed without merging

2024-04-22 20:30 UTC, akien-mga commented
Superseded by #90732. Thanks for the contribution!