Fix #84983: Choosing EditorSyntaxHighlighter in TextEdit crashes the project
godotengine/godot pull request #90267
Opened 2024-04-05 15:41 UTC by tiagorodrigues35

Instead of crashing without any debug console information, it now at least creates an instance and gives a warning. Not an ideal solution, since it doesn't say which object called the EditorSyntaxHighlighter.

2024-04-05 15:43 UTC, AThousandShips commented
This doesn't seem like a clean fix, it looks very hacky to me, a more general fix should be made IMO

2024-04-05 16:31 UTC, AThousandShips requested changes
This isn't a crash, it's a case of the engine failing to load the scene, that's not a crash, and we shouldn't allow editor only nodes to be instanced just so we can not fail to load an invalid scene IMO

Regardless this is *not* the way to solve this issue, the solution, if we should solve it at all, would be to allow loading invalid scenes somehow instead

2025-07-09 19:39 UTC, KoBeWi commented
> Instead of crashing without any debug console information

But the information _is_ written in the console (the external one).

Note that the same issue can happen e.g. when a scene dependency is missing. The scene can be loaded in the editor, but fails at runtime. We could improve it, but as said above, this PR is not the correct fix (aside from being too specific).

2025-07-09 19:49 UTC, KoBeWi commented
Closing due to inactivity (the initial comments were never addressed for a long time).

Thanks for the contribution nonetheless. Note that this is a deeper problem and not necessarily good for a first issue.

2025-07-09 19:49 UTC, closed without merging