Fix Node3D.set_global_rotation() resetting node scale.
godotengine/godot pull request #90584
Opened 2024-04-12 16:43 UTC by BMagnu

Fixes #74162.

The error was caused because the basis for the target global transform was entirely recreated. This process did not account for the scale of the basis of the current global transform.
This PR amends this by scaling the recreated basis for the global transform by the current global scale of the Node3D. Note that this scaling has to be done from the current global scale and not from the local scale of the Node3D.
This is important, otherwise a scaled parent of the Node3D would cause incorrect results on overwriting the global transform basis.

2024-04-12 19:13 UTC, ajreckof approved these changes
LGTM

2024-04-16 09:58 UTC, fire approved these changes
@aaronfranke I think this is correct?

2024-04-16 09:59 UTC, AThousandShips commented
This should be valid to fix, but I wouldn't cherry pick it as it at least mildly breaks compatibility, people might very well rely on it resetting scale and this would break their code

2024-04-16 10:01 UTC, BMagnu commented
Agreed, cherry picking it back into 4.2 is dangerous as only a patch-level fix for this reason.
Still, should be fine for the yet-unreleased 4.3

2024-04-16 11:13 UTC, aaronfranke requested changes

2024-04-16 11:13 UTC, aaronfranke commented on scene/3d/node_3d.cpp
> +	transform.basis = Basis::from_euler(p_euler_rad).scaled(transform.basis.get_scale());
```suggestion
	transform.basis = Basis::from_euler(p_euler_rad) * Basis::from_scale(transform.basis.get_scale());
```

2024-04-16 11:22 UTC, aaronfranke approved these changes

2024-04-16 11:37 UTC, aaronfranke commented
> This should be valid to fix, but I wouldn't cherry pick it as it at least mildly breaks compatibility, people might very well rely on it resetting scale and this would break their code

I would lean towards cherry-picking this. It is really weird for setting the rotation to change the scale. I would assume most users are using this method with unscaled objects, or else they would've run into this bug before.

2024-04-16 12:08 UTC, AThousandShips commented
> or else they would've run into this bug before.

This bug was discovered before 4.0 released so it's absolutely been run into, the report in question is from march last year, so just after 4.0, and there was a report before that with less details from January of the same year, so I don't think this is necessarily unnoticed

2024-04-18 10:28 UTC, merged

2024-04-18 10:28 UTC, akien-mga commented
Thanks!