Add option to open online doc for selected class in script editor
godotengine/godot pull request #90952
Opened 2024-04-20 16:22 UTC by Gaktan

When the script editor's current tab is a script (or no tab is opened):
![image](https://github.com/godotengine/godot/assets/1674095/c804af0b-1baa-4fbd-9f13-27a3284c76f9)

When the current tab is a class:
![image](https://github.com/godotengine/godot/assets/1674095/eb3233ef-cfff-42ef-b533-34742c7976db)

There might be an issue if we try to open a custom class, but from what I can tell, it's not possible to open the documentation for a custom class in the editor. (At least I was not able to)

2024-05-07 23:45 UTC, Calinou requested changes
Tested locally, it mostly works as expected. I've tested various classes such as HTTPClient, AnimatedSprite2D and so on.

One issue is that in user-defined classes, clicking **Open in Online Docs** will point to a nonexisting page. For instance, a class named `Test` will point me to `https://docs.godotengine.org/en/latest/classes/class_test.html` which doesn't exist. I suggest finding a way to disable this button for user-defined classes.

2024-05-08 20:57 UTC, Gaktan commented
Yes indeed, I did not test this since I was not able to open the documentation for the custom classes in my project. I assumed it was not possible.

Can you clarify the steps you used to open a custom class's documentation?

2024-05-09 00:36 UTC, Calinou commented
> Can you clarify the steps you used to open a custom class's documentation?

Add this line above an `extends` declaration in a script:

```gdscript
class_name Test
```

Then use **Search Help** in the top-right corner of the script editor and search for `Test`, and open its page.

2024-05-09 08:49 UTC, Gaktan commented
That's odd, it's not working for me:
![image](https://github.com/godotengine/godot/assets/1674095/c5484a47-dd33-4514-b6ee-4744f1743f86)

2024-05-09 11:14 UTC, Gaktan commented
Nevermind, I figured it out. The documentation is not available for classes that only have private attributes and functions by the looks of it.

2024-05-09 12:11 UTC, Gaktan commented
This now works with custom classes.
I have no idea if this fix works with custom C++ classes though, as I have no way to test this currently.

2024-05-13 17:22 UTC, Calinou requested changes
The button now correctly displays **Online Docs** when selecting a custom class named `Test`, but clicking it still opens the page `https://docs.godotengine.org/en/latest/classes/class_test.html` which doesn't exist.

2024-05-13 17:45 UTC, Chaosus commented
Commits needs to be squashed (see https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase).

2024-05-16 11:08 UTC, Calinou approved these changes
Tested locally, it works as expected now.

2024-05-17 09:15 UTC, merged

2024-05-17 09:17 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: