Added fix for android build on windows
godotengine/godot pull request #91339
Opened 2024-04-30 00:19 UTC by TCROC

Fixes this issue here: https://github.com/godotengine/godot/issues/91195

Copying in issue description for ease of reading:

### Tested versions

Godot v4.3.dev.mono (463ede1f7)

### System information

Windows 10

### Issue description

Scons currently errors when building an apk during the template creation process.  This is due to this line here: 

https://github.com/godotengine/godot/blob/11d3768132582d192b8464769f26b493ae822321/platform/android/SCsub#L87

There are 2 issues with this line.

1. It is executing the bash script instead of the batch script
2. It appears that Windows has some special cases with ``subprocess.call`` as can be seen in this stack overflow: https://stackoverflow.com/a/4616867/9733262

- That particular solution suggests passing "Shell=true", but when testing that also causes its own issues due to trying to treat the ``.`` operator as a program itself.

- This solution appears to actually fix it on my local test: https://stackoverflow.com/a/39474235/9733262

This was discovered when adding windows support to my ``godot-src`` project over here: https://github.com/Lange-Studios/godot-src.git.

2024-04-30 13:01 UTC, m4gr3d requested changes

2024-04-30 13:01 UTC, m4gr3d commented on platform/android/SCsub
> +            gradle_process = ["./gradlew"]
> It is executing the bash script instead of the batch script

Would replacing `./gradlew` with `./gradlew.bat` on windows fix the issue? That's the approach we usually follow in the codebase.

> It appears that Windows has some special cases with subprocess.call as can be seen in this stack overflow: https://stackoverflow.com/a/4616867/9733262

The link you refer to mentions that this is only needed for commands built into the Shell and not required for executing a batch file.

2024-04-30 13:11 UTC, TCROC commented on platform/android/SCsub
> +            gradle_process = ["./gradlew"]
I originally tested with ``./gradlew.bat`` as that seemed like the obvious approach.  I can confirm, that does not work on Windows.  I did not do any research as to why it didn't work in Python BUT I am aware that the Rust programming language had a similar CVE regarding .bat files: https://blog.rust-lang.org/2024/04/09/cve-2024-24576.html

This may be why (at least my version of) python prevents executing the .bat file directly.

The recommended approach both in that Stack Overflow and Rust's CVE seems to be going through ``cmd`` ``/c``.

I see you want me to test shel=(os.name == "nt") below so I can grab the exact error message when trying to invoke the .bat file directly as well.  Then we can discuss which approach we want to take.

2024-04-30 13:14 UTC, TCROC commented
> > That particular solution suggests passing "Shell=true", but when testing that also causes its own issues due to trying to treat the `.` operator as a program itself.
> 
> Does this fail on Windows specifically? Or on other platforms? If it's not on windows try making it `shell=(os.name == "nt"))`

It works on my POP OS Linux machine but does not work on my Windows machine.  I have not tested my Mac, but I suspect the Mac will work fine since it invokes shell scripts.

Is this what you are asking or am I misunderstanding the question?

2024-04-30 13:15 UTC, AThousandShips commented
What I asked is does adding `Shell=true` fail on Windows, or on other OSs

2024-04-30 13:15 UTC, TCROC commented
> > > That particular solution suggests passing "Shell=true", but when testing that also causes its own issues due to trying to treat the `.` operator as a program itself.
> > 
> > 
> > Does this fail on Windows specifically? Or on other platforms? If it's not on windows try making it `shell=(os.name == "nt"))`
> 
> It works on my POP OS Linux machine but does not work on my Windows machine. I have not tested my Mac, but I suspect the Mac will work fine since it invokes shell scripts.
> 
> Is this what you are asking or am I misunderstanding the question?

Oh I think I understand the question.  Yes it fails on Windows specifically.  I have not encountered this on any of my other machines.

2024-04-30 13:19 UTC, TCROC commented
> What I asked is does adding `Shell=true` fail on Windows, or on other OSs

I originally tried ``Shell=true`` per the stack overflow suggestions and it also failed on Windows.  It did not seem to make a difference on my Windows machine.  This was my experience:

Windows:

- gradlew shell script = fail ❌
- ``Shell=true`` = fail ❌
- calling ``gradlew.bat`` directly = fail ❌
- ``cmd /c gradlew.bat`` = success ✅

I'm going to double check this later today to confirm.  But this was my experience with it last week when I tested.

2024-04-30 13:59 UTC, m4gr3d commented on platform/android/SCsub
> +            gradle_process = ["./gradlew"]
Thanks for checking! 

Based on your comments, the approach looks good to me so I should be able to approve once you address @AThousandShips's comments.

I won't have access to my windows machine for a week, so I'm unable to validate the fix myself. As such, additional testing is welcomed!

2024-04-30 14:02 UTC, AThousandShips commented
Can't tell exactly how to solve this since I don't work with android, so I've got no further comments here

2024-04-30 15:18 UTC, TCROC commented on platform/android/SCsub
> +            gradle_process = ["./gradlew"]
Answers all questions in this comment here: https://github.com/godotengine/godot/pull/91339#issuecomment-2085622825

2024-04-30 16:57 UTC, m4gr3d approved these changes

2024-05-01 07:56 UTC, merged

2024-05-01 07:57 UTC, akien-mga commented
Thanks!