Add cone angle control to particle emission ring shape
godotengine/godot pull request #91973
Opened 2024-05-15 08:49 UTC by Arnklit

This adds a Cone Angle control to the particles ring emission shape for GPU and CPU particles.

![image](https://github.com/godotengine/godot/assets/4955051/3f9aee31-f128-4572-8552-2bf119a8d77f)

As far as I know there is no way to ensure completely correct distribution when the shape get's more and more cone shaped. I skew the distribution using pow here, but if someone knows of a better way that would be great.

Note: this will require some additions to https://github.com/godotengine/godot/pull/86902

2024-05-15 08:50 UTC, AThousandShips commented
Please open a [proposal](https://github.com/godotengine/godot-proposals/issues) to track the support and details of this feature

2024-05-15 08:55 UTC, Arnklit commented
> Please open a [proposal](https://github.com/godotengine/godot-proposals/issues) to track the support and details of this feature

Linked the existing proposal https://github.com/godotengine/godot-proposals/issues/6761.
Maybe @QbieShay has time to look this over and see if it works well enough.

2024-05-16 00:28 UTC, Calinou requested changes
Tested locally, it mostly works as expected.

**Testing project:** [test_pr_91973.zip](https://github.com/godotengine/godot/files/15328084/test_pr_91973.zip)

I suggest adding property hints to the ring properties, as right now, you can drag them towards negative values, which doesn't make sense.

![image](https://github.com/godotengine/godot/assets/180032/1f53e706-3241-47a1-8728-d700221403f4)

The angle in particular should be clamped between `0.0` and `180.0`, and the `degrees` inspector property hint should be used (see Node2D's `rotation` property for an example).

Emission Height, Radius and Inner Radius should be limited to positive values as well, as strange things can happen if you use negative values:

https://github.com/godotengine/godot/assets/180032/d0db0757-4de8-4500-b9d3-5031d10ab9a7

https://github.com/godotengine/godot/assets/180032/1394d96d-72ec-4261-b250-69b1e39ac940

The angle property feels a bit strange, as the cone already has a starting angle of 0 degrees when the value is about 45 in the inspector:

https://github.com/godotengine/godot/assets/180032/053cbe54-a591-4884-994e-453bb4a4cde6

2024-05-16 09:19 UTC, Arnklit commented
Thanks @Calinou . I added the property hints and it makes it nicer and I think resolves any strange behaviour.

![image](https://github.com/godotengine/godot/assets/4955051/08c02b6d-42eb-44e2-96cd-4de06afe9eda)

It did make me wonder whether it might make sense to turn the inner radius and radius into min and max values with the `ADD_MIN_MAX_PROPERTY`

2024-05-16 09:37 UTC, Arnklit commented
Just realised that the shader crashes on radius 0. Gonna have to max the value with 0.001. Give me a minute. I'll do another commit.

2024-05-20 09:56 UTC, Arnklit commented
OK, so I think I worked out all unexpected behaviour. I ended up doing it by limiting the angle between 0 and 90 instead of 0 and 180. This avoided all the strange behaviour when inner radius was larger than outer radius and you can still create the same shapes, you might just have to change the orientation of the shape to do so.

2024-06-10 08:21 UTC, Arnklit commented
@Calinou if you have time to give this another look I'd appreaciate it :)

2024-07-09 15:28 UTC, Mickeon reviewed
Documentation itself is fine if that was of any concern.

2024-07-09 18:28 UTC, Calinou approved these changes
Tested locally (rebased on top of 26d1577f3985363faab48a65e9a0d9eed0e26d86 with "Accept incoming" chosen during rebase), it works as expected. The new behavior (with the effective angle clamped if the end of the cone is reached) makes sense.

Code and documentation looks good to me.

2024-07-09 18:30 UTC, Calinou commented on doc/classes/ParticleProcessMaterial.xml
> +			The angle of the cone when using the emitter [constant EMISSION_SHAPE_RING].
```suggestion
			The angle of the cone when using the emitter [constant EMISSION_SHAPE_RING]. The default angle of 90 degrees results in a ring, while an angle of 0 degrees results in a cone. Intermediate values will result in a ring where one end is larger than the other.
			[b]Note:[/b] The angle is clamped if the ring's end is reached to form a perfect cone.
```

2024-07-09 18:30 UTC, Calinou commented on doc/classes/CPUParticles3D.xml
> +			The angle of the cone when using the emitter [constant EMISSION_SHAPE_RING].
```suggestion
			The angle of the cone when using the emitter [constant EMISSION_SHAPE_RING]. The default angle of 90 degrees results in a ring, while an angle of 0 degrees results in a cone. Intermediate values will result in a ring where one end is larger than the other.
			[b]Note:[/b] The angle is clamped if the ring's end is reached to form a perfect cone.
```

2024-07-15 15:53 UTC, Arnklit commented on doc/classes/ParticleProcessMaterial.xml
> +			The angle of the cone when using the emitter [constant EMISSION_SHAPE_RING].
done

2024-07-15 15:53 UTC, Arnklit commented on doc/classes/CPUParticles3D.xml
> +			The angle of the cone when using the emitter [constant EMISSION_SHAPE_RING].
done

2024-07-15 15:53 UTC, Arnklit commented
Rebased and added in the docs as suggested by @Calinou

2024-07-15 16:34 UTC, Calinou approved these changes

2024-08-21 21:22 UTC, akien-mga commented
The docs need to be moved so that they are in alphabetical order: https://github.com/godotengine/godot/actions/runs/9942582709/job/27464431529?pr=91973

2024-08-21 22:42 UTC, Arnklit commented
Oh sorry, did not release that. I will do this when I'm back from vacation, or if I find a free evening soon.

2024-09-02 16:09 UTC, merged

2024-09-02 16:09 UTC, akien-mga commented
Thanks!