Write Object variants with '\n' between properties
godotengine/godot pull request #92102
Opened 2024-05-19 02:28 UTC by robert-wallis

Adds line feeds '\n' after commas for each property in an `Object`.

This mirroring the format for `Dictionary` variants in `core/variant/variant_parser.cpp` [lines 2054-2066](https://github.com/robert-wallis/godot/commit/eebdc3b9ca283ad826b76e423ad8e91b487acaaf#diff-8fa43a0158f72fe267697c83f42d65e567c538c003320e7a9417faffd51f8bfeL2054-L2066)

## Before
![before diff](https://github.com/godotengine/godot/assets/145938/b29549b2-c0ca-4644-8174-4d259700fd66)
## After
![after diff](https://github.com/godotengine/godot/assets/145938/ac22485a-4ae3-45d2-bbd3-9898c9efc803)

This makes reading the diff easier.  It will likely help auto-merge conflicts when a different properties in an `Object` are changed at the same time.

2024-05-19 02:37 UTC, robert-wallis commented
## Old ui_accept Example
`project.godot`
```tscn
ui_accept={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":4194309,"physical_keycode":0,"key_label":0,"unicode":0,"echo":false,"script":null)
, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":4194310,"physical_keycode":0,"key_label":0,"unicode":0,"echo":false,"script":null)
, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":32,"physical_keycode":0,"key_label":0,"unicode":32,"echo":false,"script":null)
, Object(InputEventJoypadButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"button_index":0,"pressure":0.0,"pressed":false,"script":null)
]
}
```
## New ui_accept Example
`project.godot`
```tscn
ui_accept={
"deadzone": 0.5,
"events": [Object(
InputEventKey,
"resource_local_to_scene":false,
"resource_name":"",
"device":0,
"window_id":0,
"alt_pressed":false,
"shift_pressed":false,
"ctrl_pressed":false,
"meta_pressed":false,
"pressed":false,
"keycode":4194309,
"physical_keycode":0,
"key_label":0,
"unicode":0,
"location":0,
"echo":false,
"script":null
), Object(
InputEventKey,
"resource_local_to_scene":false,
"resource_name":"",
"device":0,
"window_id":0,
"alt_pressed":false,
"shift_pressed":false,
"ctrl_pressed":false,
"meta_pressed":false,
"pressed":false,
"keycode":4194310,
"physical_keycode":0,
"key_label":0,
"unicode":0,
"location":0,
"echo":false,
"script":null
), Object(
InputEventKey,
"resource_local_to_scene":false,
"resource_name":"",
"device":0,
"window_id":0,
"alt_pressed":false,
"shift_pressed":false,
"ctrl_pressed":false,
"meta_pressed":false,
"pressed":false,
"keycode":32,
"physical_keycode":0,
"key_label":0,
"unicode":32,
"location":0,
"echo":false,
"script":null
), Object(
InputEventJoypadButton,
"resource_local_to_scene":false,
"resource_name":"",
"device":-1,
"button_index":0,
"pressure":0.0,
"pressed":false,
"script":null
)]
}
```

2024-05-19 10:58 UTC, AThousandShips commented
You need to change this part of the GDScript tests to compensate for the new newlines:
```diff
diff --git a/modules/gdscript/tests/scripts/runtime/features/metatypes.gd b/modules/gdscript/tests/scripts/runtime/features/metatypes.gd
index 6c5df32ffe..8a57127271 100644
--- a/modules/gdscript/tests/scripts/runtime/features/metatypes.gd
+++ b/modules/gdscript/tests/scripts/runtime/features/metatypes.gd
@@ -12,7 +12,7 @@ var test_class := MyClass
 var test_enum := MyEnum

 func check_gdscript_native_class(value: Variant) -> void:
-       print(var_to_str(value).get_slice(",", 0).trim_prefix("Object("))
+       print(var_to_str(value).get_slice(",", 0).trim_prefix("Object(\n"))

 func check_gdscript(value: GDScript) -> void:
        print(value.get_class())
```

2024-05-21 15:15 UTC, Calinou commented
This would also be a good opportunity to add a space between the key and value (i.e. add a space after `:`).

2024-05-21 17:49 UTC, robert-wallis commented
> This would also be a good opportunity to add a space between the key and value (i.e. add a space after `:`).

Also it matches how `Dictionary` serializes.

✅ Done :)

2024-06-23 19:24 UTC, Mickeon commented
I do agree this makes sense but strictly for the InputEvent example I worry it would actually make readability _worse_.

2024-06-23 23:16 UTC, robert-wallis commented
Readability here is definitely subjective.  Personally I think the readability of diffs is completely unreadable without this change.  It's very hard to find the `"location":0` addition when it's all on one line.  But I agree for adds, when the whole line is new, the details are forgettable.

These files however are not written by users.  And they are text files (not binary) so that VCS can see the changes.  Having changes on newlines enables the VCS to make the correct decisions during merges.  That to me is the main reason to accept this proposal.

2025-04-15 15:16 UTC, Calinou reviewed
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/e5ccaa79e2a2d5551369bd6cc1f8ed654a791275), it works as expected.

We may want to consider adding a tab of indentation after each line break to improve readability, like https://github.com/godotengine/godot/pull/32124 does for arrays and dictionaries. However, managing nested objects this way (while possible) is nontrivial. We should make sure to do this *before* merging the PR to avoid unnecessarily doubled diffs for people using `master` to work on projects.

Note that https://github.com/godotengine/godot/pull/32124 already affects all other Variant types, but it doesn't touch Object. So this PR can probably be merged separately.

2025-04-15 15:18 UTC, AThousandShips approved these changes

2025-04-16 05:34 UTC, robert-wallis commented
I also like tabs better.  Here's an example of what it looks like now:
```tscn
ui_cancel={
"deadzone": 0.5,
"events": [Object(InputEventKey,
	"resource_local_to_scene": false,
	"resource_name": "",
	"device": 0,
	"window_id": 0,
	"alt_pressed": false,
	"shift_pressed": false,
	"ctrl_pressed": false,
	"meta_pressed": false,
	"pressed": false,
	"keycode": 4194305,
	"physical_keycode": 0,
	"key_label": 0,
	"unicode": 0,
	"location": 0,
	"echo": false,
	"script": null
), Object(InputEventJoypadButton,
	"resource_local_to_scene": false,
	"resource_name": "",
	"device": -1,
	"button_index": 1,
	"pressure": 0.0,
	"pressed": false,
	"script": null
)]
}
```

2025-06-20 12:14 UTC, Gnumaru commented
Is there hope of this being merged for 4.5?

2025-06-20 12:25 UTC, AThousandShips commented
We're in feature freeze so we don't merge new features in general, don't think this one will be an exception

2025-09-24 15:56 UTC, aaronfranke commented
This was discussed in the Godot Core Team meeting. Some notes from the meeting:

* We want this feature, improving human readability and version controllability is desired.
* We want indentation to improve human readability even more.
* We want trailing commas to ensure that adding an item to the end of the array is version control friendly.
* We need to have this tested with nested objects.
* We want to do this in a small number of commits to avoid noisy diffs for users, we only want to change this in one Godot release.

2025-09-24 16:17 UTC, Ivorforce commented
Can anybody confirm or deny whether nested objects are possible in these files? The PR in its current state adds a single `\t` in all cases, but if nesting is possible, it will need a context and nested indentation support.

2025-09-26 08:44 UTC, robert-wallis commented
Nested objects is interesting, so I did an experiment adding tabs based on the recursion level:
https://github.com/robert-wallis/godot/commit/cdee2f1e4974d28c23da8877d96b12f5f0676f7f

Is this the right direction?  If so maybe I should do the same to Dictionary?

I don't necessarily like the temporary strings, but it is easy to read, and presumably better than a for loop with `+=` for each tab.

The experiment produces tabs like this, although I haven't directly tested nested Objects, it would increase up to MAX_RECURSION

```
ui_focus_next={
"deadzone": 0.5,
"events": [Object(InputEventKey,
		"resource_local_to_scene": false,
		"resource_name": "",
		"device": 0,
		"window_id": 0,
		"alt_pressed": false,
		"shift_pressed": false,
		"ctrl_pressed": false,
		"meta_pressed": false,
		"pressed": false,
		"keycode": 4194306,
		"physical_keycode": 0,
		"key_label": 0,
		"unicode": 0,
		"location": 0,
		"echo": false,
		"script": null
	), Object(InputEventJoypadButton,
		"resource_local_to_scene": false,
		"resource_name": "",
		"device": -1,
		"button_index": 4,
		"pressure": 0.0,
		"pressed": false,
		"script": null
	)]
}
click={
"deadzone": 0.5,
"events": [Object(InputEventMouseButton,
		"resource_local_to_scene": false,
		"resource_name": "",
		"device": -1,
		"window_id": 0,
		"alt_pressed": false,
		"shift_pressed": false,
		"ctrl_pressed": false,
		"meta_pressed": false,
		"button_mask": 0,
		"position": Vector2(0, 0),
		"global_position": Vector2(0, 0),
		"factor": 1.0,
		"button_index": 1,
		"canceled": false,
		"pressed": false,
		"double_click": false,
		"script": null
	)]
}
```

2025-10-04 04:44 UTC, robert-wallis commented
Update, I got the tabs, trailing commas, and tests for nested Objects working for `Object` types

But this means that `project.godot` is a little awkward, because the tabbing level is not persisted in `Array` and `Dictionary` types for this keyboard event:
```gd
ui_cancel={
"deadzone": 0.5,
"events": [Object(InputEventKey,
			"resource_local_to_scene": false,
			"resource_name": "",
			"device": 0,
			"window_id": 0,
			"alt_pressed": false,
			"shift_pressed": false,
			"ctrl_pressed": false,
			"meta_pressed": false,
			"pressed": false,
			"keycode": 4194305,
			"physical_keycode": 0,
			"key_label": 0,
			"unicode": 0,
			"location": 0,
			"echo": false,
			"script": null,
		), Object(InputEventJoypadButton,
			"resource_local_to_scene": false,
			"resource_name": "",
			"device": -1,
			"button_index": 1,
			"pressure": 0.0,
			"pressed": false,
			"script": null,
		)]
}
```

So I'll continue to work on `Array` and `Dictionary` tabbing

2025-10-04 06:27 UTC, robert-wallis commented
Looking at the test failure: https://github.com/godotengine/godot/actions/runs/18240326106/job/51941224834#step:22:51 and the stuff I had to do to the oneline Dictionary out file https://github.com/godotengine/godot/pull/92102/files#diff-b7f66414eb9d31e9aeadecd64037bab227a3af2841a08e2a2af5a0f9d4039af1L13-L29

I think maybe we need a parameter to Variant::write that says whether to 'pretty_print' or not, and if not then it keeps everything in one line.

2025-10-05 09:15 UTC, AThousandShips commented on core/variant/variant_parser.cpp
> +			String tab_depth = tab_str.repeat(std::max(0, p_recursion_count));
```suggestion
			String tab_depth = tab_str.repeat(MAX(0, p_recursion_count));
```
Prefer using our own macros

2025-10-05 09:15 UTC, AThousandShips commented on core/variant/variant_parser.cpp
> +			String tab_parent_depth = tab_str.repeat(std::max(0, p_recursion_count - 1));
```suggestion
			String tab_parent_depth = tab_str.repeat(MAX(0, p_recursion_count - 1));
```

2025-10-05 09:15 UTC, AThousandShips commented on core/variant/variant_parser.cpp
> +			// Add a tab for every recursion depth, except this one and it's parent
```suggestion
			// Add a tab for every recursion depth, except this one and its parent.
```

2025-10-05 09:15 UTC, AThousandShips commented on core/variant/variant_parser.cpp
> +					// Add a tab for every recursion depth, except this one and it's parent
```suggestion
					// Add a tab for every recursion depth, except this one and its parent.
```

2025-10-05 09:15 UTC, AThousandShips commented on core/variant/variant_parser.cpp
> +					String tab_depth = tab_str.repeat(std::max(0, p_recursion_count));
```suggestion
					String tab_depth = tab_str.repeat(MAX(0, p_recursion_count));
```

2025-10-05 09:15 UTC, AThousandShips commented on core/variant/variant_parser.cpp
> +					String tab_parent_depth = tab_str.repeat(std::max(0, p_recursion_count - 1));
```suggestion
					String tab_parent_depth = tab_str.repeat(MAX(0, p_recursion_count - 1));
```

2025-10-05 09:15 UTC, AThousandShips commented on tests/core/variant/test_variant.h
> +	Object o1 = Object();
Should preferably use pointer and proper memory management:
```suggestion
	Object *o1 = memnew(Object);
```

2025-10-05 09:15 UTC, AThousandShips commented on tests/core/variant/test_variant.h
> +	CHECK(o_str_enc == expected_str_enc);
```suggestion
	CHECK(o_str_enc == expected_str_enc);
	
	memdelete(o1);
```

2025-10-05 09:15 UTC, AThousandShips commented on tests/core/variant/test_variant.h
> +	Object o3 = Object();
Same for these

2025-10-11 05:19 UTC, robert-wallis commented on tests/core/variant/test_variant.h
> +	CHECK(o_str_enc == expected_str_enc);
At first I was confused, because memnew/memdelete aren't used in this test file, but looking at other test files I see it is used.

2025-10-16 01:29 UTC, Calinou commented
> It doesn't make sense for me to do this to Array, because arrays are nicely 1 line, but let me know if you want me to do the same treatment to Array

Arrays (and Packed*Array) could be wrapped to get to a certain element count per line, e.g. 16 items per line. This would avoid extremely long, non-diff-friendly lines which can cause certain editors to turn off some of their functionality when opening the file. (Many editors have a limit of 4,095 columns on the file's longest line before they disable some features.)

2025-10-16 12:26 UTC, Gnumaru commented
> Arrays (and Packed*Array) could be wrapped to get to a certain element count per line, e.g. 16 items per line.

16 is a reasonable ammount of items, but maybe 12 would be nicer. with 12 items per line, you can fit exactly one Transform3D worth of floats per line (or 3 Vector4/Color, or 4 Vector3, or 6 Vector2)

2025-10-26 09:06 UTC, AThousandShips requested changes

2025-10-26 09:06 UTC, AThousandShips commented on core/variant/variant_parser.cpp
> +				const PropertyInfo &E = props.get(i);
This should not use random access, as it is a list, instead it needs to use the list iterator or element iteration, like:
```suggestion
			int i = 0;
			for (List<PropertyInfo>::Iterator itr = props.begin(); itr != props.end(); ++itr, i++) {
				const PropertyInfo &E = *itr;
```
Alternatively 
```suggestion
			for (List<PropertyInfo>::Element itr = props.front(); itr; itr = itr->next()) {
				const PropertyInfo &E = itr->get();
```
And replace `i + 1 < props.size()` with `itr->next()`

Also `auto` is not allowed

2025-10-29 06:08 UTC, robert-wallis commented on core/variant/variant_parser.cpp
> +				const PropertyInfo &E = props.get(i);
makes sense about the list iterators, will do that

unfortunately `E->next()` doesn't seem accessible https://github.com/godotengine/godot/blob/2cb2c1fb5bbeb2afbac7255841f9c66d9611bf55/core/templates/list.h#L168-L195

any other ideas on how to get it? or should I just keep using `i + 1 < props.size()`

2025-10-29 06:18 UTC, robert-wallis commented on core/variant/variant_parser.cpp
> +				const PropertyInfo &E = props.get(i);
```cpp
			int i = 0;
			for (List<PropertyInfo>::Element *E = props.front(); E->next(); E = E->next(), i++) {
				const PropertyInfo &prop = E->get();
				if (prop.usage & PROPERTY_USAGE_STORAGE || prop.usage & PROPERTY_USAGE_SCRIPT_VARIABLE) {
					//must be serialized
					p_store_string_func(p_store_string_ud, property_key_prefix + prop.name + property_key_suffix + property_value_prefix);

					write(obj->get(prop.name), p_store_string_func, p_store_string_ud, p_encode_res_func, p_encode_res_ud, p_pretty_print, p_recursion_count, p_compat);

					if (E->next()) {
						p_store_string_func(p_store_string_ud, property_value_suffix);
					} else {
						p_store_string_func(p_store_string_ud, property_value_suffix_last);
					}
				}
			}
```
I guess I could manually iterate, but this seems messy, what do you think?

2025-10-29 08:23 UTC, AThousandShips commented on core/variant/variant_parser.cpp
> +				const PropertyInfo &E = props.get(i);
You don't need `i` in that version right?

2025-10-29 08:25 UTC, AThousandShips commented on core/variant/variant_parser.cpp
> +			for (List<PropertyInfo>::Element *E = props.front(); E->next(); E = E->next()) {
```suggestion
			for (List<PropertyInfo>::Element *E = props.front(); E; E = E->next()) {
```
Or you'll skip the last element, I don't think that was intended, it was `i < size` before

2025-10-29 14:41 UTC, robert-wallis commented on core/variant/variant_parser.cpp
> +			for (List<PropertyInfo>::Element *E = props.front(); E->next(); E = E->next()) {
:man_facepalming:

2025-10-29 14:45 UTC, AThousandShips commented on core/variant/variant_parser.cpp
> +			for (List<PropertyInfo>::Element *E = props.front(); E->next(); E = E->next()) {
Iteration conditions are the worst and produce the weirdest errors!

2025-10-29 14:46 UTC, AThousandShips approved these changes
Looks good now!

2025-11-12 18:44 UTC, aaronfranke commented
In the 2025-11-12 core team meeting, it was discussed that this PR is desired, but there were 2 important notes:
- We want to have even more tests. Specifically, we should have some tests for this in `test_config_file.h`. The people in the meeting expressed that these kinds of changes are really noisy, and we ideally want to only do these changes right the first time so we only cause diffs in user projects once, so we need to make sure the tests exist to demonstrate that the behavior is exactly as desired.
- We want to merge this early in a release cycle so it gets lots of testing, and it was deemed that it is already too late to make it in for 4.6, because feature freeze is in 3 weeks. Therefore, the plan is to get this PR into tip top shape before then, with many approving reviews, and then very soon after 4.6 releases we can merge this into master for 4.7.

2025-11-19 00:04 UTC, robert-wallis commented
I added a few more checks to the test cases.  Any additional test ideas would be helpful.  Also added a struct when I was trying to figure out doing the `Array` newlines.  Is pretty-printing arrays still a thing we want with this PR?

2025-11-24 16:53 UTC, robert-wallis commented
At the core meeting last Wednesday we discussed:
- [ ] add newlines for every array element, instead of grouping by 16 or 12 because if you change one at the beginning the git diff will be recalculated for the whole array.
- [ ] don't break PackedByteArray

I'm moving about 500 miles in the next few weeks, so I'll be back mid December to continue work on this.

2026-01-26 11:58 UTC, Ivorforce reviewed
Looks simple enough. Both the changes to the pretty as well as the non-pretty case makes sense to me. Code is straight-forward and clean.

Before we can consider merging this, we need one or two people to run the new algorithm on large projects and review the diffs.

2026-01-26 11:58 UTC, Ivorforce commented on tests/core/variant/test_variant.cpp
> +}
Some unit tests we definitely need for the pretty case:

- Dictionaries of arrays.
- Arrays of dictionaries.
- Empty array.
- Empty dictionary.
- Single-element array & dictionary
- Transform2D, Vector3 (representative of variants, should probably stay on the same line?)
- PackedByteArray (unless this has a test already? Somebody said it's a base64 string?)
- PackedInt32Array

2026-01-26 15:14 UTC, KoBeWi commented
> Before we can consider merging this, we need one or two people to run the new algorithm on large projects and review the diffs.

I did that. Changes I noticed:
- Every .import file gets `metadata` saved as one line
<img width="1110" height="114" alt="image" src="https://github.com/user-attachments/assets/033bcbd6-daca-4734-b589-540d81c6364d" />
- Dictionaries inside scenes (mostly from Aniamtion) have trailing comma added
<img width="1313" height="49" alt="image" src="https://github.com/user-attachments/assets/b552e267-6192-46e7-bb9a-486982cfdf0d" />
- Dictionary indentation changes
<img width="1212" height="202" alt="image" src="https://github.com/user-attachments/assets/d9bc1221-b562-4b50-830a-4808630fd934" />

2026-02-04 22:43 UTC, robert-wallis commented
> > Before we can consider merging this, we need one or two people to run the new algorithm on large projects and review the diffs.
> 
> I did that. Changes I noticed:
> 
> * Every .import file gets `metadata` saved as one line
> 
> <img alt="image" width="1110" height="114" src="https://private-user-images.githubusercontent.com/2223172/540560351-033bcbd6-daca-4734-b589-540d81c6364d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzAyNDQ5MzcsIm5iZiI6MTc3MDI0NDYzNywicGF0aCI6Ii8yMjIzMTcyLzU0MDU2MDM1MS0wMzNiY2JkNi1kYWNhLTQ3MzQtYjU4OS01NDBkODFjNjM2NGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAyMDRUMjIzNzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBiMzRjN2IxYWZhZDliZmZhOTc0YzQ0ZGExOGNhNjQwODc1NDFiMjc2MjAxMDA2MDI0MjU3MmE3Mzg1MjY5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3-lY6_QpXm6Xz_oJuTJ92kukxk6g2jr32_tVJDcrKlw">

Metadata is somehow being non-pretty printed.

I can't seem to figure out where metadata is serialized, we only set `p_pretty_print = false` in 2 places:
* `VariantUtilityFunctions::var_to_str`
* `Variant::get_construct_string()`

So somehow it's using that version instead of the normal property printer, I'm assuming it's a Dictionary type.  Looking in `resource_format_text.cpp` I don't see an exception for "metadata".  If anyone knows where is't being serialized I can fix its call to use the pretty version.

2026-02-04 22:48 UTC, robert-wallis commented
> Metadata is somehow being non-pretty printed.
> 
> I can't seem to figure out where metadata is serialized, we only set `p_pretty_print = false` in 2 places:
> 
> * `VariantUtilityFunctions::var_to_str`
> * `Variant::get_construct_string()`
> 
> So somehow it's using that version instead of the normal property printer, I'm assuming it's a Dictionary type. Looking in `resource_format_text.cpp` I don't see an exception for "metadata". If anyone knows where is't being serialized I can fix its call to use the pretty version.

nevermind found it, editor_file_system.cpp is using get_construct_string

2026-02-04 23:17 UTC, robert-wallis commented
<img width="903" height="277" alt="Screenshot 2026-02-04 at 3 09 16 PM" src="https://github.com/user-attachments/assets/61fea275-7e8e-4331-b789-963aba2d3533" />

Now the `metadata=` dictionary and the `generic_paramaters=` dictionary are also serialized pretty.  And I tested backwards compatibility with 4.5 stable.

2026-02-05 01:54 UTC, Calinou reviewed
Tested locally on all 2D and 3D demos from https://github.com/godotengine/godot-demo-projects (with **Project > Tools > Upgrade Project Files**), it works as expected.

I ran each project and looked through the diffs and didn't see anything out of the ordinary. I was also able to open every project in 4.5.1.stable afterwards.

Nested arrays look a lot nicer now. Example from `2d/bullet_shower/shower.tscn`:

<img width="712" height="295" alt="image" src="https://github.com/user-attachments/assets/4216a248-c73f-4c13-87c1-9472bc6d0349" />

I noticed that nested dictionaries don't have trailing commas, unlike top-level dictionaries. You can see this in the above screenshot. (This issue doesn't seem to occur with objects nested within a dictionary or another object.)

2026-02-05 14:57 UTC, Ivorforce commented
@robert-wallis What's the status of the PR? It looks like you added some more unit tests, thank you! Do you feel confident that everything is covered now (and agree with the formatting)?

@Calinou @KoBeWi Thanks for testing!!
@KoBeWi If I'm interpreting correctly, @robert-wallis fixed the concerns. Could you test again?

2026-02-05 16:04 UTC, KoBeWi commented
They weren't really concerns, I just noted the new behavior.
The only thing that changed is that .import files now format Dictionaries like Animation does
<img width="1040" height="99" alt="image" src="https://github.com/user-attachments/assets/b19b063a-2e81-4d69-9aa0-e8fc45b5ae8c" />
so it's more consistent now.

2026-02-05 21:47 UTC, robert-wallis commented
@Ivorforce I think it's ready.  Honestly great work everyone keeping the code base so clean, over the last 2 years I've been rebasing this PR and I don't recall ever having a conflict.



The only final concern is what @Calinou noticed, that all `Array`s are not pretty printed by design.  The "frames" component of animations is an `Array`.  `Array`s aren't implemented with trailing commas.

We had discussed in one of the core meetings perhaps splitting arrays with a newline every 16 floats, however we decided it wasn't a good idea because if you insert an element in the front of the array, then the diff of the whole array will be different.

We could scan the contents of the array before printing it to see if it contains any complex data types, if it does then pretty print it.  But if it only contains simple data types like numbers or strings, then keep them inline.  I'd even argue that strings should be pretty printed, because I think it would be good to have a list of strings like filenames or dialog lines on newlines to have better git diff experience.

So the question is, do we want all `Array`s to have newlines?  Including just a simple array of floats?  Technically that would be the most consistent.  But it will add verticality.  And adding newlines to `Array` won't affect named array types like `PackedByteArray`, `PackedFloat32Array` or `Vector3` because they are not `Array`, so it would only look like a "waste of vertical space" if someone were using a basic `Array` type to hold floats.

2026-02-06 02:56 UTC, aaronfranke approved these changes
Looks great to me! I look forward to this getting wider testing after merging, early in the release cycle.

2026-02-10 00:19 UTC, Ivorforce commented
I tested the PR on a larger project (Rift Riff) on a dozen or so files.

In terms of formatting, it looks good. Most of the tscn files are pretty regular anyway, so there's not much room for error. Dual closing braces being indented with the former instead of the latter brace kind of weirds me out, but thinking about it, it might be more consistent than indenting it with the latter brace (which would be harder to achieve). So I think it's ok.

One observation is that a majority of changes are whitespace only. I've only found a handful of cases where a single-line object was split to be a multi-line object (which _is_ a lot nicer than before).
However, almost every single `.tscn` files has some a block of change where properties are the same as before, just indented.
While this does make sense, I'm worried that people will see this and blame us for breaking all outstanding PRs / branches in their projects for no discernible reason. If the single-line to multi-line objects would be more prevalent, i don't think it would be as bad, but since almost everything is just indentation changes, I think if we merge this we can brace for a collective outcry from Godot users.

I think it's worth rethinking the way in which we introduce this change. Perhaps it's possible to only introduce breaking without indentation changes for the moment? Sure, it would be a lot less nice, but it would avoid most of the problem.

Another option could be only adding indentation with a project setting, disabled for existing projects and enabled for new projects. This would allow users to opt-in to this part of the change, and us to slowly transition away from unindented tscn files.

2026-02-10 00:28 UTC, Calinou commented
> Another option could be only adding indentation with a project setting, disabled for existing projects and enabled for new projects. This would allow users to opt-in to this part of the change, and us to slowly transition away from unindented tscn files.

I like this approach personally. It reduces diff size in existing projects, but still allows new projects to get increased readability.

2026-02-10 01:19 UTC, KoBeWi commented
From my experience every minor version of Godot brings some changes that result it many scene/resource diffs. In 4.6 it was unique node IDs - they caused every single scene in the project to be modified. This is why we have the upgrade tool, to handle everything at once. If someone doesn't like such changes then don't upgrade the project 🤷‍♂️

> While this does make sense, I'm worried that people will see this and blame us for breaking all outstanding PRs / branches in their projects for no discernible reason.

It does not really break anything. The changes don't happen until you re-save the scenes, so for the least friction upgrade one should first merge anything they don't want to conflict with and only upgrade after that.

2026-02-10 08:22 UTC, Ivorforce commented
> If someone doesn't like such changes then don't upgrade the project 🤷‍♂️

I think this is too much of a hands-off approach to updateability. Overall we've been doing a good job, but some users are still upset about UIDs. Why risk it if we can avoid it?

Do you have anything against the Project setting based approach?

2026-02-10 08:38 UTC, dalexeev commented
> Do you have anything against the Project setting based approach?

Project settings create differences between projects; TSCN/TRES is no longer a unified format (within a given Godot version), but rather dependent on the project configuration. This can also create problems for third-party addons if they are created or saved with different settings. Godot may modify third-party files if you accidentally save a scene/resource or use the "Upgrade Project Files..." option in the tools menu.

2026-02-10 08:44 UTC, Ivorforce commented
> Godot may modify third-party files if you accidentally save a scene/resource or use the "Upgrade Project Files..." option in the tools menu.

This will happen anyway if we go through with the whitespace changes.

> Project settings create differences between projects; TSCN/TRES is no longer a unified format (within a given Godot version), but rather dependent on the project configuration. 

While technically true, i don't think it's a huge problem for two reasons:

- the versions are interchangeable, since it's just a formatting difference.
- we'd be instantly marking non-formatted versions as deprecated, so there is one canon version of the file that we expect to be adopted sooner or later (at devs behest).

If you are using third party add-ons, the initial commit will add them to the repo in the initial read state. So there too we either have a change to the source, or we don't, independent of whether it's controlled by project setting.

2026-02-10 10:05 UTC, dalexeev commented
I'm thinking of a situation where your project uses Option A and a third-party addon uses Option B. Typically, you should avoid changes to the third-party code or keep them minimal, to facilitate merging upstream changes. The project setting makes this difficult, or at least inconvenient. Since other editor systems aren't aware of the existence of special rules for certain directories/files. If you accidentally save a third-party scene/resource or run a tool to automatically update all resources in the project, you'll then have to revert the unwanted changes to the third-party files. It's good if you notice this right away. But if you or your colleagues are inattentive or uninformed about potential problems, these changes may be committed, and problems will surface later when you try to sync with upstream.

Alternatively, this shouldn't be a single setting for all files in the project, but a configurable value on a per-directory basis, like `debug/gdscript/warnings/directory_rules`. However, this approach is probably overly complex in this case.

Yes, I agree that merge conflicts can occur even with a unified format (for example, if different UIDs are generated for the same resources in your project and in the upstream). But the difference is that with a unified format, these conflicts will be resolved over time, since addon authors will be forced to use the single format when updating the engine version. Whereas with multiple options to choose from, you and the addon authors may choose different options and remain in different "camps" for quite some time.

2026-02-10 13:34 UTC, Ivorforce commented
> I'm thinking of a situation where your project uses Option A and a third-party addon uses Option B. Typically, you should avoid changes to the third-party code or keep them minimal, to facilitate merging upstream changes. The project setting makes this difficult, or at least inconvenient. Since other editor systems aren't aware of the existence of special rules for certain directories/files. If you accidentally save a third-party scene/resource or run a tool to automatically update all resources in the project, you'll then have to revert the unwanted changes to the third-party files. It's good if you notice this right away. But if you or your colleagues are inattentive or uninformed about potential problems, these changes may be committed, and problems will surface later when you try to sync with upstream.

I think we have this problem with or without the project setting. Libraries especially are rarely updated, to keep them backwards compatible. So if we merge the whitespace changes, we'll have this problem for a while.
On the other hand, if we have the setting, developers could reasonably keep it switched off at least at first, to avoid unnecessary conflicts with existing libraries.

> Alternatively, this shouldn't be a single setting for all files in the project, but a configurable value on a per-directory basis, like `debug/gdscript/warnings/directory_rules`. However, this approach is probably overly complex in this case.

This could be nice, but I also think it might be overkill.

> Yes, I agree that merge conflicts can occur even with a unified format (for example, if different UIDs are generated for the same resources in your project and in the upstream). But the difference is that with a unified format, these conflicts will be resolved over time, since addon authors will be forced to use the single format when updating the engine version. Whereas with multiple options to choose from, you and the addon authors may choose different options and remain in different "camps" for quite some time.

Addon authors aren't forced to update with the engine version. We intentionally keep the engine backwards compatible so as few people as possible need to update. There will be two "camps" for a long time either way.

Also, I'd like to reiterate that we wouldn't support "choosing" different options. You either keep the old option out of convenience, or update to the new default. Keeping the old option is deprecated and will be met with a warning.

2026-02-10 13:42 UTC, Ivorforce commented
Actually, there might be a secret third option: We could auto-detect the indentation style of the file, and adopt it when overwriting it (defaulting to single tab).

I'm not sure how we'd best implement a scene file updater for people who want to opt-in, but this solution should keep as much intact as possible while facilitating a slow migration.

2026-02-10 14:37 UTC, dalexeev commented
> I think we have this problem with or without the project setting.

I don't think the argument "we have this problem anyway in some cases, so we can expand its scope" is valid. Each potentially problematic change and the measures to mitigate it must be assessed on their own merits, to determine whether the benefits outweigh the drawbacks or vice versa.

As far as I know, the project setting option is unprecedented, so the option should be evaluated with particular caution. The situation is similar with the proposed options to disable UIDs and replace UID files with UID comments where possible (scripts, shaders). You may be right that this is a less significant change than (non-)generating `.uid` files, since it only affects whitespace formatting. But in my opinion, we should still be cautious about the unintended consequences of excessive configurability.

We could just refrain from introducing the whitespace changes, given that these changes could pose a significant inconvenience to users. I just see a certain contradiction in stating that these whitespace changes are simultaneously major (to introduce a project setting for mitigation) and minor (to worry about incompatibility between projects and third-party addons).

> Also, I'd like to reiterate that we wouldn't support "choosing" different options. You either keep the old option out of convenience, or update to the new default. Keeping the old option is deprecated and will be met with a warning.

In my opinion, this may be acceptable under the following conditions: 1. For new projects, the compatibility setting should be disabled by default. 2. The documentation clearly indicates that the previous behavior is deprecated and you should sooner or later disable the compatibility setting to resolve potential merge conflicts with stale PRs, third-party addons, etc. But I still think that a temporary project setting is not a good idea for the primarily machine-editable TRES/TSCN formats (even though they are designed to be human-readable).

2026-02-10 15:12 UTC, Ivorforce commented
I see the addition of a project settings as a mitigation of the issue, you appear to see it as more of an exacerbation. I think both perspectives are valid.

I think we've both stated our case. I won't die on this hill if you think a project setting should be avoided.

How do you feel about my [suggestion above](https://github.com/godotengine/godot/pull/92102#issuecomment-3877697466) to use the existing indentation in each file?

Either way I think the best path forward is to introduce the object wrapping without changing indentation, and potentially make indentation changes as a follow-up. Object wrapping is in line with the existing array and dict wrapping, and appears to only affect a small portion of `.tscn` files.

2026-02-11 18:59 UTC, robert-wallis commented
After core meeting today, to keep in line with the original proposal and avoid adding a big change that isn't backed by a big win, I removed tabs altogether.

Now this just adds newlines and trailing commas on the last value.

> [!NOTE]
> The trailing comma will update every image .`.import` file with a single comma added to the meta section.

<img width="248" height="311" alt="Screenshot 2026-02-11 at 10 54 47 AM" src="https://github.com/user-attachments/assets/fac2b6c0-b5b7-4178-a2c9-4960ea558c06" />
<img width="609" height="951" alt="Screenshot 2026-02-11 at 10 55 22 AM" src="https://github.com/user-attachments/assets/5499cc3e-a46d-4dc4-ba7b-c5ec336c070a" />

2026-02-11 20:42 UTC, Ivorforce commented
Thanks for updating!

The current version still inserts a lot of noise into a project, e.g.:

```
}, {
 "duration": 1.0,
-"texture": SubResource("AtlasTexture_wfb6i")
+"texture": SubResource("AtlasTexture_wfb6i"),
 }, {
 "duration": 1.0,
-"texture": SubResource("AtlasTexture_my210")
+"texture": SubResource("AtlasTexture_my210"),
 }, {
```
(from a `.tscn` file)

I'm not sure if those are dictionaries, or objects, but either way the trailing commas cannot be added in this way as it creates the kind of problem we've been trying to avoid.

2026-02-11 20:46 UTC, aaronfranke commented
@Ivorforce I completely disagree, to me that is the desired behavior. In the short term, sure it's more noise, but that's inevitable with a PR like this. In the long term, we want to include trailing commas to avoid version control noise when a new line is added to the end of a Dictionary.

2026-02-11 20:48 UTC, Ivorforce commented
@aaronfranke We've discussed this in the core meeting today and decided to go ahead with only the Object newline changes.
The reason is that this solves a very specific problem (large objects are very hard to merge), while avoiding a huge amount of git diff noise that might annoy users. Trailing commas would be nice, but would create the kind of noise we want to avoid, while being of (comparably) little benefit.

2026-02-11 20:53 UTC, Gnumaru commented
Could trailling comas as well as tabs come back in future godot versions, even if in a major version like 5.0?

2026-02-11 20:56 UTC, Ivorforce commented
> Could trailling comas as well as tabs come back in future godot versions, even if in a major version like 5.0?

No, the consensus was that this should only happen if we switch file formats altogether.

2026-02-11 22:38 UTC, robert-wallis commented
Sorry I am sick, not thinking clearly, I also removed the trailing comma.

Now image `.import` files have no change.  Only Objects and Dicts have newlines, and no comma is added on the last element of anything.
<img width="284" height="119" alt="image" src="https://github.com/user-attachments/assets/3a78d512-b690-42e6-ac2b-a81c06bb6002" />

2026-02-11 23:57 UTC, Ivorforce commented
Now that we've reduced the scope of the PR down so much, are the majority of the change in the PR still required?

I hate to ask this after most of this work came from initial feedback... And it's nice to be able to abstract it so far, but less changes is better if we do end up merging just the newlines (and spaces after colons).

(it might be worth backing the changes to a new branch, just in case we _do_ end up wanting to add the tabs / trailing commas after all)

2026-02-14 02:42 UTC, robert-wallis commented
> Now that we've reduced the scope of the PR down so much, are the majority of the change in the PR still required?

Yeah I felt the same way, the class I added made more sense when we had tab changes that made it complex with 5 different change points, but now that it's just newlines, I think 3 separate strings make sense.  So removing that class made things a bit less complex.

The tests are a bit verbose, but they test more now.  So it seemed fine to keep most of the tests.

What do you think?

This seems good to me now.

2026-02-21 20:46 UTC, Ivorforce commented
Alright, i did something I should have done a while ago: I asked some professional Godot devs if this change would actually be a problem for them.

Most developers agreed this would be a nice change, but I did receive feedback that we were a bit over eager with previous `.tscn` file changes, and some teams are still suffering from e.g. the `UID` changes in 4.6.
For example, one workload that this would create a problem for is a team which updated the Godot version for the PC distributable, but must keep it on an earlier version for a specific console because of porting details. Needing to sync the two versions is made difficult with `.tscn` format changes.

Developers brought up both of the ideas I also brought up (the project setting idea that was rejected above, as well as the idea where we only use the indentation for new files by reading back the old file before saving).

To mitigate risks from this PR, I wrote a proposal to communicate formatting changes on project upgrade: https://github.com/godotengine/godot-proposals/issues/14272
I think we should implement that feature (in a separate PR) if we want to merge this one, because the previous lack of communication and support around formatting changes exacerbates potential issues.

I'd also appreciate some opinions about the idea I raised above (re-using the file's current indentation, indenting by default). I think this might be achievable and should avoid issues on all fronts.

@robert-wallis Thank you for being patient while this is turning out so tedious!

2026-07-15 16:04 UTC, Ivorforce commented
Hello again! 

Some time has passed, we're now in early in the Godot 4.8 cycle, and two things happened: 
- A file upgrade prompt has been added, to improve how well users can adopt this change: https://github.com/godotengine/godot-proposals/issues/14272
- The Godot 5 proposal seems to be converging / becoming consensus, which specifically encourages prioritizing improvements over forwards compat: https://github.com/godotengine/godot-proposals/issues/14963 

So I think it's finally time to merge this!

We've discussed the PR again in the core meeting, and consensus was to keep it at the 'minimal change' level (newlines for `Object` but no indentation). We'll revisit indentation for Godot 5 (when a larger cosmetic change is acceptable).

I'll review the code again and hopefully we can merge it soon.
@robert-wallis I hope you're still around and ready to react/rebase? :)

2026-07-15 16:08 UTC, robert-wallis commented
@Ivorforce great news! just let me know what commit to rebase with to fix that conflict

2026-07-15 16:11 UTC, Ivorforce commented
You should be able to fix it by rebasing to `master`:

```shell
git fetch origin master
git rebase origin/master
```

(assuming `godotengine/godot` is your `origin` remote)

2026-07-15 17:23 UTC, Calinou approved these changes
Tested again on various demos including the TPS demo, it works as expected. Code and tests look good to me.

Note that it's still possible to load an upgraded project in 4.7.stable, nonwithstanding other changes that may be incompatible.

This change should be mentioned in the blog post and migration guide, due to the large VCS diffs it can result in.

2026-07-16 11:08 UTC, Mickeon approved these changes
I concur to this, but I would also like to remind that we should keep a close eye on community feedback specifically due to the extreme noise it's going to cause, especially in `project.godot` itself. Perhaps make note of it in a theoretical blog post and/or migration guide.

2026-07-16 13:12 UTC, Ivorforce requested changes

2026-07-16 13:12 UTC, Ivorforce commented on modules/gdscript/tests/scripts/analyzer/features/const_array_and_dictionary_constructors.out
> +true {{}: {}}
What's the reasoning for this change? I suppose it's more "correct" to omit the spaces, but it's not part of the same logical change.

2026-07-16 13:12 UTC, Ivorforce commented on core/variant/variant_parser.cpp
> +			const String value_suffix = p_pretty_print ? ",\n" : ", ";
This change seems to add a space to the non-pretty print path where there wasn't one before. I might be wrong, but worth a check.

2026-07-17 07:30 UTC, robert-wallis commented on modules/gdscript/tests/scripts/analyzer/features/const_array_and_dictionary_constructors.out
> +true {{}: {}}
good catch, yes this is leftover from when Dictionary was also being pretty-printed
so I removed all the dictionary stuff and just kept this focused on Object pretty printing 
in fa0f545

2026-07-17 07:33 UTC, robert-wallis commented on core/variant/variant_parser.cpp
> +			const String value_suffix = p_pretty_print ? ",\n" : ", ";
you're right, I also added tests to validate the expected behavior

2026-07-17 07:41 UTC, robert-wallis commented
I added a new test to show the specific Input example that lead me to make the PR in the first place: https://github.com/godotengine/godot/pull/92102/changes/fa0f5454aa1c23ee8e93977e2273ca13a2f3b4d1#diff-4955c6aba52421c6eadaa5b4afa2c84ff2f638ea6a06565fc11b6479def48e2aR177

Also to note, since non-pretty means "old way" not "single line" there is a weird corner case that I made a test for, a Dictionary with an object inside it, has two newlines back to back when non-pretty, one from Dictionary and one from Object:
```
	String o_str;
	VariantWriter::write_to_string(d, o_str, true);
	CHECK_EQ(o_str, "{\n1: Object(Object,\n\"script\": null\n)\n}");

	VariantWriter::write_to_string(d, o_str, false);
	// non-pretty printed Object has \n and Dictionary also has \n for a double \n\n
	CHECK_EQ(o_str, "{\n1: Object(Object,\"script\":null)\n\n}");
```
https://github.com/godotengine/godot/pull/92102/changes/fa0f5454aa1c23ee8e93977e2273ca13a2f3b4d1#diff-55351c6d9845e05dcb62803ef439301d56ee0a4a6aad641b985d4dcb46043062R2123-R2126

2026-07-17 08:53 UTC, Ivorforce commented on core/variant/variant_parser.cpp
> -			bool first = true;
The `first` design was better here. Your `E->next()` check is arguably cleaner but fails in the case where the final property is not stored. In that case, your loop inadvertently stores a trailing comma.

2026-07-20 06:14 UTC, robert-wallis commented on core/variant/variant_parser.cpp
> -			bool first = true;
I completely missed that it's possible for properties to not be stored.
Fixed in d3a753d but I haven't figured out how to write a test easily with an un-stored property yet.

2026-07-20 08:58 UTC, Ivorforce approved these changes
Looks good.

Thanks for all the hard work!

2026-07-20 09:00 UTC, Ivorforce commented on core/variant/variant_parser.cpp
> -			bool first = true;
Your coverage is already really good, and importantly much better than before. I think not testing this one explicitly is excusable :)

2026-07-20 16:05 UTC, merged

2026-07-20 16:05 UTC, Repiteo commented
Thanks!