Add Ctrl + R keyboard shortcut to restart particle emission in the editor
godotengine/godot pull request #92134
Opened 2024-05-19 22:06 UTC by Calinou

Restarting particule animation frequently is often done in the VFX tweaking process.

This shortcut is available for both GPUParticles and CPUParticles, in 2D and 3D.

- See https://github.com/godotengine/godot/pull/92089 (which inspired me to add this shortcut).

2024-05-20 23:23 UTC, QbieShay commented
Is ctrl+space available? I'd like to have a shortcut to pause particles as well. So play/pause, restart, and frameskip too (, and . probably for frameskip)
would those work?

2024-05-21 14:44 UTC, Calinou commented
> I'd like to have a shortcut to pause particles as well. So play/pause, restart, and frameskip too (, and . probably for frameskip)

Particle pausing can be implemented by toggling speed scale between its previous value and 0.0, but the issue is that this value change would be saved to the scene file. We'd need a separate, method for temporarily pausing particles.

2024-05-21 19:21 UTC, KoBeWi requested changes
You should define the shortcut once and use ED_GET_SHORTCUT.

2024-05-21 20:07 UTC, Calinou commented
> You should define the shortcut once and use ED_GET_SHORTCUT.

I tried to do that in EditorNode's cosntructor, but I got "unknown shortcut" errors when I select a particles node.

2024-05-21 20:09 UTC, QbieShay commented
@Calinou yep! for now pause doesn't make sense, but i mentioned it in case we can reserve it ^^

2024-05-21 21:00 UTC, KoBeWi commented
> I tried to do that in EditorNode's constructor, but I got "unknown shortcut" errors when I select a particles node.

It should work if you define them right after EditorSettings are created.
https://github.com/godotengine/godot/blob/aaa4560729bf0161deb71789b47eba5623893845/editor/editor_node.cpp#L6295-L6298

2024-05-21 22:36 UTC, KoBeWi approved these changes
Will conflict with #92223

2024-05-22 07:30 UTC, akien-mga commented
Needs rebase after #92223.

2024-05-22 13:34 UTC, QbieShay approved these changes

2024-05-23 07:01 UTC, merged

2024-05-23 07:02 UTC, akien-mga commented
Thanks!