Allow double-click within tracks to set a new play position
godotengine/godot pull request #92141
Opened 2024-05-20 02:56 UTC by SatLess

This feature allows the user to move the Animation Play Position by double clicking, being more intuitive and improving workflow by keeping the mouse on the tracks, as opposed to going at the top only to change its current position.

![Showcase](https://github.com/godotengine/godot/assets/124409014/2507fb67-4acf-4705-ade9-d75779e42448)

2024-05-20 07:34 UTC, akien-mga commented
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

2024-05-21 05:14 UTC, AdriaandeJongh commented
Considering snapping the play position to frames is also applied everywhere else where you move the play position, wouldn't it make sense if this feature also snapped?

2024-05-21 05:48 UTC, SatLess commented
>  wouldn't it make sense if this feature also snapped?

Snapping works just the same with it. I assume the signal `timeline_changed` handles the snapping (if enabled). Here's an example

![Snapping](https://github.com/godotengine/godot/assets/124409014/1cebff60-98ad-4edf-9911-7f676758fb02)

2025-01-17 17:39 UTC, SatLess commented
I know this might be late, however since it's a small quality of life feature, could this be pushed to Godot 4.4? I assume it does not conflict with other systems.

2025-01-17 17:48 UTC, fire commented
I aspire to get this reviewed and in for 4.5.

2025-05-17 22:07 UTC, TokageItLab reviewed
It makes sense as an operation and is a good idea.

However, since the selection cancellation action is similar to a double-click, so it would be necessary to make sure that there is no selection (means this should be into the `if (selected || editor->is_selection_active())` block)

2025-05-17 23:37 UTC, SatLess commented
@TokageItLab if we use ` !editor->is_selection_active()` that means we can't double click on a selected keyframe that is stationary. So I opted to insert the block of code into `if (!moving_selection)`. I'd also like to ask how probable it is currently for a double click to be misinterpreted as a selection cancellation by the animation player.

2025-05-18 00:38 UTC, TokageItLab commented
It may be solved by adding an additional determination if the click is on a key or not. The non-selected decision is needed when clicking on an empty area.

2025-05-18 02:00 UTC, SatLess commented
I think that tracking if a keyframe was clicked to allow double clicking kinda limits the functionality (e.g if you want to go on an empty space on the track). Additionally I tested this example and double clicking was not an issue — It did not replace selection with a double click.

![hipothetical example](https://github.com/user-attachments/assets/8675ebef-a204-416b-a8b2-b710dec68c05)

![hipothetical examplea](https://github.com/user-attachments/assets/1740ae00-9c87-4496-b4d3-55a2a4fa8213)

Is there a case where the selection consistently gets overridden by a double-click? Or a case where it double clicks and selects at the same time? I'm sorry if I'm a little slow at understanding the issue, but it's as though I'm attempting to fix something that might not be broken.

2025-05-18 03:08 UTC, TokageItLab requested changes
Oh, I was looking at 4.3 and it seems that 4.3 and 4.4 already have different behavior. I don't know where this occurred, but in 4.4 the cancel action and the selection are done at the same time.

Well, considering that fewer clicks may be preferred, it appears that right-click cancellations, etc. are not a problem at this time.

However, I found one problematic behavior: multiple selections with Shift may be made by double-clicking to deselect, so you should need to check that no mod keys (Shift/Alt/Ctrl) are pressed.

Also, I think the same changes need to be made to BezierEditor for consistency. The change requests are two of them.

2025-05-18 19:06 UTC, SatLess commented
- Double clicking now works both on the Track Editor as well as the Bezier Editor
![double_click](https://github.com/user-attachments/assets/603c052d-8d16-4945-9508-b11871eba183)

- If one of the mod keys (Shift/Alt/Ctrl) are pressed, double click will not allowed.

2025-05-19 00:35 UTC, TokageItLab approved these changes

2025-05-19 13:04 UTC, merged

2025-05-19 13:04 UTC, Repiteo commented
Thanks!