Improve layered texture preview
godotengine/godot pull request #92540
Opened 2024-05-30 12:03 UTC by BlueCube3310

Improves the layered texture previewer by making the display similar to the one used by non-layered images.

| Original | PR |
|---------|----|
|![l_orig](https://github.com/godotengine/godot/assets/53150244/7e2c5e00-d66e-4f62-8a51-6d7cbc27d474)|![l_better](https://github.com/godotengine/godot/assets/53150244/67ab59c2-26e2-4a4e-8648-28e7869d17a9)|

TODO:
- [ ] Move the layer selection SpinBox so it doesn't overlap the image,
- [ ] Ensure the displayed mipmap count and memory size are accurate (Currently it's assuming that the whole mip chain is used).

2024-06-13 13:23 UTC, Calinou commented on editor/plugins/texture_layered_editor_plugin.cpp
> +				info->set_text(vformat(String::utf8("%d×%d (x%d) %s\n") + TTR("%s Mipmaps") + "\n" + TTR("Memory: %s"),
```suggestion
				info->set_text(vformat(String::utf8("%d×%d (×%d) %s\n") + TTR("%s Mipmaps") + "\n" + TTR("Memory: %s"),
```
```suggestion
				info->set_text(vformat(String::utf8("%d×%d (×%d) %s\n") + TTR("%s Mipmaps") + "\n" + TTR("Memory: %s"),
```

2024-06-13 13:23 UTC, Calinou commented on editor/plugins/texture_layered_editor_plugin.cpp
> +				info->set_text(vformat(String::utf8("%d×%d (x%d) %s\n") + TTR("%s Mipmaps") + "\n" + TTR("Memory: %s"),
```suggestion
				info->set_text(vformat(String::utf8("%d×%d (×%d) %s\n") + TTR("%s Mipmaps") + "\n" + TTR("Memory: %s"),
```
```suggestion
				info->set_text(vformat(String::utf8("%d×%d (×%d) %s\n") + TTR("%s Mipmaps") + "\n" + TTR("Memory: %s"),
```

2024-06-13 13:24 UTC, Calinou commented on editor/plugins/texture_layered_editor_plugin.cpp
> +				info->set_text(vformat(String::utf8("%d×%d (x%d) %s\n") + TTR("No Mipmaps") + "\n" + TTR("Memory: %s"),
```suggestion
				info->set_text(vformat(String::utf8("%d×%d (×%d) %s\n") + TTR("No Mipmaps") + "\n" + TTR("Memory: %s"),
```

2024-06-13 13:25 UTC, Calinou commented on editor/plugins/texture_3d_editor_plugin.cpp
> +	info->add_theme_color_override("font_outline_color", Color::named("black"));
It's preferable to use `Color(1, 1, 1)` and `Color(0, 0, 0)` as it leads to slightly smaller binary sizes from my testing.

2024-06-13 13:25 UTC, Calinou commented on editor/plugins/texture_layered_editor_plugin.cpp
> +	info->add_theme_color_override("font_outline_color", Color::named("black"));
Same as above regarding the named colors comment.

2024-06-17 17:44 UTC, Calinou commented
> (Currently it's assuming that the whole mip chain is used).

This is almost always the case in practice (especially due to https://github.com/godotengine/godot/issues/63934), so I don't think this is a dealbreaker. Also, in the worst-case scenario (texture only has 1 mipmap but full mipmap chain is assumed), the size estimation is only off by ~8.3% for a 2D texture.

2024-06-17 17:47 UTC, Calinou requested changes
Tested locally, I noticed some issues:

- The size information label (and the maximum layer you're allowed to preview) is not updated when the texture size's changes. Example with NoiseTexture3D:

https://github.com/godotengine/godot/assets/180032/2efd9be0-9441-4ec0-aa7e-e230aeb8a0fd

It only updates when you collapse and expand the NoiseTexture3D in the inspector, although I managed to update the size label (but not the maximum selectable layer) somehow. I don't remember how I did this.

2024-06-18 11:24 UTC, BlueCube3310 commented
Should be fixed now. I've also moved the GUI updates to a separate function, so it only updates when the texture is changed.

2024-06-18 17:35 UTC, AThousandShips commented on editor/plugins/texture_editor_plugin.cpp
> +		metadata_label->add_theme_font_size_override("font_size", 14 * EDSCALE);
```suggestion
		metadata_label->add_theme_font_size_override(SceneStringName(font_size), 14 * EDSCALE);
```

2024-06-18 22:33 UTC, Calinou requested changes
Tested locally, it works as expected now. However, this error is printed when you open a NoiseTexture3D inspector (it's not printed in `master`):

```
ERROR: Required virtual method NoiseTexture3D::_has_mipmaps must be overridden before calling.
   at: _gdvirtual__has_mipmaps_call (./scene/resources/texture.h:135
```

2024-06-19 08:52 UTC, BlueCube3310 commented
Fixed, NoiseTexture3D didn't use to override the `has_mipmaps` virtual method.

2024-06-19 14:04 UTC, Calinou approved these changes
Works great now :slightly_smiling_face:

2024-07-12 14:14 UTC, AThousandShips commented on editor/plugins/texture_layered_editor_plugin.h
> +	void _update_material(bool texture_changed);
```suggestion
	void _update_material(bool p_texture_changed);
```

2024-07-12 14:14 UTC, AThousandShips commented on editor/plugins/texture_layered_editor_plugin.cpp
> +void TextureLayeredEditor::_update_material(bool texture_changed) {
```suggestion
void TextureLayeredEditor::_update_material(bool p_texture_changed) {
```

2024-07-12 14:14 UTC, AThousandShips commented on editor/plugins/texture_3d_editor_plugin.h
> +	void _update_material(bool texture_changed);
```suggestion
	void _update_material(bool p_texture_changed);
```

2024-07-12 14:14 UTC, AThousandShips commented on editor/plugins/texture_3d_editor_plugin.cpp
> +void Texture3DEditor::_update_material(bool texture_changed) {
```suggestion
void Texture3DEditor::_update_material(bool p_texture_changed) {
```

2024-08-26 21:34 UTC, merged

2024-08-26 21:35 UTC, akien-mga commented
Thanks!