Fix possible crash in joy_axis (fixes #4944).
godotengine/godot pull request #9290
Opened 2017-06-20 17:52 UTC by marcelofg55

Just adds a missing check to prevent a crash.

2017-06-20 18:23 UTC, 27thLiz requested changes

2017-06-20 18:23 UTC, Hinsbart commented on main/input_default.cpp
> +	if (p_axis < 0 || p_axis >= JOY_AXIS_MAX) {
I guess this should throw an error.
You can do it with `ERR_FAIL_INDEX(p_axis, JOY_AXIS_MAX)`

2017-06-21 00:27 UTC, marcelofg55 commented on main/input_default.cpp
> +	if (p_axis < 0 || p_axis >= JOY_AXIS_MAX) {
I've added it and commited the change, and I tried to squash the commits but I think it didn't work well :(

2017-06-21 06:17 UTC, Hinsbart commented on main/input_default.cpp
> +	if (p_axis < 0 || p_axis >= JOY_AXIS_MAX) {
Ah, you can remove  the `if (p_axis < 0 || p_axis >= JOY_AXIS_MAX) ` and the return statement, `ERR_FAIL_INDEX()` already does all of that for you :)

2017-06-21 13:18 UTC, closed without merging