Fix ReflectionProbe Cull Mask not working on Mobile rendering method
godotengine/godot pull request #93175
Opened 2024-06-14 20:23 UTC by Calinou

- This closes https://github.com/godotengine/godot/issues/93173.

## Preview

Before | After
-|-
![image](https://github.com/godotengine/godot/assets/180032/b1c66cd0-7acb-41a7-8c59-6c0e55338017) | ![image](https://github.com/godotengine/godot/assets/180032/530051eb-4181-462e-8d75-021b3dbd4ddf)

2024-06-25 14:44 UTC, clayjohn requested changes
ReflectionProbes should be masked before calling the shader. Since ReflectionProbes are linked against Meshes, we can just avoid linking them if the mask does not overlap. 

This way we can properly cull objects that don't fit in the mask without adding a run time cost in the shader

2024-06-25 15:43 UTC, Calinou commented
> ReflectionProbes should be masked before calling the shader. Since ReflectionProbes are linked against Meshes, we can just avoid linking them if the mask does not overlap.

Is this change also needed in Forward+?

2024-06-25 16:10 UTC, clayjohn commented
> > ReflectionProbes should be masked before calling the shader. Since ReflectionProbes are linked against Meshes, we can just avoid linking them if the mask does not overlap.
> 
> Is this change also needed in Forward+ and Compatibility?

It should be done in RendererSceneCull, so it would apply to Mobile and Compatibility, the Forward+ renderer has to do masking in the shader

2025-05-27 14:57 UTC, akien-mga commented
Superseded by #106411.

2025-05-27 14:57 UTC, closed without merging