Allow input mappings to be edited
godotengine/godot pull request #9347
Opened 2017-06-24 12:38 UTC by bojidar-bg

Closes #7312 

Proof gif (before double-click started to work):
![peek 2017-06-24 14-53](https://user-images.githubusercontent.com/5276727/27508669-ea879708-58f2-11e7-98c3-39f0b3b2e7da.gif)

2017-06-25 09:10 UTC, akien-mga requested changes

2017-06-25 09:10 UTC, akien-mga commented on editor/project_settings.cpp
> +	ClassDB::bind_method(D_METHOD("_add_item"), &ProjectSettings::_add_item, DEFVAL(NULL));
This fails with clang (OSX on Travis):
```
editor/project_settings.cpp:1291:75: error: conversion from 'long' to 'const Variant' is ambiguous
        ClassDB::bind_method(D_METHOD("_add_item"), &ProjectSettings::_add_item, DEFVAL(NULL));
                                                                                 ^~~~~~~~~~~~
```

2017-06-25 11:20 UTC, bojidar-bg commented on editor/project_settings.cpp
> +	ClassDB::bind_method(D_METHOD("_add_item"), &ProjectSettings::_add_item, DEFVAL(NULL));
Hm, maybe I should use DEFVAL(Variant())...

2017-06-26 20:55 UTC, akien-mga approved these changes

2017-06-26 21:00 UTC, merged

2017-06-26 21:02 UTC, Hinsbart commented on editor/project_settings.cpp
> +void ProjectSettings::_add_item(int p_item, Ref<InputEvent> p_exiting_event) {
Why is the event exiting? Did you mean existing? ^^

2017-06-27 08:46 UTC, bojidar-bg commented on editor/project_settings.cpp
> +void ProjectSettings::_add_item(int p_item, Ref<InputEvent> p_exiting_event) {
Ooops. 😃