Fix default collision shape on imported rigidbody
godotengine/godot pull request #93506
Opened 2024-06-23 11:35 UTC by BastiaanOlij

After discussing with @reduz , the functionality he was under the impression of existing was that we would use Trimesh as the default for static colliders, and Decompose Convex for dynamic colliders.

This does not seem to be applied. 
This PR fixes the automatic creation of the collision shape if no value was saved to `shape_type`, however it does not embed the logic of changing it properly when you select the right option from the dropdown. Need some guidance on how this can be made to work in the UI here. 

- Partially fixes #93501 if body type is changed.

2024-06-24 00:18 UTC, BastiaanOlij commented
Adjusted this so our default mode is "automatic" after a suggestion @Calinou made.

This way we have our backwards compatibility in tact without needing to do weird interface changes

2024-06-27 16:00 UTC, fire approved these changes
I think this is good.

2024-06-27 16:25 UTC, fire requested changes
Compatibility breaking discussion in meeting.

2024-06-27 16:30 UTC, clayjohn approved these changes

2024-06-27 16:35 UTC, fire approved these changes

2024-06-27 16:35 UTC, AThousandShips approved these changes

2024-06-28 09:37 UTC, merged

2024-06-28 09:39 UTC, akien-mga commented
Thanks!