fix: change esthetic -> aesthetic
godotengine/godot pull request #93977
Opened 2024-07-05 16:23 UTC by ericrallen

This PR ensures consistent spelling for `aesthetic` across the in-editor docs (and also a few in-code comments where it is written), preferring the more widely-used "ae" spelling.

2024-07-05 16:26 UTC, AThousandShips requested changes
This is not correct, esthetic is the US English spelling, aesthetic is generally the UK one, and we use the US spelling when it differs

Source: https://en.wiktionary.org/wiki/esthetic#English

2024-07-05 16:53 UTC, ericrallen commented
Happy to change it to the `e` if that's really preferred, but I don't think most people actually use the `e` spelling unless they are referring to skincare, where esthetic and esthetician are popular spellings.

It also seems pretty rare to find anything written about video games, art, or design that doesn't use the `ae` spelling.

As a US-born, native English speaker, I had to Google "estethic" based on your response and this English StackExchange answer has some interesting deep dives into this: https://english.stackexchange.com/q/173585

I just noticed it spelled differently in two places while looking at some in-editor tooltips.

2024-07-05 16:54 UTC, AThousandShips commented
I'd say to leave it be, it's a minor difference either way

2024-07-05 17:08 UTC, AThousandShips submitted a review, later dismissed
We can keep this for discussion, I don't think this change is worth it as it's a different (yet standard) spelling more US specific which fits our guidelines, though I don't think we should change `aesthetic` to `esthetic` either

If you still want this change please fix the translation files, they should not be manually edited, and after that I'll remove the changes requested and we'll have this as up for discussion

2024-07-05 17:08 UTC, AThousandShips commented on doc/translations/zh_CN.po
This file shouldn't be edited

2024-07-05 17:08 UTC, AThousandShips commented on doc/translations/zh_TW.po
Or this one

2024-07-05 18:59 UTC, LinuxUserGD commented
> This is not correct, esthetic is the US English spelling, aesthetic is generally the UK one, and we use the US spelling when it differs
> 
> Source: https://en.wiktionary.org/wiki/esthetic#English

See https://www.merriam-webster.com/dictionary/aesthetic (comment: https://forum.wordreference.com/threads/aesthetic-esthetic.1502784/#post-7604976).
Both variants seem to be equally common in US English spelling.

2024-07-05 20:04 UTC, ericrallen commented on doc/translations/zh_CN.po
👍 Sorry about that. Should have been more targetted in my replacing.

2024-07-05 20:04 UTC, ericrallen commented on doc/translations/zh_TW.po
👍 Sorry about that. Should have been more targetted in my replacing.

2024-07-05 20:13 UTC, ericrallen commented
I removed the changes to the translation files. Sorry for the confusion on that.

If this is too minor a change, feel free to close it - I know it's not actually that important.

I just noticed discrepancies in how the word was spelled between the official docs and then in a few places in the in-editor tooltips and wanted to make it consistent - and `aesthetic` is the far more common spelling, especially when referring to visual arts.

2024-07-05 20:35 UTC, Mickeon commented
There's actually a pretty fair debate on how people expect this word to be spelled as, so keep this PR open. At most it will just not ever be merged.
Note that it's difficult to justify these fixes in the docs unless they are typos or plainly inaccurate, because it causes the corresponding translations to become "outdated" even with minor changes.

It's not as clear-cut case of "esthetic is the `en_us` way of saying it" because both are completely fine even in US English. Now it's a matter of questioning how **non-native speakers** expect it to be.
One of the lines this PR fixes was even written by me as "aesthetic" originally, before @AThousandShips suggested to change it.

2024-07-05 20:41 UTC, akien-mga commented
It's anecdotal, but as a non native speaker "aesthetic" is a lot more natural to me.

codespell had the replacement in their en_GB to en_US dictionary for a bit, but removed it as it was indeed pointed out that aesthetic is valid in en_US.

I think we can just pick one and keep it consistent, I don't think this would rub people off the wrong way. Since aesthetic is ok in en_US, I'd say let's be nice to en_GB and international speakers by picking the "ae" variant.

2024-07-05 20:58 UTC, Mickeon approved these changes
Non-native speaker and it's my own preference too.

2024-07-05 21:01 UTC, AThousandShips approved these changes
Don't have a preference either way but this standardized things

2024-07-06 03:24 UTC, marcospb19 approved these changes
non-native here too, I didn't know "esthetic" existed and meant "aesthetic", I'm familiar with the latter

2024-07-06 10:41 UTC, aaronfranke approved these changes
I'm from the US, native English speaker, and I've always seen "aesthetic", never any other version. The existence of "esthetic" is brand new information to me. I say let's go with the correct and standard "aesthetic".

2024-07-07 09:33 UTC, mrjustaguy commented
As a non native speaker, I've only ever heard of aesthetic, and at first esthetic seemed to me like a typo

2024-07-07 10:44 UTC, merged

2024-07-07 10:45 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: