Added exclude's replace-don't-edit type property in PhysicsShapeQueryParameters3D docs
godotengine/godot pull request #94059
Opened 2024-07-08 05:09 UTC by ayanchavand

Fixes #93895 
- Added the line` Note that [code]exclude[/code] is a replace-don't-edit type property and can only be modified by replacing the entire array.` to the PhysicsShapeQueryParameters3D.exclude docs

2024-07-08 07:58 UTC, AThousandShips requested changes

2024-07-08 07:58 UTC, AThousandShips commented on scene/resources/3d/primitive_meshes.cpp
> +			x = safesin(u * Math_TAU);
Unrelated, remove from this PR

2024-07-08 08:08 UTC, AThousandShips commented
This should probably be done to *all* the cases of this, both 2D and 3D as well as the other parameters such as point and ray queries

2024-07-08 08:55 UTC, Mickeon commented
[Your own PR](https://github.com/godotengine/godot/pull/85207) does this but it is done for every Packed Array property. To handles arrays like these would require a solution that allows Array properties to add the note automatically given a certain criteria

2024-07-08 08:56 UTC, AThousandShips commented
That would be pretty complex as there's no way to detect it, so it'd be a matter of adding a new property to the XML class, not sure it's worth it, but might look into checking how many cases there are for this

2024-07-08 09:16 UTC, Mickeon commented
Not this case specifically, but there are many times where information is repeated that may benefit from such a system, similar to the keywords.

2024-07-08 09:18 UTC, AThousandShips commented
Absolutely, and I'll look at if there's enough cases to justify a system, but since this isn't automatable, and is likely not very common (i.e. cases that copy and *aren't* `Packed*Array`s which require a *different* message), it might not be worth it, but I'll take a look at adding an option to manually tag with `is_copied` or something to make the output text automated

2024-07-08 12:03 UTC, AThousandShips commented
Please add to the other cases mentioned to get this to cover all the related cases, then this should be ready!

2024-07-08 12:03 UTC, AThousandShips commented
You also merged your branch instead of using a force push, please use `git push --force` instead, and when you're done please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

2024-07-08 12:07 UTC, ayanchavand commented
I think I accidentally created a branch from some other local branch instead of master, is it okay if I open new pr with the above changes?

2024-07-08 12:08 UTC, AThousandShips commented
You can just rebase it, see the link, it shouldn't matter as long as you rebase on `master`

Also please make the final commit message something clear, like the PR title

2024-07-08 13:18 UTC, AThousandShips approved these changes

2024-07-09 15:06 UTC, Mickeon approved these changes

2024-07-09 16:13 UTC, mhilbrunner approved these changes

2024-07-10 22:28 UTC, merged

2024-07-10 22:29 UTC, akien-mga commented
Thanks!