Pass current value to `EditorInterface` node/property popups
godotengine/godot pull request #94323
Opened 2024-07-13 18:14 UTC by Naros

Fixes #94322

2024-07-13 18:40 UTC, AThousandShips commented
You need to bind compatibility methods, see [here](https://docs.godotengine.org/en/latest/contributing/development/handling_compatibility_breakages.html)

2024-07-13 18:42 UTC, Naros commented
> You need to bind compatibility methods, see [here](https://docs.godotengine.org/en/latest/contributing/development/handling_compatibility_breakages.html)

Even if these methods were introduced in an alpha/beta build of Godot 4.3?

2024-07-13 19:12 UTC, AThousandShips commented
Oh my bad didn't know they were current, then it's unnecessary

2024-07-13 19:13 UTC, AThousandShips commented on editor/editor_interface.cpp
> +void EditorInterface::popup_node_selector(const Callable &p_callback, const TypedArray<StringName> &p_valid_types, Node *current_value) {
```suggestion
void EditorInterface::popup_node_selector(const Callable &p_callback, const TypedArray<StringName> &p_valid_types, Node *p_current_value) {
```

2024-07-13 19:13 UTC, AThousandShips commented on editor/editor_interface.cpp
> +void EditorInterface::popup_property_selector(Object *p_object, const Callable &p_callback, const PackedInt32Array &p_type_filter, const String &current_value) {
```suggestion
void EditorInterface::popup_property_selector(Object *p_object, const Callable &p_callback, const PackedInt32Array &p_type_filter, const String &p_current_value) {
```

2024-07-13 19:50 UTC, Naros commented on editor/editor_interface.cpp
> +void EditorInterface::popup_property_selector(Object *p_object, const Callable &p_callback, const PackedInt32Array &p_type_filter, const String &current_value) {
Fixed.

2024-07-13 19:51 UTC, Naros commented on editor/editor_interface.cpp
> +void EditorInterface::popup_node_selector(const Callable &p_callback, const TypedArray<StringName> &p_valid_types, Node *current_value) {
Fixed.

2024-07-18 18:14 UTC, AThousandShips approved these changes, later dismissed
Not familiar with the internals so a second eye on this would be good but the code looks good to me and the existing interface is just employed

2024-07-19 09:03 UTC, akien-mga commented on doc/classes/EditorInterface.xml
> +				Pops up an editor dialog for selecting a [Node] from the edited scene. The [param callback] must take a single argument of type [NodePath]. It is called on the selected [NodePath] or the empty pa
```suggestion
				Pops up an editor dialog for selecting a [Node] from the edited scene. The [param callback] must take a single argument of type [NodePath]. It is called on the selected [NodePath] or the empty path [code]^""[/code] if the dialog is canceled. If [param valid_types] is provided, the dialog will only show Nodes that match one of the listed Node types. If [param current_value] is provided, the Node will be automatically selected in the tree, if it exists.
```

2024-07-19 13:01 UTC, Naros commented on doc/classes/EditorInterface.xml
> +				Pops up an editor dialog for selecting a [Node] from the edited scene. The [param callback] must take a single argument of type [NodePath]. It is called on the selected [NodePath] or the empty pa
Fixed @akien-mga

2024-07-22 22:56 UTC, KoBeWi commented
The `current_value` in `popup_property_selector()` seems to do nothing. Nothing is selected no matter what I tried to use.

2024-07-25 02:59 UTC, Naros commented
Hi @KoBeWi so I checked the code in the `property_selector.h` and `property_selector.cpp` files and it does seem that while one can pass the current "selected" value into the dialog, the logic within `PropertySelector::_update_search` does not actually do anything with the member variable `selected`.

Looking more closely at the uses of `PropertySelector`, there are 8 public methods that pass the current value and store that in the `selected` member variable; however, while the member variable's value is set by those 8 methods, it's not used internally in any of the presentation logic sadly.

So I think for completeness, we should at the very least keep the ability to pass this value on the `EditorInterface`.  This minimizes the need to introduce any compatibility method after-the-fact.  I think the question is really how do we want to address this bug, as a part of this PR or a follow-up.  

I'm of the opinion that give where we are with 4.3, we should likely take care of addressing the `PropertySelector` implementation bug separately at the outset of 4.4 and then consider backporting that fix.  What do others think?  @akien-mga ?

2024-07-25 10:52 UTC, KoBeWi commented
Well, you added a new argument and it didn't require any compatibility code, so looks like adding arguments in the future is not a problem.
I think this can be pushed to 4.4 and let you can finish it properly.

2024-07-25 11:19 UTC, akien-mga commented
> Well, you added a new argument and it didn't require any compatibility code, so looks like adding arguments in the future is not a problem. I think this can be pushed to 4.4 and let you can finish it properly.

It doesn't require compatibility code now because this is a new API in 4.3.

If a new argument is added in 4.4, it will indeed require a compat binding. But that's no big deal so if the added API doesn't work, I think it's better to take the time to do it right (otherwise we'd add something in 4.3 where the docs are actually wrong about what the new argument does).

2024-07-25 11:22 UTC, KoBeWi commented
We could say in the docs to say that the argument is unused 🤔
And then change it once it's fixed.

2024-07-26 00:12 UTC, Naros commented
As I see Remi has moved this to 4.4, what's the final verdict then here?

2024-07-26 08:00 UTC, akien-mga commented
To me there's not much gain adding an argument that does nothing in 4.3, to fix it later. It still means that people who want to make EditorPlugins using this API will have to special case 4.3.0 because while they can use the API, it won't work.

And making it work in 4.3.x would be confusing IMO, documentation typically doesn't state in which version an API was made operative, and the docs will be updated once the bug is fixed to remove mention of it not working.

So I'd say this should wait for 4.4. We're in RC stage, it's no longer the time to

2024-08-15 14:37 UTC, Naros commented
Can someone point me to an example of compatibility methods, I plan to update this PR with the fix & I'd like to get this in merge shape asap.  Thanks!

2024-08-15 15:39 UTC, KoBeWi commented
Check `.compat.inc` files and the PRs that added them.

2024-08-16 14:58 UTC, Naros commented
@KoBeWi added logic for the "current_value" matching for properties/methods & added compatibility methods.  Would you mind giving this another pass from your PoV?  Thanks!

2024-08-17 09:05 UTC, KoBeWi commented
Selecting now works, but it would be nice if the dialog scrolled to the selected item.

2024-08-19 09:58 UTC, KoBeWi commented
Almost. The view is not centered on the property, but awkwardly cut at the top:
![image](https://github.com/user-attachments/assets/1be11097-3b37-485f-bf6b-64d7a8bca38a)

2024-08-23 17:00 UTC, Naros commented
Thanks @KoBeWi, fixed.  It appears I needed to delay the `scroll_to_item` until the end of the frame since building of the list was still in-flight and the offset would obviously change due to additional items added.

2024-08-23 17:07 UTC, AThousandShips commented
You've added your own compatibility file, this isn't correct, it should be added to the existing `4.3-stable.expected`

2024-08-24 05:27 UTC, Naros commented
> You've added your own compatibility file, this isn't correct, it should be added to the existing `4.3-stable.expected` (creation of these files is handled by maintainers, you don't need to do it yourself)

Well, as you can see that file doesn't exist based on the HEAD of this PR, and so I based those changes on what I saw in other PRs.  I'll rebase and amend the existing file.  Is this documented somewhere ?

2024-08-24 09:18 UTC, AThousandShips commented
Don't think it's documented but it's a general maintenance thing, good to rebase after a release to make sure things are up to date

2024-09-01 19:56 UTC, KoBeWi commented on doc/classes/EditorInterface.xml
> +				Pops up an editor dialog for selecting a [Node] from the edited scene. The [param callback] must take a single argument of type [NodePath]. It is called on the selected [NodePath] or the empty pa
```suggestion
				Pops up an editor dialog for selecting a [Node] from the edited scene. The [param callback] must take a single argument of type [NodePath]. It is called on the selected [NodePath] or the empty path [code]^""[/code] if the dialog is canceled. If [param valid_types] is provided, the dialog will only show Nodes that match one of the listed Node types. If [param current_value] is provided, the Node will be automatically selected in the tree, if it exists.
```

2024-09-01 19:58 UTC, KoBeWi commented on editor/editor_interface.compat.inc
> +void EditorInterface::popup_node_selector_compat_94322(const Callable &p_callback, const TypedArray<StringName> &p_valid_types) {
The old method should just call the new one. The behavior is the same when you pass empty string for current value.

2024-09-01 20:01 UTC, KoBeWi commented on editor/property_selector.cpp
> +			callable_mp(search_options, &Tree::scroll_to_item).bind(search_options->get_selected(), true).call_deferred();
```suggestion
			callable_mp(search_options, &Tree::scroll_to_item).call_deferred(search_options->get_selected(), true);
```

2024-09-01 20:01 UTC, KoBeWi commented on editor/property_selector.cpp
> +			// As we call this while adding items, defer until list is completely populated
```suggestion
			// As we call this while adding items, defer until list is completely populated.
```

2024-09-01 20:02 UTC, KoBeWi approved these changes

2024-09-01 20:56 UTC, AThousandShips commented on misc/extension_api_validation/4.3-stable.expected
> +GH-94322
```suggestion

GH-94322
```
Two lines

2024-09-01 20:56 UTC, AThousandShips commented on misc/extension_api_validation/4.3-stable_4.4-stable.expected
This file shouldn't exist

2024-09-02 08:24 UTC, AThousandShips requested changes

2024-09-02 08:25 UTC, AThousandShips commented on editor/editor_interface.compat.inc
> +	popup_node_selector(p_callback, p_valid_types);
```suggestion
	popup_node_selector(p_callback, p_valid_types, nullptr);
```
Pass the default explicitly

2024-09-03 07:56 UTC, AThousandShips approved these changes

2024-09-03 09:54 UTC, merged

2024-09-03 09:56 UTC, akien-mga commented
Thanks!