Fix animation library copy-paste not preserving resource reference
godotengine/godot pull request #94429
Opened 2024-07-16 09:43 UTC by mihe

Currently when using the copy-paste functionality in the animation library editor (found under the "Manage Animations..." button in the Animation dock) you're not able to copy an animation while also preserving any resource file reference that it might have.

Here's how it looks currently:

https://github.com/user-attachments/assets/407179d3-893e-4b1c-b60f-1ffa912a1bf3

Here's what it looks like with this change applied:

https://github.com/user-attachments/assets/a89c053c-d539-4377-9b87-6b95a72fc35f

I've talked to @reduz who wrote the affected line, and it seems that the current behavior was not the original intention, so this is likely a bug.

2024-07-17 17:32 UTC, fire commented
@TokageItLab I think it looks ok, but didn't dig into depth.

2024-07-25 05:58 UTC, TokageItLab requested changes
I find this behavior confusing.

If there are two animations in the animation library with the same reference, won't editing the copied animation change the other one too?

I assume that this would be an undesirable behavior in the most cases. It require the user to uniquify the animation each time it is copied, which would be a waste of time and effort. If this behavior is needed, it should be an option such as Shift+Click.

2024-07-25 09:26 UTC, mihe commented
@TokageItLab I would argue that current behavior should be the one behind the keyboard shortcut in that case. Everywhere else in Godot (that I'm aware of) you end up preserving resource references when you copy something that holds such a reference (although that behavior is admittedly controversial and [will likely be an option](https://github.com/godotengine/godot-proposals/issues/9603) at some point).

I realize the video clips showed the same animation being copied into the same library, where I'll admit that referencing the same animation is a niche use-case at best, but in our case we're of course copying these between different animation libraries, where we do want changes to apply to all animations that reference it, and frankly I struggle to even see the point of being able to save animation resources to a file if the references aren't going to be preserved by default.

2024-07-25 14:50 UTC, TokageItLab commented
@mihe Adding animations with the same reference to the same AnimationLibrary will definitely create a new issue, so you have to at least separate the behavior between copying to a different AnimationLibrary and copying to the same AnimationLibrary. In doing so, we may need to warn that references will be pasted into different AnimationLibraries.

Or, simply disallow pasting into the same AnimationLibrary. In this case, it is sufficient to inform the user that pasting the same reference to the same animation library is a prohibited operation, by issuing an error in the Dialog. If you want to copy an animation to the same animation library, you can use the AnimationTrackEditor to duplicate it, so there should be no problem in prohibiting it.

2024-07-25 15:27 UTC, mihe commented
> However, I believe there are enough cases where people want to paste without reference, so I think the better compromise is to simply add a new paste+duplicate button next to the existing paste button without any prohibiting

@TokageItLab Sure, that sounds reasonable to me. I'll make a new PR for this, and we'll see where that goes.

Thank you for the feedback!

2024-08-06 16:55 UTC, reduz commented
This should be reopened. Everywhere in the editor, pasting an externally saved resource just links to it. We never, ever duplicate them so the way this PR worked originally should be the way to go.

2024-08-06 16:59 UTC, reduz commented
To clarify, as policy in the editor we _never_ duplicate external resources under any circumstance.

2024-08-26 03:15 UTC, TokageItLab approved these changes
Approve from reduz's comment

2024-08-26 09:02 UTC, merged

2024-08-26 09:02 UTC, akien-mga commented
Thanks!

2024-09-16 15:18 UTC, akien-mga commented
Cherry-picked for 4.3.1.