Fix use condition_variable after delete
godotengine/godot pull request #94801
Opened 2024-07-26 14:21 UTC by Ratio2

This fix crash on android.
Crash reproduced in 4.1.2, 4.1.4 and 4.2.2.
Crash logcat with:
```
scons platform=android target=template_debug dev_build=yes CCFLAGS=-fsanitize=hwaddress LINKFLAGS=-fsanitize=hwaddress
```
[android-crash-3.txt](https://github.com/user-attachments/files/16392993/android-crash-3.txt)

2024-07-29 10:52 UTC, RandomShaper commented
Thing that would help:
- Further info about under which situations the issue happens and so why such a fix is needed.
- A minimal reproduction project.
- Check if #94169 fixes it already.

2024-07-29 16:00 UTC, Ratio2 commented
> Thing that would help
The crash sometimes happens when loading a certain number of scenes before the game starts. The game engine should not crash under any circumstances, so this fix is ​​necessary.

I can't provide a minimal example, because it would take too much time. It's already taken a lot of time to catch this bug, fix it and test it.

See the android-crash-3.txt file in the first post, it shows that another thread destroys the object while it is in use. MR https://github.com/godotengine/godot/pull/94169 is unlikely to help, since the code for creating and deleting condition_variable remains unchanged.

Detailed description of incorrect work with condition_variable:
1. We start loading the resource.
2. Someone wants to get this resource, but it is not ready. The condition_variable is created and waiting occurs.
3. After the loading is complete, we call notify_all and immediately delete the condition_variable. But we have no right to do this, because another thread is using the object.

2024-07-29 16:37 UTC, RandomShaper commented
I see. So, one thread may still be running `ConditionVariable::wait()` when another one decides to kill the cond var. And, even worse, multiple awaiters could end up trying to do the same. That's definitely a defect.

Now, your fix has a few code style issues, such as adding a seemingly multi-purposed helper class. The way `ResourceLoader` is written, which matches all the other lower level components in Godot overall is to favor explicitness. I'd suggest you to add instead an `awaiters_count` field to `LoadTask` and mend the logic as needed, in-place.

PS: I didn't need an MRP in the end. (Thank goodness! 😅)

2024-07-30 10:37 UTC, Ratio2 commented
> Now, your fix has a few code style issues, such as adding a seemingly multi-purposed helper class. The way `ResourceLoader` is written, which matches all the other lower level components in Godot overall is to favor explicitness. I'd suggest you to add instead an `awaiters_count` field to `LoadTask` and mend the logic as needed, in-place.

Done

2024-07-30 10:54 UTC, RandomShaper requested changes
Looks great. Just little style changes and we're good to go.

2024-07-30 10:54 UTC, RandomShaper commented on core/io/resource_loader.cpp
> +					++load_task.awaiters_count;
```suggestion
					load_task.awaiters_count++;
```

2024-07-30 10:54 UTC, RandomShaper commented on core/io/resource_loader.cpp
> +					if (!--load_task.awaiters_count) {
```suggestion
					load_task.awaiters_count--;
					if (load_task.awaiters_count == 0) {
```

2024-07-30 10:59 UTC, AThousandShips commented
Please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

2024-07-30 11:03 UTC, Ratio2 commented
> Please squash your commits into one

Done

2024-08-02 07:07 UTC, RandomShaper approved these changes

2024-08-21 09:14 UTC, merged

2024-08-21 09:14 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2024-09-05 11:50 UTC, RandomShaper commented
Cherry-pick for 4.3 included in #96606.