Increase default gravity accuracy
godotengine/godot pull request #95309
Opened 2024-08-09 01:19 UTC by python-nerd-3

This pull request simply changes the default gravity from 980 in 2d/9.8 in 3d to 981/9.81. This is to be more accurate with real gravity, which is 9.80665 m/s^2 which should round to 9.81 m/s^2.

I understand if this is for a reason. This still is quite unsatisfying to my little nerd brain.

Godot engine is a great and simple engine. Thanks everyone for creating it.

2024-08-09 07:40 UTC, AThousandShips requested changes, later dismissed
Thank you for your contribution, however this does nothing, the documentation just displays the value, you need to change the declaration, which are here:
https://github.com/godotengine/godot/blob/739019e4e4a6e4763e37adfd9883a1c85d5f6249/servers/physics_server_2d.cpp#L898
https://github.com/godotengine/godot/blob/739019e4e4a6e4763e37adfd9883a1c85d5f6249/servers/physics_server_3d.cpp#L1128

Note that this, while minor, still breaks compatibility, and should be discussed, the difference is tiny so changing it is of limited necessity, while also being of limited negative impact

2024-08-09 14:12 UTC, aaronfranke commented
I'm not sure this PR is an improvement. 9.8 is accurate to 2 significant figures, while 9.81 is accurate to 3. Why go some of the way but not all the way to 9.80665 itself?

Also, the actual gravity value on Earth varies from 9.78 to 9.83 depending on the exact location, 9.80665 is just the average. So 9.8 is a simpler number and still well within the range of Earth gravity.

2024-08-09 14:24 UTC, AThousandShips commented
I agree, if we are changing it (which I don't think is necessary) we should probably match it up with the default values in the internal areas:
https://github.com/godotengine/godot/blob/c73ac74c4a44ccfed158b3603f809a24590bac0a/servers/physics_3d/godot_area_3d.h#L49

So insead should be set to `9.80665`

But regardless the actual change in *accuracy* is tiny (going from `~0.00665` to `~0.00335`), so I'd call this "increase precision", though that's just a nitpick

2024-08-09 17:13 UTC, python-nerd-3 commented
The reason this has been rounded to 981 is due to that being the most precise whole number in 2D and 9.81 in 3D for consistency. I see how you can view this as unnecessary, however.

2024-08-09 17:18 UTC, python-nerd-3 commented
Fixed it to actually do something and not just change docs as you suggested.

2024-08-09 18:32 UTC, mrjustaguy commented
I really don't see the point in this tweak.. It'll just ever so slightly affect gravity without actually being discernably different, while also breaking compatibility as you are now falling at an ever so slightly higher rate that may in some very extreme cases break existing level design

2024-08-11 22:28 UTC, python-nerd-3 commented
Closing this PR due to not really being necessary.

2024-08-11 22:28 UTC, closed without merging