Fix make checkbox text clickable in FileDialog
godotengine/godot pull request #95304
Opened 2024-08-09 00:08 UTC by Giganzo

Fixes https://github.com/godotengine/godot/issues/95079

2024-08-09 01:06 UTC, Calinou approved these changes
Tested locally, it works as expected.

![image](https://github.com/user-attachments/assets/81de46c2-ab0e-42fd-b7b6-580617dfbf4a)


This makes sense to me as a stopgap to avoid an usability regression in 4.3. https://github.com/godotengine/godot/pull/95304 is a more comprehensive PR, but it's targeting 4.4 instead.

2024-08-12 15:32 UTC, akien-mga commented
@bruvzg I see you've another draft as #95140 doing this slightly differently.
In order to (possibly) fix the regression for 4.3, do you think this approach is fine as a quick fix?

Otherwise the regression isn't critical so it's fine to have it wait.

2024-08-12 15:45 UTC, bruvzg requested changes
This will immediately break for any file dialog with more than one option, it's using Grid container and should have the same number of child controls in every row.

<img width="361" alt="Screenshot 2024-08-12 at 18 45 25" src="https://github.com/user-attachments/assets/6c7b9063-acf5-4633-a705-f754760ca924">

2024-08-12 15:46 UTC, bruvzg commented
It's not critical and I'n not sure what's the best visual way to do it (https://github.com/godotengine/godot/pull/95140 probably is not the best), so I would not do anything for 4.3.

2024-09-21 18:18 UTC, Giganzo commented
The idea was that this could be used as a quick fix. Not sure if it still needed or if we should wait for some other solution.

2024-09-21 18:21 UTC, KoBeWi commented
tbh the initial solution could be fine if you added an empty Control to take Label's space.

2024-09-21 18:43 UTC, Giganzo commented
How it looks now with vbox.
![Screenshot_20240921_160811](https://github.com/user-attachments/assets/9a52153d-c51c-4a2e-b3c3-fba2d4bbcba2)

> tbh the initial solution could be fine if you added an empty Control to take Label's space.

With GridContainer and extra Control it looks like this.
![Screenshot_20240921_162419](https://github.com/user-attachments/assets/50274a30-7ad1-4f29-a095-2f0153394197)

Can revert to the GridContainer if you think it's better and this pr is still needed.

2024-10-15 20:30 UTC, KoBeWi commented
The latter looks better, because the controls are better aligned.
However there is #97892, which might supersede this PR (it was opened independently and just happens to fix the same issue).

2025-01-13 12:39 UTC, KoBeWi commented
Superseded by #99182
Thanks for the contribution nonetheless.

2025-01-13 12:39 UTC, closed without merging