More discreet panel icons
godotengine/godot pull request #95344
Opened 2024-08-09 21:43 UTC by eobet

The Godot panel icons in the main editor window is very "shouty". In a dark theme, especially at 200% display scaling, it's a huge, bright and shiny, near white flashlight in your eyes.

Also, not knowing what it was, I actually initially thought the icon was missing or bugged, as it's just a white square!

![image](https://github.com/user-attachments/assets/4d26a6c6-0009-4108-8df6-18243d42216d)

2024-08-10 02:18 UTC, Calinou requested changes
Tested locally, there's an issue on light theme (**Interface > Theme > Preset**) where the icon's color fails to be converted. This makes the icon hard to see:

![image](https://github.com/user-attachments/assets/905fdff2-0af3-4874-8b2a-b9870c2039b4)

You likely need to double-check the fill color and make sure it matches the hexadecimal code used in the original icons **exactly** (`#e0e0e0`). You can commit the suggestions I made below to apply these changes to your fork, then [rebase](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) to squash the commits together into a single commit (so that our merge history is clean).

Other than that, it looks good in the dark theme:

1 | 2 | 3
-|-|-
![image](https://github.com/user-attachments/assets/a7ede257-41f8-4638-95c4-4074c07415ea) | ![image](https://github.com/user-attachments/assets/df9aaacc-7d97-4c10-9636-16a02725d9a4) | ![image](https://github.com/user-attachments/assets/2ed82a51-6805-47c8-bc4e-6bd7769d7909)

2024-08-10 02:19 UTC, Calinou commented on editor/icons/Panels1.svg
> +<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="2" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><g fill="#cdcece"><path d="m2373.3 5160.07v14.65c0 1.
```suggestion
<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="2" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><g fill="#e0e0e0"><path d="m2373.3 5160.07v14.65c0 1.35-1.31 2.44-2.93 2.44h-17.63c-1.62 0-2.94-1.09-2.94-2.44v-14.65c0-1.35 1.32-2.44 2.94-2.44h17.63c1.62 0 2.93 1.09 2.93 2.44zm-2.93 0h-17.63v14.65h17.63z" transform="matrix(.680794 0 0 .819261 -1599.732 -4225.443)"/><path d="m2353 5160h13v1h-13z" transform="matrix(.970803 0 0 2.37963 -2282.5171 -12277.28)"/></g></svg>
```

2024-08-10 02:19 UTC, Calinou commented on editor/icons/Panels2.svg
> +<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m2373.3 5160.07v14.
```suggestion
<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m2373.3 5160.07v14.65c0 1.35-1.31 2.44-2.93 2.44h-17.63c-1.62 0-2.94-1.09-2.94-2.44v-14.65c0-1.35 1.32-2.44 2.94-2.44h17.63c1.62 0 2.93 1.09 2.93 2.44zm-2.93 0h-17.63v14.65h17.63z" fill="#e0e0e0" transform="matrix(.680794 0 0 .819261 -1599.732 -4225.443)"/><path d="m2353 5160h13v1h-13z" fill="#e0e0e0" transform="matrix(.966892 0 0 2.37963 -2273.3145 -12277.28)"/><path d="m2359 5216v-10.29" fill="none" stroke="#cdcece" stroke-width="1.84" transform="matrix(0 1 -1.16667 0 6087.33 -2350)"/></svg>
```

2024-08-10 02:19 UTC, Calinou commented on editor/icons/Panels2Alt.svg
> +<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m2373.3 5160.07v14.
```suggestion
<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m2373.3 5160.07v14.65c0 1.35-1.31 2.44-2.93 2.44h-17.63c-1.62 0-2.94-1.09-2.94-2.44v-14.65c0-1.35 1.32-2.44 2.94-2.44h17.63c1.62 0 2.93 1.09 2.93 2.44zm-2.93 0h-17.63v14.65h17.63z" fill="#e0e0e0" transform="matrix(.680794 0 0 .819261 -1599.732 -4225.44)"/><path d="m2353 5160h13v1h-13z" fill="#e0e0e0" transform="matrix(.967544 0 0 2.37963 -2274.8483 -12277.28)"/><path d="m2359 5214v-10" fill="none" stroke="#cdcece" stroke-width="2" transform="translate(-2351 -5200)"/></svg>
```

2024-08-10 02:19 UTC, Calinou commented on editor/icons/Panels3.svg
> +<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m2373.3 5160.07v14.
```suggestion
<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m2373.3 5160.07v14.65c0 1.35-1.31 2.44-2.93 2.44h-17.63c-1.62 0-2.94-1.09-2.94-2.44v-14.65c0-1.35 1.32-2.44 2.94-2.44h17.63c1.62 0 2.93 1.09 2.93 2.44zm-2.93 0h-17.63v14.65h17.63z" fill="#e0e0e0" transform="matrix(.680794 0 0 .819261 -1599.732 -4225.44)"/><path d="m2353 5160h13v1h-13z" fill="#e0e0e0" transform="matrix(.978137 0 0 2.37963 -2299.7723 -12277.28)"/><g fill="none" stroke="#e0e0e0" stroke-width="2"><path d="m2359 5216v-12" transform="matrix(0 1 -1 0 5218 -2350)"/><path d="m2359 5210v-5" transform="translate(-2351 -5196)"/></g></svg>
```

2024-08-10 02:20 UTC, Calinou commented on editor/icons/Panels3Alt.svg
> +<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m2373.3 5160.07v14.
```suggestion
<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m2373.3 5160.07v14.65c0 1.35-1.31 2.44-2.93 2.44h-17.63c-1.62 0-2.94-1.09-2.94-2.44v-14.65c0-1.35 1.32-2.44 2.94-2.44h17.63c1.62 0 2.93 1.09 2.93 2.44zm-2.93 0h-17.63v14.65h17.63z" fill="#e0e0e0" transform="matrix(.680794 0 0 .819261 -1599.732 -4225.44)"/><path d="m2353 5160h13v1h-13z" fill="#e0e0e0" transform="matrix(.967952 0 0 2.37963 -2275.8071 -12277.28)"/><g fill="none" stroke="#e0e0e0"><path d="m2359 5216v-5.14" stroke-width="1.84" transform="matrix(0 1 -1.16667 0 6087.33 -2350)"/><path d="m2359 5214v-10" stroke-width="2" transform="translate(-2351 -5200)"/></g></svg>
```

2024-08-10 02:20 UTC, Calinou commented on editor/icons/Panels4.svg
> +<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m2373.3 5160.07v14.
```suggestion
<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m2373.3 5160.07v14.65c0 1.35-1.31 2.44-2.93 2.44h-17.63c-1.62 0-2.94-1.09-2.94-2.44v-14.65c0-1.35 1.32-2.44 2.94-2.44h17.63c1.62 0 2.93 1.09 2.93 2.44zm-2.93 0h-17.63v14.65h17.63z" fill="#e0e0e0" transform="matrix(.680794 0 0 .819261 -1599.732 -4225.44)"/><path d="m2353 5160h13v1h-13z" fill="#e0e0e0" transform="matrix(.987049 0 0 2.37963 -2320.7421 -12277.28)"/><g fill="none" stroke="#e0e0e0"><path d="m2359 5216v-10.29" stroke-width="1.84" transform="matrix(0 1 -1.16667 0 6087.33 -2350)"/><path d="m2359 5214v-10" stroke-width="2" transform="translate(-2351 -5200)"/></g></svg>
```

2024-08-10 08:31 UTC, AThousandShips commented
See also:
* https://github.com/godotengine/godot/pull/84450

2024-08-11 01:41 UTC, Calinou commented
> See also:
> 
>     * [Use unfilled panel splitting icons #84450](https://github.com/godotengine/godot/pull/84450)

That PR uses different icons (the bar on the top isn't wider than the other bars), which I think makes it a bit less intuitive.

2024-08-11 11:41 UTC, MewPurPur commented
I like this more too. I say let's get this one in.

2024-08-11 16:58 UTC, Calinou commented
@eobet I've squashed the commits together and force-pushed the result to your fork, so this PR should be in a mergeable state now. 4.3 is in release freeze, so this should be good to go early in the 4.4 cycle.

2024-08-11 17:00 UTC, Calinou approved these changes

2024-08-11 17:12 UTC, AThousandShips commented
Need to run the svg cleaning to handle CI

2024-08-11 19:02 UTC, eobet commented
> Need to run the svg cleaning to handle CI

That is strange, because I did that before I uploaded and if I try again on the file I get this:

```
eobet@surface:~/Downloads/svgcleaner_linux_x86_64_0.9.5$ ./svgcleaner --multipass Panels1.svg Panels1.svg 
Your image is 0.00% smaller now.
```

2024-08-11 19:29 UTC, eobet commented
@Calinou I just outlined, unioned and ran everything through svgclean again, with hopefully the correct color. Could you please double check this?

![image](https://github.com/user-attachments/assets/6e6ee4fd-77c7-4a76-9b12-3418c394a2cf)

2024-08-11 19:55 UTC, AThousandShips commented
The PR is now not squashed so needs to be squashed again, and it doesn't look like you updated any files but will run CI to see if it passes

2024-08-11 20:19 UTC, eobet commented
Ok, I found [this](https://docs.github.com/en/desktop/managing-commits/squashing-commits-in-github-desktop). Did I finally manage? 😰

2024-08-11 20:32 UTC, AThousandShips commented
The commits were not squashed, and it seems that you used `svgcleaner` but the CI doesn't use that now, but instead `svgo`, which is handled as part of the pre-commit hooks, lots of steps I'm sorry it's quite complicated, but setting it up is pretty straightforward if you're interested in attempting, otherwise I'm sure Calinou can work it out or I can help as well, but for the setup (it just requires setting up once and then you're ready) see [here](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#pre-commit-hook) (the page is for code style but the hooks are the same), after you've done that you need to do `git commit --amend` to make it apply to your files, possibly after squashing

2024-08-12 18:27 UTC, Calinou commented
I've applied svgo and squashed the commits together.

2024-08-12 18:48 UTC, MewPurPur requested changes

2024-08-12 18:48 UTC, MewPurPur commented on editor/icons/Panels1.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="2" clip-rule="evenodd" viewBox="0 0 16 16"><path fill="#e0e0e0" d="m2 .00195313c-1.10288522 0-2.
```suggestion
<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg"><path fill="#e0e0e0" d="M2 0a2 2 0 0 0-2 2v12.002a2 2 0 0 0 2 2h12.002a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm0 4h12v10H2z"/></svg>
```

2024-08-12 18:48 UTC, MewPurPur commented on editor/icons/Panels2.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" clip-rule="evenodd" viewBox="0 0 16 16"><path fill="#e0e0e0" d="m235
```suggestion
<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg"><path fill="#e0e0e0" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm0 4h12v4H2zm12 6v4H2v-4z"/></svg>
```

2024-08-12 18:48 UTC, MewPurPur commented on editor/icons/Panels2Alt.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" clip-rule="evenodd" viewBox="0 0 16 16"><path fill="#e0e0e0" d="m235
```suggestion
<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg"><path fill="#e0e0e0" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm0 4h5v10H2zm7 0h5v10H9z"/></svg>
```

2024-08-12 18:48 UTC, MewPurPur commented on editor/icons/Panels3.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" clip-rule="evenodd" viewBox="0 0 16 16"><path fill="#e0e0e0" d="m235
```suggestion
<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg"><path fill="#e0e0e0" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm0 4h12v4H2zm0 6h5v4H2zm7 0h5v4H9z"/></svg>
```

2024-08-12 18:48 UTC, MewPurPur commented on editor/icons/Panels3Alt.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" clip-rule="evenodd" viewBox="0 0 16 16"><path fill="#e0e0e0" d="m235
```suggestion
<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg"><path fill="#e0e0e0" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm0 4h5v4H2zm7 0h5v10H9zm-7 6h5v4H2z"/></svg>
```

2024-08-12 18:48 UTC, MewPurPur commented on editor/icons/Panels4.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" clip-rule="evenodd" viewBox="0 0 16 16"><path fill="#e0e0e0" d="m235
```suggestion
<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg"><path fill="#e0e0e0" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm0 4h5v4H2zm7 0h5v4H9zm-7 6h5v4H2zm7 0h5v4H9z"/></svg>
```

2024-08-16 21:55 UTC, eobet commented
Thank you for all your help! 🙏 I see various change attempts to fix my mess from even you experienced developers who know this system, so I know there would be zero chance for me as an artist/designer to get it right. 😰 I commented in Rocket Chat that there should be an easier avenue for artists/designers to contribute, and I hope that will be considered in the future. 💖

2024-08-16 22:55 UTC, merged

2024-08-16 22:55 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: