Added get_bus_index to AudioServer
godotengine/godot pull request #9583
Opened 2017-07-09 21:57 UTC by MadEqua

Implements proposed enhancement #9171

2017-07-09 22:06 UTC, reduz requested changes

2017-07-09 22:06 UTC, reduz commented on servers/audio_server.cpp
> +		return buses.find(bus);
this is probably redundant, just do a for() int the buses to find the right one..

2017-07-09 23:12 UTC, MadEqua commented
You're right, was trying to avoid a loop of string comparisons, but just noticed StringName is pretty efficient at that.

2017-07-10 01:56 UTC, vnen commented on servers/audio_server.cpp
> +	}
There's a trailing space here, clang-format isn't happy.

2017-07-10 01:57 UTC, vnen commented
You have two unrelated commits in the PR, you should rebase your branch to remove them.

2017-07-10 20:27 UTC, closed without merging