Fix shadow mesh recursion.
godotengine/godot pull request #95961
Opened 2024-08-22 19:09 UTC by RadiantUwU

closes #93486

2024-08-23 00:05 UTC, clayjohn commented on servers/rendering/rendering_server_default.h
> +		ERR_FAIL_COND_MSG(p1 == p2, "Cannot put the mesh itself as its own shadow mesh.");
This should be added to the implemented of `mesh_set_shadow_mesh` instead of adding a shim here.

2024-08-31 18:41 UTC, clayjohn requested changes
I think this is fine as a stopgap solution for now. I have suggested a language change for the error message to fix the english grammar. 

Ultimately, this only pushes back the issue by one level of recursion as the problem could still be reproduced with the following:
1. MeshA has shadow mesh set to MeshB
2. MeshB has shadow mesh set to MeshA

I think this is fine to merge as-is though as it fixes the reported issue and comes with very little cost. Ultimately, the problem lies in the editor itself not handling recursion as pointed out here: https://github.com/godotengine/godot/issues/93486#issuecomment-2187348151 That is a much larger problem that I don't think is worth tackling yet

2024-08-31 18:41 UTC, clayjohn commented on drivers/gles3/storage/mesh_storage.cpp
> +	ERR_FAIL_COND_MSG(p_mesh == p_shadow_mesh, "Cannot put the mesh itself as its own shadow mesh.");
```suggestion
	ERR_FAIL_COND_MSG(p_mesh == p_shadow_mesh, "Cannot set a mesh as its own shadow mesh.");
```

2024-08-31 19:40 UTC, clayjohn approved these changes

2024-09-03 09:54 UTC, merged

2024-09-03 09:58 UTC, akien-mga commented
Thanks!

2024-09-16 15:43 UTC, akien-mga commented
Cherry-picked for 4.3.1.