Sky: Adapted radiance size if AUTOMATIC_MODE resolves to REALTIME - Fixes #76166
godotengine/godot pull request #95990
Opened 2024-08-23 13:38 UTC by Breush

2024-08-25 01:41 UTC, Calinou approved these changes
Tested locally, it works as expected. Code looks good to me.

2024-08-25 18:13 UTC, akien-mga commented
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

2024-08-25 21:11 UTC, Breush commented
> For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

Thanks, I didn't noticed, updated my config.

2024-08-31 18:53 UTC, clayjohn requested changes
I don't think this is the correct fix for two reasons:
1. `material_get_data()` isn't thread safe. So this change introduces a race condition when using multithreaded rendering
2. This is hardcoded to only work with the Forward+ and Mobile rendering methods. It will fail when using Compatibility. 

I think the correct fix is to not fall back to the realtime mode when the radiance size is not 256. I.e. check for radiance size here:
https://github.com/godotengine/godot/blob/61598c5c88d95b96811d386cb20d714c35f4c6d7/servers/rendering/renderer_rd/environment/sky.cpp#L1253-L1256

and here:

https://github.com/godotengine/godot/blob/61598c5c88d95b96811d386cb20d714c35f4c6d7/drivers/gles3/rasterizer_scene_gles3.cpp#L914-L917

e.g. `if ((shader_data->uses_time || shader_data->uses_position) && sky->radiance_size == 256)`

2024-08-31 18:53 UTC, clayjohn commented on servers/rendering/renderer_rd/environment/sky.cpp
> +	SkyMaterialData *material_data = static_cast<SkyMaterialData *>(RendererRD::MaterialStorage::get_singleton()->material_get_data(material, RendererRD::MaterialStorage::SHADER_TYPE_SKY));
This will fail when using the compatibility renderer since it does not use RendererRD

2024-09-04 11:55 UTC, clayjohn approved these changes
Looks great!

Note for maintainers, this should be good for cherry picking

2024-09-04 15:17 UTC, merged

2024-09-04 15:17 UTC, akien-mga commented
Thanks!

2024-09-16 15:43 UTC, akien-mga commented
Cherry-picked for 4.3.1.