AudioStream(Playback)WAV: Use Vectors instead of pointers
godotengine/godot pull request #96017
Opened 2024-08-23 23:13 UTC by DeeJayLSP

Changes the types of (`AudioStreamPlaybackWAV::qoa.dec` and `AudioStreamWAV::data`) to use Vectors instead of pointers. This was done with `AudioStreamMP3`'s `data` between versions 3.x and 4.x of Godot.

Only private variables and function structures were modified, without altering return type, therefore does not break compatibility.

Alongside #95463, this PR makes the `AudioStreamWAV` and `AudioStreamPlaybackWAV` classes free of direct `memalloc/free` calls, and consequently the only `memalloc/free` calls within the `/scene` directory.

2024-08-26 18:18 UTC, fire commented
Does anyone know if using Vector instead of pointers causes audio corruption?

I don't understand why AudioStreamMP3 doesn't match AudioStreamWAV and AudioStreamPlaybackWAV.

2024-08-26 19:39 UTC, DeeJayLSP commented
> Does anyone know if using Vector instead of pointers causes audio corruption?

Most of audio playback works in two ways.

In case of uncompressed audio (WAV 8/16 bit) it simply copies samples from the data, into the buffer.

And with compressed (Vorbis, MP3, QOA) the data goes through a decode process, then to the buffer.

The only change is how the data is stored, not read.

2024-08-28 21:36 UTC, DeeJayLSP commented
One thing I noticed: `p_src` in `do_resample` is essentially the same as `base->data + AudioStreamWAV::DATA_PAD`, so I changed the code to use it directly.

2024-08-29 17:41 UTC, reduz requested changes

2024-08-29 17:47 UTC, DeeJayLSP commented on scene/resources/audio_stream_wav.h
> +		Vector<int16_t> dec;
Done

2024-08-30 13:02 UTC, DeeJayLSP commented
Rebased on top of master following #95463 merge

2024-09-07 07:35 UTC, reduz requested changes

2024-09-07 07:35 UTC, reduz commented on scene/resources/audio_stream_wav.h
> +	PackedByteArray data;
Since this array is not shared, use `LocalVector<uint8_t>`

2024-09-07 15:44 UTC, reduz approved these changes

2024-09-08 05:34 UTC, DeeJayLSP commented
One last force push. Forgot to set all values in the vector to 0, this was causing an audible pop when looping a 16-bit stream.

2024-09-08 21:24 UTC, merged

2024-09-08 21:26 UTC, akien-mga commented
Thanks!