Allow jumping to previous/next keyframe in animation player
godotengine/godot pull request #96013
Opened 2024-08-23 22:00 UTC by passivestar

Adds buttons to go to previous/next keyframe

If anything is selected in the scene it uses the keyframes of selected nodes. Otherwise it uses all keyframes in the current animation

https://github.com/user-attachments/assets/1d869afb-40b7-4e0e-974b-e985fdb3b2ef

Works the same way in bezier mode, it just ignores non-bezier tracks because you can't see them in the bezier editor

I also added shortcuts:

`Shift+Alt+A` - Previous keyframe
`Shift+Alt+D` - Next keyframe

Note: Animation editor is using hardcoded shortcuts for all buttons, it would be nice to make them rebindable in  a future PR

Note 2: When no keyframe to the left/right exist it jumps to the beginning or the end of the animation. Although those aren't keyframes I think this behaviour can be useful because we don't have dedicated buttons for that

Note 3: I left the repeating code in the loops because moving it into a new function would be a bit awkward since it needs to modify the nearest_key_time and it would hurt readability, but let me know if you think I should do it anyway

Closes https://github.com/godotengine/godot-proposals/issues/10142

2024-08-24 11:59 UTC, fire commented
I did not review the code yet, but I like the feature proposal.

2024-08-24 16:37 UTC, Mickeon commented
Not against this in the slightest but I'm severely concerned about the sheer amount of play buttons present. 5 is already many as is and... somewhat hard to distinguish in their current state.

2024-08-24 16:43 UTC, Mickeon commented on editor/plugins/animation_player_editor_plugin.cpp
> +	if (is_visible_in_tree() && k.is_valid() && k->is_pressed() && !k->is_echo() && !k->is_ctrl_pressed() && !k->is_meta_pressed()) {
I believe you could use `!k->is_command_or_control_pressed()` here.

2024-08-24 16:53 UTC, passivestar commented
> Not against this in the slightest but I'm severely concerned about the sheer amount of play buttons present. 5 is already many as is and... somewhat hard to distinguish in their current state.

Personally I'd remove the "play from beginning/end" buttons and expose their functionality through `Shift+Click` on the regular play buttons + keep their hotkeys (`Shift+A/D`). I find it especially unlikely that "play backwards from end" is used often to justify a button for it. You can also click on the stop button when the animation is not playing to jump to the beginning. That's already 3 different ways to play from the beginning without a button for it

> Main issue is that the current icons are not as distinct as Blender's, so I would be wary of that first.

I want to tweak them a little to make them consist of two visually distinct elements instead of one shape for better clarity. Like in blender

2024-08-24 16:57 UTC, Mickeon commented
By all means, those sound good to me. Never liked the design of anything Animation-related, so it may be a step in the right direction.

2024-08-24 17:08 UTC, passivestar commented
> By all means, those sound good to me. Never liked the design of anything Animation-related, so it may be a step in the right direction

I will tweak the icons in this PR, but open a separate one for additional cleanup because if we decide that those extra buttons should go I'll also need to make their hotkeys rebindable as I mentioned in the note above. I might also experiment with a design where play buttons are combined with the stop button

2024-08-31 21:39 UTC, TokageItLab requested changes
> Not against this in the slightest but I'm severely concerned about the sheer amount of play buttons present. 5 is already many as is and... somewhat hard to distinguish in their current state.

I agree with @Mickeon. Although I can agree only with the addition of pull-down menus (or right-click menus) and the addition of shortcuts, but I do not agree with the addition of buttons.

There are other methods to move the timeline cursor besides keyframes, such as moving to the snap position, but it is not made a button. Also, since we are planning to add markers in A, there is a possibility of moving to markers, but I don't think that all of them should be made into buttons for moving the timeline cursor. I do not think that keyframes should be treated specially.

The play button should only be for the play() stop() API, and if you want to add a button for movement, I believe it should be on a separate line or something like:

![image](https://github.com/user-attachments/assets/ead8b7ce-1fd7-4e1c-8d1c-a2e82e99f9e9)

Personally, I think this PR can be Approved if the buttons are removed.

2024-09-01 00:09 UTC, passivestar commented
@TokageItLab Thanks for the feedback! I'm ok with it being shortcut-only for the time being!

I removed the buttons and exposed the shortcuts. We can get this in and then decide on the best UI once the animation editor is feature-complete, including markers and whatever else it may need

<img width="653" alt="h" src="https://github.com/user-attachments/assets/d2db3765-a096-417d-85e8-863b01f95bb2"><br>

Since the hardcoded hotkeys needed to be removed from buttons' tooltips I also made the tooltips match the text of the shortcuts for less needed translations and removed the words "selected" and "current pos" which are arguably redundant in context

2024-09-01 00:44 UTC, TokageItLab approved these changes
I think it works well.

However, I think it is weird that the tooltip description for playback from the end is exactly the same for backward and forward playback, so I think some different wording is needed. Any one of the three suggestions below would be sufficient. If you have any other good ideas, feel free to suggest it.

2024-09-01 00:44 UTC, TokageItLab commented on editor/plugins/animation_player_editor_plugin.cpp
> +	play_bw->set_tooltip_text(TTR("Play Animation from End"));
```suggestion
	play_bw->set_tooltip_text(TTR("Play Animation Backwards from End"));
```

2024-09-01 00:44 UTC, TokageItLab commented on editor/plugins/animation_player_editor_plugin.cpp
> +	play->set_tooltip_text(TTR("Play Animation from End"));
```suggestion
	play->set_tooltip_text(TTR("Play Animation from Start"));
```
```suggestion
	play->set_tooltip_text(TTR("Play Animation from Head"));
```

2024-09-01 01:01 UTC, passivestar commented on editor/plugins/animation_player_editor_plugin.cpp
> +	play->set_tooltip_text(TTR("Play Animation from End"));
> I think it is weird that the tooltip description for playback from the end is exactly the same for backward and forward playback

A typo. Good catch 👍

2024-09-02 10:21 UTC, merged

2024-09-02 10:32 UTC, akien-mga commented
Thanks!

2024-09-11 09:41 UTC, Mickeon commented
I want the UI buttons, too. Delegating this feature to a secret option is the worst option, but it's worth addressing the current UI in separate PRs, such that it is not too overwhelming for most users but still very much accessible.

2024-09-20 19:44 UTC, nuclear commented
+1 for the keyframe buttons! This is a button the average user will want to use.
The play / play from start button should be merged. Play with a regular click, play from start with a shiftclick.

2024-09-20 23:41 UTC, TokageItLab commented
I have no strong insistence on the UI I have suggested above. However, we need to avoid confusing the "editor controls" with the "play/stop API available at runtime". So I would never agree to add it in the same column as the playback button.

Based on experience with AfterEffects, adding a keyframe move button next to TrackName in TrackEditor might be appropriate in terms of positioning in terms of functionality. How about it?

![image](https://github.com/user-attachments/assets/5613cb12-c04a-46b3-990c-8f34d5c79926)

2024-09-21 16:17 UTC, nuclear commented
Yes, this sounds like the best solution!