Add Advanced Settings switch to Editor Settings
godotengine/godot pull request #96467
Opened 2024-09-02 12:06 UTC by KoBeWi

Closes #30866

https://github.com/user-attachments/assets/58f04b4e-a62e-42d0-b1b5-40dc9a13c059

Adding the toggle was easy, the fun part is going through every setting and categorizing it as basic as relevant. I'm going to do that now, feel free to throw suggestions.

2024-09-02 12:54 UTC, Maran23 commented
Some suggestions:
[Editor]
- Language
- Dock Tab Style
- Font Size
- Display Scale
- Single Window Mode

[Theme]
- Follow System Theme
- Preset
- Spacing Preset

[Connection]
- Engine Version Update Mode
- Network Mode

[Import]
- Blender Path

[Complection]
- Idle Parse Delay
- Code Complete Delay
- Add String Name Literals
- Add Node Path Literals

[Window Placement] (also in case Godot does allow to run the game in the editor)

[Linuxbsd]
- Prefer Wayland

[Project Manager] (the three settings)

[Android]
- Android SDK Path
- Java SDK Path

[macOS]
- rcodesign

[Windows]
- rcedit
- signtool

2024-09-02 16:39 UTC, AThousandShips commented on editor/editor_settings_dialog.cpp
> +	bool use_advanced = EditorSettings::get_singleton()->get_project_metadata("editor_settings", "advanced_mode", false);
I'd say it makes sense per project, depending on what you're doing I'd say it influences what you actually want

2024-09-02 16:46 UTC, KoBeWi commented on editor/editor_settings_dialog.cpp
> +	bool use_advanced = EditorSettings::get_singleton()->get_project_metadata("editor_settings", "advanced_mode", false);
I already changed it to store globally.

2024-09-02 16:57 UTC, Mickeon commented
Are you by chance implementing this button partially because of https://github.com/godotengine/godot/pull/69012#pullrequestreview-2244280828 ?

2024-09-02 17:02 UTC, KoBeWi commented
No, but I can look into integrating that. Maybe after both PRs are merged.

2024-09-02 18:07 UTC, m4gr3d commented on editor/editor_settings.cpp
>  #endif
nit: I know this existed prior to this PR, but this section could be cleaned up by storing the default in a variable and only having that value changes based on the platform it's running on.

2024-09-02 18:17 UTC, m4gr3d requested changes

2024-09-02 18:17 UTC, m4gr3d commented on platform/android/export/export.cpp
> +	EDITOR_DEF_BASIC("export/android/debug_keystore", EditorPaths::get_singleton()->get_debug_keystore_path(), false, true);
`false, true` don't seem needed here.

2024-09-02 19:40 UTC, m4gr3d approved these changes

2024-09-02 19:43 UTC, m4gr3d requested changes

2024-09-02 19:43 UTC, m4gr3d commented on editor/editor_settings_dialog.cpp
> +	advanced_switch = memnew(CheckButton(TTR("Advanced Settings")));
Seems there are compile issues with `CheckButton`

2024-09-05 13:18 UTC, m4gr3d approved these changes

2024-09-17 07:10 UTC, akien-mga commented
Needs rebase, then looks good to merge IMO.

2024-09-17 11:45 UTC, akien-mga approved these changes

2024-09-17 19:06 UTC, merged

2024-09-17 19:07 UTC, akien-mga commented
Thanks!