Fix instant transformations not being committed when used in succession
godotengine/godot pull request #96530
Opened 2024-09-03 14:19 UTC by ev13bird

Fixes: [https://github.com/godotengine/godot/issues/96527](https://github.com/godotengine/godot/issues/96527).

The "Begin Translate/Rotate/Scale Transformation" family of actions weren't being committed when activated in succession without confirming or canceling.
This meant that they would not be added to the undo/redo history.

Using multiple transformations in succession should now commit the previous transformation.

https://github.com/user-attachments/assets/c6453992-7094-4495-9151-8b859d0d10c8

2024-09-03 19:42 UTC, ryevdokimov commented
Related: https://github.com/godotengine/godot/pull/86930

2024-09-03 20:34 UTC, ryevdokimov requested changes
Holding down the keys probably shouldn't repeatedly commit the transform. 

https://github.com/user-attachments/assets/821d1dcc-8f3f-4ddf-86c8-10f57dc32e92

2024-09-04 09:35 UTC, ev13bird commented
Good catch, thank you!

Fixed, and also disallowed starting instant transformations during a non-instant transformation (ie. when using the 3D gizmo).

2024-09-04 16:01 UTC, ryevdokimov commented
Good work, but unlike blender still, the object will immediately begin a transform if the keys are held down after mouse-down. Blender requires the key to be pressed again to start the process over.

2024-09-05 09:21 UTC, ev13bird commented
Fixed, thank you!

2024-09-05 10:36 UTC, kleonc commented
Please squash commits into one, see [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase).

2024-09-05 11:37 UTC, ev13bird commented
Squashed I think, thank you!

2024-09-05 15:13 UTC, ryevdokimov approved these changes
Looks good.

2024-09-05 15:30 UTC, akien-mga approved these changes

2024-09-05 15:56 UTC, merged

2024-09-05 15:56 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2024-09-16 15:45 UTC, akien-mga commented
Cherry-picked for 4.3.1.