fix | Allow Wayland to paste using middlemouse button
godotengine/godot pull request #96540
Opened 2024-09-03 22:16 UTC by hunterkepley

https://github.com/godotengine/godot/issues/96214

Fixes issue with middle-mouse click (even if enabled) not working with Wayland. From the issue, it works when Wayland is not in use, same system settings. But, when Wayland is in use, it breaks

Figured out `ctrl+v` pasting uses a different function than what was present for middle-mouse pasting. Replaced it here, and it works fine.

2024-09-03 22:18 UTC, hunterkepley commented
pre-commit checks passed

2024-09-03 22:28 UTC, hunterkepley commented
@fire Working on one more fix, this only fixes single line text boxes such as searching for a project

2024-09-03 22:33 UTC, hunterkepley commented
@fire fix for script editing merged, squashed`

2024-09-03 22:44 UTC, hunterkepley commented
Tested the aforementioned simpler fix (wrapping the working function within the broken one, to prevent code smell from edge case if statements that this MR provides) and it works fine

Would this be preferred?

2024-09-03 22:48 UTC, hunterkepley commented
Went ahead and pushed the other fix. Confirmed the function which returns an empty string from the clipboard primary is not working + only used in two places

Wrapping it like this prevents if statements + code smell

2024-09-03 23:53 UTC, deralmas requested changes
Hi, thank you for your contribution! The primary clipboard is different form the regular clipboard, so aliasing it to the regular one is not an acceptable solution unfortunately.

Instead, the proper fix would be to fix the primary clipboard logic itself.

Calling `DisplayServer.clipboard_get_primary` from GDScript (with a random string in my primary clipboard) returns this in a verbose log:
```
Selecting media type "text/plain;charset=utf-8" from offered types.
Read chunk of 15 bytes.
Done reading 15 bytes.
```

So it's clearly trying to read something, although in the end it returns an empty string. The regular and the primary clipboard work in a very similar way, so perhaps there's some difference between their handling? I can see a flush instead of a roundtrip but it seems to make no difference once swapped in.

The part from the above log is printed from `_read_fd` in `platforms/linuxbsd/wayland/wayland_thread.cpp`, you could take a look there.

I hope this is a good starting point and thank you again for contributing!

2024-09-04 00:03 UTC, hunterkepley commented
thanks- will make a fix soon

2024-09-04 00:19 UTC, hunterkepley commented
@Riteo Some development:
https://github.com/swaywm/sway/issues/1012#issuecomment-269126649

There seems to not be a primary clipboard in wayland

2024-09-04 01:52 UTC, hunterkepley commented
@Riteo PTAL- i am embarassed at how long it took to find this issue. We were throwing away the data gotten back from `primary_get_mime`. Assigned it to `data` and all is well

2024-09-04 02:03 UTC, deralmas approved these changes
Looks perfect! One small nitpick, please rename the commit and title to match the new change, prefixing it with `Wayland:` (e.g. `Wayland: Fix primary clipboard handling`)

2024-09-04 02:30 UTC, hunterkepley commented
Will do 🙂

2024-09-04 02:38 UTC, hunterkepley commented
On my Mac right now- downloading then amending commit msg

2024-09-04 09:22 UTC, merged

2024-09-04 09:23 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: