[GodotSharp] Implemented support for building with deprecated=no
godotengine/godot pull request #96570
Opened 2024-09-04 15:16 UTC by Drako

This fixes [GH-84426](https://github.com/godotengine/godot/issues/84426).

I added the option `--no-deprecated` to `build_assemblies.py`, which needs to be used, if the editor was built with `deprecated=no module_mono_enabled=yes`.

This conditionally disables code in `Compat.cs` which references deprecated classes or functions.

2024-09-04 16:44 UTC, akien-mga approved these changes
Makes sense to me. I'm not too familiar with C# buildsystem stuff though so I'll let @raulsntos double check.

2024-09-04 17:51 UTC, AThousandShips commented
You used a merge commit to update your branch, please use rebase in the future instead, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

You will need to squash your commits before this can be merged (though that can wait until the team has reviewed), see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) 

But make sure not to use merge commits in the future

2024-09-04 17:59 UTC, Drako commented
I don't see any merge commits ;)

2024-09-05 00:36 UTC, raulsntos requested changes
Makes sense to me, but we'd want to disable the entire `Compat.cs` and also do the same in the `GodotSharpEditor` assembly.

2024-09-05 00:36 UTC, raulsntos commented on modules/mono/glue/GodotSharp/GodotSharp/Compat.cs
> +#if !DISABLE_DEPRECATED
We'd want to disable the entire `Compat.cs` file, since all of these APIs only exist for compatibility.

2024-09-05 08:47 UTC, Drako commented
Makes sense to me. I also considered excluding Compat.cs first, but wasn't sure, if there was stuff in it which is still needed.
Anyway I conditionally excluded both Compat.cs files now and it seems to be working so far.

2024-09-05 12:33 UTC, raulsntos approved these changes
Looks good to me, thanks!

2024-09-05 15:56 UTC, merged

2024-09-05 15:58 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: