Disable rounded window corners on Windows
godotengine/godot pull request #96575
Opened 2024-09-04 21:20 UTC by pkdawson

I noticed when reading the latest [Dolphin progress report](https://dolphin-emu.org/blog/2024/09/04/dolphin-progress-report-release-2407-2409/) that it's actually possible to [disable the rounded corners](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/ui/apply-rounded-corners#example-3---rounding-an-apps-main-window-in-c) in Windows 11.

I feel like this is a desirable change for games in general, as it actually shows everything you render instead of hiding the bottom corners, which is particularly annoying when taking screenshots.

I suppose the argument against would be that it's inconsistent with the Windows 11 default, so non-game applications might look slightly odd to a user.

2024-09-04 21:53 UTC, frkntlr approved these changes
Appears without rounded corners in Windows 10.

2024-09-05 13:00 UTC, Repiteo requested changes
Note that Dolphin only applies the sharp corners for the game window; all other windows still retain the default, rounded style:
![24-09-05 07-39-51 explorer](https://github.com/user-attachments/assets/be48c869-0993-434e-b127-d05af2a29091)

2024-09-05 14:45 UTC, Repiteo approved these changes

2024-09-07 12:07 UTC, Hilderin commented
That will change a default Windows behavior. I guess for games it's great but for applications created with Godot, they probably prefers rounded corners. I think a new flag to deactivate the rounded corner should be a preferred and move flexible way. With a new flag, the condition on specific Engine window in `DisplayServerWindows` could be replaced by this new flag.

2024-10-18 15:55 UTC, pkdawson commented
Superseded by #97005

2024-10-18 15:55 UTC, closed without merging