Fix AudioStreamPlayer3D still processing when out of range
godotengine/godot pull request #96677
Opened 2024-09-07 09:42 UTC by Wierdox

Fixes #96670

Although said in [documentation](https://docs.godotengine.org/en/stable/classes/class_audiostreamplayer3d.html#class-audiostreamplayer3d-property-max-distance), AudioStreamPlayer3D doesn't do the claimed optimization: avoiding audio mixing when further than `max_distance` from the AudioListener3D. So I did a simple one line fix to the if statement for an early exit of its processing loop:
`if (total_max > max_distance)` -> `if (dist > total_max || total_max > max_distance)`
This oversight is also the case in 3.x, so it should be updated with this fix.

2024-09-07 21:42 UTC, Wierdox commented
Seems like this won't be so simple. Testing again with the MRP for the bug, it's only faster when it's never been in range of `max_distance`. After going in range of the players, they will keep processing and still be audible when exiting the `max_distance` range again, even though it is correctly doing the early exit in its process loop. See below:
|  | Very far away | Teleported to origin | To far away again |
|--------|--------|--------|--------|
| Stable + MRP with any `max_distance` | ~4ms highs, ~2ms lows | ~4ms highs, ~2ms lows | ~4ms highs, ~2ms lows |
| Fix + MRP with 0 `max_distance` | ~4ms highs, ~2ms lows | ~4ms highs, ~2ms lows | ~4ms highs, ~2ms lows |
| Fix + MRP with 100 `max_distance`| ~2ms highs, ~1ms lows| ~2.5-3ms highs, ~1.25ms lows | ~2.5-3ms highs, ~1.25ms lows |

2024-09-17 14:18 UTC, Mickeon commented
So, when you retreat from an AudioStreamPlayer3D that is continuously playing audio, the audio stream will **not** stop playing audio in this PR, right?

2024-09-17 16:10 UTC, adamscott approved these changes
Tested the PR. I confirm the sound not shutting off when moving outside the distance.

I tested also that this PR doesn't shut off other `AudioStream3D` playing when moving. Here's the MRP:
[audiostreamplayer3d-range-bug-local.zip](https://github.com/user-attachments/files/17031793/audiostreamplayer3d-range-bug-local.zip)

2024-09-17 18:30 UTC, akien-mga commented
I'm not too familiar with this class, but I see this is in a `for` loop for all Cameras. How does it handle cases where the player is out of range for one camera, but in range for another? Is this disabling processing globally or only for the current camera?

Also, should similar changes be done for AudioStreamPlayer2D, or does it already behave like this PR implements?

2024-09-17 22:38 UTC, masterthdev commented
>  How does it handle cases where the player is out of range for one camera

Multiple Camera2D/3D or AudioListener2D/3Ds do not increase processing time. Looks like it only processes current camera per viewport. A subviewport with Camera3D increased processing time from 15 ms to 500 ms on my machine. Subviewport + Camera2D doubled processing time as expected.

> Also, should similar changes be done for AudioStreamPlayer2D, or does it already behave like this PR implements?

Looks like it has same issue.

MRP for 2D: [audiostreamplayer2d-range-mrp.zip](https://github.com/user-attachments/files/17035411/audiostreamplayer2d-range-mrp.zip)

2024-09-19 12:56 UTC, Calinou commented
> For the early exit of _update_panning() processing, I'm not sure what the deal is with comparing max_distance with the area override reverb distance(assigned to total_max if > max_distance). 

If you rotate the camera quickly, panning may need to update even though you're outside the range as you're still hearing the sound via the reverb effect.

2024-09-19 13:24 UTC, Calinou requested changes
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/694d3c2930bdfb43fd93e1e6641f66c4f19a5c77), it works as expected.

However, there's now an object leak that occurs on exit with the MRP:

## `master`

```
$ bin/godot.linuxbsd.editor.x86_64.master --path /tmp/audiostreamplayer3d-range-bug --quit
Godot Engine v4.4.dev.custom_build.694d3c293 (2024-09-18 15:41:12 UTC) - https://godotengine.org
Vulkan 1.3.280 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 4090
Requested V-Sync mode: Disabled

```

### This PR

```
$ bin/godot.linuxbsd.editor.x86_64 --path /tmp/audiostreamplayer3d-range-bug --quit                                                 
Godot Engine v4.4.dev.custom_build.6819c26b1 (2024-09-19 12:31:25 UTC) - https://godotengine.org
Vulkan 1.3.280 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 4090
Requested V-Sync mode: Disabled

WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (./core/object/object.cpp:2329)
ERROR: 1 resources still in use at exit (run with --verbose for details).
   at: clear (./core/io/resource.cpp:592)
```

2024-09-19 13:30 UTC, Calinou approved these changes
Profiling when outside the range (with the project running for ~7 seconds each time):

### Before

![image](https://github.com/user-attachments/assets/c9a33766-9183-42ec-ac01-e581362a1bb2)

![image](https://github.com/user-attachments/assets/5f44e700-b0b1-498d-8a1e-2768732a104d)

### After

![image](https://github.com/user-attachments/assets/573b67b6-0b64-4210-a4d8-f660e05bbc69)

![image](https://github.com/user-attachments/assets/84d4a164-dde0-494a-8fae-e88d5bacf65e)

I'm not sure why audio resampling is still being called though.

2024-09-20 05:37 UTC, Wierdox commented
> If you rotate the camera quickly, panning may need to update even though you're outside the range as you're still hearing the sound via the reverb effect.

This would make sense, but the `continue` skips over the panning step in the function, so it doesn't seem to update that? Unless it is handled elsewhere, or I misunderstand you.

> I'm not sure why audio resampling is still being called though.

No clue myself, perhaps an internal process. I had trouble finding a way to mitigate the mixing, eventually I lucked into a function that seemed to help a decent amount. By the way, the performance gain when using the ogg or mp3 version of the sound is lesser, probably from the overhead of still resampling. Will look into this more, maybe I can set something so the resampling does an early exit itself.

------
I updated the PR to cache if it was out of range last frame, so it doesn't set the volume to zilch each time. Performance of audio server with all players out of range:
| Using .wav | Before | After|
|--------|--------|--------|
| 800 Players| ~26-30ms | ~1.5-2.75ms|
| 400 Players| ~.6-1.5ms| ~.6-1.5ms|

Seems to only make a measurable difference when overwhelmed with players, but maybe it's more noticeable on a slower CPU.

2024-09-20 14:15 UTC, merged

2024-09-20 14:15 UTC, akien-mga commented
Thanks!