Use collision detection ray to reposition an object already in the scene
godotengine/godot pull request #96740
Opened 2024-09-09 02:39 UTC by ryevdokimov

Closes: https://github.com/godotengine/godot-proposals/issues/10692

Related: https://github.com/godotengine/godot/pull/88511

Currently only works with one object at a time. Multiple objects would probably be a future PR if desired. 

Currently does not have a key binding by default: 

![image](https://github.com/user-attachments/assets/69e23427-7e66-415c-ad1f-37839d4247c8)

https://github.com/user-attachments/assets/0b00aa12-8dd5-42c6-9488-9608919adc68

2024-10-04 15:20 UTC, Calinou requested changes
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/f032af74536b317b23c7fca3bc7318ced5537344), it works as expected.

I miss a way to offset the object so that it appears outside the ground/wall though. The dragged object's collision shape AABB should be taken into account (if the dragged object is a PhysicsBody3D or CollisionShape3D). Without having this feature in place, you either have to drag a parent node that is offset compared to its child (which can break center of mass with physics nodes) or have to reposition the object manually later on, which kind of defeats the point of the feature for most objects.

Additionally, using the mouse wheel could work to offset the position in local space (i.e. relative to the current view direction)? Something like this (from Cube 2: Sauerbraten's editor):

https://user-images.githubusercontent.com/180032/136942243-c6045a02-b293-4da1-b365-682655cbeab3.mp4

> Currently does not have a key binding by default:

I suggest binding <kbd>Shift + G</kbd> by default to match https://github.com/godotengine/godot/pull/78148.

2024-10-04 15:26 UTC, ryevdokimov commented
> I miss a way to offset the object so that it appears outside the ground/wall though. The dragged object's collision shape AABB should be taken into account (if the dragged object is a PhysicsBody3D or CollisionShape3D).

Wouldn't this be resolved by: https://github.com/godotengine/godot/pull/88511?

2024-10-04 19:01 UTC, Calinou commented
> Wouldn't this be resolved by: #88511?

Yes, this works perfectly :slightly_smiling_face:

2024-10-04 19:16 UTC, ryevdokimov commented
>I suggest binding Shift + G by default to match https://github.com/godotengine/godot/pull/78148.

Done.

2024-10-04 21:49 UTC, ryevdokimov commented
Rebased and modified to work with: https://github.com/godotengine/godot/pull/88511

2024-10-04 22:13 UTC, Calinou approved these changes

2024-10-14 19:16 UTC, merged

2024-10-14 19:17 UTC, Repiteo commented
Thanks!

2024-11-10 21:59 UTC, thygrrr commented
Question, in the Dev 4 snapshot blog, this video in the top post is shown, but this shows the collisionshape fully intersecting with the surface (the snapping seems to be at the gizmo origin / anchor?

2024-11-11 03:03 UTC, ryevdokimov commented
> Question, in the Dev 4 snapshot blog, this video in the top post is shown, but this shows the collisionshape and mesh fully intersecting the surface (the snapping seems to be at the gizmo origin / anchor?

I'm not sure I understand the question, but if you're suggesting that the video in the snapshot post is somewhat misleading to the functionality in the build I would agree. This PR was created separately yet complimentary with https://github.com/godotengine/godot/pull/88511, which was also merged prior to dev 4 build, and the behavior of both is reflected within the dev4 build of the engine. The final position is offset by bounds of the object being positioned.

2024-11-14 12:35 UTC, albinaask commented
Would it be impossible to make the box not clip the conveyor belt, like offset the placement by half the AABB of the box? I think it would be a much more plausible scenario that you don't want the objects to intersect than that they would intersect like shown in the video.

2025-02-20 11:12 UTC, Nodragem commented
> I suggest binding Shift + G by default to match https://github.com/godotengine/godot/pull/78148

As long as there is no solution for implementing #78148 in a way that makes everyone happy (e.g. implementing it _alongside_ the QWER workflow, rather than overwritting/disrupting it), I would suggest to stay close to the current shortcuts?

Maybe use `Shift + W` or `ALT + W`, which are much easier to produce with the left hand. 

Alternatively, `W` could be used as a toggle between the translation tool and the `Reposition Using Collisions` tool. More accurately, it would cycle through the different "Move tools". Blender does that for the selection tools:
![image](https://github.com/user-attachments/assets/cf2caace-0f1b-4cec-ba01-f653bf25a20b)

2025-07-25 13:34 UTC, ratkingsminion commented
I tried to use this in my own scene and the object I try to snap to colliders is jumping around erratically. I just wanted to check if somebody else has experienced this, before I investigate further...

2025-07-25 16:38 UTC, ryevdokimov commented
That happens when the object is not filtering out its own collision which I've seen before with CSG objects but was fixed in a PR in 4.4. If you're still having that issue with something else, I recommend making an issue.

2025-07-25 21:33 UTC, ratkingsminion commented
I don't use any CSG objects in the scene. I'll make an issue, thanks.