Update AnimationPlayer in real-time when bezier curve properties or bezier editor changes
godotengine/godot pull request #96753
Opened 2024-09-09 13:10 UTC by Dowsley

Fix for https://github.com/godotengine/godot/issues/96591

I am unsure whether I should add the update to `AnimationBezierTrackEdit::duplicate_selected_key` as well.

2024-09-10 11:08 UTC, SaracenOne requested changes
I would consider adding an update in `_change_selected_keys_handle_mode` too since right-clicking and changing the handle mode currently does not trigger an update of the property.

2024-09-10 11:09 UTC, SaracenOne commented
I think this mostly fixes the issue. Regarding your point about the duplication, its difficult to say if the update should be added there too since A. duplicated points appear directly under the timeline cursor and B. the duplicate option from the right click menu appears to be broken anyway. I would consider adding the update anyway just for good measure, but I don't think its a big deal.

2024-09-10 15:59 UTC, Dowsley commented
> I would consider adding an update in _change_selected_keys_handle_mode too since right-clicking and changing the handle mode currently does not trigger an update of the property.

> I would also say that it is probably worth adding the update to the duplicate operation for good measure.

Updated with the required changes. I suppose the EditorUndoRedoManager is a queue, so the order of add calls matter. So I put the ape update key frame add above the queue_redraw.

2024-09-11 08:14 UTC, SaracenOne requested changes
Actually, found two more instances where we would also want to trigger the update: cutting and pasting.

To fix pasting, I think you should change line 1923 from:
```
		undo_redo->commit_action();

		queue_redraw();
```
to:
```
		AnimationPlayerEditor *ape = AnimationPlayerEditor::get_singleton();
		if (ape) {
			undo_redo->add_do_method(ape, "_animation_update_key_frame");
			undo_redo->add_undo_method(ape, "_animation_update_key_frame");
		}
		undo_redo->add_do_method(this, "queue_redraw");
		undo_redo->add_undo_method(this, "queue_redraw");

		undo_redo->commit_action();
```

For cutting, add this below line 1845:
```
		AnimationPlayerEditor *ape = AnimationPlayerEditor::get_singleton();
		if (ape) {
			undo_redo->add_do_method(ape, "_animation_update_key_frame");
			undo_redo->add_undo_method(ape, "_animation_update_key_frame");
		}
		undo_redo->add_do_method(this, "queue_redraw");
		undo_redo->add_undo_method(this, "queue_redraw");
```

This should solve the remaining edge cases.

2024-09-11 20:58 UTC, Dowsley commented
@SaracenOne good catch. Force pushed the changes.

2024-09-12 07:17 UTC, SaracenOne approved these changes
LGTM 👍

2024-09-12 08:44 UTC, merged

2024-09-12 08:44 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada:

2024-09-12 09:03 UTC, Zireael07 commented
This was someone's _first_ contribution? O_o

2024-09-12 12:00 UTC, Dowsley commented
It was mostly copying and pasting 😆 thanks for the help folks

2024-09-16 15:56 UTC, akien-mga commented
Cherry-picked for 4.3.1.