Unit tests for PhysicsMaterial
godotengine/godot pull request #97227
Opened 2024-09-20 09:54 UTC by D0V4HKIIN

Unit tests for PhysicsMaterial for tracker #43440

I am somewhat unsure about the relevancy of theses tests but here they are. Mostly testing setters and getters.

2024-09-20 10:00 UTC, AThousandShips requested changes, later dismissed

2024-09-20 10:00 UTC, AThousandShips commented on tests/scene/test_physics_material.h
> +	PhysicsMaterial *physics_material = memnew(PhysicsMaterial);
```suggestion
	Ref<PhysicsMaterial> physics_material;
	physics_material.instantiate();
```
For all, this is a RefCounted type so should use `Ref`

2024-09-20 10:00 UTC, AThousandShips commented on tests/scene/test_physics_material.h
> +	memdelete(physics_material);
```suggestion
```
Also for all

2024-09-20 11:00 UTC, AThousandShips commented
Thank you for your contribution!

These tests look good to me, but can't say if they cover things that we want to test for or not so this will have to be looked over by the physics team to give their approval

2024-10-01 13:58 UTC, Calinou commented on tests/scene/test_physics_material.h
> +TEST_CASE("[Physics_material] Defaults") {
```suggestion
TEST_CASE("[PhysicsMaterial] Defaults") {
```

2024-10-01 13:58 UTC, Calinou commented on tests/scene/test_physics_material.h
> +TEST_CASE("[Physics_material] Friction") {
```suggestion
TEST_CASE("[PhysicsMaterial] Friction") {
```

2024-10-01 13:58 UTC, Calinou commented on tests/scene/test_physics_material.h
> +TEST_CASE("[Physics_material] Rough") {
```suggestion
TEST_CASE("[PhysicsMaterial] Rough") {
```

2024-10-01 13:58 UTC, Calinou commented on tests/scene/test_physics_material.h
> +TEST_CASE("[Physics_material] Bounce") {
```suggestion
TEST_CASE("[PhysicsMaterial] Bounce") {
```

2024-10-01 13:58 UTC, Calinou commented on tests/scene/test_physics_material.h
> +TEST_CASE("[Physics_material] Absorbent") {
```suggestion
TEST_CASE("[PhysicsMaterial] Absorbent") {
```

2024-10-04 07:11 UTC, rburing approved these changes
Looks good to me, as it tests all that can be tested in isolation (using only this class). Please [squash the commits](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) as required by our workflow (and ideally, change the commit message to the current title of this PR).

2024-10-04 08:10 UTC, D0V4HKIIN commented
Done!

2024-10-04 09:33 UTC, merged

2024-10-04 09:35 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: