Add unit tests for UDPServer
godotengine/godot pull request #97311
Opened 2024-09-22 03:11 UTC by pafuent

This PR aims to help "fix" #43440

2024-09-24 12:03 UTC, RadiantUwU approved these changes

2024-09-24 16:32 UTC, Calinou commented on tests/core/io/test_udp_server.h
> +	// Required to get the connection properly stablished
```suggestion
	// Required to get the connection properly established
```

2024-09-24 16:32 UTC, Calinou commented on tests/core/io/test_udp_server.h
> +	// Required to get the connection properly stablished
```suggestion
	// Required to get the connection properly established
```

2024-09-24 16:32 UTC, Calinou commented on tests/core/io/test_udp_server.h
> +	// Required to get the connection properly stablished
```suggestion
	// Required to get the connection properly established
```

2024-09-24 16:32 UTC, Calinou commented on tests/core/io/test_udp_server.h
> +	// Required to get the connection properly stablished
```suggestion
	// Required to get the connection properly established
```

2024-09-24 16:32 UTC, Calinou commented on tests/core/io/test_udp_server.h
> +	// Required to get the connection properly stablished
```suggestion
	// Required to get the connection properly established
```

2024-09-24 16:32 UTC, Calinou commented on tests/core/io/test_udp_server.h
> +	// Required to get the connection properly stablished
```suggestion
	// Required to get the connection properly established
```

2024-09-24 16:33 UTC, Calinou commented on tests/core/io/test_udp_server.h
> +	// Required to get the connection properly stablished
```suggestion
	// Required to get the connection properly established
```

2024-09-24 16:33 UTC, Calinou commented on tests/core/io/test_udp_server.h
> +	// Required to get the connection properly stablished
```suggestion
	// Required to get the connection properly established
```

2024-09-24 16:33 UTC, Calinou commented on tests/core/io/test_udp_server.h
> +	// Required to get the connection properly stablished
```suggestion
	// Required to get the connection properly established
```

2024-09-24 16:35 UTC, AThousandShips commented on tests/core/io/test_udp_server.h
> +	// Required to get the connection properly stablished
```suggestion
	// Required to get the connection properly established.
```
Period at end as well

2024-09-29 14:00 UTC, Faless commented on tests/core/io/test_udp_server.h
> +	OS::get_singleton()->delay_usec(500000);
It's always recommended to `poll` while waiting

2024-10-01 14:08 UTC, Calinou requested changes

2024-10-10 02:34 UTC, pafuent commented
@Calinou I addressed all your comments, Could you please review again this PR?

2024-10-17 18:25 UTC, pafuent commented
Friendly remainder

2024-10-18 05:41 UTC, Faless commented
> Friendly remainder

As mentioned in https://github.com/godotengine/godot/pull/97262#discussion_r1805889374 :

> The problem here is that you keep blocking for a long time and only poll once, while you should only block for brief periods of time and regularly poll (i.e. **multiple times**), or you risk of having the same error on other OS configurations.

2024-11-12 12:40 UTC, pafuent commented
@Calinou I addressed all your comments, Could you please review if I addressed them correctly?

2024-11-22 16:00 UTC, Calinou approved these changes
Looks good to me.

2024-11-22 19:16 UTC, AThousandShips approved these changes, later dismissed

2024-11-22 19:16 UTC, AThousandShips commented on tests/core/io/test_udp_server.h
> +	Ref<PacketPeerUDP> client_from_server = server->take_connection();
```suggestion
Ref<PacketPeerUDP> accept_connection(Ref<UDPServer> &p_server) {
	// Required to get the connection properly established.
	const uint64_t time = OS::get_singleton()->get_ticks_usec();
	while (!p_server->is_connection_available() && (OS::get_singleton()->get_ticks_usec() - time) < MAX_WAIT_USEC) {
		p_server->poll();
		OS::get_singleton()->delay_usec(SLEEP_DURATION);
	}

	CHECK_EQ(p_server->poll(), Error::OK);
	REQUIRE(p_server->is_connection_available());
	Ref<PacketPeerUDP> client_from_server = p_server->take_connection();
```

2024-11-23 11:53 UTC, Faless approved these changes
As discussed with other members, I'm approving the PR, and will make the necessary changes in a separate PR.

2024-11-27 16:53 UTC, merged