Add `srgb_color` shader hint.
godotengine/godot pull request #97801
Opened 2024-10-04 07:38 UTC by basicer

Sometimes shaders want to accept a color as input that is always in the srgb color space.  This adds a hint to vec3/vec4 to enable the color picker popup for those vectors but disable color space conversion.

2024-12-09 18:23 UTC, QbieShay commented
Hey @basicer , can you list usecases for this?

2024-12-09 18:32 UTC, clayjohn commented
@QbieShay This is something that has come up a few times. I thought there was a proposal, but all I can find is https://github.com/godotengine/godot-proposals/issues/2323

Basically, people want to use the color picker, but they want to keep colors in sRGB space. When using the `source_color` hint, Godot will automatically convert the color to linear in 3D shaders and in 2D shaders when using HDR. So we need a hint that tells Godot to use a color picker without giving Godot permission to do color space operations

2024-12-10 15:27 UTC, QbieShay commented
Discussed this in the rendering meeting. It's clear to me now why the feature is wanted, but we discussed a different API:

- Support for `source_color` should be extended to vec3
- This new hint should work together with source color, and just disable the unwanted operation.

For example

```
uniform vec3 albedo_color: source_color // shows color picker, performs conversion
unifomr vec3 albedo_color1:  source_color, disable_color_conversion // shows color picker, but disables extra logic
uniform vec3 albedo_color2: disable_color_conversion // behaves like the previous one
```

This expands using color for vec3 (which is something that we should have already) and add an extra option, allows for compact syntax for advanced users, so everyone should be happy with this solution ^^

2024-12-10 19:34 UTC, QbieShay commented
NOTE: I called it "disable color conversion" but we can find something better. But it should still be clear.

2024-12-14 20:38 UTC, basicer commented
> NOTE: I called it "disable color conversion" but we can find something better. But it should still be clear.

I like it, but its a bit long?  Maybe `no_color_conversion` ?

2024-12-16 00:25 UTC, tetrapod00 commented
Judging by the existing [uniform hints](https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html#uniform-hints) and [render modes](https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/spatial_shader.html#render-modes), the most idiomatic name here is either `color_conversion_disable` or `color_conversion_disabled`.

`color_conversion_disable` matches existing hints more closely, but there is only one existing example: `repeat_disable`.  `color_conversion_disabled` matches the multiple examples of render modes (`cull_disabled`, `depth_test_disabled`, `specular_disabled`, etc.). My preference personally is `color_conversion_disabled`.

The name is a little on the long side, but we already have some verbose hints like `hint_normal_roughness_texture` or `alpha_to_coverage_and_one`, so it's probably fine.

`disable_color_conversion` is not idiomatic because the order is wrong. To use an analogy with properties, idiomatically the "property name" comes first, then the "property value".

2024-12-16 08:10 UTC, Zireael07 commented
@tetrapod00 Might be idiomatic but is too long imo.

2025-01-30 04:28 UTC, clayjohn commented
We discussed again in the rendering meeting and have settled on `color_conversion_disabled` as suggested by tetrapod

2025-03-07 22:54 UTC, Calinou approved these changes
Tested locally, it works as expected. Code looks good to me.

![image](https://github.com/user-attachments/assets/8fd37ff0-261a-44b0-b1b3-397132348593)

If you use `albedo_color1` as an albedo color in 3D (instead of `albedo_color`, it'll look significantly brighter which is expected here.

2025-04-10 17:37 UTC, clayjohn requested changes

2025-04-10 17:37 UTC, clayjohn commented on servers/rendering/shader_language.cpp
> +						options.push_back("color_conversion_disabled");
This is the completion for textures. So color_conversion_disabled shouldn't be included. 

It should be around line 11789

2025-04-10 17:37 UTC, clayjohn commented on servers/rendering/shader_language.cpp
> +bool ShaderLanguage::ShaderLanguage::is_hint_color(ShaderLanguage::ShaderNode::Uniform::Hint p_hint) {
This isn't needed now that color_conversion_disabled can't be used on its own

2025-04-10 17:37 UTC, clayjohn commented on drivers/gles3/storage/material_storage.cpp
> +			} else if ((E.value.type == ShaderLanguage::TYPE_VEC3 || E.value.type == ShaderLanguage::TYPE_VEC4) && E.value.hint == ShaderLanguage::ShaderNode::Uniform::HINT_COLOR_CONVERSION_DISABLED) {
This code won't execute since hint_source_color is always used when color_conversion_disabled is used

2025-04-10 17:37 UTC, clayjohn commented on servers/rendering/renderer_rd/storage_rd/material_storage.cpp
> +			} else if ((E.value.type == ShaderLanguage::TYPE_VEC3 || E.value.type == ShaderLanguage::TYPE_VEC4) && E.value.hint == ShaderLanguage::ShaderNode::Uniform::HINT_COLOR_CONVERSION_DISABLED) {
Same as above, this condition won't be used since source_color will always be used

2025-04-11 04:12 UTC, basicer commented
I'm not sure I follow your comments @clayjohn .

When the parser sees color_conversion_disabled it checks that the existing hint is HINT_SOURCE_COLOR and then replaces it with HINT_COLOR_CONVERSION_DISABLED since there can only be one hint set.  So the conditions do trigger.

2025-04-11 04:25 UTC, clayjohn commented
> I'm not sure I follow your comments @clayjohn .
> 
> When the parser sees color_conversion_disabled it checks that the existing hint is HINT_SOURCE_COLOR and then replaces it with HINT_COLOR_CONVERSION_DISABLED since there can only be one hint set. So the conditions do trigger.

Oh, interesting. I see what you mean. Each hint overwrites the previous one. In cases where multiple hints are valid we have edge case handling. I really don't like that approach, but its not your fault. Its best to stick with the patterns that are there. 

That just leaves my comment about the code completion.

2025-04-11 20:02 UTC, clayjohn approved these changes
Looks great to me! Thank you for your patience

2025-04-11 21:48 UTC, basicer commented
> > I'm not sure I follow your comments @clayjohn .
> > When the parser sees color_conversion_disabled it checks that the existing hint is HINT_SOURCE_COLOR and then replaces it with HINT_COLOR_CONVERSION_DISABLED since there can only be one hint set. So the conditions do trigger.
> 
> Oh, interesting. I see what you mean. Each hint overwrites the previous one. In cases where multiple hints are valid we have edge case handling. I really don't like that approach, but its not your fault. Its best to stick with the patterns that are there.
> 
> That just leaves my comment about the code completion.

Yeah, I don't like it either, but It didn't seem worth refactoring into a bitset or something just for this.

2025-04-15 00:42 UTC, merged

2025-04-15 00:43 UTC, Repiteo commented
Thanks!