Allow seconds snapping to use minimum intervals of 0.0001 once more
godotengine/godot pull request #97833
Opened 2024-10-04 23:06 UTC by AtlaStar

closes #97832, also clears up some of the naming conventions used. Confirmed that entering values when `seconds` is selected where the fractional part is less than 0.0001 floors, while fractional values greater than that are retained. Doesn't revert previous behaviors for FPS, which still clamp to the nearest 1/16.

2024-10-07 00:31 UTC, TokageItLab approved these changes

2024-10-10 21:43 UTC, TokageItLab requested changes
@AtlaStar Don't merge from master, instead you must reset them, interactive rebase and force push to keep it as 1 commit, see [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase)

2024-10-10 21:44 UTC, AtlaStar commented
@TokageItLab dangit, I thought I did a fast-forward merge not a regular merge...

2024-10-10 23:20 UTC, TokageItLab approved these changes

2024-10-14 19:16 UTC, merged

2024-10-14 19:18 UTC, Repiteo commented
Thanks!