EditorResourcePicker: Replace options to load file with button for QuickOpenDialog
godotengine/godot pull request #97860
Opened 2024-10-05 21:59 UTC by stijn-h

![afbeelding](https://github.com/user-attachments/assets/40512e20-f27c-4c02-9b1d-177abd69c0cf)

With the new quick open dialog, I think it is helpful to make it more accessible quickly. 

Currently you have to uncollapse the small button, then find the option to load at the end of a potentially long list of 'New...' options. Then you could choose between quick open, and the regular file dialog. But I don't think the regular file dialog is needed. You can look up the file in the file system dock and drag and drop the resource, or you can search the file with quick open.

Additionally, I had to change some code to handle the separators. Now all separators are added in one method: _update_menu_items. Previously the overridable set_create_options would need to do this to ensure proper separation (this wasn't documented), but it could not know whether more properties were going to be added.

2024-10-06 01:45 UTC, RedMser commented
Is there a proposal for this change? Removing working features (the menu entries in this case) is always something controversial and it needs a good reason and many users agreeing with the choice.

I personally want to keep the regular load dialog since it has thumbnails, don't see why the menu must be changed to add the button.

2024-10-06 07:14 UTC, stijn-h commented
> Is there a proposal for this change?

I added a proposal that answers some of your feedback, I hope.

2024-10-06 10:46 UTC, npinsker commented
I love the addition of the icon, but will mention that I occasionally use the slow-load option, when I can't remember exactly what a file is called, but do remember where it is in my directory tree.

2024-10-06 23:27 UTC, Calinou approved these changes
Tested locally, it works as expected.

My only concern is that the short viewable area for the path will become even shorter with the addition of a new button:

![image](https://github.com/user-attachments/assets/f94ed81d-49d1-4440-9e06-b5f50a1ab744)

I don't know a good solution to this. I'd say the saved click is worth losing some space here, since it's often needed, especially when setting up materials or audio samples.

2024-12-22 14:44 UTC, AThousandShips approved these changes

2024-12-22 14:48 UTC, AThousandShips requested changes

2024-12-22 14:48 UTC, AThousandShips commented on editor/editor_resource_picker.cpp
> +		base_types.push_back(type);
```suggestion
	Vector<StringName> base_types;
	for (String type : base_type.split(",")) {
		base_types.push_back(type);
```
Would be cleaner IMO

2024-12-22 14:48 UTC, AThousandShips approved these changes

2024-12-22 14:49 UTC, AThousandShips commented
(my bad clicked wrong should have been a simple comment)

2024-12-23 17:22 UTC, merged

2024-12-23 17:22 UTC, Repiteo commented
Thanks!

2024-12-24 12:51 UTC, KoBeWi commented
This makes an inconsistency between the buttons.
Arrow button opens the same menu as clicking the resource field, while open button does not appear in the menu.
The menu could be different for arrow button and include load options. But maybe it's fine, idk. I just find this odd.

2025-01-17 20:03 UTC, someThrowAway1900 commented
Can this be a settings option?

The new folder icon is taking up unnecessary horizontal space. Maybe the first icon can be removed and the result shown instead upon selection as a compromise.

![image](https://github.com/user-attachments/assets/d058112f-e21c-41b7-b36a-0995024a4129)

2025-01-17 20:03 UTC, someThrowAway1900 commented
Can this be a settings option?

The new folder icon is taking up unnecessary horizontal space. Maybe the first icon can be removed and the result shown instead upon selection as a compromise.

![image](https://github.com/user-attachments/assets/d058112f-e21c-41b7-b36a-0995024a4129)

2025-01-17 20:17 UTC, clayjohn commented
> This makes an inconsistency between the buttons. Arrow button opens the same menu as clicking the resource field, while open button does not appear in the menu. The menu could be different for arrow button and include load options. But maybe it's fine, idk. I just find this odd.

I also find this very odd. Losing the horizontal space is really frustrating when using textures or meshes (anything visual really) and losing the "load" menu is a huge loss.