Fix Button minimum size.
godotengine/godot pull request #97897
Opened 2024-10-06 17:47 UTC by WhalesState

* Fixes: https://github.com/godotengine/godot/issues/95580
* Fixes: https://github.com/godotengine/godot/issues/97417

This should fix it once and for all.

Instead of using this to update the button correctly

```
_shape()
queue_redraw()
update_minimum_size()
```

`NOTIFICATION_DRAW` will call `_shape()` at the start and `update_minimum_size()` will be called after shaping.

So `queue_redraw()` should be enough when the viewport updates the canvas items or when other notifications calls only `queue_redraw()`.

2024-10-06 17:50 UTC, KoBeWi commented
Updating minimum size in `NOTIFICATION_DRAW` means that the Button's size is undefined until it's drawn for the first time. This can cause various sizing problems with containers.

2024-10-06 17:59 UTC, WhalesState commented
> Updating minimum size in `NOTIFICATION_DRAW` means that the Button's size is undefined until it's drawn for the first time. This can cause various sizing problems with containers.

It's undifined

> Updating minimum size in `NOTIFICATION_DRAW` means that the Button's size is undefined until it's drawn for the first time. This can cause various sizing problems with containers.

We can use `_shape()` inside `get_minimum_size()` similar to how `Label` do, but I couldn't find any issues in editor since everything was fine after this change.

The reason why i have done this is because I have compared both `Label` and `Button` to check what happens when the `font_oversampling` changed, the `Label` is taking care of everything inside the draw notfication.

2024-10-06 18:00 UTC, bruvzg requested changes

2024-10-06 18:00 UTC, bruvzg commented on scene/gui/button.cpp
> +			_shape();
It probably should do something similar to `Label`, and check if shaped text was invalidated by font change (with `shaped_text_is_ready`), and only then call `_shape`.

https://github.com/godotengine/godot/blob/db66bd35af704fe0d83ba9348b8c50a48e51b2ba/scene/gui/label.cpp#L407-L417

2024-10-06 18:00 UTC, bruvzg commented on scene/gui/button.cpp
> +			_shape();
It probably should do something similar to `Label`, and check if shaped text was invalidated by font change (with `shaped_text_is_ready`), and only then call `_shape`.

https://github.com/godotengine/godot/blob/db66bd35af704fe0d83ba9348b8c50a48e51b2ba/scene/gui/label.cpp#L407-L417

2024-10-06 19:39 UTC, bruvzg commented on scene/gui/button.cpp
> +			_shape();
Actually, I completely forgot I did #95511, which do exactly this. Will re-check it tomorrow.

2024-10-06 20:20 UTC, bruvzg commented on scene/gui/button.cpp
> +			_shape();
> Will re-check it tomorrow.

Fixes https://github.com/godotengine/godot/issues/97417 but not https://github.com/godotengine/godot/issues/95580

I guess for #95580 we can add override for `set_disabled` to reshape it.

2024-10-06 20:59 UTC, WhalesState commented on scene/gui/button.cpp
> +			_shape();
I stumbled upon this draft PR and wanted to spark a discussion. To ensure correct updates when `queue_redraw` is called, perhaps we should follow the approach used by Label or explore alternative solutions.

2024-10-06 21:01 UTC, WhalesState commented on scene/gui/button.cpp
> +			_shape();
I will draft this PR, until you check (https://github.com/godotengine/godot/issues/97417).

2024-10-07 15:23 UTC, WhalesState commented
I just have fixed the minimum size when disabled is toggled, since you already have fixed the other issue.

2024-10-08 07:12 UTC, bruvzg approved these changes
Tested with https://github.com/godotengine/godot/issues/95580 scene, seems to be working fine.

2024-10-25 12:08 UTC, KoBeWi commented
Why was this closed?

2024-10-25 12:48 UTC, markdibarry commented
It seems they moved to a different fork project of Godot and closed all of their PRs, so I assume they're up for grabs for anyone who wants to reopen them as a new PR.

2024-10-25 12:55 UTC, KoBeWi commented
Except not all were closed https://github.com/godotengine/godot/pulls/whalesstate 🤔

Some of the closed PRs were already approved and did not require further action. You can still restore the branch and reopen them.

2024-11-11 20:19 UTC, merged

2024-11-11 20:19 UTC, Repiteo commented
Thanks!