Fix `EditorSpinSlider` grapper `TextureRect` doesn't follow parent wh…
godotengine/godot pull request #97946
Opened 2024-10-07 18:35 UTC by WhalesState

* Fixes: https://github.com/godotengine/godot/issues/97825

2024-10-10 22:37 UTC, SaracenOne commented
Hmm, the fix seems mostly fine, but I'm a little concerned about hardcoding the z-value to 1. While I don't think the z-value would change for an EditorSpinSlider, wouldn't it still make more sense to make it something like `grabber->set_z_index(get_z_index() + 1);` so it's always relative?

2024-10-10 22:38 UTC, SaracenOne requested changes

2024-10-10 22:38 UTC, SaracenOne commented on editor/gui/editor_spin_slider.cpp
> +	grabber->set_z_index(1);
I feel like this would make more sense to be `grabber->set_z_index(get_z_index() + 1);` so it's always relative.

2024-10-10 22:57 UTC, SaracenOne approved these changes
My previous feedback was mistaken since all CanvasItems have z_relative set on by default, so this should be fine to merge as is after all 👍

2024-10-25 22:27 UTC, Mickeon commented
This is relatively simple and easy to salvage, too.

2024-11-11 19:49 UTC, KoBeWi approved these changes

2024-11-12 15:36 UTC, merged

2024-11-12 15:36 UTC, Repiteo commented
Thanks!