Fix PWA callback assignment causing crash in sandboxed iframes
godotengine/godot pull request #98069
Opened 2024-10-10 18:36 UTC by thedinosoar

Pull Request: Fix Service Worker Error in Sandboxed Iframe (#98068)
# Summary

This PR addresses the issue where the service worker callback fails in a sandboxed iframe, preventing the execution of Godot web builds. The solution introduces error handling for the service worker registration process, ensuring that any SecurityError or other exceptions are caught and logged appropriately without breaking the application.
Changes Made

- Error Handling: Wrapped the service worker registration calls in try-catch blocks to gracefully handle potential errors.
  - In the `godot_js_pwa_cb` function:
            Implemented a try-catch to manage errors during the assignment of the PWA callback. This prevents the application from crashing and logs any failures to the console.
  - In the `godot_js_pwa_update` function:
            Added a try-catch block around the service worker update logic to catch any errors and log them appropriately.
            
### Testing

Tested using https://github.com/thedinosoar/godot-iframe-test.git

2024-10-19 03:31 UTC, Faless requested changes
We should also update the `installServiceWorker` function in `platform/web/js/engine/engine.js` and the `navigator.serviceWorker` access from `misc/dist/html/full-size.html` and `misc/dist/html/editor.html` to properly cover all cases where this error can occur.

2024-10-19 03:31 UTC, Faless commented on platform/web/js/libs/library_godot_os.js
> +		request_quit: function () { },
```suggestion
		request_quit: function () {},
```

2024-10-19 03:31 UTC, Faless commented on platform/web/js/libs/library_godot_os.js
> +				console.error('Failed to assign PWA callback', e); // eslint-disable-line no-console
```suggestion
				GodotRuntime.error('Failed to assign PWA callback', e);
```

2024-10-19 03:31 UTC, Faless commented on platform/web/js/libs/library_godot_os.js
> +				console.error(e); // eslint-disable-line no-console
```suggestion
				GodotRuntime.error(e);
```

2024-10-19 07:24 UTC, thedinosoar commented
> We should also update the `installServiceWorker` function in `platform/web/js/engine/engine.js` and the `navigator.serviceWorker` access from `misc/dist/html/full-size.html` and `misc/dist/html/editor.html` to properly cover all cases where this error can occur.

I thought about updating those as well, but aren't those only called if the app is a pwa? Which would mean these functions I am updating would have needed to be successfully called before those do.

2024-10-19 09:39 UTC, Faless commented
> Which would mean these functions I am updating would have needed to be successfully called before those do.

Those functions are only called if the export is a threaded build, and the relevant headers are missing, so you probably didn't notice them.



> Also inside full-size.html, navigator.serviceWorker is inside of a promise which already catches any errors that would be thrown

Not it isn't, it's inside an array constructor, which is evaluated before the promise gets created. You can easily test that with the following snippet (which you'll notice will throw the error even if the resulting promise has a catch):

```
var opt = null; Promise.race([opt.lol]).catch(e => {/* noop */})
```

2024-10-19 11:20 UTC, thedinosoar commented
> Not it isn't, it's inside an array constructor, which is evaluated before the promise gets created. You can easily test that with the following snippet (which you'll notice will throw the error even if the resulting promise has a catch):
> 

Ahh I see that now, I will fix that. I appreciate the constructive feedback!

2024-10-22 23:28 UTC, adamscott commented
I don't understand how it can be an issue when we explicitly test if `serviceWorker` is in `navigator`.

```js
if ('serviceWorker' in navigator) {
}
```

2024-10-22 23:31 UTC, thedinosoar commented
> I don't understand how it can be an issue when we explicitly test if `serviceWorker` is in `navigator`.

The issue isn't that 'serviceWorker' is not in navigator, it's that you cannot access it outside of a secure context (like a sandboxed iframe). The issue #98068 details that

2024-10-22 23:43 UTC, adamscott approved these changes
Looks good!

2024-11-25 10:14 UTC, Faless approved these changes
LGTM

2024-11-25 19:27 UTC, merged

2024-11-25 19:27 UTC, Repiteo commented
Thanks! Congratulations on your first merged contribution! 🎉