Static analysis wunused variable
godotengine/godot pull request #98394
Opened 2024-10-21 19:41 UTC by sondredl

2024-10-21 20:08 UTC, AThousandShips requested changes

2024-10-21 20:08 UTC, AThousandShips commented on editor/plugins/editor_plugin.h
> -		ERR_FAIL_INDEX_V(p_idx, creation_func_count, nullptr);
These are valid and important checks, please restore

2024-10-21 20:08 UTC, AThousandShips commented on editor/plugins/editor_plugin.h
> +		(creation_func_count >= MAX_CREATE_FUNCS);
This one too

2024-10-21 20:08 UTC, AThousandShips commented on editor/debugger/debug_adapter/debug_adapter_types.h
> +		(path.is_empty());
This is also invalid, please restore

2024-10-21 20:33 UTC, sondredl commented
> Thank you for your contribution!
> 
> Please explain what this PR is intended to achieve, it makes a lot of changes that are against our code style norms and removes several actually important error checks that shouldn't be removed, we enforce using _both_ `virtual` and `override` for readability
> 
> These are very different changes and should (if they are valid in the first place) be made in separate PRs as they are completely unrelated
> 
> But this is something that should be discussed before making these changes, so please join our [developer chat](https://chat.godotengine.org/) and ask about these things

did nit realize i was making this pull request to the main repo. Im using the godot code base to experiment with static analysis tooling. Thanks for quick feedback! will close the pull request

2024-10-21 20:33 UTC, closed without merging

2024-10-26 22:56 UTC, Calinou commented
- Superseded by https://github.com/godotengine/godot/pull/98564.