Avoid infinite recursion between AnimationPlayer and AnimationMixer
godotengine/godot pull request #98704
Opened 2024-10-31 16:35 UTC by matheusmdx

In theory `AnimationPlayer.current_animation` shouldn't be setted directly but in normal cases that don't cause any problem unless the animation key set `current_animation` to an empty string, in this case will start an infinite recursion between `AnimationPlayer` calling `AnimationMixer::_blend_process` and `AnimationMixer` setting the current animation to a empty string which will never stop until the engine crashes. This fix makes `AnimationMixer` ignore these animation keys (that would do nothing anyways) and avoid the crash.

Fix: #98076

2024-11-01 17:30 UTC, TokageItLab approved these changes
I believe this is a clean way of fixing the issue.

I do have one concern. Looking at the summary of the issue https://github.com/godotengine/godot/issues/98076, does it only occur with an empty character and not when `“[stop]”` is set? If we can confirm that, I think this can be merged.

2024-11-01 17:51 UTC, matheusmdx commented
Indeed the `["stop"]` also triggers the issue, updated again and now i think is ready to merge

2024-11-01 18:03 UTC, matheusmdx commented on scene/animation/animation_player.cpp
> +	if (p_animation == "[stop]" || p_animation.is_empty()) {
Done

2024-11-01 19:02 UTC, TokageItLab requested changes
> Indeed the ["stop"] also triggers the issue

In that case, we need to think about a different approach. This is because a set of `"[stop]"` could be called from the inspector.

BTW, is it a problem if stop() is called in a method track? How about a different approach, such as deleting the cache inside stop() deferred?

2024-11-01 19:25 UTC, matheusmdx commented
> BTW, is it a problem if stop() is called in a method track?

Nothing happens, no crash but also the animation don't stop.

2024-11-05 14:08 UTC, matheusmdx commented
> How about a different approach, such as calling clear_cache() with deferred inside stop()?

I tried that and seems to have no effect to avoid the crash.

<br>

Another alternative could be change `current_animation` from `PROPERTY_USAGE_EDITOR` to `PROPERTY_USAGE_NONE`, so that property won't appear in the "Select Property" window

2026-02-23 18:08 UTC, Repiteo commented
Superseded by #116264; thanks for your contribution!

2026-02-23 18:08 UTC, closed without merging