Reload cached resources in runtime on file reimport
godotengine/godot pull request #98710
Opened 2024-10-31 21:26 UTC by YeldhamDev

Fixes #93629.

**Sponsored By:** 🐺 Lone Wolf Technology / 🍀 W4 Games.

2024-11-01 21:13 UTC, clayjohn approved these changes
The code looks good to me. But this should also get an approval from someone with more debugger knowledge

2024-11-05 09:01 UTC, Faless requested changes
Looks good overall, see my comment about the EditorFileSystem check.

I wonder if we should put the `reload_cached_files` behind the `live_debug` flag (i.e. synchronize scene changes), and thus also rename the message to `live_reload_cached_files` and move handling to the live editor.

2024-11-05 13:51 UTC, YeldhamDev commented on editor/debugger/script_editor_debugger.cpp
> +	}
I added that because further up there was also a check for this, so I just wanted to be sure. Removed.

2024-11-05 14:08 UTC, YeldhamDev commented
> I wonder if we should put the `reload_cached_files` behind the `live_debug` flag (i.e. synchronize scene changes), and thus also rename the message to `live_reload_cached_files` and move handling to the live editor.

I thought about that, but decided against it because that's not really a "scene change", and more of an asset data modification.

2024-11-06 16:30 UTC, Faless approved these changes
LGTM

2024-11-10 18:19 UTC, merged

2024-11-10 18:20 UTC, Repiteo commented
Thanks!