Add warning in scene tree when nested CanvasItems try to clip children
godotengine/godot pull request #98949
Opened 2024-11-08 05:57 UTC by Meorge

This PR provides a partial solution to https://github.com/godotengine/godot-proposals/issues/11113 by displaying a configuration warning in the scene tree when a CanvasItem attempting to clip its children has an ancestor CanvasItem that also clips its children:

![CleanShot 2024-11-07 at 21 19 58@2x](https://github.com/user-attachments/assets/734492e9-3e5f-4592-887e-6ff10343bda2)

> [!WARNING]
> The warning notably appears on the child node attempting to clip, not on the parent that is successfully(?) clipping. This does mean that if there is a scene instance that contains within it a clipping node, the error may still be invisible to the user:
> 
> ![CleanShot 2024-11-07 at 21 48 54@2x](https://github.com/user-attachments/assets/13717098-a7dc-4a8b-90e5-a6da4e3312ea)
> 
> Placing a warning on the parent node would fix this, but it would also require each parent to do a recursive walk of its descendants in the best (and hopefully usual) case of no nested clipping. I feel like the performance penalty that this would incur would be a bit too much.

A fair number of files had to be modified so that this PR worked for all of those classes that inherited from CanvasItem; previously, their `get_configuration_warnings` methods assumed that the relevant superclass for them to call was Node, but since this PR adds `get_configuration_warnings` to CanvasLayer, which is in between them and Node, they had to be updated.

2024-11-08 09:42 UTC, AThousandShips commented
> A fair number of files had to be modified so that this PR worked for all of those classes that inherited from CanvasItem; previously, their get_configuration_warnings methods assumed that the relevant superclass for them to call was Node, but since this PR adds get_configuration_warnings to CanvasLayer, which is in between them and Node, they had to be updated.

You are *very* far behind in your branch, that was fixed two months ago in:
* #93353

2024-11-08 09:44 UTC, AThousandShips commented on scene/2d/physics/physical_bone_2d.cpp
> +	PackedStringArray warnings = Node2D::get_configuration_warnings();
Also this is wrong, though that will be fixed by just rebasing and removing all these changes

2024-11-08 09:46 UTC, AThousandShips commented on scene/main/canvas_item.h
> +	PackedStringArray get_configuration_warnings() const override;
```suggestion
	virtual PackedStringArray get_configuration_warnings() const override;
```

2024-11-08 15:41 UTC, Meorge commented
> You are very far behind in your branch, that was fixed two months ago

Oops, that made me realize that while I've been making sure to *fetch* my local repo, it's just been my (now very outdated) fork and not the official Godot repo that I've been branching off of. 😅 Thanks for catching that - I'll sync my fork and then see if I can rebase the necessary changes over to it! If not, I'll close this PR, copy my changes over to a new branch off the modern master branch, and resubmit the PR.

2024-11-09 04:13 UTC, clayjohn requested changes
This looks good to me. But this should be adjusted to also check for CanvasGroups which use the same clipping feature internally. Therefore CanvasGroups can't be children of nodes with clip_children and nodes with clip_children can't be children of CanvasGroups

2024-11-09 06:07 UTC, Meorge commented
Thanks, I've added a warning for that as well! It continues moving up the tree until both warnings have been triggered, so that if someone happens to meet both conditions, they are aware of both instead of thinking that there was only one they needed to satisfy.

It did get me wondering, though - do CanvasGroups behave incorrectly if they are children of a clipping node or another CanvasGroup, and if so, should warnings for those cases also be added to this PR?

2024-11-10 03:59 UTC, Meorge commented
Warnings have been added for:
- CanvasItems, when an ancestor is a CanvasGroup
- CanvasGroups, when an ancestor is either a CanvasGroup or clips its children

![CleanShot 2024-11-09 at 19 55 09@2x](https://github.com/user-attachments/assets/d06dba77-62df-4c39-9817-d2f12254191f)

2024-12-09 01:18 UTC, Calinou reviewed
Tested locally, it works as expected.

I suggest displaying the node name in the warning though, as nested scenarios can get confusing with multiple warnings:

![image](https://github.com/user-attachments/assets/43b9f587-b21d-4809-a47d-e17c53f4eb13)

*All nodes other than the root node have **Clip Children** set to **Clip + Draw**.*

### Warnings on Two

![image](https://github.com/user-attachments/assets/87095d19-7037-41d9-8792-e012c46f0b85)

### Warnings on Three

![image](https://github.com/user-attachments/assets/875ba6d1-372b-46cf-8efe-62078ef6af74)

2024-12-09 05:27 UTC, Meorge commented
@Calinou Thanks for testing! I've added the name of the detected ancestor node to the warnings.

With your setup:

![CleanShot 2024-12-08 at 21 19 46@2x](https://github.com/user-attachments/assets/0df3a38c-98de-44ee-a966-f10476c91573)


### Warnings on Two
![CleanShot 2024-12-08 at 21 20 00@2x](https://github.com/user-attachments/assets/f97037e1-f6f1-4daf-a644-a5395c9f6c0a)


### Warnings on Three
![CleanShot 2024-12-08 at 21 20 09@2x](https://github.com/user-attachments/assets/cd19dc19-6000-4a2e-bf5d-2446d91077f7)

2025-03-25 17:23 UTC, Calinou approved these changes
Code looks good to me.

2025-03-28 13:39 UTC, merged

2025-03-28 13:45 UTC, akien-mga commented
Thanks!