Fix animation snapping in seconds mode for 4.3
godotengine/godot pull request #99058
Opened 2024-11-11 09:46 UTC by UnfavorableEnhancer

Closes #98609 for 4.3 branch as TokageItLab suggested to do

Fixes animation snapping rounding to weird values in seconds mode + fixes holding shift not lowering snap value as intended.

2024-11-11 09:49 UTC, TokageItLab approved these changes

2024-11-11 09:53 UTC, TokageItLab requested changes

2024-11-11 09:53 UTC, TokageItLab commented on editor/animation_track_editor.cpp
> +
```suggestion
```

2024-11-11 10:03 UTC, TokageItLab approved these changes
Please fixup this PR into one commit to follow [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase).

2024-11-11 10:20 UTC, UnfavorableEnhancer commented
Fixed-up into single commit

2024-11-11 14:24 UTC, AThousandShips commented
Is there any specific reason this is done in 4.3 only? Is a separate fix planned for 4.4?

2024-11-15 18:13 UTC, merged

2024-11-15 18:13 UTC, akien-mga commented
Thanks!