Fix crash when inserting keyframes with empty properties array
godotengine/godot pull request #99148
Opened 2024-11-12 21:50 UTC by TopherBriggs

# Fix crash when inserting keyframes with empty properties array

Fixes #98751 (Crash when inserting rotation keyframe)

## Description

When inserting rotation keyframes in the animation editor, clicking on the keyframe would cause the editor to crash due to an Array out-of-bound error. Upon further inspection using coredumpctl it seems to be crashing from a out-of-bounds index on editor_inspector.cpp:2727, with accessing `F.properties[0]` without checking if the properties array is empty could cause a crash. This is accessed to see if the property is in the favorites list. However, if an element such as AnimationTrackKeyEdit does not have any properties that can be favorited. This PR adds a safety check to prevent accessing an empty array.

## Modified Files

- `editor/editor_inspector.cpp`

## PR Checklist

- [x] Code follows Godot's style guide
- [x] Added safety check for array access
- [x] Tested the fix with the provided reproduction case
- [x] No new compiler warnings

## Changes

The following changes prevent the crash by adding an empty check before accessing the properties array:

```cpp
EditorProperty ***ep = Object::cast_to<EditorProperty>(F.property_editor);
- if (ep && current_favorites.has(F.properties[0])) {
+ if (ep && !F.properties.is_empty() && current_favorites.has(F.properties[0])) {
    ep->favorited = true;
    favorites_vbox->add_child(F.property_editor);
} else {
    current_vbox->add_child(F.property_editor);
}
```

## Testing

Tested with the provided reproduction case:
1. Imported the FBX model from the reproduction case
2. Created a new inherited scene
3. Added animation track as child to Skeleton3D
4. Created new animation
5. Added upper_arm.L and upper_arm.R rotation to track
6. Successfully inserted keyframe without crash

Tested on:
- Godot v4.4.dev
- Arch Linux x86_64 GNOME 47.1 Kernel: 6.11.6-arch1-1
- CPU: 12th Gen Intel i7-1260P (16) @ 4.700GHz 
- GPU: Intel Alder Lake-P GT2 [Iris Xe Graphics]

## Notes

The crash occurred because the properties array could be empty when attempting to insert certain types of keyframes in the animation editor. This fix ensures we check for empty arrays before accessing their elements, following proper array bounds checking practices.

2024-11-13 11:36 UTC, TokageItLab commented
Can you provide a video capture of the detailed reproduction procedure for https://github.com/godotengine/godot/issues/98751 first? Since the crash does not occur in my environment.

Also, the code you are trying to fix has been no longer exist in master. So check again if the problem occurs on the latest master branch.

2024-11-13 11:41 UTC, TokageItLab requested changes

2024-11-13 11:41 UTC, TokageItLab commented on editor/editor_inspector.cpp
> +		if (ep && !F.properties.is_empty() &&current_favorites.has(F.properties[0])) {
```suggestion
		if (ep && !F.properties.is_empty() && current_favorites.has(F.properties[0])) {
```

2024-11-13 16:55 UTC, fire approved these changes
The logic to check for empty properties to avoid the crash makes sense. Also, the crash has been confirmed. Thirdly, I don't see how it will break the code even if it's wrong, so the risk of merging is low and the benefit of fixing a crash is high.

2024-11-13 17:00 UTC, TopherBriggs commented
Here's the video capture of the crash reported by #98751 replicated on my machine:

https://github.com/user-attachments/assets/bb98a0ad-dcb0-4fb1-b8f4-d54835bbd6a5

With the change in this PR the crash no longer occurs:

https://github.com/user-attachments/assets/dd0da419-215a-4ec2-bf83-9d9421b34961

I also added the requested formatting change

2024-11-13 17:01 UTC, AThousandShips commented
Need to confirm that the 4.3 crash is related so unlocking the issue until we can confirm a dedicated 4.3 version fixes this as the code is different

2024-11-13 20:56 UTC, TokageItLab approved these changes
I cannot reproduce the crash in my environment when I perform the same operation as in the video, so it may be an environment-dependent issue.

What I am concerned about is that this fix is not directly related to the animation, but is a check on the processing timing of the inspector plugin.

Considering that the inspector is displayed correctly after the fix, is it possible that the inspector plugin is being called multiple times and somewhere along the way null accesses are occurring? I think we need to take a closer look at why the property is missing there.

Well, as fire's comment says, it should be a safe change, so I'm fine with merging it to prevent crashes for now.

2024-11-15 10:06 UTC, akien-mga commented
I think #98751 was wrongly flagged as being the issue this solves, though I need to see if I can reproduce it to confirm.

This seems to be solving a very recent regression in `master` which is tracked in #99249. This one is reproducible for me in latest `master` but not 4.4-dev4 or 4.3-stable, and fixed by this PR.

2024-11-15 10:20 UTC, akien-mga approved these changes

2024-11-15 11:29 UTC, akien-mga commented
Confirmed to be fixed a bug introduced by #97415 so it's not fixing #98751.

2024-11-15 16:46 UTC, merged