Update spirv cross
godotengine/godot pull request #99214
Opened 2024-11-14 06:22 UTC by tygyh

I've recently added some assertions to spirv-cross to prove it is not vulnerable to overreads/overwrites in two of its functions and want to include them here to prove the safety of Godot too.

2024-11-14 06:28 UTC, clayjohn commented
It looks like you accidentally included some unrelated changes

2024-11-14 06:54 UTC, tygyh commented
> It looks like you accidentally included some unrelated changes

At first I was only going to include the relevant rows, but I thought it would be better to include everything which had changed since its changes was last updated in godot.

2024-11-14 06:56 UTC, tygyh commented
> What about files listed in `thirdparty/README.md` as intentionally not included like `*hlsl` files?

I mostly updated the pre-existing files and didn't include new ones since I saw not all of the files from that repo being in the thirdparty folder.

2024-11-14 06:59 UTC, dustdfg commented
> > What about files listed in `thirdparty/README.md` as intentionally not included like `*hlsl` files?
> 
> I mostly updated the pre-existing files and didn't include new ones since I saw not all of the files from that repo being in the thirdparty folder.

Looks like you accidentally did something like `git commit -a` or `git add .` because your PR definetely includes those new files
![screen-1731567559](https://github.com/user-attachments/assets/9af5567e-f581-48c2-9f9a-058baaecb6fd)

2024-11-14 07:16 UTC, dustdfg commented
And please also update `thirdparty/README.md` file

2024-11-14 07:22 UTC, dustdfg commented
It is update to a newer version from upstream? If yes, so please also update `thirdparty/README.md` to a newer commit

2024-11-14 07:37 UTC, dustdfg requested changes

2024-11-14 07:37 UTC, dustdfg commented on thirdparty/README.md
> +- Version: main (9040e0d25dc545a6d725276bdbd0362791c81f14, 2024)
To be consistent with other entries in README use `git` instead of `main`

2024-11-14 08:19 UTC, dustdfg reviewed
Now from perspective of managing thirdparties everything is good (at least all the points I was introduced to). Now wait while your PR will be reviewed by those who is competent in areas of actual changes. (rendering, shaders I assume)

2025-03-05 17:15 UTC, tygyh commented
Superseded by #99820

2025-03-05 17:15 UTC, closed without merging