Fix regression in SSS with reverse-z
godotengine/godot pull request #99220
Opened 2024-11-14 10:04 UTC by Flarkk

This PR fixes how the SSS shader fetches depth from the now remapped and z-reverse depth buffer.
It seems like SSS was missed in the original reverse-z implementation #88328.

The change is very subtle, so I had to set the depth scale to `1.0` in the settings to make it obvious in the screenshots below (`rendering/environment/subsurface_scattering/subsurface_scattering_depth_scale`).

Note that the depth value is not used in orthographic mode, hence no difference.

I also took this opportunity to rewrite the depth reconstruction code in a less convoluted way. It should allow easier maintenance in the future.

| | 4.2.1 (before reverse-z) | 4.3 (after reverse-z) | With this PR |
| - |---|---|---|
| Perspective | ![Capture d’écran du 2024-11-14 10-13-32](https://github.com/user-attachments/assets/0d9405da-2e3e-4050-89cd-03f610ce9864) | ![Capture d’écran du 2024-11-14 10-16-48](https://github.com/user-attachments/assets/d4d5f674-de81-46d3-8a85-a7b60de8138a) | ![Capture d’écran du 2024-11-14 10-14-37](https://github.com/user-attachments/assets/535e5eb0-cd53-4e2e-b4f5-333e19079861) |
| Orthographic | ![Capture d’écran du 2024-11-14 10-22-15](https://github.com/user-attachments/assets/e120663d-fcb8-4216-a79d-f1da294c7dfb) |![Capture d’écran du 2024-11-14 10-22-15](https://github.com/user-attachments/assets/ef7ce51e-6aba-418f-ae73-ee32b9a173aa)  |![Capture d’écran du 2024-11-14 10-20-51](https://github.com/user-attachments/assets/5c70d549-8bfd-4429-bba4-7ff4ea6a4d28) |

2024-11-14 12:18 UTC, akien-mga commented
Could you amend the commit message to remove the "This reverts commit dd74865f0e6d860932f6c084bceb92ab6d6c6103." line?
This seems to be something that was specific to your work branch, this commit doesn't exist upstream and this is not a revert commit.

2024-11-14 12:27 UTC, Flarkk commented
Thanks @akien-mga !
Done. Indeed I cherry-picked this fix from another local branch I'm working on and overlooked the commit message. Sorry for this !

2024-11-24 18:49 UTC, clayjohn requested changes
I would simplify this and just do the same change we did for every other shader that reconstructs depth. You can fix this issue with some very minor shader changes. Take a look at `servers/rendering/renderer_rd/shaders/effects/bokeh_dof.glsl` for example, it was modified in the reverse z [PR](https://github.com/godotengine/godot/pull/88328/files#diff-7b85f2f3ab83e69975bb9ae1c62b226b11609e59151db75504a62e44fcbe9d6b)

Overall, I prefer that all the screen space effects use the same code so that we can fix them all at the same time when they need to be fixed.

2024-11-24 19:33 UTC, Flarkk commented
Makes sense to have same code everywhere.

I would suggest instead to move to the depth reconstruction code of this PR, for all other effects.

The reason is it doesn't depend on any camera value extraction method (`get_zfar()`, `is_orthogonal()`, etc...) which can break under certain conditions (e.g. when zfar is much bigger than znear, the projection matrix becomes infinite and it's not possible to retrieve zfar anymore).

This is related to the work I'm doing on supporting a wider range of zfar / znear values especially with single precision.

What I can propose to separate the concerns is twofold : 
- simplify this PR as you suggested
- open a separate PR to change the depth reconstruction code everywhere. I almost completed this work locally and can push something quite soon

How does it sound ?

2024-11-25 00:26 UTC, clayjohn commented
> What I can propose to separate the concerns is twofold :
> 
> - simplify this PR as you suggested
> - open a separate PR to change the depth reconstruction code in all screen space effects. I almost completed this work locally and can push something quite soon
> 
> How does it sound ?

That sounds great!

2024-11-26 09:56 UTC, Flarkk commented
Done for the this PR simplification

2024-11-27 02:00 UTC, clayjohn approved these changes
Looks great!

2024-11-27 13:01 UTC, Flarkk commented
The separate PR to change the depth reconstruction code in all effects is here : #99755

2024-11-27 16:53 UTC, merged

2024-11-27 16:54 UTC, Repiteo commented
Thanks!