Support uid:// in more places
godotengine/godot pull request #99286
Opened 2024-11-15 15:16 UTC by KoBeWi

![image](https://github.com/user-attachments/assets/8df7e04c-b81c-4006-9314-3056736006eb)
Adds `uid://` support for Image, FileAccess and ProjectSettings.

Fixes #99221
Supersedes #99278

2024-11-15 15:40 UTC, syntaxerror247 approved these changes
This resolves my issue and seems to be a better solution, as it eliminates the need for manual conversions everywhere.

2024-11-15 18:38 UTC, reduz approved these changes
I guess at the end of the day, best solution is simplest solution

2024-11-16 05:01 UTC, syntaxerror247 commented
I got another issue now. It works on my PC but boot splash loading fails when I run my app on android.

![image](https://github.com/user-attachments/assets/8ad87f61-5c08-4361-a32b-2e344069118f)

2024-11-16 10:17 UTC, AThousandShips approved these changes

2024-11-16 10:17 UTC, AThousandShips commented on core/io/file_access.cpp
> +	// Helper used by file accesses that use a single filesystem
```suggestion
	// Helper used by file accesses that use a single filesystem.
```

2024-11-16 15:33 UTC, syntaxerror247 requested changes
In addition to the issue mentioned in my above comment, I'm also not able to create a gradle build for android. During export, I am getting these errors 👇
![image](https://github.com/user-attachments/assets/4d6bc6b3-a5d9-440e-b127-592c60954ee5)

2024-11-16 18:51 UTC, KoBeWi commented
@syntaxerror247 Please check again.

2024-11-16 19:33 UTC, syntaxerror247 commented
@KoBeWi Still same error with gradle export. Boot splash doesn't throw error now but icon is still not visible.

2024-11-16 20:43 UTC, KoBeWi commented
> Boot splash doesn't throw error now but icon is still not visible.

Eh, I'm not sure if it's related to UIDs anymore. The error you posted clearly says that res:// file is missing.

I can't locate where the gradle error comes from.

2024-11-17 09:00 UTC, syntaxerror247 commented
I’m still confident this issue is related to UIDs. Today, I compiled the engine with and without your PR. The boot splash error occurs in both variants, but in the latter, I can workaround it by setting the boot splash logo using 4.4 dev4 and then export with my custom build. This strongly suggests that the issue is related to UIDs.

> I can't locate where the gradle error comes from.
I think I have an idea of where this might be coming from. I’ll investigate further.

2024-11-17 11:43 UTC, syntaxerror247 commented
@KoBeWi I've fixed both issues in my fork, building on your work. I'll create a PR to supersede this one.

2024-11-17 16:23 UTC, KoBeWi commented
@syntaxerror247 I don't see why your PR would supersede mine, just remove the changes except Android ones. This PR was already reviewed and approved, so it can be merged right now.

2024-11-17 16:29 UTC, syntaxerror247 commented
@KoBeWi I wasn't sure what to do, would it be possible to include my changes in this PR?

2024-11-18 15:29 UTC, merged

2024-11-18 15:30 UTC, Repiteo commented
Thanks!

2024-11-26 00:09 UTC, KoBeWi commented
No.