Fix incorrect Z direction for AABB's position
godotengine/godot pull request #99352
Opened 2024-11-17 10:54 UTC by Mickeon

Fixes https://github.com/godotengine/godot-docs/issues/9598

Comes from https://github.com/godotengine/godot/pull/87114 (oops)

2024-11-17 13:39 UTC, Flarkk commented on doc/classes/AABB.xml
> +			The origin point. This is usually the corner on the bottom-left and forward of the bounding box.
Would `front` be clearer here ?

2024-11-22 14:40 UTC, AThousandShips approved these changes
LGTM, as far as I can tell the changes to fix the incorrect directions are correct (with my correction) and I think the word choice is good

2024-11-22 15:33 UTC, aaronfranke reviewed
Please be mindful of the precise terminology. As of Godot 4.1 we have separate concepts of forward/back direction and front/rear sides (Vector3 `MODEL_*` constants). We need to pick one of these wordings and use it consistently:

* Forward -Z and back +Z.
* Front +Z and rear -Z.

However, we should consider just mentioning directly that position is in the negative corner, -X -Y -Z, and end is in the positive corner, +X +Y +Z.

2024-11-22 18:13 UTC, aaronfranke requested changes

2024-11-22 18:13 UTC, aaronfranke commented on doc/classes/AABB.xml
> +			[b]Note:[/b] It's recommended setting the width, height, and depth to non-negative values. This is because most methods in Godot assume that the [member position] is the bottom-left-front corner,
As I mentioned in my comment we shouldn't use front/back, we should either use forward/back or front/rear.

2024-11-22 19:23 UTC, aaronfranke commented on doc/classes/AABB.xml
> +				Returns [code]true[/code] if the bounding box contains the given [param point]. By convention, points exactly on the right, top, and forward sides are [b]not[/b] included.
This is inconsistent with the rest of this PR.

2024-11-22 19:41 UTC, aaronfranke approved these changes

2024-11-22 21:03 UTC, merged

2024-11-22 21:03 UTC, Repiteo commented
Thanks!