ColorPicker: add a intensity slider in raw mode for HDR
godotengine/godot pull request #99366
Opened 2024-11-17 18:32 UTC by beicause

Add a intensity slider and reduce the max value of RGB to 1.0 in ColorPicker raw mode.
Keep the hex LineEdit always visiable and switch it to code if RGB exceeds the valid range.

<img src=https://github.com/user-attachments/assets/f60a5c49-95dc-4a8f-9aa8-3612b3c0b618 height=350>

Resolve: https://github.com/godotengine/godot-proposals/issues/1031

2024-11-17 21:44 UTC, fire reviewed
I support colour intensity (hdr), but we want to consult the rendering team and reduz since they vetoed the change during the colour picker rework.

2024-11-19 16:30 UTC, QbieShay commented
What change was veto'd? I see no harm in an intensity slider. I would see harm in adding an intensity field in Color, but that's not what this PR does

2024-11-19 16:36 UTC, Calinou commented
The way it's exposed in this PR seems less risky than what https://github.com/godotengine/godot-proposals/issues/1031 originally envisioned, since it's only available in RAW mode and does not impact the RGB/HSV modes in any way.

The downside is that you can't use HSV editing while having an HDR intensity slider on the same page, but you can switch to RAW mode after editing your HSL color and use the intensity slider there.

2024-11-19 18:49 UTC, Calinou requested changes
Tested locally, I noticed some issues:

- Switching to RAW mode increases the dialog's height, which can cause the bottom of the dialog to be unreachable if it spawns at the bottom of a window:

https://github.com/user-attachments/assets/84e545a0-d7a1-4269-bcb2-b28e3d57ad0b

- The icon when the color is overbright doesn't display correctly in the running project:

![Screenshot_20241119_194447](https://github.com/user-attachments/assets/65684f06-7a3e-4087-bacf-16fac25e2cc7)

In contrast, it displays correctly in the editor:

![image](https://github.com/user-attachments/assets/5ec88c45-8392-4295-b1f6-07fb973d9f74)

- Switching to the OKHSL Circle picker will result in broken rendering if you were in the RAW mode and intensity is over 1 (this isn't a new issue IIRC, but it's easier to achieve now):

![Screenshot_20241119_194624](https://github.com/user-attachments/assets/5fb06a00-d7cf-49f6-a7f6-226cb2a0a179)

2024-11-20 12:09 UTC, beicause commented
>Switching to RAW mode increases the dialog's height, which can cause the bottom of the dialog to be unreachable if it spawns at the bottom of a window:

I think it's acceptable, clicking "Swatches" or "Recent colors" increases the dialog's height as well.

>The icon when the color is overbright doesn't display correctly in the running project:

I have fixed it in the running project. However, in editor the 2d screen it still can't display correctly, for which I don't have a solution at the moment.

>Switching to the OKHSL Circle picker will result in broken rendering if you were in the RAW mode and intensity is over 1 (this isn't a new issue IIRC, but it's easier to achieve now):

It seems due to the incorrect value of HSV.  #99461 should fix it.

2024-11-20 12:50 UTC, Calinou commented
The color picker can have its hex/code toggle button permanently locked if you raise the intensity above 1 and lower it below 1. Closing and reopening the ColorPicker doesn't fix the issue, you need to reopen the scene:

![image](https://github.com/user-attachments/assets/289f9a18-d0cf-4cf2-ab5e-647498f85870)

https://github.com/user-attachments/assets/dff158d2-9ff4-4cf2-803f-05ea1fb75271

2024-11-22 15:36 UTC, Calinou commented
The button to switch between hexadecimal and code works now, but the button becomes invisible once you switch to code (it's still clickable):

![image](https://github.com/user-attachments/assets/0ae8fb5f-0056-458e-b4b9-25ac7ec5b0f2)

2024-11-25 04:39 UTC, beicause commented
>The button to switch between hexadecimal and code works now, but the button becomes invisible once you switch to code (it's still clickable):

It's as expected, because the "Script" icon is only available in the editor. To make it available at runtime, we may add a theme property for it and move the "Script" icon to the default theme. I don't know if it's worth. Originally, this button is only enabled in the editor.

2024-12-31 12:37 UTC, beicause commented
I have added theme property for the "script" icon and fix the issue.

2025-03-04 16:23 UTC, beicause commented
I'm still interested in this. It just helps me a lot to set overbright colors.

2025-03-04 16:56 UTC, closed without merging

2025-03-04 17:25 UTC, fire commented
I still think this is salvageable.

2025-03-04 17:30 UTC, beicause commented
I accidentally closed it, and the reopen button is disabled 😅

2025-03-04 17:30 UTC, beicause commented
ok

2025-03-04 18:11 UTC, Calinou commented
- Superseded by https://github.com/godotengine/godot/pull/103583.