Implement VisualShader Node Groups/Subgraphs
godotengine/godot pull request #99404
Opened 2024-11-18 19:27 UTC by Geometror

This PR introduces **VisualShader Node Groups/Subgraphs**, enabling the creation, editing, and reuse of grouped VisualShader nodes for enhanced modularity and efficiency in shader workflows.

Closes https://github.com/godotengine/godot-proposals/issues/7730

### See https://github.com/godotengine/godot/pull/99404#issuecomment-3967282729 for recent updates

<img width="1387" height="860" alt="image" src="https://github.com/user-attachments/assets/f3e44ac1-bdcc-42c2-b466-e759ef76b903" />

## **Detailed changes:**
- Refactor the VisualShaderEditor editor for editing both VisualShader and VisualShaderGroup
	- ShaderGraph abstraction (via composition, because inheritance is not possible  since `VisualShader` already inherits from `Shader` and `VisualShaderGroup` shouldn't; + multiple inheritance/interfaces aren't allowed)
- Add VisualShaderGroup resource
	- Has a very similar API to VisualShader (subject to change)
- Add VisualShaderNodeGroup

	![Pasted image 20241118195906](https://github.com/user-attachments/assets/6ea7caf7-a5b4-4480-b5b3-617ae6cf888a)
	- Functions as an instance of a VisualShaderGroup
	- Displays the groups name in its titlebar
	- Edit button in titlebar
		- You can enter the group by pressing this button and return by pressing the arrow button in the menu bar.  Groups can be arbitrarily nested, so a breadcrumb navigation could make sense in this
- Edit groups inside of the VisualShader editor
	- Each group has a input and output node
	- The input and output ports can be edited via the new group ports dialog:
	- Open it by pressing the respective button on the input/output node

     ![Pasted image 20241118195800](https://github.com/user-attachments/assets/1a0d55f6-7b19-4def-bbc3-ead4fb4b5430)
	 ![Pasted image 20241118195724](https://github.com/user-attachments/assets/c45e179d-19f4-4a39-9cf6-3520089471c6)

## **To-Do:**
- [x] Fix/implement port previews inside groups
- [x] Fix certain edge cases for shader generation
~- [ ] Open VisualShaderGroup resources directly in the shader editor~
- [x] Proper validation 
	- Check for conflicts in shader generation
	- Disallow parameters and varyings 
	- Disallow other unsupported stuff based on shader type
	- Disallow recursion
- [x] Cleanup/self-review
~- [ ] Implement quick group creation from selection  (maybe subsequent PR)~
~- [ ] Implement "empty" port for group input/output nodes that creates a new port automatically if you connect something to it (maybe subsequent PR)~
~- [ ] Implement breadcrumb navigation, similar to AnimationTree (subsequent PR)~

2024-12-27 12:20 UTC, Delsin-Yu commented
It's great to see that we have improved the Visual Shader!

I apologize for not understanding it correctly, but does this PR allow nesting `Subgraphs`? For example, having `subgraph b` in `subgraph a`.

2024-12-27 20:48 UTC, tetrapod00 commented
> By the way, is it possible for this PR to make it into the 4.4 release?

Seems unlikely considering this is a draft PR with remaining TODOs, and we're approaching a 4.4 beta sometime soonish.

2025-04-16 16:02 UTC, geothefaust commented
> Hello, is the author still around? It will be great if we can have this in `4.5`

Seconded. From my end, it's on my list must haves. Please let me know if there's anyway I can help get this through (testing or otherwise).

Thanks!

2025-04-17 00:00 UTC, Geometror commented
Hey, I recently started picking up my open PRs again (I was pretty busy for the last few months). No guarantees, but I'm planning to finish this in the next few weeks and will do my best to get it into 4.5.

Testing and giving feedback is always appreciated :)

2025-04-20 07:52 UTC, geothefaust commented
> Hey, I recently started picking up my open PRs again (I was pretty busy for the last few months). No guarantees, but I'm planning to finish this in the next few weeks and will do my best to get it into 4.5.
> 
> Testing and giving feedback is always appreciated :)

Most excellent! I'll keep a look out for your updates to test when you're ready! 💪

2025-05-10 15:11 UTC, Delsin-Yu commented
Hello, is the author still around? It will be ideal if we can have an approximated finish time.

2025-05-10 15:12 UTC, AThousandShips commented
If you're interested you can test and give feedback!

2025-05-19 08:44 UTC, Delsin-Yu commented
https://github.com/user-attachments/assets/5e81c29e-0da8-4f9c-8f0f-b05462e6786a

|||
|-|-|
| ![image](https://github.com/user-attachments/assets/478dc3be-d4ed-480e-a078-2e155b17e8d9) | ![image](https://github.com/user-attachments/assets/f44d9692-21dc-42e8-8151-c6dfb4b7b914) |

Hello, sorry for the delay, I was busy with some other tasks. I have done an initial test of the feature, and it looks great. Thanks for your work on this. I have some feedback and suggestions for improvement, please see below:

### User experience

1. The only way to create a node group is by using the `FileSystem/Create New/Resource` menu. It would be more intuitive to also allow users to create a node group by selecting connected nodes in a Visual Shader Graph and elevating them into a node group.
![image](https://github.com/user-attachments/assets/51df2eef-c676-41e7-bd07-137df824fd25)
2. The node group can only be edited inside a Visual Shader Graph by clicking the button labeled "Edit" from the `Node Group` node. It would be more user-friendly to directly allow users to double-click the `NodeGroup` resource to edit it, similar to how they would edit a Visual Shader Graph.
3. The node group editing can only be exited by clicking a small GUI button in the toolbar. It would be more convenient to make the `NodeGroup` functions similar to the Visual Shader Graph, where the resource is shown in the sidebar and can be exited or manipulated from there.
![image](https://github.com/user-attachments/assets/6a85b9f7-3c49-4208-8e69-ae8700212247)
4. The "Edit ports" window pops up at the wrong position, I suspect the implmentation does not take into account the multiple monitors setup, where the window position is calculated based on the bounding box of the combination of all monitors.
![image](https://github.com/user-attachments/assets/4fe511b4-fca1-42c1-8742-eca89302222c)

### Functionality

1. I got a hard crash when right click and clearing the `NodeGroup` resource from a `Node Group` visual shader node. The crash log is as follows:

<details>

```log
================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.4.dev.custom_build (b2a8f8f7c8335f98c7d01df2651d3918d1ca9908)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] Resource::connect_changed (godot\core\io\resource.cpp:186)
[1] VisualShaderNodeGroup::set_group (godot\scene\resources\visual_shader_group.cpp:635)
[2] call_with_variant_args_helper<VisualShaderNodeGroup,Ref<VisualShaderGroup> const &,0> (godot\core\variant\binder_common.h:304)
[3] call_with_variant_args_dv<VisualShaderNodeGroup,Ref<VisualShaderGroup> const &> (godot\core\variant\binder_common.h:451)
[4] MethodBindT<VisualShaderNodeGroup,Ref<VisualShaderGroup> const &>::call (godot\core\object\method_bind.h:347)
[5] ClassDB::set_property (godot\core\object\class_db.cpp:1630)
[6] Object::set (godot\core\object\object.cpp:254)
[7] VisualShaderNodePluginDefaultEditor::_property_changed (godot\editor\plugins\visual_shader_editor_plugin.cpp:7970)
[8] call_with_variant_args_helper<VisualShaderNodePluginDefaultEditor,String const &,Variant const &,String const &,bool,0,1,2,3> (godot\core\variant\binder_common.h:304)
[9] call_with_variant_args<VisualShaderNodePluginDefaultEditor,String const &,Variant const &,String const &,bool> (godot\core\variant\binder_common.h:418)
[10] CallableCustomMethodPointer<VisualShaderNodePluginDefaultEditor,void,String const &,Variant const &,String const &,bool>::call (godot\core\object\callable_method_pointer.h:107)
[11] Callable::callp (godot\core\variant\callable.cpp:57)
[12] Object::emit_signalp (godot\core\object\object.cpp:1201)
[13] Node::emit_signalp (godot\scene\main\node.cpp:3987)
[14] EditorProperty::emit_changed (godot\editor\editor_inspector.cpp:122)
[15] EditorPropertyResource::_resource_changed (godot\editor\editor_properties.cpp:3119)
[16] call_with_variant_args_helper<EditorPropertyResource,Ref<Resource> const &,0> (godot\core\variant\binder_common.h:304)
[17] call_with_variant_args<EditorPropertyResource,Ref<Resource> const &> (godot\core\variant\binder_common.h:418)
[18] CallableCustomMethodPointer<EditorPropertyResource,void,Ref<Resource> const &>::call (godot\core\object\callable_method_pointer.h:107)
[19] Callable::callp (godot\core\variant\callable.cpp:57)
[20] Object::emit_signalp (godot\core\object\object.cpp:1201)
[21] Node::emit_signalp (godot\scene\main\node.cpp:3987)
[22] Object::emit_signal<Ref<Resource> > (godot\core\object\object.h:920)
[23] EditorResourcePicker::_resource_changed (godot\editor\editor_resource_picker.cpp:136)
[24] EditorResourcePicker::_edit_menu_cbk (godot\editor\editor_resource_picker.cpp:362)
[25] call_with_variant_args_helper<EditorResourcePicker,int,0> (godot\core\variant\binder_common.h:304)
[26] call_with_variant_args<EditorResourcePicker,int> (godot\core\variant\binder_common.h:418)
[27] CallableCustomMethodPointer<EditorResourcePicker,void,int>::call (godot\core\object\callable_method_pointer.h:107)
[28] Callable::callp (godot\core\variant\callable.cpp:57)
[29] Object::emit_signalp (godot\core\object\object.cpp:1201)
[30] Node::emit_signalp (godot\scene\main\node.cpp:3987)
[31] Object::emit_signal<int> (godot\core\object\object.h:920)
[32] PopupMenu::activate_item (godot\scene\gui\popup_menu.cpp:2437)
[33] PopupMenu::_input_from_window_internal (godot\scene\gui\popup_menu.cpp:632)
[34] PopupMenu::_input_from_window (godot\scene\gui\popup_menu.cpp:447)
[35] Window::_window_input (godot\scene\main\window.cpp:1647)
[36] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (godot\core\variant\binder_common.h:304)
[37] call_with_variant_args<Window,Ref<InputEvent> const &> (godot\core\variant\binder_common.h:418)
[38] CallableCustomMethodPointer<Window,void,Ref<InputEvent> const &>::call (godot\core\object\callable_method_pointer.h:107)
[39] Callable::callp (godot\core\variant\callable.cpp:57)
[40] Callable::call<Ref<InputEvent> > (godot\core\variant\variant.h:905)
[41] DisplayServerWindows::_dispatch_input_event (godot\platform\windows\display_server_windows.cpp:3799)
[42] DisplayServerWindows::_dispatch_input_events (godot\platform\windows\display_server_windows.cpp:3769)
[43] Input::_parse_input_event_impl (godot\core\input\input.cpp:903)
[44] Input::flush_buffered_events (godot\core\input\input.cpp:1184)
[45] DisplayServerWindows::process_events (godot\platform\windows\display_server_windows.cpp:3249)
[46] OS_Windows::run (godot\platform\windows\os_windows.cpp:1987)
[47] widechar_main (godot\platform\windows\godot_windows.cpp:180)
[48] _main (godot\platform\windows\godot_windows.cpp:206)
[49] main (godot\platform\windows\godot_windows.cpp:220)
[50] WinMain (godot\platform\windows\godot_windows.cpp:234)
[51] __scrt_common_main_seh (a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[52] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

</details>

2. When modifying the input or output ports of a `NodeGroup` resource the first time, the `Edit group ports` window pops up with a blank parameter selection that has empty string as parameter name, and float as the parameter type, I suspect these controls should be hidden by default.

![image](https://github.com/user-attachments/assets/a4e99203-4704-40dc-b562-0a052fe75376)

3. While the `NodeGroup` should have similar functionality to the `ShaderGraph` node group, it does not have any `Input` parameter, which will cause some option to not function properly in the `Create Shader Node` window, for example, you can click the `Time` parameter, but the constructed `Input` node will remain empty. To be clear, it is expected that the `NodeGroup` should not have any `Input` parameter, but the `Create Shader Node` window should also not show the `Input` parameter for the `NodeGroup` resource.
![image](https://github.com/user-attachm [...]

2025-07-14 17:45 UTC, michaelharmonart commented
thrilled this is something being thought about/worked on

the ability to re-use sections of a visualshader graph between shaders is huge

2025-11-12 10:51 UTC, Delsin-Yu commented on scene/resources/visual_shader_nodes.cpp
> +Vector<ShaderGraph::DefaultTextureParam> VisualShaderNodeTexture::get_default_texture_parameters(VisualShader::Type p_type, int p_id) const {
Shader Graph?

2025-11-16 00:56 UTC, Geometror commented on scene/resources/visual_shader_nodes.cpp
> +Vector<ShaderGraph::DefaultTextureParam> VisualShaderNodeTexture::get_default_texture_parameters(VisualShader::Type p_type, int p_id) const {
Yes, this is the new abstraction which is used by both `VisualShader` and `VisualShaderGroup`. `ShaderGraph` is fully internal and won't be exposed.

2026-02-26 15:16 UTC, Geometror commented
It's finally ready for review!

<img width="1387" height="860" alt="image" src="https://github.com/user-attachments/assets/f3e44ac1-bdcc-42c2-b466-e759ef76b903" />


# New changes
- Lots of bugfixes, cleanup and refactoring
	- Renames: Fixed a few very confusing and ambigous variable/function names (non-exposed)
- Proper validation
	- Prevent cyclic references
	- Check for missing output nodes
	- Disallow parameter and varying related nodes (for now)
	- Disallow other unsupported stuff based on shader context (mode, type)
		- New virtual method `is_available`  in `VisualShaderNode` (taken from `VisualShaderNodeCustom`)
- Properly populate Input node (in groups only global builtins are allowed)
- Rework Undo/Redo System to be more user friendly and stable (shared history across edited shader types/functions and groups, "jumps" to respective graph if necessary)
- Default values for group inputs/outputs
- Add per graph (shader/group) editor layout preservation (offset, zoom)
## Open questions/notes for review:

 - There is `VisualShaderNodeGroupBase` which was added as a premature abstraction when Expression nodes were implemented. For my implementation, I needed the port management to work differently, so I reimplemented it separately to prevent breaking compat. But there's the problem that we have    `VisualShaderNodeGroupBase` and  `VisualShaderNodeGroup` with zero relation to each other and partially duplicated code and I hate it...
 - I stumbled upon a lot of places where the VisualShader system could use some refactoring, because its complexity already makes it really hard to maintain. While this PR contains a few of those refactorings, I tried to keep it minimal and only do the stuff the node groups implementation benefits from.
 - `ShaderGraph::Type` and `VisualShader::Type` are duplicated which is necessary due to backwards compatibility and because I split them up in separate files. Not ideal, but I couldn't come up with something *clearly* better.

# Further work
This PR provides a base implementation that is usable and can be built upon, with the goal to be merged early in the 4.7 dev cycle, so it can be tested extensively. 
Hence I do not wan't to blow this PR up any further - it's already a monster. 
The following features/changes should not break compatibility and can be implemented later:

- UX improvements:
	- Drag and drop group resource in editor should create group node
	- Create group based on selection
	- Breadcrumb navigation
	- Add empty port to group input and output nodes to quicken port creation (inspired by Blender)
	- Smart previews inside groups (use inputs of specific group node clicked to edit the group)
	- Edit node group directly?
- Allow parameter refs at least, consider varyings and parameters (but most likely not)
- Add an `active` property to `VisualShaderNodeGroupOutput` so that you can have multiple output nodes and switch between them
- Implement expandable ports
- Write unit tests

2026-02-27 08:03 UTC, geothefaust commented
Very exciting! I got a build worked up and did some testing this evening. So far it feels pretty solid. I was able to copy some existing nodes and paste them into a group without much trouble. Creating input and output nodes feels a lot like blender, so you can see the inspiration there.

I feel like it's in pretty good shape! I do think that the feedback posted above by @Delsin-Yu ([here](https://github.com/godotengine/godot/pull/99404#issuecomment-2890154123)) is still quite valid, particularly the User Experience aspects. But, that said, I personally wouldn't want anything holding this feature back, and could see those as future polish QOL enhancements.

Thank you once again for your hard work on implementing this! I know it's been a huge undertaking, and it's very much appreciated. I'll continue to do more testing over the next couple of weeks and report back with any findings.

Cheers!

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader_group.cpp
> +#include "core/templates/hash_set.h"
```suggestion
```
Unnecessary

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader.cpp
> +	ERR_FAIL_COND_V(!nodes.has(p_id), Ref<VisualShaderNode>());
Redundant

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +			Ref<VisualShaderNodeGroupInput> group_input = Object::cast_to<VisualShaderNodeGroupInput>(node.ptr());
```suggestion
			Ref<VisualShaderNodeGroupInput> group_input = node;
```

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +	add_port_btn->set_text("Add port");
```suggestion
	add_port_btn->set_text(TTR("Add port"));
```
I assume?

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +	remove_port_btn->set_text("Remove port");
```suggestion
	remove_port_btn->set_text(TTR("Remove port"));
```
Ditto

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +			group_icon->set_texture(editor->get_theme_icon("VisualShaderGroup", "EditorIcons"));
```suggestion
			group_icon->set_texture(editor->get_editor_theme_icon("VisualShaderGroup"));
```

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +			edit_group_btn->set_button_icon(editor->get_theme_icon("Edit", "EditorIcons"));
```suggestion
			edit_group_btn->set_button_icon(editor->get_editor_theme_icon("Edit"));
```

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +			edit_group_btn->connect("pressed", callable_mp(editor, &VisualShaderEditor::_edit_group_in_graph).bind(p_id), CONNECT_DEFERRED);
```suggestion
			edit_group_btn->connect(SceneStringName(pressed), callable_mp(editor, &VisualShaderEditor::_edit_group_in_graph).bind(p_id), CONNECT_DEFERRED);
```

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +		ERR_FAIL_COND_MSG(true, "Custom Visual Shader Node name '" + p_name + "' is not a valid identifier. It must start with a letter or underscore and can only contain letters, digits, and underscores."
```suggestion
		ERR_FAIL_MSG("Custom Visual Shader Node name '" + p_name + "' is not a valid identifier. It must start with a letter or underscore and can only contain letters, digits, and underscores.");
```

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +		DEV_ASSERT(false);
Needs a descriptive error message, if it should be kept at all, not sure it makes sense to crash here

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +	ERR_FAIL_COND(group == nullptr);
```suggestion
	ERR_FAIL_NULL(group);
```

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +			Ref<VisualShaderNodeGroupInput> group_input = Object::cast_to<VisualShaderNodeGroupInput>(node.ptr());
```suggestion
			Ref<VisualShaderNodeGroupInput> group_input = node;
```

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +			Ref<VisualShaderNodeGroupOutput> group_output = Object::cast_to<VisualShaderNodeGroupOutput>(node.ptr());
```suggestion
			Ref<VisualShaderNodeGroupOutput> group_output = node;
```

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +			Ref<VisualShaderNodeInput> input_node = Object::cast_to<VisualShaderNodeInput>(node.ptr());
```suggestion
			Ref<VisualShaderNodeInput> input_node = node;
```

2026-02-27 13:56 UTC, AThousandShips commented on editor/shader/visual_shader_editor_plugin.cpp
> +	exit_group_button->set_theme_type_variation("FlatButton");
```suggestion
	exit_group_button->set_theme_type_variation(SceneStringName(FlatButton));
```

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader.h
> +			graph[TYPE_MAX];
```suggestion
	Ref<ShaderGraph> graph[TYPE_MAX];
```

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader.h
> +	bool is_available(Shader::Mode p_mode, VisualShader::Type p_type) const override;
```suggestion
	virtual bool is_available(Shader::Mode p_mode, VisualShader::Type p_type) const override;
```

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/shader_graph.cpp
> +#include "core/math/vector4.h"
```suggestion
```

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/shader_graph.cpp
> +#include "visual_shader_particle_nodes.h"
```suggestion
#include "scene/resources/visual_shader_nodes.h"
#include "scene/resources/visual_shader_particle_nodes.h"
```

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/shader_graph.cpp
> +	// ClassDB::bind_method(D_METHOD("get_node_connections", "type"), &ShaderGraph::get_node_connections);
```suggestion
	//ClassDB::bind_method(D_METHOD("get_node_connections", "type"), &ShaderGraph::get_node_connections);
```
Or remove it

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/shader_graph.cpp
> +		r_code += "	// Node is disabled and code is not generated.\n";
```suggestion
		r_code += "// Node is disabled and code is not generated.\n";
```

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader.cpp
> +#include "core/math/vector4.h"
```suggestion
```

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader_group.cpp
> +#include "core/templates/hash_set.h"
```suggestion
```

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader_group.cpp
> +#include "visual_shader_particle_nodes.h"
```suggestion
#include "scene/resources/visual_shader_particle_nodes.h"
```

2026-02-27 13:56 UTC, AThousandShips commented on modules/visual_shader/visual_shader_group.cpp
> +	while (port_name.length() && !is_ascii_alphabet_char(port_name[0])) {
```suggestion
	while (!is_ascii_alphabet_char(port_name[0])) {
```
Already checked above

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader_group.cpp
> +		port_name = port_name.substr(1, port_name.length() - 1);
```suggestion
		port_name = port_name.substr(1);
```
Unnecessary

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader_group.cpp
> +			ERR_FAIL_COND(err != OK);
I'd add a descriptive error message here

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader_group.cpp
> +		ERR_FAIL_COND(err != OK);
And here

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader_group.cpp
> +			const Dictionary &port = ports[i];
```suggestion
		for (const Dictionary port : ports) {
```

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader_group.cpp
> +			const Dictionary &port = ports[i];
```suggestion
		for (const Dictionary port : ports) {
```

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader_group.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "group", PROPERTY_HINT_RESOURCE_TYPE, "VisualShaderGroup"), "set_group", "get_group");
```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "group", PROPERTY_HINT_RESOURCE_TYPE, VisualShaderGroup::get_class_static()), "set_group", "get_group");
```

2026-02-27 13:56 UTC, AThousandShips commented on scene/resources/visual_shader_group.cpp
> +		};
```suggestion
		}
```

2026-02-27 13:56 UTC, AThousandShips commented on doc/classes/VisualShaderGroup.xml
> +		Since an actual shader function is created for each [VisualShaderGroup], you can only use global builtin variables.
```suggestion
		Since an actual shader function is created for each [VisualShaderGroup], you can only use global built-in variables.
```

2026-02-27 13:56 UTC, AThousandShips commented on doc/classes/VisualShaderGroup.xml
> +				Returns the shader node instance with specified [param id].
```suggestion
				Returns the shader node instance with the specified [param id].
```

2026-02-27 13:56 UTC, AThousandShips commented on doc/classes/VisualShaderGroup.xml
> +				Returns [code]true[/code] if the specified node and port connection exist.
```suggestion
				Returns [code]true[/code] if the specified node and port connection exists.
```

2026-02-27 14:56 UTC, Geometror commented on editor/shader/visual_shader_editor_plugin.cpp
> +		ERR_FAIL_COND_MSG(true, "Custom Visual Shader Node name '" + p_name + "' is not a valid identifier. It must start with a letter or underscore and can only contain letters, digits, and underscores."
This whole check is broken, I don't know what I did there.

2026-02-27 15:05 UTC, Geometror commented on editor/shader/visual_shader_editor_plugin.cpp
> +		DEV_ASSERT(false);
Well this should never happen + it doesn't crash in a release builds. However, DEV_ASSERT is a bit limiting since it doesn't allow error messages. Replaced it with
```	
ERR_FAIL_COND_MSG(group_edit_stack.is_empty(), "Cannot exit group: group edit stack is empty.");
```

2026-02-27 15:14 UTC, arkology commented on editor/shader/visual_shader_editor_plugin.cpp
> +	add_port_btn->set_text("Add port");
TTRC if autotranslation is not disabled. Unfortunately I can not normally view changes on mobile, so just for information and double checking.

2026-02-27 15:25 UTC, Geometror commented on modules/visual_shader/visual_shader_group.cpp
> +	while (port_name.length() && !is_ascii_alphabet_char(port_name[0])) {
No, this is necessary since in the loop the first character of port_name is removed until the first alphabetic character. But if the string only contains non-alphabetic characters this leads to an out of bounds check.

2026-02-27 15:30 UTC, Geometror commented on scene/resources/visual_shader_group.cpp
> +		port_name = port_name.substr(1, port_name.length() - 1);
Yes, but I'd argue it's a bit clearer with it (especially if you don't have parameter inlay hints available in your IDE or disabled them)

2026-02-27 16:04 UTC, Geometror commented on scene/resources/visual_shader_group.cpp
> +			ERR_FAIL_COND(err != OK);
I just rechecked ShaderGraph::_write_node which was pulled out more or less directly from VisualShader. It looks like _write_node has never returned anything other that `OK`, so I guess the `Error` return type could be removed entirely (or we leave it and add an error message to future proof).

2026-02-27 16:13 UTC, Geometror commented on doc/classes/VisualShaderGroup.xml
> +				Returns [code]true[/code] if the specified node and port connection exist.
Copied from VisualShader, fixed there as well.

2026-02-27 16:32 UTC, Geometror commented
@Delsin-Yu @geothefaust 
Thanks a lot for testing and your valuable feedback!
All bugs and major inconveniences from https://github.com/godotengine/godot/pull/99404#issuecomment-2890154123 should be fixed by now. 
For the UX aspects, see the "Further work" section in https://github.com/godotengine/godot/pull/99404#issuecomment-3967282729 
Those features are pretty much sorted by importance (for me). I will try my best to finish them soon, but the most important goal now is getting this one rock solid.

2026-02-27 21:49 UTC, AThousandShips commented on modules/visual_shader/visual_shader_group.cpp
> +	while (port_name.length() && !is_ascii_alphabet_char(port_name[0])) {
Good point missed the loop

2026-02-27 21:49 UTC, AThousandShips commented on scene/resources/visual_shader_group.cpp
> +		port_name = port_name.substr(1, port_name.length() - 1);
I'd say it's the opposite generally, adding a default argument value implies it's not using the default, otherwise you'd use the default, it also doesn't carry any information other than "take the whole string except the first character"

Also not sure how inlay hints are relevant here, the default argument is `-1` which doesn't mean `length - 1` it means `length - p_from`

2026-02-28 04:38 UTC, HeadClot commented
> It's finally ready for review!
> <img alt="image" width="1387" height="860" src="https://private-user-images.githubusercontent.com/50084500/555458103-f3e44ac1-bdcc-42c2-b466-e759ef76b903.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzIyNTM3NDUsIm5iZiI6MTc3MjI1MzQ0NSwicGF0aCI6Ii81MDA4NDUwMC81NTU0NTgxMDMtZjNlNDRhYzEtYmRjYy00MmMyLWI0NjYtZTc1OWVmNzZiOTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI4VDA0MzcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMTQwZTg1ZjdkYzFmODhiZGYxNWJiY2EwNzA1MTFmMTBlOWU0NTlkMDg3Y2E3M2EyZWQ3YzllNmViM2NlYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bm6VkZSkpAdFqzmsHZfcDUeF0QE7xGnttpBI0YDQttA">
> # New changes
> 
>     * Lots of bugfixes, cleanup and refactoring
>       
>       * Renames: Fixed a few very confusing and ambigous variable/function names (non-exposed)
> 
>     * Proper validation
>       
>       * Prevent cyclic references
>       * Check for missing output nodes
>       * Disallow parameter and varying related nodes (for now)
>       * Disallow other unsupported stuff based on shader context (mode, type)
>         
>         * New virtual method `is_available`  in `VisualShaderNode` (taken from `VisualShaderNodeCustom`)
> 
>     * Properly populate Input node (in groups only global builtins are allowed)
> 
>     * Rework Undo/Redo System to be more user friendly and stable (shared history across edited shader types/functions and groups, "jumps" to respective graph if necessary)
> 
>     * Default values for group inputs/outputs
> 
>     * Add per graph (shader/group) editor layout preservation (offset, zoom)
> 
> 
> ## Open questions/notes for review:
> 
>     * There is `VisualShaderNodeGroupBase` which was added as a premature abstraction when Expression nodes were implemented. For my implementation, I needed the port management to work differently, so I reimplemented it separately to prevent breaking compat. But there's the problem that we have    `VisualShaderNodeGroupBase` and  `VisualShaderNodeGroup` with zero relation to each other and partially duplicated code and I hate it...
> 
>     * I stumbled upon a lot of places where the VisualShader system could use some refactoring, because its complexity already makes it really hard to maintain. While this PR contains a few of those refactorings, I tried to keep it minimal and only do the stuff the node groups implementation benefits from.
> 
>     * `ShaderGraph::Type` and `VisualShader::Type` are duplicated which is necessary due to backwards compatibility and because I split them up in separate files. Not ideal, but I couldn't come up with something _clearly_ better.
> 
> 
> # Further work
> 
> This PR provides a base implementation that is usable and can be built upon, with the goal to be merged early in the 4.7 dev cycle, so it can be tested extensively. Hence I do not wan't to blow this PR up any further - it's already a monster. The following features/changes should not break compatibility and can be implemented later:
> 
>     * UX improvements:
>       
>       * Drag and drop group resource in editor should create group node
>       * Create group based on selection
>       * Breadcrumb navigation
>       * Add empty port to group input and output nodes to quicken port creation (inspired by Blender)
>       * Smart previews inside groups (use inputs of specific group node clicked to edit the group)
>       * Edit node group directly?
> 
>     * Allow parameter refs at least, consider varyings and parameters (but most likely not)
> 
>     * Add an `active` property to `VisualShaderNodeGroupOutput` so that you can have multiple output nodes and switch between them
> 
>     * Implement expandable ports
> 
>     * Write unit tests

Wow this looks really good! Looking forward to seeing this being merged into main.

2026-02-28 14:45 UTC, Chaosus commented
Some feedback:

1. Adding/removing/changing ports should generate an event for Undo/Redo.
2. Also pressing Remove port when there are no ports generates error:
![graph_test](https://github.com/user-attachments/assets/0668882f-c393-4588-b544-41e06571d949)
3. you can have duplicated names - after closing/reopened that dialog it seems fixed  - <img width="946" height="912" alt="изображение" src="https://github.com/user-attachments/assets/23bb6d1b-0d9c-4137-9ce9-788135f836c2" />
4. Need an option to rearrange the ports order
5. I would use a types icons for output ports... 
<img width="301" height="266" alt="изображение" src="https://github.com/user-attachments/assets/0cfb8d8b-2884-45e7-a487-e12db2cc2e75" />

2026-02-28 15:03 UTC, Chaosus commented
IMO GroupInput and GroupOutput should not be created via Add Node dialog, and should not be instanced more than once, nor to be deleted by a user.

2026-02-28 15:29 UTC, passivestar commented
> IMO GroupInput and GroupOutput should not be created via Add Node dialog, and should not be instanced more than once, nor to be deleted by a user.

Being able to access group inputs via more than one input node is invaluable for keeping graphs clean, I do it all the time in blender:

<img width="1248" height="602" alt="image" src="https://github.com/user-attachments/assets/9e3d3777-af4e-4b22-9bbb-cd739ac281ab" /><br>

If you need to connect everything from a single input node you end up with a spaghetti monster in big graphs.

2026-02-28 16:49 UTC, Chaosus commented
> If you need to connect everything from a single input node you end up with a spaghetti monster in big graphs.

Well, maybe.. But the implementation of this in this PR has bugs at least for `GroupOutput`...

2026-03-03 17:47 UTC, AThousandShips commented on scene/resources/shader_graph.cpp
> +			p_list->push_back(PropertyInfo(Variant::OBJECT, prop_name + "/node", PROPERTY_HINT_RESOURCE_TYPE, "VisualShaderNode", PROPERTY_USAGE_NO_EDITOR | PROPERTY_USAGE_ALWAYS_DUPLICATE));
```suggestion
			p_list->push_back(PropertyInfo(Variant::OBJECT, prop_name + "/node", PROPERTY_HINT_RESOURCE_TYPE, VisualShaderNode::get_class_static(), PROPERTY_USAGE_NO_EDITOR | PROPERTY_USAGE_ALWAYS_DUPLICATE));
```
I missed last pass

2026-03-03 17:47 UTC, AThousandShips commented on scene/resources/shader_graph.cpp
> +			p_list->push_back(PropertyInfo(Variant::OBJECT, prop_name + "/node", PROPERTY_HINT_RESOURCE_TYPE, "VisualShaderNode", PROPERTY_USAGE_NO_EDITOR | PROPERTY_USAGE_ALWAYS_DUPLICATE));
```suggestion
			p_list->push_back(PropertyInfo(Variant::OBJECT, prop_name + "/node", PROPERTY_HINT_RESOURCE_TYPE, VisualShaderNode::get_class_static(), PROPERTY_USAGE_NO_EDITOR | PROPERTY_USAGE_ALWAYS_DUPLICATE));
```
I missed last pass

2026-03-04 00:32 UTC, Geometror commented on scene/resources/visual_shader_group.cpp
> +		port_name = port_name.substr(1, port_name.length() - 1);
Fair enough, changed it. Regarding the inlay hints: Nevermind, long story short, I confused myself there :)

2026-03-04 00:32 UTC, Geometror commented on scene/resources/visual_shader_group.cpp
> +			ERR_FAIL_COND(err != OK);
Removed it.

2026-03-04 00:34 UTC, Geometror commented
<img width="277" height="462" alt="image" src="https://github.com/user-attachments/assets/0c2133da-7a72-40cd-8d26-13f8b246a0a6" />


# New changes:
- Rework group ports dialog partially
	- Improved port name editing
	- Add/remove buttons now use icons and tooltip instead of text, hide remove button when the list is empty
	- You can now reorder ports with the respective move up/down buttons (supports undo)
	- Use variant type icons for items (even though I hate them ;))
- Fixed handling of sampler ports

## Known issues
- The problem with group port changes (removal/reorder) are connections "outside" the group, so in the graphs which contain instances of the group. Updating those connections with proper undo/redo support is pretty complex and expensive. We'd also need to decide whether all graphs (visual shaders or groups) need to be updated, even those not opened, or just the current shader graph stack.
- Currently, moving a port does simply not update connections outside the group (to group instances) due to the problems mentioned above.

2026-03-04 00:55 UTC, Geometror commented
@Chaosus Everything you mentioned should now be fixed/implemented. 

Concerning the group input and output nodes: First I had a strict implementation which ensured exactly one input and one output node. However, that came with its own set of problems and was ugly in code. After that I came up with a general solution that allowed multiple(or none) input and output nodes, which simplified things a lot while providing an actual UX benefit. One could argue that multiple output nodes are not really that useful, but I think it has some value (and making an exception would reintroduce the problem I mentioned again). In Blender, you can have multiple output nodes, but only one is active at a time. This makes sense to me: You could build branches in your group, trying things out, and switching between output nodes - basically allowing you to have several versions of your group without any runtime cost, vaguely similar to conditional compilation.
Right now, just the first output node is selected and a warning is shown on the group instance node, so this feature needs to be implemented still. But I'd rather do this in a subsequent PR.

2026-03-04 06:50 UTC, geothefaust commented
> @Chaosus Everything you mentioned should now be fixed/implemented.
> 
> Concerning the group input and output nodes: First I had a strict implementation which ensured exactly one input and one output node. However, that came with its own set of problems and was ugly in code. After that I came up with a general solution that allowed multiple(or none) input and output nodes, which simplified things a lot while providing an actual UX benefit. One could argue that multiple output nodes are not really that useful, but I think it has some value (and making an exception would reintroduce the problem I mentioned again). In Blender, you can have multiple output nodes, but only one is active at a time. This makes sense to me: You could build branches in your group, trying things out, and switching between output nodes - basically allowing you to have several versions of your group without any runtime cost, vaguely similar to conditional compilation. Right now, just the first output node is selected and a warning is shown on the group instance node, so this feature needs to be implemented still. But I'd rather do this in a subsequent PR.

Just adding my two bits as a user, I'd sure like to see multiple output nodes. They are very useful. I use them daily in UE (day job), in material functions. Please do include them. :)

Thanks!

2026-03-26 17:01 UTC, QbieShay commented
Just tested the feature. It looks good and i think it's a great basis for further development. There's some UX stuff to be discussed but it should come after this PR is merged.

The only issue i've noticed is that when a subgraph is included in two shaders and they're both open, it doesn't seem to update correctly. I don't know what happens and which version gets saved in the end.

2026-03-26 17:04 UTC, QbieShay approved these changes
Actually nevermind my previous comment. While creating a repro, it turned out to be my fault.

2026-03-29 13:01 UTC, Chaosus requested changes

2026-03-29 13:01 UTC, Chaosus commented on scene/resources/visual_shader_group.cpp
> +				code += "\t" + p_output_vars[i] + " = " + get_port_type_default_value_shader_string(group->get_output_port_type(i)) + ";\n";
```suggestion
				code += "	" + p_output_vars[i] + " = " + get_port_type_default_value_shader_string(group->get_output_port_type(i)) + ";\n";
```

2026-03-29 13:01 UTC, Chaosus commented on scene/resources/visual_shader_group.cpp
> +	code += func_name + "(";
```suggestion
	code += "	" + func_name + "(";
```

2026-03-29 13:01 UTC, Chaosus commented on scene/resources/visual_shader_group.cpp
> +			code += ",";
```suggestion
			code += ", ";
```

2026-03-29 13:01 UTC, Chaosus commented on scene/resources/visual_shader_group.cpp
> +			code += ",";
```suggestion
			code += ", ";
```

2026-03-29 13:01 UTC, Chaosus commented on scene/resources/visual_shader_group.cpp
> +			code += p_output_vars[i] + " = " + "p_" + group->get_input_port_name(i) + ";\n";
```suggestion
			code += "	" + p_output_vars[i] + " = " + VisualShaderNode::get_port_type_default_value_shader_string(group->get_input_port_type(i)) + ";\n";
		} else {
			code += "	" + p_output_vars[i] + " = " + "p_" + group->get_input_port_name(i) + ";\n";
```

2026-03-29 13:01 UTC, Chaosus commented on scene/resources/visual_shader_group.cpp
> +		code += "p_" + group->get_output_port_name(i) + " = " + p_input_vars[i] + ";\n";
```suggestion
		code += "	p_" + group->get_output_port_name(i) + " = " + p_input_vars[i] + ";\n";
```

2026-03-29 14:29 UTC, Chaosus commented
@Geometror  Why this warning is emitting?

<img width="708" height="983" alt="изображение" src="https://github.com/user-attachments/assets/e99db6dd-bcbe-42c8-bd51-5e777e6ad55e" />

I thought it was correct to use multiple output nodes...

<img width="1441" height="1079" alt="изображение" src="https://github.com/user-attachments/assets/07bc0c63-7aad-4a6b-bf0a-dce022eb11df" />

2026-03-29 17:03 UTC, Geometror commented
@Chaosus  Yes, it should be possible to use multiple output nodes in the future. However, because that isn't implemented yet, it's forbidden softly via a warning. I figured this is better than completely changing the editor and groups implementation to only allow inserting one output node, only to completely change it again in a few weeks when adding support for multiple output nodes.

2026-03-29 17:08 UTC, Chaosus approved these changes
Alright, then, I think it's fine now, I do not looked deeper into other parts of code thoug

2026-04-15 15:51 UTC, Chaosus commented
@Geometror need rebase after visual shaders moved to modules...

2026-07-31 18:20 UTC, Geometror commented
Alright, some updates:
- Rebased after #115998 
- Further refactoring: reserved node Ids are gone now, the ShaderGraph API is much cleaner now, less coupling, no friend classes needed anymore
- Fixed name collisions of default texture uniforms and nested node groups by refactoring the code generation
- Other misc fixes

2026-08-02 02:30 UTC, paddy-exe requested changes
Apart from the small nitpicks regarding comments I only found out that I am unable to revert deleting an input/output port while having the "Edit ports" window open. When closing that window the action can be reverted though. (That falls under UX I suppose but should at least be noted for the future)

I was also able to produce a consistent crash while deleting input ports from a visual shader node subgraph with the following stack trace:
<details><summary>Details</summary>

System info:
Godot v4.8.dev (7c05f9d81) - Fedora Linux 44 (KDE Plasma Desktop Edition) on Wayland - Wayland display driver, Single-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (nvidia; 610.43.03) - AMD Ryzen 7 5800XT 8-Core Processor (16 threads) - 15.52 GiB memory - PulseAudio (44100 Hz, Stereo/mono)

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.8.dev.custom_build (7c05f9d814697f15eeeef501e5a889984c682c00)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
Load address: 400000

[1] 7fc004e41fb0 (libc.so.6+19fb0) - /lib64/libc.so.6(+0x19fb0) [0x7fc004e41fb0]
[2] 51cdb2 (main+11cdb2) - StringName::operator==(StringName const&) const at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/string/string_name.h:121
[3] 20cd76e (main+1ccd76e) - VisualShaderEditor::_update_group_related_nodes() at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/modules/visual_shader/editor/visual_shader_editor_plugin.cpp:3275 (discriminator 2)
[4] 2194106 (main+1d94106) - void call_with_variant_args_helper<VisualShaderEditor>(VisualShaderEditor*, void (VisualShaderEditor::*)(), Variant const**, Callable::CallError&, IndexSequence<>) at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/variant/binder_common.h:63
[5] 218f8fc (main+1d8f8fc) - void call_with_variant_args<VisualShaderEditor>(VisualShaderEditor*, void (VisualShaderEditor::*)(), Variant const**, int, Callable::CallError&) at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/variant/binder_common.h:173
[6] 2189df1 (main+1d89df1) - CallableCustomMethodPointer<VisualShaderEditor, void>::call(Variant const**, int, Variant&, Callable::CallError&) const at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/object/callable_mp.h:107
[7] 57e26ed (main+53e26ed) - Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/variant/callable.cpp:58
[8] 5b69180 (main+5769180) - Object::emit_signalp(StringName const&, Variant const**, int) at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/object/object.cpp:1288
[9] 7fd0ff (main+3fd0ff) - Error Object::emit_signal<>(StringName const&) at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/object/object.h:778
[10] 56e110c (main+52e110c) - Resource::emit_changed() at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/io/resource.cpp:60
[11] 1fc830e (main+1bc830e) - VisualShaderGroup::_emit_pending_change() at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/modules/visual_shader/visual_shader_group.cpp:189
[12] 1fda207 (main+1bda207) - void call_with_variant_args_helper<VisualShaderGroup>(VisualShaderGroup*, void (VisualShaderGroup::*)(), Variant const**, Callable::CallError&, IndexSequence<>) at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/variant/binder_common.h:63
[13] 1fd9317 (main+1bd9317) - void call_with_variant_args<VisualShaderGroup>(VisualShaderGroup*, void (VisualShaderGroup::*)(), Variant const**, int, Callable::CallError&) at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/variant/binder_common.h:173
[14] 1fd8373 (main+1bd8373) - CallableCustomMethodPointer<VisualShaderGroup, void>::call(Variant const**, int, Variant&, Callable::CallError&) const at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/object/callable_mp.h:107
[15] 57e26ed (main+53e26ed) - Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/variant/callable.cpp:58
[16] 5b60383 (main+5760383) - CallQueue::_call_function(Callable const&, Variant const*, int, bool) at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/object/message_queue.cpp:219
[17] 5b606fa (main+57606fa) - CallQueue::flush() at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/core/object/message_queue.cpp:268
[18] 37bdc16 (main+33bdc16) - SceneTree::physics_process(double) at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/scene/main/scene_tree.cpp:660
[19] 51b06b (main+11b06b) - Main::iteration() at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/main/main.cpp:4897 (discriminator 3)
[20] 422936 (main+22936) - OS_LinuxBSD::run() at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/platform/linuxbsd/os_linuxbsd.cpp:1000 (discriminator 1)
[21] 43744d (main+3744d) - main at /home/patrick/Dokumente/Coding/GameDev/Godot/godot-builds/godot/platform/linuxbsd/godot_linuxbsd.cpp:122
[22] 7fc004e2b681 (libc.so.6+3681) - /lib64/libc.so.6(+0x3681) [0x7fc004e2b681]
[23] 7fc004e2b798 (libc.so.6+3798) - /lib64/libc.so.6(__libc_start_main+0x88) [0x7fc004e2b798]
[24] 418755 (main+18755) - _start at ??:?
-- END OF C++ BACKTRACE --
```

</details> 

MRP:
[visual-node-subgraphs.zip](https://github.com/user-attachments/files/30625633/visual-node-subgraphs.zip)

Reproduction steps:
1. Open `node_3d_vs_shader.tres` visual shader resource
2. Open inside the visual shader the group node by clicking on the Edit icon
3. On the Group input node inside the group node click on `Edit ports`
4. Click repeatedly on `Remove port` (trashbin icon)

2026-08-02 02:30 UTC, paddy-exe commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +		// TODO: Find out what to do here.
This should be either more precise or left out

2026-08-02 02:30 UTC, paddy-exe commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +	// TODOO: Allow editing just groups (rename this this whole method maybe to reflect that).
```suggestion
	// TODO: Allow editing just groups (rename this this whole method maybe to reflect that).
```

2026-08-02 02:30 UTC, paddy-exe commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +	// BFS through the shader graphs to find all (nested) groups and save them.
BFS? What does that stand for?

2026-08-03 19:19 UTC, Geometror commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +		// TODO: Find out what to do here.
This was partially outdated. Made it more specific.

2026-08-03 19:21 UTC, Geometror commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +	// BFS through the shader graphs to find all (nested) groups and save them.
Breadth first search

2026-08-03 19:26 UTC, Geometror commented
I couldn't reproduce the crash on my machine, but I think I fixed the UB bug that was causing it. Can you re-verify on your machine?
The group ports dialog now forwards undo/redo shortcuts to the editor like some other dialogs (e.g. editor settings). 
(outside of this PR I think there are lot's of other dialogs that have the same problem since you explicitly need to forward shortcuts, so it could be worth it to go over them at some point; but that's just from my memory, maybe this has been fixed for those)
I also cleaned up/addressed some remaining TODO comments that slipped through.

2026-08-04 00:33 UTC, paddy-exe commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +	// BFS through the shader graphs to find all (nested) groups and save them.
As this does come up directly after searching for it that should be fine to leave as-is I suppose

2026-08-04 00:37 UTC, paddy-exe approved these changes
My bug is solved now and all looks solid from my side.

2026-08-05 08:43 UTC, KoBeWi reviewed
Did a review of the code and found some problems.

The discoverability and usability of the feature is rather poor right now, but since improving it is already in the plans, I won't comment on it.

I noticed that Group Input/Output nodes can be removed from the group (with Delete). The editor does not support it properly, so it should be blocked I think.

2026-08-05 08:43 UTC, KoBeWi commented on doc/classes/VisualShaderNodeGroup.xml
> +		If the group contains several outputs only the first one will be used.
The note about mutliple outputs does not seem true. Unless I'm misunderstanding it?

<img width="351" height="214" alt="Image" src="https://github.com/user-attachments/assets/ee51a5d0-7cd5-4488-ab7f-b75467f07a4a" />

Works normally.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.h
> +#include "modules/visual_shader/visual_shader.h"
This should not use absolute paths.
```suggestion
#include "visual_shader.h"
```
The includes in other files are wrong since VisualShader was moved to a module.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +	while (port_name.length() && !is_ascii_alphabet_char(port_name[0])) {
```suggestion
	while (!port_name.is_empty() && !is_ascii_alphabet_char(port_name[0])) {
```
Also, any reason for not allowing unicode?

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +		port_name = port_name.substr(1);
It hardly matters, but this is inefficient. You should search for the first valid char and only `substr()` once found.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +			} else if (port_name[i] == ' ') {
Shouldn't this replace all invalid characters? Currently they just get discarded.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +	}
You could also use `validate_ascii_identifier()` (or unicode), instead of repeating this code.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +void VisualShaderGroup::_bind_methods() {
I wonder how much of this API needs to be exposed? Are users expected to interact with groups in code?

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +	group_name = RTR("Node group");
This is wrong. The default name is going to be translated and forever show revert arrow in non-English languages.

<img width="452" height="125" alt="Image" src="https://github.com/user-attachments/assets/254b6b14-543b-45b6-9a8d-09779661a503" />

```suggestion
	group_name = "Node group";
```

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +	return warning_str.trim_suffix("\n");
```suggestion
	return String("\n").join(warnings);
```

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +		return RTR("Node group");
No other node title is being translated.
```suggestion
		return "Node group";
```
(they do receive auto-translation though, but that's unrelated bug)

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +	// calling the group function.
```suggestion
	// If the group cannot be used in the current shader context, output default values instead of calling the group function.
```
I don't think breaking the comment is needed if it's shorter than the line below 🤔

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +}
Don't add empty constructors
```suggestion
```

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader.h
> +	// Keep in sync with ShaderGraph::Type.
It would be nice if this wasn't duplicated, but seems like it's for compatibility reasons :/

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader.h
> +	static constexpr int NODE_ID_OUTPUT = 0;
Duplicated from ShaderGraph. VisualShader could reuse those constants instead of making its own.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +String VisualShaderGroup::_validate_port_name(const String &p_port_name, int p_port_id, bool p_output) const {
I just noticed this method also exists in ShaderGraph.

You could do something like
```C++
String VisualShaderGroup::_validate_port_name(const String &p_port_name, int p_port_id, bool p_output) const {
	String port_name = graph->validate_port_name();
	
	// Deduplication.
	...
```
The comments below apply to the method in ShaderGraph too I guess.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/shader_graph.cpp
> +	emit_signal("graph_changed");
```suggestion
	emit_signal(SNAME("graph_changed"));
```

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/shader_graph.cpp
> +void ShaderGraph::_bind_methods() {
ShaderGraph is not exposed, so some of these binds are pointless. Only methods used by UndoRedo should be bound.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/shader_graph.cpp
> +		Shader::Mode p_mode) const {
Seeing this long argument list makes me think whether this should accept a struct instead. 🤔

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/register_types.cpp
> +		GDREGISTER_INTERNAL_CLASS(ShaderGraph);
What are internal classes even for?
It's not like you need to register anything, GDCLASS is enough to make the type work with Godot functions.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +	port_item_list = memnew(ItemList);
The list needs scroll hints.

<img width="376" height="446" alt="Image" src="https://github.com/user-attachments/assets/80a0bf6a-dfec-4fda-9bc7-7e07c467169d" />

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +void VisualShaderEditor::_restore_graph_context(int p_shader_type, TypedArray<VisualShaderGroup> p_group_stack) {
What 💀
VisualShaderGroup should really be editable as a document in the Shader Editor, not with some weird internal "sub-editor". Why was it even made like that :/

Too late to change it now, but some follow-up PR should clean that up.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +	set_title("Edit group ports");
```suggestion
	set_title(TTRC("Edit Group Ports"));
```

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +	add_port_btn->set_tooltip_text(TTRC("Add port"));
Action names usually use title case.
```suggestion
	add_port_btn->set_tooltip_text(TTRC("Add Port"));
```
Same below.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +	port_type_optbtn->add_item(TTR("Float"));
```suggestion
	port_type_optbtn->add_item(TTRC("Float"));
```
Same in all items.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +			edit_group_btn->set_tooltip_text(TTR("Edit"));
```suggestion
			edit_group_btn->set_tooltip_text(TTRC("Edit"));
```

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +		edit_ports_btn->set_text(TTR("Edit ports"));
```suggestion
		edit_ports_btn->set_text(TTR("Edit Ports"));
```

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +// separate resources, so save them here too.
So adding a group to a shader makes it saved every time the shader is saved, even if the group was never modified?

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.h
> +	Ref<ShaderGraph> editing_shader_graph;
```suggestion
	Ref<ShaderGraph> edited_shader_graph;
```

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +	}
```suggestion
	exit_group_button->set_visible(!group_edit_stack.is_empty());
```

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +		Ref<ShaderGraph> graph = current->get_graph();
The graph is created when the group is created, so what are these validity checks for? Can it ever be null?

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +	exit_group_button->set_tooltip_text(TTR("Exit currently editing group."));
```suggestion
	exit_group_button->set_tooltip_text(TTRC("Exit the currently edited group."));
```

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/shader_graph.h
> +class ShaderGraph : public RefCounted {
Why is ShaderGraph RefCounted? Its lifecycle is pretty much tied to the parent VisualShader/Group, so it's guaranteed to be valid while the parent shader is valid. Can graphs be shared between shaders/groups? If no, this could be an Object.

2026-08-05 08:43 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +			Button *edit_group_btn = memnew(Button);
The Edit button should be disabled when no group is assigned.

2026-08-05 09:17 UTC, Geometror commented on doc/classes/VisualShaderNodeGroup.xml
> +		If the group contains several outputs only the first one will be used.
Sorry, this is worded badly/partially outdated. This refers to group output nodes, not group outputs/outtput ports. The idea is that you can later add multiple output nodes and switch the active one, like in blender (to swap out the group-internal graph).
You can already add multiple group output nodes within a group (which simplifies validation a lot, so I already allow it), but right now a warning is emitted when you do that until this feature is fully implemented:
<img width="444" height="193" alt="{B61E17BE-56B7-4DB7-A03D-1F8170A861F1}" src="https://github.com/user-attachments/assets/f5988a13-d35e-447b-8016-3b72c5253526" />

2026-08-05 09:31 UTC, Geometror commented on doc/classes/VisualShaderNodeGroup.xml
> +		If the group contains several outputs only the first one will be used.
I think we can remove the comment, since the warning already covers this.

2026-08-05 09:40 UTC, Geometror commented on modules/visual_shader/visual_shader_group.h
> +#include "modules/visual_shader/visual_shader.h"
Changed them to be relative, although I'm a bit confused here. The original PR that moved VS to a module used absolute paths, so I just copied that. What do you mean with "The includes in other files are wrong"?

2026-08-05 10:32 UTC, Geometror commented on modules/visual_shader/visual_shader_group.cpp
> +	while (port_name.length() && !is_ascii_alphabet_char(port_name[0])) {
Yes, the port names are used for the parameters of the generated function and GLSL does not allow unicode for identifiers.

2026-08-05 10:38 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.h
> +#include "modules/visual_shader/visual_shader.h"
That the PR did it wrong, see https://github.com/godotengine/godot/pull/64596#discussion_r3715814780

2026-08-05 11:12 UTC, Geometror commented on modules/visual_shader/visual_shader_group.cpp
> +		port_name = port_name.substr(1);
This was basically copy-pasted from VisualShader::validate_port_name. Fixed it.

2026-08-05 11:27 UTC, Geometror commented on modules/visual_shader/shader_graph.h
> +class ShaderGraph : public RefCounted {
Primarily because of Undo/Redo. The editor itself now directly works with `ShaderGraph`s, so this is much safer and cleaner IMO since you can work with Refs. I guess we could make it an Object, but I don't see a clear benefit (overhead certainly isn't one I think).

2026-08-05 14:56 UTC, Geometror commented on modules/visual_shader/shader_graph.cpp
> +		Shader::Mode p_mode) const {
Yes, I thought of that too, we could replace the parameters (partially) with something like `CodeGenContext`. But we need to be careful since the parameters have different lifetimes. If you want, I can do it, however, I'd rather not extend this PR's refactoring work even furtther at this point.

2026-08-05 15:04 UTC, Geometror commented on modules/visual_shader/register_types.cpp
> +		GDREGISTER_INTERNAL_CLASS(ShaderGraph);
ShaderGraph should not be exposed (yet). I'd only do it if people actually need this. And I think internal classes are for exactly that, no?

2026-08-05 15:39 UTC, Geometror commented on modules/visual_shader/visual_shader_group.cpp
> +void VisualShaderGroup::_bind_methods() {
I exposed this for editor plugins.

2026-08-05 15:42 UTC, Geometror commented on modules/visual_shader/visual_shader_group.cpp
> +	group_name = RTR("Node group");
Oh, hmm, the revert button is bad, but in general default names should be translated, right? At least that's how it works in many apps/games. (however I'm not sure if we do that within Godot somewhere).

Applied your suggestion for now.

2026-08-05 15:51 UTC, Geometror commented on modules/visual_shader/visual_shader_group.cpp
> +	// calling the group function.
Well, but that's the point. You can fully read the comment in an editor with ~120 chars width (that explains the code below). If both cut out, you need to scroll. But the breaking point could be improved, and arguably the long line below could also be broken up.

2026-08-05 15:58 UTC, Geometror commented on modules/visual_shader/visual_shader_group.cpp
> +	return warning_str.trim_suffix("\n");
Replaced, although I don't like this weird Pythonesce join syntax ;)

2026-08-05 16:03 UTC, Geometror commented on modules/visual_shader/visual_shader_group.cpp
> +String VisualShaderGroup::_validate_port_name(const String &p_port_name, int p_port_id, bool p_output) const {
I pulled part of this in a sanitize_port_name function which is used by both port name validation functions.

2026-08-05 17:03 UTC, Geometror commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +void VisualShaderEditor::_restore_graph_context(int p_shader_type, TypedArray<VisualShaderGroup> p_group_stack) {
Wait, what exactly do you mean with "weird internal sub-editor"? 
There are valid reasons for this. I'm actually pretty happy with the system around this, given the many constraints implied by shader types/modes. We need some context for validation, since not all nodes are allowed for every shader type for example.
When having a complex shader with many node groups, many of which can be nested, I can edit those, jump in and out of them, and when I want to undo/redo stuff, the shader editor jumps to the correct graph where each action happened; _restore_graph_context ensures this. What's missing there related to UX is some kind of breadcrumb navigation menu, like we already have for the AnimationTree editor (also present in Blender).
The current implementation can also be extended to provide context for port preview shaders (the ones on the bottom of shader nodes), so we can have them use the actual inputs/partial graphs feeding into the specific group instance clicked to open the group. This could be a significant UX improvement.

> VisualShaderGroup should really be editable as a document in the Shader Editor

There isn't a conflict with the current implementation (this was also one of the design goals). The thing you describe (editing a node group directly/standalone) is on my TODO list, and was planned to be implemented as a follow-up.
Also, an action still has to know which graph and shader type it applied to before it "replays". Document-based editing changes how you navigate to a group; it doesn't remove the need to restore graph context on undo.

2026-08-05 23:52 UTC, Calinou reviewed
Tested locally, it works as expected.

Example with a group that brightens a color with an orange tint:

<img width="800" height="675" alt="Image" src="https://github.com/user-attachments/assets/30927bca-449e-4121-8f73-3194f8cb8d9f" />

I've tested the output in normal + headless PCK export (with `.godot/` removed before each export) and both work correctly.

Nested groups work, although I was able to get a shader compilation error once (I unfortunately can't reproduce it):

```
--res://new_shader.tres--
   26 | 
   27 | 
E  28->  group_Node_group_734b3b5c(, n_out1p0);
   29 | 
   30 | 
SHADER ERROR: Expected expression, found: 'COMMA'.
          at: (null) (res://new_shader.tres:28)
ERROR: Shader compilation failed.
   at: (servers\rendering\renderer_rd\forward_clustered\scene_shader_forward_clustered.cpp:185)
```

In terms of UX, I actually found this fairly intuitive to use, although "group" isn't the most obvious name for creating functions when you're used to text shaders. https://github.com/godotengine/godot/pull/88981 could help with this by adding `[Function]` as a shortcut notation, so that it'll appear when entering "function" in the node search.

Some feedback:

- The default name "Node group" should be "NodeGroup", as we use title case with no spaces for node names:

<img width="277" height="203" alt="Image" src="https://github.com/user-attachments/assets/1731317b-58fd-473d-ab06-d7a53afcb4dd" />

<img width="205" height="91" alt="Image" src="https://github.com/user-attachments/assets/8dd07d37-9beb-4b22-bbe6-679a7d647f33" />

- Clicking the edit button has no effect if there is no VisualShaderGroup resource assigned. I suggest either hiding the button in this case, or making it automatically create a new VisualShaderGroup resource (then edit this new group) when clicked.

- More generally, we could probably automatically create a new VisualShaderGroup resource each time you create a VisualShaderGroupNode in the visual shader editor. This would follow the workflow established by https://github.com/godotengine/godot/pull/88647 (and which was already present in nodes like Curve2D with `PROPERTY_USAGE_EDITOR_INSTANTIATE_OBJECT` beforehand).

  - That said, one of the behaviors mentioned above should still be implemented in case you clear the default VisualShaderGroup resource.

- As an aside, I noticed the `<empty>` text doesn't fit in full. This isn't the only location in the editor where it's an issue:

<img width="264" height="99" alt="Image" src="https://github.com/user-attachments/assets/ea29e2b6-e62e-415a-b765-019f4c0018ee" />

Maybe switching the placeholder to `(empty)` will reduce the number of these occurrences.

- The margin at the bottom of the node should be increased slightly (or a margin should be added to the error message), so that the error message doesn't appear too close to the bottom of the node. Compare with the output node on the right:

<img width="520" height="212" alt="Image" src="https://github.com/user-attachments/assets/15a611e4-4d56-4a39-8313-bb198afd07c6" />

- "Edit ports" button should be "Edit Ports":

<img width="183" height="113" alt="Image" src="https://github.com/user-attachments/assets/248926ce-b48e-4ce5-a166-1f6884b96d8f" />

The same applies to the dialog titles, which should also use Title Case:

<img width="195" height="83" alt="Image" src="https://github.com/user-attachments/assets/828f91e3-ad8d-4581-a462-e0c807e8d352" />

- Opening the Edit Group Ports dialog on the input/output when there are no parameters yet should automatically create one parameter, as you'll always need at least one. This saves a click.

- When adding a new parameter in the Edit Group Ports dialog, it should use type of the currently specified parameter. This makes it faster to add several parameters that aren't of the Float type (adding several Vector3/Vector4 in a row is common).

- Exiting a group could be made more obvious somehow, perhaps by adding a tinted background behind the "exit" button, similar to node-specific menus in the 3D editor:

<img width="275" height="52" alt="Image" src="https://github.com/user-attachments/assets/c94da51c-3b28-41a8-af1c-e26018ba22ba" />

<img width="296" height="43" alt="Image" src="https://github.com/user-attachments/assets/36e406a6-c188-4ffd-95f2-39154f88a688" />

The highlight should be less strong than a pressed button (i.e. less strong than the Toggle Shader Preview button besides it on the above screenshot).

For future PRs:

- It could be possible to drag-and-drop a VisualShaderGroup resource to the visual shader to create a VisualShaderGroupNode with the group automatically assigned.

2026-08-05 23:52 UTC, Calinou commented on doc/classes/VisualShaderGroup.xml
> +		If the group contains nodes that are incompatible with the shader context it is used in (e.g. particle nodes in a spatial shader), the group's outputs will silently fall back to default values.
Each line break creates a new paragraph in the class reference, so they should be used sparingly:

```suggestion
		A [VisualShaderGroup] encapsulates a graph of [VisualShaderNode]s into a reusable component. It defines its own input and output ports, which become the interface when the group is used as a [VisualShaderNodeGroup] node inside a [VisualShader] or another [VisualShaderGroup].
		Since an actual shader function is created for each [VisualShaderGroup], you can only use global built-in variables. Parameter and Varying related nodes are not allowed.
		If the group contains nodes that are incompatible with the shader context it is used in (e.g. particle nodes in a spatial shader), the group's outputs will silently fall back to default values.
```

2026-08-05 23:52 UTC, Calinou commented on doc/classes/VisualShaderNodeGroup.xml
> +		If the group contains several outputs only the first one will be used.
Remove the outdated note as per the discussion:

```suggestion
		Represents a [VisualShaderGroup] inside a [VisualShader] or another [VisualShaderGroup]. Its input and output ports are defined by the assigned [member group] resource.
		If the group contains nodes incompatible with the current shader context, the outputs will use default values and a warning will be shown.
```

2026-08-06 00:19 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +	group_name = RTR("Node group");
Well, they can be translated, but not in a property value 🙃

And as I mentioned in another comment, none of the node titles are marked for translation, and the group name is only displayed as a title.

2026-08-06 00:20 UTC, KoBeWi commented on modules/visual_shader/shader_graph.cpp
> +		Shader::Mode p_mode) const {
It's something for another PR.

2026-08-06 00:20 UTC, KoBeWi commented on modules/visual_shader/register_types.cpp
> +		GDREGISTER_INTERNAL_CLASS(ShaderGraph);
No, I have no idea what internal classes are for xd
If you don't want to expose something, just don't register it. GDREGISTER_INTERNAL_CLASS seems to be used for only one class.

2026-08-06 00:57 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +void VisualShaderEditor::_restore_graph_context(int p_shader_type, TypedArray<VisualShaderGroup> p_group_stack) {
> Wait, what exactly do you mean with "weird internal sub-editor"?

Right now you can edit a group only as part of a shader. And opening a group _takes over_ the opened file. Like, you can switch to another file, then switch back to your shader, but you don't see your shader, you see a group that happens to be on top of some "edit stack". That's... uh, not exactly friendly.

But if it's planned to be improved then fine. And yeah, the current behavior can co-exist with document-based one.

> Also, an action still has to know which graph and shader type it applied to before it "replays". Document-based editing changes how you navigate to a group; it doesn't remove the need to restore graph context on undo.

Huh? I don't see why it wouldn't be possible to get rid of this. I mean, a performed action cannot be changed once on undo stack, so it's not like you can do something invalid by undoing it, like idk, add incompatible node type. Any examples of actions that can be invalid without restoring context?

We do have some editors (like TileSet editor) that have to keep "context" as part of undo stack, but that's because they aren't editing the actual resource, but a proxy object. That's not really the case here.

2026-08-06 11:02 UTC, Geometror commented on modules/visual_shader/visual_shader.h
> +	static constexpr int NODE_ID_OUTPUT = 0;
Oh, this now possible. (I'm pretty sure this failed in the past, but I'm not sure)
```
	BIND_CONSTANT(ShaderGraph::NODE_ID_INVALID);
	BIND_CONSTANT(ShaderGraph::NODE_ID_OUTPUT);
```

2026-08-06 11:04 UTC, Geometror commented on modules/visual_shader/visual_shader.h
> +	// Keep in sync with ShaderGraph::Type.
Yes :/ I remember trying a few things, but everything just got more messy, so I think this is the best we can do for now.

2026-08-06 11:07 UTC, Geometror commented on modules/visual_shader/visual_shader_group.cpp
> +			} else if (port_name[i] == ' ') {
Changed to validate_ascii_identifier()

2026-08-06 11:09 UTC, AThousandShips commented on modules/visual_shader/shader_graph.cpp
> +	ERR_FAIL_COND_V(p_port < 0 || p_port >= node->get_expanded_output_port_count(), String());
```suggestion
	ERR_FAIL_INDEX_V(p_port, node->get_expanded_output_port_count(), String());
```

2026-08-06 11:27 UTC, Geometror commented on doc/classes/VisualShaderNodeGroup.xml
> +		If the group contains several outputs only the first one will be used.
Already done locally. I accumulate all review changes and will push them later in one batch to save CI time

2026-08-06 11:50 UTC, Geometror commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +// separate resources, so save them here too.
Yes, the problem is that the editor now works directly on the ShaderGraph abstraction (and ShaderGraph is no Resource), so Undo/Redo does not call `set_edited`. I guess we could set it manually in _queue_update ?
(and then check for this in _save_nested_groups)

2026-08-06 11:58 UTC, Geometror commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +		Ref<ShaderGraph> graph = current->get_graph();
Nope, those are unnecessary, removed them.

2026-08-06 12:36 UTC, Geometror commented on modules/visual_shader/register_types.cpp
> +		GDREGISTER_INTERNAL_CLASS(ShaderGraph);
Maybe it's worth it to keep it registered? See https://github.com/godotengine/godot/pull/119352
We might have a similar problem here, since `graph_changed` is decleared by ShaderGraph. And that could happen on a ResourceLoader worker thread, right?

2026-08-06 13:00 UTC, KoBeWi commented on modules/visual_shader/register_types.cpp
> +		GDREGISTER_INTERNAL_CLASS(ShaderGraph);
I guess that makes sense.

2026-08-06 13:51 UTC, Geometror commented
Thanks for your thorough reviews!
Addressed most of the review comments and rebased.

@KoBeWi
> I noticed that Group Input/Output nodes can be removed from the group (with Delete). The editor does not support it properly, so it should be blocked I think.

I actually think we should leave it like that. I had it implemented at some point, but honestly it wasn't worth the ugly editor code. IMO there is no UX shortcoming. You can delete the output node such as any other node and add it back in.

@Calinou
For opening a group, I'd like to completely get rid of the button. You should be able to edit the group by double-clicking the group node, clicking the group resource in the picker and via a context menu entry IMO. What do you think?
I didn't touch the margin below the error message because that's unrelated to this PR.

> Exiting a group could be made more obvious somehow, perhaps by adding a tinted background behind the "exit" button, similar to node-specific menus in the 3D editor:

I think this would be improved by the breadcrumb menu where you could click on the respective layer to jump there. For now maybe we should move the button somewhere else? I'm not that convinded by the background tint tbh.

2026-08-06 14:44 UTC, Calinou commented
> For opening a group, I'd like to completely get rid of the button. You should be able to edit the group by double-clicking the group node, clicking the group resource in the picker and via a context menu entry IMO. What do you think?

Sounds good to me for desktop, but I'm not sure if this pattern would work well on a touchscreen on the Android editor.

cc @syntaxerror247 

> I think this would be improved by the breadcrumb menu where you could click on the respective layer to jump there. 

Definitely :slightly_smiling_face: 

> For now maybe we should move the button somewhere else? 

The issue is that if we move the button to the left, it will cause all other buttons to shift whenever you're not in a group and the button is invisible. That is, unless we disable the button instead of hiding it when outside a group.

2026-08-07 09:10 UTC, AThousandShips commented on modules/visual_shader/visual_shader.cpp
> +#include "modules/visual_shader/shader_graph.h"
```suggestion
#include "shader_graph.h"
```

2026-08-09 21:19 UTC, Geometror commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +void VisualShaderEditor::_restore_graph_context(int p_shader_type, TypedArray<VisualShaderGroup> p_group_stack) {
Sorry, I lost track of what was already answered :) I also went through some of my notes, which contained the decisions I made over a year ago and did a bit of research, since this isn't that fresh anymore in my head :)

> Huh? I don't see why it wouldn't be possible to get rid of this. I mean, a performed action cannot be changed once on undo stack, so it's not like you can do something invalid by undoing it, like idk, add incompatible node type. Any examples of actions that can be invalid without restoring context?

Resizing a node or updating constants for example (which calls `edited_shader_graph->get_node(p_node)` in the do/undo function, so the id gets resolved against the currently opened graph and node ids are per graph)  

> We do have some editors (like TileSet editor) that have to keep "context" as part of undo stack, but that's because they aren't editing the actual resource, but a proxy object. That's not really the case here.

Instead of editing a Resource directly, I transformed the editor to edit the ShaderGraph both VisualShader and VisualShaderGroup share now. Since VisualShader already inherits from Shader and we can't have interfaces via multiple inheritance, I went with composition, so both VS and VSG hold ShaderGraphs (one per shader type in VS, a single one in VSG). I'm pretty happy with how this turned out, however, the editor code changes this came with are a bit exotic and suboptimal.
A lot of editor code works with the edited_shader_graph which therefore needs to be restored. Just like before, each undo/redo action first does the data layer manipulations and then updates the view via VisualShaderGraphPlugin.
I'm not saying that it isn't possible to implement it without the need to restore the graph context. I'm pretty sure it is, and I can ponder about it if you desire, but it would probably require further extensive refactoring. 
I just tried to adapt it in the most straight-forward way that doesn't hit any roadblocks first. If it were after me and I had infinite time then I'd love to rewrite the whole VS module, because it definitely has its deeply seated flaws ;)
Right now I think this isn't that important, because I actually want to keep the context restoring step (even if it is just for the UX aspect) so that the editor jumps to the correct graph when going through the history. The user should always immediately know what they undid, without looking at the output for example (which isn't that helpful either). This should actually work across the whole shader editor IMO, but that's not implemented yet (and material for another PR). I guess what I'm saying is that trying to clean up the Undo/Redo part could be done later.

2026-08-09 21:26 UTC, KoBeWi commented
> IMO there is no UX shortcoming.

The nodes are force-added every time the group is loaded, so when you remove them, they will be magically back next time, empty. Also removing Input/Output does not update the ports in the parent shader, the group stays connected as if nothing happened.

2026-08-09 22:18 UTC, Geometror commented
@Calinou
> Sounds good to me for desktop, but I'm not sure if this pattern would work well on a touchscreen on the Android editor.

I actually think using double tap is much more touch-friendly than having a separate "Edit" button, because you may accidently tap it when trying to move the group node. (even though I think you don't want to use the VS editor on touch devices at all)

The nodes are force-added every time the group is loaded, so when you remove them, they will be magically back next time, empty. Also removing Input/Output does not update the ports in the parent shader, the group stays connected as if nothing happened.

> The issue is that if we move the button to the left, it will cause all other buttons to shift whenever you're not in a group and the button is invisible. That is, unless we disable the button instead of hiding it when outside a group.

What I had in mind was a "floating" button outside of the menu bar.


@KoBeWi
> The nodes are force-added every time the group is loaded, so when you remove them, they will be magically back next time, empty. 

Ok, this is needs to be fixed. Creating an input and output node should only be done by the editor for convenience once, not on every load.

> Also removing Input/Output does not update the ports in the parent shader, the group stays connected as if nothing happened.

You mean removing a Group Input/Output node? If so, this is expected. Since you're allowed to fully rewire the inside of groups you can have multiple of those for convenience, or none. In practice this will only be temporary, but you should be able to restructure a group - possibly deleting an group input/output node - without changing the actual group inputs and outputs.

2026-08-10 11:02 UTC, KoBeWi commented
> You mean removing a Group Input/Output node? If so, this is expected. Since you're allowed to fully rewire the inside of groups you can have multiple of those for convenience, or none. In practice this will only be temporary, but you should be able to restructure a group - possibly deleting an group input/output node - without changing the actual group inputs and outputs.

Deleting single ports does get reflected in parent shader though. Seems weird to me, idk.

[Nagranie ekranu_20260810_130118.webm](https://github.com/user-attachments/assets/10d57c47-c137-4fb5-9bea-f7677936c80c)

2026-08-15 23:54 UTC, Moinefable approved these changes

2026-08-16 01:33 UTC, Geometror commented
@KoBeWi Well, this design clearly separates interface declaration (ports dialog and the [just added] ports section in inspector) from access, group input/output nodes are just accessors with a convenience button to change the interface. This is the same model Blender uses, and I think it's one of the better ones out there and people are used to it. However I don't want to disguise the fact that Unity and Unreal's native material/shader graph systems both combine interface declaration and access. I think each port is defined by exactly one node, which might be more straight-forward, but that's arguable.

I've made a few important changes:
- From now on, adding a group instance node via the editor automatically adds a new node group containing a group input and output node, they are no longer created when setting an empty group 
- Input and output ports can now also be edited in the inspector (without entering the group), not just via the group input/output dialog (this breaks compat with earlier versions of this PR due to changed serialization by using PropertyListHelper)

For an easier review I kept the commits separate, they can be squashed later.

2026-08-24 09:55 UTC, KoBeWi approved these changes
Looks good enough now.
I noticed some of my comments were marked as resolved, without being resolved .-.

2026-08-24 09:55 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.h
> +	PropertyListHelper output_port_property_helper;
Seems like you don't implement `_property_has_revert()` and `_property_get_revert()`, so reverting port properties is not available. Is this intended?

2026-08-24 09:55 UTC, KoBeWi commented on modules/visual_shader/visual_shader_group.cpp
> +	return warning_str.trim_suffix("\n");
Doesn't seem replaced.

2026-08-24 09:55 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +			edit_group_btn->set_tooltip_text(TTR("Edit"));
Still not changed.

2026-08-24 09:55 UTC, KoBeWi commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +		Ref<ShaderGraph> graph = current->get_graph();
Doesn't seem removed.

2026-08-24 23:54 UTC, Geometror commented on modules/visual_shader/editor/visual_shader_editor_plugin.cpp
> +		Ref<ShaderGraph> graph = current->get_graph();
Oh, looks like I removed all of those checks in visual_shader_group.cpp, but missed this one :/

2026-08-25 00:14 UTC, Geometror commented on modules/visual_shader/visual_shader_group.h
> +	PropertyListHelper output_port_property_helper;
I decided to leave it, because the port name is validated and auto-renamed to avoid conflicts, so e.g. if you add two ports without renaming one, the first gets the name "new_in_port" and the second "new_in_port2". Now the second gets a revert button which is stuck until there is no longer a conflict and the default name is free.

2026-08-25 01:13 UTC, Geometror commented
@KoBeWi Sorry, one of those was an oversight, but for the others I honestly can't remember. (Could be a missclick, since this GH thread is so slow in my browser, especially when all review comments are expanded; I'm literally writing my answers in notepad and copy them because the embedded text editors are unusable :) Does anyone else have this problem?)
Anyways, thanks for the thorough review! 

Rebased and once CI passes this should be ready to go.

2026-08-25 17:19 UTC, merged

2026-08-25 17:19 UTC, Repiteo commented
Thanks! This PR has been a long-time coming, so it's exciting to finally have it ready to roll!

2026-10-29 20:59 UTC, gnat commented
The removal of the call to `validate_parameter_name()` from `VisualShader::add_node()` is causing multiple regressions in tools, specifically in the very popular [Unreal to Godot Exporter](https://www.fab.com/listings/61983625-664c-4308-9b26-edfd58d41002) and likely the [Unity to Godot Exporter](https://relativegames.gumroad.com/l/unitytogodot) as well -  @Repiteo @Geometror 

This call did two things:
1. Renamed parameters that collided with existing parameter names.
2. Corrected invalid characters, including spaces.

## Breakage 1:

`validate_parameter_name()` handled `parameter_name` collisions automatically.

Big problem because underscores do not count towards a unique `parameter_name`.

`parameter_name = "BaseColor_Texture"` clashes with `parameter_name = "BaseColor_Texture__"` which breaks the Visual Shader. Quite common when exporting from Unreal Engine (we must remove special characters unsupported by godot and replaced by `_`) 

<img width="855" height="161" alt="image" src="https://github.com/user-attachments/assets/c0d4a30a-0a16-44d8-8baf-7b710c570866" />

This will break ongoing game projects which have already imported Visual Shaders.

## Breakage 2: 

**Unreal to Godot Exporter** retains spaces in `parameter_name` entries. This can be resonably patched on the **Unreal to Godot Exporter** side, but still, this is a tool compatibility regression caused by removal of `validate_parameter_name()` from `VisualShader::add_node()`, causing broken Visual Shaders. 

This will break ongoing game projects which have already imported Visual Shaders.

2026-10-30 06:35 UTC, gnat commented
Working patch. @Repiteo @Geometror

```diff
diff --git a/modules/visual_shader/visual_shader.cpp b/modules/visual_shader/visual_shader.cpp
--- a/modules/visual_shader/visual_shader.cpp
+++ b/modules/visual_shader/visual_shader.cpp
@@ -1023,6 +1023,12 @@
 void VisualShader::add_node(Type p_type, const Ref<VisualShaderNode> &p_node, const Vector2 &p_position, int p_id) {
 	ERR_FAIL_INDEX(p_type, TYPE_MAX);
 	Ref<ShaderGraph> g = graph[p_type];
+	Ref<VisualShaderNodeParameter> parameter = p_node;
+	if (parameter.is_valid()) {
+		parameter->set_parameter_name(validate_parameter_name(parameter->get_parameter_name(), parameter));
+	}
+
 	g->add_node(p_node, p_position, p_id);
 
 	Ref<VisualShaderNodeInput> input = g->get_node(p_id);
```