Detect newer Visual Studio compilers correctly like VS2017.
godotengine/godot pull request #9940
Opened 2017-07-28 04:41 UTC by brenttaylor

This is just a cherry-picked commit.  Adds proper detection of VS2017 so we're not locked to VS2015.

2017-07-28 13:51 UTC, vnen requested changes
This will break older toolsets.

2017-07-28 13:51 UTC, vnen commented on methods.py
> +    vc_amd64_compiler_detection_index = tools_env["PATH"].upper().find(tools_env['VCTOOLSINSTALLDIR'].upper() + "BIN\\HOSTX64\\X64;")
This fails if `VCTOOLSINSTALLDIR` is not set, which is the case for versions before 2017. Add the changes from 8b01f9d28ffccb21db04867d1265f0be9d40aa53 to make it work properly.

2017-07-28 22:05 UTC, brenttaylor commented on methods.py
> +    vc_amd64_compiler_detection_index = tools_env["PATH"].upper().find(tools_env['VCTOOLSINSTALLDIR'].upper() + "BIN\\HOSTX64\\X64;")
Oof, good catch.  I'll get that done today.

2017-08-04 08:14 UTC, akien-mga commented on methods.py
> +    vc_amd64_compiler_detection_index = tools_env["PATH"].upper().find(tools_env['VCTOOLSINSTALLDIR'].upper() + "BIN\\HOSTX64\\X64;")
Bump.

2017-08-11 08:31 UTC, akien-mga commented
Closing as it is getting stale. Feel free to open a new PR with the necessary changes mentioned by @vnen above.

2017-08-11 08:31 UTC, closed without merging