Disable the debugger thread selector when there's nothing to select
godotengine/godot pull request #99417
Opened 2024-11-19 04:25 UTC by passivestar

A small UI fix. Empty lists just have this tiny rectangle appear when there's nothing in them and it looks broken

| Old | New |
|--------|--------|
| ![1](https://github.com/user-attachments/assets/24330523-76f9-4431-bcb2-7a745699fa0c) | ![2](https://github.com/user-attachments/assets/0abcdff7-7cee-474b-9eba-475ebf7c8ed9) |

2024-11-19 12:58 UTC, Geometror approved these changes

2024-11-19 13:07 UTC, Geometror requested changes
![grafik](https://github.com/user-attachments/assets/32822c27-9900-452b-ac0e-a4b4a088c810)

When starting the project it's still active and empty until you reach a breakpoint/pause the project. You should probably check for the thread count instead of the `active` flag.

2024-11-20 13:23 UTC, Geometror approved these changes

2024-11-26 19:13 UTC, merged

2024-11-26 19:14 UTC, Repiteo commented
Thanks!