Fix broken includes when compiling with builtin_miniupnpc=false
godotengine/godot pull request #99556
Opened 2024-11-22 19:26 UTC by ArchercatNEO

Fixes https://github.com/godotengine/godot/issues/99196

2024-11-22 19:30 UTC, akien-mga commented on modules/upnp/SCsub
> +    env_thirdparty.Prepend(CPPPATH=[thirdparty_dir + "include/miniupnpc"])
Shouldn't it be this so it resolves the `miniupnpc/` part of the includes?
```suggestion
    env_thirdparty.Prepend(CPPPATH=[thirdparty_dir + "include"])
```

2024-11-22 20:51 UTC, RadiantUwU approved these changes
Compiled successfully with `builtin_miniupnpc=false` on Arch Linux 6.11.8-arch1-2

2024-11-23 03:55 UTC, akien-mga approved these changes
Looks good!

2024-11-25 22:49 UTC, Repiteo requested changes
Will need a rebase, as well as a minor `README.md` tweak
```diff
 thirdparty/README.md | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/thirdparty/README.md b/thirdparty/README.md
index 7a95e3c724..760ff0a1e6 100644
--- a/thirdparty/README.md
+++ b/thirdparty/README.md
@@ -628,7 +628,8 @@ to solve some MSVC warnings. See the patches in the `patches` directory.
 
 Files extracted from upstream source:
 
-- Copy `miniupnpc/src` and `miniupnpc/include` to `thirdparty/miniupnpc`
+- `miniupnpc/src/` as `src/`
+- `miniupnpc/include/` as `include/miniupnpc/`
 - Remove the following test or sample files:
   `listdevices.c,minihttptestserver.c,miniupnpcmodule.c,upnpc.c,upnperrors.*,test*`
 - `LICENSE`
```

2024-11-27 16:07 UTC, akien-mga approved these changes

2024-11-27 17:11 UTC, Repiteo approved these changes

2024-11-29 21:10 UTC, merged

2024-11-29 21:13 UTC, akien-mga commented
Thanks! And congrats for your first merged Godot contribution :tada: