Fix "occured" typo
godotengine/godot pull request #99609
Opened 2024-11-24 00:54 UTC by aaronellington

2024-11-24 03:03 UTC, tetrapod00 reviewed
I can't speak to whether this is a big enough change to be worth a PR, but if it is, it looks like there are several instances of changes to thirdparty files, and also a couple other changes that *might* need to be made.

2024-11-24 03:03 UTC, tetrapod00 commented on misc/dist/html/editor.html
> +			setStatusNotice('An unknown error occurred');
```suggestion
			setStatusNotice('An unknown error occurred.');
```
I'm not sure of the context of these messages, but it's possible that they should be sentence case with a period, if we're already updating them. There is another similar instance.

2024-11-24 03:03 UTC, tetrapod00 commented on thirdparty/basis_universal/encoder/basisu_comp.cpp
> +				// Stop using OpenCL if a failure ever occurrs.
```suggestion
				// Stop using OpenCL if a failure ever occurs.
```
I don't think this one is right :)

2024-11-24 03:03 UTC, tetrapod00 commented on misc/dist/html/full-size.html
> +			setStatusNotice('An unknown error occurred');
```suggestion
			setStatusNotice('An unknown error occurred.');
```
Possibly this. See other comment for reasoning

2024-11-24 03:20 UTC, Repiteo commented
I'm shocked that this wasn't caught by codespell; might need to add our own dictionary?

2024-11-24 03:46 UTC, tetrapod00 commented
It's in the default codespell dictionary (https://github.com/codespell-project/codespell/blob/da60275a48eabf63a01c4dab6eec3c1bc55408e1/codespell_lib/data/dictionary.txt#L40933-L40933):
```
occured->occurred
```
Possibly something wrong with the codespell setup; on the docs repo it was misconfigured for a while and did not catch deeply or shallowly nested files, only files one directory deep. Or maybe it doesn't check in comments or inside snake case variable names? I'm not super familiar with codespell's limits.

2024-11-24 03:51 UTC, Repiteo commented
Oh wait, the majority of changed cases were third-party files, and codespell deliberately ignores those. Must not recognize snake-case then, or it needs some special setup; not as big of an issue as I thought in either case

2024-11-24 08:58 UTC, AThousandShips requested changes, later dismissed
Third-party files should indeed not be changed

2024-11-24 22:56 UTC, aaronellington commented
Thanks for the feedback. I think I've made all of the requested changes. :)

2024-11-24 23:03 UTC, tetrapod00 commented
Looks reasonable to me now, but still needs approval from the relevant maintainers

2024-11-25 10:36 UTC, AThousandShips approved these changes
This makes sense, but might be better to perform in a bulk change, see:
* https://github.com/godotengine/godot/issues/91521

I'll leave it up to the production team to make the final judgement if this is too small to be appropriate

2024-11-28 16:01 UTC, akien-mga commented
As suggested, this kind of changes are best consolidated together with other similar codebase cleanups, so I went ahead and did that in #99799, which includes those changes.

Thanks for your contribution!

2024-11-28 16:01 UTC, closed without merging

2024-11-28 16:14 UTC, adamscott commented
> I'm shocked that this wasn't caught by codespell; might need to add our own dictionary?

We should maybe contribute it to codespell.