Add missing getter for sharp window corners.
godotengine/godot pull request #99879
Opened 2024-11-30 17:16 UTC by Lielay9

Noticed while issuing #46126, seems to just been forgotten from #97005.

2024-11-30 17:21 UTC, adamscott requested changes
Yes. It does seem that the getter is missing. But I just have just one nitpicky comment about this.

Thanks for your PR!

2024-11-30 17:21 UTC, adamscott commented on platform/windows/display_server_windows.cpp
> +		} break;
I would remove the case here to put it at the same relative place that the setter does it. (just after `WINDOW_FLAG_ALWAYS_ON_TOP`)

```suggestion
```

2024-11-30 17:26 UTC, adamscott approved these changes

2024-11-30 17:56 UTC, Repiteo approved these changes

2024-12-02 14:54 UTC, merged

2024-12-02 14:56 UTC, akien-mga commented
Thanks!