Add 2D CSG boolean operations
godotengine/godot pull request #99911
Opened 2024-12-02 00:24 UTC by smix8

_For now empty draft PR because I need the pr id and link but as can be seen by the animation all nodes and operations are already more or less fully functional._

Adds nodes and functions for 2D CSG boolean operations.

Implements proposal https://github.com/godotengine/godot-proposals/issues/3731

..  and many related proposals that asked for similar functionality just under a different name.
(I need to collect their links, if you find them first add them please).

### Wait, what is CSG?

![csg2d_bake_01](https://github.com/user-attachments/assets/0985e1b2-c20f-4e61-8ce9-3a3461c600bb)

To quote from the older 3D CSG blog that can be found [here](https://godotengine.org/article/godot-gets-csg-support/).

> CSG stands for “Construtive Solid Geometry”, and is a tool to combine basic (and not so basic) shapes to create more complex shapes. In the 3D modelling software, CSG is mostly known as “Boolean Operators”.

So basically you can do everything what you can do currently in scripts using the `Geometry2D` merge and slice related boolean operation functions but more convenient with nodes and there also plenty of extra features on top.

Largely copies the workflow and nodes from the 3D CSG although accounting for some specific 2D quirks.

![csg2d](https://github.com/user-attachments/assets/674536ca-2e3c-40e3-84a2-708879561d92)

### CSG Operators

The available operators are the same as in 3D:
- UNION
- INTERSECTION
- SUBTRACTION

Operations are done in node tree order same as in 3D, or to quote from the old CSG 3D blog.

> Every CSG node will first process it’s children nodes (an their operation: union, intersection substraction), in tree order and apply them to itself one after the other.

### Baking CSG results to static geometry

![csg_menu_bake](https://github.com/user-attachments/assets/ae3c4f56-5d23-4897-b054-59be16f27bf0)

Same as 3D PR https://github.com/godotengine/godot/pull/93252

CSG options to bake to static mesh and collision shape same as 3D has, aka you can "design" your stuff with CSG and bake the result to a more efficient static version for performance (or to avoid physics collision seam issues).

- Bake to MeshInstance2D
- Bake to CollisionShape2D

```
var baked_mesh: ArrayMesh = CSGShape2D.bake_static_mesh()
var baked_shape: ConcavePolygonShape2D = CSGShape2D.bake_collision_shape()
```

The jury is still out if there is need for conversion to other node types e.g. Polygon2D.

### Why name it CSG in 2D?
Although CSG "Construtive Solid Geometry” is more a name used in 3D modelling context I stayed with the name for 2D because users are already very familiar with the term in Godot from 3D. The 2D and 3D nodes and workflows are kept very similar on purpose as it allows better knowledge and documentation sharing.

2024-12-02 01:08 UTC, fire commented
Awesome, need some time to test and fix up the integration tests but looks promising.

2024-12-10 16:24 UTC, Calinou reviewed
Tested locally, it works as expected.

**Testing project:** [test_csg_2d.zip](https://github.com/user-attachments/files/18082748/test_csg_2d.zip)

![image](https://github.com/user-attachments/assets/7f71ab3b-8a30-49f7-8597-6225e51368da)

Some feedback:

- When **Use Vertex Color** is disabled, the CSG node will have a different appearance in the editor compared to the running project:

Editor | Running project
-|-
![image](https://github.com/user-attachments/assets/68dd43ab-348a-4ac8-b0c2-d15ed314a423) | ![image](https://github.com/user-attachments/assets/4661131a-5547-46e5-9825-ab2762db2ab0)

When enabled, it has the same appearance in the editor and running project. I'm guessing this may occur because when **Use Vertex Color** is disabled, the shape is still drawn in white but is drawn *behind* the debug gizmos.

- When **Use Vertex Color** is disabled, the Vertex Color property should be hidden in the inspector.

2024-12-10 16:34 UTC, smix8 commented
> When enabled, it has the same appearance in the editor and running project. I'm guessing this may occur because when **Use Vertex Color** is disabled, the shape is still drawn in white but is drawn _behind_ the debug gizmos.

That half transparent blue hue face color is editor specific to not have white solid shapes in the editor. It swaps that color on the mesh in the ` CSGShape2D::draw_shape()` function based on the editor hint. Same with the inner polygon edge line debug that is not added at runtime.

2024-12-10 16:43 UTC, Calinou commented on modules/csg_2d/doc_classes/CSGShape2D.xml
> +		Consider baking final CSG operation results into static geometry that replaces the CSG nodes.
```suggestion
		[b]Performance:[/b] CSG nodes are only intended for prototyping as they have a significant CPU performance cost. Consider baking final CSG operation results into static geometry that replaces the CSG nodes.
```

2024-12-10 16:45 UTC, Calinou commented on modules/csg_2d/doc_classes/CSGMesh2D.xml
> +		A 2D CSG node that allows to create a shape for the 2D CSG system based on the geometry of a 2d rendering mesh resource.
```suggestion
		A 2D CSG node that allows to create a shape for the 2D CSG system based on the geometry of a 2D rendering mesh resource.
```

2024-12-11 00:19 UTC, smix8 commented
Added some additional debug visuals. It was getting confusing with more CSG brushes involved what brush does what.

 There is now the option to display the CSG brush outline as debug colored by the operation type.
- OPERATION_UNION -> Green
- OPERATION_INTERSECTION -> Orange
- OPERATION_SUBTRACTION -> Red

This option can be enabled per CSG node individually.
By default this debug is off to not clutter the editor view so much.

![brush_debug](https://github.com/user-attachments/assets/c670a283-acfc-428a-8472-92eecf782d8d)

2024-12-11 00:38 UTC, smix8 commented
Pushed the last addition / changes to the PR. I think it is now good for review.

2024-12-11 11:37 UTC, smix8 commented
Added the option to bake the CSG result to a navigation mesh with `bake_navigation_mesh()`.
Added editor menu option to create a NavigationRegion2D with that baked navmesh.

2024-12-12 22:54 UTC, smix8 commented
Added a full fledged polygon editor with toolbar for the CSGPolygon2D.

2024-12-12 23:13 UTC, smix8 commented
Fixed a bug where the CSG would not react when the child node order changes.
This code was a direct copy from the 3D CSG that seem to have the same problem.

2024-12-14 20:30 UTC, Mickeon reviewed
Not much to say on the documentation side. It is actually all borrowed from the 3D equivalents. Its quality varies, but it's better to be consistent here (for the translators' sanity), and adjustments can be made on both another time.

2025-01-08 10:13 UTC, rburing requested changes
This mostly looks great to me! I have just some small comments.

2025-01-08 10:13 UTC, rburing commented on modules/csg_2d/csg_shape_2d.cpp
> +	//RenderingServer::get_singleton()->canvas_item_add_mesh(get_canvas_item(),  root_edge_line_mesh->get_rid(), Transform2D(), color, texture_rid);
I would add a `TODO` or a `FIXME` comment here, if it's not implemented in this PR.

2025-01-08 10:13 UTC, rburing commented on modules/csg_2d/csg_shape_2d.cpp
> +		//RS::get_singleton()->instance_set_transform(root_collision_debug_instance, debug_shape_old_transform);
Same here. (Also this `instance` naming is a bit 3D-ish, but no big deal.)

2025-01-08 10:13 UTC, rburing commented on modules/csg_2d/csg_shape_2d.cpp
> +	//CSGBrush2D *n = _get_brush();
Can be removed.

2025-01-08 10:13 UTC, rburing commented on modules/csg_2d/doc_classes/CSGPrimitive2D.xml
> +		Parent class for various 2D CSG primitives. It contains code and functionality that is common between them. It cannot be used directly. Instead use one of the various classes that inherit from it.
This should say base class like in the brief description.

2025-01-08 10:13 UTC, rburing commented on modules/csg_2d/editor/csg_editor_plugin_2d.cpp
> +			// CSGMesh2D *shape = Object::cast_to<CSGMesh2D>(node);
Add a `FIXME` or `TODO` comment?

2025-01-08 19:18 UTC, smix8 commented on modules/csg_2d/editor/csg_editor_plugin_2d.cpp
> +			// CSGMesh2D *shape = Object::cast_to<CSGMesh2D>(node);
There is not really anything to do here as that `CSGShapeType::MESH_SHAPE` has no editor overlay.

2025-01-08 23:07 UTC, smix8 commented on modules/csg_2d/csg_shape_2d.cpp
> +	//RenderingServer::get_singleton()->canvas_item_add_mesh(get_canvas_item(),  root_edge_line_mesh->get_rid(), Transform2D(), color, texture_rid);
Those collision debug related functions are not really doing something. They exists to stay parallel with the CSG3D in case someone wants to do anything with it. I did not add special collision debug here because it would just create overlap noise in 2D as the default csg 2d visuals already show the edges compared to 3D.

2025-01-09 00:47 UTC, smix8 commented on modules/csg_2d/csg_capsule_2d.h
> +	int get_corner_segments() const;
renamed

2025-01-12 13:01 UTC, rburing requested changes

2025-01-12 16:05 UTC, smix8 commented on modules/csg_2d/csg_capsule_2d.cpp
> +		vertices_cache.resize(radial_segments * 4 + 2);
How about I conjure a quarter circle documentation.

2025-01-23 16:48 UTC, KoBeWi commented
Baking CollisionShape fails for simple case:
![image](https://github.com/user-attachments/assets/03bff50b-f5c3-47cd-8d9a-4e92b32f0f7d)
Either it should create ConcavePolygonShape2D here, or you could add an option for CollisionPolygon2D (or the option could automatically fallback to CollisionPolygon2D if shape fails).

The bigger rectangle for rectangle shape looks weird:
![image](https://github.com/user-attachments/assets/328dbf2e-5ad8-400b-9211-cce1c50051fe)
It makes sense for other shapes, because it allows to make e.g. ovals, but for rectangle it's redundant. They don't need to be scaled I think.

2025-01-23 20:45 UTC, KoBeWi commented on modules/csg_2d/csg_capsule_2d.cpp
> +#ifdef DEBUG_ENABLED
Should be TOOLS_ENABLED.

2025-01-23 20:56 UTC, KoBeWi commented on modules/csg_2d/csg_capsule_2d.h
> +	CSGCapsule2D() {}
```suggestion
```
Empty constructors are unnecessary.

2025-01-23 21:02 UTC, KoBeWi commented on modules/csg_2d/csg_2d.cpp
> +	for (uint32_t i = 0; i < p_outlines.size(); i++) {
```suggestion
	for (const Outline &outline : p_outlines) {
```

2025-01-24 12:52 UTC, KoBeWi commented on modules/csg_2d/csg_shape_2d.h
> +#include "scene/resources/2d/navigation_polygon.h"
These can be forward-declared.

2025-02-12 22:45 UTC, Calinou reviewed
Tested locally, it works as expected.

Some feedback:

- **Bake CollisionShape2D** should be renamed to **Bake CollisionShape2D(s)**, as it can create multiple collision shapes in a single operation if the collision shape is convex but the combiner's shape is concave. When the collision shape is concave, it will also occur if the CSG combiner has multiple disjoint shapes in it. This does not occur with other baking types (even Polygon2D, surprisingly).
- **Bake Polygon2D** does not reuse the vertex color that was defined in CSGCombiner2D, so it resets to white. In comparison, the color is preserved when baking to MeshInstance2D.

2025-02-13 02:06 UTC, smix8 commented
> This does not occur with other baking types ...

There are other bake types that can result into multiple shapes or nodes depending on settings and composition, e.g. the light occluders. I added them but frankly those (s) behind node names look visually poor, especially on buttons.

> Bake Polygon2D does not reuse the vertex color ...

Added that if `use_vertex_color` is enabled on the CSG that the baked Poygon2D has that color copied into the `vertex_colors` property.

2025-02-13 14:40 UTC, Calinou approved these changes

2025-02-13 16:15 UTC, AThousandShips reviewed
Will do a second more in-depth pass over the documentation as well

2025-02-13 16:15 UTC, AThousandShips commented on modules/csg_2d/csg_shape_2d.cpp
> +		ERR_PRINT("CSGShape2D outines to convex polygons conversion failed. Check input geometry for common shape outline and precision errors like self-overlapping shapes used in intersection operations."
To confirm, this isn't a critical situation, it should continue here after failing?

2025-02-13 16:15 UTC, AThousandShips commented on modules/csg_2d/doc_classes/CSGCapsule2D.xml
> +		This node allows to create a capsule for use with the 2D CSG system.
```suggestion
		This node allows creating a capsule for use with the 2D CSG system.
```

2025-02-13 16:15 UTC, AThousandShips commented on modules/csg_2d/doc_classes/CSGCircle2D.xml
> +		A 2D CSG node that allows to create circle shapes or other regular convex polygons for use with the 2D CSG system.
```suggestion
		A 2D CSG node that allows creating circle shapes or other regular convex polygons for use with the 2D CSG system.
```

2025-02-13 16:15 UTC, AThousandShips commented on modules/csg_2d/doc_classes/CSGCombiner2D.xml
> +		For complex arrangements of shapes, it is sometimes needed to add structure to CSG nodes. A CSGCombiner2D node allows to create this structure. The node encapsulates the result of the CSG operation
```suggestion
		For complex arrangements of shapes, it is sometimes needed to add structure to CSG nodes. A CSGCombiner2D node allows creating this structure. The node encapsulates the result of the CSG operations of its children. In this way, it is possible to do operations on one set of shapes that are children of one CSGCombiner2D node, and a set of separate operations on a second set of shapes that are children of a second CSGCombiner2D node, and then do an operation that takes the two end results as its input to create the final shape.
```

2025-02-13 16:15 UTC, AThousandShips commented on modules/csg_2d/doc_classes/CSGMesh2D.xml
> +		A 2D CSG node that allows to create a shape for the 2D CSG system based on the geometry of a 2D rendering mesh resource.
```suggestion
		A 2D CSG node that allows creating a shape for the 2D CSG system based on the geometry of a 2D rendering mesh resource.
```

2025-02-13 16:15 UTC, AThousandShips commented on modules/csg_2d/doc_classes/CSGPolygon2D.xml
> +		A 2D CSG node that allows to create a polygon for use with the 2D CSG system. For CSG union and intersection operations the polygon can be arbitrarily shaped. For CSG subtraction operations the pol
```suggestion
		A 2D CSG node that allows creating a polygon for use with the 2D CSG system. For CSG union and intersection operations the polygon can be arbitrarily shaped. For CSG subtraction operations the polygons must be non-self-overlapping.
```

2025-02-13 16:15 UTC, AThousandShips commented on modules/csg_2d/doc_classes/CSGRectangle2D.xml
> +		A 2D CSG node that allows to create a rectangle for use with the 2D CSG system.
```suggestion
		A 2D CSG node that allows creating a rectangle for use with the 2D CSG system.
```

2025-02-13 20:25 UTC, KoBeWi commented
From the things I reported previously, only the polygon color was fixed.
You should fix at least debug brushes, because they are completely broken with undo and duplication.

You could also resolve my point about failed CollisionShape2D baking. Polygon2D is already an option, so fallback to CollisionPolygon2D is possible too. CollisionShape2D and PolygonShape2D are more or less interchangeable and you can use the same data as in Polygon2D.
![image](https://github.com/user-attachments/assets/4a425665-f22b-4d72-94db-ebdda643c338)

> I added it for consistency with other 2d toolings. In general I do not like scaling of 2d nodes

Then you don't need to add it ;)
Especially for CSGRectangle2D it's almost useless and looks ugly. Scaling is still possible without gizmos with the Scale Tool.

2025-02-13 21:47 UTC, smix8 commented on modules/csg_2d/csg_shape_2d.cpp
> +		ERR_PRINT("CSGShape2D outines to convex polygons conversion failed. Check input geometry for common shape outline and precision errors like self-overlapping shapes used in intersection operations."
It needs to run the code past that point for e.g. redraw so that the visuals actually update with the failed state.

2025-06-09 22:29 UTC, smix8 commented
I rebased to not be 3500++ PRs behind master (time flies).

- Addressed the documentation comments from ship (I think?)
- Removed the Node2D related scaling boxes.

2025-06-09 22:35 UTC, smix8 commented on modules/csg_2d/csg_shape_2d.h
> +#include "scene/2d/node_2d.h"
Removing this include breaks the build.

2025-06-10 09:16 UTC, AThousandShips approved these changes

2025-06-11 10:51 UTC, KoBeWi commented
> The fallback to CollisionPolygon2D is imo not a solution to do by default because that polygon is just a visual outline that also need to convert to convex polygons or segments when used as collision. If a user sets it to convex it will break either way when the input breaks it as it uses the same convex decomp behind the scene as the csg.

Right now there is no way to make CollisionPolygon2D at all. You need to make Polygon2D and then change type, afterwards the polygon works correctly. I don't see why this can't be an option. The reason conversion "fails" is because CollisionShape2D is very limited. You can't bake e.g. a triangle, which is a perfectly valid shape.
![image](https://github.com/user-attachments/assets/7e39c3f0-b25a-4842-bc8a-b56582b42fca)

2025-06-11 11:12 UTC, KoBeWi commented on modules/csg_2d/csg_shape_2d.cpp
> +	shape_update_forced = true;
This seems unused.

2025-06-11 20:22 UTC, smix8 commented
@KoBeWi silly question but did you forget to enable `use_collision` in your tests on the root node?
> Note that certain Editor toolbar menu bake options (see further below) require that collision is enabled. Without collision enabled some of the very expensive shape data is not created so it can not be exported.

Because without `use_collision` enabled I get the very same bake errors as you with that same node and shape setup. With collision enabled it all works just fine for me.

2025-06-11 20:37 UTC, KoBeWi commented
This needs to be mentioned somewhere. Also collision baking should be disabled when `use_collision` is disabled, if it does nothing.

2025-06-11 21:00 UTC, smix8 commented on modules/csg_2d/csg_shape_2d.cpp
> +	shape_update_forced = true;
removed

2025-06-11 21:14 UTC, KoBeWi commented on modules/csg_2d/csg_shape_2d.cpp
> +	_update_shape();
Now you could just make `_update_shape()` public.

2025-06-12 07:29 UTC, akien-mga commented
Moving this to the 4.6 milestone as we're entering feature freeze.
Implementation wise this PR seems mostly ready so it could nearly have made it into 4.5 before freeze, but after discussion we think that we need some more time to evaluate how needed this feature is in the first place.

The proposal it implements got a total of 4 upvotes in 4 years, which isn't much. This PR has significantly higher success but it also just sounds cool :sunglasses: which doesn't necessarily correlate an actual need for users.

We should also evaluate this in context of other related proposals such as https://github.com/godotengine/godot-proposals/issues/1126 (which on the other hand has very high demand) and #100574 and #99210 which implement it (and conversely have seen less organic engagement than this PR).

All this to say, this might very well be the right tool for the job, but let's make sure this is properly assessed and solves the needs from the community.

2025-07-19 10:33 UTC, smix8 commented
> This needs to be mentioned somewhere. Also collision baking should be disabled when `use_collision` is disabled, if it does nothing.

Changed it so that when no csg collision exists or is enabled that the editor menu option and function create all the collision shapes procedural.

2025-07-19 21:16 UTC, KoBeWi commented
The `debug_show_brush` bug I mentioned earlier still exists, and there is a similar bug where if you duplicate a shape under CSGCombiner, the CSG menu will appear while it shouldn't. Though I think this can be ironed out later, all other problems seem to be resolved.

2025-07-19 21:20 UTC, KoBeWi commented on modules/csg_2d/csg_capsule_2d.cpp
> +#ifdef DEBUG_ENABLED
Sorry, I was wrong. I missed when this method was moved to `DEBUG_ENABLED` due to same Game tab stuff.

2025-07-19 21:40 UTC, KoBeWi commented on modules/csg_2d/editor/csg_editor_plugin_2d.cpp
> +	options->set_text(TTR("CSG2D"));
```suggestion
	options->set_text(TTRC("CSG2D"));
```

2025-07-19 21:41 UTC, KoBeWi commented on modules/csg_2d/editor/csg_editor_plugin_2d.cpp
> +	options->get_popup()->add_item(TTR("Bake NavigationRegion2D"), MENU_OPTION_BAKE_NAVIGATION_REGION_2D);
```suggestion
	options->get_popup()->add_item(TTRC("Bake MeshInstance2D"), MENU_OPTION_BAKE_MESH_INSTANCE);
	options->get_popup()->add_item(TTRC("Bake CollisionShape2D(s)"), MENU_OPTION_BAKE_COLLISION_SHAPE);
	options->get_popup()->add_item(TTRC("Bake Polygon2D"), MENU_OPTION_BAKE_POLYGON_2D);
	options->get_popup()->add_item(TTRC("Bake LightOccluder2D(s)"), MENU_OPTION_BAKE_LIGHT_OCCLUDER_2D);
	options->get_popup()->add_item(TTRC("Bake NavigationRegion2D"), MENU_OPTION_BAKE_NAVIGATION_REGION_2D);
```

2025-07-19 21:42 UTC, KoBeWi approved these changes

2025-07-21 18:45 UTC, kitbdev commented
The proposal is lacking detail and mentions destructive terrain as a use case, but that was already called out as not being a good fit. So the use case for this seems to be prototyping, just like 3D CSG.
But I don't think it is really needed in 2D.
I feel like 2D CSG isn't as popular as 3D CSG since there are other easy ways to make 2D shapes. We have Polygon2D which can already be used to create custom shapes. Also sprites can be used instead in many cases.

For basic shapes, https://github.com/godotengine/godot-proposals/issues/1126, I think either https://github.com/godotengine/godot/pull/100574  or https://github.com/godotengine/godot/pull/99210 are a better fit. Those approaches are simpler, easier to use, and don't have the performance considerations that this does.
For more complex shapes, you can use multiple shapes together and Polygon2D.
If the user needs it to be a single combined 2D mesh and Polygon2D won't work for some reason, then it's more niche or not really a prototype anymore.

I'm sure 2D CSG is good for some workflows, so I think 2D CSG would be a better fit as an addon. As mentioned, the base functionality for it is already available through Geometry2D, and it is very self-contained.

2025-10-04 11:33 UTC, shafnaz commented
Is this going to be available in 4.6?

2025-10-04 14:19 UTC, rburing approved these changes
As mentioned above there are some orthogonal use cases and solutions in this context. Personally I think 2D CSG is great for prototyping and constructing more complex shapes and then baking them. Being node-based this empowers code-challenged users to conveniently create and modify interesting shapes with collisions enabled. I think eventually more multi-shape operations should be added to Geometry2D or some other low-level interface exposed to scripting (wrapping Clipper2) and 2D CSG should be calling them (instead of using Clipper2 directly), but that can be done later.

2025-12-04 19:57 UTC, closed without merging